linode/manager

packages/manager/.changeset/pr-10685-changed-1721235038298.md
packages/manager/src/components/EntityDetail/EntityDetail.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx

Some UI improvements for the LKE Details summary panel and Node Pool tables
> [!NOTE]
> There is an existing issue noticeable in dark mode for `LinodeEntityDetailBody` where the border above the VPC section in the Linode Detail header extends past the left bounds of the table. I created M3-8354 to track this.
- Add a header to the LKE Details summary panel containing "Summary" and the `Kubernetes Dashboard` and `Delete Cluster` buttons
- Remove secondary button styling from buttons
- Remove the `<Paper />` behind the entire Node Pools section, replaced with a paper behind each Node Pool table
- Place each Node Pool's plan and action buttons in a header, adjusting the styling of the action buttons to text instead of secondary buttons
7/22/24
| Before  | After |
| ------------- | …

change: [M3-8346] – UI modications for LKE Details summary panel & Node Pool tables

---

packages/manager/.changeset/pr-10672-tech-stories-1720709315853.md
packages/manager/src/queries/statusPage/requests.ts
packages/manager/src/queries/statusPage/statusPage.ts

- Updates StatusPage to use a Query Key factory 🏭
7/22
- Verify Cypress tests pass ✅
- Verify unit tests pass ✅
- Manually [change](https://github.com/linode/manager/blob/develop/packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx#L41) `scheduled` to `completed` and see banner still works
- [x ] ➕ Adding a changeset
- [] 🧪 Providing/Improving test coverage

refactor: [M3-7444] - Query Key Factory for Status Page

---

packages/api-v4/.changeset/pr-10677-upcoming-features-1721062200460.md
packages/api-v4/src/object-storage/objects.ts
packages/api-v4/src/object-storage/types.ts
packages/manager/.changeset/pr-10677-upcoming-features-1721062431452.md
packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
packages/manager/src/factories/objectStorage.ts
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableBody.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
packages/validation/.changeset/pr-10677-upcoming-features-1721062312524.md
packages/validation/src/buckets.schema.ts

Under this proposal, Cloud Manager uses this to determine which S3 endpoints or types of endpoints are available to the requesting customer when using the API to create a bucket in a particular region.
- Added new `/v4/object-storage/endpoints`
```
{
region: string;
endpoint_type: 'E0' | 'E1' | 'E2' | 'E3';
s3_endpoint: string | null;
}
```
- Modified Access Key Endpoint (GET)
-  `regions` array will contain new `endpoint_type` field
- Modified Create Bucket Request (POST)
- Cloud Manager currently omits `cors_enabled` upon creation because it defaults to true. This behavior should be updated to explicitly set `cors_enabled` to either true or false.
- Added new fields to Modify Bucket Response (GET)
- `s3_endpoint` and `endpoint_type`
- Modified Bucket Access (GET)
- If Gen2 is enabled, …

upcoming: [M3-8296] - APIv4, Validation & Endpoints for OBJGen2

---

packages/manager/.changeset/pr-10687-changed-1721198360943.md
packages/manager/src/features/Domains/DomainRecords.tsx

SRV records in the Linode DNS Manager are not labelled correctly, which can lead to confusion for customers and customer support. 
[The format for SRV records](https://en.wikipedia.org/wiki/SRV_record#Record_format) is:
service._protocol.name
In the DNS Manager, we have mislabeled the combined Service/Protocol section as a "Name" field. What would be the "name" portion of the SRV record is improperly labelled as "Domain." To align with the standard formatting for SRV records, I propose that we change the 'Name' field to something like "Service/Protocol" and the 'Domain' field to "Name".
> [!NOTE]
> Please note that the Linode's DNS Manger does not include a name field when entering these records. The current "Domain" field will be populated with whatever domain or subdomain is added to …

change: [M3-5785] - Mislabelling of SRV fields in Linode's DNS Manager

---

packages/manager/.changeset/pr-10695-tests-1721358768207.md
packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
packages/manager/cypress/e2e/core/images/create-linode-from-image.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts
packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
packages/manager/src/components/EnhancedSelect/components/SelectControl.tsx
packages/manager/src/components/PasswordInput/PasswordInput.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Security.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppDetailDrawer.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSelectionCard.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/Marketplace.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
packages/manager/src/features/Linodes/LinodesCreate/SelectionCardWrapper.tsx
packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
packages/manager/src/features/Linodes/index.tsx
packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
packages/manager/src/features/OneClickApps/oneClickAppsv2.ts

- Doing this so Cypress tests still pass when the Linode Create v2 flow is toggled on ✅ 
- Makes Existing Linode Create Cypress Tests work for both Linode Create v1 and v2 🔧 
- I'm doing this because currently, enabling Linode Create v2 in dev, causes many cypress failures.
- This shouldn't be the case because Linode Create v2 should in parity with Linode Create v1, but the problem is that some cypress test use selectors that are specific to old components like EnhancedSelect.
- This PR just updates the tests to use more generic selectors so that **they work for both flows** 
- Alternatively, we could duplicated these tests, adapt them work for v2, and manually specify the flag to use, but I decided against this because I think it would be a lot more messy and confusing
- There isn't a …

test: [M3-8359] - Make Existing Linode Create Cypress Tests work for Linode Create v2

---

packages/manager/.changeset/pr-10698-tests-1721417619359.md
packages/manager/.changeset/pr-10698-upcoming-features-1721420372481.md
packages/manager/cypress/e2e/core/account/betas.spec.ts
packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
packages/manager/cypress/e2e/core/vpc/vpc-navigation.spec.ts
packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
packages/manager/src/features/Linodes/LinodeCreatev2/schemas.ts

- `vpc-navigation.spec.ts` & ` smoke-community-stackscrips.spec.ts` & `betas.spec.ts` 
- Mocks preferences so that the Primary Nav (our sidebar) is open 📂 
- The test should run faster because preferences are mocked 💨 
- `clone-linode.spec.ts`
- Fix bug in Linode Create v2 Clone flow causing this test to fail
- Validation logic was flawed
| <video src="https://github.com/user-attachments/assets/4acc0c61-a993-4575-b9ea-a8f2daeda8fd" /> | <video src="https://github.com/user-attachments/assets/de9e2f8b-4bdb-4b3c-b800-666549f6e949" />  |
- Verify e2es pass ✅

fix: Fix Cypress Test Flakes and Failures

---

packages/manager/.changeset/pr-10696-fixed-1721397985714.md
packages/manager/CHANGELOG.md
packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx

Fixes the "Created" and "Size" headers pointing to the wrong columns in the Automatic Images section of `ImagesLanding`. This bug was introduced in #10545.
ASAP
| ![Screenshot 2024-07-19 at 10 12 19 AM](https://github.com/user-attachments/assets/21dfb87f-020c-41fe-b36f-fee439ccf081) | ![Screenshot 2024-07-19 at 10 12 03 AM](https://github.com/user-attachments/assets/5670dba5-3b12-4c9d-8092-53b05f16120c) |
Navigate to the images landing and verify that the Automatic Images headers point to the correct columns under all breakpoints (sm, md and lg).

fix: [M3-8361] - Fix column headers for Automatic Images

---

packages/manager/.changeset/pr-10707-upcoming-features-1721841482068.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts

Create a boolean feature flag for Block Storage Encryption (BSE) and support it in Cloud
- BSE feature flag toggle added to our dev tool
8/5/24
Confirm a toggle for "Block Storage Encryption (BSE)" is present in our dev tool

feat: [M3-8356] – Support Block Storage Encryption feature flag

---

packages/manager/src/features/OneClickApps/oneClickAppsv2.ts

Oops, in #10634 we forgot to add the `isNew` field to the `oneClickAppsv2.ts` file that the Linode Create Flow v2 uses.
Currently, v1 works off of the `one-click-apps` feature flag to designate new apps, and v2 requires a code change (feature flag implementation to allow us to override apps is forthcoming)
- Marked the following apps as 'New' for the August release: Apache Cassandra Cluster, OpenBao, Valkey, InfluxDB
- Removed the following apps as 'New' because they were from the June release: Couchbase Cluster, Apache Kafka Cluster
8/5/24
| --- | --- |
|![Screenshot 2024-07-24 at 1 27 15 PM](https://github.com/user-attachments/assets/0118c807-5691-424d-809d-70b040e295cb) | ![Screenshot 2024-07-24 at 1 12 54 PM](https://github.com/user-attachments/assets/3ba48cc4-705b-4 …

fix: Add new August Marketplace apps to Linode Create v2

---

packages/manager/.changeset/pr-10701-tech-stories-1721805039188.md
packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
packages/manager/src/components/Autocomplete/Autocomplete.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.types.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/shared.ts

We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries.
- Replaced all instances of `Select` with `Autocomplete` in the `Firewall` feature.
- Navigate to http://localhost:3000/firewalls/{firewall_id}
- Open the `Add an Inbound Rule` Drawer 
- Verify the select input fields remains unchanged when using Autocomplete

refactor: [M3-6901, M3-6917] Replace Select with Autocomplete in: firewalls

---

packages/manager/.changeset/pr-10711-tech-stories-1721919417354.md
packages/manager/package.json
packages/manager/src/foundations/themes/dark.ts
yarn.lock

See https://github.com/linode/design-language-system/pull/52 for latest changes with this version.
- Badge token structure has changed
- Badge tokens for dark mode are now using latest CDS design
|![Screenshot 2024-07-25 at 11 26 21 AM](https://github.com/user-attachments/assets/a3de9a3e-7a1c-4100-a70f-929a71be683c)|![Screenshot 2024-07-25 at 11 25 10 AM](https://github.com/user-attachments/assets/a89af34c-2f6c-4de6-9e7a-4c4d5c833835)|
N/A
- Ensure Cloud Manager maintains current overall design look / feel.

change: [M3-8376] - bump to latest design language system version

---

docker-compose.yml
docs/development-guide/08-testing.md
packages/manager/.changeset/pr-10713-tech-stories-1722017812325.md
packages/manager/.changeset/pr-10713-tests-1722017832242.md
packages/manager/cypress.config.ts
packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
packages/manager/cypress/support/util/tag.ts

This makes a handful of changes to facilitate our testing pipeline for Heimdall, which will run a small subset of our Cypress tests against `cloud.linode.com` repeatedly as a form of synthetic monitoring.
- Adds `CY_TEST_DISABLE_RETRIES` environment variable to allow test retries to be disabled by CI pipelines
- Adds `e2e_heimdall` Docker Compose service
- Passes `CY_TEST_TAGS` environment variable to Docker containers (this was missed in #10475)
- Adds `purpose:syntheticTesting` test tag and assigns it to a couple of tests
- Note: the tests which will be run for Heimdall will change in the future, but wanted to get these tagged in the meantime so we have something to run from the pipeline
- Confirm via CI that these changes do not break our existing test pipeline
- Confirm that these …

test: [M3-8278] - Cloud Manager changes for Heimdall test pipeline

---

packages/api-v4/.changeset/pr-10714-added-1721926327777.md
packages/api-v4/src/linodes/types.ts
packages/manager/.changeset/pr-10714-upcoming-features-1721926239567.md
packages/manager/src/__data__/linodes.ts
packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
packages/manager/src/factories/linodes.ts
packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
packages/manager/src/features/Linodes/LinodesLanding/ListView.tsx

Distributed compute instances have no transfer pool, so the Monthly Network Transfer section is irrelevant. This PR hides that section and expands the Network Transfer History chart to occupy the space.
- Hide the monthly network transfer section for Linodes in a distributed region
| ![image](https://github.com/user-attachments/assets/1d95840b-e5e7-4df9-81d4-343b8b22ee80) | ![image](https://github.com/user-attachments/assets/8ee818dc-f890-489b-b0de-1366952111f2) |
- Ensure your account has the `new-dc-testing`, `edge_testing` and `edge_compute` customer tags
- Create a Linode in a distributed region if you don't already have one
- Go to a Linode's …

upcoming: [M3-8215] - Hide monthly network transfer section for distributed regions

---

packages/manager/.changeset/pr-10706-tech-stories-1721838942488.md
packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts
packages/manager/cypress/e2e/core/managed/managed-ssh.spec.ts
packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts
packages/manager/cypress/support/ui/pagination.ts
packages/manager/src/components/IPSelect/IPSelect.tsx
packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
packages/manager/src/components/TagsInput/TagsInput.stories.tsx
packages/manager/src/components/TagsInput/TagsInput.test.tsx
packages/manager/src/components/TagsInput/TagsInput.tsx
packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx

We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries.
- Replace `react-select` with Autocomplete component within the `components`.
- Replace Select with Autocomplete in `IPSelect`,  `PaginationFooter` and `TagsInput` components
- Added tag creation behavior to Autocomplete in `TagsInput` component
- Update the stories and unit test cases for `TagsInput` component.
- Update unit test cases for TagsInput in LinodesCreatev2->Details and EditImageDrawer
- Update e2e tests
- Update `support/ui/pagination`
5th Aug, 2024
- Verify all the selects functionality for `IPSelect` component continue to work as expected.
- Verify all the selects functionality for `PaginationFooter` component continue …

refactor: [M3-6901, M3-6921] - Replace `react-select` with `Autocomplete` in: components

---

packages/manager/.changeset/pr-10720-upcoming-features-1722043886339.md
packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts
packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
packages/manager/cypress/support/intercepts/object-storage.ts
packages/manager/src/factories/objectStorage.ts
packages/manager/src/mocks/serverHandlers.ts

Laying some more groundwork
- The `setUpBucket` and `setUpBucketMulticluster` functions should use the `createObjectStorageBucketFactory` factory instead of `objectStorageBucketFactory`, which is the mocked response for the create request.
- Added new intercept `mockGetObjectStorageEndpoints` which is the new endpoint we're adding for this project.
- Added new factory `getObjectStorageEndpointsFactory`
- Added new MSW endpoint for `/v4/object-storage/endpoints`
- Added `s3_endpoint` and `endpoint_type` which are all optional properties to some factories
N/A
N/A
- Ensure existing e2e tests all pass.

upcoming: [M3-8350] - Obj Gen2 - MSW, Factories, Cypress Updates

---

packages/api-v4/.changeset/pr-10716-changed-1721936880921.md
packages/api-v4/src/account/types.ts
packages/api-v4/src/linodes/types.ts
packages/api-v4/src/regions/types.ts
packages/api-v4/src/volumes/types.ts
packages/manager/src/features/Volumes/utils.ts
packages/validation/.changeset/pr-10716-changed-1721936121033.md
packages/validation/src/volumes.schema.ts

Update types and schemas to reflect forthcoming Block Storage Encryption changes.
- Add `encryption` field to `Volume` and `VolumeRequestPayload` interfaces and `key_rotating` value to `VolumeStatus` type in `volumes/types.ts`
- Add `key_rotating` to `volumeStatusIconMap`
- Add optional `encryption` field to `CreateVolumeSchema`
- Add `Block Storage Encryption` to `Capabilities` type in `regions/types.ts` and to `AccountCapability` in `account/types.ts`
- Add `bs_encryption_supported` field to `Linode` interface in `linodes/types.ts`
8/5/24
Since there were changes to `CreateVolumeSchema`, ensure that volume creation has not been adversely impacted.
Confirm the changes are in accordance with the API spec linked in the ticket.

upcoming: [M3-8357] – Update types and schemas for Block Storage Encryption

---

packages/manager/.changeset/pr-10723-upcoming-features-1722286306937.md
packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Summary/Summary.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx

Add support for the two-step Gecko GA region select in the Linode Create v2 flow
- Add `TwoStepRegion.tsx` for Linode Create v2
| ![image](https://github.com/user-attachments/assets/fba73318-fa94-428f-ba21-858b79a86841) | ![image](https://github.com/user-attachments/assets/4c5972ce-f921-42c7-9ff3-5318acfb1ab3) |
- Ensure your account has the `new-dc-testing`, `edge_testing` and `edge_compute` customer tags
- There should be no visual or functional differences between v1 and v2 Create flows
```
yarn test TwoStepRegion
```

upcoming: [M3-8401] - Add support for Two-step region select in Linode Create v2

---

packages/manager/.changeset/pr-10724-fixed-1722289139869.md
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts
packages/manager/src/features/Firewalls/shared.ts

Fixes a bug in `FirewallRuleDrawer` causing some addresses not to appear.
8/5
| ![Screenshot 2024-07-29 at 5 29 03 PM](https://github.com/user-attachments/assets/b3a0f763-4e8f-4e1d-824b-68eb0bdb48ad)  |![Screenshot 2024-07-29 at 5 29 49 PM](https://github.com/user-attachments/assets/78c361d5-bd29-460d-8f69-eaf87611e092)  |
- Create a new rule in a new/existing firewall
- Enter any value for "Label", "Protocol" and "Ports"
- For sources, select "IP / Netmask"
- For the IP addresses, either
- Add all IPv4 addresses (0.0.0.0/0) and some IPv6 addresses or an IPv6 subnet
- Add all IPv6 addresses (::/0) and some IPv4 addresses or an IPv4 subnet
- Click "Add Rule" then "Save Changes"
- Edit the new rule that was just created
- Observe "Sources" is set …

fix: [M3-8219] - Firewall rule sources not displaying correctly

---

packages/manager/.changeset/pr-10732-fixed-1722411934254.md
packages/manager/src/features/Events/Event.helpers.ts
packages/manager/src/features/Events/eventMessageGenerator.ts

When an answer/question is "liked" on the Community Questions site, the person wrote that answer/question is sent a notification in Cloud Manager. However, the syntax for that notification doesn't really make sense:
> A post on "1 user liked your answer to: How to Make Payments" has been liked by {author username}.
and 
> A post on "1 user liked your question: How to Make Payments" has been liked by {author username}.
- "A post on "1 user liked your answer to:"" isn't grammatically correct (for both the cases).
- "has been liked by {username}." - Here username is the logged in user and the one who posted the "liked" answer/question, but not the one who actually liked the answer/question.
As discussed with @jaalah-akamai, we come to the conclusion to exclude usernames from community like …

fix: [M3-6516] - Liked Answer/Question Notifications from Community Questions Site

---

packages/api-v4/src/images/types.ts
packages/manager/.changeset/pr-10731-upcoming-features-1722444371850.md
packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts
packages/manager/src/components/ImageSelect/ImageSelect.test.tsx
packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/components/ImageSelectv2/ImageOptionv2.test.tsx
packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx
packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.types.ts
packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
packages/manager/src/features/Images/ImagesLanding/ImagesActionMenu.tsx
packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Region.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.test.ts
packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.ts
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/images.ts

- Replaces incorrect `distributed-images` capability with `distributed-sites` ✏️ 
- Adds polling every 30 seconds to the Images landing table because we don't have any account events we can use to update Region statuses when replication finishes 🔄
- Enforces that least one "available" region is submitted in the Manage Regions Drawer 🟢 
8/5
- You need the `image-gen2` account tag 🏷️ 
- Test the `distributed-sites` capability in `dev` by uploading an Image
- Verify the new image has the capability once uploaded
- Test the validation / disabled button logic in the "Manage Regions Drawer"
- I recommend testing this in `staging` by uploading an Image

upcoming: [M3-8406, M3-8407] - Image Service Gen2 - Fix Image Capability and other tweaks

---

packages/manager/.changeset/pr-10721-tech-stories-1722318698239.md
packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx

We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries
- Replaced `react-select` with MUI Autocomplete for the Longview feature
19th August 2024
- Add a few Longview Clients on http://localhost:3000/longview
- Create a few Linodes (if not already present)
- ssh into a linode and install the Longview agent on it with the command given on http://localhost:3000/longview
- Check if the client is running with: `sudo systemctl status longview`. If not (which could likely be the case), start it with `sudo systemctl start longview`. Repeat this for other Linode-Longview Client pairs
- Navigate to http://localhost:3000/longview and check if the `Sort By` dropdown works as it does …

refactor: [M3-6912] - Replace `react-select` with MUI Autocomplete for Longview

---

packages/manager/.changeset/pr-10734-tech-stories-1722442550964.md
packages/manager/package.json
yarn.lock

This new version does not include any new features for our current use but contains fixes for tokens that we may potentially want to use. See https://github.com/linode/design-language-system/pull/57 for more details
N/A
N/A
N/A
- Ensure Cloud Manager maintains current overall design look / feel.

deps: Upgrade to latest DLS 2.6.1

---

packages/manager/.changeset/pr-10733-tests-1722436583624.md
packages/manager/cypress/e2e/core/account/account-logout.spec.ts
packages/manager/cypress/support/intercepts/account.ts

Create a Cloud Manager end-to-end test which tests the Cloud Manager logout flow. This will confirm that Cloud Manager log out functionality works as expected and implicitly confirm that the login application is up, which is useful from a synthetic testing perspective.
- Add a new test to confirm flow when logout.
- Add a new util function in packages/manager/cypress/support/intercepts/account.ts
```
yarn cy:run -s "cypress/e2e/core/account/account-logout.spec.ts"
```

test: [M3-8319] - Add CM Logout test

---

packages/manager/.changeset/pr-10739-upcoming-features-1722528251084.md
packages/manager/src/foundations/themes/dark.ts
packages/manager/src/foundations/themes/index.ts
packages/manager/src/foundations/themes/light.ts

Our observability team needs data visualization colors, so we need to expose the colors available in CDS 2.0 for their use, instead of them adding their own colors.
- Adds `Chart` tokens to our theme files
N/A
| Screenshots  | |
| <img width="382" alt="Screenshot 2024-07-25 at 10 03 05 AM" src="https://github.com/user-attachments/assets/e2751f33-fe20-4401-ad2d-6e9b6f3a5666"> | <img width="161" alt="Screenshot 2024-07-26 at 9 15 30 AM" src="https://github.com/user-attachments/assets/9ebb14d2-030f-4836-85cb-9517e4422e3e"> | 
- Any component that uses `theme` should be able to access the tokens via `theme.charts.Categorical[2].Primary` (as an …

upcoming: [M3-8411] - Data Visualization Tokens

---

packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx

Fix the regionFilter for the Linode Create v2 Core region select (I missed this while copy-pasting 😅 )
| ![image](https://github.com/user-attachments/assets/8dd2b661-0576-4acd-8360-03223628ac7a) | ![image](https://github.com/user-attachments/assets/e0b9773f-2413-4fb3-87b6-838277513f97) |
- Ensure your account has the `new-dc-testing`, `edge_testing` and `edge_compute` customer tags
- On develop or a different branch, go to the Linode Create v2 flow and click on the region select in the Core tab. Observe distributed regions displayed instead
- On this branch, go to the Linode Create v2 flow and click on the region select in the Core tab. Oberserve …

fix: Region filter for Core tab in Linode Create v2

---

packages/manager/.changeset/pr-10757-tests-1722971426093.md
packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts

Our "deploys a new linode as expected" test in "smoke-community-stackscripts.spec.ts" has recently started failing when Cypress attempts to select "AlmaLinux 9" as the Image for the Linode being deployed. The test assumes that "AlmaLinux 9" will be visible immediately after opening the Images dropdown, but this is no longer the case.
- Update "Choose an image" by typing the Image name in the autocomplete and then attempting to find the entry.
```
yarn cy:run -s "cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts"
```

test: [M3-8419] - Fix failing stackscript deploy test

---

packages/manager/.changeset/pr-10697-tests-1721417045353.md
packages/manager/cypress/e2e/core/helpAndSupport/close-support-ticket.spec.ts
packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
packages/manager/cypress/support/constants/help-and-support.ts
packages/manager/cypress/support/intercepts/support.ts

Add integration test to the flow of closing support tickets
- Check users can close closable support tickets.
```
yarn cy:run -s "cypress/e2e/core/helpAndSupport/close-support-ticket.spec.ts"
```

test: [M3-8136] - Add Cypress integration test for closing support tickets

---

packages/manager/.changeset/pr-10759-tests-1723040352780.md
packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.test.tsx

Fixes unit test flake with `EditImageDrawer.test.tsx` by awaiting the `userEvent.type` call ⌛ 
This is the flake I am trying to fix
- Verify Github Actions passes ✅ 
- Run the test locally a few times and verify it consistently succeeds ✅ 
```sh
repeat 10 yarn test EditImageDrawer
```

test: Fix `EditImageDrawer.test.tsx` Unit Test Flake

---

packages/manager/.changeset/pr-10754-added-1723039007976.md
packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
packages/manager/src/features/Search/SearchLanding.styles.ts
packages/manager/src/features/Search/SearchLanding.test.tsx
packages/manager/src/features/Search/SearchLanding.tsx
packages/manager/src/features/Search/searchLanding.css

As a user, the animation on the first character of no search results can result in potentially offensive words. Let's remove the animation from the character and animate the logo instead.
- Remove the animation from the character/search query text - The first character is no longer animated.
- Add animation on svg icon.
- Update the unit test case.
8/19
| <video src="https://github.com/user-attachments/assets/d6f005f2-b348-4f5e-b96b-17878e99a65e" /> |  <video src="https://github.com/user-attachments/assets/b3e6f328-2d77-4910-ab11-c26e8f4b712d" />|
- Type something irrelevant in the Search input and Enter.
- Ensure the first character is no longer animated.
- Ensure the icon is animated in some fun way.

feat: [M3-7666] - Remove Animation from Search Results and Animate Icon Instead

---

packages/manager/.changeset/pr-10742-fixed-1722601990368.md
packages/manager/src/features/Events/Event.helpers.ts
packages/manager/src/features/Events/EventRowV2.tsx
packages/manager/src/features/Events/eventMessageGenerator.ts
packages/manager/src/features/Events/factories/community.tsx
packages/manager/src/features/Events/utils.test.tsx
packages/manager/src/features/Events/utils.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderEventV2.tsx

Improve Community Like Notifications in Event Messages v2 Refactor.
When an answer/question is "liked" on the Community Questions site, the person wrote that answer/question is sent a notification in Cloud Manager. However, the syntax for that notification doesn't really make sense in Event Messages v2:
> [!NOTE]
> Default 'Linode' is kept as it is because it was already defined as a fallback when the username is `null` in Event Messages v2.
In Event Messages v2:
- Exclude usernames from community like events.
- Add username getter utility that returns usernames from event or 'Linode' if username is null or excluded by action.
- Update the notification message for community like events to ensure it is grammatically correct.
8/19
| Before (v2) | After (v2)   |
| ![v2 …

fix: [M3-8409] - Community Notifications in Event Messages v2 Refactor

---

docs/CONTRIBUTING.md
packages/manager/.changeset/pr-10764-added-1723149902254.md

This is an action item from Cafe. (8/8/24)
Some good internal guidelines exist about writing good, small PRs. It would be useful for these to live in our public developer docs too, for ease of referencing and linking in PR reviews.
- Adds the 'Sizing a pull request' section to our contributing docs page
- Links that section in the 'Submitting a pull request' section
- Read the diff (or pull the PR and `yarn docs`, then go to http://localhost:5173/manager/CONTRIBUTING.html#sizing-a-pull-request to view it locally.
- If there are any better or additional examples to include, we can definitely do that.

change: [M3-8429] - Add a "Sizing a pull request" section to `CONTRIBUTING.md`

---

packages/manager/.changeset/pr-10763-upcoming-features-1723138942196.md
packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx

Adds a Sentry tag when Linode Create v2 is mounted 🏷️  so we can know if a Sentry error originated from the v2 Linode Create flow 
| Linode Create v1 Error  | Linode Create v2 Error   |
| ![Screenshot 2024-08-08 at 1 28 45 PM](https://github.com/user-attachments/assets/9f89abc9-2ef2-4545-a832-b311c4c08e4d) | ![Screenshot 2024-08-08 at 1 26 15 PM](https://github.com/user-attachments/assets/bb85727d-aa3d-4eb1-bbec-60a50e0821d2) |
| no tag | has an extra tag we can query by |
- Make sure you have `REACT_APP_SENTRY_URL` in your env
- If you need this value, ask me for it! 
- You can test this by adding `throw new Error("...")` in components on the Linode Create v1 and Linode Create v2
- This should cause Cloud Manager to crash and report the error to sentry
- If you are …

upcoming: [M3-8426] - Add Sentry Tag for Linode Create v2

---

packages/manager/.changeset/pr-10760-tech-stories-1723236539851.md
packages/manager/src/containers/types.container.ts
packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx
packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenuUtils.ts
packages/manager/src/queries/linodes/linodes.ts
packages/manager/src/queries/linodes/requests.ts
packages/manager/src/queries/types.ts

- Updates Linode Type Queries to use the Linodes Query Key Factory 🏭 
- Performs some small clean up 🧹 
- Verify Linode types still load as expected throughout Cloud Manager 👁️ 
- Verify automated testing passes ✅

refactor: [M3-8421] - Update Linode Types to use a Query Key Factory 

---

packages/manager/.changeset/pr-10772-fixed-1723476789978.md
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx

When creating an LKE cluster, if you add a node pool under the "Shared CPU", "High Memory", or "Premium CPU" tab, in some cases Cloud will erroneously reset the user's tab selection back to the "Dedicated CPU" tab.
This only occurs when the node pool size has been modified using the - and + buttons (or by typing in a different value) prior to adding the node pool. If you add a node pool of the default size (3) without first modifying the value, the tab selection does not change.
- Remove `setSelectedType(undefined)` to prevent tab reset after adding a node pool.
- Change the function name from `submitForm` to `addPool` for clarity.
8/19
1. Navigate to the LKE cluster create page at /kubernetes/create
2. Select a region
3. Click on the "Shared CPU" …

fix: [M3-7324] - LKE Cluster Create Tab Selection Reset Upon Adding Pool

---

packages/manager/.changeset/pr-10750-upcoming-features-1723139035892.md
packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
packages/manager/src/components/Encryption/Encryption.tsx
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/components/Encryption/utils.ts
packages/manager/src/features/Volumes/VolumeCreate.test.tsx
packages/manager/src/features/Volumes/VolumeCreate.tsx

Add "Volume Encryption" section to Volume Create page.
> [!NOTE]
> The wireframes have a warning notice below the Linode dropdown when the selected linode uses an old qemu version. However, the API team has not finalized yet where that data point will be placed, so I created M3-8420 to circle back to that once finalized.
- Unit test coverage added with `VolumeCreate.test.tsx`
- Added support in `Encryption.tsx` for warning notices above checkbox via optional `notices` prop
- Added `useIsBlockStorageEncryptionFeatureEnabled` util, updated constants
- Added "Volume Encryption" section to Volume Create page
8/19/24
| ![Screenshot 2024-08-05 at 4 40 05 PM](https://github.com/user-attachments/assets/f36bfa0f-53dc-44c9-b2a0-c47ed401fd97) | …

upcoming: [M3-8367] – Add "Volume Encryption" section to Volume Create page

---

packages/api-v4/.changeset/pr-10768-upcoming-features-1723463731514.md
packages/api-v4/src/account/types.ts
packages/manager/.changeset/pr-10768-upcoming-features-1723464477834.md
packages/manager/src/MainContent.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/factories/account.ts
packages/manager/src/features/CloudPulse/Utils/utils.ts

Added account capabilities check for user to restrict access to Cloud Pulse page.
1. Modified AccountCapability to add 'Akamai Cloud Pulse' key.
2. Modified PrimaryNav.tsx & MainContent.tsx to check ACLP enabled based on feature flag & account capability
20 August 2024
|![Screenshot 2024-08-12 at 4 55 11 PM](https://github.com/user-attachments/assets/9deac601-4282-4679-90cb-2ae2b4952c53)|![Screenshot 2024-08-12 at 4 55 27 PM](https://github.com/user-attachments/assets/050e46f4-38f6-44a4-aa72-6dca968aea99)|
You can switch between mock user & normal user and visualize the …

upcoming: [DI-16642] - Enable ACLP to be shown based on account capabilities

---

packages/manager/.changeset/pr-10777-fixed-1723516402764.md
packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
packages/manager/src/assets/timezones/timezones.ts

Kyiv is the correct name and direct translation from Ukrainian language.
- Corrects `Kiev` to `Kyiv` in `timezones.ts`, which populates the Profile timezone selector.
- Corrects timezone-related typo (this one non-customer-facing) in `smoke-billing-activity.spec.ts` - I just happened to notice this.
8/19
| ![before](https://github.com/user-attachments/assets/1a2197af-7ee1-4097-8dc5-acf28fd197eb) | ![after](https://github.com/user-attachments/assets/516cea11-90ce-4ae5-b93e-27c266fe45f4) |
- Go to https://cloud.linode.com/profile/display.
- In the timezone selector, search 'Kiev' and observe the incorrect spelling.
- Check out this PR.
- Go to …

fix: [M3-8213] - Use correct spelling of Ukrainian capital

---

packages/manager/.changeset/pr-10775-upcoming-features-1723502865486.md
packages/manager/src/factories/volume.ts
packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx

Add "Encryption" column to Volumes landing page
> [!NOTE]
> The ticket comments discuss new patterns for tables to indicate scrollability. That work will be captured in a separate ticket. For this one, we maintaining the existing table responsiveness.
8/19/24
| ![Screenshot 2024-08-12 at 6 41 15 PM](https://github.com/user-attachments/assets/6cb7b046-c716-4a80-8ced-04e7e5f1437c) | ![Screenshot 2024-08-12 at 6 42 01 PM](https://github.com/user-attachments/assets/36d92c77-c7bd-4fb6-b46e-7d59b340e751) |
- Confirm that the "Encryption" column appears and is properly populated in the Volumes landing table when the feature flag is on, and does not appear when the …

upcoming: [M3-8368] – Add "Encryption" column to Volumes landing page

---

packages/manager/.changeset/pr-10782-fixed-1723574317048.md
packages/manager/src/features/OneClickApps/oneClickAppsv2.ts

Fixes link for Secure Your Server app
n/a
- Navigate to marketplace and search for "Secure Your Server" app. Link incorrectly goes to 'secure your server' guide - https://www.linode.com/docs/products/compute/compute-instances/guides/set-up-and-secure/
- Confirm link for app now goes to https://www.linode.com/docs/products/tools/marketplace/guides/secure-your-server/

fix: [M3-7558] - Update guide link for Secure Your Server Marketplace app

---

packages/manager/.changeset/pr-10778-changed-1723563275697.md
packages/manager/src/features/OneClickApps/oneClickAppsv2.ts

Updates Passbolt Community Edition Marketplace App naming to better comply with brand/trademark guidelines.
- Adds full text 'Passbolt Community Edition'
8/19/24

change: [OCA-1411] - Use Passbolt CE full name

---

packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx

When the Linode Create v2 feature flag is not checked, trying to create a VPC from Linode Create results in the page crashing
- Update value field in VPC panel's autocomplete to ensure 'undefined' is never the value
8/14 - trying to get it into this upcoming release, as the bug it fixes is still unreleased!
- Make sure Linode Create v2 flag is _not_ checked
- Try creating a VPC from the Linode Create page 
- Verify that creating a VPC from the Linode Create page does not crash the page when Linode Create v2 flag isn't checked
- Double check that when Linode Create v2 flag _is_ checked, everything still works as expected
---
> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown …

fix: 'Oh snap' error when creating VPC from Linode Create

---

packages/manager/.changeset/pr-10779-fixed-1723593549058.md
packages/manager/cypress/e2e/core/account/account-login-history.spec.ts
packages/manager/src/features/Account/AccountLogins.tsx

Unrestricted child accounts should be treated no different than other unrestricted accounts in that they should see login history.
- Removed condition where we were explicitly disabling it for child users (restricted/unrestricted).
❗ 8/19
| ![Screenshot 2024-08-13 at 9 58 14 AM](https://github.com/user-attachments/assets/737eb660-5d0c-460e-80d4-1dfd9e124cfd) | ![Screenshot 2024-08-13 at 9 56 12 AM](https://github.com/user-attachments/assets/23ad0e75-0c84-4e07-8a5f-21bd17b3f7f9) |
- You need a child account provisioned (see me if you don't already have one)
- Go to login history on a child account and observe that it's disabled with a warning
- Pull down my branch and observe it's been restored.

fix: [M3-8443] - Enabled login history for unrestricted child accounts

---

packages/manager/.changeset/pr-10771-upcoming-features-1723731588900.md
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx

As a user, I want to see the endpoint type of each bucket's endpoint displayed in various locations within Cloud Manager and have certain features disabled or hidden for gen2 buckets (endpoint types E2 and E3).
- Endpoint Type Display
- Display the endpoint type in a new column in the top-level bucket list.
- Display the endpoint type in the bucket's Details pane, accessible from the top-level bucket list.
- Disable/Hide CORS Switch for Gen2 Buckets (E2 and E3)
- Hide or disable the CORS switch in the bucket's Details drawer for gen2 buckets.
- Disable/Hide Public/Private ACL Switch for Gen2 Buckets (E2 and E3)
- Hide or disable the public/private ACL switch for individual objects within gen2 buckets.
- Bucket List
| …

upcoming: [M3-8304] - Add Endpoint Type Column & Disable CORS for Gen2 Buckets

---

packages/manager/.changeset/pr-10791-changed-1723820950904.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshotConfirmationDialog.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshotConfirmationDialog.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx

Moves the manual snapshot error message from the Linode Backups page to the snapshot's confirmation dialog
n/a
Note - three potential options for displaying the error message - see "Other notes/questions" for more
| ![image](https://github.com/user-attachments/assets/fb110c9a-97a3-4be0-a165-42cf93d837c6)| ![image](https://github.com/user-attachments/assets/76adcaf8-f27e-4108-87da-e1760ef3c775)![image](https://github.com/user-attachments/assets/8ab676f3-b8ca-484f-b018-c09af18f3ea2)![image](https://github.com/user-attachments/assets/4d3561c6-16d4-43fd-8334-88fb5146a6c5)|
- Have a busy linode (a linode that is already creating a snapshot, shutting down, turning on, etc) or a linode with no disk and no config and try to create a snapshot
- Confirm …

change: [M3-6843] - Move manual snapshot error message to snapshot confirmation dialog

---

packages/manager/.changeset/pr-10787-upcoming-features-1723672538179.md
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Volumes/EditVolumeDrawer.test.tsx
packages/manager/src/features/Volumes/EditVolumeDrawer.tsx

Add a disabled "Encrypt Volume" checkbox in Edit Volume drawer that reflects the volume's encrypted status (i.e., encrypted volumes should have a checked disabled box, and unencrypted volumes should have an unchecked disabled box)
9/3/24
<details>
<summary>Encrypted volume</summary>
</details>
<details>
<summary>Unencrypted volume</summary>
</details>
Confirm the Edit Volume drawer has the BSE checkbox when the feature flag is on, and that the checkbox reflects the volume's encrypted status (i.e., encrypted volumes should have a checked disabled box, and unencrypted volumes should have an unchecked disabled box)

upcoming: [M3-8369] – Add "Encrypt Volume" checkbox in Edit Volume drawer

---

packages/manager/.changeset/pr-10790-upcoming-features-1724031092075.md
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx

- Updated static bucket rate limits with latest numbers
N/A
- Turn on `OBJGen2` feature flag in dev tools
- Go through each endpoint and verify the numbers display correctly

upcoming: [M3-8301] - Updated Bucket Rate Limits

---

packages/manager/.changeset/pr-10789-changed-1724075831126.md
packages/manager/.changeset/pr-10789-changed-1724075913480.md
packages/manager/package.json
packages/manager/src/features/Lish/Weblish.tsx
packages/manager/src/features/Lish/lishUtils.ts
yarn.lock

- I made some changes to LISH in https://github.com/linode/manager/pull/10689 that ended up making the experience a bit worse
- This PR addresses changes based on internal feedback and customer feedback 👤 
- Make LISH use a constant size because we need backend support to properly implement resizing 🖥️ 
- Make LISH open in a popup rather than in a new tab 🖥️ 
| ![Screenshot 2024-08-19 at 9 48 16 AM](https://github.com/user-attachments/assets/b9d740c0-2d7e-4b51-b4ab-d5b6c39feed0) | ![Screenshot 2024-08-19 at 9 47 18 AM](https://github.com/user-attachments/assets/c303583c-8eb6-45a7-98c9-8cc62b007385) |
- Verify LISH opens in a new window rather than a new tab 
- Verify LISH uses a static number of rows and columns and terminal output and cursor …

change: [M3-8456] - Update LISH experience based on feedback

---

docs/development-guide/01-repository-structure.md
package.json
packages/manager/.changeset/pr-10800-tech-stories-1724094117438.md
packages/manager/package.json
yarn.lock

- Removes the `patch-package` package 📦 
- We haven't needed to patch in years, so I think it's worth cleaning this up 🧹 
- Verify dependencies install and work as expected
- Verify all automated testing passes

refactor: [M3-8459] - Remove `patch-package` package

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
packages/manager/src/mocks/serverHandlers.ts

In `AccessSelect` we were not checking for both `object` and `bucket` variants when determining to disable CORS. Fortunately CORS is enabled by default for all objects, so this is low impact, but it requires a hotfix.
- Main fix is in [AccessSelect component](https://github.com/linode/manager/pull/10812/files#diff-09da555b7ce00d83c9a46a23ba01b3ca2254fc84576479e447cf4be93b29b4fdR145-R147) where we're checking for both `variant === 'bucket' || variant === 'object'` to enable or disable CORS.
- Other changes to `ObjectDetailsDrawer.tsx` and `serverHandlers.ts` are to confirm changes are working elsewhere.
8/22
| ![Screenshot 2024-08-22 at 11 08 35 AM](https://github.com/user-attachments/assets/9b13d987-e815-4683-87e9-244239e0e567) | ![Screenshot …

fix: Re-enable CORS for Legacy/Gen1 Endpoints

---

packages/manager/.changeset/pr-10793-upcoming-features-1723845275155.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx

Add "Encryption" column to Linode Volumes table
9/3/24
| ![Screenshot 2024-08-16 at 2 53 04 PM](https://github.com/user-attachments/assets/8363b42f-f041-4371-abe8-2c3e9c9849a1) | ![Screenshot 2024-08-16 at 2 53 40 PM](https://github.com/user-attachments/assets/c9d33304-508e-4f93-b545-691284aebdba) |
Confirm the Linode Volumes table has the "Encryption" column when the feature flag is on. For any listed volumes, the encryption status should be accurate.
Unit test should pass:
```typescript
yarn test linodevolumes
```

upcoming: [M3-8370] – Add "Encryption" column to Linode Volumes table

---

packages/manager/.changeset/pr-10803-upcoming-features-1724100276144.md
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Volumes/CloneVolumeDrawer.test.tsx
packages/manager/src/features/Volumes/CloneVolumeDrawer.tsx
packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx

Add a disabled "Encrypt Volume" checkbox in Clone Volume drawer that reflects the existing volume's encrypted status (i.e., encrypted volumes should have a checked disabled box, and unencrypted volumes should have an unchecked disabled box)
- Disabled "Encrypt Volume" checkbox added to Clone Volume drawer
- New unit test coverage for Clone Volume drawe
- Slight spacing adjustment in `PricePanel.tsx`
9/3/24
| ![Screenshot 2024-08-19 at 4 27 33 PM](https://github.com/user-attachments/assets/151f97af-2847-418f-b717-d0940e7ca827) | ![Screenshot 2024-08-19 at 4 27 22 PM](https://github.com/user-attachments/assets/4a636350-4eef-4200-87be-aee487a23494) |
Confirm the …

upcoming: [M3-8455] – Add "Encrypt Volume" checkbox in Clone Volume drawer

---

packages/api-v4/.changeset/pr-10805-upcoming-features-1724163902024.md
packages/api-v4/src/cloudpulse/dashboards.ts
packages/api-v4/src/cloudpulse/services.ts
packages/api-v4/src/cloudpulse/types.ts
packages/manager/.changeset/pr-10805-upcoming-features-1724163948287.md
packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.test.tsx
packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
packages/manager/src/features/CloudPulse/Utils/UserPreference.ts
packages/manager/src/features/CloudPulse/Utils/utils.ts
packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/cloudpulse/dashboards.ts
packages/manager/src/queries/cloudpulse/metrics.ts
packages/manager/src/queries/cloudpulse/queries.ts
packages/manager/src/queries/cloudpulse/services.ts

Modified dashboard select component to support multiple service types in the list. Also modified api request params based on API spec.
1. Added a api call to fetch list of available service types.
2. Modified request params and headers based on API spec change.
3. Added util functions to convert the api response data into appropriate format for autocomplete component.
4. Fixed the CSS issue in resource select component as highlighted by @coliu-akamai (Added screenshots)
30 August 2024
|![Screenshot 2024-08-20 at 5 07 21 PM](https://github.com/user-attachments/assets/856c5fd7-5a05-4928-81a8-ff23f9538afe)|![Screenshot …

upcoming: [DI-20284] - Added support for multiple services in the dashboards list

---

packages/manager/.changeset/pr-10784-added-1723651941893.md
packages/manager/src/components/CheckoutBar/CheckoutBar.stories.tsx
packages/manager/src/components/CheckoutBar/CheckoutBar.tsx

Add CheckoutBar Story to Storybook
- Add CheckoutBar Story
N/A
- Run yarn storybook to test locally

feat: [M3-8170] - Add CheckoutBar Story

---

packages/manager/.changeset/pr-10796-upcoming-features-1724152512210.md
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.styles.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTable.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/AccessKeyTableRow.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesDrawer.tsx

As a customer, I want to see a list of endpoints, including the type of each endpoint (E0, E1, E2, E3) alongside each endpoint hostname, in various views related to S3 access keys in Cloud Manager. This will help me understand the endpoints in which each newly created or pre-existing S3 access key can be used.
* Add "Action" Table Header for Actions Column
* Endpoint Type Display in Regions Column
* Display the type of each endpoint alongside each endpoint hostname in the existing Regions column of the top-level list of both pre-existing and new access keys. 
* (Drawer) Endpoint Type Display for Pre-existing Access Keys
* Show the type of each endpoint alongside the endpoint hostname when displaying the full list of endpoint hostnames for a specific pre-existing access key.
N/A
- Access …

upcoming: [M3-8305] - Display Endpoint Type alongside each endpoint hostname in Regions Column & Hostnames Drawers

---

packages/manager/.changeset/pr-10824-fixed-1724428840947.md
packages/manager/cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts
packages/manager/src/hooks/useEventHandlers.ts
packages/manager/src/queries/account/billing.ts
packages/manager/src/queries/account/oauth.ts
packages/manager/src/queries/databases/events.ts
packages/manager/src/queries/domains.ts
packages/manager/src/queries/firewalls.ts
packages/manager/src/queries/images.ts
packages/manager/src/queries/linodes/events.ts
packages/manager/src/queries/nodebalancers.ts
packages/manager/src/queries/profile/profile.ts
packages/manager/src/queries/profile/tokens.ts
packages/manager/src/queries/stackscripts.ts
packages/manager/src/queries/support.ts
packages/manager/src/queries/volumes/events.ts

- Fixes event handler bug discovered by @jdamore-linode  🔧 
- A [React Query change](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-react-query-4#consistent-behavior-for-cancelrefetch) in v4 makes `invalidateQueries` fire off many GET request if `invalidateQueries` is called many times sequentially
- We want to intentionally disable this new behavior (using `cancelRefetch: false`) in our event handlers because our event handlers were built based on the assumption React Query would only fire off one request when `invalidateQueries` was called many times sequentially
| <video src="https://github.com/user-attachments/assets/429b6310-0f74-434b-a3d0-d273ea706106" /> | <video …

fix: [M3-8477] - Event handlers making a proportional number of GET requests to the number of incoming events

---

packages/manager/.changeset/pr-10818-tests-1724394944251.md
packages/manager/src/components/CheckoutBar/CheckoutBar.test.tsx
packages/manager/src/components/CheckoutBar/CheckoutBar.tsx

Unit test cases for CheckoutBar Component.
- Add unit test cases for CheckoutBar Component.
N/A
- Run `yarn test src/components/CheckoutBar`

test: [M3-8463] - Add unit tests for CheckoutBar component

---

package.json
packages/api-v4/package.json
packages/manager/.changeset/pr-10830-tech-stories-1724469419694.md
packages/manager/package.json
packages/validation/package.json
yarn.lock

Updating packages to resolve this `braces` [vulnerability](https://github.com/linode/manager/security/dependabot/102).
See self review for extra details about the version bumps.
- Updating various packages and add `braces` resolution
- run unit tests
- run cloud manager and check terminal/console

change: [M3-8383] - Packages updates and resolution for braces vulnerability 

---

packages/manager/.changeset/pr-10829-tech-stories-1724462593074.md
packages/manager/package.json
yarn.lock

Small PR to mitigate a vulnerability with a sub dependency of `jsdom` (`ws`): https://github.com/linode/manager/security/dependabot/103
This is only affecting dev dependencies for our unit tests.
- Update `jsdom` to `24.1.1`
- make sure out unit test suites still all pass and don't log extra noise

change: [M3-8382] - Update jsdom to remove WS package vulnerability 

---

packages/manager/.changeset/pr-10826-tests-1724431261722.md
packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
packages/manager/cypress/support/intercepts/account.ts
packages/manager/cypress/support/ui/autocomplete.ts

This resolves some causes of test flakiness in the StackScript Linode deploy test in `create-stackscript.spec.ts`.
There seem to be two main causes of flake for this test in CI, and this PR attempts to fix both:
- Attempting to find a region in the region drop-down without scrolling to it first
- Issues selecting a region quickly upon page load
I also changed the way that StackScripts get entered into the create form. Using `cy.type()` to input the script is slow and adds several seconds to our test runtime, so I've circumvented it by setting the field's value directly.
I ran the test on repeat 30 times (with the other test skipped) and it passed each time.
(cc @mjac0bs -- I'm curious if you continue seeing failures with these changes? No worries if you don't have time to take a look!)
- …

test: [M3-8478] - Fix Cypress StackScript Linode deploy test flake

---

packages/manager/.changeset/pr-10840-tech-stories-1724713234913.md
packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Plan.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.test.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts

This PR tags the UI elements from Linode Create v2 that were not shared with the v1 flow (which was tagged in #10722).
See #10722 for an overview how form events are handled.
9/3
<details>
<summary>
Screenshots of Main Create Flow Events
</summary>
| Component | Analytics Event |
| --- | --- |
| ![GettingStarted](https://github.com/user-attachments/assets/a722ce92-471d-4b11-bfe2-9cbaa2304e77) | ![gettingStartedEvent](https://github.com/user-attachments/assets/0a815720-9e05-4d08-b7ea-3c3aa60bba89) |
| Current: ![DCPricing](https://github.com/user-attachments/assets/e9f7ab52-8692-4819-87bf-9e9c85f9ec2b) Two step:  ![twoStepRegionSelect](https://github.com/user-attachments/assets/c0a53e83-8592-4373-a718-d0c830391833)  | ![twoStepRegionSelectEvent](https://github.com/user-attachments/assets/aa …

change: [M3-8439] - Tag form events in Linode Create v2

---

packages/manager/.changeset/pr-10821-upcoming-features-1724414057285.md
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx

Add bucket rate limit info to bucket details drawer
In Bucket Details drawer:
- For legacy buckets, add the bucket rate limit of 750 RPS
- For E2/E3 buckets, add bucket rate limit table
N/A
| Before  | Legacy Bucket| E2&E3 Bucket |
| ![image](https://github.com/user-attachments/assets/9c534e55-9254-446c-982d-d589aa8cddd0)|![04_47_08](https://github.com/user-attachments/assets/7254d053-a8b8-415a-9f6d-6a38e8de4e99)|![04_47_24](https://github.com/user-attachments/assets/e2976416-73cb-45df-aa76-648cb8f7fe24)|
- Test all components for ObjectStorage buckets by toggling the `OBJ Gen2` feature flag in dev environment
- Turn on MSW
- Go to Object Storage landing page
- On opening a bucket's Details drawer, you should find a bucket rate limit table for `E2` and `E3` …

upcoming: [M3-8308] - Add bucket rate limit info to Object Storage Bucket Details drawer

---

packages/manager/.changeset/pr-10762-tech-stories-1723134446106.md
packages/manager/.storybook/main.ts
packages/manager/.storybook/utils.test.ts
packages/manager/.storybook/utils.ts

Performance optimizations for running Storybook locally
The main culprit is using `react-docgen-typescript`; it's parsing every file for docgen info. The package is also [no longer being maintained](https://github.com/styleguidist/react-docgen-typescript/issues/494) (the last release was in [end of 2021](https://github.com/styleguidist/react-docgen-typescript/releases)).
- There's a faster docgen library that Storybook 8 uses, `react-docgen`, however we're missing a lot of typing by using that since it's using a shallower analysis.
- The solution I ended up at was to keep `react-docgen-typescript`, but tighten the scope on what files are parsed for the docgen (Components and Features only). And to also disable `allowSyntheticDefaultImports` and `esModuleInterop` per the [Storybook MUI …

refactor: [M3-8184] - Improve local Storybook performance

---

packages/manager/.changeset/pr-10828-changed-1724442933954.md
packages/manager/.changeset/pr-10828-fixed-1724688319150.md
packages/manager/.changeset/pr-10828-tests-1724688351092.md
packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.test.tsx
packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
packages/manager/src/components/Dialog/Dialog.tsx

Update error text color in confirmation dialogs to not be hardcoded, as per discussion. Also added some tests/refactored styling to use styled components while I was at it
- updated error text color to use the theme
- added tests for Confirmation Dialogs
- refactor styling
n/a
| ![image](https://github.com/user-attachments/assets/e3f47fa6-8246-4e97-a0bb-d34301184145)![image](https://github.com/user-attachments/assets/de4db235-e36f-4528-a3a1-cad37cac6998)| ![image](https://github.com/user-attachments/assets/7aac6aa3-a459-4f18-a271-affb6db4cd8b)![image](https://github.com/user-attachments/assets/c73225f4-9c50-46ed-8e09-57f41a470828)|
- yarn test components/ConfirmationDialog.test.tsx
- Verify that Confirmation Dialog styling remains the same …

fix: [M3-8453] - Update error text color in confirmation dialogs to use theme, refactor styling

---

packages/manager/.changeset/pr-10832-tests-1724681646686.md
packages/manager/cypress/support/ui/autocomplete.ts

This is a tiny change that allows the `ui.regionSelect.findItemByRegionId()` and `ui.regionSelect.findItemByRegionLabel()` helpers to be used with mock regions. I also made some small doc comment improvements.
I'm doing this in preparation for some Cypress docs improvements that will encourage the use of these helpers.
- Add optional `searchRegions` parameter to `ui.regionSelect.findItemByRegionId` and `ui.regionSelect.findItemByRegionLabel` that allows mock regions to be used with helpers
- Small doc improvements
This doesn't make any changes to any tests, and the changes to the helpers should not impact the behavior of any of our tests. We can rely on CI to ensure that nothing is broken by these changes.

test: [M3-8486] - Allow using Cypress region selection helpers with mock regions

---

packages/manager/.changeset/pr-10795-upcoming-features-1724084768188.md
packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.styles.ts
packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx

We aim to enhance our bucket management interface by introducing a new "Properties" tab. This tab will display the current rate limits for each bucket and include functionality to modify these limits in future updates.
- Add Bucket Management Properties Tab for Object Storage Gen2.
N/A
- Enable MSW and ensure OBJ Gen2 flag is enabled.
> [!Note]
> - The endpoints for retrieving and updating Bucket Rate Limits are currently unavailable.
> - Hardcoded values are being used to retrieve Bucket Rate Limits data.
- Navigate to http://localhost:3000/object-storage/buckets
- Select a bucket.
- When on details page, verify that the new 'Properties' tab is rendered.
- Verify that the user interface correctly displays the retrieved Bucket Rate Limits data.
- Verify that the functionality to update …

upcoming: [M3-8378] - Add Bucket Management `Properties` Tab for Object Storage Gen2

---

packages/manager/.changeset/pr-10808-changed-1724315097131.md
packages/manager/cypress/e2e/core/volumes/create-volume.smoke.spec.ts
packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx

"Create Volume" button text changed to "Add Volume".
"Create Volume" button text changed to "Add Volume".

change: [M3-8075] - "Create Volume" button text changed to "Add Volume".

---

packages/validation/.changeset/pr-10842-fixed-1724786185430.md
packages/validation/src/buckets.schema.ts

The API currently returns an error when creating buckets, incorrectly checking for 'name' instead of 'label'. While a fix for this issue is planned for the future, we can improve our validation in the interim. 
- Update schema to account for existing validation requirements
N/A
| ![Screenshot 2024-08-21 at 10 46 24 AM](https://github.com/user-attachments/assets/8c8a9e15-b8d6-417d-934a-19261ccf0504) | ![Screenshot 2024-08-27 at 3 00 11 PM](https://github.com/user-attachments/assets/980da849-9ff3-4963-8fd1-f06cafe8ea60) |
- Ensure multicluster flag is enabled
- Try creating a bucket with a capital letter in the name
- Observe the request silently fails
- Checkout this branch
- Follow reproduction steps
- Observe validation is working as intended …

fix: [M3-8466] - Improve validation rules for create bucket schema

---

packages/manager/.changeset/pr-10846-fixed-1724859567426.md
packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts

- Updates Linode Create v2 to be in parity with Linode Create v1 when it comes to a restricted user creating a Linode in an EU region
- On Linode Create v2, if a user with `add_linodes` access, but with no account/billing permissions tried to create a LInode, they would see an infinite loading spinner. This is because Cloud Manager was trying to GET `/v4/account/agreemeents`, but failed to because the endpoint will 403 for this restricted user.
- Allow restricted users with `add_linodes` access but with no account/billing permissions to create Linodes regardless of the account's agreements. 
- This seems questionable, but this is what Linode Create v1 intentionally did. See https://github.com/linode/manager/pull/7901 
9/3/24
| ![Screenshot …

fix: [M3-8500] - Restricted users without account access unable to create Linodes on Linode Create v2

---

packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
packages/validation/.changeset/pr-10842-fixed-1724786185430.md
packages/validation/src/buckets.schema.ts

The API currently returns an error when creating buckets, incorrectly checking for 'name' instead of 'label'. While a fix for this issue is planned for the future, we can improve our validation in the interim. 
- Update schema to account for existing validation requirements
N/A
- Ensure multicluster flag is enabled
- Try creating a bucket with a capital letter in the name
- Observe the request silently fails
- Checkout this branch
- Follow reproduction steps
- Test for `-test`, `test--`, `test.-` `Test`
- Observe validation is working as intended

fix: [M3-8467] - Improve validation rules for create bucket schema

---

.gitignore
packages/manager/.changeset/pr-10819-fixed-1724404332335.md
packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.test.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx

Object Storage bucket folders containing URL special characters could not be opened. After the change, their links navigate to a correct location.
- Special characters in folder links are URI-encoded.
Any release
| ![image](https://github.com/user-attachments/assets/83612a2f-530a-40c0-ba97-0354cefa4c9d) |![image](https://github.com/user-attachments/assets/86415696-64a6-4e33-841c-b08b84625b09) |
1. Create a folder containing special characters, e.g:
> s3cmd put ./Test.txt s3://sk-test/dir+with+pluses/Test.txt
2. Open that folder in Cloud Manager
When opened, the folder should contain Test.txt file.

fix: [M3-7305] - Correct Object Storage folder links containing special characters

---

packages/manager/.changeset/pr-10848-changed-1724869290917.md
packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.test.ts
packages/manager/src/features/Linodes/LinodeCreatev2/Region.utils.ts

Not all Linux Distributions in the Linode Create OS tab support distributed regions. We want to disable a region if the selected OS does not have a distributed capability similar to the Images tab
- Remove specific check for `linodeCreateTab` in `getDisabledRegions` so that any selected image that does not have the `distributed-sites` capability is disabled
- Minor UI positioning fix for distributed helper text w/ region error text
| Gecko  | Before | After |
| Beta | ![v2-beta-before-os](https://github.com/user-attachments/assets/f8cdba16-1121-4ec4-8d83-448997d256af) | ![v2-beta-after-os](https://github.com/user-attachments/assets/c9d5c0eb-c490-431c-a123-712b854e8172) | 
| Beta | ![image](https://github.com/user-attachments/assets/3acd5bf3-19df-4c04-b6d0-c3 …

change: [M3-8379] - Disable Region in OS tab for unsupported distributed images

---

packages/manager/.changeset/pr-10855-fixed-1724944515841.md
packages/manager/.changeset/pr-10855-tests-1724944533420.md
packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
packages/manager/src/features/NodeBalancers/types.ts

- Updates helper text for Round Robin algorithm and only shows helper text relevant to the selected algorithm
- Updated helper text copy for the 'algorithm' field + updated additional helper text copies as specified
- Added unit tests for config panel 
- some eslint fixes whenever I landed on a file that had them
n/a
| ![image](https://github.com/user-attachments/assets/a392fdae-728c-45f2-85e5-d24e2a8783cd) | ![image](https://github.com/user-attachments/assets/56341474-7ecc-4028-b5dd-6ba147736f83) ![image](https://github.com/user-attachments/assets/19b36057-186b-4396-adb7-1983d88469e8)![image](https://github.com/user-attachments/assets/4c1f10c7-3fb3-4f2c-835c-93ce3cef25ba) |
- Navigate to NodeBalancer create form, note the helper text underneath …

fix: [M3-7142] - Update helper text copy in NodeBalancer Create form 'Algorithm' field

---

packages/manager/CHANGELOG.md

- Updates changelog to link to correct PR (#10797) for entry in Upcoming Features section
9/3/2024
- Confirm PR for 'Add bucket management Properties Tab for Object Storage Gen2' is #10797, not #10795

change: Update changelog to use correct PR number for Upcoming Features entry

---

packages/manager/.changeset/pr-10802-tests-1724271249856.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
packages/manager/cypress/support/intercepts/firewalls.ts

Add Cypress tests to verify the flow to generate compliant firewalls in the Linode Create form.
This flow can also be initiated from the banners in `FirewallLanding` and `FirewallDetails` but since those are already covered by unit tests, and the component is shared, I decided to only write tests for generating firewalls through the Linode create flow.
9/3
- Verify Cypress tests pass

test: [M3-8454] - Cypress test for Secure VMs firewall generation

---

packages/api-v4/src/object-storage/types.ts
packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.styles.ts
packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.test.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.test.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx

- Removed our react hook form logic for `BucketRateLimitTable` and corresponding files. This is far from being ready and it introduced complexity since this component is used in 3 different places. This will most likely be a 2025 initiative to add this logic in when it's ready.
- By removing this, we fixed an issue where app was crashing when trying to display the bucket rate table in any of the drawers for E2/E3. 
- Moved the "Bucket Rate Limits" title and corresponding helper text into `BucketRateLimitTable.tsx` since we were repeating that in 3 different places.
- The Create Bucket drawer now displays each additional step once we have the preceding information selected.
- Once we select a region, we'll show endpoint types
- Once we select endpoint types, we'll show bucket rate limits …

upcoming: [M3-8378] - OBJ Cleanup

---

packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx

We had a fix already in place for this [here](https://github.com/linode/manager/pull/10857/files#diff-5b3f25d0c59a76dccfaf45d3eb177bb551652dafbce19b6a60e3258bea88733bR62-R156) but we didn't get it in the release in time.
- Bucket rate limit text should be feature flagged
| ![Screenshot 2024-09-03 at 3 24 37 PM](https://github.com/user-attachments/assets/81ae7e62-cf98-4fd3-8d2c-68ffdb896e4b) | ![Screenshot 2024-09-03 at 3 24 23 PM](https://github.com/user-attachments/assets/1cc6f61d-7139-4fca-ac99-85fdd5eb5bb6) |
- Turn off Gen2 flag
- With Gen2 flag off
- Observe we erroneously see bucket rate changes
- Select details for any bucket
- Observe fix is in place.

fix: cherry-picked our changes to feature flag rate limit text

---

packages/manager/.changeset/pr-10871-fixed-1725373117220.md
packages/manager/src/components/RegionSelect/RegionSelect.tsx

This fixes an issue where users cannot search for a region by its ID using a `RegionSelect` when Gecko is enabled due to the layout changes made to our region options.
This fixes the issue by [passing a custom filter](https://mui.com/material-ui/react-autocomplete/#custom-filter) to the `Autocomplete` when Gecko is enabled. There should be no impact when Gecko is not enabled.
- Allow regions to be searched by ID when Gecko is enabled
N/A
| ![Screenshot 2024-09-03 at 10 16 35 AM](https://github.com/user-attachments/assets/76dba525-f49a-49a5-8eb6-0f54ed4fffdc) | ![Screenshot 2024-09-03 at 10 15 …

fix: [M3-8502] - Allow regions to be searched by ID when Gecko is enabled

---

packages/manager/.changeset/pr-10888-tests-1725482771826.md
packages/manager/cypress/support/ui/autocomplete.ts

This updates the `ui.regionSelect.findItemById()` and `ui.regionSelect.findItemByLabel()` helpers so that they work when the upcoming Gecko changes are enabled and disabled. Previously, these helpers would fail to select a region when Gecko is enabled due to the layout improvements made to the region selection options.
- Use RegEx to let `ui.regionSelect.findItemById()` and `ui.regionSelect.findItemByLabel()` work with and without Gecko
N/A
Use a test account with Gecko enabled and set `MANAGER_OAUTH` in `.env` to a PAT belonging to the account, and run Cloud against a LaunchDarkly environment where the Gecko feature flag is enabled.
On `develop`:
- Build & serve Cloud via `yarn && yarn build && yarn start:manager:ci`
- Run `yarn cy:debug`
- Search for the `gdpr-agreement.spec.ts` spec …

test: [M3-8471] - Allow Cypress region selection to work with Gecko options improvements

---

packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-10872-upcoming-features-1725396256315.md
packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/factories/account.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx

DBaaS 2.0 enhancements to create page
- New 2 node option for dedicated CPUs
- Expose handleTabChange in PanelsPanel to show/hide 2 node option
9/10/24
- "Managed Databases V2" capability
- dbaasV2 flag enabled
- 2 node option will appear on create page

feat: [UIE-8006] - DBaaS 2.0 Create

---

packages/manager/.changeset/pr-10877-tech-stories-1725397280235.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts
packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts
packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts
packages/manager/cypress/e2e/core/placementGroups/placement-groups-linode-assignment.spec.ts
packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
packages/manager/cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx
packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
packages/manager/src/features/PlacementGroups/utils.test.ts
packages/manager/src/features/PlacementGroups/utils.ts

Update CM codebase to remove `placementGroups` flag logic.
This is should bring no changes to the feature nor introduce any regressions
- Remove flag
- Remove flag tool
- Update unit & e2e tests
- Verify Placement Groups feature is available as a general feature (main navigation and feature details)
- Confirm tests are accurate and passing without flag logic

refactor: [M3-8496] - Remove Placement Group flag and underlying logic

---

packages/manager/.changeset/pr-10893-fixed-1725548041320.md
packages/manager/src/features/Lish/Weblish.tsx

When working on file edits in Weblish, current line wrapping makes it impossible to edit certain lines because of the way our columns are set up. Weblish is visually showing additional characters past 80 columns on the same line while the cursor behaves as though the line is soft wrapped.
- Set Weblish terminal `cols` to `80` to match default LISH over ssh behavior 
**9/16/2024**
| <video src="https://github.com/user-attachments/assets/01015715-5e07-4ce2-9308-bfc6d5483f93" /> | <video src="https://github.com/user-attachments/assets/7820e8ab-c261-4e3a-b08f-632f888bab3b" /> |
1. Create Ubuntu 24.04 Nanode in Miami
2. Once provisioned, click Launch LISH Console in Cloud Manager
3. Login through Weblish as root
3. Enter command vim …

fix: [M3-8529] - Weblish line wrapping

---

packages/manager/.changeset/pr-10890-tests-1725525454848.md
packages/manager/src/components/SelectableTableRow/SelectableTableRow.test.tsx

Unit test cases for SelectableTableRow Component.
- Add unit test cases for SelectableTableRow Component.
9/16
- Run `yarn test src/components/SelectableTableRow`

test: [M3-8518] - Add unit tests for SelectableTableRow component

---

packages/manager/.changeset/pr-10841-tech-stories-1724763185078.md
packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts
packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts
packages/manager/cypress/e2e/core/volumes/upgrade-volume.spec.ts
packages/manager/src/features/Events/asyncToasts.test.tsx
packages/manager/src/features/Events/asyncToasts.tsx
packages/manager/src/features/Events/factories/backup.tsx
packages/manager/src/features/Events/factories/disk.tsx
packages/manager/src/features/Events/factories/image.tsx
packages/manager/src/hooks/useToastNotifications.tsx

`const toasts: Toasts = { ... }`  should be moved to the event directory and map to event messages already defined in our new factory.
- Refactor `useToastNotification`.
- Move `const toasts: Toasts = { ... }` to `Events/asyncToasts.tsx`.
- Map to event messages already defined in our new factory.
- Update the event messages in `Events/factories/disk.tsx`.
- Update e2e test cases.
- Add unit test cases.
N/A
- Verify all the async toasts continue to work as expected.
- Confirm that the formatting and display of messages adhere to the event messages defined in our new `Events/factories`

refactor: [M3-8331] - useToastNotification async toasts

---

SECURITY.md
packages/manager/.changeset/pr-10902-changed-1725634282672.md
packages/manager/public/.well-known/security.txt
security.txt

Small updates to security policy as requested of us.
- Updates manager package's `security.txt` file to match https://www.linode.com/.well-known/security.txt
- Converts the root `security.txt` file to Markdown, which is more standard based on Git [documentation](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies).
- > When someone creates an issue in your repository, they will see a link to your project's security policy.
09/16/24
- Read the diff, and see the internal ticket / #10897.

change: [M3-8548] - Update security policy

---

packages/manager/.changeset/pr-10896-changed-1725558246039.md
packages/manager/src/components/RegionSelect/RegionOption.tsx
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx

Gecko LA will be billed so we want to hide the temp Beta pricing notice if LA is enabled
- Hide Beta pricing notice in the Linode Plan table when a distributed region is selected for Gecko LA
- Rename GA references to LA
| ![image](https://github.com/user-attachments/assets/53218573-c2e2-4566-b0cf-001fc83c7f68) | ![gecko la plan table](https://github.com/user-attachments/assets/31855d44-61dc-48a6-8dfd-40b4246a60a6) |
- Ensure your account has the `new-dc-testing`, `new-dc-testing-gecko`, `edge_testing` and `edge_compute` customer tags
- Pull this PR and run it locally pointing to dev API
- Select an image compatible with distributed regions (e.g. …

change: [M3-8531] - Hide Beta price notice for Gecko LA

---

packages/manager/.changeset/pr-10901-fixed-1725632415734.md
packages/manager/src/features/Events/factories/linode.tsx

Previously, this event message would say 'Linode migrating to X region', where X region is the region the linode is currently in, not the one it's being migrated to. We are updating this message to be generic -- see internal ticket for details.
- Since this message is now generic, we don't need to override the event message anymore
n/a
| ![image](https://github.com/user-attachments/assets/e0f733eb-985b-483c-9965-639e42df6a68) | ![image](https://github.com/user-attachments/assets/7a1d6462-9964-48ce-b4ce-2565e27e3f44) |
- Migrate a linode to a new region, and note how the message says 'Linode migrating to [original] region' once migration begins
- Confirm event message is now generic
*Check all that …

fix: [M3-7915] - Update Linode Migrate Datacenter Started message to be generic

---

packages/manager/.changeset/pr-10882-tests-1725437459486.md
packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts

Added cypress test for empty Linode landing page and restricted user Linode landing page  
Added below cypress tests under in spec file - cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
- checks empty state on linode landing page
- checks restricted user has no access to create linode on linode landing page
- M3-6615
- M3-8507
`yarn cy:run -s cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts`
When test executed using this command  `yarn cy:run -s cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts`all tests should pass successfully and you should see new test added as per below screenshot 

test: [M3-6615, M3-8507] - Cypress test for empty Linode landing page and restricted user Linode landing page 

---

packages/manager/.changeset/pr-10894-added-1725553004847.md
packages/manager/.changeset/pr-10894-fixed-1725552964331.md
packages/manager/src/components/Code/Code.tsx
packages/manager/src/components/TextField.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelectionList.tsx
packages/search/src/search.peggy
packages/search/src/search.test.ts

- Fixes https://github.com/linode/manager/issues/10869
- Allows users to use quoted strings (therefore spaces) when searching using Search v2 🔍 
- For example, if you want to search for a StackScript with the label `My StackScript`, with this PR, you can search using a quoted string: `label: "My StackScript"`
- ⚠️  Ideally, the user would be able to do `label: My StackScript` instead of `label: "My StackScript"`, but I couldn't quite get that working. I think it would require a significant rework of our search parser. I think a quoted string is probably a good step forward for now, but let me know if you disagree!
- Makes the user's search to have priority over the default StackScript filter 💪 
- This fixes an issue where and queries would not work because they were overwritten by the …

change: [M3-8530] - Allow quoted strings in Search v2 and improve StackScript searching on Linode Create v2 

---

packages/manager/.changeset/pr-10899-changed-1725595024930.md
packages/manager/cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts
packages/manager/cypress/e2e/core/notificationsAndEvents/events-menu.spec.ts
packages/manager/cypress/support/intercepts/events.ts
packages/manager/cypress/support/ui/app-bar.ts
packages/manager/cypress/support/ui/index.ts
packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx
packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
packages/manager/src/features/TopMenu/TopMenu.tsx
packages/manager/src/queries/events/events.ts

This PR is a replacement for https://github.com/linode/manager/pull/10785 which had become difficult to rebase.
It is essentially the same PR including fixes and cleanup for the new e2e tests.
This change optimizes Cloud Manager's event querying by reducing the historical data range. 
Specifically, it limits the event query timeframe from the current 90 days to a more focused 7-day period. 
- This is true for the default Cloud Manager query that also populates the Notification Center
- The `/events` page still queries 90 day and isn't affected by this PR
This adjustment aims to improve query performance and reduce unnecessary data retrieval while still providing relevant recent event information.
- Previously we fetched the first 100 events but returned almost 500 results/records. These …

change: [M3-8450] - Lower Events historical data fetching to 7 days 

---

packages/manager/.changeset/pr-10887-tech-stories-1725467686328.md
packages/manager/src/utilities/codesnippets/generate-ansibleConfig.test.ts
packages/manager/src/utilities/codesnippets/generate-ansibleConfig.ts

- Resolve codeQL alert due to not escaping backslashes by updating regex
- Added test case for the special characters not yet tested for
n/a
| ![image](https://github.com/user-attachments/assets/77148147-ba6c-4ca0-8140-211a2d6c994d) | ![image](https://github.com/user-attachments/assets/50a11d31-c5b3-4f16-9690-4608a4f0463f) |
Here are the steps I took to setup codeQL on vscode. Not sure if this is the most straightforward way, but it (seems to have) worked 😅 
- download the codeQL extension on vscode
- follow along to [this guide](https://luisrangelc.medium.com/analyze-vulnerabilities-in-your-code-with-codeql-locally-3e5d31f8ed2)
- I used the most up to date version (2.18.3) when downloading codeQL CLI this time around, but I remember using the …

tech story: [M3-8423] - Resolve "Incomplete string escape or encoding" in generate-ansibleConfig.test.ts

---

packages/manager/.changeset/pr-10852-tests-1724937535185.md
packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
packages/manager/cypress/e2e/core/parentChild/token-scopes.spec.ts

Ensure that the outgoing API request when creating an API token matches what’s expected for each type of user: regular user, parent user with restricted access, parent user with unrestricted access.
- Add new assertions for regular user in account/personal-access-tokens.spec.ts
- Add new tests for parent user with restricted access and parent user with unrestricted access in parentChild/token-scopes.spec.ts
```
yarn cy:run -s "cypress/e2e/core/account/personal-access-tokens.spec.ts"
yarn cy:run -s "cypress/e2e/core/parentChild/token-scopes.spec.ts"
```

test: [M3-7971] - Add new tests for for selecting "All" Scopes

---

packages/manager/.changeset/pr-10909-tests-1725903174019.md
packages/manager/.changeset/pr-10909-upcoming-features-1725903122030.md
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Volumes/AttachVolumeDrawer.test.tsx
packages/manager/src/features/Volumes/AttachVolumeDrawer.tsx

- Minor tooltip copy update in Edit Volume drawer
- Add disabled "Encrypt Volume" checkbox in Attach Volume drawer
This PR is quite similar to https://github.com/linode/manager/pull/10787.
9/16/24
| ![Screenshot 2024-09-09 at 1 26 33 PM](https://github.com/user-attachments/assets/599e1da4-333d-4111-a597-1b64bf740456) | ![Screenshot 2024-09-09 at 1 25 54 PM](https://github.com/user-attachments/assets/a11370e4-25cc-459a-95b4-200f5d3d343b) |
```
yarn test AttachVolumeDrawer.test.tsx
```
Confirm the Attach Volume drawer (accessed from Volume landing page --> three-dot menu for a volume) has the BSE checkbox when the feature flag is on, and that the checkbox reflects …

upcoming: [M3-8549] – BSE tooltip copy update & add "Encrypt Volume" checkbox in Attach Volume drawer

---

packages/manager/.changeset/pr-10913-fixed-1725955539025.md
packages/manager/src/components/Currency/Currency.test.tsx
packages/manager/src/components/Currency/Currency.tsx

The Storybook for DisplayPrice is crashing when the `minimumFractionDigits` in the Currency component is set with a negative value.
This PR addresses the issue by updating the Currency component to handle negative decimalPlaces props correctly. Specifically, it ensures that the `minimumFractionDigits` defaults to 2 when the `decimalPlaces `prop is `negative` or `undefined`.
- Handle negative decimalPlaces prop in Currency component to fix DisplayPrice story
- The `minimumFractionDigits` in the Currency component will now use the default value (2) when `decimalPlaces` prop is `negative` or `undefined`.
- Add a unit test case to cover the above scenario.
- Update all other unit test cases for more clarity.
N/A
- Go to the DisplayPrice storybook
- Enter a negative value for decimalPlaces …

fix: [M3-8553] - DisplayPrice story crash when Currency component's `minimumFractionDigits` is negative

---

packages/manager/src/features/GlobalNotifications/GravatarSunsetBanner.tsx

I merged #10859 and, of course, promptly noticed that there were a couple of bugs in the banner. 🤦🏼‍♀️ 
No changeset since this hasn't been released.
- Change the September 28 date to September 30, an actual Monday and day of the release
- Check for `isLoadingGravatar` from the `useGravatar` hook to avoid unintentionally displaying the banner to users without a Gravatar - we made some updates to `useGravatar` in the previous PR to use a cache and this was impacting the banner
9/16/24
| ![Screenshot 2024-09-11 at 7 55 01 AM](https://github.com/user-attachments/assets/5edf166f-754f-4de1-875d-3063b25e5af7) | ![Screenshot 2024-09-11 at 8 04 18 AM](https://github.com/user-attachments/assets/3681f0fd-6657-43a1-a7b7-08639a85416c) ![Screenshot …

fix: [M3-8158] - Fix inaccurate Gravatar sunset banner date and rendering for users without Gravatar

---

packages/api-v4/.changeset/pr-10920-added-1726070878408.md
packages/api-v4/src/linodes/types.ts
packages/manager/.changeset/pr-10920-upcoming-features-1726068029277.md
packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts
packages/manager/src/features/Volumes/VolumeCreate.tsx
packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAddDrawer.tsx
packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeAttachForm.tsx

- Change BSE capability for Linodes from `blockstorage_encryption` --> `Block Storage Encryption`
- Adjust `enabled` condition passed to `useLinodeQuery()` on Volume Create page so it is true only if `linode_id !== null`
9/16/24
| ![Screenshot 2024-09-11 at 10 55 05 AM](https://github.com/user-attachments/assets/1acd9090-e124-4df7-b5ae-548b706239aa) | ![Screenshot 2024-09-11 at 11 01 21 AM](https://github.com/user-attachments/assets/af6f7dc0-30c2-494a-a716-977d0ba868ca) |
On the Volume Create page, you should no longer see requests to `linode/instances/-1` before selecting a linode.

fix: [M3-8563 & M3-8566] – Fix BSE capability for linodes & prevent unnecessary API request on Volume Create page

---

packages/manager/.changeset/pr-10923-fixed-1726086511137.md
packages/manager/src/features/NotificationCenter/Events/NotificationCenterEvent.tsx

One more bug fix...
There are a very small number of events that we consider `ACTIONS_WITHOUT_USERNAMES`. Some of these actions have no username, and other we want to override the username with `Linode` - we have a util called `getEventUsername` to do this for us.
We weren't making use of the username from the util correctly in this component, which we assign at [L36](https://github.com/linode/manager/pull/10923/files#diff-f6365682e16359d1aa4ddb5fe6a52aa28748fde917622c7c0689dd5a9b8053bfR36).
Without using this util, if a username existed (as it does for `entity_transfer_create` events), we were rendering the wrong initial in the avatar component. Since this is an 'action without username', we want the username to be Linode and to render the Akamai logo as the avatar.
We were already using …

fix: [M3-8158] - Render the correct Avatar icon for `ACTIONS_WITHOUT_USERNAMES`

---

Jenkinsfile-component-tests.groovy
docker-compose.yml
package.json
packages/manager/.changeset/pr-10926-tests-1726156342482.md
packages/manager/cypress.config.ts
packages/manager/cypress/component/poc/region-select.spec.tsx
packages/manager/cypress/support/component/index.html
packages/manager/cypress/support/component/setup.tsx
packages/manager/cypress/support/plugins/junit-report.ts
packages/manager/package.json

This PR contains the changes needed to get the Cloud Manager component tests running via CI. There isn't too much testing that can be done for this, but I did add some information to the ticket related to validating these changes.
- Added `yarn cy:component:run` command to run component tests via the CLI
- Enables JUnit generation for component tests
- Discards passed test recordings for component tests
- Adds a Docker Compose service for running component tests
- Fixes a region select test failure related to recent util changes
- Run `yarn cy:component:run` and make sure tests run and pass
- See the ticket comments for more info about testing and validation

test: [M3-8517] - Cloud changes for component test CI

---

packages/manager/.changeset/pr-10908-fixed-1726091771498.md
packages/manager/src/features/Users/UserPermissions.tsx
packages/manager/src/features/Users/UserPermissionsEntitySection.tsx

This PR fixes the problem in which the "None", "Read-Only", and "Read-Write" radio buttons under the "Specific Permissions" of the User Permissions page do not have any label or ARIA label, making it difficult to interact with the page using screen readers.
- Replaces native `<label />` element with MUI equivalent components.
- Changes the content used by screen readers to express information to the user.
- Changes the label positioning of the radio buttons in accordance with [Advisory Technique G162](https://www.w3.org/WAI/WCAG21/Techniques/general/G162#example-3-labels-to-the-right-of-radio-buttons) of the WCAG 2.1 standards.
09/11/2024
| ![m3-7475-before](https://github.com/user-attachments/assets/860c …

fix: [M3-7574] - Fix missing labels for User Permission radio buttons

---

packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/AnsibleIntegrationResources.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/CurlTabPanel.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/GoSDKResources.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/PythonSDKResources.tsx
packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/TerraformIntegrationResources.tsx
packages/manager/src/features/Linodes/LinodesCreate/CodeBlock/CodeBlock.tsx

This PR avoid's firing LD metrics events for internal users.
9/16
- Verify LD events for DX tools shouldn't fire for internal accounts.

Filter metrics for internal users

---

packages/manager/.changeset/pr-10924-fixed-1726085139068.md
packages/manager/src/features/Domains/DomainBanner.tsx

Fixes an alignment issue in the DNS zones banner. This banner appears in the domains landing when the user has a DNS zone but no Linodes on their account.
|Breakpoint|Before|After|
|--|--|--|
|`lg`|![Screenshot 2024-09-11 at 3 59 48 PM](https://github.com/user-attachments/assets/f23954a2-b761-4ff5-bc6e-7551667ff947)|![Screenshot 2024-09-11 at 3 59 56 PM](https://github.com/user-attachments/assets/ce07197a-409c-4019-b935-256f862330ce)|
|`md`|![Screenshot 2024-09-11 at 4 00 28 PM](https://github.com/user-attachments/assets/f0403887-acf1-4ff4-afc2-8773aba8d48e)|![Screenshot 2024-09-11 at 4 00 23 PM](https://github.com/user-attachments/assets/7fd2c62c-e501-4386-89e4-fa844b6e7f2c)
|`sm`|![Screenshot 2024-09-11 at 4 00 45 PM](https://github.com/user-attachments/assets/cc9d5c97-49a9-4d7e-8d05-b82 …

fix: [M3-8161] - Fix misaligned DNS banner text

---

packages/manager/.changeset/pr-10917-tests-1726061618551.md
packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
packages/manager/src/components/Dialog/Dialog.test.tsx

Unit test cases for Dialog and DeletionDialog components.
- Add unit test cases for Dialog and DeletionDialog components.
N/A
- Run `yarn test src/components/Dialog src/components/DeletionDialog --reporter verbose` 

test: [M3-8544, M3-8545] - Add unit tests for Dialog and DeletionDialog components

---

packages/manager/.changeset/pr-10938-fixed-1726262803311.md
packages/manager/src/components/TextField.tsx

Fixes the focus area for tooltips to be a circle rather than an oval as before.
| ![Screenshot 2024-09-13 at 5 21 43 PM](https://github.com/user-attachments/assets/5d517e74-1ed0-4b47-942f-6d894e693f68) | ![Screenshot 2024-09-13 at 5 21 32 PM](https://github.com/user-attachments/assets/edfd36fa-ee43-4415-b362-11a446ffa0ab) |
Verify textfield tooltips' focus areas render as a circle and otherwise work as before.

fix: [M3-7149] - Fix textfield tooltip icon focus area

---

packages/manager/.changeset/pr-10947-fixed-1726507951785.md
packages/manager/src/queries/account/users.ts

- Updates our cache updating logic on the `useUpdateUserMutation` hook to manually update the profile cache rather than invalidating it  🔧 
- This fixes 🔧  the bug :bug: caught by @mjac0bs where the page would exhibit some flickering on the Delete button and Email fields when updating the username of the currently signed in user
| <video src="https://github.com/user-attachments/assets/7b91a532-fca0-44d8-8d2e-91e79a3a3b2e" /> | <video src="https://github.com/user-attachments/assets/1e3191e7-e539-4577-a131-94330ddb6302" /> |
- Check out this PR or use the preview link
- Go to the user profile of the **currency signed in user**
- In my case, this is http://localhost:3000/account/users/banks
- Try updating the username
- Verify there is no …

fix: [M3-8589] - Flickering on the user profile page when updating the currently signed in user's username

---

packages/manager/.changeset/pr-10945-tests-1726507532580.md
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerCreate.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerSelect.test.tsx

- Adds unit tests for the rest of NodeBalancers package to improve test coverage and confirm things render as expected
n/a
- `yarn test NodeBalancers` - confirm all tests pass

test: [M3-8565] - Add unit tests for rest of NodeBalancers package

---

packages/manager/.changeset/pr-10955-tech-stories-1726591613226.md
packages/manager/package.json
yarn.lock

Fixes dependabot alert here: https://github.com/linode/manager/security/dependabot/121
See https://github.com/linode/manager/pull/10953 for context
- Updates package.json to make dompurify dependency v3.1.6
- also takes the change from the linked PR to remove dompurify v2.4.7
- updates jsPDF to newest version (2.5.2) since they address the dompurify issue there
- confirm github actions pass
- confirm running yarn install doesn't change the yarn.lock file
- *** confirm no regression in invoice pdf generation 

tech story: Update dompurify and jsPDF to fix dependabot alert

---

packages/manager/.changeset/pr-10948-fixed-1726517375013.md
packages/manager/src/components/LinkButton.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx

- Fixes RDNS typo on a IPv6 Range row on the Linode Details page 🌎 
- Uses a `<LinkButton />` instead of an un-styled browser button 🔘 
| ![Screenshot 2024-09-16 at 3 48 59 PM](https://github.com/user-attachments/assets/ac0e2a88-5e84-4c3b-af30-86ea63c8d3c2) | ![Screenshot 2024-09-16 at 3 47 53 PM](https://github.com/user-attachments/assets/f1035647-7d3b-4e1d-8b67-6205e0f9f71f) |
- Setting up RDNS on an IPv6 range is quite a process, I recommend following [this guide 📘](https://techdocs.akamai.com/cloud-computing/docs/configure-rdns-reverse-dns-on-a-compute-instance#ipv6-pools-and-routed-ranges) on setting it up if you want to go through the trouble. The changes are minimal enough that you probably don't need to go through this process.

fix: [M3-8422] - Linode IPv6 rDNS typo

---

packages/api-v4/.changeset/pr-10939-upcoming-features-1726263534115.md
packages/api-v4/src/regions/types.ts
packages/manager/.changeset/pr-10939-upcoming-features-1726263444178.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/validation/src/databases.schema.ts

DBaaS enhancements to the Summary and Settings tabs
- Readonly host displayed
- Hide monthly maintenance window for V2
9/30/24
- Account must have capability "Managed Databases Beta"
- Use mock data to view fields in both V1 and V2
- Text Copy is different for V2
- Monthly/weekly radio is hidden for V2

feat: [UIE-8007] - DBaaS enhancements summary and settings

---

packages/manager/.changeset/pr-10965-fixed-1726675687897.md
packages/manager/src/features/OneClickApps/oneClickAppsv2.ts

The documentation for the Apache Spark Marketplace Cluster is located at:
https://www.linode.com/docs/marketplace-docs/guides/apache-spark-cluster/
The current URL is wrong and needs to be fixed at: `packages/manager/src/features/OneClickApps/oneClickAppsv2.ts`
- Change slug from `apache-spark` to `apache-spark-cluster`
September 30, 2024
See the bottom left where the URL slug is:
| Before  | 
| After   |

fix: Marketplace Apache Spark Cluster URL Slug

---

packages/api-v4/package.json
packages/manager/.changeset/pr-10960-tech-stories-1726671382649.md
packages/manager/package.json
packages/search/package.json
yarn.lock

Bumps vite and vite related packages 
we have slew of new dep vulnerabilities, and while this is all dev vulnerabilities, this one looks like an easy target.
opening in favor of the dependabot PR: https://github.com/linode/manager/pull/10957 in order to have all suites running easily
- bump vite and vite related packages to latest versions
- make sure app and test suites get no regression from PR

chore: bump vite to 5.4.6

---

packages/manager/.changeset/pr-10963-changed-1726672295505.md
packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.test.tsx
packages/manager/src/features/Profile/DisplaySettings/AvatarColorPickerDialog.tsx

Internal feedback: a user can forget to hit 'Save' once they've made their color selection.
Enabling the primary action button only if the color is changed makes the enabled Save button a more visible call to action for the user, reminding them to click it once they've selected a color.
- Disables the Save button on the `AvatarColorPickerDialog` 
9/30/24
| Color not changed | Color changed |
|--------|--------|
| ![Screenshot 2024-09-18 at 7 55 50 AM](https://github.com/user-attachments/assets/b15c7d73-5694-4c3d-8bbb-d5fb819f1ab8) | ![Screenshot 2024-09-18 at 7 56 05 AM](https://github.com/user-attachments/assets/e47ef60d-1d8b-4b1b-8644-9573e2ab2396) |
- Use an account without a Gravatar or repro the issue in the dev environment, where Gravatars are no …

change: [M3-8599] - Disable 'Save' button in Change Avatar Color dialog until color is changed

---

packages/manager/src/components/Autocomplete/Autocomplete.tsx
packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx

- Should hopefully fix the test failures we've recently begun seeing throughout the test suite when Cypress tries to interact with Autocompletes:
> cy.click() failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:
> <div.MuiBox-root.css-b5zaes>
We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page.
- Provides an alternative to @jdamore-linode 's fix https://github.com/linode/manager/pull/10976/commits/a90aba8f714b739b4e085261aef44c652047c294 that was originally in  #10976 
- This PR reverts some changes made in https://github.com/linode/manager/pull/10780  in favor of using MUI's built in `slotProps` to customize components that make up our AutoComplete
- …

fix: [M3-8617] - Autocomplete Popper re-rendering causing test failures

---

packages/manager/.changeset/pr-10973-upcoming-features-1726768912614.md
packages/manager/src/components/Encryption/constants.tsx

Update URL for Volume Encryption guide
9/30/24
The guide is linked to on the Volume Create page and in the Linode Details > Storage tab > Create and Attach Volume drawer. The "Learn more" text should link to the set URL.

upcoming: [M3-8604] – Update URL for Volume Encryption guide

---

docs/development-guide/09-mocking-data.md
packages/manager/cypress/e2e/core/databases/update-database.spec.ts

Recent [improvements made for DBaaS v2](https://github.com/linode/manager/pull/10939) began causing intermittent test failures in `update-database.spec.ts`. This PR makes a few changes to resolve these failures:
- Mocks the `dbaasV2` feature flag to be disabled
- Mocks the account so that it is lacking the `Managed Databases Beta` capability
- Updates the test's database mock to force the `platform` field to always reflect the legacy platform
- ℹ️ This seems to be what actually fixed the test, and appears to take precedence over the DBaaS v2 feature flag and account capability
- ⛔️ Going forward we might want to discourage using `pickRandom` or any similar utils that make our factories less deterministic since they're used throughout the codebase/tests
N/A
We can't rely solely on CI for …

test: [M3-8616] - Fix failures in DBaaS update tests

---

packages/manager/.changeset/pr-10959-changed-1726660002249.md
packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/shared/LinodeSelectTable.tsx
packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts

- When cloning a Linode with backups enabled, the "Backups Enabled" checkbox should be checked by default (near the bottom of the Create flow)
- When cloning a Linode with backups disabled, the "Backups Enabled" checkbox should be unchecked by default (near the bottom of the Create flow)
- When cloning a Linode with backups enabled, the "Backups Enabled" checkbox is checked by default.
- When cloning a Linode with backups disabled, the "Backups Enabled" checkbox  is unchecked by default.
N/A
-  When cloning a Linode with backups enabled/disabled, the "Backups Enabled" checkbox is unchecked.
- When cloning a Linode with backups enabled: 
- Verify the "Backups Enabled" checkbox should be checked by default.
- Without changing the state of the "Backups Enabled" checkbox, the newly cloned …

change: [M3-6838] - Better "Backups Enabled" default when cloning Linode

---

packages/manager/.changeset/pr-10983-tests-1726865807776.md
packages/manager/cypress/support/ui/autocomplete.ts

This fixes the intermittent test failures we've been seeing in `create-linode-from-image.spec.ts`, and possibly other specs, which occur when Cypress tries to select a region with a name that's similar to another region. Specifically, tests in this spec fail consistently when trying to select _UK, London_ (`eu-west`) because _UK, London 2_ (`gb-lon`) also gets matched.
This issue was triggered by recent changes to our region select UI helpers, intended to facilitate region selection when Gecko is enabled (#10888).
- Increases specificity of region selection RegEx to account for regions with similar names
N/A
Check out `develop` and build Cloud via `yarn && yarn build && yarn start:manager:ci`, then:
- Run `CY_TEST_REGION='eu-west' yarn cy:run -s …

test: [M3-8619] - Fix Cypress test flake in `create-linode-from-image.spec.ts`

---

packages/manager/.changeset/pr-10981-tests-1726863454562.md
packages/manager/cypress/e2e/core/nodebalancers/nodebalancers-create-in-complex-form.spec.ts

This attempts to resolve the test flake in `nodebalancers-create-in-complex-form.spec.ts`. The root of the issue is our execution of async code in the Cypress test without wrapping it in `cy.defer` -- this caused the Cypress tests to execute and fail rapidly without allowing Cypress to actually run and evaluate all of the `cy.*` commands in the queue.
The HTTP 429 errors we see in our CI are a symptom of this issue rather than a cause.
- Wrap async operations in `cy.defer`, remove `async` keyword from `it(...)` calls
N/A
Check out `develop`, build and serve Cloud via `yarn && yarn build && yarn start:manager:ci`
- Run `yarn cy:run -s "cypress/e2e/core/nodebalancers/nodebalancers-create-in-complex-form.spec.ts"`
- Observe intermittent failures (it may not fail on your first try but does …

test: [M3-8601] - Fix NodeBalancer `nodebalancers-create-in-complex-form.spec.ts` Cypress test flake

---

.husky/pre-commit
package.json
packages/manager/.changeset/pr-10990-tech-stories-1727187564566.md
yarn.lock

- Updates our Git hooks tool called "Husky" to the latest version 🐺 📦 
- I followed the guide here https://typicode.github.io/husky/migrate-from-v4.html  🌎 
- Upgrading husky is one pice of the puzzle 🧩 to unblocking unblocking the yarn ➡️ [pnpm](http://pnpm.io) effort 🚧 
- This goal of this PR is to just upgrade Husky and keep things working as they currently do. Hopefully in the near future we can optimize, remove, or improve our current precommit hooks
https://github.com/user-attachments/assets/37886515-1cc2-4c83-bedd-4236759107c6
- Make a random change in the codebase
- Add your changes with `git add`
- Commit your changes with `git commit`
- Verify the pre-commit hooks run as expected
> [!warning]
> If you test this PR locally, it may cause pre-commit hooks to not …

chore: Update `husky` to latest

---

packages/manager/.changeset/pr-10985-changed-1727105394355.md
packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImagesLandingEmptyStateData.ts

- Updates the Images Landing page empty state based on UX's request as part of Image Service Gen 2 💾 
| ![Screenshot 2024-09-23 at 11 25 37 AM](https://github.com/user-attachments/assets/7cec51ab-036a-457b-ae00-7a5208a84ba1) | ![Screenshot 2024-09-23 at 11 25 02 AM](https://github.com/user-attachments/assets/3a9effb7-8334-40cf-81e2-457db3c35a8c) |
- Check new copy for correctness 👀 
- Verify all automated testing passes ✅

change: [M3-8622] - Update Images empty state as part of Image Service Gen2

---

packages/manager/.changeset/pr-10999-tests-1727196449912.md
packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts

This PR attempts to address or improve the test flakiness we've been seeing in `smoke-delete-linode.spec.ts` `deleting multiple linodes with action menu`.
What initially caused this test to become flaky is still unclear, but the majority of the failures I've observed follow this sequence of events:
1. Cypress deletes the first Linode
2. After the deletion request succeeds, but before Cloud has updated the landing page list to reflect the deletion, Cypress opens the action menu for the second Linode
3. Before Cypress is able to click the "Delete" menu item, the Linode landing page updates to reflect the deletion of the initial Linode, causing the opened action menu to close
4. Cypress is unable to click "Delete" because the action menu item is no longer on-screen, and the test fails
We had …

test: [M3-8395] - Fix Linode delete test flake by fixing deletion assertion

---

packages/manager/.changeset/pr-10927-fixed-1726139552414.md
packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/queries/object-storage/queries.ts

After uploading several files into the object storage, file table was not updated correctly. In the provided fix, fresh data from the store is used during the store overriding.
- Object buckets query key moved into a separate getter function and exported.
- Fresh store data is used during the overriding process.
- Open the "Object Storage" page.
- Upload several files using drop area or browse button.
- Look at how the table is being updated after each file is uploaded.

fix: [M3-8519] - Objects Table Refreshing Logic

---

packages/manager/.changeset/pr-10993-fixed-1727189409908.md
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx

DBaaS empty landing page show logo for V2
- Use feature flag and account capability to show V2 logo
9/39/24
- Not in V2
- Go to empty landing page
- No logo for V2 user
- [] 🧪 Providing/Improving test coverage

fix: [UIE-8150]  - DBaaS empty landing page show logo for V2

---

packages/api-v4/.changeset/pr-10989-fixed-1727118907870.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-10989-fixed-1727118993352.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

DBaaS Summary tab display correct user and readonly host
- Display correct username for V2
- Display correct read-only host for V2
9/30/24
| ![Screenshot 2024-09-23 at 3 12 16 PM](https://github.com/user-attachments/assets/4d057872-4574-4cf8-9f53-60535c515e23) | ![Screenshot 2024-09-23 at 3 12 27 PM](https://github.com/user-attachments/assets/7f5802ab-4784-47a8-94c2-4e665208a82a) |
- Managed Databases Beta account capability
- Create new DB
- Go to summary tab
- Username is correct
- readonly host displays
- [] 🧪 Providing/Improving test coverage

fix: [UIE-8007] - DBaaS Summary tab display correct user and readonly host

---

packages/manager/.changeset/pr-10986-changed-1727108550951.md
packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.test.tsx
packages/manager/src/components/Uploaders/ImageUploader/ImageUploader.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx

Makes some minor copy updates and UI tweaks on the Image Upload page based on UX's request 🎨 
| ![Screenshot 2024-09-23 at 12 07 49 PM](https://github.com/user-attachments/assets/195b07ac-1157-49a8-97c9-05c622cf8ec2) | ![Screenshot 2024-09-23 at 12 06 57 PM](https://github.com/user-attachments/assets/6ecfa99e-eead-4654-8b9d-0341c1144b20) |
- Go to http://localhost:3000/images/create/upload
- Check UI and verify the changes make logical sense 🧠 
- Check copy for spelling ✏️ 
- Check for any UI regressions 👁️

change: [M3-8614] - Update Image Upload dropzone copy as part of Image Service Gen2

---

packages/api-v4/.changeset/pr-10980-changed-1726868220865.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-10980-fixed-1726845381695.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/validation/.changeset/pr-10980-changed-1726868115893.md
packages/validation/src/databases.schema.ts

DBaaS V2 bug fix
- fix: Display "resizing" database status only when expected.
- fix: Ensure tooltip text correctly reflects the time zone.
- remove replication_type and replication_commit_type fields from the Create Database
9/30/24
**Enable DatabaseV2Beta flag**
**To check 'remove replication_type and replication_commit_type fields from the Create Database'** 
- Navigate to the Databases section.
- Click the 'Create Database Cluster' button.
- Complete the database creation form.
- Click the 'Create Database Cluster' button.
- You will be redirected to the Summary tab.
**To check 'ensure tooltip text correctly reflects the time zone'** 
- Navigate to the Databases section.
- Select the …

fix: [UIE-8146] - DBaaS V2 bug fix

---

packages/api-v4/.changeset/pr-10988-changed-1727197910740.md
packages/api-v4/src/databases/databases.ts
packages/manager/.changeset/pr-10988-fixed-1727119069361.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreLegacyFromBackupDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreNewFromBackupDialog.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/queries/databases/databases.ts

Fixes for DBaaS Backups tabs
- Disable dates when there are no backups to restore from
- Avoid unnecessary API call
- Remove custom label
9/30/24
- Managed Databases Beta account capability
- Create a new DB
- Navigate to Backups while it's still provisioning, or just activated.
- You cannot select a date
- An info banner displays

fix: [UIE-8009] - DBaaS backups disable invalid dates

---

packages/manager/.changeset/pr-11001-fixed-1727211401885.md
packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx

The `ConfigSelect` component uses an Autocomplete whose value is sometimes inadvertently set to `undefined`. This causes a "A component is changing an uncontrolled Autocomplete to be controlled" console error and, more critically, may cause a crash in certain situations.
> [!NOTE]
> This bug only appears in the latest `develop`
> Edit: and I can only reproduce it in the dev environment (not in productions builds e.g., cloud.dev.linode.com)
9/30
| <video src="https://github.com/user-attachments/assets/4700dc4b-7b57-49dc-af86-4aea5c6dbfac" /> | <video src="https://github.com/user-attachments/assets/519ce4ff-0b4d-4370-b7b4-6448ed980492" /> |
- Two or more Linodes in the same region with exactly one config
- Navigate to the Volume Create page
- …

fix: [M3-8661] - Fix crash in Volume Create page caused by misconfigured Autocomplete

---

packages/manager/.changeset/pr-10956-added-1727103260742.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/components/PlansPanel/PlanInformation.tsx

Small PR to add a GPUv2 Banner for the 9/30 new GPU plans launch. This is the MVP for the initial launch, before modifying the Plans Panel to account for transfer and billing changes.
> [!NOTE]
> This is very much a temp banner, which is the reason for not adding the banner to the existing e2e coverage. It will be removed in an upcoming M2 update.
- Add new `egressBanner` property to the `GPUv2` flag object
- Add new banner behind flag conditional
**9/30/2024**
> [!IMPORTANT]
> You may want the `gpuv2beta` flag on your account to get the new GPUv2 plans to show up, but it is not a requirement for testing the display of the banner
- Make sure the `gpuv2` flag is on
- Navigate to the Linode Create flow, and verify the following:
- This notice shall be consistent for the entire length of the …

feat: [M3-8581] - GPUv2 Plan Selection Egress Banner

---

packages/manager/.changeset/pr-11010-fixed-1727359551617.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/manager/src/queries/databases/databases.ts
packages/manager/src/queries/databases/requests.ts

Include the platform header in the DBaaS type call
- Include the platform header in the DBaaS type call
9/30/24
| V1 users  | V2 users   |
| 
| 
|
- Managed Databases capability
- Navigate to resize tab
- Type call will include platform header

fix: [UIE-8157] - DBaaS type call requires X-Filter

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/coverage_badge.yml
.github/workflows/coverage_comment.yml
.github/workflows/docs.yml
.github/workflows/e2e_schedule_and_push.yml
.github/workflows/security_scan.yml
packages/manager/.changeset/pr-11009-tech-stories-1727310949305.md

- Updates our Github Actions actions to resolve some depreciation warnings ⚠️ 
- Makes a minor change to how we upload/download `api-v4` and `validation` assets 📦 
- See comment below that explains this in more detail
|  ![Screenshot 2024-09-25 at 8 32 01 PM](https://github.com/user-attachments/assets/e5d9d43b-a3c8-4393-8bb3-14a6954b36f1) | ![Screenshot 2024-09-25 at 8 32 24 PM](https://github.com/user-attachments/assets/9331e0d7-83fe-4f52-a396-a28a9c3353bd) |
| `ci.yml` on develop | `ci.yml` on this PR |
- Visually check the diff for errors 👀 
- Verify Github Actions on this PR pass ✅

chore: [M3-8662] - Update Github Actions actions

---

packages/manager/.changeset/pr-11008-fixed-1727297819528.md
packages/manager/src/session.ts
packages/manager/src/store/authentication/authentication.requests.ts
packages/manager/src/utilities/storage.ts

This PR attempts to reproduce and resolve the CodeQL code scan alerts for `DOM text reinterpreted as HTML`. Alternatively, these alerts might be determined to be false positives and will be dismissed as so.
- The changes proposed by this PR were generated by GitHub's Copilot Autofix feature.
10/16/2024
- Install the CodeQL extension on VSCode
- Install the CodeQL CLI tool using [this guide](https://luisrangelc.medium.com/analyze-vulnerabilities-in-your-code-with-codeql-locally-3e5d31f8ed2)
- Once you reached the **Create a database of your code with CodeQL** step, `cd` into the `src/` directory of the `manager` package and execute the `codeql database create codeqldb --language=javascript` command.
- This is the …

fix: [M3-8424] - Fix CodeQL alerts for `DOM text reinterpreted as HTML`

---

packages/manager/.changeset/pr-11012-added-1727369897345.md
packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.stories.tsx

Add Linode Empty Landing story under `Features/Entity Landing Page/Placeholders/Entities`
- Pull this PR and run Storybook locally, navigate to `Features/Entity Landing Page/Placeholders/Entities`

feat: [M3-8174] - Add Linode Empty Landing story

---

packages/manager/.changeset/pr-11015-tech-stories-1727465775221.md
packages/manager/package.json
packages/manager/src/features/Linodes/LinodeCreatev2/Security.test.tsx
yarn.lock

- Resolves our last dependabot alert https://github.com/linode/manager/security/dependabot/111 🤖 
- Removes `serve` and uses Vite's built-in http server 🌎 
- We use this for serving our bundle when running cypress tests in CI
> [!note]
> We are removing `serve` as a dev dependency to satisfy dependabot but if you even need to use it to serve static HTTP assets, you can always run it with `npx` / `bunx`
> 
> **For example**
> ```
> bunx serve packages/manager/storybook-static
> ```
- Verify our Cypress pipeline works (it serves the local build) ✅

chore: Fix last `path-to-regexp` depenabot alert by using `vite preview` instead of `serve`

---

packages/manager/.changeset/pr-11008-fixed-1727297819528.md
packages/manager/src/session.ts
packages/manager/src/store/authentication/authentication.requests.ts

Reverts linode/manager#11008
This PR introduces a bad bug with redirect behavior. to repro
- navigate to /linodes or any other page than root
- delete `authentication/token` from local storage to be redirected to auth screen
- reload page
- confirm auth
- notice the redirected path contains encoded characters now

Revert "fix: [M3-8424] - Fix CodeQL alerts for `DOM text reinterpreted as HTML`"

---

packages/manager/.changeset/pr-11024-fixed-1727786860656.md
packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/queries/databases/databases.ts

Description 📝
Bug Fix: Landing Page V2 issue for New Beta Users
Changes 🔄
Adjust the UI to send the correct platform field based on the user's account
Target release date 🗓️
10/01/24
Preview 📷
How to test 🧪
Prerequisites
Beta Flag must be enabled, and the user must have the "Managed Databases Beta" account capability.
Verification steps
Go to the Landing Page.
The appropriate Landing Page is displayed based on the User's account type.
As an Author I have considered 🤔
Check all that apply
🧪 …

fix: [UIE-8163] - DBaaS V2 Landing Page platform fix

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx

Reverts the changes from [this PR](https://github.com/linode/manager/pull/10970) to remove the useEffect so that the page doesn't crash. Note that this means there will be a console error again - we'll have to look into how to handle that issue differently.
- Reverts change to remove useEffect
10/2
- On the Linode Storage tab, when clicking 'Add Volume', notice how the page freezes afterwards
- confirm the page freeze no longer happens

fix: Add Volume button on Cloud Manager Linode page causing browser to freeze

---

packages/manager/CHANGELOG.md
packages/manager/src/assets/timezones/timezones.ts
packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx

- Fixes bug preventing users from updating / setting their timezone 🌎 🕐 
- I think this might be a regression from https://github.com/linode/manager/pull/10780
| <video src="https://github.com/user-attachments/assets/f5c3392c-138b-4f02-aa4b-b255a9e9bd58" /> | <video src="https://github.com/user-attachments/assets/24a84f42-9c5e-4899-b8eb-a722de6f00af" /> |
- Checkout this PR or use the preview link
- Verify you can update your timezone on http://localhost:3000/profile/display

fix: [M3-8685] - Users unable to update timezone

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
packages/manager/.changeset/pr-11033-tech-stories-1727816117048.md

Upgrade `upload-artifact@v3` --->  `upload-artifact@v4` and `download-artifact@v3` ---> `download-artifact@v4`
10/14/24
Our Github Actions checks should all pass ✅
There should be no other instances of `upload-artifact@v3` or `download-artifact@v3` in the codebase ✅

chore: [M3-8677] – Upgrade `upload-artifact` and `download-artifact` actions to `v4`

---

packages/manager/.changeset/pr-11031-added-1727814054762.md
packages/manager/cypress/e2e/core/general/account-login-redirect.spec.ts
packages/manager/src/session.ts
packages/manager/src/store/authentication/authentication.requests.ts

This PR attempts to get rid of the following dependabot warning
- https://github.com/linode/manager/security/code-scanning/105
- https://github.com/linode/manager/security/code-scanning/106
- https://github.com/linode/manager/security/code-scanning/107
which I will dismiss if this does not satisfy their uncontrollable urge to report issues that we know to be safe.
It's ok! i used that occasion to add a CY test that checks the proper encoding/decoding of the redirect URL since the last [PR](https://github.com/linode/manager/pull/11008) trying to fix this had to be reverted.
- validate redirect and login URLs via URL constructor
- test encoding/decoding of the redirect URL via CY addition
> [!NOTE]
> This is a smoke verification, since this …

[M3-8424] - Cater to dependabot moods

---

packages/manager/.changeset/pr-11016-tests-1727686556299.md
packages/manager/src/components/CollapsibleTable/CollapsibleRow.test.tsx
packages/manager/src/components/CollapsibleTable/CollapsibleTable.stories.tsx
packages/manager/src/components/CollapsibleTable/CollapsibleTable.test.tsx

Unit test cases for CollapsibleTable and CollapsibleRow components.
- Add unit test cases for CollapsibleTable and CollapsibleRow components.
- Add missing cell from CollapsibleTable story.
N/A
- Run `yarn test CollapsibleTable --reporter verbose` 

test: [M3-8541, M3-8621] - Unit tests for CollapsibleTable and CollapsibleRow components

---

packages/manager/.changeset/pr-11022-added-1727879935382.md
packages/manager/src/features/Domains/DomainRecordDrawer.test.tsx
packages/manager/src/features/Domains/DomainRecordDrawer.tsx
packages/manager/src/features/Domains/DomainRecords.tsx

For A/AAA records we default to the root hostname if left empty or by using `@`, but we do not do the same for TXT record hostnames. Due to this discrepancy, there has been confusion to whether a TXT record for their root domain was applying correctly, or whether the A/AAAA records they were creating would apply to something like `example.com.example.com`.
- TXT has been added as a case in the `shouldResolve`  function
- TXT hostname now defaults to root domain hostname
N/A
https://github.com/user-attachments/assets/8383f622-ed04-474f-b61b-c2e303c2d17b
- Create domain in cloud manager
- Add an A record for that domain leaving the hostname field blank or using @
- Create a TXT record for that domain leaving the hostname field blank or using @
- Notice the difference in "hostname" column …

add: [M3-8630] - Add default root hostname for TXT records

---

packages/manager/.changeset/pr-11041-fixed-1727966039153.md
packages/manager/src/components/Autocomplete/Autocomplete.tsx

A props object containing a "key" prop is being spread into JSX
- Explicitly define 'key' prop instead of spreading
Next release
- Turn on MSW
- Go to Cloud Pulse
- Select a dashboard
- Observe warning in console
- View changes or preview link and observe issue is fixed

fix: [M3-8696] - Explicitly define 'key' prop for Autocomplete instead of spreading

---

packages/manager/.changeset/pr-11046-changed-1727990528328.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx

This PR changes the text copy of the column header on Linodes Configurations table.
- Update the text copy from "Config" to "Configuration"
10/14/2024
| ![Screenshot 2024-10-03 at 2 10 41 PM](https://github.com/user-attachments/assets/72bc1da6-2c38-47a4-9ceb-fa59ee87e9fa) |  ![Screenshot 2024-10-03 at 2 10 23 PM](https://github.com/user-attachments/assets/9bc133d0-e4b3-47c4-ba5e-9484496d0f0a) |
- Visit the "Configurations" tab on any given Linode instance and verify that the table headers reads "Configuration"

change: [M3-6994] - Spell out "Configuration" on Linodes Configurations table

---

packages/manager/.changeset/pr-11036-changed-1727881220211.md
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/utils.test.ts
packages/manager/src/features/components/PlansPanel/utils.ts

Remove the 512 GB plan option from DBaaS
- Only show types returned by the DBaaS backend types API
10/14/24
| ![Screenshot 2024-10-02 at 10 53 16 AM](https://github.com/user-attachments/assets/49e7faec-a1a4-4207-b7b5-129abd655597) | 
|
- "Managed Databases Beta" account capability
- Create a database or navigate to an existing database resize tab
- The 512GB plan is not visible

fix: [UIE-8165] - DBaaS remove 512 GB plan selection

---

packages/manager/.changeset/pr-10941-added-1726492437722.md
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx

As a user, when I click the "Amount" column header, the Billing Activity table should be ordered by the amount column.
Related discussion: https://github.com/linode/manager/pull/9271#discussion_r1232608976
> [!Note]
> We are considering client-side ordering.
- Add client-side ordering by total amount for the "Amount" column.
- Default to ordering by date when no valid 'orderBy' value is provided.
- Change to client-side pagination on the billing activity table.
N/A
- Test with real data or turn MSW 'ON' & set it to `Legacy MSW Handlers`
- Verify that sorting by 'Amount' on the billing activity table works correctly (for both - Invoices and Payments data).
- Verify that the data is ordered by 'date' by default (when no valid 'orderBy' value is …

feat: [M3-6715] - Allow sorting by amount on billing activity table

---

packages/manager/.changeset/pr-11047-upcoming-features-1728307120334.md
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx

Update OBJ Gen2 resource links and fix issue causing test flake.
- `.includes` was causing test flake because the substring could match several options. IE: If looking for `us-10`, it may return `us-1` or even `us-100`. See `M3-8603`
- Added documentation resource links
N/A
Ensure tests pass and links work!

upcoming: [M3-8452, M3-8603] - Add Resource Links & Fix Test Flake

---

packages/manager/.changeset/pr-11050-removed-1728374181106.md
packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx

The dismissible warning banner `Assigned or unassigned Linodes will not take affect until the Linodes are rebooted.`that is displayed when a Linode is either assigned to or unassigned from a VPC subnet can be removed. 
- Removed the dismissible warning banner `Assigned or unassigned Linodes will not take affect until the Linodes are rebooted.` from the VPC Detail page.
14/10 
| ![image](https://github.com/user-attachments/assets/6429c756-dd13-45b8-8856-93bb2b43c112)| ![image](https://github.com/user-attachments/assets/ff7482e6-64cf-4b37-b15c-6878ce3eda54)|
- Navigate to `localhost:3000/vpc/:vpc_id`
- Create a subnet if it is not already present
- Assign a Linode to this subnet
- Verify that the dismissible warning banner is not displayed.
- …

change: [M3-7676] - Remove VPC Details dismissible warning banner

---

packages/manager/.changeset/pr-10937-tech-stories-1728079160083.md
packages/manager/src/dev-tools/load.ts
packages/manager/src/mocks/mockState.ts
packages/manager/src/mocks/presets/baseline/crud.ts
packages/manager/src/mocks/presets/crud/handlers/supportTickets.ts
packages/manager/src/mocks/presets/crud/seeds/index.ts
packages/manager/src/mocks/presets/crud/seeds/supportTickets.ts
packages/manager/src/mocks/presets/crud/supportTickets.ts
packages/manager/src/mocks/types.ts

This PR adds CRUD request handlers and seeding for support tickets to MSW 2.0. 
<details><summary>Mocked Data</summary>
| Mock Request  | Result   |
| `getSupportTickets` | ![Screenshot 2024-09-13 at 2 59 34 PM](https://github.com/user-attachments/assets/96e693ae-2bce-425e-be2e-b6c404bf03bc) |
| `createSupportTicket` and `getSupportTicket` | ![Screenshot 2024-09-13 at 2 42 10 PM](https://github.com/user-attachments/assets/de85e5ab-72cd-4a3e-a5a8-730082f2794d) |
| `createSupportTicketReply` | ![Screenshot 2024-09-13 at 2 48 27 PM](https://github.com/user-attachments/assets/65584705-1185-49df-84fa-f8cb2a9b01ed) |
| events from `createSupportTicket` and `createSupportTicketReply` | ![Screenshot 2024-09-13 at 2 50 …

change: [M3-8583] - Add support ticket mocks to MSW 2.0

---

packages/manager/.changeset/pr-11038-upcoming-features-1727969322447.md
packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.types.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx

- Adds a feature flag that allows us to only show regions with Object Storage capability on the Image Upload page 🌎 
- Image Service Gen2 uses Object Storage as a storage backend, so that's why we use that capability
- We using a flag because we will coordinate with API and let customers know before we make this change 🎏 
- This is part of the Image Service Gen2 effort 💾 
| ![Screenshot 2024-10-02 at 11 35 44 AM](https://github.com/user-attachments/assets/11dffba3-01de-467a-8f3d-6873c825d49f) | ![Screenshot 2024-10-02 at 11 36 06 AM](https://github.com/user-attachments/assets/9263618a-0244-4b82-94cc-9e24115d9d2a) |
- Use Launch Darkly to toggle the flag
- Verify regions get filtered appropriately 
- **Flag Off:**  Should show all core regions
- …

upcoming: [M3-8613] - Restrict Image Upload to regions with Object Storage

---

packages/manager/.changeset/pr-11056-fixed-1728428139880.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx

- Fixes a bug 🐛 preventing users from upgrading their Kubernetes cluster from the Kubernetes landing page ⬆️ 
- I believe the bug was caused by https://github.com/linode/manager/pull/10756 
- Specifically switching `isLoading` ➡️ `isFetching` - see comment for explanation
- Adds Cypress test that would have caught this bug 🧪 
- (the test uses mocked API data)
| <video src="https://github.com/user-attachments/assets/87004463-9c6d-4176-847d-d001e454f79c" /> | <video src="https://github.com/user-attachments/assets/eea9b226-7002-4a12-b4d0-074d858beebf" /> |
- Spin up a Kubernetes cluster that is **not** on the latest version
- Attempt the upgrade flow **on the Kubernetes landing page**
- Observe that when clicking "Upgrade Version", the dialog will …

fix: [M3-8726] - Users unable to upgrade Kubernetes version from landing page

---

packages/manager/.changeset/pr-11065-tech-stories-1728392959296.md
packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
packages/manager/src/features/Linodes/LinodesLanding/TableWrapper.tsx

Removes all redundant `isVLAN` logic from the codebase.
- All instances of `isVLAN` are removed.
- Removed `VLAN IP` table column since the `isVLAN` prop will not exit anymore.
10/14/2024
There are no changes to preview since the direction for this offering shifted. This PR simply removes logic that was left behind.
- Verify that there are no visual regressions in the `LinodesLanding` table.
- Verify that all `isVLAN` logic is removed from the codebase.

chore: [M3-7014] - Remove `isVLAN` code

---

packages/manager/.changeset/pr-11059-added-1728379220045.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/features/Search/SearchLanding.tsx
packages/manager/src/features/Search/refinedSearch.ts
packages/manager/src/features/Search/search.interfaces.ts
packages/manager/src/features/Search/utils.test.ts
packages/manager/src/features/Search/utils.ts
packages/manager/src/features/Search/withStoreSearch.tsx
packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
packages/manager/src/store/selectors/getSearchEntities.ts

Add databases to search result queries.
- Added databases to search result queries.
N/A
- Verify Search functionality for Databases work as expected for Databases enabled users.
- Ensure that the request to `/databases/instances?page_size=500` is not being made or executed for users who are not Databases enabled.

feat: [M3-7011] - Add databases to search result queries

---

scripts/tod-payload/index.ts

Our Heimdall pipeline began failing with the following error message after the v1.129.0 release:
```
+ yarn --silent generate-tod ./packages/manager/cypress/results --appName 'Cloud Manager' --appTeam 'Cloud Manager' --appVersion 1.129.1 --appBuild 7003 --appBuildUrl '(redacted)'
/(redacted)/node_modules/commander/lib/command.js:602
throw new Error(`Cannot add option '${option.flags}'${this._name && ` to command '${this._name}'`} due to conflicting flag '${matchingFlag}'
^
Error: Cannot add option '-t, --tag <str>' to command 'tod-payload' due to conflicting flag '-t'
-  already used by option '-t, --appTeam <str>'
at Command._registerOption ((redacted)/node_modules/commander/lib/command.js:602:13)
at Command.addOption ((redacted)/node_modules/commander/lib/command.js:643:10)
at …
```

test: [M3-8718] - Fix conflicting shorthand flags for TOD script

---

packages/manager/.changeset/pr-11076-tech-stories-1728498604542.md
packages/manager/src/components/BarPercent/BarPercent.tsx

- Improves the TypeScript type-checking performance on the `BarPercent.tsx` component 🏎️ 
| ![Screenshot 2024-10-09 at 1 58 53 PM](https://github.com/user-attachments/assets/24efbd90-2b35-43b1-bfc7-45a1dfa7ac41) | ![Screenshot 2024-10-09 at 1 54 17 PM](https://github.com/user-attachments/assets/a04960f2-72ea-477d-914a-68ec31cf3a17) |
| takes 16 seconds to typecheck | takes 14ms to type check 😦| 
- Verify type checking passes in Github Actions
- Verify there are no regressions with the component, it's types, and it's behavior
- Profile this if you want to (`yarn tsc --generateTrace ./trace --incremental false` and inspect with `chrome://tracing`)

fix: TypeScript performance of `BarPercent.tsx`

---

packages/manager/.changeset/pr-11072-changed-1728479835625.md
packages/manager/src/features/VPCs/VPCLanding/VPCRow.tsx

Here, we are disabling VPC Action buttons when they do not have access or have read-only access.
- Disabled VPC Action buttons (edit, delete)
<video src="https://github.com/user-attachments/assets/59657181-4368-4559-96ae-8a0522521900" controls width="300"></video>
<video src="https://github.com/user-attachments/assets/deecd966-b6c0-4115-85af-d9a6727e4e7a" controls width="300"></video>
- Start with Read Only for everything
- Observe as restricted user: …

feat: [M3-8703] - Disable VPC Action Buttons for Restricted Users

---

packages/manager/.changeset/pr-11079-tech-stories-1728504676937.md
packages/manager/src/hooks/usePendo.ts

After looking at Pendo data to observe what we were collecting, we should better sanitize the data in our URLs with regex that covers more cases (e.g. when the id of the entity was not the last part of the path - `/linodes/12345/storage`; when the entity does not have an id, but a name (buckets)).
10/14
- Follow the instructions here: https://github.com/linode/manager/pull/10982
- Notice in the dev environment that navigating to places like your Linode's storage tab or LKE cluster details page would include IDs  in the normalizedURL because the regex wasn't specific enough.
- Same goes for OBJ details pages - included the region and bucket name. (For example: click on the 'Access' tab.)
- …

fix: Better sanitize Pendo URLs

---

packages/manager/.changeset/pr-11073-fixed-1728472748252.md
packages/manager/src/components/Snackbar/Snackbar.tsx

The close ('X') button on toast notifications is not dismissing the toast in some cases. While most toasts dismiss after 5 seconds so this is not very noticeable, it could pose a problem for any toasts that we do persist (e.g. error toasts) because the toast will be stuck on the page (until refresh).
- Removed `notistackRef` and invoking  `closeSnackbar` method directly within the action prop.
N/A
- Volume creation and the 'Volume scheduled for creation' toast is one example:
- Go to Volumes Create page (https://cloud.linode.com/volumes/create)
- Submit the form.
- Observe the 'Volume scheduled for creation' toast and quickly attempt to dismiss the toast by clicking the 'X'.
- Observe that nothing happens. (Note that the toast does disappear after 5 seconds because it is not persistent.) …

fix: [M3-8052] - Toasts are not consistently dismissible with the 'X' button

---

packages/api-v4/.changeset/pr-11040-changed-1727911382574.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11040-added-1727911099315.md
packages/manager/cypress/e2e/core/databases/resize-database.spec.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/features/components/PlansPanel/types.ts

DBaaS Resize GA
- Added Number of Nodes selector to the Database Resize tab
- The node selection is cleared if they have 2 nodes option selected and try to switch to a plans tab where it is unavailable.
- Updated newly added Node selector so that the plan is cleared if 2 nodes option is selected for a plan that does not have it.
- Updated summary so that both current and resize cluster pricing summaries are displayed for comparison
10/14/24
| ![Before](https://github.com/user-attachments/assets/e8b04cfc-4826-4157-a393-2cf5c120ea30)| ![After](https://github.com/user-attachments/assets/e10f84bf-4fb6-48eb-872d-6bcad414d1af)|
- For testing this change, ensure that DBaaS v2 is …

feat: [UIE-8089] - DBaaS Resize GA

---

packages/api-v4/.changeset/pr-11039-added-1727885059968.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11039-upcoming-features-1727885138241.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/manager/src/features/GlobalNotifications/DatabaseClusterInfoBanner.tsx

DBaaS 2.0 Landing Page GA
- Added Action Menu Column to the Databases Table
- Updated Database Logo (removed Beta)
**Note: The suspend action menu item will be added with the suspend feature in a separate PR.**
10/14/24
| ![Screenshot 2024-10-02 at 5 47 55 PM](https://github.com/user-attachments/assets/fc3b6cc5-4c25-48ae-8aaf-45f99f85cd3f) | ![Screenshot 2024-10-02 at 5 48 24 PM](https://github.com/user-attachments/assets/28c09a24-e8a7-4aeb-b2e6-757776239497) |
| | ![Screenshot 2024-10-02 at 5 48 38 PM](https://github.com/user-attachments/assets/b8422e69-bf28-4133-a95a-506ae61f63a9) |
**Note: For testing this change, ensure that DBaaS v2 is enabled, Beta is turned off, and …

feat: [UIE-8098] - DBaaS 2.0 Landing Page GA

---

packages/manager/.changeset/pr-11069-added-1728443895478.md
packages/manager/.changeset/pr-11069-fixed-1728443895478.md
packages/manager/src/features/Linodes/LinodeCreate/shared/LinodeSelectTable.tsx
packages/manager/src/features/Linodes/LinodeCreate/utilities.ts
packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.test.tsx
packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.utils.test.ts
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.utils.ts
packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
packages/manager/src/utilities/ipUtils.test.ts
packages/manager/src/utilities/ipUtils.ts
packages/validation/.changeset/pr-11069-added-1728444089255.md
packages/validation/.changeset/pr-11069-changed-1728444173048.md
packages/validation/src/nodebalancers.schema.ts

- Updates the NodeBalancer Configuration Node IP Address Select component to show every private IP for each Linode
- Currently, the select component only shows the first private IPv4 for each Linode
- This change also fixes a bug where the select component could display the wrong selected value if the Linode has many private IPv4
- This change helps support the internal _DevCloud_ ☁️  effort
- Adds some unit testing around this component and other private IP utils 🧪 
| ![Screenshot 2024-10-08 at 10 02 41 PM](https://github.com/user-attachments/assets/5a324895-7796-4632-a703-9c38d39f25ea) | ![Screenshot 2024-10-08 at 10 01 45 PM](https://github.com/user-attachments/assets/0f489eca-febd-45f4-bdfb-fbd1cdc5fc5c) |
| Only one private IPv4 is showing …

feat: [M3-8560] - NodeBalancer Configurations - Support Linodes with Multiple Private IPs

---

packages/manager/src/hooks/usePendo.ts

We use an environment variable `PENDO_API_KEY` to load the Pendo agent. Without that API key present, we should not do any set up or loading of Pendo. (We handle Adobe Analytics in the same way -my mistake for missing it here.)
- Adds a conditional check for `PENDO_API_KEY` in the usePendo hook to confirm the env var exists before attempting to load the pendo object on the window or make a request to the CDN for the Pendo agent
- Gets rid of a console error
10/14/24 - this is pointed at the release branch because it needs to be included in the release.
| ![Screenshot 2024-10-10 at 3 39 44 PM](https://github.com/user-attachments/assets/8a19a9df-25f4-4915-832b-725e4a5f53c1) | ![Screenshot 2024-10-10 at 3 41 …

fix: Conditionally check for `PENDO_API_KEY` before Pendo set up

---

packages/manager/.changeset/pr-11084-changed-1728577518914.md
packages/manager/package.json

Small PR to increase the memory allocation for Node.js for vite, TS compiler and storybook
- Increase Node memory allocation (approximately 2GB before, to 4GB) for
- vite
- tsc
- storybook
- run `yarn start` or `yarn up`
- run `yarn storybook`
- make few changes across the codebase, save a bunch of things
- confirm no heap memory allocation in the console

change: [M#-8735] - Increase Cloud Manager `node.js` memory allocation (development jobs)

---

packages/manager/.changeset/pr-11063-added-1728386681970.md
packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx

Here, we are restricting users from creating new VPC from the Landing Page when they do not have access or have read only access.
- Disabled Create VPC Button on the Landing Page
| ![Before](https://github.com/user-attachments/assets/40ed17a1-0c8a-48c9-bc76-01c46e8fb4e4) | ![After](https://github.com/user-attachments/assets/5e61d605-a8bc-47b3-825e-f9b9ad8f8340) |
| 📷 | 📷 |
- Start with Read Only for …

feat: [M3-8703] - Disable Create VPC button with tooltip text on Landing Page for restricted users

---

packages/manager/.changeset/pr-11094-fixed-1728923124356.md
packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx

Here, we are restricting users from creating new Firewalls from the Landing Page when they do not have access or have read only access.
- Disabled Create Firewall Button on the Landing Page
| ![Before](https://github.com/user-attachments/assets/e6119ef7-be53-4125-ae67-af72b1961902) | ![After](https://github.com/user-attachments/assets/16d8da98-8d93-4c43-930f-714cc06d5f13) |
- Start with Read Only for …

feat: [M3-8704] - Disable Create Firewall button with tooltip text on Landing Page for restricted users

---

packages/manager/.changeset/pr-11106-tests-1729028269027.md
packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts

This is a quick fix to get the support ticket `can create an SMTP support ticket` test passing. With today's API release, we introduced a new SMTP Linode capability, and because our test creates a real Linode (which now has this new capability), the SMTP support ticket banner stopped appearing.
This change fixes the test by using a mock Linode that is lacking the SMTP capability. 
- Use mock Linode for SMTP support ticket test
This test is currently failing 100% of the time across all branches, so we can rely on CI for this. The test can be run locally, however, with this command:
```bash
yarn cy:run -s "cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts"
```

test: [M3-8756] - Fix Cypress SMTP support ticket test failure

---

packages/manager/.changeset/pr-11104-tests-1729020207783.md
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSelect.test.tsx

- Attempts to fix the `AppSelect.test.tsx` [test flake we've been seeing](https://github.com/linode/manager/actions/runs/11351685589/job/31573480036?pr=11103) in our code coverage jobs 🔧 
- This flake started to show up when https://github.com/linode/manager/pull/11085 was merged. I don't know exactly why this test got slower. It's annoying, but an increase in timeout should be enough to get is back into a healthy state. 
- We could consider globally increasing async unit test timeout but we should probably discuss the pros and cons of that before we make the change
- Verify test passes locally
- Verify test passes in Github Actions
```
yarn test AppSelect
```

fix: `AppSelect.test.tsx` test flake

---

packages/manager/.changeset/pr-11113-tests-1729099850186.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts

We recently enabled the APL feature flag for development environments which triggered a test failure in `lke-update.spec.ts`. This change fixes the failing test by mocking the `apl` feature flag to be disabled.
- Mock `apl` feature flag to be disabled
- Wrap existing tests in new describe block to signal that the tests apply to LKE with APL disabled
N/A
```bash
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-update.spec.ts"
```

test: Fix LKE update test failure following feature flag update

---

packages/manager/.changeset/pr-11107-tests-1729033939339.md
packages/manager/.changeset/pr-11107-tests-1729036810871.md
packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts

This PR attempts to address a specific trigger of flakiness in the Cypress Placement Group deletion tests, resulting in this failure:
```
CypressError: Timed out retrying after 80050ms: `cy.click()` failed because the page updated while this command was executing. Cypress tried to locate elements based on this query:
(...)
```
Recent improvements to our React Query `useAllLinodesQuery` hook allow components to display cached data while waiting for fresh data to be fetched. In the case of the Placement Group deletion tests, however, this introduced flakiness stemming from re-renders that occur once the HTTP request resolves. This appears to affect the tests only and doesn't impact real users as far as I'm aware.
This works around the React Query behavior by introducing calls to `cy.wait()` …

test: [M3-8744] - Reduce Cypress flakiness in Placement Group deletion tests

---

packages/manager/src/featureFlags.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLogo.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/queries/databases/databases.ts

Allow restricted DBaaS users to access beta
- Allow a restricted user without access to /account but has access to DBaaS to access DBaaS
- Call /types instead of /engines call in order to pass relative filter to check for V1 vs V2 access
- Rename useIsDatabasesEnabled properties for consistency and understandability
10/28/24
| ![Screenshot 2024-10-16 at 1 08 39 PM](https://github.com/user-attachments/assets/66d34489-f1da-4d83-b657-bb9eb7121b38)| ![Screenshot 2024-10-16 at 1 08 26 PM](https://github.com/user-attachments/assets/56df4851-2904-4cd3-ad2e-6fc210e660f3)|
- Restricted user without /account access but has DBaaS access
- Go to create page
- Verify user has access to beta (2 node option)
*Check all …

fix: [UIE-8181] - DBaaS enable restricted beta users

---

packages/manager/.changeset/pr-11105-added-1729023730319.md
packages/manager/src/components/Tabs/TabLinkList.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseMonitor/DatabaseMonitor.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx

Adding Monitor tab to the database details view.
- Added Monitor tab and page to Database Details
- Added ability to include chip for TabLinkList
10/28/24
| ![details-before](https://github.com/user-attachments/assets/78d3f11a-06e8-4f3e-af24-004e5e8c1b89) | ![details-after](https://github.com/user-attachments/assets/1af01145-4922-4b35-82e3-138a2acfeecf) |
- Have dbaasV2MonitorMetrics feature flag enabled and beta as true
- Have new database clusters available
- Navigate to the Databases tab
- Access the details of a new database cluster
- View that the new Monitor tab is displayed with a beta chip
- Click the new monitor tab
- Observe the dashboard …

feat: [UIE-7995] DBaaS Monitor GA

---

packages/manager/.changeset/pr-11090-tech-stories-1728605016946.md
packages/manager/src/mocks/mockState.ts
packages/manager/src/mocks/presets/crud/seeds/utils.ts

This PR fixes an existing bug in the way the MSW2.0 was creating the initial mock store. It made itself known after #10937 was merged because that's the first time that many of us already had an existing store, and now new values were being added to it.
🐛 Bug:
When we are trying to create our initial mock store and access `initialContext.supportReplies` or `initialContext.supportTickets`, developers were encountering a console error and white screen if they *already had an existing IndexedDB* that did not have `supportReplies` or `supportTickets` in the mockStore. This could be worked around by clearing the Application data in the browser console to reset the IndexedDB, but it would continue to happen in the future with every new set of values we track in the store.
❓ Why:
This was …

fix: [M3-8739] - Fix MSW 2.0 initial mock store and support ticket seeder bugs

---

packages/manager/.changeset/pr-11093-fixed-1728898767762.md
packages/manager/src/features/Firewalls/FirewallLanding/FirewallLandingEmptyState.tsx

Here, we are restricting users from creating new Firewalls from the Empty State Landing Page when they do not have access or have read only access.
- Disabled Create Firewalls Button on the Empty Landing Page
|  ![Before](https://github.com/user-attachments/assets/fd3af110-b03b-4ad0-bade-ad5c72a701bf) | ![After](https://github.com/user-attachments/assets/5872496b-03cf-41b8-a5fe-907ba79b097f) |
- Start …

feat: [M3-8704] - Disable Create Firewalls button with tooltip text on empty state Landing Page for restricted users.

---

packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
packages/ui/.changeset/pr-11116-changed-1729114321677.md
packages/ui/src/foundations/themes/index.ts
packages/ui/src/foundations/themes/light.ts

Follow-up to https://github.com/linode/manager/pull/11092 -- move `inputMaxWidth` into `Theme` so we can reference it as `theme.inputMaxWidth` as opposed to exporting & importing the `inputMaxWidth` variable
- Add `inputMaxWidth` to `Theme`
- Replace uses of `inputMaxWidth` variable in components with `theme.inputMaxWidth`
10/28/24
Confirm there are no width regressions for the VPC and Security sections in the Linode Create flow

refactor: [M3-8746] – Move `inputMaxWidth` into `Theme`

---

.github/workflows/coverage.yml
packages/manager/.changeset/pr-11130-fixed-1729536728596.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx

Attempting to fix an annoyance with this test **_only_** failing on the `coverage:summary` job in the CI, resulting a failing step. While this is non blocking, it prevents the coverage job from running and therefore update our score.
It is hard to pinpoint when this started happening, but every PR is experiencing this issue so it needs to be fixed.
I am forcing the  `current_branch` to run, so we can still see if `yarn coverage:summary` actually passes without issues on the current branch in case `base_branch` is flaky
- Improve `DatabaseBackups.test.tsx` test
- force `current_branch` coverage step to run
- run `yarn test DatabaseBackups.test.tsx` and verify it passes
- run `yarn coverage:summary` confirmed no flakes/passes 100%
- confirm coverage > base_branch > `Run Current Branch …

fix: [M3-8763] - fix flaky `DatabaseBackups.test.tsx` in coverage job

---

docs/tooling/analytics.md
packages/manager/.changeset/pr-11122-added-1729183156879.md
packages/manager/src/hooks/usePendo.ts

This PR creates some initial documentation for use of Pendo on Cloud Manager. See the internal doc for more details about access.
- Updated the https://linode.github.io/manager/tooling/analytics.html page of our developer docs
- Page heading is now Analytics; Adobe and Pendo are subheaders
- Section on Pendo has been added
- Updated a comment in the usePendo.js hook to better reflect the usage of the hook
- Read the diff or check out this PR locally and `yarn docs`, then go to http://localhost:5173/manager/tooling/analytics.html#pendo
- Confirm the documentation makes sense and confirm there are no typos.

change: [M3-8509] - Add Pendo documentation to our development guide

---

packages/manager/.changeset/pr-11124-upcoming-features-1729198459249.md
packages/manager/src/components/MultipleIPInput/MultipleIPInput.test.tsx
packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx

DBaaS create encourage users to add IP allow_list
- Access Controls are now wrapped in a radio button group
- User has to explicitly select "None" when adding allow lists
- Add disable prop to MultipleIPInput component to disable all actions with tests
- Refactored the AccessControl from the create page for increased modularity, added tests.
10/28/24
| ![Screenshot 2024-10-17 at 4 23 20 PM](https://github.com/user-attachments/assets/d97b5d0c-5b2d-466d-ab24-2d2d40beb729) | ![Screenshot 2024-10-17 at 4 22 31 PM](https://github.com/user-attachments/assets/13dbc464-157f-468f-b673-70ad65e69a72) | 
| ![Screenshot 2024-10-17 at 4 26 35 PM](https://github.com/user-attachments/assets/db1d5360-6d6e-481b-8eed-9711cd7caa6a)
- Managed Databases account …

feat: [UIE-8196] - DBaaS create encourage users to add IP allow_list

---

packages/manager/.changeset/pr-11120-upcoming-features-1729173753438.md
packages/manager/src/components/Accordion.tsx
packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
packages/manager/src/components/Placeholder/Placeholder.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/components/RegionSelect/RegionSelect.styles.ts
packages/manager/src/components/Tag/Tag.styles.ts
packages/manager/src/components/TagCell/TagCell.tsx
packages/manager/src/dev-tools/Preferences.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/CancelLanding/CancelLanding.tsx
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
packages/manager/src/features/components/PlansPanel/PlanSelection.styles.ts
packages/ui/src/foundations/themes/index.ts
packages/ui/src/foundations/themes/light.ts

Add global colorTokens to the theme and replace one-off hardcoded white color values.
- Global tokens are theme agnostic  and do not require any type merging.
- A follow-up PR will address the replacement of hardcoded black color values with the token.
- Added global `colorTokens` to the theme
- Replaced one-off hardcoded white color values:
- `#fff` and `#ffff` with `theme.colorTokens?.Neutrals.White`
N/A
No visual changes. 
- Ensure No visual changes. 
- Check that all `#fff` and `#ffff` values have been replaced.

upcoming: [M3-8755, M3-6700] - Add global colorTokens to theme and replace one-off hardcoded white colors

---

packages/manager/.changeset/pr-11140-fixed-1729625688555.md
packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/TagCell/AddTag.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/KernelSelect.tsx
packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/LinodeOrIPSelect.tsx
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerSelect.tsx
packages/manager/src/features/PlacementGroups/PlacementGroupTypeSelect.tsx
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Fixes this annoying little bugger when overriding `renderOption` in `AutoComplete`.
It was already fixed when not overriding in https://github.com/linode/manager/pull/11041/files, alas we needed a fix when passing `renderOption`. I did not find it possible to do it from the component so we need to remember to do it every time we declare `renderOptions`. Should be straight forward when implementing a new Autocomplete when checking the console.
- Destructure props for every renderOption instance
- ⚠️ `ImageSelect` is handled [here](https://github.com/linode/manager/pull/11058/files#diff-b1e748ce0fa210ca98b102dbbd16ae5030d118bae8a8422ecfb17584e0c96713R161), not in this PR
- Fix the annoying text selection highlight in Autocomplete 
- Verify that all `<Autocomplete />` …

fix: [M3-8696] - Autocomplete renderOption prop console warning

---

packages/manager/.changeset/pr-11148-fixed-1729687116230.md
packages/manager/src/features/Events/factories/image.tsx

- Removes the `.` we add after the API event message for Image Upload events to fix duplicate punctuation 🔧 
| ![Screenshot 2024-10-23 at 8 20 43 AM](https://github.com/user-attachments/assets/ea3c3367-96dd-42f2-853b-b1c87cdbddc1)  | ![Screenshot 2024-10-23 at 8 31 28 AM](https://github.com/user-attachments/assets/1b221e99-b4d4-4243-9c50-6a54ea3ac31f) |
- Begin uploading an image
- Cancel the upload
- Delete the Image related to the canceled upload
- Observe the toast notification 👁️
https://github.com/user-attachments/assets/ef0b0237-129a-46ce-9ef1-db484caae589

fix: [M3-8773] - Duplicate punctuation on `image_upload` event message

---

packages/manager/.changeset/pr-11131-tests-1729627189739.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/cypress/support/intercepts/lke.ts
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx

Adds tests for updating an LKE cluster's ACL from the summary/details page
Part 1: #10968 
Part 2: #11131
Part 3: #11132 
- tests added:
- Confirming ACL doesn't exist without the corresponding account capability
- Confirming enabling ACL from the summary page (+ updating IPs)
- Confirming disabling ACL from the summary page (+ updating IPs)
- Confirming enabling when ACL is not 'pre-installed'
- Confirming error/validation handling
- add related mock intercepts
- add relevant factories (some files will cause merge conflicts with part 3, #11132  - will fix as needed)
10/28
```
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-update.spec.ts"
```

test: [M3-8725] - Add cypress tests for updating ACL in LKE clusters (LKE ACL integration part 2)

---

packages/manager/.changeset/pr-11149-fixed-1729690586892.md
packages/manager/src/index.css

It does appear global CSS isn't picked up in Safari for `<strong>` and `<b>` tags, resulting in faux bold. This seems to happen systematically during DOM injection
The issue seems to stem from the browser having higher specificity over our global CSS declaration. This PR nests our `strong` & `b` CSS declaration to increase specificity, which seems to fix the problem overall
- Increase CSS specificity for `strong` & `b` for Safari
| ![Screenshot 2024-10-23 at 09 28 17](https://github.com/user-attachments/assets/b78b2bd6-3177-463a-82a1-0a291568128e) | ![Screenshot 2024-10-23 at 09 28 55](https://github.com/user-attachments/assets/89e643b5-abe6-416f-994b-05c438cc0dcb) |
- Pull code and verify fix in notification menu, toast notifications etc
*Check …

fix: [M3-8774 ] - Faux bold in Safari with `<strong />` & `<b />` tags

---

.github/workflows/coverage_comment.yml
packages/manager/.changeset/pr-11161-fixed-1729827835443.md

https://github.com/linode/manager/actions/workflows/coverage_comment.yml?query=is:failure
The "Coverage Comment" GHA depends on the "Code Coverage" workflow to be completed. However that job is designed to not run on draft, so every time a draft gets updates this job fails, because apparently it assumes the job is completed when it never runs.
This flag should fix this and remove some noise when running on drafts.
There unfortunately isn't a way to check this works until this is merged but I have confidence this should do it, and if not we can always do a quick revert
- Add a flag to the "Coverage Comment" GHA to make sure it only runs if the workflow it depends on actually succeeds 

fix: [M3-8788] - Only run coverage comment job on non-drafts

---

packages/manager/.changeset/pr-11147-changed-1729684531663.md
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Backups/BackupSelect.tsx
packages/manager/src/features/Linodes/LinodeCreate/schemas.ts

To get a better understanding of the error Notice when a backup is not selected while creating a Linode v2.
Here, we are adding the error text if a user didn't selected any backup of the Linode for improving validation.
- If backup is not selected:
- error Notice for selecting the backup will shown. 
| ![Before](https://github.com/user-attachments/assets/b84d4270-c8a7-44ab-8173-314b0e7ac3ff) | ![After](https://github.com/user-attachments/assets/900c494d-ed0e-46f9-b2c5-ea0e87fdb3dc) |
- You should have at least one Linode in your account before Reproduction :
- Ensure you are on Linode Create v2.
- Go to the backups tab.
- Select a Linode (do not select a backup).
- Submit the form.
- Observe the error shown in …

change: [M3-8461] - Improve validation error when a backup is not selected.

---

packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx

Some small design changes/feedback for LKE ACL after some additional testing
skipping a changeset since LKE ACL isn't in prod yet
- update copy in Create Cluster cc @mjac0bs 
- Remove placeholders from IP fields
- Change notice position in drawer for LKE clusters without ACL pre-'installed'
- Update corresponding tests
NOTE: when this gets merged back to develop, lke-create.spec.ts tests will fail >> will update that after!
10/28 🙏 
| ![image](https://github.com/user-attachments/assets/91dd5799-ffde-4abf-9b20-c0f60efec0fc) ![image](https://github.com/user-attachments/assets/14032384-e504-4bfb-829c-6ad6ce1d0414) | ![image](https://github.com/user-attachments/assets/683179b8-3106-4827-bccc-a45616e42b0d) …

change: LKE ACL copy and placeholder updates

---

packages/api-v4/.changeset/pr-11157-tech-stories-1729787265807.md
packages/api-v4/package.json
packages/manager/.changeset/pr-11157-tech-stories-1729787405590.md
packages/manager/cypress/support/plugins/discard-passed-test-recordings.ts
packages/manager/package.json
packages/manager/src/hooks/useInterval.tsx
packages/ui/.changeset/pr-11157-tech-stories-1729787461166.md
packages/ui/package.json
packages/validation/.changeset/pr-11157-tech-stories-1729787428923.md
packages/validation/package.json
yarn.lock

- Follow up PR for https://github.com/linode/manager/pull/10866
- This PR updates our `@types/node` version to match our Node.js version 📦  It seems to not have been kept up to date
- Removes `@types/node` from our packages that don't need Node.js types 🧹 
- Verify all type-checking passes ✅ 
- Check for regressions in files that were touched 👁️

chore: [M3-8786] - Update and clean up `@types/node` package

---

packages/manager/.changeset/pr-11176-tests-1730144406169.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx

Fixes test failures for lke-create.spec.ts and takes care of [m3-8776] while at it
- fix lke-create.spec.ts test failures that were introduced bc of #11173 
- create unit tests for the drawer and control pane to check for copy-related stuff and declutter cypress tests 
- omit prop from DOM from change in #11173 as well 😅 
11/12
```
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-update.spec.ts"
```
```
```
```
yarn test KubeControlPaneACLDrawer  
```
```
yarn test ControlPlaneACLPane    
```

test: [M3-8776] - Fix lke-create tests and create unit tests for LKE ACL

---

packages/manager/.changeset/pr-11165-upcoming-features-1729872623442.md
packages/manager/src/GoTo.tsx
packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
packages/manager/src/components/ColorPalette/ColorPalette.tsx
packages/manager/src/components/Drawer.tsx
packages/manager/src/components/EnhancedSelect/Select.styles.ts
packages/manager/src/components/ImageSelect/ImageOption.tsx
packages/manager/src/components/MainContentBanner.tsx
packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
packages/manager/src/components/Notice/Notice.styles.ts
packages/manager/src/components/Placeholder/Placeholder.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
packages/manager/src/components/ShowMore/ShowMore.tsx
packages/manager/src/components/Tag/Tag.styles.ts
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Databases/DatabaseCreate/EngineOption.tsx
packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppDetailDrawer.tsx
packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.styles.ts
packages/manager/src/features/TopMenu/TopMenu.tsx
packages/ui/src/foundations/themes/light.ts

- Follow up to the PR: #11120 
- Replace one-off hardcoded neutral black and white color values with the `colorTokens`.
- `colorTokens` are global tokens, and they are theme-agnostic.
> [!Note]
> `theme.colorTokens.Neutrals.Black` is pitch black (`"#232326"`) in design tokens 
- Replaced `#000` or `black` with ` theme.colorTokens.Neutrals.Black` (`"#232326"`)
- Replaced `#fff` or `white` with `theme.colorTokens.Neutrals.White`
N/A
- No visual changes for white color
- `#000` or `black` is now pitch black (`"#232326"`) as per neutral black design color token 

upcoming: [M3-6700] - Replace one-off hardcoded black and white color values with colorTokens

---

packages/manager/.changeset/pr-11182-fixed-1730212323309.md
packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx

Fix the display of host in DBaaS summary details
- Remove MongoDB related code as it is no longer supported
- Correctly show primary host in details
11/12/24
| ![alpha](https://github.com/user-attachments/assets/db67e35b-e041-4d0c-9ea3-83c076118e77) | ![fix](https://github.com/user-attachments/assets/7e35a2cd-f465-4946-9beb-df5b908a4690) |
- Managed Databases Beta capability
- dbaasV2 feature flag
- Navigate to database summary details page
- Host is displayed

fix: [UIE-8007] - DBaaS display host in summary details

---

packages/manager/.changeset/pr-11188-added-1730298408749.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
packages/manager/src/features/Linodes/LinodeCreate/VPC/VPC.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/VPCPanel.tsx
packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.test.tsx
packages/manager/src/features/VPCs/VPCCreateDrawer/VPCCreateDrawer.tsx
packages/manager/src/hooks/useCreateVPC.ts

- Cleans up old VPC code related to Linode Create v1 🧹 
- Preselects the VPC **and the subnet** when creating the VPC while on the Linode Create flow ⌨️ ✨ 
- Previously, the VPC would only preselect. This PR makes it so the subnet also gets selected
- Preselects a VPC's subnet if the user picks a VPC with only one subnet  ✨ 
| <video src="https://github.com/user-attachments/assets/d138a2d5-6082-4368-92ff-dc9c57a71854" /> | <video src="https://github.com/user-attachments/assets/fd7a94d6-b220-4c98-b4b4-4c31e71cd354" /> |
- Go to the Linode Create flow
- Test the VPC section of the form 🧪
- Verify both the VPC and subnet get preselected when you uses the Create VPC drawer to create a VPC
- Verify error field handling works as …

change: [M3-8807] - Improve Linode Create VPC user experience

---

packages/manager/.changeset/pr-11190-tests-1730312266172.md
packages/manager/cypress/e2e/core/databases/resize-database.spec.ts

We've been seeing DBaaS resize test failures on every test run as a result of a DBaaS feature flag change earlier today. Since this feature flag will be enabled more often as testing continues, this PR seeks to make the test pass regardless of the value of the flag.
It does this by removing an assertion that's only relevant when the feature flag is disabled. The DBaaS team is invited to refactor these tests if this assertion is crucial, but otherwise we'll proceed with this as a quick fix.
Remove assertion to allow DBaaS resize tests to pass regardless of state of v2 feature flag.
We can rely on CI for this, but you're welcome to run the test locally as well.

test: [M3-8810] - Fix DBaaS failures when v2 feature flag is enabled

---

packages/manager/.changeset/pr-11166-changed-1729892043474.md
packages/manager/cypress/e2e/core/databases/resize-database.spec.ts
packages/manager/cypress/e2e/core/databases/update-database.spec.ts
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.test.tsx

Updating text for database settings
- Updating Settings text and labels
11/12/2024
| ![Before-DB-settings-update](https://github.com/user-attachments/assets/a6e1cb3b-3823-4d27-af6b-f245e49a7b73) | ![After-DB-settings](https://github.com/user-attachments/assets/ec5ee0e1-c8f5-44f0-9616-f82c9d8715ff) |
- Have access to databases to view database settings tab
- Access database settings and view updated text
```
yarn test DatabaseSummary DatabaseSettings AccessControls AddAccessControlDrawer
```

change: [UIE-8220] - Settings text update

---

packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/APLSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/utils.ts

Minor textual changes for APL feature
- Doc links have been changed from old/placeholders to new documentation pages . 
- APL Acronym removed from public facing text.
- Node pool threshold for APL now checks for vcpu as well. 
11/12

[APL-336] - Minor textual changes for APL feature

---

packages/api-v4/.changeset/pr-11196-upcoming-features-1730465602676.md
packages/api-v4/src/databases/databases.ts
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11196-upcoming-features-1730465663102.md
packages/manager/src/factories/databases.ts
packages/manager/src/queries/databases/databases.ts

DBaaS Upgrades and Maintenance 1 of 4
- Add API to apply security patches (outside maintenance window)
- Refactor database types (alphabetize properties, annotate with JS docs deprecatations and new properties
- Add query for new API
- Add mock data for new properties to factory
11/12/24

feat: [UIE-8194] - DBaaS Upgrades and Maintenance 1

---

packages/manager/.changeset/pr-11198-upcoming-features-1730465952580.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenance.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenance.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsReviewUpdatesDialog.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsReviewUpdatesDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsUpgradeVersionDialog.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsUpgradeVersionDialog.tsx
packages/manager/src/features/Databases/DatabaseEngineVersion.test.tsx
packages/manager/src/features/Databases/DatabaseEngineVersion.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts

DBaaS Upgrades and Maintenance 1 of 4
- Create new Maintenance component that will display in the /settings tab and handle opening modals for Upgrades and Starting updates
- Create dialogs for Upgrading a version and Reviewing and applying maintenance/security patches
11/12/24
- Unit tests
- [] 🚩 Using a feature flag to protect the release

feat: [UIE-8194] - DBaaS major and minor upgrades 3

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/APLSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/utils.ts
packages/manager/src/queries/account/betas.ts
packages/manager/src/queries/kubernetes.ts

There is some unusual behaviour on the staging cluster while testing the APL component on the cluster overview page. It's hard to explain but it seems that only one APL component my exist at the same time and when you refresh the page it disappears and 'moves' to another cluster. This is quite an urgent thing as users cannot consistently go to the APL console like this.
See relevant Slack channel
- Make sure that APL feature flag is enabled and user is enrolled in beta
- Create cluster with APL enabled set to true 
- Go to cluster overview page
- When reloading a few times, observe  that APL Summary component is loaded inconsistent. 
**TO BE TESTED ON ALPHA**
It is expected for the APL summary panel to show 'Installation still in progress; please check back in a minute.' on alpha, as …

hotfix: [APL-343] - APL summary panel is not being loaded in staging 

---

packages/manager/.changeset/pr-11211-tech-stories-1730836470267.md
packages/manager/src/hooks/usePendo.test.ts
packages/manager/src/hooks/usePendo.ts

This ticket provides test coverage and corrects two discovered issues with the original URL transforms for Pendo page views:
- `id`s were replaced once, not globally, which would not account for urls with multiple ids (this is rare, but does exist in CM)
- early returns would not apply all needed transforms to the url if multiple were needed
- Created the `transformUrl` function and better documented the purpose of transforms
- Created the `usePendo.test.tsx` file to test `transformUrl()`
11/12/24
Run
``` 
yarn test usePendo
```
and confirm test cases provide full coverage of different possible urls and that the tests pass reliably.

fix, test: [M3-8830] - Use unit tested function for Pendo url transformation

---

packages/manager/.changeset/pr-11199-upcoming-features-1730465428837.md
packages/manager/src/features/Databases/DatabaseCreate/utilities.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx

DBaaS Upgrades and Maintenance 4 of 4
- Integration of components into settings, create, resize, landing, summary
11/12/24
- Managed Databases
- dbaasV2 feature flag set for GA
- Default DB created e.g. postgresql 13
- Verify you can upgrade to postgresql 14, 15, 16
- View maintenance

feat: [UIE-8194] - DBaaS Upgrades and Maintenance 4

---

packages/manager/.changeset/pr-11209-added-1730788980490.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
packages/manager/src/components/TableCell/TableCell.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/components/PlansPanel/PlanContainer.styles.ts
packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx
packages/manager/src/mocks/serverHandlers.ts

Small PR to implement conditional display of contextual help (banner + tooltip) of the new GPU ada plan split table.
**Context**: API will start returning `0` as trasnfer value for Ada plans
- Fix the potential display of the `0` transfer value in the PlanSelection GPU panel
- `0` being falsy, it would display empty in the table
- `0` `plan.transfer` was also being filtered wrongly in `PlanContainer`
- Add a new `showTransferBanner` boolean property to the `gpuv2` feature flag
- Add a Banner to the GPU plan selection panel
- Add a tooltip to the GPU transfer table header
- Add MSW data for helping review
- Adjust e2e smokes
⚠️  **11/12/2024**
LD flag variations for reference:
- best to verify is using MSW legacy:
- displays 0 as expected
- features the new egress transfer banner
- …

feat: [M3-8831] - New GPUv2 egress transfer display

---

packages/api-v4/.changeset/pr-11218-removed-1730922731323.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11218-fixed-1730922753813.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseClusterData.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/mocks/serverHandlers.ts
packages/validation/src/databases.schema.ts

Allow users to create 2 node clusters
- Remove deprecated MongoDB and Redis (not supported)
- Modify createDatabaseSchema, deprecated fields no longer required
- Modify DatabaseCreate to conditionally set deprecated fields
11/12/24
- dbaasV2 feature flag set to GA
- Try to create a two node cluster
- You can successfully create two node clusters

fix: [UIE-8246] - DBaaS provisioning 2 node clusters

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx

Conditionally give the new docs as the link on database landing page
- If the user has access, the new documentation link is used, otherwise the old link is used
11/12/24
- dbaasV2 feature flag set to GA
- Navigate to the Database landing page
- Click on the "Docs" link
- 
- [ x] 👀 Doing a self review

change: [UIE-8247] - Conditionally give the new docs as the link on database landing page

---

packages/manager/.changeset/pr-11225-upcoming-features-1730983728586.md
packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx

When the charts of ACLP for DBaaS has multiple dimensions some of the timestamps are missing across dimensions and charts are plotted wrong. Fixed by adding missing timestamps across dimensions with null value
1. Identify missing timestamps across dimensions data and add null value for those in each dimension
12-11-2024
| Hover showing two data for gapped plots | Hover showing correct data |
|----|----|
|![Screenshot 2024-11-07 at 6 04 58 PM](https://github.com/user-attachments/assets/7ba30cb1-d87d-4cfd-9a73-bbc9a046ab15)|![Screenshot 2024-11-07 at 6 05 14 PM](https://github.com/user-attachments/assets/620aa395-f14e-4e51-be7e-6cb2e77b4b0d)|
1. Login a mock user
2. Navigate to monitor page
3. Select dashboard and required filters
4. Even after post …

upcoming: [DI-21811] - Post processing of missing timestamp data across dimensions in ACLP charts

---

packages/manager/.changeset/pr-11226-upcoming-features-1730990421121.md
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx

Added one new filter - orderFilter for fetching instances in dbass servictype.
- In our resource selection component, OrderFilter is added into the request for fetching databases instances in dbass serviceType. 
12-11-2024
| ![image](https://github.com/user-attachments/assets/307c745b-d2ef-4b93-9625-967c7a182d58) | ![image](https://github.com/user-attachments/assets/e50d7c6f-f950-4216-8e59-851cf582aa4d) |
1. Login as a mock user.
2. Navigate to monitor tab.
3. Select a DBasS dashboard.
4. Open inspect, later select all the filters.
5. In networks tab, go to database instance api call, you should be able to see order_by filter in headers.

upcoming: [DI-21814] - ACLP UI - DBaaS instances order by label

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Add a tooltip for Host on the Connection Details screen.
- Added the tooltip.
11/12/2024
|  ![Screenshot 2024-11-07 at 2 59 08 PM](https://github.com/user-attachments/assets/4d070f7f-ad72-4b05-8ab7-951a9e54f7ca) | ![Screenshot 2024-11-07 at 2 58 10 PM](https://github.com/user-attachments/assets/8977a017-a2cf-419e-91e9-5a659242e8d4) |
- Navigate to Database Landing page and view connection details
- [ x] 👀 Doing a self review
- [ x] ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md)
- [ x] 🤏 Splitting feature into small PRs

change: [UIE-8254] - Add tooltip for ipv6 for new db clusters

---

packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/components/TooltipIcon.tsx
packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx

Tooltip for Create/Resize Database table
This PR is pointing to the release branch. See the original PR here for context on changes made: https://github.com/linode/manager/pull/11223.
- Added 'Usable Storage' with tooltip to the Create/Resize Database Table
- Added text note about 'Usable Storage' for smaller screen sizes
11/12/24
| ![Screenshot 2024-11-07 at 12 44 11 PM](https://github.com/user-attachments/assets/24206dd8-781a-4ea2-b08c-a3562e9a4953) | ![Screenshot 2024-11-07 at 12 44 41 PM](https://github.com/user-attachments/assets/fcc55b50-90ca-4cc4-aec5-719c346bc979) |
- dbaasV2 feature flag set to GA
- …

feat: [UIE-8193] - Usable Storage Tooltip for Create/Resize Database table

---

packages/manager/.changeset/pr-11223-added-1730985113933.md
packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/components/TooltipIcon.tsx
packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx

Tooltip for Create/Resize Database table
- Added 'Usable Storage' with tooltip to the Create/Resize Database Table.
11/12/24
| ![Screenshot 2024-11-07 at 12 44 11 PM](https://github.com/user-attachments/assets/86eabbb1-03f7-4d1b-be74-6cbf11dfd5a6) | ![Screenshot 2024-11-07 at 12 44 41 PM](https://github.com/user-attachments/assets/43dd99a9-b4be-44a5-b8eb-7e31cc1c4bb1) |
- dbaasV2 feature flag set to GA
- Navigate to the Create Database Cluster page
- Navigate to the Resize Database Tab

feat: [UIE-8193] - Tooltip for Create/Resize Database table

---

packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
packages/manager/src/features/components/PlansPanel/PlanSelectionTable.tsx

Tiny copy change for the upcoming release. Amends  https://github.com/linode/manager/pull/11209
Not having a changeset since the PR mentioned above is part of this release
- Remove "standard" from both the egress banner and the table tooltip 
⚠️ 11/12/2024
- Check the GPU tab of the plan selection in the Linode create flow

change: [M3-8866] - GPU egress transfer copy update

---

docs/development-guide/08-testing.md
packages/manager/.changeset/pr-11221-changed-1731086980327.md
packages/manager/src/components/CopyTooltip/CopyTooltip.test.tsx

Our current unit test example (https://linode.github.io/manager/development-guide/08-testing.html#unit-tests) uses fireEvent, when best practice recommended by React Testing Library is to use userEvent, unless the situation does not allow it.
From the [docs](https://testing-library.com/docs/user-event/intro):
> user-event allows you to describe a user interaction instead of a concrete event. It adds visibility and interactability checks along the way and manipulates the DOM just like a user interaction in the browser would. It factors in that the browser e.g. wouldn't let a user click a hidden element or type in a disabled text box.
This is [why you should use user-event](https://ph-fritsche.github.io/blog/post/why-userevent) to test interaction with your components.
> There are, however, …

change: [M3-8860] - Update unit testing docs to prefer `userEvent` over `fireEvent`

---

packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts

Quick fix to a few tests in `lke-create.spec.ts` to coincide with the change made by #11234, which disabled the ACL toggle by default on the LKE create page.
I don't believe any changeset is needed for this PR since it's a quick follow-up to #11234, which hasn't been released yet.
- Update ACL tests in `lke-create.spec.ts` to account for the ACL default change
This is meant for v1.32.0 (2024-11-12), but it's not absolutely crucial since there's no underlying bug and we have a good understanding of why the tests are failing. Still, it would be nice to get this merged for the release if we can
This test has a 100% failure rate. You can reproduce by checking out the `release-v1.132.0` test, building Cloud, and running the `lke-create.spec.ts` tests, and confirm that this fixes it by …

test: [LKEAPIFW-529] - Update LKE create tests for ACL defaults change

---

packages/manager/src/components/TextField.tsx

Fix styling for textfield on profile/display page as well as other sx bugs
| ![image](https://github.com/user-attachments/assets/15d751ce-5be9-472b-93ee-4fdbba54238b) | ![image](https://github.com/user-attachments/assets/2099a5c8-6e1a-450b-b55f-325e46788aa3) |
Confirm textfield styling looks the same as prod:
- profile/display
Confirm textfield styling looks the same for places that have containerProps
- LinodeCreate - vlan, vpc (** VPC has slight regression that wasn't fixed by this change, looking into it)
- AppSelect
- general check where textfield is used everywhere

fix: sx styling for Textfield component

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
packages/manager/src/queries/types.ts

- Fixes a crash on the Linode Create flow when selecting a Linode to clone from when the Linode's `type` is `null`
- See [this](https://linode.slack.com/archives/C4V05M8TS/p1731403292097249) for context
This PR ensures that `useTypeQuery` is only enabled if the type ID is truthy (not an empty string).  If the query gets enabled with an empty string, it would fetch `/v4/linode/types/`, which would unexpectedly store a paginated list of types in the cache where we expect a type object.
- View the internal ticket M3-8894
- Login as that customer
- Copy that Admin bearer token to your local Cloud Manager
- Test this PR with the Linode mentioned in the internal ticket

fix: [M3-8894] - Linode Create crash when selected a Linode with a `type` that is `null`

---

docs/PULL_REQUEST_TEMPLATE.md
packages/manager/.changeset/pr-11236-tech-stories-1731104032752.md

As developers, we want to provide better clarity to our PR template.
- Turn Author consideration checklist to bullets
- Add Author confirmation checklist of technical requirements before marking a PR as Open
- Read the diff and self review.

change: [M3-8857] - Update PULL_REQUEST_TEMPLATE (Part 2)

---

packages/manager/.changeset/pr-11238-tests-1731115121832.md
packages/manager/cypress/e2e/core/databases/resize-database.spec.ts

This fixes a few flaky tests in `resize-database.spec.ts` that fail on their first attempt and succeed on their second.
I believe this was caused by recent changes to our `databaseFactory`'s `platform` field. Because the Cypress tests pre-date that field, it inherits the default value from the factory, which is always set to `'rdbms_default'` on the first test attempt and `'rdbms_legacy'` on the second attempt.
Because the new DBaaS v2 changes introduce a couple changes to the resize flow, the tests fail when the value is set to `'rdbms_default'`, so this PR resolves the test by ensuring the mock database's `platform` is `'rdbms_legacy'`.
- Set mock database platform field to `'rdbms_legacy'`
N/A
```typescript
yarn cy:run -s "cypress/e2e/core/databases/resize-database.spec.ts"
```
*Check …

test: [M3-8890] - Fix flaky DBaaS resize test related to recent factory changes

---

packages/api-v4/.changeset/pr-11146-added-1729681812578.md
packages/api-v4/src/iam/iam.ts
packages/api-v4/src/iam/index.ts
packages/api-v4/src/iam/types.ts
packages/api-v4/src/index.ts
packages/manager/.changeset/pr-11146-added-1729681889703.md
packages/manager/src/factories/userPermissions.ts
packages/manager/src/queries/iam/iam.ts
packages/manager/src/queries/iam/queries.ts

IAM RBAC - new api for user permissions
- Added new api for User Permissions
- No visible changes
Nov 12, 2024 (dev)

feat: [UIE-8129] - IAM RBAC add new user permissions api

---

packages/manager/.changeset/pr-11252-upcoming-features-1731490251541.md
packages/manager/src/featureFlags.ts
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx

Introduction of configurable Max limit on resource selection component and other enhancements.
1. SELECT_ALL option in resources list component will not be available if number of resources are higher than the maximum resources selection limit set in launchDarkly.
2. In resource selection autocomplete, user will be able to select resources up to maximum resource selection limit, all other resources(options) will be disabled after reaching this limit.
3. Text 'Select up to `limit` `label`' is introduced under resource selection autocomplete.
12-12-2024
| ![image](https://github.com/user-attachments/assets/0a128b6e-8ee8-488f-b4b7-f20fed1c78fc) | ![image](https://github.com/user-attachments/assets/dcc1a334-84a3-41e6-92b6-bc181464451c) |
| …

upcoming: [DI-20934] - Configurable Max limit on resource selection component

---

packages/manager/.changeset/pr-11241-tech-stories-1731391925729.md
packages/manager/.changeset/pr-11241-upcoming-features-1731391925729.md
packages/manager/src/assets/icons/monitor-disabled.svg
packages/manager/src/assets/icons/toggleOff.svg
packages/manager/src/components/AreaChart/AreaChart.tsx
packages/manager/src/components/Checkbox.tsx
packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
packages/manager/src/components/Dialog/Dialog.tsx
packages/manager/src/components/EnhancedSelect/Select.styles.ts
packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/components/PasswordInput/StrengthIndicator.tsx
packages/manager/src/components/Placeholder/Placeholder.tsx
packages/manager/src/components/Tag/Tag.styles.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.style.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
packages/manager/src/features/Events/FormattedEventMessage.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/HostNamesList.tsx
packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.styles.ts
packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts
packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
packages/manager/src/features/TopMenu/TopMenu.tsx
packages/manager/src/features/TopMenu/TopMenuTooltip.tsx
packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
packages/ui/src/components/Notice/Notice.styles.ts
packages/ui/src/foundations/themes/light.ts

- Replace one-off hardcoded color values with color tokens - Part 3
- colorTokens are global tokens, and they are theme-agnostic.
> [!Note]
> The new colors are based on design tokens and have been selected to closely match the existing colors.
Related PRs: 
- https://github.com/linode/manager/pull/11120
- https://github.com/linode/manager/pull/11165
- Replaced `pink` with `theme.tokens.color.Pink[40]` (#f3c6e2)
- Replaced `#e3e5e8` with `theme.tokens.color.Neutrals[20]` and its equivalent color (#E5E5EA) in `monitor-disabled.svg` 
- Replaced `#2e3238` with `theme.tokens.color.Neutrals[100]` (#343438)
- Replaced `#c9c7c7` with `theme.tokens.color.Neutrals[40]` (#c2c2ca)
- Replaced `#606469` with `theme.tokens.color.Neutrals[70]` (#696970)
- Replaced `#555` with …

refactor: [M3-8898] - Replace one-off hardcoded color values with color tokens pt3

---

packages/manager/.changeset/pr-11240-added-1731323233092.md
packages/manager/src/features/GlobalNotifications/CreditCardExpiredBanner.tsx
packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx

Add a Credit Card Expired banner for accounts with expired credit cards
- Implemented the banner
- Turn on MSW
- Verify that the banner is visible

feat: [M3-8682] - Add 'Credit Card Expired' banner

---

packages/manager/.changeset/pr-11265-fixed-1731619488790.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Fixing DBaaS summary so that when the read-only host field is displayed and backend does not return a read-only host., N/A is displayed
When read-only host field has no value (secondary/standby), it displays N/A
12/10/2024
| ![summary-before](https://github.com/user-attachments/assets/d291b0c0-9270-42fa-849f-c75556c9c6dd) | ![summary-after](https://github.com/user-attachments/assets/cb49ac81-7991-4122-88c1-ccea010708ba) |
- Create a new database with 1 node which provides this state where the backend does not return a read-only host.
- Create a new database with 1 node.
- Navigate to the database summary and view the empty read-only host field
- Navigate to the summary new db with 1 node and see that N/A is displayed for read-only hosts field …

fix: [UIE-8259] dbaas summary blank read-only host should be N/A

---

packages/manager/.changeset/pr-11109-fixed-1729070494828.md
packages/manager/.changeset/pr-11127-changed-1729515938754.md
packages/manager/.changeset/pr-11127-fixed-1729515738287.md
packages/manager/.changeset/pr-11127-fixed-1730275015638.md
packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
packages/manager/package.json
packages/manager/src/components/Table/Table.styles.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.styles.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/utilities/CustomKeyboardSensor.ts
yarn.lock

While working on ticket M3-8533 & PR #11109, we decided to implement/use semantic markup for the Firewall rules table to improve consistency and accessibility, rather than applying a styling band-aid to div grids to make it look like our normal tables. The `react-beautiful-dnd` library has made us rely on div(Box) grids instead of our normal tables, which complicates using semantic tables/grid layouts because of the draggable elements. Plus, this library has been deprecated (announcement: https://github.com/atlassian/react-beautiful-dnd/issues/2672).
To solve these problems and make better use of our normal tables, switching to `dnd-kit`(https://dndkit.com/) would be the great idea, which is more popular, supports grid layouts better, and can replace `react-beautiful-dnd`. This will help …

change: [M3-8533, M3-8761] - Fix firewall rules table and Replace `react-beautiful-dnd` with `dnd-kit` lib

---

packages/manager/.changeset/pr-11262-changed-1731701027804.md
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingEmptyStateData.tsx

Update doc links on Database landing page empty state
- Updated doc links
12/2024
- The `showEmpty` case needs to be true, which can be manually set in a local env, but which will also be true if there are no new or legacy databases
- The documentation links are on the page that is presented when there are no databases present - i.e. if you see a table of databases, you won't see these links
- Visit the links to see if they go to the new locations
- 🔐 Removing all sensitive …

change: [UIE-8261] - Update doc links on db landing page empty state

---

packages/api-v4/.changeset/pr-11256-added-1731689702399.md
packages/api-v4/src/account/types.ts
packages/api-v4/src/linodes/actions.ts
packages/api-v4/src/linodes/types.ts
packages/api-v4/src/regions/types.ts
packages/manager/.changeset/pr-11256-changed-1731689770913.md
packages/manager/src/__data__/linodes.ts
packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx
packages/manager/src/factories/account.ts
packages/manager/src/factories/linodes.ts
packages/manager/src/factories/types.ts
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/utils.test.ts
packages/manager/src/features/components/PlansPanel/utils.ts
packages/manager/src/mocks/serverHandlers.ts

Updates api types and mocks data so that Accelerated plans show up when using MSW
Accelerated plans will be hidden behind an account capability - we currently do not plan to use a feature flag
- introduce new account and region capability
- update types and fix type errors
- add Accelerated mock data so that tab shows up
12/10
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive …

feat: [M3-8833] - Update API types and mock data for VPU plans

---

packages/manager/.changeset/pr-11274-tests-1731956375334.md
packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts

This fixes a consistent test failure in `migrate-linode.spec.ts` that was triggered by the launch of Frankfurt 2 earlier today. 
The test attempts to confirm that users cannot migrate a Linode to the same region the Linode exists in. It does this by typing the Frankfurt region's label into the autocomplete and asserting that there are no results, and the launch of Frankfurt 2 triggered the failure because the "No results" message no longer appears.
This fixes the issue by searching for the region by ID, circumventing the label conflicts altogether.
- Rework region assertions to prevent region label conflicts from causing test failures
- Remove calls to deprecated helpers `fbtClick` and `getClick`
N/A.
Build and serve Cloud, then run the migrate tests:
```bash
yarn cy:run -s …
```

test: [M3-8919] - Fix Linode migration test failure caused by region label conflict

---

packages/manager/.changeset/pr-11272-tests-1731954049354.md
packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts

Quick little fix to unskip a Placement Group nav test caused by a stray `.only`. No real urgency or significance to this, just noticed it earlier today during DC testing.
- Unskip `can navigate to Placement Groups landing page` PG nav test by removing `.only` on other test
N/A
Run and build Cloud via `yarn && yarn build && yarn start:manager:ci`, then run the Placement Group navigation tests via:
```
yarn cy:run -s "cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts"
```
Observe:
Run and build Cloud, then run the Placement Group navigation tests and observe:
- ➕ Adding a …

test: Unskip Placement Group navigation test by removing `.only`

---

packages/manager/.changeset/pr-11282-changed-1732019056361.md
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenance.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsUpgradeVersionDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx

DBaaS GA: UI update, bug fix.
- Database Settings: Changed the button style from primary to outlined for Suspend Cluster, Manage Access Controls, Reset Root Password, and Delete Cluster
- Database Settings > Maintenance: Updated UI
- Version Upgrade > Popup dialog: Updated the text to display the correct instance name
- Database Summary: Updated the UI to prevent text wrapping for the "Engine" value
- Database Summary > Connection Details: Added 'Database name' field
- Database Landing Page:  Disabled all features except resume and delete when database is either in suspended or in suspending (state)
- Database Settings refactoring
12/10/24
| ![Screenshot 2024-11-19 at 1 03 49 PM](https://github.com/user-attachments/assets/3be61f66-47e2-4e9b-bb5e- …

change: [UIE-8253] - DBaaS GA: UI update, bug fix

---

packages/api-v4/.changeset/pr-11259-upcoming-features-1731690339160.md
packages/api-v4/src/account/account.ts
packages/api-v4/src/account/types.ts
packages/manager/.changeset/pr-11259-upcoming-features-1731690367042.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/mocks/presets/extra/account/lkeEnterpriseEnabled.ts
packages/manager/src/mocks/presets/index.ts
packages/manager/src/mocks/types.ts
packages/manager/src/queries/account/account.ts
packages/manager/src/queries/account/queries.ts

We will need a feature flag in Launch Darkly to gate access to the UI changes for LKE-Enterprise. 
- The `lkeEnterprise` flag exists in Launch Darkly.
- The flag is EVERYTHING OFF in staging and prod environments and Feature ON, LA ON, GA OFF in the dev environment.
- The flag is added to the dev tools feature flag list.
- An account preset is added to the MSW to mock the capability.
- `useIsLkeEnterpriseEnabled` hook handles the enablement of the feature.
- Since there is an account capability to enable the feature, the necessary account beta endpoint updates are included.
- Test coverage was added for this hook.
- Have the LKE-E customer tag on your account (prod account is fine). See the internal LKE-Enterprise project tracker to find this.
OR
- Do not …

feat: [M3-8837] - Add LKE-E feature flag

---

packages/manager/.changeset/pr-11278-fixed-1731985440482.md
packages/manager/.storybook/main.ts

This PR attempts to config Storybook's `optimizeDeps` to stabilize the developer experience during the `@linode/ui` migration. Often time devs are getting dev build errors with cache validation when using storybook locally after components have been migrated, and especially while switching branches.. Clearing cache manually does not always achieve a clean slate, but I have found this config to help and not add friction or performance degradation. 
- Add `optimizeDeps` config to storybook
- Check out this PR and run `yarn storybook`
- Confirm no error when storybook opens
- Confirm no performance degradation

fix: [M3-8924] - Storybook `optimizeDeps` config to improve cold start

---

packages/manager/.changeset/pr-11289-fixed-1732045131625.md
packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
packages/manager/src/features/components/PlansPanel/APLNotice.tsx

This PR fixes a wrong implementation of the Linode Detail VPC IP copy UI, introduced by https://github.com/linode/manager/pull/11172
It is not only a bad visual defect, but also prevents the ability to click on the action menu
- remove `<StyledGradientDiv>`
- improve implementation of copy tooltip
- improve/cleanup styling
---
- Have a Linode with a VPC interface
- Navigate to the linode's detail
- see issue with gradient
- Navigate to the linode's detail
- Confirm gradient fix
- Confirm copy tooltip behavior
- 🧪 …

fix: [M3-8929] - Unexpected gradient on Linode Detail with VPC interface

---

packages/manager/.changeset/pr-11275-fixed-1731961142321.md
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx

DbaaS landing page table paginator disappears when the pageSize is less than the number of instances retrieved from the backend. This prevents users from being able to view the additional instances that would be displayed on the following pages.
- DBaaS Landing page now leverages the results property instead of the length of the number of database instances retrieved from a single page via the backend response. The results property provides the total number of instances.
12/10/2024
| ![before-fix](https://github.com/user-attachments/assets/e9c22a29-9871-4a61-b581-e9e7da0eb528) | ![after-fix](https://github.com/user-attachments/assets/8ac918cf-9740-465f-b2ab-b5dd9abaa854) |
- Have the ability to access the database landing page and create new …

fix: [UIE-8259] dbaas landing paginator disappears when pageSize is less than the number of instances

---

packages/manager/.changeset/pr-11291-changed-1732048644474.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Add tooltip for IPV6 to read-only host field on summary page for new db clusters. This tooltip will only appear if there is a host and it is not N/A.
- Added tooltip for IPV6 to read-only host field on summary page for new db clusters.
- The tooltip will only appear if there is a host and it is not N/A.
12/10/2024
| ![readonly-before](https://github.com/user-attachments/assets/c0631d8a-1147-45b3-8efd-07dc31f4262f) | ![readonly-after-2](https://github.com/user-attachments/assets/874bb759-6336-4bff-953d-3b7e32f2f8b3) |
- Have a new database so you can access it's summary page.
- The database must have a populated read-only host field, must not be N/A
- Access the new database summary
- View that the …

change: [UIE-8268] dbaas summary add tooltip for ipv6 to read-only host for new db clusters

---

packages/api-v4/.changeset/pr-11258-added-1731996671316.md
packages/api-v4/.eslintrc.json
packages/manager/.changeset/pr-11258-added-1731996833931.md
packages/manager/.eslintrc.cjs
packages/ui/.changeset/pr-11258-added-1731997009185.md
packages/ui/.eslintrc.json
packages/validation/.changeset/pr-11258-added-1731997101694.md
packages/validation/.eslintrc.json

Looking through recent contributions from external teams, there are some rules we can consider adding to reduce common feedback points.
note: I didn't find a way to "Enforce boolean values are not used as types (as per the ticket)" because using true/false as types is valid TS behavior.
- Remove existing camelCase rule as it is not working
- Enforce new camelCase rule
- Enforce self closing tags for JSX elements without children
- Enforce no explicit "any"
- Enforce some missing eslint rules in `api-v4`, `manager`, `validation`, and `ui` package
N/A
- Ensure any existing violations of the new rules trigger warnings/errors in your IDE
- ❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING …

feat: [M3-8741] - Add linter rules for common pr feedback points

---

packages/manager/.changeset/pr-11283-removed-1732021380915.md
packages/manager/src/components/Breadcrumb/FinalCrumb.styles.tsx
packages/manager/src/components/EditableText/EditableText.tsx
packages/manager/src/components/Placeholder/Placeholder.tsx
packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/features/CancelLanding/CancelLanding.tsx
packages/manager/src/features/Events/EventsLanding.styles.ts
packages/manager/src/features/Help/Panels/SearchPanel.tsx
packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx
packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
packages/manager/src/features/Search/SearchLanding.styles.ts
packages/ui/.changeset/pr-11283-added-1732021489065.md
packages/ui/src/components/Checkbox/Checkbox.tsx
packages/ui/src/components/H1Header/H1Header.tsx
packages/ui/src/components/H1Header/index.ts
packages/ui/src/components/Notice/Notice.tsx
packages/ui/src/components/Radio/Radio.stories.tsx
packages/ui/src/components/Tooltip/Tooltip.stories.tsx
packages/ui/src/components/index.ts

Moves the `H1Header` component to the `@linode/ui` package and updates existing imports.
- This PR needs to be merged before we move `EditableText` & `Breadcrumb` components
- Move `H1Header` component to `@linode/ui` package
- Update existing imports
N/A
- Confirm all checks pass
- Confirm nothing on CM breaks
- Ensure everything works as expected wherever `H1Header` is used
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to …

refactor: [M3-8910] - Move `H1Header` to `at linode/ui` package

---

packages/manager/.changeset/pr-11277-fixed-1732027147462.md
packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
packages/manager/src/features/Account/Maintenance/utilities.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
packages/manager/src/features/Linodes/LinodesLanding/LinodesLandingCSVDownload.tsx
packages/manager/src/features/Linodes/index.tsx

- Fixes a faulty X-Filter causing features using the `GET /v4/account/maintenance`  to not yield any results
- I will add some tests in a follow up to this PR 🧪 
> [!note]
> Without this change, none of the following maintenance banners / tooltips would show 😢 
- Refer to my internal guide I posted in Slack on how to test 📖 
- If you don't have the time to fully test, you can just check this PR for spelling / syntax, the changes are relatively safe and minimal
- 🔐 Removing all …

fix: [M3-8923] - Fix Account Maintenance Account X-Filter

---

packages/api-v4/.changeset/pr-11257-removed-1731594995947.md
packages/api-v4/src/images/types.ts
packages/manager/.changeset/pr-11257-changed-1731595083756.md
packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRow.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRow.tsx
packages/manager/src/features/Images/ImagesLanding/ImageStatus.test.tsx
packages/manager/src/features/Images/ImagesLanding/ImageStatus.tsx

- Improves the UI/UX of the status column on the Images Landing table 💾 
- Shows Image status of `Available` instead of overwritten value of `Ready` so that Cloud Manager is more similar to the API ✏️ 
- Made Status Column consider region statuses (see preview)
- Improved Image upload error state (see preview)
| -------| ------| 
| <video src="https://github.com/user-attachments/assets/67dca31c-52b3-4cb1-9d6e-114fcae2f3fa" /> | <video src="https://github.com/user-attachments/assets/625ee9bf-2bd3-49c8-b7be-24ab4e7de32a" /> |
| -------| ------| 
| ![Screenshot 2024-11-13 at 6 03 39 PM](https://github.com/user-attachments/assets/7ff61cba-0afe-4cd1-bfbc-c5d3c1f6919c) | ![Screenshot 2024-11-13 at 5 35 …

feat: [M3-8903] - Improve Image Status Column

---

packages/manager/src/features/Images/ImagesLanding/ImageStatus.tsx

- Updates `TooltipIcon` to import from `@linode/ui`
- I caused this by merging  https://github.com/linode/manager/pull/11257 - it was a bit outdated 🤦‍♂️

fix: Broken `TooltipIcon` import

---

packages/manager/.changeset/pr-11281-tests-1732015326269.md
packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts

Added cypress test for restricted user Image Empty landing page
Added below cypress tests under in spec file - `cypress/e2e/core/images/images-empty-landing-page.spec.ts`
- checks restricted user has no access to create Image on Image Empty landing page
`yarn cy:run -s cypress/e2e/core/images/images-empty-landing-page.spec.ts`
When test executed using this command `yarn cy:run -s cypress/e2e/core/images/images-empty-landing-page.spec.ts` all tests should pass successfully.

test: [M3-8918] - Cypress test for restricted user Image empty landing page

---

docs/development-guide/15-composition.md
packages/manager/.changeset/pr-11298-tech-stories-1732224052945.md

Currently, form validation implementations vary across the application. We need to establish a pattern for extending API validation schemas that maintains a clear separation between API contract validation and UI-specific validation requirements.
Create documentation explaining:
- When to use simple schema extension vs. full resolver pattern
- How to extend API validation schemas
- Best practices for async validation using QueryClient
- Examples of common validation patterns
- Establish pattern for simple validation extensions
12/10

docs: [M3-8932] - Add Form Validation Best Practices

---

packages/manager/CHANGELOG.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/utils.ts

It's decided that the name Application Platform for LKE should be changed to Akamai App Platform. 
- "Application Platform for LKE" occurrences changed to "Akamai App Platform" 
- lowered requirements for Akamai App Platform from 16gb memory to 8gb memory

fix: [APL-417] - changed APL name to Akamai App Platform

---

packages/manager/.changeset/pr-11313-changed-1732296370575.md
packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx
packages/manager/src/features/components/PlansPanel/PlanSelection.tsx

Matt Hacket requested us to adjust the `Network In` values to match `Network out` for distributed regions so we are in parity with https://techdocs.akamai.com/cloud-computing/docs/plans-distributed
- Adjust `Network In` value to match `Network Out` for distributed regions in the Linode Plan table
| ![image](https://github.com/user-attachments/assets/a5be8a3c-19bf-44e2-be55-edf6a47ffab1) | ![image](https://github.com/user-attachments/assets/ca538ad5-aa25-41d0-be3e-191ac325d26a) | 
- Ensure your account has the `new-dc-testing`, `new-dc-testing-gecko`, `edge_testing` and `edge_compute` customer tags
```
yarn test PlanSelection
```
- ❔ Our [contribution …

change: [M3-8874] - Adjust network_in values for distributed plans

---

packages/manager/.changeset/pr-11316-removed-1732523914805.md
packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/features/Account/AutoBackups.tsx
packages/manager/src/features/Account/CloseAccountSetting.tsx
packages/manager/src/features/Account/EnableManaged.tsx
packages/manager/src/features/Account/NetworkHelper.tsx
packages/manager/src/features/Account/ObjectStorageSettings.tsx
packages/manager/src/features/EntityTransfers/TransfersTable.tsx
packages/manager/src/features/Linodes/LinodeCreate/UserData/UserData.tsx
packages/manager/src/features/Linodes/LinodeCreate/VLAN/VLAN.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/UserDataAccordion/UserDataAccordion.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotificationsContainer.tsx
packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
packages/ui/.changeset/pr-11316-added-1732523878928.md
packages/ui/src/components/Accordion/Accordion.stories.tsx
packages/ui/src/components/Accordion/Accordion.tsx
packages/ui/src/components/Accordion/index.ts
packages/ui/src/components/index.ts

Migrate `Accordion` to `linode/ui` package.
N/A
- All tests should pass
- There should be no adverse impacts observed in Cloud

refactor: [M3-8639] - Move `Accordion` to `linode/ui` package

---

packages/manager/.changeset/pr-11318-upcoming-features-1732533180876.md
packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx
packages/manager/src/features/Profile/APITokens/utils.test.ts
packages/manager/src/features/Profile/APITokens/utils.ts

A new 'Monitor' scope is enabled within Cloud Manager UI for PAT token creation.
- Added new scope 'Monitor' for PAT token creation.
2-Dec-2024
| ![Before](https://github.com/user-attachments/assets/458e73f4-bd18-4ad1-980f-c4e97c138e56) | ![After](https://github.com/user-attachments/assets/721bdc67-7e4b-4eb2-8acf-9d0d98dd3959) |
1. Login as mock user.
2. Click on "mock-user" profile tab at the right top.
3. Go to api-tokens, click on "create a personal access token", you should see "Monitor" listed as one of the scopes with freedom of selecting any/all three types of access.
- ➕ …

upcoming: [DI-21118] - Monitor scope as part of PAT token

---

docs/PULL_REQUEST_TEMPLATE.md
packages/manager/.changeset/pr-11325-tech-stories-1732566065320.md

Makes some changes we discussed at last Thursday's cafe. Feel free to push further changes if this is reviewed while I'm out if changes are requested to satisfy the team.
- Removes the bullets from the list
- Updates the consideration checklist heading to add incentive (to get reviewed faster)
- Puts both checklists under a collapsible section, rather than adds a note about deletion prior to PR review
- 🔐 Removing all sensitive information from the code …

change: Update PULL_REQUEST_TEMPLATE (Part 3)

---

packages/manager/.changeset/pr-11332-tests-1732639325137.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx

- An attempt to fix the DBaaS related test flake we've been seeing 🧪 
- https://github.com/linode/manager/actions/runs/12018143380/job/33501989282
- https://github.com/linode/manager/actions/runs/12019538261/job/33506327492
- `yarn test DatabaseResize`
- `yarn test DatabaseBackups`
- Verify checks pass in CI
> [!warning]
> The code coverage check that uses `develop` as the base branch may still fail because it does not have these changes
<hr />
<details>
🧪 Providing/improving test …

test: Attempt to fix DBaaS unit test flake

---

packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
packages/manager/src/utilities/statMetrics.test.ts

Quick fix to address unit test failures - in  #11294, formatPercent now adds an extra space
```
yarn test MetricsDisplay.test.tsx && yarn test statMetrics.test.ts
```
+ checks should pass (minus potential flaky tests)
<details>
🕛 Scheduling a pair …

test: Fix unit tests depending on `formatPercentage` to reflect latest changes

---

packages/manager/.changeset/pr-11323-tests-1732563014945.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts

Adds test cases to ensure accelerated plans appear when expected
- adds various tests to verify Accelerated plans in Linode and LKE plan panels
12/10
```
yarn cy:run -s "cypress/e2e/core/linodes/plan-selection.spec.ts"
```
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 …

test: [M3-8835] - Add accelerated plans test case to `plan-selection.spec.ts`

---

packages/manager/.changeset/pr-11327-tests-1732571554878.md
packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts

Creates a mock accelerated linode. Adds a todo to eventually switch to a full e2e test (when accelerated plans are not as limited - M3-8946)
12/10
```
yarn cy:run -s "cypress/e2e/core/linodes/create-linode.spec.ts"
```
- 🔐 Removing all sensitive information from the code and PR description
- 🚩 Using a feature flag to protect the release
- 👣 Providing comprehensive reproduction steps
- 📑 Providing or updating our documentation
- 🕛 Scheduling a pair reviewing session
- 📱 Providing …

test: [M3-8836] - Add test to create a mock accelerated Linode

---

packages/api-v4/src/cloudpulse/alerts.ts
packages/api-v4/src/cloudpulse/types.ts
packages/manager/.changeset/pr-11331-added-1732627930598.md
packages/manager/src/factories/cloudpulse/alerts.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/EngineOption.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ResourceMultiSelect.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ResourceMultiSelect.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/schemas.ts
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/types.ts
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/utilities.ts
packages/manager/src/queries/cloudpulse/alerts.ts
packages/validation/src/cloudpulse.schema.ts

- Added the Resource Multi Select component under General Information section to the Create alert form.
- Added a MultiSelect Autocomplete component for selecting Resources
- Added Unit Test for the Resource Multi Select component
- Changed few variables and properties to camelCase
| ![Screenshot 2024-11-19 at 21 38 14](https://github.com/user-attachments/assets/5c482b69-527e-4848-8cf9-fbcc2c5531ec) | ![Screenshot 2024-11-26 at 18 43 55](https://github.com/user-attachments/assets/fda80b26-7823-409c-ac37-48ca3cab8f4e) |
- The tabs are …

upcoming: [DI-21694] - Added Resource Select component to the Create-alert form

---

packages/manager/.changeset/pr-11336-added-1732711112187.md
packages/manager/src/components/DocsLink/DocsLink.test.tsx

Added Unit test cases for `DocsLink` components.
- Add unit test cases for `DocsLink` components.
N/A
- Run `yarn test src/components/DocsLink --reporter verbose`

test: [M3-8547] - Add unit tests for `DocsLink` component

---

packages/api-v4/.changeset/pr-11337-added-1732714186488.md
packages/api-v4/.eslintrc.json
packages/manager/.changeset/pr-11337-added-1732714227095.md
packages/manager/.eslintrc.cjs

Follow up to the PR: #11330 
Previously added camelcase rule in `api-v4` and `manager` was causing thousands of warnings due to APIv4 property names in our codebase.
This PR Improves linter rules for naming convention - enforces rules for variables, functions, typeLike (`class`, `enum`, `interface`, `typeAlias`, `typeParameter`), and parameters, without the need to create any custom rules.
- Enforce new linter rules (in `api-v4` and `manager` package) for:
- variable
- function
- parameter
- typeLike
N/A
- Test rule against APIv4 package, factories, and mock data to ensure no false positives
- Ensure any violations of the new rules trigger warnings/errors in your IDE
- Ensure no related warnings due to APIv4 property names in our codebase
<details> …

feat: [M3-8947] - Improve linter rules for naming convention

---

packages/manager/.changeset/pr-11311-changed-1732288180106.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryClusterConfigurationLegacy.tsx
packages/manager/src/features/components/PlansPanel/PlanSelection.tsx

DBaaS Resize GA: Enable Downsizing (horizontal and vertical) and enable 'Shared' tab for resizing 2N cluster. Updated node presentation.
Database Resize: 
- Enable Downsizing (horizontal and vertical)
- Enable the 'Shared' tab for resizing 2N cluster
- Enable 'Current Plan' for selection
Updated node presentation in the 'Database Summary' and 'Database Resize' tabs.
12/10/24
| ![Screenshot 2024-11-22 at 4 00 42 PM](https://github.com/user-attachments/assets/c6b34d3b-9819-4255-8787-d9d99db1cd45) | ![Screenshot 2024-11-22 at 4 01 06 PM](https://github.com/user-attachments/assets/bdc506c6-c23b-4390-9cc0-4055399c2a1e) |
| ![Screenshot 2024-11-22 at 4 05 31 PM](https://github.com/user-attachments/assets/5470ae5a-9d10-49d0-8f7a-1ac77c768480) | …

change: [UIE-8228] - DBaaS Resize GA: Enable Downsizing, update node presentation

---

packages/manager/.changeset/pr-11322-upcoming-features-1732570083227.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/Kubernetes/CreateCluster/ClusterTypePanel.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/queries/kubernetes.ts

We want to allow users the ability to create an LKE-Enterprise cluster in the create flow. 
- A new Cluster Type section exists in the Create Cluster form.
- Copy describes the section and a docs link with placeholder content.
- The cards handle enabled/disabled state as follows:
- When the feature flag is disabled, do not display the Cluster Type Panel.
- When the feature flag is enabled but the user lacks the LKE-Enterprise account capability, the Enterprise panel is disabled and displays a tooltip.
- When the feature flag is enabled and the user has the LKE-Enterprise account capability, the Enterprise panel is enabled and LKE (standard) is selected by default. 
- When the Enterprise cluster type is enabled, the HA Control Plane section is not visible.
- Test coverage confirms the …

upcoming: [M3-8840] - Add Cluster Type selection to LKE Create Cluster flow

---

packages/manager/.changeset/pr-11326-tests-1732566960471.md
packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
packages/manager/cypress/support/intercepts/linodes.ts

The cypress/e2e/core/linodes/backup-linode.spec.ts have a few shortcomings that should be addressed:
- Navigate to the "Backups" tab of a Linode details page using the UI rather than navigating directly to "/linodes/:id/backups"
- Add test/assertions for canceling Linode backups
- Add test/assertions for error flow when attempting to re-enable Linode backups after canceling (users cannot re-enable backups without first waiting 24 hrs)
- Add new assertions for linode backup tests
```
yarn cy:run -s "cypress/e2e/core/linodes/backup-linode.spec.ts"
```
- ➕ Adding a …

test: [M3-6611] - Add new assertions for linode backup tests

---

packages/manager/.changeset/pr-11356-fixed-1733237715392.md
packages/manager/src/features/Linodes/LinodeCreate/Tabs/OperatingSystems.tsx

Super small fix to avoid having OS panel fetching a -1 region by default. 
bug introduced in https://github.com/linode/manager/pull/11206/files
The query is disabled if if there's no region ID so passing a default `-1` breaks that pattern
https://github.com/linode/manager/blob/develop/packages/manager/src/queries/regions/regions.ts#L43
- fix `-1` default fetch to regions/{id} query 
**12/12/2024**

fix: [M3-8958] - LinodeCreate OS Panel fetches region with -1 on page load

---

packages/manager/.changeset/pr-11358-tech-stories-1733240852206.md
packages/manager/package.json
yarn.lock

Bumping recharts to get rid of deprecation warnings
see https://github.com/recharts/recharts/issues/3615 for more context
- Bump recharts to ^2.14.1
<details>
♿  Providing accessibility …

tech-story: [M3-8959] - Bump recharts to ^2.14.1

---

packages/manager/.changeset/pr-11361-tech-stories-1733330515390.md
packages/manager/src/hooks/usePendo.test.ts
packages/manager/src/hooks/usePendo.ts

UXR has reported:
"On our end, to ensure we are tracking accurately, we have to replace the `XXXX` with an `<ignore>` or `*` rule in the Pendo Tagging tool. Is there a way to replace it with a `*`? It will save manual steps in Pendo.. . once most pages have those bits replaced while retrotagging, we can make sure to look out for `XXXX` and replaced it in the Rule Builder with the attached screenshots."
Even with rules configured, changing the `XXXX` to `*` now will save time and speed up the tagging process in the future because new URLs will not have to have the same rules configured to transform the `XXXX`s.
**Note: We confirmed via Pendo that the unicode %2A wouldn't be an issue - the * in a rule will match the unicode in the normalized pattern.**
- Replaced the `XXXX` string with `*` …

change: [M3-8961] - Change Pendo sanitized url path string to match UXR request

---

packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.tsx

fix styling regression from https://github.com/linode/manager/pull/11260/files
no need for a changeset this is not in prod yet
- fix app bar spacing on mobile
**12/10/2024**
https://github.com/user-attachments/assets/8c9b8e29-8775-4c86-beea-16ce38e528a4
<details>
📑 Providing or updating our …

fix: [M3-8966] - Regression with AppBar

---

packages/manager/src/components/RegionSelect/RegionSelect.tsx

fix to a regression introduced in https://github.com/linode/manager/pull/11348/files#diff-53966653a902407c449c1ebecc270efaa4bb9b0f8f1eac2c925cbf5bc2eb4268R124
no need for changeset since it was just merged to develop
- restore RegionSelect width
<details>
📑 Providing or updating our …

fix: [M3-8847] RegionSelect width

---

packages/manager/.changeset/pr-11371-changed-1733409504298.md
packages/manager/cypress/e2e/core/databases/update-database.spec.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreateAccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/constants.ts
packages/manager/src/utilities/ipUtils.ts

DBaaS: Access Controls text update, fix defaultDB for legacy instances
- Summary Tab: updated 'Database name' for legacy instances
- Database Create > Access Controls: updated copy, placeholder, button text 
- Settings Tab > Manage Access: updated copy (only for new instances)
- Manage Access Drawer: updated copy, placeholder, button text (only for new instances)
12/10/24
| ![Screenshot 2024-12-04 at 8 19 32 PM](https://github.com/user-attachments/assets/f47b6447-9045-47fa-a28c-173ea78d033c) | ![Screenshot 2024-12-04 at 8 19 48 PM](https://github.com/user-attachments/assets/eea23fa1-49b7-4d36-97c1-7b50cf7f351d) |
| ![Screenshot 2024-12-04 at 8 20 33 PM](https://github.com/user-attachments/assets/d237ca15-4dcb-4646-b50b-2a5cf2d3446c) | …

feat: [UIE-8269], [UIE-8290] - DBaaS: Access Controls text update, fix defaultDB for legacy instances

---

packages/api-v4/src/cloudpulse/types.ts
packages/manager/package.json
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
packages/manager/src/features/Images/ImagesCreate/ImageUpload.utils.ts
packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
packages/validation/src/buckets.schema.ts
packages/validation/src/cloudpulse.schema.ts
packages/validation/src/images.schema.ts
packages/validation/src/kubernetes.schema.ts
yarn.lock

- Updates  `@hookform/resolvers` to latest  📦 
- Brings enhanced type-safety and will unblock other efforts like M3-8956 ✨ 
> [!note]
> These changes were necessary to satisfy TypeScript now that yup resolvers are more type safe
- Fixes incorrect CloudPulse alerting incorrect types / schemas
- Replaces some instances of  `notRequired()` with `optional()`
- `notRequired()` means the value can be null, undefined, or not present
- `optional()` means the value can be undefined or not present 
- This change was needed to make our resolvers satisfy/match the types defined in `api-v4`
- Added missing fields on `CreateBucketSchema`
- Fixed deprecations and cleaned up the Linode Create resolver 
> [!note]
> There should be no UI changes
- Check for schema regressions
- Manually test affected forms …

refactor: [M3-8954] - Update `@hookform/resolvers` to latest

---

packages/manager/.changeset/pr-11365-tests-1733305182663.md
packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts

The test doesn't wait for the Volume to finish being created before attempting to delete.
- Added polling to the Volumes endpoint to wait for the Volume to be ready before proceeding with the rest of the test.
12/12
<details>
🕛 Scheduling a pair …

test: [M3-8758]- Fixed `delete-volume.spec.ts` flaky test

---

packages/manager/.changeset/pr-11351-added-1733194164261.md
packages/ui/src/components/TextField/TextField.test.tsx
packages/ui/src/components/TextField/TextField.tsx

Tiny PR to add better accessibility to the `Textfield` via its `helperText` prop.
On screen, it is trivial for a user to see a helper test associated with a field, but this is not necessarily true for someone using a screen reader, since the helper text is a plain paragraph floating under the input, and isn't associated with its relevant interactive element.
- Describe the textfield by its helper text when disabled
- Cleanup textfield input ID logic (see self review)

added: [M3-6989] - `aria-describedby` to TextField with helper text

---

packages/manager/.changeset/pr-11364-tech-stories-1733273269749.md
packages/manager/package.json
yarn.lock

- Removes the `reselect` dependency 📦 
- I think this is some kind of Redux tool. We probably used it at some point but don't anymore now that we've removed more redux related code.
- Verify `yarn.lock` changes look correct
- Verify `reselect` isn't used anywhere
- Verify automated checks pass 
<details>
👣 Providing comprehensive …

refactor: [M3-8964] - Remove `reselect` dependency

---

packages/manager/.changeset/pr-11379-fixed-1733476117431.md
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx

We are preventing word breaks in the billing contact information to improve layout and readability.
- Disabled word breaks in billing contact info.
N/A
| ![Before](https://github.com/user-attachments/assets/a5896216-3d90-4710-b130-c5686147b433) | ![After](https://github.com/user-attachments/assets/4d63283f-5197-4c3d-b634-ce1152626388) |
- Ensure a billing contact info is saved in the account.
- Log in and go to the Account Page.
- Check if the billing info is displayed without word breaks.
- Ensure the billing info is shown without line breaks.

fix: [M3-8796] - Disallow word-break in billing contact info

---

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx

This PR fixes a minor regression in CM (mobile view/smaller screens only) caused by https://github.com/linode/manager/pull/11179
> [!Note]
> Pointing this PR to staging
| ![Screenshot 2024-12-06 at 4 18 32 PM](https://github.com/user-attachments/assets/70566ae3-25d7-4edc-a24e-c20f9a228148) | ![Screenshot 2024-12-06 at 5 18 07 PM](https://github.com/user-attachments/assets/74fabdeb-4eac-48e0-8ba6-8e418cad86ec) |
- Fixed Summary section Overflow issue 
- Fixed "Summary" header alignment (made responsive)
- Fixed text alignments and made some other improvements
- Ensure no overflow issue in the "Summary" section on smaller devices
<details> …

fix: [M3-8972] - Overflow issue in Kubernetes Summary section on smaller screens (→ `staging`)

---

packages/manager/.changeset/pr-11383-tests-1733523460107.md
packages/manager/cypress/e2e/core/billing/credit-card-expired-banner.spec.ts

- Adds Cypress tests for the Credit Card Expired banner.
- Mocks the account endpoint with an expired and non-expired credit card.
- Verifies clicking the "Update Card" button navigates to `account/billing`.
1. `yarn cy:run -s "cypress/e2e/core/billing/credit-card-expired-banner.spec.ts"`
2. Verify CI passes

test: [M3-8693] - Cypress tests for Credit Card Expired banner

---

packages/manager/.changeset/pr-11381-upcoming-features-1733479690692.md
packages/manager/.changeset/pr-11382-upcoming-features-1733485035913.md
packages/manager/src/featureFlags.ts
packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
packages/manager/src/features/CloudPulse/Utils/models.ts
packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx

ACLP supports a limited set of regions per service type and capability based on LaunchDarkly config. Regions are now correctly filtered according to the capability they belong to and the supported regions fetched from launchDarkly.
1. Added new key for supported regions in aclpResourceType Flag.
2. Validated the region ids from flag with all the regions fetched from api.
3. Filtered the service type specific regions using corresponding capabilities.
4. Added relevant unit test to verify.
12 December 2024
1. Navigate to monitor tab.
2. Select a dashboard.
3. Open networks tab, find the launchDarkly config, see supported region ids in aclpResourceTypeMap, verify that these are same as the region ids listed in 'regions' autocomplete popper list. In case supportedRegionIds is null/undefined, …

upcoming: [DI-20595] - ACLP Supported regions per service type

---

packages/manager/.changeset/pr-11398-fixed-1733917277527.md
packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx

A small, quick PR to fix the misplaced `errorGroup` prop that was causing a console error.
Note: We will fix the other unrelated console errors in a follow-up PR
- Correctly placed `errorGroup` in textFieldProps
N/A
| ![Screenshot 2024-12-11 at 4 57 32 PM](https://github.com/user-attachments/assets/9d2a562d-200a-4b7e-83d9-182f36363aa4) | No console error due to the `errorGroup` prop|
- Go to `Create NodeBalancers`
- Ensure no console error when selecting TCP protocol in Configuration panel 
<details>
➕ Adding a …

fix: [M3-8506] - Misplaced `errorGroup` prop causing console error

---

packages/manager/.changeset/pr-11393-tech-stories-1733855306252.md
packages/manager/src/features/VPCs/VPCDetail/SubnetEditDrawer.tsx
packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
packages/validation/.changeset/pr-11393-changed-1733855352751.md
packages/validation/src/vpcs.schema.ts

- refactors VPCEditDrawer and SubnetEditDrawer to use react-hook-form instead of formik
- update drawers + introduces dynamic validation
- update validation schema regex to be more accurate for non number/letter characters
- update validation schema error messages slightly
- Confirm behavior matches prod for editing a VPC and editing a subnet*
- *there will now be some dynamic error validation tho
- Confirm tests pass
```
yarn test SubnetEditDrawer
```
```
yarn test VPCEditDrawer
```
```
yarn cy:run -s "cypress/e2e/core/vpc/vpc-landing-page.spec.ts"
```
```
yarn cy:run -s "cypress/e2e/core/vpc/vpc-details-page.spec.ts"
```
<details>
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.m …

refactor: [M3-8986] - Refactor VPCEditDrawer and SubnetEditDrawer to use `react-hook-form`

---

packages/api-v4/.changeset/pr-11413-removed-1734030444142.md
packages/api-v4/src/account/account.ts
packages/manager/.changeset/pr-11413-upcoming-features-1734030483336.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/ClusterTypePanel.tsx
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/queries/account/account.ts
packages/manager/src/queries/account/queries.ts

The LKE team has updated the /v4 endpoint to include the `Kubernetes Enterprise` capability, so we no longer have to use a seperate /v4beta account endpoint. This PR does the clean up to just use `/v4/account`.
- Removed the request and query for /v4beta/account
- Fixed a test issue where running tests locally with the LKE-E customer tag on your account would fail for the test that is supposed to *not* have the account capability -- the account endpoint was not being mocked.
- Have the LKE-E customer tag on your account.
- Ensure the LKE-E feature flag is turned on in dev tools locally.
```
```
<details>
❔ Our …

change: [M3-8928] - Switch from v4beta to v4 `account` endpoint for LKE-E

---

packages/manager/.changeset/pr-11407-tests-1734013914322.md
packages/manager/cypress/e2e/core/account/account-logout.spec.ts
packages/manager/cypress/e2e/core/general/account-login-redirect.spec.ts
packages/manager/cypress/support/constants/login.ts

This fixes test failures in two of our login related Cypress tests when the tests are run against a non-Prod environment. The issue is caused by importing the `LOGIN_ROOT` constant from `src`. Because that value gets set using the Vite-specific `meta.env` object, when imported from Cypress it always falls back to the default value.
This is necessary for running the Cloud Manager tests during the API release.
- Get login environment using `REACT_APP_LOGIN_ROOT` environment variable directly
1/14/2025
Update your `.env` file so that `REACT_APP_API_ROOT` and `REACT_APP_LOGIN_ROOT` are pointing to the staging environment. Then run the tests using this command:
```bash
CYPRESS_BASE_URL="<staging env URL here>" yarn cy:run -s "cypress/e2e/core/account/account-logout.spec.ts,cypress/e2e/core/gene …
```

M3-8974: Fix account login tests when using non-Prod login environment

---

packages/manager/.changeset/pr-11414-fixed-1734041664478.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
packages/manager/src/features/Databases/constants.ts

In DBaaS Create and Settings, Manage Access IP fields should display an updated validation error message that includes IPv6 when both IPv6 and IPv4 are available.
-  DBaaS Create and Setting Manage Access IP field validation error messages have been updated to include IPv6 when available.
1/14/25
| ![db-settings-manage-access-before](https://github.com/user-attachments/assets/1a17115a-a75d-40a5-969e-9d8d3937b9ba) | ![db-settings-manage-access-after](https://github.com/user-attachments/assets/4a667fba-df38-41d3-8adc-4c803049a4a1) |
| ![db-create-before](https://github.com/user-attachments/assets/2ce177b3-7236-4ae3-9cdd-dedb42744ec8) | ![db-create-after](https://github.com/user-attachments/assets/a43efe1f-937e-40a8-863b-349036be304f) |
- Have …

fix: [UIE-8338] dbaas IP validation should display updated error message that includes IPV6

---

packages/manager/.changeset/pr-11406-changed-1734097478149.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseSummarySection.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseSummarySection.tsx
packages/manager/src/features/Databases/DatabaseCreate/utilities.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/DatabaseEngineVersion.tsx
packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
packages/manager/src/features/components/PlansPanel/constants.ts
packages/manager/src/features/components/PlansPanel/types.ts
packages/manager/src/features/components/PlansPanel/utils.test.ts
packages/manager/src/features/components/PlansPanel/utils.ts

Database Resize: Disabled plan tooltip updated for new databases, and updated plan selection descriptions.
- Database Resize: Updated disabled plan tooltip for new database
- Database Resize: Updated plan selection descriptions for new database
- Database Resize > Summary Section : Updated text
01/14/2025
| ![Screenshot 2024-12-12 at 3 03 27 PM](https://github.com/user-attachments/assets/33c35aa4-f385-4960-b288-253a40fc39d4) | ![Screenshot 2024-12-12 at 3 02 56 PM](https://github.com/user-attachments/assets/ab41b545-a550-49f3-8b2c-10084a990a77) |
| ![Screenshot 2024-12-12 at 3 04 03 PM](https://github.com/user-attachments/assets/5d2720f4-18a9-4d1a-9d0b-70b59c36106a) | ![Screenshot 2024-12-12 at 3 03 …

fix: [UIE-8228] - Database Resize: text update

---

packages/api-v4/.changeset/pr-11399-upcoming-features-1733923542682.md
packages/api-v4/src/cloudpulse/alerts.ts
packages/manager/.changeset/pr-11399-upcoming-features-1733923517331.md
packages/manager/src/factories/index.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/cloudpulse/alerts.ts
packages/manager/src/queries/cloudpulse/queries.ts

Added a action menu for the AlertListing component table rows and Added a empty Alert detail landing page with loading and error case handling alone
1. Added action menu for different alert types that will be displayed in each row of alert listing page.
2. Added an empty Alert detail component with changes for loading and error state handling for API call alone.
3. Added a new useAlertDefinitionQuery hook, which fetches the alert details API by id and service type.
19-12-2024
| ![Screenshot 2024-12-11 at 9 53 57 AM](https://github.com/user-attachments/assets/c7899962-1dc2-4c59-8575-b07ad600c4a6)|![Screenshot 2024-12-11 at 9 54 06 AM](https://github.com/user-attachments/assets/dc3d492c-cfc1-4476-8c81-5f52ac859156)|
|![Screenshot 2024-12-12 at 2 …

upcoming: [DI-22130] - Alert listing action menu and Alert Detail landing

---

packages/manager/.changeset/pr-11417-changed-1734111263221.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenance.tsx

This pull request is for a small change in the DBaaS Settings maintenance field. It updates the text used for the tooltip that gets displayed next to the Upgrade Version button when the button is disabled due to pending maintenance updates.
- Text is changed to "Upgrades are disabled due to pending maintenance updates. To enable the upgrade, apply available updates now or wait until the next maintenance window."
1/14/25
| ![maintenance-tooltip-before](https://github.com/user-attachments/assets/12e0970f-98e3-48ed-9e58-8c58fef1984d) | ![maintenance-tooltip-after-2](https://github.com/user-attachments/assets/332a0b31-c01d-4055-a9dd-7354e16ca060) |
- Managed Databases
- dbaasV2 feature flag set for GA
- Use mock data so you can view the pending …

change: [UIE-8194] DBaaS Settings maintenance pending updates tooltip should have accurate tooltip text

---

packages/manager/.changeset/pr-11424-fixed-1734375315983.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx

- Fixes error messaging when initially selecting a VPC as the primary interface (for eth0)
- Change initial primaryInterfaceIndex to 0 (matches autocomplete's previous initial value)
next release - 1/14?
| ![image](https://github.com/user-attachments/assets/480544e7-1101-4824-a10f-155f08109d7f) | ![image](https://github.com/user-attachments/assets/b76ac1c2-a26d-42d5-95e4-55989d4671dd) |
With a Linode not assigned to a VPC,
- Go to linode's configurations and edit/add a new config
- set eth0 to VPC and notice how warning message doesn't align
- Confirm above bug fixed
- Confirm behavior still matches this PR: https://github.com/linode/manager/pull/9916
- Confirm no regressions in behavior of config panel for editing existing configs/adding new …

fix: [M3-8196] - Fix Linode Edit Config warning message when initially selecting a VPC as the primary interface

---

packages/manager/.changeset/pr-11391-tech-stories-1733949258449.md
packages/manager/cypress/component/poc/select.spec.tsx
packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
packages/manager/src/features/Managed/MonitorDrawer.tsx
packages/ui/.changeset/pr-11391-added-1733949199859.md
packages/ui/src/components/Autocomplete/Autocomplete.tsx
packages/ui/src/components/Select/Select.stories.tsx
packages/ui/src/components/Select/Select.test.tsx
packages/ui/src/components/Select/Select.tsx
packages/ui/src/components/index.ts

This PR introduces a new Select component aimed to facilitate the full deprecation of `react-select`.
This new component wraps Autocomplete to make a "simple" Select for the following reasons:
- Our new Select needs more capabilities than a simple select (easily disabling search, being clearable, being "creatable") in order to fulfill some of the UX requirements of `react-select`
- Wrapping `Autocomplete` allows us to 
- only pick the options we are interested in
- facilitates the developer experience for simple Select cases
- Customize this instance only without adding further complexity to `Autocomplete` (for instance, adding the "creatable" logic to our existing `Autocomplete` would further complicate its maintenance)
- Keep styling and common props consistency (helper text, error …

[M3-8991 + M3-6911] - New Select Component + Managed Replacement

---

packages/api-v4/.changeset/pr-11368-added-1733420616390.md
packages/api-v4/src/kubernetes/types.ts
packages/manager/.changeset/pr-11368-added-1733415278919.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx

The /pools endpoint returns Tags for node pools, but we don't currently surface them in the UI: https://techdocs.akamai.com/linode-api/reference/get-lke-node-pool 
At the bottom of each node pool section, we will now display the list of tags associated with a node pool and the option to add a new tag. 
- Added Tags to Kubernetes Node Pool table
https://github.com/user-attachments/assets/0dd7612d-5c78-4eae-841f-a309dd60798a
```
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-update.spec.ts"
```
<details>
➕ Adding a …

feat: [M3-8855] - Surface Node Pool Tags

---

docs/tooling/analytics.md
packages/manager/.changeset/pr-11427-tech-stories-1734383515695.md
packages/manager/src/hooks/usePendo.ts

ACC's Pendo implementation uses a CNAME; we want to provide the same set up with Cloud Manager and ensure Pendo is working for as many users as possible.
From Pendo docs:
> A Canonical Name record (abbreviated as CNAME record) is a type of resource record in the Domain Name System (DNS) used to specify that a domain name is an alias for another domain, which is the "canonical" domain.
> Our CNAME feature allows you to create hostnames under your own vanity domain (subdomain), used in place of Pendo hostnames for both sending events and downloading guide content. This helps ensure that events are collected and guides are served to end users who even if they're subject to ad-blocking software, firewalls, VPNs, web filters, and so on.
- Lots of coordination for this PR with Pendo, the Akamai …

change: [M3-8742] - Update Pendo URL with CNAME

---

packages/manager/.changeset/pr-11385-fixed-1733735480951.md
packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
packages/manager/src/features/StackScripts/StackScriptsLanding.tsx

This PR fixes the issue where the page title on certain landing pages (e.g., Domain Landing, Object Storage Detail pages, and StackScripts details pages) was incorrectly set to the page's URL instead of displaying the expected title with relevant keywords
- Updated the page title to display relevant keywords instead of the page's URL on the affected landing pages.
N/A
| ![Before](https://github.com/user-attachments/assets/35b70b85-47c2-48c4-b87f-ff65ba1d7bf7)| ![After](https://github.com/user-attachments/assets/5060eadd-991e-4bd0-8af6-3f74e01dc254) |
| ![Before](https://github.com/user-attachments/assets/b6ecadb3-897b-4956-9ad5-14a31f9a4f01) | ![After](https://github.com/user-attachments/assets/1f0d93d2-8db2-46 …

fix: [M3-8905] - Change document title from address to appropriate keyword

---

packages/api-v4/.changeset/pr-11426-changed-1734381690407.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11426-fixed-1734381380797.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx

When DB is provisioning, the DBaaS resize tab "Used" field under Current Configuration shows just "GB". This field is mapped to used_disk_size_gb property which is null because the value is not available yet. The "Used" field should display "N/A" when no value is available.
- Resize tab Used field will now display N/A when used_disk_size_gb is null.
1/14/25
| ![resize-null-before](https://github.com/user-attachments/assets/7a4a61d4-a950-437e-809c-c97a6bc2cec3) | ![resize-null-after](https://github.com/user-attachments/assets/45cb99e6-a8c5-4adb-970d-aefa44786cd9) |
- Have access to databases tab and the DatabaseResize tab
<details> …

fix: [UIE-8342] DBaaS resize used field should show N/A when property is null

---

packages/manager/.changeset/pr-11430-tech-stories-1734463578200.md
packages/manager/src/features/Users/UserPermissions.tsx
packages/ui/src/components/Select/Select.tsx

Replace the only instance of react-select under the `/Users` namespace.
Bonus, the old select display was broken 🎉 
- replace `react-select` instance
- added a couple props on the new Select (`sx` & `id`)
| ![Screenshot 2024-12-17 at 14 10 21](https://github.com/user-attachments/assets/099b4ef2-5836-41ad-8a80-bf356709579b) | ![Screenshot 2024-12-17 at 14 18 21](https://github.com/user-attachments/assets/68766448-5675-4c97-ba25-293c2e5ff716) |
- Navigate to  `/account/users/{user}/permissions` (for a "secondary" user)
- Disable "Full Access Account"
- Scroll down to the permission section and confirm the styling and behavior of the "Specific Permissions" select
<details>
❔ Our …

tech-story: [M3-6904] - Replace react-select instances in /Users with new Select

---

packages/api-v4/.changeset/pr-11433-changed-1734483970019.md
packages/api-v4/.changeset/pr-11433-removed-1734484000708.md
packages/api-v4/src/cloudpulse/services.ts
packages/api-v4/src/cloudpulse/types.ts
packages/manager/.changeset/pr-11433-tech-stories-1734484023886.md
packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
packages/manager/cypress/support/intercepts/cloudpulse.ts
packages/manager/src/factories/dashboards.ts
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
packages/manager/src/queries/cloudpulse/services.ts

This PR fixes some inconsistencies and inaccuracies with the types for the  `GET /monitor/services/{service_type}/metric-definitions` I discovered in my [upcoming work](https://github.com/linode/manager/compare/develop...bnussman-akamai:manager:M3-8955-update-react-vnc-to-v2?expand=1) 🔧 
- Renames `AvailableMetrics` interface to `MetricDefinition` to be more inline with the API
- Removes the `MetricDefinitions` type because `ResourcePage<MetricDefinition>` should be used instead
- Verify there are no regressions to CloudPulse 📈 
<details>
➕ Adding a …

fix: CloudPulse metric definition types

---

packages/manager/.changeset/pr-11437-fixed-1734527875368.md
packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts
packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts
packages/manager/src/features/Domains/DomainActionMenu.tsx

A small, quick PR to fix ARIA label of action menu in Domains Landing table row.
- Updated the aria-label of the Action Menu in the Domains Landing page table row from `[object Object]` to a human-readable label
- Updated e2e tests
N/A
| ![Screenshot 2024-12-18 at 6 24 38 PM](https://github.com/user-attachments/assets/e014f534-ed29-422c-92a4-6adc2e4c0eb7) | ![Screenshot 2024-12-18 at 6 40 17 PM](https://github.com/user-attachments/assets/c08527d9-6dff-4936-abae-58aab68e9c96) |
- Go to the Domains Landing Page
- Inspect the Table Row Action Menu
- Check that the `aria-label` is in a human-readable format
<details> …

fix: [M3-9032] - ARIA label of action menu in Domains Landing table row

---

packages/manager/.changeset/pr-11422-tests-1734356272451.md
packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts

Add Cypress test to validate error messages if required options are not selected in the Linode Create Backups tab.
- Related to: https://github.com/linode/manager/pull/11147
- Add a Cypress test to validate error messages if required options are not selected in the Linode Create Backups tab.
N/A
- `yarn cy:run -s "cypress/e2e/core/linodes/create-linode.spec.ts"`
<details>
🔐 Removing …

test: [M3-8864] - Cypress tests to validate errors in Linode Create Backups tab

---

packages/manager/.changeset/pr-11390-tests-1733844253656.md
packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts

The list of StackScripts loads before Cypress selects the search field, causing the search field to go out of view which triggers a failure in a should('be.visible') assertion. This can be fixed by adding .scrollIntoView before asserting the element's visibility.
- Add .scrollIntoView before asserting the element's visibility in packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
```
yarn cy:run -s "cypress/e2e/core/linodes/rebuild-linode.spec.ts"
```
🧪 …

test: [M3-8768] - Cypress test flake: Rebuild Linode

---

packages/manager/.changeset/pr-11411-tests-1734023093705.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts

The "can dynamically update prices when creating an LKE cluster based on region" test in lke-create.spec.ts fails when running against the staging API because only the Dallas region is available for LKE creation but the test assumes Newark is present. Fix the test by using a different mock region.
- Update mock region to Dallas
To reproduce the issue locally you’ll want to set your REACT_APP_API_ROOT var in .env to the staging URL. You might also have to set REACT_APP_LOGIN_ROOT to the login staging URL, then run the following command
```
```
🤏 Splitting …

test: [M3-8979] - Fix lke-create test by using a different mock region

---

packages/manager/.changeset/pr-11431-fixed-1734558226981.md
packages/manager/src/features/Managed/Contacts/Contacts.tsx
packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx
packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx
packages/manager/src/features/Managed/Monitors/MonitorTable.styles.tsx
packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx

Managed pages needed some 💚  when it came to tablet, mobile, and loading table views. This PR fixes issues across all Managed tabs where mismatches between the number of data columns and table header columns displayed.
In addition to the above, this PR:
- Removes unnecessary left padding for the first column of the Monitors table header
- Makes the row actions display in the Contacts table consistent with the other tables (it becomes a `...` action menu at small screen sizes)
- Does some linting and other small stylistic code clean up
1/14
<details>
<summary>Videos</summary>
| 🐛 | Before  | After   |
| --- | ------- | ------- |
| Monitors Loading State Bug |  <video src="https://github.com/user-attachments/assets/c403328b-f07b-4192-939e-60be0d5a67ac" /> | <video …

fix: [M3-9021] - Various bugs in Managed tables

---

packages/api-v4/.changeset/pr-11397-upcoming-features-1734001143561.md
packages/api-v4/src/iam/types.ts
packages/manager/.changeset/pr-11397-upcoming-features-1733916688951.md
packages/manager/src/factories/accountPermissions.ts
packages/manager/src/features/IAM/Users/UserDetails/DeleteUserPanel.test.tsx
packages/manager/src/features/IAM/Users/UserDetails/DeleteUserPanel.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserDeleteConfirmation.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.test.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserEmailPanel.test.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserEmailPanel.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserProfile.tsx
packages/manager/src/features/IAM/Users/UserDetails/UsernamePanel.test.tsx
packages/manager/src/features/IAM/Users/UserDetails/UsernamePanel.tsx
packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx

IAM RBAC - user details component.
This component is almost identical to an existing one in the `Account`, with some adjustments.
One difference is the addition of a new field showing the number of assigned roles.
- new user details component
1/14/25 (dev)
| 📷 |![image](https://github.com/user-attachments/assets/c20e6321-56bf-4832-9feb-cdc4a80ce1fc)|
| 📷 |![image](https://github.com/user-attachments/assets/8f918892-208f-4aa3-b07e-214a589f7b47)|
- Ensure the Identity and …

feat: [UIE-8137] - IAM RBAC: add new user details component

---

packages/manager/.changeset/pr-11435-tests-1734516339389.md
packages/manager/cypress/e2e/core/linodes/linode-network.spec.ts

Cypress test to validate ARIA label of Linode IP Addresses action menu
- Related to: https://github.com/linode/manager/pull/11167
- Add Cypress test to validate ARIA label of Linode IP Addresses table row action menu
- Refactor the code
N/A
- `yarn cy:run -s "cypress/e2e/core/linodes/linode-network.spec.ts"`
<details>
🚩 Using a feature flag to protect the …

test: [M3-8863, M3-9040] - Cypress test to validate aria label of Linode IP Addresses/Ranges action menu

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.types.ts
packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
packages/manager/src/features/ObjectStorage/hooks/useObjectStorageRegions.tsx
packages/manager/src/features/ObjectStorage/utilities.ts

- Fixes bug introduced in https://github.com/linode/manager/pull/11432
- One-off logic was added for Object Storage Gen2, but that logic was applied to all region selects throughout Cloud Manager resulting in users seeing incorrect region options outside of Object Storage 🌎 
https://github.com/linode/manager/blob/0b0fa666fff8a4252bb48591d6235eb2198abb04/packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx#L43-L45
- Add a condition to check that `currentCapability === 'Object Storage'` to the new one-off logic so that it only applies to Object Storage region selects
`sg-sin-2` is shown as both a core region and a distributed region 😳
`sg-sin-2` only shows up as a core region
- Check Region Selects throughout Cloud Manager
- Verify correct regions are shown
- Verify that on …

hotfix: Incorrect Region Options

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.types.ts
packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketRegions.tsx
packages/manager/src/features/ObjectStorage/utilities.ts

- Incorrectly displayed region options ([#11449](https://github.com/linode/manager/pull/11449))

Release v1.133.2 - staging → master

---

packages/manager/.changeset/pr-11443-removed-1734624899643.md
packages/manager/cypress/e2e/core/images/create-image.spec.ts
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.test.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx

- Removes the `Images are not encrypted` warning on the Image create flow
- We are removing it because it is no longer true. Because _Image Service Gen2_ is GA, all newly created images **are encrypted** 🔒 
1/14/2025
| ![Screenshot 2024-12-19 at 11 05 28 AM](https://github.com/user-attachments/assets/431e9f98-96d6-4be8-aa34-ff0d6aca0813) | ![Screenshot 2024-12-19 at 11 05 17 AM](https://github.com/user-attachments/assets/b0facf3d-3ee7-4ed7-9bb9-1eb958751f95) |
- Check out this PR or use the internal preview link
- Create a Linode or use an existing Linode in a core region
- Select the Linode on the images create page (http://localhost:3000/images/create/disk)
- Verify there is no notice saying `Images are not encrypted`
<details>
<summary> …

change: [M3-9041] - Remove `Images are not encrypted` warning

---

packages/manager/.changeset/pr-11460-fixed-1735030571347.md
packages/manager/src/store/selectors/getSearchEntities.ts

This PR resolves the bucket size discrepancy in CM by converting the frontend display of Object Storage bucket sizes to the **correct decimal size** unit, ensuring consistency and avoiding confusion.
- Fixed bucket size unit discrepancy in CM (converted to **Decimal Unit**).
N/A
| ![Before](https://github.com/user-attachments/assets/8add11b7-6f3a-4ef3-89d7-6f5c90a844c6) | ![After](https://github.com/user-attachments/assets/7a6e3436-18fb-4b36-bf1b-7f8d4e4ea984) |
| ![Before](https://github.com/user-attachments/assets/6356f930-0f72-4b93-a4e5-592c1618f778) | ![After](https://github.com/user-attachments/assets/fefbd8e9-e575-4864-89a1-0b3a2fe3ef52) |
- Ensure necessary permissions for managing Object Storage Buckets.
- Create a bucket and add an object.
- …

fix: [M3-9049] - Resolve bucket size discrepancy in CM

---

packages/manager/.changeset/pr-11436-upcoming-features-1734526137538.md
packages/manager/src/featureFlags.ts
packages/manager/src/features/IAM/IAMLanding.tsx
packages/manager/src/features/IAM/Shared/NoAssignedRoles/NoAssignedRoles.test.tsx
packages/manager/src/features/IAM/Shared/constants.ts
packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
packages/manager/src/features/IAM/index.tsx

Prevent routing to non-existent and invalid URLs, such as:
`/iam/invalid`,
`/iam/invalid/page`,
`/iam/users/invalid/page`,
`/iam/roles/invalid`,
`/iam/roles/invalid/page`,
`/iam/users/{username}/invalid`,
`/iam/users/{username}/invalid/page`,
`/iam/users/{username}/details/invalid`,
`/iam/users/{username}/details/invalid/page`,
`/iam/users/{username}/roles/invalid`,
`/iam/users/{username}/roles/invalid/page`,
- change url from `/iam/users/{username}/resources` to `/iam/users/{username}/entities`
1/14/25 (dev)
- Use urls from the description
<details> …

fix: [UIE-8350] - IAM RBAC: Fix Invalid routes are accessible

---

packages/manager/.changeset/pr-11464-upcoming-features-1735566884863.md
packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.test.ts
packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.test.tsx

Testing for widget components in ACLP has been improved by addition of unit tests.
- Added exhaustive unit tests for CloudPulse widget files namely [CloudPulseWidget](https://github.com/linode/manager/tree/develop/packages/manager/src/features/CloudPulse/Widget), [CloudPulseWidgetUtils](https://github.com/linode/manager/blob/develop/packages/manager/src/features/CloudPulse/Utils/CloudPulseWidgetUtils.ts),  and [CloudPulseLineGraph](https://github.com/linode/manager/blob/develop/packages/manager/src/features/CloudPulse/Widget/components/CloudPulseLineGraph.tsx).
14- Jan -2025
N/A
N/A
<details>
➕ …

upcoming: [DI-21812] - ACLP unit tests for widget components

---

packages/manager/.changeset/pr-11458-tests-1734984299850.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts

This is a quick fix for the flakiness we've been seeing in the `lke-update.spec.ts` node pool tag test. The test failures are triggered when a React render occurs while Cypress is attempting to interact with the tag button in the node pool section of the LKE cluster details page.
This PR addresses the flake by 1) mocking and waiting for the ACL and Linode instance type requests to resolve and 2) waiting for the node pool table's contents to populate before interacting with the button.
With these changes in place, I was able to run the test on repeat 20 times without any failures. For comparison, on `develop` it failed 14 out of 20 times when I ran it locally.
- Wait for LKE requests to resolve before interacting with tag button
- Wait for UI to update before interacting with tag button …

test: [M3-9035] - Reduce flakiness in `lke-update` pool tag test

---

packages/manager/.changeset/pr-11450-fixed-1734717495561.md
packages/manager/.changeset/pr-11450-tests-1735836787604.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
packages/manager/src/factories/subnets.ts
packages/manager/src/features/Linodes/LinodeCreate/utilities.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/utilities.ts

Sets VPC interfaces as the primary interface when creating a Linode - [this had been lost in the refactor](https://github.com/linode/manager/blob/988469ddde3fd9464be4bb61fc22822034f4c0c1/packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx#L898). 
See internal ticket 7706 for details of investigation. This does not resolve the unrecommended config notice for already existing Linodes, just for newly created ones. Customers with this notice on their Linode will need to manually edit their configs to resolve it. 
The bug with the Linode Config Dialog should be resolved in #11424 
1/14
| ![image](https://github.com/user-attachments/assets/92eaa631-341e-4ee1-a665-faff1cbf839b) | …

fix: [M3-7706, 9005] - Set VPC interface as primary when creating a Linode

---

packages/manager/.changeset/pr-11416-fixed-1734094290557.md
packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx

This PR fixes console errors caused due to how `RegionHelperText` component is being used in some places (like in `textFieldProps`, etc) (main reason: block-level elements should not be descendants of inline-level elements)
- Keeping in-line elements descendants of block-level elements 
N/A
| ![Screenshot 2024-12-13 at 5 57 32 PM](https://github.com/user-attachments/assets/5dcd6a13-3feb-45b3-bf6a-339ee9b20fc5) |  No console errors  |
- Go to Kubernetes/Create Cluster
- Ensure no console errors
- Go to NodeBalancers/Create
- Ensure no console errors
- Ensure everything works as expected wherever `RegionHelperText` is used
<details> …

fix: [M3-8506] - `RegionHelperText` causing console errors

---

packages/manager/.changeset/pr-11475-upcoming-features-1735939864502.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx

The cluster pricing in the Kube Specs on the LKE details page for an enterprise cluster does not currently match the price that was given when creating a cluster because the LKE-E HA price ($300/month) is not factored in. We need to update this to provide consistent and accurate pricing information for LKE-E clusters.
- Updated the kube specs to correctly calculate LKE-E HA pricing ($300/month)
- Updated `lke-create.spec.ts` with test coverage for this
1/14/25
| ![Screenshot 2025-01-03 at 1 26 08 PM](https://github.com/user-attachments/assets/3c46e675-47af-4285-b96b-42a29ee3cd56) | ![Screenshot 2025-01-03 at 1 25 58 PM](https://github.com/user-attachments/assets/1fbf5dde-e920-4b79-8e44-552fe5820f3d) |
- Have the …

upcoming: [M3-9042] - Update LKE cluster details kube specs for LKE-E monthly pricing

---

packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx

Fix region validation when a user is switching from LKE to LKE-E tier in the Kubernetes create flow
| <video src="https://github.com/user-attachments/assets/139a7bac-17a1-4d21-bdb7-f7042944bd5a" /> | <video src="https://github.com/user-attachments/assets/57715543-9bd7-4802-94bd-0a88f2b304a9" /> |
- Ensure you have the customer tags for LKE-E (check project tracker)
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRI …

fix: [M3-9025] - Region validation when switching to LKE-E

---

packages/manager/.changeset/pr-11478-tests-1736180178602.md
packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts

Add coverage for checking that there is no upgrade chip when there is no new kube version available and move kube version landing page e2e tests from `lke-update.spec.ts` to `lke-landing-page.spec.ts`
```
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-landing-page.spec.ts"
```
<details>
👣 Providing comprehensive …

test: [M3-9023] - Add coverage for Kube version upgrades in landing page

---

packages/manager/.changeset/pr-11456-tech-stories-1734933761673.md
packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.test.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx
packages/manager/src/features/ObjectStorage/utilities.ts

We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries.
- Replaced `Select` with Autocomplete in `Object Storage` component. 
N/A
- Navigate to http://localhost:3000/object-storage/buckets and open details drawer
- Verify 'Access Control List (ACL)' dropdown functionality remains unchanged when using `Autocomplete`. 

refactor: [M3-6910] - Replace instances in : Object Storage

---

packages/manager/.changeset/pr-11453-fixed-1734765509208.md
packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
packages/manager/src/features/Profile/APITokens/utils.test.ts
packages/manager/src/features/Profile/APITokens/utils.ts

This is to fix the issue where the `Create Token` button becomes disabled when the child-account is hidden and all permissions are individually selected, without using select all options.
Feel free to add a Jira ticket to my PR title if you would like to.
- Fix the issue described above.
- Slightly refactor the initialization of `excludedScopesFromSelectAll` with constant values from the map.
| ![image](https://github.com/user-attachments/assets/2c89820e-e1d0-4936-acfd-5888098323df) | ![image](https://github.com/user-attachments/assets/4af5b343-1c98-45a9-a34a-98ad2f8d08c2) |
<details> …

fix: [PDI-3099] - Enable `Create Token` button if all visible permissions selected

---

package.json
packages/manager/.changeset/pr-11434-tech-stories-1734487085461.md
yarn.lock

See: https://github.com/linode/manager/security/dependabot/131
- `cookie` is being used by `msw` (Mock Service Worker) through `@bundled-es-modules`
- `cookie` is also being used by `express` which stems from `@storybook/react-vite` and `@storybook/builder-vite`
- Add cookie resolution pinning to > 0.7.0
01/14/2025
- Run `yarn why cookie` to observe dependencies and versions found in yarn.lock
- Observe:
```
=> Found "cookie@0.5.0" info Reasons this module exists    - "_project_#linode-manager#msw#@bundled-es-modules#cookie" depends on it
=> Found "express#cookie@0.6.0" info This module exists because "_project_#linode-manager#@storybook#react-vite#@storybook#builder-vite#express" depends on it.
```
- Run same commands
- Observe:
```
=> Found "cookie@0.7.2"
info Reasons this module exists …
```

deps: [M3-8782] - Patch cookie version

---

packages/manager/.changeset/pr-11472-fixed-1736174726210.md
packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx

The property name for `endpoint_type` was misspelled causing the sorting for that column not to work.
01/14/2025
- Go to `/object-storage/buckets`
- Ensure feature flag is enabled
- Ensure you have the customer tags 
- `obj_use_regions_mode`
- `obj_enable_use_endpoint_types`
- Observe that Endpoint Type sorting now works 
<details>
👣 …

fix: [M3-9060] - Object Storage `endpoint_type`  sorting

---

packages/manager/.changeset/pr-11476-fixed-1736263048231.md
packages/manager/src/components/MaskableText/MaskableText.tsx
packages/manager/src/components/MaskableText/MaskableTextArea.tsx
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ConnectionRow.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/LongviewServiceRow.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
packages/manager/src/features/Longview/shared/InstallationInstructions.styles.ts
packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
packages/manager/src/features/Managed/Contacts/ContactsRow.tsx
packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx

We overlooked a couple of older, more niche sections of Cloud Manager with the Mask Sensitive Data feature. This PR masks data in Managed and Longview.
- Name, email, primary phone, and secondary phone are maskable and toggleable on the Managed > Contacts tab
- User, IP addresses, and SSH keys are maskable and toggleable on the Managed > SSH Access tab
- API keys, contact information, user, and IP addresses are masked and toggleable on the Longview landing and the Longview client details page
1/14/25
| ![Screenshot 2025-01-06 at 11 06 27 PM](https://github.com/user-attachments/assets/a633fa4c-d02e-4856-9595-101472e385ee) | ![Screenshot 2025-01-06 at 11 05 23 PM](https://github.com/user-attachments/assets/0a873626-33fb-4783-9b11-b10f56bbb39c) |
| …

fix: [M3-9024] - Mask sensitive data in Managed and Longview

---

packages/manager/src/MainContent.tsx
packages/manager/src/Root.styles.ts
packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/components/PrimaryNav/PrimaryNavToggle.tsx
packages/manager/src/components/PrimaryNav/SideMenu.test.tsx
packages/manager/src/components/PrimaryNav/SideMenu.tsx
packages/manager/src/components/PrimaryNav/constants.ts
packages/manager/src/components/PrimaryNav/utils.ts
packages/manager/src/features/Footer.tsx

[CDS Updates] - Handle cds sticky sidebar

---

packages/manager/.changeset/pr-11486-tests-1736284627318.md
packages/manager/cypress/e2e/core/images/search-images.spec.ts
packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-add-ons.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-ssh-key.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-user-data.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts
packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
packages/manager/src/factories/linodes.ts

This seeks to fix the Cypress test failures we're seeing on end-to-end tests which create Linodes. The failure was triggered by a backend change making the Debian 10 Image unavailable. This seeks to fix the test failures by updating our `linodeFactory` and `createLinodeRequestFactory` factories to use Debian 12 by default.
- Use Debian 12 for Linode factories
- Replace various references to Debian 10 in the test suites
ASAP since these failures are causing our E2E tests to be more or less unusable.
We can rely on CI for this. I'm half expecting there to be some lingering failures that still need to be addressed after this first pass since this is a pretty broad change across a lot of tests.
<details>
👀 …

test: [M3-9072] - Fix test failures by using Debian 12 for test Linodes by default

---

packages/manager/.changeset/pr-11428-tech-stories-1734382681885.md
packages/manager/src/dev-tools/load.ts
packages/manager/src/features/Events/FormattedEventMessage.tsx
packages/manager/src/features/Events/factories/domain.tsx
packages/manager/src/mocks/mockState.ts
packages/manager/src/mocks/presets/baseline/crud.ts
packages/manager/src/mocks/presets/crud/domains.ts
packages/manager/src/mocks/presets/crud/handlers/domains.ts
packages/manager/src/mocks/presets/crud/seeds/domains.ts
packages/manager/src/mocks/presets/crud/seeds/index.ts
packages/manager/src/mocks/presets/crud/seeds/utils.ts
packages/manager/src/mocks/types.ts
packages/manager/src/mocks/utilities/events.ts

Straight forward PR to add domains to CRUD mode (including seeds)
- Add `domains` CRUD mode 
- Add `domains` seed
- Fix small eventing display bug with "Import a zone" events
- Reset all MSW 
- Play with domains crud mode (including seeding)
<details> …

tech-story: [M3-9017] - Add MSW crud domains

---

packages/manager/.changeset/pr-11485-fixed-1736282505902.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx

Due to the way that existing code was written, we were only returning Kubernetes API endpoints for clusters if the endpoint matched port 443 (e.g. `/linodelke\.net:443`). However, LKE-E endpoints use the `6443` port so nothing was returning
This PR adds a check to render the first available endpoint if port 443 is not available
- Render the first available endpoint if endpoint with port 443 is not available
- Added some unit tests
| ![image](https://github.com/user-attachments/assets/f8c680b3-c095-4386-93f3-1fa406243db2) | ![image](https://github.com/user-attachments/assets/5fc57cfa-3a09-42e7-af50-559e24008ca6) |
- Ensure you have LKE-E customer tags (check project …

fix: [M3-9063] - Display Kubernetes API endpoint for LKE-E cluster

---

packages/manager/.changeset/pr-11481-changed-1736250933443.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.utils.tsx

Disable plans when the usable storage equals the used storage of the database cluster
- Disable plans when storage equals usage
- Refactoring
01/14/2025
| ![Screenshot 2025-01-03 at 2 44 14 PM](https://github.com/user-attachments/assets/e128ab60-3c20-4554-9a64-11335b49d6e5) | ![Screenshot 2025-01-03 at 2 43 56 PM](https://github.com/user-attachments/assets/7a9f080c-5b0d-4314-b054-30587c01017c) |
- select a database cluster
- navigate to the Resize tab
- plans with usable storage equal to the used storage of the database cluster are disabled
<details>
➕ …

change: [UIE-8228] - Database Resize: disable same size plan

---

packages/manager/src/components/DatePicker/DateTimeRangePicker.test.tsx

This attempts to fix a unit test failure in `DateTimeRangePicker.test.ts` when the test is run in an environment whose system locale is not set to central time (UTC-06:00). Also does some clean up related to the way that the system time is mocked.
Opening this so it's ready in case the unit test failure blocks our release and can point this to the release in that case (cc @hana-akamai), but otherwise no rush to review/merge this.
- Fix test failure in DateTimeRangePicker unit tests
- Clean up
Possibly 1/14, otherwise N/A
```bash
yarn test DateTimeRangePicker.test
```
<details>
➕ Adding a …

test: Fix `DateTimeRangePicker` unit test failure

---

packages/manager/.changeset/pr-11500-fixed-1736439852730.md
packages/manager/src/components/DeletionDialog/DeletionDialog.stories.tsx
packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
packages/manager/src/components/TypeToConfirm/TypeToConfirm.test.tsx
packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
packages/manager/src/features/Domains/DeleteDomain.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
packages/manager/src/features/Profile/Settings/TypeToConfirm.tsx

There is an edge case where `preferences?.type_to_confirm` is `undefined` when the user has not yet set a preference as seen in `/profile/settings?preferenceEditor=true`. 
- Ensure that `preferences?.type_to_confirm` resolves to a boolean value (default true)
01/14
| ![localhost_3000_linodes (1)](https://github.com/user-attachments/assets/d8523b48-ce45-45cf-a033-fc943742d0e2) | ![localhost_3000_linodes (2)](https://github.com/user-attachments/assets/0dbec815-3cdd-4e03-9dc3-5a65e1b3b182) |
- Removed `type_to_confirm` preference from /profile/settings?preferenceEditor=true
- Observe the disabled button for linode deletion dialogs and others
- Removed `type_to_confirm` preference from /profile/settings?preferenceEditor=true
- Ensure type-to-confirm …

fix: Preferences type_to_confirm being undefined no longer causes button to be disabled

---

packages/manager/.changeset/pr-11483-tech-stories-1736333190430.md
packages/manager/src/components/OrderBy.tsx
packages/manager/src/components/Tags/Tags.tsx
packages/manager/src/features/Domains/DomainActionMenu.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigActionMenu.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
packages/manager/src/features/Search/ResultGroup.tsx
packages/manager/src/utilities/splitAt.test.ts
packages/manager/src/utilities/splitAt.ts

Remove instances of splitAt from Ramda and replace them with a custom utility function.
Since the `splitAt` utility from Ramda is used in multiple places throughout the codebase + we aim to eliminate any dependency on Ramda, it is more efficient and maintainable to replace it with a custom utility function.
- Created a custom `splitAt` utility function
- Added unit tests for the new utility function
- Replaced all instances of Ramda's `splitAt` with the custom utility.
N/A
- Ensure no existing functionality is broken
- Make sure all the instances of `splitAt` ramda has been replaced with the custom utility
<details> …

refactor: [M3-8246, M3-8252] - Replace Ramda's `splitAt` with custom utility

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Kubernetes/ClusterList/constants.ts
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx

https://github.com/linode/manager/pull/10578 updated the "Add Node Pools" section on the LKE Create page when LDE is enabled to state that the maximum number of linodes per node pool is 250. However, this is incorrect; the max per node pool is still 100, but the max per cluster is 250. This PR updates the copy to be clearer and more explicit. More details included in the ticket.
1/14/25
| Linode Disk Encryption (LDE) disabled | Linode Disk Encryption (LDE) enabled |
| ![Screenshot 2025-01-13 at 6 08 25 PM](https://github.com/user-attachments/assets/4caef118-babf-4418-85cc-7aaaef6cfe93) | ![Screenshot 2025-01-13 at 6 08 09 PM](https://github.com/user-attachments/assets/3969b7f3-65f0-4eb8-a322-118da9ddebce) |
Toggling the `Linode Disk Encryption (LDE)` flag on and off …

fix: [M3-9086] – Revise description of "Add Node Pools" section on LKE Create page

---

packages/manager/.changeset/pr-11505-tech-stories-1736510197103.md
packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx

Ramda should be completely removed/replaced with native JS equivalent
- Removed ramda from `CreateDomain.tsx` and replaced them with native JS equivalent
N/A
- Ensure no existing functionality is broken
<details>
🕛 Scheduling a pair …

refactor: [M3-8252] - Remove ramda from `CreateDomain.tsx`

---

packages/api-v4/.changeset/pr-11515-changed-1736786729001.md
packages/api-v4/src/nodebalancers/types.ts
packages/manager/.changeset/pr-11515-upcoming-features-1736787005749.md
packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
packages/manager/src/features/NodeBalancers/utils.ts
packages/validation/.changeset/pr-11515-changed-1736786649145.md
packages/validation/src/nodebalancers.schema.ts

- This PR aims to improve the UDP NodeBalancer experience after the initial merge of https://github.com/linode/manager/pull/11405
- This fixes some things that were caught now that we can test against the API in dev
- Use the `dev` environment
- Add the `nb-udp-alpha` customer tag to your account (or ask me to do it for you if you don't have access)
- Test the create nodebalancer and update nodebalancer flow with the UDP protocol
- Verify general UDP functionality works
<details>
🧪 …

upcoming: [M3-9084] - Handle edge cases with UDP NodeBalancer

---

packages/manager/.changeset/pr-11508-tests-1736539546177.md
packages/manager/cypress/component/components/password-input.spec.tsx
packages/manager/src/components/PasswordInput/HideShowText.stories.tsx
packages/manager/src/components/PasswordInput/PasswordInput.stories.tsx
packages/manager/src/components/PasswordInput/StrengthIndicator.stories.tsx

- Adds component tests for the PasswordInput component to tests its interactions
- mainly been using yarn cy:debug and selecting component tests to check these tests
<details>
♿ …

test: [M3-8692] - Component tests for PasswordInput

---

packages/manager/.changeset/pr-11489-tests-1736348080190.md
scripts/junit-summary/formatters/slack-formatter.ts
scripts/junit-summary/util/cypress.ts

This fixes an issue in our Slack and GitHub notifications for Cypress tests. When more than one failure occurs in the spec, the `yarn cy:run` command in the notification lists the spec multiple times.
Additionally, this reduces the number of failures listed in our Slack notification from 6 to 4. This should help reduce the risk of our notification messages getting truncated.
- Only list a spec file once in command output when multiple tests in the spec fail
- Reduce the max number of specs listed in Slack notification from 6 to 4
N/A
------ | ------- |
| ![Screenshot 2025-01-08 at 9 40 01 AM](https://github.com/user-attachments/assets/2e384bf9-eb1b-4ae6-ba9e-bfc9623022b2) |  |
| ![Screenshot 2025-01-08 at 9 43 …

fix: [M3-9073] - Fix duplicate specs in Cypress Slack / GH notifications

---

packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx

- Cleans up one-off styles in `KubernetesClusterRow` 
- Uses `Link` from `src/components/Link` rather than `react-router-dom` directly so that colors are correct
- In dark mode, the raw `react-router-dom` link is too dark
| ![Screenshot 2025-01-15 at 6 19 35 PM](https://github.com/user-attachments/assets/984e01aa-8f6f-4de3-8b0b-6c62e231794e) | ![Screenshot 2025-01-15 at 6 19 40 PM](https://github.com/user-attachments/assets/ca137e61-5e1c-4c35-a8d7-a99ae373b89c) |
- Turn on the MSW or have some LKE clusters on your account
- Verify there are no regressions to `KubernetesClusterRow` 
- Verify the chips have no regressions 🏷️ 
- Enterprise chip
- HA chip
- Version upgrade chip
<details>
❔ …

fix: [M3-9124] - Link styles in `KubernetesClusterRow` and clean up one-off styles

---

packages/manager/.changeset/pr-11526-fixed-1737034837256.md
packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
packages/manager/src/assets/icons/zoomin.svg
packages/manager/src/assets/icons/zoomout.svg
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.test.tsx
packages/manager/src/features/CloudPulse/Widget/components/Zoomer.test.tsx
packages/manager/src/features/CloudPulse/Widget/components/Zoomer.tsx

Change in color is observed when zoom-in icon is hovered over.
- Zoom-in icon will have a changed color when hovered over.
_Note_: Only the first commit is related to the actual bug fix, rest are just naming corrections. 
21 Jan 2025
| ![image](https://github.com/user-attachments/assets/04f22a90-2f3e-42a6-864a-993174a0a8cb) | ![image](https://github.com/user-attachments/assets/30739ad6-a519-479a-a494-2b3173b0291d) |
- Navigate to monitor tab, select all the filters.
- Locate zoom icon, observe the change in color while hovering. Try toggling to zoom-in/zoom-out and verify the change in color while hovering in both forms.
<details> …

fix: [DI-22875] - Zoom-in icon hover effect fix in CloudPulse

---

packages/manager/.changeset/pr-11514-tech-stories-1736784891293.md
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordActionMenu.tsx
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecords.tsx
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordsUtils.ts
packages/manager/src/features/Domains/DomainDetail/DomainRecords/generateTypes.tsx

Ramda should be completely removed/replaced with native JS equivalent
- Remove ramda from `DomainRecords` - Part 1
> [!Note]
> We will remove ramda from `/DomainRecords/DomainRecordDrawer.tsx` in Part 2, after refactoring `DomainRecordDrawer.tsx` to a functional component
- Remove ramda from:
- `/DomainRecords/DomainRecords.tsx`
- `/DomainRecords/DomainRecordActionMenu.tsx`
- `/DomainRecords/DomainRecordsUtils.ts`
- `/DomainRecords/generateTypes.tsx`
N/A
- Ensure no existing functionality is broken
<details>
➕ Adding a …

refactor: [M3-8252] - Remove ramda from `DomainRecords` (Part 1)

---

packages/manager/.changeset/pr-11402-added-1736419050008.md
packages/manager/.changeset/pr-11402-upcoming-features-1733927050433.md
packages/manager/src/features/IAM/Shared/UserDeleteConfirmation.tsx
packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.test.tsx
packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx
packages/manager/src/features/IAM/Users/UsersTable/ProxyUserTable.tsx
packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
packages/manager/src/features/IAM/Users/UsersTable/UsersLandingProxyTableHead.test.tsx
packages/manager/src/features/IAM/Users/UsersTable/UsersLandingProxyTableHead.tsx
packages/manager/src/queries/account/users.ts

IAM RBAC - users table component.
Includes the table for proxy users and the logic for deleting and filtering them, and an adding a new user.
- Table for proxy users
- Deleting users
- Adding user
1/14/25 (dev)
| 📷 | 📷 |
<details> …

feat: [UIE-8136] - IAM RBAC: add new users table component (part 2)

---

packages/manager/.changeset/pr-11536-changed-1737152603420.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
packages/manager/src/components/Encryption/Encryption.test.tsx
packages/manager/src/components/Encryption/Encryption.tsx
packages/manager/src/components/Encryption/constants.tsx

In prod at maximum viewport widths, the "Disk Encryption" section's description in the Linode Create flow has a single word that hangs on the second line. This PR revises the copy to be more concise to prevent this.
1/28/25
| Prod  | This Branch   |
| ![Screenshot 2025-01-17 at 4 43 52 PM](https://github.com/user-attachments/assets/6385085f-e8d9-422d-9e07-d88dbf2c1cce) | ![Screenshot 2025-01-17 at 4 44 03 PM](https://github.com/user-attachments/assets/1ea9ad62-b566-4f11-8e5e-d92e8d5ac701) |
Confirm what you see at the maximum viewport width matches the preview above
<details>
🤏 Splitting feature into small …

change: [M3-9132] – Revise description for "Disk Encryption" section in Linode Create flow

---

packages/manager/.changeset/pr-11529-tests-1737049089021.md
packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
packages/manager/cypress/support/constants/linodes.ts

This increases the clone timeout in our `linode-config.spec.ts` and `clone-linode.spec.ts` tests to 5 minutes in hopes of reducing the flakiness of these tests a bit.
We have a dedicated ticket (M3-8804) to continue investigating this test in case other actions are needed to completely resolve the stability issues, but hoping to get a quick win out of this in the meantime.
- Linode clone timeout increased to 5 minutes
- Linode create timeout in clone test increased to 5 minutes
N/A
`yarn && yarn build && yarn start:manager:ci`, and then `yarn cy:run -s "cypress/e2e/core/linodes/clone-linode.spec.ts,cypress/e2e/core/linodes/linode-config.spec.ts"`
I'll probably run this in CI a few times to see how effective the changes are. If they aren't effective at all, I'll close the ticket.
👀 Doing a …

test: [M3-9131] - Increase Linode clone timeout to 5 minutes

---

packages/manager/.changeset/pr-11539-upcoming-features-1737537564184.md
packages/manager/src/features/IAM/Users/UserDetails/DeleteUserPanel.tsx
packages/manager/src/features/IAM/Users/UserDetails/UsernamePanel.tsx
packages/manager/src/features/IAM/Users/UsersTable/CreateUserDrawer.tsx

Fix redirects from `/account/` to `/iam/` when editing the username or deleting the user.
- small adjustment in the `CreateUserDrawer`
- fix redirects from `/account` to `/iam`
1/28/25 (dev)
| 📷 | 📷 |
- Click on the any username in the users table and go to the tab Assigned Roles or click on the user's menu View User Roles
- Edit username or delete the user
(How to reproduce …

fix: [UIE-8386] - IAM RBAC: fix redirects to old route

---

packages/manager/.changeset/pr-11544-added-1737522840655.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelectionTable.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
packages/manager/src/features/components/PlansPanel/PlanContainer.tsx
packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx
packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx

This PR brings GPU plans to the LKE create flow.
GPU plans for LKE have already been made available through the API, but not in Cloud Manger which has broken service parity between the API consumers.
This task implements a new GPU tab within the LKE create flow to provide the ability to create clusters with the GPU class. It mirrors the existing look and functionality (UI + UX) of the linode create flow plan selection, inclufing the split table (new ADA plans VS legacy RTX plans).
- Add new GPU tabs in the kubernetes create flow and cluster details 'Add Node Pool' flow
- Implement associated display logic
- disabled plans
- notices
- split table (ADA vs RTX)
- Provide/consolidate e2e tests with new plans
⚠️   **01/28/2025**
| ![Screenshot …

feat: [M3-9158] - Add GPU plans support for LKE in Cloud Manager

---

packages/manager/.changeset/pr-11561-tests-1737675052334.md
packages/manager/.changeset/pr-11561-tests-1737675335132.md
packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
packages/manager/cypress/support/plugins/configure-browser.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx

- An attempt to fix our failing Cypress test that run in Github Actions
- I believe the issue was caused by a chrome update. It seems the issue started happening on runs that use Chrome 132 ([example](https://github.com/linode/manager/actions/runs/12937051157/job/36084103538)). Things worked on Chrome 131 ([example](https://github.com/linode/manager/actions/runs/12894576526/job/35953896429)).
- Chrome 132 no longer supports the old headless mode according to [this post](https://developer.chrome.com/blog/removing-headless-old-from-chrome#:~:text=We're%20happy%20to%20announce,runs%20the%20new%20Headless%20mode.) so this PR removes the old headless mode flag we were using
- This issue is not happening in our Jenkins cypress pipeline because that uses an older Chrome version that I believe is …

fix: Cypress tests failing in Github Actions, fix `resize-linode.spec.ts` failure, address `DatabaseBackups.test.tsx` flake

---

docs/tooling/analytics.md
packages/manager/.changeset/pr-11564-tech-stories-1737743829459.md
packages/manager/src/hooks/usePendo.ts
packages/manager/src/utilities/analytics/utils.test.ts
packages/manager/src/utilities/analytics/utils.ts

This PR enables the Pendo analytics script based on the OneTrust cookie consent granted by the user in their cookie preferences. If users disable performance cookies, the Pendo script will not load.
Once we release this change to production, we _should_ be able to change a setting in our Pendo app subscription that has disabled cookies and client side storage use. The Login team needs cookies enabled on our subscription to allow for journey tracking between the anonymous users on Login and Cloud Manager's users. 
> [!NOTE]
> Confirming one thing with MADS about OneTrust and default opt-ins vs. opt-outs by geolocation (to make sure I don't have to handle anything else here) before I merge.
> ✅  **Confirmed:** For non GDPR countries, the user is opted in via OneTrust unless they choose to …

change: [M3-9159] - Enable Pendo based on OneTrust cookie consent

---

packages/manager/.changeset/pr-11571-tests-1738095531248.md
packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-summary-page.spec.ts

Add integration tests for viewing and downloading the kubeconfig file from the /kubernetes/clusters/<id>/summary page.
Added tests to packages/manager/cypress/e2e/core/kubernetes/lke-summary-page.spec.ts  
-yarn cy:run -s "packages/manager/cypress/e2e/core/kubernetes/lke-summary-page.spec.ts" 
👣 Providing comprehensive …

test: [M3-8998] - LKE view/download Kubeconfig from summary page

---

packages/manager/.changeset/pr-11560-tests-1737658018185.md
packages/manager/cypress/e2e/core/objectStorageGen2/bucket-access-keys-gen2.spec.ts
packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts

Integration tests for M3-7511 and M3-9147 (avoiding internal linkage on the public repo as a security best practice). When user navigates to object-storage/buckets/create, the label and region inputs are disabled. When user navigates to object-storage/access-keys/create, the label and region inputs as well as the Create button are disabled. 
- Added integration tests to packages/manager/cypress/support/intercepts/object-storage.ts. 
```
yarn cy:run -s "cypress/e2e/core/objectStorageGen2/bucket-access-keys-gen2.spec.ts,cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts"
```
➕ Adding a …

test: [M3-7511, M3-9147] restricted user has disabled inputs on object storage creation

---

packages/manager/.changeset/pr-11473-tests-1737472486457.md
packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
packages/manager/cypress/support/intercepts/linodes.ts

Add test to check Cloud Manager can handle cloning a Linode that has `null` type gracefully.
- Add `mockCloneLinode` function
- Add test `can clone a Linode with null type`
```
yarn cy:run -s "cypress/e2e/core/linodes/clone-linode.spec.ts"
```

test: [M3-8895] - Add Cypress test to check Linode clone with null type

---

packages/api-v4/.changeset/pr-11584-added-1738172957966.md
packages/api-v4/src/regions/types.ts
packages/manager/.changeset/pr-11584-tech-stories-1738170829685.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/utilities/linodes.test.ts
packages/manager/src/utilities/linodes.ts

- Adds a feature flag for the Linode Interfaces project 🔌 🏴 
- The flag is just a `BaseFeatureFlag` for now, but we will likely extend `BaseFeatureFlag` with more properties as this project evolves
- Adds initial `useIsLinodeInterfacesEnabled` hook 🎣 
- This is just acts as a useful abstraction over the flag and customer tags
- Opening this PR now so that we can begin building out the UI behind a flag 
- Nothing to test in the UI! Just verify the code looks correct and doesn't make any crazy errors
- Verify the unit test brings value
- It is basic for now, but it will be nice to have once this project gets a bit more complex
<details>
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING …

feat: [M3-9092] - Add Feature Flag for Linode Interfaces

---

packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
packages/manager/src/features/TopMenu/SearchBar/SearchSuggestion.tsx
packages/manager/src/layouts/Logout.tsx
packages/manager/src/utilities/errorUtils.ts

Removed instances of `pathOr` from Ramda and replace them with a custom utility function.
Since the `pathOr` utility from Ramda is used in multiple places throughout the codebase + we aim to eliminate any dependency on Ramda, it is more efficient and maintainable to remove/replace it with a custom utility function.
> [!NOTE]
> There are a large number of files that have been using Ramda's `pathOr`. Hence, I've broken this into 2 parts. [Part 1 [here](https://github.com/linode/manager/pull/11512)]
- Removed instances of Ramda's `pathOr` and replaced it with inbuilt functionality.
<details>
➕ …

refactor: [M3-8253] - Replace pathOr ramda function with custom utility - Part 2

---

packages/manager/.changeset/pr-11587-tech-stories-1738221754635.md
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawer.tsx
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawerUtils.test.tsx
packages/manager/src/features/Domains/DomainDetail/DomainRecords/DomainRecordDrawerUtils.tsx

Ramda should be completely removed/replaced with native JS equivalent
- Remove ramda from `DomainRecords` - Part 2
- Follow-up to:
- https://github.com/linode/manager/pull/11514
- https://github.com/linode/manager/pull/11538
- Remove 🧹 ramda from:
- `/DomainRecords/DomainRecordDrawer.tsx`
- `/DomainRecords/DomainRecordDrawerUtils.tsx`
- Remove duplicate `ttl_sec?: number;` from `EditableDomainFields` type
- Add unit tests for `filterDataByType` 🧪
N/A
- Ensure no existing functionality is broken
- Verify all `Create/Edit` Domain Record Drawer flows work as expected
- Ensure the Domain Record Drawer title is displaying correctly for each record type as expected
- Test `Create/Edit` for `SOA`, `NS`, `MX`, `A/AAAA`, `CNAME`, `TXT`, `SRV`, `CAA` records and `Tags`
- Open both …

refactor: [M3-8252] - Remove ramda from `DomainRecords` (Part 2)

---

packages/manager/.changeset/pr-11577-upcoming-features-1738089050033.md
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
packages/manager/src/features/CloudPulse/Alerts/constants.ts
packages/manager/src/mocks/serverHandlers.ts

Added the following features to the Alerts Listing component
- Pagination
- Ordering
- Searching (Alert label)
- Filtering (Service type, Status)
- Moved the table to `AlertListTable` from `AlertListing` component 
- Implemented filtering, searching logic in the `AlertListing` component
- Unit Tests for all the Components
- Moved the `Create Alert` button from the `AlertsLanding` component to `AlertListing` component as per latest UX mockups
- Minor changes in `serverHandler.ts`, `constants.ts` files relevant for functionalities
:lock: Use the [Mask Sensitive …

upcoming: [DI-23105] - Listing Alerts features: Pagination, Ordering, Searching, Filtering

---

packages/api-v4/.changeset/pr-11590-added-1738256458071.md
packages/api-v4/src/account/types.ts
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11590-added-1738256866553.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseStatusDisplay.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/manager/src/features/Events/factories/database.tsx
packages/manager/src/mocks/serverHandlers.ts

DBaaS migrate event notification
- added a new states: 'Migrating', 'Migrated', that are displayed for the cluster
- added an event notification under the bell icon with a message about the migration status 
2/11/25
|  | ![Screenshot 2025-01-30 at 5 54 13 PM](https://github.com/user-attachments/assets/381a88cd-3407-4564-a239-97c97aea7eb8) |
|  | ![Screenshot 2025-01-30 at 5 46 57 PM](https://github.com/user-attachments/assets/a68dfadf-1458-4c0f-82f3-876dbb1f8c64) |
- When the migration process starts, the database status will change to "Migrating", and a new event notification will appear under the bell icon indicating that the migration is in progress.
- Once the migration is …

feat: [UIE-8372] - database migration event notification

---

packages/manager/.changeset/pr-11592-fixed-1738326763592.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
packages/ui/src/components/CircleProgress/CircleProgress.tsx

This PR addresses issues with the `Copy Token` behavior on k8s Details Page
- Fixed the behavior of the `Copy Token` feature
- Ensured consistent spacing for KubeConfig items
- Removed unnecessary inline styles
- Added missing `{...rest}` additional props to the CircleProgress component when the `size` prop is provided
N/A
| Before  | After  |
| <video src="https://github.com/user-attachments/assets/d4f8fe00-a9e4-4eb3-b075-e582cbdf1385" />  | <video src="https://github.com/user-attachments/assets/c4a245d4-a072-44d0-8300-07cdff488d71" /> |
| ![Screenshot 2025-01-31 at 6 30 57 PM](https://github.com/user-attachments/assets/f61ef01c-935d-4d86-ba26-35ccfbc54307) | ![Screenshot 2025-01-31 at 6 29 06 PM](https://github.com/user-attachments/assets/07ecdd68-e16a-4e2c-8a8a-713 …

fix: [M3-9069] - Copy Token behavior on LKE details page

---

packages/manager/.changeset/pr-11595-added-1738590003764.md
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/GlobalNotifications/DatabaseMigrationInfoBanner.tsx

Database migration banner for Landing Page
- Added banner for Landing Page
2/11/25
| ![Screenshot 2025-02-03 at 2 36 57 PM](https://github.com/user-attachments/assets/cd03dd81-9b9f-4d5d-843b-bcd83c4a0ed5) | ![Screenshot 2025-02-04 at 11 56 56 AM](https://github.com/user-attachments/assets/26c23d5a-d5e7-4f8e-9b26-d2c89f827f1c) |
User should have legacy databases
- Navigate to the Database Landing Page to see the banner
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIB …

feat: [UIE-8422] - database migration banner

---

packages/manager/.changeset/pr-11599-fixed-1738615199594.md
packages/manager/src/routes/longview/longviewLazyRoutes.tsx

when going to a longview client detail (and only locally) we get a 
```
Cannot read properties of undefined (reading 'id') 
```
error. 
Interestingly, Production is unaffected and this was not an error when rerouting the features in https://github.com/linode/manager/pull/11490
- Ensure `params.id` is passed to both the base & params `EnhancedLongviewDetail` props to satisfy redux
**2/11/2025**
| ![Screenshot 2025-02-03 at 15 13 46](https://github.com/user-attachments/assets/097b3e40-fe0f-40f5-a046-48cd068143b4) | ![Screenshot 2025-02-03 at 15 14 07](https://github.com/user-attachments/assets/358c92f2-2f75-4f69-8a08-fc8250b1b12e) |
- Have a working Longview client. ex
- Create a new Linode (use Debian)
- Create a new Longview client
- Copy the …

fix: [M3-9235] - Longview Detail id param not found locally

---

packages/manager/.changeset/pr-11585-tests-1738677917619.md
packages/manager/cypress/e2e/core/account/service-transfer.spec.ts

Add test to check Service Transfers empty state.
- Add test `can display empty state when no service transfer exists`
```
yarn cy:run -s "cypress/e2e/core/account/service-transfer.spec.ts"
```

test: [M3-9142] - Add Cypress test for Service Transfers empty state

---

package.json
packages/manager/.changeset/pr-11612-tech-stories-1738701099324.md
yarn.lock

Upgrades to Vitest 3.0.5. Refer to M3-9244 for more information.
- Upgrades to Vitest 3.0.5
N/A, the sooner the better
We can rely on CI
<details> …

test: [M3-9244] - Upgrade to Vitest 3.0.5

---

packages/manager/.changeset/pr-11598-changed-1738606647435.md
packages/manager/.changeset/pr-11598-tech-stories-1738606544178.md
packages/manager/.changeset/pr-11598-tech-stories-1738606600844.md
packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx
packages/manager/src/components/RegionSelect/RegionSelect.types.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx

- Cleans up references to the `disallowImageUploadToNonObjRegions` feature flag 🏴 
- This was needed for Image Service Gen2
- It has been **enabled** for a long time so we can now safely remove the flag 🧹 
- Adds `ignoreAccountAvailability` prop to the `RegionMultiSelect` component
- This already exists on the `RegionSelect` component (done in https://github.com/linode/manager/pull/11038), but the multi-select needs it too
- This ensures the use of the "Object Storage" capability doesn't interfere with the user's ability to replicate an image to other regions
> [!note]
> No UI changes expected
- Verify users can still only upload images to regions with the "Object Storage" capability
- Verify the RegionMultiSelect in the "Manage Image Regions" drawer does not factor in account …

change: [M3-9232] - Clean up `disallowImageUploadToNonObjRegions` flag and add `ignoreAccountAvailability` prop to `RegionMultiSelect`

---

packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/components/ActionMenu/ActionMenu.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx

Fix clicking disabled delete button also collapsing/expanding the accordion. No changeset needed as this hasn't been released yet
2/11/15
| <video src="https://github.com/user-attachments/assets/96d45cd9-2c90-4eae-943d-8e8f8f659658" /> | <video src="https://github.com/user-attachments/assets/9012a7aa-b38d-4442-a613-d860610ac547" /> |
- Have a LKE or LKE-E cluster set up with 1 node pool
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-ch …

fix: Disabled button in Collapsible Node Pool Accordion

---

packages/manager/.changeset/pr-11615-upcoming-features-1738754714037.md
packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseTagsFilter.tsx
packages/manager/src/mocks/serverHandlers.ts

Updated the tags dependency and filtering based on region.
- Tags will be placed after region selection component.
- Tags will be in disabled state in case no region is selected. When a region is selected, tags will be filtered based on the region and listed in tags selection component.
11-02-2025
| ![image](https://github.com/user-attachments/assets/31e28816-38ee-4308-9497-1c72c583e390)|![image](https://github.com/user-attachments/assets/208d16f5-77b2-4930-85bc-535f356da5df)|
**Latest Flow** 👇
https://github.com/user-attachments/assets/b7429137-7956-48b0-9ae5-ca66e395346b
- Navigate to monitor tab.
- Select a dashboard.
- Tags are in disabled state if no region is selected. Select any region, tags will be enabled and …

upcoming: [DI-22941] - Update dependency and order for tags

---

packages/search/src/search.peggy
packages/search/src/search.test.ts

IAM uses Search v2 to power the users table. They noticed that it does not allow `@` and `_` in searches, which is important for usernames and emails
This PR allows more symbols to unblock the IAM team
| ![Screenshot 2025-02-05 at 10 13 53 AM](https://github.com/user-attachments/assets/1065d487-1d99-4bd8-9851-223c0520f6ae) | ![Screenshot 2025-02-05 at 10 08 39 AM](https://github.com/user-attachments/assets/ae73edc8-54dd-47d4-b5a3-3154b91855e0) |
| ![Screenshot 2025-02-05 at 10 13 41 AM](https://github.com/user-attachments/assets/cf5f72b2-8dd3-4c3a-8c8a-4d79ad8d7af1) | ![Screenshot 2025-02-05 at 10 08 16 AM](https://github.com/user-attachments/assets/27b44ac7-84da-4e49-b05e-557b6f6f5e99) |
- Using dev
- Go to http://localhost:3000/iam/users
- …

change: [UIE-8440] - Allow more symbols to be used in Search v2

---

packages/api-v4/.changeset/pr-11588-upcoming-features-1738244661751.md
packages/api-v4/src/iam/types.ts
packages/manager/.changeset/pr-11588-upcoming-features-1738244711758.md
packages/manager/src/factories/userPermissions.ts
packages/manager/src/features/IAM/Shared/AssignedEntitiesTable/AssignedEntitiesTable.test.tsx
packages/manager/src/features/IAM/Shared/AssignedEntitiesTable/AssignedEntitiesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/utilities.ts
packages/manager/src/features/IAM/Users/UserDetails/UserProfile.tsx
packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.test.tsx
packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.tsx
packages/manager/src/queries/iam/iam.ts

IAM RBAC - new assigned entities table component.
- Table for the assigned entities
- Filtering roles
do **not** include (will be introduced in the next PR):
- Any action in the action menu
- Redirecting to specific entity page by clicking on the entity name
2/11/25 (dev)
| <img width="812" alt="Screenshot 2025-01-31 at 10 33 34 AM" src="https://github.com/user-attachments/assets/3974cbe3-da31-4033-82d5-a5582c6ce05a" /> | …

feat: [UIE-8139] - IAM RBAC: add new assigned entities table component part 1

---

packages/manager/.changeset/pr-11604-fixed-1738652958345.md
packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
packages/manager/src/features/Help/SearchHOC.tsx

This PR resolves the issue of duplicate options appearing in the Help & Support search Autocomplete. Previously, duplicate results (e.g., "fedora") were displayed in the dropdown, but now they are filtered out before reaching the Autocomplete.
- Update Search filtering to remove duplicates before they reach the Autocomplete.
N/A
| ![Before](https://github.com/user-attachments/assets/407093f5-1327-434c-8c83-d0783dcbcf04) | ![After](https://github.com/user-attachments/assets/aba898ad-3c3d-41d4-b74f-710497665cff) |
<details>
➕ Adding a …

fix: [9144] - Remove duplicate options in support search

---

packages/manager/.changeset/pr-11628-fixed-1738858900211.md
packages/manager/CHANGELOG.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/features/GlobalNotifications/DatabaseMigrationInfoBanner.tsx

Fix for Timezone Display Inconsistency During Restore Backup
- Updated the date-time picker to consistently show times in UTC
- Prevented restoring from a timestamp in the future
- Ensured the time selected for restoration will always be in UTC
2/11/25
| ![Screenshot 2025-02-06 at 5 01 24 PM](https://github.com/user-attachments/assets/d340e22f-ee13-4818-84cb-3acbbc911a6f) | ![Screenshot 2025-02-06 at 5 01 05 PM](https://github.com/user-attachments/assets/c892095e-ad7a-496b-9403-2cff9582dcaf) |
| ![Screenshot 2025-02-06 at 5 02 08 PM](https://github.com/user-attachments/assets/8c4f3f6e-dd80-4597-a6c2-19e3086061a8) | ![Screenshot 2025-02-06 at 5 02 19 PM](https://github.com/user-attachments/assets/cdfc3d32-8460-4b63-95ac-64103add6f5d) |
- Navigate …

fix: [UIE-8446] - restore backup date and time fix

---

packages/manager/.changeset/pr-11631-added-1738936959631.md
packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx
packages/manager/src/features/CloudPulse/Utils/constants.ts

Changed preference key for date time range picker because preference saved with previous time range select has different structure to save preference and it may impact user experience who are first time using date time range picker with preferences have data from older time range select.
1. Updated constants to change values of TIME_DURATION
10 Feb
Error because of bug
- ...
- ...
1. Go to cloud.linode.com/monitor/dashboards.
2. Change value in time range dropdown and see the request data in network tab for preferences api
3. You'll see its value for timeDuration key is a string value based on previous time range select but with new date time range picker it should be …

fix: [DI-23411] - Updated preference key for date time range picker

---

packages/manager/.changeset/pr-11634-tech-stories-1739173865935.md
packages/manager/.eslintrc.cjs
packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
packages/manager/cypress/e2e/core/notificationsAndEvents/notifications.spec.ts
packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
packages/manager/src/features/Events/EventRow.tsx
packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotificationMessage.tsx
packages/manager/src/features/NotificationCenter/Notifications/NotificationCenterNotifications.tsx
packages/ui/.changeset/pr-11634-tech-stories-1739192088418.md
packages/ui/.eslintrc.json

Replace `data-test-id` attributes with `data-testid` and add eslint rules
We have a lot of erroneous `data-test-id` attributes defined throughout the codebase. These don't offer the same compatibility with Testing Library's functions and should be replaced with `data-testid` to avoid confusion.
- Replace `data-test-id` attributes with `data-testid`
- Add eslint rules (in `manager` and `ui` package) for:
- Disallow the use of `data-test-id` attribute
- To use the type-safe equality operators 
N/A
- Ensure any violations of the new rules trigger warnings/errors in your IDE
- To confirm if unit tests pass:
Run `yarn test`
- To confirm if E2E tests pass:
Rebuild and serve Cloud Manager by running `yarn && yarn build && yarn start:manager:ci`, then in …

refactor: [M3-9130] - Replace `data-test-id` attributes with `data-testid` and add eslint rules

---

packages/manager/.changeset/pr-11620-tech-stories-1738782536719.md
packages/manager/src/layouts/Logout.tsx
packages/manager/src/layouts/OAuth.test.tsx
packages/manager/src/layouts/OAuth.tsx

In order to reroute Accounts, we should convert our old layouts (logout, oAuth) components to functional components. It's not 100% needed, but the more class component we can get rid of the better off we are for future refactors and/or framework updates. 
Since those are sensitive areas of the application it is not a bad idea to isolate changes.
It will also reduce the scope of any future refactors, including removing redux - CC @bnussman-akamai 
- Convert `<Logout.tsx />` & OAuth.tsx to functional components
- Add missing props for test to succeed as it did previously
Nothin' here
- Ensure proper log out of user and clearing of local storage tokens
- Confirm tests are passing (units & e2e)
<details> …

Refactor: [M3-9249] - Convert Logout and OAuth to functional components

---

packages/api-v4/src/account/types.ts
packages/manager/.changeset/pr-11640-upcoming-features-1739304484421.md
packages/manager/src/factories/accountSettings.ts
packages/manager/src/features/Account/GlobalSettings.tsx
packages/manager/src/features/Account/NetworkInterfaceType.test.tsx
packages/manager/src/features/Account/NetworkInterfaceType.tsx
packages/ui/src/components/Accordion/Accordion.tsx

- Adds network Interface type accordion to account settings
- type cleanup in api package
- Confirm Network Interface Type paper is hidden when feature flag is disabled
- When flag is enabled, confirm clicking 'save' sends a request with the expected payload (note: the `interfaces_for_new_linodes` field isn't populated in the returned AccountSettings object yet...)
- NOTE: there may still be some tweaks to the accordion's final design 
<details>
🔐 …

upcoming: [M3-9104] - Implement Network Interfaces accordion in Account Settings

---

packages/manager/.changeset/pr-11627-removed-1738841591644.md
packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
packages/manager/cypress/support/ui/locators/linode-locators.ts
packages/manager/src/features/Account/CloseAccountSetting.test.tsx
packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx
packages/ui/src/components/Button/Button.tsx

This PR removes the `<span>` component from the children of the Button component. This change will make it easier for test selectors to locate button elements without having to first find the `<span>` and then locate the closest button.
- Remove `<span>` from Button component children to simplify test selector targeting.
N/A
<details>
👣 …

refactor: [M3-6675] - Remove span from button component

---

packages/manager/.changeset/pr-11643-upcoming-features-1739246456461.md
packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-dashboard-errors.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.test.tsx
packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
packages/manager/src/features/CloudPulse/Utils/FilterBuilder.test.ts
packages/manager/src/features/CloudPulse/Utils/FilterBuilder.ts
packages/manager/src/features/CloudPulse/Utils/FilterConfig.ts
packages/manager/src/features/CloudPulse/Utils/constants.ts
packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseComponentRenderer.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardFilterBuilder.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseNodeTypeFilter.test.tsx
packages/manager/src/features/CloudPulse/shared/CloudPulseNodeTypeFilter.tsx
packages/manager/src/mocks/serverHandlers.ts

Updated the node type filter selection from static to dynamic.
- Node type filter selection is made dependent on database cluster selection, if the maximum cluster size of selected clusters is one, we will have primary as the only option listed and if cluster size > 1, we will have both primary and secondary listed in our options.
- Preferences will be saved and retained after node type selection
- In contextual view, default node type selection is primary as before, but the options are now limited based on the cluster size as same as centralized view.
_**Note**: After selecting a cluster, if another cluster is added or any existing selection is removed, the node type will clear. There is no change in this functionality._
25-02-25
=>Node type …

upcoming: [DI-21796] - Make node type filter dynamic based on cluster size

---

packages/manager/.changeset/pr-11644-tests-1739256775104.md
packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.test.ts

Add `Payment` generation tests for PdfGenerator.ts
- Follow-up to #11625 
- Add `payment` generation unit tests
N/A
- Run `yarn test PdfGenerator.test.ts`
<details>
📱 Providing mobile …

test: [M3-9251] - Add payment generation tests for PdfGenerator.ts

---

packages/manager/.changeset/pr-11591-tests-1738598203085.md
packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
packages/manager/cypress/support/util/one-click-apps.ts

Refactor tests for one-click-apps to improve reliability. 
- Use random app from list of OCAs, instead of always using the first one
-"Fix" string input from OCA descriptions by replacing HTML special entities (such as "&amp;") with the html character ("&" in this case). Replacing only the ampersand and registered trademark entities for now, bc those are the only entities used in the descriptions in src/features/OneClickApps/oneClickApps.ts. 
-yarn cy:run -s "packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts"
Tests sporadically fail. The tests in the current develop branch will certainly fail if you hardcode the 2nd and 3rd tests in packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts to use a OCA …

test: [M3 8035] - Refactor Marketplace App (OCA) Cypress test

---

packages/manager/.changeset/pr-11648-changed-1739310281639.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx

This PR replaces `<Box>` elements with `<StyledLinkButton>` for better accessibility and adds `aria-label`s in the KubeConfigDisplay.
- Replaced `<Box>` elements with `<StyledLinkButton>` components to improve accessibility.
- Added aria-labels to buttons for better screen reader support.
- Ensured buttons are focusable and can be triggered via keyboard navigation.
| <video src="https://github.com/user-attachments/assets/ab1754e3-d705-4ae3-b855-f13c53575ec3" /> | <video src="https://github.com/user-attachments/assets/3bdf8d37-28c3-4744-826d-aec41dc47456" /> |
- In the Kubernetes dashboard, click into the body of the page.
- Hit the tab key on your keyboard and tab through the page.
- Confirm that the Kubeconfig controls are being recognized as a …

change: [M3-9198] - Accessibility Issues with LKE Kubeconfig Buttons

---

packages/manager/.changeset/pr-11651-changed-1739400469975.md
packages/manager/.changeset/pr-11651-fixed-1739400469975.md
packages/manager/src/assets/icons/LKEminusSign.svg
packages/manager/src/components/TabbedPanel/TabbedPanel.tsx

This PR addresses two issues with the LKE plans table in the Add Node Pool flow. It ensures the `-` (minus) button appears properly disabled and gray for disabled rows, and prevents the tab from switching unexpectedly when interacting with node pool actions.
- Updated button styles to ensure the `-` button is gray and disabled when a row is disabled.
- Fixed an issue where the tab would unexpectedly switch back to the first tab after interacting with the node pool.
| <video src="https://github.com/user-attachments/assets/346ca99c-c81a-4bdd-ac7c-a2542c8711bf" /> | <video src="https://github.com/user-attachments/assets/d6631542-d8bb-4903-bc4a-758954fc5ee9" /> |
<details>
❔ Our …

change: [M3-9162] - Bugs in Plans table for LKE

---

packages/manager/.changeset/pr-11657-tests-1739428868479.md
packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts
packages/manager/cypress/support/intercepts/cloudpulse.ts

Integration tests for CloudPulse's Edit Alert Page. The tests verify that users can navigate to the Edit Alert page, update alert details, validate correct rendering of resources, regions, pagination, and ensure alert properties like channels, rules, and trigger conditions are properly displayed and updated. The tests also confirm that actions like saving, canceling, and confirming updates work correctly, with appropriate toast notifications and URL validation.
20/02/2025
https://github.com/user-attachments/assets/35a076c0-265d-4697-88e9-f12ee8ef13fe
yarn cy:run -s "cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts"
➕ Adding a …

tests: [DI-23360] - Add Cypress tests for editing system alerts in the CloudPulse application 

---

packages/api-v4/src/cloudpulse/alerts.ts
packages/api-v4/src/cloudpulse/types.ts
packages/manager/.changeset/pr-11656-upcoming-features-1739419988145.md
packages/manager/src/factories/cloudpulse/alerts.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertActionMenu.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertTableRow.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/constants.ts
packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertResources.tsx
packages/manager/src/features/CloudPulse/Alerts/Utils/AlertsActionMenu.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/cloudpulse/alerts.ts

Handle enable/disable functionality for user created alerts.
- Any user created alert which is enabled will have action menu item listed as "Disable". Similarly, every user created alert which is disabled will have action menu item listed as "Enable".
- Clicking on enable/disable button will update the status of the alert accordingly with success and error representing snackbars being displayed in both the cases.
_Note: We are waiting for the edit api update from backend to test the status update. As of now, the status update of the alert will not show as the apis are not ready yet. The current changes are tested on mock data._
25-02-25
|![image](https://github.com/user-attachments/assets/d3ce623c-f58a-4ece-a20d-6fe7fe67bf47) | …

upcoming: [DI-23310] - Handle enable/disable action item for user created alerts

---

packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardWithFilters.tsx
packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx

increased the gap between dashboard select & time range picker before the flex box wraps.
1. Updated global filters css
2. Updated CloudPulseDashboardWithFilters css.
25th Feb
|![Screenshot 2025-02-12 at 5 26 12 PM](https://github.com/user-attachments/assets/0e7693a6-8d93-4440-8bdd-a838f2ffe384)|![Screenshot 2025-02-13 at 4 18 08 PM](https://github.com/user-attachments/assets/a5194e72-9b96-4ecf-833b-01043e8223e2)|
- ...
- ...
(How to …

fix: [DI-23469] - Fix low space between dashboard select & date time range picker

---

packages/manager/.changeset/pr-11619-added-1739207937605.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/hooks/useDefaultExpandedNodePools.test.ts
packages/manager/src/hooks/useDefaultExpandedNodePools.ts
packages/manager/src/utilities/storage.ts

Improve UX of collapsible Node Pools
- Add default logic for expanded/collapsed node pools
- Added a Collapse/Expand all pools button
- Preserve user state to local storage
<details>
<summary> Preview </summary>
| Nodes Pools  | Cluster view   |
| 1 | <video src="https://github.com/user-attachments/assets/93b18092-21d7-41a1-9911-d813bc6b4e81" /> |
| 3 | <video src="https://github.com/user-attachments/assets/5bfd8277-b5c8-4735-8945-b23043eb79db" /> |
| 4 | <video src="https://github.com/user-attachments/assets/a449a163-a0e2-496b-91d8-40e185d3804e" /> |
Expand/Collapse
<video src="https://github.com/user-attachments/assets/e1f3e2ad-0e45-4ae2-8b7a-92b17c05898b" />
</details>
- Have a LKE or LKE-E cluster with multiple node pools with …

feat: [M3-9231] - Improve Node Pool Collapsing UX

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/factories/longviewDisks.ts
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
packages/manager/src/features/Longview/request.types.ts

- Fixes bug introduced in https://github.com/linode/manager/pull/11512/files#diff-668e84515a6d0c13ebc3e9be8ef065489c8c3d46c3ed2fa65c5bfed1a4b6967cR51
- A request made to the LongView API for client metrics returns a key `Uptime` which has been incorrectly mapped in CM as `uptime`. This in turn displays 'Uptime not available'. 
https://github.com/linode/manager/blob/develop/packages/manager/src/features/Longview/request.types.ts#L120-L121
- Changed the interface `Uptime` to rightly have a key `Uptime` instead of `uptime`
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/b6e116c6-a5d0-4de3-bdf3-f7e74c3d7eb4) | ![image](https://github.com/user-attachments/assets/7b3e7a93-c5f4-41db-83b4-5421c7092529)
| …

hotfix: Uptime interface for LongView API response

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/validation/CHANGELOG.md
packages/validation/package.json
packages/validation/src/kubernetes.schema.ts

We have a client-side validation error impacting the creation of valid labels. The validation was not accepting an underscore as a valid character for DNS subdomain keys.
When applying a node pool label in Cloud Manager, the attempt is rejected with the error "Labels must be valid key-value pairs". When using the same label via API the node pool is created and the label is applied correctly. 
**Note**: If unfamiliar with labels and taints, you may be asking: can we rely on the API for validation and not worry about all the complexities client-side? See [context](https://github.com/linode/manager/pull/11553#discussion_r1932990692).
- Updated the regex
- Updated test coverage to include all valid keys to ensure naming doesn't throw validation errors
2/19
| ------- | …

fix: [M3-9343] - Fix validation with LKE Node Pool Labels creation

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/package.json
packages/manager/src/factories/longviewDisks.ts
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
packages/manager/src/features/Longview/request.types.ts
packages/validation/CHANGELOG.md
packages/validation/package.json
packages/validation/src/kubernetes.schema.ts

- Uptime not displaying in Longview ([#11667](https://github.com/linode/manager/pull/11667))
- Inability to add LKE Node Pool Labels with underscore in key ([#11682](https://github.com/linode/manager/pull/11682))

Release v1.136.1 - staging → master

---

packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts

Fixes an annoying transition when collapsing a section of the `PrimaryNav`.
🎗️ No need for a changeset, just patching the unreleased CDS updates
- Remove accordion summary transition (in Primary nav only) to prevent unwanted pixel shifts on collapse
⚠️ **2/25/2025**
| <video src="https://github.com/user-attachments/assets/d131fc19-ad50-4078-a743-b5e32a24e12c" /> | <video src="https://github.com/user-attachments/assets/eae32f79-4229-4137-a5f7-e9b0937713c7" /> |
- Verify change by comparing develop branch VS this branch:
- confirm no pixel shift while collapsing PrimaryNav section
- confirm no regression to PrimaryNav
<details> …

fix: [M3-9252] - Kill `MuiAccordionSummary-root` transition in primary nav

---

packages/api-v4/.changeset/pr-11653-changed-1739986135472.md
packages/api-v4/src/nodebalancers/nodebalancers.ts
packages/api-v4/src/nodebalancers/types.ts
packages/manager/.changeset/pr-11653-added-1739985989958.md
packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
packages/manager/src/factories/account.ts
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/kubernetes.ts
packages/manager/src/queries/nodebalancers.ts
packages/manager/src/utilities/pricing/constants.ts

- Added a `Premium` indicator on the NodeBalancer details pages for HCNBs.
- Added link to LKE/LKE-E cluster on the NodeBalancer details page if the NB is associated
- Added additional pricing text to the LKE/LKE-E checkout bar
<details>
<summary> Preview </summary>
| Nodebalancer  | LKE/LKE-E | Preview  |
| Premium | No | <img src="https://github.com/user-attachments/assets/2f8560da-8324-4fd9-a36c-3d436b3d39d9" width="300" /> |
| Premium | Yes | <img src="https://github.com/user-attachments/assets/98f0dba1-abdd-4be8-9a33-8d87f77e3eb5" width="300" /> |
| Premium | Yes (deleted) | <img src="https://github.com/user-attachments/assets/729b79d9-3437-4bf9-b368-9e1b07995e1a" width="300" /> |
| Common | No | <img …

feat: [M3-9020] - LKE UI updates for checkout bar & Nodebalancer Details summary

---

packages/manager/package.json
yarn.lock

- Updates Vite from v6.0.x to v6.1.x 📦 
- We are doing this so we can use https://github.com/vitejs/vite/pull/19325
- We will use `__VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS` for our internal docker tooling 🧰 🐳 
- Verify all builds and checks succeed  ✅ 
- Verify local development works 
- Verify `yarn why vite` shows **only** v6.1.1 installed
<details>
🚩 Using a feature flag to …

chore(deps): [M3-9356] - Update to Vite v6.1.1

---

packages/manager/.changeset/pr-11692-upcoming-features-1740111658194.md
packages/manager/src/factories/cloudpulse/alerts.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsResources/AlertsResources.tsx
packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.test.ts
packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
packages/manager/src/mocks/serverHandlers.ts

Filter regions by supported region ids by passing supported regions as an xfilter.
- Region select autocomplete of alerts will have regions listed according to the supported region ids from launch darkly.
- Displayed resources will be the ones with region ids included in supported region ids.
25-02-25
**LD flag:** 
--------------------
**servicetype: 'linode' =>** 
| ![image](https://github.com/user-attachments/assets/bb59f317-0ae0-4e52-a62d-e840cd4c49c7) | ![image](https://github.com/user-attachments/assets/63f02519-786e-4dad-af7a-99a95a073aec)|
| ![image](https://github.com/user-attachments/assets/a5f690fc-e352-4fd6-afe4-6d9c464fb088)|![image](https://github.com/user-attachments/assets/5d826490-e7e5-4d5c-bb86-553fe599d807)|
In case supported …

upcoming: [DI-23317] - Filter regions by supported region ids

---

packages/api-v4/.changeset/pr-11621-upcoming-features-1738790605953.md
packages/api-v4/src/linodes/types.ts
packages/api-v4/src/regions/types.ts
packages/manager/src/factories/linodeInterface.ts

- Update region capability to 'Linode Interfaces'
- add shared field for public interface get object ipv4/ipv6
- update `addresses` field in public interface object to `slaac`
- this field has not been updated in the API yet - it will be updated soon. adding a `wait to merge` label on this PR
- confirm changes match API spec / comments in API spec
- see linked API prs in ticket
<details>
🔐 Removing all sensitive information from the code and PR …

upcoming: [M3-9210] - Update Linode Interface types as specified

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx

1. Fix y-axis overflow when a Node Pool with a table is collapsed by setting the `PaginationFooter` position to be relative
- This was caused due to the `visually-hidden` style we're applying to the footer label which has `position: absolute`, so it didn't follow the outer div's `overflow: hidden` rule
- https://stackoverflow.com/questions/4605715/position-absolute-and-overflow-hidden
2. Unmount accordion content if there are more than 25 nodes for [performance](https://mui.com/material-ui/react-accordion/#performance)
2/25
| <video src="https://github.com/user-attachments/assets/d576a234-7e26-4bb9-aee3-637f27a33914" /> | <video src="https://github.com/user-attachments/assets/ca72a8af-c442-4255-9849-c78fe7ce978b" /> |
(How to reproduce the …

fix: [M3-9360] - Collapsible Node Pool overflow bug

---

packages/api-v4/CHANGELOG.md
packages/api-v4/src/kubernetes/kubernetes.ts
packages/manager/cypress/support/intercepts/lke.ts

Updates LKE tiered version endpoints to match new API changes (see internal slack thread / apinext pr 7547 for details)
2/25
- Confirm changes match API endpoints as specified
- confirm endpoints work as expected
<details>
🕛 Scheduling a pair …

fix: Update LKE Tiered Version endpoints

---

packages/manager/.changeset/pr-11701-fixed-1740128402516.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx

When the LKE details page is viewed on mobile screens, there is an unexpected gap between the Node Pool CTAs and the right edge of the screen + *overflow issue*.
- Add action menu for `Recycle All Nodes` and `Add A Node Pool` buttons for for screens < `md`
- Some style adjustments
N/A
| ![Screenshot 2025-02-21 at 2 08 27 PM](https://github.com/user-attachments/assets/9417b2a9-b0cf-4dec-b05e-376befe244cf) | ![Screenshot 2025-02-21 at 2 13 13 PM](https://github.com/user-attachments/assets/826778ea-e778-4594-b1a0-2950e67c6e4d) |
| ![Screenshot 2025-02-21 at 2 16 44 PM](https://github.com/user-attachments/assets/2d1f6a6f-ecc5-43a6-814c-d933181017a1) | ![Screenshot 2025-02-21 at 2 17 50 PM](https://github.com/user-attachments/assets/e2374552-9ebc-46fd …

fix: [M3-9061] - Node Pools CTA Buttons on Small Screens

---

packages/utilities/package.json
yarn.lock

We have uncommitted dependency changes in our `develop` branch's `yarn.lock`. This fixes it 🩹 
When https://github.com/linode/manager/pull/11666 got merged, it was unaware of the `eslint-plugin-cloud-manager` updrade made in https://github.com/linode/manager/pull/11689, which resulted in our lock referencing two separate versions of the plugin which we don't need. 
The lock diff seems to contain another change unrelated to the explanation above, tho seems mostly semantic. Unsure where this one comes from.
On a side note, as we are pushing our migration to packages, this could become an increasing issue unless we start considering moving some core dependencies declarations to the monorepo's root.

fix: Update yarn-lock

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx

- Fixes a UI regression on the account billing page caused by the MUI v6 upgrade (https://github.com/linode/manager/pull/11688)
| ![Screenshot 2025-02-24 at 1 11 07 PM](https://github.com/user-attachments/assets/3afd7f27-a72f-4341-868d-6562fafddfb2) | ![Screenshot 2025-02-24 at 1 10 40 PM](https://github.com/user-attachments/assets/84903ebc-0c3f-4c82-b9ac-52728f084168) |
- Test the UI on http://localhost:3000/account/billing
- Turn on the MSW and verify there are no regressions when the user has a promo code in use 🎟️ 
<details>
➕ Adding a …

fix: [M3-9401] - Account Billing page regression due to MUI v6

---

packages/manager/src/components/SelectionCard/CardBase.styles.ts

- Fixes Selection Card UI regression caused by MUI v6 (https://github.com/linode/manager/pull/11688)
| ![Screenshot 2025-02-24 at 1 25 18 PM](https://github.com/user-attachments/assets/3737eb2c-3af6-4909-8384-0c6bb1cb3463) | ![Screenshot 2025-02-24 at 1 25 01 PM](https://github.com/user-attachments/assets/6d3c0b76-a6d3-426c-bf20-ca350739d0e7) |
- Check instances of the Selection Card UI component throughout the codebase
- For example, LKE Enterprise / Linode Plan on Small Screen Sizes, etc...
<details>
➕ Adding a …

fix: [M3-9400] - Selection Card UI regression caused by MUI v6

---

packages/manager/src/components/CheckoutBar/CheckoutBar.test.tsx
packages/manager/src/components/DeletionDialog/DeletionDialog.test.tsx
packages/manager/src/features/TopMenu/CreateMenu/CreateMenu.tsx
packages/ui/src/components/Button/Button.test.tsx
packages/ui/src/components/Button/Button.tsx
packages/ui/src/foundations/themes/light.ts

- Uses MUI's (newly) built-in button loading state!
- Less code and maintenance required by us
- Button no longer changes size when loading 🎉 
| ![Screenshot 2025-02-23 at 10 25 28 PM](https://github.com/user-attachments/assets/0695b0a5-c52d-4cd1-a64c-220daf714961) | ![Screenshot 2025-02-23 at 10 24 44 PM](https://github.com/user-attachments/assets/6796972a-6711-40b1-bba9-b2fbd703e1cc) |
- Check our `<Button />` throughout the application
- Check button in Storybook 📖 
- Verify is looks and works better than the current implementation
- Verify new style aligns with Akamai's Core Design System
<details>
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/docs/C …

poc: Use MUI's Button Loading State

---

packages/validation/.changeset/pr-11712-fixed-1740408470305.md
packages/validation/src/buckets.schema.ts

Cloud Manager only reports that "Label must start and end with a letter or number." without specifying they need to be lowercase.
- Cloud Manager should report that labels must start with an lowercase letter or number
3/11
- Create an OBJ bucket with `Jjj`
- Observe `lowercase` has been added to validation message
<details>
👣 Providing …

fix: [M3-9398] - Improve clarity for OBJ validation message

---

packages/manager/.changeset/pr-11714-fixed-1740421546666.md
packages/manager/.changeset/pr-11714-upcoming-features-1740421599114.md
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
packages/manager/src/queries/kubernetes.ts

This PR fixes two minor bugs that were both related to LKE requests. They are *unrelated*, but were such small changes  that I bundled them in one PR.
- **Fix 1**: Passes the missing `params` and `filter` arguments to `getKubernetesClustersBeta` queryFn, which allows us to sort the clusters table on the LKE landing page when the LKE-E feature is enabled (aka: when we use the beta endpoint)
- **Fix 2**: Enables the `useKubernetesClusterQuery` only if the Linode has a `linodeLkeClusterId` so that we don't get any 404 errors from that endpoint for non LKE-associated Linodes
3/11
|<video src="https://github.com/user-attachments/assets/138e4d73-09b3-44ab-9b2c-568c67ff9286" /> | <video src="https://github.com/user-attachments/assets/c5b1a3bf-5fe8-4c66- …

fix: [M3-9344, M3-9336] - Fix LKE-E cluster filtering bug and non-LKE linode failed request bug

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx

Customers report that they are unable to update their Billing address without entering a Tax ID which they do not have as an individual/non-business entity. This should be an optional field.
- Removed the condition that makes this required
2/25
| ![Screenshot 2025-02-25 at 1 09 16 PM](https://github.com/user-attachments/assets/f5d01cd1-b239-42a8-abd9-a95916d70ba5) | ![Screenshot 2025-02-25 at 1 08 58 PM](https://github.com/user-attachments/assets/44a435d5-a4db-45bb-97ff-0c19ddba25cb) |
- Ensure non-US users can update their contact information without a tax id
- Ensure US users can update their contact information properly 
<details> …

fix: [M3-9410] - Unable to save non-US billing contact info without tax id

---

packages/manager/.changeset/pr-11705-tests-1740407261971.md
packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts

Add test to check the warning message and disabled fields in image create page for restricted users
- Add test to check `/images/create` page
- Add test to check `images/create/upload` page
```
yarn cy:run -s "cypress/e2e/core/images/smoke-create-image.spec.ts"
```

test: [M3-9150] - Cypress test for Image create page for restricted users

---

packages/manager/.changeset/pr-11728-tests-1740514341603.md
packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts

This fixes a pair of CloudPulse E2E test failures that were triggered by the addition of the new CDS notice. This fixes the failures by asserting the contents of the notice text.
- Fix test failures by asserting notice text directly
N/A
We can rely on CI for this, but you can also confirm that the tests pass by running them locally:
```bash
yarn cy:run -s "cypress/e2e/core/cloudpulse/create-user-alert.spec.ts,cypress/e2e/core/cloudpulse/edit-system-alert.spec.ts"
```
🔐 Removing all …

test: [M3-9417] - Fix CloudPulse test failures involving notice text assertions

---

packages/manager/.changeset/pr-11362-tests-1740410848045.md
packages/manager/cypress/support/api/vlans.ts
packages/manager/cypress/support/util/linodes.ts

Improve Cypress test to handle VLAN assignment.
- Improve Cypress test that checks if a test VLAN exists for the desired region before creating a new one. If one exists, use it instead.
Run `Boots a config` test case in
```
yarn cy:run -s "cypress/e2e/core/linodes/linode-config.spec.ts"
```
No new VLAN is created when there exists one for the desired region.

test: [M3-8487] - Improve Cypress test VLAN handling

---

packages/manager/.changeset/pr-10806-tests-1725030349963.md
packages/manager/cypress/e2e/core/account/account-linode-managed.spec.ts
packages/manager/cypress/support/constants/account.ts
packages/manager/cypress/support/intercepts/account.ts
packages/manager/cypress/support/intercepts/linodes.ts

Add Cypress test to the flow of enabling account Linode Managed.
- Add Cypress test that enable Linode Managed from account settings page.
```
yarn cy:run -s "cypress/e2e/core/account/account-linode-managed.spec.ts"
```

test: [M3-8137] - Add Cypress integration test to enable Linode Managed

---

packages/manager/.changeset/pr-11663-tests-1740588226694.md
packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts

Add test to check restricted users are not allowed to create linodes in the create page.
- Add test `should not allow restricted users to create linodes`
```
yarn cy:run -s "cypress/e2e/core/linodes/create-linode.spec.ts"
```

test: [M3-9149] - Cypress test for Linode create page for restricted users

---

packages/manager/.changeset/pr-11731-fixed-1740521257689.md
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
packages/manager/src/features/components/PlansPanel/utils.test.ts
packages/manager/src/features/components/PlansPanel/utils.ts

This PR fixes an issue where RTX 6000 GPU plans were incorrectly showing up in the LKE UI when they should not be available in that context. Only RTX 4000 plans are supported in LKE, while RTX 6000 plans should be filtered out.
- Added filtering to hide RTX 6000 plans only in LKE contexts
- Updated plan selection functions to distinguish between LKE and regular Linode contexts
- Added test to verify filtering behavior
| <img src="https://github.com/user-attachments/assets/df84f9c6-9d86-45e2-8f7a-12c5cf5209ef" /> | <img src="https://github.com/user-attachments/assets/60a99e46-4d8a-4b42-8e12-b44b982b2ff1" /> |
<details> …

fix: [M3-9345] - RTX 6000 showing up in UI

---

packages/manager/.changeset/pr-11737-tests-1740586626716.md
packages/manager/cypress/e2e/core/general/account-login-redirect.spec.ts

This is intended to resolve some test flake we're seeing in one of the `account-login-redirect.spec.ts` tests since this morning's login update. Login is displaying the "Please log in to continue." message twice in some cases, causing our tests to occasionally fail when attempting to select the text.
I'm opting to remove the assertion for this text altogether since it's outside the scope of Cloud Manager; the only thing Cloud Manager needs to be concerned with for this test's sake is that Cloud successfully redirects the user to the login page. The Login team's tests can assert the contents and functionality of the login page instead.
- Remove assertion for "Please log in to continue." text on login app
N/A
We can rely on CI for this. To run the test locally, however, you can use this …

test: Remove Cypress test assertion involving login page content

---

.github/workflows/e2e_schedule_and_push.yml

- Fixes a small oversight with pnpm. See https://github.com/linode/manager/actions/runs/13553086426/job/37882376961
- I forgot to add the `pnpm/action-setup` action to our Github Actions workflow that runs the Cypress suite 😖 
- Hopefully they run smoothly once this is merged 🤞

fix: Add pnpm to `e2e_schedule_and_push.yml`

---

packages/manager/.changeset/pr-11726-upcoming-features-1740510652938.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx

We need to hide the GPU plans tab for LKE-E because these plans will not be available for this tier until Q3 2025.
These changes apply to both the Create Cluster flow and the 'Add a Node Pool' flow on an LKE-E cluster details page.
Currently, we can see regions where GPUs are supposedly available listed under ‘global availability’ with an enterprise tier selected (which is misleading), and if we actually select that region, we can submit the form with a GPU plan, even though it’s not supported. Product's preference was to hide the GPU tab for enterprise clusters until Q3, rather than disable the panel with messaging.
- Filtered out types whose `id` included GPU if the selectedTier is `enterprise` so that these types won't be converted into plans to display under a GPU tab
- Updated test …

upcoming: [M3-9402] - Hide GPU plans tab for LKE-E

---

packages/manager/package.json
packages/manager/src/hooks/useDialogData.ts
packages/manager/src/hooks/useOrderV2.ts
packages/manager/src/hooks/usePaginationV2.ts
packages/manager/src/routes/placementGroups/index.ts
pnpm-lock.yaml

Updating TanStack to lates to benefit from a few improvements made to features such as [useBlockerHook](https://tanstack.com/router/v1/docs/framework/react/api/router/useBlockerHook) I need to use in https://github.com/linode/manager/pull/11704
This updates strengthens types overall, which affected a few custom hooks. This only modifies typing so I don't anticipate any regression to running code.
- Update Tanstack router version to `1.111.11`
- Update typing in utils
No visual or functional regressions should be encountered as a result of this PR
- Tests, CI etc
- Take a quick tour of the routed features to make sure all is good (PGs, Domains, Volumes, Longview etc)
<details> …

chore: [M3-9443] - Upgrade Tanstack Router to latest

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
packages/manager/package.json
packages/manager/src/components/AccessPanel/AccessPanel.tsx
packages/manager/src/components/Encryption/Encryption.tsx
packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx
packages/manager/src/features/Linodes/LinodeCreate/TwoStepRegion.tsx

- Fix issue where users cannot create Linodes in distributed regions
- Makes similar changes to https://github.com/linode/manager/pull/11629/files#r1945714503 which is in develop, but not staging or master yet 😭 
| Before  | After  |
|---|---|
|  ![Screenshot 2025-02-27 at 5 11 52 PM](https://github.com/user-attachments/assets/7c2b55dc-8318-4f18-8e0a-36d72ebbfe8f)  |  ![Screenshot 2025-02-27 at 5 11 10 PM](https://github.com/user-attachments/assets/b1190e1a-35cd-4672-81f9-2a8ffcdb6d93) |
| Before  | After  |
|---|---|
|  ![Screenshot 2025-02-27 at 5 12 35 PM](https://github.com/user-attachments/assets/5e6104e1-95af-4eba-915a-5b1333abcc4f) | ![Screenshot 2025-02-27 at 5 10 47 PM](https://github.com/user-attachments/assets/049b9ca4-dd0d-4ebf-a82a-f4b579f8dab2)  |

hotfix: Linode Creation in Distributed Regions

---

package.json
packages/manager/.changeset/pr-11758-changed-1740751964030.md
packages/manager/package.json
packages/manager/src/features/Lish/Glish.tsx
pnpm-lock.yaml

🎉 This will resolve 
- https://github.com/linode/manager/security/dependabot/144
- https://github.com/linode/manager/security/dependabot/142
And hopefully burry these `path-to-regex` issues for the foreseeable future 👍 
- Update `react-vnc` to 3.0.7
**3/11/2025**
No visual (or functional) regression should result from this PR
- Confirm Glish works as it should
- Linode Detail > Launch LISH Console > Glish
- Confirm tests are passing
<details> …

security: [M3-9447] - Update `react-vnc` for security updates

---

packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildForm.tsx

After merging `master` --> `develop`, the Linode Rebuild dialog started returning the `Cannot change disk encryption of a linode in a distributed region.` error for distributed instances. This PR removes `disk_encryption` from the payload if `site_type` === `distributed` to prevent this.
No changeset since this is just fixing something in `develop`
- Ensure you are able to rebuild linodes in core and distributed regions
<details>
🔐 Removing all …

fix: [M3-9455] – Fix Linode Rebuild dialog for distributed instances

---

packages/manager/.changeset/pr-11771-fixed-1740992423294.md
packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx

This PR updates the wording for adding SSH keys to reflect the support for multiple key formats.
- Updated the helper text for adding SSH keys to mention support for different key formats in addition to `ssh-rsa`.
N/A  
| ![Before](https://github.com/user-attachments/assets/b26ee586-8145-43da-9320-f61722645e44) | ![After](https://github.com/user-attachments/assets/c815f72e-3b18-498b-a811-98fd1519dea5) |
- My Profile > SSH Keys > Add An SSH Key  
- Linodes > Create Linode > SSH Keys > Add An SSH Key
<details>
</details>

fix: [M3-9253] - Incorrect helper text in `Add SSH Key` drawer

---

packages/manager/.changeset/pr-11769-fixed-1740985683618.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsSuspendClusterDialog.tsx

This PR updates the wording in the DBaaS Suspend Dialog to eliminate any confusion.
- Improved the wording of the Suspend Dialog message to make it clearer.
N/A  
| ![Before](https://github.com/user-attachments/assets/863d1551-cc48-4f16-8793-af69c887bea9) | ![After](https://github.com/user-attachments/assets/35c3845a-e91b-439a-a331-6e18e0dee237) |
<details>
</details>

fix: [M3-9270] - Confusing wording on DBaaS suspend dialog

---

packages/manager/.changeset/pr-11765-fixed-1740766037419.md
packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionList.tsx
packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx

This PR fixes an issue where the `Show Details` button for StackScripts was unresponsive when deploying a new Linode using a StackScript. Now, the button works as expected and users can view the StackScript details.
- Fixed the unresponsive `Show Details` button during the deployment of a new Linode via StackScript.
N/A  
| <video src="https://github.com/user-attachments/assets/92f6b15c-8d2b-4e2f-983e-442b1fa7a7ac"></video> | <video src="https://github.com/user-attachments/assets/76805676-648f-428f-a1ac-b7bee53b08cf"></video> |
| ![Before](https://github.com/user-attachments/assets/0c311b8b-d13a-42f5-9915-8240a867a262)| ![After](https://github.com/user-attachments/assets/3f7bebe3-98f9-43a8-967f-e5524cd97bf4) |
<details>
<summary> Author Checklists …

fix: [M3-9243] - Added show detail dailog for selected Stackscript

---

packages/api-v4/.changeset/pr-11735-upcoming-features-1740581707757.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-11735-upcoming-features-1740581501727.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/factories/databases.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.style.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationSelect.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts

DBaaS : Initial Advanced Config Tab and Drawer Setup
1. Initial Advanced Config Tab Setup
- Added a new Advanced Configuration Tab
- Added a feature flag for new Tab
- Set up the default layout (empty state with no configurations)
- Set up the table to display existing configurations
- Added mock data for the GET request to populate the table
2. Initial Drawer Setup
- Added a drawer for the Configure button
- Set up autocomplete with an empty state
Approximate 04/02/25
| Before (Figma template)  | After   |
| ![Screenshot 2025-02-26 at 2 10 42 PM](https://github.com/user-attachments/assets/7bb7c61f-30a1-4d78-a75f-b0f15048320a) | ![Screenshot 2025-02-26 at 2 09 36 PM](https://github.com/user-attachments/assets/0a79c65b-fa9d- …

feat: [UIE-8514] - DBaaS : Initial Advanced Config Tab and Drawer Setup

---

packages/manager/.changeset/pr-11779-fixed-1741096736423.md
packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx

A small, quick PR to fix the NodeBalancer Create Summary broken dividers and spacing.
- The Summary on the NodeBalancer create page is messed up. 
- Linode Create is not affected because it has its own custom summary component.
- How to reproduce:
- Go to the NodeBalancers landing page in the dev environment or on dev branch locally
- Observe broken summary spacing at bottom of page
- Fixed NodeBalancer Create Summary broken dividers and spacing
N/A
| Before (on dev)  | After   |
| ![Screenshot 2025-03-04 at 7 19 30 PM](https://github.com/user-attachments/assets/7f41aab9-8c3b-427e-82b3-33cfc83cfa5d) | ![Screenshot 2025-03-04 at 7 18 10 PM](https://github.com/user-attachments/assets/f049c681-1af1-4727-9d28-9454e0879f5c) |
| ![Screenshot 2025-03-04 at 7 19 …

fix: [M3-9415] - NodeBalancer Create Summary broken dividers and spacing

---

packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx

Fixes the broken link in the "Assign services to firewall" in Firewall create drawer. Accidentally imported from `react-router-dom` instead of our Link component.
No changeset since the bug hasn't reached prod yet
No visual changes. Click on link in below screenshot for testing:
- On staging, notice how clicking the above link in the FirewallCreate drawer is broken
- Confirm link is fixed on this branch (link should take you to the same place as prod)
<details> …

fix: Update link import in FirewallCreate section

---

packages/manager/.changeset/pr-11800-fixed-1741298651535.md
packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.test.tsx
packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
packages/manager/src/features/Profile/SSHKeys/EditSSHKeyDrawer.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeyActionMenu.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx

- Fixes spacing below the `Add an SSH Key` button
- I think this was caused by #11688 
- Cleans up some default exports and styled components too 🧹 
> [!note]
> I opted to not add any X-axis spacing on smaller viewports like we've done in some places in the app.
> - I did this because
>   - I prefer writing less one-off styles
>   - Our landing pages don't have X padding on small viewports. For example, the Linodes landing page
>      ![Screenshot 2025-03-06 at 5 01 46 PM](https://github.com/user-attachments/assets/0427c178-301f-4297-b4d4-01ef89b741c3)
> 
> Let me know if you object to this, we can talk about it in cafe
| ![Screenshot 2025-03-06 at 4 56 31 PM](https://github.com/user-attachments/assets/c65b1a7a-0e2e-4463-a1c9-3019fc087127) | …

fix: [M3-9478] - `Add an SSH Key` button spacing

---

packages/manager/.changeset/pr-11773-upcoming-features-1741023864014.md
packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListTable.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilter.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterField.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/MetricCriteria.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/GeneralInformation/ServiceTypeSelect.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.test.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddChannelListing.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannels/AddNotificationChannelDrawer.tsx
packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.test.tsx
packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertDefinition.tsx
packages/manager/src/features/CloudPulse/Alerts/Utils/AlertResourceUtils.ts
packages/manager/src/features/CloudPulse/Alerts/constants.ts
packages/manager/src/mocks/serverHandlers.ts
packages/validation/.changeset/pr-11773-upcoming-features-1741023892137.md
packages/validation/src/cloudpulse.schema.ts

UI changes across the Alerting feature validations, limits, error messages
- Added an error Notice when trying to submit a Create Alert without selecting any Notification Channel
- Added maximum limit of 5 to Metric Threshold, Dimension Filters and Notification Channels.
- Resetting the AddNotificationChannelDrawer when closing or clearing the Drawer
- Resetting the Metric Threshold components when Service is changed
- Fixed the tooltip texts for Evaluation Period and Polling Interval
- Styling changes for mobile screen compatibility and consistency for Metric Threshold and Trigger Condition components
- Added scrollToView to the components when validation or api error messages pop up
- Added scrolling to the top animation for PageChange, …

upcoming: [DI-23235] - Alerting UI changes: validations, limits, Error Messages

---

packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/AddInterfaceDrawer/Actions.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/DeleteInterfaceDialog.tsx

It looks like it's caused by merging https://github.com/linode/manager/pull/11810 without rebasing. As a result, some of the `ActionsPanel` imports from the `ui` package were missed and not updated causing some CI errors.
- Updates `ActionsPanel` to import from @linode/ui

fix: [M3-9520] - Fix Broken `ActionsPanel` Imports

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
packages/manager/src/features/Linodes/LinodeCreate/Region.tsx
packages/manager/src/features/Linodes/LinodeCreate/Security.tsx
packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/DiskEncryption.tsx

https://github.com/linode/manager/pull/11783 was done with the understanding that API would not be returning `Disk Encryption` as an account capability by default for all users; however, this is not the case as `Disk Encryption` _will_ be returned as an account capability by default for all users. The logic introduced in that PR therefore added unnecessary complexity.
- Mostly revert changes introduced in #11783
3/11/25
```
pnpm test enablebackupsdialog
```
```
pnpm test nodetable
```
```
yarn cy:run -s "cypress/e2e/core/linodes/create-linode-with-disk-encryption.spec.ts"
```
The easiest way to test would be to have one regular window open and one incognito window. One should be logged into an account without the `Disk Encryption` account capability (`linode-disk-encryption-disabled` tag) …

refactor: [M3-9493] – Streamline/simplify LDE logic

---

packages/manager/.changeset/pr-11820-changed-1741642386020.md
packages/manager/src/components/Markdown/__snapshots__/Markdown.test.tsx.snap
packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
packages/ui/.changeset/pr-11820-changed-1741642411797.md
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Body text color is currently `#696970` instead of using the designated color token. Update to use the correct design system token: Content.Text.Primary.Default (`#343438`).
Essentially all our headers and body text use the same color now, we will clean the theme as part of the larger refactor.
3/25
| ![cloud linode com_linodes_72766266](https://github.com/user-attachments/assets/242868e8-989a-45b4-9d21-7c4526492347) | ![localhost_3000_linodes_72766266 (2)](https://github.com/user-attachments/assets/efe94f03-4f79-4853-a24e-89bfa7241af4) |
- Observe new color to be `#343438`
<details>
🤏 …

change: [M3-9516] - Update body text color to use proper color token

---

packages/manager/.changeset/pr-11743-tests-1741276809069.md
packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts

Add test to check the warning message and disabled fields in volume create page for restricted users
- Add test to check the disabled fields on `/volumes/create` page
```
yarn cy:run -s "cypress/e2e/core/volumes/create-volumes.spec.ts"
```

test: [M3-9151] - Cypress test for Volume create page for restricted users

---

packages/manager/.changeset/pr-11793-tests-1741276889132.md
packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts

Add test to check the warning message and disabled fields in LKE cluster create page for restricted users
- Add test to check the disabled fields on `/kubernetes/create` page
```
yarn cy:run -s "cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts"
```

test: [M3-9152] - Cypress test for LKE create page for restricted users

---

packages/manager/.changeset/pr-11822-tests-1741678822638.md
packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts

Fix failing Edit User alert due to recent changes
The Edit User alert was failing due to modifications made in the recent updates. This commit resolves the issue by ensuring the alert triggers correctly under the expected conditions. Adjustments include refining the logic to align with the latest changes.
The alert was failing due to the use of ==, which caused an unintended comparison instead of an assignment. This commit updates it to = to ensure the correct assignment and proper alert functionality.
- ...
- ...
*
- ...
- ...

test: [DI-23925] - Fix failing Edit User alert due to recent changes

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx

Noticed a couple of regressions tracing back to the MUIv6 PR this afternoon. We need to get this into our release to avoid introducing the regressions, so this is pointed to `staging`.
No changeset since MUIv6 is not yet released.
- Removed a stray `s` in the UI
- Swapped out the `sx` prop for the correct `size` prop to retain correct table layout
⚠️  3/12 with our release
| Prod  | Staging   | This Branch |
| ------- | ------- | --- |
| ![Screenshot 2025-03-11 at 2 59 02 PM](https://github.com/user-attachments/assets/953fccc7-f3bc-465c-86cc-737f8ef389d1) | ![Screenshot 2025-03-11 at 2 58 33 PM](https://github.com/user-attachments/assets/7d35b578-667d-438a-a1cb-e7315ee958b8) | ![Screenshot 2025-03-11 at 2 58 18 PM](https://github.com/user-attachments/assets/2cfd56b4-a4d5-4d77-ad2a-31708743 …

fix: [M3-9526] - Fix database cluster config MUIv6 regressions

---

packages/api-v4/.changeset/pr-11762-upcoming-features-1740743199251.md
packages/api-v4/src/iam/types.ts
packages/manager/.changeset/pr-11762-upcoming-features-1740739892540.md
packages/manager/src/factories/accountResources.ts
packages/manager/src/factories/userPermissions.ts
packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.test.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
packages/manager/src/features/IAM/Shared/utilities.test.ts
packages/manager/src/features/IAM/Shared/utilities.ts
packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.test.tsx
packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx

IAM RBAC - update assigned roles and entities table components.
Highlight the Pull Request's context and intentions.
- update styles for Permissions component
- add Permissions component to Assigned roles table
- update styles for Assigned roles table component
- update styles for Assigned entities table component
- add new component for assigned entities
- add logic to action menu item `View entities`
- move the func from Assigned roles table to `utilities` and add test for it
dev
| ------- | …

feat: [UIE-8138, UIE-8139] - IAM RBAC: add new assigned roles table component part 2

---

packages/manager/.changeset/pr-11827-fixed-1741723772655.md
packages/manager/src/features/Kubernetes/CreateCluster/ClusterTierPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelAndTaintDrawer.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/LabelsAndTaints/LabelTable.styles.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx

This PR makes some minor spacing changes to improve some inconsistencies throughout LKE as requested by UX during review of LKE-E.
- Update the Cluster Tier selection card padding to `16px` all around and the space between the card heading and first subheading to `4px`
- Update the spacing at the bottom of the NodeTable to be equal on top and bottom (`8px`)
- Decrease the spacing at the top of the Labels & Taints drawer to be more standard (`24px`) and increase the spacing between the tables and the 'Add' buttons (`12px`)
3/25
| ![CardPaddingOld](https://github.com/user-attachments/assets/db5d7224-585a-416d-8cfd-ff77f208d791) | ![CardPaddingNew](https://github.com/user-attachments/assets/2edab014-922e-46b2-8c47-7bf1d38206c8) |
| …

fix: [M3-9465] - Make LKE/LKE-E spacing tweaks

---

packages/manager/.changeset/pr-11837-added-1741874687278.md
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
packages/manager/src/features/CloudPulse/Dashboard/CloudPulseDashboardLanding.tsx

Updated logic to handle for invalid paths after /metrics/ & /alerts/definitions/ to redirect to /metrics & /alerts/definitions respectively
1. Updated AlertsDefinitionLanding.tsx to add redirection logic
2. Updated CloudPulseDashboardLanding.tsx to add redirection logic
|<video …

refactor: [DI-23972] - Updated redirection for invalid url to metrics & alerts home page

---

packages/manager/.changeset/pr-11835-fixed-1741797017641.md
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/factories/statusPage.ts

This PR fixes a Storybook rendering issue where components fail with "TypeError: crypto.randomUUID is not a function". Components using `crypto.randomUUID` in factory files were unable to render properly in the Storybook environment.
- Added a conditional check for `crypto.randomUUID`
| <img src="https://github.com/user-attachments/assets/38815cb1-ae69-4efc-b6fe-690cbe713913" /> | <img src="https://github.com/user-attachments/assets/7fa67cd7-2e6f-4728-bbff-b563a5409469" /> |
<details>
➕ Adding a …

fix: [M3-9533] Storybook crypto.randomUUID Error

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.test.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx

Rate limits should not be displayed in the details drawer, consistent with their removal from the properties tab.
3/13
| ![Screenshot 2025-03-13 at 6 43 24 PM](https://github.com/user-attachments/assets/09f3ba65-0486-490c-bc46-d7ef7ed86dbb) | ![Screenshot 2025-03-13 at 6 43 16 PM](https://github.com/user-attachments/assets/ebac2870-d494-4060-a6d1-27db8560b35b) |
- Create an E3 object storage bucket in `DE, Frankfurt 2`.
- Go to details drawer for bucket
- Observe rate limit table is no longer rendered 
<details>
➕ Adding a …

remove: [M3-9580] - Bucket rate limit table from Object Storage details drawer

---

.github/workflows/e2e_schedule_and_push.yml

Sorry! I just merged #11845 which unfortunately broke the GHA Cypress pipeline. It's failing because we're trying to refer to a secret in the `matrix` section, but you can only use literal values there.
- Attempt to fix pipeline by removing variable from `matrix` section
ASAP
| 📷 | 📷 |
- ...
- ...
<details> …

test: [M3-9508] - Fix GHA Cypress pipeline by using literal values in matrix

---

.github/workflows/e2e_schedule_and_push.yml

Our GHA pipeline is still failing because we're setting the `parallel` option on the action. Because parallelization is only available via Cypress Cloud, Cypress is failing since we've disabled Cypress Cloud recording.
Setting `parallel` to false will fix this issue and _should_ finally allow the tests to run 🤞
- Disable `parallel` Cypress GHA option
| ------- | …

test: [M3-9508] - Disable Cypress Cloud parallelization action option

---

packages/manager/.changeset/pr-11838-fixed-1741862453402.md
packages/manager/src/features/Linodes/LinodeCreate/Tabs/StackScripts/StackScriptSelectionRow.tsx

This PR fixes the display issue with the `Show Details` button for Selected StackScripts on smaller screen sizes. The button now appears correctly and is centered.
- Fixed the display of the `Show Details` button on smaller screens.
- Centered the button for better alignment.
N/A  
| <video src="https://github.com/user-attachments/assets/23b2e970-ac69-4d1a-98d2-43f527ad76fe"></video> | <video src="https://github.com/user-attachments/assets/293b685f-5dc0-4d2c-9e71-9c0b741d4853"></video> |
- Verify the button displays correctly and is centered on smaller screens.  
- Confirm the button remains functional when clicked.
<details> …

fix: [M3-9459] - show details button misalignment for selected stackscript

---

pnpm-lock.yaml

- Updates `@babel/runtime` and `@babel/helpers` to their latest versions to resolve...
- https://github.com/linode/manager/security/dependabot/153
- https://github.com/linode/manager/security/dependabot/152
To do this, I used these commands
```sh
pnpm --recursive update @babel/helpers
```
```sh
pnpm --recursive update @babel/runtime
```
Usually I don't like making "magic" changes to the lockfile, but I think in cases like this it should be okay. I believe we'd get the same version bumps on `@babel/runtime` and `@babel/helpers` if we were to delete the lockfile and regenerate it.  This is just a less destructive way to bump these deep dependencies. 
- Use `pnpm why -r @babel/runtime` and `pnpm why -r @babel/helpers` to ensure that their versions are patched
<details> …

deps: [M3-9553] - Update `@babel/helpers` and `@babel/runtime` to latest

---

packages/manager/.changeset/pr-11862-tests-1742223400134.md
packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts

This PR fixes a few VPC tests so that they use the `chooseRegion` util rather than relying on the factory default when creating mock VPC objects. This allows the tests to pass in environments where the default region may not exist.
- Specify a region when creating mock objects, use `chooseRegion` to select region
N/A. No urgency to this whatsoever.
We want to confirm that these tests continue to pass in Prod and pass in other environments. We can rely on this PR's CI to confirm the tests still pass against Prod. Refer to the comment in M3-9476 for details about other environments.
<details>
➕ …

test: [M3-9476] - Use "chooseRegion" util when mocking VPCs so tests pass in other envs

---

packages/manager/.changeset/pr-11863-tests-1742223285423.md
packages/manager/cypress/e2e/core/billing/google-pay.spec.ts

This PR fixes a test in `google-pay.spec.ts` which fails when running against environments that use the Braintree sandbox. Refer to M3-9477 for more details.
- Update intercept URL to match against Braintree prod and sandbox requests
- Change original URL from an analytics endpoint to the actual API endpoint -- not sure why this was set that way to begin with
N/A. There's no urgency to this.
1. We can use this PR's test run to confirm this test continues passing in CI
2. Refer to the ticket comment in M3-9477 for details about testing against other envs
<details>
➕ Adding a …

test: [M3-9477] - Allow Google Pay test to pass when using Braintree sandbox

---

packages/api-v4/.changeset/pr-11840-upcoming-features-1741881740441.md
packages/api-v4/src/iam/iam.ts
packages/manager/.changeset/pr-11840-upcoming-features-1741881680603.md
packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
packages/manager/src/features/IAM/Shared/utilities.test.ts
packages/manager/src/features/IAM/Shared/utilities.ts
packages/manager/src/queries/iam/iam.ts
packages/queries/.changeset/pr-11840-upcoming-features-1741881790593.md

Add a new drawer for changing role flow
- Add a new flow for changing role
(dev)
| ![image](https://github.com/user-attachments/assets/38605af7-a47b-4766-b3f5-8d6ce7421a27) | ![image](https://github.com/user-attachments/assets/5bff3316-c996-4e3c-bfb1-85cf91df3df4) |
- Ensure the MSW is enabled in dev tools
- Click on the any username in the users table and go to the tab …

feat: [UIE-8141] - IAM RBAC: add new drawer for changing role flow

---

packages/manager/.changeset/pr-11880-upcoming-features-1742329364209.md
packages/manager/src/features/Kubernetes/ClusterList/constants.ts
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx

This is a late add that came out of reviews ahead of LKE-E's LA release.
The ask is to expose the fact that LDE is not enabled for the cluster during the cluster creation time. It is not sufficient to show it in the UI after the cluster is created or to just have it in tech docs.
Reasons LDE may not be enabled:
- LDE is turned off by LKE-E (this is expected to be the case for LA launch with a global flag on the backend; we don't have access to this flag)
- DC in which the LKE-E cluster is created does not support LDE (this is already being handled today)
_This changes will be reversed in coming weeks when LDE becomes available for LKE-E. Given potential merge conflicts with the last LDE changes in staging and the fact that this is not long-lasting, I did not go through the hassle of …

upcoming: [M3-9517] - Update LKE-E flows to account for LDE being disabled at LA launch

---

packages/api-v4/.changeset/pr-11852-upcoming-features-1742414634244.md
packages/api-v4/src/vpcs/types.ts
packages/validation/.changeset/pr-11852-upcoming-features-1742414737915.md
packages/validation/src/vpcs.schema.ts

Update endpoints and types for VPC Entity
- Add optional `ipv6` property to `VPC` and `CreateVPCPayload` interface
- Add optional `ipv6` validation to `createVPCSchema`
POST /v4/vpcs
GET /v4/vpcs
GET /v4/vpcs/{vpcId}
<details> …

upcoming: [M3-9511] - VPC IPv6 - Update endpoints and types for VPC Entity

---

packages/manager/.changeset/pr-11898-tests-1742493507045.md
packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts

This temporarily skips our Cypress Firewall end-to-end tests. We should be able to unskip them soon! See also M3-9619.
- Skips Firewall end-to-end tests
N/A
We can rely on CI for this. We just need to confirm that end-to-end tests have been skipped but integration tests that use mock API requests are still enabled.
If you want, you can test this locally using this command:
```bash
pnpm cy:run -s "cypress/e2e/core/firewalls/*"
```
All tests but 2 should be skipped, and the 2 that do run should pass. …

test: [M3-9618] - Temporarily skip Firewall end-to-end tests

---

packages/api-v4/.changeset/pr-11896-upcoming-features-1742491246746.md
packages/api-v4/src/vpcs/types.ts
packages/api-v4/src/vpcs/vpcs.ts
packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx
packages/validation/.changeset/pr-11896-upcoming-features-1742491352504.md
packages/validation/src/vpcs.schema.ts

Update types and validation for VPC Subnet
- Updated `ipv6` type for `CreateSubnetPayload`
- Separated `createSubnetSchema` into `createSubnetSchemaIPv4` and `createSubnetSchemaWithIPv6`
- Added ipv6 prefix length validation for subnets in `vpcsValidateIP`
- Updated `ipv6 subnet` schema validation in `vpcs.schema.ts`
- Minor variable refactoring
Cross-reference VPC IPv6 API spec (linked in parent ticket) and updated types for:
<details>
🔐 Removing …

upcoming: [M3-9512] - Update types and validation for VPC subnet

---

packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx

- some padding/margins seem off for Linode entity details vs prod, potentially another regression from MUIv6. I tried fixing them to make it look like prod again ... hopefully! 
No changeset needed - this hasn't hit prod yet
3/25
|   | large   |  small screen |
| ------- | ------- | -- |
|  prod |  ![image](https://github.com/user-attachments/assets/4812e611-1d49-4d6e-95cc-35e10403a20e) |   ![image](https://github.com/user-attachments/assets/afdeaa9e-9f63-4c30-a6e8-136aefd7ec62)  | 
| before | ![image](https://github.com/user-attachments/assets/82a924c9-c241-4bb9-b955-78b0c543d9d8) | ![image](https://github.com/user-attachments/assets/4c652bae-9b3c-4af9-ab13-45544d49aee9) |
| after | ![image](https://github.com/user-attachments/assets/4a8fb0b8-5b14-49a0-bc56-ecafc7c395f0) | …

fix: Fix styling for Linode Entity Details body and footer

---

packages/manager/.changeset/pr-11892-tests-1742564481277.md
packages/manager/cypress/support/util/regions.ts

Disallow legacy regions from being chosen when using the `chooseRegion` util within our Cypress tests.
- Add legacy regions to list of disallowed regions
N/A.
- We can rely on CI for this.
- Alternatively, run the tests or some subset of tests and confirm no resources get created in disallowed regions
<details>
👣 Providing comprehensive …

test: [M3-8668] - Disallow legacy regions from being selected via `chooseRegion`

---

packages/manager/.changeset/pr-11894-fixed-1742495460894.md
packages/manager/cypress/component/components/tabs.spec.tsx
packages/manager/cypress/support/component/setup.tsx
packages/manager/cypress/support/util/components.ts
packages/manager/package.json
packages/manager/src/components/Tabs/SafeTabPanel.test.tsx
packages/manager/src/components/Tabs/Tab.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/IntegrationsTabPanel.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/ApiAwarenessModal/SDKTabPanel.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
packages/manager/src/hooks/useTabs.ts
pnpm-lock.yaml

It was pointed in a recent routing refactor (thanks @dwiley-akamai 🥇) that the keyboard navigation was broken on newly Tanstack router tabs. This PR fixes that and add coverage to prevent future regressions.
- Bump `@reach/tabs` to latest version
- Fix `useTabs` onChange handler to properly propagate `@reach/tabs` event listeners
- Fix missing `<React.Suspense />` instances
- Add new Tabs component test
- Fix missing Tabs wrapper in tests (new type requirement from version bump)
https://github.com/user-attachments/assets/28f57b82-4dc0-45e8-8fef-351ab14cd28c
use `develop` branch 
- navigate to nodebalancers/{id}/summary
- try navigating the tabs via left/right arrows once focused
- confirm not working
use `this` branch 
- navigate to nodebalancers/{id}/summary
- try navigating the tabs via …

fix: [M3-9607] - Tabs keyboard navigation on Tanstack rerouted features

---

packages/ui/.changeset/pr-11871-changed-1742300523305.md
packages/ui/src/components/Checkbox/Checkbox.stories.tsx
packages/ui/src/components/Checkbox/Checkbox.tsx
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Update styles to match CDS for `Checkbox` component
- Add `Checkbox` design tokens
- Add more stories for the `Checkbox` component in Storybook
- Update styles to match CDS for `Checkbox` component
N/A
Some of the checkbox variants (from storybook):
| State | Light | Dark |
| ---- | ------- | ------- |
| _Default_: Unchecked, Checked, Indeterminate | ![Screenshot 2025-03-20 at 3 13 07 AM](https://github.com/user-attachments/assets/0d7b1467-7971-4bd6-b53a-22923959ee5a) ![Screenshot 2025-03-20 at 3 13 14 AM](https://github.com/user-attachments/assets/0e59f538-6eaa-4def-8f1f-710ddea5c477) ![Screenshot 2025-03-20 at 3 13 25 AM](https://github.com/user-attachments/assets/e6a7891b-04ee-40e2-baa9-c415e0d7e8f8) | ![Screenshot 2025-03-20 at 3 47 …

change: [M3-9430] - Akamai Design System: Checkbox Component

---

.github/workflows/ci.yml
packages/manager/.changeset/pr-11923-tech-stories-1742933716536.md
packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx

- Fixes some type errors caused when we merged `staging` into  `develop` 
- Fixes issue introduced when we migrated to pnpm (https://github.com/linode/manager/pull/11297) causing packages not to publish
- I think I just used an invalid secret key
- Verify CI passes ✅ 
- We can't really test the job that publishes packages but I'm pretty sure this will fix the issue for our next release
<details>
🔐 Removing all sensitive information from the code and …

fix: [M3-9652] - Packages unable to publish

---

packages/manager/.changeset/pr-11893-upcoming-features-1742481856731.md
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.test.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesActionMenu.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.test.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/UnassignRoleConfirmationDialog.tsx
packages/manager/src/features/IAM/Shared/utilities.test.ts
packages/manager/src/features/IAM/Shared/utilities.ts
packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx

Add a new confirmation dialog for the unassigning role flow. The design for this component is the same as the one used for deleting a user in the users table.
- Add a new component for the unassigning role flow
- Add a new component for the actions menu in the table
(dev)
| ![image](https://github.com/user-attachments/assets/c8e748ba-74cf-403f-ae5e-2547f7ea7dba) | ![image](https://github.com/user-attachments/assets/9f0de1d7-7b2d-4e48-a662-367558366f39) |
(How to setup test …

feat: [UIE-8600] - IAM RBAC: add new drawer for unassigning role flow

---

packages/manager/.changeset/pr-11930-upcoming-features-1743025907787.md
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx

While auditing the app after turning the LDE feature flag off this afternoon (see ticket for further explanation), I noticed a couple of minor issues:
1. The encryption status indicator still displays in the summary panel on the Linode Details page -- this is due to logic introduced in https://github.com/linode/manager/pull/11783 that should have been removed in https://github.com/linode/manager/pull/11817 but was not.
2. The `Node Pool data is encrypted at rest.` copy in the "Add Node Pools" panel in the LKE Create flow is visible if the region has the `Disk Encryption` capability. Since the account capability is not relevant as all LKE clusters should be encrypted by default if deployed in regions supporting the feature, we should control the display of this copy by checking for the …

fix: [M3-9669] – Adjust conditions for displaying encryption status on Linode Details page & encryption copy on LKE Create page

---

packages/manager/.changeset/pr-11914-tech-stories-1742929299022.md
scripts/changelog/generate-changelogs.mjs
scripts/changelog/utils/constants.mjs
scripts/changelog/utils/deleteChangesets.mjs
scripts/package-versions/index.js

This PR addresses path traversal vulnerabilities identified by SAST security scanning.
- Fixed path traversal vulnerabilities in `manager/scripts/` directory
- Used `path.sep` for cross-platform compatibility
| <img src="https://github.com/user-attachments/assets/96102ebd-f29d-463d-8276-3d6904b096b2"/> | <img src="https://github.com/user-attachments/assets/54485f2c-3fe9-486a-9309-6c38aca3a581"/> |
- Install `semgrep` if not already installed with `pip install semgrep`
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/C …

refactor: [M3-7277] - SAST Scan Findings: Path Traversal Vulnerability v2

---

packages/manager/.changeset/pr-11951-tests-1743535607155.md
packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
packages/manager/cypress/support/setup/defer-command.ts
packages/manager/cypress/support/util/linodes.ts

This makes a few fixes intended to improve the stability of our tests in `linode-config.spec.ts`. Some of the fixes involve the `cy.defer()` command and `createTestLinode` util which may also improve stability of other tests.
With these changes in place, I was able to run the spec locally on repeat and:
- The clone test passed 20/20 times
- Additionally, the entire spec passed 10/10 times
- In the Linode config clone test, wait for both source and destination Linodes to boot before attempting the config clone operation.
- In the Linode non-recommended config test, wait for VLAN GET request to resolve before interacting with form to prevent UI update mid interaction
- Wait for `LINODE_CLONE_TIMEOUT` duration (5 minutes currently) when waiting for config clone success toast notification
- …

test: [M3-9703] - Improve stability of Linode config Cypress tests

---

packages/manager/.changeset/pr-11954-changed-1743543232723.md
packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx

This PR fixes a UI inconsistency where Firewall Create page form fields were improperly enabled for restricted users.
- Disabled radio buttons for Default Inbound/Outbound Policy for restricted users
- Disabled dropdown menus for Linode and NodeBalancers selections for restricted users
| <img src="https://github.com/user-attachments/assets/e308ca1e-19f8-4ccc-a5f5-d3943b188e1f" /> | <img src="https://github.com/user-attachments/assets/1cf72a38-5ffb-4822-bc51-6b30dfe12d39" /> |
<details>
➕ Adding a …

change: [M3-9598] - Form fields on Firewall Create page are enabled for restricted user

---

packages/manager/.changeset/pr-11952-tech-stories-1743537321600.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx

These changes should be **REVERTED** on `release-v1.139.0` using the steps "How to omit PRs from a release branch" in our deploy docs to test that our process is sound.
- Added a stray console.log statement to LongviewLanding
- Modified a `lke-create.spec.ts` test to check for strings not existing in an unideal way
- Added a changeset that should be removed from the changelog
N/A
<details>
🔐 Removing all sensitive information …

change: Add a dummy PR to intentionally omit from the next release

---

packages/manager/.changeset/pr-11935-fixed-1743110166866.md
packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts
packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx
packages/manager/src/features/Profile/APITokens/utils.ts

This PR corrects some logic errors in the Create PAT Token drawer affecting the majority of accounts (except for parent accounts). For these accounts, the "Child Account Access" grant is hidden. Despite this:
- Individually selecting all the grants does not cause the "Select All" radio to be selected.
- Individually selecting all the grants and then submitting the form sends a list of grants to the API instead of the "*" wildcard character.
- Update `excludedScopesFromSelectAll` value to exclude `child_account` when it is hidden
- Update `permTuplesToScopeString` with new `exclude` argument to determine when to return "*"
|Prod|This Branch|
|-|-|
|<video src="https://github.com/user-attachments/assets/8cd58512-c841-4d7a-8ea5-d730ec726e3c" />|<video …

fix: [M3-9070] - Exclude `child_account` grant from PAT token calculations when it is hidden

---

packages/manager/.changeset/pr-11958-tests-1743610427083.md
packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts
packages/manager/cypress/support/setup/test-tagging.ts
packages/manager/cypress/support/util/tag.ts

This adds a few new tags to our Cypress tests surrounding environment-specific functionality. Specifically, it adds the following new tags:
- `env:marketplaceApps`: for tests that require an environment where Marketplace apps are available
- `env:multipleRegions`: for tests that require an environment where more than one region is available
- `env:stackScripts`: for tests that require an environment where Community StackScripts are available.
It applies these tags to a few tests to ensure they can be skipped when running against environments that don't meet the tests' requirements.
(Addresses M3-9481, M3-9485, M3-9554)
- Add `env:marketplaceApps`, `env:multipleRegions`, and `env:stackScripts` tags
- Apply tags to relevant E2E tests
- Fix a small issue with our tagging logic where tags …

test: [M3-9481 & more] - Apply environment-specific tags to tests

---

packages/manager/.changeset/pr-11969-added-1743779981445.md
packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
packages/manager/cypress/support/intercepts/cloudpulse.ts
packages/manager/src/queries/cloudpulse/alerts.ts

Updated alerts.ts file to push newly created alert to cache.
1. Updated alerts.ts query to set the new alert to cache
2. Updated cloudpulse.ts intercept to return new alert instead of paginated response.
22 April
|<video src="https://github.com/user-attachments/assets/4bdcf31c-089b-4f0c-a5c8-9f89235f9c77"/>|<video src="https://github.com/user-attachments/assets/4d8b8c2a-f880-41d3-bc63-7f6aa0b78b60"/>|
1. Switch to mock user
2. Go to alert tab
3. Click on create alert button …

refactor: [DI-24450] - Added logic to update the alert in cache when it is created

---

packages/api-v4/CHANGELOG.md
packages/api-v4/src/databases/types.ts
packages/manager/CHANGELOG.md
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts

Fixed drawer showing outdated config values after save and reopen
- fixed the drawer to display updated config values after save and reopen
- fixed the UI to display newly added configs as existing (without remove button) after saving and reopening the drawer
- fixed showing the "Restart Service" label according to API data
- updated validation behavior to show error messages on blur instead of on submit
- updated the default value for newly added configs (number inputs) from 0 to the minimum value provided by the API
04/08/25
Database Advanced Config feature flag should be enabled
**Verify updated value for existing config:**
- select a database cluster
- navigate to the Advanced Configuration tab
- click the …

fix: [UIE-8447] - refresh drawer after config add/update

---

package.json

Fixes an issue where `pnpm clean` doesn't actually clean all our new packages.
Didn't include a changeset since this is a one-liner, tech story, and not technically part of any package.
- Updated the `clean` command in `package.json`.
N/A
<details>
👣 Providing …

fix: Update `pnpm clean` command to include all new packages

---

packages/manager/.changeset/pr-11993-added-1744134925847.md
packages/manager/src/features/Images/ImagesLanding/EditImageDrawer.tsx

This PR adds the "Encrypted" label to the `EditImageDrawer` component.
- Adds "Encrypted" label to Edit Image Drawer
- Includes Lock icon next to text 
| <img src="https://github.com/user-attachments/assets/eb18f836-c6cb-4ae1-8d05-61293a2dabcb" /> | <img src="https://github.com/user-attachments/assets/028911b1-d260-4479-8261-94090a5bfc4f" />  |
<details>
🔐 Removing all sensitive information from the code …

change: [M3-9735] - Add encryption icon to Image edit drawer

---

packages/manager/.changeset/pr-11944-changed-1743506054914.md
packages/manager/src/components/TagCell/AddTag.tsx
packages/manager/src/components/TagsInput/TagsInput.test.tsx
packages/manager/src/components/TagsInput/TagsInput.tsx

This PR removes the validation requiring a minimum of 3 characters when adding tags. Additionally, it adds validation to handle the edge case where the tag is an empty string or contains only spaces (e.g., `" "`).
- Removed the 3-character minimum validation for adding tags.
- Added validation to show an error when the tag is an empty string or contains only spaces (e.g., `" "`).
| <video src="https://github.com/user-attachments/assets/4b78fc9d-a608-49f9-8ebe-b7bbc6caff0e"></video> | <video src="https://github.com/user-attachments/assets/8fd4b1ef-fa3a-44bc-8706-023791a1b175"></video> |
| <video src="https://github.com/user-attachments/assets/b6749aa1-7b7c-49c5-b0bc-71bc2a86142b"></video> | <video …

change: [M3-9408] - Remove min length validation for tag

---

packages/manager/.changeset/pr-11984-upcoming-features-1744052007574.md
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.test.tsx
packages/manager/src/features/IAM/Users/UserDetails/UserDetailsPanel.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.test.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx

Assigned Roles and Entities Tables - Not displaying empty state when no roles or no entities assigned.
- Fix displaying empty state
- Add tests
- Change from `Access: 8 roles assigned `to `Assigned Roles: 8` without the hyperlinking behavior
- Remove searching by role access in the table
(dev)
| ![image](https://github.com/user-attachments/assets/53251bad-be9f-4a0f-b2f6-47acbea462c7) | ![image](https://github.com/user-attachments/assets/f448ae19-1fd4-42f3-b8bf-26a7aaf84797) …

feat: [UIE-8672, UIE-8625] - IAM RBAC: fix not displaying empty state when no roles or no entities assigned

---

packages/manager/cypress/e2e/core/cloudpulse/alerts-listing-page.spec.ts

fix needed after mergin ghttps://github.com/linode/manager/pull/11941 to make develop lint-healthy

fix: [M3-9693] - Unexpected empty object pattern fix post eslint merge

---

packages/manager/.changeset/pr-11986-removed-1744096851575.md
packages/manager/cypress/e2e/core/account/smoke-enroll-beta.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/factories/index.ts
packages/manager/src/features/Betas/BetasLanding.tsx
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/mocks/serverHandlers.ts
packages/utilities/.changeset/pr-11986-added-1744096873342.md
packages/utilities/src/factories/betas.ts
packages/utilities/src/factories/index.ts
packages/utilities/src/helpers/betaUtils.test.ts
packages/utilities/src/helpers/betaUtils.ts
packages/utilities/src/helpers/index.ts

Move `betaUtils` and its associated factories to `utilities` package
<details>
<br/>
</details>

refactor: [M3-9170] - Move `betaUtils` and its associated factories to `utilities` package

---

packages/manager/.changeset/pr-12007-changed-1744290501828.md
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
packages/utilities/src/helpers/arrayToList.test.ts
packages/utilities/src/helpers/arrayToList.ts

As part of the CloudPulse Linode Integration, the "Analytics" tab on the Linode detail page needs to be renamed to "Metrics".
Since this is a Global change, feature flag is not required.
- Renamed  `Analytics` tab to `Metrics` tab on Linode Details page
- Updated the `routeName` for this tab
- Random eslint fixes
N/A
| ![Screenshot 2025-04-10 at 5 42 27 PM](https://github.com/user-attachments/assets/d53f419b-b212-43ec-9d83-57ef8fe8292f) | ![Screenshot 2025-04-10 at 5 44 43 PM](https://github.com/user-attachments/assets/3dcbddce-c9e2-49d1-a5f1-ccf6cd111ad3) |
- All checks pass
- Ensure the `Analytics` tab is now displayed as `Metrics` tab on Linode details page
<details>
❔ Our …

change: [M3-9743] - Rename `Analytics` tab to `Metrics` tab on Linode details page

---

packages/manager/.changeset/pr-12019-fixed-1744606971621.md
packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx

Add Permission Notice for Restricted User when Navigating to Image Details Page.
- Add a warning notice for restricted users navigating to the `/images`
N/A
| ![Before](https://github.com/user-attachments/assets/e4560708-11ca-49eb-9b3c-bbcbd54260f6)| ![After](https://github.com/user-attachments/assets/06feaaac-3e1f-46d7-9bbd-684295c3645a) |
<details>
🔐 Removing all sensitive information from the code and PR …

fix: [M3-9521] - Warning message in the images landing page for the restricted user

---

packages/manager/.changeset/pr-12014-tests-1744382864732.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts

Fix Cypress LKE update tests in DevCloud by mocking region whose ID was hardcoded in other resources. 
pnpm run cy:e2e -s 'cypress/e2e/core/kubernetes/lke-update.spec.ts'
<details>
♿ …

test [M3-9567]: Fix Cypress LKE update tests in DevCloud

---

packages/api-v4/.changeset/pr-12022-added-1744640457876.md
packages/api-v4/src/databases/types.ts
packages/manager/src/factories/databases.ts
packages/validation/.changeset/pr-12022-added-1744640788599.md
packages/validation/src/databases.schema.ts

Add custom validation for `wal_sender_timeout` and `max_failover_replication_time_lag` configs.
- added validation for wal_sender_timeout
- added validation for max_failover_replication_time_lag
04/22/25
Database Advanced Config feature flag should be enabled. 
Use mock data to test.
- select a database cluster
- navigate to the Advanced Configuration tab
- click the "Configure" button
- select a new `wal_sender_timeout` configuration from the Autocomplete and click "Add"
- modify the value of the newly added configuration (e.g., -1 or 5) to verify that the error is shown
<details>
🤏 Splitting feature into …

change: [UIE-8685] - Advanced Config: custom validation for wal_sender_timeout

---

packages/manager/.changeset/pr-12018-tech-stories-1744408988818.md
packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx
packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx
packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
packages/manager/src/features/Linodes/LinodesLanding/RegionTypeFilter.tsx
packages/manager/src/features/Linodes/index.tsx

Update `RegionTypeFilter` to use the new basic Select component instead of `Autocomplete`.
- Update `RegionTypeFilter` to use basic Select
- Drill `regionFilter` prop from `LinodesLandingWrapper` > `LinodesLanding` > `DisplayLinodes`
- Previously the Autocomplete was used in uncontrolled mode and internally stored the current value of the select. The basic Select component does not support being uncontrolled.
- Advantages: avoids multiple sources of truth for the currently active Region filter
- Disadvantages: prop drilling
- Alternatives: adding support for uncontrolled input in the simple Select component; custom React context
I invite feedback/suggestions for the best way to move forward.
| <video …

refactor: [M3-9767] - Use simple Select in `RegionTypeFilter`

---

packages/manager/.changeset/pr-12021-fixed-1744625544934.md
packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx

Add Permission Notice for Restricted User when Navigating to Longview Landing Page.
- Add a warning notice for restricted users navigating to the `/longview/clients`
N/A
| ![Before](https://github.com/user-attachments/assets/8d4eb04d-e7f5-43ae-a595-7e5f65bf62b8)| ![After](https://github.com/user-attachments/assets/b25c52d0-ff91-4916-85b6-99349e9d6bec) |
<details>
🔐 Removing all sensitive information from the code …

fix: [M3-9586] - Warning message in the Longview landing page for the restricted user

---

packages/manager/.changeset/pr-12032-fixed-1744732437757.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/utilities.ts

Autofill fix and clear API errors on blur for config item input.
- autofill fix
- clear API errors on blur for config item input
- correct Save button label when modifying configs with `requires_restart`
04/22/25
<details>
📑 Providing or updating …

fix: [UIE-8447] - autofill fix and clear errors on blur

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Kubernetes/ClusterList/constants.ts
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx

With the rollout of LDE GA beginning tomorrow, this PR removes references to disk encryption as it relates to LKE because LDE will not be applied to LKE for the time being.
The following pieces of copy have been removed from CM:
- "Node Pool data is encrypted at rest." (LKE Create flow)
- "Node Pool data is not encrypted at rest for LKE Enterprise clusters." (LKE Create flow)
- "To enable disk encryption, delete the node pool and create a new node pool. New node pools are always encrypted." (unencrypted status indicator tooltip in Linode Details summary panel & node pool table footer)
4/16/25
Have the `linode_disk_encryption` tag on your account.
For LKE-E: have the `lke-enterprise-eap` tag on your account.
- After selecting a region in the LKE Create flow, you should not see `Node Pool …

hotfix: [M3-9771] – Remove references to disk encryption for LKE

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/Encryption/constants.tsx
packages/manager/src/features/Kubernetes/ClusterList/constants.ts
packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
packages/manager/src/features/Linodes/LinodeEntityDetailBody.tsx

- References to disk encryption in relation to LKE ([#12034](https://github.com/linode/manager/pull/12034))

Release v1.139.1 - `staging` → `master`

---

packages/manager/.changeset/pr-12023-tests-1744653408368.md
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts

This fixes a handful of tests in `plan-selection.spec.ts` when running against non-Production environments. All of the fixes involve passing an array of mock region objects to our `findItemByRegionLabel` helper which otherwise expects the specified regions to exist.
- Allow tests in `plan-selection.spec.ts` to pass against environments where the mock region does not actually exist
N/A. No urgency.
- Confirm tests pass in CI
- Confirm tests pass against other environments
- Refer to the comment on M3-9555 which includes a CI link demonstrating that the tests pass
<details>
➕ Adding a …

test: [M3-9555] - Fix plan selection Cypress test against other environments

---

packages/manager/.changeset/pr-12033-upcoming-features-1744745488820.md
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/constants.ts
packages/validation/.changeset/pr-12033-removed-1744745547794.md
packages/validation/src/kubernetes.schema.ts

Current limit for LKE-E node pool autoscaler max is 100, when 500 is expected. This is because LKE-E allows up to 500 nodes in a node pool (and 500 nodes in a cluster) for initial LA launch.
- Moved the validation from the schema file to the AutoscalePoolDialog to determine min and max error messages based on the clusterTier
- Added clusterTier as a prop to AutoscalePoolDialog
- Updated test coverage to check for LKE-E max limit in lke-update.test.spec
- The linter fixed some misc issues
4/22
| ![image](https://github.com/user-attachments/assets/292ed7da-3ce0-4d0b-b756-e4198ac1735d)| <video src="https://github.com/user-attachments/assets/0325d949-a7dd-4750-8bfb-5e552110f56e" /> |
- Use `prod-test-004-fe` for an …

fix: [M3-9770] - Fix incorrect max autoscaler limit validation for LKE-E

---

packages/manager/.changeset/pr-12026-upcoming-features-1744709007966.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts

A small PR to create a new boolean feature flag for the upcoming CC ACLP Integration
```
aclpIntegration: boolean
```
- Introduced `aclpIntegration` feature flag
- Added it to FeatureFlagTool
- Random ESlint warning fixes
- Confirm a toggle for "ACLP Integration" is present in our dev tool
- (optional) Filter network requests for "LaunchDarkly" and observe the presence of a "aclpIntegration" object
<details>
🔐 Removing all sensitive information from …

upcoming: [M3-9758] - Create a feature flag for ACLP Integration

---

packages/manager/.changeset/pr-12029-tests-1744725232756.md
packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts
packages/manager/cypress/support/intercepts/regions.ts

This allows the three tests in `migrate-linode.spec.ts` to pass against environments where `us-east`, `us-west`, `us-central`, and `eu-central` do not exist by mocking the regions instead.
- Mock regions in `migrate-linode.spec.ts` to allow tests to pass in environments where Prod regions do not exist
- Add `mockGetRegion` intercept util
N/A. No urgency.
- Confirm test passes against Prod environments (we can rely on CI for this)
- Confirm test passes against other environments (refer to comment in Jira ticket)
To run the spec locally, you can run the following command:
```bash
pnpm cy:run -s "cypress/e2e/core/linodes/migrate-linode.spec.ts
```
<details> …

test: [M3-9578] - Use mock regions for Linode Migrate integration tests

---

packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/PromptDialogContent.tsx
packages/manager/src/features/VPCs/utils.test.ts
packages/manager/src/features/VPCs/utils.ts

No changeset/changelog update bc this hasn't hit prod yet (it's part of the M3-9250)
Surface IP range errors when assigning Linodes using Linode Interfaces to a subnet
- use regex replace function... idk why I did what I had 🤦‍♀️ 
- add tests to check ensure logic
4/22 release
| ![image](https://github.com/user-attachments/assets/60dd7b52-aa41-462d-a6c8-5eaca71a3f68) | ![image](https://github.com/user-attachments/assets/13e0a90f-9e24-4dca-acb5-912e0cb512d0) |
See #12016 for testing instructions
- Click 'add IPv4 range' and type 10.0.0.0 or 10.0.0.1
- notice how errors don't get surfaced
- Confirm IP range errors now surface
<details> …

fix: Surface IPv4 Range errors for Linode Interfaces in SubnetAssignLinodesDrawer

---

packages/manager/.changeset/pr-12051-tests-1744882097150.md
packages/manager/cypress/e2e/core/cloudpulse/groupby-tags.spec.ts

- Verifies alerts are displayed under correct tag headers when grouped by tag.
- Validates visibility of tag headers: bothTags, evenTags, oddTags, and No Tags.
- Confirms correct alerts appear under each tag grouping.
- Tests search functionality within grouped alerts.
- Ensures alerts not matching the search query are hidden.
- Verifies tag headers disappear when ungrouping by tag.
- Confirms user preferences and feature flags are applied properly.
- ...
- ...
Uploading groupby-tags.spec.ts.mp4…
|

test: [DI-24751] - Add Cypress test coverage for grouping of alerts by tags in CloudPulse Alerts Listing page

---

packages/manager/.changeset/pr-12068-upcoming-features-1745003586699.md
packages/manager/src/features/IAM/hooks/useIsIAMEnabled.test.ts
packages/manager/src/features/IAM/hooks/useIsIAMEnabled.ts
packages/manager/src/queries/iam/iam.ts

Disable API check when feature flag is off
- Pass the feature flag to the query to disable the API call when the flag is off
- Add unit test
4/22/25
| 📷 | 
|
- Regular env without IAM access
<details>
📑 …

feat[UIE-8726]: IAM disable API check when feature flag is off

---

packages/manager/.changeset/pr-12013-changed-1744375580329.md
packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodeAlerts/LinodeAlerts.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx

Add dedicated `Alerts` tab on Linode details page.
Since this is a global change, no feature flag is required. 
- Created a new `Alerts` tab and added a new route for this tab
- Removed "Notification Thresholds" section from the settings section
- Added "Notification Thresholds" section to the new `Alerts` tab
- Updated  "Notification Thresholds" heading name to "Alerts" in `Alerts` tab
N/A
- Verify new `Alerts` tab appears in Linode detail navigation
- Ensure all alert settings are accessible and functional in the new tab 
- Ensure no alert functionality remains in the `Settings` tab
- Ensure UI is consistent with existing design patterns
<details>
❔ Our [contribution guidelines](https://github.com/linode/manager/blob/develop/do …

change: [M3-9742] - Add dedicated `Alerts` tab on Linode details page

---

packages/manager/.changeset/pr-12067-upcoming-features-1745002359136.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx

This PR includes a couple improvements to the ACL IP Address section:
- Bug fix: resets the IP addresses when the acknowledgement checkbox is selected so that validation errors don't incorrectly persist
- UX improvement: disables the fields when the acknowledgement is selected so that it is clear to the user: either provide the addresses or select the checkbox
- Add the disabled prop to the IP fields to check for `isAcknowledgementChecked`
- Add a missing disabled prop to the styled MultipleIP button (the "Add IPv4/6 Address" button) so that the button can also be disabled
- Call setState functions for both IP address types in `handleIsAcknowledgementChecked`
- Fix some linting warnings
LKE-E QA has tagged this with Phase1 label, meaning they want it in the LA launch and we should include …

fix: [M3-9779, M3-9787] - Improve validation and UX for ACL IP Address fields

---

packages/manager/.changeset/pr-12037-fixed-1744750096750.md
packages/manager/src/features/Account/utils.ts
packages/manager/src/features/Volumes/VolumesLanding.tsx

This PR adds a warning notice for restricted users on the Volumes page to inform them they lack permissions to create/edit volumes.
- Added conditional warning notice in `VolumesLanding` component
| <img src="https://github.com/user-attachments/assets/6508b09f-0eb1-4c7b-93b8-92cd7d93d2b4"/> | <img src="https://github.com/user-attachments/assets/e4e26100-d012-4d83-8e13-ac801a743f39"/> |
<details>
🔐 Removing …

fix: [M3-9584] - No warning message in the volume details page for the restricted users

---

packages/manager/.changeset/pr-12043-fixed-1744782995123.md
packages/manager/.changeset/pr-12043-tests-1744782995123.md
packages/manager/cypress/e2e/core/images/images-non-empty-landing-page.spec.ts
packages/manager/cypress/support/intercepts/images.ts
packages/manager/src/factories/images.ts

This PR fixes the Recovery Images Table Header alignment with the data column in mock tests.
- Fixed Recovery Images Table Header alignment with the data column in mock tests.
N/A
| ![Before](https://github.com/user-attachments/assets/ca1dacfc-35b5-44fa-8066-a993df181098)| ![After](https://github.com/user-attachments/assets/8f2ba35f-6220-41cc-82f5-4ac5f2197224) |
<details>
🔐 Removing all sensitive information …

fix: [M3-9522] - Recovery images table headers alignment with data column

---

packages/manager/.changeset/pr-12062-upcoming-features-1744990576571.md
packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
packages/manager/src/features/IAM/Shared/Entities/utils.test.ts
packages/manager/src/features/IAM/Shared/Entities/utils.ts
packages/manager/src/features/IAM/Shared/types.ts
packages/manager/src/features/IAM/Shared/utilities.ts
packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
packages/manager/src/queries/entities/entities.ts

small bug fixies
- Disabled typing in the text field when it enters read-only mode
- Ensured that newly created entities are included in the options list when navigating via the navbar (not when opening a new tab)
- Added a loading state that displays while data is being fetched from the API.
- Minor cleanup in the `Entities` component and related parts of `utilities.ts`
(dev)
| 📷 | 📷 |
- Ensure the Identity and Access Beta flag is enabled in …

feat: [UIE-8672, UIE-8702, UIE-8703] - IAM RBAC: fix bugs

---

packages/manager/.changeset/pr-12085-tests-1745337050128.md
packages/manager/cypress/e2e/core/objectStorageMulticluster/bucket-delete-multicluster.spec.ts

Fix OBJ multicluster delete test app crash in cypress/e2e/core/objectStorageMulticluster/bucket-delete-multicluster.spec.ts by ensuring an available region is used in the created cluster. Test fn objectStorageBucketFactory.build() defaults to using hardcoded region id of 'us-east' which is not available in all test environments. 
Ensure that objectStorageBucketFactory.build() uses an available region.  
```
pnpm cy:run -s "cypress/e2e/core/objectStorageMulticluster/bucket-delete-multicluster.spec.ts" 
``` 
<details>
➕ Adding a …

test [M3-9569]: Fix for OBJ multicluster delete test app crash in DevCloud

---

packages/manager/.changeset/pr-12076-fixed-1745269382669.md
packages/manager/.changeset/pr-12076-upcoming-features-1745347113083.md
packages/manager/src/features/Kubernetes/CreateCluster/ClusterTierPanel.tsx

This PR fixes a sizing bug in the LKE Tier selection.
- Set explicit width for `SelectionCard` components at 1920px+ breakpoints in `ClusterTierPanel.tsx`
| <video src="https://github.com/user-attachments/assets/a7fe4781-72b9-4fa1-8668-cb241a21a40b" /> | <video src="https://github.com/user-attachments/assets/ec378c67-2f5e-4fcb-8b59-564802e2f0f5" />  |
<details>
🔐 Removing all sensitive information from the …

fix: [M3-9781] - Sizing bug on LKE Tier selection

---

packages/manager/.changeset/pr-12104-upcoming-features-1745508732060.md
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.test.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsListing/AlertListing.tsx

Added an info message for failed alerts in both list & details page.
1. Added Notice for failed alert in AlertDetail.tsx
2. Added Notice for failed alert in AlertListing.tsx
Next release cycle
|![Screenshot 2025-04-24 at 7 09 40 PM](https://github.com/user-attachments/assets/174a6d40-d8cf-4217-b0b9-c4bfbf0e0bb1)|![Screenshot 2025-04-24 at 7 08 46 PM](https://github.com/user-attachments/assets/66f72f1a-9987-4804-905f-9bafef678ff7)|
|![Screenshot 2025-04-24 at 7 11 …

upcoming: [DI-24085] - Added info message for failed alerts

---

packages/manager/.changeset/pr-12097-changed-1745441238928.md
packages/manager/.changeset/pr-12097-fixed-1745441307930.md
packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
packages/manager/cypress/e2e/core/account/network-settings.spec.ts
packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts
packages/manager/src/components/TableSortCell/TableSortCell.tsx
packages/manager/src/features/Account/AutoBackups.tsx
packages/manager/src/features/Account/CloseAccountSetting.test.tsx
packages/manager/src/features/Account/CloseAccountSetting.tsx
packages/manager/src/features/Account/DefaultFirewalls.tsx
packages/manager/src/features/Account/EnableManaged.tsx
packages/manager/src/features/Account/GlobalSettings.tsx
packages/manager/src/features/Account/NetworkHelper.tsx
packages/manager/src/features/Account/NetworkInterfaceType.tsx
packages/manager/src/features/Account/ObjectStorageSettings.tsx
packages/manager/src/features/Backups/BackupDrawer.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx

Tangentially related to Linode Interfaces
- Updating Account Settings to use papers instead of accordions (and updating headings to H2 instead of H3) to a) fix the heading hierarchy for Default Firewalls section and b) make Account Settings align more with Profile Settings
- Fix firewall row services column to not take up so much width if services have super long names
- update tests that depended on accordions 
- (is there a better way to target the section than test ids? saw data-qa-paper but that didn't seem as specific)
- replace grids with stacks (not a 2d layout)
n/a
| ![image](https://github.com/user-attachments/assets/923d4c98-ecb3-4594-a7c2-3bd2cdeaf9c1) | ![image](https://github.com/user-attachments/assets/0e5b933c-3cc1-48e7-a83d-7a1f65 …

change: [M3-9613, M3-9795] - Replace accordions with papers in Account Settings and fix FirewallRow services column width on FirewallLanding

---

packages/manager/.changeset/pr-12112-fixed-1745593237854.md
packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketProperties.tsx

The recent routing refactor of OBJ left a bug behind, which is the abaility to navigate through the nested bucket breadcrumb navigation. It was an unfortunate omission of an instance of `history` typed as any that was neither `react-router-dom` nor `@tanstack/react-router`. Just a stray browser native history that was working until we re-routed.
- fix bucket detail breadcrumb navigation
⚠️  06/05/2025
https://github.com/user-attachments/assets/6b6cc20a-7b65-44e5-ba76-d54455885948
- Have nested folders in a bucket
- In production, notice the bucket detail nested breadcrumb navigation is broken
- In this PR notice the bucket detail nested breadcrumb navigation is working
<details> …

fix: [M3-0836] - Wrong history instance for bucket deep navigation

---

packages/manager/.changeset/pr-12101-fixed-1745467362526.md
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx

- Fixes the broken looking `Default` chip in the  _Make a Payment_ Drawer
| ![Screenshot 2025-04-23 at 11 57 50 PM](https://github.com/user-attachments/assets/2de0907b-3dc9-4948-a50f-c02f57ac07ca) | ![Screenshot 2025-04-23 at 11 57 44 PM](https://github.com/user-attachments/assets/c4a7b06b-1425-4dca-8e64-7a6b7033ac67) |
- Ensure you have at least 1 payment method on your account
- Open the _Make a Payment_ Drawer (http://localhost:3000/account/billing/make-payment)
- Verify the `Default` chip looks good
- Check for UI regressions - check on various screen sizes
<details>
🤏 Splitting …

fix: [M3-9831] - Broken Payment Method `Default` Chip in the Make a Payment Drawer

---

packages/manager/.changeset/pr-12116-fixed-1745838194419.md
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseAdvancedConfigurationDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/DatabaseConfigurationItem.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseAdvancedConfiguration/utilities.ts
packages/validation/.changeset/pr-12116-added-1745838363692.md
packages/validation/src/databases.schema.ts

Fix for Save button text when restart cluster is needed, add error message for configs with Autocomplete input, add validation for mysql.group_concat_max_len
- corrected Save button text when a cluster restart is required
- added error message handling for configuration fields using Autocomplete inputs
- implemented validation for the mysql.group_concat_max_len
6 May 2025
Database Advanced Config feature flag should be enabled.
Save button text:
- select a database cluster
- navigate to the Advanced Configuration tab
- click the "Configure" button
- update the value for one of the existing configuration items with `restarts service` label
- "Save" button text changed to "Save and Restart …

fix: [UIE-8684] - save button text fix, error message for Autocomplete, validation

---

packages/manager/.changeset/pr-12117-tests-1745841831406.md
packages/manager/cypress/e2e/core/firewalls/add-device-to-firewall.spec.ts
packages/manager/cypress/support/intercepts/firewalls.ts
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx

- Add cypress tests for the Add Linode to Firewall flow
- fix small bug with toast upon successfully adding an interface device to firewall (accidentally used device's ID instead of interface's ID)
5/6
- confirm toast when adding interface device uses interface's ID
```
pnpm cy:run -s "cypress/e2e/core/firewalls/add-device-to-firewall.spec.ts"
```
<details>
🚩 Using a feature flag …

test: [M3-9179] - Add cypress tests for adding Linodes to firewalls

---

packages/validation/.changeset/pr-12126-added-1745937083422.md
packages/validation/src/databases.schema.ts

Custom validation for `net_buffer_length`
- added custom validation for `net_buffer_length`
6 May 2025
Database Advanced Config feature flag should be enabled.
- select database cluster with MySQL
- navigate to the Advanced Configuration tab
- click "Configure" button
- select `net_buffer_length` from the dropdown and click "Add" button
- enter a value that is not a multiple of 1024
- verify that an error message is shown
<details>
➕ Adding a …

change: [UIE-8841] - custom validation for net_buffer_length

---

packages/manager/.changeset/pr-12100-tech-stories-1745464783439.md
packages/manager/eslint.config.js

This PR adds an ESLint rule blocking Cypress imports in application code. Although this rule will work, there are already two unrelated mechanisms inherently restricting these types of Cypress imports already:
1. There's both the `cypress` node_module and our own `cypress/` directory (`packages/manager/cypress/`). Our module resolution checks for the local `cypress/` directory first at the `baseUrl` instead of the `cypress` node_module. So it doesn't look like we could import from `cypress` outside of the `cypress/` directory unless using an explicit relative path like `'../../../../../node_modules/cypress/types/net-stubbing'`
2. The explicit relative path is currently restricted by the SonarJS rule: `sonarjs/no-internal-api-use`
So this rule is really just some extra prevention and can …

tech-story: [M3-8667] - Add eslint rule to to prevent import of Cypress code in main application

---

packages/manager/.changeset/pr-12120-tech-stories-1745864893717.md
packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
packages/ui/.changeset/pr-12120-fixed-1745864924644.md
packages/ui/src/components/Notice/Notice.tsx

Fixes a visual regression following the CDS refactor of the `Notice` component in #12004. 
- Removes `display: flex` from the children of the Notice components
- Alternatively, we can wrap the contents in `Typography` for each affected Notice -- I am open to discussion surrounding this approach
- Adds an additional stack in `DismissibleNotice` to replace the flexbox removed above
| Prod  | This Branch   |
| ![Screenshot 2025-04-28 at 1 39 00 PM](https://github.com/user-attachments/assets/72cb93c1-682a-457b-99ad-958a6a4394da) | ![Screenshot 2025-04-28 at 1 29 11 PM](https://github.com/user-attachments/assets/03f8c710-8cd0-497d-90cf-b9f9f93005fd) |
* Verify `Notice`s with multiple children render text and whitespace correctly.
* An example of an affected Notice can be …

fix: [M3-9856] - Fix text layout for `Notice`s with multiple children

---

packages/manager/.changeset/pr-12145-changed-1746135077680.md
packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts
packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx
packages/manager/src/features/Linodes/LinodeCreate/Details/Details.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/Details/PlacementGroupPanel.test.tsx
packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx

Tiny PR (for real this time 😉) to move the Linode create flow PG warning to the Select helper text. As we have revamped out Notices, this one needed some TLC, following the same treatment done on the VPC panel.
The banner for availability is remaining the same above the select (in case the region does not have PG capability, which seems like it's almost never displayed since they all do).
- Move Linode create flow PG warning to PG select helper text
| ![Create Linode OS (1)](https://github.com/user-attachments/assets/adb53aa0-13eb-4d51-9485-bf7ca250f56c) | ![Create Linode OS](https://github.com/user-attachments/assets/4d87389a-2cc4-453e-bf86-60b9807342df) |
- Navigate to Linode crate flow
- Confirm UI …

change: [M3-9835] - Move Linode create flow PG warning to helper text

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx

The first PR for this (#12067) didn't adequately address this issue for both cluster tiers. Users can still enter invalid text into the IP addresses field, delete it, and the error validation persists. The issue was less noticeable with LKE-E, because the user must either provide a valid IP or check the acknowledgement checkbox (at which point the field is cleared and disabled, so the error validation is gone). For LKE (standard), the user may create a cluster with ACL enabled _without_ providing IP addresses. Users are currently blocked by a validation error if they enter invalid text and clear the field because the error persists.
- Moved the IP validation from onBlur to onChange... the reason that the validation wasn't being cleared was the IPs being validated were the old data, not …

fix: [M3-9891] - Actual fix for 'Improve validation and UX for ACL IP Address fields'

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx

When upgrading an LKE cluster, Cloud Manager should tell you what version you upgraded to upon completion. However, it seems that the upgraded version reported can be incorrect if you're upgrading an older version to a version that isn't the latest. 
Users have observed this from the cluster details page, but not the cluster landing page:
The [pre-upgrade message](https://github.com/linode/manager/blob/develop/packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx#L148-L158) calls currentVersion and [nextVersion](https://github.com/linode/manager/blob/develop/packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx#L45), which is expected behavior.
However, the [upgrade-complete message](https://github.com/linode/manager/blob/develop/packages/manager/src/features/Kubernet …

fix: [M3-9886] - Update how UpgradeVersionModal handles versioning to account for upgrades to versions older than the latest

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/SuccessDialogContent.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRowFirewallsCell.tsx
packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx
packages/manager/src/hooks/useInterfaceAndFirewallDataForLinode.ts
packages/manager/src/hooks/useInterfaceDataForLinode.ts
packages/queries/src/linodes/interfaces.ts

> [!important]
> merging this into staging
Fixes error received when trying to update interface's firewall after upgrade
Fixes link issue when navigating to /networking
- invalidate all firewalls for reasons similar to deleting an interface - we don't easily know the interface's firewall ID
- update link splicing
5/6
these errors shouldn't appear anymore:
- Have the customer tag and have Linode Interfaces flag enabled
Issue 1:
- Upgrade an Linode with a firewall 
- Go to network tab and edit interfaces, changing the firewall
- Note how 'Unable to find this Interface's firewall device" appears
Issue 2:
- Upgrade an Linode with a firewall 
- Go to network tab and edit interfaces
- Notice how link may have an extra /networking
- Confirm  'Unable to find this Interface's firewall device" …

fix: [M3-9883] - Fix Upgrade Interface issues: URL navigation and `Unable to find this Interfaces Firewall device` in Edit Interface Drawer 

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Linodes/LinodeCreate/Actions.tsx
packages/manager/src/features/Linodes/LinodeCreate/Firewall.tsx
packages/manager/src/features/Linodes/LinodeCreate/FirewallAuthorization.tsx
packages/manager/src/features/Linodes/LinodeCreate/Networking/Firewall.tsx
packages/manager/src/features/Linodes/LinodeCreate/Networking/InterfaceFirewall.tsx
packages/manager/src/features/Linodes/LinodeCreate/index.tsx
packages/manager/src/features/Linodes/LinodeCreate/resolvers.ts
packages/manager/src/hooks/useSecureVMNoticesEnabled.ts

> [!important]
> merging this into staging
- Updates the Linode Create flow to support Akamai Employee Banners when using the new Linode Interfaces UI 😐
> [!important]
> You'll want to test both with Linode Interfaces enabled and disabled. (We need to ensure the old Linode Create UI still works as expected)
> To enable Linode Interfaces, you need the `new-interfaces-beta` customer tag and to enable Cloud Manager's Linode Interfaces feature flag
- Check out locally
- Go into `packages/manager/src/hooks/useSecureVMNoticesEnabled.ts` and edit the code so that `secureVMNoticesEnabled` is forcefully enabled for the sake of testing
- Verify that the Linode Create flow internal only Akamai employee banners work correctly and show in the correct conditions
<details>
<summary> Author Checklists …

feat: [M3-9890] - Support Akamai Employee Banners on the Linode Create flow when using Linode Interfaces

---

packages/manager/.changeset/pr-12086-tests-1745341477625.md
packages/manager/cypress/e2e/core/account/restricted-user-details-pages.spec.ts

Add test to check restricted users are not allowed to operate in the following details pages:
- Linodes
- Images
- Volumes
- Databases Cluster
- Kubernetes
- Longview
- Add integration tests for `restricted user details pages`
```
yarn cy:run -s "cypress/e2e/core/account/restricted-user-details-pages.spec.ts"
```
- M3-9522
- M3-9585
- M3-9586

test: [M3-7515] - Add Cypress integration tests for restricted user details page

---

packages/manager/.changeset/pr-12127-tests-1745948285700.md
packages/manager/cypress/e2e/core/databases/create-database.spec.ts
packages/manager/cypress/support/util/regions.ts

Fix DBaaS Cypress test region mocks so tests pass in DevCloud
- Add mock region to the regions list of DBaaS capabilities
- Fix minor issue in test `cannot create database from Create menu`
```
yarn cy:run -s "cypress/e2e/core/databases/create-database.spec.ts"
yarn cy:run -s "cypress/e2e/core/databases/delete-database.spec.ts"
yarn cy:run -s "cypress/e2e/core/databases/resize-database.spec.ts"
yarn cy:run -s "cypress/e2e/core/databases/update-database.spec.ts"
```

test: [M3-9479] - Fix DBaaS Cypress test region mocks so tests pass in DevCloud

---

packages/manager/.changeset/pr-12164-tests-1746553359993.md
packages/manager/cypress/support/api/objectStorage.ts

This improves the stability of our Object Storage bucket clean up that occurs before our end-to-end OBJ tests run. During clean up, our tests fetch all of our buckets using the `/object-storage/buckets` endpoint. If any clusters are down, this endpoint responds with a 500 and causes the tests to fail.
This PR takes inspiration from our OBJ landing page by fetching buckets by region, accounting for API errors that might occur on a region-by-region basis, and cleaning up any buckets that were successfully fetched.
- Improve OBJ bucket clean up resiliency when one or more clusters are down
N/A
We can rely on CI to confirm that this change doesn't break our Object Storage tests. Testing that it behaves as expected is slightly more difficult. Right now I'm observing intermittent issues with …

test: [M3-9915] - Improve Cypress OBJ bucket clean up stability

---

packages/manager/.changeset/pr-12172-tests-1746640484987.md
packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts

This is a quick fix for the Linode rebuild tests, which are currently failing due to the Alpine 3.18 Image being deprecated. This fixes it by using 3.20 instead, but M3-9872 will properly address this by fetching the latest Image label/ID dynamically.
- Use Alpine 3.20 instead of Alpine 3.18 in Linode rebuild test
N/A
- Confirm that rebuild tests pass in CI
- **Note:** the Linode rebuild tests are flaky outside of this issue, so it's not unlikely that these tests may still fail. If so, the important point is that they don't fail because they're trying to select Alpine 3.18 from the Image dropdown.
- See also M3-9872 which aims to improve the stability of the tests in `linode-rebuild.spec.ts`
<details> …

test: [M3-9924] - Fix Cypress rebuild test by using Alpine Linux 3.20 Image following deprecation of 3.18

---

docs/CONTRIBUTING.md
scripts/changelog/changeset.mjs

During our last team retro, we discussed ways to automate some of the issues we've seen with changeset inconsistencies to reduce the need for manual editing of the changelog.
This PR implements some basic validation rules based on our existing best practices ([docs](https://linode.github.io/manager/CONTRIBUTING.html#writing-a-changeset)) and things we've discussed, such as changesets that are too long because they're overly descriptive.
- Adds validation to the description prompt in `changeset.mjs`
- Links the best practices in the description prompt when generating a changeset for easy reference
- Updates our docs to mention the character limit
| Bad description | Error   |
| Changeset starts with lowercase letter | ![Screenshot 2025-05-07 at 11 00 …

change: [M3-9925] - Add validation rules on changeset description

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx

Fixes a small bug with the Object Storage access key drawer resulting from the routing refactor 
- fix Object Storage access key drawer state
⚠️ 5/9/2025
- Navigate to /object-storage/access-keys
- Click "Create Access Key" and close drawer
- Click "Edit" in the action menu for any existing access key
- Click "Create Access Key" > Notice edit drawer reopens
- Navigate to /object-storage/access-keys
- Click "Create Access Key" and close drawer
- Click "Edit" in the action menu for any existing access key
- Click "Create Access Key" > Confirm right drawer opens
<details>
➕ Adding a …

hotfix: [M3-9944] - State issue with Object Storage access key drawer

---

.eslintrc.js
packages/manager/.changeset/pr-12195-tech-stories-1747064399669.md

- Small clean up following https://github.com/linode/manager/pull/11941
- Removes the root level `.eslintrc.js` because it is not used and not needed that we are on ESLint v9 using the new flat config approach
- Run `pnpm lint:all`
- Verify linting succeeds for all packages without any issue
- Verify all linting-related Github Actions pass 
<details>
🚩 Using a …

tech story: [M3-9964] - Delete root level `.eslintrc.js`

---

packages/manager/.changeset/pr-12159-fixed-1746488156627.md
packages/manager/src/components/AkamaiBanner/AkamaiBanner.styles.ts
packages/manager/src/components/AkamaiBanner/AkamaiBanner.tsx

Fixes a visual regression in the internal Firewall warning banner caused by the switch to CDS icons.
- Switch from `WarningIcon` to `WarningOutlinedIcon` in `AkamaiBanner.styles.ts`.
The original `WarningIcon` from MUI was outlined but the CDS one is not.
| | Prod  | This Branch   |
|-| ------- | ------- |
|Light Mode | ![Screenshot 2025-05-05 at 7 29 35 PM](https://github.com/user-attachments/assets/b4fd6f2b-4379-4b22-94ca-9ba8216e8406) | ![Screenshot 2025-05-05 at 7 29 15 PM](https://github.com/user-attachments/assets/90012e4c-1423-4e37-8ee3-d773ab690224) |
| Dark Mode | ![Screenshot 2025-05-05 at 7 29 42 PM](https://github.com/user-attachments/assets/389d6bd8-0488-4ee5-915b-8968d0ee5bcb) | ![Screenshot 2025-05-05 at 7 29 24 PM](https://github.com/user-attachments/assets/9361ae06-50fd-42 …

fix: [M3-9894] - Use outlined warning icon in Firewall warning banner

---

packages/manager/.changeset/pr-12194-fixed-1747062971408.md
packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptRow.tsx

- Fixes truncation on the StackScript landing page 
- I don't remember the cause. I think it was MUI v6 or the UI overhaul a few weeks back
| ![Screenshot 2025-05-12 at 11 12 53 AM](https://github.com/user-attachments/assets/bea35395-037e-4fd2-b023-c8b2581613ad) | ![Screenshot 2025-05-12 at 11 12 44 AM](https://github.com/user-attachments/assets/3480e408-82ac-4cf4-8e4b-e23bcdd51cbc) |
- Checkout this PR or use the internal preview link
- Go to http://localhost:3000/stackscripts/community
- Verify that StackScript descriptions and labels are gracefully truncated
- Verify it looks acceptable on all viewports
<details> …

fix: [M3-9958] - StackScripts Landing description truncation

---

packages/api-v4/.changeset/pr-12188-upcoming-features-1747068993421.md
packages/api-v4/src/kubernetes/nodePools.ts
packages/api-v4/src/kubernetes/types.ts
packages/manager/.changeset/pr-12188-upcoming-features-1747069173199.md
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
packages/manager/src/mocks/presets/crud/handlers/kubernetes.ts
packages/manager/src/queries/kubernetes.ts
packages/validation/.changeset/pr-12188-upcoming-features-1747069233094.md
packages/validation/src/kubernetes.schema.ts

Ahead of supporting the ability to update a Node Pool's `k8_version` and `update_strategy` in the UI (M3-9200 - designated as post-LA), we should update 'Add a Node Pool' for existing LKE-E clusters to use the `/v4beta` POST endpoint. The new node pools will be created with the default values assigned for the fields because neither field is required.
This should be done now, pre-LA before version/update support, because newly created NPs should have the same fields as NPs that were created when the cluster was first created. Also, LKE-6988 was raised and the cause/fix was determined to be the unintended enablement of the firewall feature in devcloud, but it is also correct to state that we should be using v4beta. With the v4beta endpoint, `firewall_id` is assigned its default 0.
- New …

fix: [M3-9957] - Add `/v4beta` endpoints for Node Pools and use POST `/v4beta` when adding a new LKE-E Node Pool

---

packages/manager/.changeset/pr-12200-fixed-1747084073178.md
packages/manager/src/components/LandingHeader/LandingHeader.tsx

Fix console warnings related to "**:first-child"** pseudo class in LAndingHeader component.
5/20
<details>
♿ …

fix: [M3-9969] - Fix console warnings related to first-child pseudo class in LandingHeader component

---

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx

Quick follow up to correct something in #12188: we should just check the `clusterTier` here (Hana was right) rather than feature flag + cluster tier because it will allow Beta users with existing LKE-E clusters to add node pools to their clusters via UI.
Should we need to support this yet? Not really, because UI support for Beta users isn't intended. But LKE-E clusters *are* still visible in the UI as normal LKE clusters, and the reality is that users are sometimes trying to use the UI to do things that could cause unexpected behavior when they switch back over to CLI tools.
- Removes the feature flag check gating the use of the v4beta endpoint. Having an LKE-E cluster is enough.
- No changeset since 12188 wasn't released.
5/20
- See the linked PR.
(How to …

fix: [M3-9957] - Remove the feature flag check so that beta customers can add Node Pools to existing LKE-E cluster

---

packages/manager/.changeset/pr-12215-changed-1747223125401.md
packages/manager/.changeset/pr-12215-fixed-1747230804629.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
packages/ui/src/components/Paper/Paper.tsx

Currently, 
- The Alerts form on Linode Details page is enclosed within an accordion component, which includes a dropdown arrow to expand/collapse the form section. The goal is to remove the accordion functionality so that the form is always visible on the page. The form should always be visible (expanded), and there should be no toggle/arrow element.
- Toggling off correctly resets the value to zero, but this does not happen when clearing the fields manually, even though the toggle turns off. This PR fixes the issue by resetting the values to zero (avoiding them being set to an empty string/ NaN) when the fields are cleared manually.
- ♻️ Removed the `Accordion` wrapper from the default Alerts tab and replaced it with `Paper` on the Linode details page
- 🔧 Fixed the issue where clearing …

change: [M3-9947] - Remove Accordion wrapper from default Alerts tab on Linode details page

---

packages/manager/.changeset/pr-12218-tests-1747241849916.md
packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
packages/manager/cypress/support/util/linodes.ts

This unskips the Firewall E2E tests that we started skipping a couple months ago due to some API issues (#11898). It also makes a few additional changes in order to get the tests to play nicely with some of the Linode Interfaces improvements that have been made in the meantime.
- Unskip Firewall E2E tests
- Update `createTestLinode` to prevent implicit Firewall creation
N/A
We can rely on CI for this. However, you can also run the Firewall tests locally using this command:
```bash
pnpm cy:run -s "cypress/e2e/core/firewalls"
```
I was able to run all the Firewall tests 10 times in a row without encountering any failures.
<details> …

test: [M3-9619] - Un-skip Cypress Firewall E2E tests

---

packages/manager/.changeset/pr-12226-tests-1747314916451.md
packages/manager/cypress/support/util/regions.ts

This fixes test failures for accounts that have Gecko enabled when Cypress performs API operations using randomly chosen regions. Because distributed sites don't support all Linode types, etc., we'll exclude them from the `chooseRegion` output by default.
- Exclude distributed sites from `chooseRegion` output by default
- Add `includeDistributed` option to `chooseRegion`
N/A
- Enable Gecko on your account
- Observe that there are no test failures stemming from distributed region incompatibilities
To make testing easier, I wrote a quick test to check the output of `chooseRegions`, which you can also insert into some spec and run:
```typescript
it.only('test chooseRegion', () => {
for(let i = 0; i < 1000; i += 1) {
const region = chooseRegion();
expect(region.site_type).to.equal('core');
} …
```

test: [M3-9985] - Exclude distributed regions from `chooseRegion` output by default

---

packages/ui/.changeset/pr-12208-fixed-1747157830376.md
packages/ui/src/foundations/themes/light.ts

Small PR to fix the placeholder opacity so we are showing the right color. Right now the placeholder text is barely readable (likely failing most accessibility standards), because of the default opacity applied to it in the MUI styles.
This style change will apply to all text inputs (Textfield, Text area, Autocomplete etc)
- Set placeholder opacity back to `1` to get the proper CDS placeholder color
| ![Screen Shot 2025-05-13 at 13 27 04](https://github.com/user-attachments/assets/de9962c1-2cc4-4626-ae7d-793e18a64129) | ![Screen Shot 2025-05-13 at 13 20 02](https://github.com/user-attachments/assets/8747920c-b27d-4a51-a5ba-5c8bfd5520a5) |
| ![Screen Shot 2025-05-13 at 13 32 22](https://github.com/user-attachments/assets/90f9ca35-43aa-4fea-827a-7f …

fix: [M3-9968] - Input placholder opacity

---

packages/manager/.changeset/pr-12252-fixed-1747765194838.md
packages/manager/.changeset/pr-12252-fixed-1747765254237.md
packages/manager/src/features/Events/factories/linode.tsx

When resizing a Linode without the "Auto Resize Disk" option checked off, the events menu/feed in Cloud Manager will say "Resizing Linode to $current_plan" rather than the plan that the user is resizing to.
There's no way to really fix this on our end since the plan info is returned from the API (which may be intentional). Rather than going through a lot of troubleshooting to achieve something we may not be able to, this PR simplifies the event to make it more generic and will avoid confusion for some users.
- Make `linode_resize` "started "event generic
| …

fix: [M3-9900] - Simplify `linode_resize` started event

---

packages/manager/.changeset/pr-12243-upcoming-features-1747670800164.md
packages/manager/src/components/Snackbar/ToastNotifications.stories.tsx
packages/manager/src/features/Events/factories/interface.tsx
packages/manager/src/features/Events/utils.test.tsx
packages/manager/src/features/Events/utils.tsx
packages/manager/src/hooks/useEventHandlers.ts
packages/manager/src/queries/linodes/events.ts

- Makes some tweaks to the Linode Interface event messages so that they show up
- They are being returned with status `notification` rather than `started`, `failed`, `finished`, etc...
- Does some clean up on our Event Message factory utils 🏭 
- Added a React Query event handler for Linode Interfaces to give a realtime-like experience
| Event messages for Linode Interfaces were not showing up | ![Screenshot 2025-05-19 at 11 53 22 AM](https://github.com/user-attachments/assets/19a657f3-6b0c-4b45-acdb-31b13ed12c69) |
I added some console warning for when an event message factory is not defined
https://github.com/user-attachments/assets/65b5b770-bf7c-4da4-b33a-4c764f222add
- `new-interfaces-beta` customer tag
- Linode Interfaces feature flag …

upcoming: [M3-9999] - Event message tweaks for Linode Interfaces

---

packages/manager/.changeset/pr-12244-tech-stories-1747680484622.md
packages/ui/src/foundations/breakpoints.ts

- Migrates from a hacky way of creating breakpoints to what seems like a slightly less hacky way
- The function is prefixed with `unstable_`, but I think it's okay.  Hopefully MUI will promote it to stable soon. Worst case we just revert this PR if we start seeing issues
- The createBreakpints function has a confusing history. It existed a long time ago and we used it, but then it was removed in v5 (which is when we introduced the hacky approach), but then it was added back as `unstable_createBreakpoints` recently.  Hopefully it is here to stay.... 🤞 
- In most cases, you can just define the breakpoints in the theme itself, but for our codebase, it is not that straightforward. See https://github.com/linode/manager/pull/11867#discussion_r2002030395 for a long explanation 
- Checkout the PR …

chore: [M3-9606] - Use `unstable_createBreakpoints` to define our MUI breakpoints

---

packages/manager/.changeset/pr-12251-upcoming-features-1747763494658.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx

As reported by LKE QA, the amount of time it takes to fully provision LKE-E cluster nodes has increased since we originally determined that nodes were provisioned within 10 minutes or less. (On staging, it takes ~1110s, or ~18 minutes.)
This PR updates the util and copy to display this message for the first 20 minutes after cluster creation.
- Renamed the util for `20` min and updated the interval
- Updated the copy to mention 20 minutes
- Updated test coverage
6/3
| ![Screenshot 2025-05-20 at 10 41 39 AM](https://github.com/user-attachments/assets/9e092420-e7ad-4a9a-961b-ac0020f13919) | ![Screenshot 2025-05-20 at 10 41 22 AM](https://github.com/user-attachments/assets/de4b66ef-ff61-447c-9dd4-4c3b7b1f63eb)|
- Have …

change: [M3-9997] - Update estimated time for LKE-E node pool pending creation message

---

packages/manager/.changeset/pr-12265-tech-stories-1747931205927.md
packages/manager/src/constants.ts
packages/manager/src/hooks/useAdobeAnalytics.ts

We're currently firing a Sentry error in the `useAdobeAnalytics` hook where one of the conditions checks that the number of Adobe-related scripts is 3. When we shared an Adobe Launch script with Login, 3 scripts were always loaded.
With the switch to the new Adobe Launch script, we're loading less Adobe-related scripts (2, but if the user's cookie preferences enable us to load Pendo, 3). 
The Sentry error was misleading because Adobe Analytics was still loading and sending events. It also caused rate limiting by Sentry due to the number of users seeing the error, so Sentry errors started getting dropped.
It would be best to just remove the number of scripts check altogether, since we can't really be certain how many scripts Adobe is loading.
- Updated the conditional for the error and …

fix: [M3-10008] - Fix erroneous Sentry error condition in Adobe Analytics hook

---

packages/manager/.changeset/pr-12266-upcoming-features-1747938663753.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/queries/kubernetes.ts

The Kubernetes Dashboard is not available to LKE-E clusters (note that the button is not shown in the UI), so we should disable that query when the cluster tier is enterprise. We weren't conditionally enabling useKubernetesDashboardQuery and should be.
- Update the `useKubernetesDashboardQuery` to accept an enabled prop
- Pass in a check for the cluster tier to enable the query in the Kubernetes summary panel
- Update Cypress test
6/3/25
| ![Screenshot 2025-05-22 at 10 58 35 AM](https://github.com/user-attachments/assets/5059e366-d137-463f-9381-2f385f8767c1) | ![Screenshot 2025-05-22 at 11 03 15 AM](https://github.com/user-attachments/assets/bb5edb81-92b1-49f4-82ff-ef99843a8f0c) |
- Have an LKE-E cluster on your …

fix: [M3-10011] - Disable the Kubernetes Dashboard request for LKE-E clusters

---

package.json
packages/manager/.changeset/pr-12267-tech-stories-1747942707347.md
packages/manager/eslint.config.js
packages/manager/src/components/Avatar/Avatar.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDisks.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
packages/manager/src/features/Linodes/LinodesDetail/utilities.ts
packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
pnpm-lock.yaml

- Brings back `eslint-plugin-react-refresh` after #11941  and configures it to `warn`
- Addresses the warning in a few places for the sake of example / testing 🧪  
- Removes `rxjs` as a restricted import. `rxjs` isn't a direct dependency in our repo so typescript will error if you try to import it. No need to lint it anymore. I think this rule is just left over from a long time ago when CLoud Manager dependend on rxjs 🤮 
- Run `pnpm install`
- Restart the eslint server
- If you use VSCode, you can do `cmd` + `shift` + `p` and type `Restart ESLint Server` and press `Enter`
- Open `packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeVolumes.tsx` in your editor
- Verify you see the following warning:
- Verify lint github actions pass
- Verify `pnpm …

chore: [M3-10036] - Re-add `eslint-plugin-react-refresh` eslint plugin

---

packages/api-v4/.changeset/pr-12272-fixed-1748009649223.md
packages/api-v4/src/quotas/quotas.ts
packages/api-v4/src/quotas/types.ts
packages/manager/.changeset/pr-12272-fixed-1748009662401.md
packages/manager/src/factories/quotas.ts
packages/manager/src/mocks/presets/crud/handlers/quotas.ts
packages/queries/src/quotas/keys.ts
packages/queries/src/quotas/quotas.ts

Small fix to correct the `quota_id` type to be a string as outlined in the [docs](https://techdocs.akamai.com/linode-api/reference/get-object-storage-quotas)
This was an omission when switching from the Compute quotas to the OBJ quotas since these have different types.
Run code is essentially unaffected since we were already doing the right transformations
- change `quota_id` type to string
- update run time code
⚠️ 06/03/2025
There should be no change or regression as a part of this PR
Confirm the Quotas UI (/account/quotas) is unaffected
<details>
➕ Adding a …

fix: [M3-100041] - Make `quota_id` type a string

---

packages/manager/.changeset/pr-12269-fixed-1747981241068.md
packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Images.tsx

Fixes the image select input overflowing off-screen on mobile viewports.
- Updated the width of the image select input on mobile to align with other select components.
| ![Before](https://github.com/user-attachments/assets/5faf2bff-511d-4656-97d7-3a8f8cfab687) | ![After](https://github.com/user-attachments/assets/11630a91-26d8-4449-8b49-30398435242a) |
1. Navigate to `/linodes/create?type=Images`.  
2. On a mobile viewport, confirm the image select input fits within the screen and aligns with other inputs.
<details>
➕ Adding a …

fix: [M3-9990] - Image Select overflows off screen on mobile viewports

---

packages/manager/.changeset/pr-12268-changed-1747968191432.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/kubeUtils.ts

Kubernetes APL is in the BETA program and is going GA on June 16. The timing of the GA release is unfortunate; since it is one day before the 6/17 release, this one needs to go out on the 6/3 release.
As a result, we do not need to check the BETA program to see if the user opted in, and we need to switch to using the `v4` endpoint since it's been promoted from `v4beta`.
This PR implements the UI logic while keeping LKE enterprise checks in mind (since LKE enterprise does not support APL quite yet). The flow reflects those changes, both in the display of the APL panel and its `BETA` labeling.
> [!NOTE]
> Because of the ephemeral nature of this logic (both the `apl` and `aplGeneralAvailability` will be promptly removed once GA has been validated, no coverage has been added to cover this …

change: [M3-9687] - Prepare LKE APL for GA

---

packages/manager/.changeset/pr-12259-tests-1747849345030.md
packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
packages/manager/cypress/e2e/core/linodes/upgrade-linode-interface.spec.ts
packages/manager/cypress/support/constants/linode-interfaces.ts
packages/manager/cypress/support/intercepts/linodes.ts
packages/manager/cypress/support/util/linodes.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/UpgradeInterfaces/DialogContents/ConfigSelectDialogContent.tsx
packages/utilities/src/factories/linodeInterface.ts

Add integration tests for Upgrade legacy interface to new Linode Interface flow
- Add test cases `Upgrade new Linode Interfaces flow` in `linode-config.spec.ts`
- Add integration test `upgrade-linode-interface.spec.ts`
```
pnpm cy:run -s "cypress/e2e/core/linodes/linode-config.spec.ts"
pnpm cy:run -s "cypress/e2e/core/linodes/upgrade-linode-interface.spec.ts"
```

test: [M3-9176] - Add integration test for Upgrade to new Linode Interface flow

---

packages/manager/.changeset/pr-12278-upcoming-features-1748242133984.md
packages/manager/src/features/DataStream/Streams/StreamCreate/EventTypeDetails.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreate.styles.ts
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreate.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSet.test.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSet.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateDataSetData.ts
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateGeneralInfo.test.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/StreamCreateGeneralInfo.tsx
packages/manager/src/features/DataStream/Streams/StreamCreate/types.ts

DataStream: General Information and Data Set forms
- General Information form
- Data Set form 
July 2025
| ![before](https://github.com/user-attachments/assets/8cd5796e-d54e-4070-8f6d-57c871c62502) | ![after](https://github.com/user-attachments/assets/99606ab8-b1c2-4fdd-8d55-b8eb4436bde4) |
- navigate to datastream/streams/create
- check both forms
<details>
<br/>
</details>

upcoming: [DPS-33114] Add General Information and Data Set forms

---

packages/manager/CHANGELOG.md
packages/manager/src/features/Kubernetes/CreateCluster/PremiumCPUPlanNotice.tsx

We've had an internal request to update the copy for  the existing info notice we display encouraging premium plan use for LKE node pools.
This copy should be displayed for all LKE tiers (standard and enterprise).
- Update the copy in the notice, which is used on both the create cluster and 'Add a Node Pool' cluster details flow.
> [!NOTE] 
> I'm going to let this sit before merging for a day to let any final copy changes settle.
⚠️  6/3/25 - this PR is pointed at staging
| Create flow: ![Screenshot 2025-05-29 at 12 20 04 PM](https://github.com/user-attachments/assets/6237a3a2-c78c-418c-a7c9-7a94c131222a) Add a Node Pool drawer: ![Screenshot 2025-05-29 at 12 20 26 PM](https://github.com/user-attachments/assets/486b4e96-8281-44fc-9636-71d2d9b2a981 …

change: [M3-10061] - Update copy for LKE premium CPU notice

---

packages/manager/.changeset/pr-12301-fixed-1748616080981.md
packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx

The SMS Notice component currently has custom styling that clashes with our Akamai Design System (ADS) recommendations. These custom styles need to be identified and removed to ensure consistency with our design system standards.
- Removed styled component
- Removed bolding
N/A
| ![Screenshot 2025-05-29 at 2 58 25 PM](https://github.com/user-attachments/assets/e45b02c7-d422-45c6-a5b2-8ad6fdde04ec) | ![Screenshot 2025-05-29 at 2 59 34 PM](https://github.com/user-attachments/assets/4ef10b03-81b3-4c30-906c-3f9b1aa151c4) |
| ![Screenshot 2025-05-29 at 2 58 15 PM](https://github.com/user-attachments/assets/a98a6a38-fbc4-4814-a167-326676632b24) | ![Screenshot 2025-05-29 at 2 59 40 PM](https://github.com/user-attachments/assets/389bfc91-a95f-46bd-8415-e …

fix: [M3-10067] - Remove custom styling for SMS Notice

---

packages/manager/.changeset/pr-12187-tests-1746812945790.md
packages/manager/cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts
packages/manager/cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts
packages/manager/cypress/support/constants/linode-interfaces.ts
packages/manager/cypress/support/ui/pages/linode-create-page.ts
packages/manager/cypress/support/util/linodes.ts

Update / Add integration tests for Create Linode
- Add function `checkLinodeInterfacesElements()`
- Update legacy integration tests for Create Linode
- Add Linode Interfaces integration tests for Create Linode
```
yarn cy:run -s "cypress/e2e/core/linodes/create-linode-with-firewall.spec.ts"
yarn cy:run -s "cypress/e2e/core/linodes/create-linode-with-vlan.spec.ts"
yarn cy:run -s "cypress/e2e/core/linodes/create-linode-with-vpc.spec.ts"
```
- M3-9955

test: [M3-9178] - Update/Add integration tests for Create Linode

---

packages/utilities/.changeset/pr-12313-added-1748968238140.md
packages/utilities/.changeset/pr-12313-removed-1748968164214.md
packages/utilities/package.json
packages/utilities/src/helpers/getAll.test.ts
packages/utilities/src/helpers/getAll.ts
pnpm-lock.yaml

- Removes `ramda` 👹 from the `@linode/utilities` package by removing it from the `getAll` helper function
- Adds a unit test for the `getAll` function 🧪 
- Verify the new ramda-less code seems safe, performant, and does the same thing as the old code
```sh
pnpm test getAll
```
<details>
📑 …

chore: [M3-10082] - Remove `ramda` from the `utilities` package

---

packages/manager/.changeset/pr-12322-tech-stories-1748968017220.md
packages/manager/package.json
packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
pnpm-lock.yaml

- Updates `qrcode.react` to the latest version 📦  to resolve a pnpm peerDependency warning
- I'm also doing this a a percaution for compatibility with React 19. React 19 may work without updating this, but I'm doing it to be safe
- Removes `@types/qrcode.react` because `qrcode.react`  ships its own types! 🎉 
| ![Screenshot 2025-06-03 at 11 18 49 AM](https://github.com/user-attachments/assets/959aaa33-0fcf-437e-bc54-a81c90535104) | ![Screenshot 2025-06-03 at 12 25 12 PM](https://github.com/user-attachments/assets/6272714d-38a8-4e25-9222-9261fed387b9) |
| pnpm warns about `qrcode.react`'s React peerDependency  | Warning is gone |
- Checkout this PR or use a preview link
- Go to `http://localhost:3000/profile/auth`
- Go through the 2FA setup / …

chore: [M3-10089] - Update `qrcode.react` to `4.2.0`

---

packages/api-v4/.changeset/pr-12324-changed-1748976166235.md
packages/api-v4/src/databases/types.ts
packages/manager/.changeset/pr-12324-upcoming-features-1748976069707.md
packages/manager/cypress/e2e/core/databases/update-database.spec.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseManageNetworking.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseManageNetworking.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseNetworking.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseNetworking.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/utilities.test.ts
packages/manager/src/features/Databases/utilities.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/routes/databases/index.ts

This pull request creates a new Networking tab in DB details, moves Manage Access to this Networking tab, and updates the Summary tab to include a new Connection Type field that displays the Connection Type (Public vs P directs to the Networking tab.
- New Networking tab has been added created for database details
- This tab appears after Summary and Metrics
- Tab will contain two fields, Manage Access and Manage Networking
- Manage Access field has been moved here from the Settings tab and has the same behavior
- Manage Networking contains a grid showing data relating to the Connection configuration (VPC vs No VPC)
- Summary has been updated to include a row for Connection type with a link to the Networking tab
**Note:**  Manage Networking …

feat: [UIE-8619, UIE-8616, UIE-8753] - DBaaS - Creating new Networking tab in DB details,

---

packages/manager/.changeset/pr-12328-fixed-1749044302497.md
packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx

This PR fixes broken spacing in the **Banner** component and removes a console error from the **NodeBalancer Details** page.
- Fixed spacing issues in the `Banner` component.
- Removed console error on the `/nodebalancers/${nb-id}/summary` page.
N/A
| ![Before](https://github.com/user-attachments/assets/49c5d6b3-d621-4e73-8c84-20726561d187) | ![After](https://github.com/user-attachments/assets/b152e069-35ab-4350-b811-a58da6b458c3) |
| ![Before](https://github.com/user-attachments/assets/c5af816d-d02a-4fdd-ad42-f96ec26da497)  | <video src="" />  |
<details>
<summary>Author Checklists</summary>
</details>

fix: [M3-10068, M3-10078] - Fix Broken Spacing for Banner and remove console error

---

packages/manager/.changeset/pr-12356-upcoming-features-1749556168543.md
packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx

Fixes a layout issue and resolves a bug when assigning roles a second time in the Assign New Roles Drawer.
- Fixed layout issue in the Assign New Roles Drawer when an entity has a long name.
- Resolved issue where previously assigned roles reappeared after reopening the drawer and clicking the "Add another role" button.
June 17th
| ![Screenshot 2025-06-10 at 1 26 37 PM](https://github.com/user-attachments/assets/76670b0b-041b-44de-bb4f-0468a72674ab) | ![Screenshot 2025-06-10 at 1 26 07 PM](https://github.com/user-attachments/assets/b9c35fc7-fc4a-46ce-a52d-4ba7ee40142e) |
| <video src="https://github.com/user-attachments/assets/2b6c30e1-3e2b-42 …

feat: [UIE-8887] - IAM RBAC: assign new role drawer fix

---

packages/manager/.changeset/pr-12366-fixed-1749660945872.md
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurationsWrapper.tsx
packages/manager/src/routes/nodeBalancers/index.ts

- This PR Fixes a routing issue where clicking on a port under the NodeBalancer Summary page causes an "Invariant Failed" error instead of navigating to the correct configuration.
- Fixed port link routing on the NodeBalancer Summary page.
**6/17**
| ![Before](https://github.com/user-attachments/assets/963648e9-1d40-4375-80ad-eff56d3a3def) | ![After](https://github.com/user-attachments/assets/2b6698c2-bf00-45c1-8ed6-b6d5a6a84fda) |
1. Create a NodeBalancer with configurations.
2. Navigate to `/nodebalancers`.
3. Click on a port under the NodeBalancer Summary.
4. Verify it redirects to the correct configuration page.
<details>
<summary>Author Checklists</summary>
</details>

fix: [M3-10146] - Port Hyperlink for Nodebalancer showing error

---

packages/api-v4/.changeset/pr-12367-upcoming-features-1749659461264.md
packages/api-v4/src/firewalls/types.ts
packages/manager/.changeset/pr-12367-upcoming-features-1749660136458.md
packages/manager/cypress/e2e/core/firewalls/add-device-to-firewall.spec.ts
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddLinodeDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/constants.ts
packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeInterfaces/EditInterfaceDrawer/EditInterfaceForm.utils.ts
packages/manager/src/mocks/presets/crud/handlers/linodes.ts
packages/validation/.changeset/pr-12367-upcoming-features-1749660085808.md
packages/validation/src/firewalls.schema.ts

API is updating the 'interface' firewall entity type to 'linode_interface' for the upcoming 6/17 release (see API's pr in ticket comments). This PR addresses those changes on our end.
> [!NOTE]  
> This PR is dependent on the API
- "interfaces" array in POST firewall object -> linode_interfaces
- "interface" firewall entity type -> "linode_interface"
6/17
DevEnv is needed for this - these changes are not yet out in prod
- confirm existing tests pass
- Confirm no regressions to firewall flows
- Creating a Linode with a firewall
- Editing an interface's firewall from the Edit Interface drawer
- Adding / removing an interface device from the firewall's detail page
- Creating a new firewall
<details>
❔ Our …

upcoming: [M3-9987] - Update `interface` firewall entity type to `linode_interface`

---

packages/manager/.changeset/pr-12368-upcoming-features-1749718711216.md
packages/manager/CHANGELOG.md
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
packages/manager/src/features/NodeBalancers/VPCPanel.test.tsx
packages/manager/src/features/NodeBalancers/VPCPanel.tsx
packages/manager/src/features/VPCs/constants.ts

- Add descriptions finalized by UX
6/17
| ![image](https://github.com/user-attachments/assets/9208d44c-110d-4ea5-8578-175caaeb5b3f) | ![image](https://github.com/user-attachments/assets/d59cc2a5-fc7a-4148-88ec-597405096774) |
- Toggle the NodeBalancer-VPC Integration feature flag
- Navigate to the Create Nodebalancer page
<details>
🔐 Removing all sensitive information from …

upcoming: [M3-10151] - UX description changes for VPC Section in the create NodeBalancers page

---

packages/manager/CHANGELOG.md
packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeEntityDetailFooter.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
packages/manager/src/features/NodeBalancers/VPCPanel.test.tsx
packages/manager/src/features/NodeBalancers/VPCPanel.tsx
packages/manager/src/features/VPCs/constants.ts
packages/manager/src/queries/cloudpulse/services.ts
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Highlight the Pull Request's context and intentions.
- Fixed issue where table headers had hoverable background color in light mode.
- NB-VPC: add descriptions finalized by UX on Create NodeBalancer page (#12368)
- Fixed: Set default `enabled` to `false` for `useCloudPulseServiceByServiceType` query
- This query is no longer used in the develop branch for the next release (June 24th), but we are keeping it in `cloudpulse/services` for potential future use. In staging, however, it is currently tied to feature flag work, and we do not want it to be called. This change prevents the query from running in staging or upcoming prod release (June 17th)
- Fixed: Remove account capability checks preventing restricted users from enabling HA and ACL on Kubernetes clusters
6/17
| …

Release Hotfix Branch - 6-12-2025

---

packages/manager/.changeset/pr-12396-upcoming-features-1750171179709.md
packages/manager/src/features/Linodes/LinodeCreate/Summary/Summary.tsx

As part of the ACLP-Linode integration for legacy/beta alerts, we want to display an "Alerts Assigned +n" count in the summary section on the Create Linode page. This will help users understand how many beta alerts have been assigned during the linode creation process.
- Add Beta "Alerts Assigned +n" Count logic to Linode Create Flow Summary
N/A
- ACLP-supported regions:
- Non ACLP-supported regions:
- Enabled MSW and `aclpBetaServices.alerts` feature flag
- Navigate to the Linode Create page
- For ACLP-supported (mocked) regions (Washington, DC or Newark, NJ):
- Go to Additional Options -> Alerts -> Beta Mode
- Verify "Assigned Alerts +n" is visible with a tooltip displaying enabled beta alert IDs in the summary section if the assigned `beta alerts count > 0`
- Verify "Assigned Alerts 0" …

upcoming: [M3-10192] - Add Beta "Alerts Assigned +n" Count to Linode Create Flow Summary

---

packages/manager/src/features/Kubernetes/CreateCluster/ControlPlaneACLPane.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeControlPaneACLDrawer.tsx
packages/ui/src/components/Toggle/Toggle.stories.tsx
packages/ui/src/components/Toggle/Toggle.tsx

Following the merge of the Toggle ADS [PR](https://github.com/linode/manager/pull/12303), a regression is introduced in the Linode Create flow. The Legacy Mode Alerts toggles are now incorrectly enabled when they should be disabled/ready-only.
> [!Note]
> - The toggle ADS PR was merged after the release cut, so a `changeset` for this PR is not required
> - We'll create a separate ticket (if one doesn't already exist) to add tests ensuring that Legacy Alerts are disabled in the Create Linode flow and enabled in the Linode Details/Edit flow cc: @jdamore-linode @dmcintyr-akamai
- Removed duplicate `disabledToggle` prop introduced in Toggle ADS https://github.com/linode/manager/pull/12303
1 July (Next release)
| On Dev branch  | On this branch   |
| ![Screenshot …

fix: [M3-10208] - Legacy Alerts toggle incorrectly enabled on Create Linode page after ADS toggle PR merge

---

packages/manager/.changeset/pr-12387-changed-1750576427858.md
packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/manager/src/features/Account/Quotas/QuotasIncreaseForm.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseEngineSelect.tsx
packages/manager/src/features/Firewalls/components/FirewallSelect.tsx
packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
packages/manager/src/features/StackScripts/StackScriptLanding/StackScriptLandingTable.tsx
packages/manager/src/features/Support/AttachFileListItem.tsx
packages/ui/.changeset/pr-12387-changed-1750089697664.md
packages/ui/src/components/TextField/TextField.test.tsx

Refactor `TextField` and `Autocomplete` components to correctly use `InputAdornment` for adornments.
- Refactor all `TextField` and `Autocomplete` components using `startAdornment` or `endAdornment` to wrap adornments with `InputAdornment`.
N/A
- Refactor all adornment usages using `InputAdornment`  
- Verify consistent appearance and behavior in both light and dark modes  
- Ensure no UI or layout regressions
<details>
🔐 Removing all sensitive …

change: [M3-9529] - Akamai Design System: inputAdornments

---

packages/manager/.changeset/pr-12410-upcoming-features-1750687946787.md
packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
packages/manager/src/features/IAM/Shared/constants.ts
packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.test.tsx
packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.tsx
packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx

Add the docs links, fix the bugs
- Add the links for the docs and Learn more buttons
- Fix the typo
- Fix the style issue
07/01
| ![image](https://github.com/user-attachments/assets/d967cccc-e5b3-4d7b-943b-44edb3b58915) | ![image](https://github.com/user-attachments/assets/6235e509-aaec-4c8c-b21f-501ec2fb2887) |
- Use devenv and login as vagrant user
<details>
➕ Adding a …

feat: [UIE-8534, UIE-8888, UIE-8881] - IAM RBAC: add the links

---

packages/manager/src/features/IAM/Users/UserDetails/UserEmailPanel.test.tsx
packages/validation/.changeset/pr-12395-added-1750167713273.md
packages/validation/src/profile.schema.ts

Updated email validation in the User Email Panel to match the backend's validation logic.
- Added regex email validation to match backend.
- Added a unit test.
Added a unit test to verify the validation displays the correct error message.
June 24th
- Use devenv and login as vagrant user
<details> …

feat: [UIE-8819] - IAM RBAC: User Email validation

---

packages/manager/.changeset/pr-12413-fixed-1750706040269.md
packages/manager/.changeset/pr-12413-fixed-1750706078072.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeActionMenu.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeRow.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskActionMenu.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskRow.tsx

Fixes some incorrectly styled action menu table rows 
| ![Screenshot 2025-06-23 at 3 02 12 PM](https://github.com/user-attachments/assets/ce3c8f5d-7bc1-4d45-9e5c-544bbfd28781) | ![Screenshot 2025-06-23 at 3 02 32 PM](https://github.com/user-attachments/assets/f4ccf854-57cb-4fb7-91bc-96e792f48d74) |
| Buttons are not the same height & Action menu is not right aligned | Fixed! |
| ![Screenshot 2025-06-23 at 3 04 06 PM](https://github.com/user-attachments/assets/c60c3717-7e3a-4599-a2ca-05127d88b232) | ![Screenshot 2025-06-23 at 3 04 17 PM](https://github.com/user-attachments/assets/7ed864b5-ea3b-418f-920c-5a9fde14d1f7) |
| Recycle button is not right aligned |  Fixed! |
- View a Linode's detail's page
- …

fix: [M3-10236, M3-10235] - Linode Disk Action Menu and LKE Node Action Menu table styles

---

packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts

Fix Cypress LKE update test failure against DevCloud.
- Use `.scrollIntoView()` to scroll down to get the `Add pool` button
```
pnpm cy:run -s "cypress/e2e/core/kubernetes/lke-update.spec.ts"
```

test: [M3-10198] - Fix LKE update test failure against DevCloud

---

packages/manager/.changeset/pr-12403-tests-1750430192369.md
packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts
packages/manager/cypress/support/intercepts/events.ts

Fix Cypress Linode clone test, and make the test more robust.
- Intercept event to get the clone event ID.
- Change a way to verify clone notification instead.
```
pnpm cy:run -s "cypress/e2e/core/linodes/clone-linode.spec.ts"
```

test: [M3-9860] - Fix Cypress Linode clone test

---

packages/api-v4/src/regions/types.ts
packages/utilities/src/factories/regions.ts
packages/utilities/src/helpers/isAclpSupportedRegion.ts

This makes the `monitors` property on the API SDK `Region` type optional while the corresponding API feature remains work-in-progress.
Since the `monitors` property hasn't been released yet, I'm not planning to add a changeset to this PR unless anyone prefers there be one.
- Make `monitors` property optional on `Region` type in the API-v4 SDK
- Make `monitors` `undefined` by default in `regionFactory`
- Add documentation noting that the `monitors` property relates to an upcoming/unstable feature
- Update `isAclpSupportedRegion` util to account for cases when `monitors` is undefined
July 1, 2025
- Confirm unit tests and Cypress tests pass in CI
- Optionally run tests in `utilities` package
- Optionally run CloudPulse Cypress tests
<details>
👀 Doing a …

upcoming: [M3-10247] - Make `monitors` property optional on API SDK `Region` type

---

packages/manager/.changeset/pr-12433-tests-1750885668250.md
packages/manager/cypress/e2e/core/account/host-maintenance-policy.spec.ts
packages/manager/cypress/support/intercepts/maintenance.ts

This adds a few Cypress tests to cover changes made to the Account Settings as part of the Host & VM Maintenance project.
- Add tests to cover Host & VM Maintenance account settings changes in `account/host-maintenance-policy.spec.ts`
- Add `mockGetMaintenancePolicies` mock util 
N/A.
You can run the tests interactively with `pnpm cy:debug`, or you can run the test via the CLI with:
```bash
pnpm cy:run -s "cypress/e2e/core/account/host-maintenance-policy.spec.ts"
```

test: [M3-9634] - Add Cypress tests for Host Maintenance Policy account settings section

---

packages/manager/.changeset/pr-12428-fixed-1750852226481.md
packages/manager/src/features/NodeBalancers/VPCPanel.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionMenu.test.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionMenu.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetNodebalancerRow.tsx

When viewing the Subnets table that lists both Linode and NodeBalancer resources, the "VPC IPv4 Ranges" and "Firewalls" columns become misaligned if there are multiple subnets present. 
- Fixed misalignment in Subnet's NodeBalancer table 
- Fixed console error for the helper text in the Create Nodebalancer's VPC Panel
- Removed backend status icon in Subnet's NodeBalancer table
09/07
| ![image](https://github.com/user-attachments/assets/981646b0-66d3-4d54-a532-407c5a9bcb3e) | ![image](https://github.com/user-attachments/assets/5456909a-3d76-498f-b5ad-5bf0afd322c3) |
| Console Error in the Create Nodebalancer page |
| ------- |
| ![image](https://github.com/user-attachments/assets/7f2ebc42-75f4-478e-92ec-68b55d1b9f85) |
<details>
<summary> Author …

fix: [M3-10176, M3-10177, M3-10244] - Fix columns misalignment in Subnet NodeBalancers Table

---

packages/manager/.changeset/pr-12430-fixed-1750866239525.md
packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeEntityDetailFooter.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx

This PR implements part of the read-only user restrictions for LKE/E clusters:
- **Kubeconfig** is now disabled (greyed out) for read-only users.
- **Kubernetes version upgrade** is now restricted for read-only users.
- Disabled Kubeconfig for read-only users.
- Removed the Kubernetes upgrade option for read-only users.
N/A
| ![Before](https://github.com/user-attachments/assets/9936a4a0-956c-4e3f-af85-262817c3ff41) | ![After](https://github.com/user-attachments/assets/f4e325dc-89f5-4210-a0de-fc6a9984a3b9) |
| ![Before](https://github.com/user-attachments/assets/c3b96710-fdb0-449d-ac9a-b2d9ababab45) | ![After](https://github.com/user-attachments/assets/44c708eb-f24e-4415-aac5-03cff2ee44d5) |
1. Assign a user read-only access via the **User Account …

fix: [M3-10246] - Disabled kubeconfig and upgrade option for read only access user

---

packages/manager/src/OAuth/constants.ts
packages/manager/src/OAuth/oauth.ts
packages/manager/src/constants.ts
packages/manager/src/features/Linodes/LinodeCreate/Tabs/Marketplace/AppSelectionCard.tsx
packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.test.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
packages/manager/src/hooks/usePendo.ts
packages/manager/src/initSentry.ts
packages/manager/src/request.tsx

- Changes from https://github.com/linode/manager/pull/12405 made it so that there was no fallback if `REACT_APP_APP_ROOT` was not defined in the environment. This broke local dev for some people because the expectation is that the default app root should be `http://localhost:3000` if  `REACT_APP_APP_ROOT` is not defined 
- Remove `REACT_APP_APP_ROOT` from your `.env`
- Clear local storage
- Verify you can still authenticate when visiting http://localhost:3000 even if there is no `REACT_APP_APP_ROOT` in your env
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/C …

fix: Missing env defaults due to auth changes

---

packages/manager/src/constants.ts
packages/manager/src/request.tsx

- Hopefully the last fix related to env vars 🤦 
- In https://github.com/linode/manager/pull/12453, I forgot to make Cloud Manager account for the `REACT_APP_API_ROOT` environment variable, which is why dev is broken right now

fix: Cloud Manager not respecting `REACT_APP_API_ROOT`

---

packages/manager/.changeset/pr-12456-fixed-1751400242708.md
packages/manager/src/components/CodeBlock/CodeBlock.styles.ts

- The copy icon on our code blocks have an extra background
- This PR fixes the extra background by removing the extra style
It's harder to tell in light mode
| ![Screenshot 2025-07-01 at 3 47 09 PM](https://github.com/user-attachments/assets/8690dbf8-8906-4284-ba92-5e16c31f39e8) | ![Screenshot 2025-07-01 at 4 00 36 PM](https://github.com/user-attachments/assets/0c196b21-3226-4a6a-88f3-23c0dd3e4683) |
The issue is more obvious in dark mode
| ![Screenshot 2025-07-01 at 3 47 00 PM](https://github.com/user-attachments/assets/d9759f2f-212e-43f3-abd8-28d6d047420c) | ![Screenshot 2025-07-01 at 4 00 49 PM](https://github.com/user-attachments/assets/9943bde7-9736-4c90-8024-58509e3c3b05) |
- Find a code snippet …

fix: [M3-10270] - Extra background on code block copy icon

---

packages/manager/.changeset/pr-12424-changed-1751354758031.md
packages/manager/src/components/AccessPanel/UserSSHKeyPanel.test.tsx
packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.test.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
packages/manager/src/hooks/usePagination.ts
packages/manager/src/utilities/testHelpers.tsx

React router methods replaced with the tanstack router inside the "usePagination" hook.
- Find any table where pagination is used.
- Change page number or page size.
- Observe proper query change in the URL bar.
♿  Providing …

fix: [STORIF-36] - Pagination navigation updated.

---

packages/manager/.changeset/pr-12478-changed-1751654923710.md
packages/manager/.changeset/pr-12478-fixed-1751654923710.md
packages/manager/src/dev-tools/FeatureFlagTool.tsx

Devtools currently supports toggling only 0 and 1-level feature flags. With the recent addition of 2-level nested flags (for eg., `aclpBetaServices.ServiceType.flagName`) under `aclpBetaServices`, the toggling is not working as expected.
This update should fix the current behavior and support setting nested flags at any depth recursively to ensure correct behavior.
- Updated feature flag toggling to support recursive toggling at any depth, instead of being limited to root (0-level) and 1-level flags
N/A
| <video src="https://github.com/user-attachments/assets/506fd088-88f5-490f-9d61-a0ba8339458f" /> | <video src="https://github.com/user-attachments/assets/d51dfb95-aeb4-47b0-b5cd-f68e644be74d" /> |
- The Alerts section under Additional Options in …

fix: [M3-10289] - Enhance Devtools to support `aclpBetaServices` nested Feature flags

---

packages/manager/.changeset/pr-12481-fixed-1751919420399.md
packages/manager/src/components/RegionSelect/RegionSelect.tsx
packages/ui/.changeset/pr-12481-changed-1751919486678.md
packages/ui/src/components/ListItemOption/ListItemOption.tsx

- Fixes the region select missing the selected icon
| ![Screenshot 2025-07-07 at 3 29 50 PM](https://github.com/user-attachments/assets/dfba82bd-0c3f-4e7e-a3f2-a0859f4ba28d) | ![Screenshot 2025-07-07 at 3 29 30 PM](https://github.com/user-attachments/assets/b7d6676a-1d8d-445b-a88e-4a9bb2c93eb1) |
- Verify the selected icon shows in the region select
<details>
🔐 Removing all sensitive information from the …

fix: [M3-10291] - Region select missing selected icon

---

docs/CONTRIBUTING.md
docs/PULL_REQUEST_TEMPLATE.md
packages/manager/.changeset/pr-12480-tech-stories-1751902475339.md

This PR updates our PR template and contribution guidelines to make it more explicit that it is the responsibility of contributors to ensure that CI checks are passing before their PRs can be merged.
- Update `CONTRIBUTING.md` to mention passing CI checks as a requirement for review and approval
- Update `PULL_REQUEST_TEMPLATE.md` to broaden the requirement regarding tests
No specific release in mind, but the sooner this is in `develop` the better.
N/A. Please review for typos, etc., and please let me know if you have any suggestions to improve the language (cc @mjac0bs).
<details>
➕ Adding a …

misc: Update contributor documentation to mention tests and CI checks

---

packages/manager/.changeset/pr-12470-tests-1751556866866.md
packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts

Fix Community StackScripts Cypress test flask.
- Add `200ms` timer to let the page fully loaded.
```
pnpm cy:run -s "cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts"
```

test: [M3-9855] - Fix Community StackScripts Cypress test flake

---

packages/manager/.changeset/pr-12499-tests-1752165592860.md
packages/manager/cypress/e2e/core/account/account-maintenance.spec.ts

Quick fix to Cypress test failures due to new `Host & VM Maintenance` feature flag.
- Mock feature flag `vmHostMaintenance` to be disabled.
```
pnpm cy:run -s "cypress/e2e/core/account/account-maintenance.spec.ts"
```

test: [M3-10311] - Fix Cypress test failures following feature flag flip

---

packages/validation/src/cloudpulse.schema.ts

I think I got something wrong when resolving conflicts when merging `develop` ⬅️  `master` into  after our last release.
The CloudPulse Alerting team requested we fix this in our release.

fix: CloudPulse alerting validation schemas due to incorrect conflict resolution

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/routes/account/index.ts

- Update billing flow to use payment method id for editing payment
- Reduces parameter surface area in navigation.
7/21
| 📷 | <img width="463" height="33" alt="Screenshot 2025-07-21 at 12 10 57 PM" src="https://github.com/user-attachments/assets/f775eba4-dfcc-43e3-aec3-02bee6937672" /> |
<details>
🚩 Using a feature flag to protect the …

fix: resort to payment id for edit billing flow

---

packages/manager/.changeset/pr-12552-upcoming-features-1753194650146.md
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.test.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummaryItem.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/NodePoolConfigDrawer.tsx
packages/manager/src/features/Kubernetes/NodePoolUpdateStrategySelect.tsx
packages/manager/src/features/Kubernetes/constants.ts

This PR builds off of #12449 by providing a way for the user to edit their node pool's configuration via the cluster summary/checkout bar. 
- This work is feature-flagged as `postLa` under the LKE-Enterprise flag.
- Adds `poolIndex` and `selectedRegion` props to the NodePoolConfigDrawer
- Adds ability to update the node pool config with drawer edit mode
- Adds the pricing in the drawer
- Adds a warning for low node count in the drawer
- Updates the NodePoolSummaryItem (in the checkout bar)
- Adds link button to the NodePoolConfigDrawer
- Removes the number input from the Node
- Updates a unit test impacted by the addition of the `poolIndex` prop
8/12 (dev)
| Flag State | Before  | After   |
| ------- | ----------- |  -- |
| Node Pool Config Drawer - Edit mode |  N/A |  Standard cluster (+ …

upcoming: [M3-10295] - Edit node pool configuration in LKE cluster create flow

---

packages/manager/.changeset/pr-12565-fixed-1753299138477.md
packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
packages/manager/src/routes/account/index.ts

- Fixes a UI alignment issue in the Invoice details page header (bug in production)
- Fixes a routing regressions with the Invoice details page
- I think it may have been introduced in https://github.com/linode/manager/pull/12532  (not in production yet)
| `develop`  | This PR   |
| ![Screenshot 2025-07-23 at 1 07 34 PM](https://github.com/user-attachments/assets/d3835d23-5a2c-4cdf-b20a-2073aec9829a) | ![Screenshot 2025-07-23 at 1 06 14 PM](https://github.com/user-attachments/assets/8c35d916-9498-4c9b-9999-c5886279b44e)  |
| The invoice details page is incorrectly rendered under the tabs and the header alignment is messed up | The invoice details is back to being a dedicated page and the header looks good 🎉  | 
- Have an account with an invoice on it
- Use dev or the …

fix: [M3-10376] - Invoice details page UI issue and routing regression

---

packages/manager/.changeset/pr-12556-upcoming-features-1753265232709.md
packages/manager/src/features/IAM/Shared/utilities.test.ts
packages/manager/src/features/IAM/Shared/utilities.ts

IAM RBAC: fix error message for the one account_admin in the account
- fix error message for the one account_admin in the account
8/12
| <img width="2746" height="1448" alt="image" src="https://github.com/user-attachments/assets/7546dedd-1ddb-402b-8776-fac5ab4c47ce" /> | <img width="2836" height="1492" alt="image" src="https://github.com/user-attachments/assets/da06bbff-32ee-438e-80eb-8ed48dd10afe" /> |
| <img width="968" height="1276" alt="image" src="https://github.com/user-attachments/assets/5eb6a467-696f-42ef-9446-dc6f721183ed" /> | <img width="966" height="1178" alt="image" src="https://github.com/user-attachments/assets/454690db-e711-495b-9428-c54d12edb913" /> |
- …

feat: [UIE-8881] - IAM RBAC: fix the error message

---

packages/manager/.changeset/pr-12576-tests-1753390501259.md
packages/manager/src/features/Linodes/LinodeCreate/Security.test.tsx

Experimenting to see if increasing the `waitFor` timeout resolves the flake in the `Security.test.tsx` spec. If CI passes, I'll kick it off a few more times to confirm it's passing reliably. If not, I'll try increasing the timeout and/or applying the timeout to the entire test.
- Increase `waitFor` timeout from 1s to 5s
N/A.
It seems like this test is passing locally for most users. Intel Mac users may be able to observe the failure by running the following against `develop`:
```
pnpm test Linodes/LinodeCreate
```
It seems like this test fails most often in CI, so I've run the tests against the PR 5 times and it's passed each time.
➕ …

test: [M3-8559] - Increase `Security.test.tsx` `waitFor` timeout from 1s to 5s

---

packages/manager/.changeset/pr-12579-fixed-1753443210506.md
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Fixes hover styling for **disabled zebra-striped table rows**.
- Updated hover style for disabled rows.
- Ensured consistency across Light and Dark themes.
| Theme       | Before | After  |
|-------------|--------|--------|
| **Dark**    | ![Before - Dark](https://github.com/user-attachments/assets/f1e576fa-8ed0-4493-9f38-94f8c3548722) | ![After - Dark](https://github.com/user-attachments/assets/cbce547c-e02e-4324-9b21-3019bf707197) |
| **Light**   | ![Before - Light](https://github.com/user-attachments/assets/be84eb18-3b64-4f6a-9995-c719f1611440) | ![After - Light](https://github.com/user-attachments/assets/18fd8465-8c45-4d4a-ad9d-e0e61e9063b1) |
1. Go to `/linodes/create`.
2. Select a region and choose a **GPU** plan.
3. Verify hover styling on disabled zebra-striped rows.
<details> …

fix: [M3-10316] - Disabled state styling for zebra stripped table rows

---

packages/manager/.changeset/pr-12578-fixed-1753437741673.md
packages/manager/.changeset/pr-12578-upcoming-features-1753437780675.md
packages/manager/src/features/Linodes/AclpPreferenceToggle.tsx
packages/manager/src/features/Longview/shared/InstallationInstructions.styles.ts
packages/shared/src/hooks/useIsLinodeAclpSubscribed.ts

This PR Add/updates inline docs for ACLP Alerts logic and fixes some dividers (In Longview) that are not aligned nicely.
- Add documentation to the `AclpPreferenceToggle` component to explain its purpose and behavior. The component currently lacks context, making it hard to understand
- Remove the 4th case comment from the `useIsLinodeAclpSubscribed` hook, as this case is not expected to occur (or may never occur)
- Fix Longview UI alignment issue
N/A
- No visual changes related to ACLP alerts
-  | Before  | After   |
| ![Screenshot 2025-07-25 at 3 22 01 PM](https://github.com/user-attachments/assets/01758a03-84b8-47ed-abdb-97ca490d18d0) | ![Screenshot 2025-07-25 at 3 21 30 PM](https://github.com/user-attachments/assets/35aae215-1bec-4ffa-bac4-076816131c69) |
- …

change: [M3-10348, M3-10013] - Add/update inline docs for ACLP Alerts logic and fix Longview UI alignment issue

---

packages/manager/.changeset/pr-12560-upcoming-features-1753279716756.md
packages/manager/src/features/Firewalls/FirewallLanding/CustomFirewallFields.tsx
packages/manager/src/features/IAM/hooks/usePermissions.ts
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.test.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx

Modified the query parameter to allow varying use cases. Return any errors from the API along with isLoading, isError values.
- Modified the query parameter to allow varying use cases
- Return any errors from the API along with isLoading, isError values.
8/12
Restricted non-beta (Grants)
Restricted beta (Permissions)
Unrestricted non-beta (Grants)
Unrestricted beta (Permissions)
- devcloud IAM account unrestricted user
- devcloud IAM account restricted user
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTIN …

feat: [UIE-8999] - IAM RBAC Adjust the parameters to useQueryWithPermissions and return errors

---

packages/manager/.changeset/pr-12605-fixed-1753890447726.md
packages/manager/src/features/Linodes/LinodeMaintenanceText.tsx

This PR improves the user experience by converting the maintenance window date/time display in the `LinodeMaintenanceText` component from a database format to a more readable format. Instead of showing dates like "2024-01-15T14:30", the component now displays "2024-01-15 14:30"
- Slightly better formatting instead of `T` being in string
N/A
> [!note]
Focus on the format, not the times in the screenshots
| <img width="1295" height="371" alt="Screenshot 2025-07-30 at 9 06 13 AM" src="https://github.com/user-attachments/assets/3c57af4c-f3c7-44c2-9a68-1e91d2c1d6dc" /> | <img width="221" height="143" alt="Screenshot 2025-07-30 at 11 33 08 AM" src="https://github.com/user-attachments/assets/6661570c-be2b-4f4a-af74-1b800b7b934f" /> |
- You can manually …

fix: [M3-10394] - Use human readable date/time for maintenance window

---

packages/manager/.changeset/pr-12601-changed-1753862177012.md
packages/manager/src/features/components/PlansPanel/utils.ts

The existing Premium tab description only fits legacy Premium plans. This update adds generic copy that works for both legacy Premium and MTC HT plans.
- Replaced the existing Premium tab description with generic description copy that works for both legacy Premium and MTC HT plans
N/A
| ![Screenshot 2025-07-30 at 1 20 22 PM](https://github.com/user-attachments/assets/3246155d-4461-4d91-bd35-8cec012d4d1f) | ![Screenshot 2025-07-30 at 1 19 08 PM](https://github.com/user-attachments/assets/aa60811d-18f8-4946-98ad-8393920b4be5) |
- Navigate to Linode -> Create  OR LKE -> Create
- In the Premium tab, verify that the description displays the new generic description copy applicable to both legacy Premium and MTC HT plans
<details>
<summary> Author …

change: [M3-9911] - Add generic description to Premium tab to support both legacy Premium and MTC plans

---

packages/manager/src/components/RegionSelect/RegionSelect.tsx

- I removed the `autoHighlight` in https://github.com/linode/manager/pull/12583 and I believe it broke a ton of cypress tests (thanks for catching @jdamore-linode )
- Verify Cypress tests pass ✅

fix: Region Select change that is causing test failures 

---

packages/ui/.changeset/pr-12603-fixed-1753955503044.md
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

This PR fixes checkbox styling issues:
- Changing the check icon color from black to white.
- Applying correct color tokens for all checkbox states.
- Updated check icon color for dark mode.
- Applied proper color tokens to all checkbox variants.
N/A
| ![Before](https://github.com/user-attachments/assets/6a79336c-ab4a-42ad-b672-9f8c76f2dbf7) | ![After](https://github.com/user-attachments/assets/bf4085ef-ba42-4bbd-a989-536d111f0e20) |
1. Enable dark mode.
2. Locate checkboxes across the UI.
3. Confirm white check icon in the disabled state.
- Correct Check icon color in dark mode.
- All variants use proper color tokens.
<details>
<summary>Author Checklists</summary>
</details>

fix: [M3-10336] - Checkbox color token - pt2

---

packages/manager/.changeset/pr-12564-tests-1753288873223.md
packages/manager/cypress/e2e/core/notificationsAndEvents/qemu-reboot-upgrade-notice.spec.ts

Add new Cypress tests for QEMU Upgrade Notice
- Add test suite `QEMU reboot upgrade notification`.
- Verify the reboot banner and notifications.
- Verify the QEMU reboot upgrade notice is displayed in the `Linode` landing page, `Linode Details` page, and `Account Maintenance` page.
```
pnpm cy:run -s "cypress/e2e/core/notificationsAndEvents/qemu-reboot-upgrade-notice.spec.ts"
```

test: [M3-10051] - Add Cypress tests for QEMU Upgrade Notice

---

packages/validation/.changeset/pr-12628-fixed-1754307870531.md
packages/validation/src/cloudpulse.schema.ts

Bugfix for missing schema validation
- Add 'in' to the list of operator values in `cloupulse.schema.ts`
- [] All customers
ASAP
| <img  src="https://github.com/user-attachments/assets/57e3923c-5a66-4716-a021-0510c70a866b" /> | <img src="https://github.com/user-attachments/assets/6bc9a277-893c-4a29-b9e7-2740662f1de1" />|
- Go to Monitor, then Alerts. Click on Create Alert button once it is enabled. 
<details>
🤏 Splitting …

fix: [DI-26114] - Adding in operator check to create-alert schema

---

packages/manager/.changeset/pr-12636-fixed-1754395419312.md
packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.test.tsx
packages/manager/src/features/CloudPulse/Alerts/EditAlert/EditAlertLanding.tsx

Replaced `isFetching` check with `isLoading` check in EditAlertLanding 
1. Updated EditAlertLanding to use isFetching instead of isLoading state
12th August
**Include a screenshot `<img src="" />` or video `<video src="" />` of the change.**
:bulb: For changes requiring multiple steps to validate, prefer a video for clarity.
| <video src="https://github.com/user-attachments/assets/46888404-6281-4d4d-9c8c-f8aca91c7863" /> | <video src="https://github.com/user-attachments/assets/7d245c99-c287-48e7-bec9-1cc0dcc7fdb8"/> |
1. Go to alerts tab …

fix: [DI-26621] - Replaced isFetching check with isLoading check

---

packages/validation/.changeset/pr-12635-fixed-1754392274805.md
packages/validation/src/linodes.schema.ts

A quick follow-up to https://github.com/linode/manager/pull/12626 and fixes the non-human-readable validation messages for Linode Alert numeric input.
- Added human-readable typeerror validation messages to the Linode Alerts object schema.
12 August 2025
| ![Screenshot 2025-08-05 at 3 22 15 PM](https://github.com/user-attachments/assets/c9865a0b-10e0-4d16-8400-d0438a1019e7) | ![Screenshot 2025-08-05 at 4 33 15 PM](https://github.com/user-attachments/assets/99ef85c6-4e3d-4023-8d2b-f611ce93a932) |
- Verify that validation messages for Linode Alert numeric input fields are now human-readable when fields are empty or invalid.
<details>
👀 Doing a …

fix: [M3-10439] - Non-Human-Readable Validation Messages for Linode Alert Numeric Input

---

packages/manager/.changeset/pr-12634-added-1754346674408.md
packages/manager/.changeset/pr-12634-fixed-1754346423085.md
packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseNodeSelector.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx
packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx
packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
packages/manager/src/features/components/PlansPanel/PlansPanel.tsx

This pull request applies a a fix for the premium plans feature in DBaaS, fixing the node options that are available and applies the plan disabling by region functionality present in Create. It also includes some additional handling for an edge case.
- Fixes the node selector options for the premium plans tab so that all 3 node options are available (1, 2, 3 nodes)
- Enables the plan disabling behavior by region in resize for new database clusters.
- Handles edge case where the current plan could appear as disabled, preventing users from making changes to an unavailable plan (ie. node selection) and provides a warning notice (See screenshots below)
- PlansPanel `additionalBanners` property added to handle rendering additional notification …

fix: [UIE-9003] - DBaaS - node selector options for premium and provide plan disabling behavior in resize

---

packages/manager/.changeset/pr-12641-changed-1754424739002.md
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx

This PR adds the new IAM permissions feature to the Firewall details / Node Balancers UI.  The only needed update was to the Add drawer.
- The Add NodeBalancer to Firewall drawer now abides by the IAM permissions - users without the proper permissions should not be able to add Node Balancers to a firewall.
Aug 13
| 📷 | ![Screenshot 2025-08-05 at 4 04 39 PM](https://github.com/user-attachments/assets/c2078dd7-2f1e-4aac-b37a-56c884e1eabd) |
- In an IAM account, have users with both `create_firewall_device` values
<details> …

feat: [UIE-8872] - IAM RBAC - Firewalls / Nodebalancers permissions

---

packages/manager/.changeset/pr-12647-fixed-1754492562580.md
packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx

Fixed incorrect unit display for per second units in metric widget
1. Added logic in CloudPulseWidget.tsx to not show /s if unit is bps but there is no scaled unit
12th August
**Include a screenshot `<img src="" />` or video `<video src="" />` of the change.**
:bulb: For changes requiring multiple steps to validate, prefer a video for clarity.
|![Screenshot 2025-08-06 at 6 35 31 PM](https://github.com/user-attachments/assets/bfb1a49f-a792-42a5-ab2d-ce472e301866)|![Screenshot 2025-08-06 at 6 37 …

fix: [DI-26688] - Fixed incorrect unit display in metric widget

---

packages/manager/.changeset/pr-12651-tests-1754580443465.md
packages/manager/cypress/e2e/core/longview/longview.spec.ts

Remove clean up from longview tests.
- Remove `cleanUp()` function within the `before` block.
```
pnpm cy:run -s "cypress/e2e/core/longview/longview.spec.ts"
```

M3-10409 Remove clean up from longview.spec.ts

---

packages/manager/.changeset/pr-12657-fixed-1754583180570.md
packages/manager/src/components/Flag.tsx

Super short and simple, adds `shouldForwardProp` to styled component
next release
This error should no longer be seen in the console:
- With your console open, navigate to any page with a Region select (eg VPC Create) and open the region select
- notice console error
- Confirm console error gone
<details>
🚩 Using a …

fix: [M3-10446] - Fix console error from `hasBorder` prop in styled component

---

packages/manager/.changeset/pr-12654-changed-1754641803662.md
packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.test.tsx
packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

This PR implements (and fix existing) payments methods IAM permissions.
- More granular permissions for components related to payment methods CRUD actions
- Adapt tests
August 26
- MSW or iam (restricted) + regular account to compare
- toggle `set_default_payment_method`, `delete_payment_method` and `create_payment_method` permissions with either IAM permissions or MSW and ensure UI disabled corresponding actions
<details> …

change: [UIE-8835] - Permissions for billing payment methods

---

packages/manager/src/components/PrimaryNav/utils.ts

After merging [the new "Administration" navigation section](https://github.com/linode/manager/pull/12633), I noticed that the activeLink matching was not working well in this case.
This PR improves the pattern to match segmentation to account for those cases
We do not need a changeset since this is not affecting prod yet
- Improve `linkIsActive` util
8/26
| ![Screenshot 2025-08-12 at 11 12 53](https://github.com/user-attachments/assets/fe1d1cc4-ec82-45cf-83cd-cebce72102a1) | ![Screenshot 2025-08-12 at 11 12 35](https://github.com/user-attachments/assets/b32a4d25-db8e-4100-8814-6431c193563b) |
- Pull current code and ensure the new "Administration" main nav category's active links …

fix: [M3-10467] - Improve Primary Nav Active Link Matching

---

.github/workflows/e2e_schedule_and_push.yml
packages/manager/.changeset/pr-12664-tech-stories-1754933120939.md

This PR fixes the [Excessive Secrets Exposure](https://github.com/linode/manager/security/code-scanning/188) vulnerability in our E2E GitHub Actions workflow to stop using dynamic secret lookups and instead use `env` variables scoped to each matrix job.
- Replaced dynamic secret access (`secrets[matrix.user.name]`) with env-based access (`env[matrix.user.name]`) for `MANAGER_OAUTH` in `.github/workflows/e2e_schedule_and_push.yml`
Full verification will need to be done after merging. In the meantime, I was able to partially verify in my forked repo by adding a copy of the `.github/workflows/e2e_schedule_and_push.yml` file with my change as this [debug Action](https://github.com/bill-akamai/manager/actions/workflows/debug-M3-987 …

refactor:[M3-9877][SECURITY] - Fix excessive secrets exposure warning in e2e GHA workflow

---

packages/manager/.changeset/pr-12691-tests-1755096527481.md
packages/manager/cypress/e2e/core/notificationsAndEvents/qemu-reboot-upgrade-notice.spec.ts

- Fixes the `qemu-reboot-upgrade-notice.spec.ts` test failure caused by https://github.com/linode/manager/pull/12665 
- The test is incorrectly checking for the text: `This Linode’s maintenance window opens at at 2025-08-13 10:44. For more information, see your open support tickets.` The text only contains one `at`...
- Verify `qemu-reboot-upgrade-notice.spec.ts`  passes locally or in CI
<details> …

test: [M3-10474] - Fix `qemu-reboot-upgrade-notice.spec.ts` test failure

---

packages/manager/.changeset/pr-12668-fixed-1754917016678.md
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu/LinodeActionMenu.tsx

Disable Linode label editing for users without the ``update_linode`` permission.
Check for both ``clone_linode`` and ``create_linode`` permissions before enabling the “Clone Linode” button.
- Disable Linode label editing for users without the ``update_linode`` permission.
- Check for both ``clone_linode`` and ``create_linode`` permissions before enabling the “Clone Linode” button.
August 26th
- devcloud IAM account or local devenv setup or mock data (use the User Permissions presets)
- _Note: The unrestricted account has full access — permission checks are skipped._
To test permissions using presets:
Enable MSW and use Legacy MSW Handlers.
- Use the …

fix: [UIE-9071, UIE-9072] - IAM RBAC: clone linode permission fix, edit linode label permission fix

---

packages/manager/.changeset/pr-12659-fixed-1754657214437.md
packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx

This PR updates the expand/collapse behavior in the IAM RBAC Roles table to prevent accidental row expansion when interacting with the selection checkbox.
- Fixed expand/collapse behavior in the IAM RBAC Roles table to prevent accidental row expansion when interacting with the selection checkbox.
August 26th
- devcloud IAM account or local devenv setup or mock data
<details>
➕ Adding a …

fix: [UIE-8142] - IAM RBAC: fix roles table expand

---

packages/manager/.changeset/pr-12724-fixed-1755617276166.md
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/RenderAlertsMetricsAndDimensions.tsx
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/utils.test.ts
packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/utils.ts

Update the capitalization logic in Show-details to handle the comma separated string values. 
- Added a util `handleDimensionValue1 to split comma separated values and transform before joining 
- Unit tests for the util
26th August
**Include a screenshot `<img src="" />` or video `<video src="" />` of the change.**
:bulb: For changes requiring multiple steps to validate, prefer a video for clarity.
| <img width="1164" height="1348" alt="image" src="https://github.com/user-attachments/assets/66f1fa94-4b1a-4ff1-8cdc-9e54985af4d1" /> |  <img width="1176" height="1392" alt="image" …

fix: [DI-26674] - Update the capitalization logic in Show-Details 

---

packages/manager/.changeset/pr-12729-fixed-1755635540451.md
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLandingTable.tsx

This pull request fixes in issue in the DBaaS Landing page where the error state is displayed shortly after "Plan" column is sorted.
- Sort Cell for "Plan" column has been updated to provide `type` which changes what we provide to `orderBy` for X-Filter in the database instances request and should work with both variations of the call (new and legacy)
- The text displayed for this column header will continue to be "Plan". This is only an update to what what we provide to the backend call for the database list.
8/26/2025
| ![legacy-databases-call-fails-after-plan-sort](https://github.com/user-attachments/assets/f8673e76-7e09-4591-ad1b-29320 …

fix: [UIE-9111] - DBaaS - Database landing page shows error state after plans column is sorted.

---

packages/manager/cypress/e2e/core/linodes/maintenance-policy-region-support.spec.ts
packages/manager/cypress/support/intercepts/linodes.ts

This is a quick change to one of the tests in `maintenance-policy-region-support.spec.ts` to use a mocked region where the maintenance policy capability is absent. This allows the test to pass in CI (where Gecko regions aren't available) yet should remain stable as Maintenance Policy capabilities continue to roll out to regular regions.
I'm not planning to add a changeset to this as long as we're targeting the 8/26 release, but will add one if it misses it.
- Create a Linode in `us-ord` instead of `us-den-1` when testing maintenance policy negative state
8/26/2025 if possible, not the end of the world if it doesn't make it (we have a solid understanding of the test failure and can disregard it during release testing if …

test: [M3-10501, M3-10477] - Use a mock region without maintenance policy capability when testing drop-down disabled state

---

packages/manager/CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx

Not sure if this was a result of the rerouting, but the link was missing a leading slash, resulting in appending an extra "linodes" in the URL.
I also noticed the browser `history -1` behavior wasn't working properly so i added a replace as well for good measure
- Fix broken entity link in Linodes list (card view)
- Fix `history -1` behavior
8/28/2025
- Navigate to /linodes
- Toggle to card view
- Click on any of the linodes title to access its details
- 🚫 notice wrong url and page not found
- Navigate to /linodes
- Toggle to card view
- Click on any of the linodes title to access its details
- ✅ confirm proper URL and getting to the linode details
- Click on the browser back button
- ✅ confirm back to the linode list …

hotfix: [M3-10558] - broken entity link on Linodes list card view

---

packages/manager/.changeset/pr-12779-added-1756330614474.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeEntityDetailFooter.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolFooter.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolFooter.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx

For LKE-E clusters, users should be able to see and easily link to the firewall associated with their node pool(s).
We now show this at the bottom of the Node Pool paper.
- Adds a linked firewall to the Node Pool Footer
- Adds test coverage
- Provides consistency across styling, specifically:
- Adds colons after each label in the footer to match the summary (e.g. `Cluster ID:`)
- Adds a copy tooltip to the Cluster ID, since it is the only ID that doesn't have copyable text
9/9
| Firewall changes | Consistent UX |
|--------| ----- |
| <video src="https://github.com/user-attachments/assets/738ab0c0-2cf0-4c2d-a3b1-77827240e544"/> |  <video src="https://github.com/user-attachments/assets/bd08437a-1b7e-4781-af2e-2e5de6d26e06"/> | …

feat: [M3-10378] - Show Node Pool firewalls in Node Pool footers

---

packages/manager/.changeset/pr-12794-tests-1756839262706.md
packages/manager/cypress/e2e/core/linodes/linode-storage.spec.ts

Today's API release triggered a test failure in `linode-storage.spec.ts` because the "Deleting (XX%)" status text no longer appears in the disk list due to the changes made by ARB-6663. Interestingly, the text does still appear when attempting to delete a disk that has encryption enabled.
- Fix failing test by removing assertion that no longer passes following API release
N/A.
We can rely on CI to confirm that the test is passing. Alternatively, you can run:
```bash
pnpm cy:run -s "cypress/e2e/core/linodes/linode-storage.spec.ts"
```
<details>
🤏 Splitting feature …

test: [M3-10568] - Fix failing `linode-storage.spec.ts` delete test following API release

---

packages/manager/.changeset/pr-12795-fixed-1756842256177.md
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/queries/src/profile/preferences.ts

Although it seems not to have been noticed so far, preferences are broken from a session to another.
Bad bug: 🐛 - The `useMutatePreferences` assumes data is available when the `PrimaryNav` component (kinda top of the tree) makes its preference mutation for the opened/collapsed sections of the menu. Somehow, along the many refactors to the component, routing and the rendering tree, this broke **any** preference persistence other than the primary nav ones from one session to the next.
- Prevent `PrimaryNav` from overriding older set preferences settings
- Fix "more" section not being set in preferences
⚠️ **09/09/2025**
nothin' visual here, except your theme choice now will actually persist (among other profile prefs)
- login …

fix: [M3-10570] - Profile preferences across sessions

---

packages/api-v4/.changeset/pr-12793-changed-1756835875675.md
packages/api-v4/src/kubernetes/nodePools.ts
packages/api-v4/src/kubernetes/types.ts
packages/manager/.changeset/pr-12793-upcoming-features-1756835231450.md
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelectionTable.tsx
packages/manager/src/features/Kubernetes/KubernetesPlansPanel/NodePoolConfigOptions.tsx
packages/validation/.changeset/pr-12793-added-1756835813761.md
packages/validation/.changeset/pr-12793-removed-1756835773560.md
packages/validation/src/kubernetes.schema.ts

- This PR allows users to configure a Node Pool's Firewall in the "Add Node Pool Drawer" for  LKE Enterprise Clusters only
- Also updates some validation schemas that are very out of date
Hoping for this to be included in the **September 9th release** 🤞  (release branch cut on September 3rd)
> [!note]
> Have a standard LKE cluster and an Enterprise cluster on your account for testing. If you need customer tags for enterprise, let me know.
- Ensure the correct LKE-E feature flags are on locally (LKE Enterprise: `enabled`, `la`, `postLa`)
- Verify you can set a Node Pool's firewall in the "Add Node Pool Drawer" 
- Verify other flows still work and are unaffected by this change
- Verify this drawer still works for standard LKE …

upcoming: [M3-10379] - Allow Firewall to be configured in the Add Node Pool Drawer

---

packages/manager/.changeset/pr-12790-added-1756817237984.md
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx

This PR implements IAM RBAC permissions for NodeBalancer summary tab
- Implement permissions in the /nodebalancers/${nodebalancersId}/summary flow (Edit label + Add tags)
- Update unit tests
9/9
- MSW or iam (restricted) + regular account to compare
- Permissions to check:
Custom User Entity Permissions preset:
```
[
"update_nodebalancer"
]
```
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRI …

feat: [UIE-9142] - IAM RBAC: perm check nodebalancer summary tab

---

packages/manager/.changeset/pr-12774-added-1756288318362.md
packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
packages/manager/cypress/e2e/core/account/account-linode-managed.spec.ts
packages/manager/src/features/Account/GlobalSettings.tsx

Add a notification banner if user doesn't have a permission to view this page
- Show Account Settings if user has view_account_settings permission.
9/9
| <img width="3292" height="1288" alt="image" src="https://github.com/user-attachments/assets/853237dc-56cb-4492-a0f6-7824e2e4a014" /> | <img width="3320" height="1404" alt="image" src="https://github.com/user-attachments/assets/27344ca8-79cd-4a6f-8729-91c56052a814" /> |
- devcloud IAM account or local devenv setup or mock data (use the User Permissions presets)
- Permission to check: `view_account_settings`
<details>
<summary> Author …

feat: [UIE-9150] - IAM RBAC: add a notification banner for Account Settings if user doesn't have permission

---

packages/api-v4/.changeset/pr-12800-changed-1756894123495.md
packages/api-v4/src/volumes/volumes.ts
packages/manager/.changeset/pr-12800-added-1756893991385.md
packages/manager/src/features/Volumes/Drawers/EditVolumeDrawer.tsx
packages/manager/src/features/Volumes/Drawers/ManageTagsDrawer.tsx
packages/manager/src/features/Volumes/VolumeDetails/VolumeEntityDetails/VolumeEntityDetail.tsx
packages/manager/src/features/Volumes/VolumeDetails/VolumeEntityDetails/VolumeEntityDetailFooter.tsx
packages/queries/src/volumes/volumes.ts

Volume tag editing feature added to the volume details page.
Added ability to add and remove tags from the volume details page.
- Run cloud manager locally.
- Enable VolumeSummaryPage feature flag.
- Open `/volumes/$volumeId` page.
- Open developer tools -> Network tab.
- Add/Remove tag.
- Observe the PUT request.
<details>
👣 Providing …

new: [STORIF-82] Volume tag editing feature added to the volume details page.

---

packages/manager/.changeset/pr-12813-fixed-1757003337258.md
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.test.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx

- Update tooltip for user who doesn't have permissions
- Disable token textfield when user lacks permissions
todo: add tests
**Include a screenshot `<img src="" />` or video `<video src="" />` of the change.**
:bulb: For changes requiring multiple steps to validate, prefer a video for clarity.
| <img width="3246" height="826" alt="image" src="https://github.com/user-attachments/assets/7a34b461-a912-4df9-a3db-2a98828199d9" /> | <img width="968" height="149" alt="image" src="https://github.com/user-attachments/assets/e9f929b8-b8c0-4609-816f-e10efab8e5aa" /> |
- Use an account with a …

fix: [M3-10533] - Fix misleading "Receive a transfer" tooltip when user lacks permissions

---

packages/manager/.changeset/pr-12820-added-1757082532771.md
packages/manager/src/features/Volumes/VolumeDetails/VolumeDetails.tsx
packages/manager/src/features/Volumes/VolumeDetails/VolumeDetailsHeader.tsx

Added ability to edit volume label.
- Created VolumeDetailsHeader component.
- Added label editing logic.
- Run cloud manager locally.
- Enable VolumeSummaryPage feature flag.
- Open /volumes/$volumeId page.
- Open developer tools -> Network tab.
- Press "Pencil" icon on the breadcrumb and edit label. 
- Observe the PUT request.
<details>
🚩 Using a feature flag to protect the …

new: [STORIF-81] Added ability to edit volume label.

---

packages/manager/CHANGELOG.md
packages/manager/src/routes/accountSettings/index.ts
packages/manager/src/routes/index.tsx

This PR redirects /settings route to /account-settings. 
9/9
https://github.com/user-attachments/assets/7ed45cd4-882f-45c3-96bf-443b7fbde773
<details>
🕛 Scheduling …

fix: [M3-10606] - Redirects /settings to /account-settings

---

packages/manager/.changeset/pr-12814-removed-1757010425024.md
packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummaryItem.tsx

Currently, with Post LA changes, the kube checkout bar was updated to show the node pool's update strategy for each pool (for LKE-E clusters, where this selection is available).
After UX feedback, we've decided to keep the information in the checkout bar simple to avoid overwhelming the user with too many details and focus on pricing. Update strategy and firewall will not be listed. 
Firewall was not added to begin with, I just forgot to remove update strategy earlier - since this is only a display change  and has no functional impact, I don't think it's priority to squeeze this into the already cut 9/9 release, even if we flip the post LA flag before 9/23.
- Remove the displayed update strategy from the UI and clean up related RHF logic no longer needed
Upon production release, changes …

change: [M3-10586] - Remove update strategy from node pool summary item in LKE checkout bar

---

packages/manager/.changeset/pr-12875-tests-1757702639982.md
packages/manager/cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts

Fix Cypress test flake in events-fetching.spec.ts
- Change code to ignore the delay within 1 second.
```
pnpm cy:run -s "cypress/e2e/core/notificationsAndEvents/events-fetching.spec.ts"
```

M3-10512 Cypress test flake in events-fetching

---

packages/manager/.changeset/pr-12879-upcoming-features-1757953229656.md
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterField.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterValue/ValueFieldRenderer.tsx
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterValue/useFetchOptions.ts
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterValue/utils.test.ts
packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/DimensionFilterValue/utils.ts
packages/manager/src/mocks/serverHandlers.ts

Support for fetching linode, linode region options for account scope in Alerting.
- Passing scope as a parameter from the DimensionFilterField component to ValueFieldRenderer, useFetchOptions
- Handling region and account scope for firewall filtering in useFetchOptions
September 23rd.
https://github.com/user-attachments/assets/f3ac314a-c1ed-4167-9b4f-2feaeeb41755
In Mock environment , please choose Legacy MSW Handlers for Base Preset
Under Monitor, click on Alerts
For Create : Click on Create Alert button, choose the Firewall service. Please select Account scope . And for Linode, Linode Region dimension filter there should be some values present which should be the same if you select Entity …

upcoming: [DI-26794] - Scope support for Cloud Firewall dimension filters

---

packages/manager/.changeset/pr-12871-added-1757674703754.md
packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeFirewalls/AddFirewallForm.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsActionMenu.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsRow.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerFirewallsRow.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.test.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx

This PR implements IAM RBAC permissions for NodeBalancer settings tab
- Implement permissions in the /nodebalancers/${nodebalancersId}/settings flow
- Update unit tests
- Filter the available firewalls in the /linodes/${linodeID}/networking Add Firewall flow
09/23
| <img width="3088" height="1778" alt="image" src="https://github.com/user-attachments/assets/f8a0f145-2009-4473-9ae2-c2a8c77768eb" /> | <img width="2818" height="1198" alt="image" src="https://github.com/user-attachments/assets/4b8c0fa8-c8f6-47e1-821d-88c5e605031c" /> |
| <img width="2442" height="1026" alt="image" src="https://github.com/user-attachments/assets/511f1fcf-44fa-48 …

feat: [UIE-9144] - IAM RBAC: perm check nodebalancer settings tab

---

packages/manager/.changeset/pr-12883-tests-1758049052198.md
packages/manager/cypress/e2e/core/kubernetes/smoke-lke-standard-create.spec.ts
packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts

We started seeing test failures since we turned the LKE-Enterprise `postLa` flag on in prod yesterday. Based on the screenshot, a couple of current tests haven't accounted for the change to the Node Pool plans table, which no longer has an enhanced number input increment/decrement button. That has been moved inside the Configure Pool drawer.
- Update `plan-selection.spec.ts` to remove the check for the disabled increment/decrement buttons. Just a disabled Configure Pool button is visible now.
- Update `smoke-lke-standard-create.spec.ts` to use the new LKE helper functions and correctly reference the Configure Pool button, rather than attempt to click the enhanced number input buttons in the plan row.
9/23 - let's please get …

test: [M3-10628] - Fix Cypress test failures after LKE-E Post LA flag was toggled on

---

packages/manager/.changeset/pr-12892-added-1758187361526.md
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx

Add more checking for users manually inputting route
- Add a noticication banner and disable autocomplete if no permissions
- Update test
10/7
| <img width="3018" height="1414" alt="image" src="https://github.com/user-attachments/assets/783851b1-5680-4ca2-8d4c-1608d078477e" /> | <img width="2980" height="1236" alt="image" src="https://github.com/user-attachments/assets/9d990eb8-ae66-448f-889e-450a250bb6d3" /> |
- iam (restricted) + regular account to compare
<details>
❔ Our …

feat: [UIE-9068] - IAM RBAC: disable field in the drawer

---

packages/manager/.changeset/pr-12894-fixed-1758298095602.md
packages/manager/src/features/Volumes/Dialogs/DeleteVolumeDialog.tsx
packages/manager/src/features/Volumes/VolumeDetails/VolumeDetails.tsx
packages/manager/src/features/Volumes/VolumeDrawers/VolumeDrawers.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx

Volume deletion from the Volume Details page fixed.
Additional "onDeleteClose" method added to the "DeleteVolumeDialog" which
is executed when delete operation is successful.
- Navigate to the volumes page.
- Create a dummy volume.
- Navigate to the volume details page.
- Open delete volume dialog.
- Cancel deletion and make sure the app stays on the volume details page.
- Open delete dialog again and delete volume.
- Make sure the app navigate back to volumes page after deletion.
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-change …

fix: [STORIF-101] - Volume deletion from the Volume Details page fixed.

---

packages/manager/.changeset/pr-12911-tech-stories-1758736596975.md
packages/manager/src/featureFlags.ts

Tiny PR to remove the left-behind and now deprecated `lkeEnterprise` flag from the Feature Flags interface.
With the release of CM v1.151.0, we moved to `lkeEnterprise2`, which is currently serving LKE-E features as of 9/23.
10/7
<details>
👣 …

change: Remove deprecated flag from Flags interface

---

packages/manager/.changeset/pr-12922-fixed-1758907285299.md
packages/manager/cypress/e2e/core/account/restricted-user-details-pages.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts
packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx

This PR updates the upgrade version modal so that the UX copy more accurately reflects the behavior based on the  update strategy. Since the version upgrade is at the cluster level, while the update strategies are at the node pool level, we worked with Tech Writing to use one sentence that is applicable in all cases.
- Updates the line of copy in the UpgradeVersionModal that references worker nodes updates for LKE-E clusters
- Updates the title (from Tech Writing: Reframes the modal as an action instead of a question. Also, this removes the word Kubernetes, since it’ll also be mentioned in the description and doing so shortens the title to the most important details.)
- Updates test coverage
10/7
| …

fix: Update LKE-E cluster Upgrade Version modal copy to mention update strategy

---

packages/manager/.changeset/pr-12933-fixed-1759235571094.md
packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx

User Menu: Hide IAM Beta badge for LA.
- hide IAM Beta badge for LA.
October 7th
| ![Screenshot 2025-09-30 at 2 29 25 PM](https://github.com/user-attachments/assets/7907fc96-a4b6-4534-b4da-cbd6da42fb50) | ![Screenshot 2025-09-30 at 2 29 02 PM](https://github.com/user-attachments/assets/2f7ca002-594b-4724-b50a-e49ced331543) |
Use IAM account.
<details>
➕ Adding a …

fix: [UIE-9286] - User Menu: Hide IAM Beta badge for LA

---

packages/manager/.changeset/pr-12942-fixed-1759355205373.md
packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts

Customers reported that they are unable to view the EU VAT and Swiss VAT on invoices issued in cloud manager since 1st of September.
The PDF generator appears to have date-based filtering logic that was preventing tax IDs from displaying. The logic would set `countryTax` to `undefined` when `hasTax` was `false` (based on invoice date vs tax start date). The actual availability of tax data is controlled by LaunchDarkly flag configuration, not by date filtering in the code.
- Always show tax id's when available
Next release
| <img width="764" height="272" alt="Screenshot 2025-10-01 at 5 36 42 PM" src="https://github.com/user-attachments/assets/0cad3dc3-accb-4704-a9d1-3a00f351c829" /> …

fix: [M3-10619] - Display tax ids for pdf generation

---

packages/manager/.changeset/pr-12939-added-1759348628476.md
packages/manager/.changeset/pr-12939-changed-1759348579491.md
packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsHostRows.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsHostRows.tsx
packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsRow.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/ConnectionDetailsRow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseNetworking/DatabaseManageNetworking.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/constants.ts
packages/manager/src/mocks/serverHandlers.ts

This pull request updates the behavior for the `hostname` field that appears in the `Connection Details` tables in the Database Details Summary and Networking tabs. It also refactors these tables so that they're easier to manage via shared components.
**This following changes were made in this pull request:**
**1. Refactoring the Connection Details tables that appear in the Database Summary and Networking tabs**
- They now use shared components so they're easier to manage conditionally. 
- The structure and usage is the same for the rows used in the two tables (ie. render a label and content). The content is the only part that varies and now that's passed down from the parent to a shared component or handled in it's own component entirely (More information on on this below)
**2. Updating …

feat: [UIE-9181] - DBaaS - Display hostname in summary tables based on VPC configuration and refactor connection details

---

packages/manager/.changeset/pr-12947-fixed-1759415336915.md
packages/ui/src/foundations/themes/dark.ts
packages/ui/src/foundations/themes/light.ts

Placeholder text should use: `component/textField/placeholder/hintText (#696970)` as opposed to (#343438)
| <img width="424" height="108" alt="Screenshot 2025-10-02 at 10 19 41 AM" src="https://github.com/user-attachments/assets/5c83c3b8-1361-49eb-b2c0-f14ba3013565" /> | <img width="432" height="104" alt="Screenshot 2025-10-02 at 10 18 29 AM" src="https://github.com/user-attachments/assets/562de3c0-585b-48c4-a69a-afd7ec63ca27" /> |
| <img width="429" height="104" alt="Screenshot 2025-10-02 at 10 19 46 AM" …

fix: [M3-10659] - Update placeholder text color

---

packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.test.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetActionMenu.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionMenu.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx

This PR fixes permission mismatches in VPC actions. It removes the unnecessary ``update_vpc`` check for PowerOn/PowerOff/Reboot/Unassign Linode and replaces the subnet deletion check with ``delete_vpc`` instead of ``update_vpc``. Additionally, it addresses an issue where multiple unnecessary requests were sent to the Permission API after navigating to /vpcs/[vpcId].
- Removed ``update_vpc`` permission check from Power On/Off/Reboot/Unassign Linode actions.
- Updated subnet deletion check to use ``delete_vpc`` instead of ``update_vpc``.
- Optimized permission fetching to avoid redundant API calls on the VPC details route.
October 7th
| 📷 | …

fix: [UIE-9266], [UIE-9268], [UIE-9299] - IAM RBAC: Fix permission checks for subnet actions in VPC, fetch permissions only when drawer is open

---

packages/manager/.changeset/pr-12944-upcoming-features-1759397682222.md
packages/manager/src/features/Delivery/Streams/StreamForm/Delivery/StreamFormDelivery.tsx
packages/manager/src/features/Delivery/Streams/StreamsLanding.tsx

Destination Name autocomplete wasn't correctly filtering existing Destination Names
- change key in Destination Name autocomplete 
October 2025
| ![before](https://github.com/user-attachments/assets/b9c354c5-7087-42c4-ace8-3eb27b156481)|![after](https://github.com/user-attachments/assets/b40b5e5e-8813-4390-83bf-028a53bfbb96)|
- Open Local Dev Tools
- Enable MSW, set Base Preset to CRUD
- Apply
- Create at least two Destinations with the same name
- Try to filter the Destination Names in Create Stream form
<details> …

upcoming: [DPS-34980] Fix Destination Name autocomplete in stream form not filtering correctly

---

packages/manager/src/App.tsx
packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts

Hooks cannot be after conditional code causing the first page load for fetching launch darkly configs to be `undefined`.
- In incognito, log into cloud manager
- Change country code to any country in EU
- Download a PDF and observe the tax id's are NOT visible
- Reload the page and try again, observe that they ARE visible
This is because of the placement of the hooks where LD configs would not load on initial app load

fix: [M3-10619] - PDF generation fix

---

packages/manager/.changeset/pr-12958-fixed-1759747213086.md
packages/manager/src/queries/entities/entities.ts

This PR fixes the issue when new created entities are not showed in the select while assigning new role
- Ensured that newly created entities are included in the options list when navigating via the navbar (not when opening a new tab)
10/21
- Use IAM account
<details>
🧪 …

feat: [UIE-9329] - IAM RBAC: refetch entities
