src/components/TabbedPanel/TabbedPanel.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx, src/features/linodes/LinodesCreate/LabelAndTagsPanel.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesCreate/SelectRegionPanel.tsx
=> M3-146 Select Linode Panel

src/App.tsx
- If you nest Routers you're gonna have a bad time
=> Fix Logout

src/components/PrimaryNav/PrimaryNav.tsx, src/features/Footer/Footer.tsx
https://jira.linode.com/browse/M3-475?filter=-1
=> Adding external links in primaryNav and footer as needed

src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/SelectBackupPanel.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/layouts/OAuth.test.tsx, src/layouts/OAuth.tsx, src/utilities/queryParams.ts
- Move common query string related functions
- Correctly limit plan selections based on selected Linode type
- Prefer class properties to bound functions
=> Respond to feedback on Create from Backup

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx
small PR to tighten styling on the adv config panel and drawers
=> Linode Settings Tab/ Adv Config - cancel button and spacing styling

src/features/TopMenu/SearchBar/SearchBar.tsx, src/features/TopMenu/SearchBar/SearchSuggestion.tsx
Fixing colors to match comps after regression introduced by the select menu drop down
=> Fix searchbar results colors from regression

.travis.yml, e2e/config/selenium-config.js, e2e/config/wdio.storybook.conf.js, scripts/pre-commit.sh, src/components/Button/Button.tsx, src/components/Button/button.spec.js, src/components/Button/button.stories.tsx, src/components/Button/index.ts, src/components/CheckBox/CheckBox.spec.js, src/components/ExpansionPanel/ExpansionPanel.spec.js, src/components/IconTextLink/IconTextLink.spec.js, src/components/Radio/Radio.spec.js, src/components/Tag/Tag.spec.js, src/darkTheme.ts, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx, src/theme.ts
This PR abstracts the button component in order to reuse the loading props when needed.
So far this implements it in the linodes/[id]settings section
=> Button component

src/eventTypes.ts, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Cancelling backups is a destructive action, so it needs a confirmation dialog
=> M3-499 Add confirmation dialog when cancelling backups

src/components/ActionMenu/ActionMenu.tsx, src/components/Drawer/Drawer.tsx, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainRecordActionMenu.tsx, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainsLanding.tsx, src/services/domains.ts, src/theme.ts, src/types/Domain.ts
Allow users to edit their SOA record for master domains.
=> add: Edit domain.

src/components/Select/Select.spec.js, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
* Adds tests for the select components
* Fixed a spelling error in the story
* Added a `data-qa` attribute for testing
=> M3-382 - Select Component Tests

src/features/Volumes/VolumesLanding.tsx
Add documentation sidebar to VolumesLanding.
=> Add docs to VolumesLanding

src/eventMessageGenerator.ts
Update event messages map for Volumes.
=> Add event messages for Volumes

src/App.tsx, src/events.ts, src/features/Domains/DomainRecordDrawer.tsx, src/features/TopMenu/UserNotificationMenu/UserNotificationMenu.tsx, src/features/Weblish/Weblish.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/powerActions.ts, src/features/profile/APITokens/APITokens.test.tsx, src/features/profile/APITokens/APITokens.tsx, src/features/profile/OAuthClients/OAuthClients.tsx, src/notifications.ts, src/services/account.ts, src/services/domains.ts, src/services/images.ts, src/services/index.ts, src/services/linodes.ts, src/services/misc.ts, src/services/networking.ts, src/services/nodebalancers.ts, src/services/profile.ts, src/services/volumes.ts, src/types/Profile.ts
Replace all HTTP requests that are relying directly on Axios with the new Request system
=> Replace axios requests

src/features/linodes/events.ts
Fixes the power state when resizing a Linode
=> add linode_resize to list of linode events

src/features/profile/APITokens/APITokenDrawer.test.tsx, src/features/profile/APITokens/APITokenDrawer.tsx
Select All function for scopes when creating new Personal Access Token. Developed per the mockup provided by O3
=> M3-488 select all permissions

src/App.tsx, src/features/Footer/Footer.tsx, src/index.css
This PR fixes many issues we had with the footer behaving oddly once the drawer was opened among other situations. I also removed some MUI base styles that were not needed as an import and ported what was needed in out theme.
=> Fix issues with footer positioning and jinxyness 

e2e/pageobjects/list-linodes.js, e2e/specs/linodes/reboot-linodes.spec.js, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodesGridView.test.tsx, src/features/linodes/LinodesLanding/LinodesGridView.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/LinodesListView.tsx, src/types/Linode.ts
I promise this will be the last PR with unnecessary formatting changes :)
Adding a dialog confirmation to two destructive actions: powering down and rebooting a Linode
=> M3-365 Linode Power Confirmation Dialog

src/features/Volumes/VolumeDrawer.tsx
This PR is just a simple typo fix.
=> Fix typo in volume drawer

src/darkTheme.ts, src/theme.ts
This PR fixes an issue on mobile devices where cancel button backgrounds turn red on click.
=> M3-482 - Remove cancel button red background

e2e/pageobjects/page.js, e2e/specs/usermenu/logout.spec.js, src/features/TopMenu/UserMenu/UserMenu.tsx
* Adds tests for logging out via the user menu
* Adds qa attributes to user menu
=> M3 573 - Log out Test

src/App.tsx, src/features/NodeBalancers/NodeBalancerActionMenu.tsx, src/features/NodeBalancers/NodeBalancers.tsx, src/features/NodeBalancers/NodeBalancersLanding.test.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/NodeBalancers/index.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/services/nodebalancers.ts, src/types/NodeBalancer.ts
List Nodebalancers. Pretty static information. No functionality yet!
=> M3-122 list node balancers

src/features/linodes/LinodesCreate/LinodesCreate.tsx
fixes
* create from backup should scroll to top if no source linode selected
* backup toggle should reset on tab change
=> Backup error scroll to top

src/features/TopMenu/SearchBar/SearchBar.tsx
=> Correct types path.

src/components/EditableText/EditableText.tsx, src/features/NodeBalancers/NodeBalancerActionMenu.tsx, src/features/NodeBalancers/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancers.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/services/nodebalancers.ts
Barebones shell of NodeBalancer Detail
* Editable label
* toggleable tabs
* docs
Found myself wanting to use the implementation for PR #3353 . Will most likely refactor pending the branch merge.
Most importantly, please note this bug: https://bits.linode.com/LinodeAPI/apinext/pull/1254. It's the reason we're getting duplicate toast notifications for errors
=> M3-123 nodebalancer detail shell

e2e/config/wdio.conf.js, e2e/pageobjects/configure-linode.js, e2e/pageobjects/linode-detail-volume.page.js, e2e/pageobjects/linode-detail.page.js, e2e/pageobjects/list-linodes.js, e2e/pageobjects/page.js, e2e/setup/setup.spec.js, e2e/specs/create/clone-from-existing-linode.spec.js, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
* Add clone from existing spec
* Add clone actions to configure linode page object
* Add `data-qa` attributes
=> M3 562 - Clone from Existing Test

src/components/ActionMenu/ActionMenu.stories.tsx, src/components/ActionMenu/ActionMenu.tsx, src/components/MenuItem/MenuItem.tsx, src/components/MenuItem/index.ts, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskActionMenu.tsx
this PR adds a tooltip prop for disabled menu items and implements a couple ActionMenu stories to demonstrate its functionality
=> M3-461 Disabled menu items tooltips

src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx
- Fixes issue where Linode volume list would not update
- Fixes issue where Linode volume count would not update
- Removes duplicate volume list request
=> M3-388 Update Linode Volumes state on all volumes events

src/components/Button/Button.tsx, src/components/ConfirmationDialog/ConfirmationDialog.tsx, src/features/NodeBalancers/NodeBalancerActionMenu.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/services/nodebalancers.ts
Delete your dang NodeBalancers
=> M3-605 Delete NodeBalancer

src/eventMessageGenerator.ts, src/features/TopMenu/UserNotificationMenu/UserNotificationList.tsx
- Added newly discovered events to the list.
- Now logging to console during development. Open your menus, check for unfound events!
=> Add newly discovered events.

src/components/AddNewLink/AddNewLink.tsx, src/components/AddNewLink/index.ts, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainsLanding.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigsPanel.tsx, src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx, src/features/profile/APITokens/APITokens.tsx, src/features/profile/OAuthClients/OAuthClients.tsx
- Add "+ Add a Node Balancer" link to NodeBalancerLanding.
- I used this as an opportunity to create an abstraction of a pretty obvious pattern.
@patthiel There may be test implications. I seen a QA data attribute "data-qa-oauth-create" used more than once, so I removed it. I think it's OK, but I thought best to let you know.
=> add: AddNewLink component and implement

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
Make NodeBalancer chart connection color purple.
=> Update NodeBalancer connections chart color

src/components/TextField.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/services/nodebalancers.ts
- Add TCP protocol
- Update labels and headings per review feedback.
- Disallow selection of HTTP Status and HTTP Body health check types when TCP protocol is selected
- Disallow selection of TCP active health check type  when HTTP/HTTPS protocol is selected.
- Changed session stickiness default to "none"
=> M3-661 M3-649 M3-648 M3-645 all the things

e2e/config/custom-commands.js, e2e/pageobjects/domain-detail/detail.page.js, e2e/pageobjects/domain-detail/domain-details.page.js, e2e/setup/setup.js, e2e/specs/domains/detail-ns-records.spec.js, e2e/specs/domains/list-domains.spec.js, e2e/utils/common.js, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainRecords.tsx
* Adds api utils for getting and removing domains
* Added test for adding a ns record
* Expanded the domain detail page object 
* added domain records `data-qa` data attributes
=> M3-572 -  Add NS record E2E Spec

src/components/ActionsPanel/ActionsPanel.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
A couples spacing fixes to tighten things up
=> NodeBalancers config styling fixes

src/features/NodeBalancers/NodeBalancerActionMenu.tsx
adds the _Summary_ and _Settings_ links to the NodeBalancer landing Kebab/Action menu
=> M3-658 Add NodeBalancer Landing Action Menu Items

src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx, src/features/NodeBalancers/ClientConnectionThrottlePanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
Remove accordion style from NodeBalancer graphs and instead use Paper component. Why collapse them, ya know?
=> M3-660 Remove Accordions from NodeBalancer Graphs

src/components/SelectionRow/SelectionRow.tsx, src/components/ShowMore/ShowMore.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/theme.ts
small responsive fixes to tighten the layout under 1200px
=> Create-from-stackscript responsive fixes

src/features/linodes/LinodesCreate/LinodesCreate.tsx
Remove check for localstorage for hiding/showing Create From StackScript tab
=> Remove local storage check for CreateFromStackScript

src/components/TextField.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv4Drawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
@alioso The position of the AddNewLink buttons needs some styling.
=> Add the ability to add a Private IP to a Linode

src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
If a user has no Linodes and navigates to the _Create from Existing_ tab on the Linode create flow, display a placeholder message instead of the form
=> M3-575 Clone From Existing Placeholder

src/__data__/LinodesWithBackups.ts, src/__data__/linodes.ts, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/types/Linode.ts
Provide means to enable/disable Lassie/Watchdog.
Requires API release 53.3
=> M3-449 Linode Watchdog Panel

src/components/ConfirmationDialog/ConfirmationDialog.spec.js, src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx
* Added confirmation dialog ui component test
```bash
yarn storybook
yarn storybook:e2e
```
Tests should all pass
=> M3-287 - Confirmation Dialog component UI test

src/components/ActionMenu/ActionMenu.spec.js, src/components/MenuItem/MenuItem.tsx
* Adds action menu tests
```bash
yarn storybook
yarn storybook:e2e # in a separate shell
```
=> M3-847 - Action menu component UI test

src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Disables submit button on Linode Resize if no plan is selected
Disables plan in the target plans if the current plan is the same
=> M3-515 M3-558 Linode Resize Fixes

src/features/Domains/DomainCreateDrawer.tsx, src/theme.ts
imported abstracted button, reordered imports and added min width to loading button as a bonus
=> M3-833 fix cancel button styles

src/features/NodeBalancers/NodeBalancersLanding.test.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/linodes/LinodesLanding/RegionIndicator.tsx
remove word wrapping on region and wrap up/down status lines
=> M3-772 Node Balancer landing table cell fixes

src/components/PaginationControls/PageButton.tsx, src/components/PaginationControls/PaginationControls.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
Scroll to top of page when the user switches pages on the Linode landing view
=> M3-179 Scroll to Top on Linode Landing

e2e/config/wdio.conf.js, src/components/HelpIcon/HelpIcon.spec.js, src/components/HelpIcon/HelpIcon.tsx, src/theme.ts
Switched the helper text behavior to hover. Used the MUI tooltip and fixed the test
=> Apply mouseOver event listener to helper text

src/App.test.tsx, src/components/NotFound.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Fix console error
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```
Fix console warning with moment js date being improperly formatted
=> M3-856 Fix Console Errors and Warnings

src/features/Domains/DomainCreateDrawer.tsx
- Start with 1 IP address
- Update label
- Client-side validation
=> M3-882 Fixes for Create Slave Zone

src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx, src/services/networking.ts
* Implement IP Sharing Panel
* Show shared IPs in Linode's IPv4 table
* Allow updating and deleting shared IPs
=> M3-782 IP Sharing 

src/components/EditableText/EditableText.spec.js, src/components/EditableText/EditableText.stories.tsx, src/components/EditableText/EditableText.tsx
* Adds an editable text ui test
* Assigned to @alioso to fix an issue with the editable text story.
=> M3-845 - Editable Text Storybook UI Test

src/components/SelectionRow/SelectionRow.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/StackScriptsLanding.test.tsx, src/features/StackScripts/StackScriptsLanding.tsx
Disabled create button and fixed some styling issues for the landing page
=> Stackscript Landing Styling

src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
Change "StackScripts" to "StackScript"
=> Correct stackscript column heading.

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx
=> Revert "Pre-Open Node Address Search Suggestions"

e2e/pageobjects/linode-detail/linode-detail-networking.page.js, e2e/pageobjects/page.js, e2e/specs/linodes/detail/ip-transfer.spec.js, e2e/utils/common.js, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
* Created a spec for testing IP transfer
* added ip transfer elements to linode-detail-networking page object.
* added data attributes for tests
* added "opposite" handling for "waitForNotice" method. This waits for a notice to not display on a page.
```bash
yarn selenium
yarn e2e --file e2e/specs/linodes/detail/ip-transfer.spec.js
```
Let me know if any additional test cases should be added!
=> M3-844 - IP Transfer Test

src/eventMessageGenerator.ts, src/features/TopMenu/UserNotificationMenu/UserNotificationList.tsx
Found two error messages didnt meet API expectations.
Removed entity usage from message.
Updated logging to give more context on error.
=> Correct error messaging. Update error reporting.

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Show node balancer IP address suggestions onFocus
They will hide onBlur
=> Default Show Node Balancer Config Search Suggestions

e2e/pageobjects/linode-detail/linode-detail-settings.page.js, src/components/ActionsPanel/ActionsPanel.tsx, src/features/Images/ImagesDrawer.tsx, src/features/Images/ImagesLanding.tsx, src/features/linodes/DiskSelect/DiskSelect.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx, src/services/images.ts
Miscellaneous fixes for Images
* Attempt to fix events polling bug
* Add RenderGuard to LinodeSelect and DiskSelect
* Refactor helper method in images.ts
* Fix typos found while making the above changes
=> Images fixes

src/App.tsx, src/features/TopMenu/UserMenu/UserMenu.tsx, src/features/Users/UsersActionMenu.tsx, src/features/Users/UsersLanding.tsx, src/features/Users/index.tsx, src/services/account.ts, src/types/Account.ts, src/utilities/gravatar.ts
- List user accounts
- Show user-related documentation in the sidebar
- Show "Add a User" as a disabled add-new link
- Show "User Profile", "User Permissions", and "Delete" as disabled menu items.
=> M3-722 List User Accounts

e2e/config/custom-commands.js, e2e/constants.js, e2e/pageobjects/configure-linode.js, e2e/pageobjects/configure-stackscript.page.js, e2e/pageobjects/list-stackscripts.page.js, e2e/pageobjects/page.js, e2e/setup/setup.js, e2e/specs/stackscripts/configure-stackscript.spec.js, e2e/utils/common.js, src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
* Added create stackscript smoke test
* Added stackscripts api utils for cleanup after the test run
* Added a generic "chooseSelectOption" method to be used in other tests (handles passing in a select Web element object OR an index)
* Tagged stackscripts form and create page with testing attributes.
=> M3-838 - Create stackscript test

src/App.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UserPermissions.tsx, src/features/Users/UserProfile.tsx, src/features/Users/UsersActionMenu.tsx, src/features/Users/UsersLanding.tsx, src/features/Users/index.tsx, src/services/account.ts
- Edit Username
- This involves the use of reloadableWithRouter, because the username that gets changed defines the routes for the page on which it can be changed
=> M3 724 - Edit Username

src/features/Users/CreateUserDrawer.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UsersActionMenu.tsx, src/features/Users/UsersLanding.tsx, src/services/account.ts, src/types/Account.ts
- Create User via drawer on Users Landing List
- Warning notice that User will set their own password
- Eager addition of User to list on create
- Navigate to permissions page on creation of a restricted user
=> M3-723: User Creation

src/components/HelpIcon/HelpIcon.tsx, src/features/Users/UserDeleteConfirmationDialog.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UserProfile.tsx, src/features/Users/UsersActionMenu.tsx, src/features/Users/UsersLanding.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/services/account.ts, src/utilities/scrollToTop.ts
* Can delete user from Action Menu with confirmation dialog, error and success shown in Notice on page
* Can delete user from a panel on the User Profile tab with confirmation dialog, error shown in Notice, success shown via route context on Users Landing page
=> Delete user panel, dialog, and action menu item

src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
Previously, when searching for a StackScript, then sorting by a table header, the search filter would not be reapplied.
Now, the two will be combined
=> Combine Search and Sort Filtering On StackScripts

src/components/IconTextLink/IconTextLink.tsx
small tweak to re-align the icon and label.
=> M3-947 Update IconTextLink alignment

src/assets/timezones/timezones.ts, src/components/EnhancedSelect/EnhancedSelect.css, src/components/EnhancedSelect/EnhancedSelect.stories.tsx, src/components/EnhancedSelect/EnhancedSelect.tsx, src/components/EnhancedSelect/index.tsx, src/features/profile/DisplaySettings/DisplaySettings.test.tsx, src/features/profile/DisplaySettings/DisplaySettings.tsx, src/features/profile/DisplaySettings/TimezoneForm.test.tsx, src/features/profile/DisplaySettings/TimezoneForm.tsx
Redo of Timezone panel with new version of Select element. MUI Select was too slow and VirtualizedSelect didn't meet accessibility requirements.
If accepted, EnhancedSelect will later be expanded to allow infinite scroll and multi-select.
Needs styling from @alioso since we can't use MUI components. (This replaces the PR that was accidentally marked as merged).
* Move object indexing into EnhancedSelect
* Clear textfield on focus
* Change import syntax in index.ts
* Submit select value on Return/Enter
=> M3-715 Update user timezone

src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
also set the proper markup for the panel title
=> M3-891 Linode resize panel padding

src/features/Users/UserPermissions.tsx
=> Describe billing permission levels

src/features/Users/UsersActionMenu.tsx
Show tooltip for user delete disabled in action menu
=> Show tooltip for user delete disabled in action menu

src/components/EnhancedSelect/EnhancedSelect.css, src/index.css, src/theme.ts
Tiny update to the primary and secondary blues
=> M3-537 Update blue link color currently implemented

src/features/Volumes/VolumesLanding.tsx
Change "attachment" to "attached to" on Volumes landing page
=> M3-985 Update Volumes Landing Column Header

src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Change order of items in Linode Kebab Menu on Linode Landing Page
* Reboot is now an option only when the Linode is powered on
=> M3-986 Linode Kebab

src/features/Images/ImagesLanding.tsx, src/features/ToastNotifications/ToastNotifications.tsx, src/features/Volumes/VolumeDrawer.tsx
Move failed action notifications into a centralized location.
Merged a filtered events$ stream into toast$.
=> M3-676 Add failed event stream to toast notifications.

src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx
Found two stray icon index imports which increased three chunks by 80k each.
=> Import icons directly.

src/features/Account/AccountPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Account/context.tsx, src/services/account.ts
Users need a means by which they can make payment using a stored credit card.
=> M3-611 Make a Credit Card Payment

src/utilities/request.ts
Report API errors (non-404/401) to Sentry.
=> Report API error via Sentry.

src/App.tsx, src/features/Longview/LongivewLanding.test.tsx, src/features/Longview/LongviewLanding.tsx, src/features/Longview/index.tsx
Add placeholder that navigates to CF Manager's Longview
=> M3-994 Longview Placeholder

src/components/IconTextLink/IconTextLink.tsx, src/components/Select/Select.tsx, src/components/SelectionCard/SelectionCard.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Users/UserPermissions.tsx, src/theme.ts
This PR only targets the high priority issues reported by @patthiel affecting Safari v11 only. Issues affecting IE10 are low priority before release.
=> Cross Browser Compatibility: Safari fixes

src/components/Notice/Notice.spec.js
* Adds test spec for the notice component
```
yarn storybook
yarn storybook:e2e --story Notice
```
=> M3-281 - Notice component functional test

e2e/pageobjects/account/users.page.js, e2e/pageobjects/page.js, e2e/specs/account/restricted-users.spec.js, e2e/specs/account/users.spec.js, src/features/Users/CreateUserDrawer.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UsersLanding.tsx
* Added test specs for creating/deleting restricted and unrestricted users
* Hardcoded my email for users (is this an issue?)
* Added page object for users page
```bash
yarn selenium
yarn e2e --dir account
```
=> M3-1018 - Account - Users Restricted/Unrestricted Tests

config/polyfills.js, package.json, yarn.lock
Some people (I won't say who but _some people_) aren't using latest Chrome or Firefox. 
main.js increased by 15kb with these polyfills.
=> M3-471 M3-1033 Fill those polys.

src/App.tsx
* Hide the SideMenu on window resize
=> Nav shelf re-opens when resizing the browser to a smaller width

src/GDPRNotification.tsx, src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx, src/components/ConfirmationDialog/ConfirmationDialog.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Images/ImagesLanding.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/Profile/APITokens/APITokens.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, src/features/Users/UserDeleteConfirmationDialog.tsx, src/features/Users/UsersLanding.tsx, src/features/Volumes/DestructiveVolumeDialog.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx, src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
-- Align actions to the right. (per PO)
-- Progressive action on the right, cancel on the left.
-- Remove lambda functions for actions.
-- User our Button abstraction.
-- Use correct verbiage on buttons. (per PO)
-- Reboot and shut-down are no longer "destructive" (per PO)
=> M3-987 Confirmation dialog updates.

src/features/Images/ImagesDrawer.tsx, src/features/linodes/DiskSelect/DiskSelect.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx
- Add option to Imagize Disk from Linode > Settings > Disks
- Re-uses the ImagesDrawer with a new mode "imagize"
=> M3 976 Imagize Disk

src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
=> Auto-bind cancelBackups

e2e/pageobjects/account/permissions.page.js, e2e/pageobjects/account/users.page.js, e2e/specs/account/view-update-permissions.spec.js, src/features/Users/UserPermissions.tsx
* This test asserts that user permissions display and that one is able to modify the permissions. It does not do anything fancy like "modify a permission -> Login as a restricted user -> attempt to do a restricted action" (Altough, that would be interesting in a followup pass!)
* Added page object with permissions page elements and utility methods
* Added data-qa attributes to permissions page
```bash
yarn selenium
yarn e2e --file e2e/specs/account/view-update-permissions.spec.js
```
=> M3-1016 - View & Edit User Permissions Test

src/components/SelectionCard/SelectionCard.tsx
making sure the card description does not wrap its content once the check mark is present
=> M3-1078 Length of Linode type name should not affect size of Selection Card

src/index.tsx, src/utilities/createImageBitmap.ts
Adds a createImageBitmap polyfill
=> Add createImageBitmap polyfill

src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
Safe access response errors on LinodeSettingsAlertsPanel.
=> M3-1089 Cannot read property 'data' of undefined.

src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTicketDetail/TicketReply.tsx, src/services/support.ts
When viewing an open ticket and its replies, a form at the bottom of the reply list allows you to add a new reply.
=> M3-1004 ticket reply

src/features/linodes/LinodesLanding/LinodeRow.tsx
Don't allow Linode plan type to wrap on LinodeRow
=> Don't allow Linode plan type to wrap on LinodeRow

package.json, src/UserAgentNotification.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx, yarn.lock
Thew goal of this PR is mostly to target IE however the manager breaks completely in IE because of JOY. I will keep this in progress until that is being fixed
=> Add Browser detect to display warning for outdated browsers

src/LinodeThemeWrapper.tsx, src/components/EnhancedSelect/EnhancedSelect.tsx, src/components/Placeholder/Placeholder.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/components/ShowMoreExpansion/ShowMoreExpansion.tsx, src/darkTheme.ts, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsButton.tsx, src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx, src/theme.ts
Latest and greatest updates for the dark theme
=> d-theme updates

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/services/nodebalancers.ts
- Allow a check path of '/'
- Clear check related fields upon check type change
- Get rid of related lambda functions in render
=> M3-1067 Nodebalancer Create Fixes

src/App.tsx, src/components/PrimaryNav/PrimaryNav.tsx
Remove support content from nav and change the Get Help URL to /support
=> Support Refactor

src/features/Help/Panels/OtherWays.tsx
If Ada chat bot script could not load, show an error
Previously, nothing happens upon error
=> Ada Error Handling

src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
Change StackScript revision note from textarea to input text field
=> M3-1066 StackScript Revision Note

src/features/Account/AccountPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Account/AccountPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/services/account.ts
* Fixes M3-1170: bad sorting of Payments and Invoices when there are multiple pages
* Fixes M3-1183: lost page controls when changing page size
* Fixes a page crash when viewing / billing as a restricted user
=> Fixes M3-1170, M3-1183 and restricted user page crash on viewing /billing

src/features/Footer/Footer.tsx
Add version number and link to Footer.
=> M3-335 Add version to footer.

src/features/Profile/AuthenticationSettings/SecuritySettings.tsx
change: Update Account Security title to IP Whitelisting (Legacy)
=> M3-1015 Update Account Security title.

src/components/EnhancedSelect/EnhancedSelect.spec.js, src/components/EnhancedSelect/EnhancedSelect.tsx
* Adds a functional test for the enhanced select component
* Note: I did not add tests for the arrow down/enter functionality, as those can be flaky on selenium. However, I have added a ticket to the backlog to add those once google chromedriver supports the actions api.
```
yarn storybook
yarn storybook:e2e --story EnhancedSelect
```
=> Enhanced Select Functional Test

src/components/TextField.tsx, src/features/Profile/Referrals/Referrals.tsx, src/theme.ts
Make referral code & URL text boxes wide enough to show you the entire value
=> Make referral code & URL text boxes fill width

src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
=> M3-1206 Support ticket landing page - ticket label alignment

src/components/Tile/Tile.stories.tsx, src/components/Tile/Tile.tsx, src/components/Tile/index.ts, src/features/Help/Panels/OtherWays.tsx
This is the one of two PRs for M3-1193.
https://github.com/linode/manager/pull/3735 targets table Rows
This one creates a new Tile component. Its only instances so far is at /support for the "Other ways to get help" tiles
=> M3-1193 clickable tiles

src/components/DocsSidebar/DocComponent.tsx, src/features/StackScripts/SelectStackScriptPanel/StackScriptsSection.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/utilities/truncateText/index.ts, src/utilities/truncateText/truncateText.test.ts, src/utilities/truncateText/truncateText.ts
Abstract truncate functions and implement in docs and stackscripts
=> M3-761 Truncate Text

src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
All entities on dashboard now sorted by label, ascending
=> M3-1190 Dashboard Entity Sorting

src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx
Change "Product News" to "Blog" on dashboard
=> M3-1911 Blog

src/features/Account/AccountDetail.tsx
Remove _Billing Account_ and _Billing Information_ headers
=> M3-1072 Remove Account Billing Headers

src/eventMessageGenerator.ts
Add messages to handle StackScript events.
FYI There's an API where two identical events are generated for the creation of a StackScript. It's being looked into.
=> M3-1056 Add StackScript event messages

src/components/Tile/Tile.spec.js, src/components/Tile/Tile.tsx
* Adds functional tests for the tile component
```bash
yarn storybook
yarn storybook:e2e --story Tile # in a separate shell
```
=> Tile Component Functional Test

src/assets/icons/diagonalArrow.svg, src/components/ExternalLink/ExternalLink.stories.tsx, src/components/ExternalLink/ExternalLink.tsx, src/components/ExternalLink/index.ts, src/components/Tile/Tile.tsx
New component for external links to add an icon next to them
added in story book and implemented at /support
=> M3-1101 New External Link component

src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx
add: Update help text for Linode disk resizing.
=> M3-901 Update disk creation drawer help text.

e2e/constants.js, src/components/Tile/Tile.tsx, src/features/Help/Panels/PopularPosts.tsx, src/features/Help/Panels/SearchPanel.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/Support/SupportTickets/TicketList.tsx
* Adds UI tests for support landing and support tickets
* Does not test support search, will create an additional ticket to test search.
```bash
yarn selenium
yarn e2e --dir support
```
=> M3-1261 - Support Landing and Tickets UI tests

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/specs/create/create-volume.spec.js, e2e/specs/linodes/detail/detach-attach-volumes.spec.js, e2e/specs/linodes/detail/edit-clone-resize-volumes.spec.js, e2e/specs/search/search-volumes.spec.js, src/features/Volumes/VolumesLanding.tsx
* This PR addresses issues in the volumes tests and refactors many of the utility methods
```bash
yarn selenium
yarn e2e:modified
```
=> M3-1049 - Refactor Volumes e2e tests

src/components/ActionsPanel/ActionsPanel.tsx, src/components/Button/Button.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx, src/utilities/storage.ts
Opt out of Linode Mutation Upgrade
1. Login to dev-test-003 or use Charles to create fake responses
2. Open mutation drawer on the Linode Detail page
3. Click Opt out
=> M3-1238 Opt Out of Linode Mutation

e2e/pageobjects/dashboard.page.js, e2e/specs/dashboard/dashboard.spec.js, src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx, src/features/Dashboard/Dashboard.tsx, src/features/Dashboard/DashboardCard.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
* Adds a few simple tests to the dashboard
* Adds a page object for future dashboard tests
* Tagged elements with data attributes.
```bash
yarn selenium
yarn e2e:modified
```
=> M3-1260 - Dashboard UI Tests

src/components/SelectionRow/SelectionRow.tsx, src/components/TableRow/TableRow.tsx, src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Domains/DomainsLanding.tsx, src/features/NodeBalancers/NodeBalancersLanding.test.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/StackScripts/SelectStackScriptPanel/PanelContent/StackScriptTableHead.tsx, src/features/Users/UsersLanding.tsx, src/features/linodes/LinodesLanding/LinodesListView.tsx, src/index.css, src/theme.ts
added to:
- recent invoices
- domains landing
- users
- all dashboard tables
- stackScripts
=> M3-1315 apply new TableRow Component siteWide

src/App.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Fix issue where app was crashing anywhere types were needed
Also filter out deprecated types on create flow and resize flow
=> Types Error

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/specs/volumes/volume-configuration.spec.js
* updates the test to use click the placeholder button when attempting to create a volume on `/volumes`
* Small fix that corrects 2 breaking tests
=> Volume Configuration Test Fix

src/components/Placeholder/Placeholder.tsx
ex: /longview
making sure the placeholder icon and placeholder text is not too large on Mobile
=> M3-1323 Style mobile placeholder

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Add a mobile version (small button) for the Create Menu in the top bar
=> M3-1325 add Create Menu mobile version

src/components/Drawer/Drawer.tsx, src/components/PasswordInput/PasswordInput.tsx, src/components/PasswordInput/StrengthIndicator.tsx, src/components/Select/Select.tsx, src/components/TextField.tsx, src/darkTheme.ts, src/features/Account/AccountPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx, src/features/Account/AccountPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/Profile/DisplaySettings/TimezoneForm.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.tsx, src/features/Users/UserPermissions.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx, src/theme.ts
This is a general ticket to get our inputs FW at a low breakpoint (< 600) in order to maximise space and usability on mobile devices. 
To be tested by navigating through all pages containing forms
=> M3-1324 Make all inputs full width on Mobile

src/features/Profile/APITokens/utils.ts
Make Personal Access Tokens default to `read_write` when opening creation drawer
=> M3-552 PAT Tokens Default

src/features/Help/Panels/OtherWays.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx
There was some text there and now there's some different text there
=> M3-1178 Help Copy Changes

src/features/Profile/APITokens/APITokenMenu.tsx
=> M3-551 PAT Token Action Menu Copy

src/components/CircleProgress/CircleProgress.spec.js, src/components/CircleProgress/CircleProgress.stories.tsx, src/components/CircleProgress/CircleProgress.tsx
* Adds a functional test for the data-inside circle progress story.
* Travis will pick this up and run it. No need to run this manually, code review is just fine for this one 😄
=> Circle progress - Data Inside Functional Test

src/services/nodebalancers.ts
Goofed on the NB config update schema.
=> M3-1381 Correct NodeBalancerUpdateSchema

package.json, src/services/nodebalancers.ts
* Fix for release blocker M3-1381: Nodebalancers - Configuration - Unable to update configurations/settings
=> Release 0.34.1

src/features/Support/SupportTicketDetail/TicketReply.tsx
Change support ticket reply button from Send to Add Update
=> M3-1312 Ticket reply copy

src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Fix issue where access panel was not rendering correctly on _Create Linode from StackScript_ form
=> M3-1378 Access Panel Fix

src/features/Account/AccountPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Show the last four digits of the customer's credit card on the payment form
=> M3-1209 Add Last Four to Payment Panel

src/components/LineGraph/LineGraph.stories.tsx
Add the very chic `<LineGraph />` component to Storybook
=> [Storybook] Line Graph

src/features/linodes/LinodesDetail/HeaderSections/NotificationsAndUpgradePanel.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx
Replace link to Classic Manager with the mutate drawer opening
=> Show Mutate Drawer

src/components/ConfirmationDialog/ConfirmationDialog.spec.js, src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx, src/components/CopyTooltip/CopyTooltip.stories.tsx
=> M3-1025 Copy Tooltip Storybook Component

e2e/pageobjects/configure-linode.js, e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/page.js, e2e/specs/create/smoke-linode-with-tags.spec.js, src/components/EnhancedSelect/EnhancedSelect.spec.js, src/components/EnhancedSelect/EnhancedSelect.stories.tsx, src/components/EnhancedSelect/EnhancedSelect.tsx, src/components/EnhancedSelect/components/MultiValue.tsx, src/components/EnhancedSelect/components/SelectControl.tsx, src/components/EnhancedSelect/components/SelectPlaceholder.tsx, src/components/Tag/Tag.tsx, src/features/linodes/LinodesDetail/HeaderSections/LinodeTag.tsx, src/features/linodes/LinodesDetail/HeaderSections/TagsPanel.tsx
**Note** this PR is based off changes in https://github.com/linode/manager/pull/3885 once that is merged i will rebase.
* Adds a spec that tests creating a linode from an image with tags, asserts that the tags then display on the linodes listing page and also tests that tags display/can be added/removed on the linode detail page.
* This could be broken down into smaller tests, using api calls to create a linode with new or existing tags. If these tests prove to be unstable I will break them down that way.
```
yarn selenium
yarn e2e --file e2e/specs/create/smoke-linode-with-tags.spec.js
```
=> M3 1420 - Tags - Linode Create/List/Detail E2E Test

src/components/EnhancedSelect/Select.tsx, src/components/EnhancedSelect/components/NoOptionsMessage.tsx, src/components/EnhancedSelect/components/SelectPlaceholder.tsx, src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx, src/darkTheme.ts
Fixes tag display for Dark Theme
=> M3-1416 DT tags

src/features/Help/Panels/AlgoliaSearchBar.tsx, src/utilities/breakpoints.ts
Let me know if you need a walkthrough of the logic changes. It gets a little dizzying.
=> M3-1346 Increase support search results from 5 to 20

src/darkTheme.ts, src/features/linodes/LinodesDetail/HeaderSections/TagsPanel.tsx, src/theme.ts
this is a small PR to better the "add tag" workflow styles
=> M3-1384 Add tag workflow

src/components/ExpansionPanel/ExpansionPanel.spec.js, src/components/ExpansionPanel/ExpansionPanel.stories.tsx, src/components/TableRowLoading/TableRowLoading.tsx, src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx
Add Expansion Panel storybook component that will asynchronously load content the first time it's opened
* Also fixed some formatting issues and loading state in Invoices Panel
=> [Storybook] Async Content in Expansion Panel

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/page.js, e2e/pageobjects/volumes.page.js, e2e/setup/setup.js, e2e/specs/create/smoke-create-attached-volume.spec.js, e2e/specs/create/smoke-create-volume.spec.js, src/components/EnhancedSelect/components/SelectPlaceholder.tsx
* Added functional tests for the new enhanced selects
* Fixed the create volumes test (since volume creation from the global create drawer now uses the enhanced select).
* @Jskobos added a fix to the enhanced select story that unties the value of two of the selects (basic and basic with error). 
```bash
yarn selenium
yarn e2e --file e2e/specs/create/smoke-create-volume.spec.js
```
```bash
yarn storybook
yarn storybook:e2e --story EnhancedSelect
```
=> Enhanced Select functional test & Create volume test fix

src/features/Users/UserDetail.tsx
1. Go to /users and click on a user to visit the details page
2. Check the console; controlled to uncontrolled input warning should be gone
=> M3-1449 controlled input warning

src/components/Table/Table.tsx, src/components/TableCell/TableCell.tsx
Adjustment to empty table cell display for small screens. See ticket for details.
=> M3-1472 Access Panel mobile style bug

src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Account/AccountPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx
Implement Pagey on Recent Invoices and Recent Payments panel
Recent Payments does not take a  `filter` parameter.
=> M3-1509 M3-1508 Pagey on Payments and Invoices

src/__data__/paginationProps.ts, src/features/NodeBalancers/NodeBalancersLanding.test.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx
Add Pagey to NodeBalancers Landing
=> M3-1504 Pagey NodeBalancers

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx, src/services/linodes/getLinodeInfo.ts
This PR filters out kernels that are incompatible with a Linode's hypervisor type in its advanced configurations.
=> M3-1180 Filter kernel MenuItems by Linode hypervisor

src/features/Longview/LongviewLanding.tsx
See ticket for copy change. Changing text of button to match the action.
=> M3-1590 Change Text on Longview Label

e2e/config/wdio.conf.js, e2e/pageobjects/account/billing.page.js, e2e/specs/account/billing.spec.js, src/features/Account/AccountPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Account/AccountPanels/SummaryPanel/SummaryPanel.tsx, src/features/Account/AccountPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
* Adds tests for viewing/updating contact info and invoices
* Fixes issue where tests would attempt to run in parallel despite only having one test user defined in your `.env` file
* Added data attributes to account pages 
```bash
yarn e2e:modified
```
=> M3-940 & M3-941 - View/Update Contact info and invoices tests

src/components/TableSortCell/TableSortCell.tsx, src/features/Images/ImagesLanding.tsx, src/features/StackScripts/SelectStackScriptPanel/PanelContent/StackScriptTableHead.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx, src/themeFactory.ts, src/themes.ts
Previously, the StackScript search bar had too much padding and was misaligning elements.
=> StackScript Table Visual Regression

src/components/EditableText/EditableText.tsx
Addressing feedback that came out of the design review.
=> Adding pencil icon to show for screen sizes below large

src/services/misc/index.ts, src/services/misc/misc.ts
* Add comment strings
* Add get method for /regions/:regionID
=> M3-1397 Refactor services/misc

src/features/Domains/DomainsLanding.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/Support/SupportTickets/TicketList.tsx, src/features/Support/SupportTickets/ticketUtils.ts, src/features/Users/UsersLanding.tsx
Add Pagey's `onDelete` method to:
* Domains
* OAuth Clients
* APITokens
* Users
* Also added Pagey to both Support Tickets and Domains
With this PR, the only Pagey task left is to add the `onDelete` logic to LinodesLanding
=> Pagey Cleanup

src/components/Toggle/Toggle.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UserPermissions.tsx
Prevent user from going into the user permissions for their account and turning restrictions on
=> M3-1185 Prevent User From Self-Restricting

src/components/ActionMenu/ActionMenu.tsx, src/components/TableRow/TableRow.tsx, src/themeFactory.ts, src/themes.ts
This ticket address only the <Tables> portions of info density. We have reduced the padding of the table cell as well as adjusting dependent components/styles.
=> M3-1465 Information Density

src/features/Account/AccountPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Account/AccountPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/features/Users/UserPermissions.tsx, src/services/account/account.schema.ts, src/services/account/oauth.ts, src/services/account/payments.ts, src/services/account/users.ts, src/services/index.ts, yarn.lock
* Add documentation for account endpoint-related things
* Add validation schemas as appropriate, updating error handling when necessary.
* Standardized function signatures, moved filters from `services` and into the Manager proper
=> M3-1393 refactor account

src/components/TabbedPanel/TabbedPanel.tsx, src/features/Account/AccountPanels/SummaryPanel/SummaryPanel.tsx, src/features/Footer/Footer.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesLanding/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeStatusIndicator.tsx, src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
This is the second part of the info density effort to address detail pages (summary panels and tabbed panels). This PR just reduces a bit of padding and fixes small styling regression due to this effort
=> M3-1465 Summary panels and Tabbed Panels density

src/components/EditableText/EditableText.tsx
Editable Text experienced some style regression after form updates were merged. Also made adjustments to breakpoint and focus state.
=> M3-1687 Input/Editable Text Regression

src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx, src/services/networking/index.ts, src/services/networking/networking.schema.ts, src/services/networking/networking.ts
- Add documentation
- Tidy method signatures
- Add missing API methods
=> clean networking and add missing methods

src/services/stackscripts/stackscripts.ts
- Add documentation
- Use consistent argument names
=> M3-1401 clean services/stackscripts

src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx, src/services/volumes/volumes.schema.ts, src/services/volumes/volumes.ts
Add comments and schema. This one was simple and didn't break anything.
=> M3-1400 Refactor services/volumes

src/features/Domains/DomainCreateDrawer.tsx, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainZoneImportDrawer.tsx, src/services/domains/domains.schema.ts, src/services/domains/domains.ts, src/services/domains/index.ts, src/services/domains/records.schema.ts, src/services/domains/records.ts
- Add missing API method on records
-  Resolve `data` on request methods and update components accordingly
**Notes:**
I would especially appreciate eyes on the components dealing with `domain` and `record` requests, since I changed the resolve signature.
**TODO:**
~Add Yup validation.~ _Done_
=> M3-1394 clean services/domains

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/features/linodes/LinodesDetail/LinodeBackup/backupUtils.ts, src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv4Drawer.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesLanding/powerActions.ts, src/services/index.ts, src/services/linodes/backups.ts, src/services/linodes/configs.ts, src/services/linodes/getLinodeInfo.ts, src/services/linodes/index.ts, src/services/linodes/linode.schema.ts, src/services/linodes/linodeActions.ts, src/services/linodes/linodeDisks.ts, src/services/linodes/linodeIPs.ts, src/services/linodes/linodes.ts, src/types/Linode.ts, src/utilities/allocateIPAddress.ts, src/utilities/getAll.ts, yarn.lock
Refactor `services/linodes`, including:
* add comments
* standardize signatures
* add schemas, types, and interfaces where applicable
* remove unused methods
* refactor manager-ized methods into generics
=> M3-1396 refactor linodes

e2e/config/wdio.conf.js, e2e/pageobjects/configure-linode.js, e2e/specs/create/smoke-linode-with-tags.spec.js, e2e/specs/linodes/smoke-linodes.spec.js
**Purpose:**
Added a test for M3-1657 and an additional flag for logLevel. To verify the test run and logLevel flag run:
yarn e2e --file e2e/specs/linodes/smoke-linodes.spec.js --logLevel (silent | verbose | command | data | result | error)
=> M3-1692 test linoderow clickable tags

src/features/TopMenu/SearchBar/SearchBar.tsx
I also modified the Placeholder text for mobile
=> M3-1684 fix zIndex issue with mobile search panel

e2e/pageobjects/account/permissions.page.js, e2e/pageobjects/account/user-detail.page.js, e2e/pageobjects/account/users.page.js, e2e/pageobjects/configure-stackscript.page.js, e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js, e2e/pageobjects/page.js, e2e/specs/account/user-detail-spec.js, e2e/specs/account/users.spec.js, e2e/specs/linodes/detail/rebuild.spec.js, src/components/Toggle/Toggle.tsx
**Purpose:**
Added a test for M3-1185 - User can restrict him/herself in the test class users.spec.js, added a qa selector to to the Toggle component, and centralized references to the HelpIcon tooltip. To test the files affected by the refactor run:
yarn selenium
yarn e2e --spec=e2e/specs/account/users.spec.js,e2e/spec
s/stackscripts/list-stackscripts.spec.js,e2e/specs/stackscripts/smoke-configure-stackscript.spec.js,e2e/specs/account/user-detail-spec.js,e2e/specs/linodes/detail/rebuild.spec.js
=> M3-1693 user can restrict them self

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
This PR fixes an typing issue that was created when we merged #4011 and #3993 that caused the build to fail.
=> FromBackupsContent typing fix

e2e/constants.js, e2e/pageobjects/account/user-detail.page.js, e2e/pageobjects/profile.js, e2e/pageobjects/profile/auth.page.js, e2e/specs/profile/tfa.spec.js, package.json, src/features/Profile/AuthenticationSettings/TwoFactor/ConfirmToken.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, yarn.lock
* Added tests for Enabling/Disabling TFA on profile
* Added otplib library as a dev dependency for generating otp tokens from the secret generated by the API. This allows us to actually enable TFA in the e2e test.  😄 
```bash
yarn selenium # in a new shell
yarn e2e --spec e2e/specs/profile/tfa.spec.js
```
=> M3-1672 - Profile Enable/Disable TFA Test

src/features/Domains/DomainRecordDrawer.tsx
Add TTL field to MX form and TTL value to MX listings
=> M3-1720: add TTL to MX record

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Set maximum graph value to default to make it adjustable to the values we get from the server
=> M3-1678: add dynamic max CPU level

src/features/Domains/DomainRecords.tsx
this PR also adjusts mobile styles for this display
=> M3-1748 Remove expanding panels for DNS landing and align add buttons

src/features/Support/ExpandableTicketPanel.test.tsx, src/features/Support/ExpandableTicketPanel.tsx
also adjusted the spacing between the icons
=> M3-1759 Open hively links in new window

src/features/Account/AccountPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Account/AccountPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx
- remove card section when current card is missing
- remove unnecessary fallbacks
=>  M3-1345: remove card placeholder on billing page

src/components/TabbedPanel/TabbedPanel.tsx, src/features/Domains/DomainDetail.tsx, src/features/Lish/Lish.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/Profile/Profile.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/Users/UserDetail.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesDetail/HeaderSections/TabsAndStatusBarPanel.tsx, src/themeFactory.ts, src/themes.ts
This PR implements responsive tabs with enhancing the styling of native MUI responsive tabs
=> M3-1740 Responsive Tabs

e2e/config/wdio.conf.js, package-lock.json, package.json, yarn.lock
Added wdio-spec-reporter for clearer reporting in CI run.
**To test**
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e --log --spec=e2e/specs/account/view-update-permissions.spec.js` ensure reporting output should contain test step detail.
=> Added the webdriverio spec reporter, for clearer failed test reporting

e2e/pageobjects/account/billing.page.js, e2e/pageobjects/account/user-detail.page.js, e2e/pageobjects/account/users.page.js, e2e/pageobjects/configure-linode.js, e2e/specs/account/restricted-users.spec.js, e2e/specs/account/user-detail-spec.js, e2e/specs/account/users.spec.js, e2e/specs/create/create-from-stackscript-with-tags.spec.js, e2e/specs/create/smoke-configure-linode.spec.js, e2e/specs/create/smoke-linode-with-tags.spec.js, yarn.lock
**Purpose**
This addressed some issues around getting information and elements from the user table, and updated some expected message text.
**To Test**
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e:modified`
=> M3 1763 nick suite repair 0.38.0

src/components/Placeholder/Placeholder.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Add pricing details to backup placeholder with a fallback based on the types data we have for current linode
=> M3-1655: add price details to backup placeholder

src/features/Support/SupportTickets/SupportTicketDrawer.tsx
My primary focus here was properly disabling the 'Open Ticket' button on submit. This required importing a different button component. Please let me know if I neglected any required prop edits.
=> M3-1275 Add submitting state to disable create ticket button onclick

e2e/config/custom-commands.js, e2e/pageobjects/account/permissions.page.js, e2e/pageobjects/account/user-detail.page.js, e2e/pageobjects/account/users.page.js, e2e/pageobjects/configure-image.page.js, e2e/pageobjects/configure-stackscript.page.js, e2e/pageobjects/linode-detail/linode-detail-backups.page.js, e2e/pageobjects/linode-detail/linode-detail-networking.page.js, e2e/pageobjects/linode-detail/linode-detail-resize.page.js, e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/list-domains.page.js, e2e/pageobjects/page.js, e2e/pageobjects/profile.js, e2e/pageobjects/profile/auth.page.js, e2e/pageobjects/profile/display.page.js, e2e/pageobjects/profile/ssh-keys.page.js, e2e/pageobjects/support/tickets.page.js, e2e/pageobjects/volumes.page.js, e2e/setup/setup.js, e2e/specs/profile/update-display.spec.js, e2e/utils/common.js
**Purpose**
Added a test for updating email address and timezone in the profile page, centralized repeated css selectors.
**To Test**
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e --spec=e2e/specs/profile/update-display.spec.js`
=> M3 933 user update email

src/components/TagsPanel/TagsPanel.tsx, src/components/TagsPanel/TagsPanelItem.tsx, src/components/TagsPanel/index.ts, src/features/Domains/DomainDetail.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx, src/services/domains/domains.schema.ts, src/types/Domain.ts
- Moved tags panel to a separate component
- Added tags panel to Domains
=> M3-1435: Add tags panel to domain details

src/features/Support/ExpandableTicketPanel.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
For M3-1648, adds last updated by user and last update time as caption below the ticket status header.
=> Updates ticket status header

scripts/e2e-modified.sh, src/components/Breadcrumb/Breadcrumb.spec.js
**Purpose**
Added functional test for breadcrumb component.
**To Test**
`yarn storybook` new shell `yarn storybook:e2e --story Breadcrumb`
=> Completed functional test for breadcrumb component M3-1540

src/features/TopMenu/SearchBar/SearchBar.tsx
- Update domain search function to include tags match
=> M3-1436: add domain search by tags

package.json, src/components/TagsPanel/TagsPanel.stories.tsx, yarn.lock
- Add TagsPanel story
- Add `axios-mock-adapter` to mock API calls in stories
=> M3-1435: add tagsPanel story

src/components/TagsInput/TagsInput.test.tsx
Adds unit tests for TagsInput component
=>  M3-1433: Add TagsInput tests

src/components/ShowMore/ShowMore.tsx, src/components/Tags/Tags.tsx, src/components/Tags/index.ts, src/features/Domains/DomainsLanding.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodesViewWrapper.tsx
- Move tags to a separate component
- Fix bug with viewing full tags list on Linode
- Add tags to Domain list view
=> M3-1434: add tags to Domains list view

src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx
change: Order payment/invoices by date descending.
=> M3-1819 Order payment/invoices by date descending.

src/features/TopMenu/SearchBar/SearchBar.tsx, src/features/TopMenu/UserEventsMenu/UserEventsButton.tsx, src/features/TopMenu/UserMenu/UserMenu.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsButton.tsx, src/features/linodes/LinodesDetail/HeaderSections/TagsPanel.tsx
Hiding enhanced select indicators in the instance of search bar.
=> M3-1831 Regression: remove drop down arrow from main search field

src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowLoaded.tsx, src/features/linodes/LinodesLanding/LinodesViewWrapper.tsx
PR was merged before i had a chance to add this.
=> M3-1658 fix icon color, tooltip, link hierarchy and hover styles

src/components/CircleProgress/CircleProgress.tsx
loader when loading/rebooting a linode ion the card view had a regression. this fixes it
=> M3-1845 fix to linodeCard loader

e2e/constants.js, e2e/pageobjects/domain-detail/detail.page.js, e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/linode-detail/linode-detail.page.js, e2e/pageobjects/list-domains.page.js, e2e/pageobjects/nodebalancer-detail/configurations.page.js, e2e/pageobjects/nodebalancer-detail/details.page.js, e2e/pageobjects/page.js, e2e/specs/account/restricted-users.spec.js, e2e/specs/linodes/detail/create-volumes.spec.js, src/components/AddNewLink/AddNewLink.tsx
* Updates nodebalancers, domains and linodes to support the new breadcrumb component
* Added breadcrumbs to the base page class
* Updates routes to account pages
```
yarn e2e --dir account && yarn e2e --dir domains && yarn e2e --dir nodebalancers
```
=> M3-1839 - Update tests to handle breadcrumb component

package.json, src/components/CopyTooltip/CopyTooltip.tsx, src/components/EditableText/EditableText.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.test.tsx, yarn.lock
Upgrade @material-ui/icons to latest release.
=> M3-1858 Upgrade @material-ui/icon@^3.0.1

src/components/Tags/Tags.test.tsx, src/components/Tags/Tags.tsx
Adds unit tests for Tags component
=> M3-1434: add tests for Tags list component

src/components/TagsInput/TagsInput.spec.js, src/components/TagsPanel/TagsPanel.spec.js, src/components/TagsPanel/TagsPanel.tsx
**To Test**
`yarn storybook` new shell `yarn storybook:e2e --story TagsPanel && yarn storybook:e2e --story TagsInput`
=> M3-1821 Storybook tests for tags input and tag panel component 

src/features/NodeBalancers/NodeBalancerCreate.tsx, src/types/NodeBalancer.ts
Added tags to NodeBalancer form.
Tags are sent to the server but not saved yet because API is not ready yet.
=> M3-1450: add tags to NodeBalancer form

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/types/NodeBalancer.ts
Adds TagsPanel to nodeBalancer details view with async tags update
=> M3-1452: add TagsPanel to nodeBalancer details view

src/WelcomeBanner.tsx
To test/view, please clear cookies/cache. It should now be centered and similar in width to production.
=> M3-1899 Welcome to New Cloud Manager modal is misaligned

e2e/config/custom-commands.js, e2e/config/wdio.conf.js, e2e/pageobjects/linode-detail/linode-detail-backups.page.js, e2e/pageobjects/list-linodes.js, e2e/pageobjects/page.js, e2e/setup/setup.js, e2e/specs/create/smoke-linode-with-tags.spec.js, e2e/specs/linodes/detail/backups-create.spec.js, e2e/utils/common.js, e2e/utils/config-utils.js, scripts/e2e-modified.sh, src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
**Purpose**
Added test for taking a snapshot of a linode, verifying that backups can be deployed to a new linode,
and verification around the restore to existing drawer.
**To Test**
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e:modified`
=> M3-570 create from backups test

src/__data__/volumes.ts, src/features/TopMenu/SearchBar/SearchBar.test.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx, src/types/Volumes.ts
Updates logic for volume filtering in search to consider tags too
=>  M3-1439: add Volumes search by tag

package.json, src/App.tsx, src/__data__/reactRouterProps.ts, src/__data__/searchResults.ts, src/components/EnhancedSelect/Select.tsx, src/features/Help/Panels/SearchItem.tsx, src/features/Search/HiddenResults.test.tsx, src/features/Search/HiddenResults.tsx, src/features/Search/ResultGroup.test.tsx, src/features/Search/ResultGroup.tsx, src/features/Search/ResultRow.test.tsx, src/features/Search/ResultRow.tsx, src/features/Search/SearchLanding.test.tsx, src/features/Search/SearchLanding.tsx, src/features/Search/index.tsx, src/features/Search/utils.test.ts, src/features/Search/utils.ts, src/features/TopMenu/SearchBar/SearchBar.test.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx, src/features/TopMenu/SearchBar/SearchSuggestion.tsx, src/features/TopMenu/SearchBar/index.tsx, src/themeFactory.ts, src/themes.ts, src/utilities/getAll.ts, yarn.lock
Merges develop (which now includes search landing PR), and moves Russ's logic/refactors into the new search/utils.ts file.
=> Merge search landing

src/themeFactory.ts, src/themes.ts
Small adjustment for disabled muiFormLabel state.
=> M3-1921 Labeling is getting wrong colors if in disabled state

src/components/Notice/Notice.tsx, src/components/SelectionCard/SelectionCard.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/StackScripts/LandingPanel/Table/LabelCell.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx
These are residuals from the mobile typography update.
=> M3-1927 updating caption variants to body text variant

src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/themeFactory.ts
=> Fix radio button styles and add margin to text on 'create a volume' form

src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/StackScriptsLanding.test.tsx, src/features/StackScripts/StackScriptsLanding.tsx
Revert Paginated StackScripts back to dumb lazy loading :(
=> Revert Paginate StackScript Landing

src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, src/services/linodes/linode.schema.ts
For whatever reason I limited CPU threshold to 2 characters...
=> M3-1890 Remove 2 character limit on CPU alert threshold.

src/components/LabelAndTagsPanel/LabelAndTagsPanel.test.tsx, src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx
Some basic test coverage for LabelAndTagsPanel
=> M3-1433: add tests for LabelAndTagsPanel

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
Correct regression for enqueuing a snackbar notification.
=> M3-1984 Remove sendToast for enqueSnacback

src/eventMessageGenerator.ts, src/features/TopMenu/UserEventsMenu/UserEventsList.tsx, src/types/index.ts
change: Added event messages for SSH key addition and deletion.
change: Added user event menu click handler for SSH key addition and deletion.
=> M3-1253 Add SSH key event messages

src/features/Volumes/VolumesLanding.tsx
Switch "Region" and "Attached to" columns for Volumes
=> M3-1995: switch volume columns

src/components/CopyTooltip/CopyTooltip.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx
Updating copy icon component color/hover for consistency in all usage areas.
=> M3-1997 Copy Icon Consistency

src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
Very small styling change that was buggin' me
=> M3-1999 better padding for dashboard table cells

src/components/PrimaryNav/PrimaryNav.tsx
=> M3-1936 reduce primary nav items padding under medium breakpoint

src/components/TagsPanel/TagsPanel.tsx
To reproduce:
1. Navigate to LinodesDetail page
2. Create Tag
3. Attempt to create tag with the same name
4. Observe misaligned error message
Error for tags should now be vertically aligned, along with improved styling for dark theme.
=> M3-2007 Update inline tag error

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.tsx
Styling for stats and units data under Linode Detail page. See ticket for more details.
=> M3-2002 Styling for Stats/Units

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx
Add "Boot This Config" action to the kebab menu for the configs list view
1. Create a config
2. Open the kebab menu and choose "boot this config"
3. Reboot progress bar should appear 
4. Block requests and try again; should receive a toast.
=> M3-2028 Update: Add boot action to kebab menu in LinodeConfigs

src/components/AccessPanel/AccessPanel.stories.tsx, src/components/AccessPanel/AccessPanel.tsx, src/components/EnhancedSelect/Select.tsx, src/components/ModeSelect/ModeSelect.test.tsx, src/components/ModeSelect/ModeSelect.tsx, src/components/ModeSelect/index.tsx, src/features/Images/ImageSelect.test.tsx, src/features/Images/ImageSelect.tsx, src/features/Images/index.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx, src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx, src/features/linodes/userSSHKeyHoc.ts, src/services/linodes/linode.schema.ts
Includes M3-1489 (deploy disk from image) and M3-2028 (add action to kebab menu). Final review before merging to develop.
=> M3-1489 deploy image to disk (#4206)

src/components/ScriptCode/ScriptCode.stories.tsx, src/components/StackScript/StackScript.stories.tsx
Adds stories for ScriptCode and StackScript components that are related to creating a unified StackScript component
- Add ScriptCode component story
- Add StackScript component story
=>  M3-880: add stories for ScriptCode and StackScript components

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/TotalTraffic.tsx
Update to Total Traffic section for Stats & Graphs
=> M3-2033 Styling for "Total Traffic" stats

src/components/PrimaryNav/PrimaryNav.tsx
We need the condensed navigation at all breakpoints now in order to allow more room for upcoming projects as well as strenghtening our effort to increase information density
=> M3-1936 Layout Update - Condense primary nav at all breakpoints

src/components/SelectionRow/SelectionRow.tsx, src/themes.ts
StackScripts tags should not be clickable. This PR switches them to reg chips
- Bug fix
=> M3-2037 Fix clickable StackScripts tags

src/components/DrawerContent/DrawerContent.test.tsx, src/features/StackScripts/StackScriptDrawer.test.tsx, src/features/StackScripts/StackScriptDrawer.tsx
Simple tests for DrawerContent and StackScriptDrawer components
- add tests for DrawerContent component
- add tests for StackScriptDrawer component
=> M3-1704: add test coverage for stackScripts drawer

src/features/linodes/LinodesLanding/LinodesLanding.tsx
Change "group by tags" to opt in.
=> Default group by tag to off.

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/userSSHKeyHoc.ts
Notify the user the Linode is being created after successfully creating from an image, backup, clone, or stackscript.
- feature
Create a Linode form image, backup, clone, and stackscript to verify functionality.
=> feature: Display notification on Linode creation.

src/features/Users/UserProfile.tsx, src/features/Users/UsersLanding.tsx
Last push to commit didn't update the messages.
=> M3-1634 (updated message)

src/features/Account/ImportGroupsAsTags.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.test.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.tsx, src/features/TagImport/TagImportDrawer.tsx
Updated copy based on AC.
- update
=> Update copy for Display Group Import

src/components/PaginationControls/PageButton.tsx, src/features/Account/ImportGroupsAsTags.tsx, src/features/Dashboard/Dashboard.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.test.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.tsx, src/features/TagImport/DisplayGroupList.tsx, src/features/TagImport/TagImportDrawer.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/themeFactory.ts, src/themes.ts, src/utilities/storage.ts
Styling updates for group by tag feature- this affects grid and list views, dashboard card, and the drawer.
=> Improved Features for Viewing By Tags- Styling Update

src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx, src/features/Profile/AuthenticationSettings/TrustedDevices.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/services/profile/index.ts, src/services/profile/profile.ts, src/types/Profile.ts
List Trusted Devices
Navigate to profile/auth
Test on dev environment
Humanized datestamp coming in subsequent PR
=> M3-2003 Add List of Trusted Devices

e2e/config/custom-commands.js, e2e/pageobjects/configure-linode.js, e2e/pageobjects/list-stackscripts.page.js, e2e/pageobjects/stackscripts/stackscript-detail.page.js, e2e/setup/setup.js, e2e/specs/create/create-from-stackscript-with-tags.spec.js, e2e/specs/create/create-linode-from-stackscript.spec.js, e2e/specs/globalsettings/auto-backup-enrollment.spec.js, e2e/specs/stackscripts/stackscript-detail.spec.js, e2e/utils/common.js, src/components/StackScript/StackScript.tsx, src/features/StackScripts/StackScriptsDetail.tsx
Added a new test suite for StackScript detail page and detail drawer.
To test: `yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e --spec=e2e/specs/stackscripts/stackscript-detail.spec.js`
=> Added tests for StackScript detail page and drawer

src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/features/Users/CreateUserDrawer.tsx, src/features/Users/UserPermissions.tsx, src/features/Users/UsersLanding.tsx
Update copy around text regarding restricted/unrestricted users
=> M3-1059 Update Copy Around Restricted Users

src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
Updated the margins between groups for list and grid view.
=> For release: M3-1770 Style Updates for Group by Tag 

src/features/Profile/APITokens/APITokenTable.test.ts, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx, src/utilities/formatDate.test.ts, src/utilities/formatDate.ts
Add additional logic to `formatDate()` so that it can correctly humanize times in the future
* `Math.abs` logic to account for future times (thanks @Jskobos)
* Testing for future times
* API Token Table now uses `<DateTimeDisplay />`
=> M3-2076 Update Humanize Future Times

src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- Add StackScript details to checkout panel
=> M3-2097: add StackScript title to checkout panel

src/components/SelectionRow/SelectionRow.stories.tsx, src/components/SelectionRow/index.ts
Adding date component with a StackScriptDrawer broke SelectionRow story because it requires Redux store to get the Timezone. This PR adds missing dependency.
- Fix SelectionRow component story
=> M3-1704: Fix SelectionRow component story

src/components/StackScript/StackScript.test.tsx, src/components/StackScript/StackScript.tsx, src/features/StackScripts/StackScriptsLanding.tsx
Source Images details from Redux on StackScripts page.
- Load `/stackscripts`
- Verify basic functionality
- Verify no additional requests made to `/images`
=> M3-2111 M3-2125 Update StackScriptsLanding to source images data from Redux.

src/components/TableRow/TableRow.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Recreates Kayla's earlier PR, since I botched that feature branch.
=> M3-2100 Fix clickable rows

src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx, src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.test.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx
Update StackScriptUpdate to source images data from Redux
- Have an existing StackScript.
- Update said stackscript.
- Verify public images exist in dropdown.
- Verify no additional images request made.
=> M3-2127 Update StackScriptUpdate to source images data from Redux

src/features/Search/SearchLanding.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx, src/utilities/getAll.ts
Use Reduxed images for the search bar and search landing page
=> M3-2126 images search bar

src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
- Add linode icon to Linodes list view table
=>  M3-2055: Add icon to Linodes list view

src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/features/Billing/BillingPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx, src/utilities/isCreditCardExpired.test.ts, src/utilities/isCreditCardExpired.ts
Credit card validation logic was off. Added tests and dependency injection for testing.
See tests.
=> bug: M3-2175 Expired credit cards not being rejected.

e2e/pageobjects/account/invoice.page.js, src/assets/logo/logo-text.svg, src/components/Table/Table.tsx, src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, src/features/Billing/InvoiceDetail/InvoiceTable.tsx, src/features/Billing/InvoiceDetail/PrintInvoice.tsx, src/index.css, src/index.tsx, src/store/ApplicationState.d.ts, src/store/reducers/resources/account.ts, src/store/reducers/resources/index.ts
re: https://github.com/linode/manager/pull/4279
Provide a printable invoice. Hey, they could even print it do PDF!
- Feature
=> M3-929 again

src/components/CircleProgress/CircleProgress.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
=> M3-1818  Update dashboard transfer card to new design

src/components/PaginationControls/PageButton.tsx, src/components/PaginationControls/PageNumbers.styles.ts, src/components/PaginationControls/PageNumbers.tsx, src/components/PaginationControls/PaginationControls.test.tsx, src/components/PaginationControls/PaginationControls.tsx
=> M3-2178 Update pagination styling

src/features/linodes/LinodesLanding/ToggleBox.tsx
Decrease the border color prominence on the List/Grid view.
=> M3-2014 Decrease the border on the List/Grid view

src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/ModeSelection.tsx
View this change from the linode details page under the `volumes` tab.
=> M3-1980 Update Radio Input Label text size on 'Create Volume' drawer

src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts, src/features/linodes/LinodesLanding/TableWrapper.tsx, src/themeFactory.ts, src/themes.ts
Change to remove a border on the side of the linode listing table that was coming from a `Paper` component. 
=> M3-2196 Display by group styling bug

src/index.css
Explicitly declaring background color on table cells for printer compatibility.
=> M3-2199 Print Invoice: dark mode captured in description

src/utilities/getAll.ts
Band-aid fix for a circular dependency bug that was causing any interaction with the search bar or search landing page to crash.
=> M3-2198 Fix search bar/search landing bug

src/components/Drawer/Drawer.tsx, src/components/StackScript/StackScript.tsx, src/features/StackScripts/StackScriptsDetail.tsx
Fixing a bad selector, creating a new one that is isolated to StackScripts so the StackScript drawer remains unaffected (along with other drawers)
=> M3-2048 Style StackScript details drawer Part2

src/components/ConfirmationDialog/ConfirmationDialog.tsx, src/components/Pagey/Pagey.ts, src/components/ToggleState/ToggleState.ts, src/components/ToggleState/index.ts, src/components/withLoadingAndError/index.ts, src/components/withLoadingAndError/withLoadingAndError.test.tsx, src/components/withLoadingAndError/withLoadingAndError.ts, src/features/Profile/APITokens/APITokenTable.test.ts, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx, src/features/Profile/AuthenticationSettings/TrustedDevices.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesDialog.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/DisableTwoFactorDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/ScratchCodeDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/services/profile/index.ts, src/services/profile/profile.ts, src/services/profile/twoFactor.ts, src/services/profile/twofactor.schema.ts, src/types/Profile.ts, src/utilities/formatDate.test.ts, src/utilities/formatDate.ts
Add List of Trusted Devices, ability to delete them.
Also adds humanizable future times (i.e. "in a month" or "in a year")
Also adds scratch code visibility after 2FA is enabled
Closes:
M3-2003 - List Trusted Device
M3-2005 - Delete Trusted Device
M3-2076 - Humanizable Future Times
M3-2093 - Display scratch code after enabling 2FA
=> Add: Trusted Devices

src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
'Create from StackScript' CTA in the create flow is now a button, and 'Download PDF' under 'Recent Payments' is now a link.
=> (For Release) M3-2222 StackScript selection and PDF buttons updates

src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
Replace 'bandwidth' with 'transfer' in the dashboard transfer card.
=> M3-2233 remove bandwidth

src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
Updating button to secondary styling.
=> M3-2222 Choose Another StackScript button Update

src/features/Users/CreateUserDrawer.tsx, src/features/Users/UserPermissions.tsx
Update copy and logic of on/off things
=> M3-2332 Update Users Copy

package.json, src/features/StackScripts/Partials/StackScriptTableHead.tsx, yarn.lock
Update TypeScript. Ensure your IDE is using the version supplied by node_modules.
`yarn tsc --noEmit` should pass without issue. Builds should succeed.
=> M3-2236 Update typescript

src/features/Account/AccountLanding.tsx
Change the title of the `Global Settings` tab to `Settings`.
I didn't change the actual component name, just the title.
=> M3-2091 Change: Global Settings title to Settings

src/components/TabbedPanel/TabbedPanel.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Display dedicated CPU plans in the plan selection panel. Covers creation and resize.
Features
Create and resize using new plans.
=> M3-2218 Include dedicated CPU in plan selection

src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
=> Disable copy for each plan class.

src/features/linodes/LinodesLanding/LinodeRow/LinodeRowTagCell.tsx
Small styling fixes to center both the tag number and the tooltip
=> M3-2261 Update: tag column styling adjustments

src/components/StatusIndicator/StatusIndicator.tsx, src/components/StatusIndicator/index.ts, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/Domains/DomainTableRow.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/ListGroupedDomains.tsx, src/features/Volumes/VolumesLanding.tsx
- add status indicator for Domains listing pages
- add status indicator for Volumes listing pages
=> M3-2168, M3-2170: add status indicator for entities pages

src/features/Profile/APITokens/APITokenTable.tsx
- remove 'type' column from Access Tokens tables
=> M3-2208: remove 'type' column from Access Tokens tables

src/features/Profile/Profile.tsx
- Change tabs order for profile page
=> M3-2266: reorder profile tabs

e2e/pageobjects/profile.js, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/Profile/OAuthClients/OAuthFormDrawer.tsx, src/features/Profile/Profile.tsx
- change My Apps text to OAuth Apps
=> M3-2209: rename My Apps to OAuth Apps

src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
Tightening panel to increase info density and layout at all breakpoints
=> M3-2272 Update: cleanup layout of dashboard transfer pool panel

src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx, src/themeFactory.ts, src/themes.ts
Layout was not optimal and we had a lot of whitespace. I rearranged the items on the pane to address that.
Test at /linodes/[id]/settings in the notification threshold panel
=> M3-2260 Update: Cleanup notification threshold pane

src/features/Profile/APITokens/APITokens.tsx
- change apps to Third Party Access Tokens
=> M3-2210: rename apps to Third Party Access Tokens

src/components/CheckoutBar/CheckoutBar.tsx
Made the button full width only when in the sidebar
- Bug fix
=> M3-2270 Fix width of create button (checkout sidebar)

src/features/Users/UserPermissions.tsx
- Bug fix
/account/users/[user_name]/permissions
=> M3-2275 fix missing typography on user permissions

src/components/Button/Button.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/themeFactory.ts
Another regression from the MUI update. Cancel buttons were sized/styled improperly.
- Bug fix
There is also a quick fix in there to resize a cell size on linode list view
=> M3-2277 fix cancel buttons sizes

src/features/Profile/DisplaySettings/TimezoneForm.tsx, src/store/profile/profile.reducer.ts
Fixes a bug where Profile Display Settings would disappear upon updating display settings.
- This was caused by the profile reducer incorrectly accessing data from the Redux action. 
- Also added typing to the Action and fixed a spelling error while I was there.
=> M3-2282 Fix: Update timezone error

src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskActionMenu.tsx
Improves user experience by adding notifications regarding disabled actions
- Add tooltip for disabled actions for disks
=> M3-1431: add tooltip for disabled actions for disks

src/components/EditableText/EditableText.tsx, src/components/EnhancedSelect/Select.tsx, src/components/PasswordInput/StrengthIndicator.tsx, src/features/Domains/DomainTableRow.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Users/UsersLanding.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx, src/index.css, src/themeFactory.ts
Going through updates and new features to achieve more consistency between Chrome, FF, Safari and Edge
Most of these changes are very small and target consistency. They should not affect chrome much as it is the default testing browser. Most of the changes improve the experience for safari
=> M3-2279 Cross browser audit and fixes

src/components/StatusIndicator/StatusIndicator.tsx, src/components/StatusIndicator/index.ts, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/Volumes/VolumesLanding.tsx
- remove volumes status indicator
=> M3-2168: remove volumes status indicator

src/themeFactory.ts
The screen shot of the toggle provided is that of the root account user, for which the user permissions toggle should be completely disabled because that user required full access. The toggle matches the styling of all other toggles when editing the permissions of a user other.
- Bug fix
=> M3-2283 fix disabled switch colors for both themes

src/components/PaginationControls/PageNumbers.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainsTableWrapper.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/TableWrapper.tsx
Tables have been added an "arial-label" that should read "aria-label"
- Bug fix
thank @johnwcallahan for pointing this out
=> M3-2296 fix incorrect arial-label spelling

src/features/Profile/APITokens/APITokenTable.test.ts, src/features/Profile/APITokens/APITokenTable.tsx, src/services/profile/appTokens.ts
- remove linode apps from the apps list
=> M3-2207: remove linode apps from the apps list

src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
On the Dashboard, the "Regions" column wasn't lining up with the Regions columns for Volumes and NodeBalancers.
=> M3-2303 "Regions" cell alignment on Linodes Dashboard Card

config/webpack.config.prod.js
Expose `REACT_APP` .env variables in the webpack production build.
=> Update Webpack to expose REACT_APP variables

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.tsx
- Add legend to Node Balancer graphs
Doubled border will be removed with https://github.com/linode/manager/pull/4446
=> M3-2307: Add legend to Node Balancer graphs

src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx
The initial value is set as the maximum size available.
The Prettier formatting is handled in the first 2 commits. Meaningful changes are in 
5c59ddc.  
1) Have a Linode without a disk.
2) Go to Linode Details –> Settings –> Advanced Configurations.
3) Click "Add a Disk".
4) **Observe:** The value of the "Size" field should be equal to the "Maximum Size" (as seen in the helper text below).
5) Experiment with adding multiple different sized disks.
=> M3-2269 Change: Initial size when creating a disk.

src/features/Support/SupportTickets/SupportTicketDrawer.test.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/utilities/getVersionString.test.ts, src/utilities/getVersionString.ts
This PR makes it such that when a user creates a support ticket, the version is automatically appended to the description of the ticket.
1) Open the Network tab of Chrome Dev Tools.
2) Create a support ticket.
3) Find the `POST` request in Chrome Dev Tools.
4) **Observe:** you will see "\n\nCloud Manager Version: X.XX.X" appended to the `description` you provided.
5) Go to Support Ticket Landing.
6) Click on the Ticket that you just created.
7) **Observe:** you will see "\n\nCloud Manager Version: X.XX.X" at the bottom of the description.
=> M3-2306 Change: Support Ticket version tracking.

src/store/tagImportDrawer/index.ts
This PR fixes a regression that appeared during recent updates to the data layer. After successfully importing Display Groups, the CTA would _still be displayed_ on the Dashboard, even though there weren't any groups to import.
Previously, importing groups called `updateLinode` and `updateDomain` from the service library, which in turn updated the store.
Recently we removed the service library's dependency on the store.  **So, when you imported groups, the store wasn't being updated.**
This also means that Domains Details and Linodes Details weren't showing updated copies of the entities (with the new tags.) 
- Bug fix
1) Have Linodes and Domains with Display Groups without corresponding tags.
2) Make sure you clear the `hasImportedGroups` property from Local Storage.
3) From the …
=> M3-2333 Fix: Group CTA display on dashboard

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx
- Add link to port on NB listing page
- remove expansion panel from NB configuration page
=> M3-2308: update NB ports UX

src/features/Search/utils.test.ts, src/features/Search/utils.ts, src/features/Search/withStoreSearch.tsx, src/store/selectors/getSearchEntities.ts
- Add IP search for Linodes, NodeBalancers and Domains
=> M3-866: add IP as a search parameter

src/features/Backups/BackupsCTA.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/themeFactory.ts, src/themes.ts, src/utilities/storage.ts
The backups CTA on the /linodes landing page needs to be dismissible and persists in local storage. This PR does exactly that
=> M3-2309 Update Backups CTA to be dismissible

src/components/EnhancedSelect/EnhancedSelect.stories.tsx, src/components/EnhancedSelect/Select.tsx, src/components/EnhancedSelect/components/SelectPlaceholder.tsx, src/components/Select/Select.spec.js, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/TextField.stories.tsx, src/components/TextField.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/NodeBalancers/utils.ts, src/services/nodebalancers/configNodes.ts, src/services/nodebalancers/configs.ts, src/themeFactory.ts, src/themes.ts, src/types/NodeBalancer.ts
- Add nb node status indicator
- Tighten layout to match new design
=> M3-2186: update nb config layout

package.json, yarn.lock
Prevent circular dependencies from being committed. Current circular dependencies: 
1) store/events/event.actions.ts > store/events/event.reducer.ts
2) store/events/event.reducer.ts > store/events/event.helpers.ts
3) features/Profile/AuthenticationSettings/TwoFactor/qrcode.react.d.ts
4) features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx > features/Volumes/VolumeDrawer/VolumeDrawer.tsx
5) features/Volumes/VolumeDrawer/VolumeDrawer.tsx > features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
6) features/linodes/LinodesCreate/LinodesCreate.tsx > features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
7) features/linodes/LinodesCreate/LinodesCreate.tsx > features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
8) …
=> M3-2324 - Testing add madge circular dependencies check to pre-commit

src/components/Select/Select.tsx, src/components/TextField.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
Make the select for the graphs less prominent by using the new small select prop.
/linodes/[id]/summary
=> M3-2329 Update graph select to be new small select

src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/features/Help/Panels/PopularPosts.tsx, src/features/Support/SupportTickets/TicketList.tsx, src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx
/linodes/[id]/settings > Advanced Configuration
=> M3-2336 Move Disk Storage Location on Advanced Configs to the right

src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/features/Help/Panels/PopularPosts.tsx, src/features/Support/SupportTickets/TicketList.tsx, src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx
This reverts commit c9a5d09d5255504836250e04bf70c34043582430.
This commit went into the wrong PR by mistake and needs a PR on its own
=> Revert "M3-2336 update underline links instances"

src/components/ExpansionPanel/ExpansionPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- Add node statuses to node config expansion panel
=> M3-2355: add node statuses to node config expansion panel

src/components/TableRow/TableRow.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/Volumes/VolumeTableRow.tsx, src/index.css, src/themeFactory.ts
In an effort to be more visually appealing and in line we want to remove all underlined text throughout the application
to review:
- breadcrumbs
- events dropdown menu
- help landing page
- secondary links in tableRows
=> M3-2336 Update underline links instances

src/components/BackupStatus/BackupStatus.tsx, src/components/BackupStatus/index.ts, src/containers/withMostRecentBackup.container.ts, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx
- Add backup status to Linode summary panel
=> M3-2319: add backup status to linode summary panel

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
=> M3-2186 Fix unknown status NodeBalancer chip color

src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
=> M3-2355: clean console log

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
- Fix SSL Certs and Private key updates
=> M3-2355: fix SSL Certs and Private key updates

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
- Fix SSL Certs and Private key updates
=> M3-2355: fix SSL Certs and Private key updates (#4486)

src/components/AccessPanel/AccessPanel.tsx, src/components/CheckoutBar/CheckoutBar.tsx, src/components/CreateLinodeDisabled/CreateLinodeDisabled.tsx, src/components/CreateLinodeDisabled/index.ts, src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/components/TagsInput/TagsInput.tsx, src/features/Profile/permissionsHelpers.ts, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx, src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/SelectImagePanel.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- Update UX for restricted users Linode create flow
=> M3-1696: add UX for restricted users Linode create flow

src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx
=> M3-2381 wrap long domain names on dashboard

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
=> M3-2366 fix https display for NB config panels

src/features/Volumes/VolumeDrawer/ConfigSelect.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/LabelField.tsx, src/features/Volumes/VolumeDrawer/LinodeSelect.test.tsx, src/features/Volumes/VolumeDrawer/LinodeSelect.tsx, src/features/Volumes/VolumeDrawer/RegionSelect.tsx, src/features/Volumes/VolumeDrawer/SizeField.tsx
- Fix restricted user experience when trying to create a new volume
=>  M3-1696: disable Create Volume form for users without permission

.travis.yml
=> Remove posting coveralls data

src/components/EntityIcon/EntityIcon.tsx, src/features/linodes/LinodesDetail/HeaderSections/LabelPowerAndConsolePanel.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/themeFactory.ts, src/themes.ts
This PR updates the powerLinode Button with the new colored icons. It also cleans up the styles and increases the visibility while making it less intrusive.
=> M3-2390 Add new icon to power button

src/features/Footer/Footer.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationListItem.tsx
Missed these in the previous iteration
=> M3-2407 Remove underline in footer links

src/features/Domains/DomainCreateDrawer.tsx
- Fix restricted user experience for adding new Domains
=> M3-1696: Configure grants restrictions for create Domains form

src/features/Domains/DomainRecordActionMenu.tsx, src/features/Domains/DomainRecords.tsx
- Fix maintaining of service name and protocol for SRV record drawer
=> M3-2000: fix maintaining of service name and protocol for SRV record

src/features/linodes/LinodesDetail/HeaderSections/NotificationsAndUpgradePanel.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx
- add link to resize page for upgrade notification
=> M3-2344: add link to resize page for upgrade notification

src/features/Images/ImageSelect.tsx, src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.test.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.tsx, src/features/StackScripts/StackScriptRowHelpers.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, src/utilities/imageToItem.test.ts, src/utilities/imageToItem.ts
Replace custom multi-select with React Select
- Updated ImageSelect to take extra props (`isMulti` and `helperText`)
- Removed a bunch of methods being used to filter and display images
- Fixed MUI and key errors
=> M3-2132 Update: StackScript image select

package.json, src/components/BackupStatus/BackupStatus.tsx, src/features/linodes/LinodesLanding/LinodesLanding.styles.ts, src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/types/index.ts, yarn.lock
This PR adds a an existing feature of classic to Cloud: The ability to download as CSV the list of Linodes
=> M3-2360 Add: CSV download link to Linodes List

src/features/Domains/DomainsLanding.tsx
we need to sort this alphabetically
=> M3-2404 Fix sorting on domain landing

src/__data__/nodeBalancers.ts, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/types/NodeBalancer.ts
- add NB port links to NB summary sidebar
=> M3-2361: add NB port links to NB summary sidebar

src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- Fix bug where user can call power on for Linode without an image
=> M3-2376, M3-2351: disable power on for linodes without image

src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/VolumeSelect.tsx
- fix grants for adding Volume to a Linode
=> M3-1696: fix grants for adding Volume to a Linode

src/components/MenuItem/MenuItem.tsx, src/features/Support/SupportTicketDetail/CloseTicketLink.tsx, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/features/TopMenu/UserEventsMenu/UserEventsMenu.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/themeFactory.ts
=> M3-2432 fix tooltip in power menu and menu drop down sizes

src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
=> M3-2416 fix power button alignment regression

src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Domains/DomainTableRow.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationListItem.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
on linodes landing and domains (landing and dashboard)
=> M3-2545 Fix small regression with new icons vertical alignment

src/components/CreateLinodeDisabled/CreateLinodeDisabled.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/NoticePanel.tsx
- add important state to restricted notices for better visibility
=> M3-1696: add important state to notices

src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, src/features/StackScripts/stackScriptUtils.ts
- fix account stackscripts loading for secondary users
=> M3-2419: enable account stackscripts for secondary users

src/features/Managed/ManagedLanding.tsx
Copy update to 'Linode Managed'. 
=> M3-1267 Managed - Copy should read Linode Managed

src/themeFactory.ts, src/themes.ts
In theme files, hex values should be lowercase, not upper. 
=> M3-2406 Apply convention for HEX values in theme files

src/features/Billing/PdfGenerator/PdfGenerator.ts
=> M3-2456: fix PDF generation failure

src/components/TagsPanel/TagsPanel.stories.tsx
Wrap TagsPanel story in SnackbarProvider
=> Fix TagsPanel Story

src/features/Volumes/VolumesLanding.tsx
We fixed a similar issue with Domains recently.
- Non breaking change ('update', 'change'
=> M3-2453 Change: Volume Labels Sorting

src/features/Support/SupportTickets/TicketList.tsx, src/features/Support/SupportTickets/TicketRow.test.tsx, src/features/Support/SupportTickets/TicketRow.tsx
Add a column to the support tickets table indicating who last updated the ticket.
Also refactored one of the the `renderSomething` methods into a separate component for better testing
=> M3-2437 Add updated-by column to support tickets

src/features/Support/SupportTickets/TicketRow.test.tsx
This was causing the linter to fail.
=> Fix imports on TicketRow.test.tsx

src/features/StackScripts/stackScriptUtils.ts, src/features/Support/SupportTickets/TicketRow.test.tsx, src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/index.tsx
=> add CA create Linode skeleton

src/features/Volumes/VolumeDrawer/VolumeSelect.tsx
- fix volume select filtering based on grants
=> M3-2433: filter volume select based on grants

src/components/TagsCell/Tags.tsx, src/components/TagsCell/TagsCell.tsx, src/components/TagsCell/index.ts, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx, src/features/Volumes/SortableVolumesTableHeader.tsx, src/features/Volumes/VolumeTableRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- add tags column to NBs and volumes
Also moved tags cell to a stand-alone component
=> M3-2367, M3-2368: add tags column to NBs and volumes

src/components/CreateLinodeDisabled/CreateLinodeDisabled.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/utilities/promiseToObservable.ts
I have a small problem thank u for ur understanding
=> OCD copy fixes

src/__data__/axios.ts, src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPConfirm.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx, src/services/linodes/linodeIPs.ts, src/utilities/errorUtils.test.ts, src/utilities/errorUtils.ts
Adds the ability to remove public IP Addresses
Did some refactoring to flatten state inside the LinodeNetworking componens
Use prod-test-003 and use Linode "has_many_pub_ips" and try deleting some IPs
=> Add: M3-2385 Ability to Remove Public IP Addresses

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
Adding helper text to NodeBalancers 'settings' and 'config' panels.
=> M3-918 Helper Text - NodeBalancers

src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/CALinodeCreateSubTabs.tsx
Fixes following bug
1. Click on My Images > My StackScripts
2. Click on One-Click
3. Crash - cannot read property 'render' of undefined
=> fix tabs render bug

src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/CALinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/types.ts
Recreating this PR to see if it can get through Travis.
=> CA: reset create state 2

src/features/linodes/LinodesCreate/CALinodeCreate.tsx
Add error state if issue loading images, linodes, or regions
=> CLAPPS Error States

src/features/Volumes/VolumeDrawer/LinodeSelect.tsx, src/features/Volumes/VolumeDrawer/RegionSelect.tsx, src/features/Volumes/VolumeDrawer/SizeField.tsx
Adding additional helper text for volumes creation drawer.
=> M3-916 Helper Text - Volumes

src/components/PasswordInput/PasswordInput.tsx
Updating password component with supportive language to detail what passwords should contain to meet strength requirements.
To view, use storybook or view under the 'create' flow.
=> M3-944 Add password requirements to the PasswordInputField

src/features/StackScripts/Partials/StackScriptTableHead.tsx, src/themes.ts
=> M3-2371 fix regression with stackscripts table headers

src/features/StackScripts/SelectStackScriptPanel/CASelectStackScriptPanel.tsx, src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Final panel (except Apps, which hasn't merged yet) to complete new layout.
Paginating StackScripts is on the todo list; not having this makes the UI for this tab really ugly.
=> CLAPPS: Add Community StackScripts panel

src/components/Select/Select.tsx
=> M3-2496 Fix regression with pagination dropdown

src/components/Pagey/Pagey.ts, src/components/Paginate.ts, src/features/linodes/LinodesLanding/DisplayLinodes.tsx, src/utilities/storage.ts
- Add storing page size configuration in local storage
=>  M3-2466: configure storing page size

src/features/linodes/LinodesDetail/maybeRenderError.tsx
Bad path when looking for errors
=> Suspended Error Typo

src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx, src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Remove the stacked Notices when UDFs have errors, and map each to the correct field.
=> CLAPPS Map UDF error fields

src/store/linodes/linodes.events.ts
Currently, after a successful migration, the "Migration Imminent" banner is not disappearing. This PR makes it so that we request notifications after a migration has finished or failed.
Use dev services and resize a Linode.
=> Fix: Request notifications after migration completion

src/store/linodes/linodes.events.ts
Re-opening this since https://github.com/linode/manager/pull/4626 was pointed to `develop`.
=> Request notifications after migration finished

src/features/Profile/APITokens/ObjectStorageDrawer.test.tsx, src/features/Profile/APITokens/ObjectStorageDrawer.tsx, src/features/Profile/APITokens/ObjectStorageKeys.tsx, src/services/profile/objectStorageKeys.schema.ts, src/services/profile/objectStorageKeys.ts
_Must be using dev services._
- New endpoint
- Send Label data with request
- Handle data in the format returned by the API
=> M3-000 Change: obj-storage updates

e2e/specs/profile/tokens.spec.js, e2e/utils/config-utils.js
Change test configs
This fixes two cases
1. Where the e2e tests would attempt to login and get a CSRF Error on the login screen, causing all subsequent tests to bomb because the test runner wouldn't attempt to relogin
2. E2E tests would fail because it was stuck on the Authorize 3rd party app page
Run `yarn e2e` and wait until you get the CSRF error. The test runner should attempt another login
=> M3-xxx Test Config Changes

src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
Applying pagination to 'clone from linode' flow.
On an account with many linodes, go to `Create New Linode/Clone from Existing` and observe pagination is now present instead of a long scrolling list.
=> M3-1444 Update Linode panel to accommodate accounts with many Linodes

src/__data__/account.ts, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/types/Account.ts
- Add uninvoiced balance display
=> M3-2337: add uninvoiced balance display

CHANGELOG.md, e2e/specs/profile/tokens.spec.js, e2e/utils/config-utils.js, package.json, src/components/RenderGuard.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/store/linodes/config/config.reducer.ts, src/store/linodes/disk/disk.reducer.ts, src/store/linodes/linodes.events.ts, src/store/store.helpers.ts
Sync master and develop branches
=> Merge Master into Develop

src/App.tsx, src/features/TopMenu/SearchBar/SearchBar.styles.ts, src/features/TopMenu/SearchBar/SearchBar.tsx, src/index.css, src/themeFactory.ts, src/themes.ts
We want to provide a better experience when searching the site through the main search and help the user focus on the drop-down options. In order to do that the following changes were made:
- Dim main content when drop down appears
- Increase size and contrast of dropShadow
- add rounded corners (shhhhhh) to help differentiate drop down from surrounding elements
Just search, yo
=> M3-2508 Dim main content when searching

e2e/pageobjects/stackscripts/stackscript-detail.page.js
=> fix distro typos in e2e tests

src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
Requested by a customer as documented in AHA-MGR-I-245
=> update delete confirmation to include Linode Label

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
- Add payment confirmation modal for card payments
=> M3-2475: add card payment confirmation modal

src/components/StackScript/StackScript.tsx
- fix compatible StackScripts images filtering
=>  M3-2475: fix compatible StackScripts images filtering

src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, src/features/Billing/PdfGenerator/PdfGenerator.ts, src/features/Footer/createMailto.ts
- Fix PDF exception logger
- Add report button to report PDF generation errors via email with error stack
=> M3-2535: fix logger, add report button

src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx
- update UI for restricted edit volumes form
=> M3-1696: update UI for restricted edit volumes form

src/features/linodes/LinodesCreate/SelectAppPanel.tsx
Create a stackscript with stackscript id instead of the cloud app id
=> Apps: Pass down correct ID to App Select Panel

public/assets/Rust.svg
=> CLAPPS: Update Rust icon

src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx, src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx, src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx, src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx
- Add permissions check for update Volume flows
- Add disabled state to Linodes select
=> M3-1696: update volume permissions

package.json, scripts/pre-commit.sh, yarn.lock
Update our pre-commit hook to only run tests related to changed files.
- Change a component in such a way as to break a test
- Try to commit the change
- Commit should fail, but only a few test files should run.
=> M3 Add find related tests to Jest config

src/components/EnhancedSelect/Select.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx
was "no options", changed to "no results"
=> M3-2506 update searchBar no results text

src/features/Backups/BackupsCTA.tsx
=> M3-2304 Backups CTA Copy Update

src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
Adding missing class to fix width issue.
=> Adding missing class to empty 'Clone Linode' container

src/WelcomeBanner.tsx
Adding close icon to welcome dialog, adding backdrop click-to-close.
=> M3-2526 iOS/Mobile Cloud Manager Welcome Screen 

src/components/Placeholder/Placeholder.tsx, src/features/Domains/DomainDrawer.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx, src/index.css, src/themeFactory.ts
This PR updates title, descritpions and links for the following landing pages:
- /linodes
- /images
- /domains
Test with **prod-test-002** which has no entities
=> M3-2311 Update empty landings pages placeholders

src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx, src/utilities/getAPIErrorFor.ts
Currently we don't have an error state for Linode label update and it stuck in loading state. This fix adds generic error state and fixes loader.
- Fix Linode label update error
=> M3-1696: Fix Linode label update error

src/features/NodeBalancers/NodeBalancerCreate.tsx
Previously
1. Navigate to NB Create flow
2. Fill out fields
3. Turn on request blocking
4. Submit and observe the crash
Now that doesn't happen
=> M3-2392 Fix NB Create Error

src/features/TheApplicationIsOnFire.tsx
so that text display properly in dark mode
=> M3-2568 Fix missing typography for crash message

e2e/config/wdio.conf.js, e2e/pageobjects/page.js, e2e/specs/profile/tokens.spec.js, src/components/ActionMenu/ActionMenu.tsx, src/components/PrimaryNav/PrimaryNav.tsx
I tried to fix the PAT token test, but then @patthiel helped me.
3. `yarn e2e --file e2e/specs/profile/tokens.spec.js --browser=headlessChrome`
=> Fix PAT Token Test

e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js, e2e/specs/linodes/detail/rebuild.spec.js, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildDialog.tsx
Fixes Rebuild E2e Tests
To Test:
`yarn && yarn start`
`yarn e2e --file e2e/specs/linodes/detail/rebuild.spec.js --browser=headlessChrome`
=> Rebuild E2E Test Maintenance 

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/list-domains.page.js, e2e/pageobjects/page.js, e2e/specs/domains/smoke-list-domains.spec.js, e2e/specs/linodes/detail/create-volumes.spec.js, src/components/TagsCell/TagsCell.tsx
`yarn e2e --spec=e2e/specs/linodes/detail/create-volumes.spec.js`
`yarn e2e --spec=e2e/specs/domains/smoke-list-domains.spec.js`
(Or run both at once, just comma-separate the files)
=> Fix Volumes and Domains tests

e2e/specs/linodes/detail/resize.spec.js
Fixes resize toast test - the toast message has changed
`yarn && yarn start`
`yarn e2e --spec=e2e/specs/linodes/detail/resize.spec.js --browser=headlessChrome`
=> Resize Toast Test

e2e/specs/profile/update-display.spec.js
yarn e2e --file e2e/specs/profile/update-display.spec.js
=> M3-2569 fix time-zone test

src/__data__/images.ts, src/features/linodes/LinodesCreate/TabbedContent/formUtilities.test.ts, src/features/linodes/LinodesCreate/TabbedContent/formUtilities.ts
Adds unit tests for formUtilities.ts file
=> [Cloud Apps] Unit Testing

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Pretty simple - just spreading props for the sake of saving some line numbers
=> [Cloud Apps] Spread Props and State

src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
Refactor smoke test to not rely on HOC display names and instead data-qa attributes
=> Refactor Smoke Test

src/index.tsx
Fix React Router for Lish rendering
=> Fix: Fix Lish React Router Route

src/store/linodes/linodes.events.ts, src/types/Linode.ts
- Fix restore process finished event handling
=> M3-2593: fix restore process finished event handling

src/components/PrimaryNav/PrimaryNav.tsx
=> M3-2623 Fix settings icon placement

e2e/config/wdio.conf.js
* forgot to add this to the mongodb PR
[x] - Bug fix ('fix', 'repair', 'bug')
cc. @benschmaus
=> fix CRED_STORE_MODE env var handling

src/components/Button/Button.tsx, src/components/Button/button.stories.tsx
Destructive buttons would not show a visual disabled state when disabled
=> M3-2627 Fix styling for disabled destructive buttons

src/constants.ts
Temporary fix for development build.
=> Temporary obj environment fix

src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx, src/features/StackScripts/StackScriptsDetail.tsx, src/features/StackScripts/stackScriptUtils.ts, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectAppPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/utilities/queryParams.ts
Adds appID query param to the create flow to allow for URLs such as
http://localhost:3000/linodes/create?type=One-Click&appID=3
This also refactors the logic a little bit to move the responsibility of updating state to the child elements, rather than the CreateContainer
=> Add: M3-2625 App ID Query Param

src/__data__/ExtendedType.ts, src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx, src/features/linodes/LinodesCreate/utilities.test.ts, src/features/linodes/LinodesCreate/utilities.ts, src/features/linodes/presentation.ts
Adds unit tests for _Create Linode_ utilities
=> [Cloud Apps] More Unit Tests

src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/utilities/promiseToObservable.ts
Our inherited error handling from pre-OCA was resulting in strange and inconsistent behavior. The general error is now handled by the SubTabs component.
=> M3-2632 Fix backups creation error display

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Someone fixed all the TS linter warnings and I added new ones :joy: Please lmk if there's a better way to fix these 🤷‍♀️ 
=> Fixing linter errors i made

e2e/config/selenium-config.js, e2e/pageobjects/configure-linode.js, e2e/pageobjects/configure-stackscript.page.js, e2e/pageobjects/list-stackscripts.page.js, e2e/pageobjects/page.js, e2e/specs/create/create-linode-from-stackscript.spec.js, e2e/specs/stackscripts/list-stackscripts.spec.js, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Fixes StackScript E2E Tests
In three different terminals:
3. `yarn e2e --spec=e2e/specs/create/create-linode-from-stackscript.spec.js,e2e/specs/stackscripts/list-stackscripts.spec.js --browser=headlessChrome`
=> [TEST] StackScripts Test Maintenance

src/__data__/images.ts, src/features/Images/ImageRow.tsx, src/features/Images/ImageSelect.test.tsx, src/features/Images/ImagesLanding.tsx, src/types/Image.ts
https://linode-internal.ideas.aha.io/ideas/MGR-I-202
This aha has quite a few votes. It ended up being a bigger change than I originally thought due to the Type info and the tests that rely on that Type
=> Add image expiry date to Image table

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Adding same drop shadow treatment to create menu as the events and notifications dropdowns.
=> M3-2609 Adding Drop Shadow to Create Menu

e2e/specs/domains/smoke-list-domains.spec.js, src/features/Domains/DomainActionMenu.tsx
Updating delete action text under the domains actions menu.
=> M3-2619 Domains change Remove to Delete in the kebob

e2e/pageobjects/configure-linode.js, e2e/specs/create/clone-from-existing-linode.spec.js
Fix _Clone from Existing_ Tests
3. `yarn e2e --spec=e2e/specs/create/clone-from-existing-linode.spec.js --browser=headlessChrome`
=> [TEST] M3-2647 Clone From Existing Tests

PULL_REQUEST_TEMPLATE.md, e2e/pageobjects/configure-stackscript.page.js, e2e/pageobjects/list-linodes.js, e2e/pageobjects/list-stackscripts.page.js, e2e/specs/create/smoke-linode-with-tags.spec.js, e2e/specs/stackscripts/list-stackscripts.spec.js, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowLoading.tsx
Fixes Linode Detail Tests and StackScript tests
3. `yarn e2e --spec=e2e/specs/stackscripts/smoke-configure-stackscript.spec.js,spec=e2e/specs/create/smoke-linode-with-tags.spec.js,e2e/specs/stackscripts/list-stackscripts.spec.js,e2e/specs/stackscripts/edit-existing-stackscript.spec.js --browser=headlessChrome`
4. DO NOT USE parallel sessions for this PR
=> [TEST] M3-2644 Linode Detail and StackScript Tests

src/features/linodes/LinodesCreate/LinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
Fixes issue where all errors were appearing as "none" errors.
See screenshot below
None
=> [OCA] Fix General Error Handling

e2e/pageobjects/profile.js
Fix tests due to addition of object storage table
3. `yarn e2e --file e2e/specs/profile/tokens.spec.js`
The object storage add key needs its own test as well, but this just fixes existing series.
=> M3-2634-tests-rebuild Fix profile token tests

src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateSubTabs.tsx
Add a Beta tag to the One-Click tab
=> OCA add beta icon

e2e/pageobjects/configure-linode.js, e2e/pageobjects/list-stackscripts.page.js, e2e/specs/create/create-linode-from-stackscript.spec.js, e2e/specs/stackscripts/list-stackscripts.spec.js, src/features/StackScripts/stackScriptUtils.ts, src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Fix community search and change instances of "My StackScripts" -> "Account StackScripts"
3. `yarn e2e --spec=e2e/specs/create/create-linode-from-stackscript.spec.js,e2e/specs/stackscripts/list-stackscripts.spec.js --browser=headlessChrome`
=> [For Release] Fix Community Search

e2e/pageobjects/linode-detail/linode-detail-backups.page.js, e2e/specs/linodes/detail/backups-create.spec.js, e2e/specs/linodes/detail/rebuild.spec.js
Fixes flaky rebuild and backups E2E Tests
In 3 separate terminals:
3. `yarn e2e --spec=e2e/specs/linodes/detail/backups-create.spec.js,e2e/specs/linodes/detail/rebuild.spec.js --browser=headlessChrome`
The second test is going to take a bit of time keep in mind. Since creating a backup is a relatively long process.
=> [TEST] Rebuild and Backups Tests

src/constants.ts
This PR reverts the change made here: https://github.com/linode/manager/pull/4755
It should be merged after the environment issues are fixed.
=> Undo temporary Obj Storage env fix

src/components/TabbedPanel/TabbedPanel.tsx, src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateSubTabs.tsx, src/utilities/safeGetTabRender.test.tsx, src/utilities/safeGetTabRender.tsx
I think we've covered all cases that would cause this, but I just triggered it in a test and I'd really rather the app never crash because of this again.
=> Add safety hatch for tab rendering

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Updating box shadow for create menu to use variable for both themes.
=> FOR RELEASE: Using theme var for drop shadow on create menu

src/__data__/stackScripts.ts, src/components/StackScript/StackScript.test.tsx, src/features/StackScripts/stackScriptUtils.ts, src/types/StackScript.ts
=> Revert "Sequence -> ordinal"

src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
Fix tests for creation/deletion of SSH keys
3. `yarn e2e --file e2e/specs/profile/ssh-keys.spec.js`
=> M3-2634-tests-rebuild-2 Fix ssh keys tests

e2e/pageobjects/configure-linode.js, e2e/pageobjects/list-stackscripts.page.js, e2e/specs/stackscripts/stackscript-detail.spec.js
This PR fixes the end to end stackscript workflow
3. `yarn e2e --file e2e/specs/stackscripts/stackscript-detail.spec.js`
=> M3-2634-tests-rebuild-2 Fix StackScripts tests

src/components/DocsSidebar/setDocs.tsx, src/documentation.ts, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
Adds documentation sidebar for all One-Click Apps.
This solutions adds onto the DocsSidebar HOC, which follows a similar pattern as `React.memo` in that you can pass an update condition when the docs should be updated. Also the `docs` argument has been typed as a `function` or `Linode.Doc[]` in order to pass the component's own props if necessary
=> [One-Click Apps] Documentation Sidebar

e2e/specs/domains/smoke-list-domains.spec.js
Fix Domains Tests. I couldn't reproduce these test failures consistently, so I'm not 100% this fix is actually fixing the problem
3. `yarn e2e --spec=e2e/specs/dashboard/view-all-links.spec.js,e2e/specs/domains/domains-listed-alphabetically.spec.js,e2e/specs/domains/smoke-list-domains.spec.js --browser=headlessChrome`
=> M3-2653 Fix Domains Tests

CHANGELOG.md, package.json, src/__data__/stackScripts.ts, src/components/AccessPanel/AccessPanel.tsx, src/components/DocsSidebar/setDocs.tsx, src/components/PasswordInput/PasswordInput.tsx, src/components/StackScript/StackScript.test.tsx, src/components/TabbedPanel/TabbedPanel.tsx, src/constants.ts, src/documentation.ts, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx, src/features/StackScripts/stackScriptUtils.ts, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/types/StackScript.ts, src/utilities/safeGetTabRender.test.tsx, src/utilities/safeGetTabRender.tsx
=> Sync Master/Develop

src/features/Domains/DomainTableRow.tsx
Adding word break to domain label on domains landing.
=> M3-2542 Wrap domains text on Domain landing

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Updating graph legend alignment to be at the bottom vs center aligned, and some adjustments for compact mode as well.
=> M3-2664 Fix Linodes graphs legends placement

e2e/specs/profile/ssh-keys.spec.js, src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
3. `yarn e2e --file e2e/specs/profile/ssh-keys.spec.js`
=> M3-2634 Fix ssh creation flow tests

src/features/linodes/DiskSelect/DiskSelect.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx
=> M3-2683 Fix image creation drawer labels spacing

src/components/ModeSelect/ModeSelect.tsx, src/features/Domains/DomainTableRow.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/ListGroupedDomains.tsx, src/features/linodes/LinodesCreate/TabbedContent/formUtilities.test.ts, src/features/linodes/LinodesCreate/TabbedContent/formUtilities.ts, src/features/linodes/LinodesDetail/LinodeNetworking/resolvers.ts, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/services/domains/domains.ts, src/services/domains/records.ts
Going through some of our older @todo items to see if any are no longer valid or can be easily taken care of. There aren't as many of these as I thought, but I'll save the rest for a follow-up PR to keep this small.
Most of the changed files are from renaming `domainID` to `domainId` across the app.
=> Fix: Clean up old @todos Part I

src/components/PrimaryNav/PrimaryNav.tsx, src/index.tsx
Added a GA event for the spacing switcher:
category: 'Theme Choice',
action: 'Spacing Toggle',
label: 'compact' | 'normal'
=> M3-2581 Add GA event for compact mode switcher

src/App.test.tsx, src/App.tsx, src/constants.ts, src/features/TopMenu/TopMenu.tsx, src/index.tsx, src/layouts/LoginAsCustomerCallback.tsx, src/layouts/OAuth.tsx, src/store/authentication/authentication.actions.ts, src/store/authentication/authentication.reducer.ts, src/store/authentication/authentication.test.ts, src/store/authentication/index.ts, src/utilities/request.test.ts, src/utilities/request.ts, src/utilities/storage.ts
Login as Customer
N/A
You must have a functioning devenv to get this working. Please reach out if you have trouble getting the devenv up and running.
Once you have devenv up and running, reach out for an INSERT statement
Once you have devenv and manager running, navigate to `http://localhost:3000/admin/callback#access_token=ec592ecb23e08bbcc0c8008b0898858436df564e04e8975603fdfbe1238e4406&destination=linodes&token_type=Admin&expires_in=7200`
=> M3-2080 Login As Customer

src/features/Events/EventsLanding.tsx
Firefox caught a sorting logic bug I put in, Chrome didn't seem to care. Please make sure your events are in the correct order on Firefox.
=> Update sorting logic

src/__data__/buckets.ts, src/containers/bucketRequests.container.ts, src/features/ObjectStorage/BucketActionMenu.test.tsx, src/features/ObjectStorage/BucketActionMenu.tsx, src/features/ObjectStorage/BucketTableRow.test.tsx, src/features/ObjectStorage/BucketTableRow.tsx, src/features/ObjectStorage/ClusterSelect.tsx, src/features/ObjectStorage/CreateBucketForm.test.tsx, src/features/ObjectStorage/ListBuckets.test.tsx, src/features/ObjectStorage/ListBuckets.tsx, src/services/objectStorage/buckets.ts, src/store/bucket/bucket.actions.ts, src/store/bucket/bucket.reducer.ts, src/store/bucket/bucket.requests.ts, src/types/ObjectStorage.ts
Stil to do:
To test, use dev services and have Object Storage enabled. Create buckets and delete them.
=> M3-OBJ-55 Add: Ability to delete buckets

CHANGELOG.md, package.json
=> Sync Master and Develop

CHANGELOG.md, package.json
=> v0.54.0 master --> develop

CONTRIBUTING.md
You need to also push git tags to upstream when releasing
=> Update Contributing Docs

src/features/Footer/Footer.tsx
Need fixed positioning so it floats around like in classic
=> M3-2707 Adjust positioning of our dear ADA

src/features/Footer/AdaLink.tsx
Is Ada actually used by customers??? We'll see.
=> Adds Analytics to Ada Events

src/features/ObjectStorage/BucketActionMenu.test.tsx, src/features/ObjectStorage/BucketActionMenu.tsx, src/features/ObjectStorage/ListBuckets.tsx
This is apparent in the kebab menus on Buckets Landing as well as the confirmation modal. Unit tests updated as well.
None
=> OBJ: Rename "Remove" bucket to "Delete" bucket

src/exceptionReporting.ts, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/utilities/safeGetTabRender.tsx
See: https://docs.sentry.io/clients/javascript/tips/#decluttering-sentry
* Adds a blacklist for both errors and URLs to Sentry
* Adds a whitelist for *.linode.com and linode.com
* Adds a better API for `reportException` that sends over the user email` and uuid along with allowing for tags and extra info.
N/A
1. Use the development Sentry URL in your `.env`
2. Trigger an error with `reportException`
3. Check sentry for your Error
=> Sentry Updates

CODE_STYLE.md
Add docs for our error handling stuff. Doesn't handle the `getApiErrorFor` stuff, which is also important and I'll try to add it later.
=> Add error handling documentation

src/features/Billing/PdfGenerator/PdfGenerator.ts
Ughhhhhhhh
Aligns the Tax ID to the right side of the page and changes the widths of the columns so we can fit _Quantity_ vs _QTY_
=> Style Updates to Invoice PDF

src/components/EditableText/EditableText.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx, src/features/Profile/AuthenticationSettings/SecuritySettings.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/features/Profile/DisplaySettings/EmailChangeForm.tsx, src/features/Profile/LishSettings/LishSettings.tsx, src/features/Profile/SSHKeys/SSHKeyCreationDrawer.tsx, src/features/Support/SupportTicketDetail/CloseTicketLink.tsx, src/features/Support/SupportTicketDetail/TicketReply.tsx, src/features/Users/CreateUserDrawer.tsx, src/features/Users/UserDetail.tsx, src/features/Users/UserProfile.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/CreateIPv4Drawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx, src/store/image/image.requests.ts
Round 3 (one more upcoming after this is merged). Also adjusts the error state of EditableText, which I couldn't test otherwise bc it was closing on error state.
See comments below.
=> M3-2107 Phase 3: error handling

src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
=> M3-975 Change: Snapshot errors inline, not in Toast

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/Users/UserPermissions.tsx, src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Last round! After this I'll try putting a global catch block somewhere in our pipeline.
None
=> Finish error conversion

CHANGELOG.md, package.json
=> v0.55.0 merge from master

CHANGELOG.md, package.json
=> v0.56.0 Merge From Master

src/App.tsx, src/assets/addnewmenu/kubernetes.svg, src/features/Kubernetes/Kubernetes.tsx, src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx, src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx, src/features/Kubernetes/KubernetesLanding/index.ts, src/features/Kubernetes/index.tsx, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Kubernetes null state page. To test, ensure REACT_APP_KUBERNETES_ENABLED='true' is set in your .env file.
=> LKE-555 Kubernetes Null State

src/services/profile/objectStorageKeys.ts
~WIP: NOT READY UNTIL API IS MERGED~ DONE
Based on recent review feedback, this API endpoint is changing.
=> OBJ-162: Move account/s3-keys > object-storage/keys

package.json, src/components/TabbedPanel/index.ts, src/components/core/Paper.ts, src/components/core/Paper.tsx, src/constants.ts, src/features/Support/ExpandableTicketPanel.tsx, src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx, src/themeFactory.ts, src/themes.ts, src/utilities/sanitize-html/sanitizeHTML.ts, yarn.lock
Adds Markdown support in ticket detail replies (not the drawer yet)
Adds code highlighting
Coming up in the next PR...
1. Docs for using markdown
2. Preview Tab in Ticket Drawer
N/A
=> Markdown Part 3 - Markdown in Replies

src/components/TabbedPanel/TabbedPanel.tsx, src/eventMessageGenerator.ts, src/features/Support/AttachFileForm.tsx, src/features/Support/ExpandableTicketPanel.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx, src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.test.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/Support/TicketDetailText.tsx
Adds Reference Guide to Support Ticket Reply
N/A
=> Markdown Part 4: Reference Guide and Drawer

src/containers/account.container.ts, src/containers/events.container.ts, src/containers/localStorage.container.ts, src/containers/profile.container.ts, src/containers/withImage.container.ts, src/containers/withImages.container.ts, src/containers/withMostRecentBackup.container.ts, src/features/linodes/LinodesDetail/LinodesDetail.container.tsx, src/features/linodes/LinodesDetail/initLinodeConfigs.ts, src/features/linodes/LinodesDetail/initLinodeDisks.ts, src/features/linodes/LinodesDetail/maybeRenderLoading.tsx, src/features/linodes/LinodesDetail/maybeWithExtendedLinode.tsx
FaR Outter --> Outer
Killing this hydra once and for all.
=> Outter Banks

src/containers/localStorage.container.ts, src/features/Domains/DomainsLanding.test.tsx, src/features/Domains/DomainsLanding.tsx, src/utilities/storage.ts
Adds a warning that domains aren't being served when there aren't any Linodes on the account
N/A
=> Add: Warning for When Domains Aren't Being Properly Served

src/features/TopMenu/UserMenu/UserMenu.tsx
Making profile dropdown menu items ctrl + clickable.
=> M3-2755 Implement ctrl+click on profile dropdown buttons

src/constants.ts, src/features/Support/ExpandableTicketPanel.tsx, src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
Wraps links in anchor tags in support ticket replies
Also fixes some weird styling
N/A
=> Markdown Part 5: Support Hyperlinks

src/__data__/kubernetes.ts, src/components/TableSortCell/TableSortCell.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/Kubernetes/ClusterList/ClusterList.tsx, src/features/Kubernetes/ClusterList/ClusterRow.test.tsx, src/features/Kubernetes/ClusterList/ClusterRow.tsx, src/features/Kubernetes/CreateCluster/CreateCluster.tsx, src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx, src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/features/Kubernetes/KubeCheckoutBar.tsx, src/features/Kubernetes/kubeUtils.test.ts, src/features/Kubernetes/kubeUtils.ts, src/features/Kubernetes/types.ts, src/utilities/sort-by.ts
Add columns to the K8s cluster table, then refactor types etc. to make it work.
N/A
Devenv as usual.
=> LKE-556 Add: Total CPU and memory columns to list view

src/components/PasswordInput/PasswordInput.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx
=> [For Release] Copy Changes

src/features/Kubernetes/CreateCluster/CreateCluster.tsx, src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
Building this PR again because of rebase issues
=> Don't allow negative values for node_count

CHANGELOG.md
=> Update release date in changelog

CHANGELOG.md, package.json, src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx, src/components/AbuseTicketBanner/AbuseTicketBanner.tsx, src/components/PasswordInput/PasswordInput.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx
=> Sync master – develop

src/exceptionReporting.ts, src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
Reports username in sentry errors
I also noticed that general errors weren't going through our abstracted function, so I made sure that it was.
=> Report Username in Sentry Errors

src/components/VATBanner/VATBanner.tsx
=> Fix conditional text (missing by)

src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
Moving the 'IP Addresses' panel underneath the 'Linode Details' panel in the sidebar of a Linode summary.
=> M3-2830 IP component placement

scripts/pre-commit.sh, scripts/pre-push.sh
- Remove storybook e2e tests from pre-commit.sh (they should still run on Travis builds)
- Add OCA to our list of approved branch names
=> Housekeeping

src/features/Images/ImagesLanding.tsx, src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, src/features/StackScripts/StackScriptsLanding.tsx
Update placeholder copy for SS and Images to include docs links and match existing Volumes/Domains copy.
=> M3-2315 M3-2316 Update empty state copy for Images and StackScripts.

src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
Match empty NB copy to the new pattern (see e.g. Volumes), where we include docs relevant to the entity type.
=> M3-2314 Update NB empty state copy

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
=> Remove Kuber from Create menu

src/features/Volumes/VolumesLanding.tsx
Adds loading state to Volumes landing, sourced from Redux state
N/A
=> Change: Adds Loading State to Volumes Landing

src/features/TopMenu/SearchBar/SearchBar.styles.ts
Updating main search bar text to not get cut off.
=> M3-2867 Fix cut off typography in main search bar

src/App.tsx, src/components/VATBanner/VATBanner.tsx, src/containers/account.container.ts, src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx, src/store/account/account.actions.ts, src/store/account/account.reducer.ts, src/store/account/account.requests.ts, src/store/accountSettings/accountSettings.actions.ts, src/store/accountSettings/accountSettings.reducer.test.ts, src/store/accountSettings/accountSettings.reducer.ts, src/store/index.ts, src/store/notification/notification.actions.ts, src/store/types.ts
Replace the Account context in UpdateContactInformationPanel with a Redux container. This allows us to (among other things) automatically update the VAT banner state when the form is submitted.
~This also includes the VAT commits, so marking as don't merge~
=> M3 redux account

e2e/pageobjects/profile.js, e2e/specs/profile/tokens.spec.js
Fixes PAT Token Tests
3. `yarn e2e --spec=e2e/specs/profile/tokens.spec.js --browser=headlessChrome`
=> Test: Fix PAT Token Tests

e2e/pageobjects/linode-detail/linode-detail-backups.page.js, e2e/specs/linodes/detail/backups-create.spec.js, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
Fixed Linode Detail - Backups Snapshot tests
- Fix
3. `yarn e2e --file=e2e/specs/linodes/detail/backups-create.spec.js --browser=headlessChrome`
=> Fix: Backups linode detail e2e test

TESTING.md
Updated the testing docs to reflect compatibility with java jdk 12
- Docs
=> Docs: Update testing requirements

e2e/pageobjects/linode-detail/linode-detail-settings.page.js, e2e/specs/linodes/detail/smoke-settings.spec.js
* Update delete linode confirmation message.
- Fixed Test
3. `yarn e2e --file=e2e/specs/linodes/detail/smoke-settings.spec.js --browser=headlessChrome`
=> Fix: Delete Linode Test

e2e/pageobjects/configure-linode.js, e2e/pageobjects/stackscripts/stackscript-detail.page.js, e2e/specs/stackscripts/stackscript-detail.spec.js
* Fixes stackscript detail tests
* Disables community stackscript detail tests, due to UX changes. Can be tackled in a separate PR.\
- Test Fix
3. `yarn e2e --file e2e/specs/stackscripts/stackscript-detail.spec.js`
=> Fix: Stackscript detail tests

src/components/DateTimeDisplay/DateTimeDisplay.tsx, src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/components/Notice/Notice.tsx, src/containers/profile.container.ts, src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx, src/features/StackScripts/StackScriptsDetail.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx, src/features/linodes/LinodesDetail/types.ts, src/store/linodes/linodes.helpers.ts
Adds Banner to Linode Detail Screen. **There are a lot of different possible messaging cases, so please use all the mock data provided with prod-test-003**
N/A
Mock Data
```js
{
"results": 5,
"page": 1,
"data": [
{
"until": null,
"entity": {
"url": "/linode/instances/500",
"id": 14341983,
"type": "linode",
"label": "loadbal1-vagrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_scheduled",
"label": "You have a scheduled migration pending!",
"message": "You have a scheduled migration pending!  Your Linode will be automatically shut down, migrated, and returned to its last state."
},
{
"until": null,
"entity": {
"url": "/linode/instances/504",
"id": 14341983,
"type": "linode",
"label": "loadbal5-xengrant"
},
"when": null, …
```
=> Maintenance Part 3: Linode Detail Banner

src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/components/OrderBy.ts, src/features/linodes/LinodesLanding/CardView.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/ListView.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
Adds "Maintenance Status" Column to Linodes Landing.
N/A
Use prod-test-003 with the following test data:
```js
{
"results": 5,
"page": 1,
"data": [
{
"until": null,
"entity": {
"url": "/linode/instances/500",
"id": 14341983,
"type": "linode",
"label": "loadbal1-vagrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_scheduled",
"label": "You have a scheduled migration pending!",
"message": "You have a scheduled migration pending!  Your Linode will be automatically shut down, migrated, and returned to its last state."
},
{
"until": null,
"entity": {
"url": "/linode/instances/504",
"id": 14341983,
"type": "linode",
"label": "loadbal5-xengrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_pending", …
```
=> Maintenance Part 4: Adding Maintenance Status To Linode Table

src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
Just some copy changes
N/A
Pls use prod-test-003 with this test data:
```js
{
"results": 5,
"page": 1,
"data": [
{
"until": null,
"entity": {
"url": "/linode/instances/500",
"id": 14341983,
"type": "linode",
"label": "loadbal1-vagrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_scheduled",
"label": "You have a scheduled migration pending!",
"message": "You have a scheduled migration pending!  Your Linode will be automatically shut down, migrated, and returned to its last state."
},
{
"until": null,
"entity": {
"url": "/linode/instances/504",
"id": 14341983,
"type": "linode",
"label": "loadbal5-xengrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_pending",
"label": "You have a migration …
```
=> Maintenance Part 6: Copy Changes

src/components/PrimaryNav/PrimaryNav.tsx
Removes the scrollbar from the Primary Nav
N/A
=> [For Release] Primary Nav Scrollbar

GETTING_STARTED.md
Ya'll spelled LISH wrong.
- Breaking change
It was probably me. I'm a terrible speller.
=> Correct REACT_APP_LISH_ROOT typo.

src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
Adds Linode label to Notification list item in the top drawer.
N/A
Feel free to login as a customer to my account `mmckenna` You can find a Linode with maintenance there.
=> [Hotfix] Adds Linode Label to Notification Drawer List Item

src/assets/icons/entityIcons/bucket.svg, src/components/EntityIcon/EntityIcon.tsx, src/components/Placeholder/Placeholder.tsx, src/features/ObjectStorage/Buckets/BucketLanding.tsx, src/features/ObjectStorage/Buckets/BucketTableRow.tsx
This PR adds the bucket icon for Object Storage.
Two places to check: 
1) Buckets `<Placeholder />` (account with no buckets)
2) Buckets row (account with buckets)
=> OBJ-164 add: Bucket Icon

CHANGELOG.md, package.json, src/assets/icons/entityIcons/bucket.svg, src/components/EntityIcon/EntityIcon.tsx, src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/components/Placeholder/Placeholder.tsx, src/features/ObjectStorage/Buckets/BucketLanding.tsx, src/features/ObjectStorage/Buckets/BucketTableRow.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
=> Merge Master --> Develop

src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/constants.ts, src/features/linodes/LinodesDetail/LinodeNetworking/resolvers.ts, src/types/Networking.ts, src/utilities/doesRegionSupportBlockStorage.test.ts
Adds support for the Mumbai DC.
Add the Mumbai customer tag to your account and create a Linode in that DC.
=> M3-2346 add: Support for Mumbai region

src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
Makes the maintenance notification yellow
N/A
=> Change: Maintenance Notification Color

src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
This did not look so hot in compact mode
=> Fix: Maintenance Banner Styles

src/services/objectStorage/buckets.schema.ts
This is in conjunction with an API change to validate this on the server as well. 
=> [ for release] OBJ-169: Validate no whitespace in bucket names

src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/types/LinodeType.ts
Add GPU to the appropriate types and to SelectPlanPanel.
New GPU types are available in dev services
=> M3-2796 Add support for GPU instances

e2e/specs/account/billing.spec.js, src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
* Added data-qa attributes to the State/Province and Country selects
* Fixed issue where test would fail due to checking for updated contact info too quickly.
- Test fix
3. `yarn e2e --file e2e/specs/account/billing.spec.js --browser=headlessChrome`
=> Fix: Update billing contact info test

src/components/Breadcrumb/index.tsx, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
This PR implements the expanded header as discussed in review.
=> M3-2247 Part 2.5

src/__data__/kubernetes.ts, src/containers/kubernetes.container.ts, src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.test.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/services/kubernetes/kubernetes.ts, src/store/kubernetes/kubernetes.actions.ts, src/store/kubernetes/kubernetes.reducer.ts, src/store/kubernetes/kubernetes.requests.ts, src/types/Kubernetes.ts
Redux and services wrappers around the API stuff needed for:
- Adding a node pool
- Updating a node pool
- Deleting a cluster
- Deleting a node pool
It'll look much cleaner after Part 2 is merged.
=> LKE 591 cluster detail Part 2.5

src/features/Profile/Profile.tsx
Fixes react router browser warnings on Profile route.
=> Fix: React Router Warnings on Profile

src/features/ObjectStorage/ObjectStorageLanding.tsx
Fixes react router warnings for OBJ Landing (along with forwardRef issue)
N/A
=> Fix: React Router warnings for OBJ

src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/themeFactory.ts
Also added a couple fixes for the menuItems in compact mode while i was at it
=> M3-2931 fix modal spacing

src/features/Dashboard/DashboardCard.tsx, src/themeFactory.ts
=> M3-2935 Dashboard header action spacing

src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
This copy change got lost in the MUI rebase.
https://github.com/linode/manager/pull/5056/files
N/A
=> Change: Notification Copy

src/features/Help/Panels/AlgoliaSearchBar.tsx, src/features/Help/Panels/SearchPanel.tsx
Styling adjustments for help landing (in the header panel) when viewing in compact mode. Also made a few adjustments for smaller devices as well. 
=> M3-2925 Fix help landing page compact mode styles

src/features/Billing/BillingPanels/SummaryPanel/PanelCards/BillingInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/services/account/account.schema.ts, src/services/account/account.ts
Refactors File Structure, fixes tests, and adds service function for cancel account.
No logic here changed - it was simply moved and made easier to read.
N/A
=> Close Account 1

src/features/ObjectStorage/AccessKeys/AccessKeyLanding.tsx, src/features/ObjectStorage/Buckets/CreateBucketForm.tsx, src/features/ObjectStorage/Buckets/ListBuckets.tsx, src/utilities/ga.ts
Adds analytics for Object Storage:
- Create Bucket
- Delete Bucket
- Create Access Key
- Edit Access Key 
- Revoke Access Key
=> OBJ-133: Add GA events

src/features/NodeBalancers/NodeBalancerCreate.tsx
=> Updates NB Price

src/__data__/kubernetes.ts, src/__data__/nodePools.ts, src/containers/kubernetes.container.ts, src/features/Kubernetes/ClusterList/ClusterActionMenu.test.tsx, src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx, src/features/Kubernetes/ClusterList/ClusterRow.test.tsx, src/features/Kubernetes/ClusterList/ClusterRow.tsx, src/features/Kubernetes/CreateCluster/CreateCluster.tsx, src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx, src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesDialog.tsx, src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx, src/features/Kubernetes/kubeUtils.test.ts, src/features/Kubernetes/kubeUtils.ts, src/features/Kubernetes/types.ts, src/services/kubernetes/kubernetes.ts, src/store/kubernetes/kubernetes.actions.ts, src/store/kubernetes/kubernetes.reducer.ts, src/store/kubernetes/kubernetes.requests.ts, src/types/Kubernetes.ts, tslint.json
Part 3! This adds API support, so the "Save" and "Delete" buttons on ClusterDetail should now work; everything except the tags panel is now functional.
Still to come:
Part 4: styling
Part 5: tests, additional refactoring and/or cleanup
MUI rebase hasn't been done on this feature branch (will do after this merges), so you might have to restart yarn, blow out node_modules, etc.
=> LKE-591 Add: Cluster Detail (Part 3)

src/components/PasswordInput/PasswordInput.tsx, src/components/PasswordInput/StrengthIndicator.tsx
Password component in compact mode was overlapping with the strength indicator, this fixes that issue and preserves normal spacing mode styles as well. 
Please check multiple places where password component is used- OCA create flow has a couple in the UDFs and the root password.
=> Adjustments to password component for compact mode

src/themeFactory.ts
Adds lineheight to our sortable table header labels. 
=> M3-2939: Sortable labels line height

src/components/EnhancedSelect/Select.styles.ts, src/themeFactory.ts
=> M3-2943 Fix MuiInput input default height

src/features/OneClickApps/AppDetailDrawer.tsx, src/features/OneClickApps/LinkSection.tsx
=> M3-2945 Fix OCA detail drawer layout

src/features/Account/AutoBackups.tsx, src/features/Account/GlobalSettings.tsx
Adds tooltip text to the auto backups setting if you're a managed user.
N/A
=> Add: Helper Text for Managed Users and Auto Backups

src/features/OneClickApps/FakeSpec.ts
=> Swap description and summary texts for CS:GO

src/assets/icons/guides.svg, src/assets/icons/moreInfo.svg
updating stroke color to inherit from class.
=> Update: Icons for OCA Detail Drawer to get theme colors

src/store/volume/volume.events.ts
Update UI based on `volume_update` events
An example of this would be changing the size of a volume.
=> Update: Subscribe to volume_update events

src/__data__/disks.ts, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/CloneLanding/Details.tsx, src/features/linodes/CloneLanding/utilities.test.ts, src/features/linodes/CloneLanding/utilities.ts
This PR includes a few items that came up in review (and slightly beforehand):
- Change to Breadcrumb/Title.
- Copy for "powering off disks".
- Error state with links to resize your Linode and Disks.
- Estimated cloning time
**To test error states:**
- Try cloning a disk to a different Linode with no free space.
- Try duplicating a disk on the same Linode that has no free space.
- Block the Request.
=> M3-2247 Review feedback

src/containers/SummaryPanels.styles.ts, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainRecordsWrapper.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/NodeBalancerSummary.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
We had console warnings for shared styles (MUI key issues) - this PR takes care of removing these warnings
=> M3-2957 Fix console warnings for sidebar styles

src/components/PrimaryNav/PrimaryNav.tsx, src/components/SideMenu.tsx, src/features/TopMenu/TopMenu.tsx, src/themeFactory.ts, src/themes.ts
Updating the primary nav to use a chevron shape as indication of user's active location instead of using a border color for accessibility reasons
- Non breaking change ('update'')
=> M3-2928 Navigation indication for the entity

src/components/BarPercent/BarPercent.test.tsx, src/components/BarPercent/BarPercent.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx
these changes affect the dashboard. linode summary and linode advanced pages
=> M3-2599 Update Monthly Network Transfer panels

src/App.tsx
We're not quite ready to deploy with LD, so I commented out the featureFlag provider in App.tsx
To verify, run the app and open up your console. You shouldn't see errors complaining about LD.
=> Disable LD provider

src/App.tsx, src/features/Account/AccountLanding.tsx, src/features/Domains/index.tsx, src/features/Images/ImagesLanding.tsx, src/features/ObjectStorage/ObjectStorageLanding.tsx, src/features/StackScripts/StackScriptsLanding.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/index.tsx
added to:
- /images
- /volumes
- /object-storage
=> M3-2971 Add breacrumb component to all landing pages

src/components/Breadcrumb/Breadcrumb.tsx, src/components/EditableText/EditableText.tsx
Had a small margins issues on the crumbs when having an editable text widget
=> M3-2970 Adjust breadcrumbs editable text margins

src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx, src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx, src/themeFactory.ts, src/themes.ts
Styling adjustments for Cluster Detail Page. See ticket for comps/details.
You'll need devenv running, if you haven't pulled latest you should be able to follow instructions originally documented (PM for link). Otherwise, if you have updated, I have found a way to mock using Charles that has been working well for me. I can DM instructions for that as well.
=> LKE-621: Styling Cluster Details Page

src/exceptionReporting.ts
Adds grouping by fingerprint to Sentry. In this PR, it will configure sentry to group all local storage errors together if the error matches on:
_localstorage_ or _quotaExceeded_
N/A
Create some errors with the error messages that will match the two strings above ^^ and you will see that no matter what the error message is, they will be grouped as one in the Sentry dashboard.
https://blog.sentry.io/2018/01/18/setting-up-custom-fingerprints
https://docs.sentry.io/data-management/rollups/?platform=javascript#grouping-priorities
=> Add: Sentry Group by Fingerprint

src/exceptionReporting.ts
Fixes type import for Sentry Events
N/A
run `yarn && yarn start`, `yarn build` and `yarn test`
=> Fix: Sentry Types

src/assets/icons/entityIcons/kubernetes.svg
Adjustment to LKE icon for the cluster row. Please view in both light/dark modes.
=> LKE Icon Styling Update

src/WelcomeBanner.tsx, src/components/EntityIcon/EntityIcon.tsx, src/components/Forms.stories.tsx, src/components/RenderGuard.tsx, src/components/Typography.stories.tsx, src/components/core/CssBaseline.ts, src/components/core/Modal.ts, src/components/core/WithWidth.ts, src/features/Account/NetworkHelper.tsx, src/features/StackScripts/LandingPanel/Dialogs/DeleteDialog.tsx, src/features/StackScripts/LandingPanel/Dialogs/MakePublicDialog.tsx, src/features/StackScripts/LandingPanel/Table/LabelCell.tsx, src/features/StackScripts/LandingPanel/Table/TableHeader.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx, src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx, src/features/TopMenu/UserEventsMenu/UserEventsMenu.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/utilities/storybookDecorators.tsx
=> M3-2956 TDT - Replace remaining components MUI Core imports

src/constants.ts, src/services/kubernetes/kubernetes.ts, src/services/objectStorage/buckets.ts, src/services/objectStorage/clusters.ts
Store the `/v4beta` endpoint in `src/constants`, since we're using it in several places now.
Please test that OBJ and LKE features work as expected.
=> M3-3000: Read beta endpoint from src/constants

src/components/DefaultLoader.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/BillingInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/CancelAccountDialog.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/services/account/account.schema.ts, src/services/account/account.ts, src/themeFactory.ts, src/themes.ts
Adds ability to close account
N/A
This endpoint don't work yet
=> Close Account Part 2

src/components/PrimaryNav/AdditionalMenuItems.tsx, src/components/PrimaryNav/NavItem.tsx, src/components/SelectionCard/CardBase.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
Fixed the following console warnings:
- key warning with `NavItem.tsx`
- forwardRef with `CardBase.tsx`
- tabIndex error with `NodeBalancersDetail.tsx`
=> M3-3004 TDT fix some console warnings

src/components/DefaultLoader.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/BillingInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/CancelAccountDialog.tsx, src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/features/Users/UserPermissions.tsx, src/services/account/account.schema.ts, src/services/account/account.ts, src/themeFactory.ts, src/themes.ts
=> Add: Ability to Close Account

package.json, src/features/linodes/CloneLanding/utilities.ts, src/features/linodes/LinodesCreate/SelectImagePanel.tsx, src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx, src/features/linodes/transitions.ts, src/store/linodes/linodes.events.ts, src/utilities/updateById.ts, yarn.lock
ramda source code has `const adjust = (arg1: number, arg2: function) => whatever`
ramda typescript types have `const adjust = (arg2: function, arg1: number) => whatever`
so the `@types/ramda` package had to be downgraded so that types matched the source code.
Clone a Linode and make sure the progress shows all the way through til the end
=> [For Release] Fix: Ramda Types and Invocation

src/constants.ts, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx, src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
Adds an estimated time of migration for the mutate drawer. This is based on a hard-coded equation from Classic. Please reach out and I can send you my sources.
N/A
=> Adds Mutation Estimated Time to Drawer

src/store/linodes/linodes.events.ts
Dispatch disks requests after rebuilding Linode
Rebuilding a Linode re-creates its disks, which have different id's
than the previous disks. This was causing 404 errors when rebuilding
a Linode then trying to immediately resize disks without reloading
the page.
- Create a new linode (I was using our Debian 9 bare image)
- Under advanced tab, resize the disk to take all available space.
- Rebuild - apply the same image
- Now the advanced tab shows that all space is allocated
- Resize the disk smaller in the advanced tab
- Get error message: 'Not found'
=> M3-2940 Fix: Dispatch disks requests after rebuilding Linode

CHANGELOG.md, package.json, src/components/PreferenceToggle/PreferenceToggle.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
=> Revert "Sync Master and Develop"

src/components/TextField.tsx, src/features/Kubernetes/ClusterList/ClusterActionMenu.test.tsx, src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx, src/features/Kubernetes/ClusterList/ClusterList.tsx, src/features/Kubernetes/ClusterList/ClusterRow.test.tsx, src/features/Kubernetes/ClusterList/ClusterRow.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesDialog.test.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesDialog.tsx, src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx, src/features/Kubernetes/types.ts, src/store/kubernetes/kubernetes.reducer.ts
Update KubernetesDialog to use the same deletion pattern as OBJ (i.e. you have to type the cluster name to confirm before deleting).
Also adds the deletion dialog to ClusterList/ClusterActions.
=> LKE-711 Change: Delete cluster

src/components/EntityIcon/EntityIcon.tsx, src/components/HelpIcon/HelpIcon.tsx, src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/linodes/LinodesLanding/CardView.tsx, src/features/linodes/LinodesLanding/LinodeCard.style.ts, src/features/linodes/LinodesLanding/LinodeCard.test.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/features/linodes/LinodesLanding/ListView.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx, src/features/linodes/LinodesLanding/TableWrapper.tsx
- you will need Charles to review this in order to add maintenance status to one of your linode
=> M3-2924 Linode Status Column

GETTING_STARTED.md, package.json
Adds `yarn clean` and `yarn test` as helper scripts to the root level package.json
`yarn test packages/manager/src/App.test.tsx` to run one test
`yarn clean` to remove top-level and package-level node_modules
=> Add: Helper Scripts

packages/manager/src/components/SplashScreen/SplashScreen.tsx, packages/manager/src/components/SplashScreen/keyframes.css
This is a temp improvement until we get something in line with marketing
=> M3-3081 - Add logo to app loader

packages/manager/src/features/Images/ImagesDrawer.tsx, packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
=> [For Release] Update images copy

packages/manager/src/components/Link.tsx, packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsList.tsx, packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx
This is an alternative approach to fixing the Events bug (See #5276). It's probably better in the long run, but I'm less confident that there are no unintended effects. It also won't work if we ever want clicking an Event to do anything other than navigate somewhere.
=> Abstract Link component so that it can handle external links

packages/manager/src/App.test.tsx, packages/manager/src/App.tsx, packages/manager/src/index.tsx, yarn.lock
Correctly send pageview events to both the Cloud Manager and Linode.com properties
N/A
Change routes and see GA events come in.
See slack for testing steps
=> Fix: Analytics Page View Events

packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
=> M3-3077 Remove leave delay for maintenance status tooltip

packages/manager/src/assets/logo/logo-animated.svg, packages/manager/src/components/SplashScreen/SplashScreen.tsx, packages/manager/src/components/SplashScreen/keyframes.css
=> M3-3092 For Release: Update Loading logo to match branding reqs

CHANGELOG.md, package.json
=> Merge Master back into Develop (release)

packages/manager/src/eventMessageGenerator.ts
Adds handling for:
- `user_create`
- `user_update`
- `payment_submitted`
These are currently being returned by the API, but not handled in Cloud.
**Note:** no `entity` is returned on `payment_submitted`, so there's not much else we can say.
**To test:**
- Create/Update/Delete a user and verify that events are coming through appropriately.
- To verify the `payment_submitted` event, I ran everything locally.
=> M3-3097: Handling for new event types

RELEASING.md, package.json
=> Update Release Instructions

Dockerfile
=> upgrades node in dockerfile

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
UI Adjustments to kubeconfig buttons and the 'View config' drawer.
=> LKE-718 Enable viewing of kubeconfig- UI Followup

packages/manager/src/components/AddNewLink/AddNewLink.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Users/UsersLanding.tsx
Disables "Add a User" button if you're a restricted user.
N/A
=> Change: Disable Add User Button for Restricted Users

packages/manager/src/__data__/account.ts, packages/manager/src/features/Dashboard/Dashboard.tsx, packages/manager/src/features/Dashboard/PromotionsBanner.tsx, packages/manager/src/types/Account.ts
Got the data shape wrong on this.
=> Change: Update types and sample data for active_promotions

packages/manager/src/index.tsx
Was looking at a simple way to implement a hot reload for the manager to speed up development time. Reloading the whole app for a single css change for example seems overkill. Not sure what is proposed here is the best way to do it, but it seems to works and was simple enough.
=> M3-3101 Enable hot reload

packages/manager/src/features/linodes/userSSHKeyHoc.ts
When adding an SSH key, we had been preserving the previous state of the userSSHKeyHoc, so that if Bill, Jane, and Charlie had been selected as authorized users before adding a key, they would be selected afterwards as well.
This PR, per review feedback from Chris, maintains this behavior with one exception: after adding a new key, the current user will be selected. 
It was much too hard to do work out how to do this...when a simple change like this needs large or unintuitive changes to the code, it's a major red flag. I'm going to work on updating/replacing the userSSHKeyHoc for the next TDT.
=> M3-3078 Change: Select user by default after she adds an SSH key

packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/index.css, packages/manager/src/themeFactory.ts
On a large breakpoint, we should set a limit on how wide the main content stretches, and center it. Lesstryit.
=> M3-3116 POC: add max-width to main content

packages/manager/e2e/pageobjects/configure-linode.js, packages/manager/e2e/pageobjects/nodebalancers.page.js, packages/manager/e2e/specs/create/smoke-configure-linode.spec.js, packages/manager/e2e/specs/create/smoke-create-volume.spec.js, packages/manager/e2e/specs/nodebalancers/smoke-create.spec.js, packages/manager/src/__data__/regionsData.ts, packages/manager/src/components/EnhancedSelect/components/Option.tsx, packages/manager/src/components/SelectRegionPanel/RegionOption.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/constants.ts, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
New design for Region select. Comps are linked from the JIRA ticket.
Still a few lingering style questions for @alioso and Jay.
Todo:
=> M3-3083 Change: Region select

packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx, packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx, packages/manager/src/features/linodes/MigrateLanding/index.ts, packages/manager/src/services/linodes/linodeActions.ts
Initial scaffolding for Inter-DC Migrations. Pretty much just sourcing data from Redux and dispalying
N/A
=> Adds Initial Inter DC Migration Skeleton

packages/manager/package.json, packages/manager/yarn.lock
=> M3-3132 Update browserslist package

packages/manager/src/components/LineGraph/LineGraph.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.test.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/TotalTraffic.tsx, packages/manager/src/themeFactory.ts
Charts needed to have different styles and color matching, as well as fixing some consistency with responsive styles.
This includes the charts in both the Linodes and NodeBalancers summaries. 
=> M3-3127 Improve charts display

.gitignore
I accidentally committed my .env file bc it was open in Vim.
=> Add .swp to gitignore

packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
=> Fix TS to repair builds

packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
Small adjustments to caption text for alignment.
=> Fix spacing in create workflow backup pane

.gitignore, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/containers/regions.container.ts, packages/manager/src/features/Volumes/VolumeDrawer/RegionSelect.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx, packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx, packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx, packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx, packages/manager/src/utilities/formatRegion.ts
Adds functionality to the submit button for inter-DC migrations.
N/A
=> Inter-DC Migration Part 3: Add Migration Logic and Error States

packages/manager/src/features/Managed/Credentials/CredentialDrawer.tsx, packages/manager/src/features/Managed/Credentials/CredentialList.tsx, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/services/managed/managed.schema.ts, packages/manager/src/services/managed/managed.ts
Pretty simple entity so nothing special about the drawer.
=> M3-700 Add credential drawer

packages/manager/src/components/TextField.tsx, packages/manager/src/features/Images/ImageSelect.tsx, packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx, packages/manager/src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx, packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx, packages/manager/src/features/Support/SupportTickets/TicketList.tsx
Hits 3 points
🔔 Please note point 2 is experimental 🔔 
1. Updates support ticket form
* changes label of "Summary" to now read "Title"
* Replaces asterisk with "(required)" text.
2. All text fields marked required, will now have "(required)" appended to it, rather than an asterisk
3. Fixes error handling for StackScript create and update. Previously, no client side errors were appearing. This is a bug
=> Update: Support Ticket Form and Required Fields

packages/linode-js-sdk/src/account/account.ts, packages/linode-js-sdk/src/account/types.ts, packages/manager/src/features/Billing/BillingDetail.tsx, packages/manager/src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, packages/manager/src/services/account/account.ts
Small addition to the SDK to make sure the build is still working when the local SDK is out of date with the one published to NPM.
I hope it works
N/A
=> Add: getNetworkUtilization to JS SDK

packages/manager/src/features/Managed/Contacts/Contacts.tsx, packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx, packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx, packages/manager/src/features/Managed/Contacts/ContactsRow.tsx, packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx, packages/manager/src/features/Managed/Contacts/common.ts, packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx, packages/manager/src/services/managed/managed.schema.ts, packages/manager/src/services/managed/managed.ts, packages/manager/src/types/Managed.ts
This PR adds the drawer to create and edit Managed Contacts.
**⚠️Things that don't work yet:**
- Deleting Contacts
- Deleting Groups
- Adding Groups 
- Editing Groups
**To Test:**
Go to Managed -> Contacts. Create and Edit contacts. Try different form values.
=> M3-694 Part II: Contact Drawer

packages/manager/src/assets/logo/logo-animated.svg, packages/manager/src/components/SplashScreen/keyframes.css
Improving animation for the loader on chrome (was a bit laggy)
=> M3-3178 Improve splash page loader animation

packages/manager/src/features/Dashboard/Dashboard.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/Healthy.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/Unhealthy.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/index.tsx, packages/manager/src/store/managed/managed.reducer.ts
Adds a Dashboard widget for managed services.
We're going to have to iterate on this, there are things in the design that it's not clear we can do, so I improvised a bit.
=> M3-691 managed dashboard widget

packages/manager/src/constants.ts, packages/manager/src/features/Volumes/VolumeDrawer/LinodeSelect.test.tsx, packages/manager/src/features/Volumes/VolumeDrawer/LinodeSelect.tsx, packages/manager/src/features/Volumes/VolumesLanding.tsx, packages/manager/src/utilities/doesRegionSupportBlockStorage.test.ts, packages/manager/src/utilities/doesRegionSupportBlockStorage.ts
replace regionsWithoutBlockStorage with region capabilities 
=> [M3-3177] Change: region block storage refactor

packages/linode-js-sdk/.babelrc, packages/linode-js-sdk/package.json, packages/linode-js-sdk/src/account/account.ts, packages/linode-js-sdk/tsconfig.json, packages/linode-js-sdk/yarn.lock
Allows for absolute imports a la
`import { blah } 'from src/request'`
=> [SDK] Update: Allow Absolute Imports

packages/manager/src/containers/withFeatureFlagProvider.container.ts, packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx, packages/manager/src/utilities/ga.test.ts, packages/manager/src/utilities/ga.ts
Adds Google Analytics to Migration initiations. Includes time of day, source and target datacenters.
=> Add: Analytics to Inter-DC Migrations

packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Needed to add some more information in the CSV download from the linodeData specs
- Non-breaking change ('update')
=> M3-3204 Add Linode description data in CSV download

packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
=> Adjust styles for SSH key component

packages/manager/src/components/TabbedPanel/TabbedPanel.tsx, packages/manager/src/features/Profile/OAuthClients/Modals.tsx, packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
=> M3-3252 Fix client Secret key wrapping

.travis.yml, packages/linode-js-sdk/.babelrc, packages/linode-js-sdk/src/index.ts, packages/linode-js-sdk/src/tags/index.ts, packages/linode-js-sdk/src/tags/tags.ts, packages/linode-js-sdk/src/tags/types.ts, packages/manager/src/components/TagsInput/TagsInput.stories.tsx, packages/manager/src/components/TagsInput/TagsInput.test.tsx, packages/manager/src/components/TagsInput/TagsInput.tsx, packages/manager/src/components/TagsPanel/TagsPanel.stories.tsx, packages/manager/src/components/TagsPanel/TagsPanel.tsx, packages/manager/src/constants.ts, packages/manager/src/services/tags/index.ts
Migrates all tags endpoints and types
=> [SDK] Migrates Tags Services into SDK

packages/manager/public/index.html
Unless I'm doing something wrong, I don't think we can test this locally. We can try some snapshots once it's in production and see how it goes.
=> Add crazy egg script

packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
Reorder columns:  Label - status - IP- Region - backups
=> M3-3052 switch linodeRows cell order

packages/manager/src/featureFlags.ts, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
I included a UI update in a previous PR that I wanted to review with the LKE team before merging. Then I forgot and merged it. This PR will make the update a flagged feature, so that we can have it as an option if/when it is approved.
=> LKE Make hidden buttons a flagged feature

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
Made sure styles are good on all breakpoints for both compact and normal mode
=> M3-3239 Fix styles for notification thresholds panel

packages/linode-js-sdk/src/index.ts, packages/linode-js-sdk/src/regions/index.ts, packages/linode-js-sdk/src/regions/types.ts, packages/manager/src/App.tsx, packages/manager/src/__data__/regionsData.ts, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx, packages/manager/src/containers/regions.container.ts, packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, packages/manager/src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx, packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx, packages/manager/src/services/misc/index.ts, packages/manager/src/store/regions/regions.actions.ts, packages/manager/src/store/regions/regions.reducer.ts, packages/manager/src/types/Region.ts, packages/manager/src/utilities/doesRegionSupportBlockStorage.ts
Migrates all types and functions from the `/regions` directory
=> [SDK] Change: Migrate all /regions functions and types

packages/linode-js-sdk/yarn.lock, packages/manager/src/components/Placeholder/Placeholder.tsx, packages/manager/yarn.lock
Fixes issue with Placeholder missing `key` prop
=> Fix: Error with Placeholders missing key prop

packages/linode-js-sdk/src/firewalls/firewalls.ts, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, packages/manager/src/store/authentication/authentication.test.ts, packages/manager/src/store/firewalls/firewalls.actions.ts, packages/manager/src/store/firewalls/firewalls.reducer.ts, packages/manager/src/store/firewalls/firewalls.requests.ts, packages/manager/src/store/image/image.reducer.ts, packages/manager/src/store/index.ts, packages/manager/src/store/types.ts
=> Add: Firewalls to Redux

packages/manager/package.json, packages/manager/src/components/Forms.stories.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/components/Radio/Radio.stories.tsx, packages/manager/src/components/TaxBanner/TaxBanner.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Dashboard/Dashboard.tsx, packages/manager/src/themeFactory.ts, packages/manager/yarn.lock
Let's do this now to grab a couple goodies and avoid bigger updates in the future. Nothing breaking from what I could see, fixed some regression with the tabs, other than that just a couple wrong types. We're getting a few new components I am interested in working with (skeleton in particular).
`yarn clean` would be necessary here to test
=> M3-3273 Update MUI to 4.4.2

package.json, packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts, packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
- fixed cancel button text to say "reset" in creation page
- fixed button (no stackScript) to go through the router
- Improve loading pattern 
=> M3-3284 Improve stackscripts creation workflow

packages/manager/src/MainContent.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Account/index.tsx, packages/manager/src/features/Firewalls/FirewallLanding.tsx, packages/manager/src/features/Firewalls/index.tsx
Adds Firewall Landing with Routing!
The big change here is in the PrimaryNav component. I wanted an easier way to add nav items between other items, without having to do `if(something) {  list.push(newNavItem }` which was getting a little verbose and frankly is a slower solution than the one proposed.
=> Add: Firewall Landing and Routing

package.json, packages/manager/src/features/Dashboard/Dashboard.test.tsx, packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, packages/manager/src/features/TagImport/TagImportDrawer.test.tsx, packages/manager/src/store/tagImportDrawer/index.test.ts, packages/manager/src/utilities/errorUtils.ts
Fixes `e.filter is not a function` Sentry error.
Also adds color back to the `yarn start` commands!
=> Fix: Safely Handle Unauthed Errors

package.json, packages/manager/src/__data__/managedIssues.ts, packages/manager/src/assets/icons/ticket-blue.svg, packages/manager/src/assets/icons/ticket.svg, packages/manager/src/features/Managed/MonitorDrawer.tsx, packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx, packages/manager/src/features/Managed/Monitors/IssueCalendar.test.tsx, packages/manager/src/features/Managed/Monitors/IssueCalendar.tsx, packages/manager/src/features/Managed/Monitors/IssueDay.tsx, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx, packages/manager/src/features/Managed/Monitors/MonitorRow.tsx, packages/manager/src/features/Managed/Monitors/MonitorTable.tsx, packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx, packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx, packages/manager/src/features/Managed/SupportWidget.tsx, packages/manager/src/hooks/useTimezone.ts, packages/manager/src/store/managed/issues.actions.ts, packages/manager/src/store/managed/issues.reducer.ts, packages/manager/src/store/managed/issues.requests.ts
Rebuild of #5471 to fix the commit history. Copied description:
Complete the Managed issue history drawer.
It turns out that Classic does not differentiate between open and closed issues, so the work I did in the reducer to request the actual tickets (to check for status/date closed) is not strictly necessary for this step. Jay suggested using the information on the landing list page, though, and it seems that Classic does make this distinction on their Managed dashboard, so I left the logic in pending feedback.
=> M3-692 rebuild

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, packages/manager/src/utilities/unitConversions.ts
Updating Linode Plan selection to utilize table component rather than selection card to simplify the experience. 
I also added an option to `convertMegabytesTo` util to remove the decimal place (maybe something like this exists already, and I am using the wrong util for this particular case?)
=> M3-3085 New Plan selection

package.json, packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
also aligned the create sidebar with content to be consistent with linode create workflow
=> M3-3298 Fix layout issue with nodeBalancers create

packages/manager/src/MainContent.tsx, packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
Route user to their ticket after they open one.
Kept some stuff commented out, pending how the review goes.
=> Change: Route Unactivated User to Ticket Detail After Ticket Submission

packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
=> Remove Unused Code

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Follow-up modifications to chip display and radio for Resize.
-Non breaking change ('update')
=> M3-3087 Follow up for chip display on resize

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
/linodes/create
- Bug fix ('bug')
=> M3-3338 Fix duplicate key issue with select plan tabbed panel

packages/manager/src/__data__/firewalls.ts, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, packages/manager/src/components/Table/Table.tsx, packages/manager/src/components/Table/index.ts, packages/manager/src/components/TableSortCell/TableSortCell.tsx, packages/manager/src/components/TableSortCell/index.ts, packages/manager/src/features/Firewalls/FirewallLanding.tsx, packages/manager/src/features/Firewalls/FirewallTable.tsx, packages/manager/src/features/Firewalls/FirewallTableRows.tsx, packages/manager/src/features/Firewalls/index.tsx, packages/manager/src/store/firewalls/firewalls.reducer.ts, packages/manager/src/store/image/image.reducer.ts, packages/manager/src/store/types.ts
Adds the darn table for Firewalls
=> Add: Firewall Landing and Table

packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx
We should as often as possible use link VS onClick for routing menu items
=> M3-3299 update add new menu to use links VS onClick for routing

packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
Allows the flag to stay in view after the user has made a selection, as we already do for images.
=> Change: Use single value component for region select

packages/linode-js-sdk/src/firewalls/types.ts, packages/manager/src/features/Firewalls/FirewallActionMenu.tsx, packages/manager/src/features/Firewalls/FirewallTableRows.tsx
Adds the Action Menu to Firewall Landing
=> Add: Firewall Action Menu

packages/linode-js-sdk/REACT.md, packages/linode-js-sdk/README.md
Updates the SDK docs with some React/TypeScript usage examples and better contributing wordage.
I'm getting excited. This is starting to become a real thing!!!!
=> Change: SDK Docs

packages/linode-js-sdk/src/firewalls/types.ts, packages/manager/src/__data__/firewalls.ts, packages/manager/src/store/firewalls/firewalls.actions.ts, packages/manager/src/store/firewalls/firewalls.reducer.test.ts, packages/manager/src/store/firewalls/firewalls.reducer.ts
Turns out `firewalls.rules` is an object and not an array.
I updated the mock data and reducer to reflect this and added reducer tests to make sure the output is good.
=> Change: Firewall Types

packages/manager/src/IdentifyUser.tsx
This just moves existing data we've already been sending to a new field.
=> Use Linode username for LD name field

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx, packages/manager/src/features/ObjectStorage/requests.ts, packages/manager/src/features/ObjectStorage/utilities.test.ts, packages/manager/src/features/ObjectStorage/utilities.ts
~**WAIT FOR https://github.com/linode/manager/pull/5507 TO MERGE.**~ DONE
This PR allows you to delete objects from your bucket. 
**NOTE:** It isn’t currently possible to delete “folders”.
**NOTE:** I had to borrow some code from another open PR... thus the first two commits of this PR will need to be rebased/dropped after https://github.com/linode/manager/pull/5507 is merged. (DONE)
**To test:**
There are a few new unit tests. To test functionality, try to delete some objects from your bucket. To handle all kinds of cases, delete objects from deep folders, shallow folders, shallow buckets, etc.
**Pro tip:** if you need to upload some files to your bucket, use: https://github.com/linode/manager/pull/5507.
=> OBJ-59 Add ability to delete objects

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx, packages/manager/src/utilities/ga.ts
Adds "Download" to the Object Action Menu. 
See the ticket for a summary of research about the method I chose to do the download. Definitely open to feedback here. 
Note: Cmd+Clicking is possible (will open the file in a new tab, if it's a filetype the browser recognizes).
Please try different file types, browsers, etc.
=> OBJ-246 File downloads

packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx
=> Change: Stop Hardcoding Status Link

packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
Fixes uncontrolled console warning
=> Fix: Uncontrolled Input Warning

packages/manager/src/components/TextField.tsx
=> M3-3387 Fix bug with create workflow password input placement

ci-environment-test.yml, package.json, packages/manager/e2e/config/wdio.conf.js, packages/manager/e2e/pageobjects/configure-linode.js, packages/manager/e2e/specs/create/clone-from-existing-linode.spec.js, packages/manager/e2e/specs/create/create-from-stackscript-with-tags.spec.js, packages/manager/e2e/specs/create/create-linode-from-stackscript.spec.js, packages/manager/e2e/specs/create/create-linode.spec.js, packages/manager/e2e/specs/create/smoke-create-volume.spec.js, packages/manager/e2e/utils/cred-store.js
all create specs updated and passing or skipped
1. `yarn up`
cd into packages/manager
`yarn e2e --dir create` will run all of the tests in the create folder, takes ~5 minutes
To run the individual tests:
`yarn e2e --file create/create-linode.spec.js`
These are the 4 …
=> updated create test specs

packages/manager/src/features/Account/EnableManaged.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedChartPanel.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/MonitorTickets.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Review feedback and other changes:
- Update chart colors to match corresponding Linode charts
- Fix punctuation in the enable panel on /account/settings
- Fill in link to support ticket
- Change name to Linode Managed
=> [For release] Fix: managed dashboard

packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDisplayDialog.tsx
=> M3-3363 Update OBJ access key creation message

packages/manager/e2e/config/custom-commands.js, packages/manager/e2e/pageobjects/domain-detail/detail.page.js, packages/manager/e2e/pageobjects/list-domains.page.js, packages/manager/e2e/specs/domains/detail-add-records.spec.js, packages/manager/e2e/specs/domains/domains-listed-alphabetically.spec.js, packages/manager/src/components/TextField.tsx
all domain tests passing or skipped
1. `cd packages/manager`
2. `yarn up`
3. `yarn selenium`
4. `yarn e2e --dir domains`
Use `yarn e2e --file domains/smoke-list-domains.spec.js` to run individual specs
=> M3-3375-domain specs 

packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedChartPanel.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard.tsx
Forces the chart to have a 300px height.
=> Fix: Managed Graph Height

packages/manager/src/components/core/Divider.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx, packages/manager/src/features/Longview/LandingContent.tsx, packages/manager/src/features/Longview/LongivewLanding.test.tsx, packages/manager/src/features/Longview/LongviewLanding.tsx, packages/manager/src/features/Longview/index.tsx, packages/manager/src/themeFactory.ts
Adds initial work for Longview Landing
=> Add: Longview Landing Skeleton

packages/manager/src/eventMessageGenerator.ts
Generate human-readable strings for Longview Events.
=> Change: Parse Longview Events

packages/manager/src/constants.ts, packages/manager/src/features/Longview/longviewRequests.ts
Jared's feature branch - just gonna merge this once the build passes because I need these functions.
=> Add: Types and helper methods for working with the Longview API (#5502)

packages/linode-js-sdk/src/index.ts, packages/linode-js-sdk/src/longview/index.ts, packages/linode-js-sdk/src/longview/longview.schema.ts, packages/linode-js-sdk/src/longview/longview.ts, packages/linode-js-sdk/src/longview/types.ts, packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx, packages/manager/src/features/Longview/AddClientDrawer.tsx, packages/manager/src/features/Longview/LandingContent.tsx, packages/manager/src/utilities/errorUtils.ts
Adds the Longview Create Drawer
I also added better typing to `getErrorMap` so that it will infer the strings you pass as the second argument.
=> Add: Longview Add Client Drawer

packages/linode-js-sdk/src/longview/longview.ts, packages/manager/src/containers/longview.container.ts, packages/manager/src/features/Longview/LandingContent.tsx, packages/manager/src/store/index.ts, packages/manager/src/store/longview/longview.actions.ts, packages/manager/src/store/longview/longview.reducer.ts, packages/manager/src/store/longview/longview.requests.ts
Adds Redux State and Container for Longview Clients
=> Add: Longview Redux State and Container

packages/manager/src/containers/longview.container.ts, packages/manager/src/features/Longview/LandingContent.tsx, packages/manager/src/features/Longview/LongviewTable.tsx, packages/manager/src/features/Longview/LongviewTableRows.tsx
Adds the table that displays the list of Longview Clients
=> Add: Longview Table
