src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/utilities/getLinodeInfo.test.ts, src/utilities/getLinodeInfo.ts
When navigating to the Create From Backup tab from the Backups tab
(the action menu for a particular snapshot), the Linode that the
backup came from was pre-selected, but the event handler for Linode
selection was not being run. Information about the selected Linode was
therefore not available in state.
Added a check to cDM to avoid this situation.
1. Create a large Linode (e.g. 8GB)
2. Create a snapshot
3. When the snapshot finishes, click on "Deploy to New Linode" from its action menu
4. Observe: you should see the smaller plans (2GB and 4GB) disabled in the list of available plans.
=>  M3-1629 Fix bug in deploy Linode from backup flow

src/components/DebouncedSearchTextField/DebouncedSearchTextField.spec.js, src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx, src/components/DebouncedSearchTextField/StoryComponents/SelectExample.tsx, src/components/DebouncedSearchTextField/StoryComponents/TextFieldExample.tsx, src/components/EnhancedSelect/components/NoOptionsMessage.tsx
* Added functional tests for the debounced search component stories
* Updated the examples return results in `800` ms instead of `2000` ms. 
* Added data-qa attributes to the tests
* Disabled the clear test on the select field suite, need to chat with @martinmckenna as to why clearing the select does not seem to reset the selected item state
```bash
yarn storybook:e2e --story DebouncedSearchTextField
```
=> M3-1675 - Debounced Search Functional Tests

e2e/config/wdio.conf.js, e2e/config/wdio.storybook.conf.js, integration-test.yml, storybook-test.yml
* Updates the `integration-test.yml` docker compose file to use selenium-hub instead of selenium-standalone.
* Adds chrome selenium-node image to `integration-test.yml` to connect to selenium hub (this allows scaling the number of chrome nodes to enable parallel tests, each running in their own container
* Updated the wdio config files to no longer reference `selenium-standalone` as the host name for selenium when running via docker. It's now simply "selenium" since the storybook tests when running via docker still use standalone (for the time being, but these could also be updated to use hub, will create a ticket)
PM me for the results of these changes running on CI.
=> M3-1735 - Enable Parallel browsers on CI

src/features/TopMenu/SearchBar/SearchBar.tsx
* Changes `Nodebalancers` to `NodeBalancers`
* Checked the code base for other instances of this spelling, none were found.
=> Fix NodeBalancer case in Search Placeholder

package.json, scripts/jira-changelog.sh, scripts/pre-push.sh, yarn.lock
* This PR adds a helper script that will output the commits in a new version that contain JIRA tickets in the Commit name and PR's that do not contain JIRA tickets. The purpose is for QA and Product Ownership to easily track changes that get into the manager project but are not documented in JIRA).
* I have also added a new module for githooks in the project called Husky. This allows us to have pre-push hooks, along with pre-commit and all the other hooks available in git.
I've set up a pre-push hook that will prevent pushing a branches that don't include a manager ticket in the branch name. This can be overridden with `--no-verify`. I figured this would be a good way to enforce JIRA as the single source of truth of what work goes into the Manager project.
However, if we find this …
=> M3-1747 - Add JIRA changelog comparison tool, Add Pre-push hook

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx
Remove stats panels from accordions on the Linode detail page.
- Refactored the ExpansionPanels into a smaller StatsPanel component that uses Paper.
- Each Panel includes loading and error states, which may not be ideal.
- Restored statsInterval call, so stats will be reloaded every 30 seconds. Loading spinner is only shown on the initial load.
=> M3-1751 remove linode accordions

src/themeFactory.ts
Some legacy table headers still have an explicit height assigned to them from MUI. This PR removes that in order to remove MOAR whitespace.
=> M3-1752 - remove explicit height on table headers

src/components/DebouncedSearchTextField/DebouncedSearchTextField.spec.js, src/components/EnhancedSelect/Select.tsx, src/components/TextField.tsx, src/features/Help/Panels/AlgoliaSearchBar.tsx, src/features/linodes/LinodesDetail/HeaderSections/TagsPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx
While the css 'bracket' targeting works locally, once compiled, we lose the styling that is being applied to material ui elements. The solution was to add a class globally to the base component itself and styling their usage in specific, custom components. 
Algolia Search:
Before:
After:
Tag Selects (note there is related work forthcoming for this component):
Before:
After:
=> M3-1717 Support search results list is too wide on production builds

scripts/pre-push.sh
* Updating your remote fork (or pushing a release/master branch) was prevented by the pre-push hook (since these do not have jira tickets in their branch names). 
* Updated the pre-push hook regex to allow for master/develop/release- branch names
=> M3-1767 - Update pre-push hook to allow develop, master, release branch names

e2e/config/browser-config.js, e2e/setup/cleanup.js, e2e/setup/setup.js
* Adds a custom user agent to browser configs and axios requests (now includes `WebdriverIO`) this will allow us to filter out e2e test runs from our API usage reporting. 
In a spec file, after the `browser.url()` command, add:
```javascript
browser.debug()
```
* Run the modified test spec with `yarn e2e --spec=e2e/specs/path/to/spec.js` 
* Once the debug REPL is available, open the browser's dev tools and look at the request headers for individual requests in the network tab.
* Confirm WebdriverIO is in the user-agent header
* Run the same test in Firefox ``yarn e2e --spec=e2e/specs/path/to/spec.js --browser=firefox` 
* Confirm WebdriverIO is in the user-agent header
=> M3-1784 - Add WebdriverIO user agent to requests/browser settings

e2e/config/custom-commands.js, e2e/pageobjects/linode-detail/linode-detail-backups.page.js, e2e/pageobjects/linode-detail/linode-detail-settings.page.js, e2e/pageobjects/page.js, e2e/specs/create/smoke-configure-linode.spec.js, e2e/specs/linodes/detail/backups.spec.js, e2e/specs/linodes/detail/smoke-settings.spec.js, e2e/specs/nodebalancers/error-handling.spec.js, package.json
* Updates form validation assertions in the e2e tests (related to the API Wrapper refactor)
* Added a "tryClick" custom command that attempts to click an element for a given timeout and will display the selenium stacktrace if the timeout is exceeded (needed to address test failures when attempting to click the Create button in the header in the beginning of a test)
```bash
yarn && yarn start  # Run your local manager
yarn selenium # start selenium in a separate shell
yarn e2e:modified
```
=> M3-1763 - Update test form validation assertions, general e2e test maintenance

src/features/linodes/LinodesLanding/powerActions.ts, yarn.lock
This PR fixes a bug that prevented users from booting a linode into a specific configuration profile.
The solution was to pass in a `config_id` argument to the existing `linodeBoot` API method. 
**Steps to reproduce bug:** 
_Prerequisites:_
- Have a Linode with at least two configuration profiles with different distros. In this example we’ll use CentOS and Ubuntu. 
- Have `develop` branch checked out.
_Steps:_
1) Power down linode
2) Power on linode and use CentOS config profile
3) SSH into the linode
4) Enter `cat /etc/os-release | grep ^NAME=`
5) Observe: the terminal will print `NAME="CentOS Linux”`
6) Power down linode
7) Power on linode and use Ubuntu config profile
8) SSH into the linode
9) Enter `cat /etc/os-release | grep ^NAME=`
10) Observe: the terminal will AGAIN print …
=> M3-1722 Boot into different config profiles

src/features/linodes/LinodesLanding/withUpdatingLinodes.tsx
The `componentDidUpdate` method was resetting linodes data upon each update which resulted in inconsistent status.
The fix makes sure that linodes data from state takes priority over the one from props.
=> M3-1671: fix linodes status update upon creation

src/components/CheckoutBar/CheckoutBar.tsx, src/components/DisplayPrice/DisplayPrice.test.tsx, src/components/DisplayPrice/DisplayPrice.tsx, src/components/DisplayPrice/index.tsx, src/constants.ts, src/features/Volumes/VolumeDrawer.tsx, src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx, src/features/linodes/LinodesDetail/LinodeVolumes/VolumeDrawer.tsx
* Refactored the price display code in CheckoutBar.tsx to a new component
(for consistent styling of prices).
* Used the new component in VolumesDrawer (both of them) to give feedback
on the price of the volume to be created.
* This information is displayed on creation and resize.
* Added copy to help users understand the pricing
* Adjusted GB to GiB
=> M3-1650 volume drawer pricing

e2e/config/wdio.axe.conf.js, e2e/utils/config-utils.js
* Updates Wdio accessibility testing config to override the wdio test hooks that were previously being inherited from the base configuration.
* Updates the login method to store the token if provided a cred path, overwise, the token will not be stored (we don't need to store tokens for accessibility testing)
=> M3-1794 - Fix automated accessibility testing config

src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/index.tsx, src/components/EditableText/EditableText.spec.js, src/components/EditableText/EditableText.tsx, src/features/Domains/DomainDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/linodes/LinodesDetail/HeaderSections/LabelPowerAndConsolePanel.tsx, src/features/linodes/LinodesDetail/HeaderSections/TabsAndStatusBarPanel.tsx
This PR includes a new Breadcrumb component with the following shape:
```javascript
<Breadcrumb
linkTo="/linodes"
linkText="Linodes"
label="test-linode-001"
/>
```
Which looks like: 
You can also pass in `onCancel()` and `onEdit()`, which will make the text editable:
Passing in `labelLink` (a string) is also possible (this will wrap the label in a link).
~Currently styling is non-existent: margins, padding, placement, etc. need some work. In accordance with the epic (M3-1468), hover states, borders, etc. need adjustments as well.~
EDIT: I added some basic styling, but it still needs tweaking.
I implemented the new Breadcrumb component on **Domains** (M3-1537), **Linodes** (M3-1536), and **NodeBalancers** (M3-1538) on this PR so that the component could be seen in the context of the app.
=> M3-1540 breadcrumb component

src/components/PrimaryNav/PrimaryNav.tsx, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/features/TopMenu/UserMenu/UserMenu.tsx
This PR does:
- keep the create button on all viewports
- hides the user icon on mobile sizes
- add the user profile and logout link in sidebar menu on mobile
=> M3-1683 User links in sidebar on mobile

scripts/jira-changelog.sh
* Refactored the changelog script to be more useful 
* `--no-merges` is the same as `set-max-parents=1`
* Default second argument to HEAD (For comparing Previous version to now)
```bash
yarn compare v0.38.1
yarn compare v0.37.0 v0.38.0
```
=> M3-1829 - Changelog comparison script fixes/enhancements

src/App.tsx, src/components/CircleProgress/CircleProgress.tsx, src/features/Account/AccountLanding.tsx, src/features/Account/AutoBackups.tsx, src/features/Account/GlobalSettings.tsx, src/features/Account/index.tsx, src/features/Backups/AutoEnroll.test.tsx, src/features/Backups/AutoEnroll.tsx, src/features/Backups/BackupDrawer.test.tsx, src/features/Backups/BackupDrawer.tsx, src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.test.tsx, src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.tsx, src/features/Dashboard/BackupsDashboardCard/index.tsx, src/features/Dashboard/Dashboard.test.tsx, src/features/Dashboard/Dashboard.tsx, src/features/Dashboard/DashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/Users/UserProfile.tsx, src/store/ApplicationState.d.ts, src/store/reducers/backupDrawer.test.ts, src/store/reducers/backupDrawer.ts
* Add BackupsDashboardCard component
* Connect to Redux
* render conditionally based on manged, backups_enabled, and the
existence of Linodes without backups
* BackupDrawer now calls both /account/settings and linodes/*/backups-enable on Submit. I chose to do this in series: if the call to settings (the toggle at the bottom of the drawer) fails, the submit process will stop, an error will be displayed, and the user can retry.
* Everything in the drawer is reduxed to connect with the accountSettings reducer (which needs to be updated) and handle the drawer open/close state adjustments needed.
=> M3-1793 Add CTA to dashboard

src/components/EventListItem/EventListItem.stories.tsx, src/features/Profile/LishSettings/LishSettings.tsx, src/features/Profile/Settings/Settings.tsx, src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx, src/utilities/promiseToObservable.ts, tslint.json
Importing `rxjs`, `@material-ui/core`, and `@material-ui/icons` directly significantly and unnecessarily increase individual chunk sizes.
=> M3-1855 Prevent import of non-shakeable libraries.

src/features/linodes/LinodesLanding/IPAddress.tsx
Currently, a linode's **private** IP is shown by default on Linodes Landing and Linodes Detail. We'd like to show the **public** IP by default. 
We're using the JS native `sort()` function to sort an array of a Linode's IPs, with a custom compare function that is supposed to sort private IPs at a lower index than public IPs.
But `sort()` is not guaranteed to be consistent across browsers. MDN documentation on `Array.prototype.sort()`:
> If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAscript standard does not guarantee this behaviour, and thus not all browsers (e.g. Mozilla versions dating back to at least 2003) respect this.
This explains why this behavior was different in Firefox. …
=> M3-1827 Show public IP before private IP

src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesDetail/HeaderSections/TabsAndStatusBarPanel.tsx, src/services/linodes/linodes.ts, src/services/volumes/volumes.schema.ts
We duplicated a significant amount of code between VolumesLanding and LinodesVolume, both were features that displayed a paginated table of Volumes and provided means by which a user could start creation. 
To DRY things up a bit, I've updated the configured request in VolumesLanding to update a few things based on existence of the linodeId React Router match param.
- Request is updated to request the Linode's volumes, rather than all volumes
- Region is hidden if the linodeId is found.
- Attachment is hidden if the linodeId is found.
I intend to remove the LinodeVolumes and ancillary components once everything is reviewed and styled.
=> M3-1515 Unified List Volumes Component

e2e/pageobjects/configure-stackscript.page.js, src/components/Breadcrumb/Breadcrumb.tsx, src/components/EditableText/EditableText.tsx, src/features/StackScripts/StackScriptCreate/StackScriptCreate.test.tsx, src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.test.tsx, src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx
This PR adds the Breadcrumb component to the `Create` and `Edit` StackScript pages. These changes are purely presentational.
@alioso and @WilkinsKa1 I added `20px` of bottom margin between the Breadcrumb and the rest of the component. I was just eyeballing it, so I'd appreciate your input.
=> M3 1542 Breadcrumb on StackScriptCreate and StackScriptUpdate

src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.test.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
On the Dashboard, replace the displayed bandwidth usage value with a percentage.
For values less than 1%, use a less-than sign
=> M3-1818 Display network usage as a percentage

src/components/ActionMenu/ActionMenu.tsx, src/features/Volumes/VolumesLanding.tsx
Updated the styling based on view, so the columns will be wider on `linodes/id/volumes` view than they are on `/volumes` (as they presently are today). I also updated the action menu padding, it was inheriting a new MUI style that was messing up alignment throughout the app.
=> M3-1515 Create a unified volumes table- Styling Updates

src/App.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/Domains/DomainsLanding.tsx, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/store/ApplicationState.d.ts, src/store/index.ts, src/store/reducers/domainDrawer.test.ts, src/store/reducers/domainDrawer.ts
This PR makes is so that `DomainCreateDrawer` closes upon success (after creating or cloning a domain). 
Making this change was challenging because we navigate to `DomainDetails` upon success. BUT at the same time, we also need to close the drawer. 
We currently have two instances of `DomainCreateDrawer`. The one mounted on `AddNewMenu` plays nicely with this change, because that component is top-level, i.e. the routing change didn't affect it.
But the drawer mounted on `DomainsLanding` doesn't work with this change, because once the routing changed happens, _the drawer isn't mounted anymore._ This means that it simply disappears, which looks very choppy.
My proposal is to have ONE `DomainCreateDrawer` which is at the App level (similar to `VolumeDrawer`). This means routing changes won't …
=> M3 1769 Dismiss domain create drawer

e2e/config/custom-commands.js, e2e/pageobjects/account/global-settings.page.js, e2e/pageobjects/configure-linode.js, e2e/pageobjects/dashboard.page.js, e2e/pageobjects/enable-all-backups-drawer.js, e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/page.js, e2e/setup/setup.js, e2e/specs/globalsettings/auto-backup-enrollment.spec.js, e2e/utils/common.js, e2e/utils/config-utils.js, scripts/e2e-modified.sh, src/features/Account/AutoBackups.tsx, src/features/Account/NetworkHelper.tsx, src/features/Backups/AutoEnroll.tsx, src/features/Backups/BackupDrawer.tsx, src/features/Backups/BackupLinodes.tsx, src/features/Backups/BackupsCTA.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx
**Purpose**
Added tests for the auto enroll in backups for future linode global setting, dashboard backup CTA, linodes backup CTA, and enroll existing linode for backups features.
**To Test**
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e:modified`
=> M3-1889 tests for auto backup enrollment M3-1789 and M3-1793 

src/features/linodes/DiskSelect/DiskSelect.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx, src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/features/linodes/LinodesDetail/LinodeVolumes/VolumeDrawer.tsx, src/themeFactory.ts
I added a class to hide the placeholder in the drop down menu once and once a selection is made it won't reappear. I only targeted selects that need a required value. This is more of a hack as the placeholder are currently not well supported. See: https://github.com/mui-org/material-ui/issues/8813
=> M3-1792 Select placeholders display

src/features/TopMenu/SearchBar/SearchBar.tsx
Adds searching by tag for NodeBalancers.
Uses temporary fallback with an empty array while we don't get that from the API.
=> M3-1904: add search by tag for NodeBalancers

src/components/EnhancedSelect/components/MultiValue.tsx, src/components/ShowMore/ShowMore.test.tsx, src/components/ShowMore/ShowMore.tsx, src/components/Tag/Tag.tsx, src/components/Tags/Tags.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/themeFactory.ts
This PR covers few stories related to the display of tags through the app:
- Show More tag wrapping
- Show more popup placement
- Chip markup (changed from button to div unless clickable)
- Chip padding and font-size
- Styling error on theme switch with Show More button
=> M3-1871 Improve Tags styling

src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Users/UserDetail.tsx, src/features/linodes/LinodesDetail/HeaderSections/LabelPowerAndConsolePanel.tsx
This PR adds the Breadcrumb component to UserDetails. This required changing the ever-evolving Breadcrumb component to accept a “label prefix component” which is rendered preceding the label. 
Further changes were made to the Breadcrumb API to keep it organized. The `labelSubtitle` and `labelLink` properties are moved to a new, optional `labelOptions` prop with the following shape: 
```
linkTo?: string;
prefixComponent?: JSX.Element | null;
subtitle?: string;
```
@alioso and @WilkinsKa1, it’d be great if one of you could have a look at this. I made a few styling adjustments so that the user icon comes in smoothly.
=> M3-1901 Breadcrumb component on User Details

src/components/EnhancedSelect/Select.tsx
Tags on search will wrap now, along with a few other adjustments:
=> M3-1869 Tags going off screen in search bar

src/features/linodes/LinodesLanding/IPAddress.tsx
Covers all three sorting cases: items are equal in rank, either of items has higher rank
=> M3-1827: update IP sorting function to cover equal items

src/features/Search/HiddenResults.test.tsx, src/features/Search/HiddenResults.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx
* Link to results page is first option in results dropdown,
rather than last
* Change Show More to Show All on results page HiddenResults buttons
=> M3-1945 Search bar: sprint review feedback

src/components/Notice/Notice.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/themeFactory.ts
Adding word break to notice component text so that long, unbreakable strings will wrap to next line and the notice containers aren't overflowed/scrollable.
=> M3-1948 Scroll regression on personal access token modal

src/features/linodes/LinodesDetail/LinodesDetail.tsx
A general-purpose error is being displayed from the mutations drawer whenever a mutation fails for any reason. This error includes the text "please try again," which in some cases (e.g. the Tokyo region) is misleading, as mutations will never succeed in those cases. It's been recommended that we pass on whatever error the API returns.
1. Use Charles to change the type of a Linode to e.g. g5-standard-1.
2. From that Linode's detail page, click the mutation banner to open the drawer, then click "Enter Queue".
3. Observe: in develop, a generic error message is displayed; on this branch, "No Mutation Pending" should be shown.
Better, more generic error handling would be helpful here, but proved too involved to include in this PR. Will do a POC later this week.
Changed:
LinodesDetail mutation …
=> M3-1946 Fix mutation error handling

src/features/Backups/BackupDrawer.test.tsx, src/features/Backups/BackupDrawer.tsx, src/store/ApplicationState.d.ts, src/store/reducers/backupDrawer.test.ts, src/store/reducers/backupDrawer.ts
Generic error message Notice when some backups had failed and others succeeded was confusing. This PR adds a more detailed message indicating how many Linodes had backups enabled successfully, and how many failed. Individual error message for each failed Linode are unchanged.
Changed
- Track number of updated Linodes in backupDrawer reducer
- Include number of successes and failures in error and success messaging in BackupDrawer.
The text wrapping within the Notice is on Alban's radar, should be fixed soon.
=> M3-1888 Report counts of successes and failures for backups

src/features/Volumes/WithEvents.tsx
It was found that the volumes landing was not being updated after a volume clone requests completed.
=> M3-1742 Refresh volumes list on volume_clone event.

src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx, src/features/Volumes/VolumeDrawer/ResizeVolumesInstruction.tsx, src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx, src/store/reducers/volumeDrawer.ts
Provide instructions for users after submitting a request to resize a volume.
I updated the openForCreating to use `typescript-fsa`. I was going to update the entire reducer, but I wanted to keep the PR relatively small.
=> M3-1800 Display resize instructions on form submission.

src/components/Notice/Notice.tsx, src/features/Profile/APITokens/APITokenDrawer.tsx, src/features/Profile/APITokens/APITokenTable.tsx
We have a default word break on the notices for just one edge cases. we needed to add that as a prop and add it only when necessary (Personal Access Tokens modal key)
=> M3-1983 Add break-word support as a prop for notices

src/features/Volumes/VolumeDrawer/SizeField.tsx
Remove redundant form helper text for volume size when creating a volume. Helper text will still appear on the resize volume drawer (as it includes a reminder that volumes can't be sized down).
changed
- Remove helper text from size field when creating a Volume
=> M3-1979 Remove size helper text from create volume form

src/components/TagsPanel/TagsPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
Previously, NodeBalancer tag errors were appearing as toasts.
We remove the toast handler because the inline error is handled natively in the TagsPanel component
There's an API issue currently that deals with tag error handling.
NodeBalancers and Volumes return this error format:
`nth is a duplicate tag ` which to the user looks like `Tag 1 is a duplicate tag`
while Linodes and Domains errors return 
`An entity may not have the same tag twice`
There is an API ticket open to resolve this. see ARB-1016 and ARB-1017
=> M3-1985 Fix NodeBalancer Tag Error

src/components/Pagey/Pagey.ts, src/components/Pagey/index.ts, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/LinodesViewWrapper.tsx
add: Enable sorting of the Linodes landing table by Linode labels.
Story for adding ordering by region M3-1989 was found to be blocked.
=> M3-1583 Add sorting by label to Linode landing table view.

.storybook/config.js, package.json, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tags/Tags.tsx, src/components/TagsPanel/TagsPanelItem.tsx, src/features/Search/ResultRow.tsx, src/features/StackScripts/LandingPanel/Table/TableRows/TableRows.test.tsx, src/features/TopMenu/SearchBar/SearchSuggestion.tsx, src/storybook.d.ts, yarn.lock
added:
- storybook-router-react added as a dev dependency (allows using a router decorator
so that stories for components with Router don't break)
changed:
- Tag is now a routable component
- Make tags clickable in Tags.tsx and SearchSuggestion.tsx
- Update tests
- When clicked, a Tag will link to the search results page for its label
(i.e. /search/?query=tag-name)
=> M3-1988 Tag links

src/features/Profile/Settings/Settings.tsx
we send notifications for other things, e.g. events. this also matches up with the description from the API docs:
https://developers.linode.com/api/v4#operation/getProfile
=> Update email notification setting label for clarity

src/components/StackScript/StackScript.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/store/reducers/backupDrawer.ts, src/utilities/analytics.ts, src/utilities/getAll.ts
Log to Google analytics how many entities we are requesting when we make a network request for all entities
* return API `results` meta data in the `getAll()` response
* Filtering out public images from the imageCount because there's no reason to include them in the total count
* Split the analytics tracking into buckets (i.e 1-10, 11-20, 21-50, etc)
* Also sent the actual number requested to analytics
* Typed the response of `getAll()`
* Typescript compiler was complaining about the rest parameter `...results` being typed as `any`, even though the linter thought otherwise. Not sure if this is a TS bug or I'm just doing something wrong.
1. Ensure the `REACT_APP_GA_ID` is in your `.env` file. Let me know if you need the ID for manager.dev.linode.com
2. Run the app and search for something …
=> M3-1939 Add analytics to GetAllEntities()

src/components/TableRow/TableRow.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx
We had reports of user experience inconsistencies for this component. clicking in some areas of the rows that were not CTAs would **not** trigger the row click. 
This PR fixes that as well as making sure sure that clicking on regular text triggers the row click while stopping propagation `<a>` and `<button>` tags and their children
=> M3-1916 Make clickable row UX more consistent

src/components/CircleProgress/CircleProgress.tsx, src/components/EnhancedSelect/Select.tsx, src/components/Tag/Tag.tsx, src/components/Tags/Tags.tsx, src/components/TagsPanel/TagsPanel.tsx, src/components/TagsPanel/TagsPanelItem.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx, src/features/TopMenu/SearchBar/SearchSuggestion.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/themeFactory.ts, src/themes.ts
This PR attempt to re-styles tags properly now that they are buttons. The goal was to achieve consistency across components and theme choice:
- check tags within tables (linodes, volumes for instance) and interact with them
- check their styling and behavior in enhanced selects (create a volume for instance)
- check their styles and behaviors on create and delete (linode detail)
- check all the above in both light and dark themes
=> M3-2004 Tag as Buttons styles refactor

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.test.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Addresses sentry error `No value passed to payment`
Turns out some people were getting to Paypal with an invalid USD amount
e: ugh formatting...the only lines that changed were 157-166 and 533 onward
=> M3-2017 Paypal Client-Side Validation

src/documentation.ts, src/features/Domains/DomainDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/Users/UsersLanding.tsx
Updated following files to point to Cloud Manager version of guides:
- `src/documentation.ts`
- `src/features/Domains/DomainDetail.tsx`
- `src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx`
- `src/features/Users/UsersLanding.tsx`
=> Update docs links to Cloud Manager versions.

src/features/Volumes/VolumeAttachmentDrawer.tsx, yarn.lock
previously, when attaching a volume to a Linode with multiple configs, no `config_id` would be sent with the POST request, even though the user had selected it in the form.
Also, we were not properly resetting default state on drawer close
=> M3-2022 Send Linode Config Along with Attach Volume Request

src/components/AccessPanel/AccessPanel.tsx, src/components/ActionMenu/ActionMenu.tsx, src/components/EditableText/EditableText.tsx, src/components/PrimaryNav/ThemeToggle.tsx, src/features/Support/ExpandableTicketPanel.tsx, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/features/TopMenu/AddNewMenu/AddNewMenuItem.test.tsx, src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx, src/features/TopMenu/UserEventsMenu/UserEventsButton.tsx, src/features/TopMenu/UserMenu/UserMenu.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsButton.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
A few high level buttons were missing proper aria description. This PR improves the screen reader experience for all top menu items:
- create new menu (screen reading was stuck and tabulation was off)
- user menu button
- user events button
- user notifications button
- theme switch button (although not a button)
=> M3-1902 Improve button accessibility

ci-environment-test.yml, e2e/config/wdio.conf.js
Maintain the integration-test.yml to still run manager UI in a docker container with most recent changes, added ci-environment-test.yml to just have selenium and test runner container, then switch test job to linodemanager-e2e-v2.
=> Compose for running automation against specific environments

src/components/PaginationControls/PaginationControls.tsx, src/components/PaginationFooter/PaginationFooter.tsx, src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Images/ImagesLanding.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/Profile/SSHKeys/SSHKeys.tsx, src/features/StackScripts/LandingPanel/PanelContent.tsx, src/features/StackScripts/LandingPanel/Table/StackScriptTable.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx, src/features/Support/SupportTickets/TicketList.tsx, src/features/Users/UsersLanding.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDisks.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
Adds analytics events to track how users use pagination, search and how many use linodes grid view
- add pagination tracking to multiple components
- add StackScript search tracking
- add listView/gridView switch tracking for Linodes landing page
=> M3-1944: add GA events: view switch, pagination, stackScript search

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/TotalTraffic.tsx, src/utilities/statMetrics.test.ts, src/utilities/statMetrics.ts
This PR adds "Total Traffic" under Linode graphs.
It also changes the way AVERAGE and LAST are calculated. Previously, AVERAGE did NOT take in to account zero values, and LAST was the last non-zero value.
=> M3-1804 Add Total Traffic to stats

src/features/linodes/LinodesLanding/LinodeStatusIndicator.tsx, src/themeFactory.ts, src/themes.ts
Updated linode 'busy' icon color to be visible for dark theme.
=> M3-2027 Linode "Busy" icon invisible on Dark Theme Dashboard

src/features/Search/ResultRow.tsx
Remove redundant "created" text from search landing tables (as Created already occurs in table headers)
- Bug fix
=> M3-2038 remove created text

src/assets/icons/sort.svg, src/assets/icons/sortUp.svg, src/components/CircleProgress/CircleProgress.tsx, src/components/Pagey/Pagey.ts, src/components/Table/Table.tsx, src/components/TableSortCell/TableSortCell.tsx, src/features/StackScripts/SelectStackScriptPanel/PanelContent/StackScriptTableHead.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/LinodesViewWrapper.tsx, src/themeFactory.ts, src/themes.ts
Now that we are starting implementing sortable headers more on the APP, the pattern has been polished and we needed new styles. In addition to the new UI kit styles, I passed a new 'isSorting' prop in pagey in order to add visual indicators while the sorting is happening.
This can be tested on the main linode list view
=> M3-2029 Update styles for sortable headers

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/MetricsDisplay.tsx
Fix for Stats & Graphs device views, label and data should be displayed closer together so they're not too far apart. Please review display at multiple breakpoints. 
=> M3-2039 Fix breakpoint for larger mobile devices for stats & graphs

src/features/Search/SearchLanding.tsx
Sprint review feedback fixes
Changed: 
- NodeBalancer capitalization (should not be Nodebalancer)
- Increase default number of results from 5 to 25
=> M3-2050 search landing fix

src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/EditableText/EditableText.stories.tsx, src/components/EditableText/EditableText.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/linodes/LinodesDetail/HeaderSections/LabelPowerAndConsolePanel.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx
Fixes an issue where the EditableText was getting cancelled out of edit mode if an event came down
- fix
1. Start an event (such as resizing a Linode)
2. Try to edit the text
3. Keep the edit text state open
4. Wait for a new event to come down
5. Observe - the field stays in edit mode
Now try doing step 1 then go to a different Linode Detail page and repeat steps 2-5
=> Fix: Editable Text cancelling upon event stream updating

src/features/linodes/transitions.test.ts, src/features/linodes/transitions.ts, src/utilities/capitalize.test.ts, src/utilities/capitalize.ts
Updates transitionText method to ensure it returns a capitalized version of the event.
- Fix linode progress bar transition text casing
=> M3-2051: capitalize linode progress bar text

src/App.test.tsx, src/App.tsx, src/features/Dashboard/Dashboard.test.tsx, src/features/TagImport/TagImportDrawer.test.tsx, src/services/domains/domains.ts, src/store/ApplicationState.d.ts, src/store/reducers/resources/domains.ts, src/store/reducers/resources/index.ts, src/store/reducers/resources/linodes.ts, src/store/selectors/getEntitiesWithGroupsToImport.test.tsx, src/store/selectors/getEntitiesWithGroupsToImport.tsx
This PR caches Domains in Redux upon application load. Create/Update/Delete Domain events update the Redux store as well.
Load the application normally. If you have domains on your account, you should see them in the Redux store (use Redux dev-tools). Try updating, creating, and deleting domains, and you should see actions happening in Redux.
We should figure out a solution for using the methods in `src/store/reducers/resources/domains` with other types of entities. I basically copied over `./linodes` and had to make only minimal changes. A more generic solution would be ideal.
=> M3-1770 Domains in Redux

src/features/Account/GlobalSettings.tsx, src/features/Account/ImportGroupsAsTags.test.tsx, src/features/Account/ImportGroupsAsTags.tsx
For users that have dismissed the CTA on the Dashboard inviting them to import their CF manager display groups as tags, the import drawer will also be available from account/settings.
This is a lot of expansion panels that no one will ever collapse. We'll probably be asked to replace them with Papers at some point
=> M3-2044 Feature: import groups global settings

src/features/Dashboard/Dashboard.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.test.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.tsx, src/utilities/storage.ts
Users who don't want to be prompted to import their groups as tags can click on a close button on the dashboard CTA. This will hide the CTA, and save their choice to local storage so it won't display (on that browser) again.
1. Have at least one Linode with a display group (and no matching tag)
2. Visit the dashboard and observe that the CTA is displayed.
3. Click the X on the CTA
4. The CTA should be hidden
5. In the Application tab in devtools, you should also see that `importDisplayGroupsCTA` is set to 'true'.
=> M3-2073 update: Make cta dismissable

src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx, src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
Update SupportSearchLanding.tsx to use updated query-parsing helper methods.
- Bug fix
changed:
- Use `getQueryParam` in SupportSearchLanding
- Add component unit tests
The original bug noted in the ticket was fixed as a side effect of #4172 but that change also broke the logic for reading params into state in the support search landing page.
=> M3-1710 Fix search results query bug

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/utilities/statMetrics.test.ts, src/utilities/statMetrics.ts
There is a bug in production causing stats to crash in circumstances in which the API returns an empty array on `stats.data.cpu`, etc. This issue is addressed by rigorously checking input on the `getMetrics` function.
- bug-fix
=> Bug-fix: stats input checking

src/features/StackScripts/SelectStackScriptPanel/StackScriptsSection.tsx, src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
Fixes issue where app would crash if a StackScript has an array of images in which one element is `null`
This is a super-edge case and probably isn't affecting most people, since we're already filtering out StackScripts that have solely deprecated images
- Bug fix
Not really sure how a stackscript can end up with a `null` image but....
=> Fix Handling of Null StackScript Images

src/features/Users/UserProfile.tsx, src/features/Users/UsersLanding.tsx
The notice of a successful deletion was inadvertently deleted during the pagination refactor. This adds a notice back in, in the form of a toast for better user experience.
- Bug fix.
Delete a user, see a toast. Enjoy.
=> fix: Display notice on successful deletion of a user.

src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx, src/utilities/capitalize.ts
The mode toggle was being displayed in the disk drawer when renaming or resizing, which is confusing because you can't change the image once a disk has been created.
- Bug fix
Also changed the names of the confirmation buttons so we don't use Submit
=> M3-2089 Fix: disk drawer

src/features/Account/GlobalSettings.tsx, src/features/Account/ImportGroupsAsTags.tsx, src/features/Dashboard/Dashboard.tsx, src/features/TagImport/TagImportDrawer.tsx, src/store/reducers/tagImportDrawer.ts, src/store/selectors/getEntitiesWithGroupsToImport.tsx, src/utilities/shouldDisplayGroupImportCTA.ts, src/utilities/storage.ts
The logic for displaying the Group Import CTA on the DASHBOARD is as follows:
- IF the user has never imported groups before
- AND the user hasn’t dismissed the CTA
- AND the user has groups to import 
- THEN we display the CTA 
The logic for displaying the Group Import setting in GLOBAL SETTINGS is as follows:
- IF the user has never imported groups before
- AND the user has groups to import
- THEN we display the setting
- change
=> change group import CTA logic

src/store/reducers/tagImportDrawer.ts
Fixes a bug where Local Storage was still set if there were errors during group import.
1) Have Linodes with groups to import. 
2) Click the "Import Display Groups" CTA button.
3) Enable request blocking.
4) Click "Import Display Groups Now"
5) Check Local Storage. 
6) **Observe:** You will NOT see the `hasImportedGroups` key.
=> bug: M3-2098 explicitly check for errors before setting local storage

src/features/Footer/Footer.tsx, src/features/Footer/createMailto.test.ts, src/features/Footer/createMailto.ts, src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx
The subject added is "Cloud Manager User Feedback". 
The user agent is accessed directly from `window.navigator`.
Click the "Provide Feedback" link in the footer. Try different browsers and manually manipulating your user agent string with Chrome Dev Tools.
=> M3-1886 Add subject and user agent to "Provide Feedback" mailto link

src/features/Search/utils.ts
Given a list of search results, display all tags for that result, regardless of whether the tag label matches the search term.
Changed:
- All tags will be displayed for search results, whether in the search bar dropdown or the search results page
=> M3-2104 Update: tag filtering when rendering search results

src/features/Profile/AuthenticationSettings/TwoFactor/DiableTwoFactorDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/DisableTwoFactorDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/ScratchCodeDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/services/profile/twoFactor.ts
Display a scratch code after a user has enabled 2FA
* Abstracted DisableTFA Dialog to it's own component
* it also now leverages the ToggleState component
* Fixed typings for the return payload of `/profile/tfa-enable-confirm`
* Scratch code dialog, which leverages ToggleState
Todo
=> M3-2093 Add Display Scratch Code After 2FA is Enabled

src/components/OrderBy.test.ts, src/components/OrderBy.ts, src/components/ShowMore/ShowMore.test.tsx, src/components/ShowMore/ShowMore.tsx, src/features/Search/utils.ts, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowTagCell.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowTags.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx, src/utilities/getLinodeDescription.ts
Replace "Plan" column in Linode Row with a "Tags" column. Tags are still displayed in the header cell, this will be addressed by M3-2059.
- Added `asLink` prop to the ShowMore component to handle this use case
- Changed sorting logic in OrderBy.tsx to allow sorting by length of array
=> M3-2060 change: plan to tags column

src/containers/withImage.container.ts, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesDetail/context.tsx
- Deleted imagesContext.
- Updated LinodesDetail, LinodeSummary, and SummaryPanel.
- Created a new container. Going to try to pursue this pattern.
- Non-breaking change.
- Visit the detail page for any Linode.
- Preferably one with an image, one with a null image, and one with an old image.
- Verify the image text is visible in the summary panel.
=> M3-2118 M3-2117 Source images information from Redux for LinodesDetail, LinodeSummary, and SummaryPanel

src/features/Account/GlobalSettings.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/Images/ImagesDrawer.tsx, src/features/Images/ImagesLanding.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, src/utilities/errorUtils.ts
Rebuilding my previous error-handling POC, this time in more manageable chunks.
This should not change the app's behavior in any way (except that errors are being set in ImagesDrawer correctly).
There are two basic API error handling patterns used in .catch blocks in the app:
1. `Linode.APIFieldError[]`: Use pathOr to get the API error response from the Axios response, or a default error if that doesn't exist.
2. `string`: Use pathOr or some other method to get the reason for the first error in the array, or a default. This pattern is not ideal, but it's widespread.
This abstracts these patterns to two functions in `src/utilities/errorUtils`
Why?
1. Fixes a few error bugs (see ImagesDrawer)
2. Consistency
3. Single concern: since Services will be a separate module, it doesn't make sense …
=> M3-2106 change: error handling

src/containers/withImages.container.ts, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx, src/store/reducers/resources/images.ts
Added
- withImages container
Changed
- LinodeDiskDrawer now gets its images from Redux rather than by going through the API.
=> M3-2115 disk drawer images redux

src/containers/withImages.container.ts, src/features/Images/ImageSelect.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx, src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskDrawer.tsx
The image select in LinodeRebuild now gets its image data from the Redux cache.
- Used ImageAndPassword component so that withImages could be used in just one place (to handle rebuilding and disk creation).
- Updated error handling
=> M3 2114 update: Add reduxed images to LinodeRebuild

src/containers/withLinodes.container.ts, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx, src/features/linodes/LinodesLanding/CardView.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/DisplayLinodes.tsx, src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
- Updated LinodesCreate to source images and Linodes from Redux.
- Update LinodesLanding to source images from Redux.
- Complete removal of ImagesContext from LinodesDeatil.
- Create a Linode.
- Verify no additional requests made to `/images`.
=> M3-2113 M3-2123 Source images and Linodes from Redux

e2e/config/custom-commands.js, e2e/pageobjects/dashboard.page.js, e2e/pageobjects/import-groups-as-tags-drawer.page.js, e2e/pageobjects/list-linodes.js, e2e/pageobjects/page.js, e2e/setup/setup.js, e2e/specs/tagmanagement/group-by-tags-linode.spec.js, e2e/specs/tagmanagement/import-groups-as-tags-linodes.spec.js, e2e/utils/common.js, src/features/Account/ImportGroupsAsTags.test.tsx, src/features/Account/ImportGroupsAsTags.tsx, src/features/TagImport/TagImportDrawer.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
**Test 1:**
- Create linodes with display group
- Verify import groups as tags CTA displays on dashboard
- Open import drawer verify expected elements and group display
- Dismiss drawer, verify flag in local storage
- Navigate to account global settings, verify import groups as tags button displays
- Import groups, verify flag in local storage
- Navigate to linode landing page, verify tags applied
**Test 2:** 
- Create 3 groups with 2 linodes
- Group by tag in list view
- Verify linodes are grouped properly
- Sort linodes asc desc verify group sorting logic
- Verify group by tags in grid view
- Ungroup verify linode listing
- Test
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e:modified`
=> Added tests for import groups as tags, and group linodes by tags

src/components/TextField.tsx, src/components/core/FormControl.ts, src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx, src/features/Support/AttachFileListItem.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
The contact info and advanced config drawer forms were slow and gross, so I added some RenderGuard logic to make them a little better.
Some of the performance hit is from MUI and still appears to not be 100% performant even with this new logic
Use chrome dev tools to audit the user interaction times between the develop branch and this branch. You can simple type into the fields to see the difference
=> change: M3-XXX Add Render Guard to Contact Info/Config Forms

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingSummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesLanding/IPAddress.test.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowTagCell.tsx, src/features/linodes/LinodesLanding/OverflowIPs.tsx, src/themeFactory.ts
Addresses M3-1914 and M3-2026; on LinodeLanding list view (and nowhere else), the copy IP address icons are hidden by default, and only appear when the IP address is hovered over.
Also on list view (and nowhere else), the `+1` button to view additional IP addresses is hidden.
Added two props (`showCopyOnHover` and `showMore`) to specify this behavior.
- Added unit tests for the new logic
- Updated existing tests to use `shallow` instead of `mount`
=> M3-2026 Change: show IP copy buttons on hover

src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
Replies and mentions on Community Questions and Answers generate events that haven't been clickable. This is changed so that these events are clickable and take you to the appropriate url.
You should be able to see the clickable events by using two users:
Create a question for user 1.
Reply to the question as user 2.
Check notifications as user 1.
Click community question event.
You should be directed to the question.
This will also work for mentioned users.
=> M3-2195 Fix community events, make all clickable.

src/features/Domains/DomainTableRow.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Domains/DomainsTableWrapper.tsx
We do not have design to place the new switch for the group by domain landing page table. The best option is to use the same convention as the linode landing for now and place it inline with the other CTA and title
=> M3-2193 Update: Style new group domain by tag switch

e2e/config/custom-commands.js, e2e/pageobjects/import-groups-as-tags-drawer.page.js, e2e/pageobjects/list-domains.page.js, e2e/pageobjects/list-linodes.js, e2e/pageobjects/page.js, e2e/setup/setup.js, e2e/specs/tagmanagement/group-by-tags-linode.spec.js, e2e/specs/tagmanagement/import-groups-and-group-by-tag-domains.spec.js, e2e/specs/tagmanagement/import-groups-as-tags-linodes.spec.js, e2e/utils/common.js, e2e/utils/config-utils.js, src/features/Domains/DomainTableRow.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/ListGroupedDomains.tsx, src/features/Domains/SortableTableHead.tsx, src/features/TagImport/DisplayGroupList.tsx
**Test:**
- Create 6 domains and 2 display groups, 3 domains per group
- Import display group as tags CTA displays
- Import display group as tags drawer displays the correct groups
- Display groups are successfully imported as tags
- Domains can be grouped by tags on Domain landing page
- Tag headers displayed in alphabetical order on Domain landing page
- Domains are sortable within tag groups
- Domains can be ungrouped by tags
- Integration Test
`yarn && yarn start` new shell `yarn selenium` new shell `yarn e2e --spec=e2e/specs/tagmanagement/import-groups-and-group-by-tag-domains.spec.js`
=> M3-2179 - Added Domain tag management tests

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesCreate/deriveDefaultLabel.test.tsx, src/features/linodes/LinodesCreate/deriveDefaultLabel.tsx, src/features/linodes/LinodesCreate/withLabelGenerator.test.tsx, src/features/linodes/LinodesCreate/withLabelGenerator.tsx
Adds a default label name during Linode creation flow. The default name is derived from the Image, Region, Linode, Backup, or StackScript, depending on which creation flow you are going through.
- Once you type in the "Linode Label" input field, the default label name will stop being derived, even if additional selections are made.
- Label name sections (image, region, etc.) may be individually shortened, if the label name is longer than the API limit of 32 characters.
- Try creating a Linode from each possible flow.
- Try creating Linodes that would yield the same default name (e.g. `arch-us-west`).
**New HOC:** `withLabelGenerator`. I chose this approach because this functionality needed to be shared across several components …
=> M3-1569 Change: Default label name during Linode creation

src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
This PR also allows deselecting of images, so that image-less Linodes can still be created.
The default is Ubuntu 18.10, which is hard-coded at the top of `FromImageContent.tsx`.
=> M3-1567 Change: Set default image in "Create from Image" flow

src/store/reducers/events.test.ts, src/store/reducers/events.ts
Timestamps from the API (which are UTC, but do not include offset) were being parsed in local time. This resulted in differences between browsers, which resulted in extraneous event notifications in Safari.
Easily verify by checking the behavior when creating volumes (w/ different browsers.)
=> M3-2213 Fix: Parse timestamps in UTC

src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
Autofill was enabled on the Password field. The styling made it such that the autofill menu covered up the disk input field. I set `autocomplete="new-password"` to fix this.
See MDN documentation: 
> If you are defining a user management page where a user can specify a new password for another person, and therefore you want to prevent autofilling of password fields, you can use autocomplete="new-password"; however, support for this value has not been implemented on Firefox.
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
=> M3-1520 Fix: Safari autofill on root password reset

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/services/account/payments.ts
"cvv" field was being posted to API as "CVV" and being ignored.
re: https://developers.linode.com/api/v4#operation/createPayment
=> Lowercase cvv.

src/components/TableRow/TableRow.tsx, src/components/Tag/Tag.tsx
Making tags in LinodeRow click to search results rather than to the linode details page. This will impact tags globally.
When reviewing the linode row, ensure the entire row is still clickable to linode details, actions still occur from the linode landing, and that the tags go to search results. Please also review other places where tags are implemented, such as the search results dropdown, linode details, etc.
=> (For Release) M3-2221 Tags in LinodeRow should be clickable

e2e/specs/tagmanagement/import-groups-as-tags-linodes.spec.js, src/features/Account/ImportGroupsAsTags.tsx, src/features/Dashboard/GroupImportCard/GroupImportCard.tsx, src/features/TagImport/TagImportDrawer.tsx
Added 'This will give you the ability to organize and view your Linodes _and Domains_ by tags.'
You can verify by logging in with prod-test-010, the message on Import Display Groups as Tags card should read 
> You now have the ability to import your Display Groups from Classic Manager as tags and they will be associated with your Domains and Linodes. This will give you the ability to organize and view your Linodes and Domains by tags. Your existing tags will not be affected.
=> M3-2177:change language on group import card

src/store/linodes/linodes.reducer.ts
When a user had 0 Linodes, a new Linode would not appear on Linodes Landing.
`results` was not being updated by `upsertLinode`, so the value (which ListLinodes was checking) stayed at 0 in this case.
=> M3-2225 Fix: Update results in Redux store when upserting a Linode

src/features/Account/AutoBackups.tsx, src/store/linodes/linodes.reducer.ts, src/store/reducers/backupDrawer.ts
Addresses 3 unrelated issues:
1. UpdateMultipleLinodes Redux action had buggy filtering logic.
2. backupsCTA was not being hidden on success
3. API was being called regardless of whether the user had toggled "enable backups" in the drawer
Please check as many possible combinations of actions/failures in the backups drawer as possible.
To test:
1. Turn backups on and off for one Linode (and have other Linodes on your account)
2. Open the backupsCTA and enable backups for existing Linodes
3: Observe: on develop, all Linodes disappear (or doubles, depending on the initial state). The behavior should be as expected on this branch.
1. Have at least one Linode that needs backups (and none that will error, e.g. have cancelled backups within the past 24 hours)
2. Open the drawer and enable …
=> M3-2223 Fix: Adjust filtering logic in updateMultipleLinodes

src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
Change default image for Linode Creation _from_ Ubuntu 18.10 _to_ Debian 9.
=> M3-1567 Change: Default image Debian 9

CHANGELOG.md, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskSpace.test.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeDiskSpace.tsx
Previously, we weren't telling the user they had 0% disk space used if it was at 0%. We were instead saying it was < 1%.
Now anything between 0 and 1 will display < 1%
=> M3-2234 0% Disk Space

package.json, src/__data__/resources.ts, src/features/Search/ResultGroup.test.tsx, src/features/Search/ResultGroup.tsx, src/features/Search/SearchLanding.test.tsx, src/features/Search/SearchLanding.tsx, src/features/Search/withStoreSearch.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx, src/store/domains/domains.actions.ts, src/store/index.ts, src/store/linodes/linodes.actions.ts, src/store/selectors/entitiesErrors.ts, src/store/selectors/entitiesLoading.test.ts, src/store/selectors/entitiesLoading.ts, src/store/selectors/entitiesLoading.tsx, src/store/selectors/getSearchEntities.ts, src/store/selectors/getSearchEntitites.test.ts, src/store/selectors/index.ts, src/store/selectors/reselect-tools.d.ts, yarn.lock
Add a new HOC, withStoreSearch, that provides wrapped components with:
- searchResults: { linodes: Item[], etc. }
- search: (query) => SearchResults;
- combinedResults: Item[]
Also adds the Reselect dev tools as a dev dependency; you will need to add the extension to Chrome if you'd like to make use of the tools.
Sorry this got big!
- NodeBalancers and Volumes are stubbed out, as they aren't yet available through Redux
- Fixed loading and error state for search landing, so please test using network throttling/request blocking (error message should show exactly which entity types didn't load, so if you block Linodes and Domains you should see both listed)
- Added logic to search bar and search landing
- Fixed error handling in linode.reducer, the API error was not getting through to state.
=> M3-2214 refactor search logic

src/features/Domains/DomainTableRow.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/SortableTableHead.tsx, src/features/NodeBalancers/NodeBalancersLanding.test.tsx, src/features/NodeBalancers/NodeBalancersLanding.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
Uses similar pattern to add icons to all tables where it was missing: NodeBalancers, Volumes, Domains.
- Add icon to NodeBalancers table
- Add icon to Volumes table
- Add icon to Domains table
- Fix spacing in Linodes table
=> M3-2168, M3-2169, M3-2170: add entities icons to tables

src/containers/volumesRequests.container.ts, src/features/Search/SearchLanding.test.tsx, src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx, src/features/Volumes/VolumeTableRow.tsx, src/features/Volumes/VolumesActionMenu.tsx, src/features/Volumes/VolumesLanding.tsx, src/services/volumes/volumes.ts, src/store/store.helpers.ts, src/store/volume/volume.actions.ts, src/store/volume/volume.reducer.ts, src/store/volume/volume.requests.ts
Added Request Thunks for create, update, and delete Volume actions.
**New container:** `volumesRequests.container.ts`
There was some inconsistency between variable naming of Volume IDs throughout several components (`volumeID` vs. `volumeId`). I changed them all to `volumeId` to keep things consistent.
**IMPORTANT:** The tests in `SearchLanding.test.tsx` have been disabled. They were failing to run because of cyclic dependency issues that will be resolved once `services/linodes` and `services/domains` don't depend on the store. Once that change is made, these tests need to be restored.
=> Volume services

src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
The dashboard "view all linodes" link was broken in case you had more than 5 linodes.
- Bug fix
Test with a n account that has more than 5 linodes (ex: prod-004)
=> M3-M3-2240 Bug Fix: view all link for dashboard linodes card

src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
`parentColumn` prop is used for responsive tables. Linode table is a different type and we don't have to display label for the mobile view (it switches to cards for linodes landing)
- Fix unnecessary Linode label on mobile view for Dashboard page
=> M3-2248: remove unnecessary label

src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx, src/features/Billing/PdfGenerator/PdfGenerator.ts, src/themeFactory.ts
- Fix 'Payment' word in Payments PDF
- Fix unnecessary tab opening
- Add 'Download PDF' link to invoice table on account page
@alioso can you help with styling 'Download PDF' on invoices table on account page, please? It is not highlighted as a link in Payments table
=> M3-2258: fix tab opening, add download invoice link

src/features/Domains/DomainCreateDrawer.tsx, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainsLanding.tsx, src/services/domains/domains.ts, src/store/domains/domains.actions.ts, src/store/domains/domains.container.ts, src/store/domains/domains.reducer.ts, src/store/domains/domains.requests.ts
This change addresses a cyclic dependency issue. Previously, we imported the store into the services library to dispatch actions upon Domain creation, deletion, and update. This PR applies the "Request Thunk" pattern to these 3 operations to git rid of this issue.
=> M3-2120 Domains services

src/components/PrimaryNav/PrimaryNav.test.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/components/TabLink/TabLink.tsx, src/components/TabLink/index.ts, src/features/Account/AccountLanding.tsx, src/features/Domains/DomainDetail.tsx, src/features/Profile/Profile.tsx, src/features/TopMenu/UserMenu/UserMenu.tsx, src/features/Users/UserDetail.tsx, src/features/linodes/LinodesDetail/HeaderSections/TabsAndStatusBarPanel.tsx, src/themeFactory.ts, src/themes.ts
We need to make the navigation more friendly and make use of the <Link /> router component to enable opening links in new window.
Feature as been added to:
- PrimaryNav
- Tabs: (linode detail, volumes, account, profile)
=> M3-853 Update: Ctrl-click enabled navigation patterns

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx, src/utilities/isRecent.test.ts, src/utilities/isRecent.ts
If no graph data is available for a Linode, we get an error from the API. This is guaranteed to happen when a user first creates a Linode, since there _isn't_ any graph data yet. But currently, we show the graphs in an error state, which is extremely jarring. 
This PR checks the `linodeCreated` prop first. If we receive an error, and it hasn't been 24 hours since the Linode was created, we show a friendlier message (same one from Classic Manager): "Graphs for this Linode are not yet available – check back later"
- New utility with tests: `isRecent`
- StatsPanel component now takes a boolean prop, `isTooEarlyForGraphData`
Please verify with long running Linodes, new Linodes, Linodes without images, etc.
=> M3-2216 Change: Friendly error message when graph data is unavailable

src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx
Fixes a visual regression where the NodeBalancer region cell wasn't lining up. The region cell had the same className as `nameCell`, which we added left padding to.
=> NB region cell alignment

src/components/TableSortCell/TableSortCell.tsx
There was a slight shift between initial and active sort icons which makes the label move (ex: tags) when sorting
- Bug fix
Linodes landing table, play with sorting
=> M3-2292 fix sortable icon styling

src/features/Volumes/VolumeTableWrapper.tsx
Was incorrectly labeled as "List of Linodes" instead of "List of Volumes".
=> M3-2297 fix: aria label on VolumeTableWrapper

src/containers/domains.container.ts
Previously, in `domains.container.ts`, values for `domainsLoading` and `domainsError` were hard-coded. This PR fixes that so they are sourced from the store.
=> use loading and error states from store instead of hardcoded values

src/components/PaginationFooter/PaginationFooter.tsx
Fixes pagination bug. Steps to reproduce:
- Login with account that has more than 25 domains
- Go to `/domains`
- Click `Show 100`
- Expected: there is a selector to switch back to `Show 25`
- Actual: pagination disappears with the selector
- Fix pagination display logic
The only change that is relevant here is
```if (count <= pageSize) { return null; }``` to
```if (count <= 25) {
return null;
}```
=> Fix pagination display logic

src/components/Paginate.ts
Currently user have to manually scroll to the top after going to the next page. This commit makes it automatic
- Fix page scroll position when changing page
=> Improve pagination experience

src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
The PR removes the option to Reboot a Linode unless the Linode currently has a status of `running`.
1. Go to the Details page of a Linode that is _powered off._
2. Click the Power Controls button in the top-right corner.
3. **Observe:** The only option displayed is "Power On". 
1. Go to the Details page of a Linode that is _powered on._
2. Click the Power Controls button in the top-right corner.
3. **Observe:** Two options are present: "Reboot" and "Power Off"
=> M3-2173 Change: Remove "Reboot" option unless Linode is running

src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
One-word typo fix.
99% of the diff is Prettier formatting changes. The real change occurs on (old) line 458:
=> M3-2235 fix: Typo in "Manual Snapshot" copy

src/containers/withBackupCTA.container.ts
Previously, an empty `<Grid />` element was appearing if you had these conditions
1. Were a managed customer
2. Had a Linode without backups
Do we now not need the managed check here?
```js
if (managed || (linodesWithoutBackups && isEmpty(linodesWithoutBackups))) {
return null;
}
```
https://github.com/linode/manager/blob/develop/src/features/Backups/BackupsCTA.tsx#L48
=> Fix: Empty Backups Column appearing in Linode Landing for Managed Users

src/components/IconTextLink/IconTextLink.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
The nodeBalancers landing page had a regression when the last feature was merged and the header spacing differed from the other landing pages
- Bug fix
=> M3-2311 fix regression with nodeBalancers header spacing

src/components/EnhancedSelect/Select.tsx, src/components/TagsPanel/TagsPanel.tsx, src/containers/SummaryPanels.styles.ts, src/features/Billing/BillingDetail.test.tsx, src/features/Billing/BillingDetail.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/features/Domains/DomainDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/NodeBalancerSummary.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/NodeBalancers/NodeBalancerDetail/context.ts, src/features/Users/UsersLanding.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx, src/index.css, src/themeFactory.ts
This PR implements a new UI pattern in which we feature the summary panel in a new sidebar. It was a major rework in order to move the TagsPanel in there as well. 
This pattern is implemented for the following entities:
- linodes
- nodebalancers
- domains
- account
linodes/[id]/summary
/nodebalancers/[id]/summary
domains/[id]/records
/account/billing
=> M3-2319 Update: Summary Panels in Sidebar

src/features/Users/UserProfile.tsx
There's general confusion between user email and account email address → we can help by removing fields you don't have that differentiate between items.  API doesn't allow changing user email address, let's use plain text instead to indicate to the user that it cannot be changed.
- Non breaking change 
account/users/[user]/profile
=> M3-1065 Update email field to be text

src/components/EnhancedSelect/EnhancedSelect.tsx, src/constants.ts, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/LinodeSelect.test.tsx, src/features/Volumes/VolumeDrawer/LinodeSelect.tsx, src/features/Volumes/VolumeDrawer/RegionSelect.test.tsx, src/features/Volumes/VolumeDrawer/RegionSelect.tsx, src/utilities/doesRegionSupportBlockStorage.test.ts, src/utilities/doesRegionSupportBlockStorage.ts
In the Volume Creation Drawer, only display regions that support block storage. Similarly, only display Linodes in regions that support block storage.
Helper text has been added explaining why not all regions are displayed. 
=> M3-1545 Change: Only display regions with block storage in Volumes Drawer

src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
Fixes a spelling error found during PR review.
=> Fix: Spelling error in Mutation Drawer

src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/features/Help/Panels/PopularPosts.tsx, src/features/Support/SupportTickets/TicketList.tsx, src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx
For some reason this commit was empty on https://github.com/linode/manager/pull/4474 - reapplying here
=> M3-2336 update underline links instances

src/components/EnhancedSelect/Select.tsx
Right now the react selects can get too high (ex: too many tags) so we need a max height and scroll capabilities
=> M3-2359 Add max height to React Select with scroll overflow

src/components/TagsInput/TagsInput.test.tsx, src/features/Images/ImagesDrawer.tsx
Clear error and success state when submitting ImageDrawer form. Currently these are only cleared when closing the drawer.
=> M3-2372 Fix: clear ImageDrawer error on submit

src/features/linodes/presentation.test.tsx, src/features/linodes/presentation.ts
For Linode plan details, display "GB" instead of "G" for storage and memory.
2-08 at 3 19 11 pm" src="https://user-images.githubusercontent.com/16911484/52503972-0c7b6880-2bb5-11e9-9c58-0f31e1120712.png">
=> M3-2365 Change "G" to "GB" in plan details

src/components/Table/Table.tsx, src/features/Domains/DomainRecords.tsx
On the domain records page, long domain names (at certain breakpoints) would require the user to scroll the table right to access (or even know) there is an action button. This PR wraps the text so that it does not happen anymore. It is not the most elegant solution to wrap strings like this but this is the best option that we have unless we start using the mobile view (stacked cells) at a higher breakpoint for this table (which is a pretty big design change i'd rather not introduce).
=> M3-2335 Update treatment for lengthy domain records

src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/themes.ts
=> M3-2383 fix typography instances

src/services/nodebalancers/nodebalancers.schema.ts
To make it a little more clear to the user why the IPv4 address is invalid it would be helpful to add the word "private" to the error message. I realize this was probably kept short so that there would not be a line break on the error message. I think there's a couple ways that could be handled (e.g., longer input box), but I'll leave that style issue up to the UI team because they would know the best consistent way to make this change.
Although this change is simple I think it would help clear up some confusion that I experienced when trying to add an IP to a NodeBalancer. I assumed that it could take *any* IPv4 and was confused why it was complaining because I did enter a valid IPv4 address. After looking up the documentation I realized it had …
=> More explicit private IPv4 address error

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Use different paypal src to not hardcode version number
This fixes an issue with v4.0.240 of Paypal that was causing 302 responses for a subset of users. Please see https://github.com/paypal/paypal-checkout-components/issues/1031
This PR fixes the issue, but we ideally want to be in a place where we can merge #4509 but is currently being blocked by ARB-1098
Point your .env at dev services
Try to make a paypal payment. Find dummy credentials in 1password or hit me up for them if you can't find them
Proof that production payments work:
=> Fix: M3-2377 Paypal Payments Non-Functional

src/components/Tag/Tag.tsx
Clicking a tag takes you to the Search Landing page, with a query of the tag name.
This PR prepends `tag:` to the query, so that only entities with a match on _tag_ will be displayed.
Click on any tag. You should be taken to the Search Results Landing page, and you should see the text: `Search Results for "tag:[TAG NAME]"`.
=> M3-2332 Change: Clicking a tag prepends "tag:" to the query

src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx, src/features/Dashboard/DashboardCard.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/ViewAllLink.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
Add count to dashboard entities if > 5 along with the view more link (re-styles as we needed to make it more visible by appending it next to the card title
=> M3-2408 Add: count to dashboard entities

src/features/TopMenu/SearchBar/SearchBar.test.tsx, src/features/TopMenu/SearchBar/SearchBar.tsx
Limit search results in the SearchBar dropdown to **20.** This is for performance and accessibility. See ticket for more details.
Use an account with many entities. Try generic queries like `is:linode` that yield many results.
=> M3-2389 Change: Limit SearchBar results to 20

src/features/linodes/LinodesCreate/withLabelGenerator.tsx, src/services/linodes/linode.schema.ts
Remove client-side validation of Linode Labels, as it is inconsistent with actual API requirements.
Test creating Linodes, as well as updating labels on existing Linodes.
=> M3-2444 Fix: Remove client-side validation for Linode labels

src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
We display a tags input field when creating a Linode from an existing Linode (cloning), but the cloning endpoint is ignoring the tags that we send with the POST request.
If the API changes its behavior, we can include the tags input; until then, we should remove it.
I left in the tag handling code, just removed sending it to LabelAndTagsPanel. If this change is permanent, we can remove that logic as well.
=> M3-2448 Hotfix: Deactivate tag input on FromLinodeContent

src/components/TagsInput/TagsInput.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/Volumes/VolumeDrawer/utils.ts, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/utilities/errorUtils.test.ts, src/utilities/errorUtils.ts
Adds an errorUtil `getTagErrors` that handles the special case of tag errors having a field `tag[0]` or `tag[1]`. For now, only displaying a single error string: since tagError is expecting a string, I'm trying to keep the footprint of this fix small.
This will need to be tested in each of the separate creation flows, also please make sure existing error handling is not affected.
=> M3-2441 Fix: Tag error display

src/features/linodes/LinodesDetail/maybeRenderError.tsx
maybeRenderError is listening for global Volumes error state (`__resources.volumes.error`), so an error when creating a Volume results in the user being unable to view any LinodesDetail page.
This will require a larger fix; in order to patch this before release, I'm using `volumes.lastUpdated` as a proxy for "is this the initial Volumes load?" The LinodesDetail page should not be dependent on Volumes data, but extricating that would be too big a change for a patch.
We could also just delete the volumes error check; but this has enough side effects that I'm not confident we could catch them all before Tuesday.
=> M3-2457 Fix: patch maybeRenderError logic

src/events.ts, src/store/linodes/linodes.events.ts, src/store/middleware/combineEventsMiddleware.ts
Decrease the amount of times we're polling `/events` when we have in-progress events happening.
1. Trigger an action (such as Linode Resize)
2. Check the Network tab3
3. Every request to `/events` should happen after 4 seconds
If no action is running, the polling should work as normal (with intervals of 1, 2, 4, 8, 16 seconds)
Pls run a lot of different events and try your hardest to break something
=> Events Polling Updates

src/components/TagsInput/TagsInput.spec.js, src/components/TagsInput/TagsInput.tsx, src/features/Domains/DomainCreateDrawer.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumeDrawer/utils.ts, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/services/volumes/volumes.schema.ts, src/utilities/errorUtils.test.ts, src/utilities/errorUtils.ts
Adjusts tag error handling (introduced in 0.48.1) for the new API release. Tag errors will have the field 'tags' rather than 'tags[0]', so our special logic for this is no longer necessary.
To test:
- change the conditional in line 39 of TagsInput to `false` (turn off client-side tag checking)
- Submit a short tag (< 3 chars)
- Use dev services
=> M3-2441 update tag errors

src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/linodes/LinodesDetail/LinodesDetail.container.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
API Team requested we display a human-readable error to the user if one of their Linodes has been suspended. So if we get that error, we need to display an error along with a link to the support page.
This error will not get returned from `v4/linodes/instances` but instead will be returned from `v4/linodes/instances/:id` or `v4/linodes/instances/:id/whatever`
=> M3-2455 Humanize Suspended Linode Error

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Adjusting breakpoint for when graph info should stack (now set for large so users never get scrolling).
• Go to a linode detail with graphs
• Shrink screen to 1015px
• Note that graph info no longer scrolls, but stacks as it should for smaller breakpoints as well.
=> M3-2461 Graphs need better breakpoints

src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts, src/themes.ts
Made download link blue instead of white for DT. Also fixed the stackscript panel's empty state text color for DT as well. 
1) Switch to dark theme. 
2) Navigate to account page. 
3) Expand recent invoices and recent payments panels.
=> M3-2458 Download PDF link color inconsistency in dark theme

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
Previously, if user visited the _create from backup_ flow and selected a Linode and a backup, clicking on the same Linode would clear the backups selection.
Now, the backups selection will only clear if a new Linode is selected
Also applied the same logic to _clone from existing_ flow
=> Fix: M3-1181 Clear Backups Selection Only Upon New Linode Selection

src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/utilities/errorUtils.ts
POC for mapping errors to input fields. Currently we use getApiErrorFor, which ignores errors with fields that you don't explicitly tell it to check for. This may have been what happened with the Support drawer feedback email we received a few days ago.
This way, any sort of error will always register somewhere. Not thrilled with the approach, feedback welcome.
Use mockAPIError from services/support.ts to create a bunch of fake errors.
=> POC for error mapping function

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx
updateFor logic didn't include ssl cert or key errors, so those errors were not being displayed to the user (unless they interacted with the fields)
- Two users complained about this happening with their certs, but I'm not able to reproduce errors with correct certs (self-signed cert & key).
- You can test this fix by using `1` in both the cert and key input boxes.
=> M3-2464 Fix: NB ssl error handling

src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/constants.ts, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/store/regions/regions.actions.ts, src/utilities/doesRegionSupportBlockStorage.test.ts
--- Sorry guys, had to re-create this one
Add the Toronto region to the region select when creating a new Linode.
- The display name is provisional, pending management approval.
- Instead of Charles, I'm manually appending the new DC when dispatching `getRegions.done`.
- This is going to live in the feature branch until the DC is available, est. March 18.
=> M3-1724 toronto region in linodes

src/features/linodes/LinodesLanding/LinodesLanding.tsx
Grid view was being forced on linodes landing for both xs and sm breakpoints, it is now set to be xs only. 
To test, emulate an ipad experience vs an iphone and see that you can change your view experience for ipad as you would on larger breakpoints.
=> M3-1100 Only force grid view at XS breakpoint

src/containers/account.container.ts, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.test.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Pre-populate the payment amount field with the user's current balance if this is a) defined and b) greater than $5 (the minimum for Paypal).
Also removed the AccountContext usage here, since account data is already available in the Redux store, and there were too many /account requests firing here.
Possible issue: I'm using componentDidUpdate to determine whether to set the default value, but it's possible that if something else hits /account while the user is editing the payment amount, it'll get reset to the balance.
You can use Charles to fudge your balance and/or hard code a value in to the account reducer.
=> M3-1302 Change: Pre-populate payment amount

src/features/Account/GlobalSettings.tsx, src/features/Backups/BackupDrawer.tsx
Hide global backup setting from Managed users - it's pointless for them!
Managed users already have backups enabled by default
=> hide global backups setting from managed users

src/components/EnhancedSelect/Select.tsx
Previously the `isClearable` logic in our React-Select abstraction was: 
```jsx
<Select 
  isClearable={isClearable || true}
  // ...
</Select>
```
This means it was impossible to set `isClearable: false`.
=> M3-2471 Tech Fix: React-select isClearable logic

src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/CALinodeCreateSubTabs.tsx
Subtab wrapper for new Create Linode flow
=> Cloud Apps: Add Subtabs

src/constants.ts, src/features/Profile/APITokens/APITokens.tsx, src/features/Profile/APITokens/ObjectStorageDrawer.test.tsx, src/features/Profile/APITokens/ObjectStorageDrawer.tsx, src/features/Profile/APITokens/ObjectStorageKeys.test.tsx, src/features/Profile/APITokens/ObjectStorageKeys.tsx, src/services/profile/objectStorageKeys.ts, src/types/Profile.ts
_Must be using development services._
This PR adds a new section in Profile > API Tokens, called “Object Storage Keys”. Clicking “Create an Object Storage Key” will allow you to create Object Storage credentials. 
This new section should only be rendered when `REACT_APP_IS_OBJECT_STORAGE_ENABLED=true`. 
**You'll need to add this to your `.env` file.**
- Nothing should actually be populating the Object Storage Keys table. Once existing key labels are returned from the API, that’s where they’ll go.
- The “Label” text field doesn’t do anything yet.
=> M3-XXXX Change: Object Storage credentials creation

src/constants.ts, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/linodes/LinodesCreate/LinodesCreate.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Prevent Tokyo 1 from being shown as an option when selecting a region for Linodes and NodeBalancers (it is already excluded from block storage selections).
Opted to do this on an individual component level, since some users still have Linodes in this region. We could *probably* just filter it out in Redux without affecting these users, but this way is safest. Eventually the API will no longer return this region at all, at which point the display name value etc. can be removed.
Also includes a fix for regions error messaging when creating a Linode (currently fix is already on a feature branch, but this fix should go out as soon as possible).
=> M3-2449 Change: Remove Tokyo 1

src/features/linodes/transitions.ts, src/store/linodes/linodes.events.ts
Adds progress for Linodes that have one of their disks being imagized
API does not return a `busy` status for Linodes that have disks being imagized, so we really can't do anything about the status icon 🤷‍♀️
=> M3-2202 Imagize Disk Busy Status

src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
Adding word break so text will wrap even if one long string- I guess at some point we lost the className so this was mostly adding it back for Volumes, NodeBalancers, and Domains.
Have a couple long, continuous entities on your dashboard view, shrink screen and note that the overlap of columns no longer occurs and text breaks to newlines as it should.
=> M3-2478 Fix text overflow on Dashboard

src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesCreate/types.ts, src/features/linodes/userSSHKeyHoc.ts
- Rather than wrap each individual FromLinodeContent etc. with the SSHKey HOC, wrap the container and use state from there.
- Also added a function to reset all SSHKeys to `selected:false` which wasn't needed before (I don't think) since the individual components would re-render whenever tabbing back to them.
=> CA: Move SSH HOC to container

package.json, src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/CALinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/store/index.ts, src/store/linodeCreate/linodeCreate.actions.ts, src/store/linodeCreate/linodeCreate.reducer.ts, yarn.lock
Move over all the tab state into Redux, for the purposes of the container component knowing which endpoint to POST to and what payload to send
* Initial redux state is determined by the query params in the URL
* Every action takes a `type` param which will set state based on the tab title.
=> CLAPPS - Tab State in Redux

src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/Panel.tsx, src/features/linodes/LinodesCreate/PrivateImages.tsx, src/features/linodes/LinodesCreate/PublicImages.tsx, src/features/linodes/LinodesCreate/SelectImagePanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/store/linodeCreate/linodeCreate.reducer.ts
- Refactor SelectImagePanel to handle our 3 use cases (show just public images, just private images, and a tabbed panel that displays both)
=> CLAPPS: Add Images subtab

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/withLabelGenerator.tsx, src/store/linodeCreate/linodeCreate.reducer.ts
Re-introduce usage of the `withLabelGenerator` HOC.
You'll notice that the dynamic label generator is a lot more generic than it was when it was split across the 4 create flows. This PR was merely creating to get things moving and we can surely refactor again later to make the dynamic label more robust, like it once was.
=> CLAPPS - fix dynamic label

src/features/Profile/AuthenticationSettings/TrustedDevices.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx
Currently, the Trusted Devices table does not display the last IP a device was used from or last time the device was used. The API already includes these fields, so adding them will give users better insight into activity on their user account.
Looks like this:
This is my first PR against manager, so if this is totally wrong just let me know. Tested it in Firefox on OS X with various window widths and it looked about as expected.
=> change: Add last auth IP address and last auth time to trusted devices table

src/components/EnhancedSelect/EnhancedSelect.stories.tsx, src/components/EnhancedSelect/Select.tsx, src/components/EnhancedSelect/components/MenuList.tsx, src/features/TopMenu/SearchBar/SearchBar.styles.ts, src/features/TopMenu/SearchBar/SearchBar.tsx
We need to let the users know about the new filters available on the search. This PR adds a help bar at the bottom of the search dropdown. Made it avail as an optional `guidance` prop for all react selects that can take a string or function
=> M3-2486 Add: new menulist component to react select

src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
_Must be using dev services to test._
The API behavior of Linode Resize is changing. Instead of the FE immediately receiving a `scheduled` event, the resize will be queued. The resize will begin shortly after, and we'll start receiving `linode_resize` events as before.
In this queued state, we'll receive a pending migration notification for the Linode in question, which is why I've dispatched a `requestNotifications` action after submitting the resize request.
=> M3-2410 Change handling of Linode Resize

src/components/EntityIcon/EntityIcon.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/Domains/DomainTableRow.tsx, src/features/Domains/ListDomains.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx, src/features/Volumes/SortableVolumesTableHeader.tsx, src/features/Volumes/VolumeTableRow.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx, src/themes.ts
This PR improves the layout of tables rows for Comp Mode:
- smaller entity icons
- better alignment of sortable headers
- better cell spacing
This PR will affect landing page table rows/cells on compact mode.
=> M3-2494 Smaller Entity Icons on Comp Mode

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
If you didn't have a credit card on file, the string 'false' would be displayed. Use a blank string instead to fix this.
=> Fix: Default lastFour to empty string instead of false

src/features/linodes/LinodesDetail/LinodeRebuild/RebuildDialog.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
Added a ConfirmationDialog after a user presses the “Rebuild ” button, since this is a destructive action.
NOTE: Ideally we’d do form validation before opening the confirmation dialog, but this will require larger changes and consideration. I thought this solution would be fine in the short-term.
=> M3-2495 Change: Add Confirmation Dialog before rebuilding Linode

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, src/services/nodebalancers/configNodes.ts, src/services/nodebalancers/nodebalancers.schema.ts, src/types/NodeBalancer.ts
Adds `backup` mode to NodeBalancers, where nodes set to `backup` only receive traffic if all non-backup nodes are down.
- Requires corresponding API changes.
- If a node is set to `backup` the current Manager displays a blank entry in the drop-down, and the mode can still be updated to existing values.
=> [SPR-141] update NB nodes to support backup mode

src/components/EnhancedSelect/components/Guidance.tsx, src/components/EnhancedSelect/components/MenuList.tsx
Using `withStyles` was replacing `innerRef` on the new custom MenuList component, which was breaking keyboard scrolling navigation. I extracted the "Guidance" part of the component out, so styles could still be applied. There's probably a better solution, though. 
Test that the main SearchBar works and that you can scroll with keyboard up/down if there are many entities.
=> M3-2498 Fix: Keyboard scrolling on on custom MenuList component

src/components/CheckoutBar/CheckoutBar.tsx, src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/CALinodeCreateSubTabs.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/index.css
UI edits for Apps work: 
• Notices are now part of Backups and Linodes, as well as adding Paper to a few of the different 'states' of the components (loading, null imagery, etc.) 
• Grid alignment updates
• Making checkout bar use css sticky instead of external library. 
This work is most noticeable under the 'My Images' tab, but 'Distributions' tab and 'Create NodeBalancer' flow should be reviewed as well since I impacted CheckoutBar. 
Also, if there are other places where Paper component should be added/ notice messaging needs to be moved, please call it out and I will address either here or in a separate …
=> Apps UI Edits

src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
This fixes the padding issue on Access Panels for RebuildFromImage and RebuildFromStackScript.
=> Fix: Add props.classes for RenderGuard updateFor

src/components/RenderGuard.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
Re-Render Renderguard if the `theme.spacing.unit` has changed
So we don't have to constantly be passing `props.classes` to a RenderGuarded component
=> M3-2510 Render Guard Spacing Check

package.json
Playing with Node/Chrome/Jest debugging integration
To test: 
1. Add a `debugger` statement to any Jest test
2. Run `yarn test:debug`
3. In chrome, visit chrome://inspect
4. Click on the Node icon
5. et voila, step through with the debugger as you would normally.
=> Add test:debug script

src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/store/linodes/config/config.reducer.ts, src/store/linodes/disk/disk.reducer.ts, src/store/store.helpers.ts
Fix issue where an error on one Linodes detail page was persisting throughout other Linode Detail pages
1. Go to Linode detail page and have a request error out
2. Page bombs - user sees error
3. Go to another Linode detail page, where all requests resolve correctly
4. Still see error on the page
1. Go to Linode detail page and have  a request error out
2. Page bombs - user sees error
3. Go to another Linode detail page where all requests resolve correctly
4. No more error - page loads as normal
This doesn't solve the issue where requests to `/backups` fail. If that request fails, the entire Linodes Landing bombs, which is not ideal.
This PR just resets the configs and disks Redux error state when the detail pages load.
=> M3 2501 Linodes Detail Errors Fix

src/containers/profile.container.ts, src/features/StackScripts/SelectStackScriptPanel/CASelectStackScriptPanel.tsx, src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx, src/features/StackScripts/StackScriptsDetail.tsx, src/features/StackScripts/stackScriptUtils.ts, src/features/linodes/LinodesCreate/CALinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Clapps refactor broke the "deploy new Linode" links from StackScriptDetail and the StackScript action menu
=> CLAPPS: Fix StackScript routing

src/features/Images/ImagesDrawer.tsx
Image creation will fail if the (compressed) disk size is greater than 2048MB. Since we're unable to show a specific error message when this happens, this PR adds helper text when selecting a disk, so that users are aware of the individual Image size limit.
=> M3-2483 Add help text when creating Image

src/__data__/objectStorageKeys.ts, src/features/Profile/APITokens/ObjectStorageDrawer.tsx, src/features/Profile/APITokens/ObjectStorageKeyTable.test.tsx, src/features/Profile/APITokens/ObjectStorageKeyTable.tsx, src/features/Profile/APITokens/ObjectStorageKeys.test.tsx, src/features/Profile/APITokens/ObjectStorageKeys.tsx, src/services/profile/objectStorageKeys.schema.ts, src/services/profile/objectStorageKeys.ts, src/types/ObjectStorage.ts, src/types/Profile.ts
Displays a paginated list of a user's Object Storage keys in Profile -> API Tokens.
Use dev services, and make sure `REACT_APP_IS_OBJECT_STORAGE_ENABLED=true` is in your `.env` file.
Try creating a few a keys and see them displayed in table. Use test account 6 to see pagination.
=> Change: Display list of Object Storage keys

src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.test.tsx, src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
LinodeRescue was making a request to /volumes every time the tab rendered. This data was already in Redux, so these calls were redundant.
Would be acceptable/in scope to get rid of the empty Volumes group label? (as is you still see "Volumes" with nothing under it if you don't have any)
=> M3-2144 Update: Source Linode Rescue volumes/disks from redux

src/components/Table/Table.tsx
Some tables (ex: linodes landing) were inheriting a scroll bar with compact mode (FF only). Apparently FF needs an explicit overflow-y declaration id overflow-x is setup to avoid this issue.
=> M3-2523 Fix extra scrollbar on tables on Firefox Compact Mode)

src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx, src/hooks/useErrors.ts
Fixes a bug in RebuildFromStackScript where "scroll to error" was happening on each re-render if there were errors. This was noticeable if the StackScript had many UDFs. `useEffect()` inside "useErrors" hook needed a second argument to fire only when `errors` changed.
**To test:** 
1) Go to Linode Detail > Rebuild > From StackScript
2) Click on a StackScript with many UDFs.
3) Click "Rebuild".
4) Observe: errors appear
5) Scroll up/down to a UDF
6) Type something in a UDF field.
7) Observe: no scrolling happens.
Also, fixed a bug where the confirmation modal wasn't being dismissed if there was an ImageID error.
=> Fix: Error scroll in RebuildFromStackScripts

src/components/AccessPanel/AccessPanel.tsx, src/components/PasswordInput/PasswordInput.tsx, src/components/PasswordInput/StrengthIndicator.tsx, src/components/ShowMoreExpansion/ShowMoreExpansion.stories.tsx, src/components/ShowMoreExpansion/ShowMoreExpansion.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx, src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx, src/features/Support/TicketAttachmentList.tsx, src/features/linodes/LinodesCreate/PublicImages.tsx
-Splitting out required fields from optional so we can put the latter in a collapsible container. 
-Some associated styling as well. 
-Also added a new prop to the password component, hideStrengthLabel determines if the `Strength:` span will display or not (default is it is displayed).
To test: Under one-click, select an app with alot of UDFs, note that the optional fields now live under an 'advanced options' container.
=> Apps UDF Improvements

src/components/Radio/Radio.tsx, src/components/TextField.tsx, src/features/Profile/APITokens/APITokenDrawer.tsx, src/utilities/convertToKebobCase.ts
This PR adds some default properties to TextField (ID, so that the label automatically inherit a `for` attribute) and Radio (an `aria-label` attribute) and improvements to the oAuth permission tables since these radios placed in a table were barely accessible at all
=> M3-2516 Fix accessibility issues with oAuth permission table

src/components/EditableText/EditableText.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
Aligning things properly.
To test on chrome and FF both regular and compact modes
=> M3-2543 Linode Detail Vertical alignment of top items

package.json, src/components/EnhancedSelect/components/Guidance.tsx, yarn.lock
Prevent storybook from auto-opening a browser when `yarn storybook` is run
Also tried to fix the following issue but I was not willing to spend an entire day upgrading our testing libs
```
DEPRECATION: Setting stopOnSpecFailure directly is deprecated, please use the failFast option in `configure`
```
=> PreCommit Updates

src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
Added word-break to some potentially longer strings, and also put them inside their own divs in case of that so they're not jumbled.
=> M3-2540 Long account names overflow container on account summary panel for narrower views

src/assets/timezones/timezones.ts, src/features/Profile/DisplaySettings/TimezoneForm.tsx
This PR contains a possible "quick fix" for our issues in selecting timezones. If this (or the options below) are still lacking, we may want to get UX involved for these decisions.
- We were sourcing our data from React Timezone, which has updated its list to include offsets.
- By updating this list, we make sure that zones are sorted by UTC offset
Pros of this approach: 
- Closely resembles Google Calendar TZ select
- Solves the sorting problem
- Easier to maintain
Cons:
- Our select is searchable, and searching for "Eastern Daylight" or "Philadelphia" doesn't provide any results.
- For some reason the search is sluggish when I'm running it locally.
- (feel free to add cons here)
Other solutions:
- Rely entirely on Moment Timezone for our selections (they have an enormous list)
- Add …
=> M3-2507 Spike: fix timezone selection

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectAppPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/formUtilities.ts, src/features/linodes/LinodesCreate/types.ts, src/services/cloud_apps/index.ts
Use API response for displaying Cloud Apps
Use dev servicesssssss
=> CLAPPS: Leverage /one-click-apps endpoint

src/App.tsx, src/components/PrimaryNav/PrimaryNav.test.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/constants.ts, src/features/ObjectStorage/ObjectStorageLanding.tsx, src/features/ObjectStorage/index.tsx
Includes link to the Object Storage landing page in the Primary Navbar. 
This is pointed to a feature branch, which I'm planning to complete in three stages:
1) Object Storage link in Navbar (this PR)
2) Bucket listing page
3) GET `buckets` API method 
I'm breaking it up so the PRs aren't huge.
Make sure the Object Storage link is visible only if `REACT_APP_IS_OBJECT_STORAGE_ENABLED=true` is in your `.env`.
=> M3-OBJ-54: Object Storage link in Primary Nav

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/PaymentBits/CreditCardDialog.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/PaymentBits/PaypalDialog.tsx, src/features/Billing/BillingPanels/MakeAPaymentPanel/PaymentBits/PaypalDialogActionButtons.tsx, src/services/account/payments.ts, src/types/Paypal.ts
Upgrade to new PayPal SDK and change logic to match new documentation.
Also abstract out the new credit card dialog
It's important to note these docs:
https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-server
Contrary to the old version of the JS SDK, the `createOrder` callback expects a promise that returns a `order_id`. In the past, this callback was named `payment` and expected a promise that returned a `payment_id`. This was changed for God knows why and now it needs to be changed. All other logic remained mostly the same.
So here's how it works
1. User types in their payment and clicks the paypal button
2. At this point, the APIv4 request should fire (`v4/account/paypal`) - this endpoint now …
=> M3-2377 Upgrade and Fix PayPal

src/features/Profile/APITokens/APITokenTable.tsx
Changed dialog size to `md` to accommodate for api token width. Please note this will only resolve for larger screens.
=> M3-2533 Personal Access Token always line wraps 

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
The "Select a Kernel" component in `Linode > Settings > Advanced Configurations > Edit` was not being populated at times.
To fix this, I added `kernels` to RenderGuard's `updateFor`. 
1) Log out of Cloud Manager. 
2) Log in to Cloud Manager. 
3) From the Dashboard, click on a Linode that has at least one configuration. 
4) From Linode Details, go to the "Settings" tab. 
5) Expand the "Advanced Configurations" accordion. 
6) On a config, click the kabob menu, then click "Edit".
7) **Observe:** the "Kernel" input component should be fully populated.
=> M3-2326 Fix: Kernel Select

src/components/ShowMoreExpansion/ShowMoreExpansion.tsx
Standard cDU malfunction, expansion panels for advanced options UDFs were closing if typed in. Added an extra check that seems to fix it.
=> M3 Fix clapps advanced option bug

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Set the selected image to Debian 9 when toggling between cloud apps (since this is usually the only option).
This will happen if Debian is, in fact, the only option. Will also run whenever a StackScript (personal or community) only has one compatible option.
=> CLAPPS: Add defaultImage logic

src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Fixes 2 bugs
1. Not resetting the `selectedStackScriptUserName` and `selectedStackScriptLabel` states upon tab change
2. We were showing the expansion panel in the UDF form even when there were no optional UDFs to fill out
=> Cloud Apps - Bug Fixes

src/components/Table/Table.tsx, src/components/TableCell/TableCell.tsx, src/features/Domains/ListDomains.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersTableWrapper.tsx, src/features/Volumes/ListVolumes.tsx
Adding a prop, `removeLabelonMobile` to `Table` that will hide the cell label for smaller screensizes. 
This should only affect mobile tables with an entity icon, so Volumes, NodeBalancers, and Domains.
=> M3-2520 Improve placement of entity icons on mobile tables

src/App.test.tsx, src/App.tsx, src/containers/bucket.container.ts, src/features/ObjectStorage/BucketTableRow.tsx, src/features/ObjectStorage/ListBuckets.tsx, src/features/ObjectStorage/ObjectStorageLanding.test.tsx, src/features/ObjectStorage/ObjectStorageLanding.tsx, src/services/objectStorage/buckets.ts, src/store/bucket/bucket.actions.ts, src/store/bucket/bucket.reducer.ts, src/store/bucket/bucket.requests.ts, src/store/index.ts
This PR adds the GET `/buckets` API method and related actions, reducer, and container. ObjectStorageLanding is now using the bucket container, which means the data is real.
**This is the 3rd and final PR for this feature branch.**
To merge first: 
~1) https://github.com/linode/manager/pull/4660~ **DONE**
~2) https://github.com/linode/manager/pull/4665~ **DONE**
**TO DO:** 
You'll need actual buckets (or you could mock them). DM me for details, or use test account 6.
- On ObjectStorageLanding, test Loading, Error, and Empty states.
- Test that the `/buckets` request is being made _only_ if you have the feature flag enabled in `.env`.
Note that the CTA (link to Profile > API Tokens) is only temporary, until creating buckets is supported. This is well documented in the code.
=> M3-OBJ-54 GET buckets API method/actions/reducer/container

src/services/linodes/linode.schema.ts
Fix incorrect client-side validation that didn't allow for `W6` as a backups timeslot option
=> Fix: M3-2525 Allow W6 Backups Timeslot

src/services/account/payments.ts
Previously, we removed all client-side validation on the CVV field while making a payment, but sending an empty string as the payload to API will result in an error.
What actually needed to happen is that the `cvv` key needed to omitted entirely in the request payload if none existed
=> Change: M3-2481 Make CVV Optional

src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
Previously, `MutationNotifications` threw an error if there was no type data, ~crashing the application~ causing an error state.
Now, it simply returns `null` if there is no type data. 
See ticket for testing instructions.
=> M3-2511 Fix: Linodes with no type data cause error state

src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/types/Linode.ts
Added Delete option to Linode action menu
- Renamed some of the existing variables/functions, since the only async actions from the action menu were boot-related and were named accordingly
- There's a separate file with powerActions in it, but I left that alone, since the logic was more specific to booting/rebooting and error handling was different since those are event-based.
- Need feedback on the error/success/loading states
=> M3-2548 Add: Delete Linode from kebab menu

src/eventMessageGenerator.ts, src/types/index.ts
Add some event types and messages for missing new events. 
To test, change some account settings and check your console afterwards. Shouldn't see any "Unknown API Event Received" warnings logged there.
=> Add event types and account events messages

e2e/pageobjects/linode-detail/linode-detail-settings.page.js, e2e/pageobjects/list-stackscripts.page.js, e2e/pageobjects/stackscripts/stackscript-detail.page.js, e2e/specs/stackscripts/stackscript-detail.spec.js, e2e/utils/common.js
Fix StackScripts e2e tests that were failing due to spelling errors.
To test, run: `yarn e2e --file e2e/specs/stackscripts/stackscript-detail.spec.js`.
=> StackScripts e2e test maintenance

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Currently we have a bug when there is no field for the error provided we don't display an error and it fails silently. It's a blocker for permissions configuration because it is lower level.
- Fix error state when there is no error field for NodeBalancers
=> Configure non-field errors for NodeBalancers

src/components/ActionMenu/ActionMenu.test.tsx, src/components/ActionMenu/ActionMenu.tsx, src/components/MenuItem/MenuItem.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx, src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Previously, we disabled a Linode’s "Power On" option if the API response for the Linode didn’t include an image. **Instead we should be checking to see if the Linode has configs.**
This was easy on LinodeDetails, since the configs are already attached to the Linode’s context. 
Not so much on LinodesLanding, because we haven’t requested the configs yet. I opted to send the request for a specific Linode’s configs when the kebab menu for that specific Linode is clicked. This means there is a brief “loading” state on the “Power On” menu item in the ActionMenu.
**TO DO:**
To test, either:
a) Create a Linode in Classic Manager and deploy an image to it.
b) Create a LInode in Cloud Manager from a backup
Then, in Cloud Manager, try to boot the Linode from …
=> M3-2570 Fix: Only disable Linode Boot if there are no configs

e2e/pageobjects/linode-detail/linode-detail-settings.page.js
Fix remove Linode test because the confirmation modal now contains the Linode label
`yarn && yarn start`
`yarn e2e --spec=e2e/specs/linodes/detail/smoke-settings.spec.js --browser=headlessChrome`
=> Fix "Remove Linode" Test

src/store/linodes/linodes.events.ts
Fixes an issue where if the user created a Linode with no image, the events middleware wouldn't do anything, so you would end up looking at the Linode Landing with an indefinitely loading Linode.
Please create a bunch of Linodes, some with images and some without to test
=> Fix: Events Middleware with Creating w/ No Image

e2e/config/wdio.conf.js, e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js, e2e/pageobjects/linode-detail/linode-detail-settings.page.js, e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/list-domains.page.js, e2e/pageobjects/list-stackscripts.page.js, e2e/pageobjects/page.js, e2e/pageobjects/stackscripts/stackscript-detail.page.js, e2e/specs/domains/smoke-list-domains.spec.js, e2e/specs/linodes/detail/create-volumes.spec.js, e2e/specs/linodes/detail/rebuild.spec.js, e2e/specs/linodes/detail/resize.spec.js, e2e/specs/profile/tokens.spec.js, e2e/specs/stackscripts/stackscript-detail.spec.js, e2e/utils/common.js, src/components/ActionMenu/ActionMenu.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/components/TagsCell/TagsCell.tsx, src/features/NodeBalancers/NodeBalancerCreate.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildDialog.tsx
Fix outstanding E2E Tests
`yarn && yarn start`
```
yarn e2e --spec=e2e/specs/stackscripts/stackscript-detail.spec.js,e2e/specs/profile/tokens.spec.js,e2e/specs/linodes/detail/rebuild.spec.js,e2e/specs/linodes/detail/create-volumes.spec.js,e2e/specs/domains/smoke-list-domains.spec.js,e2e/specs/linodes/detail/resize.spec.js,e2e/specs/profile/update-display.spec.js,e2e/specs/linodes/detail/resize.spec.js --browser=headlessChrome
```
=> Test Maintenance

src/App.test.tsx, src/App.tsx, src/containers/bucket.container.ts, src/containers/bucketDrawer.container.ts, src/containers/bucketRequests.container.ts, src/containers/clusters.container.ts, src/features/ObjectStorage/BucketDrawer.test.tsx, src/features/ObjectStorage/BucketDrawer.tsx, src/features/ObjectStorage/ClusterSelect.test.tsx, src/features/ObjectStorage/ClusterSelect.tsx, src/features/ObjectStorage/CreateBucketForm.test.tsx, src/features/ObjectStorage/CreateBucketForm.tsx, src/features/ObjectStorage/ObjectStorageLanding.tsx, src/services/objectStorage/buckets.schema.ts, src/services/objectStorage/buckets.ts, src/services/objectStorage/clusters.ts, src/store/bucket/bucket.actions.ts, src/store/bucket/bucket.reducer.ts, src/store/bucket/bucket.requests.ts, src/store/bucketDrawer/bucketDrawer.actions.ts, src/store/bucketDrawer/bucketDrawer.reducer.ts, src/store/clusters/clusters.actions.ts, src/store/clusters/clusters.reducer.ts, src/store/index.ts, src/store/types.ts, src/types/ObjectStorage.ts
Adds the ability to Create a Bucket.
**TO DO:**
Navigate to the Object Storage page and create some buckets. Try request blocking `/clusters` and `/buckets` to simulate error states.
Sorry this PR got so big. Lots of Redux boilerplate in here.
=> M3-OBJ-56 Change: Create Buckets

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/withLabelGenerator.tsx
Chris wasn't thrilled that our default app labels had "fromapp" in them, so I removed this bit of text from the auto-generated labels. The behavior now closely matches what's found in production.
=> CLAPPS: Adjust default label

src/features/ObjectStorage/ClusterSelect.tsx, src/features/ObjectStorage/ObjectStorageLanding.test.tsx, src/features/ObjectStorage/ObjectStorageLanding.tsx
Now that it's possible to create buckets, I changed the CTA behavior from "Go to API Tokens" to "Add a Bucket".
Also includes tiny adjustment to ClusterSelect.
To test, either
a) Use a test account with no buckets. 
b) Use Charles to edit the response of `/object-storage/buckets`
c) Change line 56 of ObjectStorageLanding.tsx to `if (true) {`
... and go to the Object Storage landing page.
=> M3-OBJ Update Object Storage CTA

src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/PublicImages.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Review feedback part 1
- Fixed shadowed variable name images in PublicImages.tsx
- Re-added Alpine to PublicImages.tsx
- Update error message to use new One-Click Apps branding
- Fix routing when deploying from a backup
=> One-click app feedback

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/utilities/createDevicesFromStrings/createDevicesFromStrings.test.ts, src/utilities/createDevicesFromStrings/createDevicesFromStrings.ts
This turned out to be two separate issues.
1. Our createDevicesFromStrings utility was returning "none_id: null" for
the disk ID instead of null as it should have been.
2. There is a small API bug where POST requests for creating a config are not
validated, whereas PUT requests are. This results in a state where it is possible
to create a config that then can't be updated with its initial values.
Fixed #1 by adding a === 'none' check in createDevicesFromStrings, added
temporary client-side validation for #2. (we could also just punt on #2 and let the API handle errors as it wants, since there's nothing we can do about configs created through the API without using Cloud)
To test: create a config without selecting anything for the disk chosen as the …
=> M3-2578 Fix config updating bug

src/components/TableRow/TableRow.tsx, src/features/Domains/DomainTableRow.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectAppPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/types.ts
Remove any stray logic we had from `SelectStackScriptPanel` that was doing tab handling, since this panel is now tab-less
Also fixed some typings
=> [Cloud Apps] Remove Tab Handling from SelectStackScriptPanel

src/components/Notice/Notice.tsx, src/components/TagsPanel/TagsPanel.tsx
- There's a delay between the user sending the request and the actual tag showing created/deleted resulting in the user being unsure the action took place. I added loading states on the panel for creation/deletion of tags and disabled the form submit to prevent the user from performing the same action repeatedly wondering if anything happened
- There is now Front end validation which allows us to improve the messaging (the tag index was previously part of the error message)
- The styling of the error messaging was off and needed fixing
=> M3-2579 Improve TagPanel workflow

src/features/Profile/APITokens/ObjectStorageDrawer.test.tsx, src/features/Profile/APITokens/ObjectStorageDrawer.tsx, src/features/Profile/APITokens/ObjectStorageKeyMenu.tsx, src/features/Profile/APITokens/ObjectStorageKeyTable.test.tsx, src/features/Profile/APITokens/ObjectStorageKeyTable.tsx, src/features/Profile/APITokens/ObjectStorageKeys.tsx, src/services/profile/objectStorageKeys.ts
Adds a "Rename" option to the OBJ Key kebab menu. This opens the drawer and allows you to edit the label.
This completes the full feature set surrounding Object Storage Keys (for now, at least).
**To Test:**
1) Go to Profile > API Tokens > Object Storage Keys. 
2) Create keys, edit their label, revoke them, etc.
=> M3-OBJ-126 Rename Object Storage Keys

src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
=> M3-2585 Fix missing typography for backup placeholder text

src/features/Support/ExpandableTicketPanel.test.tsx, src/features/Support/ExpandableTicketPanel.tsx
https://jira.linode.com/browse/M3-2538
This change updates the `shouldRenderHively` function so it returns false if the user is "Linode".
As it is when these icons are clicked it leads to an error. 
=> M3-2538: do not show Hively icons from 'Linode' user

src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
Safely navigate to URLs such as this, where the Linode ID is either bad or does not have backups
`http://localhost:3000/linodes/create?type=My%20Images&subtype=Backups&linodeID=12583495`
=> Fix: M3-2622 Safely Navigate to Creation Flow w/ Selected Linode

src/components/PaginationControls/PageNumbers.tsx, src/components/StatusIndicator/index.ts, src/features/Billing/PdfGenerator/PdfGenerator.ts, src/features/Domains/DomainDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/AuthenticationSettings/ResetPassword.tsx, src/features/TopMenu/UserEventsMenu/UserEventsList.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx, src/features/linodes/LinodesDetail/initLinode.ts, src/services/linodes/getLinodeInfo.ts, src/store/events/event.helpers.test.ts, src/store/events/event.helpers.ts, src/store/events/event.reducer.test.ts, src/utilities/isCreditCardExpired.ts
** **Please read the notes at the bottom of this description.** **
Fixes the following tslint warnings:
```
WARNING: src/components/PaginationControls/PageNumbers.tsx:69:1 - asterisks in jsdoc must be aligned
WARNING: src/components/PaginationControls/PageNumbers.tsx:70:1 - asterisks in jsdoc must be aligned
WARNING: src/components/PaginationControls/PageNumbers.tsx:71:1 - asterisks in jsdoc must be aligned
WARNING: src/components/StatusIndicator/index.ts:2:18 - An interface declaring no members is equivalent to its supertype.
WARNING: src/features/Billing/PdfGenerator/PdfGenerator.ts:150:11 - Class name must be in pascal case
WARNING: src/features/Billing/PdfGenerator/PdfGenerator.ts:263:5 - Calls to 'console.error' are not allowed.
WARNING: …
```
=> M3-2631: Fix TSLint warnings

src/features/Volumes/VolumesLanding.tsx
Regina had a call with a customer that was trying to create a Volume in ATL. This option is filtered out when creating a Volume through `/volumes` but it is still available from `/linodes/$linodeID/volumes`. When clicked nothing happens, no error or success message is shown. Console shows:
`POST https://cloud.linode.com/api/v4/volumes 400 (BAD REQUEST)`
This would present them with an option to open a support ticket to migrate to a data center that has block storage available, but it could easily be changed to just show an error message. I thought about filtering out the Volumes tab entirely when the Linode is in us-southeast but I think it's better that people know the reason it is not an option and it then gives them a next step which is to migrate in order to use block storage.
- Non …
=> Update volume landing

src/constants.ts
CA is ambiguous, it's what we use for California
=> Change Toronto display from CA to ON

src/features/Dashboard/VolumesDashboardCard/VolumeDashboardRow.test.tsx, src/features/Dashboard/VolumesDashboardCard/VolumeDashboardRow.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/Volumes/VolumeTableRow.test.tsx, src/features/Volumes/VolumeTableRow.tsx
On both Dashboard and VolumesLanding, if a Volume is attached, it has a column with the Linode's label (which links to the Linode). If it is unattached, this column says "Unattached."
=> M3-2262 Change: Add "Unattached" or Linode label to Volumes

src/components/CheckoutBar/CheckoutBar.tsx, src/components/SelectionCard/SelectionCard.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/index.css
Keeping checkout bar fixed at medium breakpoint + instead of only at larger screens. I also added a word break to the summary title so text won't overflow. 
=> M3-2616 Keeping Checkout bar fixed at md breakpoint+

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
Added `nofail` to the default /etc/fstab entry given at creation of new volume.
This will allow Linodes to boot normally if there is an existing /etc/fstab entry for an unattached volume.
=> DOCS-112: Update - Added "nofail" to VolumeConfigForm.tsx 

e2e/config/wdio.conf.js, package.json, patches/wdio-jasmine-framework+0.3.8.patch, yarn.lock
Patches wdio-jasmine-framework to log exceptions in test hooks so they're not swallowed.
To run relavant E2E tests, run these commands in 3 separate terminals:
3. `yarn e2e --spec=e2e/specs/search/search-tags.spec.js --browser=headlessChrome`
Make sure test runs and passes.
If sufficiently motivated, drop the following code into an `example.spec.js` file:
```
describe('test suite 1', () => {
let b = false;
beforeAll(() => {        
throw new Error("problem in beforeAll");
b = true;
});
it('test case 1', () => {
console.log("test case 1");
expect(b).toBe(true);
}); …
```
=> Adding patch to log errors in jasmine test setup

src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx
The styles for user events drop down needed to be updated as there was hover states for items that had no link. I also made sure these no links items had less opacity in order to differentiate them from clickable events.
updated version ^
=> M3-2618 Fix user events dropdown items styles

src/components/BackupStatus/BackupStatus.tsx
The backups CTA (linode row, linode detail sidebar) was using a regular link and therefore was reloading the whole app on click. Fixed it to use the router Link
=> M3-2617 Fix backup CTA link

src/features/linodes/LinodesLanding/LinodesLanding.tsx
should be a destructive button ^
=> M3-2650 Fix delete Linode button modal button style

src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
**This bug only exists on the `develop` branch. It's not in production**.
To reproduce the issue: 
1) Check out the develop branch. 
2) Have a Linode with Backups. 
3) Go to Create Linode > My Images > Backups. 
4) Observe: "Unknown Plan" is present on each Linode.keywords in the pull request title.
The `extendLinodes()` function needed `images` and `types` to work properly,.
=> M3-2633: Linodes in "Create From Backups" say "Unknown Plan" 

src/components/AccessPanel/AccessPanel.tsx, src/components/PasswordInput/PasswordInput.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
Hiding password helper text for UDF passwords only (root password for create linode should display helper text)
Can view UDF Passwords by viewing a StackScript that has those fields (search for 'basic security' and select the first option)
=> Password Helper Text Display Issue

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectImagePanel.tsx
Fixes issue where Linode Image was being un-selected on cDM if no `imageID` query param existed in the URL
To run relavant E2E tests, run these commands in 3 separate terminals:
3. `yarn e2e --spec=e2e/specs/create/create-linode.spec.js,e2e/specs/create/smoke-configure-linode.spec.js --browser=headlessChrome`
^^^ You will get failures, but the tests are fixed in https://github.com/linode/manager/pull/4772/files. If you rebase with that branch, you'll see the tests pass
=> M3-2645 Fix Select Image

src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Send some more useful data to Sentry in the event of a Paypal failure
Please reach out if you need access to sentry, but this is what the error looks like:
=> Paypal Sentry Reporting

src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Summary header is now static, adding label as a display section underneath by order of section within the create flow. 
=> M3-2614 Remove the word Summary from the Linode Creation flow

src/__data__/stackScripts.ts, src/components/StackScript/StackScript.test.tsx, src/features/StackScripts/stackScriptUtils.ts, src/types/StackScript.ts
Behavior is the same, but API is updating "sequence" field on StackScripts to "ordinal".
NONE
=> Sequence -> ordinal

src/components/IconTextLink/IconTextLink.tsx, src/features/Domains/DomainRecords.tsx
Buttons were too close to the table on compact mode
=> M3-2620 Adjust spacing for add buttons for domain records

src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesLanding/IPAddress.test.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx
We want to show all IP addresses on the sidebar component of the Linode listing page. Added a showAll prop in order to do that. The summary panel is the only place where we want to do that. The table rows should remain identical.
=> M3-2602 List all IP Addresses in summary panel

src/__data__/account.ts, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/types/Account.ts
Adds Account Creation date to the account summary panel
N/A
=> Update: M3-2394 Add Account Creation Date to Summary Panel

src/components/ActionMenu/ActionMenu.tsx, src/components/CircleProgress/CircleProgress.tsx, src/components/ExternalLink/ExternalLink.tsx, src/components/Notice/Notice.tsx, src/components/Placeholder/Placeholder.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/components/SelectionCard/SelectionCard.tsx, src/components/ShowMoreExpansion/ShowMoreExpansion.tsx, src/components/Table/Table.tsx, src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/Dashboard/ViewAllLink.tsx, src/features/Domains/ListDomains.tsx, src/features/Events/EventsLanding.tsx, src/features/Help/Panels/PopularPosts.tsx, src/features/Help/Panels/SearchItem.tsx, src/features/Profile/APITokens/APITokenDrawer.tsx, src/features/Support/ExpandableTicketPanel.tsx, src/features/TopMenu/UserEventsMenu/UserEventsButton.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationListItem.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx, src/features/linodes/LinodesCreate/AddonsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/features/linodes/LinodesLanding/LinodeCard.style.ts, src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx, src/features/linodes/LinodesLanding/ToggleBox.tsx, src/themeFactory.ts
In conjunction with the compact mode, we need to de-emphasize most UI elements by removing their bolding in order to offer more clarity to thew page and help with the overall hierarchy. This was done by implementing a new `theme.font.bold` in `themeFactory` that keeps the bolding for the normal theme but turns it off when the compact more is activated.
N/A
=> M3-2606 Unbold most of the things in compact mode

src/features/linodes/LinodesCreate/LinodeCreate.tsx
Making beta tag blue regardless of theme so it is more apparent to users. 
=> M3-2661 Make beta tag for CA Tab blue on both themes

src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx
From Caker review, available space should be last: Total > Used >> Free
N/A
- /dashboard
- /linode/{id}/summary
avail disk space in settings > adv configs has also been updated to reflect this [here](https://github.com/linode/manager/pull/4811)
=> M3-2597 re-order fields on monthly network transfer panels

src/components/TableRow/TableRow.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Domains/DomainTableRow.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/themeFactory.ts
We previously had extra links in the clickable rows to make sure we could add a focus when tabbing through. This adds duplication and weird focus styles and needed a cleanup. I removed them and added tabIndex on the rows that have links as well as matching focus styles with hover styles as well as making sure clicking enter on the keyboard acts as a click.
N/A
to test on entity clickable rows both in landing pages and dashboard (linodes, nodeBalancers & domains)
=> M3-2514 Update focus states for clickable rows

src/components/CopyTooltip/CopyTooltip.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/features/linodes/LinodesLanding/SortableTableHead.tsx
Per the Caker review, we get rid of the tag column and IPV6 listing in the table rows for both linodes and nodeBalancers. I updated col widths accordingly and styled a few regressions.
N/A
=> M3-1913 Remove IPV6 addresses and tag columns from rows

src/components/ViewAllLink/ViewAllLink.tsx, src/components/ViewAllLink/index.ts, src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummaryContent.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummaryContent.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Add a Activity Feed section to LinodeDetail/summary
None
I also updated the layout of LinodeDetailSummary to match the new-ish design (see ticket for link to Invision)
=> M3-2298 Add: event stream summary

src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
=> M3-2658 Update table cell sizes

src/utilities/getLinodeDescription.ts, src/utilities/safeGetImageLabel/safeGetImageLabel.test.ts, src/utilities/safeGetImageLabel/safeGetImageLabel.ts
Previously if there wasn't a provided image slug, we were returning 'No Image'. Now, we will display nothing if the image slug does not exist. The check for `Unknown Image` is still present though.
This impacts both dashboard and linodes list views.
=> M3-2603 Update to Linode List - Plan details

src/themeFactory.ts
Small update to style the right scroll tab button the same as the scroll left one for consistency as we are entering the world of many tab items on linode details
=> M3-2666 Update scroll buttons styles for mobile tabs

src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx
The browser's back button wasn't working correctly on Support Ticket Details, because we were pushing a extra item to history to clear its `state`. I changed this to the `history.replace` method to achieve the same thing without the extraneous history item. 
I also made a change so that clicking on a tab ("Open" or "Closed") is reflected in browser history. The downside is that this results in a double render, which I haven't found a way around. This problem exists elsewhere in the app, so I'll create a ticket to address it site-wide.
Please test all Support Ticket functionality: Browser back/forward buttons, Breadcrumb Component links, etc.
=> M3-2655 Fix: Routing on Support Ticket pages

src/components/DateTimeDisplay/DateTimeDisplay.test.tsx, src/components/DateTimeDisplay/DateTimeDisplay.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
Typography was not properly setup for activity items and related dates. `variant="inherit"` is not to be used. better to leave the default (which is no variant)
=> M3-2679 Fix Typography for new Activity Feed and update tests

src/features/ObjectStorage/ListBuckets.tsx
It was missing a `removeLabelonMobile` prop.
=> Hide label for Bucket Table on mobile

e2e/config/wdio.axe.conf.js, e2e/config/wdio.conf.js, e2e/setup/cleanup.js, e2e/utils/cred-store.js, e2e/utils/fs-cred-store.js, e2e/utils/mongo-cred-store.js
We often get test failures because of data that was not cleaned up from a previous test. Let's run the tearDown script on initialization and see of that helps
=> M3-2677 TESTS: Cleanup account data on test initialization

patches/chart.js+2.7.3.patch, src/components/LineGraph/LineGraph.stories.tsx, src/components/LineGraph/LineGraph.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Displays the charts in LinodeSummary using the user's timezone.
I had to patch-package to make this work, so it's entirely possible the cure is worse than the disease. Longer term we can and probably should switch to Rechart or something similar that gives us more control. Future versions of Chart.js are also expected to include this functionality.
=> M3-2642 Fix: chart timezone

src/components/TableCell/TableCell.tsx
Adjustments to TableRow for mobile devices, specifically for Domains, NodeBalancers, and Volumes.
Please view the ticket to see the exact bug, as this is not reproducible with chrome emulator. This would be best to test on an actual device or using XCode Simulator to replicate an accurate experience.
=> M3-2678 Mobile Tables Titles

src/components/EnhancedSelect/Select.tsx, src/features/Images/ImagesDrawer.tsx, src/features/Images/ImagesLanding.tsx, src/features/linodes/DiskSelect/DiskSelect.tsx
The only instance of this component lives in ImagesDrawer. If there's anywhere else in the app where disks are selected in a dropdown (by themselves, we already have a specialized thingy for disks & volumes), please flag it for me.
=> M3-2134 Change: Use EnhancedSelect for DiskSelect component

src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx
This fixes the logic which will disable the Resize/Delete disk options and display a tooltip when a Linode is powered on. It will also show a tooltip when the user is ReadOnly
=> M3-2693 Fix: disk action menu tooltip logic

src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
See this exchange from https://github.com/linode/manager/pull/4181:
**Now that we're greying out events of deleted entities, we can safely remove this logic.**
=> M3-2692 Change: messaging in UserEventsList for deleted entities

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/services/linodes/getLinodeInfo.ts, src/types/Linode.ts, src/utilities/initAll.test.ts, src/utilities/initAll.ts, src/utilities/statMetrics.tsx
Occasionally the last reading of each stats array is incorrectly `0`. So we ignore it.
See the ticket (and comments) for more details.
I opted to use a recursive helper function here so that it's flexible and could be used easily with both Linodes and NodeBalancers. I'm open to feedback though if this approach is too magical. See my first commit on this PR for a more declarative version.
I also fixed some typing issues with the services library.
To test, view a Linode with graph data. Look at the `/stats` request in Dev Tools and verify that we're not displaying the last element of each of the stats arrays. Repeat with a NodeBalancer.
=> M3-2562 Change: Don't use last Stats reading, because sometimes it's wrong

src/features/ObjectStorage/BucketTableRow.test.tsx, src/features/ObjectStorage/BucketTableRow.tsx
I forgot to do this in the original implementation.
To test, go the the Object Storage landing page and look at buckets with different numbers of items.
=> OBJ-149: Pluralize number of items in buckets.

src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, src/services/stackscripts/stackscripts.schema.ts
There is currently an API bug where StackScript Images are not being validated on PUT. Images actually should be required, so I updated the our client-side schema to check that `images` is not empty when updating a StackScript.
Try editing a StackScript – specifically, adding/removing images.
=> M3-2704 change: Validate presence of images during StackScript update

src/__data__/axios.ts, src/features/ObjectStorage/ListBuckets.tsx, src/utilities/errorUtils.test.ts, src/utilities/errorUtils.ts
`getErrorStringOrDefault` wasn't properly handling AxiosErrors, but was being passed them in several components. Handled this case in the function rather than adjust the consumers.
Also addressed the @todo in ListBuckets that was waiting on this change.
=> M3-2702 Fix: errorUtils bug

src/layouts/Logout.test.tsx, src/layouts/Logout.tsx, src/services/authentication/index.ts, src/services/index.ts, src/store/authentication/authentication.requests.ts
Expire token on logout
1. User clicks logout
2. We hit an endpoint to expire the token
3. Then redirect the user to login
Use development api services
Your OAuth App must be public. In other words, the _Public_ checkbox must be clicked.
=> Change: M3-2084 Expire Token on Logout

e2e/utils/common.js, src/containers/withLinodes.container.ts, src/features/Images/ImagesDrawer.tsx, src/features/Images/ImagesLanding.tsx, src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx
Replace the ImagesLanding LinodeSelect with one that uses our enhanced select. Previously you could only choose from the first page of Linodes when creating an Image; now you get everything in the store as an option, and can search as well.
None
There are other places in the app where this could be useful, we can add them later. This component is already used in VolumeAttachmentDrawer so that's been updated, but other places include VolumeCreateForm [...todo figure out all the remaining places]
=> M3-1388 Update: Use EnhancedSelect for selecting Linodes

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx, src/services/nodebalancers/configNodes.ts, src/store/store.helpers.ts
Add polling for NodeBalancers on NB landing and detail pages. This keeps the "Nodes: 1 up, 2 down" status indicators in both locations up to date.
None
- prod-test-004 is set up with a NodeBalancer & 5 nodes. Just open a new tab and boot/shutdown any of the `example-instance` Linodes, then wait a bit.
- Current interval is 30 seconds; feedback welcome.
- I used the existing `getAllNodeBalancersWithConfigs` Thunk, since it's safe and reuses existing logic. We might be able to slightly lower network usage by only getting configs for NBs already in Redux state but I didn't think this was worth it.
- NodeBalancerDetail has a NodeBalancerContext but I'm not completely clear what it's doing. I pulled out the PromiseLoader/preloaded business, and …
=> M3-2502 Update: polling for NodeBalancer node status

CODE_STYLE.md, src/components/Paginate.ts, src/features/Domains/DomainRecords.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/ListGroupedDomains.tsx, src/features/Images/ImagesLanding.tsx, src/features/NodeBalancers/NodeBalancersLanding/ListGroupedNodeBalancers.tsx, src/features/NodeBalancers/NodeBalancersLanding/ListNodeBalancers.tsx, src/features/ObjectStorage/ListBuckets.tsx, src/features/Volumes/ListGroupedVolumes.tsx, src/features/Volumes/ListVolumes.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.test.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/DisplayLinodes.tsx, src/store/linodes/config/config.requests.ts, src/store/linodes/disk/disk.requests.ts
Remove Pagey from Disks and Configs panel in favor of Paginate render-props component
N/A
Also removed the auto scroll-to-top from disks and configs because they don't have their own dedicated pages, so it would make sense. We should implement some sort of scroll-to-id feature, similar to `scrollToError`
=> Change: M3-2669 Paginate Disks and Configs with Paginate Render Props Component

src/features/Lish/Lish.tsx, src/index.css
Tabs were showing the scrollbar by default so that is fixed. I also updated the active tab state to make it more clear as well as adding some padding to the lish console itself. Should improve the UX quite a bit.
=> M3-2703 Lish tabs style updates

src/themeFactory.ts
On a sortable table cell:
- Arrow should be pointing up for ascending order
- Arrow should be pointing down for descending order.
=> M3-2718 Reverse sorting arrows for sortable tables

src/components/ActionMenu/ActionMenu.tsx, src/features/Volumes/SortableVolumesTableHeader.tsx, src/features/Volumes/VolumeTableRow.test.tsx, src/features/Volumes/VolumeTableRow.tsx, src/features/Volumes/VolumesLanding.tsx, src/themeFactory.ts
The volumes landing table was problematic as the content would make it scrollable and hide the action menu at certain breakpoints. So i had to wrap/break the system path strings. I made sure to keep in check the volumes table on the linodes detail as well
=> M3-2705 Volumes tables style updates

e2e/config/wdio.axe.conf.js, e2e/config/wdio.conf.js, e2e/setup/cleanup.js, e2e/utils/cred-store.js, e2e/utils/fs-cred-store.js, e2e/utils/mongo-cred-store.js
Reverts calling `credStore.cleanupAccounts` in the before hook of the test framework.
=> E2E - Revert cleanup in before hook

src/components/PrimaryNav/PrimaryNav.tsx
The previous positioning was only temporary. Now the placement has been decided on.
None.
=> OBJ-152: Change Object Storage placement in the Primary Nav

src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesLanding/IPAddress.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx
In order to get a consistent experience from list view to card view, it makes sense to list all IP addresses on card view to be able to copy the addresses quickly without the use of the pop-up.
Updated margins as well
=> M3-2680 Update IP address listing on card view and styling

src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/utils.ts
We weren't displaying errors with a `region` field, bc this is a Formiked component and there is no `region` input to match the error. Put the error in the general error Notice instead.
None
1. Create a Linode in Toronto
2. Navigate to that Linode's detail, Volumes tab
3. Create a Volume
4. On Cloud, no error is shown. With this PR, you should get a Notice telling you that Volumes in Toronto don't work yet (unless they've been fixed before you're reading this, in which case who knows)
=> M3-2594 Fix: Explicitly display regions error in Linode Volumes form

e2e/specs/create/create-linode-from-stackscript.spec.js
Adding an e2e that checks that upon clicking anywhere on a stackscript table row, that stackscript will be selected.
3. `yarn e2e --file e2e/specs/create/create-linode-from-stackscript.spec.js --browser=headlessChrome`
=> M3-OCA-664 Add: e2e test for Create from StackScript 

src/features/Profile/DisplaySettings/DisplaySettings.test.tsx, src/features/Profile/DisplaySettings/DisplaySettings.tsx, src/features/Profile/DisplaySettings/TimezoneForm.test.tsx, src/features/Profile/DisplaySettings/TimezoneForm.tsx, src/store/profile/profile.requests.ts, src/utilities/formatDate.ts
Using the `isLoggedInAsCustomer` value from Redux, set the timezone (also in Redux) to the browser's timezone when logged in as customer.
None
You'll have to use devenv (or use some clever method to capture the redirect urls from linode/admin): http://localhost:3000/admin/callback#access_token=ec592ecb23e08bbcc0c8008b0898858436df564e04e8975603fdfbe1238e4406&destination=linodes&token_type=Admin&expires_in=7200
I had trouble getting to a place in Manager where the time display was visible and not humanized (in devenv, that is), but the current timezone is displayed at /profile/display. Vagrant (the user you're impersonating) is set to GMT, your browser is likely EDT.
=> M3-1842 Change: Use browser timezone when logged in as customer

src/__data__/events.ts, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/store/events/event.helpers.test.ts, src/store/events/event.helpers.ts, src/store/events/event.reducer.test.ts, src/store/events/event.reducer.ts
Subscribes to Redux state to update events automatically in the Activity Stream without needing a refresh.
N/A
This does not affect the events landing.......yet. This is simple a POC that will also affect that view if this approach is received well.
=> Change: M3-2696 Update Activity Stream Based on Events

src/App.tsx, src/containers/volumes.container.ts, src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx, src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/features/linodes/LinodesDetail/maybeWithExtendedLinode.tsx, src/features/linodes/LinodesDetail/types.ts, src/store/store.helpers.test.ts, src/store/store.helpers.ts, src/store/types.ts, src/store/volume/volume.actions.ts, src/store/volume/volume.reducer.ts, src/store/volume/volume.requests.ts, src/store/volume/volume.selector.ts, src/utilities/errorUtils.ts
Removes Volumes from the `maybeRenderError` component.
N/A
New volumes error state in Redux looks like the following: 
```
{
read: Linode.APIFieldError[],
create: Linode.APIFieldError[],
update: Linode.APIFieldError[],
delete: Linode.APIFieldError[]
}
```
First of all, the requests from the services library still return `AxiosError`. They are not converted to `Linode.APIFieldError[]` until we get to the reducer
So:
1. Service function request runs
2. Rejects with `AxiosError`
3. Redux Action is invoked with `AxiosError`
4. In the reducer, `getAPIErrorOrDefault()` is invoked with the `AxiosError`
5. Redux State is set: `{ error: { read: getAPIErrorOrDefault(myError) } }`
All the functions in `store.helpers.ts` are backwards compatible. The error …
=> Remove Volumes From MaybeRenderError

src/components/TagsPanel/TagsPanel.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesDialog.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/DisableTwoFactorDialog.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/services/linodes/linodeActions.ts, src/store/backupDrawer/index.ts, src/store/tagImportDrawer/index.ts
Searched for `['response', 'data', 'errors', 0, 'reason']` and replaced with `getErrorStringOrDefault`. End goal is to avoid passing Axios errors to components, and this single interface guarantees that any change we make won't break things.
None
=> M3-2107 Part I: Replace all pathOr<string>s with getErrorStringOrDefault

src/App.tsx, src/components/EntityIcon/EntityIcon.tsx, src/themeFactory.ts, src/utilities/storage.ts
Three optimizations made surrounding local storage:
1. Removed a function that accessed local storage on every re-render, which AFAICT is unnecessary.
2. EntityIcon now checks the theme object instead of local storage for compact mode (this was happening for every re-render of every Entity Icon).
3. I added a plain JavaScript object to cache local storage values, since we're reading local storage _a lot_ (like, 100 times on every render). Theoretically, accessing values from an object is faster than local storage: https://jsperf.com/localstorage2.
The third item is sort of POC-ish, and if we don't like it, I'll rebase to drop the commit and we can merge the first two optimization. 
FWIWI, once we get a user preferences endpoint, all of this will basically be unnecessary.
- Optimization …
=> M3-2497 Local storage optimizations

src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx, src/features/Billing/BillingPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/DomainZoneImportDrawer.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, src/features/linodes/LinodesLanding/powerActions.ts
Trying to keep these PRs manageable. Started replacing `['response', 'data', 'errors']` with `getApiErrorOrDefault`, but there's more variation with these so I had to fix some things. 
=> M30-2107 Phase 2: more error handling

src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx, src/types/Linode.ts
The API now returns reserved IPv4 addresses (used in cross data-center migrations). 
In this PR, they've been added to the IPv4 table in Linode Details -> Networking.
To test:
1) Have a Linode with a pending migration.
2) Navigate to Linode Detail -> Networking.
3) Observe: reserved IPs appear in the IPv4 table.
Reserved IPs cannot be deleted, and RDNS cannot be edited. `Public Reserved` and `Private Reserved` are both possible.
=> M3-2648 Change: Display reserved IPs in IPv4 table (Linode Detail)

src/features/linodes/LinodeSelect/LinodeSelect.tsx
Volume attachment drawer was always showing an error because the default was an empty array and `![] === false` in JS
N/A
=> Fix: Volume Attachment Always Shows Error

src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
We don't get stats for a Linode until at least 5 minutes after it has been created. So before requesting stats, make sure the Linode was created more than 5 minutes ago. Doing this avoids an expensive `/stats` request and console errors.
**EDIT:** There's still a stats request that will error-out. It's for LinodeNetSummary, and since that will be taken out in a few weeks when we get an endpoint for per-Linode network transfer, I left it in.
=> M3-2290 Change: Stats request optimization

CODE_STYLE.md, src/components/Paginate.ts, src/components/core/RootRef.ts, src/features/Domains/DomainRecords.tsx, src/features/Domains/ListDomains.tsx, src/features/Domains/ListGroupedDomains.tsx, src/features/Images/ImagesLanding.tsx, src/features/NodeBalancers/NodeBalancersLanding/ListGroupedNodeBalancers.tsx, src/features/NodeBalancers/NodeBalancersLanding/ListNodeBalancers.tsx, src/features/ObjectStorage/Buckets/ListBuckets.tsx, src/features/Volumes/ListGroupedVolumes.tsx, src/features/Volumes/ListVolumes.tsx, src/features/linodes/LinodesCreate/SelectLinodePanel.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, src/features/linodes/LinodesLanding/DisplayLinodes.tsx
Scrolls to the header of the paginated data for disks and configs
N/A
Have lots of disks and configs and start switching pages
=> Add: M3-2694 Scroll-to logic for Disks and Configs page changes

scripts/pre-push.sh, src/App.tsx, src/__data__/kubernetes.ts, src/components/OrderBy.ts, src/components/PrimaryNav/PrimaryNav.tsx, src/constants.ts, src/features/Kubernetes/ClusterList/ClusterList.test.tsx, src/features/Kubernetes/ClusterList/ClusterList.tsx, src/features/Kubernetes/ClusterList/ClusterRow.test.tsx, src/features/Kubernetes/ClusterList/ClusterRow.tsx, src/features/Kubernetes/ClusterList/index.tsx, src/services/kubernetes/index.ts, src/services/kubernetes/kubernetes.ts, src/types/Kubernetes.ts
Add a list of Kubernetes clusters at `/kubernetes`. Almost entirely boilerplate of the sort we use on all landing pages. See Notes for details.
None
- Add `REACT_APP_KUBERNETES_ENABLED='true'` to your `.env` file
- Follow KB steps for setting up devenv to work with the new LKE API (PM for link)
- To test pagination, you'll have to run Anton's `post-cluster.sh` script a bunch of times, maybe swapping a few values (version, label, created) here and there.
- Only routing/landing page; Add a Cluster button is present but disabled.
- Data management is a little up in the air; the comps make it look like we'll be grouping by tag here, which means that we'll need to Redux this (or at least getAll on page load), and use the Paginated component. I used …
=> LKE-473 List Kubernetes clusters

src/components/PrimaryNav/PrimaryNav.tsx, src/containers/bucketRequests.container.ts
Currently, clicking on "Object Storage" in the Primary Nav results in this:
This PR makes it so that it results in this:
Note the bolding of the tab title "Buckets". 
=> Fix: Add /buckets to OBJ link in PrimaryNav

src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Some UDFs were getting cutoff depending on screen size. To test, go to linode create flow, and select an OCA that has selects, such as CSGO or minecraft. You should observe the right border of the selects is no longer being cutoff no matter your screen size. 
=> Dropdown fields in OCA creation screen get cut off

src/components/PaginationControls/PageNumbers.test.tsx, src/components/PaginationControls/PageNumbers.tsx
There are a few problems with the page numbering of our pagination footer:
This PR attempts to fix these issues.
Test multiple pages with varying page numbers. Click on each page number and ensure the sequence makes sense. Here's where you can find different page numbering combinations:
**11 pages:** Test Account 1 - Linodes
**7 pages:** Test Account 1 – Domains
**6 pages:** Test Account 9 – Domains (remove one domain to make it 5 pages)
=> M3-2322 Fix: Pagination Footer numbering

src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
Adds ipv6 prefix to each range table row
3. `yarn e2e --spec=e2e/specs/linodes/detail/networking.spec.js --browser=headlessChrome`
Only showing prefix for ipv6 range as per feedback from @asauber
=> Add: Prefix Length to the IPv6 Pools and Ranges

src/components/EnhancedSelect/EnhancedSelect.stories.tsx, src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Fixes 2 sentry errors
1. Backups error state wasn't being rendered
2. Storybook select had an undefined value and was trying to lower-case it.
N/A
=> Fixing Sentry Errors

src/__data__/events.ts, src/components/EntityIcon/EntityIcon.tsx, src/features/Events/Event.helpers.test.ts, src/features/Events/Event.helpers.ts, src/features/Events/EventRow.test.tsx, src/features/Events/EventRow.tsx, src/features/Events/EventsLanding.test.ts, src/features/Events/EventsLanding.tsx, src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.test.tsx, src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, src/store/events/event.helpers.test.ts, src/store/events/event.reducer.test.ts, src/store/middleware/combineEventsMiddleware.ts
Adds similar logic from the activity summary to the events landing page so we can update the list of events with new events from Redux as they come down.
N/A
`useReducer` is basically acting as `shouldComponentUpdate`
https://reactjs.org/docs/hooks-reference.html#usereducer
=> Add: Update Events Landing in Real-Time

package.json, src/exceptionReporting.ts, yarn.lock
Updates Sentry whitelist URLs to be correct and also include localhost:3000
N/A
Upgraded Sentry because of:
https://github.com/getsentry/sentry-javascript/issues/1891
=> Update Sentry Whitelist URLs

src/features/Billing/PdfGenerator/PdfGenerator.ts
Make sure we don't call `split()` on an undefined item.
- Use Charles to break on /invoices/id/items, then use:
```
{
"pages": 1, 
"data": [
{
"quantity": null,
"amount": "40.00",
"tax": 0,
"from": "2019-03-01T05:00:00",
"type": "prepay",
"total": "40.00",
"to": "2019-04-01T03:59:59",
"unit_price": null,
"label": "Linode 8GB"
},
{
"quantity": null,
"amount": "10.00",
"tax": 0, 
"from": "2019-03-01T05:00:00",
"type": "prepay",
"total": "10.00",
"to": "2019-04-01T03:59:59",
"unit_price": null,
"label": "Backup Service - Linode 8GB"
}
],
"page": 1,
"results": 2
}
```
for the body.
=> Fix: invoice split

src/__data__/notifications.ts, src/components/AbuseTicketBanner.tsx, src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx, src/components/AbuseTicketBanner/AbuseTicketBanner.tsx, src/components/AbuseTicketBanner/index.tsx, src/features/Dashboard/Dashboard.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/linodes/LinodesLanding/LinodeCard.test.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, src/store/selectors/getAbuseTicket.ts, src/store/selectors/index.ts, src/types/index.ts, src/utilities/testHelpers.tsx
Display a banner on the Dashboard and tickets landing pages if the customer has an open abuse ticket. 
Prod-test-001 has an open abuse ticket. Please check both the dashboard and support/tickets.
=> M3-2757 Add: abuse ticket banner

src/components/TableRow/TableRow.tsx
Fixing a regression with not being able to use meta/ctrl key while clicking when wanting to open entity detail in new tab (table rows)
=> M3-2754 Update: Enable ctrl-click on clickable rows

src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
This PR fixes 3 issues
1. Previously, if a stats request on Linode Detail succeeded and the next one failed, an error view would appear
2. Previously, if a stats request on NodeBalancer Detail succeeded and the next one failed, an error view would appear
3. If the NodeBalancer detail polling first succeeded and the next one failed, an error view would appear.
Basically, we should not be removing the data state even if a subsequent request fails.
N/A
=> Fix: Error Views on Linode and NodeBalancer Detail

e2e/specs/nodebalancers/error-handling.spec.js, src/constants.ts, src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/Volumes/VolumeDrawer/utils.ts, src/services/index.test.ts, src/services/index.ts, src/store/volume/volume.actions.ts, src/store/volume/volume.requests.ts, src/utilities/errorUtils.test.ts, src/utilities/errorUtils.ts, src/utilities/request.ts
Retrieved API errors from our Axios interceptors, so that consuming components will only ever receive Linode.ApiFieldError[] and won't have to deal with Error or AxiosError responses. Also updated `getApiErrorOrDefault`, some typings, and tests to reflect the new pattern.
We'll run the full suite when we think this is ready for a merge.
Please test as many error states as possible. I've done EditableText, Images, Domains, and a few other spot checks.
=> M3 Update: Axios interceptor

src/features/ObjectStorage/Buckets/BucketTableRow.test.tsx, src/features/ObjectStorage/Buckets/BucketTableRow.tsx, src/features/ObjectStorage/Buckets/ListBuckets.test.tsx, src/features/ObjectStorage/Buckets/ListBuckets.tsx
This came out of review feedback on 5/8.
Exact copy hasn't been discussed – open to feedback.
Make sure OBJ is enabled. Look at the Buckets landing page.
=> OBJ-159: Split "Size" column into "Objects" and "Size"

src/App.tsx, src/components/ErrorState/ErrorState.tsx, src/containers/withLinodes.container.ts, src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/store/linodes/linode.requests.ts, src/store/linodes/linodes.actions.ts, src/store/linodes/linodes.events.ts, src/store/linodes/linodes.reducer.ts, src/store/selectors/entitiesErrors.ts, src/store/selectors/entitiesLoading.ts, src/store/types.ts
Changes Linode error state to fall in line with the previous PR. Linode Redux Error State now looks like:
```js
{
read?: Linode.APIError[],
create?: Linode.APIError[],
delete?: Linode.APIError[],
update?: Linode.APIError[]
}
```
N/A
=> Refactor Linode Error State

src/features/Support/AttachFileForm.tsx, src/features/Support/AttachFileListItem.tsx, src/features/Support/ExpandableTicketPanel.tsx, src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyActions.tsx, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx, src/features/Support/SupportTicketDetail/TabbedReply/index.ts, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/Support/TicketDetailText.tsx, src/features/Support/index.ts
This is mostly a refactor to the structure of the ticket detail reply components.
I created a container element and am passing down state and handlers as props. This is solving for the issue where the entire ticket attachment list was re-rendering every time the input was changed, which was very slow.
Coming up in the next PR....
1. Prevent Form Submission with bad markup
2. Code Highlighting
3. Preview Tab
3. `yarn e2e --spec=e2e/specs/support/smoke-tickets.spec.js`
=> Markdown Part 2: Refactor to Ticket Detail

src/features/Users/UserDetail.tsx, src/features/Users/UserProfile.tsx
The difficult with this is:
a) Username is only editable at `/account`
b) Email is only editable at `/profile`
Therefore the “User Profile” form had to be separated into two parts. “Email” is disabled if an account owner is looking at another user’s profile (account owners don’t have the ability to change other user’s email addresses.)
Please test a range of success/failure states, as there are two forms to deal with.
=> M3-2560 Add: Ability to update email from account -> user profile

src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Reverts https://github.com/linode/manager/pull/4388. At the time, this copy hadn't been finalized anywhere. Now that we have finalized copy for this in classic, we may as well use it here and re-enable it.
=> re-enable plan type copy and update the text

src/eventMessageGenerator.ts
Feedback welcome... the host initiated restart messages in particular are awkward ... probably a better way to phrase all of this that doesn't use "via"
=> Add event messages for host and lassie reboots and lish boots

src/constants.ts, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingSummaryPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/resolvers.test.ts, src/features/linodes/LinodesDetail/LinodeNetworking/resolvers.ts, src/types/Networking.ts
There were two problems with the way we were displaying IPv6 resolvers.
1) We weren't displaying the full addresses.
2) We were displaying IPv6 resolvers for every region, when we should only be displaying resolvers for the region of the particular Linode we're looking at.
Also, I added new typing: `ZoneName` (region name?). Wasn't totally sure what to call this; feedback welcome.
Please assume I made a mistake in copying the resolvers over, and thoroughly check that they're all correct. Test account 9 has a Linode in every region to help with this.
=> M3-2787 Fix: IPv6 DNS Resolvers

src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/constants.ts, src/features/linodes/LinodesDetail/LinodeNetworking/resolvers.ts, src/types/Networking.ts, src/utilities/doesRegionSupportBlockStorage.test.ts
~Wait for #4928 to be merged, then rebase feature branch with develop and drop 2a5d1c87804a7496a87aa921944517fb4bccf2d9 from this PR.~ DONE
Adds support for Mumbai. Merging this into a feature branch until launch, so we can coordinate with API.
1) Use Charles to add `{"country": "in", "id": "ap-west"}` to the response for `/regions`. 
2) Go through the Linode Create flow, NodeBalancer Create flow, & Volume Create flow.
Prod test account 9 has a Linode in Mumbai, called `ap-west`, which you can use to look at the DNS resolvers on the LinodeNetworking page.
=> M3-2346 Add: Mumbai region in Linodes Create

e2e/pageobjects/linode-detail/linode-detail-volume.page.js, e2e/pageobjects/volumes.page.js, src/components/EnhancedSelect/Select.tsx, src/features/Volumes/DestructiveVolumeDialog.tsx, src/features/Volumes/RenderVolumeData.tsx, src/features/Volumes/VolumeDrawer/LinodeSelect.tsx, src/features/Volumes/VolumeDrawer/RegionSelect.tsx, src/features/Volumes/VolumeTableRow.tsx, src/features/Volumes/VolumesActionMenu.tsx, src/features/Volumes/VolumesLanding.tsx
Adds Volume and Linode label to volume dialogs (delete and detach)
3. `yarn e2e --spec=e2e/specs/create/smoke-create-attached-volume.spec.js --browser=headlessChrome`
=> Add: Linode and Volume Labels to Volume Dialogs

e2e/pageobjects/list-linodes.js, e2e/specs/linodes/smoke-linodes.spec.js, e2e/specs/linodes/smoke-reboot-linodes.spec.js, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx
Includes the Linode Label in the delete dialog on the Linode Landing page
3. `yarn e2e --spec=e2e/specs/linodes/smoke-linodes.spec.js,e2e/specs/linodes/smoke-reboot-linodes.spec.js --browser=headlessChrome`
=> Change: Includes the Linode Label in Delete Dialog Modal

src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.test.tsx, src/features/linodes/LinodesDetail/LinodeRescue/DeviceSelection.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
This was a bug ticket from Support, but I wasn't able to reproduce the error in production. However, development was broken due to the use of GroupType with EnhancedSelect, so I fixed that.
None
To test, visit the Advanced tab of Linode Detail and open a config for editing. The Device Assignment dropdowns should populate and update as expected.
=> M3-2643 block device assignment

patches/@types+sanitize-html+1.18.3.patch, patches/sanitize-html+1.20.1.patch, src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, src/utilities/sanitize-html/sanitize-html.test.ts, src/utilities/sanitize-html/sanitizeHTML.ts
Renders Blacklisted tags as text, including unknown tags.
This will still strip the attributes, please note.
N/A
Try variations of
'''  <------ pretend these are backticks
<script src="hello.js"></script>
'''
<script>alert('hello world');</script>
<marty>Hello world</marty>
<p><script></script></p>
=> Markdown: Render Blacklisted Tags as Text

src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
Entering the migration queue by clicking "click here" didn't result in any UI feedback, even though the request to `/migrations` might have been successful.
The `withSnackbar` HOC wasn't being included in the export for the component, so the success toast wasn't actually appearing.
Additionally, the `.catch()` function was empty, so an error toast has been added here.
_Note:_ There's another ticket, M3-2509, which states that we should request notifications as soon as migrations start, which would clear the "Migration imminent" notification once the migration starts. Once that's done, this flow will be even better.
**TO TEST:**
_The happy path:_
1) Configure a migration for a Linode.
2) Navigate to that Linode's Details page.
3) Click "click here" on the …
=> M3-2414 fix: UI experience when entering migration queue

src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx, src/services/linodes/getLinodeInfo.ts, src/utilities/unitConversions.test.ts, src/utilities/unitConversions.ts
With this PR, we fix the per-linode Network Transfer information on LinodeDetails. To do this, we consume a new API endpoint:
`/linode/instances/:id/transferpool`
This is in contrast to the hacky way we were doing it before, where we (incorrectly) used the `/stats` data.
None.
**IMPORTANT: This new endpoint is not in production yet. You must use dev services.**
To test, use dev services and look a several Linodes, noting the network transfer. Modify the request within the code or Charles to see different values for `used`.
Much of this PR is actually adding several options to the `readableBytes()` utility function, which were needed to display the network transfer info in a friendly and intuitive way. I did a bit of annotating and refactoring to make …
=> M3-2699 fix: Per-linode network transfer pool

scripts/pre-push.sh, src/features/ObjectStorage/Buckets/BucketActionMenu.test.tsx, src/features/ObjectStorage/Buckets/BucketActionMenu.tsx, src/features/ObjectStorage/Buckets/BucketTableRow.tsx, src/features/ObjectStorage/Buckets/ListBuckets.test.tsx, src/features/ObjectStorage/Buckets/ListBuckets.tsx, src/services/objectStorage/buckets.ts
TODO:
By default, the API returns an error when attempting to delete a bucket with items in it.
A new API feature allows a `force` option, which recursively deletes every item in the bucket, and then deletes the bucket itself.
This PR uses the `force` option when deleting a bucket from the landing page.
Attempt to delete a bucket with objects in it. It should work.
=> OBJ-158 Change: Force-delete buckets

src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx, src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
Instead of mapping over an array of abuse tickets, display a single alert banner
with the total number of open tickets.
=> Aggregate multiple abuse tickets

e2e/pageobjects/domain-detail/detail.page.js, e2e/specs/domains/detail-add-records.spec.js, src/features/Domains/DomainRecordDrawer.tsx, src/services/domains/domains.schema.ts
Values for axfr_ips were typed as string[], but the string input
was never being split. Added split() to the change handler, and also:
- Filtered and trimmed input on form submit to avoid API errors
for trailing commas and whitespace
- Updated schema so that a better error message would be displayed
in the future
- Added placeholder and helper text to make it clear what the "Domain
transfers" field was intended to do and what input it expects.
- Fixed a bunch of e2e tests
2. `yarn …
=> M3-2774 Fix: Domain SPA edit error

e2e/config/wdio.conf.js
Gives accurate reporting of overall test suite failures. The current setting will indicate how many suites have failing tests. The main problem with the way it's set currently is that the test reporter does not mark the tests following a failure as skipped. So if a test suite has a failure, that test is reported as failing and all the following skipped tests are missing from the report.
Please describe the tests that you ran …
=> E2E Tests - Continue on spec failure

src/store/linodes/config/config.requests.ts, src/store/linodes/disk/disk.requests.ts
In `getAllLinodeDisks` and `getAllLinodeConfigs`, we were throwing a new error inside the catch block, which was unhandled. This resulted in a Sentry error and a console error, though thankfully the app wasn't crashing.
Block request to `/disks`  and to `/configs` and go to Linode summary. This shouldn't result in any console errors, and no error should be reported to Sentry.
=> Fix uncaught error in disks and configs requests

e2e/specs/profile/clients.spec.js, src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx
Adds app name to both the delete and reset secret modal for OAuth Apps
3. `yarn e2e --spec=e2e/specs/profile/clients.spec.js --browser=headlessChrome`
=> Change: Include App Name in Reset and Delete OAuth App Modal

src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
Previously there was an issue where if you
1. Navigated to stackscripts landing
2. Scrolled down to request a few pages of stackscripts
3. Sorted the table
The sort would start requesting StackScripts at the page you left off at, rather than resetting back to page 1.
N/A
=> Fix: StackScripts Sorting Logic

src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
The `compose(lensPath)` logic was causing some incorrect behavior. Because they were not correctly typed, when we switched over to returning `Linode.ApiFieldError[]` for all `.catch`es, they were looking at the wrong property keys.
This also addresses recent Sentry errors
N/A
=> Fix: Error Handling re: Linode Settings Panels

src/App.tsx, src/components/Notice/Notice.spec.js, src/components/Notice/Notice.stories.tsx, src/components/Notice/Notice.tsx, src/components/VATBanner/VATBanner.test.tsx, src/components/VATBanner/VATBanner.tsx, src/components/VATBanner/index.tsx, src/constants.ts, src/containers/account.container.ts, src/utilities/mockLocalStorage.ts, src/utilities/storage.ts
Show banner for EU users
- Conditionally render banner
- Add list of EU country codes to src/constants
- Add logic to display banner (if country is in the EU and no tax_id)
- Adjust banner padding
- Make Notices dismissible
- Add VAT notification to localStorage
- Add tests
Toggle your country (in or out of the EU) and tax_id (defined or undefined).
NOTE: The Billing info panel is using an old Context rather than Redux, and toggling your account settings here won't update the banner until you reload the page. I'm going to start working on that change in a follow-up PR, and we can decide whether or not to wait for that change before releasing this.
=> M3-2829 VAT banner

src/components/EnhancedSelect/Select.tsx, src/containers/withNodeBalancers.container.ts, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainDrawer.tsx, src/features/Domains/DomainsLanding.tsx, src/features/Images/ImagesDrawer.tsx, src/features/NodeBalancers/NodeBalancerSelect.tsx, src/features/Volumes/VolumeAttachmentDrawer.tsx, src/features/linodes/LinodeSelect/LinodeSelect.tsx
Adds the ability to automatically create domain records from either Linode or NodeBalancer IP addresses while creating a master domain
Fixes #4941 
3. `yarn e2e --spec=e2e/specs/domains/smoke-list-domains.spec.js --browser=headlessChrome`
Please test by both request blocking both requests to `/domains` and `domains/${id}/records`
Also please attempt to request only some network requests to `domains/${id}/records` but not all.
=> Add: Option to Automatically Create Domain Records

.gitignore, src/features/Profile/OAuthClients/Modals.tsx, src/features/Profile/OAuthClients/OAuthClientActionMenu.tsx, src/features/Profile/OAuthClients/OAuthClients.tsx, src/features/Profile/OAuthClients/OAuthFormDrawer.tsx, src/services/account/oauth.ts
Adds loading and error state for both the OAuth Dialogs and Drawer
Sorry I went a bit overboard with the refactoring. This code was ugly. 2 Dialogs were being rendered for every table row 😢 
N/A
=> Fix: Error and Loading States for OAuth View

src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx
=> M3-2831 Change data transfer pool circle to be a progress bar

src/components/TableCell/TableCell.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
Adjustments for the Linode list layout on tablet size. Entity title width was off and the details labels were getting scrunched up. 
=> M3-2799 Fix Linode list layout tablet size layout

.gitignore, src/__data__/disks.ts, src/components/CheckBox/CheckBox.tsx, src/components/Notice/Notice.stories.tsx, src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx, src/services/linodes/linodeActions.ts
Adds the ability to toggle choice to automatically resize disks after the Linode resize is finished.
N/A
As per @rmcintosh, the conditions for showing this toggle should be
1. If the user has 1 ext disk (and nothing else)
2. If the user has 1 ext disk and 1 swap disk (and nothing else)
=> Add: Ability to Optionally Resize Disks after Linode Resize

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Our recent upswing in test failures is because we forgot to update data-qa attributes, which are wonky with React-Select. This fixes the NB section.
3. ` yarn e2e --dir nodebalancers`
=> Fix NodeBalancer e2e tests

src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesPanel.tsx, src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesRow.tsx, src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, src/features/Billing/InvoiceDetail/InvoiceTable.tsx, src/features/Billing/PdfGenerator/PdfGenerator.ts
1. Requests all line items when the Invoice Detail Screen mounts
2. Uses `<Paginate />` to show all Invoice Line Items on the Invoice Detail Screen
3. Requests all line items when clicking "Download PDF" on the expansion panel
4. Adds loading state to downloading PDF button
N/A
=> Fix: Show all Line Items on Invoice PDF and Detail Screen

src/components/EnhancedSelect/Select.tsx, src/components/PaginationFooter/PaginationFooter.tsx, src/features/Billing/InvoiceDetail/InvoiceTable.tsx
Fixes issue with the page size select in the invoice detail not functioning correctly
N/A
Same deal as before - either mock out the data with Charles to get multiple pages or login as an account with many invoices
=> Fix: Invoice Select

Dockerfile
The patches were not being installed in the Docker container. This resolves that issue.
This also removes an extraneous call to install Yarn, since Yarn is already installed by default in `node` docker images.
=> fix: add patches and remove extraneous yarn install

src/features/Profile/OAuthClients/OAuthClients.tsx, src/services/account/oauth.ts
Fixes issue where OAuth Client Secret Modal was not appearing after creating a new Client
3. `yarn e2e --spec=e2e/specs/profile/clients.spec.js --browser=headlessChrome`
Try creating an OAuth Client and then see the modal pop up after the drawer closes.
=> Fix: OAuth Secret Modal

e2e/pageobjects/account/user-detail.page.js, e2e/specs/account/user-detail-spec.js
* Fixes user detail tests. The cancel button was removed from the page breaking a bunch of the tests that rely on it being there to reset the state.
* Removed a test that didn't really add much value.
- Test fix
3. `yarn e2e --file e2e/specs/account/user-detail-spec.js --browser=headlessChrome`x
=> Fix: fix user detail e2e tests

src/components/Button/Button.tsx, src/components/DateTimeDisplay/DateTimeDisplay.tsx, src/components/StackScript/StackScript.test.tsx, src/components/StackScript/StackScript.tsx, src/components/Table/Table.tsx, src/components/TableCell/TableCell.tsx, src/features/Footer/Footer.tsx, src/features/StackScripts/Partials/StackScriptTableHead.tsx, src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx, src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts, src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx, src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx, src/features/StackScripts/StackScriptRowHelpers.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
The StackScripts landing page was in great need of work - the work was help up waiting for pagination. Since it is not happening anytime soon we still need to update the styles and give users a better experience.
The stackScripts table on the create workflow was also updated and since we have a button there for details I removed some of the table cells so that's it's easier to read and provides a better experience.
**To be tested on various breakpoints and browsers.**
=> M3-2797 Refactor/Improve StackScripts Table styles and mobile handling

src/containers/withNodeBalancers.container.ts, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx, src/store/nodeBalancer/nodeBalancer.actions.ts, src/store/nodeBalancer/nodeBalancer.reducer.ts, src/store/nodeBalancer/nodeBalancer.requests.ts
Adds the CRUD error shape to NodeBalancers in redux.
```js
error: {
create?: Linode.ApiFieldError[];
update?: Linode.ApiFieldError[];
read?: Linode.ApiFieldError[];
delete?: Linode.ApiFieldError[];
}
```
N/A
=> Change: Adds CRUD error shape to NodeBalancers

src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/store/linodes/config/config.actions.ts, src/store/linodes/config/config.reducer.ts
Adds the CRUD error shape to Linode Configs in redux.
```js
error: {
create?: Linode.ApiFieldError[];
update?: Linode.ApiFieldError[];
read?: Linode.ApiFieldError[];
delete?: Linode.ApiFieldError[];
}
```
N/A
=> Change: Adds CRUD error shape to Linode Configs

src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx, src/features/linodes/LinodesDetail/maybeRenderError.tsx, src/store/linodes/disk/disk.actions.ts, src/store/linodes/disk/disk.reducer.ts
Adds the CRUD error shape to Linode Disks in redux.
```js
error: {
create?: Linode.ApiFieldError[];
update?: Linode.ApiFieldError[];
read?: Linode.ApiFieldError[];
delete?: Linode.ApiFieldError[];
}
```
N/A
=> Change: Adds CRUD error shape to Linode Disks

src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
=> Change: Use Name of Datacenter in Outage Notifications

generate_changelog.py
Previously, we were iterating over the list of commit messages and popping them from the array if they matched a blacklist set of keywords.
This was problematic because popping meant that it would skip over the next commit message from the list because what would have been index 5 now becomes index 4, for instance
N/A
=> Fix Generate Changelog Script

e2e/pageobjects/list-linodes.js, e2e/specs/linodes/smoke-linodes.spec.js, src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/constants.ts, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, src/features/linodes/LinodesLanding/LinodeCard.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, src/types/LinodeType.ts
Adds a "Clone" option in the kebab menu on the Linodes Landing page. This option takes you to the Create Linode flow with the appropriate options pre-selected.
This was pretty straightforward since the Create Linode flow accepts (some) query params. I just had to add support for `regionID` and `typeID` query params.
The one wrinkle in this was getting the correct Continent and Plan Type tabs pre-selected. I added some logic in `SelectRegionPanel` and `SelectPlanPanel` to set the correct `initTab` if appropriate.
3. `yarn e2e e2e/specs/linodes/smoke-linodes.spec.js --browser=headlessChrome`
Create several Linodes with different regions …
=> M3-2762 add: Clone Linode from Linode Action Menu

e2e/specs/linodes/linode-no-image.spec.js
A copy change broke the test.
3. `yarn e2e --spec=e2e/specs/linodes/linode-no-image.spec.js --browser=headlessChrome`
=> e2e: fix linode-no-image test

e2e/pageobjects/linode-detail/linode-detail-networking.page.js, e2e/specs/linodes/detail/ip-transfer.spec.js, e2e/specs/linodes/detail/networking-ip-sharing.spec.js, src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
Fixes IP sharing and transfer tests
3. `yarn e2e --spec=e2e/specs/linodes/detail/networking-ip-sharing.spec.js,e2e/specs/linodes/detail/ip-transfer.spec.js --browser=headlessChrome`
=> Test: Fix IP Sharing and Transfer Tests

src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Previously there was an issue where if you
1. Queue up a nodebalancer with 3 configs to be created
2. Remove config 2
3 Observe - deleted config 2 values are now applied to the last config
N/A
Found this bug on a personal project and just so happened that the bug existed in Cloud as well - go figure:
https://github.com/martinmckenna/cocktails-app/commit/5e91ef5f469f2e3650402c71c02dd7ed19860026
=> Fix: NodeBalancer Config Default Values

e2e/config/wdio.conf.js, e2e/config/wdio.storybook.conf.js, e2e/utils/config-utils.js, e2e/utils/fs-cred-store.js
All this logging when running the e2e tests was unnecessary noise. I removed it and also made a change to override the `onPrepare` method in the `storybook.conf.js`. No creds need to be checked out to run the storybook tests, so this overrides the base onPrepare method delcared in `wdio.conf.js`.
- Tests fix
1. `yarn && yarn storybook`
3. `yarn storybook:e2e`
=> Test Fixes: Override onPrepare in Storybook config, remove extraneous logging

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
It was taken out during a hotfix, #4996. This adds it back in, and renders it only if Kubernetes is enabled.
Try running the app with Kubernetes enabled and with it disabled.
=> M3-2883: Re-add "Kubernetes" button to Create menu

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Changes default text value to use the literal `memory_limit` from the APIv4's `/instances/:id/config/:id` response
=> Fix LinodeConfig default memory_limit value

e2e/pageobjects/configure-linode.js, e2e/pageobjects/list-stackscripts.page.js, e2e/specs/create/create-linode-from-stackscript.spec.js
I narrowed the scope of the create linode from stackscript tests quite a bit. They were running through a lot more tests and setup steps than described (they created custom stackscripts before each test and removed them after each test, as opposed to using a known community stackscript and attempting to deploy with that).
Ultimately, the tests are a bit more specific, but don't rely on creating a stackscript several times over the course of the test in order to run.
- Test fix
3. `yarn e2e --file …
=> Fix: create from stackscript tests

src/App.test.tsx, src/App.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsMenu.tsx, src/store/linodes/linodes.actions.ts, src/store/linodes/linodes.helpers.test.ts, src/store/linodes/linodes.helpers.ts, src/store/linodes/linodes.reducer.ts, src/store/notification/notification.reducer.ts, src/types/index.ts
Adds all the Redux nonsense to get maintenance notifications attached to the relevant Linodes
N/A
Flow goes like this:
1. App loads
2. Request Linodes and Notifications
3. Call Redux action to append each `maintenance` notification to the Linode 
4. Redux store is updated and some linodes will have a `maintenance` key on it's schema
Here's some mock data to play around with from GET `/notifications`. Be sure to replace the Linode IDs appropriately
```js
{
"results": 5,
"page": 1,
"data": [
{
"until": null,
"entity": {
"url": "/linode/instances/500",
"id": 500,
"type": "linode",
"label": "loadbal1-vagrant"
},
"when": null,
"body": null,
"severity": "major",
"type": "migration_scheduled",
"label": "You have a scheduled migration pending!", …
```
=> Linode Maintenance Part 1

e2e/specs/profile/clients.spec.js
Fixes a flaky oauth clients test. There was an issue where it would get the text of the modal too quickly and it wouldn't contain the secret confirmation msg.
- Test Fix
3. `yarn e2e --file=e2e/specs/profile/clients.spec.js --browser=headlessChrome`
=> Fix: flaky oauth clients test

src/features/Domains/DomainDrawer.tsx
Adding tags while cloning a Domain is not supported by the API, but we were displaying the TagsInput component in the Domain Drawer while in Clone mode. This PR removes it.
It also disables the Master/Slave radio buttons while in Cloning mode, since these buttons don't do anything (i.e. when cloning a Master domain, the new domain is also a Master).
N/A
Create a few Domains (both master and slaves) and try cloning them. Verify functionality of the Domain Drawer in general.
=> M3-2847 change: Remove TagsInput when cloning a Domain

src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
The SelectPlanPanel only displayed a tab if there were any instances
of that plan type (so if no Nanodes are passed to the component,
the Nanodes tab is hidden). However, the "what tab should I default to"
logic didn't consider this case, so the selected tab would default to
an incorrect value. Dynamically calculated the tabOrder list to account
for this.
This was causing weirdness on the Kube cluster create flow, but please also test other instances of this component (cloning a Linode, creating, etc.)
=> Update SelectPlanPanel to allow different tab sets

src/layouts/Logout.tsx
Because the prefix for the `Authorization` header is included in the token in local storage, POST to login's `/oauth/revoke` endpoint with the full token payload was not actually revoking anything. This should fix that.
If you are running this on an environment where you can fiddle with local storage, try transplanting a token used in one manager session into another manager session after logging out and see if the old token still works. Alternatively, strip out the `Bearer` prefix and try to use the token directly against the API.
=> bug: Updated logout to split token before revoking it

e2e/pageobjects/profile/lish.page.js, e2e/specs/profile/lish.spec.js, src/features/Profile/LishSettings/LishSettings.tsx
* Updated select to include `data-qa` attributes.
- Test Fix
3. `yarn e2e --file e2e/specs/profile/lish.spec.js --browser=headlessChrome`
=> Fix: Lish E2E tests

src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Previously we were requesting only the first page of the selected entity type in the Support Ticket drawer. This means if you had more than 100 Linodes, for example, you'd only be able to select one of the first 100.
I also added a loading spinner to the entity Select component.
**Note:** This component should probably be refactored in order to get data, errors, loading, etc. from Redux. I started down that path, but turned out to be a healthy-sized refactor, especially since this is an old component that uses a lot of old patterns. This at least fixes the bug, and I've opened a ticket to do the refactoring (M3-2902).
None.
Use an account with a lot of stuff, and open the Support Ticket Drawer. All of your entities should be there.
=> M3-2890 fix: Request all entities in the Support Ticket Drawer

src/containers/kubernetes.container.ts, src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx, src/store/index.ts, src/store/kubernetes/kubernetes.actions.ts, src/store/kubernetes/kubernetes.reducer.ts, src/store/kubernetes/kubernetes.requests.ts
Decided to go with Redux/getAll pattern, so that K8s clusters are eventually searchable app-wide.
Still have to run locally (I hear alpha support is coming soon!), functionality should be the same.
=> Add redux boilerplate for K8s clusters

src/features/Volumes/DestructiveVolumeDialog.tsx, src/features/Volumes/VolumesLanding.tsx
We weren't handling errors when deleting or detaching a Volume. They were 10-month old @todos that we forgot about.
Block /volumes then try deleting and detaching.
=> M3-2087 Fix: Add error handling for delete/detach Volume confirmation modals

src/__data__/domains.ts, src/features/Domains/DomainDrawer.tsx, src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/DomainRecords.tsx, src/features/Domains/domainUtils.test.ts, src/features/Domains/domainUtils.ts
API currently allows you to add records with a duplicate hostname
(e.g. a TXT record for "www" when there's already a "www" entry in
CNAME). Added uniqueness checking to fix this.
Also added validation to prevent email addresses in the target domain, e.g. using john@example.com when creating the domain example.com. CF doesn't check for this, and it doesn't seem to break anything, but it's a bad idea (if your domain goes down you can't be contacted by email about it) and Support asked for this fix.
1. Create a CNAME record in one of your domains (e.g. 'mail'), the alias doesn't matter.
2. Create a TXT (or any other record) with the same hostname ('mail'). You should observe an error.
3. Any other records should be fine (an A and TXT/whatever record can …
=> M3-2771 Fix: domains validation

src/App.tsx, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/CloneLanding/Configs.tsx, src/features/linodes/CloneLanding/Disks.tsx, src/features/linodes/CloneLanding/index.ts, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx
Cloning of Linode configs and disks. See the ticket for designs.
I'm planning on getting this feature merged this in 4 parts:
**1) Routing** _(this PR)_
2) Components/internal state (bulk of the code changes)
3) Functionality (API requests, error, loading states)
4) Unit tests
To test, go to Linode Details -> Advanced. Click the action menu of a Config or Disk, and you'll be taken to the new Clone page.
=> M3-2247 Clone Configs/Disks: Part 1 (Routing)

src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx
Volumes and NodeBalancer cards were requesting manually on load, with special events-based logic to keep the list up to date. We have Redux to do all this now, so this is redundant and inefficient.
- Linodes are handled in a separate PR, domains are already Reduxed.
- Note that NBs are actually slower this way, since all the configs/nodes/etc. are fetched on app load. Follow-up POC, if accepted, can be adapted to quicken this up.
=> Change: Source Dashboard cards from Redux

src/features/Profile/AuthenticationSettings/TwoFactor/EnableTwoFactorForm.tsx
The two factor URI had an issuer prefix before the account name, but it is recommended to have the issuer in the optional parameters as well. [link](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer)
fix: Issuer parameter was missing from TFA URI.
M3-2893 #done
=> fix: Added issuer to TFA URI

src/App.tsx, src/assets/timezones/timezones.ts, src/components/MaintenanceBanner/MaintenanceBanner.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/features/linodes/LinodesLanding/utils.test.ts, src/features/linodes/LinodesLanding/utils.ts
Adds Linode Maintenance window start time to the CSV. Totally forgot to add this feature.
N/A
Also does the following:
1.  Removes timezone from banner (with the exception of the Linode Detail page)
2. Fixes Troll timezone.
3. Converts the start window to observe user timezone at the time the notification is attached to the Linode object.
=> Add: Maintenance Window to CSV

src/components/TextField.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Adds a radio toggle to the memory limit field in the config drawer, so it's more clear to the user what they are doing.
N/A --- I think....I couldn't find any tests for this at least.
=> Add: Radio Toggle For Config Memory Limit

src/features/Profile/LishSettings/LishSettings.tsx
When updating profile from LISH settings, we were ignoring `authorized_keys` if `lish_auth_mode` was "disabled". This meant that a user could not remove keys while LISH was disabled. This was unnecessary, though. From the API docs: 
> `authorized_keys`: The list of SSH Keys authorized to use Lish for your User. This value is ignored if `lish_auth_method` is "disabled."
Navigate to `/profile/lish`. Try adding and removing pub keys. This should work regardless of "Authentication Mode".
=> M3-2772 fix: Ability to remove LISH key when it's disabled

src/components/Button/Button.tsx, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/CloneLanding/Configs.tsx, src/features/linodes/CloneLanding/Details.tsx, src/features/linodes/CloneLanding/Disks.tsx, src/features/linodes/CloneLanding/utilities.ts, src/features/linodes/LinodeSelect/LinodeSelect.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx, src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx, src/features/linodes/LinodesDetail/LinodesDetail.tsx
I apologize for the size of this PR. It got larger and more complex than I anticipated.
This PR adds the components and internal state for cloning Configs/Disks:
The mapping of configs/disks made this complex, because of a few properties:
1. A single config can have multiple disks associated with it.
2. A single disk can be associated with multiple configs.
3. When you clone a config, _all it's associated disks are cloned too._
From the UI perspective, when a config is selected, the associated disks shown as selected and disabled:
A few changes to components:
- `<Button />` added a new prop/class: `superCompact` with tighter spacing
- `<LinodeSelect />` can now take a custom `label` prop.
To test, go to Linode Details -> Advanced. Click the action menu of a Config or Disk, and you'll be …
=> M3-2247 Part 2: Components and internal state

src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/CloneLanding/Details.tsx, src/features/linodes/CloneLanding/utilities.ts, src/features/linodes/LinodeSelect/LinodeSelect.tsx, src/features/linodes/transitions.ts, src/services/linodes/linodeActions.ts, src/services/linodes/linodeDisks.ts
This PR adds the API requests necessary to make this feature work. It includes error and loading states.
**To test**, go to Linode Details -> Advanced. Click the action menu of a Config or Disk, and you'll be taken to the new Clone page. Try cloning different combinations of disks/configs to different Linodes.
1. Routing
2. Components/internal state
3. **Functionality (API requests, error, loading states)** _(this PR)_
3.5. Proactive space errors / grouped Linodes in LinodeSelect
4. Unit tests
=> M3 2247 Part 3: Functionality

src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/store/linodeCreate/linodeCreate.reducer.ts
The Redux state wasn't being set when navigating to Create Linode URL with `types` and `subTypes` as query params, which meant the appropriate API requests were not being made.
The problem was that the Redux state was being initialized by looking for lowercased strings in the query params to set the initial state. 
Please test the Create Linode flow thoroughly. Make sure the appropriate API requests are being made on specific creation types.
=> [for release] Fix Linode Clone kebab 

src/features/Domains/DomainDrawer.tsx, src/features/Domains/domainUtils.ts
Previous logic was checking `!type === 'master' && !isValidSOAEmail` when in reality in should have been `type === master && !isValidSOAEmail `
N/A
=> Fix: Conditional Logic When Validating SOA Record for Slave Domains

src/__data__/linodes.ts, src/components/EnhancedSelect/Select.tsx, src/features/linodes/CloneLanding/Details.tsx, src/features/linodes/LinodeSelect/LinodeSelect.test.ts, src/features/linodes/LinodeSelect/LinodeSelect.tsx
This PR adds a new optional prop to `<LinodeSelect />` called `groupByRegion`.
The only place this is implemented is in the new clone disk/config feature.
=> M3-2247 LinodeSelect group by region

src/components/CircleProgress/CircleProgress.tsx, src/components/PrimaryNav/SpacingToggle.tsx
Removes reliance on local storage in favor of the theme spacing unit for the toggle
N/A
=> Fix: Rely on Theme Spacing Unit for Theme Toggle

src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
Fixes react router warnings on Linode Detail by correctly code-splitting the routes.
N/A
=> Fix: React Router Warnings on Linode Detail

src/components/SupportLink/SupportLink.tsx, src/components/SupportLink/index.tsx, src/components/TabbedPanel/TabbedPanel.tsx, src/features/Support/SupportTickets/SupportTicketDrawer.tsx, src/features/Support/SupportTickets/SupportTicketsLanding.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx
Review feedback, we were asked to make the "open a ticket" error message when requesting a GPU link to a support ticket with the summary filled out.
Added a `<SupportLink>` component to make this easier in the future, as it's likely to be a common request.
To test the support link, set line 245 of SelectPlanPanel to `true`. It's hard to test the conditional logic until GPUs are closer to release, but the fallback is just displaying the original error message without a link, which is the current behavior.
=> M3-2926 Change: Add link to support ticket in SelectTabPanel

src/themeFactory.ts, src/themes.ts
=> M3-2932 fix subtitle typography color regression

src/components/Notice/Notice.tsx, src/features/TopMenu/UserNotificationsMenu/UserNotificationsList.tsx
Small styling updates to make the border thicker for the important warnings and make the icon black for the warning notice (white icon present contrast issues)
Additionally, I fixed regressions with the maintenance messages severity in the notification menu as well as the message itself that got overridden by a rebase
=> M3-2936 update notice styles and maintenance messages regressions

src/features/Domains/DomainDrawer.tsx
Previously, we were attempting to create default domain records on slave domains, even though that functionality doesn't exist.
N/A
big ups to Sentry for this one.
=> Fix: Prevent Default Domain Records from Being Created on Slave Domains

src/__data__/ipResponse.ts, src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.test.ts, src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, src/types/Linode.ts
This PR includes 2 changes:
1. A customer reported seeing a shared IP listed multiple times in the IPv4 table in LinodesDetail/networking. Marty and I were unable to reproduce this, but I added a `uniq` to the address lists as a safety check, which shouldn't hurt anything.
2. We were manually filtering private IPs out of the list of available choices, which the API doesn't seem to care about. Removed that filter.
=> M3-2837 Fix: IP sharing 

src/store/linodes/linode.requests.ts
After a Linode was deleted, if it had long-running events on it,
our linode.events.ts logic was requesting the (nonexistent)
Linode after every event, and these errors were uncaught and therefore
being reported to Sentry.
Fixed this in two ways:
- Added a catch block to the requestLinodeForStore method, which
drops the error
- Added a check in the requestLinodeForStore thunk, so that the API
is only hit for a Linode that exists in our store. Since requestLinodeForStore
is only called for existing Linodes, this shouldn't cause any issues; however,
fix #1 above is enough to resolve this issue, so it might be safer to remove this.
=> M3-2899 Fix: Catch deleted events errors

src/exceptionReporting.ts
Adds account meta data to all unhandled browser errors
do `throw new Error('something')` somewhere (but make sure the account data has loaded)
=> Add Sentry Meta Data to All Browser Errors

src/components/Notice/Notice.tsx
Making the font size of notices consistent(16px/1rem) for both theme spacing modes.
=> M3-2941 Font size of <Notice /> in compact mode

src/features/ObjectStorage/Buckets/BucketLanding.test.tsx, src/features/ObjectStorage/Buckets/BucketLanding.tsx, src/features/ObjectStorage/Buckets/ClusterSelect.tsx, src/features/ObjectStorage/Buckets/ListBuckets.test.tsx, src/features/ObjectStorage/Buckets/ListBuckets.tsx
This PR fixes two console errors from React:
1) State error when typing in Label field (CreateBucketForm).
2) State error when deleting your last bucket.
The **first** was an easy fix – just needed to wrap the initial form setting in `React.useEffect()` in `<ClusterSelect />`.
The **second** required restructuring BucketsLanding and ListBuckets. Previously, the structure was:
```
-- BucketsLanding
| -- ListBuckets (handles bucket deletion)
| -- ConfirmationModal
```
This sometimes caused an issue when deleting your last bucket. Now the structure is:
```
-- BucketsLanding (handles bucket deletion)
| -- ListBuckets 
| -- ConfirmationModal
```
It should have been this way to begin with – my bad.
**Note** that there's not much _new_ code ... I just moved several chunks from `ListBuckets.tsx` …
=> OBJ fix console errors

src/features/TopMenu/UserMenu/UserMenu.tsx
Added `handleClose` to profile menu links so they will close during navigation.
- Bug fix ('bug')
=> M3-2942 Profile Menu doesn't auto close when clicking item from it

GETTING_STARTED.md, src/constants.ts, src/perfMetrics.ts
Previously, performance metrics were always logged in the console when running the dev server. I found this to be noisy. Now you need to explicitly set `REACT_APP_LOG_PERFORMANCE_METRICS='true'` in order to see logging of performance metrics in the console.
Also, I removed the browser/OS tracking from the reporting, as it apparently caused errors for some users.
=> M3: Reduce perfume.js noise

src/services/objectStorage/buckets.schema.ts
We now know that the max length for a bucket label is 63. This PR updates the schema.
=> OBJ: Update max length for Bucket label 

src/features/ObjectStorage/ObjectStorageLanding.tsx
This fixes a console error.
This wasn't an issue originally, but when I moved these requests from `App.tsx` to `ObjectStorageLanding.tsx` in [this PR](https://github.com/linode/manager/pull/4916/files#diff-46ef2374da6211486f3a408db68b2bcbL228) , we lost the `catch()` handling that happens there.  (See: [App.tsx](https://github.com/linode/manager/blob/develop/src/App.tsx#L270)).
Note that from the user's POV, nothing changes, since the error handling is done by Redux.
1. Request block `*bucket*` and `*cluster*` 
2. Visit OBJ
3. **Observe:** no uncaught errors in the console.
=> Add catch() for OBJ requests

src/features/Support/SupportTickets/SupportTicketsLanding.tsx
http://localhost:3000/support/tickets?type=closed&drawerOpen=true should do what it looks like it should do
=> [For release] Allow external links to open support ticket drawer

src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx, src/features/Support/SupportTickets/TicketRow.tsx, src/types/index.ts, src/utilities/getEventsActionLink.ts
Update both entity links on SupportTicketDetail and TicketRow to use the same logic:
- If there is no entity assoc with the ticket, don't render an entity label/icon.
- If the entity does not exist in the store, display the label/icon as text.
- If the entity exists, display it as a link to the detail or landing page as
appropriate.
This logic prevents displaying links to deleted entities, which result in 404s.
Note: If a user navigates directly to one of these pages, due to the length of the initial
load it's possible that the getState() method used to check if the entity still exists
will return an empty state, in which case a valid entity won't be shown as a link.
=> M3-2904 Change: Make entity links in Support tickets clickable

src/components/EnhancedSelect/Select.tsx, src/components/TextField.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedMultiSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedSelect.tsx, src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx, src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx, src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesCreate/types.ts
Previously, there was an issue where:
1. Navigate to Create OCA flow
2. Select MERN
3. Then Select LAMP
4. Observe - the UDF for `dbpass` was unchanged, even though one is supposed to be Mongo while the other MySQL
This also uncovered a more apparent issue. We're not clearing form values when a user switches between Apps/StackScripts that have the same UDF label.
So for example
1. Create 2 SSs that have the same UDFs
2. Select 1st SS
3. Fill out all UDFs
4. Switch to second StackScript
5. Observe - form fields are still filled out, despite the parent state being cleared.
N/A
1. Create 2 StackScripts with the script below
2. go to creation flow and select first stackscript
3. Fill out UDFs
4. select second stackscript
5. Try to submit form
6. You _should_ …
=> Fix: UDFs not Resetting on App/StackScript Change

e2e/specs/create/smoke-linode-with-tags.spec.js
* Tags are no longer displayed on the list view of /linodes , removes a test for this.
- Test fix
3. `yarn e2e --file e2e/specs/create/smoke-linode-with-tags.spec.js --browser headlessChrome`
=> Fix - Remove List Linodes tags test

src/components/EnhancedSelect/Select.tsx
Fixes issue where default value was not populated if one wasn't explicitly provided
Timezone Form was an offender of this. Please check many selects app-wide.
=> Fix: Default Value for Selects

src/features/linodes/LinodesLanding/LinodeCard.tsx
It's possible for IPv6 to be disabled on your Linode, which resulted in the app crashing in in LinodesLanding grid view, since we were rendering an IPAddress component with `null`.
Prod test account 9 has a Linode with IPv6 disabled.
=> fix: Linodes Landing bombing the app when no IPv6

src/components/Notice/Notice.tsx
Uses fixed line height on Notice component because compact mode text was very squished.
=> Fix: Line Height on Notices

src/App.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/constants.ts, src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/types/Account.ts, src/utilities/accountCapabilities.ts
Use the pattern @johnwcallahan did with OBJ to read account.capabilities. Kubernetes routes will be active if:
- .env has been set (REACT_APP_KUBERNETES_ENABLED) OR
- 'Kubernetes' is part of the list returned by account.capabilities.
Try all combinations (deleting from your .env, blocking /account on Charles (from dev services) and deleting 'Kubernetes' from the capabilities list.
=> LKE Use capability for LKE show/hide

src/components/GPUError.tsx, src/features/OneClickApps/FakeSpec.ts, src/features/linodes/LinodesCreate/LinodeCreate.tsx, src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/utilities/interceptGPUError.tsx, src/utilities/request.ts
The GPU "you need to open a support ticket" error was not GPU- or type-specific, so it was not being replaced as intended. Moved the intercepting logic to the Axios interceptor, where we're doing a simple check based on the error text and whether or not "type" contains "gpu".
Also fixed another (old) bug where general errors were displaying twice on the My Images creation tab.
To test:
Use prod-test-004 (or set your account's reputation to ~10) and try to create a GPU. Anywhere that types can be selected this error can occur (for LinodeResize it shows up in a toast), so please test them all.
=> Do GPU error handling in the Axios interceptor

src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
Update the TextFields to use recently added `min` and `max` logic. I'm not crazy about the UX here, but talked to @asauber about this, and one way or the other we should prevent node_counts of 0, as well as negative ones.
This PR also fixes a glitch where the success/error state would persist if re-entering the editing state by adding a new node pool.
Maybe it would be better to have default values for min and max props; something like `if typeof min === 'number' && !typeof max === number then max = Infinity`. What do you think @martinmckenna?
=> LKE Fix: negative number inputs

src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Title says it all.
We already show the "this is too small, resize your disks or delete some" message from Classic when submitting the form with a smaller disk. I just added helper text to the form to let users know why the option is disabled. We could think about disabling these plans in advance of form submit, but that would require additional calculation (which I think we're currently leaving to the API).
=> M3-2900 Fix: Disable auto-resize option when moving to a smaller plan

src/App.tsx, src/features/Dashboard/Dashboard.tsx, src/features/Profile/AuthenticationSettings/AuthenticationSettings.test.tsx, src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx, src/features/Profile/AuthenticationSettings/SecuritySettings.test.tsx, src/features/Profile/AuthenticationSettings/SecuritySettings.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/features/Profile/DisplaySettings/DisplaySettings.test.tsx, src/features/Profile/DisplaySettings/DisplaySettings.tsx, src/features/Profile/DisplaySettings/EmailChangeForm.tsx, src/features/Profile/DisplaySettings/TimezoneForm.tsx, src/features/Profile/LishSettings/LishSettings.tsx, src/features/Profile/Settings/Settings.tsx, src/features/Users/UserDetail.tsx, src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx, src/features/linodes/LinodesLanding/LinodesLanding.tsx, src/services/profile/profile.ts, src/store/profile/profile.actions.ts, src/store/profile/profile.reducer.ts, src/store/profile/profile.requests.ts, src/store/types.ts
This does not implement any actual PUTing to `/profile/preferences`
This PR accomplishes one goal: Change `updateProfile` in Redux from being a synchronous action to an asynchronous one.
So what was done
1. Created `start`, `done`, and `failed` actions on `updateProfile` along with loading, error, and data states.
2. Components now subscribe to `read` state on the `error` object
3. Adds `preferences` as a new key-value pair on the `profile.data` object
4. Adds conditional logic to the `updateProfile` action creator to maybeUpdateUserPreferences if the user preferences are included in the PUT payload.
What still needs work
1. User grants are a key-value pair on the `profile.data` object, so we need to make sure when we PUT `/profile`, grants get updated as well if they exist in the PUT …
=> User Preferences Part 1

src/exceptionReporting.ts
Based on the massive influx of errors over the weekend, more Sentry errors were added to the blacklist.
Try logging `e.touches is undefined` to Sentry and watch it _not_ appear.
N/A
=> Change: Blacklist more Sentry Errors

src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx, src/features/Profile/AuthenticationSettings/SecuritySettings.tsx, src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, src/features/Profile/DisplaySettings/DisplaySettings.tsx, src/features/Profile/DisplaySettings/EmailChangeForm.tsx, src/features/Profile/DisplaySettings/TimezoneForm.tsx, src/features/Profile/LishSettings/LishSettings.tsx, src/features/Profile/Settings/Settings.tsx, src/store/preferences/preferences.actions.ts, src/store/preferences/preferences.reducer.ts, src/store/preferences/preferences.requests.ts, src/store/profile/profile.actions.ts, src/store/profile/profile.reducer.ts, src/store/profile/profile.requests.ts
Decouples preferences state from profile state in Redux.
This was a super bad idea and shame on me.
N/A
=> Users Preferences Part 2: Decouple Profile and Prefs

src/components/SelectRegionPanel/SelectRegionPanel.tsx, src/constants.ts
This is a small enhancement. 
Consider a situation where you want to create a new Linode by cloning an existing one. In the Create flow, when you select a Linode, its region is automatically selected, but the tab it falls under _isn't._
The solution I went with is adding a `key` prop, equal to the value of the initialTab. This is a handy React pattern I learned about here: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key
None.
**To test:**
1. Have multiple Linodes in multiple regions. 
2. "Create Linode" -> "My Images" -> "Clone Linode".
3. Select a Linode.
4. **Observe:** The tab containing the selected region is selected.
=> M3-2852: LinodeCreate selected region tab state

src/features/Billing/PdfGenerator/PdfGenerator.ts
Long company names were overflowing. This PR fixes that by using jsPDF's `.splitTextToSize()` method to simulate overflow-wrap.
Try out several company names with varying lengths. Print an invoice and observe the top right header.
=> M3-2910: Invoice – overflow of company name 

src/App.test.tsx, src/App.tsx, src/LinodeThemeWrapper.tsx, src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx, src/components/PaginationControls/PaginationControls.test.tsx, src/components/PreferenceToggle/PreferenceToggle.tsx, src/components/PreferenceToggle/index.ts, src/components/PrimaryNav/ThemeToggle.test.tsx, src/containers/preferences.container.ts, src/containers/profile.container.ts, src/features/Dashboard/Dashboard.test.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx, src/features/Profile/DisplaySettings/EmailChangeForm.test.tsx, src/features/TopMenu/AddNewMenu/AddNewMenuItem.test.tsx, src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx, src/features/linodes/LinodesLanding/LinodeCard.test.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, src/features/linodes/LinodesLanding/OverflowIPs.test.tsx, src/index.tsx, src/store/index.ts, src/store/preferences/preferences.reducer.ts, src/store/preferences/preferences.requests.ts, src/store/profile/profile.reducer.ts, src/store/profile/profile.requests.ts, src/themeFactory.ts, src/themes.ts, src/utilities/storage.ts, src/utilities/storybookDecorators.tsx, src/utilities/testHelpers.tsx
Observe user preferences when selecting and toggling theme and spacing.
Next PR: Add Analytics back and document usage of TogglePreference component
N/A
Some things to note in this PR are
1. Toggling a preference is debounced and will not make any API calls if you keep toggling the preference very quickly
2. `TogglePreference` handles all state internally, but you can override that and handle state externally if needed.
3. `TogglePreference` render blocks by default, unless a `value` prop is passed, and you want to handle state externally.
4. `toggleCallbackFn` does not care if the API PUT requests succeed or fail. It's run immediately after the preference is toggled.
=> User Preferences Part 3: Theme and Spacing

src/LinodeThemeWrapper.tsx, src/components/PreferenceToggle/PreferenceToggle.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/index.tsx, src/utilities/ga.ts
Re-adds GA tracking for theme and spacing.
Regression: Since we're using a render props component, we cannot successfully send both the theme and spacing choices in one event anymore, since each has its own handlers for when a preference is initially set.
N/A
=> User Preferences Part 4: Re-Add Google Analytics

src/features/Domains/DomainDrawer.tsx
If a Linode does not have IPv6 enabled, do not attempt to create default DNS records for it 
N/A
=> Change: Do Not Create DNS Records for nulled IPv6 Linodes

src/features/StackScripts/StackScriptDrawer.tsx
This was happening because the StackScriptDrawer Redux state was not cleaned up on unmount.
**To test:**
1. Create -> Linode -> One-click -> Community StackScripts.
2. Click “Show Details” on a StackScript.
3. **Observe:** the drawer opens.
4. Click the browser’s “Back” button”.
5. Click “Community StackScripts”. 
6. **Observe:** the drawer is NOT open
=> M3-2836 fix: StackScript Drawer state bug

src/features/Account/AutoBackups.tsx
This was caught in Sprint Review. We should display the "Enabled" label text if the user has backups enabled OR they are a managed customer.
**To test:**
1) Be a Managed user.
2) Go to Account -> Settings.
3) Under "Backup Auto Enrollment" you should see appropriate toggle state and label text:
=> Show 'Enabled' text for backups if Managed user

src/containers/localStorage.container.ts, src/utilities/storage.ts
This addresses https://github.com/linode/manager/issues/5162.
The "Group By Tag" feature was acting strangely, because of two issues:
1) The `localStorageCache` was not attempting to save values as parsed JSON, as we are doing for accessing values directly from localStorage. This meant that the localStorage value "false" (string) would be parsed as the boolean `false` when accessed the first time, but "false" (string) on subsequent reads. This affected LinodesLanding (and others).
2) There was a similar issue that persistent on VolumesLanding, NodeBalancersLanding, and DomainsLanding, but because of a different issue. Previously, the initialState function in `localStorageContainer` was only being called once, in a closure around `withStateHandlers`. This meant that only the value it got …
=> M3-2967 fix: Group by Tag localStorage state

src/components/Button/Button.tsx, src/themeFactory.ts
The loading icon was not spinning for some of the button variations - This can be tested in storybook or for instance the delete Linode confirmation button.
=> M3-2974 Fix progress button loading icon

src/features/Events/EventRow.test.tsx, src/features/Events/EventRow.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
At customer request, we are now including the username of the user who initiated the event in the Events Landing and Linode Activity Panel
N/A
=> M3-2964 Change: Add username to Event rows

src/components/TextField.tsx, src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx, src/themes.ts
Linode --> Settings --> Notification Thresholds
Default value would not be populated on page load - this was due to https://github.com/linode/manager/blob/develop/src/components/TextField.tsx#L187-L188
Added a fix which i hope won't introduce further regressions to some of our TextFields - some poking around should be done to test properly
=> M3-2963 FOR RELEASE - Fix Linode Notification Threshold updates not displaying

src/services/nodebalancers/nodebalancers.schema.ts
The API schema was updated to allow uppercase characters. Our schema has be updated to allow these as well. I also added periods to our schema, as these are allowed by the API.
Add a NodeBalancer Config Node with uppercase characters, periods, etc.
=> M3-2915: Update NB Config Node schema

README.md
Not sure what that was but looking at the Internet Archive's Wayback Machine, it looks like it was shutdown https://web.archive.org/web/20190514195744/https://waffle.io/
=> Remove 404 waffle.io badge from README

src/components/TextField.tsx
Add conditional logic to only make a shallow copy of the `event.target` if the sanitizedValue is _not_ equal to `event.target.value`
This fixes the issue where changing the select value on a MUI TextField select variant would cause this console error to be thrown and the app to crash:
```
Uncaught TypeError: e.target.cloneNode is not a function
```
N/A
To test, please make sure both regular text fields, number fields, and MUI select fields work properly. Examples of MUI select fields can be found under the Minecraft OCA.
=> Fix: Clone Node

src/__data__/disks.ts, src/features/linodes/CloneLanding/Configs.test.tsx, src/features/linodes/CloneLanding/Configs.tsx, src/features/linodes/CloneLanding/Disks.test.tsx, src/features/linodes/CloneLanding/Disks.tsx, src/features/linodes/CloneLanding/utilities.test.ts, src/features/linodes/CloneLanding/utilities.ts
More unit tests for the Clone Configs/Disks feature.
You'll probably need to clear out `node_modules` since this doesn't have the MUI update. 
This is the last PR into the feature branch. Once it's merged I'll rebase against `develop`.
**To test:** `yarn test src/features/linodes/CloneLanding/`
=> M3-2247: Unit Tests for Clone Configs/Disks

src/App.tsx
The VAT banner will likely be coming back at some point, hidden/displayed with feature flags. For the time being, I commented out the component in App.tsx.
Set your country to one in the EU, remove your Tax ID if you have one, and clear the local storage value for hiding the VAT banner. Previously, under these conditions, you should see the banner. With this PR, you shouldn't.
=> M3-22886 [for release]: Remove VAT banner

src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Fix spelling of "Paravirtualization" and "Full virtualization" in `LinodeConfigDrawer.tsx`.
=> M3-2988: Fix spelling mistake in LinodeConfigDrawer

src/features/Kubernetes/kubeUtils.ts, src/services/kubernetes/kubernetes.ts
Use beta API prefix for LKE endpoints.
Also includes a temporary fix to keep the Cluster Landing page from crashing.
=> LKE: use beta endpoint

src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Uhhh yeah. Not really sure why this block of code was in there in the first place. `private_ip` is a boolean value that already exists on the `POST /instances` endpoint.
This prevents tens of thousands of Sentry errors.
N/A
=> Stop Allocating Private IPs on Linode Create

src/features/Volumes/VolumesLanding.tsx, src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
Adding a new prop to VolumesLanding, `removeBreadCrumb`, that will hide the breadcrumb and display a static header instead. 
Please view both `/volumes` to see Breadcrumb still in use, and `LinodeDetails/volumes` to view static heading.
=> M3-2999 Breadcrumb regression on LinodeDetails/Volumes

src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, src/features/Volumes/VolumeDrawer/CreateVolumeForm.tsx, src/features/Volumes/VolumesLanding.tsx, src/store/volumeDrawer/index.ts, src/utilities/ga.ts
Currently there are three places you can open the Volume Drawer. This means there are three potential origins of Volume creation: 
1) "Add New Menu"
2) Volumes Landing
3) Linode Details ("Volumes" tab)
We'd like to include the origin in our GA event.
To accomplish this, I created a new property on the `volumeDrawer` Redux state called `origin`, which is set appropriately when the drawer is opened.
The origin is sent as an action on the GA, so when you look at the events with `Category="Create Volume"` you'll see something like:
Please test all methods of Volumes creation. Test that they work as expected, and that the appropriate GA events are being sent.
=> M3-2934: Better analytics for Volume Creation

src/components/Notice/Notice.tsx
Adjusts icon placement on important notices:
Compact:
Normal:
Please view on multiple breakpoints, and in both theme spacing modes.
=> M3-3006 Important notice styling

src/eventMessageGenerator.test.ts, src/eventMessageGenerator.ts, src/exceptionReporting.ts, src/features/Events/EventRow.tsx, src/features/TopMenu/UserEventsMenu/UserEventsList.tsx, src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
This PR does a couple things
1. Moves the `onUnfound` logic inside of the `eventMessageGenerator` rather than having to explicitly pass a callback
2. Adds more descriptive sentry errors with the full event payload, so we can properly debug.
N/A
=> Change: Enhance Sentry Reporting for Events

src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx, src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx, src/features/Users/UserPermissions.tsx
Removes button from the UI if you are a restricted user
Also removes cancel_account grant from the UI because we're not observing it, so it basically useless.
N/A
=> Close Account 3

src/features/Domains/DomainRecordDrawer.tsx, src/features/Domains/domainUtils.test.ts, src/features/Domains/domainUtils.ts
Left off a check when I added this validation.
1. create TXT record with host 'domain'
2. create CNAME with host 'domain'
should error. Currently only errors if you reverse the steps.
=> M3-3008 Fix domain record validation

src/utilities/backups.test.ts, src/utilities/backups.ts
I can't actually reproduce this, and the Sentry error/corresponding Jira ticket are pretty old. But safe access never hurt anyone, so thought I'd put this up for review anyway.
If the API returns `snapshot` as undefined or null, the app will crash when loading backups. It doesn't seem like the API will ever actually do this, but it seems to have happened somehow at least once.
Please give 👍 or 👎 ; no problem just closing this.
=> TDT: Safe access backups.snapshot (fix Sentry error)

e2e/config/custom-commands.js, e2e/pageobjects/nodebalancers.page.js, e2e/setup/setup.js, e2e/specs/nodebalancers/configurations.spec.js, e2e/specs/nodebalancers/error-handling.spec.js, e2e/specs/nodebalancers/smoke-create.spec.js, e2e/utils/common.js, src/features/NodeBalancers/ConfigNodeIPSelect.tsx, src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
Fixes NB Test Suite
3. `yarn e2e --dir /nodebalancers`
I skipped some unnecessary tests that weren't providing value and were just bombing, unrelated from the react-select change.
=> Fix: NodeBalancer E2E Tests

src/components/AccessPanel/AccessPanel.tsx, src/features/linodes/userSSHKeyHoc.ts
Adds two pieces of feedback/follow ons from the POC:
- Disables the SSH panel unless the consumer explicitly passes the `users` prop. This will remove the panel from e.g. the UDF fields.
- Preserves selected state, so after adding a key the list of selected users should be the same as before. 
prod-test-004 has 3 users with SSH keys. Toggle away!
=> M3-2969 Change: SSH Key flow

src/analytics.ts, src/constants.ts, src/index.tsx, src/utilities/ga.ts
Adds ability to use multiple GA IDs (we are going to add linode.com GA ID)
N/A
Add both cloud and linode.com GA IDs to your `.env` and trigger some events
=> Add: Ability to use multiple GA IDs

e2e/config/wdio.conf.js
If a test in a spec fails, stop running that spec entirely. This config will ultimately reduce the total number of tests, but give a more accurate count of how many tests are currently failing.
Also, set the bail count to 100, so if there's a 100 test failures to just exit since we know somethings wrong at that point (like the login service being down, etc)
We had this set up before, but we
- Test fix ('fix', 'repair', 'bug')
1. We'll run these on CI and compare the results
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> stop on spec failure, set bail count to 100

src/components/TableRow/TableRow.tsx, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, src/features/Domains/DomainTableRow.tsx, src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx, src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, src/themeFactory.ts, src/themes.ts
Instead of trying to capture a lot of event on the row, it's probably better to just make the titles for these entities a link so that people have the options to perform regular operations on them. While the feature is not obvious at first, it is a good fallback to have. I also made sure that these links have a negative tabIndex to not add a tab event to the row itself.
this was added for the linodes, domains and NBs entities as well as their dashboard placements
=> M3-2990 - TBT Re-add links in rows for Linodes, domains and NBs

src/eventMessageGenerator.ts
API release includes a `profile_update` event which we weren't handling. This event should probably be swallowed rather than show up in the user events bell, but we can save that for our ongoing events audit.
Please let me know what you think about the message. I think it'll almost always be redundant "Jared's profile has been updated by Jared" but thought it was worth it.
=> [For release] Handle profile update event

src/features/linodes/transitions.ts, src/store/events/event.helpers.ts, src/store/linodes/linodes.events.ts
If the last event that comes downstream from the API has 100% complete but a `status` of `started`, we need to get rid of the loading indicator and progress bar anyway.
N/A
Either clone a Linode or clone a disk and wait until you get an event that is has a `percent_complete` of `100` and a status of `started`. You must NOT get a final event with a `finished` status to test this scenario.
=> [For Release] Clone Progress Fix

src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
These changes add some clarity to the way the Linode Backup Service works in response to the confusion raised here:
https://twitter.com/DavidWolfpaw/status/1150847733101748226
=> Update LinodeBackup.tsx text

src/features/Domains/DomainActionMenu.tsx
Adding a tooltip for the Zone File action on domains. This will eventually be actionable but until then we want users to be presented with a little more information than prior to the tooltip. 
Go to `/domains`, click the kebob of a master and/or slave domain, and view the tooltip for the 'Zone File' action.
=> M3-2894 Zone file tooltip

src/components/CookieWarning.tsx, src/index.tsx
For uses with cookies disabled (or blocking cookies for cloud.linode.com), we show a warning that the user must enable cookies before browsing the app and report to Sentry.
N/A
Block cookies for localhost:3000 and browse the app. https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en
=> Add: Cookie Warning Message

src/components/PreferenceToggle/PreferenceToggle.tsx, src/features/Volumes/VolumesLanding.tsx, src/utilities/storage.ts
Observes user preferences when toggling "group by tag" on the Volumes landing page.
N/A
Toggle all existing user preferences (theme, spacing, linode view, and linode group by tag). Make sure they're not overwriting each other and PUT to the API with the correct payload.
=> Change: Observe User Prefs for Volumes Group By Tag

src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
Added a loading state to the edit RDNS drawer (in the Linode networking tab). Since this usually takes 30 seconds, I also added some "please be patient"-ish helper text.
This component is still pretty iffy. I opened a tdt ticket for refactoring it to use more up-to-date patterns. We should also consider moving this component to the root level and managing its state through Redux, since the submission action, while technically synchronous, can take ~30 seconds, so if the user closes the drawer and moves to another part of the site, they won't be able to see the result of their request. Toasts might be a better choice for error/success messaging.
=> M3-2994 Change: handle RDNS loading state

src/__data__/kubernetes.ts, src/__data__/nodePools.ts, src/containers/kubernetes.container.ts, src/features/Kubernetes/CreateCluster/CreateCluster.tsx, src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx, src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, src/features/Kubernetes/KubeCheckoutBar.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx, src/features/Kubernetes/kubeUtils.ts, src/features/Kubernetes/types.ts, src/services/kubernetes/index.ts, src/services/kubernetes/kubernetes.ts, src/services/kubernetes/nodePools.ts, src/store/index.ts, src/store/kubernetes/kubernetes.actions.ts, src/store/kubernetes/kubernetes.reducer.ts, src/store/kubernetes/kubernetes.requests.ts, src/store/kubernetes/nodePools.actions.ts, src/store/kubernetes/nodePools.reducer.test.ts, src/store/kubernetes/nodePools.reducer.ts, src/store/kubernetes/nodePools.requests.ts, src/types/Kubernetes.ts
This separates LKE clusters from LKE node pools; previously API requests to /clusters returned a list of node pools for each cluster.
This involves changing both the services library and the Redux store.
Test using dev services; this PR does not use the new Redux state, so you'll have to create a cluster with some pools, then check the Redux dev tools to make sure everything is there and actions were called correctly. Part II will restore the previous app functionality by using node pools from Redux to populate ClusterList and ClusterDetail.
Many of the files changed are just find-and-replace variable renaming.
=> LKE-615: Update: Add NodePools to Redux

src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, src/components/PreferenceToggle/PreferenceToggle.tsx
Fixes issue where white screen was loading on throttled connections.
Basically, the issue was happening because the 
```js
React.useEffect(() =>  /* do something */, [props.preferences])
```
was running on mount when `props.preferences` was `undefined` This was unacceptable behavior because we only want that `useEffect` to run when we either have a successful or failed GET from the API.
N/A
Throttle your network connection with chrome dev tools and navigate to the app
The amount of time the white screen appears for slower connections is still unacceptable. I'm going to next work on POC to give some better visual indicators, while our chunks are in-flight.
=> Fix: White Screen Issue

src/__data__/kubernetes.ts, src/__data__/nodePools.ts, src/containers/kubernetes.container.ts, src/features/Kubernetes/ClusterList/ClusterList.tsx, src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, src/features/Kubernetes/kubeUtils.test.ts, src/features/Kubernetes/kubeUtils.ts, src/features/Kubernetes/types.ts, src/store/kubernetes/nodePools.reducer.ts, src/types/Kubernetes.ts
Brings the LKE section back up to where it was before the API changed. Viewing, editing, adding, and deleting clusters should work normally.
Tests and __data__ fixes have a big footprint here. Major changes are in the kubernetes.container, where we're adding node pools before passing them on to the consumer; typing updates; and a fix to the reducer (which was concatenating responses, causing the size and price of a cluster to increase linearly every time you clicked back to /kubernetes).
=> LKE-615 Fix node pools

src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx, src/utilities/storage.ts
Observes user preferences when toggling "group by tag" on the NodeBalancers landing page.
N/A
Toggle all existing user preferences (theme, spacing, linode view, and nodebalancer group by tag). Make sure they're not overwriting each other and PUT to the API with the correct payload.
=> Change: Observe User Prefs for NodeBalancer Group By Tag

src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx, src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
'Settings' action was being removed if backups weren't enabled. You should now always see 'Settings' in the dropdown (and only `Enable` or `View Backups` depending on if you have backups enabled)
Please check linodes with and without enabled backups. Also please note I created a follow-up ticket to update our tests for this as well.
=> M3-2996 Settings option not showing in Linode Action dropdown unless backups are enabled

src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
Current Behavior:
1. Do some long-running action on Linode
2. Navigate to Linode detail
3. Observe - the power control shows "offline"
New Behavior:
1. Repeat steps 1 and 2
2. Observe - power control correctly shows "busy"
N/A
=> Fix: Power Control Not Showing Busy Status

src/features/Domains/DomainsLanding.test.tsx, src/features/Domains/DomainsLanding.tsx, src/utilities/storage.ts
Observes user preferences when toggling "group by tag" on the Domains landing page.
N/A
Toggle all existing user preferences (theme, spacing, linode view, and domain group by tag). Make sure they're not overwriting each other and PUT to the API with the correct payload.
=> Change: Observe User Prefs for Domains Group By Tag

src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
Fixes two bugs:
1. While long-running events are happening on a Linode, you cannot interact with the IP transfer panel because it kept re-rendering with every new event and resetting the entire form.
2. While swapping IPs, when selecting different target Linodes, the 4th IP select panel wasn't updating its values to match the IPs associated with the selected Linode.
N/A
I also made the executive decision to get rid of the fields being disabled if there's only one value. imo, it's bad UX and implies that something is wrong.
=> Fix: IP Transfer Logic

src/eventMessageGenerator.ts, src/features/TopMenu/UserEventsMenu/UserEventsMenu.tsx, src/utilities/eventUtils.ts
There are enough edge/special cases that I'm giving up on trying to reduce duplication for now. `removeBlacklistedEvents` now takes an optional "extra" blacklist, so that each consumer can filter out events in addition to the global blacklist. This is used to filter `profile_update` events from Events Landing.
Also adds handling for new events `ipaddress_update` and `user_update` .
=> Try a different approach for blacklisting events

src/__data__/linodeConfigs.ts, src/features/linodes/CloneLanding/CloneLanding.tsx, src/features/linodes/CloneLanding/Configs.tsx, src/features/linodes/CloneLanding/Disks.tsx, src/features/linodes/CloneLanding/utilities.test.ts, src/features/linodes/CloneLanding/utilities.ts
The problem:
1. Open the Config/Disk Clone page.
2. In another tab, delete a disk.
3. **Observe:** in a few seconds, the Clone page will crash.
This was because `disks` (from LinodeDetailContext) changed, but the CloneLanding `useReducer` state did _not_  change.
Now, the state changes whenever there is a change to `configs` or `disks`, via `useEffect`.
To achieve this without a lot of wasteful re-renders required moving some things around. This blog post (actually a mini-book) was particularly helpful in understanding the ins and outs `useEffect()`: https://overreacted.io/a-complete-guide-to-useeffect/
- `configs` won't change when you delete a config in another tab, because we're not listening for that event (will do another PR).
- Try multiple …
=> M3-3025 fix: Update CloneLanding state when configs or disks change

src/components/Pagey/Pagey.ts, src/features/ObjectStorage/AccessKeys/AccessKeyTable.test.tsx, src/features/Profile/APITokens/APITokenTable.tsx, src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx, src/features/Profile/SSHKeys/SSHKeys.test.tsx, src/features/Profile/SSHKeys/SSHKeys.tsx, src/features/StackScripts/LandingPanel/Table/StackScriptTable.tsx, src/features/StackScripts/LandingPanel/Table/TableRows/TableRows.tsx, src/features/Users/UsersLanding.tsx, src/utilities/request.ts
Adds descriptive messaging if requests to `/users`, `/sshkeys` or `/tokens` returns a `403` status
N/A
There's a lot of noise in this PR mainly because I changed the `error` type in Pagey to be a `Linode.ApiFieldError[]`
=> Add: Unauthorized Messaging for Users, SSH Keys, and API Tokens

src/components/AccessPanel/AccessPanel.tsx, src/components/AccessPanel/UserSSHKeyPanel.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx, src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx, src/features/linodes/userSSHKeyHoc.ts, src/store/linodes/linodes.events.ts
Fixes two bugs:
- Rebuild a Linode, then try to edit the configuration profile (this was 404'ing; we fixed this for disks, but I forgot about configs. Config IDs change after a Linode is rebuilt, but our Redux store doesn't know this and attempts to access the (deleted) original configs.)
- Log in as a restricted user and try to add an SSH key (these were not displaying; I removed some code I thought was redundant in UserSSHKeyHoc.ts, but requests to both `/profile/ssh-keys` and `/account/users` are necessary to handle the case of a restricted user.)
Also changes the "Add SSH Key" to a secondary button rather than primary.
=> M3-3049 M3-3050 Fix: Refresh configs after rebuild; SSH Keys

src/App.tsx, src/containers/domains.container.ts, src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, src/features/Domains/DomainDetail.tsx, src/features/Domains/DomainDrawer.tsx, src/features/Domains/DomainsLanding.test.tsx, src/features/Domains/DomainsLanding.tsx, src/store/domains/domains.actions.ts, src/store/domains/domains.reducer.ts, src/store/selectors/entitiesErrors.ts, src/store/selectors/entitiesLoading.ts, src/store/selectors/getEntitiesWithGroupsToImport.test.tsx, src/store/selectors/getEntitiesWithGroupsToImport.tsx, src/store/selectors/getSearchEntities.ts, src/store/types.ts, src/utilities/getEntityByIDFromStore.ts, src/utilities/updateOrAdd.ts
This PR restructures the Redux state shape of Domains. Previously it was `EntityState`, now it's `RequestableDataWithEntityError`.
Nothing from the user's point of view should change. Test domain actions and error states.
=> M3-2879: Update Redux state shape for Domains

.travis.yml, src/components/Breadcrumb/Breadcrumb.spec.js, src/components/EntityIcon/EntityIcon.spec.js, src/components/EntityIcon/EntityIcon.stories.tsx, src/components/ErrorState/ErrorState.spec.js, src/components/ErrorState/ErrorState.stories.tsx, src/components/ExpansionPanel/ExpansionPanel.spec.js, src/components/ExpansionPanel/ExpansionPanel.stories.tsx, src/components/HelpIcon/HelpIcon.spec.js, src/components/IconTextLink/IconTextLink.spec.js
Correct and upgrade breadcrumbs storybook test
3. `yarn storybook`
These updates were to make sure that the breadcrumb storybook tests were able to run again. Also added in some more validation and began using withContext() to add error messaging. You will need to use node v10 to run these tests. All the tests are not running and passing.
=> M3-2992 Feature/wdio v5

packages/manager/e2e/pageobjects/account/invoice.page.js, packages/manager/src/constants.ts, packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
- View a bunch of invoice PDFs, moving your country setting in and out of the EU. This doesn't quite break the layout of the PDF, which is finicky so I left it as is. Let me know if we need to add additional space (conditionally) to account for this row.
- I also stripped "(pending upgrade)" from Linode type descriptions, as this was breaking the PDF layout.
AFAICT no tests actually use the typo I fixed, but I can't actually run them atm so not 100% sure.
=> M3-3014 Add: Show Linode tax ID on invoices for users in EU

packages/manager/src/constants.ts, packages/manager/src/features/Events/EventsLanding.tsx, packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsList.tsx, packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsListItem.tsx, packages/manager/src/store/events/event.helpers.ts, packages/manager/src/utilities/getEventsActionLink.ts, packages/manager/src/utilities/getEventsActionLinkStrings.ts
- Fixed regression where all events were clickable in the UserEventsMenu
- Fixed a previously unnoticed bug where events labeled something_delete
(config_delete, disk_delete) were causing all of the events for the
corresponding Linode to be unclickable, even if the Linode was still there
- Added click handlers for linode_addip, ipaddress_update, and user_update.
- Filtered profile_update events from the events landing page (request from Chris)
As always this section of the app is a pain. There's a lot of duplication that's accumulated, opened a ticket to handle this (next TDT possibly).
=> M3-3070 Fix: Events regressions and add handling for new event types 

packages/manager/src/containers/kubernetes.container.ts, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/types.ts
ClusterDetail page now includes a (X up, Y down) status notification similar to NodeBalancers. While on the details page, the /pools endpoint will be polled every 10 seconds to keep the status information up to date. 
There's an API bug that is throwing off the number of linodes in each node pool. And the status of all nodes is always "down" for now. Try to ignore all that! The logic should work
=> LKE-691 Add: Node pool polling

packages/manager/src/store/profile/profile.reducer.ts, packages/manager/src/utilities/request.ts
Adds reporting for unexpected errors from the API that don't have the `{ reason: 'hello world' }` shape. A few of these have come in lately and they're hard to troubleshoot.
N/A
Use Charles to 400 an API response with some crazy response
=> Change: Sentry Updates

packages/manager/src/App.tsx, packages/manager/src/IdentifyUser.tsx, packages/manager/src/components/DataLoadedListener.tsx, packages/manager/src/constants.ts, packages/manager/src/containers/withFeatureFlagProvider.container.ts
I think it works this time! h/t to @martinmckenna for the splash screen (which I know may or may not be included in this release; it really should be since it ties this together).
To test:
- Set up a conditional use of a flag anywhere in the app:
- `import useFlags from 'src/hooks/useFlags'`
- `const flags = useFlags();`
- `if (flags.demo) { renderFeature(): }`
I used the maintenance banner in Dashboard.tsx, since it's rendered on app load. `flags.demo` is `true` for anonymous users (before we have /profile data), and `false` for all other users.
You should never see the banner (or feature you've flagged).
=> Add identify-user logic to App.tsx

packages/manager/src/eventMessageGenerator.ts, packages/manager/src/features/linodes/transitions.ts, packages/manager/src/store/linodes/linodes.events.ts, packages/manager/src/types/index.ts, packages/manager/src/utilities/eventUtils.ts
This PR adds messaging for the following events:
1. `token_create`
2. `token_update`
3. `token_delete`
4. `oauth_client_create`
5. `oauth_client_update`
6. `oauth_client_secret_reset`
7. `oauth_client_delete`
8. `tag_create`
9. `tag_delete`
10. `linode_migrate_datacenter_create`
11. `linode_migrate_datacenter`
Additional logic was also added to handle cross DC migration progress and status.
**USE STAGING**
1. Create/Rename/Revoke Personal Access Tokens
2. Create/Edit/Delete/Rest Secret for OAuth Apps
3. Create/Delete tags (must be done with API – can't do this in Cloud yet)
4. Initiate cross DC migration (must be done with API – can't do this in Cloud yet)
=> [For Release] Add: event types

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/services/kubernetes/kubernetes.schema.ts
Some feedback suggestions from @jnschaeffer :
- Fix error message in our kubernetes.schema label validation.
- Fix page title (was still hardcoded to 'label')
- Don't force uppercasing of cluster label in the breadcrumb view
=> LKE-728 Change: schema copy

packages/manager/src/components/TextField.tsx
Fixes issue where any custom `inputProps` that were passed to our `TextField` component were not being applied.
For example, the NodeBalancer Config Node label was not updating correctly when you typed in the field because this prop wasn't being passed down: `inputProps={{ 'data-node-idx': idx }}`
1. `yarn up`
2. `lerna run selenium`
3. `lerna run e2e -- --spec=packages/manager/e2e/specs/nodebalancers/smoke-create.spec.js`
=> Fix: Properly Spread inputProps to TextField

packages/manager/src/containers/kubernetes.container.ts, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.test.tsx, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx, packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx, packages/manager/src/store/kubernetes/nodePools.reducer.ts
- New success message (may or may not stick)
- Loading state for node pools panel (they were previously relying on the cluster loading, but node pools are now extra requests so the loading experience was bad).
=> LKE-692 Change: update success message when editing node pools

packages/manager/src/components/EnhancedSelect/components/Option.tsx, packages/manager/src/features/Help/Panels/SearchItem.tsx
Algolia search bar (at `/support`) had broken scrolling functionality; the mouse wheel would work, but arrow keys didn't. This is a leftover to-do from moving from Downshift to RS.
=> Fix: Wrap SearchItem in RS <Option /> to fix arrow key scrolling

packages/manager/src/App.tsx, packages/manager/src/components/SplashScreen/SplashScreen.tsx
🚨 REQUIRES NODE 10 🚨 
Prevents issues with both the app and splash screen being visible at the same time for a split second.
=> Update: Splash Screen Styles

CLOUD.md, GETTING_STARTED.md, RELEASING.md, TESTING.md
The getting started guide was making the assumption that lerna is installed globally on a user's machine. `npx` users the binary installed in `$PROJECT_ROOT/node_modules/.bin/lerna`. 
- Docs fix
* None
=> fix: run lerna commands with npx

packages/manager/src/assets/icons/ticket-blue.svg, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/features/Managed/SupportWidget.tsx, packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Open a Support ticket from the Managed landing page.
Additionally, fixed a regression in the ticket drawer where the selected entity wasn't clearing when you selected a different entity type.
Use the testing LD key, and make sure the `managed` flag is toggled on.
=> M3-711 Add SupportWidget to Managed landing

packages/manager/package.json, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/yarn.lock
The listed flags in the Create flow were not displaying for Firefox; the CSS addition fixes that. I think it's kinda hacky, but there doesn't seem to be any other explanation or solution.
This issue was only occurring in Firefox, but all browsers should be checked to ensure this fix doesn't regress anywhere else.
=> M3-3056 England, Singapore, and Tokyo Flag's are not rendering under "Region" using Firefox

packages/manager/src/components/Breadcrumb/Breadcrumb.test.tsx, packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
Small changes from the Caker sessions
1. We get rid of leading slash for all breadcrumbs
2. We asjust the color of the remaining slashes to make them less prominent
- existing crumbs (profile, tickets, entities etc)
=> M3-3038 Breadcrumb enhancements

packages/manager/src/components/DownloadCSV/DownloadCSV.test.ts, packages/manager/src/components/DownloadCSV/DownloadCSV.tsx, packages/manager/src/components/DownloadCSV/index.ts, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
🚨 REQUIRES NODE 10 🚨 
Recursively wraps instances of `+`, `-`, and `=`  in double quotes to prevent CSV injections
N/A
If you have  a windows machine and microsoft excel, try following the steps [here.](https://github.com/linode/manager/pull/5294/files#diff-6bf2769986df56bab95b913bdc2d8867R32) Otherwise, I'm not really sure how to test.
=> Change: Add Logic to CSV Link to Prevent CSV Injections

packages/manager/src/components/CircleProgress/CircleProgress.stories.tsx, packages/manager/src/features/Billing/BillingPanels/RecentInvoicesPanel/RecentInvoicesRow.tsx, packages/manager/src/features/Billing/BillingPanels/RecentPaymentsPanel/RecentPaymentsPanel.tsx
Links were previously bold (wrong styles, shown above) and I also added a circular progress for the PDF generating duration (there was previously one as it as a button)
=> M3-3115 Improve link styles for PDF downloads in account

packages/manager/src/containers/managedServices.container.ts, packages/manager/src/features/Managed/Monitors/MonitorTable.tsx, packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx, packages/manager/src/features/Managed/Monitors/Monitors.tsx, packages/manager/src/services/managed/index.ts, packages/manager/src/services/managed/managed.ts, packages/manager/src/store/index.ts, packages/manager/src/store/managed/managed.actions.ts, packages/manager/src/store/managed/managed.reducer.test.ts, packages/manager/src/store/managed/managed.reducer.ts, packages/manager/src/store/managed/managed.requests.ts
Follow-on to #5303. Uses live data to populate the Monitors table at managed/monitors.
- Add services/managed with a `getServices()` method
- Add Redux boilerplate for `requestManagedServices()`
- Add `containers/managedServices.container`
- Add loading states and live data to Monitors.ts
=> M3-692 Add: Managed service monitors in redux

packages/manager/src/components/TextField.tsx, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
• Adjusting width of textfield input for node pool count (On the create flow, and under cluster details page for both 'add node pool' panel and 'edit node pools' panel)
• Preventing jumping/shifting that was happening if user edited their node pool count (from a 1 digit to 3 digit number, for instance)
=> LKE-693: Node Pool Input Updates

packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
In an attempt to make the search landing more prominent, move the
final search option in the Algolia search bar on the Get Help landing
page, which is a link to the search landing page, to the top of the
results list.
Now, when users type in a search query and press Enter, they'll be
taken to the search landing page. If they click on one of the results
in the dropdown, or scroll down to an option with the arrow keys,
they'll be taken (as before) to the external link for that result.
=> M3-3044 Change: Make search link the first option in Algolia search bar

packages/manager/src/LinodeThemeWrapper.tsx, packages/manager/src/components/PrimaryNav/ThemeToggle.tsx
Since switching the theme wrapper to a functional component we experienced some issues with css transitions after the theme switch (we disable all css transitions on theme switch as some elements would get background or color transitions on theme switch). This PR fixes that.
To test, before and after, do a theme switch and open a drawer (ex: create a volume from the create menu)
=> M3-3108 Fix issue with css transitions on theme switch

packages/manager/src/containers/managedServices.container.ts, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx, packages/manager/src/features/Managed/Monitors/MonitorRow.tsx, packages/manager/src/services/managed/managed.ts, packages/manager/src/store/managed/managed.actions.ts, packages/manager/src/store/managed/managed.reducer.test.ts, packages/manager/src/store/managed/managed.reducer.ts, packages/manager/src/store/managed/managed.requests.ts
Use the action menu on the Monitors list to disable an active monitor.
You'll have to use Classic to create a managed service monitor (first enroll yourself in Managed if you're not). You can curl the api (`POST managed/services/{id}/enable`) to toggle services back on so you don't have to keep creating them.
=> M3-703 Add: disable managed service monitor

packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx
Builds were failing for typescript reasons
=> Fix: Monitor Action Menu Tests

packages/manager/src/components/Breadcrumb/Breadcrumb.test.tsx, packages/manager/src/components/Breadcrumb/Breadcrumb.tsx, packages/manager/src/components/Breadcrumb/Crumbs.tsx, packages/manager/src/components/Breadcrumb/FinalCrumb.tsx, packages/manager/src/components/Breadcrumb/FinalCrumbPrefix.tsx, packages/manager/src/components/Breadcrumb/types.ts, packages/manager/src/components/EditableText/EditableText.tsx
Previously, there was a bug where
1. Create a Linode
2. Perform some long running action (such as resize)
3. Open up the editable text edit mode
4. Wait - the editable text should exit edit mode automatically
The reason for this is because the editable text component was re-mounting every single time it updated because there was a function being re-instantiated inside the `<BreadCrumb />` component. I removed this logic, but also split the breadcrumb into smaller, more digest-able components, so it's more clear what's happening
N/A
=> Fix: Issue with Editable Text Remounting

packages/manager/src/__data__/account.ts, packages/manager/src/features/Billing/BillingPanels/PromotionsPanel/PromotionDisplay.tsx, packages/manager/src/features/Billing/BillingPanels/PromotionsPanel/PromotionsPanel.tsx, packages/manager/src/features/Dashboard/Dashboard.tsx, packages/manager/src/types/Account.ts
Backend folks have added `summary` and `image_url` fields to each promotion so that we can display header text separate from the description. (We're not using image url atm but maybe we should?)
Note: Unrelated to this specific PR, there will also be a notification for active promotions on your account. I'm not doing anything with that, and calculating the values from the `active_promotions` array on the `account` object. The reason for this is that we would have to do text splitting to match the design on the Dashboard, and we already have access to all the information we need through the aforementioned `active_promotions` object.
=> Promo codes: Add summary field to promotion

packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/CancelAccountDialog.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/DeleteIPActions.tsx, packages/manager/src/features/linodes/LinodesLanding/DeleteDialog.tsx, packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
Finding and replacing the cancel buttons with a "secondary" buttonType prop (should be "cancel") 
=> M3-3126 Fix wrong button types for cancel actions

packages/manager/src/components/Placeholder/Placeholder.tsx, packages/manager/src/themes.ts
This small fixes remove some of the console warnings in the pre commit hook for our tests:
```
PASS src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.test.tsx
linode-manager:   ● Console
linode-manager:     console.warn node_modules/tiny-warning/dist/tiny-warning.cjs.js:13
linode-manager:       Warning: [JSS] Referenced keyframes rule "rotate" is not defined.
linode-manager:     console.warn node_modules/tiny-warning/dist/tiny-warning.cjs.js:13
linode-manager:       Warning: [JSS] Referenced keyframes rule "rotate" is not defined.
linode-manager: PASS src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx
linode-manager: PASS src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx (31.13s)
linode-manager:   ● Console
linode-manager: …
```
=> M3-3131 Fix wrong instances of css animations in JSS

packages/manager/src/components/SelectionCard/CardBase.tsx, packages/manager/src/components/SelectionCard/SelectionCard.tsx
fixing this ^
- Bug fix ('bug')
=> M3-3128 Fix one-click cards display on large breakpoints

packages/manager/src/__data__/account.ts, packages/manager/src/types/Account.ts
A field has been removed from the API response. We weren't using it anyway, so this is just to keep the typings up to date.
=> Update: Remove label from active_promotions typings

packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/linodes/LinodesLanding/ToggleBox.tsx
Adds a 'Create New Linode' button on the Linode Landing to match the pattern for other entity landing pages.
=> Add a create new button for Linode Landing

packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.test.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx, packages/manager/src/hooks/useAPIRequest.ts, packages/manager/src/services/managed/managed.schema.ts, packages/manager/src/services/managed/managed.ts
**Part III** includes the Action Menu and scaffolding for the drawer.
_Still to come in Part IV: SSH Access form (in the drawer)._
I've made a few changes so that the `useAPIRequest` hook exposes two additional methods to the consumer:
- `update()`, which will re-run the request. This actually isn't used in the final version of this PR, but will be useful nonetheless, so I left it in.
- `transformData()`, which accepts a function and uses Immer.js to mutate the data. It can be used like this:
```typescript
const { data, transformData } = useAPIRequest(someRequest, []);
// Update one element
const updateOne = (linodeSetting) => {
transformData(draft => {
const idx = draft.findIndex(l => l.id === linodeSetting.id);
draft[idx] = linodeSetting;
});
};
// When `updateOne()` is called, the …
```
=> M3-695 SSH Access Part III: Action Menu and Drawer scaffold

packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
Updating `buttonType` and `destructive` props to include reboot action so 'Reboot' matches 'Power On' styling.
On Linodes Landing, Use the action menu to initiate the reboot confirmation modal.
=> Reboot confirmation modal

packages/manager/src/__data__/managedCredentials.ts, packages/manager/src/__data__/serviceMonitors.ts, packages/manager/src/features/Managed/Credentials.tsx, packages/manager/src/features/Managed/Credentials/CredentialActionMenu.tsx, packages/manager/src/features/Managed/Credentials/CredentialList.tsx, packages/manager/src/features/Managed/Credentials/CredentialRow.tsx, packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx, packages/manager/src/features/Managed/Credentials/index.tsx, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/features/Managed/Monitors/Monitors.tsx, packages/manager/src/services/managed/managed.ts, packages/manager/src/types/Managed.ts
View a list of Credentials on your account at managed/credentials. Adding isn't included yet, so you'll have to use classic to add a few.
I turned ManagedLanding into a function component so I could use John's new useAPIRequest hook. I don't think this introduced any bugs or performance problems but please check.
The API doesn't yet return last_decrypted, so that field will always be blank for now. I'm not exactly sure what the response will look like (Classic shows the username that did the decrypting), but there's some sample data in __data__ that you can use to get some idea.
=> M3-696 Add: View managed credentials

packages/manager/src/components/IPSelect/IPSelect.tsx, packages/manager/src/components/IPSelect/index.ts, packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx, packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx, packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx, packages/manager/src/services/managed/managed.schema.ts, packages/manager/src/utilities/ipUtils.ts
This PR includes the SSH Access Edit Form inside the drawer. This should be the final PR for this page.
Go to Managed > SSH Access, and edit several Linodes to get a feel for the form.
`<IPSelect />`
This component accepts a Linode ID and will display that Linode's IPv4 and IPv6 addresses as options. Linode data is sourced from Redux. 
It allows a `customizeOptions` function, used by the consumer to apply any desired transformations:
```jsx
<IPSelect 
linodeId={1234}
customizeOptions={options => 
options.map(option => option.label = "CUSTOM LABEL")
}
/>
```
=> M3-695 SSH Access Part IV: Form

packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeBusyStatus.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx, packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx, packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.test.ts, packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx, packages/manager/src/features/linodes/MigrateLanding/MigrationImminentNotice.tsx, packages/manager/src/utilities/formatRegion.ts, packages/manager/src/utilities/ga.ts
Adds CTA to the Advanced tab on the Linode detail screen. Also incorporates GA to track navigation on both that page and the Linode Action Menu.
* Adds Banner if `migration_imminent` notification exists that the user cannot schedule another migration to replace the existing one, with a CTA to open a support ticket if they really want to do it
* Fixes a bug where if you do the following, you will not see a progress bar for your Linode
* 1. Do some long running event
* 2. Change the Linode label
* Adds CTA to Advanced tab to navigate to the Migrate workflow.
N/A
If you
1. POST to `/migrate`
2. POST again before the migration starts
You will notice that GET `/notifications` still returns a `migration_imminent` payload, even after the migration is …
=> Inter-DC Migration Part 4: Add CTA on Advanced Tab with GA Integration

package.json
Adds more decoupled `start` commands so that Docker containers can start the projects without having to re-run the install commands every time.
`yarn start:manager` - builds the SDK and starts manager
`yarn start:all` - starts all projects in watch mode.
=> Update: Root Package.json Commands

.gitignore, packages/manager/src/features/Domains/DomainTableRow.tsx, packages/manager/src/features/Domains/ListDomains.tsx, packages/manager/src/features/Domains/ListGroupedDomains.tsx
In order to be consistent with the rest of the landing pages, we should remove the tags from the row since we display tags in the detail pages for all entities.
=> M3-3175 Remove tags from domains landing table rows

packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Conditionally determines where the OBJ docs go depending on what tab you're on
Also removes `withRouter` since components inside a Router have those props available without the need for the HOC.
=> Update: Generate OBJ docs conditionally

packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessTable.tsx, packages/manager/src/features/Managed/SSHAccess/common.ts
This PR adds clarity to the defaults of `user` and `port` in Managed SSH Access settings. 
For all intents and purposes, the default `user` is "root", and the default `port` is 22. These are returned as `null` from the API. We want to display the defaults to the user, though, so we normalize the data by exchanging `null` for the defaults.
**To test:**
_Use a Managed account_
1) Create a new Linode.
2) Go to Managed -> SSH Settings.
3) **Observe:** User and Port should be  displayed as "root" and "22".
4) Open the Edit drawer for the settings for that Linode.
5) Give it a custom user and port.
6) **Observe:** this should be successful.
7) Open the Edit drawer again.
8) Clear out the user and port fields.
9) Submit the form.
10) **Observe:** A request was …
=> Managed SSH Access Settings – clarify defaults

packages/manager/src/components/DeletionDialog/DeletionDialog.tsx, packages/manager/src/components/DeletionDialog/index.tsx, packages/manager/src/features/Managed/Contacts/Contacts.tsx, packages/manager/src/features/Managed/Contacts/ContactsActionMenu.tsx, packages/manager/src/features/Managed/Contacts/ContactsRow.tsx, packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx, packages/manager/src/features/Managed/Credentials/CredentialList.tsx, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/features/Managed/Monitors/MonitorTable.tsx, packages/manager/src/services/managed/managed.ts
The PR adds the ability to delete a contact from your list of Managed Contacts.
Since this was the third place `MonitorDialog` was used, I moved that component to the `src/components` directory and renamed it `DeletionDialog`. I updated `MonitorTable.tsx` and `CredentialList.tsx` to honor this change.
Go to Managed -> Contacts. You'll need to add contacts in Classic (or https://github.com/linode/manager/pull/5377). Try deleting contacts. Note: deleting groups is not yet supported.
=> M3-707 Managed: Delete Contact

packages/manager/src/App.tsx, packages/manager/src/components/TaxBanner/TaxBanner.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Dashboard/Dashboard.test.tsx, packages/manager/src/features/Dashboard/Dashboard.tsx
Shows the dashboard on the account landing and dashboard only.
Also conditionally renders "click here" text.
=> Change: Show Tax Banner on Dashboard and Account Landing

packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx, packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
Removes Private IP checkbox from clone workflow because API doesn't support it.
=> Change: Remove Private IP Checkbox from Clone Workflow

packages/manager/src/App.test.tsx, packages/manager/src/App.tsx, packages/manager/src/components/DataLoadedListener.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/containers/accountSettings.container.ts, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/features/Managed/EnableManagedPlaceholder.tsx, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/features/Managed/ManagedLandingContent.tsx, packages/manager/src/hooks/useAPIRequest.ts, packages/manager/src/services/managed/managed.ts, packages/manager/src/store/accountSettings/accountSettings.actions.ts, packages/manager/src/store/accountSettings/accountSettings.reducer.ts
If:
- you don't have Managed on your account; and
- flags.managed is active
going to /managed will show a new Placeholder with a button to enable Managed
- I tried to keep this small, so touched the accountSettings Redux stuff as little as possible. It uses our most ancient patterns though and is in dire need of a refactor. Will try to do that in another PR.
- Copy is not final
=> M3-1464 Add: Placeholder to enable Managed

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Fixes issue where kernel input was not being populated due to race conditions with the getAllKernels request and how react-select's `defaultValue` props functions.
Keep opening and closing the Advanced Config edit drawer and make sure the Kernel input is pre-populated.
=> Fix: Kernel Default Value in Edit Config Drawer

packages/manager/src/components/TaxBanner/TaxBanner.tsx
Wanted to make sure the banner had an "important" prop, was had proper markup/padding
=> M3-3235 Update styling issue with Tax info banner

packages/manager/src/features/Dashboard/ManagedDashboardCard/Healthy.tsx, packages/manager/src/features/Dashboard/ManagedDashboardCard/Unhealthy.tsx, packages/manager/src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
There was a discrepancy of styles when having the managed dashboard card on top of other cards. The icon was disproportionate and needed to be adjusted to match the entity icons in order to create a better visual flow.
=> M3-3234 Update managed icon on dashboard to align with entity icons

packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
This is more of a quick fix; we always intended to update the default labeling logic post-1Click but never did, so I made a ticket for that too.
This prevents 'debian' being set as the label for creation flows where no image is selected/submitted (Cloning and backups).
=> M3-3238 Fix: Backups and clones always labeled as "Debian"

packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
Closing https://github.com/linode/manager/pull/5420 in favor of this solution
So the issue here is that [some of the country short hand codes](https://github.com/country-regions/country-region-data/blob/master/data.json#L269) are the numeric ISO 3166 format, which is a problem and instead we should just send the full country name.
BUT 
as @Jskobos correctly pointed out [here](https://github.com/linode/manager/pull/5420#pullrequestreview-283180448), the DB and API has a 24 character limit, so sending the full region name just won't work. This is the interim solution until we can up the character limit - just let the user type whatever they want.
=> Change: Replace Province/State Select Field with TextField

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx, packages/manager/src/services/linodes/getLinodeInfo.ts
Adjusts the Mutation Banner to account for types that don't exist in the response data from `GET /types` or `GET /types-legacy`. 
Login to prod-test-003. There you'll find 2 Linodes. 1 with a deprecated plan that exists in `GET /types-legacy` and 1 that doesn't
=> Change: Request Type if None Found in /types or /types-legacy

packages/manager/src/features/Managed/EnableManagedPlaceholder.tsx
=> M3-3257 Increase font size for enabling managed confirmation modal

packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessActionMenu.tsx, packages/manager/src/features/Managed/SSHAccess/SSHAccessRow.tsx
Previously, the API erroneously returned false for the ssh.access
boolean of a Linodes Managed Settings object when access was
enabled in our database.
This was fixed and reversed in ARB-1411.
I ran this locally but haven't done any automated tests on it yet.
=> [Fix] Inverting SSH access boolean for a Linodes Managed settings

packages/manager/src/components/TagsInput/TagsInput.test.tsx
1. Have `REACT_APP_API_ROOT='https://cloud.dev.linode.com/api/v4'`
2. Run `yarn test  packages/manager/src/components/TagsInput/TagsInput.test.tsx`
3. Should pass
=> Fix: Use Relative APP_ROOT path

packages/manager/src/features/Managed/EnableManagedPlaceholder.tsx
As per review feedback, change Managed placeholder text to exactly match Classic. There may be a further update from Marketing at some point, but for now it's always safe to stick with Classic.
=> update Managed placeholder/confirmation text to match Classic

packages/manager/src/components/BarPercent/BarPercent.test.tsx, packages/manager/src/components/BarPercent/BarPercent.tsx, packages/manager/src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx
=> M3-3174 Implement over limit quota visuals on Linode detail summary and dashboard

packages/manager/src/components/EntityIcon/EntityIcon.tsx, packages/manager/src/constants.ts, packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx, packages/manager/src/features/ObjectStorage/utilities.test.ts, packages/manager/src/features/ObjectStorage/utilities.ts, packages/manager/src/services/objectStorage/buckets.ts, packages/manager/src/types/ObjectStorage.ts
This still has a little way to go, but I thought it'd be wise to go ahead and get some feedback. Requested changes can go in this PR or another (since this is going to a feature branch).
This PR contains the basic mechanisms for "folder traversal" of a Object Storage bucket. 
There are three mechanisms used for folder traversal: **prefix**, **delimiter**, and **marker**.
In reality, a bucket is only capable of holding flat objects. For organization, objects can grouped together using a common prefix:
`my-folder/file1.txt`
`my-folder/file2.txt`
In this example, it would be appropriate to display these two objects as belonging to a folder called `my-folder`.
We can specify a `prefix` when hitting the `/object-list` endpoint. This ensures that all objects returned BEGIN with the provided …
=> OBJ-58 Part III: Folder Traversal

packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.test.tsx, packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu.tsx, packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
Add the cluster label to kubeconfig filename when downloading (e.g. `my-cluster-kubeconfig.yaml`)
=> LKE-783 Add cluster label to filename when downloading kubeconfig

packages/manager/src/containers/managedIssues.container.ts, packages/manager/src/containers/managedServices.container.ts, packages/manager/src/features/Managed/Monitors/HistoryDrawer.tsx, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.test.tsx, packages/manager/src/features/Managed/Monitors/MonitorActionMenu.tsx, packages/manager/src/features/Managed/Monitors/MonitorRow.tsx, packages/manager/src/features/Managed/Monitors/MonitorTable.tsx, packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx, packages/manager/src/features/Managed/Monitors/Monitors.tsx, packages/manager/src/services/managed/managed.ts, packages/manager/src/store/index.ts, packages/manager/src/store/managed/issues.actions.ts, packages/manager/src/store/managed/issues.reducer.ts, packages/manager/src/store/managed/issues.requests.ts, packages/manager/src/store/managed/managed.requests.ts, packages/manager/src/types/Managed.ts
Add services method, actions, requests, and reducer for Managed issues. Chose to use Redux for these because:
- It looks like they will be a major part of our upcoming Managed dashboard widget
- There will be some logic for iterating over the list of issues and fetching the corresponding support ticket for each to determine its status. Best to put this in one place.
There is a dummy drawer at /managed/monitors that is always open and will display the ids of returned issues. (prod-test-004 has a single issue available).
=> M3-692 Add: Redux boilerplate for Managed issues & issue drawer

packages/manager/src/components/SelectionCard/SelectionCard.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
This is an old regression from the last MUI update with tooltips.
Best way to test is cloning a linode and check a disabled card in the plan selection panel
=> M3-3095 Fix: Tooltip not showing for selection cards

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
A line of code passing the memory_limit to its text field had been commented out.
As a result, opening a config for editing didn't display the value, leading
users to think that their edits had not been saved.
No idea why this line was commented out in the first place; must have been a reason
but I hope it's no longer valid.
=> M3-3157 Fix: Config memory size limit not displayed

packages/manager/src/__data__/images.ts, packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx, packages/manager/src/components/ImageSelect/ImageSelect.tsx, packages/manager/src/containers/withImages.container.ts, packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
to reproduce:
1) trigger a resize or other long-lived event
2) go to create from distro and open the image select
3) navigate the options with your keypad
4) Observe: the cursor is reset every time a new event is received.
Used React.memo in ImageSelect to prevent these re-renders;
Also fixed a bug that was causing the /rebuild tab to crash. This was a leftover from the imagesByID pattern update that wasn't caught previously.
I'd love to have bugs like this caught before they go to production (as the first one did) or before they start Jenkins crashes (as the second one did). Unit tests probably won't do the trick. Open to discussion.
=> M3-3277 image select bug

packages/manager/src/components/EnhancedSelect/Select.styles.ts, packages/manager/src/components/EnhancedSelect/Select.tsx, packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx, packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx, packages/manager/src/components/ImageSelect/ImageSelect.tsx, packages/manager/src/themeFactory.ts
One could argue that anyone who triggers this deserves it, but might as well patch it up.
=> Fix overflow in react selects

packages/manager/src/features/Managed/Credentials/CredentialRow.tsx
This column was already in the table, but it was blank when the `last_decrypted` field was null. Now it will say "Never" in this case.
=> M3-3109 Change: Managed credential decryption field

packages/manager/src/components/TabbedPanel/TabbedPanel.tsx, packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx, packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
A recent change in tabbed reply introduced a regression on the create workflow page, this fixes it and cleans up the code for the support ticket tabbed reply comment field
=> M3-3281 Fix regression with tabbed reply and code cleanup

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
=> M3-3176 Hide active caret on mobile navigation

packages/manager/src/features/Domains/DomainsLanding.test.tsx, packages/manager/src/features/Domains/DomainsLanding.tsx
On the Domains landing page, users with no Linodes on their account should see a banner warning them that their DNS records are not being served. Restricted users can often not view the number of Linodes on the account, so to prevent the possibility of displaying inaccurate warnings, we don't show the banner to restricted users.
=> M3-2892 Change: Hide DNS banner warning for restricted users

packages/manager/src/components/PasswordInput/PasswordInput.tsx, packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx, packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
Add an eyeball to the password input when adding/editing a Credential
- Added an optional hideValidation prop to the PasswordInput,
bc for cases like credentials, the "password" field has been
defined elsewhere, and it could be any value. Validating using
standard password strength requirements doesn't seem very effective.
=> M3-3254 Change: Use PasswordInput component for Credential drawers

packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard.tsx
The previous logic assumed that all Managed users would have monitors on their account, which obviously is not a safe assumption. 
Load the dashboard, then (without reloading) block requests to /managed. Also for completeness you can try the other way around, load the page with /managed blocked then unblock it.
=> Use safer check for the Managed dashboard card error state

packages/manager/src/store/regions/regions.actions.ts, packages/manager/src/store/regions/regions.reducer.test.ts, packages/manager/src/store/regions/regions.reducer.ts
Trying to unify our Redux patterns, so they're less confusing for new devs.
At the same time trying to keep these PRs relatively small, so this only updates:
- regions
- images
There's a discussion to be had about whether to enforce EntityError state for all Redux entities (for consistency and so you don't have to look up what an entity's error state will look like). OTOH, since we don't update, create, or delete regions through redux, it's kind of wasteful.
=> TDT: redux refactors

packages/linode-js-sdk/src/firewalls/firewalls.ts, packages/linode-js-sdk/src/kubernetes/kubernetes.ts, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, packages/manager/src/containers/firewalls.container.ts, packages/manager/src/features/Firewalls/FirewallLanding.tsx, packages/manager/src/layouts/Logout.tsx, packages/manager/src/store/authentication/authentication.requests.ts, packages/manager/src/store/bucket/bucket.actions.ts, packages/manager/src/store/domains/domains.actions.ts, packages/manager/src/store/firewalls/firewalls.actions.ts, packages/manager/src/store/firewalls/firewalls.requests.ts, packages/manager/src/store/kubernetes/kubernetes.requests.ts, packages/manager/src/store/kubernetes/nodePools.requests.ts, packages/manager/src/store/linodes/config/config.requests.ts, packages/manager/src/store/linodes/disk/disk.requests.ts, packages/manager/src/store/linodes/linode.requests.ts, packages/manager/src/store/nodeBalancer/nodeBalancer.requests.ts, packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.requests.ts, packages/manager/src/store/notification/notification.requests.ts, packages/manager/src/store/preferences/preferences.requests.ts, packages/manager/src/store/profile/profile.requests.ts, packages/manager/src/store/store.helpers.ts, packages/manager/src/store/types.ts, packages/manager/src/store/volume/volume.actions.ts, packages/manager/src/store/volume/volume.events.ts, packages/manager/src/store/volume/volume.reducer.ts
Adds better typing, so we can type the parameters that are getting passed to action creators through `createRequestThunk`
I recommend hovering over multiple places where `dispatch(someAction())` is happening to make sure the param typings are correct.
If types weren't explicitly passed in the actual action creator type arguments, then it will remain a `any?` but otherwise should be typed correctly.
=> Change: Update Typings for Thunk Action Creators

packages/manager/src/components/EnhancedSelect/Select.styles.ts
=> M3-3343 Fix overflow-x in select drop downs on compact mode

packages/manager/src/components/EnhancedSelect/Select.tsx, packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
console warning: `Found 2 elements with non-unique id #react-select-2-input:`
at /linodes/create
=> M3-3340 Fix: duplicate ID for react-select

packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
One-word change to sort support tickets by date opened (instead of updated). There was a bug in the API that prevented this ordering from being honored, but it has been fixed and will go out in the next release.
=> M3-2436 Change: Sort support tickets by order created

packages/manager/src/features/ToastNotifications/ToastNotifications.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx, packages/manager/src/store/linodes/disk/disk.actions.ts, packages/manager/src/store/linodes/disk/disk.reducer.ts, packages/manager/src/store/linodes/linodes.events.ts
We had previously been doing a client side check to disallow deleting
a disk on a Linode that is running. However, this is too restrictive;
deleting a disk is possible as long as the disk is not in use
(that is, it's not associated with the config profile that booted
the Linode).
It turns out that proper validation here is impossible, so we're going
to allow deletions on any disk, and rely on the error event to let users
know that it failed. This involves creating a new Redux action to
update the linodeDisks.error.delete error field, and adding logic
in linode.events to trigger this action as well as refresh disk state.
We also send a toast notification if the user is still on the disks menu
when this happens.
I'm not thrilled about this UX. We could try something more complicated like …
=> M3-3216 Allow deletion of disks on active Linodes

packages/manager/src/constants.ts, packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx, packages/manager/src/types/ObjectStorage.ts
The API returns a `200` when creating a new bucket with the _same name of a bucket you already own in the same cluster._
We can prevent the user from doing this by looking at the buckets they already own. 
Also in this PR:
- Support for `us-east` cluster
- Display "Region" instead of "Cluster" in the Add Bucket drawer.
**To test:**
- Run the new unit tests: `yarn run test packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx`
- Create buckets with names of buckets you _do not_ own (happy path)
- Try to create buckets with names of buckets that you already own.
- Try to create buckets with names of buckets that you _do not_ own, but other people do (e.g. `test`, `jc1`).
=> OBJ-225 Don't allow duplicate bucket names

packages/linode-js-sdk/src/firewalls/types.ts, packages/manager/src/__data__/firewalls.ts, packages/manager/src/features/Firewalls/FirewallTableRows.tsx, packages/manager/src/store/firewalls/firewalls.reducer.ts
API is removing the `sequence` key from the list of firewall rules. This means that _when we support drag-and-drop sorting_, we'll need to send the ENTIRE list of firewall rules back in a specific order, rather than explicitly specifying what sequence they should be ordered in.
Most object properties with the except of a few (such as `Object.keys`) will retain the order properly, but this PR serves as more of an escape hatch. Drag-and-drop sorting isn't planned for MVP, but in attempts to make this feature more future-proof, I've opted to add the `sequence` key at the time the data is stored in Redux.
=> Change: Firewall Interface

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, packages/manager/src/themeFactory.ts
This work adds a height to table row for Resize so all rows will be a consistent size as well as adjustments to chip label styles to accommodate for Firefox.
Please view in multiple browsers and places where the chip component is used in such as tags panel on linode detail, the beta tag on OCA create flow, and the 'current plan' chip on resize.
=> M3-3341 Firefox styles for chip and tags

packages/manager/src/constants.ts, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
This PR adds tax id for Australian customers to invoices.
To test, update country in contact information to be Australia, and download a PDF to view the tax id.
=> M3-3274 Add Australian ARN to Invoices for Australian Customers

package.json
Currently, there exists an issue for first-time starters of the monorepo in that when you run `yarn up`, both Cloud and the SDK are started in parallel, but Lerna exposes no good way to have 1 package depend on the other, so they both start ASAP.
The problem is that the SDK almost always builds after the Cloud process has started, so when first upping the projects, you get _a lot_ of console errors that it couldn't find assets located in `linode-js-sdk/lib`.
This is especially a problem for Docker because every time you start the docker container, it's building the monorepo from scratch, so these console errors are unavoidable.
The actual solution is hopefully going to be posted [here](https://github.com/lerna/lerna/issues/2260), but in the meantime I've added a command for Docker …
=> Add: Docker-Specific Start Command

packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx, packages/manager/src/features/OneClickApps/FakeSpec.ts, packages/manager/src/features/OneClickApps/TipSection.tsx
This adds the info panel for the Plesk OCA. It also adds a **Tips** section, which will hopefully allow us to move any simple configurations directly to manager, as opposed to redirecting users to external resources. (The whole panel should probably be reworked a little to include markdown)
Also, **Guides** will no longer display if there are no guides in the `FakeSpec`
=> OCA Add: Plesk info panel and a Tips section

packages/manager/src/constants.ts, packages/manager/src/features/Longview/LongviewLanding.tsx, packages/manager/src/features/Longview/longviewRequests.ts
Plenty more to do here but I wanted to get feedback before going much further. I'm hoping to get some tests for these, but mocking the setup through Axios has been tricky.
New content is in features/longview/longviewRequests.ts.
If you log in as prod user 004 and go to /longview, a few demo requests will be made and logged to the console.
=> Add: Types and helper methods for working with the Longview API

packages/manager/src/featureFlags.ts, packages/manager/src/features/StackScripts/stackScriptUtils.ts, packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
We need a way to prevent new One-click StackScripts from being shown as options to the user before we have a chance to provide app details and logo icons for the new app. 
This PR attempts to use feature flags. Basically, we start with a hard-coded list of OCAs in `stackScriptHelpers.ts`. Any apps returned from the LD `oneClickApps` flag are appended to this list, and then the GET /stackscripts response is filtered to only include apps in the combined list.
I chose to hard-code the "basic" apps within Cloud bc LD doesn't seem to provide a way to extend flag variations, so there's no way to say "show this user the basic apps PLUS these two", each new variant would have to be a full list.
To test, delete the ARK entry in the baseApps variable in …
=> OCA Add: feature flags

packages/linode-js-sdk/src/managed/managed.ts, packages/linode-js-sdk/src/managed/types.ts
Uses the secret Managed/stats endpoint to retrieve summary data for a Managed user's account.
There isn't documentation for this endpoint yet, so I'm basing this shape off of:
`curlp managed/stats | jq 'keys'`
`curlp managed/stats | jq '.data | keys'`
....and some console logging.
=> Add Managed stats SDK method and types

packages/linode-js-sdk/src/domains/types.ts, packages/manager/src/containers/domains.container.ts, packages/manager/src/features/Domains/DisableDomainDialog.tsx, packages/manager/src/features/Domains/DomainActionMenu.test.tsx, packages/manager/src/features/Domains/DomainActionMenu.tsx, packages/manager/src/features/Domains/DomainTableRow.tsx, packages/manager/src/features/Domains/DomainsLanding.tsx, packages/manager/src/features/Domains/ListDomains.tsx, packages/manager/src/features/Domains/ListGroupedDomains.tsx, packages/manager/src/features/Domains/SortableTableHead.tsx, packages/manager/src/utilities/ga.ts
Gives the user the ability to either enable or disable domain status. This does not recognize the possibility of a zone being in `has_error` or `edit_mode` status. If it's in either of these statuses, the only option is to disable. You can then enable again after the zone is disabled.
Also adds status as a table column.
=> Add: Ability to Edit Domain Status

packages/manager/patches/chart.js+2.7.3.patch
Upgrades ChartJS to fix issue with tooltips not respecting the time offset.
`yarn clean && yarn up` <---- important
In develop, set your timezone to GMT, look at your graphs and notice the tooltip datetime doesn't match up wit the X-Axis
And then try it again in this branch.
=> Change: Upgrade ChartJS

packages/manager/src/components/ActionMenu/ActionMenu.spec.js, packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx, packages/manager/src/components/Drawer/Drawer.tsx, packages/manager/src/components/Drawer/index.ts, packages/manager/src/components/EnhancedSelect/EnhancedSelect.spec.js, packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.tsx, packages/manager/src/components/IPSelect/IPSelect.tsx, packages/manager/src/components/TagsInput/TagsInput.spec.js, packages/manager/src/components/TextField.tsx, packages/manager/src/components/core/Divider.ts, packages/manager/src/components/core/Divider.tsx, packages/manager/src/containers/withLinodes.container.ts, packages/manager/src/features/Firewalls/AddFirewallDrawer.tsx, packages/manager/src/features/Firewalls/FirewallLanding.tsx, packages/manager/src/features/Volumes/VolumesLanding.tsx, packages/manager/src/store/linodes/linode.requests.ts, packages/manager/src/store/linodes/linodes.actions.ts, packages/manager/src/store/linodes/linodes.reducer.ts
Adds the fields and buttons for the _create firewall_ drawer
I also did a couple other things
1. Updated the `withLinodes` container to follow new patterns and get better typing
2. Allowed for putting the `helperText` copy at the top of a `<TextField />` because the Firewall designs have the helper copy on top. This is inconsistent with the rest of the site, though, so we might end up putting the copy on the bottom.
=> Add: Create Firewall Drawer

packages/manager/src/features/Managed/SSHAccess/LinodePubKey.tsx
Adds a copied indicator when the user pushes the Linode SSH Key _Copy to Clipboard_ button.
=> Change: Add Copied Indicator to SSH Key Button

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/services/objectStorage/buckets.ts
Recall that we were doing two hacks to help with OBJ pagination:
- Sorting the object list and using the name of the last file as a marker to get the next page.
- Assuming we've gotten all objects if the number of objects returned is less than the number we requested.
The API is now returning `next_marker` and `is_truncated` on the `/object-list` response. This means we can remove these hacks.
Look through buckets with many files to test. Feel free to use prod account 9, bucket name jc2 to see Cloud source code.
=> OBJ: Use API response for pagination

packages/manager/src/__data__/buckets.ts, packages/manager/src/constants.ts, packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx, packages/manager/src/services/objectStorage/buckets.ts, packages/manager/src/store/bucket/bucket.reducer.ts, packages/manager/src/types/ObjectStorage.ts, packages/manager/src/utilities/ga.ts
API is removing:
- bucket.region
- bucket.size
- bucket.objects
- The ability to force delete buckets (so we can no longer delete non-empty buckets)
Because of this, we need to:
- Remove "Size" column from Buckets Landing
- Remove "Objects" column from Buckets Landing
- Change deletion confirmation text so that we don't reference the objects and size
We should also probably add some helper text before attempting to delete a bucket, letting the user know the bucket needs to be empty first, but I'm waiting to hear from Jay about this. The API _does_ return a helpful message, so at least there's that.
In Charles, …
=> Updates for breaking API OBJ changes

packages/manager/src/components/TextField.tsx, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
- Keep the cell height consistent between modes in the edit Node Pools table
- Adjusted TextField styling (a margin was pushing the field down even when a label wasn't specified)
- Added handling for nodebalancer_node_delete events, which apparently exist.
=> LKE 938: Fix cell height when not in Cluster edit mode

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx, packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx, packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx, packages/manager/src/features/ObjectStorage/ObjectUploader/reducer.test.ts, packages/manager/src/features/ObjectStorage/ObjectUploader/reducer.ts, packages/manager/src/features/ObjectStorage/utilities.ts, packages/manager/src/hooks/usePrevious.ts, packages/manager/src/types/ObjectStorage.ts, packages/manager/src/utilities/ga.ts
This PR makes it possible to upload multiple files at once.
It's possible to drop up to 100 files at a time,  but the uploads are batched, with a max of 25 parallel uploads at a time (feedback appreciated on these numbers).
Since the DOM is being updated rather frequently, there are many performance considerations that have gone into this. This informed the shape of the data structures used in the reducer, as well as which values are memoized. Feedback is greatly appreciated in this regard.
Here's how this component works:
1. Files are dropped in the upload area (e.g. `file1` and `file2`).
2. The `onDrop()` function is called. An action is dispatched, which sets the status of these files to `QUEUED`.
3. Because the number of queued files has changed, the memoized value `nextBatch` is …
=> OBJ-247 Simultaneous file uploads

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx, packages/manager/src/features/ObjectStorage/utilities.test.ts, packages/manager/src/features/ObjectStorage/utilities.ts
This PR fixes a bug where successfully uploaded objects might not appear in the correct place in the Object Table once the upload was successful.
**To test:**
Look at the new unit tests to see how the helper functions should behave.
While object uploads are in progress, navigate to different directories in your bucket. The newly uploaded objects should only appear if they belong in a directory you're currently viewing.
Try uploaded whole folders, duplicates, etc. Compare with a tool like CyberDuck to make sure the uploads ended up in the correct place. Refresh the page, download, delete files, etc.
=> [For release] Fix bug with table updates

packages/manager/src/components/ActionMenu/ActionMenu.tsx, packages/manager/src/features/Events/EventsLanding.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx, packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx, packages/manager/src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx, packages/manager/src/features/StackScripts/stackScriptUtils.ts, packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx, packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/hooks/useAPIRequest.ts, packages/manager/src/layouts/OAuth.test.tsx, packages/manager/src/services/objectStorage/buckets.ts, packages/manager/src/services/objectStorage/clusters.ts, packages/manager/src/store/image/image.actions.ts, packages/manager/src/store/image/image.requests.ts, packages/manager/src/types/index.ts
Deprecates `Linode.ResourcePage` along with some other leftover namespace items.
`Linode.TodoAny` was supposed to be a marker to let the devs know to go back and re-type it later, but realistically nobody is going to actually do that.
=> Change: Deprecate Linode.ResourcePage

packages/manager/src/components/EnhancedSelect/Select.styles.ts, packages/manager/src/components/EnhancedSelect/Select.tsx, packages/manager/src/components/TextField.tsx
Recently, we made a change to the textfield prop to stop using the built-in `label` prop and instead use the `<InputLabel />` component. This caused a visual bug where if a TextField was being wrapped in `<FormControl />` component, it was picking up a `transform` style that was putting the label underneath the actual TextField.
This PR removes that `transform`
Look at Selects and TextFields around the app. Some affected fields included the `<LinodeConfigDrawer />` and the `<APITokenDrawer />`.
Before: 
After:
=> Fix: TextField Styles

packages/manager/src/eventMessageGenerator.ts
- consistency for "was" VS "has been"
=> M3-3288 Update copy for boot jobs in activity feed

packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
Someone reported that their node status display was off (`17 (0 up, 14 down)`). It's not entirely clear what caused that case, but since those numbers are based off of different sources (`count` from the API vs. a sum of all the node pool statuses) it's possible that they'll diverge. If they're different, we can show helper text asking the user to open a support ticket.
You may have to mess with the logic to see the tooltip, since normal cluster creation and node pool editing don't seem to reproduce the reported issue.
=> LKE 775 Add helper text if not all nodes are accounted for

packages/linode-js-sdk/src/firewalls/firewalls.ts, packages/linode-js-sdk/src/firewalls/types.ts, packages/manager/src/__data__/firewallDevices.ts, packages/manager/src/__data__/firewalls.ts, packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.ts, packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallTableRows.tsx, packages/manager/src/store/firewalls/firewalls.reducer.test.ts
Firewall devices are no longer included in the `GET /firewalls` request, so we need to make a `GET /firewalls/$id/devices` request for each firewall.
=> Change: Request Firewall Devices on Mount

packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/DestructiveSnapshotDialog.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
For manual snapshots, we will now present a dialog to allow the user to confirm/cancel that they want to proceed with the new snapshot and inform them they will lose their previous snapshot. 
Please test creating various snapshots and verifying errors (one way is to try creating a snapshot while one is already in progress)
Also, does this make sense as a dialog? The requested copy from classic seems to fit our dialog pattern, but maybe a warning notice is all that is needed. Let me know what you think!
=> M3-3228 Add warning when user creates a new snapshot

packages/manager/src/features/Longview/AddClientDrawer.tsx, packages/manager/src/features/Longview/LandingContent.tsx, packages/manager/src/features/Longview/LongviewDeleteDialog.tsx
Adds the Dialog to delete a Longview Client
Also adds a `<form>` element to the _add drawer_ so that users can hit the _enter_ key on the textfield.
=> Add: Longview Client Delete Dialog

packages/linode-js-sdk/src/linodes/types.ts, packages/manager/src/__data__/linodes.ts, packages/manager/src/containers/withMostRecentBackup.container.ts, packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/linodes/LinodesLanding/ListView.tsx, packages/manager/src/features/linodes/LinodesLanding/requestMostRecentBackupForLinode.ts, packages/manager/src/store/linodes/linodes.helpers.test.ts, packages/manager/src/store/linodes/linodes.helpers.ts, packages/manager/src/store/linodes/linodes.reducer.ts, packages/manager/src/store/linodes/types.ts, packages/manager/src/store/selectors/getSearchEntities.ts
The following properties were being added to the Linode object by Cloud Manager, but not actually included in the `GET /linodes` API response:
* `mostRecentBackup`
* `notifications`
* `recentEvent`
* `notification`
To keep the SDK pure, we need to remove those typings from the base `Linode` interface.
Other changes include:
*  make `linode.ipv6` possibly `null`.
* Add `gpus` to the `Linode.specs` object
Look around the app - ensure nothing crashes
=> [SDK] Change: Refactor Linode Types

packages/manager/src/components/GaugePercent/GaugePercent.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/common.ts, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewTable.tsx
This PR adds `<GaugePercent />` components with dummy data. 
Each of these components will get their own data and manage loading, error states, etc.
I thought about making _one_ `<LongviewGauge />` component that takes a `getData` prop to do its data fetching/manipulation.... but I think it makes since to start with the super verbose version. If we want to eventually combine components, we can do it later.
**NOTE:** Mobile styling doesn't exist yet. Not sure if this has been decided on.
=> LV: Add <GaugePercent /> components on Landing

packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, packages/manager/src/themeFactory.ts
This PR addresses 2 separate issues; please see tickets for more details.
• On Nodebalancer create workflow under 'Backend Nodes' selection, if the linode label was a bit longer it was wrapping weirdly. Now the label is display blocked on its own line.
• The other issue was occurring on Firefox mobile screen sizes. On dashboard, Nodebalancer links were pushing the table and not wrapping as expected. 
=> M3-2042 & M3-3296: Nodebalancer create- label wrapping issue & Dashboard FF mobile issue

packages/manager/src/components/GaugePercent/GaugePercent.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewTableRows.tsx, packages/manager/src/hooks/usePrevious.ts
Adds logic to the Longview Load gauge.
Load of 1 === 100% CPU utilized.
=> Add: Longview Load Gauge

packages/manager/src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx
The Blog RSS feed url needed to be updated to linode.com/blog/feed, where the XML is located.
=> M3-3411 Change dashboard feed links

packages/manager/src/components/EntityIcon/EntityIcon.tsx, packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx, packages/manager/src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx, packages/manager/src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx, packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx, packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx, packages/manager/src/features/Dashboard/VolumesDashboardCard/VolumesDashboardCard.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeCard.style.ts, packages/manager/src/features/linodes/LinodesLanding/LinodeCard.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/linodes/LinodesLanding/ListView.tsx, packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx, packages/manager/src/store/linodes/types.ts
We've gotten report that many users like to see the maintenance status without having to open a tooltip. The display was a bit of an issue but this POC offers a way to improve the layout. This was also added to the dashboard
In addition to this I fixed the sorting that was broken (we can now sort with maintenance statuses)
=> M3-3412 Improve display of status maintenance in linode row

package.json, packages/linode-js-sdk/package.json, packages/linode-js-sdk/yarn.lock, packages/manager/package.json, packages/manager/yarn.lock, yarn.lock
Yarn Audit Vulnerability review
Ran yarn audit on main repository
See https://yarnpkg.com/lang/en/docs/cli/audit/
Handlebars has issues:
```bash
yarn audit v1.17.3
│ high          │ Prototype Pollution                                          │
│ Package       │ handlebars                                                   │
│ Patched in    │ >=4.3.0                                                      │
│ Dependency of │ lerna                                                        │
│ Path          │ lerna > @lerna/changed > @lerna/version >                    │
│               │ @lerna/conventional-commits > conventional-changelog-core >  │
│               │ conventional-changelog-writer > handlebars                   │
│ More info     │ …
```
=> fix vulnerability on manager packages

packages/manager/e2e/config/custom-commands.js, packages/manager/e2e/pageobjects/nodebalancers.page.js, packages/manager/e2e/pageobjects/page.js, packages/manager/e2e/specs/nodebalancers/configurations.spec.js, packages/manager/e2e/specs/nodebalancers/error-handling.spec.js, packages/manager/e2e/specs/nodebalancers/list.spec.js, packages/manager/e2e/specs/nodebalancers/settings.spec.js, packages/manager/e2e/specs/nodebalancers/smoke-create.spec.js, packages/manager/src/components/TextField.tsx
*Skipped all non smoke tests
*Fixed the nodebalancer smoke test
*Fixed the detail-add-records test
*Added better selector values for textfield component
unfortunately all of these tests needed to be skipped and then refactored. Only the smoke test is currently working.
1. `cd packages/manager`
2. `yarn up`
3. `yarn selenium`
4. `yarn e2e --dir nodebalancers`
It is still good to validate that all the tests but the smoke test are skipped and not causing a failure.
Single tests can be run with:
`yarn e2e --file …
=> M3-3379 update nodebalancers specs

packages/linode-js-sdk/src/domains/types.ts, packages/manager/src/__data__/domains.ts, packages/manager/src/features/Domains/DomainRecordDrawer.tsx, packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.test.tsx
`zonefile` is not a property returned from GET `/domains` so we remove it.
=> [SDK] Change: Removes Zonefile from Domain Typings

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx, packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
This PR updates several documentation links in Object Storage, since some new guides have been published. New links can be found in the following places:
- Bucket Landing Page
- Documentation Button (top-right, on all pages)
- Delete Bucket modal.
Prod test account 1 doesn't have any buckets, so you can easily see the landing page. To see the Delete modal, add a bucket (but don't upload any objects) click "Delete" in the action menu on the Buckets Landing.
=> OBJ-257 Update Documentation Links

packages/manager/src/components/Notice/Notice.tsx
The Important Error notice styling was off in the Volumes creation drawer for restricted users (likely that this issue was happening elsewhere as well). I think eventually combining the icon + border into one element may be a future improvement that would help make the styling a little more predictable, but this should suffice in the short-term.
Please view a variety of important notices in both regular and compact theme views:
• Volumes creation drawer (for users restricted from creating volumes)
• Maintenance banner on dashboard
• Stories for `Notice`
=> M3-3473 Styling regression on Important Error notices

packages/manager/src/store/domainDrawer/index.test.ts, packages/manager/src/store/domainDrawer/index.ts
domainsDrawer was using an old `actionCreator` function that wasn't type-safe or consistent with the pattern of volumesDrawer. This updates domainsDrawer to utilize `actionCreatorFactory` instead of the old function.
Please make sure there aren't any regressions to the domains drawer and that the `Create Domain` analytics are working as expected.
=> M3-3453 Update domainsDrawer reducer to use similar pattern as volumesDrawer reducer

packages/manager/config/testSetup.js, packages/manager/src/containers/kubernetes.container.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx, packages/manager/src/store/kubernetes/kubernetes.actions.ts, packages/manager/src/store/kubernetes/kubernetes.reducer.test.ts, packages/manager/src/store/kubernetes/kubernetes.reducer.ts, packages/manager/src/store/kubernetes/kubernetes.requests.ts
- Update kubernetes.container and typing to use updated patterns
- Add requestClusterActions and reducer handling
- Update kubernetes.reducer to use immer
- Use API error message (rather than generic) on error state for ClusterDetail
- Add a mock to setupTests.js to clear up a console error
Visit the cluster detail link for a cluster that you don't own or doesn't exist. You should see a "Not found" message. The rest of the LKE section should work as before despite refactors.
We don't seem to have a pattern for handling getOne errors in Redux. I used errors.read since that's what we're doing, but open to suggestions.
=> Fix: No error handling for 404's on kubernetes/clusters/:clusterID

packages/manager/src/features/Profile/APITokens/APITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx, packages/manager/src/features/Profile/APITokens/APITokenTable.tsx, packages/manager/src/features/Profile/APITokens/APITokens.test.tsx, packages/manager/src/features/Profile/APITokens/utils.test.ts, packages/manager/src/features/Profile/APITokens/utils.ts
⚠️This should be feature flagged OFF until Object Storage GA. ⚠️ 
This PR adds Object Storage to the list of scopes when creating a PAT. This issue was brought to our attention here: https://github.com/linode/linode-cli/issues/142
This required changing the APIToken utility functions to take in `perms` as an argument, since the list of scopes is no longer static. In my opinion, we should keep this pattern around even after OBJ GA, since we might need it for other kinds of scopes in the future.
I also noticed and fixed a bug where we were allowed users to attempt to rename …
=> OBJ-253 Add Object Storage to list of PAT scopes

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx, packages/manager/src/services/objectStorage/objects.ts
This PR takes advantage of the new "content_disposition" option in the /object-url endpoint so that the resulting URL will have a `Content-Disposition` header. Set to `attachment`, this will force a browser download.
=> M3-3384 Force object downloads

packages/manager/src/utilities/storage.ts
This seems to have already been done, but I removed the references to VAT within storage.ts since they're not being used anywhere within the app. 
Please test to make sure this doesn't introduce any regressions.
=> M3-2983 Replace VAT Notification Preference with User Preference Impl

packages/linode-js-sdk/src/kubernetes/kubernetes.schema.ts, packages/linode-js-sdk/src/kubernetes/types.ts, packages/manager/src/__data__/kubernetes.ts, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
Removing references to tags within the LKE flow, as the ability to edit tags for clusters will not be implemented for beta.
Please verify that there are no regressions to the LKE create flow + details page. 
cc @asauber
=> LKE-987 Hide the ability to tag clusters in Cloud Manager

packages/manager/package.json, packages/manager/testServer.js, packages/manager/yarn.lock
solve the vulnerability of subtext yarn audit by upgrading hapi test server to moder version
=> fix vulnerability by upgrading to @hapi/hapi

packages/manager/src/MainContent.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketDrawer.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketDrawer.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx, packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
This PR accomplishes two things:
1. Show "Object Storage" in Primary Nav for all users (behind `object-storage` feature flag).
2. Display Object Storage feature to restricted users.
Previously we were looking at `account.capabilities` to determine whether to show Object Storage in Primary Nav. This works for account owners, but in order show Object Storage to restricted users, we need to include it in the Primary Nav by default (since we don't have access to `/account` for restricted users). This will currently be hidden behind the `object-storage` feature flag.
Restricted users currently can't use Object Storage. This PR makes it so that restricted users can see everything within the feature, with notices explaining they need to contact an account admin (following the pattern we have …
=> OBJ-242 [OBJ] Primary Nav and Restricted Users

packages/linode-js-sdk/src/account/types.ts, packages/manager/src/__data__/account.ts, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx, packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx, packages/manager/src/features/ObjectStorage/utilities.test.ts, packages/manager/src/features/ObjectStorage/utilities.ts
**[USE DEV]**
This PR makes use of the new `object_storage` attribute on `/account/settings`. This attribute will be: `active`,  `disabled`, or `suspended`.
If a user attempts to create a bucket or create an access key, we display a confirmation modal first (because these actions result in new charges on their account).
TODO: 
Currently the new attribute works only in dev. Use Charles to change the value of `object_storage`.
Test that the Create Bucket and Create Access Forms work as expected. The form should be validated _before_ the confirmation modal appears.
=> OBJ-263 Confirm OBJ before adding a bucket or access key

packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Last Updated State in the Longview Row component was only being set if it differed after the API request finished. But because API will return a `lastUpdated` of `0` if the Longview has no client installed, then we need to differentiate between `undefined` and `0` on the client.
=> Fix: Gauge Last Updated Logic

packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
NodeBalancer inputs regressed and lost a prop that removed the top margin, causing misalignment. This PR adds that back as well as a small margin adjustment.
=> M3 NodeBalancer Input Fixes

package.json, packages/manager/src/__data__/longview.ts, packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.test.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/request.ts
🚨  This code got a little muddy. I think in follow up PR, I'm going to add logic to the Gauge to say
`if (value === 0 && max === 0) { max = 1 }`
so that we end up with a full grey bar if the stat is actually sitting at 0. [See this commit in the next upcoming PR](https://github.com/linode/manager/pull/5619/commits/969046ebfe509caa86abd5acec9606b32cdd461f) 🚨 
Adds Longview Memory Gauge
I tried deleting my swap disk and seeing the dataset that is returned from the Longview API. It appears that if you don't have a certain disk, the response will still return the same keys but just have a value of `0`.
I also initialized all values as `undefined` so that `value || 1` logic isn't applied when a value is actually `0`.
=> Add: Longview Memory Gauge

packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
Submitting the Create Access Key form with the 'Enter' key caused the confirmation modal to be accepted as well.
The diff is not helpful here.... I just removed the `<form>`.
This means the form cannot be submitted with the 'Enter' key, unless you tab to it.
Please describe the tests that you ran to verify your changes. Provide instructions so …
=> [hotfix] Remove Form on Access Key Drawer

packages/manager/src/components/GaugePercent/GaugePercent.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx
Puts the responsibility on the `<Gauge />` component to figure out a logical default for max.
So basically if `max` and `value` are both `0`, `max` will default to `1` so that we end up with a completely grey gauge.
=> Change: Gauge Refactor

packages/linode-js-sdk/src/regions/types.ts, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
We were previously displaying all DCs as available in k8 creation, however if you tried to create a cluster in a DC without LKE capability, it would throw an error. Now we filter based on capability so users won't be able to attempt an action that will only result in error. 
Please test (for now) using staging.
=> LKE-1065 Cloud Manager filters regions to only those regions that have LKE

packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.test.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/request.ts, packages/manager/src/features/Longview/request.types.ts
This PR includes the storage gauge for the Longview overview page. Follows the same pattern as the CPU gauge.
New utility function with unit tests to sum storage.
- Non breaking change ('update', 'change'
=> Me-3430 [LV]:  Storage Gauge

.travis.yml, packages/manager/e2e/config/selenium-config.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail-backups.page.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail-networking.page.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail-rebuild.page.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail-volume.page.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail.page.js, packages/manager/e2e/specs/linodes/detail/backups-create.spec.js, packages/manager/e2e/specs/linodes/detail/backups.spec.js, packages/manager/e2e/specs/linodes/detail/create-volumes.spec.js, packages/manager/e2e/specs/linodes/detail/ip-transfer.spec.js, packages/manager/e2e/specs/linodes/detail/networking-allocate-ip.spec.js, packages/manager/e2e/specs/linodes/detail/networking-ip-sharing.spec.js, packages/manager/e2e/specs/linodes/detail/networking.spec.js, packages/manager/e2e/specs/linodes/detail/rebuild.spec.js, packages/manager/e2e/specs/linodes/detail/rescue.spec.js, packages/manager/e2e/specs/linodes/detail/resize.spec.js, packages/manager/e2e/specs/linodes/linode-no-image.spec.js, packages/manager/e2e/utils/common.js, packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx, packages/manager/src/components/Drawer/Drawer.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
**Updated all of the syntax for the linode details specs**
Updated networking spec and backups for syntax
* networking spec is still a little iffy. It tends to fail every other time need to look into why this is not stable.
* added another more info to data-qa-type attrib is now using {ip.type}. This allows us to more easily get to the IPV4 or IPV6 address types
* updated chrome webdriver (actually pushed by the company jamf update needing to update chrome)
* Updated the syntax for the backups-create spec only one test passing right now.
Backups-create spec issues
* Unsure of the reason right now but a simple backup seems to get hung up around 97% and takes over 5 minutes to get there. The test is only waiting for 5 minutes but even waiting for about 10 minutes it doesn't finish. This …
=> M3-3380 Updated syntax for linode details specs

packages/linode-js-sdk/src/account/account.schema.ts, packages/linode-js-sdk/src/account/types.ts, packages/manager/src/features/Billing/BillingPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx
Making the CVV code required on the Update Credit Card panel under /account/billing. 
=> M3-3369 Make CVV required on Update Credit Card Panel

packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
Opts to set errors on gauges if that data hasn't resolved at least once. We choose not to do checking on the actual value of the gauge because `0` is a valid value and `0` evaluates to `false`, so we need to set errors only if we don't already have data.
Ensure your Longview client successfully recovers from an error -> data state.
Ensure your Longview client does not error out if it's already been supplied with data at least once.
=> Change: Sets Error On Gauges

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
At 1280 screen width, the Kubeconfig buttons were overflowing their container. I bumped up the breakpoints so the buttons stay wrapped until the xl breakpoint. 
=> M3-3482 Kubeconfig View button overflow at 1280 width

packages/manager/src/components/Breadcrumb/Breadcrumb.tsx, packages/manager/src/components/Breadcrumb/Crumbs.tsx, packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
Stackscripts breadcrumb display was causing a test to break because we were capitalizing the crumb label with CSS. This adjusts that, the spacing of the 3rd slash if there are 3 crumbs, and an alignment issue I noticed on smaller screens for breadcrumb labels that weren't editable. 
Please take a look at Stackscripts detail page, as well as other places with 3+ crumbs (ex. User details), editable vs non-editable crumb labels, etc.
=> M3-3509 Stackscripts breadcrumb display issue

packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.test.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
Preloads disks into the device selects when visiting the Rescue tab. The ticket title implies that we should get the disks from the Linode's active Config, but it turns out that this isn't what Classic does. Classic's behavior is weirder: it maps all of your disks to the available slots until you run out of either disks or slots. Fortunately, this is much easier for us than figuring out which config profile was booted most recently, which would involve requesting events for this Linode and finding the most recent boot or reboot event.
=> M3-3179 preload disk assignments on rescue tab

packages/linode-js-sdk/src/account/types.ts, packages/manager/src/__data__/events.ts, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/features/Events/Event.helpers.test.ts, packages/manager/src/features/Events/Event.helpers.ts, packages/manager/src/features/Events/EventRow.test.tsx, packages/manager/src/features/Events/EventRow.tsx, packages/manager/src/features/Events/EventsLanding.test.ts, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx, packages/manager/src/features/linodes/transitions.test.ts, packages/manager/src/store/events/event.helpers.test.ts, packages/manager/src/store/events/event.reducer.test.ts
Update eventMessageGenerator to show which config is associated with `linode_boot` and `linode_reboot` events. The exact syntax is up for debate (other options include "Linode my-linode has been booted with my-config by prod-test-004), please weigh in.
There's a ton of other stuff we can do in this file now that we have secondary entities, but afaict the other boot events e.g. `lassie_reboot` don't have them (I'm asking the API team for confirmation).
I also cleaned up some of the messaging, we were getting things like "Linode my-linode has been booted by the Lassie watchdog service by Linode" and "Linode my-linode is booting by Linode".
Boot and reboot things with different config profiles.
=> M3-3011 show booted config

packages/manager/e2e/pageobjects/list-stackscripts.page.js, packages/manager/e2e/specs/stackscripts/edit-existing-stackscript.spec.js, packages/manager/e2e/specs/stackscripts/list-stackscripts.spec.js, packages/manager/e2e/specs/stackscripts/stackscript-detail.spec.js
Updated edit-existing-stackscript spec file
* file is linted and syntax has been updated
* this spec will need to be refactored as the functionality has changed
Updated list-stackscripts spec
* removed last test as functionality has changed and test can be refactored
* All tests passing
Updated stackscript-detail spec
* All tests skipped as they need to be refactored
1. `yarn up`
3. `yarn e2e --dir stackscripts`
Only one spec file actually runs tests and passes. Takes about 1 minute to run. This should be an easy pass through.
=> M3-3382 Updated syntax for stackscripts specs

package.json, packages/manager/src/factories/longviewClient.ts, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx, yarn.lock
Tab layout and routing for Longview Landing. Involved moving the current LongviewLanding into LongviewClients.tsx and creating a placeholder for LongviewPlans.
Missing:
=> M3-3543 Longview landing tabs (git redo)

packages/manager/src/components/EditableTableRowLabel/EditableInput.tsx, packages/manager/src/components/EditableTableRowLabel/EditableTableRowLabel.stories.tsx, packages/manager/src/components/EditableTableRowLabel/EditableTableRowLabel.tsx, packages/manager/src/components/EditableText/EditableText.tsx, packages/manager/src/components/TextField.tsx
This includes a new table cell with an editable text field. Currently visible only in storybook (under EditableTableRowLabel).
This shares a lot of DNA with EditableText, but in this case the input needs to be a controlled component. EditableInput is an abstraction of just the markup of EditableText; if this approach is accepted, I can adjust the existing EditableText to use EditableInput internally to keep things consistent.
🔥 Styling for the error states is not yet complete.
=> M3 editable table cell

packages/linode-js-sdk/src/kubernetes/kubernetes.ts, packages/linode-js-sdk/src/kubernetes/types.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
We were using a hardcoded API endpoint for LKE clusters, until the
API had added that information. This is now requestable at
/lke/clusters/:clusterID/api-endpoint, so the hard-coding can be
removed.
- added a service method and types for the new endpoint
- added a request in useEffect in the cluster detail component,
along with error handling and simple loading state.
LKE isn't working properly in dev, so the best way to test this is to point your stuff at staging
=> LKE-1064 endpoint

packages/manager/e2e/pageobjects/dashboard.page.js, packages/manager/e2e/pageobjects/linode-detail/linode-detail-volume.page.js, packages/manager/e2e/pageobjects/list-domains.page.js, packages/manager/e2e/pageobjects/list-linodes.js, packages/manager/e2e/pageobjects/page.js, packages/manager/e2e/specs/domains/smoke-list-domains.spec.js, packages/manager/e2e/specs/linodes/detail/backups.spec.js, packages/manager/e2e/specs/linodes/smoke-linodes.spec.js, packages/manager/e2e/specs/tagmanagement/group-by-tags-linode.spec.js, packages/manager/e2e/specs/tagmanagement/group-by-tags-nodebalancer.spec.js, packages/manager/e2e/specs/tagmanagement/group-by-tags-volumes.spec.js, packages/manager/e2e/specs/tagmanagement/import-groups-and-group-by-tag-domains.spec.js, packages/manager/e2e/specs/tagmanagement/import-groups-as-tags-linodes.spec.js, packages/manager/e2e/utils/common.js, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Updated tag management specs
* all syntax has been updated
* most tests are being skipped. This is because we have changed the functionality and styling of the page (e.g. dropdowns instead tables with cards). We have also changed how settings are saved and this will require some refactoring to get this to work correctly. noted have been left in tests where needed/known.
1. `yarn up`
3. `yarn e2e --dir tagmanagement`
=> M3-3383 Updated tag management specs

packages/manager/src/containers/longview.stats.container.ts, packages/manager/src/features/Longview/request.ts, packages/manager/src/store/index.ts, packages/manager/src/store/longviewStats/longviewStats.actions.ts, packages/manager/src/store/longviewStats/longviewStats.reducer.test.ts, packages/manager/src/store/longviewStats/longviewStats.reducer.ts, packages/manager/src/store/longviewStats/longviewStats.requests.ts, packages/manager/src/store/types.ts
Adds both Longview Client Data to Redux state and a container component
For this component to function, you'll need a client ID available as `ownProps`, so the usage looks like the following:
```js
import withLongviewStats, { Props as LVDataProps }
interface Props {
clientID: number;
apiKey: string;
}
type CombinedProps = Props & LVDataProps;
const MyComponent: React.FC<CombinedProps> = props => {
React.useEffect(() => {
props.getClientStats(props.apiKey)
}, [])
return (
<div>hello world</div>
)
}
export default withLongviewStats<Props>((ownProps) => ownProps.clientID)(MyComponent)
```
=> Change: Add Longview Client Data to Redux State

packages/manager/config/webpack.config.dev.js, packages/manager/config/webpack.config.prod.js
Fixes recent warnings about ForkTsCheckerWebpackPlugin memory usage that aborted some commits.
Also had to add a no-rule for ordering for the webpack config files, since they were picked up by the linter. All other changes are automatic "prettyfying" which tells me these files had not been touched for a bit.
=> M3-3554 Increase memory limit for TS checking

packages/manager/e2e/pageobjects/enable-all-backups-drawer.js, packages/manager/e2e/specs/globalsettings/auto-backup-enrollment.spec.js, packages/manager/e2e/utils/common.js, packages/manager/e2e/utils/cred-store.js
* uppdated all files for the global settings spec
* needed to make some modifications for the switchTab function that is no longer working with the  current webdriver changes. This will need to be looked into and fixed for furture reference. At the moment only tests in the global settings are using this so not dire to fix.
* not sure why browser.getSource needed to be changed to browser.getPageSource again
* Only two tests were skipped due to the tab switching issue
1. `yarn up`
3. `yarn e2e --dir globalsettings`
=> M3-3381 Updated global settings spec

packages/manager/src/features/Domains/DomainRecordDrawer.tsx
This was causing some confusion, so the title of the drawer has been updated.
The drawer title is dynamic. I changed `typeMap`, which isn't used anywhere else. Just poke around Domains and make sure nothing broke.
=> M3-3559 Update A/AAAA record drawer title

packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Uses the `longviewStats` redux to state to supply data for the CPU Gauge
=> Change: Hydrate CPU Gauge from Redux

packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
As a followup to https://github.com/linode/manager/pull/5703, this PR handles the Plan Details page for restricted users.
There are a few different states:
**With read/write permissions:**
**With readonly permissions:**
Please test several combinations between restricted, (read and read-write), Managed, unrestricted, etc.
=> M3-3416 [LV] Plan Details – handling for restricted users

packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
This fixes a `React.useEffect()` bug noticed when reviewing https://github.com/linode/manager/pull/5712. 
An effect that set an interval was missing a dependency array, resulting in `mounted` being set to false on every render. This caused occasional race-condition issues where the data wasn’t always being populated on page load.
=> [LV] Fix useEffect bug in LongviewClientRow

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DetailNavigation.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/Details.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeCluster.tsx, packages/manager/src/features/Kubernetes/index.tsx
Replaced LKE content with a tabbed layout with placeholders.
This is going to fail the linter since there's commented out code and variables that aren't used as a result.
=> Add routing skeleton for new LKE detail layout with tabs

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DetailNavigation.tsx, packages/manager/src/features/Kubernetes/index.tsx
- Add a Redirect to the new details navigation page, so that clicking
on a cluster from the list view will go to kubernetes/clusters/xxx/details,
rather than kubernetes/clusters/xxx/ with the details tab mysteriously active.
- Fix a longstanding issue where the clusters view was at /kubernetes with
the detail view at /kubernetes/clusters/xxx. Navigating to Kubernetes now
takes you straight to the list view at /kubernetes/clusters, which matches
Object Storage's pattern.
=> Fix LKE Routing

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/Details.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
This PR focuses on the /details tab, which includes a modified "view only" version of node pools details and a documentation blurb. 
=> Separate LKE Cluster Details and Resize into two nested tabs: Details Page

packages/manager/src/eventMessageGenerator.test.ts, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/factories/events.ts
I assumed that all events would come back with a secondary_entity,
but events created prior to this change were not updated. This caused
a lot of noise in Sentry (millions of reported exceptions) since we
weren't safe accessing the field.
Added a helper method, safeSecondaryEntityLabel, which handles this.
We should revisit this logic, since it gets pretty repetitive.
=> Hotfix: Safe access event.secondary_entity

packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx, packages/manager/src/components/Breadcrumb/Breadcrumb.tsx, packages/manager/src/components/Breadcrumb/Crumbs.tsx
In order to make the breadcrumb component more versatile, we wanted to be able to only keep the first and last crumbs and keep the component as simple as possible for basic usage. Instead of enhancing the `removeCrumbX` prop with an array, doing it this way will satisfy most use cases.
This will not affect any existing crumb unless the `firstAndLastOnly` prop is set
=> M3-3577 Add option to allow only first and last crumbs in breadcrumbs

packages/manager/yarn.lock
This follows Jared's PR that needed this commit after another `yarn clean`
=> M3-yarn-cleanup: remove dep after cleanup

packages/manager/src/containers/kubernetes.container.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeCluster.tsx, packages/manager/src/features/Kubernetes/kubeUtils.ts, packages/manager/src/store/kubernetes/kubernetes.reducer.ts, packages/manager/src/store/kubernetes/kubernetes.requests.ts, packages/manager/src/store/kubernetes/nodePools.reducer.ts
Found a few cases where the node pools table wasn't accurately reflecting the new state of the cluster after submitting the form. Added a .then thingy that re-requests the node pools from the API after all the update/delete/create requests have finished. (This wasn't necessary in the previous iteration since after submission we exited "edit mode", so the table always had the updated state.)
Try a bunch of combinations of update/edit/delete on the node pools table, with and without some request blocking going on.
=> LKE Fix: node pool deletion

packages/manager/src/events.ts, packages/manager/src/exceptionReporting.ts
Stops reporting some of the biggest offenders to Sentry
Ideally, we just need to buckle down and `.catch` all the promises in the events middleware, but there's just no time for that.
Use Charles to mock an API error and then remove a `catch` from some promise. I chose the `updateProfile` request in the `UpdateTimeZoneForm` component - in this example, you'll have to remove the `.catch` in both the component and the redux request.
=> Change: Stop Reporting OAuth and Not Found Errors To Sentry

packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
The link points to the current (old) version of the doc, but will be updated to the new doc when it's done.
=> Longview: Update documentation link URL

packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
This link is the same as the one in the new /details view, which means that it's 404'ing at the moment. It (the guide) will be fixed before the beta is public.
=> Update LKE landing empty state link to point to new LKE guide

packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/common.ts, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Lets the Gauges know there was an error fetching `lastUpdated` and displays and error state for that.
Also fixes an issue where the `requestLastUpdated` closure wasn't getting the most up-to-date `lastUpdated` value because that's how closures work.
[The solution comes from a Facebook employee](https://github.com/facebook/react/issues/14010#issuecomment-433788147) - I'm just following instructions
=> Change: Expose Gauges to Fetch LastUpdated Errors

packages/manager/src/features/Volumes/VolumesLanding.tsx
The create a volume button should route to the volume creation page, not the drawer anymore. This is a regression from the workflow refactor.
- Bug fix ('fix', 'bug')
=> M3-3588 Fix empty volumes create button path

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx
⚠️ ~**TODO: Merge #5758 first, then rebase this branch**~ ⚠️ DONE
~_Note: There is a bug where the form resets every time we receive events. This is unrelated to the present work, so the fix is coming in a separate PR._~ 
Went ahead and fixed this ^^^ here. It's kind of a hack fix; I went ahead and created M3-3595 to remove all instances of componentWillReceiveProps since it is being deprecated in React 17.
This PR allows the Edit RDNS Drawer for IPv6 ranges. I reused the existing `<EditRDNSDrawer />` component for this.
Now, if we're editing RDNS for a range, we display a new text field to allow the user to enter the specific IP address to set RDNS on. The text field is pre-populated with the range prefix.
**To fully test**, you'll need to …
=> M3-3456 RDNS drawer for IPv6 ranges

packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx, packages/manager/src/store/longviewStats/longviewStats.reducer.test.ts, packages/manager/src/store/longviewStats/longviewStats.reducer.ts
This includes the layout and live data logic for "Data last updated at..." display.
The select for sorting clients by different values is a static Select for now.
I'm hoping to show this at review to get feedback on design, whether or not we want a global "last time any client was updated" display, etc. The actual sorting logic is going to be a nightmare and there's no chance it'll be ready for the next release. Please let me know if you think merging in this state (pending PR review) is acceptable.
=> M3-3512 Longview: sort clients by values

packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx, packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx, packages/manager/src/components/EditableEntityLabel/EditableInput.tsx, packages/manager/src/factories/accountSettings.ts, packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
Loose ends:
- Updating labels in LongviewClientInstructions
- Hide CTA if you're already LV Pro
- Add optional placeholder prop to DebouncedSearchTextfield
=> M3 Longview landing: cleanup
