- packages/manager/src/features/Longview/LandingContent.tsx
- packages/manager/src/features/Longview/LongviewActionMenu.tsx
- packages/manager/src/features/Longview/LongviewTable.tsx
- packages/manager/src/features/Longview/LongviewTableRows.tsx
Adds Action Menu to Longview Table
> Add: Longview Action Menu

- packages/manager/src/containers/longview.container.ts
- packages/manager/src/features/Longview/AddClientDrawer.tsx
- packages/manager/src/features/Longview/LandingContent.tsx
- packages/manager/src/features/Longview/LongviewTable.tsx
- packages/manager/src/features/Longview/LongviewTableRows.tsx
- packages/manager/src/store/longview/longview.actions.ts
- packages/manager/src/store/longview/longview.reducer.ts
- packages/manager/src/store/longview/longview.requests.ts
Uses Thunk Action to create a Longview Client.
> Add: Add Longview Clients to Redux State with Action

- packages/linode-js-sdk/src/longview/longview.ts
- packages/manager/src/containers/longview.container.ts
- packages/manager/src/features/Longview/LongviewTable.tsx
- packages/manager/src/features/Longview/LongviewTableRows.tsx
- packages/manager/src/store/longview/longview.actions.ts
- packages/manager/src/store/longview/longview.reducer.ts
- packages/manager/src/store/longview/longview.requests.ts
Adds the Redux boilerplate for deleting a Longview Client
> Add: Longview Client Delete Redux Actions

- packages/linode-js-sdk/src/longview/longview.ts
- packages/manager/src/features/Longview/LongviewActionMenu.tsx
- packages/manager/src/store/longview/longview.actions.ts
- packages/manager/src/store/longview/longview.reducer.ts
- packages/manager/src/store/longview/longview.requests.ts
Adds Redux boilerplate to update a Longview Client.
> Add: Redux Update Logic For Longview Clients

- packages/manager/src/containers/longview.container.ts
- packages/manager/src/features/Longview/AddClientDrawer.tsx
- packages/manager/src/features/Longview/LandingContent.tsx
- packages/manager/src/features/Longview/LongviewTable.tsx
- packages/manager/src/features/Longview/LongviewTableRows.tsx
- packages/manager/src/features/Longview/UpdateClientDrawer.tsx
Adds the ability to rename a Longview Client
> Add: Ability to Rename Longview Clients

- packages/manager/e2e/pageobjects/search.page.js
- packages/manager/e2e/specs/search/search-tags.spec.js
- packages/manager/e2e/specs/search/search-volumes.spec.js
- packages/manager/e2e/specs/search/smoke-search.spec.js
All search specs updated. All tests passing or skipped
This updates the search test specs
1. `cd packages/manager`
2. `yarn up`
3. `yarn selenium`
4. `yarn e2e --dir search`
to run an individual test:
`yarn e2e --file search/search-tags.spec.j`
> M3-3377 Search specs updated

- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
Adds Types for data necessary for the Donut graphs
> Add: New Longview Response Types

- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewTable.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewTableRows.tsx
- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
Polls the Longview API for the `lastUpdated` datetime.
> Add: Poll Longview Last Updated Time

- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
Adds system info interface to Longview typings
> Change: Add new System Info interface to Longview Typings

- packages/manager/e2e/config/custom-commands.js
- packages/manager/e2e/pageobjects/configure-linode.js
- packages/manager/e2e/pageobjects/profile.js
- packages/manager/e2e/pageobjects/profile/lish.page.js
- packages/manager/e2e/specs/profile/clients.spec.js
- packages/manager/e2e/specs/profile/lish.spec.js
- packages/manager/e2e/specs/profile/ssh-keys.spec.js
- packages/manager/e2e/specs/profile/tfa.spec.js
- packages/manager/e2e/specs/profile/tokens.spec.js
- packages/manager/e2e/specs/profile/update-display.spec.js
Updated the profile tests. A lot of tests ended up being skipped due to instability. We are also planning on using Jest test to cover a lot of the things the e2e tests are doing.
`cd packages/manager`
`yarn up`
`yarn e2e --dir profile`
Single tests can be run with:
`yarn e2e --file profile/clients.spec.js`
> M3-3378 updated profile specs

- packages/manager/src/features/Billing/BillingPanels/PromotionsPanel/PromotionsPanel.tsx
- packages/manager/src/features/Dashboard/BlogDashboardCard/BlogDashboardCard.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/DestructiveSnapshotDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
> M3-3443 Adjust display of expiring credit in expandable panel header

- packages/manager/src/index.css
> M3-3441 Fix wrong CSS in index

- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
> M3-3455 Make maintenance status tooltip persistent on hover

- packages/manager/config/testSetup.js
- packages/manager/src/__data__/longview.ts
- packages/manager/src/components/GaugePercent/GaugePercent.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
Adds unit tests for Load Gauge
Tests both utility functions and UI, using mock API responses.
> Add: Unit Tests for Load Gauge

- packages/manager/src/features/OneClickApps/FakeSpec.ts
> OCA Update: cPanel and Plesk

- packages/linode-js-sdk/src/linodes/types.ts
- packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
Updates misc Linode typings that didn't belong.
> [SDK] Update: Linode Typings

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
Note that you'll get an Access Denied message in your browser if your bucket is not public.
> OBJ-195 Make Bucket URLs clickable

- packages/manager/package.json
- packages/manager/src/features/Lish/Weblish.tsx
- packages/manager/yarn.lock
Looking at Sentry related to weblish partially
I also saw that we had a quite outdated version of Weblish and sentry
As a first step in cleaning up sentry i thought i would start with these.
Includes update of the 2 packages sentry (2 minor versions) and xterm (major version change)
And update of Weblish use of xterm API
> M3 sentry & weblish update

- packages/manager/src/features/StackScripts/stackScriptUtils.ts
Adds the feature flags for the cPanel and Plesk One-Click Apps to be displayed on the OCA dashboard.
> OCA Add: cPanel and Plesk feature flags

- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Account/GlobalSettings.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
> OBJ Update flag sequence

- packages/manager/src/features/Users/UserProfile.tsx
Previously looked like this:
Now looks like this:
> Change: User Profile Styles

- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
Removing GPU from plan selection for LKE.
> LKE-1067 Remove GPU plan option from K8 Create Flow

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
> Add: Longview Swap Gauge

- packages/manager/src/features/Lish/VncDisplay.tsx
Glish being remote access to the virtualised VGA and PS2 Mouse and PS2
Keyboard does not have a pasting functionality. This PR enables pasting
by listening for a paste event on the document. If the mouse is on the
canvas noVNC will capture the paste event and pasting will not proceed,
but if the mouse is on the document part of the window then pasting will
occur in the window.
This works by taking the text from the paste buffer, and "manually"
actuating the keys through noVNC in an automated fashion. Currently this
works on text only and anything that is supported by a standard 104 key
keyboard.
In addition this only works in one direction browser to Linode. The
other way is not possible with this implementation.
This PR used
https://gist.github.com/byjg/a6378edb420a1c654c5f27bb494ca1c8 …
> M3 Enables pasting for glish

- packages/manager/e2e/specs/stackscripts/stackscript-detail.spec.js
Strangely this did not make the test fail, but linter detected
> Fixing M3-3541

- packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
> [OBJ] Copy edits for confirmation modal

- packages/manager/src/__data__/longview.ts
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
> Add: Longview Network Gauge

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
- packages/manager/src/store/image/image.reducer.ts
> 0.77.0 Master -> Develop

- Dockerfile
> Change: Dockerfile

- package.json
- packages/linode-js-sdk/package.json
- packages/manager/package.json
Updates the license in the package.json files
> Change: License

- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DetailNavigation.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeCluster.tsx
Moves the logic for updating your cluster down into the new Resize component, at clusters/444/resize.
> M3-3560 LKE resize tab

- packages/manager/src/containers/__new__/nodeBalancerConfigNodes.container.ts
- packages/manager/src/containers/__new__/nodeBalancerConfigs.container.ts
- packages/manager/src/containers/__new__/nodeBalancers.container.ts
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/__new__/EditNodeBalancerConfigs.tsx
- packages/manager/src/store/index.ts
- packages/manager/src/store/nodeBalancerConfig/configNode.requests.ts
Adds containers for NodeBalancers, configs, and nodes
Also adds nodes to Redux state.
> [NodeBalancer Refactor] - Redux Containers

- packages/manager/e2e/specs/stackscripts/stackscript-detail.spec.js
fix sonar report, of bad argument passed to this test functions
> Eliminate bad argument in e2e test

- packages/manager/src/features/Longview/index.tsx
Updating copy of our current Longview page to indicate to users that this feature is coming soon.
> For Release: Updating copy for Placeholder Longview Landing

- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
Adds a CTA to the bottom of the Longview landing page. For now, this will always appear. I'm waiting on some logic from #5737 before I make the CTA dynamic.
Also fixes a typo that would crash the landing page on error.
It's a link.
> M3-3520 longview cta

- CLOUD.md
- CREATE_CLIENT.md
- packages/manager/src/App.tsx
- packages/manager/src/IdentifyUser.tsx
- packages/manager/src/containers/withFeatureFlagProvider.container.ts
Load the app as normal if no Launch Darkly ID exists
> Change: Make Launch Darkly ID Optional

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Updates Load gauge to source data from Redux
> Change: Load Gauge Sources Data From Redux

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Sources network data for gauge from Redux
> Change: Source Network Data From Redux

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Sources swap disk gauge data from Redux
> Change: Source Swap Gauge Data From Redux

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
Sources Storage Data for Gauge from Redux
> Change: Source Storage Data from Redux

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
> Merge Master back to develop

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Installation.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetailOverview.tsx
Adds Longview Installation Page
> Add: Longview Installation Page

- packages/manager/src/assets/icons/copy.svg
- packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
- packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
- packages/manager/src/components/GaugePercent/GaugePercent.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/common.ts
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
Enhancing styles and markup for instruction panel and client rows
> M3-3576 Longview Landing Panels styles/markup

- packages/manager/src/components/Button/button.stories.tsx
- packages/manager/src/components/Typography.stories.tsx
- packages/manager/src/themeFactory.ts
> Revert "Link Button Styles"

- packages/manager/src/MainContent.tsx
- packages/manager/src/features/Footer/Footer.tsx
> M3-3594 Fix footer placement after primary nav refactor

- packages/manager/src/components/CircleProgress/CircleProgress.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> M3 Quick fix to ipv6 ranges styles

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Re-adds OCA to the primary nav - this was a regression from earlier this week
> Fix: Primary Nav OCA Regression

- packages/manager/src/features/Account/GlobalSettings.tsx
Fixes the bug Chris saw in account/settings (we noticed this earlier and just didn't get to fixing it).
- GlobalSettings.tsx was toasting on every render based on the Redux
error state (accountSettingsErrors.update), which led to strange behavior.
Specifically, if you triggered a settings error from longview/plan-details
then navigated to /account/settings, the error was not clear and you
could be toasted for it multiple times.
Imo it's best practice to never toast based on Redux state. I added
`.catch()` blocks to the specific requests made in GlobalSettings and
toasted based on those errors.
> M3-3602 Fix: Multi-toast bug in account/settings

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
> Manually update IPs after editing RDNS

- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
- packages/manager/src/store/longviewStats/longviewStats.requests.ts
Changes 3rd argument of Longview Stats GET from `string[]` to `Options`
> Change: Arguments for Longview GET Request Abstraction

- packages/linode-js-sdk/src/nodebalancers/types.ts
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/__new__/EditNodeBalancerConfigsLanding.tsx
- packages/manager/yarn.lock
Adds a skeleton for the new NodeBalancer Configs Edit page.
> [NodeBalancer Refactor] - Edit Flow Skeleton

- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
This PR extracts the logic previously in LongviewClientRow to determine the time the Longview data was last updated.
> [LV] Extract lastUpdated and authed logic

- packages/manager/src/App.tsx
- packages/manager/src/analytics.ts
- packages/manager/src/constants.ts
- packages/manager/src/index.tsx
- packages/manager/src/utilities/ga.ts
> Change: Remove Possibility for Second GA ID

- packages/manager/src/components/Button/Button.tsx
- packages/manager/src/components/Button/button.stories.tsx
Does 2 things:
1. Gives buttons a min-width to make the transition from not loading -> loading state less jarring
2. Allows for new `loadingText` prop which will give the button text along with the SVG spinner
> Change: Button Styles

- packages/manager/e2e/specs/stackscripts/stackscript-detail.spec.js
Uncommented the test on line 99, along with some additional linter fixes.
3. `yarn e2e --spec=stackscript-detail.spec.js --browser=headlessChrome`
> M3-3515 Update stackscript-detail.spec.js

- packages/manager/e2e/specs/domains/smoke-list-domains.spec.js
- packages/manager/src/components/ExternalLink/ExternalLink.tsx
- packages/manager/src/features/Domains/CheckDomainDrawer.test.tsx
- packages/manager/src/features/Domains/CheckDomainDrawer.tsx
- packages/manager/src/features/Domains/DomainActionMenu.test.tsx
- packages/manager/src/features/Domains/DomainActionMenu.tsx
- packages/manager/src/features/Domains/DomainTableRow.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Domains/ListDomains.tsx
- packages/manager/src/features/Domains/ListGroupedDomains.tsx
- Remove "Zone file" action
- Check zone now opens a drawer with a `dig` command to run. There will eventually be a link to documentation in there as well, but since that guide isn't likely to be ready before the next release I left the code commented out.
> M3-3280 Update check zone action for Domains

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/__data__/account.ts
- packages/manager/src/containers/account.container.ts
- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/PromotionsPanel/PromotionsPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
- packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
- packages/manager/src/features/Profile/APITokens/APITokens.test.tsx
- packages/manager/src/features/Profile/APITokens/utils.test.ts
- packages/manager/src/features/Profile/APITokens/utils.ts
> Add: LKE to PAT Scopes

- packages/manager/src/assets/icons/activeRowCaret.svg
- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Events/EventRow.test.tsx
- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
- packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
This PR styles the Longview processes table rows and add selected states styles
> M3-3634 Longview processes table

- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/store/selectors/imageEvents.ts
Phase 2 of getting progress bars displayed when creating an Image. This adds a progress event to images on Images Landing. Next up is adding create/update image requests to Redux.
Create an image, then reload the page. Look in devtools and you should see an event with a secondary entity attached to the currently-being-created Image.
> M3-3563 image events

- packages/manager/src/features/Longview/LongviewLanding/LongviewActionMenu.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/LongviewLanding/RestrictedUserLabel.tsx
Prevents restricted users from updating or deleting Longview Clients they don't have access to delete or update.
> Change: Prevent Longview Deletion and Updating for Restricted Users

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/DiskPaper.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/themeFactory.ts
> Disks Tab: Inodes and Space Graphs

- packages/manager/src/features/Longview/LONGVIEW.md
Adds *super rough* docs for Longview. [View as markdown here](https://github.com/linode/manager/blob/5eccf39b1039fa81dce74d6d3092f603444ebbe8/packages/manager/src/features/Longview/LONGVIEW.md)
> Add: Longview Documentation

- packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
- packages/manager/src/components/DialogTitle/DialogTitle.tsx
- packages/manager/src/components/DialogTitle/index.tsx
- packages/manager/src/components/Drawer/Drawer.tsx
- packages/manager/src/components/H1Header/H1Header.tsx
- packages/manager/src/components/Placeholder/Placeholder.tsx
- packages/manager/src/features/TheApplicationIsOnFire.tsx
- packages/manager/src/themeFactory.ts
Added necessary markup and new component (modal title, in order to implement focus) to improve accessibility of modal windows 
> M3-3670 Making modals and drawers more accessible

- packages/manager/src/components/GaugePercent/GaugePercent.tsx
- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/GaugesSection.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
Various styling refinements mostly for overview display page, though this does update gauge and LV line graph styling.
Please test both landing and overview in multiple browsers and screen sizes. Note there is another PR up that has cross-browser display fixes.
> M3-3647: Overview Styling Adjustments

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/shared/formatters.ts
- packages/manager/src/features/Longview/shared/utilities.test.ts
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/themeFactory.ts
This PR includes the Network graph on the LV Detail Overview page.
To do:
> [LV] Network graph

- packages/manager/src/factories/longviewDisks.ts
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/request.types.ts
- packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/themeFactory.ts
> M3-3525 disk graph

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/DiskPaper.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/request.ts
Adds in special cases to show helper text when a disk is of a certain type.
* adds unit tests for the graph UI and helper functions
* fixes `showToday` logic
* safely accesses `y` value for graphs
* adds placeholder value for times in the past
> Change: Adds Special Cases For Disk UI

- packages/manager/src/components/EditableEntityLabel/EditableInput.tsx
Small aria additions to the LV client header on landing.
> A11y Improvements for LV landing

- packages/manager/src/components/EditableEntityLabel/EditableInput.tsx
- packages/manager/src/components/TextField.tsx
> M3-3645 Fix error formatting on editable input labels

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/types.ts
Pass the lastUpdated value from longviewDetail down to Overview -> OverviewGraphs
and then to each of the graphs, so that they can request new data when lastupdated
is changed.
> [LV] Poll on lastUpdated for overview graphs

- packages/manager/src/components/TableSortCell/TableSortCell.tsx
Pretty straight forward accessibility enhancement.
> M3-3676 Add aria label for sortable header buttons

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/DiskPaper.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/request.types.ts
- packages/manager/src/features/Longview/shared/formatters.ts
🚨 This the last last disks PR 🚨 
Adds Disk I/O Graphs
Also adds the dummy point at the beginning.
> Change: Add Disk I/O Stats

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- Fix bug where emptyState was being mutated, causing data to bleed
into different client views (h/t @johnwcallahan)
- Fix some typos
> [LV] Fixes

- packages/manager/src/components/IconTextLink/IconTextLink.tsx
Another small Caker item that has been a recurring demand (styling, button text alignment and spacing).
> M3-3695 Styling adjustment to IconTextLink

- packages/manager/src/components/PasswordInput/PasswordInput.tsx
Small changes requested by design after initial POC
> M3-3696 Password tips styling adjustments

- packages/manager/src/features/Domains/DomainDetail.tsx
- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
Caker item that breaks a bit our conventions but does not really affect the ability to get to editing tags. This is a POC of sorts, but needed to get in ASAP.
> M3-3621 Move domains tags sidebar

- packages/manager/src/components/Radio/Radio.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Adding more a11y support for Linode Resize, though this will extend to some small improvements for Radio as well.
> [For Release] M3-3646 Accessibility issue with Disk resizing options

- packages/manager/src/components/H1Header/H1Header.tsx
Removing focus from h1 component.
> FOR RELEASE: Removing focus from h1 header component

- packages/manager/src/factories/domain.ts
- packages/manager/src/factories/volume.ts
Made these for PR testing, might as well keep them
> Add factories for Domains and Volumes

- packages/manager/package.json
- packages/manager/src/components/H1Header/H1Header.tsx
Things got a little messy with stuff that was in testing/master but not yet in develop so we're not able to sync master to dev until these conflicts are fixed. I will revert these changes back to what had been added once the master sync has merged!
> Reverting conflicts for dev/master sync

- packages/manager/package.json
- packages/manager/src/components/H1Header/H1Header.tsx
This adds back the changes that were in develop that were conflicting for master -> develop.
> Reverting develop revert

- packages/manager/package.json
- yarn.lock
> remove pretty bytes direct dependency

- packages/manager/package.json
- yarn.lock
It looks like these are not used, but i would like to check this.
Is it part of lish?
I must test the PR website first
> remove typeface ubuntu

- packages/manager/package.json
- yarn.lock
remove useless dep react-text-mask
> remove react-text-mask (unused), which removes a prop-types 15

- yarn.lock
Clean yarn lock after some of the changes from
https://github.com/linode/manager/pull/5934
were partially reverted during merge of https://github.com/linode/manager/pull/5941/files
> clean yarn lock after merges in develop

- packages/manager/public/index.html
Simply remove this script as we do not use it
> remove script crazyegg

- packages/manager/src/utilities/groupByTags.ts
> M3-3725 Move untagged items under tagged ones for all entities

- packages/manager/public/.well-known/security.txt
- security.txt
Copy the existing security.txt file used for Linode.com and make it
available at the standard path (/.well-known/security.txt). Guidelines
for a repo say that it should be at the root level, and I couldn't figure
out how to do this with a symlink, so I just pasted it there too. It's a
very stable file so having multiple copies shouldn't be an issue.
To run …
> Add security.txt file

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/index.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/request.types.ts
Layout for Network tab in LV. Data is empty (unused), but the time range select etc. should be working.
> M3-3526 Layout for Longview network graphs

- packages/manager/package.json
- yarn.lock
follow up to previous PR, that was closed too early
> constrain more sentry version

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/FeatureComingSoon.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/index.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
Skeleton/empty graphs and TS types for NGINX tab in Longview detail view
I will base upcoming PRs on this and rebase one this is approved.
> M3-3538 [Longview] Add NGINX layout

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Update Grafana Jenkins & Prometheus text as per marketing suggestion
* Non breaking update ('update', 'change')
Ready to merge
> OCA Update: Grafana, Jenkins & Prometheus

- packages/manager/package.json
- packages/manager/src/components/SnackBar/CloseSnackbar.tsx
- packages/manager/src/components/SnackBar/SnackBar.tsx
- yarn.lock
Update outdated lib notistack
Fixed a yarn install warning:
Check that the snack bar works
> M3-3627 update notistack only

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Changed the copy to remove the censorship portion.
This is to go out with the release of the new OCA's
> [change] Edit to the shadowsocks Copy

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLProcessesGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/index.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXProcessGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx
- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Longview/request.types.ts
- packages/manager/src/features/Longview/shared/utilities.test.ts
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/themeFactory.ts
Mostly copy-pasted and adapted from NGINX.
- Updated some logic for summing up Processes data, where there were multiple processes related to MySQL. I don't know if the situation will occur in NGINX as well, but just to be safe I used the same logic there.
- Fixed a units error in memory graphs that was also present in NGINX
> M3-3537 [Longview] MySQL

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Always show OCA in both the primary nav and the AddNew menu. Remove usage of this feature flag ~ AB test
> M3-3724 Change: Remove oneClickLocation feature flag

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/shared/utilities.ts
I had larger plans for this, but I'd like to get this refactor in so @WilkinsKa1 and I can use it for memory graphs in the other tabs.
> Refactor memory graph

- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
> [LV] Improve Processes Table on small viewports

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
> Master --> Develop

- CHANGELOG.md
Had some missed deletions in the read me. These have now been removed.
> Fixed CHANGELOG.md file

- packages/manager/src/components/StackScript/StackScript.tsx
> StackScript Detail: use internal link for author

- packages/manager/package.json
- yarn.lock
Upgrade typescript to a stable version (was in beta)
Leads to multiple version dedupe
No addition of dependency
> Upgrade typescript fsa to stable version

- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeCluster.tsx
Actual change here is quite small, please check all places where node pools are added (create and resize cluster menus is it, I think). I also added some factories for tests that didn't work out. Left the factories in bc they might be useful in the future.
> M3-3612 [LKE] Node pools should have 3 nodes by default

- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/kubeUtils.ts
Warn users when they're about to create or edit a cluster such that it will have a single node.
> M3-3613 [LKE] Warning for clusters with a single node pool

- packages/manager/public/assets/phpmyadmin_color.svg
> OCA Update: set phpMyAdmin asset size

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
> Revert "Master -> Develop"

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
Take 2. I accidentally squash merged last time.
> Master -> Develop

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
Trying to not load all the data when using lish
> Not reloading everything when we load the lish

- packages/manager/config/webpack.config.dev.js
- packages/manager/config/webpack.config.prod.js
- excludes test files from rules in compilation of manager
> reduce compile time

- packages/manager/src/features/OneClickApps/FakeSpec.ts
> CT-1623, update, OCA Copy Edit

- CHANGELOG.md
While releasing the hotfix release, the non-edited changelog entry was committed by accident.
> Fix changelog for 0.84.1

- packages/manager/package.json
- yarn.lock
cleaning types not useful anymore 
> Clean types deps that are not needed anymore

- packages/manager/public/index.html
trying to solve this issue in audits
the change is ugly, but goal is to pass after the ada script is injected and inject the ada bot iframe title for a11y
> add title to ada chat bot in ad hoc way

- packages/manager/src/features/Images/ImagesDrawer.tsx
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
Noticed that we weren't handling all possible cases for what the Images drawer button should say. This should be more comprehensive.
> Use appropriate button text when restoring from an image

- packages/linode-js-sdk/src/firewalls/firewalls.schema.ts
- packages/linode-js-sdk/src/firewalls/index.ts
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallTable.tsx
- packages/manager/src/features/Firewalls/shared.ts
Completes the AddDrawerFirewall, including adding Formik, validation, error, and submission logic. This included updating validation schemas for firewalls, and reshaping the data for the predefined firewall options, since the format didn't play well with EnhancedSelect and Formik.
Todo:
> M3-3246 Add: Create firewall

- packages/manager/src/features/Lish/Weblish.tsx
The problem I set out to solve in Lish is much more involved than I thought. In the meantime, however, I found this option, which seems to work pretty well for screen readers.
> Add screen reader mode to Weblish

- packages/manager/package.json
- yarn.lock
Used to be problematic because of old dependancies but is now very straightforward 
> realign versions of yup between packages

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/MainContent.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
We actually introduced handling for restricted users in #5640, but it was reversed by a regression in #5785.
Re-adding handling for restricted users is especially important for the upcoming promo.
I also adjusted padding and margins.
Please test OBJ and Dashboard for restricted users as well as unrestricted users.
> [hotfix] Show OBJ for restricted users

- TESTING.md
> basic cypress doc in Testing .md

- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
Non breaking change ('update', 'change')
Manually checked on Linode page. Ran the following for unit testing:
1. `yarn up`
2. `yarn test RegionSelect`
> Refactored RegionSelect to replace pathOr

- packages/manager/src/components/EntityIcon/EntityIcon.tsx
- packages/manager/src/components/ProductNotification/ProductNotification.tsx
- packages/manager/src/containers/withBackupCTA.container.ts
- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Backups/BackupsCTA.tsx
Refactor pathOr with optional chaining practice
> M3-3766: Refactor pathOr

- yarn.lock
> fix vuln on kind-of 6.0.2

- packages/manager/src/components/DialogTitle/DialogTitle.tsx
- packages/manager/src/components/H1Header/H1Header.tsx
- packages/manager/src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx
- packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
- packages/manager/src/features/Domains/DomainTableRow.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
Set all negative tabIndex to 0 in order to comply with accessibility guidelines.
> M3-3487: Change tabIndex from -1 to 0 for all files

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Fix misspelled word in Django fakespec
> OCA update: Fix Django Spelling

- packages/manager/cypress/support/commands.js
Fix the fact that the expire date of the token was **hardcoded**
This only affect cypress code
> fix expireDate for login that was hardcoded :facepalm:

- packages/manager/cypress/support/commands.js
> fix cypress login expiredate

- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
Clicking "Edit" in the action menu will navigate the user to the details page for that Firewall.
> M3-3924: Redirect edit Firewall to details page

- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
There's a border that's showing up on the left of the graphs/metric legends that shouldn't be there.
> M3-4047: Remove border on graph legends

- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
In accordance with our pattern elsewhere in the app.
> Use H3 for Firewall labels

- packages/manager/package.json
- packages/manager/testServer.js
- yarn.lock
Package is deprecated
https://www.npmjs.com/package/inert
see warnings
> inert is deprecated replaced by @hapi/inert for security

- packages/manager/src/features/Billing/BillingDetail.test.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
Run `yarn test`; hopefully there should be no more console errors about making a real API request.
> Clean up remaining test requests

- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
Backend was updated to support this, see ticket with more info.
https://developers.linode.com/api/v4/account-payments-paypal#post
> allow up to 10000usd payment with paypal

- packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
Day 12 of self isolation - I'm doing work for free
Before:
After:
> Removes Broken Style

- packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/StackScripts/stackScriptUtils.ts
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
this should go into production on March 30, 2020. If you need to coordinate with marketing, reach out to Hillary Wilmoth
I tried to change the text in the side bar, and in the 'create from' menu to marketplace from 'one-click apps'. Let me know if I did it wrong. or if I missed any files.
> [DONOTMERGE] Update - changed one-click to marketplace

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
Just some boilerplate to allow the resize node pool to be opened. Submitting the form won't do anything yet.
> LKE: Add drawer handling with dummy submit function

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
> [LKE] Update docs link

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.tsx
Add wiring to make the resize pool drawer actually do stuff. Most of this is boilerplate, small change overall.
> Add loading, submit, and error handlers for drawer

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
Add a dialog for deleting node pools. A follow on PR will add a separate dialog for deleting nodes.
> [LKE] Delete node pool

- CHANGELOG.md
- packages/linode-js-sdk/package.json
- packages/manager/package.json
This merge needed a commit and there were conflicts with the updated UI, so I thought it was best to do a PR for this. Please make sure none of your recent work got overwritten somehow in the merge.
> Merge hotfix

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
We have a docs button on the create flow, but the designs also specify one on the detail view. Adding that in now.
> Add DocumentationButton to the top right of Cluster detail view

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
In some of the refactoring we lost the ability to add pools on mobile, this adds that in.
> Updating SelectPlanQuantityPanel Mobile Functionality

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/AddNodePoolDrawer/AddNodePoolDrawer.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.tsx
- Add missing parentheses in AddNodePoolDrawer
- Pluralize node count properly in AddNodePoolDrawer
- Remove outdated final sentence from the warning displayed
when resizing your node pool to a smaller size
> [LKE] Copy fixes

- TESTING.md
Improve the documentation for cypress usage
> add doc to use cypress

- CODE_CONVENTIONS.md
Minor fixes of typos + other miscellaneous edits I noticed while reading through the doc
> Minor fixes to CODE_CONVENTIONS.md

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
EditRDNSDrawer.tsx was previously using old patterns including class components, createStyles & withStyles, and unsafe lifecycle methods. This refactor brings the file up to our current patterns, with it being rewritten as a function component with hooks.
The part of the app this touches is the Networking tab in an individual Linode; you click the "Edit RDNS" option for an individual IP. Please ensure that no functionality is lost compared to what is currently in production. 
> M3-3015: Refactor old code out of EditRDNSDrawer.tsx

- packages/manager/src/features/Billing/BillingPanels/PaymentDrawer/CreditCard.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentDrawer/PaymentDrawer.tsx
- packages/manager/src/features/Billing/BillingSummary/BillingSummary.tsx
Wiring to render the payment drawer, with open/close logic inside BillingSummary.
> Change: Add payment drawer to billing summary

- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
> M3-4162 Remove stray characters in FromBackupsContent

- packages/manager/e2e/pageobjects/nodebalancer-detail/details.page.js
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/SortableTableHead.tsx
Rename "node status" to "backend status" in NodeBalancers list view (and elsewhere for consistency). All other changes are linter fixes.
> M3-4071 Change: "Node Status" to "Backend Status"

- package.json
- yarn.lock
I tested `yarn up`, `yarn build`, `yarn cy:e2e` and the app seems to work. Please try to find something I didn't.
> Resolve version of yargs-parser

- packages/manager/src/components/TabLinkList/TabLinkList.tsx
- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Account/EnableManaged.tsx
- packages/manager/src/features/Account/GlobalSettings.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- yarn.lock
Updating Account landing, Object Storage landing, and Firewall details page to the new linked tab pattern.
There shouldn't be any regressions to these pages, the only thing that should be changed is the ability to navigate through the tabs via keyboard.
> Tab Refactor: Account Landing, OBJ Landing, FW Details

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/EditRDNSDrawer.tsx
Fixes to https://github.com/linode/manager/pull/6353 addressing @johnwcallahan's feedback
> M3-3015: Fix for EditRDNSDrawer range bug & hook naming conventions

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentDrawer/CreditCard.tsx
Small items from the payment drawer:
- Use "ending with" text instead of a XXXX XXXX ... mask
- Hide the button tooltip unless the button is disabled
- Move the CVV field next to the credit card info
- Fix a few random linter things
> [Billing] Payment drawer feedback items

- packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
Simple fix to align the NodeBalancer columns with the other tables.
> M3-4156: Align NodeBalancer column on dashboard

- packages/manager/src/features/Account/CancelAccountDialog.tsx
- packages/manager/src/features/Account/CancelAccountSetting.tsx
- packages/manager/src/features/Account/GlobalSettings.tsx
This PR adds "Cancel Account" to Account -> Settings.
> Move Cancel Account to Settings

- .github/workflows/sdk.yaml
Will build and test whenever a push happens on master. Publishing will be added/enabled when we're ready to publish.
> Add SDK workflow for GitHub

- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx
- packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationForm.tsx
- Collapse unpopulated Contact Info fields
- If left column is unpopulated, don't render it -- this allows the right column to move left instead of having fields in the right column just floating over there
- Put "Required" in parentheses next to "Email" in drawer
Try filling out and omitting the pieces of data in various ways to see if you observe any unwanted or odd behavior.
> [Billing] Contact Info & Edit Drawer refinements

- packages/linode-js-sdk/src/volumes/types.ts
- packages/manager/src/features/Volumes/RenderVolumeData.tsx
- packages/manager/src/features/Volumes/types.ts
Bring Volume SDK types in line with the API
Move recentEvent from SDK Volume type and add to ExtendedType in features/volumes/types
> M3-3195 (2) [SDK] Change: Volume types

- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
> [Billing] Change "Refund to Card" to "Refund"

- packages/linode-js-sdk/README.md
- packages/linode-js-sdk/src/index.ts
- packages/linode-js-sdk/src/request.ts
- Add setToken helper method so that users don't have to manually
add an interceptor to authenticate requests.
- Update README.md
> [SDK] Add helpers and update docs

- packages/manager/src/components/IconTextLink/IconTextLink.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
adjustment to the linkButton when i is wrapped in a link so it stacks in alignment.
> [Billing] Button alignment when stacking on medium breakpoint 

- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
- Change expiration date placeholder to "MM/YY"
- Accept two digit years when updating payment method expiration date
- Add "optional" placeholder to CVV field
- Close drawer after submit
> [Billing] Accept "MM/YY" for credit card expiration date

- CHANGELOG.md
- packages/api-v4/package.json
- packages/manager/package.json
- packages/manager/src/components/EnhancedSelect/Select.tsx
> Release 1.9.0

- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
Hide the TPA tab behind a feature flag.
If you've never toggled a flag before, reach out for help.
> Hide TPA tab behind feature flag

- packages/manager/src/components/SafeTabPanel/SafeTabPanel.tsx
- packages/manager/src/components/SafeTabPanel/index.ts
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Installation.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/NodeBalancerSummary.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingTableRows.tsx
- packages/manager/src/features/Profile/APITokens/APITokens.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
- packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
- packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
- packages/manager/src/features/Profile/Profile.tsx
- packages/manager/src/features/Profile/Referrals/Referrals.tsx
- packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
- packages/manager/src/features/Profile/Settings/Settings.tsx
- packages/manager/src/features/Users/UserDetail.tsx
- packages/manager/src/features/Users/UserPermissions.tsx
- packages/manager/src/features/Users/UserProfile.tsx
- packages/manager/src/features/Users/UsersLanding.tsx
Edit: This also introduces a new component, `SafeTabPanel` that will only render content based on active tab selection (thanks @johnwcallahan for this addition!)
Switching over to the Reach pattern for the above sections + cleanup. 
> M3-4128 Refactor User details, NodeBalancer details, Profile, Longview landing and details

- packages/manager/src/features/Managed/Contacts/Contacts.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList.tsx
- packages/manager/src/features/Managed/ManagedLandingContent.tsx
- packages/manager/src/features/Managed/Monitors/Monitors.tsx
- packages/manager/src/features/Managed/SSHAccess/SSHAccess.tsx
Refactoring Managed tabs to use Reach instead.
> Managed Tabs Refactor

- CODE_CONVENTIONS.md
Add notes for where commonly used CSS codes are
> CSS file locations

- packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyDialog.tsx
- Remove smart quote.
- Clarify LISH statement.
> TPA copy edits

- packages/manager/src/containers/nodebalancerConfigs.container.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.events.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.reducer.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.requests.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.selectors.ts
- packages/manager/src/store/nodeBalancerConfig/configNode.actions.ts
- packages/manager/src/store/nodeBalancerConfig/configNode.reducer.test.ts
- packages/manager/src/store/nodeBalancerConfig/configNode.reducer.ts
- packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.actions.ts
- packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.containers.ts
- packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.events.ts
- packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.reducer.ts
- packages/manager/src/store/nodeBalancerConfig/nodeBalancerConfig.requests.ts
- packages/manager/src/store/store.helpers.tmp.ts
Includes both NodeBalancer Configs and NodeBalancerConfig Nodes. The Nodes have been in Redux for a while now, but as far as I know have never been used.
NodeBalancer actions should be unchanged.
> Refactor NodeBalancer Redux state

- packages/manager/src/MainContent.tsx
- packages/manager/src/components/BLMBanner.tsx
- packages/manager/src/components/MainContentBanner.tsx
- packages/manager/src/components/SideMenu.tsx
- packages/manager/src/featureFlags.ts
Adding a fixed banner to show support for Black Lives Matter.
> Adding BLM banner

- Dockerfile-e2e
- Dockerfile-storybook
This change is included here as well: https://github.com/linode/manager/pull/6342.
> Remove tslint from Dockerfile

- packages/manager/package.json
- packages/manager/src/components/core/Form.tsx
- packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
- packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
- packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/EditVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx
- yarn.lock
Not too involved but still worth putting in a separate PR. 
The `translate="yes"` thing is one of the worst things I've ever done, but it seems to be the recommended solution: https://github.com/jaredpalmer/formik/issues/2120
We have a version of @types/react that the issue suggests, and variously upgrading other things doesn't seem to help either.
> Bump formik to v.2.1.3

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.styles.ts
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/features/TopMenu/TopMenu_CMR.tsx
There was no ticket for this yet, but the menu to open the sidebar was bothering me (it also still works, with weird effects, so I wanted to hide it before the demo).
I left the right-hand side of the menu unchanged for now, until we have support for profile/events elsewhere. Mobile is still a little sketchy.
> [CMR] TopMenu

- packages/api-v4/.eslintrc.js
- packages/api-v4/src/linodes/actions.ts
I forgot one usage of Ramda when I removed it. We don't notice when using it locally since it can resolve to the version of Ramda in packages/manager.
> Fix: Ramda reference in JS client

- WRITING_E2E_TESTS.md
- packages/manager/cypress/integration/domains/smoke-create-domain-records.spec.ts
- packages/manager/cypress/integration/linodes/rescue-linode.spec.ts
- packages/manager/cypress/integration/linodes/smoke-delete-linode.spec.ts
- packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts
- packages/manager/cypress/integration/nodebalancers/smoke-create-nodebal.spec.ts
- packages/manager/cypress/support/ui/events.ts
Simple basic test checking a rescue process
> first e2e on linode rescue

- WRITING_E2E_TESTS.md
- packages/manager/cypress/support/api/nodebalancers.ts
Doc improvement, and future bug fix
there was no bug as the function is not used yet
> big fix on E2E oauth doc and NodeBal

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/linodeDetailContext.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderLoading.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeWithExtendedLinode.tsx
This reverts commit 86fa6e2fc46f8e1007e97aebe5c413e67447c707.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
> Revert "[For release] Fix 404 issue (#6540)"

- packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
[6502](https://github.com/linode/manager/pull/6502)
> [Update] - M3-4177 - Appending  PR 6502 to change "Warning" to "Note"

- packages/manager/cypress/integration/linodes/rescue-linode.spec.ts
Non breaking change ('update')
> M3-4258 - refactor of rescue test

- packages/api-v4/package.json
- packages/api-v4/src/constants.ts
- packages/api-v4/src/linodes/disks.ts
- packages/api-v4/src/linodes/linodes.schema.ts
- packages/manager/config/webpack.config.prod.js
- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/PasswordInput/PasswordInput.tsx
- packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
- packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
- packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
Update our password validation to match the API.
Includes:
- Remove any validation for passwords based on length and character classes
- Remove any text in the UI that implies that we're checking these
- Include old zxvcbn logic and use complexity to validate passwords
> M3-4241 Update: password validation

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
Adding the new entity landing header to Linodes landing.
> M3-4232 Implement EntityHeader on Linodes Landing

- packages/manager/src/assets/icons/sort-up.svg
- packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.tsx
- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/components/TableRow/TableRow_CMR.tsx
- packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
This fixes the hover state for the up arrow and borders for dark mode.
The hover state for the rows is a bit off in dark mode since there isn't a provided color for that yet.
> [CMR] M3-400: Fixes for Table Styling

- .gitignore
- packages/manager/scripts/pre-push.sh
Reverts linode/manager#6459
Going to try to find a better way to do this.
> Revert "Support for environment switcher"

- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/hooks/useRegions.ts
Tweaks & refinements for Linode Actions column
> M3-4234: Linode Actions column improvements

- packages/manager/src/components/Table/Table.stories.tsx
- packages/manager/src/components/TagCell/AddTag.tsx
- packages/manager/src/components/TagCell/TagCell.stories.tsx
- packages/manager/src/components/TagCell/TagCell.tsx
- packages/manager/src/components/TagCell/TagDrawer.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- packages/manager/src/hooks/useLinodes.ts
Add TagCell, TagDrawer, and associated actions to LinodeRow etc.
> M3-4287 linode table tags

- README.md
> fix link to SDK docs

- packages/manager/src/components/AddNewLink/AddNewLink_CMR.tsx
- packages/manager/src/components/IconTextLink/IconTextLink.stories.tsx
- packages/manager/src/components/IconTextLink/IconTextLink_CMR.tsx
This PR applies the new styles to the "Add a [insert component]" button and currently only exists on [Storybook](http://localhost:6006/?path=/story/icontextlink--cmr).
> [CMR] Add a [insert component] button

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/EntityDetail/EntityDetail.tsx
- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/features/Domains/DomainsLanding.test.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
Please note I based this PR off of the work from here: https://github.com/linode/manager/pull/6607 so that should be merged first. We have been running into some grid issues with the CMR headers in context on landing pages. I've commented throughout on notable changes.
- Bug fix ('repair')
Please test using storybook, Linodes landing (CMR and non), Domains landing (CMR and non).
> M3 Grid header issues for CMR

- packages/manager/src/utilities/isCreditCardExpired.test.ts
- packages/manager/src/utilities/isCreditCardExpired.ts
date is checked to be >= instead of >
also uses luxon instead of date (changing only `>=` did not fix it so i thought it was easier
To test it:
you need to change the CC expiry date
> fix expiry date check

- packages/manager/src/components/ColorPalette/ColorPalette.stories.tsx
- packages/manager/src/components/ColorPalette/ColorPalette.tsx
I thought I would create a way to easier reference and visualize the colors used in the theme, 
[http://localhost:6006/?path=/story/color-palette--default](http://localhost:6006/?path=/story/color-palette--default)
> Reference for colors

- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/components/StatusIcon/StatusIcon.tsx
- packages/manager/src/components/StatusIcon/index.tsx
- packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
- packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
- packages/manager/src/features/Domains/DomainTableRow_CMR.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
Use CMR stuff for Domains listings.
- Took my best guess on which actions should be inline since there are no designs for this
- Some of the styling is in progress pending work in other PRs. Did the best I could but happy to adjust as needed.
> M3-4271 [CMR] Domains landing

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer_CMR.tsx
New Configs table for CMR in the Configs tab
~~Resize, Imagize functionality~~
> M3-4301: Configs table in Configs tab

- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu_CMR.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
Updating K8 Cluster landing to utilize CMR styles. Also made adjustments to border handling for Linodes landing table based on @DevDW 's callout in demo prep.
> CMR Kubernetes clusters landing

- packages/manager/cypress/integration/account/smoke-billing-activity.spec.ts
Fixing broken test as i was testing another e2e
> fix e2e timezones, and selector for billing activity

- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx
Fixes a small regression introduced here: https://github.com/linode/manager/pull/6509/files#diff-9af515d8c2c7ef335d595349bd0dd943R71
> [for release] Fix copy in LinodeRebuild

- packages/manager/cypress/integration/linodes/rescue-linode.spec.ts
> e2e linode detail page changed

- packages/manager/src/components/EntityTable/EntityTable.stories.tsx
- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/components/EntityTable/types.ts
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow_CMR.tsx
- packages/manager/src/features/Firewalls/index.tsx
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/mocks/serverHandlers.ts
CMR style to the Firewalls table. Added a few style tweaks to the EntityTable component and allowed it to accept loading and error props.
Please make sure Domains and Firewalls are the same as before, except for the Firewalls styling.
> M3-4330 [CMR] Firewalls

- packages/manager/cypress/support/ui/common.ts
- packages/manager/cypress/support/ui/constants.ts
These have been buried in the volume test pr but I needed to get it in and get it merged.
> fix for deep link tests. break was caused by cmr changes

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
> Start adding types back

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/containers/withFeatureFlagProvider.container.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
Allow filtering by clicking on the status pills above the Linodes table. Styling still in progress.
> M3-4303 CMR: Filterable pills

- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/MultipleLinodes.tsx
CMR Dashboard view for users with multiple Linodes
> M3-4339: Dashboard view for multiple Linodes

- packages/manager/src/features/Dashboard_CMR/Dashboard.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/LinodeDashboardContent.tsx
Fix to single-Linode view in the Dashboard (feedback from demo prep). @WilkinsKa1 maybe you fixed this already in another PR? If so lemme know and I'll close it out.
> Fix: Add min height to Linodes display on Dashboard

- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
- packages/manager/src/features/Domains/DomainTableRow_CMR.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
This handles responsive styling for CMR Domains landing. 
> M3 4343 Domains table landing: responsive styles

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleAllNodesDialog.tsx
Update copy for recycle nodes action.
> LKE Recycle Nodes copy

- packages/manager/src/LinodeThemeWrapper.tsx
- packages/manager/src/components/Breadcrumb/FinalCrumbPrefix.tsx
- packages/manager/src/components/PasswordInput/HideShowText.tsx
- packages/manager/src/components/PromiseLoader/PromiseLoader.tsx
- packages/manager/src/components/core/Divider.tsx
- packages/manager/src/features/Images/ImageSelect.test.tsx
- packages/manager/src/features/Images/ImageSelect.tsx
- packages/manager/src/features/linodes/CloneLanding/Details.tsx
- packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx
- packages/manager/src/store/notification/notification.reducer.ts
- packages/manager/src/utilities/haveAnyBeenModified.ts
- packages/manager/src/utilities/images.test.ts
- packages/manager/src/utilities/images.ts
Needed something soothing to do on Friday afternoon
> Fix: Linter errors

- yarn.lock
https://github.com/linode/manager/network/alert/yarn.lock/lodash/open
> fix lodash vuln

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
Not much to say other than applying the CMR styles to another table and hiding the Protocol and Port Range columns mobile views.
> [CMR] M3-4349: Table styles for Firewall Rules

- packages/manager/src/dev-tools/dev-tools.css
Make devtools stick to the bottom of the view
> Make devtools stick to the bottom of the view

- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow_CMR.tsx
Hide inline actions and the Rules and Linodes column for mobile view
> [CMR] M3-4348: Add responsiveness to Firewall Landing table

- package.json
- yarn.lock
This should fix the builds.
What I did:
1. Update package.json resolutions.
2. `yarn install`
> Resolve dot-prop version

- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceRow_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
Applying CMR table styles to Firewall / Linodes
> [CMR] M3-4350: Table styles for Firewall Linodes

- packages/manager/package.json
- yarn.lock
removing warning in console when running `yarn up` about `caniuse-lite`
> fix caniuse-lite warning

- packages/manager/cypress/integration/linodes/smoke-create-linode.spec.ts
- packages/manager/cypress/integration/linodes/smoke-delete-linode.spec.ts
quick fix for delete e2e test that was broken
> M3 4398 update delete linode test

- packages/manager/cypress/integration/linodes/smoke-create-linode.spec.ts
test wasn't working. now it should be working
> a few small updates for create nanode test to get it working again

- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/NotificationCenter/PastDue.tsx
Use APIRequest hook to get most recent invoice on DashboardNotifications.
> M3-4310 Dashboard plumbing 

- packages/manager/src/hooks/usePreferences.ts
Because why not?
Going to use this to dismiss the changelog once #6720 is merged.
> Add usePreferences hook

- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/NotificationCenter/Alerts.tsx
- packages/manager/src/features/NotificationCenter/Maintenance.tsx
- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
- packages/manager/src/features/NotificationCenter/index.tsx
> CMR Dashboard: Remove Alerts from notifications center/drawer

- packages/manager/src/components/Dialog/Dialog.tsx
- packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
Add a prop to Dialog.tsx that makes the dialog fill the available screen height. So far only applied to MigrateLinode.
> Dialog full height

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
Another oversight from an earlier PR.
> Wire events into the drawer

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
This was preventing the API pagination from doing its thing, I completely forgot about it in the initial PR.
> Don't prefetch domains for a large account

- packages/manager/src/features/Help/Panels/PopularPosts.tsx
This changes one of the popular posts so that it points to SMTP restrictions. Making these restrictions more visible is the goal. There is no corresponding Jira task.
> Update Popular Posts 'update'

- packages/manager/src/components/TableCell/TableCell_CMR.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
- packages/manager/src/features/Support/SupportTickets/TicketList_CMR.tsx
- packages/manager/src/features/Support/SupportTickets/TicketRow_CMR.tsx
Applying CMR table styles for tickets landing- this includes responsive styles as well. Please note that no action menu is present.
> CMR table styles for Support Tickets

- packages/api-v4/package.json
- yarn.lock
Yup types need to be distributed with the package or else consumers of
the application will need to install separately.
> fix missing yup types dependency

- packages/api-v4/package.json
- yarn.lock
This was merged to develop yesterday, but we should have included it in the release. Moves @types/yup from devDependencies to dependencies.
Possible this will result in weirdness when merging the release branch back into develop.
> For release: Yup types

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
> Release v1.16.1

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/types.ts
• Versioning & Changelog for 1.16.2
• Fix to clear UDF data on tab change
• Fix for form fields issue on One-click Apps and StackScripts creation flows
> Release v1.16.2

- packages/manager/cypress/integration/volumes/smoke-create-volumes.spec.ts
**How to verify that that the test works:**
- yarn up
- yarn cy:debug
- Choose test file(s) in the cypress test runner
- Test(s) should pass
**Extra check (runs headless):**
- yarn cy:e2e -s <test file(s)>
Make sure your .env contains:
REACT_APP_LOGIN_ROOT='https://login.linode.com'
REACT_APP_API_ROOT='https://api.linode.com/v4'
REACT_APP_APP_ROOT='http://localhost:3000'
REACT_APP_LAUNCH_DARKLY_ID='*************************' (CMR flag)
REACT_APP_CLIENT_ID='********************' (https://cloud.linode.com/profile/clients, copy ID)
MANAGER_OAUTH='**************************************************************************' 
(create in https://cloud.linode.com/profile/tokens > "Add a Person Access Token", Save the token that appears in the modal, you …
> a couple small fixes for volumes tests

- .github/workflows/cloud.yml
> poc actions

- packages/manager/src/components/TableCell/TableCell_CMR.tsx
- packages/manager/src/features/Profile/APITokens/APITokenMenu_CMR.tsx
- packages/manager/src/features/Profile/APITokens/APITokenTable_CMR.tsx
- packages/manager/src/features/Profile/APITokens/APITokens.tsx
Applying CMR styles and responsiveness to the API Tokens table
> [CMR] M3-4359: Table styles for Profile > API Tokens

- packages/manager/src/features/Profile/OAuthClients/OAuthClientActionMenu_CMR.tsx
- packages/manager/src/features/Profile/OAuthClients/OAuthClients_CMR.tsx
- packages/manager/src/features/Profile/Profile.tsx
Applying CMR styles and responsiveness to the OAuth Apps table
> [CMR] M3-4360: Table styles for Profile > OAuth Apps

- packages/manager/src/features/Volumes/VolumesLanding_CMR.tsx
Implement `useReduxLoad` in `VolumesLanding_CMR.tsx` for logic governing loading state
> M3-3961: Implement useReduxLoad in VolumesLanding

- packages/manager/src/features/Managed/Contacts/ContactsActionMenu_CMR.tsx
- packages/manager/src/features/Managed/Contacts/ContactsRow_CMR.tsx
- packages/manager/src/features/Managed/Contacts/ContactsTableContent_CMR.tsx
- packages/manager/src/features/Managed/Contacts/Contacts_CMR.tsx
- packages/manager/src/features/Managed/ManagedLandingContent.tsx
Applying CMR styles and responsiveness to the Contacts table
- ActionMenu items have been moved to inline
- Group column is hidden first, followed by Primary and Secondary Phone
> [CMR] M3:4355: Table styles for Managed > Contacts

- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Users/UsersActionMenu_CMR.tsx
- packages/manager/src/features/Users/UsersLanding_CMR.tsx
CMR Table Styles for Account > Users
> M3-4272: CMR Table Styles for Account Users

- packages/manager/src/components/StatusIcon/StatusIcon.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
- packages/manager/src/mocks/serverHandlers.ts
Made the "other" statuses blink and included some mock linodes for easier testing
> [CMR] M3-4306: Blinking pending statuses

- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel_CMR.tsx
CMR Table Styles for the Billing & Payment History table
> M3-4272: CMR Table Styles for Billing

- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
We have a doc url now, though it still 404s since the doc itself isn't published yet.
> Update Firewall doc URL

- packages/manager/src/components/Button/Button.tsx
- packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel_CMR.tsx
Follow-up to https://github.com/linode/manager/pull/6825 addressing [feedback](https://github.com/linode/manager/pull/6825#pullrequestreview-477675983)
Modifies `InlineMenuAction` component to use `Button` component instead of `button` element and take a `loading` prop; use it in `BillingActivityPanel_CMR.tsx` and clean up button styling
> M3-4272: Improve Download button in BillingActivityPanel

- packages/manager/src/features/Users/UsersLanding_CMR.tsx
Remove styling that increases gravatar size at medium & larger breakpoints
> M3-4515: Decrease gravatar size in Accounts > Users table

- packages/manager/src/features/Profile/APITokens/APITokenTable_CMR.tsx
Sort tokens on `My Profile > API Tokens` by label, date created or expiry
> [CMR] M3-4433: Make API tokens table sortable

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
Commenting this out- will add later when final copy has been decided.
> For demo: commenting out FW copy

- packages/manager/src/features/Profile/OAuthClients/OAuthClients_CMR.tsx
Sort apps on `My Profile > OAuth Apps` by label
> [CMR] M3-4436: Make OAuth apps table sortable

- packages/manager/src/features/OneClickApps/FakeSpec.ts
You have to fake the name change to the MySQL stackscript to see the drawer open with this change, reach out if you need a patch or etc.
> Update MySQL info to clarify that we install MariaDB

- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
Thanks to @asauber for catching this.
Fixes "2 RAM"
> Fix copy in Linode Entity Detail

- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
In the AddNewMenu, Create -> Kubernetes should be Create -> Kubernetes Cluster
- Fix
> Fix, Change "Create Kubernetes" to "Create Kubernetes Cluster"

- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable_CMR.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Apply CMR Header to Object Storage Access Key and Buckets landing pages
> M3-4489: CMR Header for Object Storage > Buckets & Object Storage > Access Key

- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
Fixes a regression introduced here: https://github.com/linode/manager/commit/68761773892d4d0c9a0c49005d22706dc2bd18e9#diff-abe388724bac6662531eddab5b0bb68cR581
> Fix StackScript waypoint scrolling

- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow_CMR.tsx
CMR table styles for table on Bucket Detail page
> M3-4505: CMR Table Styles for OBJ Bucket Detail

- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.test.tsx
- packages/manager/src/utilities/groupByTags.ts
I removed the consecutive occurrences of 'the' on 3 different files.
> Fix typos: consecutive occurrences of 'the'

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/features/Vlans/VlanLanding/VLanRow.tsx
- packages/manager/src/features/Vlans/VlanLanding/VlanLanding.tsx
- packages/manager/src/features/Vlans/VlanLanding/index.ts
- packages/manager/src/features/Vlans/index.tsx
I commented out the conditionals that hide this feature for review purposes, will add back before I merge. As described, very basic component structure for VLAN landing. 
> VLAN Landing Skeleton

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Conditionally hides the status chip based on count for Linode Landing.
> M3-4518 Hide status filter if no linode has that status

- packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
Add a link to the docs. Final link coming shortly.
> Add docs link for Object Storage SSL/TLS

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
Super small fix, adding a tooltip to the sort button in the notifications drawer.
> CMR: Tooltip for sort in Notifications drawer

- packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
- packages/manager/src/mocks/testBrowser.ts
Removing the `display: flex` fixed it
> [CMR] M3-4573: StackScripts ActionMenu is offset on mobile

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
Change the speed of the animation to more resemble a heartbeat/pulse
Please compare with the animation in the prototype, would love some feedback!
> [CMR] M3-4571: Adjust animations for pending actions

- packages/manager/.env.example
Following our tech talk, adding more examples to the `.env.example` file.
> Add more examples to .env.example

- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
> Make VLAN IP column sortable

- packages/manager/src/hooks/useVlans.ts
Rename the `interface` in `useVlans.tsx` appropriately
> Rename interface appropriately in useVlans hook

- packages/api-v4/src/databases/databases.schema.ts
- packages/api-v4/src/databases/databases.ts
- packages/api-v4/src/databases/types.ts
- packages/api-v4/src/vlans/vlans.ts
JS Client stuff for DbaaS.
Some things are _not_ here, because either the API doesn't support them or we're not likely to work on them for a while and I'm not sure the API is stable, namely:
- Methods for backups
- Method for resizing
> M3-4614 Add: JS Client methods and types for DbaaS

- packages/api-v4/src/account/types.ts
- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/assets/icons/resize.svg
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/index.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseDetail.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseDetailNavigation.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/index.ts
- packages/manager/src/features/Databases/DatabaseDetail/index.ts
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
- packages/manager/src/features/Databases/DatabaseLanding/index.ts
- packages/manager/src/features/Databases/index.tsx
Added routing and created very basic components used in the Database Landing and Details page
> M3-4598: DBaaS Routing + Skeleton

- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
- packages/manager/src/index.css
Got the actual specs for the Linode busy pulse animation from Jay so updating it to match
> [CMR] Refine pending actions animation

- packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard_CMR.tsx
- packages/manager/src/features/Search/ResultGroup.tsx
- packages/manager/src/features/Search/ResultRow.test.tsx
- packages/manager/src/features/Search/ResultRow.tsx
- packages/manager/src/features/Search/SearchLanding.tsx
- yarn.lock
Updating search results landing with CMR styles. 
> Applying CMR table components to search results landing

- packages/manager/src/constants.ts
This is the search link used in /support/search.
> Update docs search url

- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
Please check with a non-restricted user, a restricted user with no access / read access / read+write access to account.
> M3-4634 Change: Hide billing section of dashboard for users without account access

- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
From demo prep, for consistency. This is likely to change later down the road so I'm just commenting it out for now.
> For demo: removing status column on Dbaas backups table 

- CODE_CONVENTIONS.md
I was reading through your Code Conventions document and found this silly typo.
> Fix code typo in Paginating Things example

- packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
Removing custom focus state that was causing regression.
> For release: Linode Power Control visual regression

- packages/manager/src/constants.ts
This had already been done (old ticket); I deleted unused variables here (threw in LKE while I was at it) and opened a separate PR to clean up our build configs.
> M3-3951 Remove all conditional display logic from OBJ

- CHANGELOG.md
- packages/api-v4/CHANGELOG.md
I made a few on the fly edits to the changelog before publishing the [GitHub release](https://github.com/linode/manager/releases/tag/linode-manager%40v1.24.0); up for review here. Whatever changes are requested here I will edit the release as well (and in the Developers Site PR).
> Update Changelog to match GH release

- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/EntityTable/EntityTableHeader.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/components/EntityTable/types.ts
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow_CMR.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
We've needed an additional hideOnTablet prop to handle for tablet styling on the entity table component. This adds that in and makes adjustments for the NB table (CMR).
> Add hideOnTablet prop for Entity Table Component

- packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsLabelPanel.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsPasswordPanel.tsx
- packages/manager/src/store/databases/databases.actions.ts
Cleanup based on feedback left on [https://github.com/linode/manager/pull/7046](https://github.com/linode/manager/pull/7046) including:
- Resetting success state when the panel opens
- Resetting password input
> DBaaS Details Settings tab feedback

- packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
Also cleaned up the Create DBaaS modal a bit so it's more consistent with the DBaaS Settings tab (mostly margins and removing the underscore from timezones)
> M3-4642: Maintenance window and day selection should be inline

- packages/manager/e2e/pageobjects/linode-detail/linode-detail-settings.page.js
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
Fixing typos to resolve PDI-1657
> Fixing typos to resolve PDI-1657

- packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
- packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
New copy explaining restrictions for new credit cards. Follows: https://github.com/linode/docs/pull/3742/files
The drawer-on-drawer pattern is not something we normally do, but it honestly kind of works here. Open to feedback.
> Add copy explaining CC address restrictions

- packages/manager/src/components/Accordion/Accordion.stories.tsx
- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.stories.tsx
- packages/manager/src/components/Breadcrumb/Breadcrumb.stories.tsx
- packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.stories.tsx
- packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.tsx
- packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.tsx
- packages/manager/src/components/Notice/Notice.stories.tsx
- packages/manager/src/components/TabbedPanel/TabbedPanel.stories.tsx
- packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
- packages/manager/src/themeFactory.ts
Went through and fixed broken stories (with the exception of two, both having to do with snackbar). I also added the light theme color palette in addition to updating our global buttons to match the new CMR button style.
To test, run yarn storybook and go through the stories. There are 2 that will throw errors as I mentioned above:
> Storybook cleanup

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
- packages/manager/src/components/DocumentationButton/DocumentationButton.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
- packages/manager/src/features/Profile/Profile.tsx
- packages/manager/src/features/Search/ResultGroup.tsx
- packages/manager/src/features/Search/SearchLanding.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel_CMR.tsx
- packages/manager/src/features/Support/ExpandableTicketPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
This is to reduce the content width from 1280px to 1100px for CMR. 
> Reducing content width to 1100px

- packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
- packages/manager/src/themeFactory.ts
Table sort cell icon color was off for CMR- this addresses that.
> For release: Fixing table sort cell icon colors

- packages/manager/src/dev-tools/FeatureFlagTool.tsx
Firewalls now has a corresponding account capability, but Databases does not.
> Dev Tools: database feature flag toggle

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- packages/manager/src/themeFactory.ts
Removing tags column from Linode list (table) landing view and removing status filter functionality (the status counters will be static now)
> Linode List Landing Adjustments

- packages/manager/src/factories/support.ts
- packages/manager/src/features/Support/SupportTickets/TicketList.test.tsx
- packages/manager/src/features/Support/SupportTickets/TicketList_CMR.tsx
This adds some basic tests for TicketList.
> M3-1184 Support unit tests

- packages/manager/src/initSentry.ts
Ignore a few noisy "bugs":
- Local Storage errors
- Network Errors resulting in "Unexpected end of script" bugs
> M3-3494 Ignore some more Sentry errors

- packages/manager/src/components/EntityDetail/EntityDetail.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Vlans/VlanDetail/VlanDetail.tsx
- packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/RenderIPs.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/themes.ts
Fixed the regressions on the VLAN and DBaaS details page. I tried to prevent scope creep but I made a few adjustments to the LinodeEntityDetail and the landing pages (ie. chips) since they were all related
> Detail Entity Regressions (mainly on VLANs and DBaaS)

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/assets/community.svg
- packages/manager/src/assets/primary-nav-help.svg
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/TopMenu/Community.tsx
- packages/manager/src/features/TopMenu/Help.tsx
- packages/manager/src/features/TopMenu/NotificationButton.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.styles.ts
- packages/manager/src/features/TopMenu/TopMenu_CMR.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu_CMR.tsx
- packages/manager/src/features/TopMenu/iconStyles.ts
> New profile menu drop down

- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.styles.ts
- packages/manager/src/features/TopMenu/UserMenu/UserMenu_CMR.tsx
- packages/manager/src/features/TopMenu/iconStyles.ts
- Fix the badge icon for notifications in the top menu so that
it's dynamic and the text doesn't overflow the badge for any number
of events
- Add the username inline next to the user menu (hidden on mobile).
- Remove the display-username-on-hover logic
> Fix top menu

- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
This ditches the Linode Status Pills for good and tightens up the Create Menu spacing (final copy still TBD):
> Remove status pills, tighten up spacing in Create Menu

- packages/manager/cypress/integration/images/smoke-create-image.spec.ts
- packages/manager/cypress/support/ui/constants.ts
**How to verify that that the test works:**
- yarn up
- yarn cy:e2e **(runs headless)**
Make sure your .env contains:
REACT_APP_LOGIN_ROOT='https://login.linode.com'
REACT_APP_API_ROOT='https://api.linode.com/v4'
REACT_APP_APP_ROOT='http://localhost:3000'
REACT_APP_LAUNCH_DARKLY_ID=(CMR flag)
REACT_APP_CLIENT_ID=(https://cloud.linode.com/profile/clients, copy ID)
MANAGER_OAUTH=(create in https://cloud.linode.com/profile/tokens > "Add a Person Access Token", Save the token that appears in the modal, you will only see it once)
> Daily Updates

- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Now, going to localhost:3000/account/billing/make-payment should bring you to the billing page with the drawer open.
> Open the payment drawer at /account/billing/make-payment

- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- Copy icon is the size of the entire cell
- Separate AccessTable into its own component
- Fix text selection on double-click
> Linode Detail Header feedback

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/Firewalls/index.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenuItem.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
A few items from demo feedback/Trello:
- Remove trailing periods in Create Menu
- Add margin to group name in Group By Tag list view
- Add “Buckets” to search hint text
- Add “Firewalls” and “Buckets” to create menu
- Default page for Managed users is Managed
Note: the “Buckets” option doesn’t work yet… it needs to be wired up to Redux. Will come back to this after the demo.
> Demo feedback items

- packages/manager/src/MainContent_CMR.tsx
Re-add MainContentBanner to the CMR version of MainContent
> Add MainContentBanner to CMR Main Content

- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
NodeBalancer config nodes: (editing or creating a NB config)
- Replace "Remove" button with link styles
- Add inputId to prevent DOM validation error (duplicate id elements)
Create Domain modal:
- Change button from Create -> Create Domain
> Change: Assorted Trello tasks

- packages/manager/src/components/TableRow/TableRow_CMR.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
> Longview buttons & table fixes

- packages/manager/src/components/MainContentBanner.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
I hadn't looked at these with the PrimaryNav opened (which makes the table narrower).
Please check all kinds of scenarios (I restored a few mocks as well).
> Adjust Linode Table cell widths

- packages/manager/src/features/Managed/ManagedLandingContent.tsx
The bug I thought I found here was just a mock service worker thing. But while I was there I cleaned up a bit.
> Change: Clean up CMR stuff in ManagedLandingContent

- packages/manager/config/testSetup.js
- packages/manager/package.json
- packages/manager/src/components/GaugePercent/GaugePercent.tsx
- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedChartPanel.tsx
- packages/manager/src/features/Users/UserPermissions.tsx
- packages/manager/src/utilities/charts.ts
- yarn.lock
This reverts commit 96e0fa20d56f2453740adefab6cf48fa5707f2d4 (https://github.com/linode/manager/pull/6591)
Make sure to re-yarn up.
> hotfix: Revert "Upgrade: Chart.js 3.0 (beta)"

- packages/manager/src/components/ColorPalette_CMR/ColorPalette_CMR.tsx
- packages/manager/src/components/EntityDetail/EntityDetail.tsx
- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/EntityHeader/HeaderBreadCrumb.tsx
- packages/manager/src/components/TabLinkList/TabLinkList.tsx
- packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
- packages/manager/src/components/TableRow/TableRow_CMR.tsx
- packages/manager/src/components/TagCell/TagCell.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
- packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.styles.ts
- packages/manager/src/features/TopMenu/TopMenu_CMR.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
This is the first step of cleaning refining the colors used. The scope of this PR includes removing unused or duplicate color variables and combining similar colors
The next steps which will be addressed in a separate PR will include making sure the colors meet a11y standards and combining the non-CMR and CMR palettes with better naming conventions
> Clean up CMR color palette

- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.test.tsx
- packages/manager/src/components/TagsInput/TagsInput.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
- packages/manager/src/features/Search/ResultRow.test.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
- packages/manager/src/mocks/serverHandlers.ts
Clean console noise in the unit test runs.
> Fix: Unit test maintenance

- packages/manager/src/components/TabLinkList/TabLinkList.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation_CMR.tsx
- Increase spacing between Entity Detail and tabs
- Decrease spacing between tabs and tab content
- Networking Tab: Reduce whitespace and the height of the graphs
> M3-4765: Linode Detail adjustments

- packages/manager/src/App.tsx
- packages/manager/src/GoTo.tsx
- Styling bug on hover state
- Fix order, add "Help & Support"
- Fix `hidden` functionality (wasn't actually doing anything)
> Fix bugs in GoTo component

- packages/manager/src/components/Toggle/Toggle.stories.tsx
- packages/manager/src/components/Toggle/Toggle.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
> M3-4794: Update toggle switch

- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/Firewalls/index.tsx
> Revert query changes to firewalls landing and detail

- packages/api-v4/src/kubernetes/kubernetes.ts
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleAllPoolNodesDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleAllClusterNodesDialog.tsx
- packages/manager/src/hooks/useDialog.ts
Placement is temporary (may be part of the updated cluster summary header) but the functionality will be more or less this.
> Add: Button to recycle all nodes in a cluster

- .github/workflows/e2e.yml
I made a small mistake on the last pr. nothing that will do any harm. it just won't run. This one should work. I hope. changed time for testing purposes and if it works then I'll do one more pr to change the time to the evening instead.
> M3 4577 initial e2e actions workflow

- packages/manager/src/components/StackScript/StackScript.test.tsx
- packages/manager/src/components/StackScript/StackScript.tsx
Add copyable StackScript ID field to StackScript Details page
> M3-4777: Add copyable StackScript ID field to StackScript Details page

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/utilities.tsx
Update language regarding GPU instances
> M3-4732: Remove "Pilot" language from GPU tab under Linodes

- packages/manager/src/containers/kubernetes.container.ts
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.test.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
- packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
- packages/manager/src/features/Kubernetes/kubeUtils.ts
- Move upgrade modals to separate component
- Add modals to ClusterList
- Fix types of kubernetes.container to match what was actually used
- Add (conditionally) "upgrade" chip to ClusterRow
> M3-4787 Part 2: Add upgrade functionality to LKE list view

- packages/api-v4/src/firewalls/types.ts
- packages/manager/src/components/EnhancedSelect/Select.styles.ts
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
Add “Label” and “Description” fields to FW Rule Drawer and Table.
TODO:
> M3-4783: Add Label and Description fields to FW rules

- packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
Differences can be seen on NB landing and LKE landing
> Allow custom top margin for TransferDisplay component

- packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
- packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
- packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
> Clean up; close notification drawer when an event is clicked

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
> Change wording for OBJ utilization

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Change to card view at an earlier breakpoint to prevent the label from wrapping
> Prevent SelectPlanPanel wrap in Linode Create flow

- packages/api-v4/src/account/types.ts
- packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
Filter out the noisiest events. Others can be added to the array based on further discussion offline.
> Filter unwanted events

- packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
- packages/manager/src/features/NotificationCenter/NotificationData/notificationUtils.tsx
- packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.test.ts
- packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
- packages/manager/src/mocks/serverHandlers.ts
Follow-up to https://github.com/linode/manager/pull/7364 to improve formatting of Notification section items and more closely match the mockup:
> M3-4839: Notifications section in Notifications drawer follow-up

- packages/api-v4/src/firewalls/firewalls.schema.ts
- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/shared.test.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/shared.ts
This is mostly working; I'm going to hold off on finishing touches etc. until we've gotten some feedback on the approach, since some of the possibilities I've discussed offline would require throwing out most of this logic.
> M3-4784 Add: port presets in FirewallRuleDrawer

- packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
- packages/manager/src/components/SelectableTableRow/index.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferHeader.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/transferReducer.ts
Putting this up to get some feedback on the general approach before I get too far down the rabbit hole.
Q: Does this match the designs?
A: No
Q: Does it include all the important functionality?
A: lol no
Q: Does it use real data?
A: also no
Q: Is it hideous?
A: God yes
Q: Is the code clean and tested at least?
A: Stop hounding me
Q: What does it do, exactly?
A: You should be able to select all/some entities, deselect them, and submit the form to generate a payload.
- Is the abstraction for the tables worth it? I'm hoping to simplify the process for adding other entity types down the road but the savings is kind of marginal.
- What about the table row with a checkbox? Same reason, we want to do bulk actions everywhere eventually so I thought it would be helpful to have, but the actual …
> M3-4900 Add: Create new entity transfer (Skeleton)

- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
Includes styling along with the max-width and scroll behavior discussed offline. The fake data has been updated so that if you click the select all box you can see the scroll behavior.
> M3-4900 Change: Styling for transfer checkout bar

- packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferHeader.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
> Styling for transfer controls

- packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
Searchbar isn't there yet, data is still static, and mobile is a work in progress (because the checkout bar is in a separate PR). But the table itself should match the designs now.
> M3-4900 Table style for Create Transfer page

- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
Fix the alignment of the ActionMenu on the Firewall Landing page for mobile
> M3-4739: Fix Firewall Landing ActionMenu

- packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
> Fix link target

- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
- packages/manager/src/hooks/usePagination.ts
- packages/manager/src/queries/linodes.ts
The pagination footer is the style currently in use, and doesn't match the designs. As Matthew says in the comment on the design, the new footer style shouldn't be a blocker for getting this feature out.
> M3-4900 Add real data and pagination to the Transfer table

- packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
- packages/manager/src/components/CopyableTextField/index.ts
- packages/manager/src/components/DialogTitle/DialogTitle.tsx
- packages/manager/src/components/InformationDialog/InformationDialog.tsx
- packages/manager/src/components/InformationDialog/index.ts
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx
- packages/manager/src/features/Profile/Referrals/Referrals.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumesInstruction.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
If you could create a transfer, which you can't, you would see this modal afterwards. The data here is fake, this is just to get the modal working and looking correct.
The modal will open automatically on this branch if you go to /account/transfers.
> Create Transfer Success Modal

- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
Add a search bar that uses API filtering to let you uh search for things in the Create Transfer view.
> Search bar

- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.test.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.tsx
- packages/manager/src/index.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/entityTransfers.ts
This PR adds the Transfers Pending, Received, and Sent tables to the Transfers landing page.
> M3-4896/M3-4897: Transfers Pending, Received, & Sent tables

- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
You should be able to create a transfer. Until #7397 is merged you'll have to use the mock service worker; until #7399 is merged this diff will look very messy.
> M3-4900 Connect the wires

- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
> Hide the X (close button) in TransferCheckoutBar rows except on hover

- packages/manager/src/components/Button/Button.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Add variant for button with outline and apply it to "Cancel Backups" button. Also disable "Take Snapshot" and "Save Schedule" button until a change has been detected
> M3-4792: Linode Detail > Backups buttons

- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
- packages/manager/src/features/EntityTransfers/TransfersPendingActionMenu.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.tsx
Add the Cancel Transfer modal with a fully functional cancellation flow.
> M3-4905: Cancel Transfer modal

- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.tsx
> Mobile transfer controls 2

- packages/manager/.prettierrc
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
- packages/manager/src/utilities/scrollErrorIntoView.ts
Got started adding the Network Interfaces section here and decided to make life more difficult for myself, so here we are. Functionality should be unchanged (except for the empty interfaces section I'll add to later).
> M3-4937 Change: Refactor LinodeConfigs drawer to an FC that uses Formik

- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Got a little too optimistic in an earlier PR, we should hide this section for demo/release.
> Vlan stuff won't be ready for the upcoming release

- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.tsx
Copy edits we discussed during demo prep today.
> Entity Transfer Copy Edits

- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Account/index.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferHeader.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferTable.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferDetailsDialog.tsx
- packages/manager/src/features/EntityTransfers/TransfersTable.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
- packages/manager/src/utilities/ga.ts
This renames all **user facing** references. We can rename filenames etc. as a TDT thing down the line.
> Rename Entity Transfers to "Service Transfers"

- packages/manager/src/LinodeThemeWrapper.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/utilities/ga.ts
- Send (debounced) event after clicking "Copy Transfer Token"
- Send (debounced) event after clicking "Copy Draft Email"
Also did some eslint cleanup of the ga.ts file.
> Add additional analytics for EntityTransfers

- .github/workflows/ci.yml
> Remove caching from build validation step of CI

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
To test, schedule a migration in admin (test account 4 has one pending). Visit the Linode's detail page and click the link in the banner.
> Add confirmation dialog when entering the migration queue

- packages/api-v4/src/firewalls/firewalls.schema.ts
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.test.tsx
Only L80 is changed, rest is linter.
> Update FW schema to account for required label

- packages/api-v4/src/linodes/types.ts
- packages/manager/src/factories/linodeConfigInterfaceFactory.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
- packages/manager/src/queries/vlans.ts
> M3-4937 Add: Interfaces section to Linode Configs modal

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.test.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
...and change default inbound Policy to "ACCEPT".
> Remove default Firewall rules

- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
The alignment was slightly off when the width was > 1280px
> M3-5015: Fix alignment on Longview Landing filter input

- packages/manager/src/components/Notice/Notice.tsx
- packages/manager/src/factories/statusPage.ts
- packages/manager/src/features/Help/StatusBanners.test.tsx
- packages/manager/src/features/Help/StatusBanners.tsx
- packages/manager/src/mocks/serverHandlers.ts
And adjust mocks for tomorrow's demo
> Add tests for banners

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
Change the eth0 details ("Public", "Public, Private") from all capital letters.
> Demo prep feedback: Fix casing for eth0 in Configurations table

- packages/api-v4/.eslintrc.js
- packages/api-v4/src/linodes/linodes.schema.ts
- packages/api-v4/src/request.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
- packages/manager/src/utilities/formikErrorUtils.ts
Fix the linodeInterfaceSchema and error paths in the InterfaceSelect
You should be able to submit the Add Config form (using alpha services).
> Fix schema and error handling for interfaces

- packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
- packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
Changes include:
- M3-5004: Fix Service Transfer controls wrapping in between breakpoints
- M3-5005: Fix pagination height on the Make a Service Transfer page
- M3-5006: Remove tab/spacing for Step 3 in the Service Transfer draft email
> Service Transfers related UI changes

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
Removed the extra padding surrounding the pagination in the Linodes Landing group by tag view and fixed the alignment for the Linode Detail graphs
> UI fixes for Linode pagination and graphs

- packages/manager/src/features/StackScripts/Partials/StackScriptTableHead_CMR.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
- packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
StackScripts is a nightmare but I managed to wrangle the UI into something more consistent with our current style. Noticeable changes include decreasing the font sizes, updating the image chips, and better responsiveness.
Please check the Linode Create From StackScripts page and both the tabs on the StackScripts Landing page at different viewports. 
I'll also be releasing another PR ([https://github.com/linode/manager/pull/7528](https://github.com/linode/manager/pull/7528)) to cleanup the remaining CMR files for StackScripts.
> M3-4963: StackScripts Refinements

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
> M3-4959 Change: Hide CPU and Disk IO graphs from the analytics view for metal instances

- packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
Add VLAN helper text to the Linode Create flow:
And the Config Modal:
> VLAN helper text

- .github/workflows/e2e.yml
- packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts
> E2e LKE test update

- packages/manager/src/features/Users/UserPermissions.tsx
> M3-4872: Fix the wrapping for Account > User Permissions > Specific Permissions

- packages/api-v4/src/linodes/linodes.schema.ts
See ticket for details; edit a config, change only the IPAM address of a vlan, and submit. Doesn't go through in develop, but will here.
> Fix: editing VLAN configs

- packages/manager/src/features/Domains/DeleteDomain.tsx
- packages/manager/src/features/Domains/DomainActionMenu.tsx
Left align the inline "Enable/Disable" actions and change the "Delete" button in the Edit drawer
> M3-5021: Domains related UI stuff

- packages/api-v4/src/linodes/linodes.schema.ts
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/Images/ImageSelect.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Per Chris's suggestion, be a little clearer about the required format for IPAM addresses.
> Change: Add placeholder and tooltip to clarify IPAM address format

- packages/api-v4/src/account/types.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/eventMessageGenerator_CMR.tsx
> M3- 5060 Add event handling for image_upload events

- packages/manager/src/components/StackScript/StackScript.tsx
- packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
Shift the username up 1px so that it's aligned with "StackScripts" and the title
Also refactored the component for funsies and fixed the background color
> M3-4985: StackScripts Details breadcrumb alignment

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
Will address the different units for the IPv4 and IPv6 graphs in a separate PR
> Feedback: Remove redundant title from Linode Details Analytics tab

- packages/manager/src/features/Images/ImagesLanding.tsx
Adds helper text to the manual images table
> add helper text to manual images table

- packages/manager/src/MainContent.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/Images/ImageUpload.tsx
- packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
- packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
- packages/manager/src/features/Images/ImagesCreate/ImageCreateContainer.tsx
- packages/manager/src/features/Images/ImagesCreate/ImagesCreateContainer.tsx
- packages/manager/src/features/Images/ImagesCreate/index.ts
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/Images/index.tsx
- Create new "Images / Create" page at `/images/create`
- Make "/images*" to "/images" redirect & Create button behavior conditional on `machineImagesEnabled`
> M3-5045: Images Create page

- packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Gravatar displays to the left of the username instead of the right
> M3-4950: Swap order of username and gravatar

- packages/manager/src/features/Images/ImageRow.tsx
Per demo feedback, rename "Available" to "Ready"
> M3-5076: Label available Images as "ready"

- packages/manager/src/features/Images/ImagesLanding.tsx
Revised, more precise helper text developed in collaboration w/ John and Jackley. The linked guide will be updated next week with more Automatic Images information.
> M3-5079: More precise helper text on Images Landing

- packages/manager/src/components/TagCell/TagCell.tsx
Check the tags for different breakpoints but especially > 1200px
> M3-5103: Fix Linode Details tags collision

- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
- Reduce size of copy to 14px and add spacing around it
- Make button match style used in the Rules tab
> M3-4917: Firewalls Linodes tab refinements

- packages/manager/src/components/core/Paper.tsx
- packages/manager/src/containers/SummaryPanels.styles.ts
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Adds a 1px border to the top 3 papers in account billing and adjusts spacing between the 3 rows
Click on `Account` on the left nav
> M3-5035: Add box rule and adjust spacing in account billing

- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Profile/AuthenticationSettings/TPADialog.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
Manually add Linode as a provider to reduce repetitive code and make it easier to read. Also conditionally hide text that contains "Google" until TPA is actually released
> TPA Feedback

- .github/workflows/ci.yml
- packages/api-v4/webpack.config.js
Publishes the validation library on merge to master if the version is different from the currently published package.
> Add publish action for @linode/validation

- CHANGELOG.md
- packages/api-v4/package.json
- packages/manager/package.json
- packages/validation/package.json
To test:
Build and test the app, make sure everything is working correctly.
> Hotfix: update "main" in Validation package.json

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Search/useAPISearch.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/store/selectors/getSearchEntities.ts
> Sync master -> develop

- packages/manager/src/features/Images/ImagesLanding.tsx
The default sorting for Images landing tables should now be by label, ascending (instead of label, descending).
> M3-5172: Change Images landing tables to have default sorting by label ascending

- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- Add divider between "Root Password" and "SSH Keys"
- Move VLAN into it's own panel
- Rename the add-ons panel and add divider between "Backups" and "Private IP"
Go to http://localhost:3000/linodes/create
> M3-5061: Create Linode UI Refinements

- packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts
just a small lke e2e test update
- `yarn cy:e2e -s ./cypress/integration/lke/smoke-lke-create.spec.ts` in another
```
MANAGER_OAUTH
```
> E2E Update: lke text validation

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Found a regression in Create Cluster from the changes made in #7672
> Fix paper padding regression in Create Cluster

- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
- packages/manager/src/themes.ts
Adjust color and spacing of divider and shift the "Add a Device" button over by 1px
1. Go to `/linodes`
2. Click on any Linode
3. Go to the "Configurations" tab
4. Click "Add Configuration"
5. Scroll through the modal and check for issues
> M3-5063: Linode Configs modal refinements

- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Fixes #7691 
Ensure the `Open New Ticket` model works as expected. Specially test the functionality that allows the form's state to permit data (using localstorage) after exit.
> #7691: New Ticket Dialog: fixed clearing form state after submit

- packages/manager/cypress/integration/linodes/linode-storage.spec.ts
instead of alerting you with a toast, the delete button is now disabled if linode is in use. this test now accounts for that change
- `yarn cy:e2e -s ./cypress/integration/linodes/linode-storage.spec.ts` in another
```
MANAGER_OAUTH
```
> E2E Update: linode-storage test

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/request.tsx
If additional verification is required, autofill the request description with the plan the user was trying to create.
Try to create a Linode on an account that requires additional verification.
> M3-5000: Auto fill request description when opening support ticket

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
Fix UI bugs (row border misalignments and column header mismatching) in Object Storage landing table at smaller viewports
> M3-5269: Fix Object Storage landing table UI bugs

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
- Edit copy for High Mem plans in Linode & LKE Create flows
- Small copy change in Upgrade drawer
> M3-4264: Copy changes for High Memory plans

- packages/manager/cypress/integration/domains/smoke-create-domain.spec.ts
- packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts
- packages/manager/cypress/integration/linodes/backup-linode.spec.ts
- packages/manager/cypress/integration/linodes/clone-linode.spec.ts
- packages/manager/cypress/integration/linodes/create-linode.spec.ts
- packages/manager/cypress/integration/linodes/linode-storage.spec.ts
- packages/manager/cypress/integration/linodes/rescue-linode.spec.ts
- packages/manager/cypress/integration/linodes/resize-linode.spec.ts
- packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
- packages/manager/cypress/integration/longview.spec.ts
- packages/manager/cypress/integration/nodebalancers/smoke-create-nodebal.spec.ts
- packages/manager/cypress/integration/objectStorage/access-keys.spec.ts
- packages/manager/cypress/integration/stackscripts/stackscripts.spec.ts
- packages/manager/cypress/integration/volumes/smoke-create-volumes.spec.ts
- packages/manager/cypress/support/index.js
- packages/manager/cypress/support/ui/common.ts
- packages/manager/cypress/tsconfig.json
- packages/manager/package.json
- yarn.lock
small create-linode e2e test update to catch the case of not updating to running without reloading.
Also a cypress eslint update and a small update for cleanup
- `yarn cy:e2e -s ./cypress/integration/linodes/create-linode.spec.ts` in another
```
MANAGER_OAUTH
```
> E2e create linode test update

- packages/manager/src/features/Account/Maintenance/MaintenanceTable.test.tsx
- packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
- packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
- packages/manager/src/hooks/useOrder.test.tsx
- packages/manager/src/hooks/useOrder.ts
- packages/manager/src/utilities/testHelpers.tsx
- Adds tests for the Maintenance Table
- Adds tests for the useOrder hook
- Moved Row logic into `MaintenanceTableRow.tsx`
- Make sure Maintenance Table still functions an intended
- `yarn test Maintenance`
- `yarn test useOrder`
> Maintenance Table Updates and Tests

- packages/manager/src/factories/accountPayment.ts
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
- packages/manager/src/mocks/serverHandlers.ts
- Improves Payment Methods mocking
- ~~Makes Payment Methods on `/account/billing` scrollable~~
- We will not make it scrollable because native browsers hide the scroll bar when user is not scrolling and it unintentionally  hides payment methods from the user
- Test MSW on `/account/billing`
- ~~Make sure you are able to scroll in the payment methods panel~~
> Improve Payment Methods Mocking

- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
- packages/manager/src/features/Billing/Providers/GooglePay.ts
Logs errors relating to Google Pay to Sentry.
> Log Google Pay Errors to Sentry

- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
- packages/manager/src/themeFactory.ts
- Changes `CVV` to `Security Code` in the **Update Credit Card Drawer** to be consistent with the rest of Cloud Manager
- Makes sure there is a way for a user to add a payment method if they have no payment methods and the feature flag is off
- Go to `/account/billing`
- Click `Edit` in the Action Menu of your credit card in the **Payment Methods** paper
- Make sure the drawer that opened says `Security Code` and not `CVV`
> M3-5328: Change CVV to Security code and Fix Feature Flag Off Issue

- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
Reduce the spacing and refactor to a FC.
Go to `/nodebalancers/[insert id]/settings` and make sure all the functionality works as usual.
> M3-5335: Reduce spacing for NodeBalancer Settings

- packages/manager/package.json
- yarn.lock
There's not a lot you need to do to test this. The best way to see that it worked is to get it merged. I've verified that it still runs tests and doesn't break the app. You can run one or a few tests if you'd like to verify that as well.
> M3-5379 E2E Cypress Upgrade to (hopefully) address CI performance issues

- packages/api-v4/src/account/payments.ts
- packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
- packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
- packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
- Adds **Delete** button to the Payment Method Row dropdown
- Adds Dialog as confirmation to deleting a payment method
https://user-images.githubusercontent.com/6440455/127023306-d4760ab2-348c-4599-a76e-14fa4fa7cca4.mov
- Go to `/account/billing` and try deleting a payment method
> M3-5297: Delete a Payment Method

- packages/manager/cypress/support/ui/constants.ts
updating test to handle basic page check now that there are multiple login methods. will need a more detailed test for this specific page soon
small deeplink e2e test update
- `yarn cy:e2e -s ./cypress/integration/smoke-deep-link.spec.ts` in another
```
MANAGER_OAUTH
```
> E2E deeplink test update

- packages/manager/cypress/integration/objectStorage/buckets.spec.ts
trying to solidify this test - primarily for ci runs
small buckets e2e test update
- `yarn cy:e2e -s ./cypress/integration/objectStorage/buckets.spec.ts` in another
```
MANAGER_OAUTH
```
> E2E Buckets Test Update

- packages/api-v4/src/account/index.ts
- packages/api-v4/src/account/promos.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PromoDialog.tsx
- packages/manager/src/queries/account.ts
- packages/manager/src/utilities/date.test.ts
- packages/manager/src/utilities/date.ts
- packages/validation/src/account.schema.ts
- Adds ability for users to add promo codes to their accounts
https://user-images.githubusercontent.com/6440455/128060832-bf3f9e9a-cd93-460f-972d-9b048e6687f5.mov
- Test adding a promo code
- Test on accounts with a balance, with credit, etc...
- Test on restricted user accounts
> M3-5302: Ability to add a promo code to account

- packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx
- Fixes Typescript errors
- Updates padding for payment method information in modal
- Pull PR and typecheck
> Fix type errors for Deleting a Payment Method

- packages/manager/src/features/Managed/Contacts/Contacts.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList.tsx
Check the Managed section for any remaining redundant headers
> Remove redundant headers for Managed

- docs/development-guide/01-repository-structure.md
- docs/development-guide/02-component-structure.md
- docs/development-guide/03-component-state.md
This adds a development guide with three entries:
1. Repository Structure 
2. Component Structure 
3. Managing State
There are more guides to be written but this is a decent start.
Still to come (in a separate PR):
4. Fetching Data 
5. Component Performance
6. Writing Unit Tests
7. Mocking Data 
8. Using the Local Dev Tools
9. Writing a Feature Flag
10. Installing and Updating Dependencies
> Documentation: add development guide

- packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
comments out price estimator in `CreateImageTab.tsx`.
Navigate to `CreateImageTab.tsx` and verify that the price estimator is not shown.
> comment out price estimation in CreateImageTab

- CHANGELOG.md
- docs/development-guide/04-fetching-data.md
- docs/development-guide/05-performance.md
- docs/development-guide/06-writing-unit-tests.md
- docs/development-guide/07-mocking-data.md
- docs/development-guide/08-local-dev-tools.md
- docs/development-guide/09-feature-flags.md
- docs/development-guide/10-installing-dependencies.md
- packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
- packages/manager/cypress/support/index.js
- packages/manager/cypress/tsconfig.json
- packages/manager/package.json
- packages/manager/src/components/EnhancedSelect/Select.tsx
- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Images/ImageUpload.tsx
- packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/Users/UserPermissions.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
- yarn.lock
Merge release-v1.48.0 into staging
> Release v1.48.0

- CHANGELOG.md
- docs/development-guide/04-fetching-data.md
- docs/development-guide/05-performance.md
- docs/development-guide/06-writing-unit-tests.md
- docs/development-guide/07-mocking-data.md
- docs/development-guide/08-local-dev-tools.md
- docs/development-guide/09-feature-flags.md
- docs/development-guide/10-installing-dependencies.md
- packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
- packages/manager/cypress/support/index.js
- packages/manager/cypress/tsconfig.json
- packages/manager/package.json
- packages/manager/src/components/EnhancedSelect/Select.tsx
- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Images/ImageUpload.tsx
- packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/Users/UserPermissions.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/accountMaintenance.ts
- yarn.lock
> Merge staging into master

- packages/manager/src/features/linodes/CloneLanding/Details.tsx
- We deemed the agreement was not needed here
- Make sure component was completely removed from the Linode Disk / Config Clone flow
> M3-5407: Remove EU Contract on Disk/Config clone

- packages/manager/src/components/MaintenanceScreen.tsx
Follow-up to https://github.com/linode/manager/pull/7870 based on feedback received during demo today to simplify the copy.
> M3-5446: Simplify copy on API Maintenance screen

- package.json
- yarn.lock
Adds set-value to package.json resolutions to resolve the dependabot issue opened earlier.
Also adds the correct version of axios to yarn.lock since I forgot to run `yarn install` on the last PR.
> Update set-value and yarn install axios

- packages/manager/src/eventMessageGenerator.ts
- Adds event message for GDPR events
- Sign the GDPR event and ensure you see the proper event message
- I used devenv to test signing via the API
> GDPR Event Message

- packages/api-v4/src/volumes/volumes.ts
- packages/manager/src/documentation.ts
- packages/manager/src/features/Billing/PdfGenerator/utils.ts
- packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
- packages/manager/src/features/Volumes/VolumeTableRow.tsx
- packages/manager/src/store/selectors/getSearchEntities.ts
To be consistent with Marketing/Docs sites.
Do a general check around Volumes pages.
> Find-and-replace GiB -> GB for Volumes

- packages/manager/src/components/ExternalLink/ExternalLink.tsx
- packages/manager/src/components/HelpIcon/HelpIcon.tsx
- packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- packages/manager/src/features/linodes/SMTPRestrictionText.tsx
- packages/manager/src/utilities/ga.ts
This PR logs a Google Analytics event when a user does any of the following on `/linodes/create`
- Clicks the `Use our speedtest page` in the region section
- Clicks the SMTP guide link in the checkout sidebar
- Views the IPAM tooltip in the VLANs section
- View the dev console and make sure the debugging Google Analytics logs an event when any of those 3 actions listed above are performed.
> M3-5521: Contextual help for Linode Create

- packages/manager/src/features/OneClickApps/FakeSpec.ts
This PR updates the name of the app per the partners request and updates the content in the app information tab
> Marketplace: Utunnel app name update

- packages/manager/src/components/Paper.stories.mdx
Adds a story in storybook mdx format for the Paper component
Ensure the Paper component has a story that renders correctly in storybook.
> M3-5591: Add Story for Paper

- packages/api-v4/src/databases/databases.ts
- packages/api-v4/src/databases/types.ts
- packages/manager/src/factories/databases.ts
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/databases.ts
Fix TypeScript error from `id` field in `databaseBackupFactory` and update `databaseType` interface and `databaseTypeFactory` per API specs
> Small types & factories fixes/updates

- packages/manager/src/factories/databases.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
- packages/manager/src/features/Databases/DatabaseDetail/index.tsx
This PR adds the breadcrumb to the Database Details page and the Cluster Configs section to the Summary tab.
Turn on MSW and go to any Database Details page.
> DBAAS1-82: Database Details - Cluster Configs

- packages/manager/src/components/FileUploader/FileUploader.tsx
- packages/manager/src/features/Account/CloseAccountDialog.tsx
- packages/manager/src/features/Account/EnableObjectStorage.tsx
- packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Updates the spelling of:
- cancelled -> canceled
- cancelling -> canceling
- cancelation -> cancellation
where needed
Verify we have no outdated spellings throughout the codebase
> Update cancel<ending> spelling

- packages/api-v4/src/databases/types.ts
- packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
- packages/manager/src/factories/databases.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummary.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/databases.ts
Adds Connection Details component to the Database Summary tab
- Turn on the MSW and go to a database (e.g. `databases/mysql/0`)
- Test the show and download buttons.
- The download button should only be visible if `ssl_connection` is enabled
- Test loading and error states
> DBAAS1-83: Database Connection Details

- .github/workflows/README.md
* Adds `README.md` to `.github/workflows` which provides an overview of our GitHub workflows
* No testing needed -- this PR does not include any code changes
> M3-5659: Add GitHub workflows documentation

- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Update ssl verbiage in Connection Details
Verbiage should be `ssl = ENABLED/DISABLED` in Connection Details
> M3-5680: Update DBaaS Connection Details ssl verbiage 

- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
- Fix API IP errors not being surfaced
- I went with displaying error notices as it was the simplest option; mapping the errors to the input fields is a bit more involved and maybe something we can revisit later
- Sorts DB engine dropdown by version descending
- `yarn test DatabaseCreate`
- Try creating a database cluster and ensure that API IP errors surface
> M3-5681: DBaaS Create UI refinements

- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
M3-5684: Add notice that beta is free
M3-5685: Update Add Access Controls language
M3-5686: Move the provisioning helper text next to create button
In `databases/create` check for the changes above and also check mobile view
`yarn test DatabaseCreate`
> Database Create Copy updates

- packages/manager/src/components/TaxBanner/TaxBanner.tsx
- packages/manager/src/features/Account/AccountLanding.tsx
- Fixes account page tab routing
- May have been caused by #8118
- Should resolve failing e2es
- Test account routing involving `/account/*`
> Fix Account Routing

- packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
As discussed in Sprint Review Prep.
> Use secondary style for Download PDF button (Invoice)

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
Changes the default image from Debian 10 to Debian 11.
> change default linode image to Debian 11

- packages/api-v4/src/databases/databases.ts
- packages/api-v4/src/databases/types.ts
- packages/manager/src/factories/databases.ts
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/databases.ts
Update endpoints, queries, types, and variable names to reflect `/databases/versions` --> `/databases/engines` change.
Confirm no functionality has been adversely impacted for DBaaS.
> M3-5702: Changes resulting from GET /databases/versions --> GET /databases/engines

- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- Updates the DBaaS Docs link on the Database Landing Page
- Test the `Docs` button that is shown in the header of the Database Landing table
> Database Landing Docs Link

- packages/manager/src/features/Lish/lishUtils.ts
Change "alpha" to "dev" for glish
Deploy this PR to dev
> Change alpha to dev for glish

- packages/manager/src/components/FileUpload.stories.mdx
- packages/manager/src/components/FileUploader/FileUploader.stories.mdx
- packages/manager/src/components/FileUploader/FileUploader.tsx
Adds a Storybook Story for our File Uploader
Because we don't have a generic file uploader component (😔), there are two variants of the File Uploader in this story
- Image Uploader
- Object Uploader
- `yarn storybook`
- Find the `Components`/`File Uploader` story and test it!
> M3-5589: Added Storybook Story for File Uploads

- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
- packages/manager/src/queries/objectStorage.ts
- Fixes deletion not showing correct object after a delete (Found by @HanaXu)
- Fixes multiple uploads not showing in list (Found by @DevDW)
- Test the two fixes
- Upload many objects at once and sure they all show in the table
- Upload two objects, then delete the first. One object should remain
> React Query for Object Storage Bug Fixes

- packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx
Adds storybook story for Status Icons using MDX format.
Ensure story renders correctly.
> M3-5612: Update stories for status icons

- .github/workflows/ci.yml
Trying to publish storybook from develop
Verify this will run against develop
> Run Publish Storybook against develop

- .github/workflows/ci.yml
- We also need to enable build-storybook on develop
> Also Build Storybook on develop

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/IdentifyUser.tsx
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
- packages/manager/src/queries/account.ts
- packages/manager/src/queries/accountAgreements.ts
- packages/manager/src/queries/accountSettings.ts
- packages/manager/src/queries/base.ts
Merge `staging` into `master` for Cloud v1.61.1 including code for EAP SLA banners for DBaaS and the bug fix that prevented users with restricted account access from loading Cloud.
- Ensure the EAP SLA banners display as intended on the Database Create and Database landing empty state pages
- Ensure that the app functions normally for unrestricted and restricted users
> staging --> master for Cloud v1.61.1 (EAP SLA banners + fix for restricted users)

- packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.test.tsx
- packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
- packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
- packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
- packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
- packages/manager/src/queries/account.ts
This PR adds a new section to the Display tab under My Profile to encourage users to using individual profile photos rather than the default user icon. 
Some other UI changes to the Display tab include:
- Moving the other sections into the same `<Paper />` component
- Adding a label and descriptive text to the Timezone selector
- Aligning the buttons to the right to reduce vertical spacing
- Changing the button text to better explain what fields it corresponds to
- Go to `/profile/display`
- Create a Gravatar account to update existing profile photo or change the existing photo via the links provided
- Check UI for restricted users
- `yarn test SingleTextFieldForm`
- `yarn test TimezoneForm`
> M3-5471: Add reference to Gravatar to My Profile settings

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Fix Prometheus & Grafana and Ant Media Enterprise docs link
Go to Marketplace, open the drawer for the app and check the docs link
> Fix Marketplace docs links

- packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx
- packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
- packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Forgot to push the changes to use consistent references to the profile photo copy.
Also increases the profile copy width and removes timezone text.
Go to `/profile/display` and check the copy
> Update copy for Gravatar settings and address feedback from demo

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
> IPv6 Sharing Copy

- package.json
- yarn.lock
This bumps `trim-newlines` from 1.0.0 to latest (4.0.2)
Ensure the app and tests run as expected.
> Bump trim-newlines 

- packages/api-v4/src/profile/profile.ts
- packages/api-v4/src/profile/types.ts
- packages/manager/src/factories/profile.ts
- packages/manager/src/mocks/serverHandlers.ts
- Adds alt payments functions and types for new API endpoints to the `@linode/api-v4` package
- Adds factories for new types
- Adds MSW handlers for new API endpoints
N/A
N/A
> M3-5797: Add alt payment methods API functions/types, factories, and MSW handlers

- CHANGELOG.md
- packages/api-v4/CHANGELOG.md
- packages/api-v4/package.json
- packages/manager/package.json
- packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
- packages/manager/src/components/Notice/Notice.tsx
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
- packages/validation/CHANGELOG.md
- packages/validation/package.json
Merge `staging` into `master` for release of Cloud v1.64.1
> Staging --> Master for Cloud Manager v1.64.1

- CHANGELOG.md
- packages/api-v4/package.json
- packages/manager/package.json
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
- packages/validation/CHANGELOG.md
- packages/validation/package.json
- packages/validation/src/databases.schema.ts
Merge `master` into `develop` following release of Cloud Manager v1.66.2.
> master --> develop following release of Cloud v1.66.2

- packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
> Revert "Indicate that MongoDB and PostgreSQL are in beta."

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
- packages/manager/src/features/TopMenu/NotificationButton.tsx
Fix bug that was spamming seen and preference calls when clicking a link inside the Notification Menu (caused by https://github.com/linode/manager/pull/8393)
Open the Notification Menu, click on a link and observe the network requests, there should no longer be an infinite spam of calls
> Fix Notification Menu bug

- packages/manager/cypress/integration/databases/delete-database.spec.ts
- packages/manager/cypress/integration/databases/update-database.spec.ts
- packages/manager/cypress/support/intercepts/databases.ts
- packages/manager/cypress/support/ui/buttons.ts
- packages/manager/cypress/support/ui/index.ts
- packages/manager/cypress/support/ui/tab-list.ts
- packages/manager/cypress/support/util/errors.ts
- packages/manager/cypress/support/util/random.ts
- packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
Adds integration tests that cover DBaaS update operations for databases in `provisioning` status, as well as delete operations for `provisioning` and `active` DBs.
**How do I run relevant tests?**
```bash
yarn cy:run -s "cypress/integration/databases/delete-database.spec.ts,cypress/integration/databases/update-database.spec.ts"
```
> M3-5844: DBaaS update and deletion tests for provisioning DBs

- packages/api-v4/src/profile/profile.ts
- packages/manager/src/components/LinkButton.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/Question.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/validation/src/profile.schema.ts
- Makes minor UI changes to Security Questions and SMS Verification
- Fixes Security Questions causing app to crash
> **Note**: You can test against our dev environment now
- Check UI of Security Questions and SMS Verification
- Test functionality of Security Questions in many different configurations
> Security Questions and SMS Verification Fixes and Updates

- packages/manager/src/factories/profile.ts
Minor PR to match the mock Security Questions to the real ones.
These get returned when you hit `/profile/security-questions`. Retaining the ability to mock what gets returned from this endpoint allows us to test various edge cases.
> Updated mock Security Questions

- CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/components/MainContentBanner.tsx
This adds a set width to the main content banner to prevent longer messages in the banner being clipped.
> Add width to main content banner

- packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
- Test the Marketplace Details Drawer
- You can modify `FakeSpec.ts` to test different configurations of app details
> Move Marketplace Guides Links

- packages/manager/cypress/integration/images/create-linode-from-image.spec.ts
This PR attempts to fix today's failure in the `create-linode-from-image.spec.ts` E2E tests. These changes appear to fix the failure (as well as some other problems with the tests) when ran locally.
I believe that the failure in question was a rare fluke ultimately caused by [this Cypress issue](https://github.com/cypress-io/cypress/issues/20397), but these improvements should prevent the issue from causing test failures going forward.
I posted a more thorough write up of the failure in the frontend notification channel for anybody who is curious how this all ties together, but tl;dr is that removing the extra `cy.visitWithLogin()` call prevents this Cypress race condition from occurring.
I had …
> Fix E2E tests for Linode creation from image flows

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Fix for "App Details Not Found" error when opening Ant Media Server drawers
Go to Marketplace and open the two Ant Media Server (Community & Enterprise) drawers
> M3-5930: Fix Ant Media Server display in drawer

- docs/PULL_REQUEST_TEMPLATE.md
- docs/development-guide/14-configuring-environments.md
- Updates docs to include information on specifying multiple envs
- Updates PR template to include some color and a section for screenshots 
- Check for spelling and style of the new doc and template
> New Environment Docs and Updated PR Template

- packages/manager/.storybook/manager-head.html
- packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- Changes Linode logo size so the `Akamai` text is more visible
- Test Primary Nav and check logo for sizing
- test collapsing it and hovering it
> Increase Logo Size

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
- IPs in Transfer IP Dialog were not correct after a change has been made
https://user-images.githubusercontent.com/115251059/199073105-8dedabb5-cccb-461b-afaf-2c69fe1701d0.mov
- Invalidate the React Query cache after an IP has been changed
https://user-images.githubusercontent.com/115251059/199073407-4782eb7f-844c-4875-ad94-fe2ee6d61312.mov
- Test the Transfer IP dialog in depth
- Test swapping IPs between two Linodes twice in a row
> Fix IP Transfer Dialog

- packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
- packages/manager/src/components/Button/Button.tsx
- packages/manager/src/components/Button/button.stories.mdx
- packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
- packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
- packages/manager/src/features/Support/AttachFileForm.tsx
- packages/manager/src/features/linodes/CloneLanding/Details.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
- Tighten up spacing in the Kubernetes Cluster details page
- Refactoring and code clean up
- Added compactY to Button component and renamed compact to compactX
- Updated Storybook Button to include compactY
Before
After
- Go to a Kubernetes cluster details page and check the changes
- Run Storybook locally (`yarn storybook`) and check the Button story
> M3-5766: LKE UI refinements

- docs/development-guide/01-repository-structure.md
- docs/development-guide/04-component-library.md
- docs/development-guide/13-coding-standards.md
Updates the repo's development guide with `yarn` commands for building & starting up an instance of Storybook locally and best practices/tips collected from previous Slack channel lore. 
- Read through for any typos or unclear/inaccurate parts.
- Check that all links are valid.
> M3-5981: Improve Storybook dev guide

- docs/development-guide/04-component-library.md
- packages/api-v4/.eslintrc.json
- packages/manager/.eslintrc.js
- packages/manager/.storybook/preview.tsx
- packages/manager/src/components/SelectionCard/SelectionCard.stories.mdx
- packages/manager/src/components/SnackBar/SnackBar.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx
- packages/validation/.eslintrc.json
- Fixes the following for MUI v5
- Toast styles not being applied
- Support ticket input too large
- Compare the UI of Toast and the Support Ticket Modal of this PR to production. They should look nearly identical
> MUI v5 - Fix Toast Styles and Support Ticket Input Size

- packages/manager/cypress/e2e/linodes/linode-storage.spec.ts
- packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
- packages/manager/cypress/e2e/managed/managed-monitors.spec.ts
- packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts
This fixes a few E2E test failures for the MUI v5 upgrade. These all stem from some slight markup changes and aren't caused by any actual bugs or issues.
```
yarn cy:run
```
(You may observe one failure related to opening support tickets -- that's outside the scope of these fixes)
> E2E test fixes for MUI v5

- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/HelpIcon/HelpIcon.tsx
- packages/manager/src/components/PasswordInput/HideShowText.tsx
- packages/manager/src/components/PasswordInput/PasswordInput.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
- packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/LabelField.tsx
- Change placeholder text from "Enter your password" to "Enter your token" for API token field
- Add tooltip about setting up an API token next to the token input field
Click on a Marketplace app that has an API token input field under Setup such as Mongodb Cluster
> M3-5995: UDF copy updates

- packages/manager/cypress/e2e/databases/update-database.spec.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
Simple PR to show the region in summary view for Databases.
> M3-6000: Add missing region text in Database summary view

- packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Fixes deploying Linode from backup
https://user-images.githubusercontent.com/119517080/212214390-79e8ba56-6fbe-47f8-b4a8-b9fd5f43bdcf.mov
- Navigate to Create Linode page
- Click backup tab
- Select Linode
- Select backup
- Click Create Linode button
- Checkout to develop branch
- Navigate to Create Linode page
- Click backup tab
- Select Linode
- Select backup
- Click Create Linode button
Navigate to Create Linode page
Click backup tab
Select Linode
yarn test
> M3-6064: Deploying a Linode Backup to a new Linode forces a different plan size to be chosen

- packages/manager/src/components/Notice/Notice.tsx
- packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- Updates new API/CLI modal with new copy on the Linode Create Flow
- **To verify copy check the internal ticket**
- Check copy and links in the modal on the Linode Create Flow
- **To verify copy check the internal ticket**
> M3-6067: Linode Create - API/CLI Copy Changes

- packages/manager/src/components/TabLinkList/TabLinkList.tsx
- packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
- Re-adds copy that got cut out and updates spacing
- I am open to suggestions on spacing, it could be better
- Test and view styles in the new API/CLI Modal on `/linodes/create`
> M3-6067: Update Copy and Spacing - Part 2

- packages/manager/src/utilities/escapeStringForCLI.ts
- packages/manager/src/utilities/generate-cURL.ts
- packages/manager/src/utilities/generate-cli.ts
- Attempt at Escaping and Parcing changes
> API/CLI Escaping and Parcing

- packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
Fix E2E test from https://github.com/linode/manager/pull/8806
- Go to `package/manager`
- `yarn start`
- Additionally run `cy:debug`
- Run `packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts`
- Observe everything passes
> fix(PrimaryNav): M3-6162 - Update E2E tests for this previous change

- .github/workflows/security_scan.yml
This adds a GitHub Actions workflow to perform static application security testing on Cloud when code is pushed to `develop`. This shouldn't impact our existing CI workflows at all.
> ST-4251: Add Semgrep SAST testing workflow

- packages/manager/src/index.tsx
Fixes the accidental disappearance of RQ DevTools in #8795.
Ensure RQ DevTools appear when in a development environment.
> Re-enable RQ DevTools

- packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/SideMenu.tsx
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
- packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
- packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
- packages/manager/src/features/CancelLanding/CancelLanding.test.tsx
- packages/manager/src/features/CancelLanding/CancelLanding.tsx
Remove the conditionals relying on the `brandUpdate` feature flag.
- Confirm the Akamai logo is visible in the side bar
- Confirm the billing invoices look good
`yarn test cancellanding`
> M3-6166: Remove dependency on `brandUpdate` flag

- docs/development-guide/13-coding-standards.md
Updated some documentation as we discussed. 
> Note: When we’re making progressive updates to files, let's change all the event handlers in the file to follow our new convention rather than limiting the changes to whatever you’re adding.
> docs: Add event handler naming convention section

- docs/development-guide/02-component-structure.md
- docs/development-guide/13-coding-standards.md
Updates guidelines for component-specific styles.
> docs: Update styles coding standards to reflect FE Cafe consensus

- .github/workflows/ci.yml
This fix addresses the Storybook build failure in CI.
- Validate CI flow
- Run yarn build-storybook
> fix:  increases the maximum heap size to 4096 in CI for  build-storybook step

- .github/workflows/ci.yml
Uncomment conditions for storybook build and publish steps
> ci: cleanup, enable conditions for storybook build steps

- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- Users are unable to save NodeBalancer configurations because _in production builds_, a Javascript error occurs.
- We think this happened because `import * as Promise from 'bluebird'` conflicted with the native js promise
- The fix could have been as simple as changing the import, but for the sake of making things less confusing, I just switched this component to use Javscript's Promises. 
https://user-images.githubusercontent.com/115251059/226973638-718e93bb-7d71-42bf-9239-4f945725ba92.mov
I think the big takeaway from this is don't do imports like, especially when the name `Promise` is already a natively defined thing
```typescript
import * as Promise from 'bluebird';
```
> **Warning**: Test this both locally and using our internal preview link. We need to verify the issue is fixed in …
> fix: [M3-6426] - Fix NodeBalancer Configurations not saving

- packages/api-v4/src/linodes/types.ts
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Introduces new plan in Plans table
Validate Plan tabs as per the Jira ticket.
- yarn test
- yarn cy:run
> feat: [M3-6072] - New tab for plans table

- packages/api-v4/src/linodes/types.ts
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Introduces new tab for plans table.
> feat: [M3-6072] - New tab for plans table (#8906)

- docs/CONTRIBUTING.md
- docs/PULL_REQUEST_TEMPLATE.md
Add `change` as a commit type and update the definition of refactor
Check the updated files
> docs: [M3-6451] - Add change as a commit type and update refactor definition

- docs/development-guide/02-component-structure.md
Add changes to Component naming conventions.
> docs: [M3-6452] - Update Docs for JSX element naming convention

- packages/manager/cypress/e2e/databases/create-database.spec.ts
- packages/manager/cypress/e2e/databases/database-configuration.ts
- packages/manager/cypress/e2e/databases/delete-database.spec.ts
- packages/manager/cypress/e2e/databases/update-database.spec.ts
- packages/manager/cypress/support/constants/databases.ts
- Parameterize DBaaS `update` and `delete` tests for multiple engines
Run the commands: 
`yarn cy:run -s "cypress/e2e/databases/create-database.spec.ts"`
`yarn cy:run -s "cypress/e2e/databases/update-database.spec.ts"`
`yarn cy:run -s "cypress/e2e/databases/delete-database.spec.ts"`
> refactor: [M3-5945] - Parameterize DBaaS tests for multiple engines

- packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
- packages/manager/src/components/EntityTable/GroupedEntitiesByTag.tsx
- packages/manager/src/components/LineGraph/MetricDisplay.styles.ts
- packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Domains/DomainBanner.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
- packages/manager/src/formatted-text.css
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
Resolves pseudo class console errros (notice this while running unit tests)
Validate Overall app look and feel. 
yarn test
yarn cy:run
> chore: resolves pseudo class console errors

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
- packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
- Fixes unit tests after Metadata copy changes https://github.com/linode/manager/pull/8977
- `yarn test UserData`
- Check changes to type and logic (small changes but please verify I did not break anything)
> fix: Unit Tests for Metadata and Improvements to Typesafety

- packages/manager/src/hooks/useAPIRequest.test.ts
Resolves async await console erros in unit test
- yarn test useAPIRequest.test.ts
> fix: async await console erros in unit test

- packages/manager/cypress/support/ui/constants.ts
- Fixes `smoke-deep-link.spec.ts` after copy changes caused by https://github.com/linode/manager/pull/8982
- Run `yarn cy:debug` and run the `smoke-deep-link.spec.ts` test
> fix: `smoke-deep-link.spec.ts` after copy changes

- packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
- packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
- packages/manager/src/components/DisplayPrice/index.tsx
- packages/manager/src/features/Backups/BackupDrawer.tsx
- packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
- packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/PricePanel.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx
- Styles clean up for `<DisplayPrice />`
- Also includes some related clean ups and removal of unused test selector
- Check for UI regressions in components such as 
- Volume Resize Form
- Kubernetes Create side bar
> refactor: [M3-6322] - SRC > Components > DisplayPrice

- CHANGELOG.md
Getting the changelog ready for the next release
> chore: Update changelog with unreleased section

- packages/manager/cypress.config.ts
This disables uploading Cypress recordings for specs who run without any flake or failures. Before this change, all recordings get uploaded to the Cypress dashboard regardless of whether they are successful or not. Because we don't need recordings for passed tests, we can save some time by skipping the compression/recording step in these cases.
This change only applies when the `CI` environment variable is present; recording behavior is unchanged for local runs (but can be tested locally by setting the `CI` env var).
This can be tested using the automatic run against this PR, but can also be tested locally:
```bash
CI=true yarn cy:run
```
Confirm that the CLI output only shows recording information for tests that fail or are flaky, and that there is no mention of a recording being …
> change: [M3-6057] - Avoid saving/uploading Cypress recordings for successful specs in CI

- packages/manager/src/components/LandingHeader/LandingHeader.tsx
Fixing a small regression with header doc link
|  ![Screenshot 2023-05-16 at 10 03 24 AM](https://github.com/linode/manager/assets/130582365/59deb6ac-9030-4b78-af4c-2c50685a1711) | ![Screenshot 2023-05-16 at 10 25 15 AM](https://github.com/linode/manager/assets/130582365/a49dc549-20b7-40f2-9a77-92bbced98854) |
> fix: [M3-6578] Regression with create flow header doc link

- CHANGELOG.md
- packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
- packages/manager/package.json
- packages/manager/src/components/EntityTable/EntityTableHeader.tsx
- packages/manager/src/components/EntityTable/types.ts
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx
- packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
- packages/manager/src/features/linodes/index.tsx
- packages/manager/src/features/linodes/transitions.ts
- Merge master into develop following the `1.93.2` release
- Fixes conflicts caused by hotfix
- **This will be merge committed into develop**
- Do a sanity check to ensure that this PR behaves like production
- Check for issues with Linodes landing and linode details
> `develop` ⬅️ `master` for v1.93.1 and v1.93.2 release

- docs/development-guide/02-component-structure.md
Update our docs to provide clarity surrounding components in `/features/`.
> chore: update component structure docs

- packages/manager/.changeset/pr-9241-tech-stories-1686337150607.md
- packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.test.tsx
- packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.tsx
- packages/manager/src/components/ExtendedAccordion/index.ts
- packages/manager/src/components/NavTabs/NavTabs.tsx
- packages/manager/src/components/Prompt/Prompt.tsx
- packages/manager/src/components/Prompt/index.ts
- packages/manager/src/components/SafeTabPanel/SafeTabPanel.tsx
- packages/manager/src/components/SafeTabPanel/index.ts
- packages/manager/src/components/Tabs.stories.mdx
- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Databases/DatabaseDetail/index.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/Images/ImageUpload.tsx
- packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/index.tsx
- packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
- packages/manager/src/features/Lish/Lish.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/Users/UserDetail.tsx
- packages/manager/src/features/Users/UserPermissions.tsx
Update the ExtendedAccordion, Prompt, and SafeTabPanel components to match our current patterns
Check that the components still render
> refactor: [M3-6338, 6381, 6383] - `ExtendedAccordion, Prompt, SafeTabPanel`

- packages/manager/.changeset/pr-9243-changed-1686346732563.md
- packages/manager/src/components/ScriptCode/ScriptCode.tsx
- packages/manager/src/components/ScriptCode/index.ts
- packages/manager/src/components/StackScript/StackScript.tsx
Use the `styled()` API in `ScriptCode.tsx` and make changes according to our current code conventions.
Confirm that there have been no changes to the "Script" section of StackScript Detail pages.
> refactor: [M3-6384] – MUI v5 Migration – `Components > ScriptCode`

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
- packages/manager/src/features/OneClickApps/FakeSpec.ts
- packages/manager/src/features/StackScripts/stackScriptUtils.ts
- Fix June Marketplace apps feature flag toggle (they are not slated for release until 6/26)
- Fix Illa Builder drawer spelling and hide New apps section if there are no new apps
| ![image](https://github.com/linode/manager/assets/115299789/e0f013ae-860b-4f66-b4f1-ff4fb0b6dd08) | ![image](https://github.com/linode/manager/assets/115299789/6c89edcf-cf13-49ce-a589-ab2198bfc44d) |
- Check that the June Marketplace apps do not display when the feature flag is toggled off and that they do display when the flag is toggled on
- The New apps section should not display when the feature flag is off
> hotfix: June Marketplace apps

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Linodes/LinodesCreate/AppPanelSection.tsx
- packages/manager/src/features/OneClickApps/FakeSpec.ts
- packages/manager/src/features/StackScripts/stackScriptUtils.ts
https://github.com/linode/manager/pull/9259
> Release v1.95.1 – `staging` → `master`

- packages/manager/.changeset/pr-9267-tech-stories-1686857766076.md
- packages/manager/src/components/ImageSelect/ImageSelect.test.tsx
- packages/manager/src/components/ImageSelect/ImageSelect.tsx
Minor updates to `ImageSelect`
- Renamed props 
- Removed FC
No visual changes and no functional changes
Not much to test here
> refactor: [M3-6349] - MUI v5 Migration - `SRC > ImageSelect`

- packages/manager/.changeset/pr-9287-changed-1687360553653.md
- packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
**Updated copy of Premium plans tab**
| ![image](https://github.com/linode/manager/assets/119517080/2290ce60-ada0-420e-b940-8df8fe9c1bb9) | ![image](https://github.com/linode/manager/assets/119517080/7f7aa1b8-3837-45b8-ba85-adf86d50470e) |
1. **Navigate to Plans table validate copy under Premium plans tab**
> chore: [M3-6557] - Improve Premium plans Tab copy

- packages/manager/.changeset/pr-9291-tech-stories-1687369699291.md
- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
- packages/manager/src/components/LongviewLineGraph/index.ts
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/ApacheGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
Update styles and code patterns for the LongviewLineGraph component
So, we don't have an account that has Longview setup and when I tried to run the curl command to set it up, I kept running into errors. I think the changes are minor enough that we can just check the code
> refactor: [M3-6359] - MUI v5 Migration - `Components > LongviewLineGraph`

- packages/api-v4/.changeset/pr-9363-added-1688564871453.md
- packages/api-v4/src/aglb/entrypoints.ts
- packages/api-v4/src/aglb/loadbalancers.ts
- packages/api-v4/src/aglb/routes.ts
- packages/api-v4/src/aglb/service-targets.ts
- packages/api-v4/src/aglb/types.ts
- Adds api-v4 endpoints and types for the AGLB
- Adds all endpoints that should be needed for the AGLB project
- No testing to be done, just review the endpoint, spelling, and typescript types
- When reviewing, compare type to the API specification linked on the internal ticket
> feat: [M3-6779] - AGLB api-v4 endpoints

- packages/manager/.changeset/pr-9368-added-1688662246154.md
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/featureFlags.ts
Add VPC feature flag
Check that `vpc` is being returned from `useFlags()` and that it is under the feature flag tool
> feat: [M3-6840] - Add VPC feature flag

- packages/api-v4/src/aglb/types.ts
- packages/manager/src/factories/aglb.ts
- packages/manager/src/factories/index.ts
- packages/manager/src/mocks/serverHandlers.ts
Adding both factories and MSW mock endpoints for AGLB - no impact to the customer facing codebase
**Note**: this will need to be iterated on as we go as the API is a moving target, but made sure to leave ample comments through the types to reflect that
> feat: [M3-6781] Add MSW endpoints with factories for AGLB

- packages/manager/.changeset/pr-9404-added-1689282822245.md
- packages/manager/cypress/e2e/core/loadBalancers/load-balancer-navigation.spec.ts
- packages/manager/cypress/support/intercepts/feature-flags.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
This PR adds a primary nav entry for the AGLB feature
- Not visible to customers (behind a feature flag)
- Customized beta chip (see self review comments)
- Will be iterated on as needed
1. Pull code locally, enable both MSW & the AGLB flag
2. Confirm presence and behavior of new menu entry
3. Verify there's no regression with the nav when the flag is off
> Feat: [M3-6805] AGLB Primary Nav Entry

- packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
Add Linode resize decrease size end-to-end tests
- Linode resize decrease size end-to-end tests
`yarn cy:run -s "cypress/e2e/core/linodes/resize-linode.spec.ts"`
> test: [M3-6618] - Add Linode resize decrease size end-to-end tests

- packages/manager/.changeset/pr-9458-tech-stories-1690481194169.md
- packages/manager/.storybook/preview.tsx
- packages/manager/src/components/BetaChip/BetaChip.stories.mdx
- packages/manager/src/components/Currency/Currency.stories.mdx
- packages/manager/src/components/DateTimeDisplay/DateTimeDisplay.stories.mdx
- packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.mdx
- packages/manager/src/components/ErrorState/ErrorState.stories.mdx
- packages/manager/src/components/FileUploader/FileUploader.stories.mdx
- packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx
- packages/manager/src/components/Tabs.stories.mdx
- packages/manager/src/components/Tag/Tag.stories.mdx
- packages/manager/src/components/Tags/Tags.stories.mdx
- packages/manager/src/components/TagsInput/TagsInput.stories.mdx
- packages/manager/src/components/TagsPanel/TagsPanel.stories.mdx
- packages/manager/src/components/Toggle/Toggle.stories.mdx
- Update Storybook sections
- Remove `Elements` section 🗑️
- Made Storybook's sidebar order the following 🧾
- Intro
- Core Styles
- Components
- Features
| ![Screenshot 2023-07-27 at 2 04 11 PM](https://github.com/linode/manager/assets/115251059/30eeacf3-38bf-485c-affc-8136c94bf53e) | ![Screenshot 2023-07-27 at 2 03 17 PM](https://github.com/linode/manager/assets/115251059/82d8c3e6-1f28-45a6-a9b3-0d196ac44374) |
- Run `yarn storybook`
- Go to `http://localhost:6006/` and verify the changes look good! 👀✅
> chore: [M3-6947] - Update Storybook Categories 

- packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
- Fixes the `resize-linode.spec.ts` by fixing the spelling of "Linode"
- Verify e2es pass on this PR
> fix: Resize e2e test

- CHANGELOG.md
If anyone asks, you haven't seen me around here 👻
> chore: Fix broken changelog links

- packages/manager/.changeset/pr-9490-upcoming-features-1691091640290.md
- packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
- packages/manager/cypress/support/intercepts/vpc.ts
- packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx
- packages/manager/src/features/VPC/VPCLanding/VPCDeleteDialog.tsx
- packages/manager/src/features/VPC/VPCLanding/VPCLanding.test.tsx
- packages/manager/src/features/VPC/VPCLanding/VPCLanding.tsx
- packages/manager/src/features/VPC/VPCLanding/VPCRow.test.tsx
- packages/manager/src/features/VPC/VPCLanding/VPCRow.tsx
- packages/manager/src/mocks/serverHandlers.ts
Add VPC delete functionality and dialog
https://github.com/linode/manager/assets/115299789/c40f1408-ba19-4bb7-8cb9-6ff24ab94d87
```
yarn test VPCRow
```
Create a VPC and then delete it or delete a VPC via the MSW
> feat: [M3-6734] - VPC delete dialog

- packages/manager/src/components/LandingLoading/LandingLoading.stories.tsx
- Moves `LandingLoading`  to a better place in the Storybook sidebar
| ![Screenshot 2023-08-07 at 6 08 20 PM](https://github.com/linode/manager/assets/115251059/27574e80-04a8-4374-b86e-c6adee3f985c) | ![Screenshot 2023-08-07 at 6 00 02 PM](https://github.com/linode/manager/assets/115251059/e1090dd6-1f15-44b0-8f53-29b3416bc960) |
- `yarn storybook`
> chore: Organize Storybook `LandingLoading` component

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
- Incorrect timezone form styles on profile page ([#9573](https://github.com/linode/manager/pull/9573))
- Create Linode from Stackscript field state bug ([#9573](https://github.com/linode/manager/pull/9573))
> Release v1.100.1 - staging → master

- packages/api-v4/src/account/types.ts
- packages/manager/.changeset/pr-9544-added-1692992268848.md
- packages/manager/cypress/e2e/core/account/betas.spec.ts
- packages/manager/src/MainContent.tsx
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/factories/betas.ts
- packages/manager/src/features/Betas/BetaDetails.test.tsx
- packages/manager/src/features/Betas/BetaDetails.tsx
- packages/manager/src/features/Betas/BetaDetailsList.test.tsx
- packages/manager/src/features/Betas/BetaDetailsList.tsx
- packages/manager/src/features/Betas/BetaSignup.tsx
- packages/manager/src/features/Betas/BetasLanding.test.tsx
- packages/manager/src/features/Betas/BetasLanding.tsx
- packages/manager/src/features/Betas/index.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/accountBetas.ts
- packages/manager/src/utilities/betaUtils.ts
Adds the `BetaDetails` and `BetaDetailsList` components to list out the betas relevant to a user.
- Run `yarn test BetasLanding BetaDetailsList BetaDetails betaUtils`
> feat: [M3-6690] - Beta details

- yarn.lock
Committing latest tarn lock to develop
> chore: Update yarn lock

- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
- Caused by https://github.com/linode/manager/pull/9603
| ![Screenshot 2023-09-01 at 10 43 15 AM](https://github.com/linode/manager/assets/115251059/65cb3881-c3e6-4e9e-8062-7fd8cd71b7fa) | ![Screenshot 2023-09-01 at 10 43 32 AM](https://github.com/linode/manager/assets/115251059/aec0c892-c66f-4679-987a-309545bc5cdf) |
- Make sure `/account/billing/make-payment` looks good 🎨
> fix: Payment Drawer Style Regression from MUI Update 

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/queries/databases.ts
- packages/manager/src/queries/domains.ts
- packages/manager/src/queries/firewalls.ts
- packages/manager/src/queries/images.ts
- packages/manager/src/queries/kubernetes.ts
- packages/manager/src/queries/linodes/linodes.ts
- packages/manager/src/queries/nodebalancers.ts
- packages/manager/src/queries/volumes.ts
- packages/validation/.changeset/pr-9641-fixed-1694095072428.md
- packages/validation/CHANGELOG.md
- packages/validation/package.json
- packages/validation/src/linodes.schema.ts
-  Restricted users unable to edit Firewall after creation ([#9637](https://github.com/linode/manager/pull/9637))
- Edit interfaces config validation to allow null values for label and ipam_address ([#9641](https://github.com/linode/manager/pull/9641))
> Release v1.101.1 - staging → master

- packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
- packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts
Add integration tests for Community Stackscripts.
- Add test to check StackScripts are listed with expected info.
- Add test to check Pagination works as expected.
- Add test to check Search works as expected
- Add test to check Deploy flow works as expected
`yarn cy:run -s "cypress/e2e/core/stackscripts/smoke-community-stackscripts.spec.ts"`
> test: [M3-6551] - Add Community Stackscripts integration tests

- packages/manager/.changeset/pr-9658-added-1694206862050.md
- packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigs.tsx
- packages/manager/src/utilities/analytics.ts
Add a docs link to our configuration documentation, especially needed for UUID updates that are forthcoming.
- Add analytics event
- Add configuration docs link
- Cleaned up configuration component
1. Ensure docs link to https://www.linode.com/docs/products/compute/compute-instances/guides/configuration-profiles/
> feat: [M3-7060] - Add configuration docs for upcoming UUID update

- packages/manager/src/components/DynamicPriceNotice.tsx
- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
- packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
- packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx
- packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
- packages/manager/src/features/Linodes/LinodesCreate/constants.ts
- packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx
- packages/manager/src/utilities/pricing/constants.ts
Adding test coverage for the SelectRegionPanel.
This component has been modified (and will continue to be) to allow for the display of various warnings/notices related to the Dynamic DC Pricing feature.
Not adding a changeset here since this it completes the recent refactor of the component and is not particularly relevant in a changelog by itself.
1. Pull code locally and run `yarn test SelectRegionPanel.test.tsx`
> feat: [M3-6984] Test coverage for SelectRegionPanel

- packages/manager/.changeset/pr-9706-added-1695240077611.md
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Add the feature flag to the create menu.
- Feature flag on create menu
1. Turn off Managed Databases feature flag, menu item will be hidden.
> feat: [UIE-6899] - Add Database Feature Flag to Create Menu

- packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
- packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
This is causing our pipeline to fail
> fix: type error in SubnetUnassignLinodesDrawer

- packages/api-v4/src/aglb/routes.ts
- packages/api-v4/src/aglb/types.ts
- packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts
- packages/manager/cypress/support/intercepts/load-balancers.ts
- packages/manager/src/components/Autocomplete/Autocomplete.tsx
- packages/manager/src/components/LinkButton.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/factories/aglb.ts
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/AddRuleDrawer.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/MatchTypeInfo.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetSelect.tsx
- packages/manager/src/queries/aglb/routes.ts
- packages/manager/src/queries/aglb/serviceTargets.ts
- packages/manager/src/utilities/formikErrorUtils.test.ts
- packages/manager/src/utilities/formikErrorUtils.ts
- packages/validation/src/loadbalancers.schema.ts
- Adds AGLB Route - Add Rule Drawer 🎉
- Go to `http://localhost:3000/loadbalancers/0/routes`
- Click `Add Rule` on any route
- Test the "Add Rule" drawer for general functionality and style
- Test error states and success states
- Note: upon submit, a new rule won't show up in the table because of how the MSW works
> feat: [M3-7152] - Add AGLB Route Add Rule Drawer

- packages/api-v4/CHANGELOG.md
- packages/manager/CHANGELOG.md
- packages/validation/CHANGELOG.md
- Update API package's changelog to include changes for the `UpdateCertificatePayload` and `Certificate` interface
- Update Manager package's changelog to include AGLB Edit Certificate Drawer
- Update Validation package's changelog to include changes for `UpdateCertificateSchema`.
> Release v1.105.0 - Update API, Manager, and Validation changelogs

- packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.stories.tsx
Add storybook for `MigrationNotification` to `/Features/LinodesDetail/` section
- Run `yarn storybook`
- Go to http://localhost:6006/?path=/docs/features-linodesdetail-migrationnotification--documentation
> docs: Add MigrationNotification Storybook

- packages/api-v4/.changeset/pr-9800-upcoming-features-1698173062924.md
- packages/api-v4/src/aglb/service-targets.ts
- packages/manager/.changeset/pr-9800-upcoming-features-1698173161683.md
- packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts
- packages/manager/cypress/support/intercepts/load-balancers.ts
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/CreateServiceTargetDrawer.tsx
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/queries/aglb/serviceTargets.ts
- packages/validation/.changeset/pr-9800-upcoming-features-1698172955122.md
- packages/validation/src/loadbalancers.schema.ts
Add ability to edit a Service Target via a drawer. 
- Refactors `CreateServiceTargetDrawer.tsx` to `ServiceTargetDrawer.tsx` and is used in both add and edit modes
- Adds 'Edit' action menu item functionality to open the Service Target Drawer
- Adds integration test coverage for edit functionality
- Updates `apiv4` and `validation` packages in order to validate and submit the PUT request
- Updates mock endpoint for `rest.get('*/v4beta/aglb/:id/service-targets')` to test the edit flow more accurately 
https://github.com/linode/manager/assets/114685994/3ce21c30-0ec2-4bc8-b090-1bd1886fbf0a
- Check out this PR.
- Ensure AGLB feature flag is on.
- Turn the MSW on
- Go to http://localhost:3000/loadbalancers/0/service-targets.
- Open up the …
> feat: [M3-6888] - Add AGLB "Edit Service Target" drawer

- packages/manager/.changeset/pr-9882-tech-stories-1699380531301.md
- packages/manager/src/features/Support/AttachFileForm.test.tsx
- packages/manager/src/features/Support/AttachFileForm.tsx
- packages/manager/src/features/Support/AttachFileListItem.test.tsx
- packages/manager/src/features/Support/AttachFileListItem.tsx
- packages/manager/src/features/Support/ExpandableTicketPanel.tsx
- packages/manager/src/features/Support/Hively.tsx
- packages/manager/src/features/Support/SupportTicketDetail/AttachmentError.tsx
- packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/MarkdownReference.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyActions.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
- packages/manager/src/features/Support/SupportTickets/TicketRow.tsx
- packages/manager/src/features/Support/TicketAttachmentList.test.tsx
- packages/manager/src/features/Support/TicketAttachmentList.tsx
- packages/manager/src/features/Support/TicketAttachmentRow.tsx
- packages/manager/src/features/Support/TicketDetailText.tsx
Performs general refactors on `SRC > Features > Support` to reduce tech debt, use MUI v5 features, and make Support tickets look _slightly_ less broken.
- Rewrites some class components to functional components
- Makes the UI look a bit less broken
- Rewrite a few enzyme unit tests
- Runs the tss coded on 8 files
> [!note]
> Minimal UI changes are expected. Some styles may look different in attempts to make things look better.
| ![Screenshot 2023-11-07 at 12 46 44 PM](https://github.com/linode/manager/assets/115251059/b38bd0a5-9e29-4c6e-8a14-2e4464205e46) | ![Screenshot 2023-11-07 at 12 45 39 PM](https://github.com/linode/manager/assets/115251059/33b6bf11-d518-4394-aa32-6e4892d4fe3a) |
> [!warning]
> I recommend testing against the dev …
> refactor: [M3-7385]- MUI v5 Migration - `SRC > Features > Support`

- packages/manager/.changeset/pr-9924-tests-1700679833619.md
- packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts
- packages/manager/cypress/support/intercepts/load-balancers.ts
- packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
- Adds more e2e testing 🧪 for AGLB configurations
- `yarn cy:debug`
- Run `load-balancer-configurations.spec.ts`
> test: [M3-7132] - Add AGLB Configuration e2e tests

- packages/manager/.changeset/pr-9931-upcoming-features-1700686098973.md
- packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.test.tsx
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.styles.ts
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
This PR is to place the Firewall-Nodebalancer behind a feature flag.
- Created new feature flag in featureFlags.ts
- Placed code behind feature flag
- Access to Launch Darkly
Toggle the flag on and off and ensure the feature work toggles as well in the following pages:
| On  | Off   |
| ![Screenshot 2023-11-22 at 3 40 16 PM](https://github.com/linode/manager/assets/139489745/0e4c65f9-826f-4930-80c5-28d9dcb3d061) | ![Screenshot 2023-11-22 at 3 57 08 PM](https://github.com/linode/manager/assets/139489745/a93085d8-f09f-4c6d-869d-61781ca52c19) |
| On  | Off   |
| ![Screenshot 2023-11-22 at 3 40 23 PM](https://github.com/linode/manager/assets/139489745/eec7ba58-bbf2-4ae1-b618-fb92f1bca67c) | ![Screenshot …
> feature: [M3-7442] - Put Firewall-Nodebalancer behind feature flag

- packages/manager/.changeset/pr-10004-tests-1702676791962.md
- packages/manager/cypress/e2e/core/domains/domains-empty-landing-page.spec.ts
- packages/manager/cypress/e2e/core/domains/domains-landing-page.spec.ts
- integration test for domains empty landing page
- yarn cy:run -s "cypress/e2e/core/domains/domains-empty-landing-page.spec.ts"
> test: [M3-7466] - Add integration test for Domains empty landing page

- packages/manager/.changeset/pr-10060-upcoming-features-1704989096198.md
- packages/manager/src/dev-tools/EnvironmentToggleTool.tsx
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/dev-tools/dev-tools.css
- packages/manager/src/featureFlags.ts
Small PR to add feature flag tools for VM Placement
- Confirm flag is being returned from Launch Darkly and available in our dev tools
> upcoming: [M3-7606] VM Placement feature flag

- packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
Fix broken unit test for KubeCheckoutBar
Fix broken e2e test for LKE create flow.
| ![image](https://github.com/linode/manager/assets/119517080/0871eac1-e39a-4c4a-a4e0-3d0f9191a0d2)| ![image](https://github.com/linode/manager/assets/119517080/35e6f467-069c-4480-8564-3897a102b31f)|
- Navigate to LKE create.
- Validate the verification steps mentions in this PR https://github.com/linode/manager/pull/10141
---
> fix: Broken LKE unit and e2e tests

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/components/TextTooltip/TextTooltip.test.tsx
- packages/manager/src/components/TextTooltip/TextTooltip.tsx
- Tooltip not closing when unhovered ([#10523](https://github.com/linode/manager/pull/10523))
> Release v1.120.1 - staging → master

- packages/manager/.changeset/pr-10586-upcoming-features-1718384912084.md
- packages/manager/src/factories/stackscripts.ts
- packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSelect.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppsList.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/utilities.test.ts
- packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/utilities.ts
- Adds the ability to search / filter Marketplace apps on the new Linode Create flow 🔍 
https://github.com/linode/manager/assets/115251059/ff8eb927-722a-42c6-b4d5-1d5b744af130
- Turn on the **Linode Create v2** feature flag 
- Test the searching / filtering functionality
- Compare functionality to the old Linode Create flow, ensure it provides the same user experience
> upcoming: [M3-8265] - Linode Create v2 - Add Marketplace Searching / Filtering

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/utilities.ts
- Object Storage showing incorrect object URLs ([#10603](https://github.com/linode/manager/pull/10603))
> Release v1.121.2 - staging → master

- .github/workflows/stale.yml
- Adds a Github Action to auto-close stale PRs
- Based on the [DX team's workflow](https://github.com/linode/linodego/blob/main/.github/workflows/stale.yml)
> feat: [M3-8207] - Auto-close Stale Issues/PRs with Github Actions

- packages/manager/.changeset/pr-10692-upcoming-features-1721254990748.md
- packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts
- packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/EUAgreement.test.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/EUAgreement.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/SMTP.test.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/SMTP.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts
- packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts
- Adds the "EU Agreement" to Linode Create v2 🇪🇺 
- Should show if you have not previously agreed to the EU agreement and you are trying to deploy to an EU region
- Use an account that **does not** have the `eu_model` agreement set to `true` (look for the `/v4/account/agreements` API request on the Linode Create page )
- I am using devenv to do this because you can't unsign agreements as far as I know🙄 
- Verify the checkbox shows if
- You have not agreed to the `eu_model`
- You have selected an EU region
- Verify you get a validation error if you try to create a Linode in an EU region when the checkbox is showing and you have not checked it
- Verify that creating a Linode in an EU region causes the EU agreement to be signed
> upcoming: [M3-8315] - Add EU Agreement to Linode Create v2

- packages/manager/.changeset/pr-10746-added-1722932770115.md
- packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketProductSelectionFields.tsx
- packages/manager/src/features/Support/SupportTickets/constants.tsx
- packages/manager/src/utilities/getEventsActionLink.ts
Users should have the ability to open up support tickets about specific VPCs as they can do for other entities. 
- Added "VPCs" as an option in the "What is this regarding?" dropdown menu
- Added a subsequent field for the user to select a specific VPC on their account. 
| ![12_16_32](https://github.com/user-attachments/assets/79dba25a-e4d9-42bb-be02-4f86ec3902a3)| ![12_17_15](https://github.com/user-attachments/assets/55b9b25e-4a14-4585-9524-7ace7371c4a8)|
- *Please test in the dev environment if submitting any support tickets to avoid bothering Customer Support with extra  tickets.*
- Navigate to [http://localhost:3000/support/tickets?type=open](http://localhost:3000/support/tickets?type=open)
- Click on 'Open New Ticket' to create a new …
> feat: [M3-7447] Added Support for VPCs in 'Open Support Ticket' Flow

- packages/manager/.changeset/pr-10870-added-1725366701050.md
- packages/manager/src/components/SelectableTableRow/SelectableTableRow.stories.tsx
- packages/manager/src/components/SelectableTableRow/SelectableTableRow.tsx
Add SelectableTableRow Story to Storybook
- Add SelectableTableRow Story
9/16
- Run yarn storybook to test locally
> feat: [M3-8178] - Add SelectableTableRow Story

- packages/manager/.changeset/pr-10879-tests-1725646369852.md
- packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
- New Integration Test for Object Storage Gen2: E2 Endpoint - Bucket Creation
N/A
- `yarn cy:run -s "cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts"`
> test: [M3-8434] - Cypress integration test for Object Storage Gen2: E2 Endpoint

- packages/manager/.changeset/pr-10904-added-1725873382370.md
- packages/manager/src/components/DisplayPrice/DisplayPrice.stories.tsx
- packages/manager/src/components/DisplayPrice/DisplayPrice.tsx
Add DisplayPrice Story to Storybook
- Add story for SelectableTableRow component
9/16
- Run yarn storybook to test locally
> feat: [M3-8173] - Add DisplayPrice Story

- packages/manager/.changeset/pr-10905-added-1725893781288.md
- packages/manager/src/components/CheckoutSummary/CheckoutSummary.stories.tsx
- packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
Add CheckoutSummary Story to Storybook
- Added CheckoutSummary Story
N/A
- Run `yarn storybook` to test locally
> feat: [M3-8171] - Add CheckoutSummary Story

- packages/manager/.changeset/pr-10911-tests-1725912717549.md
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.test.tsx
Added unit tests for several files in the NodeBalancersLanding package
n/a
- `yarn test NodeBalancersLanding` 
- (note - there is a console error that appears when running the test - will see what I can do but it might be something to do with mui based on the stacktrace?)
> test: [M3-8555] - Add unit tests for NodeBalancersLanding package

- packages/manager/cypress/e2e/core/linodes/create-linode-view-code-snippet.spec.ts
- packages/manager/src/__data__/ldClient.ts
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/AnsibleIntegrationResources.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/CurlTabPanel.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/GoSDKResources.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/LinodeCLIPanel.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/PythonSDKResources.tsx
- packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/TerraformIntegrationResources.tsx
- packages/manager/src/features/Linodes/LinodesCreate/CodeBlock/CodeBlock.tsx
Fixes broken cypress tests by merging  #10906
> Fix broken cypress tests caused by -  #10906

- packages/manager/.changeset/pr-10942-added-1726774387695.md
- packages/manager/.storybook/main.ts
- packages/manager/package.json
- yarn.lock
We could utilize Storybook more. One way we could do that is by using it for Accessibility testing when developing a component
- Add Accessibility tab to Stories
https://github.com/user-attachments/assets/a61c8030-63f0-4a0c-8524-30bb841b8253
- Pull this PR and run storybook locally
- Open a Story and you should see a new Accessibility tab
> feat: [M3-8185] - Add Accessibility tab to Storybook Stories

- packages/manager/.changeset/pr-10987-upcoming-features-1727113889522.md
- packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx
- packages/manager/src/features/Linodes/LinodeCreatev2/TwoStepRegion.tsx
Update region helper description text for Core and Distributed tabs
| ![image](https://github.com/user-attachments/assets/2c5b09d9-3df2-4e79-a4b4-bcd104af0cac) | ![Screenshot 2024-09-23 at 1 49 01 PM](https://github.com/user-attachments/assets/db06f318-8a83-454f-aade-378b2dd98f39) |
| ![image](https://github.com/user-attachments/assets/25401f9f-e4e3-408f-9ed5-08f3eb4c2b7c) | ![Screenshot 2024-09-23 at 1 49 21 PM](https://github.com/user-attachments/assets/4833bf80-97fd-4f7f-bec2-9969de0e9b31) |
- Ensure your account has the `new-dc-testing`, `new-dc-testing-gecko`, `edge_testing` and `edge_compute` customer tags
- Pull this PR and run it locally pointing to dev API
- Go to the Linode Create …
> upcoming: [M3-8624] - Update Region description helper text

- packages/manager/.changeset/pr-11010-fixed-1727359551617.md
- packages/manager/CHANGELOG.md
- Unable to push directly to staging, so opening up this PR to update the changelog to account for #11010 
- confirm changelog fix
- confirm testing steps for pr #11010
> Update changelog and remove changeset for DBaas fix

- packages/manager/.changeset/pr-11061-tests-1728374977579.md
- packages/manager/src/components/CheckoutSummary/CheckoutSummary.test.tsx
- packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
Unit test cases for CheckoutSummary Component
- Added unit test cases for CheckoutSummary Component
N/A
- Check if all the unit tests pass
> test: Unit tests for CheckoutSummary component

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/legacy/DatabaseSummaryConnectionDetailsLegacy.tsx
- Hostnames not showing on the Database details page ([#11182](https://github.com/linode/manager/pull/11182))
> Release v1.131.1 - staging → master

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Kubernetes/CreateCluster/ApplicationPlatform.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/APLSummaryPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/kubeUtils.test.ts
- packages/manager/src/features/Kubernetes/kubeUtils.ts
- packages/manager/src/features/components/PlansPanel/constants.ts
- packages/manager/src/features/components/PlansPanel/utils.ts
- packages/manager/src/queries/account/betas.ts
- packages/manager/src/queries/kubernetes.ts
- APL summary panel not being loaded consistently ([#11207](https://github.com/linode/manager/pull/11207))
> Release v1.131.2 - staging → master

- packages/api-v4/.changeset/pr-11181-added-1730207508835.md
- packages/api-v4/src/iam/iam.ts
- packages/api-v4/src/iam/types.ts
- packages/api-v4/src/index.ts
- packages/api-v4/src/resources/index.ts
- packages/api-v4/src/resources/resources.ts
- packages/api-v4/src/resources/types.ts
- packages/manager/.changeset/pr-11181-added-1730207569813.md
- packages/manager/src/factories/accountPermissions.ts
- packages/manager/src/factories/accountResources.ts
- packages/manager/src/queries/iam/iam.ts
- packages/manager/src/queries/iam/queries.ts
- packages/manager/src/queries/resources/queries.ts
- packages/manager/src/queries/resources/resources.ts
IAM RBAC - new account api with
- Added new api for Account
- No visible changes
Nov 12, 2024 (dev)
> feat: [UIE-8128] - IAM RBAC add new account api with

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx
- packages/manager/src/features/components/PlansPanel/APLNotice.tsx
- packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx
- packages/manager/src/features/components/PlansPanel/PlanInformation.tsx
- packages/manager/src/features/components/PlansPanel/constants.ts
- packages/manager/src/features/components/PlansPanel/utils.ts
Hotfix branch based on https://github.com/linode/manager/pull/11216. See link for details
> hotfix: APL-354 to staging

- packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-navigation.spec.ts
- packages/manager/cypress/e2e/core/cloudpulse/dbaas-widgets-verification.spec.ts
- packages/manager/cypress/e2e/core/cloudpulse/linode-widget-verification.spec.ts
- packages/manager/src/MainContent.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsDefinitionLanding.tsx
- packages/manager/src/features/CloudPulse/Alerts/AlertsLanding/AlertsLanding.tsx
- packages/manager/src/features/CloudPulse/CloudPulseLanding.tsx
- packages/manager/src/features/CloudPulse/CloudPulseTabs.tsx
- packages/manager/src/routes/cloudPulse/index.ts
Updated tech docs & ACLP path url
1. Update tech docs url to https://techdocs.akamai.com/cloud-computing/docs/akamai-cloud-pulse
2. Updated ACLP url from `/monitor/cloudpulse` to `/monitor`
3. Updated routing for every `/monitor/*` path to redirect to default `/monitor/dashboards`
4. Updated routing for every `/monitor/alerts/*` path to redirect to default `/monitor/alerts/definitions`
2 Dec 2024
https://github.com/user-attachments/assets/5ac29120-0d48-4177-80ad-9900fa4fa704
1. On the monitor tab click `Docs` on top right for tech docs
2. add anything after `/monitor/` and …
> upcoming: [DI-22040] - Updated tech docs & ACLP path url

- packages/manager/.changeset/pr-11394-tests-1733856095533.md
- packages/manager/.changeset/pr-11394-tests-1733856145159.md
- packages/manager/cypress/e2e/core/billing/smoke-billing-activity.spec.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.test.tsx
-  Cleaned up `DatabaseBackups.test.tsx` to hopefully finally stop flake 🧹 
- I cleaned up the tests as much as possible (for example removed unnecessary mocks)
- Fixed some flawed tests
- Separated DBaaS v1 and V2
- Removed assertions known to be flakey
- Fixed up `smoke-billing-activity.spec.ts` after @abailly-akamai patched it 🧹 
- Added some extra assertions
- Re-added dynamic timezone label
- Fixes incorrect `key` for `Coordinated Universal Time`
```sh
yarn cy:run -s cypress/e2e/core/billing/smoke-billing-activity.spec.ts 
```
```sh
yarn workspace linode-manager test DatabaseBackups
```
<details>
🤏 Splitting feature into …
> test: Fix and clean up `smoke-billing-activity.spec.ts` and `DatabaseBackups.test.tsx`

- packages/manager/.changeset/pr-11467-tech-stories-1735836122260.md
- packages/manager/package.json
- yarn.lock
- Updates `react-vnc` to the latest version (`2.0.2`)
- There are no breaking changes that I'm aware of!
- Verify **GLISH** works as expected with no regressions
<details>
♿  Providing …
> dep: [M3-8955] - Update react-vnc to 2.0.2

- packages/api-v4/.changeset/pr-11429-upcoming-features-1734442308306.md
- packages/api-v4/src/resources/types.ts
- packages/manager/.changeset/pr-11429-upcoming-features-1734442339368.md
- packages/manager/src/factories/accountResources.ts
- packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Shared/utilities.ts
- packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
- packages/manager/src/mocks/serverHandlers.ts
IAM RBAC - new entities component. This component currently uses mock data for demonstration purposes. The mock data will be removed in the next PR for the `Assign Permission component`.
- new entities component
1/14/25 (dev)
| 📷 | ![image](https://github.com/user-attachments/assets/e43789a3-fd15-4379-b442-e80c98e38963) |
- Click on the username in the users table and go to …
> feat: [UIE-8134] - IAM RBAC: add new entities component

- packages/manager/.changeset/pr-11513-changed-1736782843874.md
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketRateLimitTable.tsx
We're going to be routing customers to a different tech doc for this now.
01/28
- Verify that the link goes to the proper section in tech docs
<details>
♿  Providing accessibility …
> change: Update understanding bucket rate limits for OBJ Gen2

- packages/manager/.changeset/pr-11593-tech-stories-1738564796090.md
- packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
- packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
- packages/manager/src/features/Managed/MonitorDrawer.tsx
Ramda should be completely removed/replaced with native JS equivalent
- Remove ramda from `Managed`
- Remove 🧹 ramda from:
- `packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx`
- `packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx`
- `packages/manager/src/features/Managed/MonitorDrawer.tsx`
N/A
<details>
🚩 Using a feature flag …
> refactor: [M3-8256] - Remove `ramda` from Managed

- packages/api-v4/.changeset/pr-11597-upcoming-features-1738601486075.md
- packages/api-v4/src/quotas/quotas.ts
- packages/api-v4/src/quotas/types.ts
- packages/manager/.changeset/pr-11597-upcoming-features-1738601515225.md
- packages/manager/src/factories/quotas.ts
- packages/manager/src/mocks/presets/crud/handlers/quotas.ts
- packages/manager/src/queries/quotas/quotas.ts
Small PR to update the code (types, queries, mocks) to account for recent API spec changes.
> [!NOTE]
> This change has no effect on any runtime code as the moment, since this feature is in is infancy and the UI has not been implemented yet.
API specs available in Jira and KB project tracker
- Add support for new /usage endpoint
- Remove `used` from the `Quotas` payload since now returned by the usage endpoint
<details> …
> upcoming: [M3-9224] - Limits evolution: revise types, queries and mock data

- packages/manager/.changeset/pr-11596-tests-1738650165686.md
- packages/manager/cypress/e2e/core/cloudpulse/alert-show-details.spec.ts
- packages/manager/cypress/support/intercepts/cloudpulse.ts
- packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
Adding New Tests for Resource and Notification Changes
This update includes new automated tests to verify the accuracy and functionality of resource details and notification changes. The tests ensure that:
Resource details are correctly fetched and updated.
Notification settings are accurately applied and updated.
The system behaves as expected when changes are made to resources or notifications.
- ...
- ...
https://github.com/user-attachments/assets/8b82b8d1-32e1-4749-add4-92035f229591
| …
> test: [DI-22613] - ACLP: Automate Resource Details and Notification Changes with enhanced test coverage

- packages/manager/.changeset/pr-11605-upcoming-features-1738668460766.md
- packages/manager/src/factories/accountPermissions.ts
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.test.tsx
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
- packages/manager/src/features/IAM/Shared/utilities.test.ts
- packages/manager/src/features/IAM/Shared/utilities.ts
- packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
- packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
- packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
IAM RBAC - new assign panel component
- new assign panel component
- fixing styles for `Permissions` and `Entities` components
- fixing a bug in the `Permissions` component when there are fewer than two lines of items
2/11/25 (dev)
| ![image](https://github.com/user-attachments/assets/9363e9cf-3cbc-4fb2-b402-7a61c3f389ae) | ![image](https://github.com/user-attachments/assets/f0f27383-df00-4611-9511-ba3297051f85) |
| …
> feat: [UIE-8135] - IAM RBAC: add new assign panel component

- docs/GETTING_STARTED.md
- packages/manager/.changeset/pr-11622-changed-1738868106892.md
> This PR makes a small update to the guide and helps me get familiar with the contribution process for this repository.
This PR updates the Getting Started section of the README to clarify the OAuth App setup process. It adds a note to check the "Public" checkbox when creating an OAuth App.
- `docs/GETTING_STARTED.md` - Getting Started step 4
2/25/25
|<img src="https://github.com/user-attachments/assets/273df943-d938-44cc-a843-7b6a3d895667"/> | <img src="https://github.com/user-attachments/assets/49e5a122-ce87-4244-9282-70b87ca580f0"/> |
- N/A
<details> …
> docs: [NO-TICKET] - Update ReadMe: Getting Started OAuth Token Step

- packages/manager/.changeset/pr-11635-fixed-1739187388251.md
- packages/manager/src/features/Account/AccountLogins.tsx
- packages/manager/src/features/Account/GlobalSettings.tsx
- packages/manager/src/features/Betas/BetasLanding.tsx
- packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/index.tsx
- packages/manager/src/features/IAM/Users/UsersTable/Users.tsx
- packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
- packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
- packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
- packages/manager/src/features/Linodes/LinodesLanding/LinodesLandingEmptyState.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/OMC_BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx
- packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
- packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
- packages/manager/src/routes/images/ImagesRoute.tsx
- packages/manager/src/routes/placementGroups/PlacementGroupsRoute.tsx
This PR addresses inconsistencies in document titles for the `Create Landing Pages`. The title has been updated to ensure consistency with the appropriate keyword formatting used across other pages in the platform.
This change has been applied wherever needed across the CM to maintain consistent title formatting throughout.
- Update document title for `Create Landing Pages` to the correct format:
- Other necessary title updates across the CM for consistency.
N/A
| ![Before](https://github.com/user-attachments/assets/33cb201d-6460-48cc-81a9-0bac629ef72a)| ![After](https://github.com/user-attachments/assets/3ba3ec6e-69bc-4135-a3c9-55a1797c13f5) |
| ![Before](https://github.com/user-attachments/assets/744944b5-25eb-4df5-9386-af4e1f5e7003) | …
> fix: [M3-9078] - Ensure document titles for all pages have appropriate keywords

- packages/manager/.changeset/pr-11660-tests-1739459826226.md
- packages/manager/src/features/Databases/utilities.test.ts
DBaaS: Backups unit test fix.
02/25/2025
| 📷 | 📷 |
- Run Databases/utilities.test.ts   
<details>
♿  Providing …
> test: [UIE-8528] - DBaaS: Backups unit test fix

- packages/manager/.changeset/pr-11689-tests-1739986270581.md
- packages/manager/.eslintrc.cjs
- packages/manager/cypress/support/util/linodes.ts
- packages/manager/package.json
- packages/ui/package.json
- yarn.lock
Applying v0.7 of eslint-plugin-cloud-manager repo to flag usage of createLinode function in cypress test files. The new no-createLinode rule flags usage of the createLinode fn anywhere. But we obviously only want to prohibit it in test files, and not in src. But i have to apply the prohibition everywhere and then allow it in the src directory, and also allow it in the packages/manager/cypress/support/util/linodes.ts file w/ a eslint-disable-next-line exception.
-Update the version of the eslint-plugin-cloud-manager from 0.6 to 0.7
-Configure the severity and scope of the rule in the eslint.cjs
-Add exception to allow direct usage in packages/manager/cypress/support/util/linodes.ts
-yarn install
-yarn lint
<details>
❔ Our …
> test: [M3 8672] - use eslint to flag createLinode function 

- packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
Highlight the Pull Request's context and intentions.
- ...
- ...
<br/>
---
> test: [DI-23274] - Fix lint issue for `create-user-alert.spec.ts`

- packages/api-v4/src/account/types.ts
- packages/manager/.changeset/pr-11672-fixed-1739863532671.md
- packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
- packages/manager/cypress/e2e/core/objectStorageGen2/bucket-create-gen2.spec.ts
- packages/manager/src/factories/grants.ts
- packages/manager/src/features/Account/constants.ts
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLandingEmptyState.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Disable OBJ Create Flow for Restricted user
- Disable OBJ Create Flow for Restricted user
N/A
| ![Before](https://github.com/user-attachments/assets/6fa2cd4e-7325-4912-b27e-0f065e7168bb)| ![After](https://github.com/user-attachments/assets/3f26ec26-e58a-41b8-a578-57b84d69ee35) |
| ![Before](https://github.com/user-attachments/assets/2e6b8dd3-8303-4882-b6fd-6ee3eb8cbf05)| ![After](https://github.com/user-attachments/assets/1a47a076-76a2-45a8-b5c6-49f673cbdc2d) |
- Login to CM using restricted-user with no access
<details>
➕ Adding a …
> fix: [M3-9146] - Disable OBJ create flow for restricted user

- packages/utilities/.changeset/pr-11749-tech-stories-1740669995320.md
- packages/utilities/package.json
- pnpm-lock.yaml
Update `@vitest/ui` in `utilities` package
- Update  @vitest/ui  from "^2.1.1" to "^3.0.3" in utilities' package.json
N/A
- Ensure `pnpm-lock.yml` changes look correct
- Ensure all checks pass
<details>
📱 …
> deps: [M3-9442] - Update `@vitest/ui` in `utilities` package

- packages/manager/src/components/BarPercent/BarPercent.test.tsx
- packages/manager/src/components/BarPercent/BarPercent.tsx
- packages/manager/src/components/BarPercent/utils.test.ts
- packages/manager/src/components/BarPercent/utils.ts
- packages/manager/src/components/TableRowEmpty/TableRowEmpty.tsx
- packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
- packages/manager/src/features/Account/Quotas/Quotas.test.tsx
- packages/manager/src/features/Account/Quotas/Quotas.tsx
- packages/manager/src/features/Account/Quotas/QuotasTable.test.tsx
- packages/manager/src/features/Account/Quotas/QuotasTable.tsx
- packages/manager/src/features/Account/Quotas/utils.test.tsx
- packages/manager/src/features/Account/Quotas/utils.ts
- packages/manager/src/mocks/presets/crud/handlers/quotas.ts
- packages/manager/src/mocks/presets/crud/quotas.ts
Build a new Quotas table for the Limits M1 milestone.
- Build new components and move relevant queries there
- Build UI, loading & error patterns
- Add `customColors` prop to our `<BarPercent />` component
- Add coverage (unit tests)
- use CRUD mode in dev tools
- use an API delay to confirm loading states (I used `1000ms`)
- Navigate to /account/quotas.
- Play with service and location controls and confirm:
- UI matches figma (see project tracker or epic)
- Loading patterns
- Error handling
- Pagination
- Proper copy
- tests pass
<details>
➕ Adding a …
> upcoming: [M3-9396] - Quotas Table

- packages/api-v4/.changeset/pr-11818-upcoming-features-1741627601695.md
- packages/api-v4/src/quotas/quotas.ts
- packages/manager/src/mocks/presets/crud/handlers/quotas.ts
Switch the quota endpoint to use beta endpoints (new requirement)
- Update APIv4 quota endpoints
- Update CRUD handlers to intercept either
- Locally, navigate to `/account/quotas`
- Confirm requests point to beta and are properly intercepted by MSW
<details>
📑 Providing or updating our …
> upcoming: [M3-9496] - Beta Quota Endpoints

- packages/manager/.changeset/pr-11815-upcoming-features-1741615995524.md
- packages/manager/src/queries/cloudpulse/alerts.ts
Added refetch interval of 2 min in alerts all & alerts by service type queries
1. Updated alerts.ts file with refetchInterval parameter
12th March
| 📷 | 📷 |
1. Switch to mock user
2. Go to monitor tab & select alerts
3. Notice alerts data fetching at an interval of 2 mins
- ...
- ...
<details> …
> upcoming: [DI-23817] - Added refetch interval in alerts query

- packages/manager/cypress/e2e/core/stackscripts/delete-stackscripts.spec.ts
fix linting error in cypress test file
> M3_8370 emergency fix for linting error

- .github/workflows/e2e_schedule_and_push.yml
I'm so sorry 😭😅. Next time I'll go through the trouble of setting up my secrets on my account so I can test this beforehand, really didn't think it was worth the trouble for what (I thought) would be such a small change.
- Set `record` to false
| 📷 | 📷 |
- ...
- ...
(How …
> fix: [M3-9508] - Set GHA Cypress action `record` action property to `false` (one last fix)

- packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
- Fixes failing checks due to a recent merge to develop with an incorrect `Drawer` import
> fix: Incorrect Drawer import in IAM

- packages/manager/.changeset/pr-11945-changed-1743511226551.md
- packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.test.tsx
- packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetail.tsx
- packages/manager/src/queries/cloudpulse/alerts.ts
Added 2 mins refetch interval to alerts details query.
1. Updated alerts.ts to add refetch interval
2. Updated AlertDetails.tsx to use isLoading instead of isFetching 
8th April
| 📷 | 📷 |
1. Switch as mock user
2. Go to alerts tab from mega menu
3. Click on an alert from the list of alerts, you'll see alert details page
4.  Open the network tab and you'll notice that alert details api call will go in every 2 min interval.
<details>
👀 Doing a self …
> refactor: [DI-24423] - Added a refetch interval to alert details query

- packages/api-v4/.changeset/pr-11938-upcoming-features-1743446020892.md
- packages/api-v4/src/vpcs/types.ts
- packages/api-v4/src/vpcs/vpcs.ts
- packages/manager/.changeset/pr-11938-upcoming-features-1743446079043.md
- packages/manager/src/factories/vpcs.ts
Update types for VPC IPs to support IPv6
<details>
<br/>
</details>
> upcoming: [M3-9515] - Update types for VPC IPs

- packages/manager/src/features/components/PlansPanel/constants.ts
Updates Learn more link for Accelerated plans
next release
- Confirm "Learn More" link (second link - 'Learn more about our Accelerated Plans') goes to https://techdocs.akamai.com/cloud-computing/docs/accelerated-compute-instances
<details>
🕛 …
> change: Update docs link for Accelerated Linode Plans GA Launch

- package.json
- packages/manager/.changeset/pr-12002-tech-stories-1744219481332.md
- packages/manager/Dockerfile
- packages/manager/package.json
- pnpm-lock.yaml
- Upgrades Cypress to 14.3.0
- See https://docs.cypress.io/app/references/changelog 
- This _should_ resolve our failing Cypress Github Action 🤞 
- Run `pnpm i`
- Ensure Cypress works
- For example, run `pnpm cy:debug` and run a test using the GUI
<details>
📑 Providing or …
> deps: [M3-9749] - Upgrade Cypress to 14.3.0

- packages/manager/.changeset/pr-12044-upcoming-features-1744808175869.md
- packages/manager/src/MainContent.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
- packages/manager/src/features/IAM/Shared/utilities.ts
- packages/manager/src/features/IAM/Users/UserRoles/AssignedEntities.tsx
- packages/manager/src/features/IAM/hooks/useCalculateHiddenItems.ts
- packages/manager/src/features/IAM/hooks/useIsIAMEnabled.test.ts
- packages/manager/src/features/IAM/hooks/useIsIAMEnabled.ts
- packages/manager/src/queries/entities/entities.ts
- packages/manager/src/queries/iam/iam.ts
Add an API access to check along with the feature flag check for IAM access.
- Move hooks out of utilities.ts into their own dir/file
- Add API check to useIsIAMEnabled hook
- Add tests for useIsIAMEnabled hook
4/22/25
- devenv setup to verify access
- devcloud or other environment to test blocked access via API
- Verify Identity & Access Management is not visible in primary nav and cannot be navigated to directly via url.
<details>
🔐 Removing all …
> feat[UIE-8656] - IAM / RBAC useIsIAMEnabled hook to check user API access

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Add isIAMBeta and isIAMEnabled to memo deps in PrimaryNav
- Add isIAMBeta and isIAMEnabled to memo deps in PrimaryNav
4/22/25
| 
| 
|
- devenv setup
- vagrant user
- feature flag enabled
- login with vagrant user view menu in left nav
- IAM is visible in left nav
<details>
👣 Providing …
> feat[UIE-8656]: IAM/RBAC - Add isIAMBeta and isIAMEnabled to memo deps

- packages/manager/.changeset/pr-12064-changed-1744993764105.md
- packages/manager/src/components/Snackbar/Snackbar.tsx
- packages/ui/src/foundations/themes/dark.ts
- packages/ui/src/foundations/themes/light.ts
This PR implements design feedback on https://github.com/linode/manager/pull/11962
- Removes vertical centering of icon in Toasts
- Uses correct design token property for the icon background
4/22/25
| <img src="https://github.com/user-attachments/assets/655cf0e7-a537-4172-b073-19d4e5124dbb"/> | <img src="https://github.com/user-attachments/assets/b25b9375-2eb5-4d79-8d04-ce26237b240d"/> |
<details>
🔐 …
> change: [M3-9655] - [Akamai Design System] Toast Component - Design Feedback

- packages/api-v4/.changeset/pr-12053-upcoming-features-1744891132478.md
- packages/api-v4/src/iam/types.ts
- packages/manager/.changeset/pr-12053-upcoming-features-1744891161989.md
- packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
- packages/manager/src/features/IAM/Shared/Entities/Entities.test.tsx
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Shared/constants.ts
- packages/manager/src/features/IAM/Shared/utilities.test.ts
- packages/manager/src/features/IAM/Shared/utilities.ts
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
Added a logic for facade roles
- Logic has been added to retrieve descriptions for facade roles (roles without permissions).
- Logic has been added for overriding the entity types “VPC”, “NodeBalancer”, and “StackScript”
(dev)
| ![image](https://github.com/user-attachments/assets/7683290e-a7d0-4ef9-8716-09515169d964) | ![image](https://github.com/user-attachments/assets/241d0132-0a1b-4963-a581-e47dd9d328ae)|
| 📷 | ![image](https://github.com/user-attachments/assets/add974d7- …
> feat: [UIE-8671] - IAM RBAC: facade roles description

- packages/manager/.changeset/pr-12098-changed-1745515258326.md
- packages/manager/src/components/DismissibleBanner/DismissibleBanner.stories.tsx
- packages/manager/src/components/Encryption/Encryption.tsx
- packages/manager/src/components/ErrorMessage.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
- packages/manager/src/features/Linodes/LinodeCreate/Tabs/Backups/BackupsWarning.tsx
- packages/manager/src/features/Linodes/LinodeCreate/Tabs/Clone/CloneWarning.tsx
- packages/manager/src/features/Linodes/LinodesDetail/VolumesUpgradeBanner.tsx
- packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
- packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
- packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeActionNotice.tsx
- packages/ui/src/components/Notice/Notice.stories.tsx
- packages/ui/src/components/Notice/Notice.styles.ts
- packages/ui/src/components/Notice/Notice.test.tsx
- packages/ui/src/components/Notice/Notice.tsx
- packages/ui/src/foundations/themes/light.ts
- Page-level notifications should be stretched to the full width of the screen (content area)
- Notifications inside Papers should match the width of the message text
- Margin/padding fixes for lists in a notice
- Updated list styling inside notice
- Updated notice width inside paper
- Updated notice and dismissible banner stories
- Fix Icon and text alignment for ErrorMessage
- Other various notice fixes
| ![image](https://github.com/user-attachments/assets/9455d3ad-3b14-4807-915a-a946ed46c9f2) | ![image](https://github.com/user-attachments/assets/656d052f-c59b-4933-ba5f-3b19942026a5) |
| ![image](https://github.com/user-attachments/assets/6315576e-2a1f-409e-8e10-1be777e009b3) | ![image](https://github.com/user-attachments/assets/54540549-408b-4 …
> change: [M3-9809] - Notice paper and list spacing

- packages/api-v4/src/account/payments.ts
- packages/manager/.changeset/pr-12136-fixed-1746028814998.md
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/index.ts
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
- packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
- packages/queries/.changeset/pr-12136-added-1746028890631.md
- packages/queries/src/account/payment.ts
- Fixes the dark mode UI issues with our PayPal buttons
- Does some general clean up 🧹 
- Creates and uses `useAddPaymentMethodMutation` to replace some direct api-v4 calls
- Cleans up some default exports
- Replaces some instances of `Grid` with `Stack`
| ![Screenshot 2025-04-30 at 11 52 21 AM](https://github.com/user-attachments/assets/d80dff2e-a3cc-4115-9059-49256052aee6) | ![Screenshot 2025-04-30 at 11 52 11 AM](https://github.com/user-attachments/assets/15ca3987-9c52-4ef3-8516-aa54105a902d) |
| ![Screenshot 2025-04-30 at 11 52 54 AM](https://github.com/user-attachments/assets/f01e1289-1e88-4cb7-b2b2-9b7ffc248db8) | ![Screenshot 2025-04-30 at 11 52 47 AM](https://github.com/user-attachments/assets/1865b19c-f9a1-4ca4-befb-9998f6a642bf) |
- …
> fix: [M3-9847] - PayPal button styles in dark mode

- packages/manager/.changeset/pr-12167-upcoming-features-1746614302548.md
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/AssignedRolesTable.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.test.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/ChangeRoleDrawer.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.test.tsx
- packages/manager/src/features/IAM/Shared/AssignedRolesTable/UpdateEntitiesDrawer.tsx
- packages/manager/src/features/IAM/Shared/constants.ts
- packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
- packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.test.tsx
- packages/manager/src/features/IAM/Users/UserEntities/ChangeRoleForEntityDrawer.tsx
- packages/manager/src/features/IAM/Users/UserEntities/UserEntities.test.tsx
- packages/manager/src/features/IAM/Users/UserEntities/UserEntities.tsx
- packages/manager/src/features/IAM/Users/UserRoles/UserRoles.test.tsx
- packages/manager/src/features/IAM/Users/UserRoles/UserRoles.tsx
- packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.test.tsx
- packages/manager/src/features/IAM/Users/UsersTable/UsersActionMenu.tsx
Update text across the iam, update the tests, update the sorting logic for Assigned Roles table
- Update text
- Update logic for sorting
5/20
| ![image](https://github.com/user-attachments/assets/2043c967-e751-4ccb-9c12-467e401136af) | ![image](https://github.com/user-attachments/assets/e4ba6436-815c-4617-af47-f88a4c259e1c) |
| ![image](https://github.com/user-attachments/assets/9784a8f8-4f54-4ba8-861c-87e3d2aaa15a) | …
> feat: [UIE-8762, UIE-8621] - IAM RBAC: update text, fix sorting

- packages/manager/cypress/support/util/regions.ts
Fix comments in https://github.com/linode/manager/pull/12127#pullrequestreview-2819677984
> test: [M3-9479] - Remove mock regions for Database Cluster

- packages/manager/.changeset/pr-12177-upcoming-features-1746722622457.md
- packages/queries/.changeset/pr-12177-upcoming-features-1746731515329.md
- packages/queries/src/vpcs/requests.ts
- packages/queries/src/vpcs/vpcs.ts
Add queries for the following endpoints:
`/v4/vpcs/ips`
`/v4/vpcs/{vpcId}/ips`
<details>
<br/>
</details>
> upcoming: [M3-9492] - Add queries for VPC IPs endpoints

- packages/manager/.changeset/pr-12184-fixed-1746801653201.md
- packages/manager/.changeset/pr-12184-upcoming-features-1747047890188.md
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.style.ts
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.tsx
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
- packages/manager/src/features/IAM/Users/UserRoles/AssignNewRoleDrawer.tsx
- packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
Fixes styling issues in the Assigned Permissions Panel and the Assigned Entities Table.
- fix 'Hide details' logic
- text update
- fix styles (font, spacing, etc.)
- refactoring
20 May 2025
| ![Screenshot 2025-05-09 at 4 27 52 PM](https://github.com/user-attachments/assets/adef3e68-0122-4b0d-bd1d-8e0964ad4264) | ![Screenshot 2025-05-09 at 4 28 00 PM](https://github.com/user-attachments/assets/26b50a0c-749b-4796-af91-6953066eb801) |
- Use devenv and login as vagrant user
- Click is to see a specific user
- Click on the Assigned Roles tab
(How to …
> fix: [UIE-8679, UIE-8532] - Assigned Permissions Panel, Entities Table: Styling Issues

- packages/shared/src/components/LinodeSelect/LinodeSelect.test.tsx
- packages/ui/src/components/TextField/TextField.stories.tsx
- packages/ui/src/components/TextField/TextField.tsx
- packages/ui/src/components/TooltipIcon/TooltipIcon.stories.tsx
- packages/ui/src/components/TooltipIcon/TooltipIcon.tsx
- packages/ui/src/foundations/themes/dark.ts
- packages/ui/src/foundations/themes/light.ts
Reverts linode/manager#12005 which is causing bad visual regressions with copy, radios and other UI items
> Revert "refactor: [M3-9656] - [Akamai Design System] Label Component"

- packages/manager/.changeset/pr-12295-fixed-1748524056623.md
- packages/manager/src/features/CloudPulse/Widget/CloudPulseWidget.tsx
- packages/manager/src/features/CloudPulse/Widget/CloudPulseWidgetRenderer.tsx
- packages/manager/src/mocks/serverHandlers.ts
Fixed 2 bugs, identified in the dashboard widget
1. Time granularity & aggregate function was not visible for linode dashboard
2. For half size widget, scroll bar was automatically introduced in widget filters for large widget labels.
1. Updated widget filter renderer to use metric as comparison parameter
2. Updated cloud pulse widget to fix the scroll bar issue
17th June
|![Screenshot 2025-05-28 at 1 46 11 PM](https://github.com/user-attachments/assets/402d2ed9-0cd1-4139-90 …
> fix: [DI-25399] - Fix widget filter issue in dashboard

- packages/manager/.changeset/pr-12317-upcoming-features-1748960578731.md
- packages/manager/src/features/IAM/Roles/RolesTable/AssignSelectedRolesDrawer.tsx
- packages/manager/src/features/IAM/Roles/RolesTable/AssignSingleSelectedRole.tsx
- packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
- packages/manager/src/features/IAM/Shared/AssignedPermissionsPanel/AssignedPermissionsPanel.style.ts
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.style.ts
IAM: Roles Table pagination fix, Assign Roles Drawer UI fix
- hide pagination when there are empty results in the table or there is just one page of items and their size is less than minimum pagination size
- Assign Roles Drawer - styling Issues
June 17th
| ![Screenshot 2025-06-03 at 4 07 24 PM](https://github.com/user-attachments/assets/41516a0a-14ab-41f3-9864-370581505a22) | ![Screenshot 2025-06-03 at 4 06 45 PM](https://github.com/user-attachments/assets/0fa7e9da-8864-464b-8e4f-982cb745d1b3) |
| ![Screenshot 2025-06-03 at 4 07 37 PM](https://github.com/user-attachments/assets/81143a8c-1d6b-482f-bb8d-f48b5225962c) | ![Screenshot 2025-06-03 at 4 06 …
> feat: [UIE-8792], [UIE-8794] - IAM: Roles Table pagination fix, Assign Roles Drawer UI fix

- packages/manager/.changeset/pr-12297-upcoming-features-1748525253975.md
- packages/manager/src/features/IAM/Roles/RolesTable/RolesTable.tsx
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.test.tsx
- packages/manager/src/features/IAM/Shared/Permissions/Permissions.tsx
- packages/manager/src/features/IAM/hooks/useCalculateHiddenItems.ts
IAM RBAC: useCalculateHiddenItems fix
- Fixed incorrect hidden count in “Expand (+N)” button
- Fixed “Expand” button disappearing after collapsing
- Hid expand button when all permissions are visible
- Added unit tests
June 17th
| <video src="https://github.com/user-attachments/assets/f15ba0ec-e8ba-4230-8670-3e3435e03415" /> | ![Screenshot 2025-05-29 at 3 03 15 PM](https://github.com/user-attachments/assets/b7d4c9bc-48cf-4828-97cc-3365581c6872) |
| ![Screenshot 2025-05-29 at 3 03 40 PM](https://github.com/user-attachments/assets/c420f331-954c-4a63-b6a3-e281bac33819) | ![Screenshot 2025-05-29 at 3 03 …
> feat: [UIE-8820] - IAM RBAC: useCalculateHiddenItems fix

- .github/workflows/README.md
- .github/workflows/ci.yml
- .github/workflows/coverage_badge.yml
- .github/workflows/e2e_schedule_and_push.yml
- .github/workflows/security_scan.yml
- .github/workflows/stale.yml
- packages/manager/.changeset/pr-12501-tech-stories-1752162803188.md
This PR aims to specify GitHub token permissions for each of our GitHub Actions workflows to resolve security scanning alerts. I gave each workflow the most limited permissions I could, and tested each workflow against my fork with the exception of `coverage_badge.yml` and `e2e_schedule_and_push.yml`.
- Assign `contents: read` permissions for `ci.yml` workflow
- Assign `contents: read` permissions for `coverage_badge.yml` workflow
- Assign `contents: read` permissions for `security_scan.yml` workflow
- Assign `pull-requests: write` permissions for `stale.yml` workflow
N/A. Let's aim to merge this **after** our upcoming 7/15 release just in case this introduces CI issues that could cause trouble for our release.
- I tested a number of the workflows using a test PR on my fork here (I had …
> change: [M3-9878] - Specify GitHub Actions workflow permissions

- packages/manager/.changeset/pr-12526-fixed-1752675535397.md
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceTable.tsx
The search feature in a Firewall's devices tabs are not working  
- Fixed the Firewall Device Search
N/A
| <video src="https://github.com/user-attachments/assets/e45d0234-ebf9-479e-baa1-62c839c34c52" /> | <video src="https://github.com/user-attachments/assets/4b138fef-2b00-436f-9c4c-fdfe2bb44f88"/> | 
<details>
🚩 Using a feature flag to …
> fix: [M3-10234] - Firewall Device Search

- packages/manager/.changeset/pr-12542-upcoming-features-1753085924888.md
- packages/manager/src/features/IAM/Shared/Entities/Entities.tsx
- packages/manager/src/features/IAM/Shared/RemoveAssignmentConfirmationDialog/RemoveAssignmentConfirmationDialog.tsx
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.test.tsx
- packages/manager/src/features/IAM/Users/UserEntities/AssignedEntitiesTable.tsx
- packages/manager/src/features/IAM/Users/UserEntities/UserEntities.test.tsx
- packages/manager/src/features/IAM/Users/UserRoles/AssignSingleRole.tsx
IAM RBAC: fix error message and styles issues
- Update the text from 'Remove' to 'Remove Assignment'
- Update the error message to match the logic of other drawers
- Fix styles issues
July 29th
| <img width="3456" height="2160" alt="image" src="https://github.com/user-attachments/assets/2b9cf974-fba3-4106-91e8-03bed00dbaaf" /> | <img width="1354" height="1078" alt="image" src="https://github.com/user-attachments/assets/e06959d3-b37a-44eb-ad27-65db9070be66" /> |
| <img width="986" height="1922" alt="image" src="https://github.com/user-attachments/assets/09e9a8ff-82ed-4c00-a548-4a2fee0387ce" /> | <img width="1078" height="1774" alt="image" src="https://github.com/user-attachments/assets/07f50920-f46c-4e3 …
> feat: [UIE-8931, UIE-8888] - IAM RBAC: fix error message and styles issues

- packages/manager/.changeset/pr-12531-added-1752851222394.md
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/OMC_CreateBucketDrawer.tsx
- packages/manager/src/features/ObjectStorage/QuotasInfoNotice.tsx
Quotas informational banner created and added to the "Objects" tab and "Create Bucket" drawer.
- Run Cloud Manager.
- Navigate to "/object-storage/buckets/create".
- Observe the notice.
- Navigate to "/object-storage/buckets/{region}/{bucket}"
- Observe the notice.
<details>
📑 Providing or …
> new: [STORIF-62] - Quotas informational banner created.

- docs/PULL_REQUEST_TEMPLATE.md
- packages/manager/.changeset/pr-12608-tech-stories-1753905809598.md
This PR updates the PR template to encourage video previews for multi-step changes for easier review.
> chore:[M3-10397] - Update PR Template to Encourage Video Previews

- docs/PULL_REQUEST_TEMPLATE.md
- packages/manager/.changeset/pr-12609-tech-stories-1753907236327.md
Makes small tweaks to our PR template based on team retro discussion on 7/30.
- Moves the bottom section of the PR to a HTML comment, hiding it from view but preserving the content
- This means we don't have to manually delete it from all our PRs
- Adds a checkbox underneath the Changes section as an attempt at quick visual confirmation whether changes are customer-facing
- Adding this because we have so many projects with feature flags in various states; I'm open to feedback on it!
N/A
<details>
➕ Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CO …
> change: Improve PR template based on team feedback

- packages/manager/.changeset/pr-12683-tests-1755010896822.md
- packages/manager/cypress/e2e/core/linodes/alerts-edit.spec.ts
- packages/manager/src/features/Linodes/constants.ts
Show legacy 'Save Alerts' confirmation modal only if user has already opted/subscribed into Beta Alerts mode in Linode Details page
On a linode details alerts tab that displays the beta alerts, if the user switches back to legacy alerts mode, and then edits a legacy alert, the user should be receive a prompt, 'Are you sure you want to save legacy Alerts?' with confirm/cancel options. 
pnpm run cy:run -s cypress/e2e/core/linodes/alerts-edit.spec.ts
To test manually in local dev environment, in launchdarkly devtool 1) Enable MSW 2) Set preset to "Legacy MSW handler" & 3) Apply. Then in the list of linodes, select "aclp-supported-region-linode-1". 
<details> …
> test: [M3-10325] - Show legacy 'Save Alerts' confirmation modal only if user has already opted into Beta Alerts mode

- packages/manager/.changeset/pr-12681-fixed-1755003617659.md
- packages/manager/src/features/Account/AccountLogins.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
Disable Firewall label editing for users without the ``update_firewall`` permission.
Show login-history if user has ``list_account_logins`` permission.
- Disable Firewall label editing for users without the ``update_firewall`` permission.
- Show login-history if user has ``list_account_logins`` permission.
August 26th
- devcloud IAM account or local devenv setup or mock data (use the User Permissions presets)
- _Note: The unrestricted account has full access — permission checks are skipped._
To test permissions using presets:
Enable MSW and use Legacy MSW Handlers.
- Use the Custom Profile preset with the restricted option selected.
- For …
> fix: [UIE-8838, UIE-9087] - IAM RBAC: login-history permission fix, firewall edit label permission fix

- packages/manager/.changeset/pr-12746-upcoming-features-1755808123912.md
- packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.test.tsx
- packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx
Copy adjustments to the VPC Create flow as requested by Daniel
| <img width="1774" height="1218" alt="image" src="https://github.com/user-attachments/assets/afffaa14-2f11-41bd-9425-547a4dfa6673" /> | <img width="1796" height="1214" alt="image" src="https://github.com/user-attachments/assets/ad6c0873-5be8-4882-a88e-879c57a8596b" /> |
- Pull this PR and point to devcloud (ensure your account has vpc ipv6 customer tag)
<details>
➕ Adding …
> upcoming: [M3-10486] - Update dual-stack labeling in VPC Create

- packages/manager/.changeset/pr-12768-fixed-1756151182727.md
- packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx
Fixes LKE jumping UI on the control plane
Vertical (and horizontal) padding on the tooltip was 12px, which led to the jumping. Reduced vertical padding a bit
n/a
| <video src="https://github.com/user-attachments/assets/a8004781-52b8-4a6a-9b3a-59d05f171a48" /> | <video src="https://github.com/user-attachments/assets/ffde9467-0097-4034-8cd5-b7eb42dba025" /> |
Navigate to LKE create
Select 'Yes, enable Akamai App Platform'
- notice UI jump
- confirm ui jump doesn't exist anymore
<details>
➕ …
> fix: [M3-10496] - Fix LKE jumping UI on HA Control Plane

- packages/manager/.changeset/pr-12743-changed-1755774240085.md
- packages/manager/src/features/IAM/IAMLanding.tsx
- packages/manager/src/features/IAM/Shared/constants.ts
- packages/manager/src/features/IAM/Users/UserDetailsLanding.tsx
This PR changes the docs links for iam to be relevant to content on page
- Change docs links
September 9th
- devcloud IAM account or local devenv setup or mock data (use the User Permissions presets)
<details>
🚩 Using a …
> feat: [UIE-9055] - IAM RBAC: change docs links

- packages/manager/.changeset/pr-12738-tests-1755723265426.md
- packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts
Fix LKE create smake flaky test
- Change the way to select region
```
pnpm cy:run -s "cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts"
```
> test: [M3-9717] - Fix LKE Create Smoke Test Flake

- packages/api-v4/.changeset/pr-12780-added-1756715574168.md
- packages/api-v4/src/iam/types.ts
- packages/manager/.changeset/pr-12780-added-1756375762995.md
- packages/manager/src/features/IAM/hooks/adapters/accountGrantsToPermissions.ts
- packages/manager/src/features/IAM/hooks/adapters/nodeBalancerGrantsToPermissions.ts
- packages/manager/src/features/IAM/hooks/adapters/permissionAdapters.ts
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
This PR implements IAM RBAC permissions for NodeBalancer. It follows the mapping conventions to safely provide backwards compatibility with legacy grants. It covers NodeBalancer landing page.
- Implement new nodebalancer access type
- Implement permissions in the /nodebalancers flow (Create Nodebalancer btn + Action Menu)
- update unit tests
9/9
- MSW or iam (restricted) + regular account to compare
Permissions to check:
`Custom User Entity Permissions` preset:
```
[
"delete_nodebalancer"
]
```
`Custom User Account Permissions` preset:
```
[
"create_nodebalancer"
]
```
<details>
👀 Doing a …
> feat: [UIE-9141] - IAM RBAC: add perm check for nodebalancer landing

- packages/manager/CHANGELOG.md
- packages/manager/package.json
- packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
- packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx
- Broken entity link on Linodes list card view
> Release v1.149.1 - staging → master

- packages/manager/.changeset/pr-12787-changed-1756744243536.md
- packages/manager/cypress/e2e/core/cloudpulse/create-user-alert.spec.ts
- packages/manager/cypress/e2e/core/cloudpulse/edit-user-alert.spec.ts
- packages/manager/cypress/support/constants/alert.ts
- packages/manager/src/features/CloudPulse/Alerts/AlertsDetail/AlertDetailCriteria.test.tsx
- packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.test.tsx
- packages/manager/src/features/CloudPulse/Alerts/constants.ts
Change aggregation function label
- Changing the values from `Average`,`Minimum`,`Maximum` to `Avg`,`Min`,`Max` in Show-details and Create Alert page
| <img width="1110" height="166" alt="image" src="https://github.com/user-attachments/assets/b15ef4d6-ecb8-4cba-9476-f43b654117bf" /> | <img width="1126" height="174" alt="image" src="https://github.com/user-attachments/assets/29a82f84-884f-4bf6-88aa-dd4b8d7a82b6" /> |
| <img width="556" height="428" alt="image" …
> upcoming: [DI-26718] - change aggregation function label

- packages/manager/.changeset/pr-12874-changed-1757696731696.md
- packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx
Update copy in the "Manage Image Regions Drawer" to account for billing being postponed 💵📆  
| ![Screenshot 2025-09-12 at 12 56 59 PM](https://github.com/user-attachments/assets/0a8c0910-26fa-48bd-8e4a-c610fac04955) | ![Screenshot 2025-09-12 at 12 57 06 PM](https://github.com/user-attachments/assets/93bab4ae-ecc6-4765-ae36-bd8b463b86dd) |
- Have a custom Image on your account (Create one or upload one)
- Go to the "Manage Replicas" / "Manage Regions" drawer for your image
- Verify you see updated copy that mentions billing starting in 2026
<details> …
> change: [M3-10615] - Update pricing copy in the Image Replicas Drawer because billing is postponed

- packages/manager/.changeset/pr-12882-changed-1758028381746.md
- packages/manager/src/GoTo.tsx
Tiny PR to implement the new permission model to the GoTo menu.
- Implement `is_account_admin` permission check for 
10/07/2025
- Have an admin IAM account 
- Have a restricted IAM account
- Have a non-IAM account (regular linode account)
- Have a restricted non-IAM account (regular linode account)
- Turn off the `IAM Primary Nav Changes` feature flag
For each of the accounts below, navigate to any page and use the [CTRL-SHIFT-K] shortcut to trigger the GoTo menu.
- Admin IAM account
- ✅ Account menu item is present in the menu
- Restricted IAM account
- ✅ Account menu item is **not** present in the menu
- Non-IAM admin account
- ✅ Account menu item is present in the menu
- Non-IAM Restricted account
- ✅ Account menu item is …
> feat: [UIE-8875] - IAM RBAC permissions for GoTo menu

- packages/manager/CHANGELOG.md
- packages/manager/src/features/TopMenu/UserMenu/UserMenuPopover.tsx
User Menu fix: IAM Beta badge is visible for non-Beta users.
- hide IAM Beta badge for non-Beta users
October 7th
| ![Screenshot 2025-10-07 at 9 36 43 AM](https://github.com/user-attachments/assets/d19dd5f2-3aa6-421e-8ea8-bd5f22fc24d3) | ![Screenshot 2025-10-07 at 9 36 25 AM](https://github.com/user-attachments/assets/cdc66ac2-75af-4381-9307-08ca87f350be) |
- Login to CM as non-Beta user.
- Click User Menu.
- Verify that Beta badge is not visible in User Menu
<details> …
> fix: [UIE-9340] - IAM: User Menu Beta badge fix
