- .dockerignore
- Dockerfile
- package.json
* The two biggest changes to reduce the size and time right now:
1. witched from node:10 to node:10-alpine. This reduced the image size down to 1.9 gigs
2. add 'packages/**/node_modules' instead node_modules to the .dockerignore file. This reduced
image size down to 1.35 gigs.
* merged 2 sets of 3 COPY lines down to 2 COPY lines reducing layers needed
* tested that changes to code will be automatically updated/rebuilt as with running locally
* next goal is to see if using multi-staged builds will reduce size further and improve speed
It would be a good idea to remove any large images or unneeded images on your machine
1. `docker system df` will show you how much space you can reclaim
2. `docker system prune -a` will remove all unused containers …
> Making Changes to the cloud dockerfile

- packages/manager/src/utilities/getAPIErrorFor.ts
Add type checking to this oldish utility function in case it gets something we're not expecting.
This is an attempt to fix a crashing bug noticed during review. I wasn't able to reproduce the bug, so this was my best shot. There may still be a bug in this PR: https://github.com/linode/manager/pull/5773 but if there is, I haven't been able to find it.
Please test places around the app that use this utility function.
> Add type checking in getAPIErrorFor 

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.test.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
The previous logic in the `listIPv6InRange` utility function didn't account for /116 pools, which have a type of `ipv6/pool`. The logic has been adjusted so that RDNS entries for /116 pools will be displayed as well.
**To test,** have an assigned /116 pool and set RDNS on matching entries.
> [for release] Allow RDNS for IPv6 pools

- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
When testing https://github.com/linode/manager/pull/5776 I noticed that the Backup Settings form was using old patterns. Specifically, there was no loading state and the error states were not being cleared upon new submission. This PR addresses both of these items.
**To Test**, navigate to Linode Detail > Backups. Scroll down to Settings and submit the form. Request block to simulate error states, and/or select “Choose a time” or “Choose a day”.
> Add loading state and clear errors on form submission [Linode Backups]

- packages/manager/src/factories/longviewService.ts
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ConnectionRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/index.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/LongviewServiceRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/index.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/request.types.ts
Adds tables for services and connections. Static data only in this PR.
These two responses are very similar, and it might be possible to do some conditional stuff and use a single table for both of them. I tried a few ways but there are small differences between them; this is mostly boilerplate so I'm ok with this approach.
> M3-3604 Add static tables for listening services/active connections

- packages/linode-js-sdk/src/networking/types.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
IPv6 range route targets are now exposed by the API. This PR update our types in the SDK and adds them to the IPv6 table in Linode > Networking.
I didn't see any other place where ranges are used in the app (neither did VSCode), but please double check. 
You should see route targets for /64 and /56 ranges, but not for /116 pools.
> Add route target to IPv6 ranges

- packages/manager/src/store/linodes/linode.requests.ts
- packages/manager/src/store/linodes/linodes.events.ts
- packages/manager/src/store/types.ts
Linodes that are created outside of the UI were not being appended to the Linode list when `linode_create` and `linode_boot` events came in.
Think Kubernetes - try creating a Cluster and wait a couple minutes - you'll see events coming in but the list remains the same.
Adding an optional argument to `requestLinodeForStore` called `isUpdatingOrCreating`. This will just override whatever internal logic this function does and always make a GET request for the Linode in question.
The reason we had to implement this is because no GET request was being made if the Linode didn't exist in the list (which was solving for `linode_delete` events)
[Take a look at the comments here.](https://github.com/linode/manager/blob/develop/packages/manager/src/store/middleware/combineEventsMiddleware.ts#L78) …
> Fix: Linode Create Events Updating Redux State

- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
Search box now filters by hostname
- Added a 3rd argument to pass lvClientData to the filtering function
- Adjusted types/typings so we can .filter rather than .reduce (since
in this case we need an array ultimately anyway)
- Fixed tests to adjust to new pattern
- Refactored a few things
> Enable searching LV clients by hostname

- packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsButton.tsx
This bug is only true if you set your operating system to always show scrollbars.
> M3-3596 fix: Events Badge Hides behind scrollbar

- packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
- packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
This fixes an issue with alignment shown in the screenshot and a responsive typography issue needed for a caker item.
> M3-3620 Update breadcrumb typography and alignment

- packages/manager/src/constants.ts
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
- packages/manager/src/utilities/formatRegion.ts
Add mapping for display name of test cluster. This will only ever be visible in dev.
- I cheated the typing a bit here, since I didn't want the `ObjectStorageClusterID` type to be polluted. 
- I changed instances of `formatRegion` in OBJ to the unused `formatObjectStorageCluster` because I didn't want to pollute the rest of the region types.
Please check that both prod and dev look OK.
> [OBJ] add display name for Philadelphia

- packages/manager/src/store/linodes/linodes.events.ts
After a Linode resize is completed, if the Linode was previously running, the API will attempt to boot it. There's no linode_boot event, though, so we show the Linode as offline forever until the user reloads the page. After talking with the API, the only way around this is to wait for 20 seconds after the resize finishes then request the Linode again.
Has to be ~20 seconds or the Linode is still offline when we request. This may not work for every size/shape of Linode, but 20 seconds is already a long time without any progress bar. We could do an interval that polls until it's online, but we don't really know if there is even a boot in progress, and "poll forever after a resize just in case" seems like overkill.
> M3-3290 Wait 20 seconds after a resize then request the Linode again

- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
Initial work on the layout for the Processes tab. 
My thought is that if we merge this, @WilkinsKa1  can work on styles in a separate PR while I work on the data fetching and munging.
New `selected` prop on `<TableRow />`. Styling isn't complete here, and there are rough edges around hover/focus/click states. 
- Data is static.
- The Graphs sidebar component is currently a stub.
- Loading/Error states aren’t really a thing yet.
- Ditto with Mobile styling.
Things to look for:
- Please check that the general shape of the layout and code makes sense. 
- Table sorting should work.
> M3-3523 Processes Tab (Layout & Table)

- packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewListRows.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
This PR ended up being a bit of a mix of visual adjustments mostly to landing but also to plan details (mobile). Of note:
• Removed entity icon from client rows
• Updated location and styling for last updated timestamp (now displays for each client row)
• Packages link styling
• Mobile Landing header
• Mobile Plan Details fix
> M3 Longview Landing Adjustments

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/request.types.ts
This fixes a bug in develop where the app crashes if DATA.Processes doesn't exist (which is likely to happen if the Linode in question is powered off).
This is indirectly fixed in this PR: https://github.com/linode/manager/pull/5799, but I wanted to go ahead and address this to get develop working again. I wanted to make the typing change anyway, so it'll still be useful once 5799 is merged.
> [LV] Safely access Processes

- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Domains/domainUtils.test.ts
- packages/manager/src/features/Domains/domainUtils.ts
Removes validation we had in place for making sure that a Domain's SOA address was outside of the domain.
Try creating a domain such as mydomain.com and set the SOA address to you@mydomain.com. In production this will trigger a client-side error, on this branch you should proceed successfully.
All additional client-side validation we do (making sure CNAME records are unique, mostly) should be unchanged.
> M3-3962 Remove same-domain SOA email restriction (client-side validation)

- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
Several tabs for Longview will not be included in the MVP release,
so this PR hids them under a separate LD flag (so that we can activate
longview without showing these tabs). Using a flag allows us to continue
to access the tabs in development without showing them to the user.
- Added a `<Redirect />` to LongviewDetail to match behavior elsewhere.
> Hide Longview tabs

- packages/manager/package.json
- packages/manager/src/components/PasswordInput/PasswordInput.spec.js
- packages/manager/src/components/PasswordInput/PasswordInput.tsx
- packages/manager/yarn.lock
- by removing ZXCVBN we are cutting 900k dependency in prod
- The regex serves the same purpose as before, to inform the user of the (relative) strength of their password. We update two states similarly to errors returned from the API (length and character reqs)
- Not a new problem, but seems like we get an error with a 6 chars password
> M3-3597 POC to remove ZXCVBN from Cloud and use Regex

- packages/manager/src/utilities/unitConversions.test.ts
- packages/manager/src/utilities/unitConversions.ts
Two changes made to readableBytes in this PR:
1. Added a `unitLabels` option, which allows you to substitute labels for units. Now we can do `readableBytes(1, { unitLabels: { bytes: 'B' } })` to get `1 B` instead of `1 bytes`. This matches Classic and the LV designs, and is a handy option to have for this utility function beyond LV.
2. Handled cases where the input is greater than 0 but less than 1. I don't really like this, as ideally you wouldn't use this function for inputs that are less than 1 byte. However, on the LV Processes Tab (in Classic) we often see values like "0.5 B/s", for Average IO. Thus this addition was necessary to get to parity.
**The new unitLabels option isn't used anywhere in the app yet.** But you can try it out yourself!
Have a look at the new unit tests, and try …
> Additions to readableBytes (needed for LV Processes)

- packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
- packages/manager/src/features/Longview/shared/utilities.test.ts
- packages/manager/src/features/Longview/shared/utilities.ts
Enables the "Sort by" select on the landing page. Each metric has its own idiosyncratic calculations, so the sorting function is long af.
I was a little fast and loose with how I handled the logic. I added a few things to Kayla's new shared/utilities file, and left others in place. I don't think any of this will be reused anywhere else so it shouldn't be a problem, but if I have time I can take a pass at cleaning it up for consistency (probably everything should live in the utilities file and the gauges should import it).
Todo:
You'll have to either mock data or set up your clients to get different values to sort on. A fun one to try is `stress`:
```
apt install stress
stress -c 1 --timeout 500
```
> Longview: Enable sorting clients on LongviewLanding page

- packages/manager/src/containers/profile.container.ts
- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx
- packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
Disables "add a client" button for restricted users
View the landing page as a user who has the `longview_add` global grant turned off
> Change: Disable Add Client Button for Disabled Users

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.tsx
This PR hides the "View Details" link in the Top Processes table, since it leads to a tab that won't be included in the MVP.
There are a few new unit tests. Try running the app with and without the `longview-tabs` feature flag enabled.
> [LV] Hide "View Details" link behind feature flag

- packages/manager/src/events.ts
- packages/manager/src/eventsPolling.ts
- packages/manager/src/features/Images/ImagesDrawer.tsx
- packages/manager/src/features/Volumes/ListGroupedVolumes.tsx
- packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CloneVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/ResizeVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeTableRow.tsx
- packages/manager/src/features/Volumes/VolumesLanding.tsx
- packages/manager/src/features/Volumes/types.ts
- packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
- packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
- packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
- packages/manager/src/store/events/event.helpers.ts
- packages/manager/src/store/middleware/combineEventsMiddleware.ts
- I previously moved setRequestDeadline, setPollingInterval and related
logic out of events.ts, because this had resulted in a circular dependency
(events imports the store which imports some of the methods above). Unfortunately,
this resulted in a bug where anything that subscribed to the events state in Redux
would render constantly as the polling interval was updated.
To try to avoid both issues, I created a new file at src/eventsPolling
that includes getters and setters for the variables in question.
- Resolved a circular dependency where ExtendedVolume was being imported
from child components.
- Fixed a typo in GroupedVolumes
Uncomment the console stuff in `src/eventsPolling.ts` to verify that the updating is happening as planned.
> M3-3624 Move events polling interval out of Redux

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/shared/formatters.test.ts
- packages/manager/src/features/Longview/shared/formatters.ts
Adds general-purpose function for adding placeholder datetime to a Longview Dataset.
Code comes mostly from https://github.com/linode/manager/pull/5844
See comments for explanation. Basically, the Longivew API will only return data for the time the Longview server has been alive. So if it's only been running since yesterday, requesting the last 30 days of data will only give you the last day of data in practice.
So this function will take a dataset, an array of paths to look for, and the selected start time and only add a dummy datetime under specific conditions.
> Change: Longview Placeholder Datetime

- packages/manager/src/features/Search/refinedSearch.test.ts
- packages/manager/src/features/Search/refinedSearch.ts
Taken from user feedback. It probably makes more sense for queries to be case-insensitive.
- Added two new unit tests.
> Make search bar case-insensitive

- packages/manager/src/App.css
- packages/manager/src/components/Breadcrumb/Crumbs.tsx
- packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
- packages/manager/src/components/EditableText/EditableText.tsx
- packages/manager/src/components/H1Header/H1Header.tsx
- packages/manager/src/components/H1Header/index.tsx
- packages/manager/src/components/Placeholder/Placeholder.tsx
- packages/manager/src/components/StackScript/StackScript.tsx
- packages/manager/src/features/CancelLanding/CancelLanding.tsx
- packages/manager/src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.tsx
- packages/manager/src/features/Dashboard/Dashboard.test.tsx
- packages/manager/src/features/Dashboard/Dashboard.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/Help/Panels/SearchPanel.tsx
- packages/manager/src/features/Help/SupportSearchLanding/DocumentationResults.tsx
- packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx
- packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx
- packages/manager/src/features/Profile/Profile.tsx
- packages/manager/src/features/Search/SearchLanding.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
- packages/manager/src/index.css
This PR improves accessibility by adding focus on the H1 when navigating to a new page. Since this is a one page app, our router does not do that automatically, so I implemented the focus() function in the breadcrumb (and editable text component since it also contains the H1) and replaced the breadcrumb wherever an isolated `<Typography variant="h1" />` was found. This should be the pattern to follow for ALL page titles from now on to preserve this enhancement.
1. Please review EditableText component as i refactored it as a functional component with hooks
2. You'll notice the css for focus is a red outline. This is intentional for everyone to test, and will be removed once PR is approved
> M3-3640 Accessibility: Focus on content when navigating

- packages/manager/src/features/Longview/request.types.ts
With the addition of adding placeholder data points to the Longview data for the purposes of getting the graphs to show past times correctly, this PR introduces a way to override the `Stat` interface by making the `y` possible to be `null`.
The goal here is to not have to muddy up the existing `Stat` interface for components that don't use Line Graphs.
```js
const thing: LongviewDisk<'yAsNull'> = {};
/** _y_ is number | null */
console.log(thing.Disk!.something.fs.free[0].y)
```
> Change: Allow For Override of Stat Type

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
You could already open the drawer from /longview/clients, now you can open it from the overview section too
> [LV] Open packages drawer from LV overview tab

- packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx
- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
- packages/manager/src/themeFactory.ts
There were a couple visual items in safari and firefox that weren't consistent with chrome- this PR updates the following items:
• Safari entity label wrap issue on LV landing
• Safari Installation instructions text wrap issue
• Firefox and Safari inconsistencies with selected table row + caret on Processes table
Please test in multiple browsers, breakpoints, etc. and take a look around to make sure there aren't any other visual discrepancies or regressions.
> M3-3637: LV Styling adjustments for Firefox and Safari

- packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
- packages/manager/src/features/linodes/LinodesLanding/IPAddress.tsx
I introduced a regression, this fixes it 😅 CopyTooltip now takes an optional prop for aria label, otherwise it'll default to `text` like before. In particular this aids the IP Address copy icon implementation and gives more context to screen reader users.
> A11y: Adding new prop for aria label

- packages/manager/src/components/CircleProgress/CircleProgress.tsx
- packages/manager/src/components/DrawerContent/DrawerContent.test.tsx
- packages/manager/src/components/Skeleton/Skeleton.tsx
- packages/manager/src/components/SplashScreen/SplashScreen.tsx
- packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx
- packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
- packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
- packages/manager/src/utilities/accessibility.ts
We should let visually impaired people know when content has loaded in case it takes a long time. My first initial effort was to make the user know both when content is loading and when content has loaded, but it ends up being too much verbiage, and sometimes the events trigger so fast that we only get the first one ('content is loading) and never that content has loaded, which is misleading. Instead, we just let the user know that content has loaded as needed, and if it takes a long time to do so, user will navigate to the row and find the loading container with aria-label showing loading state. Pattern was added to both circle progress and table row loading. Added also one for splash screen.
You can test with VoiceOver (which is less accurate …
> M3-3656 Aria Polite loading pattern

- packages/manager/src/components/EditableText/EditableText.tsx
Error text was not resetting properly after switching to a functional component (try cancelling after getting an error). Added a `useEffect` to fix that
> M3-3667 Fix regression with editable text

- packages/manager/src/components/Notice/Notice.tsx
- packages/manager/src/components/TextField.tsx
Super simple PR to add accessible alerts to inline errors and notices. Toast notifications have the pattern already.
> M3-3662 Add accessibility support for textfield errors and notices

- packages/manager/src/components/Paginate.ts
- packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/utilities/storage.ts
This PR introduces a "Show All" option so it is possible to view more than 100 Linodes.
I'm marking this as a POC because there are severe performance penalties for trying to render too many Linode Rows to the screen. It's not a matter of handling re-renders... it's the initial render that takes longer than is acceptable.
We could explore using a virtualized window to solve this, but in my estimation that would be a huge effort, especially since there are several ways we display Linodes (Grouped, List, Grid). Similarly, we could explore an infinite scrolling mechanism so that not all Linodes are rendered to the DOM at once.
I'm open to thoughts from the gallery here. The original intent is to better enable CTRL-F searching, but maybe our search bar is enough and we should promote it more. …
> M3-3245 "Show All" on Linodes Landing

- packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx
- packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
This more explicitly lets the user know that in order to cancel Object Storage billing, they'll need to do so in Account Settings.
- I also added a few unit tests for EnableObjectStorageModal.
> [OBJ] Add cancellation info to Enable Object Storage Modal

- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/RevokeAccessKeyDialog.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/CancelNotice.tsx
If a user is attempting to delete their last Bucket or last Access Key, display a warning that they will still be billed unless they cancel Object Storage in Account Settings.
> [OBJ] Display billing notice when deleting last Bucket or Access Key

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/__data__/events.ts
- packages/manager/src/factories/events.ts
- packages/manager/src/features/Events/Event.helpers.test.ts
- packages/manager/src/features/Events/Event.helpers.ts
- packages/manager/src/features/Events/EventRow.test.tsx
- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/Events/EventsLanding.test.ts
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
- packages/manager/src/features/linodes/transitions.test.ts
- packages/manager/src/store/events/event.helpers.test.ts
- packages/manager/src/store/events/event.reducer.test.ts
- packages/manager/src/utilities/minute-conversion/minute-conversion.test.ts
- packages/manager/src/utilities/minute-conversion/minute-conversion.ts
Adds duration column to activity feed and events landing.
`duration` can be `0`, `null`, or `number` (in seconds)
https://regex101.com/r/mPDfuk/1/
There's no design for this - I was really just winging it.
> Add: Duration Time to Events Landing and Activity Feed

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
Removing className from the component level to allow features to dictate styling needs instead.
Please view the places `TimeRangeSelect` are in use to ensure there has not been a regression in their styling (mostly affecting placement + width)
> Fix: Styling regression on LV Disks tab

- packages/manager/src/components/Tag/Tag.tsx
- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx
- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/NodeBalancerSummary.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- packages/manager/src/index.css
The way the sidebars (containing tags etc) are being ordered is wrong from a tabular POV. The come first in the markup order and we change the order with flex-box.
I also fixed a couple related sidebar content issues (cancel account button, tags buttons)
> M3-3671 Accessibility: Summary Sidebars

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/themeFactory.ts
This changes the color to gold, as in the designs:
> [LV] Update Load graph color

- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
This was previously a placeholder. The documentation hasn't been updated to reflect LV in Cloud Manager, but this is the best we can do right now. The new link takes you to https://www.linode.com/docs/platform/longview/longview/.
> [LV] Update documentation link

- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
Previously the LV client title was capitalized in the title: 
This PR adds the `noCap` option as we have with other entity detail pages.
> [LV] Use noCap option for Longview Detail breadcrumb

- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/types.ts
- POC for an error state. Right now it's only used in DiskGraph; if the idea is approved I can add it to the rest. One potential problem: a red error state for a user who has a openvz Linode might be distracting, and it isn't really an error. We could possibly use the `message` prop I'm hoping to add later (see below!) for that case as well.
- All graph components now listen to lastUpdatedError and re-request data when it changes. This solves for when an initial error causes the graphs not to load, then subsequent requests should fill in the data (they don't, currently).
- Extracted GraphProps interface to overview/types.ts. It was the same set of props used in all of the overview graphs, so it made sense.
Holding off on loading and empty states for now, until after Alban's finished his …
> [LV] Graphs error state

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
Uses the pattern from #5880 to provide error states to the remaining overview graphs.
> [LV] Add errors to remaining graphs

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/FeatureComingSoon.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
This is an alternate approach to https://github.com/linode/manager/pull/5881.
Instead of hiding the tabs for features that haven't been released, we show an empty state with a link to Classic.
**To test:** change line 90 of LongviewDetail.tsx to:
```typescript
const showAllTabs = false;
```
> [LV] Placeholder component for soon-to-be-released features

- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
> M3-3697 fix tag dropdown in domains

- packages/manager/src/containers/longview.stats.container.ts
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
- packages/manager/src/store/longviewStats/longviewStats.actions.ts
- packages/manager/src/store/longviewStats/longviewStats.requests.ts
Separate PR since I'm not sure about this. The issue is that `getLatestValue` always returns a value, and we're using those values to populate the gauges. If a client returned data a month ago, our "live" gauges will show that data, whereas Cloud will (correctly) not display it.
> [For Release] LV Don't request/display stale data

- packages/manager/package.json
- yarn.lock
A dependency of react-dropzone called attr-accept had been bumped to the newest version in our yarn.lock. This version included breaking changes. As a result, in the Object Storage file uploader files were not correctly being accepted. Bumping the version of react-dropzone fixes this problem.
**To see the regression:** check out develop and attempt to upload a file. The file uploader area will be red. 
**To see the fix:** check out this branch and to the same thing. Please test with multiple browsers, filetypes, etc.
> [for release] Upgrade react-dropzone

- packages/manager/e2e/config/custom-commands.js
- packages/manager/e2e/config/wdio.conf.js
- packages/manager/e2e/constants.js
- packages/manager/e2e/pageobjects/longview/longview-landing.page.js
- packages/manager/e2e/pageobjects/longview/longview-plan-details.page.js
- packages/manager/e2e/pageobjects/page.js
- packages/manager/e2e/setup/setup.js
- packages/manager/e2e/specs/longview/longview-plan-details.spec.js
- packages/manager/e2e/specs/longview/longviewText.js
- packages/manager/e2e/utils/Logger.js
- packages/manager/e2e/utils/assertionLog.js
- packages/manager/e2e/utils/common.js
- packages/manager/e2e/utils/cred-store.js
- packages/manager/src/components/Breadcrumb/FinalCrumb.tsx
- packages/manager/src/components/Button/Button.tsx
- packages/manager/src/components/H1Header/H1Header.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Installation.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewDeleteDialog.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.tsx
- packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
Longview UI tests
* Created test for the longview plan subscription and longview clients.
* All tests can be run individually or together. The beforeEach and API calls will set up the data for the tests to run and use the information
from the responses for verification.
**note** there is an ugly browser.pause(1500) in the changePlan function.
This is because once the button is selected it is set to a disabled mode
so the check for the button to not be enabled will not work. Need a better
way to wait for the loading state on the button.
When running tests remember to use a user that does NOT have longview
clients installed. The tests will clear out all longview clients to make
sure the tests run reliably.
Added in some needed selectors to allow for UI automation to work easier. We are now …
> M3-3599 Longview e2e tests

- packages/manager/src/components/ImageSelect/ImageSelect.tsx
> M3-3714 Show deprecated label for distros in images drop down

- packages/manager/src/components/SelectionCard/CardBase.tsx
- packages/manager/src/components/SelectionCard/SelectionCard.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
> M3-3715 Reduce OCA tile spacing between Icon and Label

- packages/manager/src/features/Billing/PdfGenerator/utils.ts
Show "$0.80" instead of "$0.8" to match Classic when printing a PDF invoice.
> M3-3433 use toFixed(2) on invoice PDF

- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.test.tsx
- packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/useGraphs.ts
- packages/manager/src/features/Longview/shared/formatters.ts
Overlays some text on empty/loading graphs. Currently loading logic is only implemented in the MemoryGraph, as a demo.
Also did a thing to fix for when graph data was empty, 
the X axis ticks would use default values,
which didn't generally match the selected time scales. It should
be possible to add custom formatting through charts.js, but since
we're already using null padding in our data processing, I just
added some more logic to that.
If a data series is empty, we'll use `[[start, null], [end, null]]`
instead of an empty array. This sets the X axis ticks to the expected
values without populating any graph data.
This allows us to do things like clear the data when making a new request,
so that the loading state doesn't overlay on stale data.
> M3-3699 [LV] Empty/Loading states for LV overview graphs

- packages/manager/src/exceptionReporting.ts
- packages/manager/src/initSentry.ts
To test: block all requests to LaunchDarkly and check your console. No output from the `reportException` logic should be present.
All of these errors are network errors, so it might be better to just not report any of those. This was more precise so I thought it was the safest choice.
> Don't report LaunchDarkly errors to Sentry

- packages/manager/public/index.html
Without a leading slash, this script was being loaded relative to whatever path it was loaded from. Thus, if a user navigated directly to linodes/create, the script would fail to load.
**To test:**
To verify the bug (from **testing** branch):
1) Open dev tools (network tab)
2) Go to localhost:3000/linodes/create
3) Observe: newrelic.js has been loaded from localhost:3000/linodes/newrelic.js
To verify the fix (from **this branch**):
1) Open dev tools (network tab)
2) Go to localhost:3000/linodes/create
3) Observe: newrelic.js has been loaded from localhost:3000/newrelic.js
> Fix: Use relative path for NewRelic script

- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
This PR addresses two issues:
1) “Most Recent Backup” values were not appearing in the CSV file downloadable from Linodes Landing.
2) The “Last Backup” column was not being sorted properly on Linodes Landing.
To fix:
1) Use nested key for the CSV header (`backups.last_successful`)
2) Use nested key for sortable table head label (`backups:last_succesful`)
I also removed a prop called `mostRecentBackup` from LinodeCard that was confusing and wasn’t being used anyway.
Please check Linodes Landing. Last backups should appear in the downloadable CSV file and the "Last Backup" column should be sortable. Check group by tag, multiple browsers, etc.
> [for release] Most Recent Backup fixes

- packages/manager/src/components/PrimaryNav/AdditionalMenuItems.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/PrimaryNav/utils.ts
- packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
Sub tabs will break the active caret on primary nav. These PR allows to have multiple ones. I also did some cleanup on the function and files.
> M3-3700 Allow primary nav to set multiple active links

- packages/manager/src/components/Skeleton/Skeleton.stories.tsx
- packages/manager/src/components/Skeleton/Skeleton.tsx
- packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallTable.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallTableRows.tsx
- packages/manager/src/features/Managed/Contacts/ContactsTableContent.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList.tsx
- packages/manager/src/features/Managed/Credentials/CredentialRow.tsx
- packages/manager/src/features/Managed/Credentials/CredentialTableContent.tsx
- packages/manager/src/features/Managed/Monitors/MonitorTableContent.tsx
- packages/manager/src/features/Managed/SSHAccess/SSHAccessTableContent.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
- packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
- packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
- packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
- packages/manager/src/features/Users/UsersLanding.tsx
- packages/manager/src/themeFactory.ts
In order to make the pattern matching various table rows layout I added some props and styles in various tables. (`oneLine`, `hasEntityIcon`).
StoryBook was updated to show the different states
> M3-3614 Improve TableRow Loading skeleton

- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
In https://github.com/linode/manager/pull/5852#pullrequestreview-327561285 @Jskobos noticed there wasn't an error state for Access Keys.
This is an interesting bug. The form's global error is stored in Formik's `status`, which wasn't being de-structured out of `formikProps`. Our check for the error looks like this:
```tsx
{status && (
<Notice key={status} text={status} error data-qa-error />
)}
```
... but the TypeScript compiler was cool with this because [`window.status`](https://developer.mozilla.org/en-US/docs/Web/API/Window/status) is a thing!
**To reproduce bug:**
1) Go to /object-storage/access-keys.
2) Click "Create an Access Key".
3) Open Dev Tools and block all requests
4) Enter a label in the "Label" field and click "Submit".
5) Observe: …
> [OBJ] Fix: Error state in Access Key Drawer.

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
On Linode details under the Networking tab, the Networking Actions section had a couple form elements that had a visual relationship but were confusing for assistive technologies.
To test, have at least 2 linodes in the same region. Using a screenreader, navigate to Details > Networking > Networking Actions and tab through the IP input field and the 'Select action' select.
> M3-3752 Linode details networking actions A11y issues

- packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
Adding aria-label to checkbox on SSH Keys under Rebuild tab on Linode details so the checkbox is given context as to what it controls for assistive technologies.
> M3-3755 Linode details Rebuild SSH keys A11y issues

- packages/manager/src/initSentry.ts
We received reports of errors in newrelic.js. This PR adds the `blacklistURLs` option so we can avoid reporting these errors to Sentry. 
I also copied the Chrome extension snippet from the[ Sentry docs](https://docs.sentry.io/platforms/javascript/#decluttering-sentry) so we can avoid reporting browser extension errors as well. 
To test (lack of) newrelic.js error reporting:
1) Make sure `REACT_APP_SENTRY_URL` is defined.
2) Make a bogus change in `newrelic.js`.
3) Observe (in the Network tab and Sentry Dashboard): the error appears in the console but is not reported to Sentry.
> [Sentry] Ignore newrelic.js and Chrome extension errors 

- packages/manager/src/App.tsx
- packages/manager/src/exceptionReporting.ts
- packages/manager/src/initSentry.ts
This PR makes the following improvements to our Sentry integration:
1. Stop reporting JavaScript errors picked up by global `error` listener. The Sentry SDK already does this, so we were getting double-reporting.
2. Use `withScope()` instead of `configureScope()` for "extra" and "tag" data. This ensures the additional data is only sent on that specific Sentry event.
3. Configure scope for user data only once, in cDM of App.tsx. (Previously we were doing this in every `reportException()`  call.)
4. Ensure Sentry’s `captureException()` receives an Error object instead of a string. This should solve for the `"<unknown>: [object Object]"` errors we were getting.
**To test:**
Break the application in as many ways as you can. Call undefined functions, manually throw errors, use the …
> Sentry improvements

- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
- packages/manager/src/store/linodes/disk/disk.events.ts
- packages/manager/src/store/linodes/linodes.events.ts
The original plan here was to make use of the secondary_entity on these to make more targeted requests when CRUDding disks and configs. I actually left more intact than I planned: we're still optimistically adding/deleting disks and configs to the tables as soon as we get a 200.
Lots of changes, though:
- Update events messages for these events to include the disk/config name
- Request all disks or configs if we get a failed event for these
- Add loading state to submit button in config drawer
- Source config data from Redux in config drawer (we were requesting it separately)
- Add loading state to config deletion modal
- Move error message from toast to within the config deletion modal
- Change the name of the "Advanced" tab to "Disks/Configs" because we've been talking about it for ages …
> M3-3318 Support for Disks/Configs events (secondary entity!)

- packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/ResetPassword.tsx
API has now implemented the ability to use a URL parameter to pre-fill the username when trying to reset password from cloud. This PR adds this URL param.
> M3-2431 Add URL param to reset password button

- packages/manager/src/features/Lish/Weblish.tsx
We were getting error reports of `Cannot read property 'type' of null.` I was not able to reproduce this issue, but safe accessing the "type" (and "reason") attributes of `data` should at least stop the app from crashing if/when this happens.
To test, add `data = null;` to line 155 of Weblish.tsx.
> Fix Weblish error (safe access properties)

- packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
I was digging around in backups for an unrelated reason, and realized we weren't toasting when a snapshot failed (we just have error handling for when the initial request fails).
> Add toast for failed snapshot

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/App.tsx
- packages/manager/src/__data__/account.ts
- packages/manager/src/analytics.ts
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.test.tsx
Once we get `euuid` back from the API (on `/account`) add a `userInfo` event to the dataLayer. This takes place in cDM of `<App />`.
**To test,** make sure `REACT_APP_GTM_ID` is defined in your environment. Load the app. There are a few ways to verify the event is being added to the dataLayer:
1) Open up the console and type `dataLayer` (it's just an array on `window`).
2) Use an extension like [Dataslayer](https://chrome.google.com/webstore/detail/dataslayer/ikbablmmjldhamhcldjjigniffkkjgpo?hl=en-US)
3. Use Tag Manager preview mode
Also try logging out of Cloud and going through the whole flow with Login (the same `userInfo` event occurs there as well.)
> M3-3459 UserID for GTM

- .gitignore
- packages/manager/package.json
- yarn.lock
Changes:
- adds sonar to .gitignore
- adds 1 npm devDependency for coverage reporting
To use it, in CICD you can build and use this script to send an analysis to sonarcloud directly.
Replace `XXXXXXX` with proper info
```
docker run --rm -v $(pwd):/usr/src/ -w /usr/src/ node:10-alpine yarn install:all
docker run --rm -v $(pwd):/usr/src/ -w /usr/src/ node:10-alpine yarn workspace linode-js-sdk build
docker run --rm -v $(pwd):/usr/src/ -w /usr/src/ node:10-alpine yarn test --coverage --coverageDirectory=output/coverage/jest
echo sonar.projectKey=XXXXXXX > sonar-scanner.properties
echo sonar.organization=XXXXXXX >> sonar-scanner.properties
echo sonar.ws.timeout=120 >> sonar-scanner.properties
echo sonar.sources=packages/manager/src/,packages/manager/e2e/,packages/linode-js-sdk/src/ >> …
```
> add sonar reporter dep for sonar on jenkins

- packages/manager/src/features/Billing/PdfGenerator/utils.ts
invoiceItem.amount (and .tax and .total) are guaranteed by the API
to be numbers, but some special cases (Customer Packages) and older
records returned these values as strings, which causes toFixed()
to throw an error.
The API will fix this bug in ARB-1607, but for safety sake we
should continue to manually convert values.
If anything other than a number or a valid numeric string comes in,
we'll end up showing "$NaN" to the user. I don't think this is possible
so I didn't do any complex conditional logic to account for it, but
we should keep this in mind in case something like this happens again.
> M3-3770 Convert invoice fields to Number() before using toFixed()

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/useGraphs.ts
Add a Placeholder component with empty state messaging when a user
has no disks that are reporting to Longview. This is different from
most empty states in LV, since most other tabs will have empty tables
or graphs. Disks, however, is an object of `sda: {data}` objects,
which will be empty if no data is available for the specified time frame.
We had discussed hiding the time select component from view in this empty
state, but on further testing discovered that it's easy to end up in a situation
where the empty state will disappear if the user changes to a longer time
frame, one in which data is present.
This tab needs some follow-up work to match the behavior of other graphs (specifically, updating the X axis when the time box is changed), but that's turning out to be a big lift so I'm …
> Longview: Add empty state for Disks tab in LongviewDetail

- packages/manager/src/components/LineGraph/LineGraph.stories.tsx
- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
Chart.js has a built-in legend that Alban suggested we use for the LV graphs. This matches the designs, except for the positioning: it would actually be hugely difficult to move them outside of the graphs and into the header, so I'm going to hold off until we're sure that's something we really want to do.
I added the new prop to the Overview graphs (except Load, which has a single data series). Please click around.
> Chart native legend

- packages/manager/src/features/Dashboard/TransferDashboardCard/TransferDashboardCard.tsx
The total amount of transfer shown on the Dashboard is prorated for the month. For example, if you create a 1GB Linode halfway during the month, 500GB is added to your transfer instead of 1000GB.
https://www.linode.com/docs/platform/billing-and-support/network-transfer-quota/#why-is-my-linode-s-network-transfer-less-than-my-plan-s-transfer
This was causing some confusion, since the transfer on Linode Details in the total transfer that Linode type adds to your your pool.
To clarify, I included the note from Classic that explains that monthly transfer is prorated.
**Note:** There is currently an API bug where Object Storage is not included in your account transfer, so if you're comparing to Classic, there will be a 1000GB discrepancy.
> M3-3161 Change: Add copy clarifying prorated transfer

- packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
- packages/manager/src/components/PaginationFooter/index.ts
- packages/manager/src/factories/nodebalancer.ts
- packages/manager/src/features/Domains/ListDomains.tsx
- packages/manager/src/features/Domains/ListGroupedDomains.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/ListGroupedNodeBalancers.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/ListNodeBalancers.tsx
- packages/manager/src/features/Volumes/ListGroupedVolumes.tsx
- packages/manager/src/features/Volumes/ListVolumes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/hooks/useInfinitePageSize.ts
- packages/manager/src/utilities/storage.ts
Following the pattern done as a POC on LinodesLanding.
I added a NB factory to help test pagination here.
To test NB pagination, add this to line 236 of NodeBalancersLanding.tsx:
```typescript
const factoryData = nodeBalancerFactory
.buildList(150)
.map(nb => ({ ...nb, configs: [] }));
```
And this on line 299: 
```typescript
<OrderBy data={factoryData} order={'desc'} orderBy={`label`}>
```
> Include "Show All" on Volumes, Domains, NodeBalancers

- packages/manager/src/components/Skeleton/Skeleton.test.tsx
- packages/manager/src/components/Skeleton/Skeleton.tsx
- packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
Sonar reported a few functions inside `render()` methods that weren't returning anything. These weren't bugs, just some unorthodox array handling, but it's still worth fixing to make the code more readable and use more accepted React patterns. 
Functionality should be unchanged. Please check the Skeleton component in Storybook and in various tables throughout the app.
> M3 sonar fixes

- packages/manager/config/testSetup.js
- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/DiskPaper.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/useGraphs.ts
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/utilities/isToday.test.ts
- packages/manager/src/utilities/isToday.ts
Some tech debt stuff for Longview graphs:
- Refactor the Disks tab to use similar logic as the other graphs. This was partially done for consistency, and partially for recent updates such as updating the X axis and clearing data whenever a new time interval is selected.
- Added an interval to the useGraphs component, since if e.g. requests
were blocked/unblocked, it wouldn't register this. (most of the consumers
were running this in a useEffect that listened for start, end, lastUpdated,
error, etc, but that wasn't penetrating).
- Add mounted checking to useGraphs to match useClientLastUpdated
- Removed feature flag from Disks tab, since if this PR is merged
we're good to release that feature.
> M3 lv disks update logic

- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharingPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
The components in the "Restore to Linode" drawer (Linode Detail -> Backups) and the "Networking Actions" section (Linode Detail -> Networking) were making their own requests to `/linode/instances` in order to populate options in the Selects. 
They were only requesting the first page, which means that **if you had more than 25 Linodes in one region, you would not see all of them listed.**
In this PR, the data is sourced from Redux.
**Notes:**
- I thought about using the LinodeSelect component but wanted to keep the changes to an absolute minimum.
Use production test account 1
- Navigate to the Backups Tab for `pagination-test-source`.
- Click "Restore to Existing Linode" in the Action Menu of one of the backups.
- **Observe:** `pagination-test-target` …
> M3-3785 Source Linodes from Redux in Networking and Backups

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
Noticed a layout regression for LV overview graphs section, this fixes that issue (resource allocation header and the time range select were extending outside of the grid).
- Bug fix ('repair')
> Fixing layout issues with overview graph section

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXProcessGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/themeFactory.ts
Due to issues with opaque colors, we're re-introducing transparent colors for all longview graphs. Additionally, I removed the borders on the graphs to more closely align with the designs and removed 'deprecated' color values. 
Something to consider is the naming scheme for these colors- I used the graph values so I could better keep track of them all and keep Longview graphs consistent, but maybe they should be actual color names so they're more general. Let me know if there's a preference and if these are actually helpful or more confusing.
> Updating Longview graph colors

- packages/manager/src/features/Profile/APITokens/APITokens.tsx
I think this should have a space
> Add space to API Tokens html title

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/shared/formatters.ts
- packages/manager/src/utilities/unitConversions.test.ts
- packages/manager/src/utilities/unitConversions.ts
- Adds a maxUnit prop to our LineGraph component. If this component is provided, the graph will assume that the values provided are in bytes, and convert them to the specified unit.
- Except in the tooltip, which will do what Classic does and convert to an appropriate unit for each individual value.
- Also stacked all values into each tooltip so the user doesn't have to scroll over the value they want to see it.
- Tried to get the color to work, but I'm not sure that's possible in chartjs without using a manual (HTML) tooltip.
> M3-3784 POC for units in memory graph

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesLanding.tsx
- packages/manager/src/utilities/escapeRegExp.test.ts
- packages/manager/src/utilities/escapeRegExp.ts
A crash resulted when typing the forward-slash character in the Processes filter text input. The input string needed to be properly escaped before creating the regular expression. I added a utility function from the MDN documentation to do so.
**To verify bug:** 
Go to a LV Client’s “Processes” tab. Type `\` in the filter text input. The app crashes.
Feel free to play around with the new tests to further verify.
> [LV] Processes filter bug

- packages/linode-js-sdk/src/nodebalancers/nodebalancers.ts
- packages/manager/src/constants.ts
- packages/manager/src/store/image/image.requests.ts
- packages/manager/src/utilities/getAll.ts
API has increased the maximum page size to 200. This PR moves this value to a constant and uses it in the getAll helper function.
API is returning an error when requesting 200 Images, but since there is a limit of 3 Images per account, I made a change to `images.requests` so that we _don't_ use `getAll` for images.
> M3-3780 Request 200 entities at a time

- packages/linode-js-sdk/src/object-storage/account.ts
- packages/linode-js-sdk/src/object-storage/buckets.ts
- packages/linode-js-sdk/src/object-storage/clusters.ts
- packages/linode-js-sdk/src/object-storage/objectStorageKeys.ts
- packages/linode-js-sdk/src/object-storage/objects.ts
These endpoints can now be safely used with the v4 prefix.
Just make sure Object Storage still works.
> Use v4 instead of v4beta for OBJ

- packages/manager/src/features/Backups/BackupsCTA.tsx
- packages/manager/src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.tsx
- packages/manager/src/features/Profile/permissionsHelpers.ts
This issue from @nwisnewski is still unfixed, so here we go. any restricted user, regardless of permissions, will no longer see the backups CTA on either the dashboard or Linode view. It's possible for a user with sufficient permissions to toggle this setting, so it might be worth it to check the specific grants involved.
> M3 -1867 Fix: Hide Backups CTAs from restricted users

- packages/manager/src/factories/linodeConfigs.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx
- packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.test.tsx
- packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx
The API logic that determines which config to reboot with
when no config ID is provided seems to glitch out when
in Rescue mode. If a user has a single config, we just call
reboot(), which returns an API error "No bootable config found"
API is aware of this now, but since it's not going to get fixed
in time for EOL, the simplest thing for us to do is pass the configId
manually whenever only one config is present.
- This affects the "Power action dropdown" in detail view and the action menu from list view. I don't think there's anywhere else but please double check.
- I also renamed "Submit" to "Reboot into Rescue Mode" on the rescue button
to match Classic.
To test:
1. Have a Linode with only one config.
2. Boot into Rescue mode
3. Select "Reboot" from one of the above action menus.
4. …
> M3-3465 Allow rebooting from Rescue mode

- packages/linode-js-sdk/src/domains/domains.schema.ts
- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Domains/DomainTransferInput.tsx
We had a field to allow users to update axfr IPs (addresses allowed
to transfer for this Domain) when editing the SOA record for a master
Domain, but nothing was available for slave domains, since there's
only a single drawer for all slave-related editing actions.
Abstracted the axfr textfield so that it could be used in both places.
I kept this change simple to limit the scope, but that drawer is problematic. Really needs to be broken into separate drawers or components. There's some dubious cDU logic in there too, such that if you leave an editing drawer open and the app reloads you can end up in a weird limbo form. This likely only happens when hot-reloading in development, but it's icky and needs to be fixed on a tdt.
> M3-3779 ADD: Ability to edit axfr for slave Domains

- packages/manager/src/features/Domains/DomainRecords.tsx
This uses the same local storage key as Linodes, Domains, Volumes, and NodeBalancers, so if you select "Show All" on one of those pages, you'll see all of your Domain Records listed as well.
If we don't like this approach, we could make the Domain Records pagination independent or not saved in local storage at all. 
**Side note:** there are some serious performance problems when you have a ton of records on the page (at least running a dev server). E.g. try opening a drawer... all the record rows are re-rendered. Creating a ticket to address separately.
Use production test account #1, Domain "many-domain-records" for a Domain with 150 CNAME records.
> M3-3780 Add "Show All" option to Domain Records

- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
We had a faulty pathOr in useClientLastUpdated:
```typescript
pathOr(0, ['updated'], response)
```
It should have been: 
```typescript
pathOr(0, ['DATA', 'updated'], response)
```
But I used optional chaining and nullish coalescing instead.
To verify bug:
1. Open the Network tab.
2. Open Dev Tools, Network tab.
3. Filter on “fetch” to easily see requests.
4. Do something to generate traffic on your Linode.
5. Wait a while and check each polled `/fetch` request.
**6. Observe:** even though `lastUpdated` has changed, the graphs have not been updated.
To verify fix, follow steps 1-5, then:
**6. Observe:** graphs have been updated.
> [LV] Fix bug in useClientLastUpdated.

- packages/manager/src/constants.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
- packages/manager/src/store/bucket/bucket.requests.ts
- packages/manager/src/utilities/getAll.ts
In this PR we specify the API page size from an environment variable rather than a feature flag. The new variable is `REACT_APP_API_MAX_PAGE_SIZE`, so add that to your `.env`.
I also fixed two places where the API returns an error if requesting more than 100 items:
- /networking/ips
- /object-storage/buckets
> API page size from config variable

- packages/linode-js-sdk/src/regions/types.ts
- packages/manager/src/MainContent.tsx
- packages/manager/src/__data__/regionsData.ts
- packages/manager/src/components/RegionStatusBanner/RegionStatusBanner.test.tsx
- packages/manager/src/components/RegionStatusBanner/RegionStatusBanner.tsx
- packages/manager/src/components/RegionStatusBanner/index.tsx
- packages/manager/src/factories/regions.ts
- packages/manager/src/features/Dashboard/Dashboard.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
- packages/manager/src/features/Volumes/VolumesLanding.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/store/regions/regions.reducer.ts
Add a banner to the top of all relevant pages (and to the support
ticket drawer) if any region returns a status of "outage". If multiple
regions have outages, the notices will stack.
This was our first use of the region.status field, so we had to update
typings and test data to respect the new API response.
We could do this site-wide in App.tsx, but the AC made it clear that it should only be on relevant pages so I took my best guess at what counted (Domains don't, OBJ does). Feedback welcome.
To test, replace line 34 of `src/store/regions/regions.reducer.ts` with the following: 
```
draft.entities = [
...result,
{
id: 'us-east',
status: 'outage',
capabilities: [],
country: 'US'
}
];
```
To test multiple outages, use:
```
{
id: 'us-east',
status: 'outage',
capabilities: [],
country: 'US' …
```
> M3-2446 Region status message

- packages/manager/src/MainContent.tsx
- packages/manager/src/components/SuspenseLoader/SuspenseLoader.tsx
- packages/manager/src/components/SuspenseLoader/index.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/index.tsx
- packages/manager/src/features/Volumes/Volumes.tsx
Add React.lazy / React.suspense POC in the K8s and Volumes sections. The goal is to replace the react-loadable library (which we use in our DefaultLoader component), which is obsolete and hasn't been updated in more than a year.
If everything works out here, we can apply this pattern everywhere else we currently use DefaultLoader.
> React.lazy

- packages/manager/src/features/linodes/CloneLanding/Details.tsx
Previously these `<a />` elements were changed to `<button />`s to make them more accessible. This resulted in a visual regression. This fixes that regression by adding a few CSS properties.
**Before:**
**After:**
> M3-3812: Fix visual regression on Clone Configs/Disks

- packages/manager/src/features/Domains/DeleteDomain.test.tsx
- packages/manager/src/features/Domains/DeleteDomain.tsx
- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
This PR adds the ability to delete a domain from the Domain Details page.
Still to do:
> [M3-3689] Add: Ability to delete a Domain from Domain Detail

- packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx
- packages/manager/src/components/StackScript/StackScript.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.test.ts
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
This PR addresses the fact that StackScript author (in StackScript Details) links recently stopped working.
The original AC was to remove the link entirely, but I realized we could use our own StackScript search if we made a few changes to honor some query params.
Now, `/stackscripts?type=community?query=<query>` does what you'd expect it to. I changed the author links to use this new feature.
Test that the StackScript Landing and Detail pages work as expect. Try to break it by putting junk in the query string. Also check the StackScript Detail drawer (in the Linode Create flow).
> M3-3717 StackScript author links

- packages/manager/package.json
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- yarn.lock
There was some console noise from deprecated React lifecycle methods, upgrading should fix them.
Waypoint is used in 3 places: Object storage buckets, events landing page, and stackscripts. Please make sure behavior is unchanged in all 3.
> Bump react-waypoint to 9.0.2

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/types.ts
- packages/manager/src/utilities/statMetrics.test.ts
- packages/manager/src/utilities/statMetrics.tsx
- Calculate max units for Linode IPv4/IPv6 graphs and convert graphs to that unit.
- v4 and v6 graphs were redundant and tightly coupled, so I extracted them to a separate component. This also made it easier for the unit in the graph header to be dynamic.
LineGraph had 3 props related to units:
- unit
- maxUnit
- tooltipUnit
Unit was unused, so I removed it and renamed tooltipUnit to unit to be
more concise.
> M3-3682 Fix Linode network graph units

- packages/manager/src/components/TableRow/TableRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx
This was a bit of an edge case- but if the process name was lengthy enough to wrap to next line, the selected caret arrow wouldn't expand with the table row, which was not ideal. The solution was to use pure CSS for the caret instead of an svg so it could dynamically expand/shrink as needed per row. 
To test, make a process name long enough to wrap, and observe the new arrow style compared to production. I checked Safari, Firefox, and Chrome without any notable issues, as well as tested to make sure the spans would have no impact for screen readers. There should also be no difference on mobile.
> LV Improvement- Process Arrow Rework

- packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
- packages/manager/src/features/Profile/APITokens/utils.ts
The API now allows scopes to be a string of space-separated values, as in:
"linodes:read_write domains:read_only"
This means that:
- We _must_ be able to read these
- We _can_ use this format when creating, I did it this way bc
the Oauth spec has it this way, but it isn't necessary.
Test account 4 has a few tokens of both types. Try creating, reading, editing, etc. to see if everything works as before.
> M3-3735 Scopes can be space separated

- packages/manager/src/components/Toggle/Toggle.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
Adding helper text/ tooltip text to the configuration section to match the captions currently in Classic.
> M3-3356 Improve Form context help/info in Configuration Edit

- packages/manager/src/containers/account.container.ts
- packages/manager/src/features/Billing/BillingPanels/UpdateCreditCardPanel/UpdateCreditCardPanel.tsx
- packages/manager/src/store/account/account.actions.ts
- packages/manager/src/store/account/account.reducer.ts
The Billing Summary component sources its info from Redux. Upon updating credit card information, only the account context was being updated, which meant that Billing Summary didn’t display the updated information.
To fix, I created a new Redux action to update the credit card information, which is dispatched after the CC info is successfully updated.
Note: this entire section should be refactored to use Redux instead of the Context API since it’s one of the only big components/features that uses it.
> M3-3813 Display updated CC info in Billing Summary

- packages/manager/src/features/Domains/DeleteDomain.tsx
- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/hooks/useDialog.ts
Add a "Delete Domain" button to the Domain Drawer (while in Edit mode). This (along with https://github.com/linode/manager/pull/6028) solves the problem of not being able to delete a domain after clicking on a Slave Domain on the Search Landing page (or Dashboard).
I reused the brand new `<DeleteDomain />` component for this. I made a slight modification so that the consumer can decide what to do after successfully deleting the domain. The `<DeleteDomain />` component _still initiates the Toast_ since I figured we wanted that in all cases, but I'm open to other opinions here.
To test, open the drawer for a slave domain from the Domains Landing and Dashboard and delete the domain.
> M3-3826 Delete Domain from drawer

- packages/manager/src/components/AccessPanel/AccessPanel.spec.js
- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/Breadcrumb/Breadcrumb.spec.js
- packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.spec.js
- packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
- packages/manager/src/components/EnhancedSelect/EnhancedSelect.spec.js
- packages/manager/src/components/EnhancedSelect/EnhancedSelect.stories.tsx
- packages/manager/src/components/ErrorState/ErrorState.spec.js
- packages/manager/src/components/TagsInput/TagsInput.spec.js
**Fixed the TagsInput and ErrorState test files:**
Changes to the styling for the page seems to broken these tests.
ErrorState issue was that we changed the font size and styles.
TagsInput was a change in the styling.
example:
old selector '#add-tags input'
new selector 'input#add-tags'
another selector fix was to use the newer selectors added for automation
[data-qa-textfield-error-text="Add Tags"]
**Fixed the AccessPanel tests:**
Needed to change up some more selectors.
Moved the data-qa-password-input from the Access Panel div to the the PasswordInput section in packages/manager/src/components/AccessPanel/AccessPanel.tsx
Since we change the password strength area completely we are now using the password limitations and counting the number of warnings.
When the pass is not good enough …
> M3-3833 Fix storybook tests

- packages/linode-js-sdk/src/profile/profile.ts
- packages/linode-js-sdk/src/profile/types.ts
- packages/manager/src/LinodeThemeWrapper.tsx
- packages/manager/src/components/PreferenceToggle/PreferenceToggle.tsx
- packages/manager/src/containers/preferences.container.ts
- packages/manager/src/features/Longview/shared/TimeRangeSelect.tsx
- packages/manager/src/store/preferences/preferences.actions.ts
- packages/manager/src/store/preferences/preferences.reducer.ts
- packages/manager/src/store/preferences/preferences.requests.ts
Part I, only addressing the TimeRangeSelects used in Longview
- Return preferences data from the preferences container if no mStP is provided
- Add UserPreferences type to the SDK for easier reference
- Wrap TimeRangeSelect in the container, and default the select value to
the one stored in the longviewTimeRange preference
- Request + update preferences every time the time range is toggled
> M3-3819 Longview user preferences

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/StackScript/StackScript.tsx
- packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.test.ts
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
- packages/manager/src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
@Jskobos pointed out [here](https://github.com/linode/manager/pull/6010#pullrequestreview-346085330) that the query string was being re-read when the tab was changed. I set out to fix this, which led to a few other enhancements as well:
1. Clicking a tab ("Account" or "Community") will update the query string, which means that the tabs are now bookmark-able and are added to browser history. 
2. The query string is updated when the user types in the Search field, which means searches are bookmark-able. Note that in this case, **the history is replaced** meaning history events aren't added each time the user types.
A few behind-the-scenes things:
- Use the `qs` library to properly encode author links.
- Allow a specific value to be given to `<TabbedPanel />` (necessary for these changes)
- …
> StackScript Panel + query string improvements

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/ApacheGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
- packages/manager/src/utilities/roundTo/index.ts
- packages/manager/src/utilities/roundTo/roundTo.test.ts
- packages/manager/src/utilities/roundTo/roundTo.ts
Remove the concept of maxUnit inside our LineGraph abstraction, and replace it with two optional props:
- formatData(), called by the internal formatData method. Replaces the functionality of maxUnit, so consumers now have to pass readableBytes or whatever they'd like to use to shrink the data to a manageable unit.
- formatTooltip(), called by the tooltip callback inside LineGraph. We need two methods bc units in a tooltip can be mixed (to account for smaller values).
Rearranged things to work with the new pattern.
Possible future enhancements:
- Quarantine Longview utilities inside the LV directory, and make Manager-specific copies of any needed utilities to reduce the square peg/round hole problem. Alternatively, generalize our data pipeline so we can put different units through it.
- …
> [Fix] Refactor LineGraphs to allow mixed units for network graphs

- packages/manager/src/components/GaugePercent/GaugePercent.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
The original plan was for a single loading state on the landing page. This didn't work out well; we have to first request the clients and then request data for each of them, which would be a long load. In addition, the page is set up to rely on the gauges to make requests to the LV API; in order to do this, we'd have to add a `getAllClientData([...longviewClientAPIKeys])` method and call it. We'd also lose the individual loading states for clients and gauges.
So I'm trying another idea, where we set a height for the client cards so there's no jumping in the view as each client loads.
@WilkinsKa1 I didn't like how they looked when they were all the same height as the instructions component, but I noticed that clients don't switch from instructions to normal during loading, so it's ok. …
> M3-3818 longview loading state

- packages/manager/src/features/Domains/DomainDrawer.tsx
Feedback from stakeholder review. The Master nameserver IP section is more important than the AXFR section and should be higher in the drawer.
**Notes:**
- I remove a class on the `<Notice />` that wasn't doing anything since the `spacingTop` prop takes precedence (so I used that instead).
- Non breaking change ('update', 'change'
> M3-3837 Re-order Edit Domain drawer

- packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
- packages/manager/src/features/StackScripts/StackScriptUpdate/StackScriptUpdate.tsx
- packages/manager/src/features/StackScripts/StackScriptsDetail.tsx
This was a result of the dynamic breadcrumb. I added crumb overrides for: 
- Create StackScript
- Edit StackScript
- StackScript Detail
> Fix capitalization of "StackScripts" 

- packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeBusyStatus.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
- packages/manager/src/features/linodes/transitions.test.ts
- packages/manager/src/features/linodes/transitions.ts
- packages/manager/src/store/events/event.selectors.test.ts
- packages/manager/src/store/events/event.selectors.ts
- packages/manager/src/store/selectors/recentEventForLinode.ts
Previously we only showed progress on the source Linode during clone events. Now that the target Linode is included as the event’s `secondary_entity`, we can show progress there as well.
This required adjust both event selectors. Please feel free to judge readability and variable names harshly; I struggled coming up with meaningful names.
Still to do: 
Notes: 
- I added another argument to `transitionText()`: the Linode ID. I had to adjust the order of the arguments since the `event` arg is optional and `linodeId` is not.
Please test that Linode events work as expected across all views: Dashboard, Linode Landing, Linode Detail.
> M3-3817: Show progress on cloned Linode targets

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/OverviewGraphs.tsx
When I refactored isToday to take (start,end), I missed one place where the arguments had to be flipped.
> Fix: Istoday arguments reversed in OverviewGraphs

- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
This fixes an issue a customer reported where the button on the support ticket page was wrapping strangely.
This was reproducible only in Safari, but please also test for possible regressions in other browsers.
> M3-3840 Support 'Open Ticket' button is misaligned

- packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.test.tsx
- packages/manager/src/features/Longview/shared/utilities.test.ts
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
- packages/manager/src/utilities/statMetrics.test.ts
- packages/manager/src/utilities/statMetrics.tsx
Use base-2 for graph metrics
Previously the metrics displayed under each Linode and NodeBalancer graph were in base-10. This makes it so that these metrics are calculated with base-2 since that’s the way the data is formatted in the actual graph.
I also changed the following units:
`Kb` -> `Kibit`
`Mb` -> `Mibit`
This affects the Linode graphs and the Longview graphs.
Please test against production and Classic. Compare values for Max, Avg, and Last. The values in this PR should be slightly lower (the difference between base-10 and base-2).
Please remember to test the NodeBalancer graphs (which haven’t actually been updated to use native legends yet).
> M3-3838 Use base-2 for graph metrics

- packages/manager/src/features/Domains/DomainRecords.tsx
Another small adjustment based on customer feedback, there was a typo on the DNS Manager record time display.
> M3-3839 DNS manager displays '1 hours' instead of '1 hour'

- packages/manager/src/containers/withImages.container.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/Images/ImagesDrawer.tsx
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
Started out updating Images messaging to account for new secondary_entity capability, and found ~two~ four bugs while I was at it:
- Images list wasn't updating after editing label etc.
- CreateLinodeContainer wasn't looking at the imageID param, so "Deploy image to Linode" action was essentially broken
- ImagesDrawer didn't have a loading state
- Changing selected disk/Linode didn't reset the error state, so you could:
1. Open the Images drawer
2. Block requests
3. Select a Linode
4. Observe: you get a disks error
5. Unblock requests and select a new Linode
6. Observe: error is persistent, can't be gotten rid of until you submit the form.
Refactored a few things too, but there's still more tech debt in there, like many of our older components.
- Non …
> M3-3841 Fix: Images events messaging & assorted bugs

- packages/manager/src/store/selectors/recentEventForLinode.test.ts
- packages/manager/src/store/selectors/recentEventForLinode.ts
Thanks to @Jskobos for catching this.
This PR fixes a regression with Linodes that have an in-progress action happening as well as a more recent non-progress action. An example:
1. Reboot a Linode.
2. Quickly, change the Linode's label.
3. Observe: You no longer see progress on the reboot action.
This was happening because the `linode_update` was being considered as an "recent" event for the Linode. This was a regression that happened here: 
https://github.com/linode/manager/pull/6039/commits/dbf7af8faa45e62984fba2dbab8c34a8211090aa#diff-c3ba94a71d4fe8736aae34e6f82d0813L20
I also added unit tests to validate this behavior and prevent future regressions.
> Fix regression with in-progress events

- packages/manager/src/constants.ts
The comment on both intra- and inter- DC migrations said intra. This makes the inter- comment match the inter- constant.
Typo (bug fix in comment only)
Should not have any impact whatsoever on the functionality of the code
> Fix typo intra -> inter

- packages/manager/src/store/image/image.requests.ts
This fixes a regression introduced here: https://github.com/linode/manager/pull/6003/files#diff-c4e144660fa52d0b24fad41fcf71e0b4R16
There is an API bug in which the pagination of `GET /images` is validated differently than other types of entities. The max page size for this endpoint is 100 (instead of 500). The change above removed the `getAll` wrapper around `getImages` as a way to get around this error, but this didn't take into account that images can be created from deleted disks, so it is possible to have many Images – more than the ~35 public images and 3 private images that you are allowed on your account.
This PR adds the `getAll` wrapper back with a custom page size of 100.
To test, verify that all Images are loaded (public and private). Use mock data to simulate or an account …
> [hotfix] Fix Images pagination issue

- generate_changelog.py
Previously PR IDs were included on each commit message (e.g. `"Linode Configs (#1234)"`. These had to be removed manually after generating the changelog, so this just saves a few steps.
I also cleaned up the way the lines were being read from standard output.
To test, generate a changelog:
```
$ python3 generate_changelog.py v0.99.0 2020-01-31 upstream
```
Compare the results to running the same command on develop.
> Update generate_changelog script to remove PR IDs

- packages/manager/scripts/pre-push.sh
Accept "patch" as a valid prefix for branch names.
To test, create a branch and run the `pre-push.sh` script: 
```
$ sh packages/manager/scripts/pre-push.sh
```
> Accept 'patch' as a branch prefix

- packages/manager/src/features/Domains/DomainsLanding.tsx
Idea is to have an import zone button on the landing page of domains by default
Here i did not see an existing e2e to update.
But I will create a task to have e2e on all placeholder actions i guess.
> have an import zone drawer when no domain exist

- packages/linode-js-sdk/src/kubernetes/types.ts
- packages/manager/src/__data__/nodePools.ts
- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolRow.tsx
- packages/manager/src/features/Kubernetes/types.ts
**Do not release until API changes are in production.**
- The NodePools key "linodes" has been renamed to "nodes".
- NodePools now has an `instance_id` which can be a number or null.
- The NodePools key "id" is now a string instead of a number.
The renaming of "linodes" to "nodes" was causing a bug where the node status display was incorrect.
Currently you must these changes in dev.
> [for release] Update LKE types

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
This PR does two things:
1) Fixes a regression introduced [here](https://github.com/linode/manager/pull/6046/files#diff-d9337d394dbeec6c368da20a7e38a161R156), which meant that the default image wasn’t working. To fix, I used nullish coalescing to give an optional value to selectedImageID.
2) Changes the default image from Debian 9 to Debian 10.
> Fix default image and change default to Debian 10

- packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Previously, in the Create Linode from Backup flow, we requested ALL backups for ALL Linodes at once. This caused huge slowdowns for users with many Linodes.
Now, backups aren't requested until an individual Linode is selected.
**NOTE:**
These components are old and have a lot of old patterns. There is still room for improvement. I took the path of least resistance where I could find it.
Please test all scenarios:
- with backups enabled
- without backups enabled
- backups enabled but no backups
- ...etch
> [for release] M3-3870 Request backups after selecting Linode in Linode Create

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
This fixes a regression introduced in [this commit](https://github.com/linode/manager/pull/6081/commits/95480dd3e554bb00af5a85baf9c8f38b6cd76aa6) where clicking "Deploy to a new Linode" didn't preselect the backups.
> [for release] Fix backup from Linode

- packages/manager/src/components/OrderBy.test.ts
- packages/manager/src/components/OrderBy.ts
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
- packages/manager/src/store/preferences/preferences.actions.ts
POC for how to save sortable table selections (order and orderby) in user preferences. Right now, only activated in the bottom Longview Overview tables (connections and services).
The idea is that you pass an optional `preferenceKey` prop to `OrderBy` if you'd like a table's options stored in preferences. OrderBy then does all the work of looking for and updating order and orderby for that table.
I debounced the actual API calls so that a user can toggle back and forth without it getting laggy. The experience still doesn't seem super-fast though, suggestions welcome.
> M3-3819  [LV] User preferences phase 2

- packages/manager/src/features/Lish/Lish.tsx
To test:
- Go to Linode Detail and select Launch Console
- From the original tab, log out
In prod, the Lish window would stay open. On this branch, it will close automatically.
Other fun things to try: 
- Mobile 
- Opening a link to Lish directly (something like http://localhost:3000/linodes/{id}/lish/weblish) and seeing how it responds to logging out in a separate window
- Triggering a token refresh (setting your token to expire in a minute or two) and making sure it doesn't disrupt the experience of the other open windows.
> M3-3846 Close any Lish sessions when logging out

- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/ToastNotifications/ToastNotifications.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
- packages/manager/src/utilities/minute-conversion/minute-conversion.test.ts
- packages/manager/src/utilities/minute-conversion/minute-conversion.ts
- Add toasts for successful/failed resize, clone, and migrate events
- Refactor the ToastNotification.tsx logic (long time coming, the copy/paste was getting unmanageable)
- Remove (Unknown) from the duration column if we don't have a duration (has Jay's ok)
Trigger a bunch of disk deletes, images, resizes, clones, etc. and make sure you get the same toasts as before, and that the new ones work correctly
> M3-3842 Change: Update event toasts

- packages/linode-js-sdk/src/object-storage/types.ts
- packages/manager/src/constants.ts
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
Add OBJ support for Frankfurt DC.
I also changed the Cluster Select to use `formatRegion()` instead of `formatObjectStorageCluster()`, since these display names are based on the region, not cluster (there was initially some back-and-forth with this).
I also removed the display name mapping for PHL and defaulted to the actual cluster ID and region slug for this case (this can be seen in Dev).
Here is an `/object-storage/clusters` payload you can use to test (Charles, hardcoded, whatever you like):
```json
{ 
"data":[ 
{ 
"id":"us-east-1",
"region":"us-east",
"status":"available",
"domain":"us-east-1.linodeobjects.com",
"static_site_domain":"website-us-east-1.linodeobjects.com"
},
{ 
"id":"eu-central-1",
"region":"eu-central",
"status":"available", …
```
> [hotfix] OBJ support in Frankfurt

- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx
I happened to find this extra space:
> Remove extra whitespace in Contact Information on account/billing

- packages/linode-js-sdk/src/firewalls/types.ts
- packages/manager/src/__data__/firewalls.ts
- packages/manager/src/features/Firewalls/shared.ts
- packages/manager/src/store/firewalls/firewalls.reducer.test.ts
We want to provide some common, predefined firewall rules for users to choose from when creating a Firewall. They can add or edit these rules afterwards.
These won't be used until we update the create drawer. In the meantime, please test the `rules` payloads with `curl` or Insomnia.
> M3-3247 Add: Predefined firewall rules

- packages/manager/src/components/SnackBar/CloseSnackbar.tsx
- packages/manager/src/components/SnackBar/SnackBar.tsx
We recently upgraded to Notistack 0.9.7, and our logic update was incorrect.
This introduced a regression where clicking on the X on a toast message
dismissed all notices currently on the screen.
To fix this, I used patterns from the official docs
(https://iamhosseindhv.com/notistack/demos#action-for-all-snackbars).
This involved changing our Snackbar abstraction to a function component
and passing an onClick handler down to CloseSnackbar (rather than the key prop
that was previously used).
It may be possible to use the useSnackbar hook with this new version,
but I felt safer using officially recommended methods.
> M3-3930 Fix: Regression with Notistack

- packages/manager/src/factories/disk.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderError.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderLoading.tsx
- packages/manager/src/store/linodes/disk/disk.reducer.test.ts
- packages/manager/src/store/linodes/disk/disk.reducer.ts
- packages/manager/src/store/linodes/disk/disk.selectors.ts
- packages/manager/src/store/store.helpers.ts
This fixes a bug in which editing disks for _one_ Linode in _one_ tab modifies the **display of disks** for a _different_ Linode in a _different_ tab.
The mechanism behind this faulty behavior is that we have ONE key for Linode Disks in the store, called `__resources.linodeDisks`. This state is populated when a user navigates to a particular Linode’s Detail page. By design, only disks belonging to _that particular Linode_ are loaded in this state.
However, we dispatch the `getAllLinodeDisks` action when we receive a Disk event, so if we get a `disk_update` event for LinodeA, the `linodeDisks` state gets populated with LinodeA’s disks, even if we’re currently viewing LinodeB.
To fix, I have changed the shape of `linodeDisks`. Instead of being an instance of MappedEntityState, we map Linode …
> M3-3467 Fix updating Disks bug

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
To test:
- Use dev services
- Set your reputation to 0 in Admin
- Create a cluster
- Observe: you should see nicely formatted events for this event type, one for each node you specified.
@jnschaeffer mentioned a CTA to open a support ticket, I'm working on that as an add-on, but currently the necessary API filters aren't enabled.
- Added the event action type to EventAction
- Pre-filled the k8s version in the Create flow, I should have done this to start with and it's been bugging me.
> M3-3810 LKE: Add messaging for lke_node_create error event

- packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedChartPanel.tsx
- packages/manager/src/features/Longview/shared/utilities.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
This PR does three things:
1) Use the new formatData and formatTooltip patterns on the Managed Network Graph. So instead of always showing `bit/s`, we generate the units dynamically. We had previously done this work for Linode graphs but not Managed. Still to do: NodeBalancers.
2) Fix bug where dynamic units were being double converted, so sometimes the scale of Linode graphs was incorrect. 
3) Use the native legend on Managed Graph.
To test, run up various amounts of traffic on Linodes and look at Linode graphs and Managed graphs.
> Managed network graph units

- packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
While creating/editing a NB config, the "TCP Connection" health check option was intentionally disabled when "HTTP" or "HTTPS" was the selected protocol. It is unclear why this was the case, but we've received feedback that this is restrictive for some use cases, so this PR removes it.
Please check the NB config creation/update flow, cross reference with API documentation.
> M3-3556 Always enable TCP Connection as a health check

- packages/manager/src/__data__/firewalls.ts
- packages/manager/src/containers/firewalls.container.ts
- packages/manager/src/factories/firewalls.ts
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallTable.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallTableRows.tsx
- packages/manager/src/features/Firewalls/index.tsx
- packages/manager/src/store/firewalls/firewalls.actions.ts
- packages/manager/src/store/firewalls/firewalls.reducer.test.ts
- packages/manager/src/store/firewalls/firewalls.reducer.ts
- packages/manager/src/store/firewalls/firewalls.requests.ts
- packages/manager/src/store/image/image.reducer.ts
- packages/manager/src/store/longview/longview.reducer.ts
- packages/manager/src/store/store.helpers.ts
- packages/manager/src/store/types.ts
Adds Redux methods for the basic Firewall CRUD actions, and wires them all into firewall.container.ts. I haven't done any of the rules/devices work yet, since I'm not sure all of that belongs in Redux.
Some typing changes were involved but the behavior of the app should be unchanged from develop.
> M3-3857 firewall sdk redux

- packages/manager/src/components/DrawerContent/DrawerContent.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigPanel.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
- packages/manager/src/features/Support/TicketDetailText.tsx
- packages/manager/src/formatted-text.css
Syntax highlighting broke in the kubeconfig drawer, and we had a request to not split lines (we were doing this to show all of the config values within the drawer without scrolling).
- Fixed highlighting in the kubeconfig drawer
- Fixed highlighting in the support ticket preview drawer (logic was the same)
- Removed `splitLines` function
- Allowed passing a custom error message to `<DrawerContent />` (this was a separate ticket--M3-3969--but I was in the file anyway).
To test, create a new k8s cluster and immediately click "View Config" (this will let you test the error message). After a minute or so, view config again to check the highlighting.
> M3-3931 Fix: kubeconfig format

- packages/manager/src/features/Firewalls/FirewallDetail/FirewallLinodesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallRulesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
This PR contains the basic tabbed routing structure for Firewall Details. A lot of this boilerplate code comes from similar tabbed interfaces (I copied this one from ObjectStorageLanding).
Until https://github.com/linode/manager/pull/6108/files is merged, apply this patch to request Firewalls at the Firewall index level: https://gist.github.com/johnwcallahan/857efc9dc1d9302f36fb74593b840416
Please check the usual suspects:
- Loading
- Error
- 404
- Browser "Back" and "Forward" buttons
> M3-3278 Firewall Detail structure (tabs, routing)

- packages/manager/public/manifest.json
Customer would like to have a "standalone" experience, whereas we had previously opted for "minimal-ui". I'm not sure what the reason was for choosing minimal-ui, but this seems to do what's requested on both Android and Safari.
To test:
- Open local build in Chrome or Safari (I think only Safari will work on IOS).
- Choose "Save to home screen"
- Click the generated link.
- You should see a native-like experience with no web browser UI (navbar, bookmarks, etc.) visible.
> M3-3971 Update manifest.json display to standalone for IOS support

- packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
@acourdavault this took 5 minutes so I just went ahead and did it.
Try http://localhost:3000/linodes/create?type=One-Click&appID=401697&showInfo, WP should be selected and the info drawer should be open.
> Add checking for showInfo URL param

- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/utilities/ga.ts
- yarn.lock
Adding Event tracking on GA:
- search + select, or go to landing page of search event.
- pathname  (to know the context of the search)
Goal is to be able to track the usage of this feature.
I decided so far not to track the searched text, or time of search, Both could be useful informations though
> simple search bar event tracking in GA

- packages/manager/src/factories/config.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderError.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderLoading.tsx
- packages/manager/src/store/linodes/config/config.reducer.test.ts
- packages/manager/src/store/linodes/config/config.reducer.ts
- packages/manager/src/store/linodes/config/config.selectors.ts
- packages/manager/src/store/store.helpers.ts
This implements the new Redux shape for configs, following https://github.com/linode/manager/pull/6073.
There is _a lot_ of copy/paste from the disk reducer and tests. I don’t love this, but I thought it was better than trying to use one reducer for multiple entity types. I’m open to suggestions if you see something that I don’t.
To test, please thoroughly check everything to do with configs:
- Linode creation/deletion/cloning/resizing/rescue/migrating
- Config creation/editing/deletion/cloning
- Since disks are related, check those too.
- etc…
Please monitor Redux Dev Tools, operate multiple tabs, and just try to break it in general.
> M3-3970: Implement new Redux shape for Configs

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivityRow.tsx
There is currently an API bug where `host_reboot` event durations are not reported correctly. This patch hides the duration for these events until the API bug is fixed.
> Hide duration for host_reboot events

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
We use the same Disk drawer for all cases, disabling/hiding unneeded fields
for actions such as renaming a disk, where only one field is editable.
However, we were not resetting the "mode" of the drawer on close. This lead
to a bug:
1. Open the "Add Disk" drawer and choose "from Image"
2. Close the drawer
3. Reopen the drawer in "rename" or "resize" mode.
4. The "from image" fields are all there and editable.
This PR resets the mode to "from empty" on close.
- Fixes a small typo
NOTE: I did this on close to avoid the `prevProps.open === false && props.open === true` logic in a cDU. If the change while the drawer is closing is too jarring, I can do on open instead.
> M3-3942 Fix: Mode persistence in Linode Disk drawer

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
At UX review for LKE yesterday, Andrew expressed that we don't want to select a k8s version by default when creating a cluster. The UX isn't ideal (it's an additional 2 clicks) but there are technical reasons for it, so disabling this logic for the time being.
> Hold our horses

- packages/manager/src/constants.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/index.tsx
This changes the name of the `isProduction` variable in `constants.ts` to `isProductionBuild`.
This has tripped us up more than once, because the name leads you to believe that it will be `true` only in the production environment. In reality, this value is `true` across all builds that aren’t your local dev server.
BTW, the NODE_ENV is set [here](https://github.com/linode/manager/blob/develop/packages/manager/scripts/build.js#L5).
> Rename isProduction constant

- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
We noticed that selecting an invalid stackscript when rebuilding didn't
result in an error that the user can see. It turns out what was wrong
was that the field returned in that case was script, whereas our
Formik field was listening for stackscript_id.
I also tweaked the styles of SelectStackscriptPanel so that the
resulting error wasn't stuck to the top of the Paper.
Steps to reproduce: 
1. Go to the /rebuild tab in LinodesDetail
2. Select a crummy stackscript to rebuild from (LinodeApps/Wordpress will do the job)
3. Submit the form (with devtools open)
4. Observe: the request returns a 404, but nothing is displayed to the user.
> M3-3685 Display invalid SS errors on Linode rebuild

- packages/manager/src/features/StackScripts/stackScriptUtils.ts
All of these apps are available to the public, so we want to remove reliance on LD to serve them. When this is released, we can clear out these values from LD.
> Add current slate of apps to baseApps

- packages/linode-js-sdk/src/firewalls/types.ts
- packages/manager/src/__data__/firewallDevices.ts
- packages/manager/src/components/TableContentWrapper.tsx/TableContentWrapper.test.tsx
- packages/manager/src/components/TableContentWrapper.tsx/TableContentWrapper.tsx
- packages/manager/src/components/TableContentWrapper.tsx/index.tsx
- packages/manager/src/factories/firewalls.ts
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallDeviceActionMenu.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallDeviceRow.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallDevicesTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallLinodesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/hooks/useFirewallDevices.ts
- packages/manager/src/store/firewalls/devices.actions.ts
- packages/manager/src/store/firewalls/devices.reducer.test.ts
- packages/manager/src/store/firewalls/devices.reducer.ts
- packages/manager/src/store/firewalls/devices.requests.ts
- packages/manager/src/store/index.ts
- packages/manager/src/store/store.helpers.ts
- packages/manager/src/store/types.ts
Adds content to the firewalls/id/linodes view. Includes:
- Redux boilerplate for Firewall devices
- Hook with useSelector instead of a normal container for devices
- 2 new Redux types that we hope will serve as our universal store format
- TableContentWrapper, which abstracts our loading/empty/error logic for tables
Still to come in this PR: 
Still to come in the next PRs:
- Add the "Add a Linode to this Firewall" drawer
- Enable the action menu ("remove" is there but non-functional)
- Rewire the existing FirewallRows component to use the new hook
> M3-3928 Add: Firewall linode tab

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
Well here’s a fun one! Previously the Bucket Table Row used `label` as it’s key. That’d be fine if bucket labels had a unique constraint. Well… they actually do, but only per region. Now, with multiple regions, it’s possible to have two items in this table with the same label, and therefore the same key.
Which means, that when the table is re-ordered (e.g. adding a new bucket or sorting the table) React doesn’t throw away the old entry, and you end up with duplicate items in the table.
This changes this behavior so that the key is determined by the label AND the region. This should ensure uniqueness.
> fix: Use label + region as React key for OBJ table

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
The `label` and `active` props were looking at `region` instead of `cluster`, which meant sorting by clicking the Region header column doesn't work.
To test: create buckets in multiple regions. Click the "Region" table header to sort.
> Sort by OBJ cluster instead of region

- packages/manager/src/utilities/formatUptime.test.ts
- packages/manager/src/utilities/formatUptime.ts
Longview uptime is inaccurate for servers up longer than 30 days. To test the fix, please compare clients of various ages/uptimes against Classic. The displays should match.
> M3-4018 Fix uptime calculation in Longview

- packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
- packages/manager/src/hooks/useFirewallDevices.ts
- packages/manager/src/store/firewalls/devices.reducer.ts
Each FirewallRow was making its own request to /devices to see
what Linodes were attached to it. This is hard to avoid, but every
time you e.g. switched tabs and came back, the requests happened again.
This way, the requests are only made once, whenever we first need to
access a Firewall's device list. Subsequent views will read from the
Redux store.
Navigate around the app with the networking tab open (filter for /devices). Ensure that devices load normally in all views, and that requests are only made the first time a particular Firewall's devices are needed.
> Change: Use Redux/useFirewallDevices hook in FirewallRow

- package.json
- yarn.lock
Adds `yarn upgrade:sdk`
This feature allows you to easily update the package json sdk version
I also did some dedupe of the lock file this way when running `yarn upgrade:sdk` you simply enter interactively the new version, an d your lockfile is untouched
0. **create a clean copy** (because `yarn link` or `lerna` could have created symlink in your working copy
1. checkout + `yarn install:all`
2. try `yarn upgrade:sdk` and enter in the interactive command whatever version you want.
3. should only affect package.json files in both packages. **must not ask for npm registry version**
At this point this does not create a git tag
> yarn upgrade:sdk command

- packages/manager/src/features/Firewalls/FirewallDetail/FirewallRuleTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/FirewallRulesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- Use real data for FW rules.
- Add an “Empty” table row state.
The Add/Edit/Delete actions don't work yet, so you'll still need to add rules with the API to see them. Here's a sample payload:
```
PUT https://api.linode.com/v4beta/networking/firewalls/{ID}/rules 
{
"inbound":[
{
"ports":"443",
"protocol":"TCP",
"addresses":{
"ipv4":[
"0.0.0.0/0"
],
"ipv6":[
"::0/0"
]
}
},
{
"ports":"80",
"protocol":"TCP",
"addresses":{
"ipv4":[
"0.0.0.0/0"
],
"ipv6":[
"::0/0"
]
}
},
{
"ports":"22",
"protocol":"TCP",
"addresses":{
"ipv4":[
"0.0.0.0/0"
],
"ipv6":[
"::0/0"
]
}
}
]
}
> Use real data for Firewall rules

- packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.test.tsx
- packages/manager/src/components/PromotionalOfferCard/PromotionalOfferCard.tsx
- packages/manager/src/factories/promotionalOffer.ts
- packages/manager/src/featureFlags.ts
This gives us the ability to specify a promo button’s type as “secondary”, which will use styling similar to the “secondary” variant of our Button component. The colors are different here, so I added the CSS manually.
@WilkinsKa1  let me know your thoughts on the colors.
**To test:** check out this PR and have a look at the Dashboard. The change has already been made to the feature flag, so you should see it.
> Add support for secondary promo button

- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.test.tsx
- packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
- packages/manager/src/components/LinodeMultiSelect/index.tsx
- packages/manager/src/factories/linodes.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDevicesTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
- packages/manager/src/store/firewalls/devices.requests.ts
- packages/manager/src/utilities/getAll.ts
- Adds an Add Device drawer
- Extracts the select multiple Linodes logic from AddFirewallDrawer to a new component (LinodeMultiSelect)
Still missing: 
To test: Use test account 4 or create your own Firewall. Navigate to /firewalls/id/linodes and click "Add Linodes to Firewall"  to try and add Linodes through the drawer. Please test all paths (success, failure, single addition, multiple additions, "All Linodes").
> M3-4020 Add: "Add Device" drawer to Firewall Linodes tab

- packages/manager/src/themes.ts
In dark theme mode, the table cells were inheriting a white border. This fixes that!
> Adjustment for table cell dark theme styles

- packages/manager/src/features/Footer/Footer.tsx
This brings the footer up to date with our current tagging practice. This is backwards compatible (will work with the current release) and will allow us to stop creating the bogus 3rd tag for every release.
Click the version link at the bottom of Cloud and make sure it takes you to a valid GitHub release.
> Pin GitHub release link to linode-manager tag

- packages/manager/src/constants.ts
- packages/manager/src/features/Images/ImagesDrawer.tsx
- packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
DM for link to the post explaining why this is happening. The change should go live soon-ish, so we should update our messaging.
> Update Images messaging to reflect new 6144 MB default limit

- packages/manager/config/webpack.config.prod.js
To make sure we're not excessively bloating the javascript bundle size, we can set a performance budget that will fail `yarn build` if the bundle exceeds 1.08MiB. The current size is 1.07MiB. We might want to loosen this threshold a bit so it doesn't fail every time.
> Utilize webpack performance budgets

- packages/manager/config/webpack.config.prod.js
Looks, like build was broken by check of the assets max size.
With recent addition of firewall it seems to make some sense that we increased by about ~ 200kb
I upgraded the limit to 1.12 MB (Instead of 1.08) to trigger only in case of a big bump over our current new size (1.09).
> increase asset limit to 1.12 MB

- packages/manager/src/features/Support/SupportTickets/TicketList.tsx
There are a few fields we can sort by (via API filters) that we're not taking advantage of. This adds sortable table columns for "Subject", "Ticket ID" and "Updated By".
Note: Sorting by "Ticket ID" and "Updated By" may not be very useful, but since it's possible with the API and I didn't see any harm, I decided to included it anyway.
**To test**, visit "/support/tickets" and play around with the sorting.
> Make Support Ticket table sortable by summary, ID, and updated_by

- packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
Assorted feedback items from the original PR and sprint review:
- disable addDevice form button if no Linodes have been selected
- Show slightly more helpful message if all Linodes are already attached
- use e.preventDefault() to prevent page from reloading when pressing Enter inside the <form>
- Use `key` prop to reset LinodeMultiSelect form state
When the Add Device form is submitted, and an error occurs,
the previously selected Linodes remained selected in the LinodeMultiSelect
field. They remained unchanged regardless of whether the Linode in question
was successfully added to the firewall.
This could cause problems, e.g.:
1. Select one invalid Linode and two valid Linodes
2. Submit the form
3. Observe: all 3 are still selected and an error is displayed for the "bad" Linode
4. Submit …
> M3-4020 Follow-up

- package.json
- packages/manager/package.json
- yarn.lock
This fixes a security alert found with yarn audit. Here are the steps I took:
1) Run `yarn audit --low` and took note of the dependency chain.
2) Add resolution to root package.json and packages/manager package.json.
3) Run `yarn install`.
**I did not make manual changes to yarn.lock.**
A few other changes were made to yarn.lock were when I ran `yarn install` rather than `yarn install --frozen-lockfile` (this was necessary to resolve the most recent version of minimist).
To test, `yarn clean && yarn up` and  run the app and the tests. Everything should work like before.
> Update minimist to ^1.2.3

- packages/manager/src/features/Domains/ListGroupedDomains.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/ListGroupedNodeBalancers.tsx
- packages/manager/src/features/Volumes/ListGroupedVolumes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
Addresses https://github.com/linode/manager/issues/6191.
Previously right/left padding was set to 0 for all groups except the first. I think originally this was probably to make the "No tags" group stand out, since the "No tags" group used to be first in the table. This has since changed, and now "No tags" is the last group in the list.
I tried applying the 0 padding to the *last* group (where the "No tags" group currently lives) but this looked a bit off to me.
Instead I applied the 0 padding everywhere, except for smaller viewports where the cards are used (this looked better to me).
@WilkinsKa1 and @tiffwong let me know if this looks OK to you.
Please check `/linodes` with all display options (group by tag, list, grid, etc.).
> Adjust header padding in Linode Group By Tag

- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolDisplayTable.test.tsx
Console noise was bugging me.
On `develop`, `yarn test nodepooldisplay` will give a bunch of duplicate key errors.
On this branch, should be clean.
> Use factories in node pools test to resolve console error

- packages/manager/src/components/MultipleIPInput/MultipleIPInput.test.tsx
- packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
- packages/manager/src/utilities/ipUtils.ts
For Firewall Rules we need a way to display errors for individual IPs in the Rule Drawer. The MultipleIPInput component dealt with an array of strings, which didn't lend itself well to also keeping track of errors.
I tried a few different things to address this, including a separate `ipErrors` array (and map) but managing state separately led to numerous headaches.
The best solution I found was to create a new `ExtendedIP` interface, which has an address and optional `error` string. This way an error is explicitly bound to the IP address it references.
To test, please check the places where MultipleIPInput is used, specifically when creating a slave domain and editing the SOA record of a master domain. **Nothing should be different.**
Don't pay much attention to the changes in …
> Multiple IP Input errors

- packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
Currently, situations can arise where if a Linode is not running and is not offline (i.e., in a transition state), a user can click the Linode Power Control menu and it will be empty.
To remedy this, I made it so that the menu is disabled while the Linode is in one of those transition states, such as cloning.
1. `yarn test LinodePowerControl.test.tsx`
> M3-3888: Prevent Linode Power Control menu from being empty upon click

- packages/linode-js-sdk/src/account/types.ts
- packages/manager/src/factories/invoiceItem.ts
- packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
- packages/manager/src/features/Billing/PdfGenerator/utils.ts
- packages/manager/src/features/Profile/Referrals/Referrals.tsx
This fixes https://github.com/linode/manager/issues/6089.
This PR removes an unnecessary page break that was inserted before the "Invoice Totals Table" at the bottom of PDF invoices.
It also:
- Adds an `invoiceItem` factory for testing.
- Fixes typing of `unit_price` on `invoiceItem`.
- Adjusts widths of the "Invoice Totals Table" to fix clipping.
**To test,** please check real invoices on test accounts as well as your personal accounts. To test specific numbers of line items (to check line breaking) insert this at L11:
```typescript
import { invoiceItemFactory } from 'src/factories/invoiceItem';
```
and this at L138:
```typescript
items = invoiceItemFactory.buildList(20);
```
and adjust the number as desired.
> M3-3558 Remove page break on invoices

- packages/manager/src/containers/domains.container.ts
- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/features/Domains/DomainsLanding.test.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
This fixes an issue described here: https://github.com/linode/manager/issues/6105
Previously after a successful zone import, we were redirecting to the Domain Detail page but not updating the Redux store with the domain. This resulted in a 404.
In this PR, we dispatch an `upsertDomain` action first to update the Redux store.
**To test**, you need to you import a domain from another DNS provider that allows AXFR requests (you also need to whitelist Linode's servers as described [here](https://www.linode.com/docs/platform/manager/dns-manager/#import-domains-with-axfr)). I've got a test domain set up if you want to reach out to me for ease of testing.
> Update Redux store after importing Domain Zone

- packages/manager/src/components/Prompt/Prompt.tsx
- packages/manager/src/components/Prompt/index.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
This PR adds a confirmation modal when the user navigates away from a Firewall with unsaved rule changes.
React-router has a `<Prompt />` component which almost does the thing we want. The problem is that you can't provide a custom modal (since it uses the browser's `window.confirm()` function).
There are a few ways around this, but they are in general fairly anti-React (like this one, which involves manually creating DOM nodes at the root level: https://gist.github.com/robertgonzales/e54699212da497740845712f3648d98c)
Another alternative is the [react-router-navigation-prompt library](https://www.npmjs.com/package/react-router-navigation-prompt), which I took for a test drive. The problem there is that with the way the components are rendered, we lose MUI transitions on the modal, so it …
> M3-4055: Prompt user when navigating away from Firewall Rules

- packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.test.tsx
- packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
- packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
This PR acts as a followup to the conversation from the original PR: https://github.com/linode/manager/pull/6182#pullrequestreview-375294060 
I updated the theme from `highlight.js` to a more light-theme-friendly style, but that caused issues for dark theme. Originally I wanted this to be a bit more dynamic than it is, but at this point in time conditional imports aren't a thing (yet). Instead, I added a custom style to aid in the switch of the styling of MD for dark theme.
Please view highlighted markdown usage in a variety of places (LKE, Support ticket preview, etc.) in both themes.
> Follow up: Dynamic theming for highlight.js

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/containers/firewalls.container.ts
- packages/manager/src/containers/longview.container.ts
- packages/manager/src/containers/withLinodes.container.ts
- packages/manager/src/hooks/useEntities.ts
- packages/manager/src/store/domains/domains.actions.ts
- packages/manager/src/store/firewalls/firewalls.actions.ts
- packages/manager/src/store/linodes/linodes.actions.ts
- packages/manager/src/store/longview/longview.actions.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.actions.ts
- packages/manager/src/store/store.helpers.tmp.ts
- packages/manager/src/store/volume/volume.actions.ts
- packages/manager/src/utilities/getAll.ts
In an attempt to make the typing work out for the updated createRequestThunk,
I returned response.data from the Thunk's "done" logic. This broke single-entity
requests, such as createVolume, which returns a single Volume object and has
no data property.
I undid this, and tried a different way to resolve the typing. This involved
matching the GetAllData type with ResponsePage, which assumes an array
of its type argument (`ResponsePage<Linode>` returns `Linode[]` in its data field).
For now, manually did then(result => result.data) in the Volumes and NBs
handling in useEntities so that they return an array as intended.
Please make sure everything still works. Volume creation was broken after the change described above and the support ticket drawer was broken before it, but anything related …
> Fix Volumes creation bug

- packages/manager/src/components/EditableText/EditableText.tsx
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
Edit a Firewall's label in the breadcrumb of the detail view. This will be the only way to edit a Firewall's label.
**Update:** 
Added error handling to the breadcrumb and prevented the error text from shifting the the textfield up.
> M3-3925: Make Firewall breadcrumb editable

- packages/manager/src/features/Domains/DomainRecords.tsx
There was a bug due to the regex logic where users were not able to edit DNS records that had Name Servers containing "linode.com" substrings. This logic was to prevent users from editing the five (e.g., ns1.linode.com, ns2.linode.com, ... ns5.linode.com) that are automatically created upon a domain's addition, but it was also preventing the editing or deleting of any DNS records that had the "linode.com" substring in the NS at all.
I revised the regex to include only the 5 initial ones that get created automatically.
> M3-4054: Edit DNS Records containing "linode.com" substring in NS

- packages/manager/src/features/Search/ResultGroup.tsx
An extra empty table header cell was causing a shift on the search results landing page. Removing this should fix that issue.
> Removing extraneous empty table header cell on Search Landing

- packages/manager/config/testSetup.js
- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.test.tsx
- packages/manager/src/components/TagsInput/TagsInput.test.tsx
- packages/manager/src/components/TagsInput/TagsInput.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/__mocks__/LongviewClientRow.tsx
- packages/manager/src/features/Longview/__mocks__/request.ts
- packages/manager/src/features/Longview/request.ts
- packages/manager/src/features/Volumes/VolumeDrawer/LinodeSelect.test.tsx
- packages/manager/src/store/longviewStats/longviewStats.requests.ts
- Mock client rows in the LinodeClients.test to prevent them from
rendering the gauges and making a ton of mock requests unrelated
to the test. (this fixes the not wrapped in act warnings)
- When trying to track that down, I added logic to log an error
if any of our tests attempted to hit the real Linode API. This led
down a bit of a rabbit hole:
- removed axios-mock-adapter from the TagsInput test and rewrote
those tests in RTL
- mocked preferences calls since it turns out that our wrapWithTheme
helper was making a call on each use
- fixed TopProcesses tests, which were calling resetAllMocks() instead
of clearAllMocks(), which was resetting the mocked preference calls
- stopped a call to /linodes in the old LinodeSelect tests
No "real" files were affected by this PR, test stuff only. …
> Test Cleanup

- packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Previously the `addTitles()` method (used to insert the Tax ID into the document) used a constant value for the Y coordinate. This meant that if a user had a long address, there would be a collision:
To fix this, the `addLeftHeader()` and `addRightHeader()` methods now return the Y value of the last line they inserted. We then pass the max of these (either left OR right header Y coordinate) to the "addTitles" method, which uses this dynamic value instead of the constant.
Note: I don't like this code.
Make your address long, change your country a tax country and add a Tax ID. Check that invoices and payment receipts work OK.
> M3-4033 Invoice PDF tax ID collision

- packages/manager/cypress/support/api/linodes.js
Bed regression, the test code is supposed to clean up test linodes when launching cypress, but instead it was deleting  all linodes ignoring if they were test linodes ('cy-test' tag or 'cy-test-' prefix in name)
> Fix deletealltestlinodes was deleting ALL linodes (not just test ones)

- packages/manager/src/features/Search/SearchLanding.test.tsx
resetAllMocks undoes the mocking of the preferences endpoint,
which in turn breaks any tests wrapped in LinodeThemeWrapper.
Please describe the tests that you ran to …
> Use clearAllMocks instead of resetAllMocks in SearchLanding.test.tsx

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
Added error handling to the Kubernetes breadcrumb to let users know why the label isn't being changed.
> M3-4072: Add error handling to Kubernetes breadcrumb

- packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
Cloud was sorting StackScripts by `deployments_active`, was wasn't officially supported by the API. The API introduced a change that broke this behavior, so we need to sort by `deployments_total` instead of `deployments_active`.
> Change StackScript "Active Deploys" column to "Total Deploys"

- packages/manager/src/App.tsx
- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/components/DataLoadedListener.tsx
- packages/manager/src/containers/withNodeBalancers.container.ts
- packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.test.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
- packages/manager/src/store/nodeBalancer/nodeBalancer.containers.ts
- packages/manager/src/store/nodeBalancer/nodeBalancer.requests.ts
There may be a part III, since it turns out NB detail doesn't use Redux at all, and just eternally polls the API to maintain its internal state. Fixing this is a lot of overhead and won't actually save many requests (polling is polling), but I still think it's worth it if I have time.
> [Performance] NodeBalancers part II

- packages/manager/src/components/ImageSelect/ImageSelect.tsx
We were using the onFocus handler in the ImageSelect component,
and passing it the same change handler as in the onChange prop.
Since onFocus is always called with undefined, clicking on the select
to view available options would clear the input. Removed the onFocus
handler to account for this.
> Fix bug in image select

- packages/manager/src/constants.ts
In production, we proxy the api through cloud.linode.com/api/v4. I forgot
about this when doing the caching logic, and as a result types requests
are cached when running locally against prod services, but not in
actual production. Updated the regex to account for this.
> Fix regex for isProdApi constant

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/components/ImageSelect/ImageSelect.tsx
- packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
- packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx.rej
- packages/manager/src/features/Images/ImageSelect.test.tsx
- packages/manager/src/features/Images/ImageSelect.tsx
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding.test.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/features/linodes/LinodesLanding/index.tsx
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/store/image/image.reducer.ts
Remove requestImages() from our initialRequests block and have different components request images data as needed.
Performance gains are likely to be small here, since Images are needed in most of the major workflows in the app.
> M3-3963 [Performance] Images Redux load

- packages/manager/src/features/Domains/DomainRecords.tsx
- packages/manager/src/features/Domains/domainUtils.test.ts
- packages/manager/src/features/Domains/domainUtils.ts
A follow-up to #6224. This PR stores the regex pattern in a const and adds unit testing.
`yarn test domainUtils.test.ts`
> M3-4054: Edit DNS Records containing "linode.com" substring in NS, Pt. 2

- packages/manager/src/components/TableRowLoading/TableRowLoading.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
Previously the skeleton loaders on the EventsLanding page were questionable at best:
The EventsLanding table has 4 columns, but one of them is used for the entity icon, so to the user it appears like there's only 3 columns.
We still want the TableRowLoading component to span 4 columns, but we only want to show 3 skeleton loaders. Previously, `colSpan` was overloaded in the sense that it handled both of these things. Now, `colSpan` can be used as intended and `numberOfColumns` can be used to specify the number of skeleton loaders.
If `numberOfColumns` is NOT provided but `colSpan` IS provided, we use `colSpan` for both purposes, like it was previously.
> M3-4088: Fix skeleton loader on EventsLanding

- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.tsx
This PR allows the consumer of `<EventsLanding />` to specify a message to display in the empty state. This means the Activity tab of Linode Details can say "No recent activity for this Linode." instead of "No events on your account".
Also, `<EventsLanding />` now takes into account the number of events when determining whether to display "No more events to show." 
DM for an example of a Linode with no recent events. Additionally, please check the Events Landing page (http://localhost:3000/events) in different states.
> M3-4089: Allow custom empty messaging on EventsLanding

- packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
- packages/manager/src/components/CheckoutBar/DisplaySection.tsx
- packages/manager/src/components/CheckoutBar/DisplaySectionList.tsx
- packages/manager/src/components/CheckoutBar/index.ts
- packages/manager/src/components/CheckoutBar/styles.ts
- packages/manager/src/features/Kubernetes/KubeCheckoutBar.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
The designs for updated LKE call for a more flexible checkout bar than we've used in the past, but since this is used elsewhere it's important to maintain consistency, styling, etc. I refactored the existing CheckoutBar component to render props.children instead of a list of display sections. I provided an additional DisplaySectionList component to make the original use case easier, since that's what everything has used up to this point.
Nothing LKE-specific has been changed; this PR just re-creates the existing functionality using a slightly different pattern. Checkout bars are found wherever users create something that will cost $; please check that Linode, NodeBalancer, K8s cluster, and Volume creation are unchanged.
> [LKE] Refactor Checkout bar

- packages/manager/src/layouts/OAuth.tsx
- packages/manager/src/utilities/queryParams.ts
Query params from returnTo urls were being lost, so a user trying to
visit cloud.linode.com/linodes/create?type=One-Click&appID=401719&showInfo=true
without being logged in would end up at cloud.linode.com/linodes/create?type=One-Click after completing the login process.
This is due to how parsers such as qs interpret query strings containing
URLs that themselves contain query params. We were ending up with an object
like:
```
{
access_token:
'0d025eaa329b643032b7a4905f145d70410e186a713b121cd87646a674084e1b',
token_type: 'bearer',
expires_in: '7200',
scope: '*',
state: '83388bfa-207f-4ea9-a1c5-8653750b721b',
return:
'http://localhost:3000/oauth/callback?returnTo=/linodes/create?type=One-Click',
appID: '401719',
showInfo: 'true'
}
```
Other approaches like new UrlSearchParams() had the …
> Fix query param parsing

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
Data was being given to the graph in bytes, but not converted to bits before being passed to `convertNetworkToUnit`, (which accepts bits).
Test acct 4 has a LV client named "nginx-working". Compare the Network graphs to Classic, and make sure the tooltip values/units align with the graph.
> Convert values on LV Network graphs

- packages/manager/src/utilities/sanitize-html/sanitize-html.test.ts
Original discussion here: https://github.com/linode/manager/pull/6227 ... @Jskobos this is pretty much what you suggested. 😆 
I still think it's valuable to have these three tests, which confirm:
- We're escaping non-whitelisted tags.
- We're stripping non-whitelisted attributes.
- We're stripping invalid "href" values.
The specific string tests have been removed, as they are noisy and probably fall in the category of "testing the library". With these basic tests I'm proposing, we verify that sanitization is working, and not much else about implementation.
> Basic sanity tests for sanitizeHTML

- packages/manager/src/__data__/types.ts
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/index.tsx
- packages/manager/src/features/Kubernetes/kubeUtils.ts
- packages/manager/src/features/linodes/presentation.ts
- packages/manager/src/hooks/useTypes.ts
Drawer for resizing node pools. To avoid conflicts, I've avoided doing any of the logic to add this component to the details view. Instead, I added a dummy drawer to ClusterDetails that I'll delete before merge. Then I can follow-up after #6251 is merged (since that's where the action to open this drawer will live).
> M3-4063 Add: Resize Node Pool Drawer

- packages/manager/src/components/H1Header/H1Header.tsx
- packages/manager/src/components/Placeholder/Placeholder.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/Volumes/VolumesLanding.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
Currently there are states within the app where a double h1 could occur (ex. landing pages that are empty). To fix, we added a new prop to render the Placeholder title as an h2 instead of an h1 as needed. There should be no visual impact, but the output will now be semantically correct.
> Placeholder A11y Improvement: add component prop

- packages/manager/package.json
- yarn.lock
Merging PR to fix peer dep on cypress-axe https://github.com/avanslaars/cypress-axe/pull/26
Incidentally, updated the lockfile that had incorrect entries on sanitize-html
> upgrade cypress axe to remove warning of peer dependency

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
- packages/manager/src/features/Longview/shared/utilities.ts
A user reported that their NGINX tab in Longview was crashing.
This is due to a badly malformed response from the Longview API.
Classic Manager's Longview client handled for this case but did
not display data for the malformed request (probably a try/catch somewhere).
It turns out the crash was because we weren't manually type checking
the arguments to appendStats() in longview/shared/utilities. The bad
request was sending an array rather than an object to that method
and Object.keys().reduce() was crashing. Added an isArray() check
to prevent this.
We actually display data in this case, though it can't possibly be
entirely accurate since the "bad" data is being ignored. I'm not sure
whether the best thing to do is check the shape higher up and blank
out the graphs if the shape doesn't …
> M3-4048 Fix Longview NGINX bug

- packages/manager/src/layouts/Logout.tsx
- packages/manager/src/store/authentication/authentication.actions.ts
- packages/manager/src/store/authentication/authentication.reducer.ts
I originally thought that handleLogout was called on manual logout, and
handleExpireTokens was called when a user's tokens had expired. On closer
inspection, I realized that handleExpireTokens was never called at all.
This meant that the original case the localStorage cache of support
tickets was intended to solve wouldn't actually work, since when the
user is redirected to Login the values are cleared. To resolve this,
I deleted the unused refreshTokens action and instead cleared localStorage
from inside the Logout component, which is the actual logic triggered uniquely
when a user clicks the logout button.
> Fix handling of local storage on logout

- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
This in theory fixes a unreproducible bug in which loading the PayPal script fails, but `react-async-script-loader` thinks it was loaded successfully. If that happens, the app will crash because we try to use `window.paypal`, which is `undefined` unless the actual PayPal script is loaded correctly.
We've heard a report of this happening, and I believe it had to do with blocked pages in the user's network configuration. In this case, the PayPal script was routed through a filter, which returned a 200 but without the correct content.
With this fix, if something like the above happens, PayPal will simply not appear as a payment option (instead of the app crashing). This is already what happens is PayPal isn't loaded correctly, i.e. we have no true error for this (maybe should address later). …
> Make sure window.paypal is defined before using it (fixes crash)

- packages/manager/src/exceptionReporting.ts
This PR stops reporting a few errors to Sentry:
- Flow Control xterm errors (we know we need to address this, no reason to keep reporting them)
- Safari and Chrome extensions
- MUI touch Ripple error (see discussion here: https://github.com/mui-org/material-ui/issues/16841
> More Sentry improvements

- packages/manager/package.json
Tests are run on Travis builds (and/or in Baker), we can rely on that instead. Devs can also run the tests locally before pushing if they have doubts.
> Don't run unit tests pre-push

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- Added a Notice to display errorMap.none (general error)
- Adjusted the updateFor dependencies in the checkout bar. This
fixes a bug introduced by the conversion to an FC. The functions
are no longer instance methods, so they change to reflect current
component state. Since the checkoutBar wasn't listening for changes
to these functions, when submitted older versions of the functions
were called with old state.
Example:
1. Fill in Region and Version but don't add node pools
2. Submit the form
3. Observe: field errors are displayed for both version and node pools,
even though version is correct.
I considered removing renderGuard from the components in this form,
but that actually slows down the form significantly. I think the ideal
thing is a bunch of React.memo and React.useCallback, but …
> LKE Fix: Create cluster bug

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
It felt weird to see the "Use our speedtest page to find the best region for you" message if there was only 1 region.
> LKE – hide region helper text if only one region

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
Follow-up to https://github.com/linode/manager/pull/6284.
Selects the first region by default is there is only one to choose from.
> [LKE] Create Cluster – select region by default

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
The AppBar on the K8 Details page was competing with the Add New Menu's zindex. Wrapping AppBar in a grid element resolves this issue.
- Bug fix ('fix'')
> LKE Details & Add New Menu z-index issue

- packages/manager/src/store/events/event.request.ts
- packages/manager/src/utilities/requestFilters.test.ts
- packages/manager/src/utilities/requestFilters.ts
In the new LKE Node Pool display, I noticed that after creating a new cluster the Node Rows weren’t always updated with the Linode’s status once provisioned. A few of the nodes might be displayed as "Powered off", even though the Linodes were running.
After studying the polled requests to `/events` during this sequence, I realized this was happening because _we weren't receiving all events from the API_. And if we don’t receive a completed `linode_boot` event, for example, we don’t update the Linode’s status. 
**So why aren’t we receiving all events from the API?** A little context on how we poll `/events`...
When we receive a batch of events, we find the most recent `created` time. We use that timestamp in a filter like this: 
```
{ "created": { "+gt": <mostRecentCreatedTime> } }
``` …
> Adjust events polling filter to handle edge case

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
KubeSummaryPanel.tsx previously had the "CPU Cores" phrase explicitly written in instead of being singular or plural based on the total CPUs value of the cluster. I brought in the `pluralize` util to remedy this, so it should now say "1 CPU Core" when there is only one, and "[2, 3, etc.] CPU Cores" when there are multiple. 
> [LKE] Fix Summary Panel's "CPU Cores" pluralization based on number of cores

- packages/linode-js-sdk/src/kubernetes/kubernetes.schema.ts
- packages/linode-js-sdk/src/kubernetes/types.ts
- packages/manager/src/__data__/kubernetes.ts
- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.test.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
The API is changing the Kubernetes cluster schema such that version is now
k8s_version. This will break our creation flow and display unless we make
a matching change.
> Hotfix: Change version to k8s_version

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
We had logic to automatically select the region field if there
was only one available region. However, we were only pre-populating
the field and not setting the region to state. This fixes it and memoizes
the filteredRegions calculation to support it.
> LKE Fix: Autoselect region

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
This is a follow-up to https://github.com/linode/manager/pull/6272 that does some minor clean-up and addresses two bigger issues:  the brief delay in transition from the "Provisioning" view when a user clicks into an existing cluster, and the unavailability of the Kubeconfig for download although the download links are shown.
- The checks for the availability of the endpoint and kubeconfig were decoupled. This allows for the "Provisioning" view to show only when the endpoint is available, but the kubeconfig is not yet ready. 
- `kubeconfigAvailable` now defaults to true, and is set to false if the `getKubeConfig` request fails. This is to stop the "Provisioning" screen from displaying when a user clicks into an existing cluster.
- The default initial view is now "Loading..." -- when a …
> M3-4059 [LKE]: Logic clean-up for "Provisioning" view of Detail Summary

- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
- The "Add" button is now disabled only if that row's count < 1.
- Adding a pool resets that row's count to 0.
Also:
- Removed unnecessary useEffect which sometimes caused an bug where the first click of the "Plus" button didn't do anything.
- Removed a state value and updater that AFAICT were not being used.
> [LKE] Adjustments to create cluster component

- packages/manager/src/factories/kubernetesCluster.ts
A test in ResizeNodePoolDrawer was failing randomly. Turns it, it actually was random! The Node Pool factory randomized "count", and if "count" was 0, the test would fail.
> [LKE] Fix failing test

- packages/linode-js-sdk/src/kubernetes/kubernetes.schema.ts
- packages/linode-js-sdk/src/kubernetes/kubernetes.ts
- packages/linode-js-sdk/src/kubernetes/types.ts
- packages/manager/src/__data__/kubernetes.ts
- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.test.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/utilities/getAll.ts
We did it for the old UI, now we have to do it for the new UI. LKE should function as before, despite the following API changes:
- /api-endpoint is now /api-endpoints, and returns a standard paginated response.
- k8s clusters "version" field has been renamed k8s_version, for both request and response payloads.
Point your env at staging.
> LKE: API updates

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeActionMenu.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
- packages/manager/src/hooks/useLinodes.ts
This PR adds the Action Menu for the Node table, with a "Delete" action.
- Add "deleteLinode" to the `useLinodes` hook. 
- Rename the existing pool deletion dialog to `deletePoolDialog`.
- Add new dialog for node deletion called `deleteNodeDialog`.
I thought about using the existing `<DeleteDialog />` component (used for Linodes), but I wanted to keep the pattern consistent with the other deletion dialog (for Node Pools). Plus, it's possible we'll want to change the messaging of this dialog (but for now I reused the text from `<DeleteDialog />`
Try deleting some nodes on an LKE cluster. Success/Failure/Loading states should all work correctly.
> [LKE] Node Table action menu

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
Looks like this class was lost here: https://github.com/linode/manager/pull/6295/files#diff-86d0256904fe6812859a8e7f376682f9R147
This made this column too wide.
> Fix SelectPlanPanel visual regression

- packages/linode-js-sdk/src/kubernetes/types.ts
- packages/manager/src/__data__/kubernetes.ts
- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Search/SearchLanding.test.tsx
- packages/manager/src/features/Search/SearchLanding.tsx
- packages/manager/src/features/Search/search.interfaces.ts
- packages/manager/src/features/Search/utils.test.ts
- packages/manager/src/features/Search/utils.ts
- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/store/selectors/entitiesErrors.ts
- packages/manager/src/store/selectors/getSearchEntities.ts
- packages/manager/src/store/selectors/getSearchEntitites.test.ts
Previously Kubernetes Clusters were not searchable in our search bar. Now that we're going to support tags, we need clusters to be searchable (clicking on a tag takes you to the search results landing page).
Also updated the KubernetesCluster type to include `tags[]` and `updated`.
To test: make sure everything with search still function. Search bar, search landing, failure scenarios, etc.
> Add LKE as searchable entity

- packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.stories.tsx
- packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.test.tsx
- packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx
- packages/manager/src/features/Kubernetes/KubeCheckoutBar/NodePoolSummary.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.tsx
The min in the Resize drawer needed to be `1`, otherwise you could do this:
I added max and min props to EnhancedNumberInput and added `min={1}` in the Resize drawer. I also updated pluralization for the copy (to fix "1 nodes").
TODO: 
Please check the create flow works as expected as well. Now, the increment button will be disabled if the value is `100` (@Jskobos mentioned this was the upper limit).
> [for release] Add min/max on EnhancedNumberInput

- packages/manager/src/components/Table/Table.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
When the Recent Invoices section wraps for smaller screens, the Date Created section on the right was misaligned so this should fix that
> M3-4041: Fix alignment on invoice labels

- packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
Disable the LKE "Create Cluster" button when there are no Node Pools added.
> [LKE] Disable "Create Cluster" button unless at least 1 Node Pool has been added

- packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/TheApplicationIsOnFire.tsx
We received reports of users with very old NodeBalancers being unable
to edit their configs. Spaces used to be permitted in NB labels,
but have since been restricted in both Classic and the API.
I wasn't able to reproduce the specific issue described, even when
creating a NB with an illegal name in devenv; however, I did find
that our error handling for the editable breadcrumb was incomplete.
I fixed this, added a general error Notice (don't know how that would
happen but just in case), and used the errorMap pattern instead of
the older getErrorFor.
If you want to check the case described in the ticket, you'll have to use Devenv and set up a NodeBalancer with an illegal name. As mentioned above, even after doing this I was unable to reproduce the issue, which in any case would only apply …
> M3-3972 Update: NodeBalancer error handling

- packages/manager/src/features/Users/UserPermissions.tsx
I wasn't able to reproduce the issue described in this ticket. I pinged Adrien and we can probably close it out or refer it to ARB. I did find that we're not clearing errors on the UserPermissions form on submit, so I did that here.
> Clear permissions errors on form submit

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.tsx
Little bit of overzealous copy-pasting caused a problem here. Only the Resized Pool: display should update when toggling the number input.
> Use nodePool.count instead of updated count for displaying current pool

- packages/manager/src/App.tsx
- packages/manager/src/IdentifyUser.tsx
Previously there was a bug where the `initGTMUser()` function would not fire if the `/account` endpoint was slower than the component was rendered.
To fix this, I moved the `initGTMUser()` invocation to the `<IdentifyUser />` component. 
I also moved the `configureErrorReportingUser()` invocation, which could theoretically be suffering the same bug.
To reproduce the bug, throw in some console.log statements around this functions and add a breakpoint on on `/account`. You'll see that `initGTMUser()` isn't called because the euuid isn't available in cDM.
> Move identify user functions to fix race condition

- packages/manager/src/components/CheckoutBar/CheckoutBar.tsx
- packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
Follow-up to https://github.com/linode/manager/pull/6322.
Added a data-testid attribute to the Button in `CheckoutBar` component and a unit test to make sure the button is disabled when zero Node Pools have been added by user.
`yarn test KubeCheckoutBar.tsx`
> [LKE] Unit test for "Create Cluster" button being disabled when 0 Node Pools added

- packages/manager/cypress/integration/nodebalancers/smoke-create-nodebal.spec.js
- packages/manager/cypress/support/api/linodes.js
- packages/manager/cypress/support/api/nodebalancers.js
- packages/manager/cypress/support/index.js
I would like to add some e2e test to cover NodeBalancers,
This PR aims at throwing some base code for testing creation, clean up nodebal test resources etc.
It checks:
- no error (should succeed)
- bad label error displayed (on validation of the form)
- bad stickiness for tcp is displayed (on API response)
when running the e2e tests, normally i wait for the linode to be created and the nodebal to be created before deletion so hopefully no race issue here
About the re-rendering/detached element, we should have no rerendering issue here hopefully, 
The list of Private IPs available is populated based on the region, so IF the data for this was missing, would we have an error?
=> probably not as i type the IP directly.
> Basic e2e smoke create nodebal

- packages/manager/src/LinodeThemeWrapper.tsx
- packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
- packages/manager/src/components/LineGraph/MetricsDisplay.test.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
- packages/manager/src/components/PrimaryNav/ThemeToggle.test.tsx
- packages/manager/src/components/RenderGuard.tsx
- packages/manager/src/features/Dashboard/Dashboard.test.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewPlans.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
- packages/manager/src/themes.ts
- packages/manager/src/utilities/storybookDecorators.tsx
This PR does two things: 
- Memoizes safelyGetTheme in PreferenceToggle so that createTheme isn't called repeatedly.
- Improves markup by not passing the theme object to every component wrapped in RenderGuard (that's why we were getting `<div theme="[object Object]" />` throughout the markup).
I've tried to run some benchmarks but haven't produced anything that proves performance is actually better. It _feels_ snappier to me, but the placebo effect is powerful, so I'm taking that with a grain of salt. I'm curious to know you're experience.
**Note:** many of the line changes are the result of moving the dark theme options to a variable.
In any case, the markup is cleaner this way, and we demonstrably save some JavaScript cycles by not calling the createTheme methods with almost every …
> Theme performance optimizations

- packages/linode-js-sdk/src/kubernetes/kubernetes.ts
- packages/linode-js-sdk/src/kubernetes/nodePools.ts
- packages/manager/src/App.tsx
- packages/manager/src/MainContent.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/utilities/accountCapabilities.test.ts
- packages/manager/src/utilities/accountCapabilities.ts
- Use the normal api root instead of beta for LKE methods in the SDK
- Remove conditional rendering of LKE routes and views
- Remove isObj & isKube enabled methods from accountCapabilities
- Refactor accountCapabilities.test to test the exported generic function
rather than the (deleted) OBJ-specific method.
To test: make sure LKE is working as before.
> Update LKE endpoint and capabilities

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/store/bucket/bucket.requests.ts
The getAllBucketsForAllClusters `done` action was only dispatched if data.length > 0, which meant that if you didn't have any buckets, you'd see an eternal loading spinner on the BucketsLanding page.
I also realized another issue, which is that if you only have buckets in Newark, and the Newark request fails, you'll see the "Empty" state, without an error message. I abstracted the error display out to its own component and include it in the main content as well as the "Empty" state.
Try to test all combinations:
- No buckets
- No buckets with partial failure (block requests to one DC)
- No buckets with complete failure (block requests to all DCs)
- 1 bucket
- 1 bucket with partial failure 
... etc
> [for release] Fix issue loading spinner when bucket data == 0

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
- packages/manager/src/themeFactory.ts
- Removed the `width` to fix the coloring
- Added `borderBottom` to fix the large border injected with the Mui Table Cell Root class.
> [for release] FW Rule table visual regression

- packages/manager/src/themeFactory.ts
Removing width from empty table cell styles. I checked to ensure this fixes the issue as well as still keeping the original fix (height not expanding to match other table header cells) and it seems to work well, but please check various tables with empty cells present.
> [For Release]: Removing width from empty table cell styles

- TESTING.md
- package.json
- packages/manager/config/development.example.json
- packages/manager/cypress/integration/smoke-axe.spec.js
- packages/manager/cypress/integration/smoke-deep-link.spec.js
- packages/manager/cypress/plugins/index.js
- packages/manager/cypress/support/api/common.js
- packages/manager/cypress/support/api/linodes.js
- packages/manager/cypress/support/commands.js
- packages/manager/cypress/support/login.js
- packages/manager/package.json
- packages/manager/scripts/start.js
Removes need for development.json file
Uses `.env` instead.
To use e2e with staging change `.env`, and restart `yarn up`
delete or Rename your `development.json` file for cypress, restart `yarn up` the dev server should still work without it.
The e2e test with cypress should also work.
Also remove need for `cy:stage` type of command
> Cypress uses .env, no independant json file anymore

- packages/manager/src/containers/kubernetes.container.ts
- packages/manager/src/hooks/useEntities.ts
- packages/manager/src/store/domains/domains.reducer.ts
- packages/manager/src/store/kubernetes/kubernetes.actions.ts
- packages/manager/src/store/kubernetes/kubernetes.reducer.test.ts
- packages/manager/src/store/kubernetes/kubernetes.reducer.ts
- packages/manager/src/store/kubernetes/kubernetes.requests.ts
- packages/manager/src/store/selectors/getSearchEntities.ts
- packages/manager/src/store/selectors/getSearchEntitites.test.ts
- packages/manager/src/store/store.helpers.tmp.ts
- packages/manager/src/utilities/getEntityByIDFromStore.ts
We're in the process of updating our reducers so that they use the
same set of helper methods/actions/data shape (where possible). This
brings LKE up to date with our patterns. The behavior of the app should
be unchanged.
> Refactor LKE Redux to use MappedEntityState2

- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/MakeAPaymentPanel/MakeAPaymentPanel.tsx
We show "5.00 minimum" in the number input for choosing a payment amount.
We do this under all conditions, even though the API will accept a smaller
payment if the balance is greater than 0 but less than 5. Our placeholder
has confused a few customers with small balances, who didn't think
it was possible to only pay their balance.
Paypal (I think) always requires a minimum of $5. For all other payments
we follow the API's validation logic.
To test:
You'll have to use admin (dev admin is probably best, reach out if you need help) to invoice yourself for various amounts. dev test account #4 currently has a $1.50 balance, so you can use that to get started. The API's validation logic is explained in the ticket (and in the code comments here).
> M3-4136 Update: Minimum payment placeholder text

- packages/manager/src/features/Account/GlobalSettings.tsx
- packages/manager/src/features/Dashboard/Dashboard.tsx
- Remove some dead code (the tagimport drawer was still on the Dashboard
even though we no longer included logic to open it)
- Refactor GlobalSettings to a function component to use useReduxLoad.
There's a small bug post-performance refactor where if you have a group
on your Domains that should trigger showing the "Import Groups as Tags"
CTA on the Global Settings view, but you navigate directly to that page,
you don't see the CTA (Domains haven't been requested yet).
To test the bug:
1. Use the API or classic to add a "group" to one of your Domains
2. Go to /account/settings/. Depending on where you came from, you may see a CTA to import your group as a tag.
3. Reload the page. 
4. Observe: the CTA is not displayed (because Domains have not yet been requested).
> M3-3950 Fix and clean Import Groups as Tags logic

- packages/linode-js-sdk/package.json
Simply add the peer dep eslint in the `package.json` of the SDK.
This was already in manager, so it does not impact the lockfile
Before when running `yarn install:all` this warning shows, with this fix, this warning should be gone
> fix eslint peer dependancy wrning from eslint-plugin-sonarjs in sdk

- packages/manager/package.json
- Removed `tsc` from `lint-staged` because you can't pass a `--project` as well as file name arguments. Add to `precommit` instead.
- Removed `git add` which was causing this warning: `Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.`
I've verified that does PR does the following on commit:
- Compiles `.ts` files
- Compiles `.tsx` files
- Writes prettier changes
> Adjustments to precommit/tsc

- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptsSection.tsx
Fix bug when deleting a StackScript:
1. Scroll down past the waypoint and delete one of the stackscripts there.
2. Observe: you are redirected to the top of the page, but are unable
to trigger infinite scroll.
This happened because the delete handler was requesting the first page
of data (correctly) but wasn't updating the current page in state.
Fix error and loading handling when deleting:
There were no submitting states for the confirmation dialogs. Added one
for the delete dialog. In addition, the "fieldError" in state wasn't displayed
anywhere, and in any case it's our pattern to display errors like this inside
the confirmation dialog. Adjusted the dialog state and props to account for this.
Prod test account 4 has a bunch of StackScripts on it, enough to trigger infinite scroll. …
> M3-4150 Fix: StackScripts bugs

- packages/linode-js-sdk/src/nodebalancers/nodebalancers.schema.ts
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/linodes/LinodeSelect/LinodeSelect.tsx
- packages/manager/src/utilities/errorUtils.ts
This is a similar ticket to our recent attempts to fix error handling in NBs. In this case a customer was unable to update his SSL cert and key. I'm not able to reproduce this, and it's possible our earlier fixes took care of this too. To be safe, I made a few extra changes that might catch errors we're not accounting for, but it's hard to be sure. See my longer comment in the ticket.
- Linter fixes
- Resolve duplicate id errors (includes adding inputId prop to a few components and passing down to the underlying TextField)
- Extracted NodeBalancerConfigNode to a separate component. It's too hard to reason about all the updateFors and errorMaps and subrenders when everything is in a single file. Ideally there would be a bunch of React.memo'd components with explicit error fields.
The …
> M3-4146 Fix: NodeBalancer Error Handling (SSL)

- packages/manager/src/factories/account.ts
- packages/manager/src/store/account/account.actions.ts
- packages/manager/src/store/account/account.reducer.ts
- packages/manager/src/store/account/account.requests.test.ts
- packages/manager/src/store/account/account.requests.ts
A DB snafu resulted in some active_promotions with an expiry of null. This is invalid, since by definition an expiring credit must expire. Admin and billing ignore these credits (which are erased already btw), but we show them, resulting in a few confused customers who saw "ghost" credits being applied to their bills instead of the actual credits they were enrolled in.
This is unlikely to happen again, but to be safe we're stripping out anything with an expire_dt of `null`. I did this in account.requests for convenience, since we read promos in several places. I did a small refactor of the account Redux jawn (which I swear I remember doing 6 months ago) while I was at it.
~I'm working on an easier way to test this. For now, test account 4 has a valid promo code on it. You can use Charles …
> M3-4040 Fix: Remove invalid credits

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
- packages/manager/src/features/Kubernetes/kubeUtils.ts
- packages/manager/src/store/selectors/getSearchEntities.ts
- packages/manager/src/store/selectors/getSearchEntitites.test.ts
Added a "description" field for LKE cluster search results.
Roughly matches what we show for Linodes, in this case the total
node count, CPU count, and RAM count for the cluster. Added a
getDescriptionForCluster method to kubeUtils.ts to provide this description.
> M3-4144 Add LKE search results details

- packages/manager/src/components/Currency/Currency.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/BillingSection.test.tsx
- packages/manager/src/utilities/testHelpers.tsx
Funny ticket/situation. A user asked Support for a refund because the price of his Linode was "$0" when he pressed create. This was due to how Google Translate parses our currency component. I'm not sure why it's just this component (tried both before and after John's changes, as well as just sending a raw number). But according to:
https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website
...this is the Google-recommended solution.
Adding this to the feature branch and not develop because this is what the Currency component is going to look like in the future, so it's best to make sure it works on the new version.
Add the Google Translate extension to Chrome, go to the Linode create page, and choose "Translate Page" (This user was …
> M3-3678 Fix: Google Translate not translating Currency component correctly

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/features/Lish/Weblish.tsx
We were receiving Sentry reports of xterm.js reaching its flow
control limit and discarding write data. After talking with Abe,
this is a normal thing and an appropriate way to handle it. Since
the underlying screen session has a log, no data is actually lost.
I've been unable to replicate this effect (Abe suggested cat /dev/urandom
but that doesn't trigger it). He suggested that we do what they've
previously done for Glish, which is reload the Lish window when one
of these errors occurs. This will bring the window back in sync with
the screen session.
I also moved the events polling initialization so that it doesn't happen when the user
is loading Lish. There's no reason to poll events from inside a Lish console.
> M3-3798 Address Xterm flow control errors

- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
- packages/manager/src/utilities/date.ts
This PR adds functionality to the "Transaction Type" and "Transaction Date" inputs.
Transaction Type is filtered entirely client-side. Transaction Date is filtered on with a combo of API/client-side filtering:
1. Default is "6 Months", so we only request invoices/payments from the last 6 months.
2. If a user selects a range smaller than 6 months (e.g. 30 days) we don't fetch more data, but we filter out items with dates greater than 30 days.
3. If a user selects a larger range (e.g. 12 months), we re-fetch all data for the last 12 months.
There's an additional optimization that could be made, which is that in step 3 above, it's only actually necessary to fetch invoices/payments from the time of the last invoice/payment to the date cutoff of 12 months. However, This would significantly …
> [Billing] Billing and Payment history filtering

- packages/manager/.eslintrc.js
We originally had this rule, then got into a debate over whether it was helpful. The official React docs use lambdas in their examples, we've never observed a performance impact, and in many cases the stuff we had to do to resolve the warning was weird. The verdict at the time was to remove the rule, and as a result we now have dozens or hundreds of lambda functions in our renders. 
I'm open to more performance testing to determine if this is after all something worth fixing (in theory since we now have the useCallback hook it would be possible to wrap all of these things, although that introduces its own overhead), but in the meantime this falls into the category of things that we're not going to fix immediately, so the warnings will clutter up the linter output.
> Remove no-lambda rule

- packages/manager/src/components/Placeholder/Placeholder.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/hooks/useObjectStorageBuckets.ts
- packages/manager/src/hooks/useObjectStorageClusters.ts
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/store/bucket/bucket.reducer.ts
- packages/manager/src/store/bucket/bucket.requests.test.ts
- packages/manager/src/store/bucket/bucket.requests.ts
- packages/manager/src/store/clusters/clusters.actions.ts
- packages/manager/src/store/clusters/clusters.reducer.ts
- packages/manager/src/store/index.ts
- packages/manager/src/utilities/testHelpers.tsx
In https://github.com/linode/manager/pull/6269 I chose to use the hard-coded list of clusters to make bucket requests. One thing I hadn't considered is that this would break non-prod environments. 
In this PR, the behavior is changed such that the list of clusters is requested first, before making buckets requests. This wasn't just to fix the present issue; I decided that if this has _already_ bitten us, better to go the safe route, The /object-storage/clusters endpoint is pretty fast, too, so it's not a huge performance penalty.
Also some misc. items in this PR:
- Add `useObjectStorageBuckets()` and `useObjectStorageBuckets()` entity hooks.
- Resolve some ESLint warnings.
- Get rid of the containers in ObjectStorageLanding in favor of hooks.
- Rewrite ObjectStorageLanding tests to use …
> Reorganize OBJ Bucket request to fix other environments

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
Remove stray semicolon from Object Storage landing page
> [For Release]: Remove semicolon from Object Storage landing page

- packages/manager/src/features/Dashboard/ManagedDashboardCard/MonitorTickets.tsx
Since support is not referring to the team, it should be lowercase.
> M3-4157: Change 'S' in support tickets on the managed dashboard to lowercase

- packages/manager/src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.test.tsx
- packages/manager/src/features/Dashboard/BackupsDashboardCard/BackupsDashboardCard.tsx
- packages/manager/src/features/Dashboard/Dashboard.test.tsx
- packages/manager/src/features/Dashboard/Dashboard.tsx
This is mostly future-proofing, since atm the app stays at the
splash screen until Linodes are loaded.
Adds loading state and useReduxLoad to BackupsDashboardCard.
Adds some accessibility props to a button to resolve linter warnings.
> M3-3954 Lazy load Linodes on BackupsDashboardCard

- packages/manager/src/components/Paginate.ts
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
This adds a `shouldScroll` option/prop to the `<Paginate />` component. The context the scrolling was bothering me in is the new Billing Activity feed, so that's the only place shouldScroll=false. Prod test account 1 has multiple pages of items so you can test it there.
> Ability to disable Paginate scroll

- packages/manager/src/formatted-text.css
- packages/manager/src/utilities/getVersionString.test.ts
- packages/manager/src/utilities/getVersionString.ts
In https://github.com/linode/manager/pull/5355, HTML was added to the version string. I believe this was done so that it could be targeted for styling.
We actually lost the styling in a recent update to the markdown conversion anyway (by not allowing classes). 
This PR removes the HTML (which was showing up in emails) and targets the last `<p>` of `.formatted-text` and applies the styling that was intended.
Test new and old support tickets.
> M3-4176 Remove HTML from version string

- packages/linode-js-sdk/src/domains/types.ts
- packages/manager/src/__data__/domains.ts
- packages/manager/src/factories/domain.ts
- packages/manager/src/features/Domains/DomainTableRow.tsx
- packages/manager/src/features/Domains/ListDomains.tsx
- packages/manager/src/features/Domains/ListGroupedDomains.tsx
- packages/manager/src/features/Domains/SortableTableHead.tsx
- packages/manager/src/store/selectors/getEntitiesWithGroupsToImport.test.tsx
In the Classic Manager, users were able to see a "Last Modified" date for each domain on the DNS Manager page. This information is not currently shown in Cloud.
This PR brings that information into the Domains landing page with a new "Last Modified" column.
> M3-3776: Add 'Last Modified' column to Domains landing page

- packages/manager/src/components/EnhancedSelect/Select.tsx
When upgrading React-Select, we missed this: https://github.com/JedWatson/react-select/pull/3416
To reproduce the bug: 
1. Go to https://cloud.linode.com/volumes/create
2. Select a Tag
3. Click "X". 
4. Observe: the page crashes.
This PR basically reverts the change React-Select made. The other option is to rewrite the handlers of components that use `isMulti` Selects. (Maybe better in the long term but bigger lift).
> M3-4180 Fix isMulti Selects 

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
- packages/manager/src/features/Support/SupportTickets/TicketList.tsx
- packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
- packages/manager/src/features/linodes/CloneLanding/Configs.tsx
- packages/manager/src/features/linodes/CloneLanding/Disks.tsx
Refactoring to use Reach UI Tabs for LKE Details, Support Tickets landing, and Linode Clone landing. Ticket landing and LKE details are outliers from the other patterns, as neither TabbedPanel nor linked tab work for these particular cases. Instead, we're following the convention as described by Reach.
> Tab Refactor: LKE Details, Support Tickets Landing, Linode Clone Landing 

- packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx
This is another one of those bugs that we haven't been able to reproduce (this one was reported by a single user on an older version of Firefox). We know the line of code that was causing the crash, and I've updated it to be as safe as I can make it.
Please check that syntax highlighting still works (in Support tickets and LKE kubeconfig view).
> M3-4161 Fix: Safe access ref

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/components/SplashScreen/SplashScreen.tsx
- packages/manager/src/index.tsx
This is an older ticket that's mostly already been completed. Taking it as an opportunity to separate out the requests that are urgent (can't load the app without them) and those that are needed for all users but don't block anything.
The number of requests made on app load should be unchanged by this PR. The new-ish flow is:
1. App begins load; users see splash screen
2. Initial requests are made (account, profile, etc.)
3. Initial requests complete; app is marked as done
4. As splash screen goes away, secondary requests (Linodes, types, regions) are kicked off
> M3-3960 Change: Initial vs. secondary requests

- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Default to what was previously "None/General" when creating a Support Ticket. Also re-label "None/General" to "General/Account/Billing"
> Default support ticket option to 'General'

- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/ContactInformation.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/PanelCards/EditBillingContactDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/SummaryPanel/SummaryPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationForm.tsx
- packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/UpdateContactInformationPanel.tsx
- packages/manager/src/features/Billing/BillingPanels/UpdateContactInformationPanel/index.ts
This moves the editing of Billing Contact Info into a drawer instead of an expansion panel
To-Dos:
> [Billing] M3-4109: Edit Billing Contact Info (Panel and Drawer)

- packages/manager/src/components/PrimaryNav/NavItem.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav.test.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/PrimaryNav/utils.ts
- packages/manager/src/hooks/useAccountManagement.ts
- packages/manager/src/utilities/routing/isPathOneOf.ts
This is a refactor of the PrimaryNav, which was a bit of a mess. This is the first part of M3-3964 (prefetch entities on hover) and I wanted to use some of our hooks, hence the refactor as a FunctionComponent.
I also hope that this cleans things up such that the re-working of the nav for CMR will be more straightforward.
Also new:
- Brand new tests for PrimaryNav with RTL.
- useAccountManagement hook. Often data is needed that is derived from account, profile, and/or settings. This hook conveniently bundles them together, along with a few pieces of derived data. Better name welcome.
The diff is pretty horrible, sorry.
This is a refactor – nothing should be different to the user. So please check all states (mobile, expanded), different browsers, etc.
> M3-3964 Part 1: Refactor PrimaryNav as FC

- packages/manager/src/features/Support/ExpandableTicketPanel.test.tsx
- packages/manager/src/features/Support/ExpandableTicketPanel.tsx
- packages/manager/src/formatted-text.css
- packages/manager/src/utilities/getVersionString.ts
- packages/manager/src/utilities/sanitize-html/sanitize-html.test.ts
- packages/manager/src/utilities/sanitize-html/sanitizeHTML.ts
My solution to this issue in https://github.com/linode/manager/pull/6397 overshot a bit. There, I applied the CSS to the last "p" element of a Support Ticket. That's a problem though, since not everything has the version string attached (replies, subsequent updates, tickets opened by Linode).
This inserts a "span" with a class for the CSS to select on.
If you have a less-bad solution in mind, I'm all ears 🙂 
Please check new tickets, old tickets, ticket replies, etc.
> HTML in support tickets [again]

- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Previously, an image is required in order display SSH keys in the "Create Linode" flow. The reason the SSH keys were showing up in the table for some flows but not others is because a default image was selected for the user. This logic might have been leftover from the past but there is no need for this anymore so I removed it from everywhere that it's being used.
Please access the "Create Linode" flow from every entry point (via navbar, blue button and action menus) to make sure that the SSH keys are being displayed if they exist and that there are no regressions.
> M3-4103: Remove image requirement from showing SSH keys

- packages/manager/src/features/Dashboard/NodeBalancersDashboardCard/NodeBalancersDashboardCard.tsx
- packages/manager/src/themeFactory.ts
The tags on the Linode detail view used to be a different style for mobile (blue circle with a white 'X' inside) which should no long be the case now.
> M3-2063: Fix visual regression for tags on mobile viewport

- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
A customer had expressed that our messaging about auto disk
resizes when resizing a Linode was unclear. We included relevant
information in tooltips (when the new plan was smaller or the user
had custom disks). I added some clarifying comments to the text
next to the checkbox, and left the tooltips as they were.
> Clarify auto-resize text

- packages/manager/src/features/Domains/DomainRecordDrawer.test.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
See issue #5721. Allows users to use @ as an alias for the current Domain name when creating records. This isn't yet comprehensive; the differing usage of 'target' and 'name' fields makes it tricky and I want to validate the concept. Both CNAME and AAAA records should allow you to use a @ alias in the appropriate place (please make sure our intuitions about what is appropriate agree). Most record types will have a field where this makes sense, but again I want to validate the concept.
I started a larger refactor of this drawer, which is sloooooow. I will push that up as a follow-on PR because it will be pretty large.
> M3-4039 @-expansion for Target field in Domain records

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingIPTransferPanel.tsx
Couldn't reproduce this bug and the error logic looks good. These are just a few linter warning adjustments since I was in the file anyway.
> M3-4056 Fix: IP transfer errors not displayed

- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
I forgot to add the Payment ID to the label in the Billing Activity Table, as described in the designs.
> [Billing] Add Payment ID to Activity Feed

- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
Another small fix. This disables pagination for the Billing Activity Feed, which can be very jumpy.
To test, use an account with many invoices/payments. Select "All Time" then toggle the pagination footer controls.
> [Billing] Disable scrolling on Activity Feed Paginate

- packages/manager/src/features/Account/CloseAccountDialog.tsx
- packages/manager/src/features/Account/CloseAccountSetting.tsx
- packages/manager/src/features/Account/GlobalSettings.tsx
- packages/manager/src/features/Billing/BillingDetail.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
Based on feedback from Jay:
- Rename "Cancel Account" to "Close Account"
- Remove "Account Active Since" from Account -> Settings
- Add "Account Active Since" to it's previous position above the Billing Activity Feed
Also: 
- Clean up tests for Billing Activity Feed
- Add missing dependencies to a React.useCallback in the activity feed component
> [Billing] Adjustments to Close Account

- packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
- Helper text on Email field in Billing Contact Info drawer
- Gave Email and Phone fields their own lines to prevent misalignment from helper text
- Removed "(optional)" from Company Name label
> [Billing] Contact Info helper text & minor formatting changes

- packages/manager/src/components/Drawer/Drawer.tsx
- packages/manager/src/components/TabLink/TabLink.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
We got customer feedback that screen reader users were having trouble opening support tickets. I verified with JAWS that while the button/drawer functionality is fine, the drawer content itself was not providing any auditory cues, thus leading users to a bit of a dead-end. This fix should impact all drawers.
In addition to this fix, I also moved the required field to be the first input users would focus. 
The only way to replicate this issue is with JAWS, if you need help getting setup with that, let me know. 
**For consideration:**  I'm thinking about hiding the "what is this regarding" select from SRs for now until we fix our select issues. It's not ideal, but I'm concerned this will lead to continued confusion for visually-impaired users and it doesn't necessarily add …
> Fix: Screen reader user cannot open up tickets on account

- packages/manager/src/components/EnhancedSelect/Select.tsx
When I created the wrapper around React-Select's onChange, I forgot the second actionMeta argument, causing tag creation to fail.
To reproduce the bug, try creating a tag. This is the line that was causing failure: https://github.com/linode/manager/blob/develop/packages/manager/src/components/TagsPanel/TagsPanel.tsx#L276
> [for release] Fix tag creation

- packages/manager/src/features/Profile/Referrals/Referrals.tsx
Remove space before parenthesis. Also escaped apostrophe according to linter.
> Copy fix for Profile -> Referrals 

- packages/manager/src/features/Domains/DomainDrawer.test.tsx
- packages/manager/src/features/Domains/DomainDrawer.tsx
To offer a concise explanation, there are Linodes that do not have IPv6 enabled.
When a user does: Add a Domain --> Insert Default Records: Insert default records from one of my Linodes, if the Linode they choose does not have an IPv6 record, the Domain that is subsequently created should not have an IPv6 that is force-created for it.
To prove that this behavior is taking place, I created the tests in `DomainDrawer.test.tsx`. The expected results are:
- If the IPv6 value is null, only the 3 base IPv4 records should be created.
- If the IPv6 value is not null and not undefined, the 3 base IPv4 records + 4 IPv6-related records should be created (so 7 records total).
I also made a small change to the ipv6 parameter type for `generateDefaultDomainRecords()` in `DomainDrawer.tsx`, so that it …
> M3-2868: Creating Domains with DNS records created from Linodes with no IPv6

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/exceptionReporting.ts
This addresses the `Cannot read property "c" of undefined` errors we were seeing with 1.9.0. This was a multi-part problem/solution.
- `exceptionReporting.ts` was throwing this error because we were trying to call `firstReason.match()`. We thought `firstReason` was a string, but sometimes it was an object. 
- **Why was it sometimes an Object?** Because we replace some error messages with... React components. I'd like to change this eventually, but for now, the fix was make sure `firstReason` is always a string.
- **But where were the unhandled rejections coming from?**  They were coming from unactivated users requesting Linodes and other _secondary request_ things. The problem is promise rejections happening in`makeSecondaryRequests()` are unhandled.
- To fix this, I added a Promise.all …
> [for release] Fix c.match Sentry error

- packages/api-v4/src/profile/types.ts
- packages/manager/src/store/profile/profile.actions.ts
- packages/manager/src/store/profile/profile.reducer.ts
`Profile` in the SDK had a `grants` property that we tacked onto it. Moved that addition to `ExtendedProfile` in `profile.actions.ts`.
> [SDK] Update Profile interface

- packages/manager/src/features/Profile/AuthenticationSettings/ThirdPartyDialog.tsx
Small adjustment here. This dismisses the TPA modal when "Go to GitHub" is clicked. The ideal flow is a complete circle in the same tab, but until then, this at least makes it so that the modal isn't still open when you navigate back to your Cloud Manager tab after enabling TPA.
> [for release] Dismiss TPA modal

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/containers/withBackupCTA.container.ts
- packages/manager/src/features/Backups/BackupsCTA.tsx
- packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
- packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/store/linodes/linodes.reducer.ts
3 requests were being made to linode/instances on the Dashboard for
users viewing the Backups card. An extra request was also made on Linodes
landing.
Two problems were causing this:
- The new secondaryRequests logic was calling requestLinodes()
unconditionally. This wasn't a problem when it was in initial requests,
but now other components can fire useReduxLoad before the secondary requests
happen, resulting in extras.
- useReduxLoad's logic is a little wonky; if two useReduxLoad's mount
at the same time, it's possible for them both to look at Redux state,
determine that something hasn't been requested yet, then queue that
thing for requesting. This was causing the third request on the Dashboard.
Short term fix (this commit):
- make secondaryRequests for Linodes conditional
- Add an …
> Fix: duplicate instances requests

- packages/manager/cypress/integration/nodebalancers/smoke-create-nodebal.spec.js
- packages/manager/src/components/TextField.tsx
Since https://github.com/linode/manager/pull/6356/files
we fixed the fact that Ids of the different configs when creating a NB where not the same,
Although as a consequence i think the `for="label"` part was forgotten.
Try to create a NodeBal: https://cloud.linode.com/nodebalancers/create
Look at this field. It cannot be found by label
Before
After
This fixes the e2e that used the label to find the input
Test e2e with `yarn cy:e2e --spec "./**/*nodebal.spec.js"` (assuming `yarn up` is running)
> Accessibility: fix textfield to use inputid for "for" attribute

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.test.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
This fixes a bug where editing an existing non-ICMP rule will fail, since the port doesn't get cleared at the correct step in the pipeline.
Also fixed some linting errors and added a test case.
To reproduce the bug:
1. Create a non-ICMP rule with a value for "Port Range".
2. After creating that rule, refresh the page and edit it.
3. Change the protocol to ICMP and clear out the "Port Range" input.
4. Click "Edit Rule".
5. Observe: the "Port Range" has not be cleared in the Rule Table.
6. Click "Apply Changes"
7. Observe: an error explains that ICMP protocols must not have a port range.
> [FW] Fix bug with ICMP ports

- packages/manager/.eslintrc.js
Comma was lost in a rebase somewhere. John and I have this same fix in different PRs, but it's breaking commits #now so better to resolve it.
> Patch eslintrc file

- packages/api-v4/package.json
- packages/api-v4/src/request.test.ts
- packages/api-v4/src/request.ts
- yarn.lock
Rewrite request.ts without using Ramda methods. This only saves ~2K from the final build bundle size, so it may not be worth it. otoh, fewer dependencies means fewer vulnerabilities/upgrades/management issues, and in this case we were only using a handful of methods.
The tests pass with the new refactor, but I'm not sure that every possible case is handled. Please check the app to make sure requests are being made properly, including more complicated cases such as pagination, filtering, etc.
> [SDK] Remove Ramda dependency

- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
This fixes two issues:
1. `List of Firewalls | Firewalls` document title segment on FW Landing.
2. `Firewalls | Firewalls` document title segment on FW Details.
> [FW] Fix DocumentTitleSegments

- packages/manager/src/initSentry.ts
This makes it so that client network errors aren't reported to Sentry.
To test:
1. On `develop`: make sure you're running Cloud locally with a SENTRY_URL
2. Request-block one of the chunk.js files on app load.
3. Observe: network request to Sentry is made.
Then, checkout this PR and do the same. No request is made to Sentry.
Also, make sure you're running on port 3000 (or change the code in initSentry to whitelist whatever port you're running on.) I've been running on 3050 lately and this stumped me for a bit.
> Ignore ChunkLoadErrors

- packages/api-v4/src/regions/index.ts
- packages/api-v4/src/regions/regions.ts
- packages/api-v4/src/regions/types.ts
- packages/manager/.eslintrc.js
- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
- packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/types.ts
- packages/manager/src/request.tsx
- packages/manager/src/store/regions/regions.actions.ts
- packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.test.ts
- packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.ts
- packages/manager/src/utilities/arrayToCommaSeparatedList/index.ts
Solves a UX problem when creating a GPU Linode that we've had numerous reports of. Three problems, specifically:
1. We were showing all plans, including GPU, even when the user had selected a region that doesn't support GPUs (GPUs are only in Newark for now). This has been fixed by disabling the GPU plan tab if the user selects an invalid region.
2. We allow you to select a plan first, and we were allowing users to select an invalid region after selecting a GPU plan. This has been fixed by filtering the regions to those that support the selected plan and adding a tooltip to explain where all the other regions went.
3. When a user submitted an invalid combination, we were intercepting a useful API error message ("there is no availability for the selected plan in the selected region") and …
> M3-3932 Change: Improve UX for GPU selection

- packages/manager/src/features/Images/ImageRow.tsx
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/store/middleware/imageEvents.ts
Currently, when a user creates an Image, a row is automatically added to the Image landing page for it, despite us not knowing at that point whether the creation will be successful or not. Additionally, the Image size displayed is inaccurate.
This PR adds a progress bar that fills the last 4 columns instead that goes away upon successful Image creation.
To-Do:
> M3-4096: Add progress bar for newly-created Images

- packages/manager/src/features/Profile/Profile.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
Some of our routing is out of date and doesn't handle bad input
(e.g. cloud.linode.com/profile/garbage is a valid route in prod,
it shows you the /display page). It's also possible to break navigation
by navigating directly to profile/ (with the slash) then trying to
tab around, since the router tries to resolve profile//whatever.
> Fix: Profile routing

- packages/manager/src/features/linodes/LinodesDetail/linodeDetailContext.tsx
- packages/manager/src/store/linodes/config/config.actions.ts
- packages/manager/src/store/linodes/config/config.reducer.test.ts
- packages/manager/src/store/linodes/config/config.reducer.ts
- packages/manager/src/store/linodes/config/config.requests.ts
Same changes, different part of the Redux store. Linode configs functionality should be unchanged, patterns should make sense.
> Refactor LinodeConfig reducer to use updated Redux patterns

- packages/manager/config/webpack.config.dev.js
- packages/manager/config/webpack.config.prod.js
Make our prefixing config more explicit, so that class names are not
auto-prefixed but ids are. We do some CSS targeting on class names
in SVGs, which prefixing breaks. Otoh id conflicts were causing
a visual bug in the Linode create flow, where the Mumbai flag svg
conflicted with the circle svg in the select plan panel.
To test: In the Linode create flow, select a type then choose Mumbai as your region. In prod the plan selection circle svg gets screwy, this should fix it. Other svg's throughout the app should be unchanged.
> Fix @webpack/svgr settings

- packages/manager/src/store/regions/regions.actions.ts
API is releasing their part of this on Monday, we should undo the fake stuff before we release.
> Remove mocked GPU Linodes region.capabilities since API supports it

- packages/api-v4/src/domains/records.schema.ts
- packages/manager/src/components/TextField.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.test.tsx
- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
We were using +e.target.value to coerce string inputs to numbers.
This allowed our types to play well together internally, but it had
the drawback of not allowing users to clear the input, since '' coerces
to 0.
The solution is pretty messy: we stop the coercion in the event handlers,
and instead handle conversion just before sending data to the API.
I had to update the typings in the drawer, and its parent, to make
this work. It is very messy, and this whole workflow is screaming
for a refactor.
> Allow clearable numeric inputs in DomainRecordsDrawer

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.test.ts
- packages/manager/src/utilities/arrayToCommaSeparatedList/arrayToList.ts
- Reduce the opacity of disabled table rows in SelectPlanPanel
so it's more obvious that they're not active.
- Fix arrayToList to handle empty arrays or undefined input.
> Update disabled state when selecting GPU plans

- packages/manager/src/App.test.tsx
- packages/manager/src/App.tsx
- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/featureFlags.ts
This PR moves the PrimaryNav from the left side of the viewport to the top. **Note** that the organization of the links will be done in the next PR. For now, I've hidden a few of the links so the proportions roughly match those of the designs.
Notes:
- Make sure you're testing in the LD testing environment.
- There's a noticeable shift when the flag is evaluated... in a separate PR I'm going to adjust this.
- The diff is going to be large for these PRs, but I structured the commits in such a way that if you de-select the first commit when viewing the diff, you should see an accurate representation of what actually changed.
Still to do:
- General markup/CSS cleanup. A lot of it is now unused so it can be removed.
> M3-4195 Move PrimaryNav

- .github/workflows/sdk.yaml
To test this, commit and push to master _on your fork_. Note that I'm uploading the entire packages/api-v4 directory now...that's because at some point we'd like to test the build artifact itself, and the contents of that directory in their entirety is what will get published to NPM.
> Undo bad autoreplace that broke artifact upload

- CHANGELOG.md
- packages/api-v4/package.json
- packages/api-v4/src/domains/domains.schema.ts
- packages/manager/package.json
Tags should not be required when creating a Domain.
> Hotfix: remove required() from tags in Domain schema

- .gitignore
- packages/manager/scripts/pre-push.sh
This adds support for a new environment switcher script. A _very hacky_ environment switcher script.
The script injects the variables into `src/constants.ts` directly, so all you need to do is run the script and refresh the page. It's awful, but saves about 1 minute each time you switch environments.
This just adds an entry to gitignore and a block to the pre-push hook to warn you if you try to push temporary variables.
Msg me for the actual `switch.sh` script.
> Support for environment switcher

- packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/VolumeDrawer.tsx
- packages/manager/src/utilities/formikErrorUtils.ts
Currently, if a user hits the limit for the number of Volumes on a Linode and attempts to add another Volume, the Create button spins and returns to its normal state, no error message is displayed, and a 400 response code hits the console.
This change is an attempt to ensure the API error message feeds through and displays.
Perhaps it is better to change the wording of the error displayed, instead of using the API error, to make it easier for users to understand.
To test:
1. Create 6 Volumes on an 8GB Linode
2. Attempt to create a 7th Volume
3. Observe: off this branch, the behavior described in the first paragraph of the Description; on this branch, you should see the error message displayed below
> M3-4173: Show error when user reaches Volumes limit

- .github/workflows/sdk.yaml
- packages/api-v4/package.json
This will (hopefully) publish the JS client to NPM on every push to master, if the version in package.json has changed. Before our next release we can bump the version to beta (from alpha).
I'm a bit at a loss how to test this. There's no support for `--dry-run` in the action, so the only way to test it would be to run it from my fork, which would either publish it for real or publish it to my personal NPM account if I gave it a different token. Neither option seems awesome.
Our NPM access token is stored in Settings for this repo.
> Add NPM publish action

- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
Some users trying to reset their passwords may be confused by the Root Password fields in the Rebuild & Settings tabs, because each field has the same guidance information re: password requirements. It might also be easy to overlook the fact that rebuilding will wipe the Linode.
I bolded the `"Rebuilding will destroy all data on all existing disks on this Linode."` text in the Rebuild tab to make it more prominent, and added some helper text to the Root Password fields in the Rebuild & Settings tabs. The exact verbiage is still preliminary; awaiting Jay's approval on it.
> M3-4016: Some changes to clarify Linode password fields in Reset Root Password vs. Rebuild

- packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
- packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.test.tsx
- packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
- packages/manager/src/store/authentication/authentication.helpers.ts
- packages/manager/src/utilities/storage.ts
Does for StackScript creation what we did for Support Tickets. In-progress work is saved to localStorage and read when loading the component. Creating is simple, but editing is much harder and involves a lot of refactoring, which is why I'm breaking this into two PRs.
There is one broken test in StackscriptForm that I fixed in the editing work. Please disregard.
> M3-4179 Save in-progress work when creating a StackScript

- TESTING.md
https://github.com/linode/manager/pull/6508 adds a few helpers for mocking flags for testing; this updates the documentation for that and for mocking Redux state.
Question: should this live here in TESTING.MD or the new MOCKING_DATA.md? I'm leaning towards TESTING.MD.
> Update documentation with testing techniques for mocking store and flags

- packages/manager/src/MainContent.test.tsx
- packages/manager/src/MainContent.tsx
- packages/manager/src/components/MainContentBanner.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/store/preferences/preferences.actions.ts
This makes the main content banner dismissible. 
The data shape for the main content banner flag now requires a unique `key` so we can map dismissals to specific banners (since we could potentially reuse this flag in the future).
To test, I recommend mocking a feature flag with a new key each time you want to test.
> Dismissible main content banner

- packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
- packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
Add a check for negative amounts and add the correct text if it is negative. 
Also lined up the margins for the total on the upper right with the invoice summary on the bottom and removed the empty row when there is no pagination.
**Before:**
**After:**
> M3-4163: Handle negative amount on invoice details better

- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/constants.ts
This adds support for OBJ Singapore. All we needed to do is update the display mapping; when `ap-south-1` is returned from `/object-storage/clusters`, a /bucket request to that region will be made. 
To test: 
- Mock `/object-storage/clusters` to include ap-south-1.
- Mock existing buckets to look like they're from ap-south-1.
> Support for OBJ Singapore

- packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
Hide unit price instead of having it show `$None` in the invoice table
> M3-4163: Hide unit price if none

- packages/manager/src/initSentry.ts
This ignores the "ResizeObserver loop limit reached" error we've been seeing. Apparently it is benign: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
Full disclosure: I was not able to reproduce this issue, and I'm not positive this will actually work to silence it.
> Ignore ResizeObserver loop error

- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/components/TableCell/TableCell_CMR.tsx
- packages/manager/src/components/TableContentWrapper/TableContentWrapper_CMR.tsx
- packages/manager/src/components/TableHeader/TableHeader_CMR.tsx
- packages/manager/src/components/TableRow/TableRow_CMR.tsx
- packages/manager/src/components/TableRowEmptyState/TableRowEmptyState_CMR.tsx
- packages/manager/src/components/TableRowError/TableRowError_CMR.tsx
- packages/manager/src/components/TableRowLoading/TableRowLoading_CMR.tsx
- packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
This contains the "base" for CMR work on tables. I'm not exactly sure all of these components will be needed, but I included all of our components that deal with tables.
These new files are copy/pastes of the original. As a reminder, the idea is that CMR work is done in these new files/components, which are conditionally rendered:
```tsx
flags.cmr ? <Table_CMR /> : <Table />
```
When CMR is complete/deployed, we'll copy paste in reverse... (copy the CMR files and paste the contents in the original, to maintain some Git history).
Check out the second commit for a change I made to fix linting errors: https://github.com/linode/manager/pull/6538/commits/7005f0799649ddcea41355160ecd7a46df9dcca9.
There should be no change, as these components aren't in use anywhere yet. But please take a look …
> M3-4239 CMR table base

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/themeFactory.ts
I have a bad habit of editing the styles directly...this should keep the chip styles localized in CMR and prevent any regressions
> Fix regression for MuiChip and move it to appropriate CMR file

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
This fixes two regressions:
**Crashing bug on the Linode Resize tab when viewing a Nanode**
This happened when I removed the "Nanodes" tab, since it meant that the selected tab on Linode Resize was `-1`, which had bad consequences. To fix, I manually changed the selected class to "standard" for Nanodes, and added a tab select safeguard anyway. 
**Correct tab isn't selected when Cloning a Linode**
This fixes an old regression from here: https://github.com/linode/manager/commit/ccad3792cdf966f012b952b5fa3b82f12311a71c#diff-86d0256904fe6812859a8e7f376682f9R344 where cloning a Linode resulted in the Create page being opened without the correct plan tab selected.
Please test everything related to creating Linodes and viewing their details.
> [for release] Fix Linode -> Resize bug

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/linodeDetailContext.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeRenderLoading.tsx
- packages/manager/src/features/linodes/LinodesDetail/maybeWithExtendedLinode.tsx
This is a band-aid for the release, to resolve the issue where sometimes a 404 Not Found message is displayed when loading LinodesDetail.
There are 2 different "Not found" paths, which has previously been hidden since all Linodes were requested before LinodesDetail was ever loaded. Now you see both of these 404 messages in sequence (for a Linode that genuinely doesn't exist) or just the first one (for a Linode that hasn't been requested yet, or the request is in flight.)
A better solution will be to use `useReduxLoad` in LinodesDetail and only after `_loading` is false do all the things to extend the Linode, generate the needed actions/context/etc. This is too large a change for a patch to a release branch, so in the short term I adjusted what was already there to hide the duplicate 404 …
> [For release] Fix 404 issue

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx
- packages/manager/src/features/linodes/LinodesDetail/MutateDrawer/MutateDrawer.tsx
Currently there is logic to display a list of changing specs for upgrades. This doesn't work with g6 -> g7 High Memory upgrades, since the specs are the same. I added a hacky way around this.
To test, please try several combinations of different upgrades. Msg me for instructions if needed.
> [for release] Fix upgrade drawer for High Memory g6 -> g7 plans

- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.spec.js
- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.stories.tsx
- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.test.tsx
- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
- packages/manager/src/components/ActionMenu_CMR/index.ts
Updating the action menu to the new styling in addition to leveraging Reach's MenuButton component to make this fully accessible. This is best viewed in Storybook. 
Standard usage:
With inline label:
Please note that mobile and the menu item's tooltip state have not been finalized. 
> CMR action menu styling

- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsList.tsx
- packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsMenu.tsx
- packages/manager/src/store/events/event.helpers.ts
To determine if an event was related to an entity that has been
deleted, we were checking (among other things) that the relevant
deletion event had a status of finished or notification. This caused
a slight problem when deleting a Linode, since a linode_shutdown
event is generated at exactly the same time as the linode_delete
event, and it was possible to click on this event in the events menu
before the delete had finished; however, the API already considered
this deleted ~(or maybe it was just our Redux store?)~ [Edit: no], so clicking
the event caused a 404.
I adjusted this logic so that we only check that the delete event
didn't fail (status !== failed). This handles the case above,
and should prevent the behavior the original logic was (I think)
intended to avoid: a long-ago failed …
> M3-4087 Update setDeletion logic for Events

- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
It is currently possible to create an NS record for a domain that does not have any A/AAAA records, but this results in an Invalid Zone file on the back-end.
After discussions with API, the consensus was that a solution on that end could be done, but would require some complicated checking and making users jump through hoops in a manner inconsistent with the specs. 
This PR sets out to reduce the number of these scenarios arising by displaying a notice to the user if they are trying to add an NS record on a domain that does not have an A/AAAA record.
> M3-4085: Add a <Notice /> when user tries adding an NS record to a domain w/ no A/AAAA record

- packages/manager/src/utilities/unitConversions.test.ts
- packages/manager/src/utilities/unitConversions.ts
Our `readableBytes` function doesn't handle invalid input very well:
Theoretically this shouldn't happen, but just in case, I changed the behavior to return `0 bytes` instead. 
Nothing should have changed, so just for regressions in places that use `readableBytes` and run the new tests.
> readableBytes: handle invalid input better

- packages/manager/cypress/integration/linodes/smoke-create-linode.spec.ts
Now that the "Nanode" tab is gone, this line in the create Linode smoke test is unnecessary. 
**To test:** 
```
yarn cy:e2e --spec cypress/integration/linodes/smoke-create-linode.spec.ts
```
> Remove outdated command in Create Linode smoke test

- package.json
- patches/@reach+menu-button+0.9.1.patch
⚠️  ~Wait until https://github.com/linode/manager/pull/6508 is merged to review this.~ done
There's a bug in the Reach UI Menu Button where _one_ menu doesn't always close when you click on _another_ menu. This leads to two menus being displayed at once.
This has been reporting to the Reach UI maintainers [here](https://github.com/reach/reach-ui/issues/566) and apparently a fix is coming soon, but this applies a patch in the meantime. This patch essentially it removes [this branch](https://github.com/reach/reach-ui/blob/25840c3d15278e316cc74eaecf096fa01377f361/packages/menu-button/src/index.tsx#L858-L860).
> Patch Reach UI menu button

- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
A customer must explicitly cancel Object Storage services in Account Settings. This adds a warning if a user has OBJ enabled but no Buckets that they are still being billed. 
I also refactored the OBJ Landing to use the account management hook instead of `connect` for isRestrictedUser.
**Todo:** 
- Write some unit tests
> M3-4227 Add billing warning for OBJ

- packages/manager/src/__data__/domains.ts
- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/features/Domains/DomainsLanding.test.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/utilities/testHelpers.tsx
Originally reported in https://github.com/linode/manager/issues/6550. It looks like this was a regression from the EntityTable component.
To fix, I added an optional `initialOrder` prop to `<EntityTable />`, which is passed down to the `order` and `orderBy` props on `<OrderBy />`. 
This new prop is optional since `<OrderBy />` defaults them to `label` and `asc` anyway.
I also added a test to ensure default order (as well as a helper function for testing order of elements).
**To test,** have a handful of domains starting with different names. On page load, they should be sorted by Domain name ascending. All other sort functions should be unaffected.
To run new unit test: `yarn test packages/manager/src/utilities/testHelpers.tsx`
> Fix sort order on Domains Landing

- packages/api-v4/src/linodes/linodes.schema.ts
- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
This drawer was old, needed a lot of refactoring:
- Added Formik using the newish useFormik hook
-  Moved drawer state management (mostly) inside the drawer itself
- Refactored the drawer to a function component
Still coming:
> M3-2020 Change: Add Formik to LinodeDiskDrawer

- packages/manager/src/exceptionReporting.ts
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx
- packages/manager/src/initSentry.ts
- Added "Network Error" to our list of ignored errors
- Most of these seemed to be coming from calls to the Longview API,
and it turns out we weren't catching errors for some of those requests.
Added some catch => null blocks (errors are handled through Redux).
A third type of error, "request aborted", also seems to be coming from calls to the LV API. 
I haven't been able to reproduce these errors (blocking requests to LV doesn't cause any exceptions or reporting, nor does anything else I've tried), but these are Good Changes and in theory ought to cut down on actual as well as reported errors.
> M3-4255 Ignore network errors in Sentry

- packages/manager/public/fonts/fonts.css
- packages/manager/src/themeFactory.ts
Casing was off and causing issues.
> Fixing casing for semi bold font variant

- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/__data__/buckets.ts
- packages/manager/src/factories/objectStorage.ts
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
This will allow users to quickly see their total space utilization by bucket. This is still pending review from the API side before this PR is functional.
Once that side of things goes through, combined with this should resolve #6256.
> STOR-34 Change: Added Size column on the OBJ Bucket Landing page

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
`renderPlanContainer` in `SelectPlanPanel.tsx` was reordered based on the ticket specifications:
- Ram was changed to RAM
- Table headers are now Plan > Monthly > Hourly > RAM > CPUs > Storage
**Before**:
**After**:
> M3-4242 Adjustments to the SelectPlan table

- packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
- packages/manager/src/features/Volumes/VolumeCreate/VolumeCreate.tsx
- packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx
Converted ConfigSelect from a class component to a function component.
In addition to the standard changes for class => function component conversions, this PR also retrieves configs from state to save an API request from being made.
Please ensure that creating and attaching volumes still work as they should.
I am planning on creating a test for this in a follow-up PR.
> Convert ConfigSelect from class component to function component

- packages/manager/src/features/Account/AutoBackups.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
- packages/manager/src/features/Lish/Glish.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/Support/SupportTicketDetail/CloseTicketLink.tsx
- packages/manager/src/features/TheApplicationIsOnFire.tsx
- packages/manager/src/themeFactory.ts
We often restyle html buttons to look like links- to make this styling easier to implement, we can now spread the styling to other elements in the app, similar to a mixin. I applied this to places we're already restyling buttons, but if I missed any please call them out here.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …
> Create "button reset" CSS mixin

- packages/manager/src/containers/withImage.container.ts
- packages/manager/src/containers/withImages.container.ts
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
- packages/manager/src/hooks/useEntities.ts
- packages/manager/src/hooks/useImages.test.ts
- packages/manager/src/hooks/useImages.test.tsx
- packages/manager/src/hooks/useImages.ts
- packages/manager/src/store/firewalls/firewalls.reducer.ts
- packages/manager/src/store/image/image.actions.ts
- packages/manager/src/store/image/image.reducer.test.ts
- packages/manager/src/store/image/image.reducer.ts
- packages/manager/src/store/image/image.requests.ts
- packages/manager/src/store/selectors/getSearchEntities.ts
- packages/manager/src/store/selectors/getSearchEntitites.test.ts
- packages/manager/src/utilities/getEntityByIDFromStore.ts
Started out trying to add a `public` filter to the useImages hook, since it seemed useful. Led me down the usual TDT rabbit hole, I ended up:
- Refactoring Images in Redux to use the current state shape
- Added some tests for the useImages hook
- Fixed a few bugs in the Firewalls reducer
To test, please make sure that all Images functionality is unchanged (CRUD-ing images, displaying them in tables, searching for them, etc.)
> TDT: Images hooks and redux

- packages/api-v4/package.json
- packages/api-v4/src/linodes/linodes.schema.ts
- packages/manager/config/webpack.config.prod.js
- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/PasswordInput/PasswordInput.tsx
- packages/manager/src/constants.ts
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
- packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
- packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
- packages/manager/src/utilities/validatePassword/index.ts
- packages/manager/src/utilities/validatePassword/validatePassword.test.ts
- packages/manager/src/utilities/validatePassword/validatePassword.ts
- Add new feature flag for passwordValidation, and conditionally
re-add the previous helper text.
- Add a new validatePassword method that can handle different
types of validation.
- Remove zxcvbn from the JS client (commented out, as I hope to move all schemas to a separate workspace).
Toggle the flag in the test environment between `length` and `complexity`. You should see the helper text appear or disappear accordingly. 
This is phase 1. No client validation is currently being done on passwords (except for `.required()`). Phase two will use the new `validatePassword` wherever passwords are submitted. Eventually we'll use Formik everywhere and a simple dynamic schema will work (by then we'll be using complexity permanently, so even one schema should do it).
> Feature flags for password validation

- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
Options for disabling actions due to maintenance mode were being
spread after the ones for readOnly status, so that a restricted
user viewing a Linode not undergoing maintenance could access
many of the actions that were being disabled; the latter were
being overwritten by the former.
Switching the order of the prop spreading fixes this; it also means
that when both cases are true, the reason given for why actions
are disabled is because of permissions rather than maintenance.
This actually makes more sense, since it means the messages will be
consistent--permissions are more restrictive than maintenance.
---
Please test all possibilities:
- Linode has active maintenance (fake status to 'stopped')
- User has read-only access to the Linode
- Neither
- Both
> M3-4283 Fix LinodeActionMenu disabled props

- packages/manager/src/features/Domains/DomainRecordDrawer.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
The original issue (Support ticket link in JIRA) seems to have been mistaken: I logged in as the customer and saw that Cloud was displaying exactly what the API returned, which the user seems to think had been clipped. I'm not sure how the TXT record got into that state, but displaying what the API sends us is all we can do. Furthermore, I created a TXT record in production using the exact values the customer used, and was able to create, view, and edit the record normally.
However: it is a little weird, and a relic of the one-field-input-for-all-types pattern in this component, that we use a single-line text input for TXT records, which are frequently long (though not that long). I added some handling to turn the input into a textarea when working with TXT records.
Test account 4 has a …
> M3-4172 Make target field for TXT records multiline

- packages/manager/src/hooks/useEntities.ts
- packages/manager/src/hooks/useKubernetesClusters.ts
- packages/manager/src/store/kubernetes/kubernetes.requests.ts
Regression/bug that was brought up through PIE. Selecting an LKE cluster when creating a support ticket worked only if you had previously navigated somewhere else in the app that requested clusters. The request was being made correctly in the drawer, but a type mismatch meant that the data returned from the request was `undefined`. 
To test:
1. Have at least one LKE cluster on your account
1. Go directly to /support/tickets
2. Reload the page to be safe
3. Select LKE as the entity type
4. Observe: a request should be made and the "Select a cluster" dropdown should be populated with your clusters.
NOTE: the back end for this is still not working correctly, so if you actually open a support ticket with a cluster id, the entity won't show up in the tickets table.
> Remove unneeded .then() from K8s request in useKubernetes

- packages/api-v4/src/object-storage/buckets.ts
- packages/manager/src/containers/bucketRequests.container.ts
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.test.tsx
- packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
- packages/manager/src/store/bucket/bucket.actions.ts
- packages/manager/src/store/bucket/bucket.reducer.ts
- packages/manager/src/store/bucket/bucket.requests.ts
As suggested by @Jskobos in https://github.com/linode/manager/pull/6547#pullrequestreview-438264490
This adds getBucket() to Redux/containers etc. and calls is after updating Objects, so that the updated Bucket size will be displayed on the landing page.
The calls to getBucket after Object uploads are debounced, since many Objects can be uploaded at once.
> getBucket() after updating Objects

- packages/api-v4/src/linodes/linodes.schema.ts
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
- packages/manager/src/utilities/validatePassword/validatePassword.test.ts
- packages/manager/src/utilities/validatePassword/validatePassword.ts
The previous PR (#6567) made our root password validation controllable by a feature flag, but it didn't actually use the new validation logic anywhere. This PR (should) manually validate root passwords in all the places where we previously validated them. I think this is a comprehensive list, but please check me:
- Linode creation (LinodeCreateContainer)
- Linode Disk creation
- Linode rebuild
Other places where we take password inputs, such as Managed credentials, never did client validation in the first place since they don't share the API's criteria.
Toggle the flag to each of its values (`none`, `length`, `complexity`) and make sure validation is working properly.
> Change: manual password validation

- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
- packages/manager/src/store/events/event.helpers.test.ts
- packages/manager/src/store/events/event.reducer.test.ts
- packages/manager/src/store/linodes/linode.events.test.ts
- packages/manager/src/utilities/date.ts
- packages/manager/src/utilities/formatDate.ts
Added a case for formatDate to accept a number. LongviewClientHeader
was passing an ISO string to formatDate, which it doesn't recognize.
By using fromMillis with the actual clientLastUpdated value, we can
avoid the back and forth conversion.
> Fix Longview date formatting

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Note: These links don't currently point to valid guides. The apps will remain behind a flag until the guides are published.
> Update OCA links for Nextcloud and Percona

- packages/manager/src/components/LineGraph/LineGraph.tsx
Fixing disabling a linegraph line should cross it out:
> fix disabling a graph line in linegraph

- packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
- packages/manager/src/features/OneClickApps/FakeSpec.ts
- Rename Percona to Percona (PMM)
- Update matching logic in AppDetailDrawer so that app names
with parentheses don't break it.
> Fix Percona name and matching logic

- package.json
- yarn.lock
- Added `"kind-of": "^6.0.3"` resolution to the root level package.json
- Ran `yarn install`
As expected, there are other changes to yarn.lock. 
To test: `yarn clean && yarn up`. Verify the app & tests work as before.
> Resolve ^6.0.3 of "kind-of" package

- packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
- packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
- packages/manager/src/features/Billing/PdfGenerator/utils.ts
For some types of invoice, `to` and or `from` are `null`. This causes an error in `parseAPIDate`. We have try/catch logic in place, so there is no customer impact. However we'd like to prevent reporting errors like this to Sentry.
I added logic to the specific method that calls `formatDate` when viewing an invoice. I considered moving the null checking to parseAPIDate itself, but it seems like maybe that would have side effects; it's also hard to say what the default should be (an empty string maybe?)
Fixed a small state management bug that was causing the loading state to hang when requesting an invalid invoice (404).
To test: find an invoice that will cause this behavior. Lots of ways to do this, I logged in as the customer in the JIRA ticket and used the invoice ID from the Sentry …
> Handle null dates in invoice details logic

- packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
- packages/manager/src/features/Longview/shared/formatters.ts
Longview was crashing intermittently for a customer; one of the methods we thought would always receive a number was not always receiving a number.
> Fix: Longview CPU formatting

- packages/manager/src/features/TopMenu/TopMenu_CMR.tsx
Adjust the width of the secondary nav to be 1280px, centered.
> Secondary Nav Width

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph_CMR.tsx
Analytics tab in Linode Details as per the designs, with the old Summary tab used as a starting point.
The designs have a Longview section, but we do not have a way to tie those in presently to Linodes.
> M3-4294: Analytics tab in Linode Details

- packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
I noticed that the permissions warning wasn't consistent between options:
This makes it so they use the same component.
> Volume drawer: consistent Notices for restricted users

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
Disable "Add a Disk" button under the `Storage` tab if disk is full.
> [CMR] Disable "Add a Disk" button if disk is full

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
Improvements to https://github.com/linode/manager/pull/6602:
- Use TableRowLoading when kernels are loading to prevent table jump
- Put cancelBoot back as onClose handler for Boot modal
- 'No limit' shown for memory limit when config.memory_limit === 0, instead of the Linode RAM
> M3-4301: Configs Tab improvements

- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize_CMR.tsx
- packages/manager/src/mocks/serverHandlers.ts
Safe access Linode data in mapStateToProps from the LinodeResize modal.
Moving it outside of the LinodeDetailContext means that it is always
present on the landing page, and it was being read with the deleted Linode's
ID after deletion, causing a crash.
In addition, added a mock for Linode deletion.
You can use the new mocks to test this, Linode deletion now works there.
> Fix Linodes Landing crash after deletion

- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/utilities/getAll.ts
The hope is that this will help us improve performance for huge accounts. That doesn't seem to be panning out so far, but removing Bluebird in favor of Promise.all is on our radar.
Updates our mock helpers to allow you to specify a number of pages to request from the API. Currently the mocks are set up to simulate an account with a very large number of Domains; these changes will be removed before merge.
> M3-4311 Change: Use Promise.all instead of Bluebird.reduce for getAll

- packages/manager/cypress/integration/linodes/smoke-delete-linode.spec.ts
The case of not found was making the test fail.
Interestingly i do not see when this would have been changed, so why would it have passed before?
did we change the styling of this in CMR?
> E2E fix: change case of Not Found

- packages/api-v4/src/object-storage/types.ts
Following the [API-Reference](https://developers.linode.com/api/v4/object-storage-buckets/#post) for the function the function "createBucket".
To be used in TypeScript right now, I had to use @ts-ignore | @ts-expect-error.
> Fix "Create Object Storage Bucket" types.

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/features/Dashboard_CMR/Dashboard.tsx
- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/LinodeDashboardContent.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/MultipleLinodes.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/SingleLinode.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/index.tsx
- packages/manager/src/features/Dashboard_CMR/index.tsx
Add structure, tabs, and display logic for the new Dashboard. Shows:
- "notification center" placeholder
- 1 Linode placeholder when 1 or fewer Linodes on the account
- TabbedPanel with stubs when multiple Linodes are present.
I started with our standard Tabs pattern but changed my mind and used TabbedPanel instead, so that the URL is unchanged. Feel free to talk me out of this, but I think the routing is too messy to be worth it (since all of these tables will have permanent, dedicated URLs that people can bookmark). The main issue is: what happens if someone bookmarks dashboard/volumes when that table won't be visible unless they have both a) Volumes and b) 2+ Linodes? We could handle these in fancy ways but I think simple is better here.
> M3-4338 CMR: Dashboard base

- packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
Remove handleClick from ...props spread so it doesn't get passed
down to a `<th>` where it doesn't belong.
Fixes the console warning currently present on Linodes landing (and anywhere else SortableTableCell_CMR is used)
> Fix console warning

- package.json
- packages/manager/package.json
Our `cy:e2e` command runs Cypress in headless mode (`--headless)`. I like to use `yarn workspace linode-manager cypress run -b chrome` so I can watch the test running in the browser. This PR adds `yarn cy:run` as a shortcut.
> Add command to run Cypress tests in non-headless mode

- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/LinodeDashboardContent.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/SingleLinode.tsx
- packages/manager/src/features/Volumes/Volumes.tsx
- packages/manager/src/features/Volumes/VolumesLanding.tsx
- packages/manager/src/features/Volumes/VolumesLanding_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDashboardNavigation.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/mocks/serverHandlers.ts
Renders LinodesDetail on the Dashboard if you have only one Linode on your account.
After discussion/experimentation, decided not to have the details tabs change the URL. This required adding a separate navigation component to LinodesDetail that gets used when we're on the dashboard.
@WilkinsKa1 How does this look tabs-wise? Will it port over easily to the Reach tabs?
> M- 4337 CMR: Dashboard -- Single Linode view

- packages/manager/src/features/Kubernetes/kubeUtils.ts
- packages/manager/src/features/Search/useAPISearch.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/store/selectors/getSearchEntities.ts
This is part 1. It replaces the current client-based search with API based search. The search is debounced, so a set of requests is made .5 seconds after typing in the search bar stops.
There is duplication still, since the client search logic is still there and active (just not showing any of its results). Part 2 will add logic to determine whether or not the account is "large", and use the appropriate search accordingly.
For this, the eventual plan is to request the upcoming account summary endpoint on app load, since we'll be doing that anyway for the dashboard etc. Then we can store isBigAccount in Redux, or store the summary in Redux and derive the account type from that. But since that endpoint is weeks/months away and we can't wait that long, in the short term I plan to add a call …
> M3-4332 Change: Use API search for large accounts

- packages/manager/src/components/BarPercent/BarPercent_CMR.tsx
- packages/manager/src/factories/account.ts
- packages/manager/src/factories/linodes.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
- packages/manager/src/mocks/serverHandlers.ts
This contains adjustments to the Linode Monthly Transfer section.
Per the new designs, this combines Linode + Account transfer into the same bar graph. There are two reasons for this:
1. It's helpful to see how _this_ Linode contributes to your overall account-level monthly transfer.
2. The Dashboard Transfer section is going away.
The new designs for this were done in parallel with adjustments to the [historic network transfer graph](https://github.com/linode/manager/pull/6616) based on the info available from the API.
**Note: this does not handle for transfer overages. Jay is considering this and will provide guidance.**
I added a new `account/transfer` handler in testHandlers.ts, so play around with values here as well as the `linode/{id}/transfer` handler.
> M3-4376 Linode Monthly Transfer Adjustments 

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary_CMR.tsx
A bug came about where the Linode Summary (pre-CMR)/Analytics (CMR) tab's graph options dropdown was displaying "2020" as the year for all month options.
This PR corrects that bug by setting the year property.
> M3-4380: Display correct years in Linode Summary graph options

- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeNetSummary.tsx
Previously the `total` being used to calculate "remaining" was from `linode.specs.transfer`, which is the amount of transfer this Linode adds to your total pool each month. This is a static number, however, meaning that it doesn't account for prorated transfer if you create your Linode in the middle of the month, for example.
Instead, we should be using the `quota` from the `/linode/instances/:id/transfer` endpoint (which this component was already hooked into already).
Note: this is changing in CMR anyway, but since that's still a ways away, and this was a really simple fix, I went ahead and made the change.
Compare newly created Linodes with production. The "remaining" value should be different. Also compare older Linodes which have been around all billing cycle – these should be no …
> Fix Linode transfer "total" (non-CMR)

- packages/manager/src/components/Link.tsx
- packages/manager/src/features/Backups/BackupDrawer.tsx
- packages/manager/src/features/Backups/BackupsCTA_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
This does two things:
1. Fix placement of Linodes Landing Backups CTA in Production (non-CMR)
2. Add new CMR component for BackupsCTA implementing mockup from Jay
**Note:**
The new CTA doesn't have a link to the backups guide, so I included in the drawer, which is used by CMR _and_ Production. IMO it doesn't hurt to show it in both places for a little while.
To remove changes to the CTA:
```
git diff HEAD:packages/manager/src/features/Backups/BackupsCTA.tsx packages/manager/src/features/Backups/BackupsCTA_CMR.tsx
```
Please check all combos:
1. No local storage flag, Linodes without backups.
2. Local storage flag, Linodes without backups (i.e. "dismissed")
etc., for CMR and non-CMR.
> M3-4366: Fix placement of Backups CTA

- packages/api-v4/src/kubernetes/nodePools.ts
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleAllNodesDialog.tsx
This PR makes use of the new recycle nodes endpoint, currently available in dev only.
I didn't put this action into Redux since this kicks off an asynchronous process and it could be several seconds before anything changes. Since there's no immediate feedback that anything is happening, we should maybe include a note about this in the confirmation modal (which is sort of placeholder text right now anyway). @Jskobos what do you think?
Use dev. The "Recycle Nodes" option is now available on the Cluster Detail page.
> M3-4314 Recycle all LKE cluster pool nodes

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
> Adjust grid sizes to prevent EntityHeader elements from wrapping

- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/NotificationCenter/PastDue.tsx
- packages/manager/src/mocks/serverHandlers.ts
Going to add live data to the Dashboard notifications section in chunks. This is the Balance banner. You'll have to fake a positive balance to see it (the mocks are set up to give you a balance of $50 if you use them).
On my Macbook display (none of my other monitors) the focus ends up jumping down to halfway down the view. Is this happening for anyone else? Any ideas why?
> CMR: Add balance check and invoice request to PastDue.tsx

- packages/manager/src/assets/timezones/timezones.ts
This is a simple fix pointed by a user.
Although i have a larger concern about the fact that we use a constant table in assets while this is mostly built in luxon (and was in moment) which is why this bug was not fixed by the update of these libraries.
> fix brasilia time to GMT-3

- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
Suggestion from @WilkinsKa1 to hide the search helper text (with tips on advanced search techniques) for large accounts, since the fancy-pants is:linode stuff won't work with API search.
A large account (test #1 for instance) should not display the helper text in the search bar, normal accounts still should. Please check both CMR and non-CMR.
> Hide search tips for large accounts

- MOCKING_DATA.md
- packages/manager/src/components/Dialog/Dialog.tsx
- packages/manager/src/components/Dialog/index.tsx
- packages/manager/src/components/Link.tsx
- packages/manager/src/features/Profile/Settings/PreferenceEditor.tsx
- packages/manager/src/features/Profile/Settings/Settings.tsx
Since [user preferences are tied to OAuth Clients](https://developers.linode.com/api/v4/profile-preferences), to change Cloud Manager preferences you must grab the short-lived token from the app and use that to curl. 
This adds a secret "user preference" editor directly in Cloud, accessible by going to `/profile/settings?preferenceEditor=true`. The editor is pretty simple; it allows you to enter arbitrary JSON and submit it (validating that it's valid JSON first). This makes it easier to quickly edit preferences when developing features that depend on it.
> Utility/Easter Egg: user preferences editor

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
Follow-up to https://github.com/linode/manager/pull/6628 -- add widths to Configs table columns to eliminate table jump upon Config load and populating of the table with data.
> [CMR] Configs table column widths to prevent table jump

- .gitignore
- packages/manager/src/containers/withFeatureFlagConsumer.container.ts
- packages/manager/src/dev-tools/DEV_TOOLS.MD
- packages/manager/src/dev-tools/FeatureFlagTool.tsx
- packages/manager/src/dev-tools/dev-tools.css
- packages/manager/src/dev-tools/dev-tools.tsx
- packages/manager/src/dev-tools/load.ts
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Dashboard/Dashboard.test.tsx
- packages/manager/src/features/Dashboard/Dashboard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
- packages/manager/src/hooks/useFlags.ts
- packages/manager/src/index.tsx
- packages/manager/src/store/index.ts
- packages/manager/src/store/mockFeatureFlags/index.ts
- packages/manager/src/utilities/testHelpersStore.ts
Following the lead of https://kentcdodds.com/blog/make-your-own-dev-tools.
This adds "custom dev tools" to Cloud. So far it only supports feature flags (and only CMR). To do this, I created a new slice of state, `mockFeatureFlags`, which the dev tools dispatches actions to when flag toggles are checked.
Both feature flag providers – the HOC and the hook – subscribe to this state and override the real feature flags with the mock feature flags.
The method of enabling the dev tools is the same from the blog post. They are enabled by default when running locally, and disabled by default when the prod bundle is built.
**This means the dev tools will be accessible in production by adding `?dev-tools=true` to the URL.** I think this is fine useful, but we should be mindful of what's allowed in …
> Custom dev tools

- packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
We were explicitly passing `is_public: false` when creating a StackScript (which is not necessary as it defaults to false), and when I combined create and edit forms a few months back (part of the save progress work) this started being passed when editing a script, as well. This is never necessary, and passing `is_public: false` to a script that's already public results in an error, since you can't un-publish a StackScript. I removed this part of the payload.
Please make sure that creating and editing scripts works correctly, with both public and private scripts.
> Don't pass is_public when creating or editing a StackScript

- packages/api-v4/src/account/types.ts
- packages/manager/src/MainContent.tsx
- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
Use existing isFeatureEnabled logic so that Firewalls will be
displayed if *either* the feature flag in LD is on *or*
a user's account.capabilities array includes Cloud Firewall.
This allows us to support a public beta, which is generally managed
by adding customer tags rather than through LD. In addition, while
we display the section if the LD flag is active, the API is working on 
the customer tag, so that the section is unusable for someone if
we only turn on the LD flag for them.
The update to account.capabilities is available in dev. To test, use dev services, turn the LD flag off. Please test all permutations:
In dev, Firewalls should always work, with or without the LD flag. (account.capabilities is true there for all users)
Against prod services, Firewalls should ONLY work with …
> Adjust Firewalls flag logic

- packages/api-v4/src/account/types.ts
- packages/api-v4/src/profile/profile.ts
- packages/api-v4/src/profile/types.ts
- packages/manager/src/factories/events.ts
- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/NotificationCenter/Community.tsx
- packages/manager/src/mocks/serverHandlers.ts
Request events since user last logged in and extract out the `community_like`'s, `community_question_reply`'s, and `community_mention`'s to add to the "Community Updates" section.
I added some mock data which you can use for testing by enabling the mock service worker in your .env file.
> M3-4308: Community Updates in Dashboard Notifications

- packages/api-v4/src/profile/types.ts
- packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
- packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
This fixes a bug where the `/profile/tokens` page crashes when you have an OAuth token with an expiry of `null`.
Our types (and the API documentation) wrongly assumed that “expiry” was always a string, so TypeScript hadn’t caught this.
If you want to test this for real, you’ll need to create a private OAuth client (authorization flow) and grab a token (it's pretty easy, just follow: https://developers.linode.com/api/v4/#o-auth)
Or, you can mock an expiry of `null` using your favorite method.
> M3-4381: Fix OAuth Table bug

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/NotificationCenter/NotificationContext.ts
CMR's notifications drawer/dashboard center share the same set of events, which are different from the events we store in Redux. (in short, we show all events in certain categories since the user's last login, whereas in Redux we store the last ~100 events on a user's account regardless of login status).
Since the two are separate in the component tree, and we don't need the usual set of Redux actions, I decided to make a simple context to allow the drawer and dashboard to share data.
The only place using this data atm is the Community Events section of the Dashboard Notification center. You may have to use the mock server to have events in this category; but the behavior of that section should be unchanged from develop.
> M3-4310 CMR: Notification context

- packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts
creates an e2e that will mock linode+FW+regions data to see if the UI hides incompatible firewalls from the migrate DC list
This test will really only be useful onde we implement the change in the UI and uncomment the line on london
> adding test for linode migration with firewall

- packages/manager/src/components/Table/Table.stories.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/TableWrapper_CMR.tsx
Adding group by tag toggle and list/grid view toggle to the Linode table header for CMR.
- Non breaking change ('update'
> M3-4292 Add "Group by tag" toggle to Linode Table

- packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
- packages/manager/src/features/Billing/PdfGenerator/utils.ts
currently it seems that we hide the tax id of a customer if we do not have a tax agreement with this country.
But customer are requesting that we show this, which we do in the admin tools generated invoice
*check jira ticket*
> always show tax id of customer in invoice if available

- packages/api-v4/src/account/types.ts
- packages/manager/src/__data__/events.ts
- packages/manager/src/eventMessageGenerator_CMR.tsx
- packages/manager/src/factories/events.ts
- packages/manager/src/features/Events/EventsLanding.test.ts
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- packages/manager/src/features/NotificationCenter/PendingActions.test.tsx
- packages/manager/src/features/NotificationCenter/PendingActions.tsx
- packages/manager/src/hooks/useEvents.ts
- packages/manager/src/store/events/event.helpers.test.ts
- packages/manager/src/store/events/event.reducer.test.ts
- packages/manager/src/utilities/eventUtils.ts
- packages/manager/src/utilities/getEventsActionLinkStrings.ts
Pending Actions section of the Dashboard/Notification drawer. The designs specify a different event message format than we use currently, so I had to patch data together from a bunch of places.
The spec is a little vague (see Jira ticket); this section is intended to display long-running actions. I had to do individual handling for all such actions, and made a few judgment calls. For example: volume creation technically has progress events, but it is generally extremely fast and I didn't include it here. If you see anything I missed, or disagree with any of my assessments, please say so!
> M3-4310 CMR Notifications: pending actions

- packages/manager/src/components/EntityTable/types.ts
- packages/manager/src/features/Volumes/RenderVolumeData_CMR.tsx
- packages/manager/src/features/Volumes/VolumeTableRow_CMR.tsx
- packages/manager/src/features/Volumes/Volumes.tsx
- packages/manager/src/features/Volumes/VolumesActionMenu_CMR.tsx
- packages/manager/src/features/Volumes/VolumesLanding_CMR.tsx
~~Converted `Volumes.tsx` to a function component; tweaked logic in `VolumesLanding_CMR.tsx` to show proper conditional formatting and sections.~~
Separate the VolumesLanding view from the Linode-level list of Volumes.
Linode-level list of Volumes (Storage tab) coming in follow-up PR.
> M3-4351: CMR Table Styles for Volumes Landing page

- packages/api-v4/src/support/support.ts
- packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- packages/manager/src/features/NotificationCenter/OpenSupportTickets.tsx
- packages/manager/src/features/Support/SupportTickets/TicketList.tsx
- packages/manager/src/features/Support/SupportTickets/ticketUtils.ts
- packages/manager/src/hooks/useNotifications.ts
- Add request for support tickets to OpenSupportTickets.tsx
- Add function to convert SupportTicket[] to NotificationItem[]
- Fix getTickets return (missing the then(response => response.data) we
use everywhere else)
- Refactor NotificationItem.tsx to allow a loading state. This got messy
so I extracted a ContentBody component.
Still to come:
> M3-4310 CMR: Support Tickets and loading state

- packages/manager/src/utilities/formatDate.ts
Fixes unit tests
if the userTimezone is not defined or empty or incorrect we default to 'utc', date API format.
**If we want to default to the local zone as suggested done in this PR, we would have to check this is the behavior intended in a few tests and the app itself, as we would default to this but this would not set the userTimezone in the API**
> fix default zone if no user timezone

- packages/manager/src/components/Tag/Tag_CMR.tsx
- packages/manager/src/components/TagCell/TagCell.tsx
- packages/manager/src/components/TagCell/TagDrawer.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
Updating CMR tag styles (please view the prototype to see how the hover state should look):
This updates their styling in Linodes table, Linode detail header (both grid and details view), and the Tag drawer. Please let me know if I'm missing a location where these should be updated!
> M3-4302 CMR Tag Styles

- packages/manager/src/components/EntityTable/EntityTableHeader.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallDeviceActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu_CMR.tsx
Changes to the Firewall ActionMenu items and fixes the headers that are showing up on mobile (as a result, this also fixes it for domains)
> Fixes for responsive Firewall Tables

- packages/manager/src/features/Volumes/VolumeTableRow_CMR.tsx
Removed classes setting widths of label and size columns; this was unnecessarily overriding widths being set with `headers` in the new RowComponent/EntityTable pattern and resulting in the "Attached To" header wrapping.
> [CMR] Adjust column widths for Volumes table

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
- packages/manager/src/features/TopMenu/NotificationButton.tsx
- packages/manager/src/mocks/serverHandlers.ts
- Hook up event context to NotificationDrawer so it gets real events
- Update the count next to the bell (still in progress)
- Removed temporary community event mocking from serverHandlers
(mocking events like that causes pileups from our normal events polling
and so can't be left as a normal part of our mock server)
> CMR Notifications: Add context to Drawer

- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeNews.tsx
As per the designs, add a banner below the Notification section on the Dashboard with info about our most recent release and a link to the release notes (GitHub release). This banner will be made dismissible in a follow-on PR.
A little farther down the road, there will be some "flavor text" included (see designs for an example) but I don't see a plausible way to set that up before the internal beta starts, so holding off for now.
> CMR: Add static banner to Linode changelog

- packages/manager/src/utilities/ssh-fingerprint.test.ts
- packages/manager/src/utilities/ssh-fingerprint.ts
Customer reported that their SSH key fingerprints (at /profile/keys) were displayed incorrectly. In fact, the same fingerprint
was displayed for 2 different keys.
Our fingerprint() function was borrowed (copy/pasted) from an obsolete NPM library, from back in the days when only 
RSA and DSA were available as signing algorithms. As a result, the user's Ed25519 keys were breaking the logic.
I'm using a...much simpler approach. Seems to work for multiple key types generated with `ssh-keygen`, but needs more investigation.
Add an SSH key to Cloud, and check that the fingerprint shown at profile/keys matches the output of `ssh-keygen -lf $1 -E md5;` where `$1` is the path to your public key.
> M3-4401 Fix SSH fingerprints 

- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
When enabling backups from either the Linode action menu or Linode
detail /backups tab, we didn't ask for confirmation. Since this is a billing
change, we should show a confirmation modal in these cases. This is especially
true now that we're using Reach components for the action menu.
This was supposed to be a small change, but our pattern here was janky. When a user
clicked the action menu for Enable Backups, we were:
1. Redirecting to /backups
2. Passing router state such that
3. in the cDM of LinodeBackups, we called enableBackups() automatically
if the state had been passed.
In the new pattern, we'll use a single confirmation dialog, reused in both locations.
When the action menu is clicked, it will:
1. Open the dialog
2. The dialog can be submitted, enabling backups
3. Once that's …
> M3-4373 Confirm enabling backups

- packages/manager/src/App.tsx
- packages/manager/src/components/DownloadCSV/DownloadCSV.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.test.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/SecuritySettings.test.tsx
- packages/manager/src/features/Profile/AuthenticationSettings/SecuritySettings.tsx
- packages/manager/src/features/TopMenu/UserEventsMenu/UserEventsMenu.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/ActivitySummary.tsx
- packages/manager/src/utilities/eventUtils.ts
- packages/manager/src/utilities/sanitize-html/sanitize-html.test.ts
The original ask was for the Firewalls feature, but I went ahead and updated our terminology for user-facing and CM-controlled code for whitelist/blacklist to be allowlist/blocklist based on the guide here: https://tools.ietf.org/id/draft-knodel-terminology-00.html#:~:text=Replace%20the%20oppressive%20term%20%E2%80%9Cblacklist,suggested%20alternatives%20at%20Section%201.2 
> Updating language to 'allowlist' and 'blocklist'

- packages/manager/src/eventMessageGenerator_CMR.tsx
- packages/manager/src/features/NotificationCenter/PendingActions.tsx
- packages/manager/src/features/NotificationCenter/RenderEvent.test.tsx
- packages/manager/src/features/NotificationCenter/RenderEvent.tsx
- packages/manager/src/features/NotificationCenter/eventQueue.tsx
Feedback from design was that in-progress actions in the Pending Actions section of the Dashboard/drawer should not disappear after completion but instead remain in the section marked as "completed".
No design for this scenario so I'm winging it a bit, feedback welcome. Also, the API really doesn't have the concept of an event queue, which is what this is; we want to display new in-progress events as they come in, and move them to completed as they finish. To do this, I added a reducer which keeps track of the in progress events and moves them to a completed state once they've finished. Logic here seems to work but could probably be improved, feedback welcome for this as well.
Load the dashboard and/or Notification drawer and trigger a bunch of progress events. Try to get a few events to …
> M3-4310 completed progress events

- packages/manager/src/features/NotificationCenter/NotificationContext.ts
Doesn't affect our display of events, but as a good-practice thing it's nice to do. Once we've finalized what events we actually need, we can filter our request so we're not marking things as seen unless we've actually shown them to the user.
> Mark events as seen when requesting in the notificationContext

- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/types.ts
As promised, un-break the Enable Backups action from the Linode action menu. I ended up removing the redirect to the /backup tab after enabling succeeds; there are so many places where the action menu can be found now that in some of them at least being redirected would be jarring. Additionally, we used to redirect to Linode Detail for many of the actions in the menu, but since we're not doing that anymore this would be the odd action out. Happy to add that back in if needed.
Please enable Linodes from all possible action menus (dashboard, detail header, grid view, list view)
> M3-4373 CMR: Backups enable from Linode action menu

- packages/manager/src/features/StackScripts/stackScriptUtils.ts
- packages/manager/src/store/linodeCreate/linodeCreate.reducer.ts
To test this bug, navigate to `/StackScripts`, select a StackScript and click 'deploy new Linode' (either from button or action menu). Notice you are redirected to marketplace instead of StackScript selection. 
In this PR, that link is adjusted to go straight to StackScript tab with the proper StackScript selected. There was an additional side effect once this was fixed, which was StackScripts were still considered `fromApp` for the docs logic, and so a long list of docs would show up (those should only be present for one-click apps). This is fixed here as well.
> Hotfix/StackScript linking & create from setup

- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
Based off some feedback in the project channel, we updated maintenance information to live inside the tooltip to reduce the size of the table cell. There will still be a scroll present on larger screens because the table exceeds the 1280 width, but it's not as long as it was before. Please note I did add a fake maintenance date to this PR to ease testing, will of course remove that pre-merge.
> CMR Linode Table Adjustments

- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
NodeBalancer tabs were expecting an exact match in the routeName to render any specific tab's content. This PR updates the index to check for routeName matching but default to 0 (or first tab) if the route doesn't match exactly. Also updated the breadcrumb props as a consequence.
Please test the various places one can link to a NodeBalancer detail page- dashboard, landing, etc.
> HOTFIX: NodeBalancers- defaulting tabindex to 0 if path doesn't match tab routeName

- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
Resolves the console error when you rescue a Linode. Note that this PR does not fix the actual navigation; when rescue is successful, you are no longer taken to /summary. That fix is more involved and probably not necessary for this hotfix. Discussion to follow.
To test: Boot a Linode into Rescue mode with the console open. In production, there is an uncaught error. Here nothing should break.
> Add withRouter to LinodeRescue

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/types.ts
Small oversight that was causing a glitch. UDF data wasn't included in the default state, so it wasn't being reset on tab change. If you went to the Marketplace tab, selected an app, then went to a different non-StackScript tab and submitted the form, `stackscript_data` was included in the API request, causing an error.
1. Open the Linode create flow
2. Navigate to Marketplace
3. Select an app that has UDFs (Wordpress is fine)
4. Navigate to Distributions
5. Submit the form normally
6. Observe: on develop, the request to the API includes stale data, and an error is displayed ( Requires stackscript_id for StackScripts). Should be fixed in this branch.
> Clear UDF data on tab change

- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
To recreate this issue, navigate to  `/linodes/create?type=One-Click`, select Wordpress, and try to edit email field, and admin username field in the UDF panel- in prod, updates to either input is wiping out the other. In this PR, this should no longer occur and creation of a WP one-click app should be successful.
I mostly fixed this by switching this component back to a class-based component (for now) and removing the repeat content we no longer need in lieu of the tab refactor work (in prod but not impacting to this bug)
> Hotfix: App & Stackscript Creation bug

- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Dashboard_CMR/LinodeNews.tsx
Designs for the link to the most recent Cloud changelog on the dashboard
included possible "flavor text" summarizing the release changes. Decided
that the best way to do this is through LaunchDarkly. If the version
of the changelog flag matches the currently deployed version, the notes
are shown. If the flag is off, or the versions don't match, nothing
is displayed. This way, the display is safe: if we forget to write
a message for a given release (which seems very likely), nothing will
go wrong and no incorrect information will be displayed.
The downside of this is that we're once again relying on LD as a
pseudo CMS. Especially given the cost of the service, we shouldn't
be increasing our reliance on it for non-flag-related things.
Play around with the version and text in the LD …
> M3-4310 Flavor text in LinodeNews banner

- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Added inputProps in the "Ticket Title" TextField to restrict character entry to 64 characters. This stops the user from entering more than 64 characters (which is currently disallowed; they will receive an error if they try to submit a title of longer length).
> PIE-1578: Update SupportTicketDrawer.tsx to enforce 64 character limit in text field on Ticket Summary

- packages/manager/src/features/Dashboard_CMR/LinodeNews.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/store/preferences/preferences.actions.ts
Use preferences to make the Linode News banner dismissible. Needs to be rebased after #6748 is merged.
> Change: Make Linode News banner dismissible

- packages/manager/cypress/integration/account/change-username.spec.ts
- packages/manager/src/features/Users/UserDetail.tsx
Type:
bugfix: M3-4437
The bug is a little weirder than not being able to change a username from the `account/users/<username>` page. You actually can make changes. Currently you can make exactly one change, but it won't update the UI. For example, if your username was `natedukatz` and you focused on the username table view and then typed `backspace`, `a`, `b` and then clicked save, the username would change to `natedukatzb`. or if you were to type: `a`, `b`, `backspace` then save, the username would change to `natedukat` from the original username (`natedukatz`). In other words, whatever the last thing you typed before saving is the only change that will take effect.  I poked around in the user pages for a while and this is what I traced it back to, though I'm not 100% positive why this …
> Can't edit username in account/users

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- packages/manager/src/store/preferences/preferences.actions.ts
Add "chronological view," which is all the things that would be in the drawer in a single giant chronological list rather than notification groups. The user's choice is stored in user preferences.
To test, you'll have to mock the various things that can cause notifications. Unfortunately there's no single way to handle every type of event, so you'll need to be creative. Some suggestions:
- Use a dev account for the support tickets
- Use the cli to trigger a bunch of boots/create events for progress events
- Use prod test account 4 and remove the time filter from the API request in NotificationContext.ts.
I think the useEffect logic is robust enough to spamming it (toggling the view back and forth repeatedly), but please have fun verifying this.
> Notification drawer: chronological display

- packages/manager/cypress/support/ui/constants.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
The URLs were mentioning a "subtype" parameter which appears to be deprecated at this point. Removing the existing "type" parameter and changing the "subtype" parameter to "type" seems to fix this.
Confirmed to work with the expected results in my locally deployed Cloud Manager environment. You should be able to replicate these working results on your end.
> M3-4461 -- Fix params for new-Linode backup restoration URLs

- packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
- packages/manager/src/features/Domains/DomainDetail/index.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Domains/index.tsx
- packages/manager/src/hooks/useDomains.ts
- packages/manager/src/store/domains/domains.requests.ts
For historical reasons, DomainsDetail pages were relying on a getAllDomains() request from domains/index.tsx (the routing page for both landing and detail pages).
A change I put in 2 releases ago means that for large accounts, we no longer getAll() from the routing page (since this crashes the app for v large accounts), and instead relies on API pagination in the landing page table. 
The detail page doesn't have this pagination logic (obviously), and as a result no request for domains was being made. In addition, since the large account logic doesn't touch Redux, the Details page (which reads state from Redux) had no data to look at even when navigating from the landing view. Due to quirks of the routing logic, this meant an infinite loading spinner for anyone on a large account …
> M3-4460 Make getAllDomains request from inside Domains landing

- packages/manager/cypress/support/ui/constants.ts
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
- packages/manager/src/store/linodeCreate/linodeCreate.reducer.ts
This PR addresses the links to create flow that determine the params needed for preselection in the Create flow, focusing on Images and Clone flows. Please note the work for backups references was addressed here: https://github.com/linode/manager/pull/6805 
To test: 
• Select 'Deploy New Linode' from an Image action menu -> should take you to the Images tab in the create flow with that particular image selected. 
• Select 'Clone' from a Linode action menu  -> should take you to the Clone tab with the intended Linode preselected.
> For Release: Fix params for new Linode from Clone, from Image

- packages/manager/src/utilities/ga.ts
Following discussion w/ Market we would want to reduce the hits on GA to avoid reaching our limit,
As a starting point to avoid reaching this limit We can cut the theme related `sendEvents`
We will further discuss with marketing how to rationalize our use of GA events.
If this change is not affecting anybody in the long term we will simply delete this code, not just comment it.
> reduce GA hits by cutting theme events

- package.json
- yarn.lock
** this is a quick fix, the better fix is to upgrade yup to v0.29.5 but this raises a lot of type errors **
https://snyk.io/vuln/npm:property-expr has to be upgraded to 2.0.3 or above
This error scanned by snyk
> force resolution of property-expr to 2.0.3 due to vuln

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
> M3-4441: Tweaks to Linode Storage tab

- packages/manager/src/store/linodeCreate/linodeCreate.reducer.ts
These were originally removed for cleanup, but these actually determine what should be conditionally hidden in the UI. To test, can compare against staging:
• Try deploying a new Linode from clone. Note that on staging, the access (password) panel is displayed. In this PR, it should be hidden but preselection of clone selection will persist. 
• Try deploying a new Linode from backup. Note that on staging, the access panel and region sections are displayed. In this PR, those sections are hidden and preselections still persist.
> Adding type back for determining createType

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
Fix to avoid click on label to return not found
I do not really like the fix though as it change the page look, any idea?
https://www.loom.com/share/8525fa39553949e58be23296151a1d64
> fix link when clicking on label link in details

- packages/manager/src/features/Dashboard/DashboardCard_CMR.tsx
- packages/manager/src/features/Dashboard/ManagedDashboardCard/ManagedDashboardCard_CMR.tsx
- packages/manager/src/features/Dashboard_CMR/DashboardNotifications.tsx
Basically what the title says ☝️ 
Make sure managed is enabled in order to see the card and I made some minor styling changes to make it better match the CMR styles
- Adding a white background to the title and "View Details" link
- Making the padding/margin match the other Dashboard components
Before:
After:
> [CMR] M3-4472: Move ManagedDashboardCard to Dashboard

- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
The labels for graphs on the Linode Detail view were previously hidden for mobile so I unhid them, changed the orientation of them to match the data and repeated the labels for each data set
> M3-4004: Graph labels hidden for mobile

- packages/manager/src/features/Domains/DomainsLanding.tsx
We display a banner to users who have Domains but not Linodes, letting them know that their Domains aren't being served. This banner is sandwiched between the CMR table header and table, which looks weird. Moved it above all the headers. 
I moved an error Notice while I was at it; I'm not sure it's possible for this error to ever be displayed, but maybe I'm reading the logic incorrectly. Had to hardcode to test it.
Have at least one Domain and exactly 0 Linodes on your account, and go to Domains landing. Please check with and without CMR.
> M3-4486 Fix: Move domains banner above table

- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
Before:
After:
Try changing a firewall's name to something illegal (add whitespace for example) using the editable breadcrumb on the Firewall detail page.
> Prevent error message overlap on Firewalls detail

- packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
Some background: Please note there are plans to make additional adjustments to this section post-CMR to more closely align with the new CMR patterns, but as John pointed out this is a complex part of the UI. Being this close to CMR's initial beta release, it is not worth adding any additional risk with this work.
**To view**: navigate to a Linode details page,  go to ‘Configurations’ tab, select ‘Clone’ from action menu. This will navigate you to an independent page for cloning a config/disk to a Linode. You should see the CMR header instead of the 'old' header UI.
> Adding CMR header to the config/disk clone landing

- packages/manager/public/index.html
This PR makes it so that NewRelic is only loaded in production builds. 
By default HTMLWebpackLoader uses a Lodash-flavored EJS loader, so we can use conditionals like this right in `index.html`. See the [HTMLWebpackLoader]( https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md#1-dont-set-any-loader) docs for details. Also see https://github.com/facebook/create-react-app/issues/3112#issuecomment-328829771.
**To test**, please check both development and productions builds (`yarn up` and `yarn build`). Open up dev tools and look for the NewRelic script. It should only be loaded in the production build.
> Load NewRelic script only in production build

- packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
This fixes an issue with the StackScript Landing tabs. Two things were happening:
1. The handleTabChange function was happening on every keystroke from the search bar, resulting in a “Cannot read property 'category' of undefined” error (reported via Sentry).
2. The query string was not being properly updated when switching tabs.
These things were happening because the `handleTabChange` prop was incorrectly being passed to `<TabPanels />` instead of `<Tabs />` in TabbedPanel.tsx.
This also fixes the fact that the Select Plan panel wasn’t resetting in the LKE “Add a pool” drawer when switching tabs. 
To test, go to the StackScript landing page and experiment with the search bar. Please also check the LKE "Add a Node Pool" drawer, and tab functionality …
> Fix tab change handler

- packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts
- packages/manager/src/factories/firewalls.ts
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
- packages/manager/src/features/Firewalls/shared.test.ts
- packages/manager/src/features/Firewalls/shared.ts
Apparently the value we were sending to the API for "Allow All IPv6" (`::0/0`) can possibly break things on Debian 10. Use the correct value (`::/0`)
> Change: All IPv6 for Firewalls should be read as ::/0

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
If a user uses the API to manually set their Addresses field for a rule
and leaves either ipv6 or ipv6 undefined (instead of an empty array, which
is how we handle this), the app will crash when trying to open the edit drawer.
Not sure that `undefined` should be a valid value here, but since the API allows
it for now we should handle the edge case.
To test: set a firewall rule's `address` to have either ipv4 or ipv6 be an array of strings, but the other undefined. On develop, the app will crash when opening the Edit rule drawer. This should fix it.
> Firewalls: Fix handling of empty IPv6 responses

- packages/api-v4/src/firewalls/firewalls.schema.ts
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
- packages/manager/src/features/Firewalls/shared.ts
Confirmed with Jott that none of our templates should include outbound rules. (As an example, if you create a firewall with the SSH preset, you'll be able to ssh into your Linode but things like `apt-get` will fail.)
~This will crash until #6827 is merged.~
> Change: Don't set outbound rules for firewall presets

- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
So this is to fix the logix to compute the tab index based on what processes are running on the client machine. in a client case mysql was not rendered (tabindex null) due to a case not handled by the previous code
see ticket M3-4491
> fixes mysql tab not rendering if not nginx

- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
Labels are not required when creating a firewall; we reflect this in our schema, and explicitly replace an empty string with `undefined` when submitting the form. However, the textfield itself still is labeled as "required", which is confusing.
> Change: Firewall labels are not required when creating a Firewall

- packages/manager/src/dev-tools/EnvironmentToggleTool.tsx
Fixes a console warning coming from the environment switcher:
> Remove console warning from env switcher

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
Several Linode screens that used to have dedicates routes now just feature their content in modals (/resize, /rescue, etc.).
This makes URLs to those screens backwards compatible. Now, visiting `https://cloud.linode.com/linodes/:id/resize` will take you to the details page with the Resize Modal already open (same for the other routes).
We have at least one link to one of these screens within Cloud Manager, and I imagine a lot of these links are floating around docs, etc.
To do this, I used the `useRouteMatch` router hook (new to our codebase), which I think works really well.
**To test,** try out the new routes and existing routes within Linodes (details, list, CMR, non-CMR, etc).
> M3-4483: Routing for Linode Modals

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
This came up via internal feedback- the copy on the FW rules page was a bit misleading from actual functionality for Firewalls. I also made an adjustment to the breadcrumbs. The exact copy is still TBD, but wanted to get eyes/feedback on this sooner than later.
> Firewall copy needs clarification

- packages/api-v4/src/regions/regions.ts
Fixes the issue reported in https://github.com/linode/manager/issues/6774.
As far as I can tell, this method isn't currently used in Cloud Manager code. You'll need to import `getRegion` somewhere to try it out.
> Fix type of getRegion JS Client method

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
I introduced a change [here](https://github.com/linode/manager/pull/6594/files#diff-117f855269a2f760c3c15da2fb97afd4R307) which meant that the “Group by Tag” toggle setting would be ignored if there are Linodes with pending maintenance. This was to ensure Linodes with maintenance always appeared at the top of the list.
We’ve gotten a lot of feedback from customers that are unhappy with this behavior. In retrospect, I can see how this is behavior is frustrating.
This PR reverses that "feature". I figure with the upcoming changes to the CMR dashboard, Linodes with pending maintenance will still be plenty visible.
**To test,** you'll need to mock a maintenance notification. Run the app with MSW, and either comment out the `/preferences` handlers, or change L156 of serverHandlers.ts to this: …
> M3-4383 Always honor Linodes "group by tag"

- packages/manager/src/store/linodes/linodes.reducer.ts
- packages/manager/src/store/store.helpers.tmp.ts
Previously, a failed request to get one Linode set the Redux error state (i.e. linodes.error.read). This meant that, for example:
1. Navigate to /linode/instances/hello/
2. Observe the 404 page.
3. Navigate to the Linodes List page.
4. Observe: "Not found" error.
This removes the setting of that error, which AFAICT isn't being used in this context anywhere.
I went through our Redux code to see if this issue was happening with other entities, but didn't find anything.
To test, please verify the bug fix with the steps above. Also please check general Redux-y Linodes things around the app (simulating loading failures, updating Linodes, etc.) to check for regressions.
> M3-4382: Don't set Redux error when "getOneLinode" request fails

- packages/manager/src/utilities/useTimezone.ts
The Issue History drawer was crashing on prod test account 4. This was happening because the timezone on this account is set to `""` (empty string). The `useTimezone` function in use by the drawer gets the raw value (defaulting to GMT if undefined), and didn't make sure it was a valid timezone before parsing, hence the crash. 
To fix this I modified useTimezone to call `getUserTimezone()`, which ensures the timezone is valid. Feel free to disagree with this behavior. A case could be made for `useTimezone` returning _whatever the user has set_, though it seems more useful to ensure the zone is valid. To get the raw value, a consumer could always use `useAccountManagement` to get profile data directly. 
To test the bug, use test account 4, or set your own timezone to `""` with the API. Open …
> M3-4477 fix: Managed Issue Drawer crash

- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
This error was being reported via Sentry. AFAICT this was happening when a user clicks the error message in the Search Bar. It doesn't crash the app or anything, but this will clean up some noise.
Zooming out, it looks like _some_ of the search errors were happening when a restricted users on a large account (and thus, using the API search) uses the search bar. In this case, LKE requests return a 403, resulting in an API error, making the search feature unusable. This also includes a (hacky) fix for that.
**To test,** use a restricted user and change this line: https://github.com/linode/manager/blob/e504be951e013f733c0f4a55ca93701989a562c0/packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx#L110 to `if (true)` to use the API search method. Type …
> Fix "Cannot read property 'searchText' of undefined" error

- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
I never quite understand what the removeCrumbX is for, but in this case removing it seems to give us the correct behavior on Firewall Detail for both CMR and non-CMR.
> Fix Firewall detail breadcrumb

- packages/manager/package.json
- yarn.lock
Previously there was an issue where some HTML tags were removed instead of escaped, which led to confusing support ticket bodies (see ticket for more details). This was happening even though we have `sanitize-html` set to "escape".
It looks like this was a bug in that library. Upgrading the library fixed the issue, with no regressions as far as I can tell.
As a simple example, in production: entering `<input />` in the Support Ticket Reply box will yield an _empty_ Preview tab. In this branch, you'll see `<input />` in the Preview tab, properly escaped behind the scenes.
Note: there is still some confusing behavior in the library which @acourdavault opened an issue about here: https://github.com/apostrophecms/sanitize-html/issues/334. As an example, `<input>` yields `<input />` …
> M3-4452 Upgrade sanitize-html

- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
We had client validation that would prevent users from submitting port ranges when using the ICMP protocol for a Firewall (matching the API's validation). We got some feedback saying that allowing the user to type in ports, then only later telling them it wasn't allowed, was weird. This PR disables the ports input (with helper text) as long as ICMP is selected.
Add a rule to a Firewall; select the ICMP protocol. The ports field below it should be disabled.
> M3-4485 Change: Disable port range when selecting ICMP

- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
The grid/flex setup for Linode create regressed in the more recent create refactor. This fixes that! 
To test, compare against to develop and/or prod and shrink your screen size when on create. You should observe a collision of the main area with the checkout sidebar.
> Linode Create grid bug

- packages/manager/src/components/PrimaryNav/MobileNav.test.tsx
- packages/manager/src/components/PrimaryNav/MobileNav.tsx
This fixes a bug where hidden links were not filtered out in the Mobile Nav.
First commit is a failing unit test, second commit fixes it.
To test manually, view the MobileNav as a user without Managed. On this branch, you shouldn't be able to see the "Managed" link.
> M3-4503: Hide hidden links from mobile nav

- packages/manager/src/factories/nodebalancer.ts
- packages/manager/src/features/NodeBalancers/utils.ts
- packages/manager/src/mocks/serverHandlers.ts
This is a fun one. The basic problem here is that the "Check HTTP Path" and "Expected HTTP Body" form fields are _only shown_ when "HTTP Status" or "HTTP Body" is selected as the health check type.
As a result, if there are _errors for these fields_ upon form submission, the error message is displayed **only if one of these types is selected.** 
This scenario only happens when updating an existing config _with a check_path/body,_ because we **re-submit all existing fields on the config** when making the PUT request.
The most straightforward way to find yourself in this state:
**When editing a config:**
- Select "Check HTTP Path" as the health check type. 
- Enter an invalid HTTP Path (e.g. `/ping_me`). 
- Change the health check type to "None". 
- Submit the form. 
- Observe: since the …
> M3-4385 fix: NodeBalancer Config form submission

- packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
Move the `generalError` into a `<Notice />` instead of having it display below the LinodeSelect field.
To test, please block requests to `*attach*`, go to the Volumes landing page, and try to attach a volume to a Linode. You should see the error message below the drawer title.
> M3-4420: Tweak error message display when there's a failure in VolumeAttachmentDrawer

- packages/manager/src/utilities/ga.ts
Removing a redundant event in GA from my POv.
today we track both:
- toggle of linode action menu
- select an action in action menu
Here are the hits
Linode Action Menu	117,749
Linode Action Menu Item	111,068
we can see that except if we wanted to know how often a user ens up not selecting an option the 1st event is pretty redundant
> removing event in GA for toggling action menu

- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
Currently on devlop, when you navigate to e.g. `/linodes/:id/resize`, you are taken to the Linode Details page with the resize modal opened. When you close the modal, the URL is unchanged, so if you refresh the page the modal is opened again.
This makes it so the URL is updated to remove the `/resize` bit.
I also renamed a variable/fn for clarity.
**To test:** please try navigating directly to /resize, /rescue, /rebuild, and /migrate and closing the modal. The URL should change. Try opening those modals manually (from different places in Linode Details). The URL should not change.
> M3-4517 followup: Change URL on Linode modal close

- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.stories.tsx
- packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
- packages/manager/src/features/Domains/DomainActionMenu_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallActionMenu_CMR.tsx
- packages/manager/src/features/Images/ImagesActionMenu_CMR.tsx
- packages/manager/src/features/Kubernetes/ClusterList/ClusterActionMenu_CMR.tsx
- packages/manager/src/features/Managed/Credentials/CredentialActionMenu_CMR.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerActionMenu_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu_CMR.tsx
- packages/manager/src/features/Profile/SSHKeys/SSHKeyActionMenu_CMR.tsx
- packages/manager/src/features/Users/UsersActionMenu_CMR.tsx
- packages/manager/src/features/Volumes/VolumesActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
Please see the commit messages (pasted below) for details. tldr;
Action menus weren't closing because we were in the habit of (inconsistently)
calling e.preventDefault() and e.stopPropagation() in our action callbacks.
That is (I think) cruft left over from MUI. The Reach [docs](https://reach.tech/menu-button/#menupopover)
say that their action menus don't call the native events directly, and it seems like
our preventDefault() etc. was preventing their handlers from doing things like closing the menu.
In short, I:
- replaced MenuLink with MenuItem
- Changed the signature of onClick to match the onSelect method of MenuItem
- Deleted every e.preventDefault() to match the new typing
In the long term:
- actions that act as links can be differentiated somehow (action.href or something), and …
> M3-4506 Close action menu after action is selected

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
- packages/manager/src/utilities/formatRegion.ts
The “Unknown Region” reporting has yet to prove useful (and IMO it’s unlikely to in the future). Instead it is frequently (and noisily) reported during internal usage. This removes that exception report, and adds a better fallback for the `formatRegion` function (just display the raw value).
To test, mock a Linode with an unknown region, i.e. one not found here, and vist the Linode Networking page: https://github.com/linode/manager/blob/c16f448a82e6343eb802b26e06b4fe0e7594cb62/packages/manager/src/constants.ts#L103
> Improve handling of unknown regions

- packages/manager/src/features/Users/UsersLanding_CMR.tsx
Extremely minor change, but added an ellipsis to the "Add a User" button on the Account > Users page to be consistent with other Create/Add buttons.
> [CMR] Add ellipsis to 'Add a User' button

- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
> Fix casing of NodeBalancer breadcrumb

- packages/manager/src/features/OneClickApps/FakeSpec.ts
Renaming an OCA. This won't change anything until the StackScript name itself is updated, so you'll have to mock to test.
Please see provided patch for testing this with mocks. When mocked correctly, clicking the i icon in the marketplace view will open a drawer with details about the app.
> Change Minecraft OCA to Minecraft: Java Edition

- packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
For some reason the general error in the API token drawer was put in as FormHelperText underneath the form. This breaks our pattern for error handling, so I moved it. Made a few changes to update the patterns in the component, which is still very old (Github suggested Andrew Sauber to me as a reviewer) and could use a larger refactor.
> Improve error handling for API token drawer

- packages/manager/src/components/Table/Table.tsx
- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable_CMR.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel_CMR.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
Our non-CMR Table component had an optional isResponsive prop.
The CMR version does not use this prop, though it was copied over
in the props interface and included in many instances of the table.
However, since it isn't used anywhere, it ends up being passed down
to the underlying component as an html attribute as part of the ...rest
spread, which triggers a React console warning.
Removed isResponsive from the CMR table interface and used that
to hunt down all the CMR tables that were using it.
Please visit some CMR tables (LinodeDisks, LinodeConfigs, FirewallRules, Stackscripts) and make sure the console is clean.
Note:
One regression is introduced here; the StackScript table loses its conditional isResponsive declaration, which means under certain circumstances (I'm not 100% clear) it …
> Fix console error (isResponsive prop not recognized)

- packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/utilities/ga.ts
This consolidates the "Search" GA events, replacing the three categories ("Search Auto", "Search Select", "Search Landing") with one category ("Search"), and encoding the previous categories as actions. Example:
```
Category: "Search"
Action: "Search Select"
```
(For now, I removed the reporting of "Auto" and "Landing".)
I also removed the OCA events.
**To test,** run the app with GA (let me know if you need instructions) and verify the appropriate events are going through. Verify everything with the search bar, primary nav, and create button is working as expected.
> M3-4465 Reduce GA events

- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable_CMR.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
Similar to https://github.com/linode/manager/pull/6876, the `removeLabelonMobile` prop was an artifact carried over into `Table_CMR` from the old table, and passed to it as a prop in `BucketTable_CMR`. This PR removes the prop and does a small refactor in `StackScriptBase.tsx` to avoid TypeScript errors.
> M3-4524: Prevent removeLabelonMobile console error

- packages/manager/src/components/EntityHeader/HeaderBreadCrumb.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel_CMR.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding_CMR.tsx
Remove the white container around the table and adjust the spacing to improve the grouping as mentioned in the demo prep
> [CMR] M3-4511: Remove container around StackScript table

- packages/manager/src/features/linodes/MigrateLanding/MigrateLanding.tsx
**Edit:** this is for the non-CMR component only, so you'll need to test without the feature flag.
Because of the change I made here: https://github.com/linode/manager/pull/6838/files#diff-79f01013d6e7dec6cc15eef8a4760ee1R82, MigrateLanding no longer implicitly inherited router props. Thus the call to `props.history.push()` failed, causing an error (reported via Sentry).
To reproduce the bug:
- Migrate a Linode
- Observe: you are not redirected to the Details page, and there is a console error.
> M3-4526: Fix MigrateLanding routing bug

- packages/manager/src/__data__/ExtendedType.ts
- packages/manager/src/__data__/types.ts
- packages/manager/src/factories/kubernetesCluster.ts
- packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
- packages/manager/src/mocks/serverHandlers.ts
This is prep work to the real ticket, which is fixing calculations and display for huge LKE clusters. Thought I'd keep the PR's separate and small.
Load the mock service worker and visit a k8s cluster detail. Node pools should be displayed accurately.
> M3-4468 Update mocks for LKE cluster detail page

- packages/manager/src/features/Dashboard_CMR/Dashboard.tsx
- packages/manager/src/features/Dashboard_CMR/LinodeDashboardContent/MultipleLinodes.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDashboardNavigation.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/LinodesLanding/index.tsx
In the old days, each tab of Linode Detail rendered its own DocumentTitleSegment.
This no longer works, because:
- the tabs are sometimes rendered on the dashboard and override the segment there
- the version of LinodeDetail we use on the dashboard renders all tabs at once,
which results in a document title with all of the tab annotations in it.
Added a single title segment to LinodeDashboardNavigation that is dynamic
depending on the selected tab. The dynamic part only works on page load for now
because of a lack of communication between Reach Router and React Router
(location.history is not updated when changing tabs).
Other changes:
- Removed title segments from the individual tabs
- Added a segment to the CMR dashboard
- Removed rescue/rebuild/resize tabs from the Dashboard version of …
> CMR: Fix document titles

- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable_CMR.tsx
Fixes a regression in the Firewall rules table caused by recent changes to the OrderBy component we use for sorting table data.
Previously, modified and unmodified firewall rules were filtered
into separate lists in the FirewallRulesTable, and only unmodified rules
were passed to OrderBy. This was so that modified rules appeared unsorted
at the bottom of the list (in the order in which they were added).
This worked until recently, when changes to OrderBy caused a very
confusing react key collision. To avoid this, this commit moves
the filtering to after the OrderBy sorting.
> Filter firewall rules inside OrderBy

- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/store/kubernetes/nodePools.requests.ts
- Use getAllWithArguments rather than getAll, which was not properly
passing pagination params through to the API. This lead to weird behavior
for clusters with more than 100 node pools; essentially the same pools were
being returned twice, resulting in 200 pools being displayed.
- Add Waypoint to node pools display table for accounts with many pools
Mocking doesn't quite capture the bug for some reason, I've put a giant cluster on test account 4 for your use. On develop, you can see the summary panel basing its calcs on 200 pools (e.g. 400 cpus). This branch should accurately calculate based on what the API is returning.
> M3-4468 LKE: handling for large clusters

- packages/api-v4/src/nodebalancers/nodebalancers.schema.ts
- packages/api-v4/src/nodebalancers/types.ts
- packages/manager/src/factories/nodebalancer.ts
- packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx
- packages/manager/src/features/NodeBalancers/types.ts
- packages/manager/src/features/NodeBalancers/utils.ts
The API now supports a `Proxy Protocol` field, so this PR adds support for this field in the NodeBalancer Create and configuration change (individual NodeBalancer > Configurations tab) flows when the user selects TCP for the Protocol.
> M3-4522: Add Proxy Protocol field to NodeBalancer Settings

- packages/manager/src/components/OrderBy.tsx
Fixes a bug in OrderBy that led to the FW regression yesterday. This makes use of refs and does the equality check in the function body itself instead of useEffects, which are run _after_ render.
While I was here I again tried to get rid of this equality check with no luck. I tried storing previous values of `order` and `orderBy` but this becomes very complicated (you need to keep track of previous values on a stack) and I'm not sure the tradeoff is worth it. 
We _do_ have performance issues when sorting large lists, but AFAICT the issues come from the massive DOM tree and not the actual `equals()` calls.
> M3-4529 fix OrderBy lifecycle bug

- packages/manager/src/components/PrimaryNav/MobileNav.tsx
- packages/manager/src/components/Table/Table_CMR.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable_CMR.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx
- packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel_CMR.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.styles.ts
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/StackScripts/StackScriptsLanding_CMR.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
As I was working through this, discovered some additional fixes that I've added here (comments throughout). What has been addressed:
• Approved by Jay: StackScripts landing header/element adjustments (made to match pattern for landings with tabs such as OBJ, Managed, etc.)
• Z-indexing issue for mobile nav overlay vs page content
• Sticky header issue for tables (StackScripts on Linode Create was most noticeable offender)
• Misaligned mobile table headers on some Linode detail tabs
> Check margin around headers above tables for consistency

- packages/manager/src/MainContent_CMR.tsx
Not sure why the `overflowX` is causing StackScripts issues but I removed it
We'll need to come up with another way to prevent the app from scrolling horizontally when the viewport is either mobile or tablet
> Fix StackScript network calls

- packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
Per feedback, add an explicit list of which regions are available to our helper text ("Only Linodes in regions that support Firewalls (eg, eg, eg)").
This should work with current prod and display Sydney. You can mock a few other regions with "Cloud Firewall" in the region.capabilities array to see how it handles them.
> Use arrayToList to list allowed regions when creating or adding Linodes to a Firewall

- packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.test.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectActionMenu_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow_CMR.tsx
This adds the Object Details Drawer.
It's accessible by a new action menu item ("Details") and by clicking the row (non-CMR) or Object name (CMR).
**Note:** we're waiting on API work to be able to do the "Enable Public URL" toggle in the designs. 
Another deviation from the designs: I didn't include the "Open" link at the bottom, since clicking on the URL does the thing you'd expect.
> M3-4480 Object Details Drawer

- packages/manager/src/components/PrimaryNav/MobileNav.tsx
@tiffwong noticed in a separate PR that the disabled scroll on mobile menu activation got lost in the shuffle from some of the menu adjustments made last week. I don't love the location of this if/else, but it works because we need to be able to access the `isExpanded` prop. Open to suggestions if there's a better way to do this that will be consistent!
- Bug fix ('repair')
> Mobile Menu: Adding check to toggle overflow hidden class on body

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- packages/manager/src/features/NotificationCenter/OpenSupportTickets.tsx
- packages/manager/src/features/NotificationCenter/PendingActions.tsx
This makes it so that the new CMR notification drawer closes when you click "View history" (pending actions) or "View all tickets" (open support tickets).
> Close notification drawer on internal links

- packages/manager/src/features/Footer/Footer_CMR.tsx
- packages/manager/src/features/Footer/createMailto.ts
When on CMR, the footer link to feedback@linode.com should instead point to <new-feedback-email>@linode.com. Non CMR should be unchanged.
Will push the correct email address as soon as it's available.
> Send feedback emails to correct address if we're running CMR

- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/__data__/objectStorageKeys.ts
- packages/manager/src/components/TableRow/TableRow_CMR.tsx
- packages/manager/src/features/Account/AutoBackups.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDisplayDialog.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
- packages/manager/src/features/Profile/APITokens/utils.ts
- packages/manager/src/mocks/serverHandlers.ts
Add limited access controls for OBJ access keys. See the JIRA ticket for details.
Work for this is done, but some changes to the API for this endpoint are in the works, so marking it `wait` until that's ironed out.
To test:
Create access keys of both varieties (with and without the "Limited Access" toggle active). Check the payload and API response, if limited is not toggled, `bucket_access: null` should be sent, and that should come back from the API along with `limited: false`. If the switch is toggled, the selected permissions should be included in request and response payloads.
If you try to create a key with access to 0 buckets (select "limited access" and set all the radio buttons to "none"), you'll end up with a non-limited key--this is the bit the API has to fix.
> M3-4478 Add: access management for OBJ access keys

- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
Suggested in https://github.com/linode/manager/issues/6856.
I'm not in love with my copy... "able to enable". 😅 
@Jskobos do you have any suggestions?
> Add warning about 24 hour wait period before disabling backups

- packages/api-v4/src/account/types.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/featureFlags.ts
Add feature flag logic for VLANS. 
Flag is in Launch Darkly. It also looks at account.capabilities, but there's a bug there in the API and no one is getting 'Vlans' in their list even on dev services.
On CMR, and only CMR, you should see a VLans option in the primary nav when the flag is toggled on. The page it goes to doesn't exist yet.
> Add feature flag logic for VLANS

- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDrawer_CMR.tsx
Trying to make casing a little more consistent here - fixed a typo while I was at it
> Make casing slightly more consistent and fix typo in config helper label for automount devtmpfs

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ActiveConnections.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ActiveConnections/ConnectionRow.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/ListeningServices.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ListeningServices/LongviewServiceRow.tsx
Follow-up to https://github.com/linode/manager/pull/6914 -- the Listening Services and Active Connections table rows needed to be CMR also, along with having TableCell_CMR.
> M3-4272: Longview CMR tables follow-up

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
The offset logic in TransferHistory.tsx was creating dates
using the native JS Date object (one for the current time and one
based off the Linode's create date). These Dates were then converted
to Luxon DateTime/Intervals inside various helper methods.
This approach works fine in almost all cases, but in the case
where a Linode has recently been created, the API returns the timestamp
in UTC, which will be after Date.now() if you run them both through
new Date(). This causes Interval.fromDateTimes() to crash since the
interval end is before the start.
As a result, clicking the < on a new Linode causes the app to crash.
Using Luxon DateTimes from the start and explicitly comparing both
in UTC allows us to avoid this issue.
1. Have a Linode created in the past ~2 hours
2. Go to the Linode's …
> Fix crashing localization bug

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
When the url changes on Linode Detail, make sure we re-request IP addresses on the Network tab.
In both CMR and non-CMR, visit a Linode's network tab, then search `is:linode` in the search bar and select one of the results. On develop, the IP addresses don't update; here they should.
> Re-request Linode when id changes in URL

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
Think we got a little too fancy here:
Not sure the mobile handling here is the best, but I think it's ok.
> Prevent overflow of resolvers

- packages/manager/src/components/InlineMenuAction/index.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyMenu.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyMenu_CMR.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.test.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable_CMR.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/ViewPermissionsDrawer.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/types.ts
Add "View Permissions" to the access key action menu and open a separate view-only drawer. I went away from the ticket requirements in a few ways:
- Separate drawer: did this because juggling all the "modes" has proven to be bug-prone in the past, and the logic was getting dicey when I tried it here. There's a little duplication but not much.
- Hide table when editing: When you select "Edit label", the drawer that opens only has the label field. I did this because it was confusing to have the read-only permissions table in two different contexts, with slightly different behaviors.
- Hide label etc. from view only drawer: The ticket specified that the label input and toggle would be present in view mode, but disabled. Once I had decided to use a separate drawer, this no longer seemed to …
> Add view mode to access key drawer

- packages/api-v4/.eslintrc.js
- packages/api-v4/src/index.ts
- packages/api-v4/src/linodes/index.ts
- packages/api-v4/src/linodes/interfaces.ts
- packages/api-v4/src/linodes/linodes.schema.ts
- packages/api-v4/src/linodes/types.ts
- packages/api-v4/src/vlans/index.ts
- packages/api-v4/src/vlans/types.ts
- packages/api-v4/src/vlans/vlans.schema.ts
- packages/api-v4/src/vlans/vlans.ts
- packages/manager/src/__data__/linodeConfigs.ts
- packages/manager/src/factories/config.ts
- packages/manager/src/factories/linodeConfigs.ts
First round of JS stuff for the VLAN API methods. Creating a VLAN seems to only work in dev (no availability errors in prod). I tested the endpoints and payloads in Insomnia, see below for testing suggestions.
Includes: 
- CRUD for VLANS
- CRUD for linode/instances/:id/interfaces (creating/deleting network interfaces on individual Linodes)
- Updating payload for `/linode/instances/:id/configs/:id`, which now returns `interfaces` and allows you to POST to add interfaces to an existing config.
There are a few endpoints in the work, `vlans/id/attach` and `/detach`, which I'm leaving out for now because I don't know when they'll be merged/released on the API side.
At this point it's fine to focus on the code, response types, etc. To actually use the methods, you can import them in Cloud or …
> M3-4541 Add: VLAN methods/types to JS Client

- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
This looks to fix the issue of the Resize modal not disappearing after one confirms the plan resize at cloud.linode.com/linodes/$LINODE_ID/resize. Currently, after confirming the resize the modal hangs around, requiring the user to either click 'Cancel' to close the modal or refresh the page.
> Added isOpen: False to clear resize modal after confirmation

- packages/api-v4/src/vlans/types.ts
- packages/api-v4/src/vlans/vlans.ts
- packages/manager/src/store/index.ts
- packages/manager/src/store/vlans/vlans.actions.ts
- packages/manager/src/store/vlans/vlans.reducer.ts
- packages/manager/src/store/vlans/vlans.requests.ts
Redux boilerplate for Vlans. No tests for the reducer this time because we entirely rely on the store.helpers methods, which are well-tested elsewhere.
You can dispatch the thunks from anywhere (VlanLanding is a function component so you can use `const dispatch = useDispatch()`). Make sure the correct actions are called and the state is correct in the Redux dev tools.
> Add: Redux for VLANs

- packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketSettings.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
- packages/manager/src/features/ObjectStorage/index.tsx
This ticket is to add inputs to allow users to upload SSL certs to an object storage bucket. In order to make room for these inputs, this PR converts Bucket detail to a tabbed interface.
We may end up commenting out /access for the next release, since it isn't likely to be ready.
I hoisted a bunch of stuff from BucketDetail to the new BucketDetail/index.tsx, shouldn't affect the functionality.
> M3-4482 Part 1: bucket tabs

- packages/manager/src/App.tsx
- packages/manager/src/request.test.tsx
- packages/manager/src/request.tsx
- packages/manager/src/store/profile/profile.actions.ts
Currently we read a user's EUUID from `/account`. Unfortunately this endpoint is not available to restricted users, so the API will start returning an `X-Customer-Uuid` HTTP header with this value.
This adds a `_euuidFromHttpHeader` field to our `ExtendedProfile` type, (which is injected by Axios middleware) so that this value can be used for non-restricted and restricted users alike.
This header actually isn't accessible by JS unless it's same-origin (which is the case in Prod), so you'll need to configure your Webpack Dev Server to proxy the API... reach out for a snippet to use (you'll also need to use `testing` services).
However, do test without the proxy to see what happens if the header isn't there for some reason. Please test restricted and non-restricted users.
> M3-4534 Inject EUUID to /profile from HTTP header

- packages/manager/src/features/linodes/SMTPRestrictionText.test.ts
Parse test datetimes in UTC so they work in all environments.
> Fix SMTP tests

- packages/api-v4/src/linodes/linodes.schema.ts
- packages/api-v4/src/linodes/types.ts
- packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
- packages/manager/src/features/linodes/LinodesCreate/types.ts
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/hooks/useVlans.ts
Add an "Attach to a VLAN" select to the optional addons panel in the Linode create flow.
I'm not at all sold on the styling, and there is no design for this. Feel free to propose any style changes, or argue for a different placement entirely (e.g. in its own panel).
Create Linodes both with and without specifying a VLAN. Make sure the payment is sent correctly in each case, and that the Linode ends up being attached to the VLAN as planned.
> M3-4558 Add: VLAN attachment option to Linode create flow

- packages/api-v4/src/account/types.ts
- packages/manager/src/__data__/events.ts
- packages/manager/src/factories/events.ts
- packages/manager/src/features/Events/EventRow.test.tsx
- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/Events/EventsLanding.test.ts
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/features/linodes/transitions.test.ts
- packages/manager/src/store/events/event.helpers.test.ts
- packages/manager/src/store/events/event.reducer.test.ts
Please note that you'll need to use dev services to see the message field return for Events. Most of the time this field will be an empty string or null, which is why I placed it on the end of the row.
> M3-4535 Add "Message" column to the Activity Feed table

- packages/manager/src/features/Account/AccountLanding.tsx
- packages/manager/src/features/Firewalls/FirewallDetail/index.tsx
- packages/manager/src/features/Lish/Lish.tsx
- packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewLanding.tsx
- packages/manager/src/features/Managed/ManagedLandingContent.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
- packages/manager/src/features/Profile/Profile.tsx
- packages/manager/src/features/Users/UserDetail.tsx
- packages/manager/src/features/linodes/CloneLanding/CloneLanding.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation_CMR.tsx
When we made the switch to reach tabs, the active tab was only reflected in the UI, not in the url (unless you hard-refresh). This fixes that as you switch tabs, either via click or with keyboard, the url will be updated. This is based off work Jared had done here: https://github.com/linode/manager/pull/6757/ and converts any tab components using TabLinkList to follow this pattern (as that component is using Link from react-router under the hood). The one section I'm a little hesitant on is the Linode Create flow- this section feels noticeably slower but we're also updating create type in redux so there is a bit more complexity going on here than elsewhere. 
- Bug fix ('repair')
I looked into converting to reach-router instead, but this …
> M3-4553 Fix tab-based navigation 

- packages/api-v4/src/object-storage/buckets.schema.ts
- packages/api-v4/src/object-storage/buckets.ts
- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx
Fill in the SSL tab (which may end up renamed to Settings) with a form to allow users to upload an SSL/TLS cert
Includes: 
- JS client methods for uploading, getting, and deleting certs
- BucketSSL component
Todo: 
There were no designs for this, and I had to make a bunch of judgment calls. I decided to hide the SSL inputs if you already have a cert on your bucket, since trying to submit the form in this case always causes a "Please delete existing certs first" error. Please give feedback on the approach.
To test this properly (successfully upload a cert), you have to create a cert that's valid for the bucket. I followed a combination of these two guides:
https://www.linode.com/docs/platform/object-storage/host-static-site-object-storage/ …
> M3-4482 Add: Ability to upload a TLS certificate for a Bucket

- packages/manager/src/components/IconTextLink/IconTextLink.tsx
- packages/manager/src/components/IconTextLink/IconTextLink_CMR.tsx
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
More action menu refinements from Jay: 
• Updating styles for focus/hover states on the inline actions on details landing/details
• Removing 'View Backups' and 'Settings' actions from all Linode action menu variants
• Making 'Reboot' second action (after power on/off, before launch console for all variants)- when reviewing please note we only display 'Reboot' on powered on Linodes.
> M3-4566 CMR Action menu refinements

- packages/manager/src/features/TopMenu/NotificationButton.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
The Linode status chip on the dashboard and the notification icon on the secondary nav is being cut off. You can reproduce this on Safari and certain phones on dev and beta.
Please check different browsers and resolutions and other places that the EntityHeader is used such as Linode Details summary view
> [CMR] M3-4578: Linode status chips and notification icon cut off

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.test.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/TopProcesses.tsx
Used an absolute rather than relative path when linking to the processes tab.
Steps to Reproduce: 
1. If you visit this URL: `http://localhost:3000/longview/clients/:clientID/overview ` and click view details, it works. 
2. It doesn't work if you visit this URL: `http://localhost:3000/longview/clients/:clientID` and click view details. 
This PR should fix that.
> M3-4560 - Fixed Longview navigation bug

- packages/manager/src/features/linodes/SMTPRestrictionText.tsx
The way I was parsing the magic date for the SMTP port notice wasn't working in Safari.
To test, open the Linode Create screen in Safari as a new-ish user.
> Change date format so it works in Safari as well

- packages/manager/src/features/linodes/LinodesDetail/LinodesDashboardNavigation.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
Fixes include:
The changes for the font size in EntityHeader and linode detail tabs are in [https://github.com/linode/manager/pull/6958](https://github.com/linode/manager/pull/6958), oops
> [CMR] M3-4569: (Mostly) Linode Details Refinements

- packages/manager/src/features/linodes/LinodesDetail/utilities.ts
Use the ZoneName instead of the region ID to construct the correct Lish Link (currently in CMR the link is incorrect).
Have a few Linodes in a few regions and compare the Lish link (in the LinodeEntityDetail component) with production.
> CMR: Fix Lish link

- packages/api-v4/src/vlans/types.ts
- packages/manager/src/factories/vlans.ts
- packages/manager/src/features/Vlans/CreateVLANDialog/CreateVLANDialog.tsx
- packages/manager/src/features/Vlans/VlanLanding/VlanRow.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
`vlan.linode` is now `{ id: number, mac_address: string, ipv4_address: string }[]` instead of `number[]`.
There's also a new `created` field.
To test, use dev services.
> Update VLAN Linodes typing

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/hooks/useAccountManagement.ts
- packages/manager/src/store/accountManagement/accountManagement.actions.ts
- packages/manager/src/store/accountManagement/accountManagement.reducer.ts
- packages/manager/src/store/accountManagement/accountManagement.requests.ts
- packages/manager/src/store/domains/domains.requests.ts
- packages/manager/src/store/index.ts
- packages/manager/src/store/preferences/preferences.actions.ts
Since the API has determined that a "thing count" endpoint
is not feasible, and our existing logic (which waits for
a getAllDomains request to be triggered, then saves is_large_account
to user preferences if > 500 results come back) has caused
frustration in customers from huge accounts who don't like the
initial crash of their accounts, we need to update our approach.
I added a new Redux state, accountManagement, to the __resources
envelope. This is debatable; we could have stored this data in
a context, or added it to an existing state component. I chose
this way because it's fairly clear and our Redux structure makes
it easy to bring in thunks from other parts of the state.
In practice, the checkAccountSize thunk is called on app load.
It requests a single page of Domains (page size of …
> Change: Request Domains on load to determine account size

- packages/manager/src/features/Search/SearchLanding.tsx
- packages/manager/src/features/Search/useAPISearch.tsx
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/hooks/useReduxLoad.ts
When a user has >500 Domains, we trigger our useApiSearch() logic,
to prevent the search bar from crashing. A corner case was recently
discovered that broke this logic:
If a restricted user has access to >500 Domains, the search bar
returns an empty results list inline, and the search landing page
displays an error.
This is because restricted users, regardless of access/grants, always
receive a 403 when attempting to access /lke/clusters. This may change
at some point, but is not expected until at least 2021.
Since we were making API search requests to /lke/clusters unconditionally,
this meant that we always ended up in the .catch() block of our search
logic, and results were not displayed. (Promise.all() bails as soon as
a single request fails).
By making this particular request only for …
> M3-4563 Fix: Search results not displaying for some restricted users

- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.style.ts
- packages/manager/src/features/linodes/transitions.ts
This fixes the issue of table overflow, the result is that a longer status (such as clone) will become scrunched up, depending on the label. Unless we consider truncation, I can't think of a better way to handle for this 🤷‍♀️ Open to suggestions/feedback!
> CMR: Table too wide when cloning Linodes (status column is expanded, causing overflow)

- packages/manager/src/features/Vlans/DetachLinodeDialog/DetachLinodeDialog.tsx
- packages/manager/src/features/Vlans/VlanDetail/VlanDetail.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
- packages/manager/src/features/linodes/types.ts
Adds the "Detach" button to the Action Menu on the VLAN Details page:
Though the conditional stuff is not ideal, it's not as awful as I thought it'd be. I stuck with the existing patterns as far as opening dialogs from the Linode Action menu goes.
In a different PR, I'll do the same for the Card/Detail view.
> M3-4595 Detach Linode from VLAN

- packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu_CMR.tsx
Based on feedback that came out of demo prep, updating our logic to always display the Reboot action in action menu regardless of view context or Linode status. You should now see reboot in the following scenarios:
**Table view**: 
- in action menu, disabled if linode is not online
**Details view:** 
- in inline view, disabled if linode is not online.
- in action menu on smaller screens, disabled if linode is not online.
> CMR: updating Reboot in action menu display logic

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
This fixes a bug in production (beta) where toggling the chronological display in the Notification Drawer causes repeated `updatePreferences` calls. 
This was happening in an effect, which was being called every time preferences updated (so, an infinite loop).
> Fix repeated updatePreferences calls in Notification Drawer

- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/PasswordInput/PasswordInput.tsx
- packages/manager/src/featureFlags.ts
- packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
- packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
- packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript_CMR.tsx
- packages/manager/src/utilities/validatePassword/validatePassword.test.ts
- packages/manager/src/utilities/validatePassword/validatePassword.ts
I think our zxcvbn validation (which matches the API's) is stable enough now to remove a bunch of conditional logic that's reading a value from LD.
Please check all of our password fields (Linode creation, StackScripts, disk creation, managed credentials) to make sure we're validating as expected.
> Remove flag-based dynamic password validation logic

- packages/manager/src/features/linodes/presentation.ts
I went through the codebase and didn't see anywhere the `formatRegion()` function in `linodes/presentation.ts` was being used (the one in `utilities/formatRegion.ts` is the one used throughout the codebase), so this PR removes it from that file and deletes the now-unused imports in it.
> M3-4532: Remove duplicated, unusued formatRegion() function

- packages/manager/src/store/image/image.reducer.ts
The filter I added a year ago to prevent users from deploying from public LKE images was incomplete, and as a result if you have a private image containing "kube" it isn't available. This updates the filter.
> Make sure we don't filter private images containing 'kube'

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/RemoveVlanDialog.tsx
Fixes small oversight in https://github.com/linode/manager/pull/6981 -- renames `resetInterfaces` to `refreshInterfaces` in `RemoveVlanDialog.tsx` to be consistent with prop name for `AttachVlanDrawer.tsx`.
> Rename prop for RemoveVlanDialog for consistency

- .travis.yml
Giving this a shot to see if it improves performance of unit tests on Travis.
See: 
https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
> Use --runInBand option when running unit tests on Travis

- packages/api-v4/src/databases/databases.ts
- packages/api-v4/src/databases/index.ts
- packages/api-v4/src/databases/types.ts
- packages/manager/src/factories/databases.ts
- packages/manager/src/hooks/useDatabaseTypes.ts
- packages/manager/src/hooks/useDatabases.ts
- packages/manager/src/store/databases/databases.actions.ts
- packages/manager/src/store/databases/databases.reducer.ts
- packages/manager/src/store/databases/databases.requests.ts
- packages/manager/src/store/databases/types.actions.ts
- packages/manager/src/store/databases/types.reducer.test.ts
- packages/manager/src/store/databases/types.reducer.ts
- packages/manager/src/store/databases/types.requests.ts
- packages/manager/src/store/index.ts
Redux, a few factories, and hooks for databases and database types.
~depends on #7021 ; will rebase once that's merged.~
You can import the new hooks anywhere in a FC and make sure state is populated correctly in Redux.
> M3-4614 Add: DbaaS in Redux

- packages/manager/src/features/Vlans/VlanDetail/VlanEntityDetail.tsx
Forgot to include the ID label on the details page
> [VLAN] Add ID label to detail page

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
In the linode/networking tab. Anton reached out to say that it's perfectly valid to create a VLAN without an IP address.
> Fix: Don't filter out VLANs without an IP address

- packages/api-v4/src/databases/databases.schema.ts
- packages/manager/src/components/TagCell/TagDrawer.tsx
- packages/manager/src/factories/index.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
- packages/manager/src/features/Databases/index.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
- packages/manager/src/hooks/useDatabases.ts
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/mocks/serverHandlers.ts
Landing page for DbaaS. Thoughts:
1. The chips add a lot of boilerplate; I want to work out a way to abstract them so we don't have to go through all this for every landing page. BUT Chris has expressed that he doesn't like them, so I'm not in a hurry to put in that work until this is demoed.
2. Known bug: blocked requests to /databases/ will result in an infinite request loop. Separate PR will fix this (it also occurs on DB detail and VLANs).
3. Known issue: the delete modal should be type-to-confirm. I want to make that change in DeletionDialog.tsx, which is too large for here. I'll do a follow on.
Mocks are set up if you'd like to use them.
> M3-4613 Add: dbaas landing and row

- packages/manager/src/hooks/useReduxLoad.test.ts
- packages/manager/src/hooks/useReduxLoad.ts
This fixes a bug where `useReduxLoad` continues to make requests to a resource after if fails, so you can for example:
1. Block requests to /images
2. Go to the Images Landing
3. Observe: infinite failed request loop to /images.
This handles both EntityError and APIError[] shapes. For an example of this working with APIError[], visit the Object Storage Landing page and block /clusters.
> Fix re-request bug in useReduxLoad

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
- packages/manager/src/features/linodes/LinodesDetail/types.ts
- packages/manager/src/hooks/useExtendedLinode.ts
- packages/manager/src/hooks/useInterfaces.ts
- packages/manager/src/store/index.ts
- packages/manager/src/store/linodes/interfaces/interfaces.actions.ts
- packages/manager/src/store/linodes/interfaces/interfaces.reducer.ts
- packages/manager/src/store/linodes/interfaces/interfaces.requests.ts
Add actions, reducer, etc. for Linode Interfaces to enable data to be shared across the Linode Network and Configurations tabs easily.
> M3-4590: Store Linode Interfaces in Redux

- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeCard.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowHeadCell.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowLoading.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/transitions.ts
- packages/manager/src/store/events/event.helpers.ts
- packages/manager/src/store/linodes/linodes.events.ts
- packages/manager/src/store/middleware/combineEventsMiddleware.ts
This does three things:
- Poll events every **1.5s** during progress events instead of every **1s**.
- Don't aggressively poll for long-running events like resizing and migration.
- Don't re-request the Linode every `scheduled` and `started` event. Instead, re-request the Linode only on first of these event types, and on `failed`, `notification`, and `finished` events (with the exception of Linode Rebuild: explanation in comment).
The 3rd item caused a rough UI transition. Just after the event is `finished`(but before we've gotten back the updated Linode status from the API) the old status of e.g. "rebooting" was displayed, but the Linode wasn't considered to be in "transition", so we didn't show progress or the pending status icon.
This is because our "transition" logic _requires_ there …
> Poll events/Linodes less aggressively

- packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
Spotted by @DevDW here: https://github.com/linode/manager/pull/7041#pullrequestreview-517073193
To reproduce: 
- Kick off a Linode Resize
- Watch the Dashboard
- When the event is almost finished, you'll see `(~null)` in the progress display
To fix, I moved some things around to check for `null`.
> Fix "null" progress on CMR Dashboard

- packages/manager/src/components/AuthenticationWrapper/AuthenticationWrapper.tsx
In AuthenticationWrapper, before launching all of our requests (to
profile, account, etc.) we first check to see if we're rendering Lish,
and abort requests if so, since this data is not necessary in that
case and the requests will slow things down.
However, we were matching too casually (just checking to see if the
url contained "/lish/"), and as a result if you navigated directly
to a url like profile/lish/garbage, you'd end up with an infinite loading
state.
Matching more precisely with a regex for the actual paths used (weblish or
glish) fixes this situation.
On develop, go to localhost:3000/profile/lish/blahblah; observe the infinite loading state. Shouldn't happen here. Lish and Glish should still work normally, with no extra requests (you can check this by typing …
> Fix Lish bug

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/VlanTableRow.tsx
Add some additional logic to prevent the extra commas display bug in the Linodes column of the VLAN panel on the Network tab.
> Refine VlanTableRow logic to prevent comma visual display bug

- package.json
On my machine, this reduced unit test runs (all of them – `yarn test`) from ~500s to ~100s.
> Improve unit test speed by setting maxWorkers to 4

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Small oversight when adding the Linodes table to VLAN detail:
There are a few conditions to meet before the banner is displayed, which is why we didn't notice. Dev account 4 is set up correctly, or you can:
- Make sure managed is not active on your account
- create a Linode after managed is disabled, or cancel backups on an existing Linode
- Check local storage and make sure there is nothing in there for "backupsCTA" or similar.
- Go to VLAN detail
> hide backups CTA on LinodesLanding in VLAN context

- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/features/Vlans/CreateVLANDialog/CreateVLANDialog.tsx
Feedback from stakeholders was that the IP range field when creating a VLAN looked like it was required; we were asked to make it clear that it was optional. I cleared the default value and marked Region, the only actual required field, as (required).
> Remove default value for IP range and mark Region as required

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
Remove the transition when hovering over the Linode status filters at the top of the table
> [CMR] Remove Linode status filter hover transition

- packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Domains/DeleteDomain.test.tsx
- packages/manager/src/features/Domains/DeleteDomain.tsx
- packages/manager/src/features/Managed/Contacts/Contacts.tsx
- packages/manager/src/features/Managed/Contacts/Contacts_CMR.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList_CMR.tsx
- packages/manager/src/features/Managed/Monitors/MonitorTable.tsx
- packages/manager/src/features/Managed/Monitors/MonitorTable_CMR.tsx
Jay has asked that we make all deletion type-to-confirm, app-wide. We created a DeletionDialog component a while ago, mostly forgot about it, then I ended up using it for DatabasesLanding. Putting the two together, adding type-to-confirm to this component both matches the DBaaS designs and brings some of the older dialogs up to spec.
NOTE: by chance, this component is used in some of the places--Managed contacts etc.--where it's hardest to justify type-to-confirm. It would be easy to make this controllable by prop, say `confirmDeletion` or something. I haven't done that because Jay has repeatedly said that _all_ deletion should have this behavior. Please weigh in.
This should show up when trying to delete:
- Databases
- Domains (only from within the drawer)
- Managed monitors, contacts, …
> M3-4316 Add type-to-confirm to DeletionDialog

- packages/manager/src/features/Vlans/AttachVLANDrawer/AttachVLANDrawer.tsx
Adding a warning notice to the linode attach drawer for VLANs. Please feel free to suggest copy/placement changes.
> Add warning when attaching Linodes to a VLAN that the Linode must be rebooted

- packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.test.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
- packages/manager/src/features/linodes/LinodesCreate/SelectVLAN.tsx
- packages/manager/src/features/linodes/LinodesCreate/types.ts
For most customers the max number of VLANs you can attach to a Linode is 2, and the payload is not what you'd expect (not a list of VLAN ids) so I made this select a single-value dropdown.
Feedback received is that this is bad, so this PR updates it to a multi select.
Known issues:
- I'm relying on the API to throw an error if the user selects too many VLANs. More than 2 is rare, but it's configured on the customer record so we don't know for sure until we fire. I brought this up with Anton as a case for exposing thing limits as we're considering elsewhere.
- The error message in this case is unhelpful. I'd go so far as to call it a bug (it includes the Linode ID, even though the Linode doesn't exist yet); for this reason, I'm going to follow up on their end rather than add error …
> M3-4628 Change: allow multi-select when adding VLANs during Linode create

- packages/api-v4/src/databases/types.ts
- packages/manager/src/factories/databaseBackups.ts
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
Please consider this a glorified boilerplate for the backups table. To view, navigate to `/databases/1234/backups`. I've applied a factory to aid with testing. 
I've commented todos and notes throughout the code, but I made guesses on what we'd like to display on the table based on what exists on Linode backups/the response we get back for Dbaas backups (including actions, which currently do not work at all). Please let me know what you think. 
> M3-4602 DBaaS Detail Backups table 

- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
Cleaned up some boolean logic in AddIPDrawer. There was a case (IPv6 was selected
in the dropdown, the user did not already have an IPv6 address) where an incorrect
tooltip was displayed ("This Linode already has a private IPv6 address).
Please check all paths:
- restricted user w/o IPv6 on the Linode
- normal user with IPv6
- normal user without IPv6
- All of the above with the select unselected
> M3-4592 Fix:  IP popover bug

- packages/manager/src/eventMessageGenerator.ts
- packages/manager/src/eventMessageGenerator_CMR.tsx
- packages/manager/src/features/Events/Event.helpers.ts
- packages/manager/src/features/Events/EventRow.test.tsx
- packages/manager/src/features/Events/EventRow.tsx
- packages/manager/src/features/Events/EventsLanding.tsx
- packages/manager/src/mocks/serverHandlers.ts
No one asked for this, exactly, but I think it's helpful. I added a bit to our event message generators that uses the `event.message` API message when it's provided. Almost all events don't have one still, so the fallback (our existing logic) will usually be used. 
I also removed the Message column in the event table, since this information will now appear in the main Label column instead.
Please feel free to push back on or discuss any of this.
> Events refactor

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskRow.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks_CMR.tsx
- packages/manager/src/mocks/serverHandlers.ts
Refactor LinodeDisks so that LinodeDiskRow is a separate component. Each row now looks to see if there's a matching `disk_resize` event for the current disk, and if so shows a progress bar instead of a value for the "size" field.
The acid test, which kicked off this ticket, will be:
1. Create a small Alpine disk
2. Imagize it
3. Create a new disk from the image, specifying a size a bit larger than the image itself.
4. Observe: we display an incorrect size in the table when the creation is complete.
This is because a disk resize is kicked off in the background after the disk is created. Previously we couldn't detect the resize because no events were created, and as of Monday afternoon we still can't do much because the newly-added events don't contain information about which disk they …
> M3-4006 Add: progress bar to LinodeDiskRow when resizing

- packages/manager/src/components/Dialog/Dialog.tsx
Because the dialog title and close button stays on top of the modal, the content overlaps while the user scrolls as seen here: [https://www.loom.com/share/0d31e8c37a6c46808015915c050b0709](https://www.loom.com/share/0d31e8c37a6c46808015915c050b0709) 
To fix this, I added a background to the container containing the title and the close button
There shouldn't be any regressions since the background I added matches the existing dialog background but it can't hurt to keep an eye out in case I missed something
> M3-4623: Preventing dialog title and content from overlapping

- packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
- packages/manager/src/features/Databases/CreateDatabaseDialog/SelectDBPlanPanel.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMaintenancePanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup_CMR.tsx
- packages/manager/src/utilities/initWindows.test.ts
- packages/manager/src/utilities/initWindows.ts
Follow-up to https://github.com/linode/manager/pull/7026. Various improvements and cleanups for the Create Database modal
> M3-4603: Refinements for Create Database modal

- packages/manager/src/assets/icons/fileUploadComplete.svg
- packages/manager/src/assets/icons/uploadPending.svg
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
- packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
- packages/manager/src/themeFactory.ts
- packages/manager/src/themes.ts
Adjustments to some dark theme colors for the 'browse' button on OBJ Details and some of the file icons- also added some fixes to appease the a11y linter. 
> Visual bug with Object Storage Browse Files button (dark theme)

- packages/manager/src/events.ts
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/useGraphs.ts
- packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx
- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
- packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
The original idea here was to use the new usePolling hook to everywhere in the app that does polling. Didn't work out that way, because a lot of the polling logic is customized and not a good fit, or else in old class components. Fortunately, the underlying API is very simple so it's easy to skip polling when the page is not visible.
> Polling followup

- packages/api-v4/src/object-storage/objects.ts
- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/components/EnhancedSelect/__mocks__/Select.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ACLSelect.test.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ACLSelect.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx
- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
- packages/manager/src/features/ObjectStorage/utilities.ts
Adds ACL selection to the Object Details drawer.
- Two new methods for the JS Client.
- GET the Object's ACL when the drawer is opened.
- Allow the user the make an ACL selection.
- If they've selected "Public Read/Write" display a confirmation modal upon clicking "Save".
- Fix the EnhancedSelect mock to correctly account for the selected value
I created a new component, ACLSelect, since we'll need almost identical components/logic for Buckets.
To test an Object having a "Custom" ACL, use the s3 API directly (reach out if you need help).
> M3-4479 Object ACLs

- packages/manager/src/components/NavTabs/NavTabs.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseDetail.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
Similar to React Router's API, NavTabs now accepts a `render` prop in addition to the existing `component` prop. The new `render` prop is useful if you need more control of the props that the child component receives (as is the case with DBaaS, which I've updated here).
No existing functionality should have changed; please check the places where NavTabs is used (DBaaS, Profile).
> Small refactor of NavTabs to accept "render" prop

- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/__data__/buckets.ts
- packages/manager/src/factories/objectStorage.ts
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow_CMR.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketTable_CMR.tsx
When a user clicks the "Details" button of a bucket listed on the Buckets landing page, open a drawer for that bucket listing details about it.
The JSX and props for ACL and CORS pieces can be commented out prior to merging as those are just stubbed for now.
> M3-4646: Implement Bucket Details Drawer

- packages/manager/src/factories/index.ts
- packages/manager/src/factories/oauth.ts
- packages/manager/src/features/Profile/APITokens/APITokenTable.test.ts
- packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
- packages/manager/src/features/Profile/APITokens/APITokenTable_CMR.tsx
- packages/manager/src/mocks/serverHandlers.ts
We previously filtered results from profile/apps to remove anything
pointing at a callback url containing "linode.com". This was to prevent
us from showing "official" Linode apps in the list. However, the API
now does this, so it's no longer necessary. Additionally, a user who
has such a token is unable to revoke it. This PR removes the filtering.
It's pretty hard to get a "real" token that will test this, but you can use the provided mocks.
> M3-4650 Remove filtering of app tokens

- packages/manager/src/MainContent_CMR.tsx
The conditional was mistakenly using `props.flags.vlans`, this changes it to the appropriate `props.flags.databases`
> Fix Database flag conditional in MainContent_CMR.tsx

- packages/manager/src/components/DeletionDialog/DeletionDialog.tsx
- packages/manager/src/features/Databases/DatabaseDetail/DatabaseEntityDetail.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Domains/DeleteDomain.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
Follow-on from last sprint. Makes the typeToConfirm behavior of DeletionDialog conditional on a prop. Makes it so you can delete a Managed contact without typing the contact name.
While I was in there, I also updated DomainsLanding to use this pattern, since the dialog you got when deleting a Domain was previously dependent on where you tried to delete from.
> Change: Make typeToConfirm optional in DeletionDialog

- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
Lazy load OBJ buckets
It doesn't seem that loading them in the background in `MainContent_CMR.tsx` offers any significant improvement, so I'm sticking with the approach in this PR
> M3-4278: Lazy load OBJ Buckets

- packages/manager/src/features/Search/SearchLanding.test.tsx
- packages/manager/src/features/Search/SearchLanding.tsx
- packages/manager/src/features/Search/search.interfaces.ts
- packages/manager/src/features/Search/useAPISearch.tsx
- packages/manager/src/features/Search/utils.test.ts
- packages/manager/src/features/Search/utils.ts
- packages/manager/src/features/TopMenu/SearchBar/SearchBar_CMR.tsx
- packages/manager/src/hooks/useObjectStorageBuckets.ts
- packages/manager/src/hooks/useReduxLoad.ts
- packages/manager/src/store/bucket/bucket.requests.test.ts
- packages/manager/src/store/bucket/bucket.requests.ts
- packages/manager/src/store/selectors/entitiesErrors.ts
- packages/manager/src/store/selectors/getSearchEntities.ts
- packages/manager/src/store/selectors/getSearchEntitites.test.ts
Adds Object Storage Buckets to the Search Results (search bar and landing page).
Only works in CMR and on non-large accounts.
I ended up creating a new `useObjectStorage` hook which abstracts away the need to first request Clusters. A remaining TODO item is to use this hook everywhere that depends on Object Storage.
(Note: the dependency on first requesting Clusters is why I didn't end up adding this to `useReduxLoad`... I could make it work but it would be really messy for not much gain.
Note: This adds a few seconds of latency to the search experience. One possible remedy is to trigger the requests when the user clicks on the search bar (instead of typing). Curious to hear your thoughts.
Please try out the search bar, search landing page, etc. on large accounts, small accounts, …
> M3-3799 Add Buckets to Search Bar

- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
When a user has no Object Storage buckets and goes to create an access key, the permissions table in the drawer is now hidden. Previously it was shown and was able to be interacted with, which wasn't useful and probably confusing. I opted to hide it instead of disable it to streamline the drawer and maximize clarity for users.
> M3-4647: Hide OBJ Access Key permissions table if user has no buckets

- packages/api-v4/package.json
- packages/api-v4/src/firewalls/firewalls.schema.ts
- yarn.lock
Total failure on this one. The goal was to switch from the custom IP validation and separate form validation in FirewallRuleDrawer to using a Yup schema. The validation works well as is, but since it's custom it isn't available to consumers of the JS client.
Fixing the firewall rule schema so that it matches the behavior of the custom validation logic is easy, but actually using it in the drawer is...almost impossible. IP addresses, in particular custom user input, are stored in state in a shape that doesn't match the API payload, and only converted *after* validation has run. I tried a bunch of ways to get around this, but all of them had shortcomings (or didn't work at all). This drawer is a good case for custom validation, so I'm going to include the updated schema here but leave the …
> Update firewall rule schema in JS client

- packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LInodeResize.test.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/ResizeConfirmationDialog.tsx
When a customer tries to resize their Linode to a smaller plan without first resizing their disks, they trigger an error message. 
I updated the copy of this error message, and added a link to our "Resize a Linode" document for instructions on how to size down a plan.
> Updated Resize error message and added link

- packages/api-v4/src/account/payments.ts
- packages/api-v4/src/account/types.ts
- packages/api-v4/src/types.ts
- packages/manager/src/components/MigrateError.tsx
- packages/manager/src/factories/billing.ts
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentBits/CreditCardDialog.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.test.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/types.ts
- packages/manager/src/mocks/serverHandlers.ts
The API recently added an optional "warnings" field to the envelope
for responses. It's currently only used when making a payment (for
a rare edge case where jailbreaking fails even when the payment succeeds).
This PR adds that to the appropriate types, and displays any warnings
to the user in the payment drawer.
Note: we've had some feedback that leaving the drawer open after a successful
payment is confusing and has led to multiple payments. In a separate PR, we can
move all of this up a level to the billing info page.
Still needs some:
It isn't easy/possible to go through this process for real. Turn on the service worker and make a credit card payment (mocking the PayPal equivalent is much harder and I haven't worked it out).
> M3-4655 Change: Handle warnings after a successful payment.

- packages/manager/src/dev-tools/MockDataTool.tsx
- packages/manager/src/dev-tools/ServiceWorkerTool.tsx
- packages/manager/src/dev-tools/dev-tools.tsx
- packages/manager/src/mocks/testBrowser.ts
I've never mucked with the devtools before, I hope I didn't break anything. Note that this will completely remove the old way of activating the mocks--nothing you have in your .env will affect those anymore.
> Make service worker dependent on dev tools rather than env variable

- packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
As discussed in demo prep, remove the "Copy to Clipboard" text in the OBJ Bucket Details and Object Details drawers.
> Remove 'Copy to Clipboard' text in OBJ drawers

- packages/manager/src/components/PrimaryNav/MobileNav.tsx
- packages/manager/src/mocks/serverHandlers.ts
- Add a mock handler for OBJ clusters (the PrimaryNav_CMR test
was hitting the actual API several times against this endpoint,
with warnings logged in the test output)
- Fix a key warning in MobileNav
`yarn test primarynav` will run all the affected tests.
> Small fixes

- packages/manager/src/exceptionReporting.ts
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetail.container.tsx
- packages/manager/src/hooks/useLinodes.ts
- packages/manager/src/initSentry.test.ts
- packages/manager/src/initSentry.ts
A few Sentry cleanup things:
**1. Remove global `unhandledrejection` error reporting.** 
Looking through the Sentry dashboard with a search filter of `mechanism:onunhandledrejection`, these are just not very helpful and sometimes result in double reporting.
**2. Normalize error messages.** 
Many errors are going through sentry with an `APIError[]` as the message type. This means that Sentry's built in `ignoreErrors` functionality isn't working for these. To address this, I added a function to ensure the error messages are strings.
**3. Catch getLinode errors**
There's a problem with the way we tend to use thunks created with `createRequestThunk`. Namely, the generator function returns a rejected promise on failure, but we don't always catch the errors. This means, for example, if you go …
> Sentry cleanup Items

- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Domains/CreateDomain/index.tsx
- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Domains/index.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
As mentioned in [https://github.com/linode/manager/pull/5646](https://github.com/linode/manager/pull/5646), the Domain Create flow is inconsistent with the rest of Cloud's creation flows. To fix this, Domain Create has been moved to it's own page with a corresponding route, `/domains/create`.
Please check the different paths that lead to the Domain Create workflow including non-CMR and CMR.
> M3-4630: Refactor Domain Create workflow

- packages/manager/package.json
- packages/manager/src/components/LineGraph/LineGraph.tsx
- packages/manager/src/initSentry.ts
- yarn.lock
- Safe access and type checking to prevent "can't read match of undefined"
error
- Don't reset chart instance to null in useEffect. I don't really
like or understand the useEffect that is updating the chart. Rebuilding
the chart from scratch seems odd and inefficient, and I don't understand
what the line I deleted is supposed to do. However, we're planning
to upgrade Chart.js in the next sprint, we can revisit this logic
if it's still necessary with v3.X.
- Bump up to the latest patch version of Chart.js, which I'm told will be the final release before 3.0 is released from beta.
You can see the error message (which is inconsistent) in the /summary page of any Linode. You may have to refresh the page a bunch of times.
> Sentry fixes

- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/components/OrderBy.test.tsx
- packages/manager/src/components/OrderBy.tsx
- packages/manager/src/store/preferences/preferences.actions.ts
Adjust query sorting
- Save entity table sorting in user preferences
- Since this is dynamic, remove the SortKey type and wing it
- Read query params in OrderBy, and assign the default sort in the
following precedence:
1. query params
2. user preferences
3. component-specific values
4. default values
One quirk of this approach is that if the url contains a garbage sort key (e.g. "label" on the Domains table), we revert back to the defaults, since query params are highest priority and the sort keys are unknown (in OrderBy where this is happening). I think this is ok--you can always sort the table yourself after loading, and if you click a bad url it isn't exactly our fault. Open to feedback though.
> M3-4328 Query sorting

- packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
This enables Bucket searching in the non-CMR Search Bar. Honestly I’d be fine leaving it CMR only, but currently search DOES work if you’ve already loaded Buckets (by going to /object-storage) so as-is it’s a confusing experience.
Corresponds to the changes here: https://github.com/linode/manager/pull/7094/files#diff-411faeadb41c7310302cd47315602e2925c730ecf57ce66bc0c243c3fa27e0d6R24
> for release: Enable Bucket searching in production environment

- packages/manager/src/features/Dashboard/LinodesDashboardCard/LinodesDashboardCard.tsx
This is a regression from my Linode Extension PR: https://github.com/linode/manager/pull/6999/files#diff-d0c71d26667a02404807d7c46861a2b65aa6d5630d5f1cf2ce05dec014544a05L220
Currently in production we show **all** Linodes in the LinodeDashboardCard (non-CMR) which causes performance issues for large accounts. The correct behavior is to show (up to) 5.
> Hotfix: Only display 5 Linodes on the Dashboard

- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
- packages/manager/src/hooks/useEntities.ts
- packages/manager/src/hooks/useLinodeActions.ts
- packages/manager/src/hooks/useLinodes.ts
We were using const { updateLinode } = useLinodes() in several places.
Because of hooks weirdness and rerendering, this was causing an enormous
amount of processing (we were mapping through Linodes to extend them
~10 times per each actual Linode). By separating the actions to a separate
file, we can use this hook from consumers without triggering any of the state-based
Redux logic.
> Hotfix: separate linode actions from useLinodes hook

- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/useGraphs.ts
- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
The recent polling work introduced two LV bugs:
- Gauge data not loading most of the time
- Graph data never loading
The gauge bug was due to the callback argument of useClientLastUpdated being saved to a ref [here](https://github.com/linode/manager/pull/7085/files#diff-dfb08f57563f1c45e69b6c65cf85d07697eaf835951feac2ea8e554efd8716b4R13). This was a problem because LongviewDetail gives this [argument conditionally](https://github.com/linode/manager/blob/89d3b30d2362cc43cd6b4203039bec2cd249e27f/packages/manager/src/features/Longview/LongviewDetail/LongviewDetail.tsx#L89).
The graph bug is trickier. For one thing, the mounted ref was incorrectly initialized to `false`, but it took removing the `useCallback()` wrapper for it to work.
> Fix LV gauges and graphs

- packages/manager/src/features/Dashboard/DomainsDashboardCard/DomainsDashboardCard.tsx
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/features/Domains/DomainActionMenu.test.tsx
- packages/manager/src/features/Domains/DomainDetail/index.tsx
- packages/manager/src/features/Domains/DomainDrawer.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
- packages/manager/src/features/Domains/DomainTableRow.tsx
- packages/manager/src/features/Domains/DomainTableRow_CMR.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Domains/domainUtils.ts
- packages/manager/src/features/Volumes/WithEvents.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Replace all customer-facing usage of "master/slave" Domains with
primary/secondary. Also rename methods, update comments where appropriate.
API response types and our handling of them remain unchanged. A follow-on
will update these for forward-backward compatibility once the API has decided
on an approach.
> M3-4656 Rename domains: phase 1

- packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel_CMR.tsx
This was a regression from CMR work; there was no way to visit the invoice details page without typing the URL directly.
> M3-4671 Fix: Add missing link to invoice details in invoice rows

- packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx
Small request from Chris. This applies only to the url when visiting the support search page, at /support/search.
> M3-4620 Change: update URL query param on input change on support search landing page

- packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
I turned off the LD flag for this yesterday since we have account.capabilities and should rely on that. But Anton couldn't see the VLAN select when creating a Linode, because that particular UI bit was looking only at flags.vlans.
> Fix: Flag logic for attaching VLANs when creating a Linode

- packages/manager/config/webpack.config.dev.js
- packages/manager/config/webpack.config.prod.js
This fixes an issue where a few CSS source map files were being duplicated during our webpack builds. I'm not sure of the root cause here (something to do with css-loader + style-loader and the way we're importing the files, maybe), but this at least cleans up the source map names.
> Add fallback template function in webpack config

- packages/manager/src/assets/icons/docs.svg
- packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.stories.tsx
- packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.tsx
- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/LandingHeader/LandingHeader.tsx
- packages/manager/src/features/Footer/Footer_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- Revert to the previous style (inline with breadcrumb but convert text to "Docs")
- Add underline and external link arrow on hover
- Create storybook entry
- Also changed the max-width for the footer to 1100px
The scope of phase 1 is to optimize the DocumentationButton for Linodes Landing and add it to storybook while phase 2 will add the component to the rest of the app
> CMR Documentation Button - Phase 1

- packages/manager/package.json
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/react-async-script-loader.d.ts
- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/react-async-script.d.ts
- yarn.lock
Replace [react-async-script-loader](https://www.npmjs.com/package/react-async-script-loader), which hasn't been updated in several years, with [react-async-script](https://www.npmjs.com/package/react-async-script).
The only place this was being used was the Payment drawer. I don't believe that `react-async-script` passes props as `react-async-script-loader` did, so this will require some adjusting to keep working as intended.
> M3-3783: Replace react-async-script-loader package w/ react-async-script

- packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx
- packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
- packages/manager/src/factories/notification.ts
- packages/manager/src/features/Dashboard/Dashboard.tsx
- packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
- packages/manager/src/mocks/serverHandlers.ts
- packages/manager/src/store/selectors/getAbuseTicket.ts
Now that we no longer have a dashboard, abuse ticket notifications were shown only on the support landing page. Now 
Turn on the mocks to view an abuse ticket.
> M3-4663 Change: move abuse ticket banner to global notifications

- packages/manager/src/features/Footer/AdaLink.tsx
Adds some right padding to the "End Chat" button in the Ada chatbot window.
Currently:
vs.
This PR:
In figuring out how to target the right element, I realized that [Ada Chaperone has been deprecated](https://github.com/AdaSupport/docs/blob/master/chaperone.md). I'll check for/create a ticket to upgrade to their new [Embed2 script](https://adasupport.github.io/documentation/#introduction) (we never switched to Embed1 so we'll skip that).
> M3-4155: Fix Ada Chatbot overlapping buttons

- packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
Depending on which method we decide to go with, if we decide to allow
the migration then migrating to a datacenter where vlans aren't
supported with cause the VLAN not to work for a given Linode so we
should include an informational message about this.
If we go with not allowing the migration to proceed in the API then this
PR will not be needed.
> RFC: add notice about migrating with VLANs attached

- packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
- packages/manager/src/features/Managed/Credentials/CredentialList_CMR.tsx
Some things I noticed when I was combing through the app:
- Paypal button wasn't aligned, 
- White border above the ActionMenu cell in Managed / Credentials,
> UI Minor Fixes

- packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize_CMR.tsx
This is a recent regression. When intercepting the disk size error
message, we forgot that other errors could have already been intercepted
at a higher level (in request.tsx). This is the case for the reputation error,
which can fire if your score is low and you try to resize a Linode.
This adds some special handling to that, and resolves a DOM nesting error
where Typography's got nested inside each other in the GPU tab header of the
SelectPlanPanel.
Please test all possible errors:
- No error response (block requests to /resize)
- Additional verification required (set your account's reputation to 1)
- Disks too small (try to resize to a smaller plan without resizing disks first)
- CMR and non
- Normal API error (use the service worker)
> M3-4677 Resize error

- packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
- packages/manager/src/features/Longview/shared/useClientLastUpdated.ts
We've had a few reports of users with large numbers of Longview clients having performance problems on longview landing. This is unsurprising, since we poll the Longview API fairly aggressively for _each client_. I thought maybe paginating this view would help, but it's already paginated. I made a few small changes, none of which I'm thrilled about:
- Ignore user preferences and make the page size 25 on load for the Longview page. 100 clients is ridiculous given the way LV works right now, and unfortunately many of these customers have their account-wide items-per-page preference set to 100.
- Poll for client last updated values less aggressively (every 30 seconds instead of 10)
- General linter and effect clean up
There doesn't seem to be a lot of waste, no runaway effects etc. We're …
> M3-4673 Change: try to speed up Longview Landing

- package.json
- yarn.lock
This manually resolves y18n to ^4.0.0.  
AFAICT this package is only in use by Storybook, so make sure that works. Also check other commands for good measure, like `yarn test`, `yarn build`, etc.
> M3-4672 upgrade y18n

- packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
This fixes a regression where the Tags section is narrower than the records:
The normal stuff, check CMR, non, mobile, tablet, desktop.
> M3-4682 Domain Tags section width

- packages/manager/src/features/Volumes/VolumesLanding.tsx
Simple fix for a bug (reported through Sentry) where clicking the "View Linode Configurations" button results in a crashing bug. 
This is only an issue on non-CMR but it's quick and we get a lot of reports.
To reproduce:
- Have a Linode without a config
- Linode Details > Volumes
- Click "View Linode Configuration" 
- Observe: the app crashes.
This is because on L328 of VolumesLanding, we do `this.props.history.push()` but in the LinodesDetail context, it doesn't inherit route props from anywhere.
> VolumeLanding routing fix

- packages/manager/src/__data__/objectStorageClusters.ts
- packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
- packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
- packages/manager/src/factories/objectStorage.ts
- packages/manager/src/features/Databases/CreateDatabaseDialog/CreateDatabaseDialog.tsx
- packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.test.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx
- packages/manager/src/features/Vlans/CreateVLANDialog/CreateVLANDialog.tsx
- packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
- packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx
This enhances the Object Storage Cluster Select so that it uses a RegionSelect under the hood. This gives us group-by-country as well as country flags (makes it look like a RegionSelect).
I also went through and made the labels and placeholders for the RegionSelect more consistent.
Todo:
> Object Storage Cluster Select enhancement

- packages/manager/src/features/Vlans/CreateVLANDialog/CreateVLANDialog.test.tsx
- packages/manager/src/features/Vlans/CreateVLANDialog/CreateVLANDialog.tsx
- packages/manager/src/hooks/useVlans.ts
Simple change: use the Redux action instead of the API method directly for VLAN creation. This way the store is updated (previously, if you were already on the VLAN landing page and created a new one, you wouldn't see the UI update).
> Use Redux action for VLAN creation

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
In the .csv downloaded from the Linodes landing page, the "Most Recent Backups" column has been renamed to "Last Backup," and the logic for populating that field is as follows now:
1. If `backups.last_successful` is not null, display that as the last backup
2. If it is null, and `thisLinode.backups.schedule.day` and `thisLinode.backups.schedule.window` are not null, display "Scheduled" since a backup will be done soon
3. If it is null and `thisLinode.backups.schedule.day` and `thisLinode.backups.schedule.window` are null also, display "Never"
To test, have some linodes without Backups enabled and with Backups enabled
> M3-3759: Improve Backups column in Linode .csv file

- packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx
- packages/manager/src/features/linodes/MigrateLanding/ConfigureForm.tsx
- packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
- Check if the region to be migrated to supports VLANs.
- If it doesn't, show a note under the region input letting them know.
- Fix DOM nesting validation (we need to be more careful what we
put inside a `<Notice />`).
- Fix a glitch where you could submit the form without accepting the
conditions.
Todo:
> Change: add warning when migrating a Linode with VLANs to a region w/o VLANs

- packages/manager/src/assets/icons/resize.svg
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Follow-up from #7154. Fixes NodePool rows so that they use the same CMR behavior as other table rows (the row itself is not clickable, the entity label is a link to the entity).
This affects both CMR and non-CMR, some flag logic can be added if necessary to separate them.
You can add nodes to a node pool to see the unlinked state (which will eventually transition to the linked state)
> M3-4685 Change: use CMR style for Node Pools

- packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/LinodeRescue.tsx
Occasionally, depending on the speed of the `/linode/instances/:id/disks` request, the component may render faster than the request completes. In this case the state is not updated with the correct disks since it is initialized with an empty array if `props.linodeDisks` is undefined. Adding a `componentDidUpdate()` in which the disks are properly set should fix this.
I only encountered the bug once, before writing this fix, and haven't ran into it since, so I haven't had the chance to test this fully. But the intent is: if the props change, and `linodeDisks` was previously unpopulated but is now populated, set `disks` in state to `props.linodeDisks`.
> M3-4649: Add componentDidUpdate() in LinodeRescue.tsx to keep disks in state accurate

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.test.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/components/SideMenu.tsx
- packages/manager/src/features/Footer/Footer_CMR.tsx
To do this, I re-copied what was in `PrimaryNav.tsx` into `PrimaryNav_CMR.tsx` and made the following adjustments:
1. Group nav items (denoted by margin)
2. Replace hover state with gradient
I also adjusted the main content spacing to work with the new (old) layout.
**Notes:**
- I'm waiting on the designs for final spacing/placement + logos. This can be reviewed/merged as-is, though.
- The preferences "gear icon" will eventually be moved somewhere else, but I left it in for now so we can easily toggle dark theme.
> M3-4687 Move PrimaryNav back to the side

- packages/manager/src/features/Longview/LongviewLanding/LongviewList.tsx
To avoid this bit of slight awkwardness:
> Hide Longview pagination footer if there's only one page

- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessCell.tsx
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/LimitedAccessControls.tsx
- packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
- packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx
For OBJ access tokens and API access tokens, instead of showing a disabled version of the scopes form (with a bunch of radio buttons), if a user is in view-only mode instead use check marks for selected permissions. I opted to go with a shared (new) component for this, though it isn't clear if it's worth it in this case.
@ndukatz there are a few existing e2e tests that used data-qa attributes that are lost using this approach (nothing in Cypress though). Please let me know if I broke anything you're working on.
@tiffwong making this change meant that the aria stuff needed to be dynamic. The results are a bit different but I think they're ok. Please let me know.
> M3-4582 Change: Use a shared component for view-only permissions tables.

- packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
Improve alignment of the "Make a Payment" and "View last invoice" buttons: 
Please check all viewport sizes.
> Left-align billing buttons

- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/EntityIcon/EntityIcon.tsx
- Main Content padding from md to lg breakpoint
- No loading icons in search bar
@Jskobos I wasn't able to reproduce the /preferences issue. I was having trouble with the mock service worker there, though... could that have been what you were experiencing?
> Address feedback from #7180

- packages/manager/src/components/EntityTable/EntityTableHeader.tsx
- packages/manager/src/components/NotFound.tsx
- packages/manager/src/components/Placeholder/Placeholder.tsx
- packages/manager/src/components/Typography.stories.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallEmptyState.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/Images/ImagesLanding.tsx
- packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx
- packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
- packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
- packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
- packages/manager/src/features/Volumes/VolumesLanding.tsx
- packages/manager/src/features/Volumes/VolumesLanding_CMR.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.test.tsx
- packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
- packages/manager/src/mocks/serverHandlers.ts
- Update icons for the empty state placeholders for each entity
- Tweak styling to match newest designs
- Refactor Placeholder.tsx to use props.children instead of `copy=<EmptyCopy />`
- Add empty state placeholders for entities that didn't have them (except VLANs because you know)
- Make adjustments as necessary to get all this to hang together.
Mocks are set up so that almost all entities have 0, which should trigger the placeholder. Please check loading and error states for all entities as well, and placeholders used elsewhere (the 404 not found screen, for instance) to make sure they're unchanged.
> M3-4702 Change: Update empty states for all entities

- packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
- packages/manager/src/features/NotificationCenter/NotificationSection.tsx
- Change NotificationSection to return null if the passed list
of notifications is empty
- Add a message for section view saying "nothing to see here"
if all sections are empty (chronological view already has this message)
> M3-4717 Change: Hide empty notification sections in drawer

- packages/manager/src/MainContent.tsx
- packages/manager/src/MainContent_CMR.tsx
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.styles.ts
- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
- packages/manager/src/components/SideMenu.tsx
- packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu_CMR.tsx
Basically, the primary nav will always have the icon visible
> Condense primary nav and add icon to expanded state 

- packages/manager/src/features/Images/ImagesDrawer.tsx
Currently, when you go to imagize a disk, you can click the "Create" button multiple times which fires off multiple creation requests.
This PR closes the drawer after a successful imagize request. ~~moves the setting of the `submitting` state to `false` into the `setTimeout`, which fires after 4 seconds. This keeps the button in its loading state until the request completes.~~
> M3-1198: Prevent multiple imagize submissions in succession

- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/components/EntityTable/EntityTable.tsx
- packages/manager/src/components/EntityTable/EntityTableHeader.tsx
- packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
- packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
- packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
- packages/manager/src/components/EntityTable/types.ts
- packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
- packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding_CMR.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
- packages/manager/src/features/Vlans/VlanLanding/VlanLanding.tsx
- packages/manager/src/features/Volumes/VolumesLanding_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking_CMR.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/VLANPanel/LinodeVLANs.tsx
- packages/manager/src/features/linodes/LinodesLanding/SortableTableHead_CMR.tsx
- Fix regression where IP buttons (IP Transfer, Sharing, Add IP) went missing from the table in the Linode Networking tab. (This was due to re-arranging of the EntityHeader.)
- Add GroupByTag controls to Volumes, NodeBalancers, Domains for parity with production.
> Restore IP Controls, Group NBs, Volumes, Domains by Tag

- packages/manager/src/components/EntityDetail/EntityDetail.stories.tsx
- packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader_CMR.tsx
- packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
- packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow_CMR.tsx
- packages/manager/src/features/linodes/transitions.ts
Adds support for states like "disk duplicating" and "cloning" to the Entity Detail header.
> Add "secondary status" to Linodes

- packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx
Forgot this, so user preferences weren't being read on the Linodes table.
As a reminder, the sorting priority is:
1) query params
2) user preferences (if any)
3) defaults passed to the component
4) the default specified in OrderBy.tsx
> Add missing preferenceKey prop to Linodes landing

- packages/manager/src/features/ObjectStorage/BucketLanding/BucketActionMenu_CMR.tsx
When we removed the Details button from all TableRows, we didn't consider the fact that the only way to open the Bucket Details drawer is to use this button (clicking the title takes you to the object listing page).
Obviously the pattern isn't ideal and the Bucket Detail page should have an Entity Header, but this will have to do for now.
> Restore Details button for Buckets

- packages/manager/src/components/PrimaryNav/PrimaryNav_CMR.tsx
We're going to have to do this anyway, and it makes it easier not having to worry about VLANs when we're clicking through the app. Feature is still available at /vlans if anyone wants to check/use it for any reason.
> Change: remove vlans from primary nav

- packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx
The button refactor from a few weeks back caused a visual regression in the 2FA form (reach out for a link to the Trello item).
To test:
1. Go to profile/authentication
2. Toggle 2FA
3. The QR code will pop up with (hopefully) a properly styled link above it to toggle showing/hiding the code.
> Use link styles (previously destructive button) in 2FA form

- packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu_CMR.tsx
- packages/manager/src/features/TopMenu/TopMenu_CMR.tsx
- packages/manager/src/features/TopMenu/UserMenu/UserMenu_CMR.tsx
- packages/manager/src/features/TopMenu/iconStyles.ts
Make entity name in the create menu blue and add underline on hover
Fix focus states for the top nav: 
**Before:**
**After:**
> Change create menu entity name color and fix focus state for top nav

- packages/api-v4/src/object-storage/objectStorageKeys.ts
- packages/api-v4/src/object-storage/types.ts
- packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
This bug exists in production, too. You can only edit the label of OBJ access keys if the key is not limited access.
Please try the edit label action for both restricted and unrestricted keys.
> Fix: Unable to update label of OBJ limited access key

- packages/manager/src/features/Profile/Settings/Settings.tsx
- packages/manager/src/features/Profile/Settings/ThemeToggle.tsx
- packages/manager/src/features/Profile/Settings/ThemeToggle_CMR.tsx
The enabled state of the Dark Mode toggle looks like this currently:
This PR makes it match the look of the Notifications toggle when enabled (blue and white).
> Fix color scheme for Dark Mode toggle button's enabled state

- packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx
Following up on https://github.com/linode/manager/pull/7233#discussion_r543717446 and Matthew's confirmation, this PR changes the "View Details" `ButtonLink` for a Longview client on the Longview landing page to a regular button with link styling.
> Turn Longview "View Details" ButtonLink into a regular button with link styling

- packages/manager/src/components/AccessPanel/AccessPanel.tsx
- packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
- packages/manager/src/features/NodeBalancers/ConfigNodeIPSelect.tsx
- packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
- packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Disable a few fields we were missing for users that can't create Linodes or NodeBalancers:
- IP select (NBs)
- AccessPanel (Linode create--password, SSH keys)
This logic also disables the SSH key checkbox and "Add SSH key drawer" for a non-restricted user who hasn't selected an image. I think this is correct, please sanity check me.
> M3-4736 Fix: Disable create flow fields for restricted users

- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx
Remove the banner that shows up for restricted users in the Linode Create / Marketplace page that's inside the component since one is already present at the top
> M3-4725: Remove duplicate restricted banner for Marketplace

- packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
The`<Waypoint />` component on Bucket Details got lost in translation with CMR, so we're only showing the first 100 objects of a Bucket. This fixes that and gets rid of the conditional CMR rendering.
For testing: production tests account 9 has a Bucket with many objects.
> M3-4756 Object List not showing more than 100 objects

- packages/manager/src/App.tsx
- packages/manager/src/GoTo.tsx
I was inspired by @Jskobos's keyboard shortcut for light/dark mode toggle, so I started this on FTFF. This one is "CMD+K" and brings up a "Go To" component for quick navigation around the app.
Still needs a bit of testing, some styling updates (I copied over a lot of styles from SearchBar.styles), etc.
> POC: "Go To" functionality

- packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.tsx
- packages/manager/src/components/EntityHeader/EntityHeader.tsx
- packages/manager/src/features/Domains/DomainsLanding.tsx
Prevent the create button on landing pages from being flush to the edge of the screen
> M3-4767: Add padding to the right of the create button on mobile

- packages/manager/src/features/Users/UserPermissions.tsx
Just a little housecleaning; see ticket for details.
Update text to accurately reflect what read_only account access lets you do
> Fix: Update read_only grant description for account access

- packages/api-v4/src/domains/domains.schema.ts
- packages/api-v4/src/domains/domains.ts
- packages/api-v4/src/domains/index.ts
- packages/api-v4/src/domains/types.ts
- packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
- packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
- packages/manager/src/store/domains/domains.reducer.test.ts
The task here was to disable the create button until the required fields were filled in. Since required fields differ based on what kind of Domain you're creating, I added some conditional logic that felt yucky.
Then I thought, It's Christmas, Jared. Why not do it the hard way? So I did. This PR:
- Refactors the create domain modal to use Formik
- Updates Domains types and tests to be accurate (we were using `Partial<Domain>` for both create and update payloads)
- Does a lot of fancy schmancy stuff with the live validation
Please make sure I didn't break anything. Creating primary and secondary Domains, with and without tags or default records, should all work as before, including error states.
> Change: Refactor Domain creation and disable submission until required fields are present

- packages/manager/src/dev-tools/EnvironmentToggleTool.tsx
- packages/manager/src/dev-tools/MockDataTool.tsx
- packages/manager/src/dev-tools/ServiceWorkerTool.tsx
- packages/manager/src/dev-tools/dev-tools.css
- packages/manager/src/dev-tools/dev-tools.tsx
The goal here was to clean up the dev-tools column spacing at smaller viewports to make things cleaner. Particularly with some new options for mock data being added shortly, this could've become slightly messy.
Before:
After: 
> Improve spacing of dev-tools columns for smaller viewports

- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/PreviewReply.tsx
- packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx
- packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
Customers had mentioned that they don't always have enough room to fill out ticket text. Expanded everything to improve the situation.
> Convert Support ticket drawer to a dialog and make inputs bigger

- packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx
Quick change per demo feedback making ascending disk creation time the default sort for the Linode Disks table
> Linode Disks table now sorted by default by Created time (ascending)

- packages/manager/src/LinodeThemeWrapper.tsx
The logic to deactivate the inactive theme for code syntax
highlighting was only run when the theme was toggled, not on
page load. This meant that users loading the app with light theme
enabled saw dark/bad highlighting everywhere HighlightedMarkdown
was used.
Extracted this logic to a function and called it in the existing
useEffect.
> Fix: Set highlight.js theme on app load

- packages/api-v4/src/kubernetes/nodePools.ts
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeActionMenu.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeDialog.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
- packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
- packages/manager/src/hooks/useDialog.ts
- Add new undocumented API method for recycling a single node
- Uncomment the old NodeActionMenu and bring it up to date
- Adjust types and props to handle passing around the node ID
- Make useDialog's entityID `string | number`. Bit of chicanery involved.
> Change: Re-add and rework recycling for individual nodes

- packages/manager/src/components/Toggle/Toggle.stories.tsx
- packages/manager/src/features/Domains/DomainDetail/DomainDetail.tsx
- packages/manager/src/features/Domains/DomainRecords.tsx
Remove the plus icons and the tags button from the upper right since all it did was scroll to the tags section at the bottom of the page
> M3-4710: Remove icons from Domain Detail buttons
