- karma.conf.js
- package.json
- src/components/Navigation.js
- src/components/Sidebar.js
- test/components/Dropdown.spec.js
- test/components/Navigation.spec.js
- test/components/Sidebar.spec.js
I have Navigation stashed, since testing it was dependent on what drew was working on, and working on actions and pulling in Navigation next.
> Test Component Rendering

- src/linodes/actions/create.js
- src/linodes/reducers/create.js
- test/linodes/actions/create.spec.js
- test/linodes/actions/index.spec.js
Will finish this up after the weekend. All that's left is to flesh out the tests for creating a Linode.
> Add tests for actions on linodes

- .eslintrc
- package.json
- src/store/configureStore.js
- test/actions/api/linodes.spec.js
- test/api-store.spec.js
- test/components/Dropdown.spec.js
- test/components/Navigation.spec.js
- test/components/Sidebar.spec.js
- test/linodes/actions/create.spec.js
- test/linodes/actions/index.spec.js
- test/linodes/reducers/index.spec.js
- test/mocks.js
- test/reducers/authentication.spec.js
And fix all of the linting problems that arise.
> Add linting for our test suite as well

- README.md
No sense in starting someone off on the wrong foot.
> Lint readme js

- src/linodes/layouts/IndexPage.js
- test/data.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/IndexPage.spec.js
Also implements one of the tests
> Add test stubs for IndexPage

- scss/layout/linode-details.scss
- src/linodes/index.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/layouts/LinodeGeneral.js
- test/data.js
- test/linodes/layouts/LinodeGeneral.spec.js
> implement linode general tab

- scss/manager.scss
- src/components/Header.js
- src/linodes/components/Linode.js
- src/linodes/layouts/IndexPage.js
* Add clearfix on header-main and header-info
* Proper btn-primary class for "Add a Linode"
* Checkbox checked use boolean always instead of optional inclusion
> Fix misc breakage

- scss/components/distro.scss
- scss/manager.scss
- src/linodes/actions/create/source.js
- src/linodes/components/DistroVendor.js
- src/linodes/components/SourceSelection.js
- src/linodes/layouts/CreateLinodePage.js
- src/linodes/reducers/create/index.js
- src/linodes/reducers/create/source.js
- src/linodes/reducers/index.js
- test/data.js
- test/linodes/actions/create/source.spec.js
- test/linodes/components/DistroVendor.spec.js
- test/linodes/components/SourceSelection.spec.js
- test/linodes/layouts/CreateLinodePage.spec.js
- test/linodes/reducers/create/source.spec.js
> Implement distro selection UI

- karma.conf.js
- test/index.js
> Webpack bundle single test file

- karma.conf.js
- scss/components/distro.scss
- scss/linodes/linodes.scss
- src/assets.js
- src/constants.js
- src/linodes/actions/create/datacenter.js
- src/linodes/components/DatacenterSelection.js
- src/linodes/components/DistroVendor.js
- src/linodes/layouts/CreateLinodePage.js
- src/linodes/layouts/LinodeGeneral.js
- src/linodes/reducers/create/datacenter.js
- src/linodes/reducers/create/index.js
- src/linodes/reducers/create/source.js
- test/linodes/components/DatacenterSelection.spec.js
- test/linodes/components/DistroVendor.spec.js
- test/linodes/layouts/CreateLinodePage.spec.js
> Add datacenter to add a linode page

- scss/components/distro.scss
- src/linodes/actions/create/service.js
- src/linodes/components/ServiceSelection.js
- src/linodes/layouts/CreateLinodePage.js
- src/linodes/reducers/create/index.js
- src/linodes/reducers/create/service.js
- test/data.js
- test/linodes/components/ServiceSelection.spec.js
- test/linodes/layouts/CreateLinodePage.spec.js
> Add service selection

- package.json
- scss/components/card.scss
- scss/layout/linode-details.scss
- scss/linodes/linodes.scss
- scss/linodes/settings/alerts.scss
- scss/linodes/settings/settings.scss
- src/actions/api/linodes.js
- src/api-store.js
- src/components/Form.js
- src/index.js
- src/linodes/index.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/layouts/LinodeGeneral.js
- src/linodes/settings/index.js
- src/linodes/settings/layouts/AlertsPage.js
- src/linodes/settings/layouts/IndexPage.js
- src/linodes/settings/layouts/index.js
- test/api-store.spec.js
- test/components/Form.spec.js
- test/components/Header.spec.js
- test/data.js
- test/linodes/layouts/LinodeDetailPage.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
- test/linodes/settings/layouts/AlertsPage.spec.js
- test/linodes/settings/layouts/IndexPage.spec.js
> Add settings alert page

- scss/layout/linode-details.scss
- scss/manager.scss
- src/components/WarningButton.js
- src/linodes/components/Linode.js
- src/linodes/components/ServiceSelection.js
- src/linodes/layouts/LinodeGeneral.js
- test/components/WarningButton.spec.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
> Common styles fix

- src/components/Dropdown.js
- src/linodes/components/DistroVendor.js
- test/components/Dropdown.spec.js
- test/linodes/components/DistroVendor.spec.js
> Fix dropdowns

- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/LinodeGeneral.js
- src/linodes/layouts/LinodeNetworking.js
- test/data.js
- test/linodes/create/components/ServiceSelection.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
- test/linodes/layouts/LinodeNetworking.spec.js
Keeping our code with how the API responds, and expecting datacenter.datacenter to go away.
> Updates for API Changes

- src/components/Sidebar.js
- test/components/Sidebar.spec.js
> implement account link in sidebar

- scss/manager.scss
- src/linodes/layouts/BackupsPage.js
> Fix radio styles

- scss/linodes/linodes.scss
> Set header color gray

- package.json
- scss/manager.scss
- src/components/Header.js
- src/components/Navigation.js
- src/layouts/Layout.js
- src/reducers/authentication.js
- test/components/Navigation.spec.js
- test/reducers/authentication.spec.js
the logout functionality will be replaced in a future PR, when clicking on the user image brings a dropdown and one of the items in there will be logout
Closes #158
> add gravatar image and badge to header, remove logout

- src/actions/api/backups.js
- src/linodes/layouts/BackupsPage.js
- test/actions/api/backups.spec.js
- test/linodes/layouts/BackupsPage.spec.js
Just want to get review going ASAP.
> wiring up enable and cancel for backups

- package.json
- scss/linodes/create/create.scss
- scss/manager.scss
- src/linodes/create/components/Details.js
Closes #233 
Still needs tests.
> Add password strength meter

- src/api-store.js
- src/linodes/components/Linode.js
- src/linodes/layouts/BackupsPage.js
- src/reducers/api/linodes.js
- test/data.js
- test/linodes/layouts/BackupsPage.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
> Wire backups list to the API

- scss/manager.scss
- src/components/Navigation.js
Closes #280 and #292
Chrome:
Firefox:
> Fix header on FF

- src/linodes/layouts/LinodeNetworking.js
> Fix display of reverse dns

- src/constants.js
This could be changing down the line but for now this follows the current documentation and is a simple change. Closes #230
> Repopulate current region map

- scss/manager.scss
- src/components/Sidebar.js
- src/layouts/Layout.js
- test/components/Sidebar.spec.js
> highlight link in sidebar for current path

- scss/manager.scss
- test/components/Sidebar.spec.js
adjust margin top for sidebar li element
> add retroactive test for future bug

- scss/components/backup.scss
- scss/components/card.scss
- scss/components/components.scss
- scss/components/distro.scss
- scss/layout/linode-details.scss
- scss/linodes/create/create.scss
- scss/linodes/linodes.scss
- scss/manager.scss
- src/linodes/components/Backup.js
- src/linodes/create/components/BackupSelection.js
- src/linodes/create/components/SourceSelection.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/BackupsPage.js
- test/data.js
- test/linodes/components/Backup.js
- test/linodes/create/components/BackupSelection.spec.js
- test/linodes/create/components/SourceSelection.spec.js
- test/linodes/create/layout/IndexPage.spec.js
- test/linodes/layouts/BackupsPage.spec.js
> Add backups selection to add a linode flow

- package.json
- src/api-store.js
- test/api-store.spec.js
This also does a lot of general refactoring and documentation, limited to the first commit.
Closes #225
> Add cache invalidation to API store

- src/actions/api/backups.js
- src/linodes/layouts/BackupsPage.js
- src/reducers/api/linodes.js
- test/actions/api/backups.spec.js
- test/data.js
- test/linodes/create/components/BackupSelection.spec.js
- test/linodes/layouts/BackupsPage.spec.js
- test/reducers/api/linodes.spec.js
> Implement take backup

- src/linodes/layouts/LinodeGeneral.js
- test/components/ResponsiveCharts.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
> Linode Graphs Filler

- src/linodes/create/components/Details.js
- src/linodes/create/layouts/IndexPage.js
- test/linodes/create/components/Details.spec.js
- test/linodes/create/layout/IndexPage.spec.js
> Group and quantity options for Linode create

- scss/manager.scss
- src/linodes/components/Linode.js
- src/linodes/layouts/LinodeGeneral.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
> Update Linode Index page with Labels

- .eslintrc
- src/actions/api/linodes.js
- src/components/PasswordInput.js
- src/linodes/create/components/Details.js
- src/linodes/index.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/layouts/RepairPage.js
- test/data.js
- test/linodes/layouts/RepairPage.spec.js
> Reset root password

- src/linodes/settings/index.js
- src/linodes/settings/layouts/IndexPage.js
> Drop boot settings subtab from settings tab

- src/account/index.js
- src/dnsmanager/index.js
- src/index.js
- src/linodes/index.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/settings/index.js
- src/longview/index.js
- src/nodebalancers/index.js
- src/support/index.js
> stubbing out pages and adding linode rebuild

- src/linodes/settings/index.js
- src/linodes/settings/layouts/AdvancedPage.js
> linode > settings > advanced skel

- src/linodes/components/Linode.js
- src/linodes/layouts/LinodeGeneral.js
- src/linodes/layouts/LinodeNetworking.js
- test/data.js
- test/linodes/layouts/LinodeGeneral.spec.js
- test/linodes/layouts/LinodeNetworking.spec.js
This addresses a recent breaking change in the API.
> Fix IP addresses

- scss/layout/linode-details.scss
- src/actions/api/linodes.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/layouts/RepairPage.js
- test/actions/api/linodes.spec.js
- test/data.js
- test/linodes/layouts/LinodeDetailPage.spec.js
> Implement booting to a specific config profile

- src/api-store.js
- src/linodes/settings/layouts/AlertsPage.js
- test/api-store.spec.js
- test/linodes/settings/layouts/AlertsPage.spec.js
> Fix alerts

- test/components/PasswordInput.spec.js
> Add PasswordInput.spec.js

- scss/layout/linode-details.scss
- src/linodes/components/Backup.js
- src/linodes/layouts/BackupsPage.js
> Adjust the snapshot section when appropriate

- src/linodes/components/Linode.js
- test/linodes/layouts/LinodeGeneral.spec.js
> Render distro vendor instead of label

- src/linodes/layouts/IndexPage.js
> Fix alignment of group headers on grid view

- src/constants.js
- src/linodes/components/Linode.js
- src/linodes/create/components/DatacenterSelection.js
- test/data.js
- test/linodes/create/components/DatacenterSelection.spec.js
Just a quick update for how our country codes work, leveraging the API, instead of local constants.
> Use country codes

- src/components/Navigation.js
This is not an available feature right now.
> Remove search bar

- src/linodes/create/components/Details.js
> Render Linode > Create > Details > Alert box below password generator.

- src/linodes/settings/components/ConfigPanel.js
- test/linodes/settings/components/ConfigPanel.spec.js
> Do not show delete button for the last config

- scss/manager.scss
> Fix grid spacing

- index.html
- scss/manager.scss
- src/components/Footer.js
- src/layouts/Layout.js
- src/linodes/layouts/LinodeDetailPage.js
- test/components/Footer.spec.js
And some minor cleanup
Closes #382
> Add footer

- src/components/Header.js
- src/components/Infobar.js
- src/layouts/Layout.js
- test/components/Infobar.spec.js
- test/layouts/Layout.spec.js
For the sake of `<Header />` just being a dumb element.
> Fetch blog post in layout not header

- src/store/index.js
> Tweak how we create our store

- src/reducers/authentication.js
Which should fix (or help with) some of the issues around local storage
getting stale and borken.
> Change the way email hashes are handled

- .babelrc
- package.json
- scss/linodes/settings/disks.scss
- scss/manager.scss
- src/actions/api/linodes.js
- src/api-store.js
- src/linodes/layouts/BackupsPage.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/settings/components/DiskPanel.js
- src/linodes/settings/layouts/AlertsPage.js
- test/api-store.spec.js
- test/linodes/layouts/BackupsPage.spec.js
- test/linodes/settings/components/ConfigPanel.spec.js
- test/linodes/settings/components/DiskPanel.spec.js
- test/linodes/settings/layouts/AdvancedPage.spec.js
- test/linodes/settings/layouts/IndexPage.spec.js
> Edit and delete Linode disks

- scss/components/modal.scss
- src/actions/api/linodes.js
- src/api-store.js
- src/linodes/settings/components/DiskPanel.js
- test/api-store.spec.js
- test/data/distros.js
- test/data/linodes.js
- test/linodes/create/components/DistroVendor.spec.js
- test/linodes/settings/components/DiskPanel.spec.js
> Implement disk creation

- scss/manager.scss
- src/components/Error.js
- src/index.js
- src/layouts/Layout.js
- test/components/Error.spec.js
- test/layouts/Layout.spec.js
> Add reusable error components

- package.json
- scss/manager.scss
- src/actions/api/kernels.js
- src/actions/api/linodes.js
- src/components/HelpButton.js
- src/errors.js
- src/linodes/layouts/LinodeDetailPage.js
- src/linodes/settings/components/ConfigPanel.js
- src/linodes/settings/components/DiskPanel.js
- src/linodes/settings/index.js
- src/linodes/settings/layouts/ConfigEdit.js
- src/reducers/api/index.js
- src/reducers/api/kernels.js
- test/data/index.js
- test/data/kernels.js
- test/data/linodes.js
- test/linodes/settings/components/ConfigPanel.spec.js
- test/linodes/settings/components/DiskPanel.spec.js
- test/linodes/settings/layouts/ConfigEdit.spec.js
Closes #217 
Take particular note of fb3fc69 when reviewing
> Profile edit - part one

- src/linodes/layouts/LinodeGeneral.js
Corrects a misspelled word in usage graphs
> spelling: useage -> usage

- scss/components/backup.scss
- scss/layout/linode-details.scss
- src/linodes/components/Backup.js
- src/linodes/layouts/BackupsPage.js
- test/linodes/components/Backup.spec.js
- test/linodes/layouts/BackupsPage.spec.js
> Predicted Backups

- scss/manager.scss
- src/linodes/settings/components/DiskPanel.js
- src/linodes/settings/layouts/AdvancedPage.js
Closes #451
Closes #447
Did these at the same time since one would affect the other.
> Reorganize settings adv and fix spacing

- src/linodes/layouts/LinodeNetworking.js
- test/linodes/layouts/LinodeNetworking.spec.js
Closes #449 
Rework of PR #459
> Remove private network help button

- scss/manager.scss
- src/linodes/settings/layouts/ConfigEdit.js
Closes #452 
Also changes Edit profile to Edit config, which slipped through when we went through the rename.
> fix notes spacing, and change profile to config

- src/linodes/layouts/LinodeGeneral.js
- test/linodes/layouts/LinodeGeneral.spec.js
> null distro now unknown

- src/constants.js
> Change shutting to powering off

- src/linodes/layouts/LinodeNetworking.js
- test/linodes/layouts/LinodeNetworking.spec.js
> Buttons more clear and inet > address

- src/linodes/layouts/LinodeGeneral.js
> Move backup row down in Linode details

- src/actions/api/backups.js
- src/actions/api/datacenters.js
- src/actions/api/distros.js
- src/actions/api/kernels.js
- src/actions/api/linodes.js
- src/actions/api/services.js
- src/api-store.js
- src/linodes/components/Linode.js
- src/linodes/create/components/ServiceSelection.js
- src/linodes/layouts/LinodeGeneral.js
- src/linodes/layouts/LinodeNetworking.js
- test/actions/api/backups.spec.js
- test/actions/api/datacenters.spec.js
- test/actions/api/distros.spec.js
- test/actions/api/linodes.spec.js
- test/actions/api/services.spec.js
- test/api-store.spec.js
- test/data/linodes.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/BackupsPage.spec.js
- test/linodes/layouts/IndexPage.spec.js
- test/linodes/layouts/LinodeDetailPage.spec.js
- test/linodes/layouts/LinodeGeneral.spec.js
- test/linodes/layouts/LinodeNetworking.spec.js
- test/linodes/layouts/RescuePage.spec.js
- test/linodes/settings/components/ConfigPanel.spec.js
- test/linodes/settings/components/DiskPanel.spec.js
- test/linodes/settings/layouts/AlertsPage.spec.js
- test/linodes/settings/layouts/ConfigEdit.spec.js
I have found at least one more bug, and need to run everything through manual testing to verify everything else is working properly, but want to get this out ASAP, so more than one person can work on the manager.
> Fixes from API changes - Sept 2016

- src/actions/api/backups.js
- src/linodes/components/Backup.js
- src/linodes/create/components/BackupSelection.js
- src/linodes/create/components/DatacenterSelection.js
- src/linodes/create/components/SourceSelection.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/BackupsPage.js
- test/linodes/create/components/BackupSelection.spec.js
- test/linodes/create/components/DatacenterSelection.spec.js
- test/linodes/create/layout/IndexPage.spec.js
- test/linodes/layouts/BackupsPage.spec.js
Closes #174 
Clicking restore now takes you here:
> Restore backup to new linode

- src/actions/authentication.js
- src/index.js
- src/layouts/OAuth.js
- src/reducers/authentication.js
- src/session.js
- src/storage.js
- test/layouts/OAuth.spec.js
- test/reducers/authentication.spec.js
> Pure reducers

- src/layouts/OAuth.js
- test/layouts/OAuth.spec.js
> Handle errors returned during the OAuth flow

- scss/manager.scss
- src/linodes/linode/layouts/NetworkingPage.js
- src/linodes/linode/settings/components/ConfigPanel.js
- test/linodes/linode/layouts/NetworkingPage.spec.js
Closes #488, closes #487, closes #486
> Few style bug fixes

- src/linodes/components/Backup.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/linode/layouts/BackupsPage.js
- test/components/Header.spec.js
- test/layouts/Layout.spec.js
- test/linodes/components/Backup.spec.js
- test/linodes/create/layout/IndexPage.spec.js
- test/linodes/linode/layouts/BackupsPage.spec.js
- test/linodes/linode/layouts/DashboardPage.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
- test/linodes/linode/layouts/RescuePage.spec.js
- test/linodes/linode/settings/layouts/ConfigEdit.spec.js
> Fix warnings raised during test runs

- package.json
- src/actions/modal.js
- src/index.js
- src/linodes/linode/settings/layouts/IndexPage.js
- src/reducers/modal.js
- test/actions/modal.spec.js
- test/components/Modal.spec.js
- test/reducers/modal.spec.js
> Hide modal on page change

- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/components/DiskPanel.js
- src/linodes/linode/settings/layouts/ConfigEdit.js
- test/data/services.js
- test/linodes/components/Linode.spec.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> Replace disk size slider with input fields

- src/components/Navigation.js
- test/components/Navigation.spec.js
> Move /profile links to /account/profile

- scss/manager.scss
- src/linodes/linode/layouts/BackupsPage.js
- src/linodes/linode/settings/components/DiskPanel.js
- test/linodes/linode/layouts/BackupsPage.spec.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> Change nevermind buttons to links

- scss/components/modal.scss
> Fix modal overlay to viewport

- src/linodes/linode/layouts/IndexPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/layouts/AlertsPage.js
- src/linodes/linode/settings/layouts/DisplayPage.js
- test/linodes/components/Linode.spec.js
- test/linodes/linode/settings/layouts/DisplayPage.spec.js
Closes #480. More tests to come
> Add display page

- scss/components/form.scss
- scss/manager.scss
> Fix select text clipping

- src/linodes/create/components/Details.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/linode/layouts/BackupsPage.js
- test/data/types.js
- test/linodes/create/components/Details.spec.js
- test/linodes/linode/layouts/BackupsPage.spec.js
> Get backups price from API

- src/linodes/linode/layouts/IndexPage.js
- test/linodes/linode/layouts/IndexPage.spec.js
if you are in a different subtab
closes #526
> Clicking on a tab takes you to the default subtab page

- src/linodes/linode/settings/components/ConfigPanel.js
- src/linodes/linode/settings/layouts/ConfigEdit.js
- test/linodes/linode/settings/components/ConfigPanel.spec.js
- test/linodes/linode/settings/layouts/ConfigEdit.spec.js
> add create new config

- src/linodes/linode/layouts/DashboardPage.js
- test/linodes/linode/layouts/DashboardPage.spec.js
> Drop graphs for now

- scss/components/components.scss
- scss/components/status-dropdown.css
- scss/layout/linodes.scss
- scss/manager.scss
- src/components/StatusDropdown.js
- src/linodes/components/Linode.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/layouts/IndexPage.js
- test/components/StatusDropdown.spec.js
- test/linodes/components/Linode.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
> Status dropdown

- src/api/configs/dnszones.js
- src/api/index.js
- src/api/reducer.js
- src/components/Sidebar.js
- src/dnsmanager/index.js
- src/dnszones/index.js
- src/dnszones/layouts/IndexPage.js
- src/index.js
- src/linodes/linode/layouts/IndexPage.js
- test/components/Sidebar.spec.js
- test/data/dnszones.js
- test/data/index.js
- test/dnszones/layouts/IndexPage.spec.js
> Add DNS Zones list

- karma.conf.js
- package.json
- src/constants.js
- src/index.js
- webpack.config.dev.js
- webpack.config.prod.js
> add analytics

- src/linodes/linode/layouts/Weblish.js
> Add group/label to weblish window title

- scss/manager.scss
- src/components/Sidebar.js
- test/components/Sidebar.spec.js
> Implemented new sidebar

- src/actions/authentication.js
- src/components/Modal.js
- src/index.js
- src/layouts/Layout.js
- src/layouts/Logout.js
- src/layouts/OAuth.js
- src/reducers/index.js
- test/layouts/Logout.spec.js
> Add logout endpoint

- src/account/index.js
- src/actions/source.js
- src/dnszones/layouts/IndexPage.js
- src/index.js
- src/layouts/Layout.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/IndexPage.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/IndexPage.js
- src/linodes/linode/layouts/NetworkingPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/layouts/AdvancedPage.js
- src/linodes/linode/settings/layouts/AlertsPage.js
- src/linodes/linode/settings/layouts/ConfigEdit.js
- src/linodes/linode/settings/layouts/DisplayPage.js
- src/reducers/index.js
- src/reducers/source.js
- test/data/index.js
- test/layouts/Layout.spec.js
- test/linodes/create/layout/IndexPage.spec.js
- test/linodes/linode/layouts/RescuePage.spec.js
- test/linodes/linode/settings/layouts/AdvancedPage.spec.js
- test/linodes/linode/settings/layouts/DisplayPage.spec.js
- webpack.config.dev.js
> Add source links

- src/linodes/create/components/Details.js
- test/linodes/create/components/Details.spec.js
> No hide backup / drop root password text

- src/components/Sidebar.js
- src/dnsmanager/index.js
- src/dnsmanager/layouts/IndexPage.js
- src/index.js
- test/components/Sidebar.spec.js
- test/dnsmanager/layouts/IndexPage.spec.js
> Rename DNS Zones to DNS Manager

- index.html
- karma.conf.js
- package.json
- scss/manager.scss
- src/actions/feedback.js
- src/components/Feedback.js
- src/components/Notifications.js
- src/constants.js
- src/index.js
- src/layouts/Layout.js
- src/reducers/feedback.js
- src/reducers/index.js
- src/reducers/modal.js
- src/reducers/notifications.js
- test/components/Feedback.spec.js
- test/components/Notifications.spec.js
- test/layouts/Layout.spec.js
- webpack.config.dev.js
- webpack.config.prod.js
Closes #570 
Also includes some cleanup of the notifications sidebar as I saw better ways to do that. Closes #601
> Feedback extractor

- devServer.js
- index.html
> Include common.js in index.html

- src/dnsmanager/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- test/dnsmanager/layouts/IndexPage.spec.js
- test/linodes/layouts/IndexPage.spec.js
> Add no objects helpers to Linodes and DNS Manager views

- src/linodes/create/components/Plan.js
- test/linodes/create/components/Plan.spec.js
> Fix plan disk size

- src/components/Feedback.js
- src/linodes/create/components/Details.js
- src/linodes/linode/settings/layouts/AlertsPage.js
- src/linodes/linode/settings/layouts/DisplayPage.js
- test/components/Feedback.spec.js
- test/linodes/linode/settings/layouts/AlertsPage.spec.js
- test/linodes/linode/settings/layouts/DisplayPage.spec.js
> Set button type explicitly to not submit

- src/linodes/layouts/IndexPage.js
- test/linodes/layouts/IndexPage.spec.js
> Select all

- scss/manager.scss
- src/components/StatusDropdown.js
- src/linodes/components/Linode.js
- src/linodes/components/StatusDropdown.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/IndexPage.js
- test/linodes/components/StatusDropdown.spec.js
> Update status dropdown with weblish link

- scss/components/status-dropdown.scss
- src/api/genThunks.js
- src/linodes/components/StatusDropdown.js
- src/linodes/linode/layouts/IndexPage.js
- test/linodes/components/StatusDropdown.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
Here is my first attempt at a progress bar, this uses rc-progressbar right now which might be replaced by something custom and simple very soon.
Closes #551
> Progress bar

- src/linodes/create/layouts/IndexPage.js
- test/linodes/create/layout/IndexPage.spec.js
The button was there, but it didn't work.
> Create a linode with backups enabled

- src/linodes/linode/backups/layouts/IndexPage.js
- test/linodes/linode/backups/layouts/IndexPage.spec.js
> Add enable backups page

- scss/components/backup.scss
- src/linodes/linode/backups/layouts/SummaryPage.js
- test/linodes/linode/backups/layouts/SummaryPage.spec.js
Only snapshots work, once API backups changes are solidified we can add the others.
> Implement backups summary page

- scss/components/card.scss
- scss/components/status-dropdown.scss
- scss/layout/linodes.scss
- scss/manager.scss
- src/components/Feedback.js
- src/linodes/components/Linode.js
- src/linodes/components/StatusDropdown.js
- src/linodes/layouts/IndexPage.js
- test/linodes/components/Linode.spec.js
- test/linodes/components/StatusDropdown.spec.js
- test/linodes/layouts/IndexPage.spec.js
Closes #587, closes #598, closes #635, closes #597, closes #153
> Updated linode card and row views

- src/linodes/components/StatusDropdown.js
> Allow multiple lish windows

- src/api/linodes.js
> Linode state is called status

- src/linodes/linode/backups/layouts/SettingsPage.js
- test/linodes/linode/backups/layouts/SettingsPage.spec.js
> Backup settings

- scss/manager.scss
Closes #637. Could probably still use some tweaking but it's an improvement and demonstrates the concept.
> Override bootstrap default column breakpoints

- src/errors.js
- src/linodes/linode/backups/layouts/IndexPage.js
- test/linodes/linode/backups/layouts/IndexPage.spec.js
> Show errors when backups fail to enable

- src/api/gen.js
> Read ID from API during POST

- scss/manager.scss
- src/dnsmanager/components/NewMasterZone.js
- src/dnsmanager/index.js
- src/dnsmanager/layouts/CreatePage.js
- test/dnsmanager/components/NewMasterZone.spec.js
Closes #430 (just leaving out the insert default records line for now)
> Add dns master zone

- src/linodes/components/Linode.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- test/data/linodes.js
- test/linodes/linode/layouts/DashboardPage.spec.js
- test/linodes/linode/networking/layouts/SummaryPage.spec.js
> updates for endpoint ip changes

- package.json
- scss/manager.scss
This dependency was causing issues and it appears to not be used, yet.
> Remove unused rc-slider component

- src/api/genThunks.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> Fix kernels

- scss/manager.scss
- src/linodes/components/Linode.js
- src/linodes/linode/layouts/DashboardPage.js
- test/linodes/linode/layouts/DashboardPage.spec.js
> Fix ips css

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/data/linodes.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
Also get our kernel code inline with the intentions of the API.
> Select kernel from list on load

- src/components/Feedback.js
- src/dnsmanager/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/SettingsPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/components/DiskPanel.js
> Replace Nevermind with Cancel

- src/linodes/linode/layouts/RescuePage.js
> add labels for disk and password resuce page

- scss/manager.scss
- src/linodes/components/Linode.js
Closes #699 
Messed up my git trying to type too fast.
> Move distro image in Dashboard

- src/linodes/components/Linode.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/IndexPage.spec.js
> backup status links to backups page

- src/linodes/create/components/Details.js
- src/linodes/linode/backups/layouts/IndexPage.js
> add "mo" to indicate montly price

- scss/components/form.scss
- scss/manager.scss
- src/linodes/components/Linode.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- src/linodes/linode/settings/layouts/AlertsPage.js
- src/linodes/linode/settings/layouts/DisplayPage.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
> Misc css fixes

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> add option groups to kernel select

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/data/linodes.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> Add initrd

- src/linodes/linode/settings/layouts/EditConfigPage.js
> Reorder config page

- scss/components/FormRow.scss
- scss/components/datacenter.scss
- scss/components/index.scss
- scss/linodes/components/Distribution.scss
- scss/linodes/components/Distributions.scss
- scss/linodes/components/index.scss
- scss/linodes/index.scss
- scss/linodes/linode/index.scss
- scss/linodes/linode/layouts/RebuildPage.scss
- scss/linodes/linode/layouts/index.scss
- scss/manager.scss
- scss/mixins.scss
- src/api/gen.js
- src/api/genThunks.js
- src/api/linodes.js
- src/components/FormRow.js
- src/components/Notifications.js
- src/layouts/Layout.js
- src/linodes/components/Distribution.js
- src/linodes/components/Distributions.js
- src/linodes/create/components/Details.js
- src/linodes/create/components/Source.js
- src/linodes/linode/index.js
- src/linodes/linode/layouts/RebuildPage.js
- test/linodes/components/Distribution.spec.js
- test/linodes/create/components/Source.spec.js
> Add rebuild page

- src/linodes/create/components/Source.js
- test/linodes/create/components/Source.spec.js
> Add Clone and StackScripts to create source tabs

- scss/components/status-dropdown.scss
- src/linodes/components/StatusDropdown.js
> Fixed status box width

- scss/components/Notifications.scss
> Make notifications slide down

- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/layouts/RescuePage.spec.js
> Rescue mode rebase

- src/components/Confirm.js
- src/linodes/layouts/IndexPage.js
- test/components/Confirm.spec.js
- test/linodes/layouts/IndexPage.spec.js
> Confirm deletion of multiple Linodes

- scss/components/status-dropdown.scss
- src/linodes/components/StatusDropdown.js
- src/linodes/linode/layouts/IndexPage.js
> Stripe progress bar and fix over progression

- src/api/configs/datacenters.js
- src/api/configs/distributions.js
- src/api/configs/kernels.js
- src/api/configs/types.js
- src/api/events.js
- src/api/gen.js
- src/api/genThunks.js
- src/api/linodes.js
- src/constants.js
- src/linodes/create/components/Backups.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/IndexPage.js
- src/linodes/linode/layouts/IndexPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/layouts/Weblish.js
- src/linodes/linode/settings/components/ConfigPanel.js
- src/linodes/linode/settings/components/DiskPanel.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/data/linodes.js
- test/linodes/create/layout/IndexPage.spec.js
- test/linodes/layouts/IndexPage.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
- test/linodes/linode/layouts/RescuePage.spec.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> Poll for status updates and linode additions/deletions

- src/linodes/linode/settings/components/DiskPanel.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> Serial delete disks

- src/linodes/components/StatusDropdown.js
- test/data/linodes.js
- test/linodes/components/StatusDropdown.spec.js
> Show default status if unrecognized

- src/linodes/linode/layouts/IndexPage.js
> Delete to one config removed dropdown

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> remove the text slot

- src/linodes/layouts/IndexPage.js
> remove the word all from delete selected Linodes

- package.json
- src/components/PasswordInput.js
- test/components/PasswordInput.spec.js
> remove generate password button

- src/linodes/linode/backups/layouts/SummaryPage.js
- test/data/linodes.js
- test/linodes/linode/backups/layouts/SummaryPage.spec.js
> Wire up backup summary page

- src/fetch.js
- src/index.js
- src/layouts/Logout.js
- src/router.js
- src/session.js
- src/store.js
- test/router.spec.js
- test/session.spec.js
> Remove onEnter calls, hook into pre-preload for blocking authentication

- scss/manager.scss
- src/layouts/Layout.js
> source grey and to bottom

- README.md
- karma.conf.js
- src/components/DevTools.js
- src/store.js
- webpack.config.dev.js
> Dev-tools disabled in production env

- src/linodes/linode/backups/index.js
- src/linodes/linode/backups/layouts/BackupPage.js
- src/linodes/linode/backups/layouts/SummaryPage.js
- src/linodes/linode/backups/layouts/index.js
- test/data/linodes.js
- test/linodes/linode/backups/layouts/BackupPage.spec.js
- test/linodes/linode/backups/layouts/SummaryPage.spec.js
> Implement backup details page

- src/layouts/Layout.js
> Footer should not cover content

- scss/components/Header.scss
- scss/manager.scss
- scss/variables.scss
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- test/linodes/layouts/IndexPage.spec.js
- test/linodes/linode/layouts/DashboardPage.spec.js
- test/linodes/linode/networking/layouts/SummaryPage.spec.js
> Give columns more space

- scss/manager.scss
> Fix button vertical alignment

- src/api/configs/datacenters.js
- src/api/configs/distributions.js
- src/api/configs/kernels.js
- src/api/configs/types.js
- src/api/genThunks.js
- src/router.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
- test/router.spec.js
> Drop localstorage caching

- src/layouts/Layout.js
> Wait for OAuth token to become available before polling for events

- scss/components/Notifications.scss
- src/api/objects/Event.js
- src/components/Notifications.js
> Updated notification UI and more event support

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> Finnix option

- scss/linodes/components/ConfigSelectModal.scss
- scss/linodes/components/StatusDropdown.scss
- scss/linodes/components/index.scss
- src/linodes/components/ConfigSelectModal.js
- src/linodes/components/StatusDropdown.js
- src/linodes/linode/layouts/IndexPage.js
- test/data/linodes.js
- test/linodes/components/ConfigSelectModal.spec.js
- test/linodes/components/StatusDropdown.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
> Implement config selection modal

- scss/linodes/linode/layouts/RebuildPage.scss
- src/components/Confirm.js
- src/components/Feedback.js
- src/dnsmanager/components/NewMasterZone.js
- src/dnsmanager/layouts/IndexPage.js
- src/linodes/linode/backups/components/RestorePanel.js
- src/linodes/linode/backups/components/SnapshotPanel.js
- src/linodes/linode/backups/layouts/SettingsPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/components/DiskPanel.js
- src/linodes/linode/settings/layouts/AlertsPage.js
- src/linodes/linode/settings/layouts/DisplayPage.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/components/Confirm.spec.js
- test/linodes/layouts/IndexPage.spec.js
- test/linodes/linode/backups/layouts/SettingsPage.spec.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
- test/linodes/linode/settings/layouts/DisplayPage.spec.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> switch primary and danger buttons to default

- src/api/events.js
- src/components/Header.js
- src/components/Notifications.js
- src/layouts/Layout.js
- test/common.js
- test/components/Header.spec.js
- test/data/events.js
- test/layouts/Layout.spec.js
> Use seen for notification count

- src/api/linodes.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- test/data/linodes.js
- test/linodes/linode/networking/layouts/SummaryPage.spec.js
> Update networking page to match API changes

- scss/manager.scss
- src/layouts/Layout.js
> sticky and dull source link

- scss/manager.scss
> Add top and bottom padding back

- src/api/configs/datacenters.js
- src/api/configs/distributions.js
- src/api/configs/dnszones.js
- src/api/configs/events.js
- src/api/configs/kernels.js
- src/api/configs/linodes.js
- src/api/configs/types.js
- src/api/gen.js
- src/api/genThunks.js
- src/linodes/linode/layouts/Weblish.js
- test/api/gen.spec.js
- test/api/genThunks.spec.js
- test/api/linodes.spec.js
- test/linodes/linode/layouts/Weblish.spec.js
> Add api tests

- scss/linodes/components/StatusDropdown.scss
Addresses #825 
also:
- removes a line-height
- uses color var
> remove 1px adjustment and unnecessary line-height

- scss/manager.scss
- src/linodes/components/Linode.js
#827 
Reduces space between checkbox and label to just the padding, 15px
Adds pointer cursor on hover
> Checkbox label spacing

- scss/manager.scss
- src/linodes/components/Linode.js
> adjustments for ip centering

- scss/manager.scss
- src/linodes/linode/layouts/IndexPage.js
- test/linodes/linode/backups/layouts/IndexPage.spec.js
- test/linodes/linode/layouts/IndexPage.spec.js
- test/linodes/linode/settings/layouts/IndexPage.spec.js
> Add control-click or cmd-click opens new browser tab

- scss/manager.scss
- src/linodes/create/components/Source.js
fixes a tab style issue on the create form
> Adds form specific tab class for tabs without links

- src/components/form/CancelButton.js
- src/components/form/Form.js
- src/components/form/SubmitButton.js
- src/components/form/index.js
- src/linodes/linode/settings/components/DiskPanel.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
Begins to address issue defined in #806, by starting with the DiskPanel form
Form elements were added where missing to get appropriate submit behavior for both buttons and inputs.
Regarding addition of button types, see implicit-submission notes here: https://html.spec.whatwg.org/multipage/forms.html#implicit-submission
> Disk panel form consistency

- src/api/gen.js
> Fix repeated disk creation

- scss/components/PasswordInput.scss
- scss/components/index.scss
- src/components/PasswordInput.js
- test/components/PasswordInput.spec.js
> password strength meter and time to crack text appears on separate line

- src/linodes/linode/settings/layouts/DisplayPage.js
- test/linodes/linode/settings/layouts/DisplayPage.spec.js
> Redirect when Linode label changes

- src/linodes/create/components/Details.js
- test/linodes/create/components/Details.spec.js
> remove group from create

- src/api/events.js
> Stop events from being overwritten by seen

- scss/manager.scss
- src/linodes/linode/settings/layouts/EditConfigPage.js
> sub-headers for add/edit config

- scss/manager.scss
- scss/variables.scss
> Use smaller font for linode title

- src/api/events.js
> Fix browser hang on notification show

- scss/components/Notifications.scss
- src/components/Notifications.js
- test/components/Notifications.spec.js
> Unbold read notification title

- src/api/events.js
> Fix notifications seen bug

- src/api/linodes.js
- src/linodes/components/StatusDropdown.js
> Use default progress while progress is unavailable

- src/components/Header.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
> Disable unwired

- scss/manager.scss
> Fix alert checkbox alignment

- src/linodes/linode/settings/layouts/EditConfigPage.js
> Add help text to boot helpers in add/edit config

- src/linodes/linode/layouts/RescuePage.js
> Align rescue page buttons with input fields

- scss/manager.scss
- src/linodes/components/Linode.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/settings/components/DiskPanel.js
- src/linodes/linode/settings/layouts/AlertsPage.js
> grey out dashboard ipv6

- scss/manager.scss
Closes #852 
Disabled all mouse events to disabled elements.
> fix disabled button hover state

- index.html
- package.json
- src/components/PasswordInput.js
- test/index.js
Reduced the pre-gzip size from ~2.1mb to ~1.2mb.
> Load zxcvbn library from script tag not bundle

- src/linodes/components/Linode.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- test/linodes/components/Linode.spec.js
- test/linodes/linode/layouts/DashboardPage.spec.js
- test/linodes/linode/networking/layouts/SummaryPage.spec.js
> Netmask display

- src/actions/title.js
- src/dnsmanager/layouts/CreatePage.js
- src/dnsmanager/layouts/IndexPage.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/layouts/IndexPage.js
- src/reducers/index.js
- src/reducers/title.js
> Set titles to current page header

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> add config max ram option

- src/linodes/components/Linode.js
- src/linodes/linode/layouts/DashboardPage.js
- test/linodes/components/Linode.spec.js
closes #828 
Linodes page:
List view:
Card view:
Dashboard page:
> add word backup to everywhere except dashboard page

- scss/components/Header.scss
> Add border to notification count

- scss/components/Header.scss
> change from an oval to an elongated bubble for notifications

- scss/components/modal.scss
> move modal title down 1px

- scss/styleguide/components/StyleguideSubSection.scss
- scss/styleguide/components/index.scss
- src/styleguide/components/sections/Overview.js
closes #885 
Feedback and suggestions on wording and content welcome!
> Styleguide overview

- scss/components/Dropdown.scss
- scss/components/datacenter.scss
- scss/components/index.scss
- scss/manager.scss
- src/components/Dropdown.js
- src/styleguide/components/sections/Buttons.js
Closes #889
(redid PR since the first branch seems messed up)
> Add dropdowns to buttons section in the styleguide

- scss/components/Header.scss
- scss/components/badge.scss
- scss/styleguide/components/sections/StyleguideForm.scss
- src/linodes/create/components/Details.js
- src/styleguide/components/sections/Forms.js
- adds label-col where missing
- shrinks size of badges and adjusts positions
- adds some missing descriptions
- fixes labels on Add a Linode > Details
> Cleanup styleguide forms

- scss/manager.scss
- src/linodes/layouts/IndexPage.js
> Add group colspan, fix border

- src/linodes/components/Distribution.js
> Rename no distro to empty

- src/linodes/linode/settings/layouts/EditConfigPage.js
> Move max ram above input

- src/linodes/linode/settings/components/ConfigPanel.js
- test/linodes/linode/settings/components/ConfigPanel.spec.js
> Remove <th> from config table

- src/linodes/linode/layouts/RebuildPage.js
> Update rebuild page form

- src/linodes/linode/layouts/RebuildPage.js
> Rebuild validation and inputs

- src/api/objects/Event.js
- src/components/Notifications.js
- test/data/events.js
> fix event bug due to api parity

- src/components/form/PasswordInput.js
- test/components/form/PasswordInput.spec.js
> Change password strength message

- src/linodes/linode/backups/layouts/SettingsPage.js
- test/linodes/linode/backups/layouts/SettingsPage.spec.js
> Update backups settings

- src/linodes/linode/networking/layouts/SummaryPage.js
- test/data/linodes.js
- test/linodes/linode/networking/layouts/SummaryPage.spec.js
> Updated network page with recent API changes

- scss/components/form/PasswordInput.scss
> Password strength bar to match input field size

- src/api/genThunks.js
- src/linodes/linode/layouts/IndexPage.js
It was both fetching outdated objects incorrectly and incorrectly deciding which objects were outdated. Closes #945
> Fix genThunks

- src/linodes/linode/layouts/RescuePage.js
- src/linodes/linode/settings/components/ConfigPanel.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
- src/router.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> Router waits on all preloads it started

- scss/components/form/form.scss
- scss/linodes/linode/settings/components/DiskPanel.scss
- src/components/form/FormGroupError.js
- src/components/form/Select.js
- src/linodes/linode/settings/components/AddModal.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> AddModal form validation and Input components

- src/linodes/linode/settings/components/EditModal.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
> Edit disk form components

- src/components/Sidebar.js
- src/index.js
- src/linodes/linode/layouts/IndexPage.js
- src/profile/index.js
- src/profile/layouts/AuthenticationPage.js
- src/profile/layouts/IndexPage.js
- test/components/Sidebar.spec.js
> Profile skeleton

- src/linodes/linode/settings/layouts/EditConfigPage.js
> Config update as dict

- src/profile/index.js
- src/profile/integrations/index.js
- src/profile/integrations/layouts/IndexPage.js
- src/profile/layouts/IndexPage.js
> Add integrations skeleton

- scss/components/PrimaryPage.scss
- scss/components/PrimaryTable.scss
- scss/components/index.scss
- scss/layout/index.scss
- scss/manager.scss
- src/components/form/Checkbox.js
- src/dnsmanager/layouts/IndexPage.js
- src/linodes/components/Linode.js
- src/linodes/layouts/IndexPage.js
- test/dnsmanager/layouts/IndexPage.spec.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/IndexPage.spec.js
> Refactor dns and linodes page and clean up dns styles

- src/linodes/linode/layouts/RescuePage.js
> update rescue page to use form components

- src/linodes/linode/layouts/RescuePage.js
> change col-sm-9 to 10 to make the combo equal 12

- src/components/notifications/NotificationList.js
- src/components/notifications/NotificationListItem.js
- src/components/notifications/index.js
- src/components/notifications/util.js
- src/layouts/Layout.js
- test/components/notifications/NotificationList.spec.js
> Add X-Filter header for updated

- src/api/linodes.js
- src/linodes/components/ConfigSelectModalBody.js
- src/linodes/linode/layouts/RescuePage.js
- test/linodes/linode/layouts/RescuePage.spec.js
> Reboot to rescue endpoint

- src/api/configs/nodebalancers.js
- src/api/index.js
- src/api/reducer.js
- src/nodebalancers/index.js
- src/nodebalancers/layouts/CreatePage.js
- src/nodebalancers/layouts/IndexPage.js
The API support for what we'd like to [do with this](https://cloud.githubusercontent.com/assets/3925912/22255384/3077566c-e225-11e6-87cb-0d8ba8533dde.png) does not exist right now.
This is about all that I could do with the response we currently get. However, it is in good shape to be continued at a later point.
Dependent on #1102
Closes #1076
> Nodebalancer list

- src/layouts/Layout.js
fixes a bug in linode status, see https://github.com/linode/manager/issues/1167 for details
> Reverts the updated filter to fix linode status

- scss/components/buttons.scss
> Fix select all checkbox sizing

- scss/linodes/components/StatusDropdown.scss
- src/linodes/components/StatusDropdown.js
- test/linodes/components/StatusDropdown.spec.js
> fix status indicator

- assets/weblish/weblish.css
> Fix weblish font size

- scss/components/buttons.scss
> cancel button fix

- scss/components/form/form.scss
- src/nodebalancers/layouts/CreatePage.js
> css fixes for nodebalancers create

- scss/components/buttons.scss
> catch rounded corner

- scss/components/form/form.scss
- src/dnsmanager/components/NewMasterZone.js
- src/dnsmanager/layouts/CreatePage.js
> css fixes for dns zone

- scss/layout/Layout.scss
- scss/layout/index.scss
- scss/manager.scss
- src/layouts/Logout.js
- src/linodes/actions/index.js
- src/linodes/components/Linode.js
- src/linodes/layouts/IndexPage.js
- src/linodes/reducers/index.js
- test/layouts/Logout.spec.js
- test/linodes/actions/index.spec.js
- test/linodes/components/Linode.spec.js
- test/linodes/layouts/IndexPage.spec.js
- test/linodes/reducers/index.spec.js
> Drop Linode card view

- src/components/Card.js
- src/linodes/linode/layouts/RescuePage.js
> Fix Rescue page layout error and Card bug

- src/components/Sidebar.js
- src/index.js
- src/longview/index.js
No reason to not just get this out of the way.
> Remove longview link

- scss/components/backup.scss
- src/linodes/linode/backups/layouts/SummaryPage.js
- test/linodes/linode/backups/layouts/SummaryPage.spec.js
> Fixed backup hover style on backup summary page

- src/linodes/linode/backups/index.js
- src/linodes/linode/backups/layouts/HistoryPage.js
- src/linodes/linode/backups/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/index.js
- test/linodes/linode/backups/layouts/IndexPage.spec.js
> remove-backup-hist-tab

- src/linodes/components/Linode.js
- test/linodes/components/Linode.spec.js
> Unique IPs IDs

- scss/components/buttons.scss
> Fix dashboard buttons 1171

- src/billing/index.js
- src/billing/layouts/IndexPage.js
- src/components/Sidebar.js
- src/index.js
- src/linodes/linode/backups/index.js
- src/linodes/linode/backups/layouts/HistoryPage.js
- src/linodes/linode/backups/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/index.js
- src/settings/index.js
- src/settings/layouts/IndexPage.js
- src/support/layouts/IndexPage.js
- src/users/index.js
- src/users/layouts/IndexPage.js
- test/linodes/linode/backups/layouts/IndexPage.spec.js
> Routes and source

- src/components/form/PasswordInput.js
- src/linodes/create/components/Details.js
- test/linodes/create/components/Details.spec.js
> Disable password input on empty linode

- scss/components/modal.scss
- src/api/configs/dnszones.js
- src/components/form/ModalFormGroup.js
- src/components/form/Select.js
- src/components/form/index.js
- src/components/modals/ConfirmModalBody.js
- src/components/modals/ModalShell.js
- src/components/modals/index.js
- src/dnsmanager/components/EditSOARecord.js
- src/dnsmanager/components/SelectTTL.js
- src/dnsmanager/layouts/IndexPage.js
- src/dnsmanager/layouts/ZonePage.js
- src/linodes/components/ConfigSelectModalBody.js
- src/linodes/linode/settings/components/AddModal.js
- src/linodes/linode/settings/components/DeleteModal.js
- src/linodes/linode/settings/components/EditModal.js
- src/styleguide/components/sections/Modals.js
- test/common.js
- test/dnsmanager/components/EditSOARecord.spec.js
- test/dnsmanager/layouts/IndexPage.spec.js
- test/nodebalancers/layout/CreatePage.spec.js
> Edit SOA record and abstract some form modal components

- src/components/Tabs.js
- src/dnsmanager/layouts/CreatePage.js
> Add a zone uses internal Tabs

- scss/components/backup.scss
- src/linodes/linode/backups/layouts/SummaryPage.js
> Adjust snapshot padding/margin

- src/api/util.js
- test/api/util.spec.js
Closes #942 (and solves the same problem for all other sections that do a label lookup)
> 404 on label lookup failure

- src/linodes/linode/layouts/RescuePage.js
- test/linodes/linode/layouts/RescuePage.spec.js
> Use components in Rescue Page

- src/components/Dropdown.js
- src/dnsmanager/actions/index.js
- src/dnsmanager/layouts/IndexPage.js
- src/dnsmanager/reducers/index.js
- src/reducers/index.js
- test/dnsmanager/layouts/IndexPage.spec.js
> Dnsmanager select all

- src/dnsmanager/components/EditMXRecord.js
- src/dnsmanager/layouts/ZonePage.js
- test/dnsmanager/components/EditMXRecord.spec.js
> Edit MX records

- src/dnsmanager/components/EditTXTRecord.js
- src/dnsmanager/components/SelectDNSSeconds.js
- src/dnsmanager/layouts/ZonePage.js
- test/dnsmanager/components/EditTXTRecord.spec.js
> Dns edit txt

- scss/components/PreloadIndicator.scss
Open for discussion
Closes #1238 
Closes #788
> Preload does not go backwards

- src/components/notifications/EventTypes.js
- src/components/notifications/NotificationListItem.js
- test/components/notifications/EventTypes.spec.js
- test/data/events.js
> Event entity is now an object

- src/dnsmanager/components/EditARecord.js
- src/dnsmanager/layouts/ZonePage.js
- test/dnsmanager/components/EditARecord.spec.js
> Edit A records

- scss/components/cards/SecondaryCard.scss
- src/components/cards/SecondaryCard.js
- src/constants.js
- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/index.js
- src/profile/integrations/layouts/AuthorizedApplicationsPage.js
- test/data/index.js
- test/data/tokens.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/layouts/AuthorizedApplications.spec.js
> Display authorized applications

- src/api/account.js
- src/components/form/PasswordInput.js
- src/profile/layouts/AuthenticationPage.js
- test/profile/layouts/AuthenticationPage.spec.js
> wire up profile password change

- src/linodes/linode/settings/layouts/EditConfigPage.js
> Don't redirect on config create

- scss/components/NavigationHeader.scss
- scss/components/cards/SecondaryCard.scss
- scss/components/index.scss
- src/api/apiResultActionReducerGenerator.js
- src/api/clients.js
- src/api/configs/clients.js
- src/components/cards/SecondaryCard.js
- src/constants.js
- src/fetch.js
- src/profile/integrations/components/CreateApplication.js
- src/profile/integrations/components/EditApplication.js
- src/profile/integrations/components/MyApplication.js
- src/profile/integrations/layouts/MyApplicationsPage.js
- test/profile/integrations/components/CreateApplication.spec.js
- test/profile/integrations/components/EditApplication.spec.js
- test/profile/integrations/components/MyApplication.spec.js
- test/profile/integrations/layouts/MyApplicationsPage.spec.js
> Add edit applications

- src/api/linodes.js
- src/linodes/linode/layouts/ResizePage.js
- test/data/types.js
- test/linodes/components/Plan.spec.js
- test/linodes/linode/layouts/ResizePage.spec.js
> Resize Linode

- src/components/SecondaryTable.js
- src/dnsmanager/layouts/ZonePage.js
- test/data/dnszones.js
- test/dnsmanager/layouts/ZonePage.spec.js
> Dns delete record

- src/api/apiResultActionReducerGenerator.js
- test/api/apiResultActionReducerGenerator.spec.js
> Adds list of ids and optional sort function support

- src/api/util.js
- test/api/util.spec.js
precursor to changes for #1191
> Adds util functions

- src/api/apiActionReducerGenerator.js
- src/api/util.js
- src/fetch.js
- test/api/util.spec.js
> Adds default stringify for api calls

- src/api/linodes.js
- src/components/buttons/Button.js
- src/components/form/ModalFormGroup.js
- src/dnsmanager/components/EditARecord.js
- src/dnsmanager/components/EditCNAMERecord.js
- src/dnsmanager/components/EditMXRecord.js
- src/dnsmanager/components/EditNSRecord.js
- src/dnsmanager/components/EditSOARecord.js
- src/dnsmanager/components/EditSRVRecord.js
- src/dnsmanager/components/EditTXTRecord.js
- src/linodes/linode/networking/components/EditRDNS.js
- src/linodes/linode/networking/layouts/IPManagementPage.js
- src/linodes/linode/networking/layouts/ReverseDNSPage.js
- src/linodes/linode/networking/layouts/index.js
- test/linodes/linode/networking/components/EditRDNS.spec.js
- test/linodes/linode/networking/layouts/ReverseDNSPage.spec.js
> Add reverse dns

- scss/components/PrimaryTable.scss
> Links are links

- src/fetch.js
- test/fetch.spec.js
> Drop X-Status header

- src/api/configs/tokens.js
- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/layouts/AuthorizedApplicationsPage.js
- src/profile/integrations/layouts/PersonalAccessTokensPage.js
- test/profile/integrations/layouts/AuthorizedApplications.spec.js
> revoke app 1219

- src/profile/integrations/components/CreateApplication.js
- src/profile/integrations/components/EditApplication.js
- src/profile/integrations/components/MyApplication.js
- src/profile/integrations/layouts/MyApplicationsPage.js
- test/data/clients.js
- test/profile/integrations/components/CreateApplication.spec.js
- test/profile/integrations/components/EditApplication.spec.js
- test/profile/integrations/components/MyApplication.spec.js
- test/profile/integrations/layouts/MyApplicationsPage.spec.js
> Delete My Application 1220

- src/api/apiActionReducerGenerator.js
- src/api/linodes.js
- src/api/util.js
- src/components/SecondaryTable.js
- src/components/cards/index.js
- src/components/form/Checkbox.js
- src/linodes/linode/networking/components/IPSharing.js
- src/linodes/linode/networking/components/IPTransfer.js
- src/linodes/linode/networking/components/index.js
- src/linodes/linode/networking/layouts/IPManagementPage.js
- src/router.js
- test/data/linodes.js
- test/linodes/components/Linode.spec.js
- test/linodes/linode/layouts/DashboardPage.spec.js
- test/linodes/linode/networking/components/IPSharing.spec.js
> Ip sharing

- src/api/apiActionReducerGenerator.js
- src/api/linodes.js
- src/fetch.js
- src/linodes/linode/networking/components/IPList.js
- src/linodes/linode/networking/components/IPSharing.js
- src/linodes/linode/networking/components/IPTransfer.js
- src/linodes/linode/networking/layouts/IPManagementPage.js
- test/linodes/linode/networking/components/IPTransfer.spec.js
> Ip transfer

- scss/components/cards/SecondaryCard.scss
- src/api/configs/users.js
- src/api/index.js
- src/api/reducer.js
- src/components/cards/SecondaryCard.js
- src/users/layouts/IndexPage.js
- test/data/index.js
- test/data/users.js
- test/users/layouts/IndexPage.spec.js
> user list 1190

- scss/components/buttons.scss
- scss/components/form/form.scss
- scss/components/modal.scss
- scss/layout/Layout.scss
- src/layouts/Layout.js
- src/linodes/linode/settings/components/AddModal.js
- src/linodes/linode/settings/components/DeleteModal.js
- src/linodes/linode/settings/components/EditModal.js
- test/linodes/linode/settings/components/DiskPanel.spec.js
Allows modals to scroll when the screen is not tall enough and fixes cancel buttons.
> Allow modal to scroll

- scss/manager.scss
- scss/profile/integrations/components/OAuthScopes.scss
- scss/utilities.scss
- src/api/account.js
- src/api/configs/tokens.js
- src/components/modals/ConfirmModalBody.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
- src/profile/components/SelectExpiration.js
- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/components/CreateApplication.js
- src/profile/integrations/components/CreatePersonalAccessToken.js
- src/profile/integrations/components/EditPersonalAccessToken.js
- src/profile/integrations/components/OAuthScopes.js
- src/profile/integrations/components/PersonalAccessToken.js
- src/profile/integrations/layouts/AuthorizedApplicationsPage.js
- src/profile/integrations/layouts/PersonalAccessTokensPage.js
- src/profile/layouts/AuthenticationPage.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/components/CreatePersonalAccessToken.spec.js
- test/profile/integrations/components/EditPersonalAccessToken.spec.js
- test/profile/integrations/components/PersonalAccessToken.spec.js
- test/profile/integrations/layouts/AuthorizedApplicationsPage.spec.js
- test/profile/integrations/layouts/PersonalAccessTokensPage.spec.js
- test/profile/layouts/AuthenticationPage.spec.js
Closes #1154, closes #1367, closes #1335
TODO:
> Add edit delete PAT

- src/api/apiActionReducerGenerator.js
- src/api/clients.js
- src/components/modals/ConfirmModalBody.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
- src/profile/integrations/components/CreateApplication.js
- src/profile/integrations/components/CreatePersonalAccessToken.js
- src/profile/integrations/components/MyApplication.js
- src/profile/integrations/components/OAuthScopes.js
- src/profile/layouts/AuthenticationPage.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/components/CreateApplication.spec.js
- test/profile/integrations/components/MyApplication.spec.js
- test/profile/integrations/components/PersonalAccessToken.spec.js
Depends on #1368, closes #1221, closes #1376
> Reset client secret

- src/api/apiResultActionReducerGenerator.js
- src/api/configs/users.js
> Allow variable api primary key

- src/linodes/components/StatusDropdown.js
- src/linodes/components/WeblishLaunch.js
- src/linodes/linode/layouts/DashboardPage.js
decouples weblish launch from status dropdown
> Separate weblish from status dropdown

- src/constants.js
> increase default polling timeout to 15 seconds

- karma.conf.js
- scss/manager.scss
- src/constants.js
- src/layouts/Layout.js
- webpack.config.dev.js
- webpack.config.prod.js
> Add version

- src/dnsmanager/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
fixes excess 5px margin on primary list
> Conditional group label rendering

- src/linodes/linode/layouts/RebuildPage.js
> Add needed clearfix on rebuild page

- src/nodebalancers/layouts/CreatePage.js
> Selects a default dc in nodebalancer create

- src/nodebalancers/layouts/IndexPage.js
> Fix create helper wording on nodebalancer index

- scss/components/tables/Table.scss
- scss/manager.scss
- scss/support/layouts/Tickets.scss
- src/api/configs/support.js
- src/api/configs/tickets.js
- src/api/index.js
- src/api/reducer.js
- src/components/notifications/EventTypes.js
- src/components/notifications/index.js
- src/components/tables/Table.js
- src/components/tables/cells/LinkCell.js
- src/linodes/layouts/IndexPage.js
- src/support/layouts/IndexPage.js
- test/components/notifications/EventTypes.spec.js
- test/data/index.js
- test/data/tickets.js
- test/support/layouts/IndexPage.spec.js
> Add support ticket list

- src/api/apiActionReducerGenerator.js
- src/api/linodes.js
- src/api/polling.js
- src/components/Header.js
- src/components/notifications/Notifications.js
- src/layouts/Layout.js
- src/linodes/components/StatusDropdown.js
- src/linodes/create/layouts/IndexPage.js
- test/api/polling.spec.js
- test/components/notifications/Notifications.spec.js
- test/layouts/Layout.spec.js
- test/linodes/create/layout/IndexPage.spec.js
closes #1423 
breaks polling into it's own module that is used in both notifications, and linode
> Fix linode status change break

- scss/components/Header.scss
- scss/components/Notifications.scss
- src/components/Header.js
- src/components/Sidebar.js
Kinda makes the sidebar look ugly in the meantime. But this will help move the process along.
> Add relevant links to user dropdown

- scss/components/TicketHelper.scss
- scss/components/form/form.scss
- scss/components/index.scss
- scss/utilities.scss
- src/components/notifications/Notifications.js
- src/support/index.js
- src/support/layouts/CreatePage.js
- src/support/layouts/IndexPage.js
- test/common.js
- test/support/layouts/CreatePage.spec.js
Depends on #1382, closes #1201
> Create support ticket

- src/dnsmanager/layouts/CreatePage.js
- src/dnsmanager/layouts/ZonePage.js
- src/linodes/create/layouts/IndexPage.js
- src/linodes/linode/layouts/IndexPage.js
- src/nodebalancers/layouts/CreatePage.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
> Add crumbs and misc nodebalancer formatting

- .travis.yml
> Ignore css changes in tests

- src/linodes/components/StatusDropdown.js
> start polling linode while provisioning

- src/components/notifications/NotificationListItem.js
> Add username to event notification display

- src/dnsmanager/components/EditSOARecord.js
- src/dnsmanager/layouts/ZonePage.js
- test/dnsmanager/layouts/ZonePage.spec.js
> replace history state if zone label changes

- src/dnsmanager/components/NewSlaveZone.js
> Updates label wording on DNS Slave Zone

- src/linodes/create/components/Details.js
a support ticket if the account Limit has been reached.
This information is not currently returned from the API until after the
Linode is attempted to be created and the only information we get is the
error response.  In order to bring more ease of use to the app we link
to the create a ticket page.
closes #790
> Add a link next to the error message returned from the API to create

- src/linodes/linode/settings/layouts/EditConfigPage.js
> change xvda to sda for placeholder

- src/api/polling.js
- src/api/util.js
- src/components/notifications/Notifications.js
only polls for most recent (in addition to unseen) after initial data received.
> Add filter to notifications poll

- src/styleguide/components/sections/Forms.js
> fix bad button import

- src/dnsmanager/components/NewMasterZone.js
> Fix location of error in create master zone

- src/dnsmanager/layouts/IndexPage.js
> Simplify and correct grouping of domains

- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
> Rename Performance to Graphs

- scss/components/tables/Table.scss
- src/components/tables/cells/NameserversCell.js
- src/dnsmanager/layouts/ZonePage.js
> Hook up edit and delete modals

- src/linodes/create/components/Details.js
Up for discussion. Requested by @Dorthu , closes #1494
> Give reason why password is disabled on Empty selection

- src/components/form/Checkboxes.js
- src/linodes/linode/settings/layouts/EditConfigPage.js
> Fixes edit config page

- scss/components/Badge.scss
- scss/components/Header.scss
- scss/components/index.scss
- src/components/Header.js
- src/styleguide/components/sections/Forms.js
> Rename badge to component badge, fix padding and missing border

- src/linodes/linode/layouts/DashboardPage.js
> Fix ssh buttons

- src/actions/errors.js
- src/api/util.js
- src/layouts/Layout.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/IndexPage.js
- src/nodebalancers/nodebalancer/layouts/EditConfigPage.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
- src/support/layouts/TicketPage.js
- src/users/user/layouts/IndexPage.js
This also fixes some bugs in the setError and fetch code. Closes https://github.com/linode/manager/issues/1234
> Don't redirect to the 404 page on error

- package.json
- src/components/Region.js
This was breaking a number of create pages.
> Fix renderRegion misnaming after refactor

- src/api/util.js
- src/components/notifications/EventTypes.js
- src/nodebalancers/layouts/IndexPage.js
- src/nodebalancers/nodebalancer/index.js
- src/nodebalancers/nodebalancer/layouts/AddConfigPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/EditConfigPage.js
- src/nodebalancers/nodebalancer/layouts/IndexPage.js
- src/nodebalancers/nodebalancer/layouts/SettingsPage.js
- test/data/nodebalancers.js
- test/nodebalancers/nodebalancer/layouts/AddConfigPage.spec.js
- test/nodebalancers/nodebalancer/layouts/DashboardPage.spec.js
- test/nodebalancers/nodebalancer/layouts/EditConfigPage.spec.js
- test/nodebalancers/nodebalancer/layouts/IndexPage.spec.js
- test/nodebalancers/nodebalancer/layouts/SettingsPage.spec.js
> NodeBalancer page in tabs and settings editable

- components/scss/components/modals/Modal.scss
- src/domains/layouts/ZonePage.js
- src/nodebalancers/layouts/IndexPage.js
- test/profile/integrations/components/CreatePersonalAccessToken.spec.js
> Fix nodebalancer and dns record deletions

- components/cards/CardImageHeader.js
- src/components/TimeDisplay.js
- src/components/notifications/NotificationListItem.js
- src/components/tables/cells/LastBackupCell.js
- src/layouts/OAuth.js
- src/linodes/components/Backup.js
- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/components/PersonalAccessToken.js
- src/support/components/TicketReply.js
- src/support/layouts/IndexPage.js
- test/components/TimeDisplay.spec.js
- test/layouts/Logout.spec.js
- test/support/components/TicketReply.spec.js
- test/support/layouts/IndexPage.spec.js
> User timezones

- src/router.js
Makes page changes behave like a normal site.
> Force scroll to top on page change

- components/scss/components/forms/Input.scss
- components/scss/defaults.scss
- components/scss/mixins.scss
I keep getting these placeholders confused for values.
> Lighten placeholder color

- scss/linodes/components/StatusDropdown.scss
> Fix power border

- src/linodes/linode/settings/layouts/EditConfigPage.js
- test/linodes/linode/settings/layouts/EditConfigPage.spec.js
> create linode config - use default network helper

- scss/layout/index.scss
> Increase height of "add" buttons

- components/scss/components/lists/List.scss
- components/scss/components/tables/Table.scss
- components/tables/Table.js
> Fix group position and color

- src/profile/integrations/components/MyApplication.js
- test/common.js
- test/profile/integrations/components/CreateApplication.spec.js
- test/profile/integrations/components/EditApplication.spec.js
Let tests run again, 21 failing
> [WIP] Fix tests

- docs/src/components/Method.js
Fixes cases where examples are not yet present:
> Optional examples

- docs/package.json
- docs/webpack.config.prod.js
- package.json
Current build size is 500kb or so. We should work on that.
> Add docs build script

- docs/index.html
- docs/scss/components/Example.scss
- docs/scss/docs/Layout.scss
- docs/scss/layout.scss
- docs/src/layouts/Layout.js
fixes varying height and width issues across different pages
> Fix docs layout

- src/nodebalancers/nodebalancer/layouts/SettingsPage.js
- test/nodebalancers/nodebalancer/layouts/SettingsPage.spec.js
Closes #1626 
We still have the bug where the label doesn't match with content on the right.  Same problem exists on other pages.
> Nb add missing fields

- docs/CHANGELOG.md
- docs/package.json
Docs needs a package version bump, to be followed by manager release and tag
> Add changelog and bump version for docs

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/profile/integrations/components/CreatePersonalAccessToken.js
- src/profile/integrations/components/MyApplication.js
To test, try to reset the secret for one of "My Applications".
> Fix client reset secret not shown

- src/api/nodebalancers.js
- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
> Node graph

- components/tables/cells/ButtonCell.js
- scss/components/Tables/Cells/Columns.scss
- src/components/forms/FormSummary.js
- src/linodes/linode/networking/components/EditRDNS.js
- src/linodes/linode/networking/components/IPSharing.js
- src/linodes/linode/networking/components/IPTransfer.js
- src/linodes/linode/networking/layouts/IPManagementPage.js
- src/linodes/linode/networking/layouts/IndexPage.js
- src/linodes/linode/networking/layouts/ReverseDNSPage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- src/linodes/linode/settings/components/ConfigPanel.js
- src/nodebalancers/nodebalancer/configs/layouts/ViewConfigPage.js
- test/linodes/linode/networking/components/EditRDNS.spec.js
- test/linodes/linode/networking/components/IPSharing.spec.js
- test/linodes/linode/networking/components/IPTransfer.spec.js
- test/linodes/linode/networking/layouts/ReverseDNSPage.spec.js
- test/linodes/linode/settings/components/ConfigPanel.spec.js
Closes https://github.com/linode/manager/issues/1499
> Finish networking forms

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/users/components/UserForm.js
To test: go to user page, add a user, switch between restricted. Previously switching was broken.
> Fixed user restricted radio

- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
- test/data/nodebalancers.js
- test/nodebalancers/nodebalancer/layouts/DashboardPage.spec.js
> node up down

- scss/components/region.scss
- src/linodes/components/Plan.js
- src/linodes/create/components/Details.js
- src/linodes/linode/backups/layouts/IndexPage.js
- test/data/types.js
- test/linodes/components/Plan.spec.js
> Group plans

- docs/src/assets.js
- docs/src/layouts/Layout.js
> add something to the docs top nav

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/components/tables/cells/IPAddressCell.js
- test/data/linodes.js
- test/linodes/linode/layouts/DashboardPage.spec.js
Follow up merge to master after #1817
> Fix ipv4 rendering

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/components/Region.js
> Fix region rendering

- src/settings/layouts/IndexPage.js
- test/settings/layouts/IndexPage.spec.js
> reword account settings and make like current manager

- .travis.yml
- CHANGELOG.md
- README.md
- src/constants.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/Weblish.js
- test/linodes/linode/layouts/DashboardPage.spec.js
> Drop LISH_ROOT

- docs/docsConvert.js
- docs/src/components/MethodResponse.js
- docs/src/data/endpoints/api.js
> docs enums

- docs/docsConvert.js
- docs/scss/docs/Docs.scss
- docs/src/data/endpoints/api.js
fixes response examples for all top level GETs that provide them
Follow up for a few special cases: https://github.com/linode/manager/issues/1848
> fix missing example data

- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/layouts/AuthorizedApplicationsPage.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/components/CreatePersonalAccessToken.spec.js
- test/profile/integrations/layouts/AuthorizedApplicationsPage.spec.js
To test, revoke a token. It should not 404. Also, make sure tokens are rendered from most recently created to latest created.
> Revoke tokens correctly and render by most recent first

- src/domains/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- src/nodebalancers/layouts/IndexPage.js
> Fix mass delete

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
> docs 0.2.0

- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
> delete nodebalancer config

- src/nodebalancers/nodebalancer/configs/layouts/ViewConfigPage.js
- test/nodebalancers/nodebalancer/configs/layouts/ViewConfigPage.spec.js
> delete nb config node

- src/components/notifications/EventTypes.js
- src/components/notifications/NotificationListItem.js
> nb config events render correctly

- src/components/TimeDisplay.js
- src/components/graphs/LineGraph.js
- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
- src/profile/components/ChangeTimezone.js
- test/linodes/linode/layouts/DashboardPage.spec.js
> format tooltip data correctly

- CONTRIBUTING.md
bash was playing games with the exclamation point.
> update echo'd snippet to prevent shell interpretation

- docs/docsConvert.js
- docs/src/components/MethodResponse.js
- docs/src/data/endpoints/api.js
> fix some arrays in docs response and examples

- components/tabs/Tabs.js
- docs/src/components/Example.js
- docs/src/components/MethodRequest.js
> Fix subtle tabs bug

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/components/notifications/EventTypes.js
> Fix domain events

- CHANGELOG.md
- src/linodes/linode/layouts/Weblish.js
To test: hit Launch Console on a Linode. Closes #1887
> Fix weblish

- scss/components/AppLoader.scss
- scss/components/index.scss
- scss/layout/Layout.scss
- src/components/Header.js
- src/fetch.js
- src/index.js
- src/layouts/Layout.js
- src/layouts/Logout.js
- src/layouts/OAuth.js
- src/router.js
- src/session.js
- test/layouts/Logout.spec.js
- test/layouts/OAuth.spec.js
- test/router.spec.js
- test/session.spec.js
> Add app loader

- docs/src/App.js
> Redirect /reference to /introduction

- docs/src/RoutesGenerator.js
> fix docs reference index crumbs

- components/scss/components/tables/Table.scss
- scss/components/Tables/Cells/AuthScopeCell.scss
- scss/components/Tables/Cells/index.scss
- src/components/tables/cells/AuthScopeCell.js
- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/components/CreatePersonalAccessToken.js
- src/profile/integrations/components/PersonalAccessToken.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/components/CreatePersonalAccessToken.spec.js
- test/profile/integrations/components/PersonalAccessToken.spec.js
> Fix PAT creation

- src/linodes/linode/components/ResetRootPassword.js
> Fix disk password reset

- src/profile/index.js
- src/profile/layouts/IndexPage.js
- src/profile/layouts/ReferralsPage.js
> bring back referral page

- docs/src/api.js
- docs/src/data/endpoints/linodes.yaml
> replace warning html with plain text

- docs/scss/components/Tables/cells/Columns.scss
> Increase endpoint index link width for long urls

- docs/CHANGELOG.md
- docs/prebuild.js
- docs/src/api.js
- docs/src/data/endpoints/services.yaml
- docs/src/data/endpoints/types.yaml
- docs/src/data/objects/type.yaml
> Fix docs linode types

- src/components/graphs/LineGraph.js
> Graphs start Y at Zero

- src/api/linodes.js
- src/api/networking.js
- src/linodes/linode/networking/components/EditRDNS.js
- src/linodes/linode/networking/components/IPTransfer.js
- src/linodes/linode/networking/layouts/IPManagementPage.js
- src/linodes/linode/networking/layouts/IndexPage.js
- src/linodes/linode/networking/layouts/ReverseDNSPage.js
- src/router.js
- test/linodes/linode/networking/components/EditRDNS.spec.js
> Optimize networking requests and fix ip management page for now

- components/tables/Table.js
- docs/src/components/EndpointIndex.js
- docs/src/components/MethodParams.js
- docs/src/components/MethodResponse.js
- src/components/CreateHelper.js
- src/domains/components/MasterZone.js
- src/domains/layouts/IndexPage.js
- src/linodes/linode/settings/advanced/components/ConfigPanel.js
- src/nodebalancers/nodebalancer/configs/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
- test/domains/components/MasterZone.spec.js
- test/domains/layouts/IndexPage.spec.js
- test/linodes/linode/settings/advanced/components/ConfigPanel.spec.js
closes #1797 
updates empty state texts
> Add empty states for docs tables, update others

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/api/profile.js
- src/profile/layouts/AuthenticationPage.js
- test/data/profile.js
> two_factor_auth on profile is a boolean

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/prebuild.js
- docs/src/App.js
- docs/src/components/guides/python/Python.js
- docs/src/constants.js
- docs/src/layouts/Layout.js
> v0.4.0 Add v4 base url

- src/components/graphs/LineGraph.js
- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
> Change colors for line graphs

- src/router.js
> Don't render AppLoader in weblish window

- docs/npm-shrinkwrap.json
- docs/package.json
- docs/scss/components/Example.scss
- docs/scss/docs/Docs.scss
- docs/scss/index.scss
- docs/src/components/Example.js
- docs/src/components/MethodRequest.js
- docs/src/components/MethodResponseExample.js
- docs/src/components/guides/curl/CreateLinode.js
- docs/src/components/guides/curl/TestingWithCurl.js
- docs/src/components/intros/Access.js
- docs/src/components/intros/Errors.js
- docs/src/components/intros/Filtering.js
- docs/src/components/intros/Introduction.js
- docs/src/components/intros/Pagination.js
- docs/src/components/tables/Cells/ExampleCell.js
closes #1753 
Adds syntax highlighting for curl, json, and python via highlight.js
Adds copy-to-clipboard buttons to curl + python examples via clipboard.js
Uses Darkula theme, other themes can be seen here: https://highlightjs.org/static/demo/
g)
Clipboard has a state change so you know something happened, and then resets:
> docs syntax highlighting and clipboard

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/scss/components/Endpoint.scss
- docs/scss/components/Method.scss
- docs/scss/components/Title.scss
- docs/scss/components/index.scss
- docs/src/components/Endpoint.js
- docs/src/components/Method.js
> docs v0.6.0 cost indicators ( and version for highlighting )

- src/layouts/Layout.js
> Fix page source 404

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/src/data/objects/distribution.yaml
> docs v0.7.1 rename recommended to deprecated

- components/modals/DeleteModalBody.js
> Add count to delete modal

- CHANGELOG.md
- components/scss/components/tabs/SubTabs.scss
- components/scss/components/tabs/Tabs.scss
- npm-shrinkwrap.json
- package.json
> reduce tab margins and padding

- CHANGELOG.md
- components/scss/components/tabs/Tabs.scss
- npm-shrinkwrap.json
- package.json
> retain tab active border color

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/src/data/endpoints/domains.yaml
- docs/src/data/objects/domain.yaml
- docs/src/data/objects/event.yaml
closes #1889 
closes #2003 
closes #1866
> docs v0.7.3 fix event enums and groups name

- components/scss/linode-components.scss
- components/scss/utilities.scss
- docs/src/components/intros/Introduction.js
- src/linodes/linode/components/ResetRootPassword.js
- src/linodes/linode/settings/advanced/components/DiskPanel.js
> add info block to intro page for PAT generation

- docs/scss/components/Title.scss
- docs/src/components/Endpoint.js
- docs/src/components/Method.js
- docs/src/components/intros/Access.js
> review oauth, add oauth field to endpoints

- docs/prebuild.js
- docs/src/data/endpoints/domains.yaml
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/nodebalancers.yaml
- docs/src/data/endpoints/stackscripts.yaml
- docs/src/data/objects/event.yaml
- docs/src/data/objects/linode.yaml
- docs/src/data/objects/linode_config.yaml
- docs/src/data/objects/profile.yaml
- docs/src/data/objects/usergrants.yaml
> Docs missing type

- README.md
- components/navigation/Header.js
- components/scss/components/modals/Modal.scss
- components/scss/components/navigation/Header.scss
- components/scss/variables.scss
- docs/scss/docs/Layout.scss
- docs/src/layouts/Layout.js
- scss/components/Notifications.scss
- scss/components/SessionMenu.scss
- scss/layout/Layout.scss
- src/components/Header.js
- src/constants.js
> Add beta banner and adjust README and constants

- src/nodebalancers/nodebalancer/components/ConfigForm.js
- test/nodebalancers/nodebalancer/configs/layouts/EditConfigPage.spec.js
- test/nodebalancers/nodebalancer/layouts/AddConfigPage.spec.js
> Add http body and path check inputs

- src/domains/components/EditSRVRecord.js
- src/domains/components/MasterZone.js
> fix SRV rendering

- docs/index.html
- docs/src/App.js
- docs/src/components/EndpointIndex.js
- docs/src/getting_started/Routes.js
- docs/src/getting_started/guides/GuidesIndex.js
> Add setTitle logic

- docs/src/getting_started/guides/curl/TestingWithCurl.js
- docs/src/getting_started/guides/python/CoreConcepts.js
- docs/src/getting_started/guides/python/Introduction.js
- docs/src/getting_started/guides/python/OAuthWorkflow.js
- docs/src/getting_started/intros/Access.js
- docs/src/getting_started/intros/Errors.js
- docs/src/getting_started/intros/Filtering.js
- docs/src/getting_started/intros/Introduction.js
- docs/src/getting_started/intros/Pagination.js
> add next links to docs

- docs/scss/components/MethodResponse.scss
- docs/src/components/MethodParams.js
- docs/src/components/MethodResponse.js
- docs/src/components/tables/Cells/index.js
- docs/src/components/tables/cells/NestedParentCell.js
> Add expandable icon to table rows

- src/linodes/linode/networking/layouts/SummaryPage.js
> Fix reset rdns wording and only display when relevant

- README.md
- docs/src/layouts/Layout.js
- src/components/Header.js
- src/components/SessionMenu.js
Accidentally closed this in #2141.
> Minor wording updates

- docs/scss/docs/VerticalNav.scss
- docs/src/App.js
- docs/src/RoutesGenerator.js
- docs/src/data/python/python.js
- docs/src/getting_started/Routes.js
- docs/src/layouts/Layout.js
closes #1870 
uses `location.path` to set an `active` class on matching nav items
uses the current hover state as active state, open to suggestions for improved styles though
> show active nav item in docs

- docs/src/components/EndpointIndex.js
> sort endpoints alphabetically

- src/profile/integrations/components/AuthorizedApplication.js
- src/profile/integrations/components/EditPersonalAccessToken.js
- src/profile/integrations/components/PersonalAccessToken.js
- src/profile/integrations/utilities.js
- test/profile/integrations/components/AuthorizedApplication.spec.js
- test/profile/integrations/components/PersonalAccessToken.spec.js
Closes https://github.com/linode/manager/issues/2138
> Fix oauth scope formatting

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/domains/components/MasterZone.js
> Apply tooltip to overflowing text in TXT record

- components/scss/components/tables/cells/TableCell.scss
- docs/index.html
- docs/scss/components/Article.scss
- docs/scss/components/EndpointIndex.scss
- docs/scss/components/Method.scss
- docs/scss/components/Tables/ColumnWidths.scss
- docs/scss/components/Title.scss
- docs/scss/docs/Layout.scss
- docs/scss/docs/ToggleNav.scss
- docs/scss/docs/VerticalNav.scss
- docs/scss/docs/index.scss
- docs/src/App.js
- docs/src/components/Endpoint.js
- docs/src/components/Method.js
- docs/src/getting_started/guides/curl/TestingWithCurl.js
- docs/src/layouts/Layout.js
> docs sidebar nav collapse

- src/domains/components/EditARecord.js
- src/domains/components/EditSRVRecord.js
- src/domains/components/MasterZone.js
- src/domains/components/SelectDNSSeconds.js
- test/domains/components/EditARecord.spec.js
- test/domains/components/MasterZone.spec.js
Closes #1296, closes #1289, closes #1942, closes #1279
> Fix some dns issues

- scss/manager.scss
> remove duplicate stylesheet import

- components/scss/components/tables/cells/TableCell.scss
- docs/scss/components/Article.scss
- docs/scss/components/EndpointIndex.scss
- docs/scss/components/Method.scss
- docs/scss/components/Tables/ColumnWidths.scss
- docs/scss/docs/Layout.scss
- docs/scss/docs/ToggleNav.scss
- docs/scss/index.scss
- docs/scss/layout.scss
- docs/src/data/python/linode_client.yaml
* Unhide dropdowns in tables
* Sidebar in docs collapses at 1000px not 768px. But tables stay 100% width until 768px
* Fixes broken Python LinodeClient yaml
> Misc docs (regression) fixes

- components/scss/components/forms/Input.scss
- components/scss/components/forms/form.scss
Closes #2179 
This is my first pull request! Please let me know if something needs to be changed or added.
> fixed nodebalancer ssl settings placeholder color

- components/scss/components/navigation/Menu.scss
- components/scss/components/navigation/index.scss
- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
> Add unit select to graphs

- docs/src/components/Method.js
- docs/src/data/endpoints/account.yaml
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/networking.yaml
- docs/src/data/endpoints/nodebalancers.yaml
> Hook up missing docs data

- components/dropdowns/Dropdown.js
- components/lists/controls/MassEditControl.js
- components/lists/controls/MassEditDropdown.js
- components/scss/components/dropdowns/Dropdown.scss
- src/domains/layouts/IndexPage.js
- src/linodes/components/Distribution.js
- src/linodes/components/StatusDropdown.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/networking/layouts/SummaryPage.js
- src/nodebalancers/layouts/IndexPage.js
- src/profile/integrations/components/MyApplication.js
- src/profile/integrations/components/PersonalAccessToken.js
- test/components/Dropdown.spec.js
- test/components/tables/controls/MassEditDropdown.spec.js
- test/domains/layouts/IndexPage.spec.js
- test/linodes/layouts/IndexPage.spec.js
- test/profile/integrations/components/PersonalAccessToken.spec.js
> Add support for grouping in Dropdowns

- src/profile/integrations/components/CreatePersonalAccessToken.js
- test/profile/integrations/components/CreatePersonalAccessToken.spec.js
> Enable support for no access tokens

- docs/prebuild.js
- docs/scss/components/Tables/cells/DescriptionCell.scss
- docs/scss/components/Tables/cells/FieldCell.scss
- docs/scss/components/Tables/cells/index.scss
- docs/scss/components/Tables/index.scss
- docs/src/components/tables/cells/DescriptionCell.js
- docs/src/data/objects/linode.yaml
- docs/src/data/objects/linode_config.yaml
- docs/src/data/objects/stackscript.yaml
> add see also link to docs endpoint description

- components/scss/components/navigation/Header.scss
- components/scss/variables.scss
> Tone down MiniHeader

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/api/networking.js
- src/components/notifications/EventTypes.js
- src/linodes/linode/networking/layouts/SummaryPage.js
> Add support for deleting IP address

- src/api/apiActionReducerGenerator.js
> Async fetch all

- components/scss/components/forms/Input.scss
- components/scss/components/forms/form.scss
- components/scss/mixins.scss
- src/api/util.js
- src/linodes/layouts/IndexPage.js
> Add linode filtering

- components/lists/controls/MassEditControl.js
- src/api/util.js
- src/domains/layouts/IndexPage.js
- src/linodes/layouts/IndexPage.js
- src/nodebalancers/layouts/IndexPage.js
> Add nodebalancer filtering

- src/domains/layouts/IndexPage.js
> Add domains filtering

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/linodes/linode/layouts/RebuildPage.js
- test/linodes/linode/layouts/RebuildPage.spec.js
> Add rebuild confirm check

- docs/src/libraries/python/Python.js
A patch went in that the linter didn't like.
> Fixes for linter

- src/components/Header.js
- src/components/SessionMenu.js
Move the Support link out of the user menu and into the top-level nav.
> Add support to header

- src/nodebalancers/nodebalancer/components/ConfigForm.js
> Set min zero on relevant nb config fields

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/session.js
adds a response_type for changes in login, WIP until server changes happen
> add reponse_type to oauth flow for changes in login

- src/api/configs/stackscripts.js
- src/api/index.js
- src/api/reducer.js
- src/index.js
- src/stackscripts/index.js
- src/stackscripts/layouts/IndexPage.js
- test/data/index.js
- test/data/stackscripts.js
- test/stackscripts/layouts/IndexPage.spec.js
Closes #2249 
Closes #2254 
Closes #2267
> StackScript list and delete

- docs/src/data/python/stackscript.yaml
Similar to https://github.com/linode/manager/pull/2137
> Fix StackScript import

- src/nodebalancers/nodebalancer/components/ConfigForm.js
> Fix spelling mistakes on nodebalancer settings page

- src/api/backups.js
- src/api/linodes.js
- src/components/notifications/EventTypes.js
- src/linodes/linode/backups/components/BackupDetails.js
- src/linodes/linode/backups/components/BackupRestore.js
- src/linodes/linode/backups/components/TakeSnapshot.js
- src/linodes/linode/backups/components/index.js
- src/linodes/linode/backups/layouts/SummaryPage.js
- test/common.js
- test/linodes/components/CloneLinode.spec.js
- test/linodes/linode/backups/components/TakeSnapshot.spec.js
- test/linodes/linode/backups/layouts/SummaryPage.spec.js
- test/linodes/linode/layouts/RebuildPage.spec.js
- test/linodes/linode/networking/components/AddIP.spec.js
- test/linodes/linode/networking/components/EditRDNS.spec.js
- test/linodes/linode/networking/layouts/IPSharingPage.spec.js
- test/linodes/linode/networking/layouts/IPTransferPage.spec.js
- test/profile/components/TwoFactor.spec.js
- test/profile/components/TwoFactorModal.spec.js
> Add label option when taking snapshot

- src/linodes/stackscripts/components/Settings.js
Thanks @displague 
Closes #2377
> Prevent public stackscript UI from appearing to be privatizable

- docs/README.md
- docs/package.json
> Add rebuild-components script and docs to docs

- docs/prebuild.js
> Better debugging on yaml read failure

- src/domains/components/EditSOARecord.js
- src/domains/layouts/IndexPage.js
- test/domains/layouts/IndexPage.spec.js
> Show dns zone status

- CHANGELOG.md
- components/forms/Select.js
- npm-shrinkwrap.json
- package.json
- src/index.js
- src/layouts/Layout.js
> setState when using default Select value

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/networking.yaml
- docs/src/data/endpoints/support.yaml
- docs/src/data/objects/supportticketreply.yaml
label, group, and with_backup are pending/waiting for backend changes -- the rest is gtg
> document linode clone endpoint and options

- docs/src/data/endpoints/account.yaml
- docs/src/data/endpoints/domains.yaml
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/networking.yaml
- docs/src/data/endpoints/nodebalancers.yaml
- docs/src/data/endpoints/profile.yaml
- docs/src/data/endpoints/support.yaml
- docs/src/data/endpoints/volumes.yaml
- docs/src/getting_started/guides/curl/CreateLinode.js
- docs/src/getting_started/guides/curl/TestingWithCurl.js
- docs/src/getting_started/intros/Access.js
- src/fetch.js
- test/fetch.spec.js
waiting on login and API support
> Change to bearer token

- src/api/configs/volumes.js
- src/api/index.js
- src/api/reducer.js
- src/components/notifications/EventTypes.js
- src/linodes/volumes/index.js
- src/linodes/volumes/layouts/IndexPage.js
- test/data/index.js
- test/data/volumes.js
- test/linodes/volumes/layouts/IndexPage.spec.js
> Volume list

- src/profile/index.js
- src/profile/layouts/IndexPage.js
- src/profile/layouts/LishPage.js
- test/data/profile.js
- test/profile/layouts/LishPage.spec.js
> Hook up lish settings

- components/lists/controls/MassEditControl.js
- components/lists/controls/MassEditDropdown.js
Unchecks all selected items when not all are selected a la gmail.
> Add support for indeterminate checkbox state

- scss/support/components/TicketReply.scss
- src/support/components/TicketReply.js
> Add attachments to ticket

- src/profile/components/TwoFactorModal.js
> Add tfa autofocus attribute

- src/api/util.js
- src/domains/layouts/IndexPage.js
- src/linodes/stackscripts/layouts/IndexPage.js
- src/linodes/volumes/layouts/IndexPage.js
- src/profile/layouts/APITokensPage.js
- src/users/layouts/IndexPage.js
This allows you to search on any item in the underlying data. It also attaches the path of the keys to each value so you can hone in on a particular value.
For example:
* running -> shows you all linodes with "running" inside some value of the underlying object
* status=running -> shows you all linodes with a status running key value pair
* 168 -> shows you all linodes with 168 inside (for instance IPs)
* backups:enabled=false -> shows you all linodes who do not have backups enabled
And so forth.
> Add advanced filter

- src/profile/components/CreatePersonalAccessToken.js
- test/profile/components/CreatePersonalAccessToken.spec.js
This also reverses the list so that All Access is last.
> PAT creation default to no access

- src/support/layouts/CreatePage.js
- test/support/layouts/CreatePage.spec.js
> Add support for volumes and other tickets

- scss/components/Backup.scss
- scss/components/backup.scss
- scss/components/index.scss
- src/linodes/linode/backups/components/BackupDetails.js
- src/linodes/linode/backups/layouts/IndexPage.js
- src/linodes/linode/backups/layouts/SummaryPage.js
> Fix up error formatting and when restore buttons are displayed

- src/api/util.js
- src/profile/layouts/APITokensPage.js
- src/users/layouts/IndexPage.js
Fix after I screwed up this rebase: https://github.com/linode/manager/pull/2408/files#diff-603cdd3c5b0b5e1002450b2c4e338129
> Add back advanced filtering

- src/linodes/linode/settings/advanced/components/AddDisk.js
> Don't crash when no distro is selected in AddDisk modal

- src/linodes/components/PlanStyle.js
- src/linodes/layouts/IndexPage.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/IndexPage.js
- test/linodes/linode/layouts/DashboardPage.spec.js
> Adjust plans

- components/scss/components/modals/Modal.scss
- scss/layout/Layout.scss
- src/components/notifications/NotificationListItem.js
- src/domains/components/EditSOARecord.js
- src/domains/layouts/IndexPage.js
- test/data/domains.js
- test/domains/components/EditSOARecord.spec.js
Closes #2221 
This is the biggest domain you can have (for testing):
bigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbigbi.com
> Fix css length regressions

- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/prebuild.js
- docs/src/data/endpoints/account.yaml
- docs/src/data/endpoints/domains.yaml
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/nodebalancers.yaml
- docs/src/data/endpoints/profile.yaml
- docs/src/data/endpoints/support.yaml
- docs/src/data/objects/linode_config.yaml
- docs/src/data/objects/stackscript.yaml
- docs/src/data/objects/usergrants.yaml
Closes #2458, closes #2460, closes #2461, closes #2455, closes #2456, closes #2457
> Fix unlinked docs and fail if unlinked

- components/scss/components/navigation/VerticalNav.scss
- docs/CHANGELOG.md
- docs/npm-shrinkwrap.json
- docs/package.json
- docs/scss/docs/Layout.scss
- docs/scss/layout.scss
- docs/src/App.js
- docs/src/components/Endpoint.js
> Remember previous scrolls

- src/api/linodes.js
- src/linodes/components/CloneLinode.js
- test/linodes/components/CloneLinode.spec.js
> Clone with label and backup

- src/linodes/linode/components/RescueMode.js
- test/linodes/linode/components/RescueMode.spec.js
> set an initial disk array for rescue configs

- components/formats/Code.js
- components/scss/components/formats/Code.scss
- docs/scss/components/MethodResponse.scss
- docs/scss/components/MethodResponseExample.scss
- docs/src/components/Method.js
- docs/src/components/MethodParams.js
- docs/src/components/MethodRequest.js
- docs/src/components/MethodResponseExample.js
> Show more of example up front

- components/lists/ScrollingList.js
- components/modals/DeleteModalBody.js
- components/scss/components/modals/Modal.scss
- src/utilities.js
> Show number of dups when deleting

- docs/src/data/objects/event.yaml
> Remove user_id from account/events

- docs/src/data/objects/stackscript.yaml
> Removed customer_id from stackscript

- components/forms/Checkbox.js
- components/forms/Input.js
- components/forms/Radio.js
- docs/src/data/endpoints/linodes.yaml
- src/api/volumes.js
- src/components/notifications/EventTypes.js
- src/linodes/volumes/components/AddEditVolume.js
- src/linodes/volumes/components/AttachVolume.js
- src/linodes/volumes/components/ResizeVolume.js
- src/linodes/volumes/components/VolumesList.js
- src/linodes/volumes/components/index.js
- test/linodes/volumes/components/AttachVolume.spec.js
- test/linodes/volumes/components/ResizeVolume.spec.js
> Add resize

- components/scss/components/forms/Select.scss
- components/scss/components/forms/form.scss
- components/scss/components/navigation/Menu.scss
- scss/components/GraphGroup.scss
- scss/components/LineGraph.scss
- scss/components/index.scss
- src/components/graphs/GraphGroup.js
- src/components/graphs/LineGraph.js
- src/components/notifications/EventTypes.js
- src/linodes/linode/layouts/DashboardPage.js
- src/nodebalancers/nodebalancer/layouts/DashboardPage.js
- src/utilities.js
> Moar graphs

- components/scss/components/tooltips/Tooltip.scss
> Give tooltip a max width

- src/domains/components/EditCNAMERecord.js
> CNAME hostname placeholder should not be a FQDN

- src/constants.js
- src/linodes/linode/components/RescueMode.js
- src/linodes/linode/settings/advanced/components/CreateOrEditConfig.js
- test/data/linodes.js
- test/linodes/linode/settings/advanced/layouts/EditConfigPage.spec.js
> handle xen disk labels correctly (xvda-xvdh)

- src/api/networking.js
> Fix IP setRDNS creating duplicate

- docs/src/data/endpoints/linodes.yaml
with_backup will be replaced by backups_enabled
> Changed with_backup to backups_enabled

- components/scss/components/forms/Select.scss
- components/scss/components/forms/form.scss
> Fix multi select

- components/dropdowns/Dropdown.js
- src/linodes/components/StatusDropdown.js
- src/linodes/volumes/components/VolumesList.js
- test/components/Dropdown.spec.js
Represents the dropdown button in the dropdown list.
> ![image](https://user-images.githubusercontent.com/317653/31196776-f01fc79c-a91c-11e7-951f-7308d90c4f5b.png)
---
> ![image](https://user-images.githubusercontent.com/317653/31196796-027ace6e-a91d-11e7-9a2c-be8be5fc13b1.png)
---
> ![image](https://user-images.githubusercontent.com/317653/31196823-13e9a828-a91d-11e7-9c1b-4a19978088e2.png)
> Dropdown has all children

- src/api/volumes.js
- src/linodes/volumes/components/AddEditVolume.js
- src/linodes/volumes/components/AttachVolume.js
- test/linodes/volumes/components/AddEditVolume.spec.js
- test/linodes/volumes/components/AttachVolume.spec.js
> select config for volume

- src/linodes/linode/components/UpgradeToKVM.js
> Xen to kvm update

- docs/prebuild.js
- docs/src/data/endpoints/images.yaml
- docs/src/data/objects/image.yaml
Includes:
* GET /images
* GET /images/$id
* PUT /images/$id
* DELETE /images/$id
> Added initial set of Image endpoint Docs

- docs/src/data/endpoints/account.yaml
- docs/src/data/objects/notification.yaml
This documents the account/notifications endpoint and the Notification
object
> Adds Documentation for Notifications

- docs/CHANGELOG.md
- docs/package.json
- docs/prebuild.js
- docs/src/data/endpoints/account.yaml
- docs/src/data/endpoints/images.yaml
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/endpoints/longview.yaml
- docs/src/data/endpoints/support.yaml
- docs/src/data/objects/account.yaml
- docs/src/data/objects/image.yaml
- docs/src/data/objects/longviewclient.yaml
- docs/src/data/objects/longviewsubscription.yaml
- docs/src/data/objects/notification.yaml
- docs/src/data/python/type.yaml
- docs/src/getting_started/changelogs/Changelogs.js
- docs/src/getting_started/guides/python/Introduction.js
- docs/src/getting_started/intros/Access.js
Docs 0.14.0 (2017-10-23)
======
Changed
------
- /account/payments "amount" is now a string
Added
------
- /user/:id/grants GET includes "longview" and "images"
- /profile/grants GET includes "longview" and "images"
- /images GET
- /images/:id GET, PUT, and DELETE
- /linode/instances/:id/disks/:id/imagize POST
- /linode/instances POST now accepts "image"
- /linode/instances/:id/rebuild POST now accepts "image"
- /account/notifications GET
- /account/settings GET and PUT now includes "longview_subscription"
- /longview/subscriptions GET
- /longview/subscriptions/:id GET
- /longview/clients GET and POST
- /longview/clients/:id GET, PUT, and DELETE
> Docs release 0.14.0

- docs/src/data/objects/linode.yaml
- docs/src/data/objects/linodenetworking.yaml
> capitalize slaac->SLAAC

- docs/src/data/objects/backup.yaml
ensure datetimes are datetimes
> update backup docs

- docs/src/data/objects/disk.yaml
* Add Disk ID description
* Add missing .
* Add descriptions for datetimes
> update disk docs

- docs/src/data/objects/distribution.yaml
* Add ID description
* Switch updated to Datetime, add description
> distribution docs updates

- docs/src/data/objects/domain.yaml
> fix domains docs

- docs/src/data/objects/kernel.yaml
> kernel doc updates

- docs/src/data/objects/type.yaml
* Properly nest backups.price
* ID description
> types docs updates

- docs/src/data/endpoints/account.yaml
- docs/src/data/objects/profile.yaml
Cleanup profile docs
Add missing `restricted` key
> profile docs updates

- docs/src/data/endpoints/linodes.yaml
- docs/src/data/objects/device.yaml
Cleanup linode endpoint docs by adding missing example parameters and documenting rules about resizing disks
> Linode post/put/delete docs cleanup

- src/api/ad-hoc/linodes.js
- src/api/generic/images.js
- src/api/generic/index.js
- src/components/notifications/EventTypes.js
- src/components/tables/cells/TimeCell.js
- src/linodes/images/components/AddImage.js
- src/linodes/images/components/EditImage.js
- src/linodes/images/components/index.js
- src/linodes/images/index.js
- src/linodes/images/layouts/IndexPage.js
- src/linodes/linode/settings/advanced/components/Disks.js
- test/data/images.js
- test/data/index.js
- test/linodes/images/components/AddImage.spec.js
- test/linodes/images/components/EditImage.spec.js
> image list and add

- src/api/generic/images.js
- src/api/generic/index.js
- src/components/notifications/EventTypes.js
- src/linodes/components/LinodeFromImage.js
- src/linodes/components/index.js
- src/linodes/layouts/IndexPage.js
- test/data/images.js
- test/data/index.js
- test/linodes/components/LinodeFromImage.spec.js
> create linode from image

- components/modals/FormModalBody.js
- src/components/notifications/EventTypes.js
- src/components/notifications/NotificationListItem.js
- src/linodes/components/LinodeFromImage.js
- src/linodes/images/components/AddImage.js
- src/linodes/images/layouts/IndexPage.js
> Add image bug fix

- src/profile/components/CreateOrEditApplication.js
- src/profile/layouts/MyAPIClientsPage.js
- test/profile/components/CreateOrEditApplication.spec.js
Reverts linode/manager#2735
This was intended for the development branch ..
> Revert "Add public option for oauth clients"

- src/billing/components/BillingHistoryList.js
- src/billing/layouts/DashboardPage.js
- src/billing/layouts/HistoryPage.js
- src/billing/layouts/InvoicePage.js
- src/billing/layouts/PaymentPage.js
- src/components/DisplayCurrency.js
- src/linodes/components/BackupsCheckbox.js
- src/linodes/components/PlanStyle.js
- src/linodes/linode/backups/layouts/IndexPage.js
- test/billing/layouts/InvoicePage.spec.js
- test/components/DisplayCurrency.spec.js
Closes #2705 
Created a component for use across project for displaying currencies. Can be easily extended to support additional currencies if that comes up later.
With the collective 👍  I can apply across the project.
> #2705 Add DisplayCurrency component and tests.

- src/constants.js
- src/linodes/components/DistributionSelect.js
- src/linodes/linode/settings/advanced/components/AddDisk.js
- src/linodes/linode/settings/advanced/components/Disks.js
- src/linodes/linode/settings/advanced/layouts/AdvancedPage.js
- src/linodes/linode/settings/advanced/layouts/IndexPage.js
- test/linodes/linode/settings/advanced/components/AddDisk.spec.js
Adds Images to the distributions dropdown.
Closes #2680
> Disk from image

- docs/src/App.js
Fixes: #2733 
Fix scrolling when you click on sidebar nav element
> Fix scrolling when you click on sidebar nav element

- src/domains/components/EditCAARecord.js
- src/domains/components/MasterZone.js
- test/data/domains.js
- test/domains/components/EditCAARecord.spec.js
- Follows conventions set by other records (specifically SRV).
Closes #2626 
---
> 
---
> Add CAA record CRUD.

- src/linodes/linode/backups/components/ScheduleForm.js
- test/linodes/linode/backups/components/ScheduleForm.spec.js
- Adjust select times to users selected timezone.
- Added some help text to clarify use.
> Adjust backup schedules to user timeszones.

- docs/prebuild.js
- docs/scss/components/Tables/cells/FieldCell.scss
- docs/src/components/tables/cells/ParamFieldCell.js
- docs/src/data/endpoints/linodes.yaml
- docs/src/data/objects/linode.yaml
* add deprecate key to docs renderer
* add deprecated key to yaml
> Add deprecated key to docs renderer

- src/linodes/components/ConfigSelectModalBody.js
- src/linodes/components/StatusDropdown.js
> stuck in finnix fix

- CONTRIBUTING.md
- package.json
- yarn.lock
- Runs testing and linting on commit to prevent me from pushing bad code to repo.
> Add pre-commit package and config.

- .gitignore
- .vscode/settings.json
- No longer forcing other VSCode users to do things my way.
> Ignore vscode ettings.

- docs/src/data/objects/image.yaml
> put vendor in images

- src/linodes/linode/backups/components/ScheduleForm.js
re: https://github.com/moment/moment/issues/854 for incrementing and not setting time increases.
> #2786 Correct adding duration via moment

- src/linodes/linode/backups/components/ScheduleForm.js
Had to open a new branch and PR, somehow my original got tainted.
Closes #2804
> #2804  Add reasonable defaults, disable submission.

- src/constants.js
> show linode rebuilding transition

- scss/components/Tables/Cells/Cells.scss
- src/profile/layouts/MyAPIClientsPage.js
- src/profile/layouts/MyAPIClientsPage.spec.js
Add's "access" column to display public or private key.
Closes #2737
> #2737 Add public/private access column.

- src/api/ad-hoc/networking.js
Fixes #2750 
The fetch response to RDNS change for an IP address was not being used to update the Redux store. In addition, the shape of response for ipv4 is an Object and for ipv6 is an array of objects. This PR handles both cases.
Closed #1736 and #1353
> Normalize shape of response to RDNS change, use fetch response

- CONTRIBUTING.md
- Update testing information 
- Removed absurd test coverage expectation.
- Spelled most things correctly.
Closes #2782
> Update testing in CONTRIBUTING

- src/linodes/linode/settings/advanced/components/Disks.js
- src/linodes/linode/settings/advanced/components/__snapshots__/Disks.spec.js.snap
Depends on this PR to linode-react-components 
https://github.com/linode/linode-react-components/pull/6
> Disable the AddDisk button when a Linode has no free space

- src/linodes/components/StatusDropdown.js
A bug was revealed by the recent change to check for exactly 1 config on boot and reboot.
The code branch which intended to show a modal asking which config the user would like to use for a boot or reboot was never shown.
This change makes a synchronous call to grab a linode's configs before booting or rebooting.
> Allow config select on boot and reboot

- src/api/ad-hoc/networking.js
- src/linodes/linode/networking/components/EditRDNS.js
- src/linodes/linode/networking/layouts/SummaryPage.js
This allows the user to take IPv6 RDNS actions and addresses #2853
> Make Linode ID an explicit param for setRDNS

- CHANGELOG.md
- package.json
- src/api/internal.js
- Fix permissions page for usernames with numbers (#2884)
> Release 0.17.1

- scss/components/Notifications.scss
- scss/components/SessionMenu.scss
- src/components/session/index.js
- src/linodes/index.js
- src/linodes/linode/index.js
Clean up what I broke, namely the navigation/session menus, correct the DOM structure on LinodeIndex which created was incorrectly nested causing a UI bug, and update the way LinodeIndex redirects on a 404.
> MAN2-2852 Cleanup

- CHANGELOG.md
- package.json
- src/components/__snapshots__/TimeDisplay.spec.js.snap
- src/linodes/volumes/components/AddEditVolume.js
[fixed]
* Allow config selection when adding a Volume to a Linode
> Release 0.17.3

- src/index.js
- src/linodes/linode/layouts/Glish.js
- src/linodes/linode/layouts/Weblish.js
Add Glish/Weblish routes/components back into the software.
> [WIP] Add Glish/Weblish Routes

- src/linodes/linode/components/UpgradeToKVM.js
> MAN2-1327 Update a word.

- src/middleware/modalCloser.js
- src/nodebalancers/index.js
- src/nodebalancers/nodebalancer/configs/index.js
- src/store.js
- Add middleware to close open modals on route change.
- Correct NodeBalancerConfigAdd routing and layout.
> Modal close fix

- src/api/ad-hoc/linodes.js
- src/components/notifications/EventTypes.js
- src/images/components/AddImage.js
This fixes a breaking change for API v50.0
> Use POST /images instead of the /imagize endpoint

- src/LinodeAPI/index.js
Correct usage of Axios for sending a DELETE request.
> Use Axios constructor.

- src/components/Banners.js
- src/constants.js
- src/data/banners.js
Also, use matchProps to get Linode Label.
This fixes a breaking change for API v50.0
> Update notification types for Banners

- src/api/ad-hoc/nodebalancers.js
- src/nodebalancers/nodebalancer/components/ConfigForm.js
- src/nodebalancers/nodebalancer/configs/layouts/NodeBalancerConfigEdit.spec.js
Update consistent with API 50 release changes.
> MAN2-2935 Use nodebalancer().config.put() for SSL.

- src/linodes/linode/layouts/Glish.js
- src/linodes/linode/layouts/Weblish.js
Fix broken lish token request.
> Update Glish token request

- package.json
Quality of life improvement. Run the faster linter first then the longer tests.
> Lint first for fast failing.

- src/LinodeAPI/index.js
- src/store.js
Found the Redux Dev Tools enabled in production.
> Hide Redux in production.

- src/linodes/linode/components/GlishControls.js
- src/linodes/linode/layouts/DashboardPage.js
- src/linodes/linode/layouts/Glish.js
- src/linodes/linode/layouts/__snapshots__/DashboardPage.spec.js.snap
> Add link to Linode in Glish message that opens in parent window

- jsconfig.json
#MakeVSCodeSlightlyFasterAgain
> Update jsconfig.json excludes

- src/api/internal.js
- src/api/internal.spec.js
Increase documentation and testing coverage of internal.js utility functions.
I did some refactoring after the tests were added to make use of native reduce vs Lodash reduce and forEach.
> Test and document internal.js

- src/api/external.js
- src/api/external.spec.js
This adds tests and additional documentation for the genThunk* family of functions in external.js
> Add tests for genThunk functions

- src/index.js
This allows us to use Sentry in dev environments.
> Enable sentry in dev

- src/linodes/linode/networking/layouts/SummaryPage.js
Range has been removed from IPv6 object. Address will remain address/prefixi
> Remove ipv6 pool conditional.

- src/api/actionCreatorGenerator.js
- src/api/internal.js
- src/api/internal.spec.js
- src/typedefs.js
Add testing and typedefs to ReducerGenerator.
> MAN2-2955 again

- src/analytics.ts
- src/constants.ts
- src/index.tsx
- src/utilities/routing/isPathOneOf.spec.ts
- src/utilities/routing/isPathOneOf.ts
Add Google Analytics for pageview.
- I'd like to get a development GA property to test this. _M3-16_.
- Do we need event based analytics?  _M3-17_
> M3-7 Add Google Analytics for pageviews.

- src/index.tsx
Forgot to check myself and I wrecked myself.
> Check for GA before calling during route change.

- src/components/DocComponent.tsx
- src/components/WithDocumentation.tsx
Apparently you can't use the key property provided to components. Bummer. Also, off by one!!
> Correct 'last doc' logic.

- src/components/AddNewMenu/AddNewMenuItem.spec.tsx
- src/components/AddNewMenu/AddNewMenuItem.tsx
- src/components/AddNewMenu/index.tsx
- src/components/TopMenu.tsx
Initial pass at the AddNewMenu. Split into two components for styling sake.
> M2-28 Initial pass at AddNewMenu.

- src/App.tsx
- src/components/Footer.tsx
> M3-9 Add Footer.

- .travis.yml
Adding build step to TravisCI. Certain items can pass tests and linting, but not the build compilation.
> Add build to travisci.

- src/api/ad-hoc/linodes.js
- src/profile/components/CreatePersonalAccessToken.js
> Fix stats and nonexpiring tokens

- src/components/LinodeStatusIndicator.tsx
- src/features/linodes/ListLinodes/LinodeCard.tsx
- src/features/linodes/ListLinodes/LinodeRow.tsx
- src/features/linodes/ListLinodes/LinodesListView.tsx
- src/types/Linode.ts
- Add Linode status indicator which respects transition states
> Linode Status Indicator

- src/App.tsx
- src/components/ActionMenu.tsx
- src/components/AddNewMenu/AddNewMenuItem.tsx
- src/components/AddNewMenu/index.tsx
- src/components/CircleProgress.tsx
- src/components/DocComponent.tsx
- src/components/PrimaryNav.tsx
- src/components/UserMenu.tsx
- src/features/linodes/ListLinodes/IPAddress.tsx
- src/features/linodes/ListLinodes/LinodeCard.tsx
- src/features/linodes/ListLinodes/LinodeRow.tsx
- src/features/linodes/ListLinodes/ListLinodesEmptyState.tsx
- src/features/linodes/ListLinodes/OverflowIPs.tsx
- src/features/linodes/ListLinodes/RegionIndicator.tsx
- src/features/linodes/ListLinodes/ToggleBox.tsx
- src/theme.ts
- src/types/index.ts
- Allow custom theme variables
> Allow custom theme variables

- src/utilities/request.ts
- Adds interceptor to redirect to login on 401
> Redirect to login on 401

- .storybook/config.js
- .storybook/webpack.config.js
- package.json
- src/components/CircleProgress.stories.tsx
- src/components/ErrorState.stories.tsx
- yarn.lock
- Added React Storybook. `yarn storybook` and visit http://localhost:6006.
- Added stories for ErrorState and CircleProgress.
> M3-84 React Storybook

- src/components/ShowMore.test.tsx
- src/components/ShowMore.tsx
- src/features/linodes/ListLinodes/IPAddress.test.tsx
- src/features/linodes/ListLinodes/IPAddress.tsx
- src/theme.ts
This PR contains the code from https://github.com/linode/manager/pull/3022 (which can be closed) and my styling commits.
Please double check I modified the state properly to load the active class to the chip when the drop down is active.
> Add ShowMore component.

- src/exceptionReporting.ts
- Added top level unhandled promise rejection reporting via RavenJS.
> Report unhandled Promise rejections to raven.

- src/features/linodes/LinodesLanding/LinodeRow.tsx
- src/features/linodes/LinodesLanding/LinodesListView.tsx
- src/features/linodes/LinodesLanding/presentation.ts
Done, hopefully removed all references
> m3-87 remove volumes from linodes list view

- package.json
- src/App.tsx
- yarn.lock
- Upgraded Material-UI to latest.
> Install latest Material-UI

- src/components/button.stories.tsx
- src/utilities/storybookDecorators.tsx
Adds a theme decorator which cuts down on repeated imports in storybook stories
> Add theme decorator for storybook

- src/components/TabbedPanel/TabbedPanel.stories.tsx
- src/components/TabbedPanel/TabbedPanel.tsx
- src/components/TabbedPanel/index.ts
- src/theme.ts
> M3-39 Add TabbedPanel abstraction.

- src/App.tsx
- src/components/ActionMenu/ActionMenu.test.tsx
- src/components/AddNewMenu/AddNewMenuItem.tsx
- src/components/AuthenticationWrapper/AuthenticationWrapper.test.tsx
- src/components/ErrorState/ErrorState.tsx
- src/components/PrimaryNav/PrimaryNav.tsx
- src/components/ShowMore/ShowMore.tsx
- src/components/Tag.tsx
- src/components/Tag/Tag.tsx
- src/components/TopMenu.tsx
- src/components/WithDocumentation/DocComponent.tsx
- src/components/WithDocumentation/WithDocumentation.test.tsx
- src/components/WithDocumentation/WithDocumentation.tsx
- src/events.test.ts
- src/events.ts
- src/features/linodes/LinodesLanding/IPAddress.tsx
- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/features/linodes/LinodesLanding/LinodeRow.tsx
- src/features/linodes/LinodesLanding/OverflowIPs.tsx
- src/types/index.ts
- src/utilities/storybookDecorators.tsx
- tslint.json
- No trailing whitespace tslint rule
> No trailing whitespace tslint rule

- src/components/WithDocumentation/WithDocumentation.tsx
- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/features/linodes/LinodesLanding/LinodeRow.tsx
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
> List and Grid view toggle enhancements

- src/App.tsx
- src/components/TextField.stories.tsx
- src/components/TextField.tsx
- src/theme.ts
Add text fields
- Normal
- Active
- Error
- Affirmative
- Disabled
> M3-42 Text Fields

- src/components/ExpandPanel/ExpandPanel.stories.tsx
- src/components/ExpandPanel/ExpandPanel.tsx
- Adds ExpandPanel component with transition animation
> M3-41 ExpandPanel component

- src/components/ActionMenu/ActionMenu.tsx
- src/components/AddNewMenu/AddNewMenu.tsx
- src/components/ShowMore/ShowMore.tsx
- src/index.css
- src/theme.ts
Styled component and make sure to avoid regressions with other components - which allowed me to remove necessary styles from index.css
Also reorganized all theme.ts overrides alphabetically for future ease of development
> m3-73 popover menus

- src/features/linodes/LinodesLanding/LinodesLanding.tsx
- Fixed an issue where navigating away from and back to loading component would result in an indefinite loading component.
> Add conditional for unfinished events.

- src/App.tsx
- src/components/AddNewMenu/AddNewMenu.tsx
- src/features/linodes/LinodesCreate/LinodesCreate.tsx
- src/features/linodes/LinodesCreate/index.ts
- src/features/linodes/index.tsx
- tslint.json
- Add route change for Linode in AddNewMenu.
- Add close-on-click functionality to AddNewMenu items.
- Add LinodesCreate feature stub.
- Add LinodesRoutes component.
-  `/linodes` now points to newly created LinodesRoutes component.
- TSLint update; Change no-console-log to warning.
> M3-51 LinodesCreate feature start.

- src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/features/linodes/LinodesLanding/powerActions.ts
- Adds Reboot functionality to Linode card.
> M3-142 Add reboot method and click handler.

- package.json
- src/components/ExpandPanel/ExpandPanel.tsx
- src/components/ExpandPanel/index.tsx
- src/components/PrimaryNav/PrimaryNav.tsx
- Add expansion panel with sub-links for Account management
- Add expansion panel with sub-links for Support
> M3-83 Side Navigation sub-links

- package.json
- src/components/ExpandPanel/ExpandPanel.stories.tsx
- src/components/ExpandPanel/ExpandPanel.tsx
- src/components/SelectionCard/SelectionCard.stories.tsx
- src/components/SelectionCard/SelectionCard.tsx
- src/index.tsx
- src/utilities/storybookDecorators.tsx
- yarn.lock
Adds "Selection Card" component that supports:
- Icons
- Images
- Font Glyphs
- Checked and Unchecked state
> M3-40 Selection Card

- src/components/WithDocumentation/WithDocumentation.tsx
Small PR to fix doc title regression
> m3-144-doc-title-color

- src/components/SelectionCard/SelectionCard.stories.tsx
- src/components/SelectionCard/SelectionCard.tsx
@alioso can you have a look at the styles on this. There's some weird interactions when the Tooltip is used. See the Storybook interactive demo for context.
> Add disable and tooltip.

- src/components/SelectionCard/SelectionCard.tsx
> Fix disabled selection card tooltip

- src/components/UserMenu/UserMenu.tsx
a small PR to match to user drop menu styles with the 03 comps
> User drop down menu styles

- src/components/CheckBox/CheckBox.stories.tsx
- src/components/CheckBox/CheckBox.tsx
Add checkbox component with the following states:
Checked/Unchecked X Disabled
Checked/Unchecked/Hover X Enabled
Checked/Unchecked/Hover X Warning
Checked/Unchecked/Hover X Error
> M3-48 Checkbox Component

- config/webpack.config.prod.js
- Added a temporary fix to the Webpack production build to address an error relevant to  ExtractTextPlugin.
> Add temporary prod build change.

- src/App.tsx
- src/components/ActionMenu/ActionMenu.tsx
- src/components/CheckBox/CheckBox.tsx
- src/components/CheckBox/index.ts
- src/components/ExpandPanel/ExpandPanel.tsx
- src/components/PasswordInput/HideShowText.tsx
- src/components/PasswordInput/PasswordInput.tsx
- src/components/PrimaryNav/PrimaryNav.tsx
- src/components/SelectionCard/SelectionCard.tsx
- src/components/TabbedPanel/TabbedPanel.tsx
- src/features/linodes/LinodesCreate/AddonsPanel.tsx
- src/features/linodes/LinodesCreate/LabelAndTagsPanel.tsx
- src/features/linodes/LinodesCreate/LinodesCreate.tsx
- src/features/linodes/LinodesCreate/PasswordPanel.tsx
- src/features/linodes/LinodesCreate/SelectImagePanel.tsx
- src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- src/features/linodes/LinodesCreate/SelectRegionPanel.tsx
- src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
- src/theme.ts
- src/types/Region.ts
You might want to use production services, otherwise you'll only see one region coming back from the API.
> M3-59 M3-54 M3-60 M3-61 M3-62 Putting er all together.

- package.json
- src/App.test.tsx
- src/App.tsx
- src/components/UserMenu/UserMenu.test.tsx
- src/components/UserMenu/UserMenu.tsx
- src/types/Profile.ts
- yarn.lock
- Populate username and gravatar using /profile
- Don't show the Gravatar logo if the user doesn't have a Gravatar
- Add types for Linode.Profile
> M3-172 Populate username and gravatar

- src/assets/icons/plus-square.svg
- src/components/IconTextLink/IconTextLink.stories.tsx
- src/components/IconTextLink/IconTextLink.tsx
- Adds combined icon and text link with disabled and activated states
> M3-118 Icon and Text Link

- src/components/PaginationControls/PageButton.tsx
- src/components/PaginationControls/PaginationControls.tsx
- src/components/PaginationFooter/PaginationFooter.tsx
- src/components/PaginationFooter/index.ts
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
- src/theme.ts
> M3-81 Add Pagination to LinodesLanding.

- src/features/linodes/LinodesCreate/AddonsPanel.tsx
- src/features/linodes/LinodesCreate/CheckoutBar.tsx
- src/features/linodes/LinodesCreate/LinodesCreate.tsx
- Display backup pricing based on Linode type selection
> M3-177 Display of dynamic backup pricing

- src/features/linodes/LinodesLanding/LinodesLanding.tsx
- Allow Linode refresh request on Event failed status
> M3-188 Update Linode on Event failed status

- src/index.tsx
- src/session.ts
Add a null route to the application for sake of injecting OAuth tokens
> Add a null route to the application for sake of injecting OAuth tokens

- src/features/linodes/LinodesLanding/IPAddress.tsx
Added a simple Tooptip with a timeout. I left the focus on in order to see what item was copied last.
> Ip copy tooltip notification

- src/components/EventListItem/EventListItem.stories.tsx
- src/components/EventListItem/EventListItem.tsx
- src/components/EventListItem/index.tsx
- src/theme.ts
- Adds component for Notification and Event menu list items with 4 states
> Add EventListItem component

- src/App.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/APITokens/index.tsx
- src/features/profile/OAuthClients/OAuthClients.tsx
- src/features/profile/OAuthClients/index.tsx
- src/features/profile/Profile.tsx
- src/features/profile/index.tsx
- Add My Profile component
- Add API Tokens and OAuth Clients component
- Add tabs and routes
- Connect tabs to browser history and React Router
> Add "My Profile" tabs and components, connect to router

- package.json
- src/components/EditableText/EditableText.stories.tsx
- src/components/EditableText/EditableText.tsx
- src/components/EditableText/index.tsx
- yarn.lock
- Add EditableText component
- EditableText is an uncontrolled text input with 2 states which calls an onEdit callback upon edit
> M3-119 Editable Text

- src/App.tsx
- src/features/profile/Profile.tsx
- Update logic to use React Routers matchPath for selection.
- Use Route not TempRoute.
- Add keys to routes to prevent index warning.
> Update Profile section tab logic.

- src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx
- src/components/ConfirmationDialog/ConfirmationDialog.tsx
- src/components/ConfirmationDialog/index.ts
- Creates a simple confirm/decline dialog.
> add: Create a simple confirm/decline dialog.

- .storybook/webpack.config.js
- src/components/Drawer/Drawer.tsx
- src/components/ErrorState/ErrorState.tsx
- src/components/ExpansionPanel/ExpansionPanel.tsx
- src/components/Footer.tsx
- src/components/Grid/Grid.tsx
- src/components/Grid/index.ts
- src/components/PaginationFooter/PaginationFooter.tsx
- src/components/PasswordInput/PasswordInput.tsx
- src/components/PasswordInput/StrengthIndicator.tsx
- src/components/PrimaryNav/PrimaryNav.tsx
- src/components/SelectionCard/SelectionCard.tsx
- src/components/WithDocumentation/WithDocumentation.tsx
- src/features/linodes/LinodesCreate/AddonsPanel.tsx
- src/features/linodes/LinodesCreate/LinodesCreate.tsx
- src/features/linodes/LinodesCreate/SelectImagePanel.tsx
- src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
- src/features/linodes/LinodesCreate/SelectRegionPanel.tsx
- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/features/linodes/LinodesLanding/LinodeRow.tsx
- src/features/linodes/LinodesLanding/LinodesGridView.tsx
- src/features/linodes/LinodesLanding/LinodesListView.tsx
- src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
- Adds Grid wrapper in response to MUI changes.
> add: Add Grid wrapper in response to MUI changes.

- src/components/CheckBox/CheckBox.tsx
- src/components/Radio/Radio.tsx
- src/theme.ts
Implementing status variables for checkboxes and radios as well as fixing the error base color. This should not affect the styling of the elements, just implement the variables for future theme switching handling
> Status color variables

- src/components/Select/Select.stories.tsx
- src/components/Select/Select.tsx
- src/theme.ts
- Create Select component wrapper.
- Extends MaterialUI SelectProps adding a property of "success" of type boolean.
> M3-114 Select component.

- src/components/SideMenu.tsx
Small PR to fix main nav regression
> Remove main navigation drop shadow (regression from drawer)

- src/components/Select/Select.stories.tsx
- src/components/Select/index.ts
- src/events.ts
- src/features/linodes/LinodesLanding/powerActions.ts
- src/features/profile/APITokens/APITokenDrawer.tsx
- src/features/profile/APITokens/APITokenMenu.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/APITokens/utils.ts
- src/features/profile/OAuthClients/OAuthClients.tsx
- src/time.ts
- src/types/Profile.ts
- src/utilities/getAPIErrorFor.ts
- List API Tokens
- Separate List for App Tokens and Personal Access Tokens
- English duration formatting for creating date and expiry
> M3-231 View, Create, Edit, Revoke for API tokens

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/index.ts
- src/features/profile/OAuthClients/OAuthClients.tsx
This is the first step of this implementation: basic scroll overflow of the tables. 
I did not not include the Linode list view as it has its own responsive handling
> Responsive Tables

- CONTRIBUTING.md
- TESTING.md
- package.json
* Added: unit test documentation
* Clarify one aspect creating the `.env` file
> Testing.md - Unit Test Documentation

- src/components/Select/Select.tsx
- src/theme.ts
making the drop down more responsive and consistent
> Select Dropdown Adjustments

- src/assets/icons/minus-square.svg
- src/assets/icons/plus-square.svg
- src/components/IconTextLink/IconTextLink.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/OAuthClients/OAuthClients.tsx
Component transition and placement on the api and oauth pages
> Icon text link styling and placement

- src/components/Drawer/Drawer.tsx
- src/components/Table/Table.tsx
- src/features/profile/APITokens/APITokenDrawer.tsx
- src/features/profile/APITokens/APITokens.tsx
Added responsive tables to api and token tables and adjust drawer dimmensions to add consistency to their content
> Apply responsive tables

- src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
- src/features/linodes/events.ts
- Factor out linode events subscription filtering logic
- Add linode events subscription to linode details page
> Factor out linode events subscription filtering logic

- src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/LinodesLanding/IPAddress.test.tsx
- src/features/linodes/LinodesLanding/IPAddress.tsx
- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/theme.ts
- src/types/Volumes.ts
* Add Linode summary panel
* Request a Linode's Image, Types, and Volumes on the Linode Detail Page
> M3-237 Add Summary Panel

- src/features/TopMenu/UserNotificationMenu/UserNotificationMenu.tsx
min with and max height for menu
> Notification DropDown Menu feedback fixes

- src/components/Drawer/Drawer.tsx
- src/components/SelectionCard/SelectionCard.tsx
- src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
UI comps show usage of selection cards, not select menus.
> Switch radio to selection cards.

- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/features/linodes/LinodesLanding/LinodeRow.tsx
- src/features/linodes/LinodesLanding/LinodesListView.tsx
- Removes display of tags/group in LinodeRow and LinodeCard.
> Remove references to group/tag.

- src/features/linodes/LinodesLanding/LinodeCard.tsx
Added some custom breakpoints to prevent possible overflow
> M3-185 Grid view containment

- src/features/profile/APITokens/APITokens.tsx
Added some width to the table cells to achieve some display consistency
> Profile table cells consistency

- src/features/linodes/LinodesCreate/AddonsPanel.tsx
couple fixes for spacing and better markup
> Linode create addon panel

- src/features/linodes/LinodesLanding/LinodeCard.tsx
- src/theme.ts
Add light bg shade to card header
> M3-299 card header bg

- src/App.tsx
- src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- src/features/TopMenu/TopMenu.tsx
- src/features/TopMenu/UserMenu/UserMenu.tsx
- src/features/TopMenu/UserNotificationMenu/UserNotificationButton.tsx
Pertains to top menu items at smallest breakpoint
> Mobile adjustments

- src/components/TabbedPanel/TabbedPanel.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/theme.ts
Wanted to consolidate the tabs spacing and also made adjustments to the API token tables typography
> Tabs & Tables - spacing and typography

- src/features/TopMenu/UserMenu/UserMenu.tsx
Applied the same focus fix we have for the action menu to the user menu
> User menu drop-down focus fix

- src/features/TopMenu/UserNotificationMenu/UserNotificationMenu.tsx
I don't think we want to truncate titles, best is to just add a width to the drop down and let titles wrap accordingly
> M3-357 Notification titles 

- package.json
- src/App.tsx
- src/components/EditableText/EditableText.tsx
- src/components/ErrorState/ErrorState.tsx
- src/components/ExpansionPanel/ExpansionPanel.tsx
- src/components/PromiseLoader/PromiseLoader.tsx
- src/features/TopMenu/UserMenu/UserMenu.tsx
- src/features/TopMenu/UserNotificationMenu/UserNotificationMenu.tsx
- src/features/Weblish/Weblish.tsx
- src/features/linodes/LinodesCreate/LinodesCreate.tsx
- src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/OAuthClients/OAuthClients.tsx
- src/theme.ts
- src/utilities/charts.ts
- yarn.lock
- Add stats charts to Linode Detail page
- Add React-Chart.js-2
- Poll stats endpoint for live update of charts
- Configure charts to match required styles
- Write time, and b/sec axis formatters
> M3-351 Add charts to Linode Detail

- src/components/WithDocumentation/WithDocumentation.tsx
- src/features/Footer/Footer.tsx
- src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
- src/features/TopMenu/TopMenu.tsx
footer needed a fix and I discovered minor responsive spacing issues within the frame
> M3-356 spacing fixes in footer, appbar and withDoc

- src/features/profile/APITokens/APITokens.tsx
fixes: Converts API supplied UTC times to browser local time.
> M3-341 Future tokens fix.

- src/features/Weblish/Weblish.tsx
seems like I could achieve *some* consistency across most browsers with these settings.
> Weblish xterm window size and font stack

- package.json
- src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/events.ts
- src/services/linode.ts
- src/types/Linode.ts
- yarn.lock
- Add Linode Backups Management
> M3-92 Linode Backups Management

- src/components/PrimaryNav/PrimaryNav.tsx
> Re-center linode logo above main nav

- src/App.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/profile/Profile.tsx
Potentially address Firefox/Win11 "to much recursion" issue.
> Use Redirect component directly.

- src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
- src/features/linodes/LinodesLanding/IPAddress.tsx
A small regression fix related to the ip address display
> Linode summary spacing fixes 

- src/features/profile/APITokens/APITokenDrawer.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/OAuthClients/OAuthClientActionMenu.tsx
- src/features/profile/OAuthClients/OAuthFormDrawer.tsx
- src/theme.ts
I had the wrong styles for the cancel buttons (were previously black) and applied the proper styles as well as targeting a few missing ones on the profile drawers and dialogs
> Cancel buttons

- src/assets/icons/toggleOff.svg
- src/assets/icons/toggleOn.svg
- src/components/Toggle/Toggle.stories.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/index.ts
- src/components/Toggle/toggle.css
- src/theme.ts
Switch toggle component and the story. 
Note: we need the class associated with the label (and the small css file along with it as the handling of this label is quite different from the other formControlLabels we've had previously, and we can't access the parent label styling from the switch component itself.
> Toggle component

- src/theme.ts
fixing small regression from tabs container
> Fix missing bottom border on tabs container

- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/services/linodes.ts
Fix what I broke. Mistyped and therefore implemented incorrectly.
> Correct type and usage of linodes getType.

- src/components/Select/Select.tsx
Use prop helpText vs stock text. Good eye @patthiel.
> M3-456 Select helpText fix

- src/features/profile/APITokens/APITokens.test.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/types/Profile.ts
- src/utilities/isPast.test.ts
- src/utilities/isPast.ts
- src/utilities/testHelpers.test.ts
- src/utilities/testHelpers.ts
- Filter tokens who's expiry is past now.
- Added some test helpers, who have tests.
- Added tests to verify filtered tokens.
Note: There were missing dangling commas, and my formatter made some changes. For APITokens, look at the top of the render function for the actual changes.
> M3-340 Filter tokens who's expiry is past now.

- src/components/ProductNotification/ProductNotification.tsx
- src/components/ProductNotification/index.ts
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/linodes/LinodesLanding/LinodesLanding.tsx
This was more of an implementation than it was any form of component, since we had them already. The pattern was pretty basic, subscribe to the notifications$ stream, filter as appropriate for the location, then display the notifications.
> M3-274 Product Level Notifications

- src/features/ToastNotifications/ToastNotifications.tsx
Set toast auto hide duration to 6000ms. Additionally prevented "click away" dismissal, consistent with drawers and dialogs.
> M3-448 Toast hide duration.

- src/components/Select/Select.tsx
- src/features/TopMenu/UserMenu/UserMenu.tsx
- src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
- src/features/linodes/LinodesDetail/LinodeRebuild/LinodeRebuild.tsx
- src/theme.ts
As per the accessibility issues we have defined, we want to consolidate the drop down menu items to match the action menu ones. This PR applies these styles to the select, power control and user (top menu bar)drop down menu items.
> M3 457 select menu style fixes

- src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.tsx
- src/features/linodes/LinodesLanding/LinodeRow.tsx
I had omitted to place the arguments in an array for a couple of them, which produced a console error
> Fix theme create transition functions

- src/index.css
Reverts linode/manager#3285
Reverting PR, since Rob and Andrew were assigned to review
> Revert "Styling for webkit scrollbars"

- e2e/pageobjects/create.js
- e2e/pageobjects/linode-detail-resize.page.js
- e2e/pageobjects/linode-detail.page.js
- e2e/pageobjects/page.js
- e2e/specs/linodes/detail/resize.spec.js
- src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
* Added page object for linode - detail - resize
* Added spec for resizing a linode
* Added `data-qa` attributes to LinodeResize.tsx
```bash
yarn start
yarn selenium # execute in a new shell
yarn e2e --file e2e/specs/linodes/detail/resize.spec.js
```
> M3-404 - Linode Detail - Resize Tests

- src/App.tsx
- src/components/HelpIcon/HelpIcon.stories.tsx
- src/components/Select/Select.stories.tsx
- src/components/SelectionCard/SelectionCard.stories.tsx
- src/components/TabbedPanel/TabbedPanel.stories.tsx
- src/features/Volumes/VolumesLanding.tsx
- src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
- src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx
- src/features/linodes/LinodesLanding/LinodesListView.tsx
- src/features/linodes/LinodesLanding/ToggleBox.tsx
We had a few wrong table imports within the app, importing from material-ui while we have our abstracted component. Updated all remaining wrong instances in this PR
> Fix wrong table imports

- src/components/EditableText/EditableText.tsx
- src/darkTheme.ts
- src/theme.ts
Changed the editable text default state color to match the updated comp
> Editable text default color

- src/features/Volumes/VolumeAttachmentDrawer.tsx
- src/features/Volumes/VolumeDrawer.tsx
- Select Linode config for volume during volume creation
- Select Linode config for volume during volume attachment
> M3-478 Select Linode Config for Volumes

- src/index.css
This reverts commit c9fecb59837577bc920321aafc756173abaffb88.
remaking this pull request because Rob and Andrew were assigned to the original PR
> Revert "Revert "Styling for webkit scrollbars""

- src/features/Volumes/VolumesLanding.tsx
- src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
- src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigsPanel.tsx
- src/features/linodes/LinodesDetail/LinodeSummary/SummaryPanel.tsx
- src/features/linodes/LinodesDetail/LinodeVolumes/LinodeVolumes.tsx
- src/features/linodes/LinodesDetail/LinodesDetail.tsx
- src/features/profile/APITokens/APITokens.tsx
- src/features/profile/OAuthClients/OAuthClients.tsx
Previous PR left a few of these out. This should not change anything visually, just making sure we are using our abstracted component. Styles fixes in this PR are related to regression when switching to our Grid component
> Remaining wrong imports for Grid component

- src/features/profile/APITokens/APITokens.test.tsx
- src/features/profile/APITokens/APITokens.tsx
Switching order of app tokens and personal access token
> M3-480 switch order of personal access and app tokens

- src/features/profile/APITokens/APITokenDrawer.tsx
Small css PR to maker the personal token table cells equal width
/profile/tokens > open drawer (add a personal access token)
> Personal token table cells width
