packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable_CMR.tsx

When no outbound rules are present for a firewall, all outbound traffic is allowed. The empty state of the Outbound Rules table now contains text stating this.

M3-4782: Clearer explanation of implications of not having any Outbound FW rules

---

packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx

Merging inline and normal actions led to the Reboot action breaking, since (for good reasons) we don't request a Linode's configs until someone opens the menu for that Linode.
I'd like to remove this whole configs check from the action menu. I've never been a fan, and there's a useful error if you try to reboot a Linode without configs from the API. Conversation for another day.

Hotfix: Make sure inline action isn't disabled

---

packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx

We had a display for Linodes in regions where block storage was not available, but it was lost in CMR. This change hides the Volumes table from /storage if the Linode's region doesn't support block storage (e.g. Atlanta). I also tried something more similar to what we used to have but I thought it was too jarring:
Feedback welcome. nb Atlanta is the only region without Block Storage, and it's deprecated.

Hide Volumes table for Linodes in regions w/o Block Storage

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/DNSResolvers.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx

Instead of hiding the "DNS Resolvers" column, I swapped the order with the "Network Transfer History" graph and moved that to its own row starting at 960px
Since the content in the "DNS Resolvers" column also varies, I added a horizontal scroll to prevent it from overlapping with the "Network Transfer History" graph
---
**Screenshots**
<details>
<summary>Before</summary>
1280px:
< 960px:
< 600px:
<br>
</details>
<details>
<summary>After</summary>
1280px:
< 960px:
< 600px:
<br>
</details>

M3-4747: Improve responsiveness of Linode Network Summary

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx

Update the URL appropriately when opening, closing, and navigating to Linode Resize, Rebuild, Rescue, & Migrate modals.
The following scenarios should work:
1. Navigating to, for example, `/linodes/:id/resize` should still work as it did before.
2. From any tab in Linode details, clicking Resize/Rebuild/Rescue/Migrate should add said action to the URL as a query param (i.e. if you click Resize, "?resize=true" should be appended)
3. Navigating directly to a Linode details tab with a modal indicated to be open (e.g., `/linodes/:id/storage?rebuild=true`) should take you to the appropriate tab with the appropriate modal open.
4. Closing the modal should return you to the appropriate tab and update the URL accordingly.

M3-4763: Update URL appropriately when opening, closing, and navigating to Resize, Rebuild, Rescue, & Migrate modals

---

packages/api-v4/src/firewalls/firewalls.schema.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Sort ports more intuitively in the Firewall rules table. See comments for examples, or check the ticket (where I took the examples from).
I'll rebase to fix the diff once #7315  is merged; if you look at the last 3 commits in the meantime you'll see the real changes here.

M3-4780 Change: Sort Firewall rule ports

---

packages/api-v4/src/kubernetes/kubernetes.ts
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/RecycleAllPoolNodesDialog.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/RecycleAllClusterNodesDialog.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
packages/manager/src/hooks/useKubernetesClusters.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/kubernetesVersion.ts

Add modal for bumping LKE version. Only one version bump is supported per PUT (1.16 -> 1.17 but not 1.16 -> 1.18). Copy and some UX details are still under discussion.
- To test, create an LKE cluster with a version lower than the current (1.18). On the cluster detail page there should be a modal prompting you to upgrade.
- I also updated the mocks so if you turn those on the flow should work.
- Does the transition between 2 modals bother anyone else? Looking for a way around it
Still to come: Banner on LKE landing page and "upgrade" badge in individual cluster rows.

M3-4787 Add: modal for upgrading LKE minor version

---

packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx

This fixes a bug where the "Log Out", "My Settings", and "Referrals" buttons are apparently missing from the User Menu. 
This happens on Chrome (and other browsers) when there is an increased font size. To reproduce, change your font size to "Large" at `chrome://settings/appearance`.
**To fix this**, I broke up the links into two actual Grid columns rather than relying on max-height + CSS wrapping.

M3-4771 Fix wrapping in UserMenu causing disappearing Log Out button

---

packages/manager/src/App.tsx
packages/manager/src/MainContent.tsx
packages/manager/src/index.css

~~Since our navigation is pretty lengthy, I created a hidden "Skip to Main Content" link that is only visible when the user starts to tab through the website. This way users navigating with the keyboard can bypass tabbing through the sidebar and the top nav when they reload the page~~
We already have one so I added some styles that would show up on focus instead
Here's a link for more info: [https://webaim.org/techniques/skipnav/](https://webaim.org/techniques/skipnav/)
After clicking on the skip link, it should take you to the first element in the main content which is usually the breadcrumb which doesn't have a focus state but you should be able to traverse to the documentation and the create button pretty quickly

POC: Make visual indicator for "Skip to Main Content" link

---

packages/manager/src/features/Support/ExpandableTicketPanel.test.tsx
packages/manager/src/features/Support/ExpandableTicketPanel.tsx
packages/manager/src/features/Support/Hively.tsx
packages/manager/src/features/Support/ticketUtils.ts

Hide "Linode Expert" text for Linode and Linode Trust & Safety accounts. Also added Trust & Safety to the list of names to not show Hively (the rating system icons).
Test account 4 has a closed ticket with a reply from T&S.

M3-4795 Change: don't show "Linode Expert" for Linode accounts

---

packages/manager/src/components/StackScript/StackScript.test.tsx
packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/factories/index.ts
packages/manager/src/factories/stackscripts.ts

We weren't requesting images from StackScript detail view,
which meant that if you navigated directly there the "Compatible Images"
section would be blank.
There was some defaulting "No compatible Images found" text meant to be
displayed in that situation, but that wasn't working either.
- Converted StackScript.tsx to a function component
- Used useImages and useReduxLoad to get the Images data
- Fixed the empty state
- Updated and refactored the tests that this broke
I considered using React-Query, but images are a harder case for
this since withImages is still used in some class components. Going
to punt that until later so we don't have 2 parallel data channels
for them.

M3-4879 Fix: "Compatible Images" field on StackScript detail

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx
packages/manager/src/mocks/serverHandlers.ts

This is what it looked like before:
[http://localhost:3000/linodes/0](http://localhost:3000/linodes/0) has a mock migration banner for ease of testing

M3-4800: Fix scheduled migration banner font color on dark mode

---

packages/manager/src/assets/icons/docs.svg
packages/manager/src/components/CMR_DocumentationButton/DocumentationButton.tsx

Set the Docs icon to 18px and the text to 14px
Before:
After:

M3-4845: Reduce size of Docs text link and icon

---

packages/manager/src/components/Table/Table_CMR.tsx
packages/manager/src/components/TableSortCell/TableSortCell_CMR.tsx
packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs_CMR.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts
packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx
packages/manager/src/themeFactory.ts
packages/manager/src/themes.ts

The new grey color has been applied to table headers and the "Download CSV" link on the Linode Landing page
This PR also includes a fix make sure all table headers have a blue background and white text on hover which was previously missing on the Linode Landing page and a few other tables

M3-4833: Change table header font color

---

packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx

This was a hooks dependency issue. The dialog state was being
reset when the dialog opened, as intended, but since only [open]
was included in the deps array, stale values of the device map
were used. In addition, when the dialog was opened without /disks
having been previously requested, the completed request wouldn't trigger
the effect.
Used the usePrevious hook to run the reset logic whenever `open`
changes _and_ the calculated deviceMap is different from the previous
value. This involves a deep object comparison on every render while
the dialog is open, but it seems ok in practice.

M3-4880 Fix: Disk selection when opening Rebuild from /linodes

---

packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx

Fixing the flags that appear shorter than the rest and adding a light gray border to flags with a lot of whitespace (ie. Japan and Singapore)

M3-4857: Update flag art

---

packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/features/StackScripts/Partials/StackScriptTableHead_CMR.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx

Removing the type from `querySearch` fixes the search redirecting to /accounts
**Update:**
- If the username matches the one in the profile, the username link from the StackScripts Detail page redirects to `/accounts`
- If not, it'll redirect to `/community/?query=username[insert username]` instead
- Change the table headers to the new gray color
- Made the link underline color match the text instead of blue

M3-4854: Fix StackScripts search

---

packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx
packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
packages/manager/src/features/TopMenu/TopMenu.tsx

M3-4836: Vertically center the hamburger menu in the top nav
M3-4860: Remove plus icon from "Add a Node" link, change "Delete" button type and swap places with the "Save" button

M3-4836 & M3-4860: Vertically center hamburger menu and clean up NodeBalancers buttons

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleActionMenu.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts

Add "Clone" to the Firewall rule action menu; directly clones a rule and adds it to the queued changes.
Holding off on the open-the-drawer piece, still not sure how to handle that part but this works and we might as well get it in and get some feedback on it.

M3 4781 firewall rule clone

---

packages/manager/src/assets/icons/minus-square.svg
packages/manager/src/assets/icons/plus-square.svg
packages/manager/src/components/Accordion/Accordion.tsx
packages/manager/src/components/AddNewLink/AddNewLink.tsx
packages/manager/src/features/Support/TicketDetailText.tsx
packages/manager/src/themeFactory.ts
packages/manager/src/themes.ts

Swap the previous expand/collapse icons used in the `Accordion` component and the same icons used in `/support/tickets`

M3-4835: New Accordion expand/collapse icons

---

packages/api-v4/src/firewalls/types.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/shared.ts

A change made in the API means that an empty address list is not accepted. Therefore if there are no ipv6 addresses for example, we don't include the ipv6 field at all.
I also made `ports` optional since that was changed in the API as well.
**To test,** use the dev API and check FW rule submission/editing thoroughly.

Firewalls: update submission of IP addresses

---

packages/manager/src/components/StackScript/StackScript.tsx

Fix double declaration of "profile" variable in StackScript.tsx

Fix double declaration of "profile" variable in StackScript.tsx

---

packages/manager/src/features/StackScripts/stackScriptUtils.ts

I did some research and can't figure out anything that would cause this user to be unable to contact LaunchDarkly from any browser or device. It might have been our old targeting rules, which were a bit scattershot. But those are gone now, and in any case this PR will make it so that all currently-available apps are available regardless of what Launch Darkly returns.
To test, block all requests to LaunchDarkly. You should see the same set of Marketplace apps as when the request goes through normally.

M3-4804 Change: Add all existing apps to baseApps

---

packages/manager/src/components/Prompt/Prompt.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx

Move the "Save Changes" button for Firewall rules to somewhere where it's easier to see. Also displayed it at all times, disabled until there are changes to save or discard. The idea is to make it clearer to users that they need to make and then save changes.
Edit: based on Matthew's feedback, also fixed a bug where clicking the sort headers with unsaved changes triggered the "Are you sure?" confirmation modal.

POC: Move save changes button to bottom of rules table

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Sorting by this field isn't very useful.

Make FW Rule "Description" field non-sortable

---

packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx

Change "Edit Rule" to "Add Changes" in the FW Rule Drawer, since this button doesn't actually save/edit the changes right away.
Also fixed the vertical centering of the "X" button on the beta banner.

Update FW rule editing button label

---

packages/manager/src/components/Button/Button.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeyCreationDrawer.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodePowerControl/LinodePowerControl.test.tsx

The button variant, `superCompact`, wasn't being used so I adjusted the styling a bit and applied it to the links on the Firewalls Detail page

M3-4893: Make use of variant to reduce padding around secondary button types

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx

Designs aren't final and everything is stubbed. I want to have a skeleton for these elements asap so we can work in parallel (and also so there's a link in the UI to the /create-transfer page).

M3-4895 Add: Entity transfer controls

---

packages/manager/src/features/Backups/BackupDrawer.tsx
packages/manager/src/features/Backups/BackupsCTA.tsx
packages/manager/src/features/Backups/BackupsTable.tsx
packages/manager/src/store/backupDrawer/index.ts

Move Auto Enroll, the action panel, and the price above the list of linodes; default Auto Enroll toggle to enabled. Indent Backups CTA banner text.

M3-4907: Enable Backups drawer rearrangement & tweaks

---

packages/api-v4/src/entity-transfers/index.ts
packages/api-v4/src/entity-transfers/transfers.schema.ts
packages/api-v4/src/entity-transfers/transfers.ts
packages/api-v4/src/entity-transfers/types.ts
packages/manager/src/factories/entityTransfers.ts
packages/manager/src/factories/index.ts
packages/manager/src/mocks/serverHandlers.ts

New methods for the account transfer feature, based on a spec doc from the API. Also includes mocks. These methods may not be complete/final, but they should be enough for us to work with.

Add: Account transfer methods for JS client and mock service worker

---

packages/manager/src/components/TabLinkList/TabLinkList.tsx
packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx

Also includes a fix for scroll bars appearing below 1280px when the setting for scrollbars is set to always show even though there's no overflow (M3-4752, see ticket for more info)

M3-4886: Remove text underline on selected tab

---

packages/manager/src/components/Dialog/Dialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.test.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/transfers.ts

- Add an override for the styling in src/components/Dialog
- Fill in the Accept a Transfer dialog
- It'll work with any random token with the mocks.

M3-4898 Receive Transfer Confirmation

---

packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx

The function component in `LinodeVolumes.tsx` is better-named "LinodeVolumes" than "LinodeStorage," the latter of which refers to the component that contains `LinodeVolumes.tsx`.

Rename function component in LinodeVolumes.tsx

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx

The confirm transfer dialog was originally put on the Transfers landing page
but it turns out we don't need that state there. Moving the dialog and its state
management inside TransferControls makes it easier to memoize things and should
prevent some renders.

Change: Move token management to TransferControls

---

packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx

Fix: Make event progress bars always full-width

---

packages/manager/src/features/EntityTransfers/TransfersTable.tsx

Moved code comment to its own line to resolve the `validateDOMNesting(...)` console error re: whitespace appearing as a child of `<tr>`

Resolve validateDOMNesting(...) console error on Transfers landing

---

packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
packages/manager/src/features/EntityTransfers/TransfersTable.tsx
packages/manager/src/queries/entityTransfers.ts

Ensure that the Transfers Pending & Transfers Sent tables update appropriately after a transfer is canceled; this is done by refreshing the `entity-transfers` query.

Cancel Transfer modal follow-up

---

packages/manager/src/components/ErrorState/ErrorState.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.test.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx

It's possible to open the "receive transfer" with a transfer you or another user on your account created. You get an error if you submit the form, but it's a weird UX (including the display of -111354 minutes if you use an expired token). I think the best thing to do is show an error up front in these cases.

Prevent users from loading the receive transfer dialog for transfers on their own account

---

packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferCancelDialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
packages/manager/src/features/EntityTransfers/utilities.test.ts
packages/manager/src/features/EntityTransfers/utilities.ts
packages/manager/src/utilities/ga.ts

Most of the changes here are adjustments for the linter.
Add GA events for: Entity Transfer Create, Entity Transfer Receive, Entity Transfer Cancel.
To test, run the app with GA and check the console/network tab to verify events are going through. The Create and Receive events should have a label like "Linodes: 2".

Add analytics for Entity Transfers

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx

I think that because API dates don't include an explicit timezone, fromISO() was inferring an incorrect zone. To see this:
1. Create a new transfer
2. From another account, plug the token into the Receive Transfer box
3. Observe: the message says it will expire in >24 hours (I was seeing 28).

Explicitly read transfer.expiry in UTC

---

packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeAdvancedConfigurationsPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
packages/manager/src/utilities/createStringsFromDevices/createStringsFromDevices.ts

In the create/edit config dialog, update the block assignment
logic to match what we do with Rescue mode: only show the currently
selected/assigned devices plus one empty "None" slot. Add a button
to increment the number of devices (up to the limit).

M3-4940 Change: Block device assignment form

---

packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
packages/manager/src/features/linodes/LinodeSelect/LinodeSelect.tsx

Instead of adding plumbing to work with the /Volumes/LinodeSelect component that's only really used here, I used src/features/linodes/LinodeSelect instead and adjusted things to make it work out.

M3-4943 Change: Selecting a Linode auto-selects the region when creating a Volume

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx

In the create transfer success modal the time was labeled UTC but was 5 hours too far ahead. Should use parseAPIDate here instead of messing with `.toUTC()` which appears to shift from the browser's timezone to UTC.

Don't convert time to UTC twice

---

packages/api-v4/src/firewalls/firewalls.schema.ts
packages/api-v4/src/firewalls/types.ts
packages/manager/src/__data__/firewalls.ts
packages/manager/src/factories/firewalls.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
packages/manager/src/features/Firewalls/shared.test.ts
packages/manager/src/features/Firewalls/shared.ts

Includes the updated types and factories for the updated Firewall rule policy switches. These types will break things against any environment except devenv, but you can check them against the spec docs. Reach out if you're feeling suicidal and would like a link to the PR to pull if you want to actually run the in-review backend code.
All UI changes to work with these new types will come in a future PR.
Most of the diff is linter/prettier. api-v4/src/firewalls has most of the actual changes. Most of our rule presets have also been adjusted, we can adjust or remove the defaults when the UI is complete.

Update types and factories to reflect new Firewall rule policy types

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/mocks/serverHandlers.ts

Recent changes to how we display past due balances lead to confusion
for some customers. Specifically, a balance due was being hidden
during the first 3 calendar days of the month. This is a problem because:
- Some customers have a custom grace period much longer than 3 days
- Customers with old balances were seeing them disappear
Solution (for now!):
- No longer hide the balance due during the first 3 days of the month
This is a temporary fix, the balance will still be displayed in red
and as "Past Due." Customers with longstanding balances were seeing
this disappear at the beginning of the month.
- Use the notification past_due instead of hiding it and faking a similar one.
For now, we'll still hide this for the first three days of the month as a
stopgap.
- Use the natural severity …

Fix: Account balance display

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/EntityTransfersLanding.tsx
packages/manager/src/queries/entityTransfers.ts

When receiving a transfer, the table is not updated immediately
after submitting the confirmation form. In addition, the X-Filtering
for the tables is incorrect.
~There seem to be some API problems related to filtering that caused
us to not notice this, and this PR won't actually work as written.
It should work, though, when the API is fixed.~
The API fix has been merged to development, you should be able to test this PR using dev services.

Fix: Received Transfers table update

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.test.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts

This PR allows saving of FW rules that have been reordered. 
I went back and forth with how to represent these modifications in our data structure. The challenge is that:
- Each rule is represented as list of "revisions"!
- These lists of revisions are themselves stored in an array. The order of the array corresponds to the order of rules.
- So, there's no good way to indicate that the order has been modified without pushing a new revision to each rule stack.
~I opted to change the reducer state to~:
```ts
export interface RuleEditorState {
revisionLists: ExtendedFirewallRule[][]; // <-- existing reducer state
hasModifiedOrder: boolean;
}
```
~When the order is modified, **no new revisions are pushed to the rule stacks.** Instead, `revisionLists` is reordered and we set `hasModifiedOrder` …

Allow saving reordered FW rules

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx

You should be able to test this using dev services. There are some edge cases to work out in a future PR (specifically, we're defaulting outbound_policy to ACCEPT for new firewalls, but then if someone adds an outbound rule set to ACCEPT we might want to auto-toggle outbound_policy to DROP.

Add: Policy toggles to Firewall rule tables

---

packages/manager/src/features/linodes/LinodeSelect/LinodeSelect.tsx

Confusing situation where I started passing `{...rest}` to the Select inside of LinodeSelect, which in the NodeBalancers config IP select meant that `noOptionsMessage` was being passed down. This is a real prop but it's supposed to be a function, whereas in LinodeSelect the prop is a string that gets converted to a function. The ...rest (string) version of the prop was overriding the functionified version, causing a 💥 .
Create a NodeBalancer, and in the form open the IP select for a backend node.

Don't pass noOptionsMessage through LinodeSelect -> Select

---

packages/manager/src/queries/entityTransfers.ts

As discussed in the demo, the Transfers tables should now be sorted in descending order by the Created date/time.

M3-4977: Created, descending order for Transfers tables

---

packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx

This came up in demo today. Have more than 1 page of Linodes, go to page 2+, search for a Linode label that matches something you know is on page 1. Search will come up empty now, on this branch should contain the thing.

Fix search/pagination bug in LinodeTransferTable

---

packages/manager/src/features/Events/Event.helpers.ts

We can add some of these back when we've worked out the details with the API.

Remove usernames from all entity transfer events

---

packages/manager/src/features/EntityTransfers/EntityTransfersCreate/EntityTransfersCreate.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersCreate/TransferCheckoutBar.tsx

Step 1 of making the empty state of the make transfers page less weird, particularly when using Dark theme

Display some text on empty state in transfer checkout bar

---

packages/api-v4/src/stackscripts/types.ts
packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/features/StackScripts/Partials/StackScriptTableHead_CMR.tsx
packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanelContent.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx
packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
packages/manager/src/features/StackScripts/stackScriptUtils.ts
packages/manager/src/features/StackScripts/types.ts
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx

Since Community StackScripts are all public, this removes the "Status" column from the table on the Community StackScripts tab on the StackScripts landing page.
Areas elsewhere in the app where StackScripts appear (Create flow; Rebuild, etc. from Community StackScript; etc.) should be unaffected.

M3-4966: Remove "Status" column from Community StackScripts landing page

---

packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx

This PR adds copy icons (only visible on row hover) to the right of Transfer tokens in the Transfers tables.

M3-4976: Add CopyTooltip next to Transfer tokens in tables

---

packages/manager/src/components/AddNewLink/AddNewLink_CMR.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx

Fix this collision:
In doing so, I restored the passing down of classNames to the Button in AddNewLink_CMR. This reverses a change made here: https://github.com/linode/manager/pull/7270/files#diff-14508ed4b0441d547fadf5aa1f4c123ee37bb0abc5e2a5b97029bf80c6d73405L30.

Fix collision on FW -> Linodes

---

packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
packages/manager/src/hooks/useDismissibleNotifications.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/store/preferences/preferences.actions.ts

Opening this for review, still things to address in future PRs but I want to get feedback on the approach, which is:
- Store a set of `Record<hash, { created: string, key: hash }>` in user preferences
- Add a dismissible notification hook that exposes a few things:
- hasDismissedNotifications: given a list of Notification[] (or anything really) will check the hashes of those things against
the hashes in userPreferences and return `false` if _any_ item in the list doesn't have a matching hash.
- dismissNotification: given a list of Notification[] (or anything again), hashes and timestamps them, and updates user preferences. Because the full payload must be included when updating preferences, I use this opportunity to filter out any items with a `created` date older than 60 days (to prevent …

Add: dismissible notifications hook and logic

---

packages/manager/src/factories/linodeConfigInterfaceFactory.ts
packages/manager/src/factories/linodeConfigs.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx

Removes some old VLANs logic from the previous feature iteration; adds Config interfaces mocks; tweaks Network Interfaces column to show VLAN info if the interface is connected to a VLAN.
Please use the Mock Service Worker as the mocks are updated with the new data shape for Linode Config interfaces

M3-4938: Add network interface information to Configurations table

---

packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx

- Remove `VM Mode` and `Kernel` columns from Configurations table
- Rename `Label` column to `Config` and add kernel after the label
- Adjustments to column widths since there are fewer columns now

M3-4939: Configurations table revamp

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

Apparently calling `formik.resetForm()` does not, in fact, reset the form.
To test:
1. create a config
2. edit it and change some things
3. go to create a new config
4. the inputs from editing are still there

Pass default values to formik.resetForm

---

packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx

Aiming to prevent the wrapping of Linode Detail graph legends. This approach adds the `noWrap` prop to the `<TableCell />` the legend keys are rendered in, which seems to fix the issue while not causing any adverse effects where the `LineGraph` component is used elsewhere (Longview, etc.)
Before (this can currently be seen as you shrink to around the tablet view, let's say ~1080px width):
After:

M3-4971: Prevent wrapping of Linode Detail graph legends

---

packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.test.tsx
packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
packages/manager/src/hooks/useDismissibleNotifications.ts

Some changes to the banner pattern after previewing it to Chris:
- The toggles in /profile/preferences won't be implemented
- Clicking the link in the abuse ticket banner takes you to the tickets landing page
- Dismissing notifications via the drawer is handled separately from the banner, so if you dismiss the banner the badge count is unchanged, and if you close the drawer the badge count is cleared but the banner still appears. If the user clears it both ways, we're fine with having no visual indication that abuse tickets are still open.

Banner feedback

---

packages/manager/src/components/AbuseTicketBanner/AbuseTicketBanner.tsx
packages/manager/src/features/GlobalNotifications/EmailBounce.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/MigrationNotification.tsx

Assorted items from demo prep this morning:
- M3-5017: Show IDs (and entity labels as a POC) for abuse ticket notifications in the drawer
- M3-5018: Remove "right" from "right now" in the migration banner/confirmation modal
- M3-????: Make the abuse ticket banner a warning not an error

Demo feedback

---

packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx

Use a separate onCancel handler for the support ticket modal's Cancel
button. If the user closes the modal by clicking outside it, hitting the X button,
or pressing ESC (most of these can be done accidentally), close the drawer but
don't clear the values from local storage. In this way, if the user opens the drawer
their contents are still present.
If the user explicitly hits the "Cancel" button, though, take this opportunity to
clear the contents. Contents will also clear when a ticket has been created successfully.
We can also consider disabling backdrop and escape click handlers for the support dialog (or any dialog, if accidental closures become annoying), it would be easy to do.

M3-4948 Fix: Don't clear support modal contents from local storage on close

---

packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallBanner.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx

Newest installment in "all banners should be dismissible: a continuing saga." LKE version upgrade banners are now dismissible, using the hooks from useDismissibleBanners. Once dismissed, they won't reappear until a new version of LKE is available.

Change: Make LKE upgrade banner dismissible

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

- Make interfaceSelect filterable by region (since vlans are region-limited)
- Make sure when loading a config for editing in the drawer that there are
enough empty interfaces (purpose === 'none') added to it to match the UI pattern.

VLAN assorted fixes

---

packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx

This PR:
1. Picks up the Bare Metal flag from LD,
2. Adds an option in our Dev Tool for easily toggling the flag on and off locally,
3. Adds some temporary & basic code in `LinodeDetailHeader.tsx` to allow for easy confirmation of whether the flag is on or off (will be removed before merging)
To test easily, have your console open while visiting a Linode's Detail page. When the flag is on you should see a statement logged to the console. You can turn the flag on and off locally using the "Bare Metal" option under "Feature Flags" in our Dev Tool.

M3-4955: Bare Metal feature flag

---

packages/manager/src/features/Domains/DomainBanner.tsx
packages/manager/src/features/Domains/DomainsLanding.test.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationDrawer.tsx
packages/manager/src/hooks/useDismissibleNotifications.test.ts
packages/manager/src/hooks/useDismissibleNotifications.ts
packages/manager/src/store/preferences/preferences.actions.ts

Make the "Your domains aren't being served" banner disappear. This involved adding an optional `expiry` field to our mini-database and refactoring a bunch of stuff around it. The idea is:
- If a notification is dismissed normally, it is considered "stale" after 60 days. The next time a user dismisses anything, the stale stuff will be removed from the mini-database (this is clean-up to avoid bloat inside user preferences)
- If a notification is dismissed with a specified expiry date, it is not considered "dismissed" if the expiry has passed (so regardless of cleanup, an expired dismissal will reappear in the UI; in this case, the Domain banner will reappear after 30 days). Dismissals past their expiry are also considered "stale" and will be cleaned up as described above.
To test:
1. Have …

Change: Make Domain banner dismissible

---

packages/manager/src/features/OneClickApps/FakeSpec.ts

Current URL is 404'ing simply updating the URL for the Openlitespeed Linode doc. Can be merged at any time.

Marketplace update: Openlitespeed document link

---

packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/CreateTransferSuccessDialog.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/BucketBreadcrumb.tsx

Successful copying of text using tooltips throughout the app should show "Copied!" 
Specific locations in app include:
- IP Address in Linodes Landing table
- IP Addresses & Access in Linode Detail header
- Tokens in Service Transfers tables
- OBJ Bucket breadcrumb
- OBJ Bucket Details drawer
I believe all instances in the app should be consistent now, but if you are aware of others, please let me know.

M3-5007: Copy tooltip confirmation capitalization

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

Update the list of VLANs in local state when creating or editing a config.
To test:
- Create or edit a config, adding a new vlan as you do so (in eth1 or wherever)
- Open the config dialog again, and check the vlans dropdown; the VLAN you just created should be listed.
You still have to pin yourself to a host that supports VLANs then create a Linode in the host's region. test account 4 has this set up already.

Fix: Invalidate VLAN query when creating/editing a new config

---

packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx

When creating a Linode without an image, interfaces are not allowed.
Remove interfaces from the payload in this case to avoid an error
from the API. Disable the VLAN select and show helper text to explain
what needs to be done.

Allow creating a Linode without an image

---

packages/api-v4/src/regions/types.ts
packages/manager/src/constants.ts
packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
packages/manager/src/store/linodeType/linodeType.requests.ts
packages/manager/src/store/regions/regions.reducer.ts
packages/manager/src/utilities/isProdApi.ts

Add a tab for metal plans on the Linode create flow. This was the easy part. In order to make the flow work out, I also had to:
- Update our isProdAPI logic
- Disable VLANs if a metal type is selected
- Filter out metal types (so the tab doesn't appear) when creating from a private image or backup
See commit messages for more details. There's a new open ticket for adding metal to region.capabilities, but until that's done we can't do our usual filtering (using the GPU pattern).

M3-4956 bare metal create

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

- Don't include interfaces in the payload if no VLAN has been added.
- Fix handling of empty interface arrays now that normal Linodes don't have a public interface added by the API

VLANs fixes

---

packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
packages/manager/src/features/NotificationCenter/NotificationData/notificationUtils.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.test.ts
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/mocks/serverHandlers.ts

`migration_pending` notifications were previously being treated incorrectly as Linode maintenance. This PR fixes that.
I also took this opportunity to refactor `RenderNotification.tsx` and `useFormattedNotifications.tsx` so that notifications aren't intercepted at two levels, per https://github.com/linode/manager/pull/7390#discussion_r575285171. Intercepting logic has been consolidated in `useFormattedNotifications.tsx`.
Mocks can be turned on for testing; I made a couple of additions and changes to the mocked notifications

M3-5025: Properly handle migration_pending notifications & refactor rendering logic

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx

1. Set a config with VLANs in eth0 and eth1
2. Open the edit modal
3. Switch the eth0 to Public Internet
4. Submit the form (have devtools open)
5. The public interface shouldn't have a label in the payload

Clear label and ipam when switching from purpose.vlan to purpose.public

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Prevent the label column and the "Port Range" header from wrapping on top of dropping the protocol column sooner

M3-5016: Fix wrapping on Firewall Rule table

---

packages/api-v4/src/linodes/linodes.schema.ts
packages/api-v4/src/linodes/types.ts
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx

There was a bug where you could not successfully edit a configuration that had a VLAN interface. That was due to some incorrect validation. This PR revises the schema and allows `null` to be a valid type for `interface.label` in several places.
Please ensure that Linode configurations with and without VLANs can be edited and created as expected, and that Linodes can be created with or without VLANs.

For Release: Schema and typing revisions to allow interface.label to be null

---

packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptActionMenu.tsx

Move all actions for Account StackScripts inside of a dropdown ActionMenu regardless of viewport width

M3-5008: Hide inline actions for Account StackScripts

---

packages/api-v4/src/linodes/linodes.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx

Bare metal Linodes don't have disks that are managed through the API, so they have to use a new endpoint (linode/instances/:id/password) to reset their root password. In planning I recommended using a separate component for this to avoid a bunch of prop-driven stuff, but it turns out there's a lot of shared logic between the two flows that would be repeated and I couldn't think of a great way around it. So I kept the existing stuff in place and a) hid the disks dropdown then b) used a different method on submit.

M3-4961 Change: Separate password change flow for bare metal Linodes

---

packages/api-v4/src/linodes/linodes.schema.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

We heard from the VLAN team that the spec has changed a bit and public interfaces can be placed anywhere, not just on eth0. Since the API supports this we should too, though it's a rare use case.
We still don't have a validation schema attached to this dialog, and I've had trouble getting one to behave properly because of all the surgery we do on the interfaces payload. The schema is being run on submit, which I think is fine for now. We might want to open a separate ticket for including "live" validation on this form.
The API validates to make sure only a single public interface is included, regardless of position. I added validation for that too, though there's one discrepancy: the API returns this error without a field, so it appears as the general error at the top of the form. The …

Change: Public interface can appear in any slot

---

packages/api-v4/src/linodes/linodes.schema.ts

Seems that the Linode Create flow was broken on `develop` because the linodeInterfaceSchema test was failing when there were no interfaces. This change addresses that case 
Please confirm that Linode creation and editing and Linode Configuration creation and editing with and without VLANs function as intended

Fix for linodeInterfaceSchema test

---

packages/api-v4/src/linodes/linodes.schema.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

We received internal feedback that the "disappearing" interfaces were confusing. This makes it so that all interfaces are shown all the time. Validation runs before form submission, potentially resulting in this error message (word-smithing welcome):
I also updated the error message displayed when a user doesn't select or enter a VLAN name, as mentioned in https://github.com/linode/manager/pull/7570. I made the change here since there was already an `onValidate()` function in these changes.

M3-5056 Display all interfaces all the time

---

packages/api-v4/src/account/types.ts
packages/manager/src/MainContent.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts

This PR:
1. Picks up the Machine Images flag from LD,
2. Adds an option in our Dev Tool for easily toggling the flag on and off locally,
3. Adds some temporary & basic code in MainContent.tsx to allow for easy confirmation of whether the flag is on or off (will be removed before merging),
4. Adds `Machine Images` to the `AccountCapability` type as confirmed w/ API team
To test easily, have your console open while navigating through the app. When the flag is on you should see `Machine Images enabled.` logged to the console. You can turn the flag on and off locally using the "Machine Images" option under "Feature Flags" in our Dev Tool.

M3-5044: Machine Images feature flag

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
packages/manager/src/queries/vlans.ts

This fixes the following bug:
- Create a new Linode with a **new** VLAN attached.
- Navigate to the new Linode's Configs tab.
- Click "Edit" on the configuration.
- **Observe:** the VLAN is not present under the "Network Interfaces" section.

Ensure VLANs are fresh when opening the config drawer

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

M3-5049: In Config Dialog, save button should be labeled "Save Changes"
M3-5051: In the Config Dialog, the targets for toggles are too wide
M3-5052: In the Linode Create flow and Config Dialog, change VLAN "Label" field to "VLAN"
M3-5055: Remove (or disable) "None" as an option for eth0 network interface
One thing I haven't addressed in M3-5052 is that the error message for this field will still say e.g. "Label is required". I didn't want to make this change in the API wrapper / validation layer since this is Cloud-specific. Still thinking about how to best do this.

Assorted VLAN feedback

---

packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx

Ensure VLANs are fresh in the AttachVLAN component, to fix the following bug:
1. Create a Linode with a new VLAN
2. Create another Linode in the same DC
3. Observe: the new VLAN isn’t an option until you refresh the page

For release: ensure VLANs are fresh on Linode Create

---

packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraph.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/StatsPanel.tsx
packages/manager/src/themes.ts

Changes include:
- New title
- Gray background
- Remove "Toggle Graphs" label and icon (aka the caterpillar)
- Abbreviate legend labels and decrease font size
- Decrease graph height
Also updated the dark mode colors used in the graphs that previously blended in due to the transparency
The legend converts to a smaller view too quickly imo and the dark mode colors (border vs background color) aren't ideal but everything is legible so I'll have a separate PR address these two issues
Before:
After:

M3-4970: Linode Details graphs UI refinements

---

packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx

Instead of being visible all the time, the copy tooltips for NodeBalancer IP Addresses on the NodeBalancer landing page now appear on row hover.

M3-5038: NodeBalancer IP Addresses' copy tooltips appear on row hover

---

packages/api-v4/src/images/types.ts
packages/manager/src/components/ActionMenu_CMR/ActionMenu_CMR.tsx
packages/manager/src/components/EntityTable/APIPaginatedTable.tsx
packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
packages/manager/src/components/EntityTable/GroupedEntitiesByTag_CMR.tsx
packages/manager/src/components/EntityTable/ListEntities_CMR.tsx
packages/manager/src/components/EntityTable/types.ts
packages/manager/src/factories/images.ts
packages/manager/src/features/Images/ImageRow.tsx
packages/manager/src/features/Images/ImagesActionMenu.tsx
packages/manager/src/features/Images/ImagesLanding.tsx
packages/manager/src/mocks/serverHandlers.ts

- Using client-side sorting (for now, until the API work is complete), split
Images into 2 tables, one for manual (normal images) and one for automatic (created
by Linode when a Linode is deleted).
- Manual images no longer have an Expiry column, since they never expire
- Add a Status column, present only when the machineImages flag is active
- When image.status is pending, only one action is possible ("Cancel", which
just deletes the image)
- When image.status is not "available", disable "deploy" actions
I used our normal flagging logic to keep with convention and because it's in the ticket's AC, but I think I might feel a bit safer if we showed the Status column if the API returns a "status" field on the Image. It amounts to the same thing but we'd be tying the display to exactly what …

M3-5043 Change: ImagesLanding split into 2 tables

---

packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx

In v1.36.0 the default behavior when creating a new firewall was changed to no longer create default SSH and DNS rules. There was still a message on the drawer for creating a firewall that said it created these rules which it did not. The message has been removed from the drawer to reflect the default behavior. The documentation about the removal of this behavior can be found [here](https://github.com/linode/manager/releases/tag/linode-manager%401.36.0).

M3-5066: Removed the Typography containing incorrect helper text

---

packages/manager/src/features/EntityTransfers/EntityTransfersLanding/ConfirmTransferDialog.tsx

Removes the overriding font styles for the receive service transfer modal, using Typography's body font-style of 0.875rem(14px) instead.
Before:
After:

M3-4951 change: remove overriding font style for receive transfer modal

---

packages/manager/src/components/Tag/Tag_CMR.tsx
packages/manager/src/components/TagsPanel/TagsPanelRedesigned.tsx
packages/manager/src/features/Domains/DomainRecords.tsx
packages/manager/src/features/Domains/DomainRecordsWrapper.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesDialog.tsx

Currently it's only possible to delete a cluster from the action menu on the cluster list view. This adds a button to do the same thing from a cluster's detail view.
Also included in the ticket is restyling the tags section of the summary panel to match what's used in Linode detail view. This is tricky since it's the same component used in DomainRecordWrapper. I don't love what I did here, I tried to match the appearance and behavior of the TagCell component, which we can't use here because it requires a fixed width to do its fade-out magic. Discussed this with Matthew and decided on this approach for now.

M3-5040 Add: Delete cluster button/modal in LKE detail view

---

packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx

Removes copy related to disk size limits as that will no longer apply when Machine Images is accessible (and this view will only be seen under that circumstance); adjusts width so text fits nicely under Disk dropdown.

Demo feedback: Remove copy re: disk MB limits

---

packages/manager/src/features/Images/ImageRow.tsx
packages/manager/src/features/Images/ImagesActionMenu.tsx

- Always expose actions for pending Images
- Update "Cancel" to "Cancel Upload"
- Remove progress bar for pending images and have the corresponding size be "N/A"

Feedback: Machine Images table row updates

---

packages/manager/src/components/Button/Button.tsx
packages/manager/src/components/Button/button.stories.tsx
packages/manager/src/components/DocumentationButton/DocumentationButton.tsx
packages/manager/src/features/linodes/LinodeEntityDetail.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/themeFactory.ts
packages/manager/src/themes.ts

This PR includes several small UI updates:
- M3-4916: Tighten spacing between the radio button and Linode Plan name in the `SelectPlanPanel`
- **How to test:** Navigate to the Linode Create page and check the Linode Plan section
- M3-5011: Remove hover state color change for Docs link
- **How to test:** Navigate to any landing page and locate the Docs link on the upper right
- M3-5022: Add hover state for secondary buttons with outlines
- **How to test:** Run `yarn storybook` and navigate to the Button story (or check the NodeBalancers Configs tab)

Tighten Create flow radio buttons and update hover states for docs and secondary buttons

---

packages/manager/src/App.tsx

This PR changes the keyboard shortcut for toggling light and dark mode for the manager from `Ctrl+Shift+D` to `Ctrl+Shift+L`. This was done to avoid conflicts with existing keyboard shortcuts built into browsers.
Press `Ctrl+Shift+L` the manager should switch from light to dark mode or vice versa. It should also not pop up any dialogs from the browser.

light/dark mode shortcut changed to Ctrl+Shift+D

---

packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx
packages/manager/src/features/Billing/billingUtils.test.ts
packages/manager/src/features/Billing/billingUtils.ts

This PR corrects an incorrect argument type declaration for a function called `renderUnitPrice`. Previously the function took a type of `null | number` but in practice was being given a `null | string`. The function was extracted from the `InvoiceTable` react component and moved into the `billingUtils.ts` file. Tests were added to verify that strings that parse into valid numbers return a formatted string for the unit price. Tests were also added that if a string that cannot be parsed into a Number or null are passed tot he function then the function returns null. 
To run the unit tests associated with this PR run `yarn test ./packages/manager/src/features/Billing/billingUtils.test.ts` from the project root directory.

M3-4225: Fix Typing of renderUnitPrice and Test

---

packages/manager/src/features/Images/ImagesActionMenu.tsx

Per demo feedback, rename:
- "Restore to Existing Linode" to "Deploy to Existing Linode"
- "Deploy New Linode" to "Deploy to New Linode"

M3-5077: Rename Image deployment actions

---

packages/manager/src/features/StackScripts/StackScriptsDetail.tsx

Removes old `mapStateToProps` pattern in favor of using hooks
Tech story, doesn't seem like the values were actually being used anywhere yet.

M3-5067: remove mapStateToProps in favor of hooks in StackScriptsDetail

---

packages/api-v4/src/linodes/linodes.schema.ts
packages/validation/src/linodes.schema.ts

Update VLAN validation to match API
Create a VLAN containing capital letters in the label. This can be done from linodes/:id/configs or linodes/create. On develop, it won't get through our client validation (check the network tab to see that no request is being made).

Fix: VLAN label validation

---

packages/manager/src/components/ImageSelect/ImageSelect.tsx

Filters out images with the status of `creating` or `pending_upload` in the ImageSelect component.
1. Create a manual image for a Linode in `Images`
2. While the image status is creating or pending upload, go to `Linodes` and click on `Create Linode`
3. In the `Images` tab within Create Linode, click on the `Choose an image` dropdown
4. The image we just created should not display
5. Go back to image status and wait for the status to be `Ready`
6. Check the dropdown again and the new image should now display

M3-5086: Filter out creating and pending images from ImageSelect

---

packages/manager/src/events.ts
packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
packages/manager/src/store/events/event.helpers.test.ts
packages/manager/src/store/events/event.helpers.ts

Adjust our handling of the image_upload event.
In general, if an event has a percent_complete from 0-99 we consider it "in progress." This means that we show a progress bar for it in the notifications drawer, may display related entities differently throughout the app, and (most importantly) we don't throttle our polling interval if there are any in progress events still running. In practice this means we'll request events every 1.5 seconds, instead of ramping down to every 16 seconds.
The image_upload event, generated when you POST to image/uploads, is different, in that it can stay in percent_complete: 0 for up to 24 hours (until the user actually uploads an image to the provided URL). There may be some other long-running events we can consider that would fall into a similarly long …

Fix: image_upload events

---

packages/manager/src/features/Images/ImageUpload.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx

This PR adds a beta notice to the Upload Image tab, and updates the container padding on both image creation tabs:
Visit localhost:3000/images/create. View both tabs to check the container spacing. Look near the "Generate URL" button to see the beta notice.
I'm open to wordsmithing here. I couldn't exactly figure out what to call this feature... we don't say "Machine Images" anywhere else on this page. The grammar might be a bit weird too... "Image Uploads **are** currently in beta...". Would love to hear your thoughts.

Add beta notice for image uploads

---

packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
packages/manager/src/features/linodes/transitions.test.ts
packages/manager/src/features/linodes/transitions.ts

Changes status transition text from `Disk Imagize` to `Capturing Image`
1. Go to `Images` and create/capture an image.
2. The status in `Images` should be `Creating`
3. Go to `Linodes`, the linode status you captured the image from should be `Capturing image`

change status from disk imagize to capturing image

---

packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

Remove the beta notice and legal text from the VLAN section of the Linode create flow and config modal. This will be released on 4/28 when the feature goes into GA.
Everything should work as before; the beta chip and info should not be displayed.

For release: Remove beta notices and link for VLANs since they're leaving beta

---

packages/manager/cypress/integration/stackscripts/stackscripts.spec.ts

just a small stackscripts e2e test update
- `yarn cy:e2e -s ./cypress/integration/stackscripts/stackscripts.spec.ts` in another
- Result should be `✔  All specs passed!`
```
MANAGER_OAUTH
```

small fix for stackscripts e2e

---

packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/themeFactory.ts

Update the green icon color and remove the opacity on hover to make the icon look more vibrant
| Before: | After: |
| :--- | :--- |
| <img width="199" alt="Screen Shot 2021-04-28 at 3 05 22 PM" src="https://user-images.githubusercontent.com/7692354/116458925-2efc0980-a833-11eb-8df5-ab0b5e7dc857.png"> | <img width="198" alt="Screen Shot 2021-04-28 at 3 04 30 PM" src="https://user-images.githubusercontent.com/7692354/116458926-2f94a000-a833-11eb-8e37-5679accb389f.png"> |
Hover over the rows in the `PrimaryNav`

M3-5041: Make icon more vibrant on hover

---

packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx

Change the color of the instructional text in the Object Storage drag and drop area to `theme.palette.text.primary` (gray in light mode, white in dark mode).

M3-5013: Change OBJ drag and drop instructional text color

---

packages/manager/src/components/BackupStatus/BackupStatus.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx

Backups are unavailable for Bare Metal instances. This PR adds "N/A" with a tooltip explaining this to the "Last Backup" cell for Bare Metal instances in the Linodes landing table.

M3-4957: "Last Backup" cell for Bare Metal instances

---

packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts

Forgot to apply the changes from [https://github.com/linode/manager/pull/7619](https://github.com/linode/manager/pull/7619) to the active state

Apply adjusted brightness for PrimaryNav icon to active state

---

packages/api-v4/src/account/types.ts
packages/manager/src/__data__/account.ts
packages/manager/src/factories/account.ts
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx

Displays `Applies to: <service_type>` in the promo billing summary if the service type is not "all".
1. You will need to update your `.env` file to use dev services
2. Login to a dev test account that has a specific service type promo applied to it. The 4th dev test account currently has the service type `linodes` applied.
3. Click on `Accounts`
4. You should see a promotions box, under the `expires` line, there should be another line that says `Applies to: <service_type`

M3-5058: Show promo service type in billing summary

---

packages/manager/src/components/BackupStatus/BackupStatus.tsx

- Adds a link to our ["Backing Up Your Data"](https://www.linode.com/docs/guides/backing-up-your-data/) guide in the tooltip
- Refactors file to use `useStyles()`
Use an account that has a Bare Metal Linode and navigate to the Linodes landing table. Check the tooltip in the "Last Backup" cell

M3-5128: Add docs link in "Last Backup" Bare Metal column tooltips

---

packages/manager/src/components/Button/Button.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx

Fixes `Add Disk` button styling and alignment in `RescueDialog`
In `Linodes`, click on a kebab for a linode and then click `Rescue`

fix Add Disk button styling in RescueDialog

---

packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts
packages/manager/src/components/SideMenu.tsx

Refactors the SideMenu component and prevents the scrollbar from overlapping it when the height of the viewport is decreased. 
Since the menu is only in the collapsed view when the width is > 600px, I set the vertical overflow to hidden in order to hide the scrollbar but the scroll is restored on hover. 
Set your MacOS preferences to always show the scrollbar and decrease the height of the viewport. The scrollbar should no longer be visible on the collapsed view of the SideMenu until you hover which also expands the menu.

M3-5070: SideMenu scrollbar overlap

---

packages/manager/src/features/Events/EventsLanding.tsx

Make the column headers of the Events landing table (found under "Activity Feed" and the /events page) bold, size 14, and color `#888F91`

M3-4862: Styling for EventsLanding table column headers

---

packages/manager/src/features/Images/ImagesDrawer.tsx
packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
packages/manager/src/features/Kubernetes/kubeUtils.ts
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDiskSpace.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
packages/manager/src/features/linodes/presentation.test.tsx
packages/manager/src/features/linodes/presentation.ts
packages/manager/src/store/linodeType/linodeType.reducer.ts
packages/manager/src/utilities/formatStorageUnits.test.ts
packages/manager/src/utilities/formatStorageUnits.ts

This PR updates formatting for storage units across the cloud manager application. There are a few places where storage sizes are listed that needed to updated in place but for the Linode plans there is an update to the reducer that should be reflected in all places where the name of the Linode plan are visible.
Check to see if there are any places in the app where there is not a space before the storage unit

M3-4841 consistent storage units render

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx

- Remove all Beta notices and chips for Firewalls
- Hide regions list when all regions are supported
Visit all Firewalls pages and make sure no Beta stuff is visible. You can mock or otherwise adjust your data so that all regions include "Cloud Firewall" in their `capabilities` array; when this is true, the list of available regions shouldn't be displayed.

Remove beta notices for Firewalls 

---

packages/manager/cypress/integration/linodes/resize-linode.spec.ts
packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts

This change was needed because of some recent ui changes to these pages
just a small stackscripts e2e test update
- `yarn up` 
-  For First Test: `yarn cy:e2e -s ./cypress/integration/linodes/resize-linode.spec.ts`
- For Second Test: `yarn cy:e2e -s ./cypress/integration/lke/smoke-lke-create.spec.ts`
```
MANAGER_OAUTH
```

E2E Update: resize-linode and lke tests

---

packages/manager/src/features/Images/ImagesLanding.tsx

This renames:
- "Manual Images" => "Custom Images"
- "Automatic Images" => "Recovery Images"
Visit /images to view the changes. 
N/A

M3-5144 changed names of image sections

---

packages/manager/src/components/EnhancedSelect/Select.styles.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx
packages/manager/src/queries/linodes.ts

Fixes issues sharing IPs on a huge account, screen shots shared privately to avoid exposing customer details.
- Set the page_size to the API max in the linodeQuery used in IPSharing.tsx
(a single request of page_size: 100 isn't enough to return every option
in a datacenter for large customers, which resulted in strange behavior.
- Added a useAllLinodesQuery so that we can request all Linodes in e.g. a
single region. This is so that if a user with more than 500 Linodes in a single
region tries to use IP sharing, all options will be available. (There are a handful
of customers that meet these criteria). The search solution that we use for IP transfer
doesn't work here without a lot of overhead/mess, because the list of Linodes is
used for multiple purposes and filtering it on search text …

Fix: IP sharing for large accounts

---

packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/BareMetalRescue.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/shared.ts

Added a link to Linode's ['Rescue and Rebuild' documentation](https://www.linode.com/docs/guides/rescue-and-rebuild/) on the Rescue Dialog. 
I modeled this off of the Resize Dialog in `LinodeResize.tsx`.
Open the **rescue** modal for any Linode and verify there is a 'Learn more.' link that brings you to the documentation linked above.

M3-5130 added link to documentation on rescue modal

---

packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevices.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesDialog.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TrustedDevicesTable.tsx
packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
packages/manager/src/features/TopMenu/iconStyles.ts

- **M3-5124:** Shift the help, community, and notification icons on the top nav down so they're vertically centered with the user icon
- **M3-5037:** Change the font weight for the "Show Details" button on the Create Linode via StackScripts panel
- **M3-5108:** Updates to the Trusted Devices section under "Login & Authentication" if Linode credentials are in use:
- Add helper text below title
- Hide table when no devices are selected
- Change "Untrust" to "Revoke"

Multiple UI updates

---

packages/manager/src/features/Images/ImagesActionMenu.tsx

Changes the dropdown option `Deploy to Existing Linode` to `Rebuild an Existing Linode`
Go to `/images` and use the dropdown on an image and verify there is a `Rebuild an Existing Linode` option.

M3-5145 changed dropdown option Deploy to Existing Linode to Rebuild an Existing Linode

---

packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx

This PR fixes the rendering issues on the Kubernetes create cluster screen for chromium based browsers. This is accomplished by removing an unused radio button that was `visually-hidden` which interacted strangely with the `EnhancedNumberInput` component.
Open the manager in a chromium based browser and navigate to the create Kubernetes cluster screen. Shrink the browser window height enough so that the linode plan quantity selection table is just out of view. Refresh the page. Scroll down to the plan quantity selection table. All the quantity selectors should be visible and hovering over any of the fields or buttons should not cause any other field/button to disappear.

M3-4799 create cluster button flickering fix

---

packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/utilities/images.ts

If there is an unknown icon, fallback to the Tux icon (instead of not displaying an icon at all).
To test, log in to one of the prod test accounts and create a Linode. You should see AlmaLinux as an option with the Tux icon. On develop, there will be no icon.

hotfix: Fallback to Tux icon for unknown distro icons

---

packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts

small lke e2e test update
- `yarn cy:e2e -s ./cypress/integration/lke/smoke-lke-create.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Update: small change based on default node number

---

packages/manager/package.json
packages/manager/src/features/ObjectStorage/ObjectUploader/ObjectUploader.tsx
yarn.lock

Upgrade react-dropzone to 11.2.0, specifically to allow for use of `maxFiles` prop (see [this section](https://react-dropzone.js.org/#section-accepting-specific-number-of-files) of docs -- useful for https://github.com/linode/manager/pull/7615). Use new `FileRejection` type in `ObjectUploader.tsx`.
Please test the Object Storage uploads to ensure that no functionality has been lost or compromised.

M3-5198: Upgrade react-dropzone

---

packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/BareMetalRescue.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx

Adds copy to the Rescue Dialog for Bare Metal instances informing the user that they should use the LISH console to connect to their Linode upon rescue. Also includes a link that directly opens LISH for them. 
Open the Rescue Dialog on a Bare Metal Linode and ensure copy and links are good.

M3-5129:  Added connect with LISH copy to rescue modal for Bare Metal instances

---

packages/manager/src/index.css

This removes focus styles for focusable elements when the element is clicked on with the mouse.
**Example:** Linode Create -> "Choose a Distribution" Paper
In production, clicking this panel will activate the browser's focus styles around the Paper (e.g. dashed border). This is because tabbed panels have a `tabindex`, making it focusable. This is good for accessibility, but it is not necessary when the element is selected with a mouse.
This uses the new `:focus-visible` pseudo-class , which selects for the same heuristics the browser uses to display the default focus indicator. This can be combined with `:focus:not` to select elements which are focusable _but that the browser has determined should not have a focus indicator._ 
```
:focus:not(:focus-visible) {
outline: none;
}
```
More …

Remove focus styles for mouse users

---

packages/manager/package.json
packages/manager/src/components/ImageSelect/icons.ts
yarn.lock

Updates font-logos to v0.17 so we have access to the AlmaLinux Icon
Get this PR locally and run `yarn` to ensure you have the latest dependencies.
Go to `Create a Linode` and see if the new AlmaLinux icon shows up in the Image selector for the AlmaLinux image as shown above.

M3-5165: Updated font-logos dependency and added AlmaLinux icon

---

packages/manager/src/factories/objectStorage.ts
packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/mocks/serverHandlers.ts

Addresses potential issue with loading paginated data from the API  when loading objects in an object storage bucket.
Some users experience incomplete results when loading their objects.  It appears that the API sometimes does not respect the page number query parameter resulting in a response that tells the client: "here are a few items (less than the quested page number), but there are still more to load." When the API does that, it also returns a nextMarker that does not make sense. This may be an issue with the API or Object Storage. 
This PR fixes this edge case by removing the check `results >= 100` so our infinite scroll waypoint renders depending on `allObjectsFetched` which is going to be accurate. The actual bug fix is in `BucketDetail.tsx`.
This PR also enables the MSW to mock …

M3-5113: Fix viewing Object Storage contents

---

packages/manager/cypress/integration/account/smoke-billing-contact.spec.ts
packages/manager/cypress/integration/notificationsAndEvents/notifications.spec.ts

just a small stackscripts e2e test update
- `yarn cy:e2e -s ./cypress/integration/account/smoke-billing-contact.spec.ts` in another
Also:
-  `yarn cy:e2e -s ./cypress/integration/notificationsAndEvents/notifications.spec.ts`
```
MANAGER_OAUTH
```

E2E Update: small changes to work with credit card drawer

---

packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/ResizeNodePoolDrawer/ResizeNodePoolDrawer.test.tsx
packages/manager/src/features/Kubernetes/kubeUtils.ts

Changes the language in the warning recommending users use at least 3 nodes for their LKE cluster. 
Prepare to buy a Kubernetes Cluster with less than 3 nodes and ensure the warning says `We recommend a minimum of 3 node in each NodePool to avoid downtime during upgrades and maintenance.`

M3-5162: changed warning message to include new language

---

packages/manager/src/components/EntityTable/APIPaginatedTable.tsx
packages/manager/src/components/EntityTable/EntityTableHeader.tsx
packages/manager/src/components/EntityTable/EntityTable_CMR.tsx
packages/manager/src/features/Domains/DomainTableRow.tsx
packages/manager/src/features/Domains/DomainsLanding.test.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx

Tables using the `APIPaginatedTable` component did not have the right styling and are missing the last column in the header since the props weren't being passed down.
Login to `prod-test-001` and go to `/domains`

M3-5208: Fix Domains table header for large accounts

---

packages/manager/src/eventMessageGenerator.ts

Updates the logic for displaying an event when the API sends us an optional message. This change allows us to use the API's message in our own message we generate. 
Domain record creation and update event messages now use our own message combined with what the API gives as a message. 
View your events in the drawer or on the Events landing page and verify that the message for domain record creation and updates are more descriptive and grammatically correct.

M3-5150: updated event text for domain record creation and update

---

packages/manager/src/queries/linodes.ts

Fixes IP sharing for large accounts. 
_Accounts with over 500 linodes were affected by this issue._
Go to a `Linode`, go to the `Network` tab, open the `IP Sharing` modal and ensure the `Select an IP` includes **every**
possible IP from all of a user's Linodes in the region of that Linode.
Please test on large accounts.

M3-5202: Fix IP Sharing for large accounts

---

packages/manager/src/features/Images/ImageUpload.tsx

Remove beta chip, text and link from Machine Images after confirming that Machine Images is in GA
1. Go to `/images`
2. Click on the "Create Image" button
3. Click on the "Upload Image" tab
4. The beta tag should no longer be above the label textfield

M3-5203: Remove "beta" tag from Machine Images

---

packages/manager/cypress/integration/notificationsAndEvents/events.spec.ts
packages/manager/cypress/tsconfig.json

This change was needed because of a recent change
just a small events e2e test update
- `yarn cy:e2e -s ./cypress/integration/notificationsAndEvents/events.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Update: Events

---

packages/api-v4/src/account/payments.ts
packages/api-v4/src/account/types.ts
packages/validation/src/account.schema.ts

Adds new payment endpoints with respective validation.
Updates
- `POST` `https://api.linode.com/v4/account/payments`
Adds
- `GET` `https://api.linode.com/v4/account/payment-methods`
- `POST` `https://api.linode.com/v4/account/payment-methods`
- Add validation with `PaymentMethodSchema`
- `GET` `https://api.linode.com/v4/account/client-token`
Test payment endpoints in`@linode/api-v4` and `@linode/validation`.

M3-5230: Added new payment endpoints and validation

---

packages/manager/src/featureFlags.ts
packages/manager/src/features/Profile/Referrals/Referrals.tsx

Adds a Notice component to the referrals page. The presence of this Notice, along with the content, is sources from Launch Darkly.
Go to profile/referrals. Test with and without the flag (in the test environment).
N/A.

Hotfix: Referral Banner

---

packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts

firewalls have been added to dallas. this is a negative test so needed to change region to non firewall
just a small firewall e2e test update
- `yarn cy:e2e -s ./cypress/integration/firewall/migrate-linode-with-firewall.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Update: Firewall

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

When editing a Linode's default config or adding a new one, clicking the "Add a Device" button should be possible until you reach `/dev/sdh`. Users were being blocked from getting there because the condition disabling the button was set 1 lower than it should've been. 
Edit default configs and add new ones from a Linode's "Configurations" tab. Confirm that clicking the "Add a Device" button until it is disabled takes you up to `/dev/sdh`. Save Changes/Add Configuration and confirm that the proper disks/volumes are tied to the Block Devices you assigned them to.

M3-5133: Fix bug that prevented /dev/sdh Block Device from showing up 

---

packages/manager/src/components/core/Divider.tsx

Fixes the `unknown-prop` warning that shows up in the console as a result of the custom props (`spacingTop`, `spacingBottom`) that I made for Divider. More information on that [here](https://reactjs.org/warnings/unknown-prop.html).
Passing the remaining properties as `...rest` should prevent the DOM from complaining
Check the console to make sure that there's no longer an error

Fix console warning for Divider custom props

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx

Uses React Query to populate `/account/transfer`
This should not cause any visual changes. 
Make sure network transfer usage appears to be accurate across Cloud Manager.

M3-5178: Use React Query query to populate account network transfer

---

packages/manager/src/features/OneClickApps/FakeSpec.ts

Updates Virtualmin and Webmin Marketplace links in the detail drawer
Go to Marketplace and click on the blue information icon for Virtualmin/Webmin. In the detail drawer, click on the guide link and ensure it works.

M3-5265: Update Virtualmin and Webmin Marketplace links

---

packages/manager/src/components/FileUploader/FileUploader.tsx

Currently we are determining if an image is the correct file type by making sure the mime-type is "application/x-gzip". This PR makes this check more broad so that "application/gzip" (which is valid) also passes the test.
Image uploads should continue to work as before. I was unable to reproduce the original bug report, and am unclear about the mechanics of the mime-type here. Even if a file as a mime-type of `application/gzip` on my computer, when I drag it to the upload area the browser reads it as `application/x-gzip`. **So this is more of a theoretical fix that shouldn't break anything.**

M3-5256: Match Image Upload file types more broadly

---

packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/Paypal.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
packages/manager/src/queries/accountBilling.ts

- Populate billing & payment history table using React Query
- Update the table by invalidating the query after a payment is made and also update account balance
- Close payment drawer and display success toast after successful payment
Go to Account and make a payment. After a payment is successfully submitted, the following should update without a page refresh:
- The billing & payment table with the new payment
- The account balance in the Account Balance paper and also in the Make a Payment drawer
- The payment drawer should close and there should be a success toast displayed

M3-5261: Successful payment UI updates

---

packages/manager/src/components/TextField.tsx

Fixes Formatting Error when Showing rDNS Error by removing the static `34px` height on the error text. 
I'm sure at some point there was a reason for using a static height of `34px` so please look for breaking changes throughout Cloud. 
- Go to any Linode, Click the Network tab, Edit your Linode's RDNS with an invalid domain
- Check for issues in other text fields in Cloud Manager for

M3-5030: Fix Formatting Error when Showing rDNS Error

---

packages/manager/src/components/HelpIcon/HelpIcon.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
packages/manager/src/features/Billing/Providers/GooglePay.ts

- Adds loading spinner to the GPay Chip & Button components while Google Pay is still loading
- If there is an error loading or initializing Google Pay, the spinner is replaced by an error message
- Error messages while making a payment in the Make a Payment drawer are now toasts to match the Add Payment Method drawer
- Minor refactoring
In `account/billing` on dev:
- Refresh the page and click on `Add Payment Method`. In the drawer, you should briefly see a loading spinner before it's replaced by the Google Pay Chip
- Refresh the page again and this time click on `Make a Payment`. In that drawer, you should briefly see a loading spinner near the bottom before it's replaced by the Google Pay Button
- Adding Gpay as a Payment Method & making a payment should still work as before
- Switch …

M3-5281: Add loading spinner while GPay loads

---

packages/api-v4/src/account/payments.ts
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/UpdateCreditCardDrawer/UpdateCreditCardDrawer.tsx
packages/manager/src/queries/accountPayment.ts

- Use `POST /account/payment-methods` since `POST /account/credit-card` is deprecated.
- Refetch payment methods after the edit occurs
- Adds a success toast 
- Updated the credit card icon map to correctly map based on the API's card types
- Point Cloud Manager to dev environment 
- Try editing your credit card by using the `Edit` button on your credit card's action menu. 
- You can find a list of test credit cards [here](https://developer.paypal.com/braintree/docs/guides/credit-cards/testing-go-live/php)
- Ensure you credit card gets updated, you see a success toast, and your payment methods show the new card.

M3-5285: Update the Edit Credit Card drawer to use new API endpoint

---

packages/manager/src/features/Images/ImageRow.tsx
packages/manager/src/features/Images/ImagesActionMenu.tsx
packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
packages/manager/src/features/Images/ImagesLanding.tsx

Allows users to retry a failed Image upload. If during the processing of an image on the server side an error is encountered then the Image in the ImagesLanding table will change it's status to 'failed' and two options will be available to the user via the ImageActionMenu on the right side of the row. First will be Remove which will remove the Image entry from the table. The Image will already have been removed on the server side since the Image processing failed. The other option will be to Retry the Image upload. This will bring the user back to the Image upload form where the Label and Description will be pre-filled based on the failed Image they are retrying. 
Attempt to upload an image known to cause an error during processing. Wait for the processing to fail. Check that the image …

M3 5205 retry image upload

---

packages/manager/package.json
packages/manager/src/components/ImageSelect/icons.ts

- Updates [font-logos](https://github.com/lukas-w/font-logos/releases/tag/v0.18) to `v0.18`
- Adds Rocky Linux icon to distro icon map
- Restart your local dev environment so dependencies get updated
- Go to `Create a Linode`, select the `Image` dropdown and make sure `Rocky Linux 8` appears with its icon. You should **not** see the default Linux penguin.

M3-5257: Updated font-logos and added Rocky Linux icon

---

packages/manager/.env.example
packages/manager/src/constants.ts
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/statusPage/statusPage.ts

Uses new env variable `LINODE_STATUS_PAGE_URL` instead of  `LINODE_STATUS_PAGE_ID` to populate system status. This also improves defaults because you no longer need an env variable for the fetch to work. 
Ensure Manager can still fetch for system status.

Use new status page url for system status

---

packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
packages/manager/src/components/FileUploader/FileUploader.tsx
packages/manager/src/components/LinodeCLIModal/LinodeCLIModal.tsx
packages/manager/src/features/Images/ImageUpload.tsx
packages/manager/src/utilities/ga.ts

Add analytic events:
- When a user begins an image upload
- When an image upload is successful
- When an image upload fails
- When a user clicks "Copy" on the Image Upload CLI modal
The first three event types capture the file size. 
For the CLI Modal, I call the function on the generic LinodeCLIModal component if an `analyticsKey` prop is passed in (since we'll likely want to capture these events for future CLI modals.
- Run the app with GA enabled
- Open the dev tools console
- Upload and image and notice the events being sent
- Open the CLI modal and click "Copy"; notice the event that is sent.
Also, I fixed an invalid DOM nesting console error in the LinodeCLIModal component.

Add analytics for Image Uploads

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx

For `payment_due` notifications where a user is outside of their grace period, the API will now be returning a severity of `critical` instead of `major`. We will key off of `critical` to govern the intensity of our messaging regarding account balance, on /account/billing and in the notification drawer.
Check two accounts: one with a past due balance, and one with an outstanding balance that is not yet past due (reach out for a couple of accounts that meet this condition already).
The account with a past due balance should have an Account Balance panel and a drawer notification that look as follows:
The account with an outstanding balance that is not yet past due should have an Account Balance panel and a drawer notification that look as follows:
Other balance cases (no balance or a …

M3-4721: Changes to how account balances are communicated in app

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx

- Expands all Linode Settings accordions by default
- Forces fetch for disks when password section is mounted
- Visit `/linodes/{id}/settings`
- Make sure all accordions are expanded by default and all forms function as expected

M3-5280: Expand all Linode Settings accordions by default

---

packages/manager/src/components/CheckoutBar/DisplaySectionList.tsx
packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx

- Fixes a console error telling us we need to have children with difficulty keys. 
- Fixed by using the Nodebalacer's config id when rendering the configs instead of duplicating the Nodebalancer's id. 
- Make sure you have at least one Nodebalancer and that Nodebalancer has more than one config on it.
- Go to `/nodebalancers`
- Check your console for errors regarding duplicate keys.

M3-5163: Fix Nodebalancer Table console error children with the same key

---

packages/manager/src/components/TableRow/TableRow.tsx

Fix the `staticContext` console warning caused by #7705 
Go to any page with a table on it and the console should no longer be displaying a warning

M3-5260: Fix staticContext console warning

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

Adds a deep link to the `Add a Payment Method` drawer at `/account/billing/add-payment-method`.  This works the same way `/account/billing/make-payment` works. This is very beneficial because support can link customers directly to the open drawer. 
- Make sure going to `/account/billing/add-payment-method` opens the drawer.
- Make sure the drawer still functions as expected

Deep link Add Payment Method Drawer

---

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/features/Kubernetes/index.tsx
packages/manager/src/features/linodes/index.tsx

- Make Kubernetes router a functional component
- Clean up Linodes router
- Fixed `/kubernetes/create` not showing as active in the main navigation
- Test all `/kubernetes` routing
- Make sure `Kubernetes` in the navigation shows as active when at `/kubernetes/create`

M3-5314: Fix Kubernetes Create Active State and Refactor

---

packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx

Payments listed in the Billing & Payment History table will no longer show payments as a negative number in parentheses. The number of a credit or debt will be shown as the absolute value of the credit or debt. Instead relying on other information to show a credit as opposed to a debt.  
Load an account with debts and credits to verify the parenthesis should not be shown. 
run: `yarn workspace linode-manager run test BillingActivityPanel`

payments in payment activiy table are never negative

---

packages/api-v4/src/account/payments.ts
packages/api-v4/src/account/types.ts
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
packages/manager/src/factories/accountPayment.ts

- Click `Make Default` in a payment method's action menu and make sure it becomes your default payment method

M3-5298: Change Default Payment Method

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

Allows dismissing of the `Google Pay is now available...` notice and saves it to the user's preferences
In `account/billing` on an account without Google Pay added as a payment method, you should see the `Google Pay is now available...` notice in the Payment Method paper along with an `x` button. Clicking the `x` button should dismiss the notice and the notice should no longer appear after refresh.

Allow dismissing of Google Pay available notice in Payment Methods paper

---

packages/api-v4/src/account/types.ts
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.stories.tsx
packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCardPayment.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx

- Show card info in the Payment Method Row for Google Pay
- Show Google Pay text on desktop, hide for mobile
- Refactor to use CreditCard type
In `account/billing`, ensure that Google Pay is added as a Payment Method. The Payment Methods paper should now display the card information.

Show card info for GPay in Payment Methods paper

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx

The "Other Entities" data point has been a recurring source of confusion and opaque fluctuations. This PR removes it since Monthly Network Transfer Pool was added back to the Linodes landing page a while ago.
Checking the "Network" tab of a Linode detail page, "Other Entities" should no longer be listed in the "Monthly Network Transfer" section. Confirm that no other data or graphs are thrown off by this removal.

M3-5247: Remove "Other Entities" from Monthly Network Transfer section of Network tab

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/AlertSection.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsDeletePanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeWatchdogPanel.tsx
packages/manager/src/themeFactory.ts

Since the Linode settings are now expanded by default, I tightened up the spacing in the Notification Thresholds and Shutdown Watchdog panels.
Also refactored and cleaned up the code for those, the Linode Label, and Delete Linode panels. While I was in there, I also adjusted the Linode Label primary action to be disabled unless a change is detected. 
Go to `/linodes/[insert_id]/settings` and make sure all the functionality hasn't changed.
- If you're testing the Shutdown Watchdog panel, check the API responses for `/linode/instances` to confirm that the change is reflected.

Clean up Linode Settings

---

packages/manager/cypress/integration/helpAndSupport/open-support-ticket.spec.ts

This ended up being caused by a weird cypress scrolling bug that specifically effects elements in fixed containers such as modals: https://github.com/cypress-io/cypress/issues/4233. I added a workaround ({ scrollBehavior: false }) for now. 
a small support-ticket e2e test fix
- `yarn cy:e2e -s ./cypress/integration/helpAndSupport/open-support-ticket.spec.ts` in another
```
MANAGER_OAUTH
```

fix for cypress bug with workaround for now

---

packages/manager/cypress/support/ui/constants.ts
packages/manager/e2e/pageobjects/profile/ssh-keys.page.js
packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx

The primary button at `/profile/keys` says "Add a SSH Key," while in the Linode Create flow we say "Add an SSH Key." The latter is more grammatically correct, so this PR brings the former into agreement with it and updates a couple of other files accordingly.

M3-5326: "Add an SSH Key" button

---

packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/features/StackScripts/Partials/StackScriptTableHead.tsx
packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx

Adding a hover state for the `SelectPlanPanel` inside of the Linode Create flow and the StackScript table row heights
- Go to `/linodes/create` and hover over the tabs under "Linode Plans".
- The background color should change on hover
- Go to `/stackscripts` and `/linodes/create?type=StackScripts`
- The table header row height should now be 46px which matches the other table headers

Minor UI fixes

---

packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx

Remove the hover state for the button in the top nav and adjust the link styles once the menu is expanded.
- The background for My Profile / Account in the top nav should no longer change.
- The links inside the menu should be 14px and no longer have a hover state as well unless the user is navigating through it via a keyboard.

M3-5277: My Profile / Account dropdown changes

---

packages/manager/src/features/Users/UserPermissions.tsx

Minor change that improves user experience. If a user grants full permissions to another user on their account, we need to refetch the users list so it us up to date. 
- Go to `/account/users`
- Find a user that is not you and click `User Permissions`
- Toggle `Full Account Access` and make sure changes are reflected when you navigate back to `/account/users`

M3-5329: Refresh Users Table on Permission Change

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransfer.tsx

Follow-up to https://github.com/linode/manager/pull/7766. 
As discussed in demo prep, to decrease discrepancies, remove the parenthetical GB limit after "Monthly Transfer Limit" on the Linode Network tab.

[For Demo] Remove parenthetical GB limit from Monthly Transfer Limit

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx

Fixes the GPay mark being too big in the Add Payment Method drawer 
Go to `account/billing/add-payment-method` and the icon shouldn't be huge anymore

Fix GPay mark regression in Add Payment Method drawer

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/Providers/GooglePay.ts

Some API warning messages do not have a `detail` field, which was causing the app to crash when trying to make a credit card payment. This fixes that and also adds warning handling for Google Pay payments
See slack

Handle API warning message when making a payment

---

packages/manager/cypress/integration/account/billing-contact.spec.ts

fix for billing contact which was failing because of the email address also appearing in the banner saying the sending the email failed
just a small billing-contact e2e test update
- `yarn cy:e2e -s ./cypress/integration/account/billing-contact.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Billing Test Update

---

packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx

Add a call to action sentence to the `payment_due` notification in the Notifications drawer.
Outstanding balance that isn't past due:
Outstanding balance that is past due:
In each case, the first sentence links to `/account/billing` and the second links to `/account/billing/make-payment`. Upon arriving at each destination, the notification drawer closes.
Check the Notifications drawer for an account with an outstanding balance that isn't past due and for one that is. Ensure no other notifications have been adversely impacted.
I have some reservations about the red and blue text in a single notification for the past due outstanding balance notification.
~~This PR is an alternative path from https://github.com/linode/manager/pull/7790 pending managerial and executive clarification and …

M3-5332: Refine handling of payment_due notifications in Notifications drawer

---

packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/Databases/CreateDatabaseDialog/SelectDBPlanPanel.tsx
packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectBackupPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx

- Refactors `SelectionCard.tsx` to be a functional component
- Removes the check icon from the selected plan and changes selected state
- The goal here is to make things like `2GB RAM` not wrap so it is more clear and readable
**The new selected state:**
https://user-images.githubusercontent.com/6440455/127504305-022e998a-fd4b-454b-bd82-6ad2c61f2fcd.mov
- Test selecting a Linode plan at `/linodes/create` on a small screen size

M3-5248: Change look of Selectable Linode Plan to fix wrapping

---

packages/manager/cypress/integration/firewall/migrate-linode-with-firewall.spec.ts

just a small firewall e2e test update. The intercepts were getting mixed up and not stubbing the post correctly. 
- `yarn cy:e2e -s ./cypress/integration/firewall/migrate-linode-with-firewall.spec.ts` in another
```
MANAGER_OAUTH
```

M3-5350 E2E firewall test update

---

packages/manager/cypress/integration/objectStorage/buckets.spec.ts
packages/manager/cypress/support/api/objectStorage.ts

Create Bucket Flow Test
Goes through flow of creating a bucket, mocked data
- `yarn cy:e2e -s ./cypress/integration/objectStorage/buckets.spec.ts` in another
```
MANAGER_OAUTH
```

M3-4411  E2E test for create bucket flow

---

packages/manager/cypress/integration/objectStorage/access-keys.spec.ts

This change was needed because of some recent copy changes to this page
just a small access-keys e2e test update
- `yarn cy:e2e -s ./cypress/integration/objectStorage/access-keys.spec.ts` in another
```
MANAGER_OAUTH
```

M3-5349  E2E update test to reflect copy update

---

packages/manager/src/components/PaymentMethodRow/ThirdPartyPayment.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx

Fixes the vertical stretching and missing icon occurring in Payment Methods for GooglePay in Safari and iOS Chrome.
Turns out Safari's default setting for `alignItems` is `stretch` so defining it as `flex-start` fixes the issue. A similar thing is happening to the GooglePay icon where Safari needs the height or width of the svg in order to render it.
Go to `accounts/billing` on different browsers and check the display for different resolutions.

M3-5346: GooglePay display in Safari

---

packages/manager/src/components/ErrorState/ErrorState.tsx
packages/manager/src/components/Skeleton/Skeleton.tsx

- Fixes x-overflow for Table related components by manually setting width to `100%` for the necessary Gird containers
Before:
After:
- Make sure things that use `Skeleton.tsx` still display as expected
- Make sure Loading state and error states of Tables look ok and have no x-overflow

Improve Table Loading and Table Error Styles

---

packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
packages/manager/src/features/Profile/OAuthClients/OAuthClients.test.tsx
packages/manager/src/features/Profile/OAuthClients/OAuthClients.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeys.test.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
packages/manager/src/features/Users/UsersLanding.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeActivity/LinodeActivity.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettings.tsx

Remove redundant headers from the Linode Detail tab pages and the settings related pages.
After removing the headers, there are several pages (ie. `/account/users`, `/profile/keys`, and `/linodes/id/configurations`) that are left with only a button in the header region. We decided to generally leave the buttons as they are except we removed the white background and aligned the button to the right. 
Check the page headers and make sure the ones remaining add some context or information rather than repeating the tab label.

M3-5331: Remove redundant headers

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx

From the Analytics tab in a Linode's Detail view, navigating to another Linode via the search bar results in a charts data update delay of up to 30 seconds in which the previous Linode's chart data is still shown.
From what I can tell, this happens because the `<LinodeSummary />` component doesn't unmount in that process, so `getStats()` doesn't get called before the interval is up.
This PR checks in `componentDidUpdate()` whether the `linodeId` prop has changed (which it does when you switch Linodes) and if it has, `getStats()` gets called, pulling in the correct chart data.
On the Analytics tab in a Linode's Detail view, use the search bar to navigate to another Linode. The chart data and all other data shown should be for the Linode you just navigated to, not the previous one.

M3-5164: Fix delay in graph reporting when navigating to Linodes from search

---

packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx

This fixes a bug in develop where creating a new volume with a tag results in a field error: "Unable to tag Volume." 
This appears to have been introduced in the recent [Yup upgrade](https://github.com/linode/manager/pull/7787). I don't exactly know why, though. We've always been validating tags in the CreateVolumeSchema as `array().of(string())`, but we've been sending an array of `_Tag`, which are objects. Maybe yup wasn't validating properly beforehand. In any case, we should dig more into this issue because it may also be present elsewhere.
To fix this, I extended the schema in CreateVolumeForm.
Create a Volume from the Create Volume page with a tag. Check that other validation still works as expected.

Fix: unable to add tags to Volumes during creation.

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

- Does not render the Google Pay notice when loading payment methods
- This makes the initial page load look better. Users that have Google Pay added would briefly see the Google Pay notice as their payment methods were loading, and then see the notice quickly disappear. This PR makes sure the payment methods are loaded before showing the Google Pay notice
**Before:**
https://user-images.githubusercontent.com/6440455/128217545-0923aa78-746c-4e74-8d5a-787582a75dd3.mov
**After:**
https://user-images.githubusercontent.com/6440455/128217536-812ca04f-23ad-4e57-a2c8-23ee75050cdf.mov
- Go to `/account/billing` and make sure
- Payment methods show up
- The Google Pay notice shows up on an account without Google Pay added
- The loading state for the payment methods section looks good

Do not display the Google Pay notice when loading payment methods

---

packages/manager/src/features/Billing/Providers/GooglePay.ts

This PR adds better error handling with respect to GooglePay errors. In particular on non-chrome browsers if a user closed the GooglePay pop-up window without authorizing a payment an error is thrown that was then logged into Sentry and caused a Toast notification to pop up that informed the user "Unable to add payment method". A similar error ocurred if the GooglePay pop-up was left up for more than 5 minutes. This should be handled in the same way. 
Attempt to add a new payment method using GooglePay on a non-chrome browser. Close the pop-up window without authorizing payment. This should silently fail without informing the user. There should be no Toast notification or error logged to sentry. The same should be true if the pop-up is left open for more than 5 minutes.

M3-5347: Handle errors thrown when payment popup is closed or timesout

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

- User has a credit card on file
- Go to /account/billing/add-payment-method
- Test on an account with a credit card on file
- Test on account with only Google Pay added
- Test on account with no payment methods on file

M3-5372: Add edit credit card notice to Add Payment Method drawer

---

packages/manager/src/components/Notice/Notice.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx

Improve firewall error message when trying to add a firewall to a Linode on an unsupported host
- Remove the Id
- Make the Linode label a link to that Linode's detail page
- Remove unnecessary `open a Support ticket` text
- Users can initiate inter-DC migration on their own. And in the event that this was a migration unrelated to one they queued up, there should already be a ticket open for it
Before:
After:
Try to add a firewall to a Linode that is on an unsupported host (reach out for exact steps)

M3 5339: Improve firewall error message for unsupported hosts

---

packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx

Fixes the placement of the "Edit" button on "Billing Contact" and the "Add Payment Method" button on "Payment Methods" and a regression for the add GooglePay banner.
Go to `/account/billing` and checking the "Billing Contact" and "Payment Method" panels.

UI fixes for /account/billing

---

packages/manager/config/webpack.config.prod.js
packages/manager/package.json
packages/manager/src/index.tsx
yarn.lock

This is essentially a rollback of https://github.com/linode/manager/pull/7779.
Although the app was working with Workbox, we want to do a bit more analysis and testing to see what exactly it is doing within the context of the app before releasing it into production. One risk with Workbox is that it can make debugging deployments more difficult.
Workbox will be explored further with a possible follow-up PR re-adding it.
The app should compile and function properly, and no service workers should be registered.

M3-5373: Remove workbox-webpack-plugin

---

packages/manager/src/eventMessageGenerator.ts
packages/manager/src/features/Events/Event.helpers.ts
packages/manager/src/utilities/getEventsActionLink.ts
packages/manager/src/utilities/getEventsActionLinkStrings.ts

Add handling for new `entity_transfer_accept_recipient` event; fix link strings for Service Transfer events so that clicking on those notifications brings you to the "Service Transfers" tab. 
Initiate and complete a service transfer; for `entity_transfer_accept_recipient` events, the recipient account should see a notification in the drawer that reads, "You have accepted a service transfer," and the account that sent the transfer should just have one that says, corresponding to the `entity_transfer_accept` event, "A service transfer has been accepted." Clicking both should bring you to the "Service Transfers" tab (`/account/service-transfers`).

M3-5385: Handling for entity_transfer_accept_recipient events

---

packages/manager/src/constants.ts

Adds the correct display location for the OBJ cluster at us-southeast-1.

Add display location for us-southeast-1 OBJ cluster

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts

This fixes a bug in production that my [dependency update PR](https://github.com/linode/manager/pull/7787) introduced.
That PR included an upgrade of Immer to v8.0.4. One thing I missed is that Immer introduced a breaking change in v8.0.0 that made state tree freezing (via `Object.freeze()`) the default behavior. This means that any state modified with `produce` is frozen, and attempting to modify properties results in a runtime error (e.g. `Cannot delete property 'ports' of #<Object>`). 
This is a sane default, but we were modifying part of the state tree intentionally in order to prepare the rule state to send to the API. That probably wasn't a good idea anyway, so what I've done here is _copied the object_ first, so modifications can be made without error.
See: 
- …

[for release] Fix: unable to add Firewall rules that use ICMP protocol

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

Unfortunately some of the changes made in https://github.com/linode/manager/pull/7718 opened the door to a couple of bugs in the LinodeConfigDialog, namely a non-functional "Use Custom Root" button and Root Device dropdown.
This PR fixes that by adding the relevant variables to `updateFor` for the `<Grid />` that contains these fields.
Ensure that adding and editing Linode Configurations work as expected.
To see the intended functionality prior to these bugs being introduced in late July, you can checkout a release from June by running `git checkout f5c6168bbce32a0a42a1d3de20ccb307e976f003` (Cloud v1.43.1) to compare.

M3-5360: Fix Root Device bugs in LinodeConfigDialog.tsx

---

packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx

Remove DC verbiage from Firewalls and add back link to open a support ticket in `AddDeviceDrawer.tsx`
Check the verbiage in `firewalls/create` and `firewalls/<firewall_id>/linodes`. The Linode select dropdown should also not be filtering regions anymore

Update firewalls text

---

packages/manager/src/components/FileUploader/FileUploader.tsx
packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
packages/manager/src/components/PaymentMethodRow/DeletePaymentMethodDialog.tsx

This fixes the background color for disabled buttons and the Upload Image button in dark mode.
Example:
- Turn dark mode on
- Go to `/linodes` on a restricted account (or turn off one or more Linodes on any account)
- The background of the disabled inline actions should be the same color as the table background
- Go to `/images/create/upload` 
- The "Browse File" font and background color should be different

M3-5381: Fix disabled action buttons in dark mode

---

packages/manager/cypress/integration/objectStorage/buckets.spec.ts

this test had some issues when running in ci. this will hopefully fix that
just a small stackscripts e2e test update
- `yarn cy:e2e -s ./cypress/integration/objectStorage/buckets.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Buckets test fix

---

packages/manager/cypress/integration/account/change-username.spec.ts
packages/manager/cypress/support/index.js

There is not too much to test with this. This change is primarily for the benefit of ci runs. I made a small change to the username test but it's minimal. This should help to avoid some api conflicts when trying to delete right after a test runs. Now we will only do cleanup before each test block so things should go a bit more smoothly.

E2E removing after hook to avoid conflicts in ci runs

---

packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/components/Drawer/Drawer.tsx
packages/manager/src/features/Account/CloseAccountSetting.tsx
packages/manager/src/features/Account/EnableObjectStorage.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
packages/manager/src/features/Managed/MonitorDrawer.tsx
packages/manager/src/features/Profile/APITokens/APITokenDrawer.tsx
packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
packages/manager/src/features/Profile/OAuthClients/OAuthFormDrawer.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeyCreationDrawer.tsx
packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx
packages/manager/src/features/Users/CreateUserDrawer.tsx
packages/manager/src/features/Users/UserProfile.tsx
packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
packages/manager/src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
packages/manager/src/features/Volumes/VolumeDrawer/VolumesActionsPanel.tsx

This PR will right align all Action Buttons in drawers, but I did not update the order in some drawers. @tiffwong will have a PR that fixes other drawers button placement. 
- Switch order of buttons and right align
- Make ‘Add SSH Public Key’ Secondary button style
- Switch order of buttons and right align
- Remove ‘Done’ button
- Switch order of buttons and right align
- Switch order of buttons and right align
- Switch order of buttons and right align
- Switch order of buttons and right align
- Right align button
- Switch order of buttons and right align
- Switch order of buttons and right align
- Remove close button
- Switch order of buttons and right align
- Should be Primary Buttons
- Switch order of buttons and right align
- Switch order of buttons and right align
- Make both buttons …

M3-5274 & M3-5275: Updated Button Placement and Styles

---

packages/manager/src/themes.ts

- Fixes the loading spinner not showing up in primary buttons
Before
After
- Check the styles of all buttons
- Make sure you can see the loading spinner in dark and light mode
- Make sure text inside buttons is still the correct color and not affected by this change

M3-5392: Fix primary button loading state in dark mode

---

packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx

- Fixes dark mode text color for Object Storage warning banners
```tsx
<Typography component="div" style={{ fontSize: '1rem' }}>
```
I used `component="div"` because `<ul>`'s can't appear as children of a `<p>` but I want the children to inherit the Typography styles. 
Before
After
- Manually mock a warning to show a banner
- Ensure styles look good in dark mode and light mode

M3-5391: Fixed Object Storage warning message styles in dark mode

---

packages/manager/cypress/integration/volumes/smoke-create-volumes.spec.ts

small update for volumes drawer change
- `yarn cy:e2e -s ./cypress/integration/volumes/smoke-create-volumes.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Volumes Test Update

---

packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx

- Fixed a random but somewhat important bug I found where on `/images/create/disk`, the **label** and **description** fields were not getting passed to the API and not being used. This made creating an Image from a disk really confusing. 
- Test creating an Image from a disk and also test uploading an Image.
- Make sure label and description get passed to the API in the dev tools network tab (previously it those values were not being sent)

M3-5395: Fix users unable to set a label and description when capturing an Image

---

packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx

- Fixes Kubernetes Debian images showing up in the Rebuild Dialog
- Caused by #7800 
- Fixed by filtering out Kube images when ImageSelection variant is `all`
Please check my filtering logic. I want to make sure Linode's Kubernetes images get filtered out but I want to make sure that if a user has a script with Kube in the name, it still gets shown.
- Check all Image selections in Cloud Manager
- Specifically Check the Linode Rebuild from Image Dialog

M3-5394: Fix Kubernetes Debian images showing up in the Rebuild Dialog

---

packages/api-v4/src/support/types.ts

- Fixes #7686 by using a relative path to import
- Pull this PR 
- Build @linode/api-v4 with `yarn build:sdk`
- Start a new Typescript project
-  `mkdir ts-test`
- `npm init`
- `npm install typescript --save-dev`
- `npm i @linode/api-v4`
- Use this `tsconfig.json` and `index.ts`
```{
"compilerOptions": {
"target": "es5",
"module": "commonjs",
"strict": true
}
}
```
```
import { getLinodeTypes } from '@linode/api-v4'
getLinodeTypes().then(types => {
console.log(types)
})
```
- Delete all files in the new project in `node_modules/@linode/api-v4`
- Manually copy the @linode/api-v4 files into a new Typescript project's `node_modules/@linode/api-v4`
- Run the Typescript compiler and make sure we don't see any import errors (as seen in #7686)

M3-5313: Fix @linode/api-v4 import issue

---

packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TicketReply.tsx

- FIxes weird text overflow issues in the Create Ticket dialog Text Field or Ticket Reply Text Field when user changes their browsers font size (chrome://settings/?search=Font)
- This issues was happening because the TextField component takes `rows` as a prop which dictates the size, but we also had a height css property on it, these were most likely conflicting.
- This fix is to remove the static CSS heigh we assigned and rely on the `rows` prop for size
Before
After
- Go to Chrome's settings and change the browser's font size to **large** or anything bigger
- Test the **Open a Support Ticket** dialog
- Make sure the reply Text Field for a ticket thread still looks right
- Make sure the size of ticket related dialogs look correct, because this PR changes the size a bit

M3-5368: Fix support ticket input with different font sizes

---

packages/manager/cypress/integration/account/google-pay.spec.ts

needed to change amex to american express
small gpay e2e test update
- `yarn cy:e2e -s ./cypress/integration/account/google-pay.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Gpay Test Fix

---

packages/manager/src/features/Domains/DeleteDomain.tsx
packages/manager/src/features/Domains/DomainDrawer.tsx
packages/manager/src/features/Domains/DomainRecordDrawer.tsx
packages/manager/src/features/Domains/DomainRecords.tsx

Make add buttons on the Domain Detail page primary and remove "Delete Domain" from the edit drawer
- Go to `/domains`
- Click on "Edit" and the "Delete Domain" button should no longer show up in the drawer
- Click on the label for any primary domain
- The add buttons on the right of each table should now be in the primary style

M3-5278: Update buttons for Domains

---

packages/manager/src/components/Accordion/Accordion.tsx
packages/manager/src/components/LinearProgress/LinearProgress.tsx
packages/manager/src/features/Support/AttachFileForm.test.tsx
packages/manager/src/features/Support/AttachFileForm.tsx
packages/manager/src/features/Support/AttachFileListItem.test.tsx
packages/manager/src/features/Support/AttachFileListItem.tsx
packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.test.tsx
packages/manager/src/features/Support/SupportTicketDetail/SupportTicketDetail.tsx
packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyActions.tsx
packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/TabbedReply.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
packages/manager/src/features/Support/TicketAttachmentList.tsx

This is a fairly older ticket which described the "Add Update" button going off the screen on mobile if there's a lot of text. I was still able to access the button when I tried to replicate this so it might've gotten fixed. 
I did reduce the vertical spacing on that page, collapsed the "Formatting Tips" by default aligned the "Add Update" button to the right so it's consistent with our style guide.
Also refactored the test for `AttachFileListItem` and fixed a bug where the `defaultExpanded` prop wasn't being applied to the `Accordion` component.
- Go to `/support/tickets/[insert id]` 
- Either create a bunch of replies on the ticket or message me for a test account that already has content in it
- Make sure you can access the "Add Update" button on mobile

M3-3874: Tighten spacing for Support Ticket Details

---

packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.tsx
packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx

- Hide the `Pay Now` button if there are no payment methods on file
- Fix displaying of expired cards
- Show tooltip if a card is expired and display the tooltip on the left side instead of the right
- On an account with no payment methods, the `Pay Now` button should not display in the make payment drawer
- If a payment method is expired:
- The text in the SelectionCard should be red and read `expired`
- The `Pay Now` button should be disabled and a tooltip should appear on the left side of the button

Make Payment Drawer UI fixes

---

packages/manager/cypress/integration/domains/smoke-create-domain-records.spec.ts

A small domain records e2e test update
- `yarn cy:e2e -s ./cypress/integration/domians/smoke-create-domain-records.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Domain Records Test Update

---

packages/manager/cypress/integration/linodes/clone-linode.spec.ts
packages/manager/cypress/integration/linodes/create-linode.spec.ts
packages/manager/cypress/integration/linodes/resize-linode.spec.ts
packages/manager/cypress/integration/lke/smoke-lke-create.spec.ts
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx

Swaps the order of the “Shared CPU” and “Dedicated CPU” tabs. I was initially going to make dedicated the standard, but api still has shared as standard. 
When you go to Create Linode, Resize Linode, Clone Linode, or Create LKE Cluster “Dedicated CPU” should be the first tab, selected by default. Test creating, resizing, cloning, creating LKE cluster flows as well just to be safe.
I will be adding some test updates to this pr as well.

M3-5418 Swap shared and dedicated cpu tabs

---

packages/manager/src/MainContent.tsx
packages/manager/src/components/MaintenanceScreen.tsx
packages/manager/src/request.tsx
packages/manager/src/store/globalErrors/types.ts

If the API is in maintenance mode, users would not be able to do anything in Cloud because successful API requests wouldn't be possible.
To avoid that, this PR creates a maintenance view that will display if the API is in maintenance mode:
To just test the view itself, you can make the condition on line 261 of `MainContext.tsx` true.
To test the logic for the response headers & errors, you'll need to use devenv. Please reach out if you need details on putting the API into maintenance mode in that environment.

M3-5375: Handle API maintenance mode

---

packages/manager/cypress/integration/images/create-linode-from-image.spec.ts
packages/manager/cypress/integration/stackscripts/stackscripts.spec.ts

This change is needed because of the tab swap pr
small stackscripts and create-linode-from-image e2e test updates
- `yarn cy:e2e -s ./cypress/integration/stackscripts/stackscripts.spec.ts` in another
-  Then `yarn cy:e2e -s ./cypress/integration/images/create-linode-from-image.spec.ts` in another
```
MANAGER_OAUTH
```

updates for tab change that I forgot in previous pr

---

packages/manager/src/featureFlags.ts
packages/manager/src/features/Images/ImageUpload.tsx
packages/manager/src/hooks/useFlags.ts

Starting on Sep. 1, 2021, Custom Images will be billed at $0.10/GB per month.
The current copy we have at the top of the "Capture Image" and "Upload Image" tabs will need to be replaced on 9/1 with permanent pricing copy.
This PR adds a feature flag for that permanent copy and updates the "Upload Image" tab.
I added temporary, commented-out code in `useFlags.ts` for both flags related to Images pricing copy (`imagesPricingCopy` is for the temporary copy currently in prod, `imagesPriceInfo` is the new one for the permanent copy) so you can locally override the flag values from LD.
To test what the state should be before 9/1, uncomment only the line for `imagesPriceInfo`.
To test what the state should be on 9/1 and after, uncomment only the lines for `imagesPricingCopy`.

M3-5429: Add feature flag for post-9/1 Images pricing copy & update "Upload Image" tab

---

packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
packages/manager/src/features/Users/UserPermissions.tsx

Un-comment the image price estimation and put it behind the `imagesPriceInfo` feature flag.
If the `imagesPriceInfo` flag is overridden then the price estimator for copying a disk image should be shown on the `ImageCreateTab` component.

Feature flag image price estimation

---

CHANGELOG.md
packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/accountMaintenance.ts

- Enables the getAllAccountMaintenace query by default
- Adds padding to the `Reason` column in the Maintenance Table (`/account/maintenance`)
- Parses any possible markdown returned in the reason field for the Maintenance Table (`/account/maintenance`)
- Make sure all maintenance events are populated on the Linodes landing page
- Make sure `/account/maintenance` still works as expected (still is API paginated and sorted)
- Make sure a notice banner appears for a Linode having maintenance on the Linode Detail Page

Fix Linode Maintenance Query

---

packages/manager/src/factories/accountAgreements.ts
packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/accountAgreements.ts
packages/manager/src/queries/base.ts

- Functionality for EU Contract on NodeBalancer Create
- The component should only be visible if the user has not signed the EU MC contract and is not a restricted user (restricted users have no access to view agreements)
- The "Create NodeBalancer" button should be disabled unless the the EU MC confirmation is checked.
- After the EU MC confirmation has been checked, when the user clicks "Create NodeBalancer", a POST to /account/agreements signing the eu model contract should be made. 
- Go to `/nodebalancers/create`
- Try to create a Nodebalancer in a non-EU region
- You should not see an Agreement Checkbox and you should be able to create a Nodebalancer as per usual
- Try to create a Nodebalancer in an EU region
- You should see an Agreement Checkbox
- If you don't it's probably …

M3-5402: Functionality for EU Contract on NodeBalancer Create

---

packages/manager/src/features/Support/SupportTicketDetail/TabbedReply/ReplyContainer.tsx
packages/manager/src/store/authentication/authentication.helpers.ts
packages/manager/src/utilities/storage.ts

When a user starts to write a reply to a support ticket the ticket ID and the user's response is stored in LocalStorage. This mimics the behavior of opening a support ticket. Unlike opening a support ticket a user may have multiple ticket replies to edit. When a user opens a ticket the application checks to see if `LocalStorage` has an entry in the `ticketReply` entry that has a `ticketId` that matches the support ticket the user is replying to. If the `ticketId` matches then it will prefill the reply text box with what is stored in `LocalStorage`. If the `ticketId` does not match what the user types will overwrite what is currently stored in `LocalStorage`.
There are 4 key functionalities to test
- Navigate to a support ticket and start to type a reply then leaving before submitting. …

M3-5317: Preserve Ticket Reply in LocalStorage

---

packages/manager/src/components/MaintenanceScreen.tsx

Update Linode logo used in MaintenanceScreen.tsx.
Before:
After:
Change the condition to `true`:
https://github.com/linode/manager/blob/f434767652640b634717d519cf6459b65482337c/packages/manager/src/MainContent.tsx#L261-L263

M3-5443: Update Linode logo used in MaintenanceScreen.tsx

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx

Add functionality for the EU Contract on Linode Create.
- The component should only be visible if the user has not signed the EU MC contract and is not a restricted user (restricted users have no access to view agreements)
- The "Create Linode" button should be disabled unless the the EU MC confirmation is checked.
- After the EU MC confirmation has been checked, when the user clicks "Create Linode", a POST to /account/agreements signing the eu model contract should be made. 
TODO:
On an account that hasn't signed the eu agreement:
- Go to `/linodes/create`
- Select a non-EU region:
- You should not see the EU agreement checkbox in the checkout bar
- Select an EU region:
- You should see the EU agreement checkbox and the `Create Linode` button should be disabled until it is checked
- …

M3-5400: EU contract functionality for Linode create

---

packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/accountAgreements.ts

Adds functionality for the GDPR agreement on the Volumes Create page.
Things to test:
- Create a Volume normally without having signing the agreement
- Create a Volume singing the agreement
- Create a Volume singing the agreement with either request failing
- Other things
Use the MSW to mock an account needing to sign the agreement. Uncomment the /agreements POST in serverHandlers to simulate a failure.

M3-5403: Functionality for EU Contract on Volumes Create

---

packages/manager/src/components/EnhancedSelect/Select.styles.ts
packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx

Remove spacing related styles that were throwing off the vertical alignment
Check dropdown components throughout the app

M3-5427: Vertically center icons and texts in dropdown

---

packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx

- Functionality for EU Contract on Object Storage - Bucket Create
- The component should only be visible if the user has not signed the EU MC contract and is not a restricted user (restricted users have no access to view agreements)
- The "Create Bucket" button should be disabled unless the the EU MC confirmation is checked.
- After the EU MC confirmation has been checked, when the user clicks "Create Bucket", a POST to /account/agreements signing the eu model contract should be made. 
- Go to `/object-storage/buckets/create`
- Try to create a Bucket in a non-EU region
- You should not see an Agreement Checkbox and you should be able to create a Bucket as per usual
- Try to create a Bucket in an EU region
- You should see an Agreement Checkbox
- If you don't it's probably because it is …

M3-5404: Functionality for EU Contract on Bucket Create

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx

Re issue https://github.com/linode/manager/issues/7750: Adds additional client-side Firewall rule label validation to match the API
I looked into validating using `FirewallRuleTypeSchema` but the current structure of the code made it difficult and it was a bit out of scope, so I just added onto the `validateForm` function
- Label is required
- There is inconsistency between actual API behavior and the docs. The [docs](https://www.linode.com/docs/api/networking/#firewall-create__request-body-schema) says label is required, however you can create a Firewall rule without a label. ARB-2686 has been created to address this
- Label must begin with a letter
- Label must only include ASCII letters, numbers, underscores, periods, and dashes
**What are the steps to reproduce the issue or verify the …

Add additional client-side Firewall rule label validation

---

packages/manager/cypress/integration/domains/smoke-create-domain.spec.ts

updating create domain test after input attributes were changed
- `yarn cy:e2e -s ./cypress/integration/domains/smoke-create-domain.spec.ts` in another
```
MANAGER_OAUTH
```

E2E Update Create Domain Test

---

packages/manager/src/features/Images/ImagesLanding.tsx

This PR increases the width of the linode image name width
Clone branch and view images under /images
N/A No relevant unit tests - small styling change only
ImagesLanding.tsx: "widthPercent" before only added up to 100 in the case of tableType=='automatic' and flagEnabled==true headers being passed in. 
This PR has the side effect of making the width percents not add up to 100 in this case but the way components/EntityTable/EntityTableHeaders.tsx presents the width to the TableCell doesn't seem to have a 100% sum requirement. Perhaps it's OK to ignore this since we do in most other instances, and making the ratios change to sum to 100% is kinda unwieldily?

M3-5358: Allow more room for image names

---

packages/manager/src/components/FileUploader/FileUploader.tsx
packages/manager/src/features/Images/ImageUpload.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
packages/manager/src/mocks/serverHandlers.ts

- Functionality for EU Contract on Image Create
- The component should only be visible if
- An EU region is selected
- The user has not signed the EU MC contract
- The user is not a restricted user (restricted users have no access to view agreements)
- The "Create Image" button should be disabled unless the the EU MC confirmation is checked.
- The dropzone and `Browse Files` button should be disabled if the checkbox is not checked 
- After the EU MC confirmation has been checked, when the user clicks "Create Image", a POST to /account/agreements signing the eu model contract should be made. 
- Go to `/images/create/disk` and `/images/create/upload`
- Try to create a Bucket in a non-EU region
- You should not see an Agreement Checkbox and you should be able to create a Bucket as per usual …

M3-5405: Functionality for EU Contract on Image Create

---

packages/manager/src/features/Managed/Contacts/Contacts.tsx
packages/manager/src/features/Managed/Credentials/CredentialList.tsx

Change the font size of the copy to 14px and removed the `subtitle1` variant since it was applying additional styles that we don't need
Go to `/managed` and click on the "Credentials" and "Contacts" tab to see the copy

M3-5445: Change font size for Credentials and Contacts copy

---

packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx

When a restricted user creates a Firewall, they are given read/write access to the newly created Firewall. This fixes the Firewall action buttons displaying as disabled after creation even though the user has r/w access. Current prod behavior is that the user needs to refresh the page for the buttons to display as non-disabled.
Note: There is a known issue where users can assign a read-only Linode while creating a Firewall. M3-5435 and ARB-2692 have been created to address that
On a restricted user with permissions to add Firewalls:
1. Go to `/firewalls` and click on `Create Firewall`
2. Give the Firewall a unique label and click `Create Firewall`
3. The action buttons for the newly created Firewall should not be disabled

M3-5436: Fix action buttons being disabled upon Firewall creation for restricted users

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx

According to API, the docs are wrong about label being a required field for Firewall rules. This undos that bit from my previous Firewalls PR https://github.com/linode/manager/pull/7874
- Go to `/firewalls/<firewall_id>`
- In the Rules tab, edit an existing rule or add a new inbound/outbound rule
- You should be able to edit/add a new rule with a blank label field
`yarn test FirewallRuleDrawer`

Undo label required for Firewall rules

---

packages/manager/src/components/TextField.tsx
packages/manager/src/features/Account/CloseAccountDialog.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Managed/Contacts/ContactsDrawer.tsx
packages/manager/src/features/Managed/Credentials/AddCredentialDrawer.tsx
packages/manager/src/features/Managed/Credentials/UpdateCredentialDrawer.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx

Add an optional label to `Textfields` to be used when the majority of fields are required and make the styling match the required styling (ie. lowercase in parenthesis and normal weight). Also renamed some of the fields on `AddCredentialDrawer` and `UpdateCredentialDrawer`.
Go to the following components and test to make sure the functionality has not changed:
- Go to `/managed`, click on the "Credentials" tab, and click "Add Credential"
- Go to `/managed`, click on the "Credentials" tab, and click "Edit" on any existing credential
- Go to `/managed`, click on the "Contacts" tab, and click "Add Contact"
- Go to any Linode Details page, click on the "Configurations" tab, click "Add Configuration", and select "VLAN" for any Network Interfaces dropdown
- Go to `/billing` and check the …

M3-5444: Add optional prop to Textfield and cleanup optional fields

---

packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx

Add's the ability to sign the EU contract agreement for the Create Kubernetes Cluster page.
If a user who has not accepted the GDPR agreement tries to create a cluster in an EU region then:
- In the checkout bar there should be a check-box component that allows the customer to agree to the terms.
- When the check-box is not checked then the checkout button should be disabled.
- When the check-box is checked then the checkout button should be enabled.
- If the user has agreed to the GDPR agreement then the checkbox should not be visible.
- If the user selects a region that is not in the EU then the checkbox should not be visible.

M30-5401: EU Contract Cluster Create

---

packages/manager/src/factories/statusPage.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx

The feature flag for API Maintenance events needed to be adjusted to give us more control over the title and body of the banner due to length and specificity concerns of the Statuspage data within the context of Cloud.
This PR accounts for that adjustment and does some other minor cleanup to the banner.
Pointing to prod, you should see a global banner that corresponds to [this upcoming maintenance](https://status.linode.com/incidents/khfqpfsfdh0g). Persisted dismissibility should still work across pages within the app and across different sessions.
You can uncomment the mocked data and turn on the MSW to confirm multiple maintenances are handled again.

M3-5458: Adjustments for API Scheduled Maintenance feature flag and banner

---

packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx
packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
packages/manager/src/queries/statusPage/statusPage.ts

Adjust dismissal logic to key off of `suppliedMaintenances` instead to allow a check to be done in `GlobalNotifications.tsx`
On `staging` right now, you will see a request to `scheduled-maintenances.json` on every window focus, even when you've dismissed the API Maintenance notification.
On this branch, you should see a single request to `scheduled-maintenances.json` when Cloud first loads, and no new requests to it on subsequent window focuses. If you dismiss the banner, that request should not be made on subsequent Cloud reloads.

[For Release] Reduce number of requests associated w/ API Maintenance Banner

---

packages/manager/src/features/linodes/LinodeEntityDetail.tsx

Removes the prefix length for IPv6 on the Linode Details Page
Navigate to a Linode that has an IPv6 address. In the details header the IPv6 address should not include the length prefix `/128`

M3-5442: Linode Details: remove /128 prefix length from IPv6 address

---

packages/manager/cypress/integration/images/machine-image-upload.spec.ts

since ci runs tend to load slower/differently than they do locally sometimes, I needed to make a couple changes to make sure these pass in ci
- `yarn cy:e2e -s ./cypress/integration/images/machine-image-upload.spec.ts` in another
```
MANAGER_OAUTH
```

E2E machine images test fix for ci

---

packages/api-v4/package.json
packages/manager/package.json

There was a bug introduced in axios v0.21.2 that handled interceptors incorrectly. 
We upgraded to 0.21.2 here: https://github.com/linode/manager/pull/7937
The result was that the app would crash when the API returned an error, since we rely on an interceptor to transform Axios errors into `APIError[]`. 
See the axios changelog: https://github.com/axios/axios/blob/master/CHANGELOG.md
Generally test that things are working throughout the app (happy paths and error paths).

Upgrade Axios again to fix app crashing bug

---

packages/validation/src/linodes.schema.ts

Currently, there's a bug preventing users from editing their Linode Configurations successfully without a workaround. Clicking "Save Changes" would look unresponsive.
Basically, non-VLAN network interfaces should be able to have `null` label fields in the schema (the appearance of a lack of response was because this schema-related error does not get surfaced in the UI -- you can edit `handleError` in `LinodeConfigDialog.tsx` to log errors to the console to observe the error prior to the fix in this PR). Making this adjustment makes the Config dialog function as intended.
Try to:
- edit a Linode Configuration's IPAM address by itself and save the changes
- edit anything else in the config aside from the IPAM address and save the changes
- edit the IPAM address + other stuff in the dialog …

M3-5438: Fix bug preventing Linode Configuration changes

---

packages/manager/cypress/integration/images/create-linode-from-image.spec.ts
packages/manager/cypress/integration/linodes/rescue-linode.spec.ts
packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
packages/manager/cypress/integration/volumes/smoke-create-volumes.spec.ts
packages/manager/cypress/support/api/linodes.ts
packages/manager/cypress/tsconfig.json

Multiple test updates and changes for image, linode-landing, and volumes tests as well as a change to the create mock linode helper.
- `yarn cy:e2e -s ./cypress/integration/images/machine-image-upload.spec.ts` in another
---------------------------------------------
- `yarn cy:e2e -s ./cypress/integration/volumes/smoke-create-volumes.spec.ts` in another
---------------------------------------------
- `yarn cy:e2e -s ./cypress/integration/linodes/smoke-linode-landing-table.spec.ts` in another
``` …
```

E2e multiple test updates

---

packages/manager/src/MainContent.tsx
packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
packages/manager/src/components/ConfirmationDialog/index.ts
packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx
packages/manager/src/components/SupportLink/SupportLink.tsx
packages/manager/src/context/complianceUpdateContext.ts
packages/manager/src/factories/notification.ts
packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx
packages/manager/src/features/GlobalNotifications/ComplianceUpdateModal.tsx
packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.test.ts
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/mocks/serverHandlers.ts

This adds two things:
1.  Banner indicating the user must accept the EU Model Contract agreement
2. Handling for the EU Model Contract agreement notification
The new modal component sits in the GlobalNotifications wrapper component, and context is used in order to control the component from across the app. This pattern is debatable and honestly I didn’t think about it as much as I would like since we’re moving quickly. If you have other suggestions I’d love to consider them.
I also did a slight refactor of the DismissibleBanner component to be able to use the functionality from another component.
**TODO**: ~Listen for the correct API notification (I just mocked it in for now)~
I included a mock notification in serverHandlers so if you use the MSW you should see the banner/notification.
To …

M3-5431 EU Model Contract agreement banner + notification 

---

packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx

Reduces the bottom padding of tag headers to make dark more more readable. I accidentally deleted the last [PR](https://github.com/linode/manager/pull/7919) 🙃
Create a few Linodes, tag them in the details view, return to the Linodes screen, and group by tag and verify they have a smaller padding than before. Make sure to check various screen sizes

M3-5341: Reduce bottom padding for Linodes grouped by tag

---

packages/manager/src/features/Images/ImageUpload.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketForm.tsx
packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
packages/manager/src/queries/accountAgreements.ts

- Updates state variable names to be consistent across files
- Adds error handling to all React Query Mutations we added
- Should we be calling the API with `{ eu_model: true, privacy_policy: true }`or`{ eu_model: true }`?
- My thought is `{ eu_model: true, privacy_policy: true }` since the agreement actual copy mentions and links the privacy policy.
- Ensure all agreement functionality still works
- Linode Create
- Linode Migrate
- Image Upload
- Bucket Create
- Volume Create 
- Nodebalancer Create
- ~Kubernetes Create~ (still in progress #7928)

GDPR Clean Up and Error Handling

---

packages/manager/src/features/Lish/Lish.tsx
packages/manager/src/mocks/serverHandlers.ts

This disables glish for bare metal machines by checking if the current Linode is bare metal
First you must authorize yourself for bare metal then create a bare metal linode and a non bare metal linode. Verify that the bare metal one has no glish and the non bare metal one does
Note: Not important but I went down a bunch of dead ends trying to use src/hooks/useExtendedLinode but because Lish is not a FC that didn't work. Then I thought about passing in the data from store.getState() in src/index.tsx because I misguidedly thought that perhaps Lish being a separate popup couldn't access the store and needed it passed in without realizing api calls work. TLDR - read documentation 🙃

Disable Glish on Bare Metal Machines

---

.github/workflows/e2e.yml

This PR changes the UI automation workflow to run on pushes to staging, as well as PR's when the `e2e` label is added. For now, all tests will run. Soon I will create more workflows for running only select tests based on what is changed in the PR.

E2e run workflow on staging and PRs with e2e label

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
packages/manager/src/utilities/creditCard.test.ts
packages/manager/src/utilities/creditCard.ts
packages/validation/src/account.schema.ts

- Allows user to enter a **two digit** or **four digit** expiry date
- Users were getting `Expiry too far in the future.` when entering a four digit year (MM/YYYY).
- Added `parseExpiryYear = (expiryYear: string | undefined): string | undefined` function to parse user input (year only)
- Added some unit tests for this
- Test the validation for the Credit Card form in the **Add a Payment Method** Drawer
- Test the **Expiry** field specifically
- Test with a 4 digit expiry year
- Test with a 2 digit expiry year
- `yarn test creditCard`

M3-5437: Fix validation saying "expiring too far in the future" when entering credit card expiration date

---

packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.test.tsx
packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx

Remove the cancel button, change the primary button label depending on the mode, and disable the primary button if no change has been detected in edit mode. Also includes **M3-5459** which involves renaming the drawer title from "Create an Access Key" to "Create Access Key".
Go to `/object-storage/access-keys` and click "Create Access Key"
- The drawer title should be "Create Access Key"
Close the drawer and click "Edit Label" on any access key 
- The button should say "Save Changes"
- The button should also be disabled unless a change is detected

M3-5441: Fix Create Access Key button order

---

packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx

Removes the "File System Path" column from the Volumes landing table
Check the Volumes landing table and ensure the "File System Path" column has been removed and that the table looks good across viewport sizes.
Also check the Volumes table on the Linode Detail --> Storage tab to make sure it has not been impacted.

M3-5481: Remove "File System Path" column from Volumes landing table

---

packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx

- The VLAN option was disabled in the Linode Create flow when restoring from a backup or cloning 
- Hides the VLANS section when cloning a Linode because cloning will copy the network interfaces
- Updates disabled tooltip copy for creating a Linode from a backup. (You cannot attach a VLAN when creating from a backup shown in the screenshot)
- Test all Linode Create Flows (from Image, from Backup, from Cloning, etc...)

M3-5424: Improve experience when attaching a VLAN when creating a Linode from a Backup or Clone

---

packages/manager/src/components/ActionMenu/ActionMenu.tsx
packages/manager/src/components/BackupStatus/BackupStatus.tsx
packages/manager/src/components/Button/Button.tsx
packages/manager/src/components/HelpIcon/HelpIcon.tsx
packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
packages/manager/src/components/TextField.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
packages/manager/src/features/Images/ImageSelect.tsx
packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

Make help icons consistent throughout the app and remove styles that are no longer needed. 
Help icons should generally be:
- Gray (#888f91) by default and blue (#3683dc) on hover
- 20x20px
**Note:** Found a "(required)" regression in `MultipleIPInput` so added a required prop there to make it consistent.
Check the help icons throughout the app.

M3-5448: Global changes to help icon

---

packages/api-v4/src/volumes/types.ts
packages/manager/src/__data__/volumes.ts
packages/manager/src/factories/volume.ts
packages/manager/src/features/Volumes/RenderVolumeData.tsx
packages/manager/src/features/Volumes/VolumeTableRow.test.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/mocks/serverHandlers.ts

- Add `hardware_type` to `Volume` interface
- Update mocks, fix TS errors
- Display an NVMe chip on the Volumes landing page to the right of the labels of volumes that have a `hardware_type` of `nvme`
I updated the mocks, so you can turn on the MSW and see two mocked volumes with the NVMe chip.

M3-5482: Add NVMe chip for NVMe volumes

---

.github/workflows/e2e.yml
packages/manager/cypress/integration/linodes/smoke-linode-landing-table.spec.ts
packages/manager/cypress/integration/objectStorage/access-keys.spec.ts
packages/manager/cypress/integration/objectStorage/buckets.spec.ts

The previous workflow PR added a security measure to only run for PR's with a label. I failed to realize that would also block the runs on pushes to staging and develop. This should correct that.  
There are also a couple of test fixes/updates. One to run all linode landing tests instead of just one, another for an access keys update, and one more to account for EU agreement in buckets test.
For workflow: 
We won't know for sure that it is working until another merge to develop happens and instead of being blocked, the tests run. Tests should also only be run in checks for PRs with the e2e label. 
- `yarn cy:e2e -s ./cypress/integration/linodes/smoke-linode-landing-table.spec.ts` in another
- …

E2e test updates and workflow update

---

packages/manager/src/features/Domains/DomainRecords.tsx

Truncate TXT Record value and fix overflowing bug
Before:
After:
- Go to `domains/<domain_id>`
- Add/Edit a TXT Record value to be at least 439 characters
- The value should be truncated with an ellipsis and should not overflow into the next cell

M3-5322: Fix formatting of long strings in Domains TXT Record

---

packages/api-v4/src/account/types.ts
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
packages/manager/src/mocks/serverHandlers.ts

Display upgrade volumes banner on a Linode's details page if upgradeable volumes are attached
Set `numUpgradeableVolumes` to 1 or 1+, turn on the MSW, and go to a Linode's details page:

M3-5485: Upgrade volumes banner on Linode details

---

packages/api-v4/src/kubernetes/nodePools.ts
packages/api-v4/src/kubernetes/types.ts
packages/manager/src/__data__/nodePools.ts
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/featureFlags.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.test.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
packages/manager/src/features/Kubernetes/kubeUtils.test.ts
packages/manager/src/features/Kubernetes/types.ts
packages/validation/src/kubernetes.schema.ts

Adds support for Autoscaling a Node Pool on a Kubernetes Cluster's summary page
Go to `kubernetes/clusters/<cluser_id>/summary`, ensure the `autoscaler` feature flag is on
- You should see an `Autoscale Pool` button before the Resize Pool button
- If the Autoscaler is on, you should see min/max values next to the autoscale pool button
- If the Autoscaler is off, you should not see min/max values next to the autoscale pool button
- Clicking on Autoscale Pool should display a dialog
- The Save Changes button should be disabled until there has been a change in the form and there are no errors
- If Autoscaler is off, the Min/Max input fields should be disabled
- If the Minimum value is not between 1-99 or greater than the Maximum value, there should be an error displayed under the input field …

M3-5452: Add support for Autoscaling Node Pools

---

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AutoscalePoolDialog.tsx

- Fix alignment of the resize button
- Smaller warning notice text
- Go to `kubernetes/clusters/<cluster_id>/summary`
- Click on Autoscale Pool and set the max lower than the current max, you should see the warning notice

Autoscaler UI fixes

---

packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/mocks/serverHandlers.ts

If a user has any notifications for volumes scheduled for migration (`volume_migration_scheduled`), display one notification in the drawer regarding volumes scheduled for migration (thus, if there were multiple volumes scheduled for migration, their individual notifications would be filtered out in favor of our customized, condensed one to prevent potential flooding of the Notifications drawer).
Turn on the MSW --> check the Notifications drawer --> you should observe a single condensed notification regarding volumes eligible for upgrade to NVMe ("condensed" because every attached volume scheduled for upgrade has a notification come through for it, simulated here by there being 2 in the mocks, but we want only a single representative one in the Notification drawer so as to not clutter it)

M3-5488: Add Notification in drawer when a user has Volumes scheduled for migration

---

.github/workflows/ci.yml
.gitignore
.npmignore
packages/api-v4/package.json
packages/api-v4/webpack.node.config.js
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
packages/validation/package.json

1. Adds `files` key to validation package (which determines what gets published to NPM)
2. Changes `main` key in `package.json` (which dictates where things are imported from).
* As of right now `import { blah } from '@linode/api-v4'` by default imports things from `lib/index.js` which is unminified code, unlike `./index.js` which is minified.
* In other words, importing from `./index.js` is impossible right now
* Didn't update `types` key because it's fine as is
1. Run all projects locally
2. Make changes to `api-v4`
3. Ensure manager still hot reloads with changes
-------
1. Also ensure imports from `@linode/api-v4/lib/whatever` still works
-------
1. Run `cd ./packages/validation && npm publish --dry-run` to see what files are getting published to NPM. Comparing this branch to dev, …

Updates Package.json

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx

When a user goes through the Volume upgrade flow successfully, the dismissible "A Volume attached to this Linode ..." banner should disappear automatically.
This PR re-requests notifications upon a successful addition to the migration queue to ensure this occurs.

M3-5555: Re-request notifications after successful enqueueing of volumes

---

packages/manager/src/store/volume/volume.events.ts

Handles for the `volume_migrate` event type in `volume.events.ts`. Grab all volumes after `volume_migrate` starts and finishes.
Once the volume migration is completed, you should see the chip next to the volume label on the Volumes landing page change from "Upgrade to NVMe" to "NVMe" without having to refresh the page.
When https://github.com/linode/manager/pull/8002 is merged, after pushing a volume into the queue, you should see the chip change from "Upgrade to NVMe" to "Upgrade Pending," and then from "Upgrade Pending" to "NVMe" once the volume migration is completed.

M3-5556: Refresh Redux upon volume_migrate starting & finishing

---

packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/AddNodePoolDrawer/AddNodePoolDrawer.tsx

- Right aligns the `Add Pool` button in the `Add Node Pool` drawer for a Kubernetes Cluster
- Go to any Kubernetes Cluster
- Click `Add Pool`
- Try many different Node Pool configurations and screen sizes and ensure the `Add Pool` button placement is good

M3-5515: Fix button placement and improved spacing in Add Node Pool Drawer

---

packages/manager/cypress/integration/account/google-pay.spec.ts

https://github.com/linode/manager/pull/8009 removed the google pay notice banner, this PR removes the banner test
- `yarn cy:e2e -s ./cypress/integration/account/google-pay.spec.ts` in another
tests should pass

E2E: Update Google Pay test

---

packages/manager/src/components/PaginationFooter/PaginationFooter.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceLanding.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceTable.test.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx

- Ensure the Status indicator and text are properly aligned vertically
- Same issue as #7983
- Hide Pagination controls if there are not >25 results
- Move the `Download CSV` link outside of the table to the bottom right below it
- Still hides link when accordion is collapsed 
- Go to `/account/maintenance` in Cloud Manager
- Test the three changes listed above
- Double check functionality of tables and accordians

M3-5553: Revisions to Account Maintenance Page for Volumes

---

packages/manager/src/features/Backups/BackupDrawer.tsx

- Fixes button order in the **_Enable All Backups_** drawer
- Go to `/account/settings` on a non-managed account
- Click `enable now` to open the **_Enable All Backups_** drawer
- Make sure buttons are right aligned and the primary action button is on the right side

M3-5559: Button alignment in the Enable All Backups drawer

---

packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx
packages/manager/src/components/Drawer/Drawer.tsx
packages/manager/src/components/InformationDialog/InformationDialog.tsx
packages/manager/src/components/core/RootRef.ts
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Managed/Contacts/Contacts.tsx
packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx
packages/manager/src/features/TheApplicationIsOnFire.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeDisks.tsx

Keeping the developer console clean is crucial to debugging and developing Cloud Manager. Putting this PR up in hopes to make the dev console cleaner so it can help us be more productive using it. 
- We were seeing a lot of deprecation errors in the console due to Material UI depreciating the `disableBackdropClick` prop. 
- This PR implements a fix that is recommended by MUI to fix this deprecation warning.
- Replaced `justify` with `justifyContent` because `justify` prop is deprecated by MUI.
- Replace `RootRef`s with regular `refs` because MUI should now forward that properly and `RootRef`s have also been deprecated.
- Make sure all Modals, Dialogs, and Drawers are only dismissable by the `esc` key or the close buttons.
- Ensure no Modals, Dialogs, or Drawers close by clicking out of …

Fixed general console errors due to Material UI deprecation warnings

---

packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx

Changes the location the link in the `HAClusterCheckbox` points to for information of HA Clusters in the guides.
The link in the checkout summary that points to the HA Clusters guide should bring the user to the HA Cluster guide.

M3-5563: Update location of HA Cluster guide link

---

packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Devices/FirewallLinodesLanding.tsx

- Switched the order of buttons in the Add Linode to Firewall drawer so the primary button is on the right side
- Also made the action button on `/firewalls/{id}/linodes` `primary` instead of `secondary`
- Go to `/firewalls/{id}/linodes`
- Check button style
- Open the drawer and check button order

M3-5565: Fix button order in the Add Linode to Firewall drawer

---

packages/manager/src/components/DocsLink/DocsLink.tsx
packages/manager/src/components/EntityHeader/EntityHeader.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx
packages/manager/src/utilities/ga.ts

- Adds a label to the existing Google Analytics event which allows us to specify where the link click was initiated. 
- The goal was to see how often the Docs link was clicked on Linode Detail and Linode Landing. In a way, this was already recorded (we recorded how often the [destination link](https://www.linode.com/docs/platform/billing-and-Support/linode-Beginners-Guide/
) was visited) (the links on Linode Landing and Linode Detail are the same link), but we didn't know where the click was initiated. 
Currently unsure if I can test this in a dev environment.

M3-5524 & M3-5523: Contextual help with Google Analytics on Docs Links

---

packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx
packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx

This changes `linode.com/speedtest` to `linode.com/speed-test` to avoid an unnecessary redirect.

Update speed test link to avoid redirect

---

packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx

The inline menu actions on the LinodeLanding page were too short. Removing this unnecessary div allows the button to fill the height of the row.
1. Open manager in Safari.
2. Navigate to the LinodesLanding page.
3. Ensure the `Power Off`, `Reboot`, and kabob menu should fill the row vertically when hovered over.
4. Repeat steps 1 through 3 in Chrome and Firefox.

M3-5537: Table row height too high in Safari

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddCreditCardForm.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx
packages/manager/src/features/Billing/Providers/GooglePay.ts

- Disabled the `Add Credit Card` button until the user enters all required credit card data
- Any new payment method becomes the default payment method (Users can change default payment method on the Billing page)
- In the Add Payment Method Drawer, the check box to make a credit card default is removed
- A new payment method is added to the bottom of the list of payment methods upon add
- Improves spacing in the Add Payment Method Drawer
- Go to `/account/billing/add-payment-method`
- Ensure all items listed above are true

M3-5575: Updates to Payment Method Logic and UI

---

packages/api-v4/src/networking/networking.ts
packages/manager/src/factories/linodes.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.test.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/networking.ts

Add functionality to move/swap IPv6 Ranges in the IP Transfer Modal
- On the dev env, go to `linodes/<linode_id>/networking`
- Pick a Linode that already has an IPv6 Range, or add an IPv6 Range to a Linode (reach out for more details)
- Pick a second Linode that has more than one public IPv4 address, or add an additional IPv4 address to a Linode (reach out for more details)
- Click on the `IP Transfer` button to open up the transfer modal
- You should see the IPv6 Range as a row in the modal and should be able to move or swap it to another Linode
- To swap it with an IPv4 address, the Linode you're swapping with must have at least one public IP after assignment.
- To swap it with another IPv6 range, your account needs to be able to have more than 1 max allowed IPv6 range, otherwise you'll …

M3-5530: Add IPv6 ranges to IP Transfer modal

---

packages/manager/src/eventMessageGenerator.ts

Before:
After:
Open to changing the language, perhaps removing the "on your account" phrase.
- Add an IPv6 range
- Delete it
- Check the Notifications drawer

M3-5535: Handle IPv6 events language

---

packages/api-v4/src/networking/networking.ts
packages/api-v4/src/networking/types.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx
packages/manager/src/mocks/serverHandlers.ts

Updates the types and requests to support the new IPv6 functionality, updates the mocks accordingly, and makes a few changes in the "Add an IP Address" drawer:
- Changes IPv4 dropdown to radio buttons
- Adds IPv6 radio buttons
From the "Network" tab of a Linode Detail page, click "Add an IP Address" and confirm that no functionality has been lost for allocating IPv4 addresses and that you can now allocate IPv6 addresses successfully.

M3-5529: Update "Add an IP Address" drawer and provide for ability to add IPv6 ranges in it

---

packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings/NodeBalancerSettings.tsx

- Made NodeBalancer settings look more like Linode settings
- Adds the ability to delete a NodeBalancer from `/nodebalancers/{id}/settings`
- Previously, this was only possible from the NodeBalancer Landing Table
- Also fixes a bug where the Breadcrumb label would not update when the label was changed on the settings tab
- Try deleting a NodeBalancer from `/nodebalancers/{id}/settings`
- Ensure no other functionality was broken as a result of this work

M3-5560: Add Delete Button to NodeBalancer Detail in Settings

---

packages/manager/src/utilities/unitConversions.test.ts
packages/manager/src/utilities/unitConversions.ts

Removes use of `Math.ceiling` from `convertMegabytesTo` function. This use of `Math.ceiling` causing only increases in the magnitude on the order of the nearest whole storage unit to be shown to the user. Adds tests for `convertMegabytesTo` function.
Ensure that when a Node Balancer has transferred a quantity of bytes that should be represented with a string containing a number with two decimal places of precision that the representation is as accurate as possible. For example if a Node Balancer has transfered `1.432342 GB` of data then that should be represented as `1.43 GB` and not as `1.00 GB` or `2.00 GB`.
yarn test packages/manager/src/utilities/unitConversions.test.ts

M3-4983: Transferred column on NodeBalancer page not showing the correct amount

---

packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts

This PR makes the line graph's axis label color match the one used for table headers and prevents the y-axis labels from being cutoff if there are more than 3 digits.
1. Go to any Linode Detail view
2. Go to the "Analytics" tab if it's not on there already
3. Scroll down and inspect the font color
4. The "Disk IO" graph will usually have 3 digits in the y-axis but in case there isn't, make a new Linode

M3-5492 & M3-5547: Axis label UI refinements

---

packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
packages/manager/src/store/authentication/authentication.helpers.ts
packages/manager/src/utilities/storage.ts

When a StackScript is edited without being saved the data stored in local storage now includes the `updated` field. Before the data from local storage is loaded its `updated` is compared to the `updated` field from the response. If response has been updated since the edits in the local storage then the local storage data is not loaded.
1. Open a StackScript in two different browsers.
2. In browser A edit the StackScript without saving the changes.
3. In browser A navigate away from the StackScript.
4. In browser B edit the StackScript in a different way and save the changes.
5. In browser A navigate to the same StackScript.
6. In browser A click the `edit` button for the StackScript.
7. The prefilled text in the StackScript should reflect the changes from browser B.

M3-5059: Persisting when editing stackscripts on separate computers

---

packages/api-v4/src/linodes/linodes.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/BareMetalRescue.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDescription.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx
packages/manager/src/queries/linodeFirewalls.ts

Linodes booted into Rescue Mode no longer have firewall rules enabled.
This PR adds a warning notice in the Rescue dialog that says, `Cloud Firewall rules are not enabled when booting into Rescue Mode.` if the Linode is assigned to a firewall.
To facilitate this, a new method `getLinodeFirewalls` has been added to the JS Client, along with a new RQ query `useLinodeFirewalls`.
There are 3 cases. Only case #1 should display the notice; the other two cases should look the same as they do in prod.
1. A Linode assigned to a firewall
2. A Linode not assigned to a firewall
3. A Bare Metal instance (this PR modifies the logic for `BareMetalRescue.tsx` and `RescueDescription.tsx`)
Please also check React Query to confirm that the data is being stored and handled as expected.

M3-5567: Add warning when booting into Rescue Mode that Cloud Firewall will not be enabled

---

packages/manager/src/components/InlineMenuAction/InlineMenuAction.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx

- Fixes two **massive** console errors in hopes to improve usability of dev tools
- One fix required a useless fragment which is unfortunate, but usability and styles should remain unchanged
This first error shows when you are on `/volumes` and you have >= 1 volume
The second error shows on `/account/billing` and many other places in Cloud Manager
- Ensure all `InlineMenuAction` work as expected and have no visual regressions

Fix Console Warnings

---

packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx
packages/manager/src/features/Volumes/types.ts

In `VolumeTableRow.tsx`, the approach of using `notifications.some()` comes with some performance drawbacks since the array is looped through for every row, on every render.
This PR lifts that logic to `VolumesLanding.tsx` and uses a `.reduce()` to add booleans on the volume objects.
Create a few HDD volumes (attached and unattached) and have them go through the full NVMe migration flow. The chips should show up just as they have been with no regressions.

M3-5551: Refactor logic for displaying NVMe-related chips

---

packages/manager/src/themeFactory.ts

Previously "secondary" Buttons had a border-radius of 4px (coming from MUI) since the border-radius was not overwritten for that variant. 
This moves the `borderRadius: 1` specification to the `root` of the MUIButton class so it applies to all variants.
**To test:** 
- look through the app to make sure there are visual regressions with buttons
- find a secondary button (e.g. "Add Linode to Firewall" drawer) and compare the border-radius to production (seen when you click and hold the button).

Styling: border-radius of 1px for all button variants

---

packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx
packages/manager/src/utilities/ga.ts

- Logs an event when the user clicks
- The `Docs` button in the Object Storage Landing header
- The `Learn more about storage options...` docs link in the Object Storage empty state
Click one of the buttons described above and check the console to make sure Google Analytics logs the event. (You may not see this is the console if you have an ad blocker or use [Pi-hole](https://pi-hole.net). Google Analytics may be blocked preventing this from loading)

M3-5522: Object Storage Landing contextual help

---

packages/manager/src/components/Notice/Notice.tsx
packages/manager/src/features/Account/AutoBackups.tsx

Removes the redundant header on the account settings backup auto enrollment section. There was also a tooltip that would show up to inform managed users that they are already auto enrolled in backups. I removed the tooltip and replaced it with a success notice.
1. Open the Account Settings page as managed user.
2. There should be no redundant header in the back up auto enrollment section.
3. There should be a success notice informing you that you are already enrolled in auto backups.
4. Open the Account Settings page as an unmanaged user.
5. There should be no redundant header in the back up auto enrollment section.

M3-5549: Backup Auto Enrollment – Remove redundant head

---

packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx

Fixes an issue where we are passing the wrong param to associate with an LKE cluster when creating tickets.
Create a ticket with the old code and try associating with a cluster, it will fail. Try with this new code, it will associate with the cluster.

bug: fix support ticket entity param for LKE clusters

---

packages/manager/src/store/selectors/getSearchEntities.ts

I noticed we were displaying the raw `domain.type` in search results (in the search bar and on the search landing page). This PR overrides that to ensure we display `"primary" | "secondary"` instead of `"master" | "slave"` which is a change we’ve made everywhere else in the app.
Have a primary and a secondary Domain on your account and search for them in the search bar. Production will display the type as being either 'master' or 'slave', while in this PR they should be displayed as 'primary' or 'secondary'.

Override Domain type display in search results

---

packages/manager/src/components/Chip.stories.mdx
packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx

- Adds `<Chip />` in Storybook with `mdx`
- Minor clean up in `StackScript.tsx`
[https://m3-5600-storybook-for-chips.manager-ec2.pages.dev](https://m3-5600-storybook-for-chips.manager-ec2.pages.dev/?path=/docs/ui-elements-chips--chip#chips)
- `yarn storybook`
- Test the `Chips` Story in Storybook

M3-5600: Chips in Storybook

---

packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx
packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx

-------
Adds a menu item to the Create button menu that directs the user to the database create page.
This feature is feature flagged behind the `databases` flag.
1. Open cloud to any page.
2. Click the Create button in the top nav.
3. A new menu item should be there for Database.
- The new menu item should have a title of Database.
- The new menu item should have a summary of:
`High-performance database clusters`
- The new menu item should have the Database icon.
4. Click the new menu item.
5. Ensure the page you are directed to is the Database create page.

DBAAS1-77: Add Database to the Create button

---

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/HACheckbox.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeClusterDialog.tsx

Add a beta badge for the HA Upgrade dialog and to the HA Checkbox in the Kubernetes Checkout Bar.
1. Navigate to Kubernetes page.
2. Open Kubernetes creation.
3. Ensure that next to the `Enable HA Cluster Plane` label there is a `BETA` badge.
4. Navigate back to Kubernetes Landing page.
5. Open an existing non-HA enabled Cluster.
6. Click the `Upgrade to HA` button.
7. Ensure that next to the `Enable HA Cluster Plane` label there is a `BETA` badge.

M3-5631: Add beta badge to HA Upgrade and HA Checkbox

---

packages/manager/src/features/Account/EnableObjectStorage.tsx

Removes instructions for clearing out and removing buckets from Object Storage cancellation copy, as this now happens automatically on the backend.
Run through Object Storage cancellation flow and verify copy is updated to not mention clearing out and removing buckets

M3-5636: Updates Object Storage cancellation copy

---

packages/manager/src/features/Domains/DomainZoneImportDrawer.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx

When searching for a secondary domain and clicking on it, Cloud Manager would freeze and call the useEffect many many times in an infinite loop
https://user-images.githubusercontent.com/6440455/146985697-0613b6f5-00fc-47b3-be43-66832c9801ff.mov
The fix was removing a redundant `useEffect` that called same function as the other `useEffect`
I also fixed the button order in the `Import a Zone` drawer
- Test editing a primary and secondary domain
- Test editing from search and from the landing table
- Make sure that what happens in the video above does not happen anymore

M3-5638: Fix Editing a Secondary Domain Freezing Cloud Manager

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts

This PR fixes some customers unable to edit Firewall rules
- User was able to click `Save Changes` but no change occurred when editing a firewall rule.
- An API validation error occurred but was not surfaced to the frontend (only viewable in devtools)
- This was caused by what we suppose to be a very old firewall rule that had **many** rules with an empty IPv6 array that the API no longer accepts when you make a PUT
- Ensure we don't pass any empty IPv4 or IPv6 arrays in the PUT request
- I was unable to reproduce on my personal account. Refer to the internal ticket to see which Firewall and Account had this issue
- Test editing a firewall rule in various ways
- Test creating a firewall rule

M3-5632: Fixed Customer Unable to Edit Cloud Firewall Rules

---

packages/manager/src/features/Databases/DatabaseDetail/index.tsx

If a user tries to navigate to a URL that doesn't exist which uses the `SafeTabPanel`, the expected behavior is to redirect them to the content on the default tab. This fixes the issue of the URL not being updated when this happens for DBaaS.
Will release another PR that fixes this for other pages.
- Go to `/databases/[id]`
- Navigate to a different tab
- Change the URL to something else (ie. `/databases/[id]/test`)
- The URL should now be updated to `/databases/[id]`

Update URL after redirecting from a URL that doesn't exist

---

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx

Fixes an unaligned status icon in the Kubernetes Node Table. This recession was caused by linode#7763. An extra wrapping Grid caused the centering to not happen. I was able to remove the extra styles and wrapping Grid. 
I removed the `whiteSpace: 'nowrap'` because in my testing, it had no effect on the UI. 
Before
After
- Navigate to any `/kubernetes/clusters/{id}/summary`
- Check the status icon of a node at all viewport sizes
- Compare this PR build to https://cloud.linode.com

M3-5647: Fix Icon Alignment for Kubernetes Nodes

---

packages/manager/src/features/OneClickApps/FakeSpec.ts
packages/manager/src/features/OneClickApps/LinkSection.tsx

This PR is to clean up FakeSpec.ts. Long overdue cleanup of doc URLs, clean up formatting, remove "One Click App" references, align all apps, and put them in alphabetical order. 
Click the info tabs on each Marketplace app and review. 
One Note: OpenLiteSpeed Wordpress URL will be the only doc link that 404s. This is set to be update tomorrow via the Docs team.

Marketplace: Document link updates an cleanup

---

packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx

This PR will make the state/province a dropdown field if the US or Canada is selected as the country. If the previous input does not match any of the options, keep that field as is until the user goes to modify their state/province. Additionally, the country and state/province fields are now required and the form layout has been changed to better match the sign up form. 
**Remaining tasks:**
Switch between countries as you input valid and invalid values for the US/Canada and other countries.

M3-5645: State/Province dropdown

---

packages/manager/src/constants.ts
packages/manager/src/dev-tools/dev-tools.tsx
packages/manager/src/dev-tools/load.ts
packages/manager/src/mocks/testBrowser.ts

Allows us to specify an environment variable that will explicitly enable the MSW in the dev tools. 
Specifying `REACT_APP_ENABLE_DEV_TOOLS` will explicitly enable the data mocking tools in the dev tools and show the dev tools in PR builds unless explicitly disabled. 
For now, we can't test this because the internal ticket is not yet merged. 
If you **really** want to test this, you should run your own production build with `yarn build` with the normal Cloud Manager secrets and `REACT_APP_ENABLE_DEV_TOOLS=true`. Host this on your own web server and see if mock data tools are showing up and working.
I did the steps above and confirmed that with `REACT_APP_ENABLE_DEV_TOOLS=true`, we should have mock data when that env variable is specified. Please review this PR for nomenclature and do your …

M3-5651: Enable Mock Data in PR Builds

---

packages/api-v4/src/databases/types.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx

- Adds `version` to the `Database` type
- Uses the same `queryClient` for all `DatabaseCreate` unit tests
- Makes the Database factory use the same type for every database (fixes the no cluster config issue)
- Make sure the type change I made is accurate
- make sure unit tests pass
- Make sure the change to the database factory type makes logical sense and fixes the empty cluster config

DBaaS Fixes and Updates

---

packages/manager/cypress/integration/account/billing-contact.spec.ts
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx

- Updates a Cypress test to match a change made by #8111 
- This test is kind of weird right now because it runs the same test but Cloud Manager has two different region / country selections right now that are toggled with a feature flag. I updated the test so it should pass if the flag is both on or off.
- Is the change from `ZIP / Postal Code` to `Postal Code` desired? (I have no problem with it, just asking the question to be 100% sure)
- If the e2e GitHub Actions passed ✅, we should be good!
- If you want to run the test locally, run `yarn cy:debug` and run the test from Cypress's GUI

Update Cypress Test for Editing Account Information

---

packages/api-v4/src/databases/types.ts
packages/manager/src/components/TableSortCell/TableSortCell.tsx
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx

- Changes the title `Databases` ➡️ `Database Clusters`
- Updates the create button `Create Database` ➡️ `Create Database Cluster`
- Fixes the table shifting when changing the `order by` column
- Fixed this by making the inactive sorter icon have the same margin as the active sorter icon
- Change how the version is determined in the table row
- Updates the possible Database statuses and the respective status icons
- Verify all of the changes described above are accurate
- You should be able to use the internal PR build to test all of this
- Test with the MSW and optionally the alpha environment

M3-5668: DBaaS Landing Page Refinements

---

packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx

Without the mocks on, if you try removing the last IP that is allow listed on a cluster, an error message will be returned. It gets surfaced in the confirmation modal but not in the drawer. The API is working on some changes that will render this a non-issue, feel free to reach out for further details.

M3-5671: Tweaks to Access Controls

---

packages/api-v4/src/databases/types.ts
packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
packages/manager/src/components/TextField.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/queries/databases.ts
packages/manager/src/utilities/formatStorageUnits.ts
packages/validation/src/databases.schema.ts

Addresses Create Database feedback
1. At mobile screen size breadcrumb needs left margin
4. Add space between top of helper text and baseline of headers Number of Nodes and Access Controls to 12 px (currently 8 px)
5. Move tooltip about limits of selecting Linode 1 GB plan to inline with the text block
6. Reduce size of pricing text to 12 px (currently 14 px)
7. Add (required) to field label
8. Button to be active by default
9. Remove references to IP Ranges from "Add Access Control" copy
10. Enable SSL mode by default
11. Add nanode to DatabaseTypeClass type
12. Update is1GbPlan variable logic so that selecting the 1 GB nanode plan disables the 3 Node option (logic is currently based on memory but we're getting null back from the api rn)
15. remove 'DBAAS MYSQL - ' from plan labels
16. …

M3 5665 - Create page refinement

---

packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx

Updates the NVMe Block Storage banner copy in the Volume Create form and adds link to rollout status blog
Go to `volumes/create` and check the banner/link

M3-5630: Update NVMe Block Storage copy

---

packages/api-v4/src/databases/databases.ts

Adjust the type of `typeSlug` that is passed to the `getDatabaseType` method to a string so it is correct.

Revise parameter type for getDatabaseType() method

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx

Changes the title of the Root Password Reset section of `DatabaseSettings` component to Reset Root Password. This better informs the user what the section is for and what action will happen when the button is clicked.
1. Navigate to a database summary
2. Click on the Settings tag
3. Ensure the title and button text for the Reset Root Password section match

Reset root password heading cleanup

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx

If the user previously had a region that is in options provided, display the region as the placeholder until they try to modify in which case the user will have to choose one of the provided options in the dropdown.
1. Make sure the flag is turned off
2. Set the country as the "United States"
3. Type in a random word as the state in the input field
4. Turn the flag on
5. The state input field should now be a dropdown with the previous input displayed as the placeholder

hotfix: Region dropdown not showing previous value

---

packages/manager/src/constants.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

This uses a constant in lieu of the response from the `/credentials` endpoint, meaning we no longer need to mask the username.
Test success/loading/error scenarios and check the placement of the button and loading spinner.

Do not mask DB username

---

packages/api-v4/src/databases/types.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/validation/src/databases.schema.ts

Replace instances of `semi-synch` with `semi_synch` per imminent API hotfix.
Once the hotfix has been merged, ensure that everything in the DBaaS flow still functions properly.

DBaaS1-205: Replace instances of 'semi-synch' with 'semi_synch'

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx

The API returns the disk in MB so use a util function to convert the value to GB.
Navigate to a database cluster that uses the `Nanode 1 GB` plan and the storage should be `25 GB`.

M3-5689: Fix storage unit for DBaaS

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

- Displays a databases's secondary host if available from the API
- A tooltip is included to give the user context about what the secondary host is to be used for
- Test with the MSW enabled (the API is not returning secondary hosts yet)
- Go to `/databases/mysql/0` and ensure you see `private network host` with a `HelpIcon` in the `Connection Details`

M3-5683: Add Secondary Host and Tooltip

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupTableRow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx

- Added **relative date** column to the backups table
- Updated **copy** to explain that **backups are retained for 7 days**
- When user successfully initializes a restore, we toast a success message, and redirect them to the summary page
- The user will see the status `Restoring` immediately they start a restore successfully. This may not be immediately updating until #8131 is merged. 
- Try restoring a database form a backup. Ensure the flow as described above is accurate
- Check copy change for spelling and grammar
- Check that the relative date in the table works and looks good

M3-5676: Database Backups Refinements

---

packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.test.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx

- When you go to remove an IP address, confirm there is a button loading state, and that errors display as expected
- Check that copy matches what is specified in ticket
- Confirm that CIDR notation (`/32`) is accepted and enforced on IPs in the drawer

M3-5675: Post-demo Refinements to Access Controls

---

packages/api-v4/src/databases/types.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/validation/src/databases.schema.ts

The API has revised the shapes of some data points:
1. The database types will no longer have `addons` or `price` properties; they are being replaced by `cluster_size` which is an array here consisting of a `quantity` property and a `price` property.
2. `failover_count` is being replaced by `cluster_size` (different from the above), which is a number (either 1 or 3) here. 
`yarn test DatabaseCreate`
- Test things mentioned in the description
- The database create page should no longer crash
- All the pricing comes from the API now, check that the prices displayed match the API and check the POST request
- 3 Node option for Nanodes are no longer disabled

M3-5694: Changes to types, schema, and Database components to reflect cluster_size

---

packages/api-v4/src/databases/types.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

The `GET /databases/mysql/instances/{id}/ssl` endpoint now just returns `ca_certificate`
Go to the summary tab of a database cluster and try to download the CA certificate, you should no longer see an error toast

Update SSLFields type and Download CA Certficate button

---

packages/api-v4/src/account/types.ts
packages/manager/src/MainContent.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/index.tsx
packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx

This PR changes the `flags.databases` checks to make use of the `isFeatureEnabled` function, taking into account the user's capabilities. **When we go to beta the LD flag should be off.** (Otherwise DBaaS would be shown to everyone, not just beta participants).
To test, check all combos and make sure that DBaaS works (or doesn't work) correctly:
- LD flag on, account capability off **(DBaaS should work)**
- LD flag on, account capability on **(DBaaS should work)**
- LD flag off, account capability off **(DBaaS should NOT work)**
- LD flag off, account capability on **(DBaaS should work – this is the situation for beta)**

Observe account.capabilities to enable DBaaS

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/queries/databases.ts

Creates a query for resetting a database's credentials. The query invalidates and removes the cached response from the get credentials query.
1. Navigate to a database cluster's details page
2. Click the show button for the root database password
3. Take note of the current root database password
4. Navigate to the settings tab
5. Click the Reset Root Password button
6. Click the confirm button in the confirmation modal
7. Navigate back to the summary tab
8. Click the show button for the root database password
9. Ensure that the new root password is different from the one from step 3.

M3-5679: Querify database credentials reset

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/mocks/serverHandlers.ts

Disables the show button in a database cluster's connection details if the database is still provisioning since it will just result in an error
Go to the summary tab of a database cluster. To see the disabled button state, turn on the MSW

M3-5701: Disable show button if database cluster is provisioning

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Adds a copy tooltip to the password (after user clicks show), host, and private host fields
Check the summary page of a Database Cluster

Add copy tooltip to password and hosts in Database Connection Details

---

packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx

- Standardizes the capitalization for "Database Cluster"
- Fixes the double border on the last row of IP addresses for Access Controls
- Removes the line break from the Delete Cluster copy
- Add "Root" to the primary action for the Reset Root Password modal
- Check all the copy references to "Database Cluster" and check for capitalization
- Check the other changes on the Settings tab

DBaaS UI fixes

---

packages/manager/src/features/Billing/BillingDetail.test.tsx
packages/manager/src/features/Billing/BillingDetail.tsx
packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx

Add the users's country to the panel and fix the alignment for Tax ID (M3-5640).
**Before**
**After**
Go to `/account/billing`

Display country in the Billing Contact panel

---

packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx

Got an update to include the Armed Forces regions (which was previously hidden).
- Go to `/account/billing/edit` and make sure that the country is set to "United States"
- If you click on the "State" dropdown, the Armed Forces regions should now show up at the very end of the list

Un-exclude certain regions for US in the billing region dropdown

---

packages/manager/src/queries/databases.ts

- When a Database goes from `provisioning` to `success`, the host fields also get populated. We need to refetch to pick those up
- Test event polling transitioning a Database from `provisioning` to `success`

DBaaS React Query Minor Change

---

packages/manager/cypress/integration/stackscripts/stackscripts.spec.ts

This fixes the failing StackScript Cypress test. The test was failing because it attempts to use a target image (Alpine 3.10) which no longer exists. I just updated to Alpine 3.15, which appears to be the newest version available, and I'm now seeing the test succeed.
You can reproduce the issue by checking out `develop` and running `yarn up` followed by `yarn cy:debug`. Once the Cypress window opens, select `stackscripts.spec.ts` -- you should observe a failure when it attempts to select Alpine 3.10 as the target image for the Stack Script.
Check out this PR and run the same steps to observe that the test no longer fails.

Fix StackScript Broken Cypress Test

---

docs/development-guide/05-fetching-data.md

- Adds documentation to explain when to use a (React Query) mutation vs. using the `api-v4` library directly
- Check spelling, gramar, and general docs updates

M3-5657: Data Fetching Docs for React Query vs api-v4

---

.github/workflows/README.md
.github/workflows/e2e_pr.yml

Removes the check for the `e2e` label on PRs before running the Cypress end-to-end tests. Workflows already require approval to run for PRs authored by outside contributors, so the thought is that the check for the `e2e` label isn't really necessary from a security perspective.
We're limited in our ability to test this before merging. If the code is merged, I'll open two PRs -- one with this account, and one with my personal account -- to make sure that:
* PRs opened by team members have their E2E tests run automatically
* PRs opened by outside contributors require approval before their E2E tests run
I'll revert these changes if we do not observe the above behavior.
* :white_check_mark: This …

M3-5662 Remove check for E2E label when running tests against PRs

---

packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanelContent.tsx

Adds success & error toasts when making a StackScript public.
Pointing at the dev environment, make a StackScript. Then from the "Account StackScripts" tab, choose "Make StackScript Public" from the StackScript's action menu. It should go through successfully and you should see a success toast. To test the error toast, block requests to `*stackscripts*` and then try to make a StackScript public. You should see an error toast.

M3-4768: Add toasts when making a StackScript public

---

packages/manager/package.json

Trying to stick to the Storybook theme this sprint 😄 
This tweak prevents Storybook stories from being included in Jest's code coverage report. At the moment, stories ending in `.tsx` appear in the code coverage report. Since stories have no code coverage, they make it appear at a glance that our components have less coverage than they actually do.
From the root of the repository:
```bash
yarn test --coverage
```
Once tests finish running, navigate to `packages/manager/coverage/lcov-report/` and open `index.html` in your browser. Observe that stories ending in `.stories.tsx` are included in the code coverage report (or, if you've checked out this PR, are excluded).
The `Accordion` component is a …

Exclude Storybook stories from Jest code coverage report

---

packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/ConfigRow.tsx

- Fixes alignment issues in the Linode Configurations table
- Create a Linode and attach two volumes to it
- Visit `http://localhost:3000/linodes/{id}/configurations`
- Create many different types of configurations and ensure content remains vertically centered in each row

M3-5583: Fixed Linode Configurations Table Misalignment

---

packages/manager/src/features/Account/AutoBackups.tsx

Improves the consistency of the styling for the "enable now" link that is found in the "Backup Auto Enrollment" section of the Account Settings page.
Navigate to `/account/settings` and confirm that the "enable now" link style is consistent with other links throughout Cloud Manager.

M3-5732: Improve styling consistency for backup auto enrollment

---

packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx

- Removes the `$` shown in the screenshot
- I let this slip through the cracks when I did some refactoring and added Firewall and Database support to the support ticket form
- #8122
- Go to `/support/tickets`
- Click the `Open New Ticket` button
- Select an entity that you have none of on your account
- Ensure the empty message does not include a `$`
- Text should read `You don't have any Domains on your account.`, not `You don't have any $Domains on your account.`

Fixed Support Ticket Entity Selection Extra Character

---

README.md

If you go to our [main repo page](https://github.com/linode/manager), the logo currently doesn't render (plus, the image that's supposed to render is the old logo):
This PR updates the logo and fixes things so that the logo renders 🎉 :
To verify this is now displaying as intended, you can check [the branch](https://github.com/linode/manager/tree/DevDW-update-readme-new-logo).

M3-5750: Update README.md with new logo

---

packages/manager/src/LinodeThemeWrapper.tsx
packages/manager/src/utilities/testHelpers.tsx

Prevents storybook from making a call to the preferences endpoint.
Run `yarn storybook`
Once it is available to view in your browser open the network tab in dev tools and make sure there are no calls to the preferences endpoint while browsing components.

Prevent preferences call from storybook

---

packages/manager/src/LinodeThemeWrapper.tsx

- Highlight.js's theme was stuck in dark mode
- This resulted in the `View Kubeconfig` drawer displaying the yaml in the wrong theme
- Bug was caused by #8040
- Check against the actual CSS values instead of an inline comment to disable each Highlight.js theme
- We use to check for a comment in the CSS, but now that we use esbuild, comments are removed and we can't change that
- Go to (or create) a Kubernetes Cluster
- View the Kube Config
- Ensure the yaml's theme matches and respects Cloud Manager's theme (Toggle themes with `control` `shift` `d`)
- A slight delay in the yaml's theme is expected

Fixed Highlight.js Theme Issues caused by Webpack 5

---

packages/manager/.storybook/main.js
packages/manager/.storybook/preview.tsx
packages/manager/package.json

- Removes the attempt to import the service worker at all. This was breaking production storybook for Safari
- Fixes favicon
- This will work because I did a production build with Cloudflare Pages and it works now
- https://b50bbf70.manager-ec2.pages.dev

Fix Storybook for Safari and Fix Favicon

---

.github/workflows/e2e_pr.yml

This disables the recording of Cypress runs for end-to-end tests run on PRs. End-to-end tests that run upon pushing to `develop`, `staging`, and `master`, as well as scheduled tests that run each morning, will continue to be recorded.
We're approaching our monthly limit for test recordings on Cypress.io and thought this would be a workable compromise. If anybody relies on the Cypress.io test recordings for PRs, please let me know!

Disable Cypress recording for PR end-to-end tests

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx

Adds dismissible banners containing copy on the Early Adopter Program SLA to the Database Create & empty state Landing page for beta.
Check both the Database Create page and the empty state Database Landing page to confirm the banners display. When either is dismissed, the other should no longer be seen. The banner should not be visible on the landing page in the non-empty state.

[Hotfix] Add EAP SLA dismissible banners to Database Create & empty state Landing page

---

CHANGELOG.md
packages/manager/src/IdentifyUser.tsx
packages/manager/src/queries/account.ts
packages/manager/src/queries/accountAgreements.ts
packages/manager/src/queries/accountSettings.ts
packages/manager/src/queries/base.ts

This adds `accountError` to the dependency array of the effect that "identifies" a user with LD and sets feature flags to "loaded" (thus letting users past the splash screen).
This caused an issue in production where restricted users without billing access (i.e. access to `/account`) could not load the app.
It seems to have been introduced in the Webpack 5 PR, but it is entirely unclear why to me why that is the case. In fact, it's unclear to me why this _ever_ worked (without `accountError` in the dependency array.)
I also changed "retry: false" on the account query so the page would load faster for restricted users. This _may_ have other effects that we should look into.
Run the app as a full …

Patch: restricted users without billing access cannot use the app

---

packages/manager/src/features/linodes/LinodeEntityDetail.tsx

Fixes the background not covering the copy cell during hover **on Safari**. This PR also cleans up the CSS by removing usages of `!important` which were related to the issue
Check out the copy icon on the Linode Detail header on Chrome and Safari (and Firefox if you prefer)

Fix hover state for Linode Detail header copy icon on Safari

---

packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx

Fix LiteSpeed cPanel drawer opening the cPanel drawer & OpenLiteSpeed Django drawer opening the Django drawer instead of the LiteSpeed versions.
This was due to the `cPanel` and `Django` apps being matched first and returning true before we get to their LiteSpeed versions. So, I updated the find function to find exact matches instead.
Go to Marketplace and check that:
- LiteSpeed cPanel opens the LiteSpeed cPanel drawer
- OpenLiteSpeed Django opens the OpenLiteSpeed Django drawer
- Apps with special characters still open their drawers (Minecraft: Java Edition, MySQL/MariaDB, Percona (PPM), Rocket.Chat, WireGuard®)

M3-5644: Fix mismatching Marketplace drawers

---

.github/workflows/e2e_pr.yml

This will re-enable Cypress test recording so that test results are once again published to Cypress Dashboard. This will also resolve the consistent failures we've been seeing for PR E2E tests over the past few days.
This can be merged any time on or after March 14th.

Re-enable Cypress recording

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PayPalChip.tsx

- Added PaymentMethodCard component for displaying payment method cards
- Don't report popup closed errors to Sentry
- There's no exact way to reproduce this. The one time I did get this error, the payment went through anyway. I was also unable to find more info on this specific error so I think we can go ahead and filter these out
- Removed unused classes
Go to `/account/billing/make-payment` and ensure the payment methods still display correctly

M3-5604: Clean up payment method code

---

packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx

This temporarily disables a couple of Jest tests in `PaymentInformation.test.tsx` which seem to be related to the Jest issues we're having with GitHub Actions.
This should allow the `ci` workflow to pass, but in the coming days or weeks I'll try to figure out the root cause of this issue and fix/restore these tests.
Wait for GitHub Actions to run -- if it stalls, this PR should not be approved. If it succeeds, we should be good.

M3-5768: Temporarily disable Jest payment tests

---

packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx

Removes the manage SSH keys link from the `UserSSHKeyPanel` success notice
Create an SSH key (e.g. in the Linode Create flow) and the link should no longer display in the success notice

M3-5727: Remove manage SSH keys link

---

packages/manager/src/features/Databases/DatabaseDetail/index.tsx

Similar to Linodes, LKE, etc., the labels of DBaaS clusters are now editable from the breadcrumb on the Database Detail page.
Please test the success flow and also the error flow by blocking requests to `/database` before attempting to submit the label change.

M3-5743: Editable DBaaS cluster labels

---

packages/manager/src/components/Notice/Notice.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx

Replace the static `Linode Images cannot be created if you are using raw disks or disks that have been formatted using custom filesystems.` text on the Capture Image tab in the Image Create flow with a warning notice that displays only if the chosen disk is a raw disk. If the warning notice is being displayed, the estimated price also does not display.
From the "Capture Image" tab in the Image Create flow, choose a Linode that you have a raw disk added to. Then select that raw disk. The warning notice should display. If you choose a different, non-raw disk, or choose a different Linode, the warning should disappear.

M3-5514: Dynamically-shown warning for raw disks in Capture Image tab

---

packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptPanel.tsx
packages/manager/src/features/StackScripts/SelectStackScriptPanel/SelectStackScriptsSection.tsx
packages/manager/src/features/StackScripts/SelectStackScriptPanel/StackScriptSelectionRow.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx
packages/manager/src/features/StackScripts/StackScriptRowHelpers.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/store/image/image.helpers.ts
packages/manager/src/store/linodeCreate/linodeCreate.reducer.ts

- Fixes backwards "Account" and "Community" stackscript routing on Linode Create
- Fixes surfacing LKE stackscripts that should not be shown on Linode Create Stackscript tab (shown in screenshots)
- Fixes tons of docs from rendering in the summary section on the Linode Create page when deploying from a StackScript (reported by @HanaXu)
- Cleaned up some unused props
- Fixed unnecessary x-overflow shown in the first screenshot below eb508e9
- Fixed broken action menu height on StackScripts landing (seen in before after screenshots) 6fb1360
- Test Linode Create StackScript tab routing
- Test Deploying a Linode from a StackScript
- Make sure there are not a ton of docs in the Checkout Summary panel at the bottom of the create page
- Test Deploying a Linode from a StackScript when you have a …

StackScript Fixes

---

packages/manager/cypress/integration/linodes/linode-storage.spec.ts

This reduces or eliminates the test flakiness found in the `try to delete in use disk` test within `linode-storage.spec.ts`.
This test is flaky because navigating to the Linode details page "Storage" tab too quickly after creating a Linode can cause the Linode's disk not to appear (presumably because it has not been created yet), and the disk will not appear until the page is refreshed.
These changes sidestep the issue by waiting for the Linode to boot before navigating to the "Storage" tab. See M3-5762 for more information.
```bash
yarn cy:run -s "**/*/linode-storage.spec.ts"
```
Confirm that tests succeed.
Unfortunately, reproducing the issue is difficult and it only occurs once in a while, so …

M3-5762: Resolve "try to delete in use disk" E2E test flakiness

---

packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/RestoreToLinodeDrawer.tsx

- Aligns the primary button to the right and secondary to the left in the Restore from Backup drawer
- Add logic to automatically display primary buttons to the right (can be updated in the future if we wanted to swap orders again)
- Go to a Linode's details page, click the backups tab, and click `Restore to Existing Linode` to open the drawer
- Ensure that the new logic hasn't negatively affected other places where ActionsPanel is used

M3-5587: Swap button order in Restore from Backup drawer

---

packages/manager/src/components/StackScript/StackScript.test.tsx
packages/manager/src/components/StackScript/StackScript.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx
packages/manager/src/features/StackScripts/StackScriptsLanding.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/store/image/image.helpers.test.ts
packages/manager/src/store/image/image.helpers.ts

- Shows StackScripts that use deprecated Images
- Previously we just filtered out StackScripts that used deprecated images and user's StackScripts would not be viewable at all in Cloud Manager
- Adds a new "Deprecated Images" section to the StackScript details page containing any deprecated images the StackScript uses (show in screenshot)
- Test viewing account StackScripts
- Ensure Linode Kubernetes StackScripts do not display when you have LKE clusters deployed
-  Refer to internal ticket

M3-5719: Fixed StackScripts with deprecated Images not showing

---

packages/manager/src/features/linodes/MigrateLanding/CautionNotice.tsx

Fixes a typo caused by the luxor package.
1. Navigate to the Linode landing page
2. Click the action menu
3. Click the migrate button
4. Ensure that the final line in the warning notice has proper grammar.

replaced the word in with empty string

---

packages/manager/src/components/EnhancedNumberInput/EnhancedNumberInput.tsx

Fixes a bug with the `EnhancedNumberInput` that would allow numbers above the max to be input. This bug in conjunction with how the component updated its value resulted in truncated large values being submitted. Now when the user tries to input a number larger than the max the component will set the value to the max.
1. Navigate to the Kubernetes cluster create page
2. Click a node pool quantity to begin to edit it
3. Type in a number larger than the max (100)
4. Ensure that the value shown in the input does not exceed the max (100)
5. Ensure that when adding that pool to the checkout bar that the value is the max (100)

M3-5776: Cloud Manager doesn't give feedback when resizing a Node Pool over the 100 node limit

---

packages/manager/src/components/TabLinkList/TabLinkList.tsx
packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/components/core/ReachTab.ts
packages/manager/src/components/core/ReachTab.tsx
packages/manager/src/components/core/ReachTabList.ts
packages/manager/src/components/core/ReachTabList.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.test.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
packages/manager/src/features/Support/SupportTickets/TicketRow.tsx

- Update support ticket table links to match our newest pattern for links in tables
- The old tab styles were driving me nuts so...
- Wrap Reach Tabs and TabList so we can apply our styles to them before we import them in other components
- Go to `/support/tickets` and check Tab styles and link styles in the table
- Please check **all Tabs** in Cloud Manager because of the minor refactor

M3-5733: Support Ticket Refinements

---

packages/manager/src/components/Drawer/Drawer.tsx
packages/manager/src/components/ExtendedAccordion/ExtendedAccordion.tsx
packages/manager/src/components/NotificationDrawer/NotificationDrawer.tsx
packages/manager/src/components/NotificationDrawer/index.ts
packages/manager/src/components/NotificationMenu/.NotificationMenu.stories.mdx
packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
packages/manager/src/components/NotificationMenu/index.ts
packages/manager/src/components/Table/Table.stories.mdx
packages/manager/src/features/NotificationCenter/Events.tsx
packages/manager/src/features/NotificationCenter/NotificationContext.ts
packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderNotification.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx
packages/manager/src/features/NotificationCenter/NotificationSection.tsx
packages/manager/src/features/NotificationCenter/Notifications.tsx
packages/manager/src/features/NotificationCenter/index.tsx
packages/manager/src/features/TopMenu/NotificationButton.tsx
packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
packages/manager/src/features/TopMenu/iconStyles.ts
packages/manager/src/features/linodes/LinodeEntityDetail.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
packages/manager/src/features/linodes/LinodesLanding/CardView.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
packages/manager/src/features/linodes/LinodesLanding/ListView.tsx
packages/manager/src/mocks/serverHandlers.ts

This PR updates the UI for the notification drawer and it's empty state. The notification drawer is less of a drawer and is more consistent with the user menu. 
**Todo:**
**Tasks that will be addressed in a future PR:**
Check the notification events view:
- Notifications but a few events (< 5 events)
- Notifications but a lot of events (turn on mocks)
- No notifications and no events (comment out code inside of `serverHandlers.ts`)
Test menu opening/closing:
- Opening the menu via another action other than the bell icon (such as clicking on a Linode's status when it is booting)
- Toggling the menu by double clicking the bell icon
- Clicking inside the menu should not close the menu
- Unless you clicked a link inside the menu (such as `View all events`), then the menu should close
Other:
- …

M3-5338: Notification Drawer refinements

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx

Adds back in /116 ranges to a Linode's networking panel. These were accidentally removed when support for routed and shared /64s and /56s was added. This happened because we get our /64 and /56 info from /networking/ipv6/ranges which doesn't surface /116 information
Also adds comment about adding in RDNS info in the future
See internal message "Testing https://github.com/linode/manager/pull/8327"

Show /116s in networking panel

---

packages/manager/src/features/Events/EventsLanding.tsx

- Fixes the broken table loading state shown in the video below
- Fixes responsiveness of that same loading state
- This bug was introduced because we did not spend time testing #8289 and #8305 together
https://user-images.githubusercontent.com/6440455/163873798-e5d39963-5f3d-4f7b-a8a7-7d51b6a993a3.mov
- View the Activity Feed `/linodes/{id}/activity` of any Linode and check the loading state for any UI weirdness
- Check the loading state at all screen sizes for issues

Fix Events Table Loading State

---

packages/manager/cypress/integration/linodes/linode-storage.spec.ts
packages/manager/cypress/integration/linodes/resize-linode.spec.ts

(See also: #8305, #8335 )
Fixes the remaining test failures from #8305.
The crux of these failures is that the new notification menu is always present in the DOM, whether or not it is open (it's simply hidden when closed). This differs from the older implementation, where no notification content existed in the DOM when the notifications drawer was not open. This change caused some tests to fail because the tests assumed that the notice text would only exist once in the DOM, and it now exists twice (visible in a banner, invisible in notifications menu).
```bash
yarn cy:run -s "cypress/integration/linodes/linode-storage.spec.ts","cypress/integration/linodes/resize-linode.spec.ts"
```

Fix remaining test failures related to notification changes

---

packages/manager/src/features/TopMenu/NotificationButton.tsx

Fix broken e2e notification tests caused by https://github.com/linode/manager/pull/8305
```
yarn cy:run -s './cypress/integration/notificationsAndEvents/events.spec.ts'
```
```
yarn cy:run -s './cypress/integration/notificationsAndEvents/notifications.spec.ts'
```

Fix broken notifications e2e tests

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettings.tsx

Set the `spacingTop` to `28` and `spacingBottom` to `22`.
Per the ticket comments, I took a look at modifying `Divider.tsx` to make these the default values if those props weren't passed to the component, but many files would need to be updated to maintain the integrity of spacing in other instances outside of this page.
Take a look at the spacing on the Settings tab of a Database Detail page.

M3-5773: Adjust spacing on DBaaS Settings page

---

packages/manager/src/IdentifyUser.tsx
packages/manager/src/containers/withFeatureFlagProvider.container.ts

Makes use of the private user attributes feature of Launch Darkly to limit the collection of PII. In particular the items of `country` and `taxID`. 
Instructions listed in ticket

M3-5748: Use private user attributes for LaunchDarkly fields

---

packages/manager/src/components/Dialog/Dialog.stories.mdx
packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
packages/manager/src/features/Profile/Settings/Settings.tsx

Changes all occurrences of the phrase `type to confirm` to `type-to-confirm`
Ensure the phrase `type to confirm` is always formatted as `type-to-confirm`

M3-5774: Type to confirm add hyphens

---

packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableRow.tsx

Removes the `strong` tag wrapping the object name in the `ObjectTableRow` component.
1. Navigate to an bucket with objects in it
2. Ensure the object names in the table are not bold

M3-5581: Change object name text to regular weight

---

packages/manager/cypress/integration/firewalls/migrate-linode-with-firewall.spec.ts

Fixes the failing Cypress test related to firewalls. The tests were failing to select options within an enhanced select; I think Cypress was finding the option elements in the DOM and attempting to interact with them before they were actually visible on-screen.
```bash
yarn cy:run -s "cypress/integration/firewalls/migrate-linode-with-firewall.spec.ts"
```
To reproduce the issue, run the above command against `develop` and observe failures (the test doesn't fail every time, but does seem to fail most of the time). To test the fix, run the same command against this PR and confirm that the tests succeed.

Fix failing firewall E2E test

---

packages/manager/src/components/ErrorState/ErrorState.tsx
packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx

- Changes `Linode Authentication` to `Security Settings`
- Adds placeholders for `Phone Verification` and `Security Questions`
- Moves all 3rd party login information to a single `Login Method` paper
- Adds dividers as shown in mock up (in internal ticket)
- Check UI compared to the mockup

M3-5790: Login & Authentication Scaffolding for Security Questions and Phone Verification

---

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx

Controls the beta chips for DBaaS using the `databaseBeta` feature flag
1. Disable database beta in the dev tools
3. Ensure that the beta chip for databases in the primary nav does not render
3. Navigate to Database Create
4. Ensure that the beta chip in the breadcrumb at the top of the page does not render

feature flagged the beta chips for DBaaS

---

packages/api-v4/src/databases/types.ts
packages/api-v4/src/linodes/types.ts
packages/manager/src/factories/databases.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/mocks/serverHandlers.ts

Adjustments to the Database Create flow, Database types, and mocks to reflect forthcoming API changes.
Go through the Database and Linode Create flows on dev or staging. Ensure that nothing is broken and things behave as you would expect them to.
Please note that the app will crash on dev currently if you choose a MongoDB or PostgreSQL database engine while a plan is selected. This is because the rows have not been populated on dev with data for those engines. Neither DB engine will appear outside of dev presently.

M3-5808: Adjustments to Database Create flow and types due to API changes

---

packages/manager/src/components/Button/Button.tsx
packages/manager/src/components/DocsLink/DocsLink.tsx

This PR fixes the vertical alignment for button text on Firefox by adding slight margin for Firefox only. 
Check buttons throughout the app and the docs link as well.

M3-5578: Button text not vertically centered in Firefox

---

packages/manager/src/features/OneClickApps/FakeSpec.ts

Currently, the link for the Wazuh Marketplace app guide is actually pointing to the Webuzo guide.
Fix the link.

Update Wazuh link

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Display `admin` as the username for MongoDB clusters.
MySQL and PostgreSQL database clusters should have `linroot` as the username, and MongoDB clusters should have `admin` as the username in Connection Details.

M3-5827: Hotfix for MongoDB username

---

packages/api-v4/package.json
packages/manager/package.json
packages/validation/CHANGELOG.md
packages/validation/package.json
packages/validation/src/databases.schema.ts

- Fixes typo in `@linode/validation` package allowing users to create 3 node MySQL clusters. 
- Try to create a 3 node MySQL cluster
- Try testing many other configurations of Databases in Cloud Manager

M3-5828: Fix creation of 3 node MySQL clusters

---

packages/manager/cypress/integration/volumes/create-volume.smoke.spec.ts

- Updates e2e tests for volumes to not use the NVMe banner we removed in #8371 
- `yarn cy:run -s "./cypress/integration/volumes/create-volume.smoke.spec.ts"`

Fix volumes e2e tests after removing NVMe banners

---

packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
packages/manager/src/hooks/useDismissibleNotifications.ts

There was an existing bug in production that caused events to sometimes disappear from the notification menu upon opening/closing the menu and then refreshing the page.
This was because every time the menu was closed, we were calling `dismissNotifications`, which calls `updatePreferences`, which creates a `profile_update` event, even if there were no notifications. The issue with this is that we store a certain amount of most recent events in the redux store, and then from those events, we filter out `profile_update` events. So eventually, after opening/closing the menu enough times, actual events would get pushed out and only `profile_update` events would be in the store.
This fix makes sure that preferences are only updated when there are actually notifications.
Before: …

M3-5801: Fix events sometimes disappearing from the notification menu

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx

- Allows users to sort their Databases by `Configuration` and `Status` in addition to the existing `Label` and `Created`
- We can add this because the API supports it and this table is fully paginated and sorted by the API
https://user-images.githubusercontent.com/6440455/169611034-49d0f160-fc86-4fb4-9f9c-337275b9b4ae.mov
- Ensure you have a few databases of different types to test with
- Go to `http://localhost:3000/databases`
- Test all sortable columns
- Test table responsiveness
- Ensure query params get set properly when a column is changed

Allow more sorting options for Databases 

---

packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx

- Caused 6 months ago
- Caused when updating code to fix a Material UI deprecation regarding `backdropClick`
- The `onClose` function was not getting passed to our function that generates the modal action buttons
- Fixes a flaw in the `ConfirmationDialog.tsx` component by passing `onClose` down to the actions
- Test action buttons and cancel buttons in Linode dialogs
- Specifically test the Linode configs deletion dialog

M3-5829: Fix Linode Configs Cancel Button

---

packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx

This adds a “BETA” chip to the DB engine selection on Databases Create.
Whether or not a DB engine is controlled by LaunchDarkly. There’s a new “Database Engine Betas” flag, which is an array of engines that are considered to be in Beta. The values are the display names (e.g. “MongoDB” and “PostgreSQL”).
New copy has been added under the Engine Selection component if a beta engine is selected:
Try different values for databaseEngineBetas (you can override the flags in `useFlags.ts`). Make sure everything works as expected.
**ALSO:** to address Matthew's comment below, I added some height to the SingleValue component, used by Region Select and Image Select. Please check for regressions here as well.

Indicate that MongoDB and PostgreSQL are in beta.

---

packages/manager/src/features/Profile/APITokens/utils.test.ts
packages/manager/src/features/Profile/APITokens/utils.ts

Adds Databases to the `Personal Access Token` drawer, which lets the user set smaller scopes such as read_only.
I also went ahead and added Firewall to the drawer since it's a simple change and we'll need to add support for that later anyway.
- Go to `/profile/tokens` and click on `Create a Personal Access Token`
- You should see `Databases` and `Firewall` in the access table
- Create a token and then click on `View Scopes` for the token you just created. You should see a checkmark for the values you selected when creating the token.
- Make an API request with the token and ensure that the permissions are working as expected

M3-5817: Add support for scoping Database and Firewall permissions

---

packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
packages/manager/src/features/TopMenu/NotificationButton.tsx

Since revamping the notification menu (#8305), the notification menu content has been present in the DOM even when hidden.
This PR changes the behavior of the `NotificationButton` component so that the notification menu content is not present in the DOM when the menu is not open.
**Why?**
A few tests are failing or are flaky because `cy.findByText(...)` and similar calls are now selecting elements within the notification menu instead of the elements that were intended. We can (and do) fix these on a case-by-case basis, but it's becoming a game of whack-a-mole as changes to the notification menu and event language continue to cause previously stable tests to break.
To reproduce:
1. Checkout …

Remove notification menu content from DOM when not expanded

---

packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx

- We stored the Engine state in two places on the Database Create page
- This PR removes one state and pulls the database's engine from Formik's state
- Test the Database Creation flow for different engines
- Run Database Create Cypress tests

Database Create Remove Duplicate State

---

packages/manager/cypress/integration/firewalls/migrate-linode-with-firewall.spec.ts

Fixes the `migrates linode with firewall - real data` and `adds linode to firewall - real data` Cypress tests, which have been flaky.
The tests fail often because some of our test accounts have so many resources that the label for the desired Linode is not immediately visible in the drop-down when creating a firewall, causing a `should('be.visible')` assertion to fail. This PR changes the test behavior so that the Linode label is typed into the field instead.
**Note:** this issue can only be reproduced if you have enough Linodes on your test account.
To reproduce, check out `develop`, do `yarn up`, and run:
```
yarn cy:run -s "cypress/integration/firewalls/migrate-linode-with-firewall.spec.ts" …
```

Fix Flaky Cypress Firewall Tests

---

packages/manager/src/features/Volumes/UpgradeVolumeDialog.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesActionMenu.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/UpgradeVolumesDialog.tsx
packages/manager/src/mocks/serverHandlers.ts

- Allows unattached volumes to be migrated to NVMe instantly by the user
- Refer to internal ticket on what problem this is trying to solve
- This flow is different that an attached volume because it does not associate the action with an entire linode
https://user-images.githubusercontent.com/6440455/172462431-d20492c9-00d7-4f64-b27a-300d32341382.mov
- Turn on MSW, try upgrade flow for the volume called `hdd-unattached`

M3-5835: Allow users to migrate unattached volumes

---

packages/api-v4/src/account/types.ts
packages/manager/src/factories/billing.ts
packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
packages/manager/src/features/Billing/PdfGenerator/utils.ts

If we have `tax_summary` data, display associated taxes on their own lines on invoices otherwise just display the tax subtotal
Standard tax
More specific taxes (turn on MSW)
Empty `tax_summary` array
- Click on an invoice and look at the invoice details
- Download an invoice and check the PDF

M3-5826: Display tax lines on invoices

---

packages/manager/src/features/TopMenu/NotificationButton.tsx
packages/manager/src/features/TopMenu/iconStyles.ts

Before (more of an oval than a circle):
After:
Check the Notifications badge in several browsers and ensure it is a circle with no distortions to the shape or the text

M3-5833: Make Notifications badge a true circle

---

packages/manager/src/hooks/useDismissibleNotifications.test.ts
packages/manager/src/hooks/useDismissibleNotifications.ts

Reduce `STALE_DAYS` from 60 to 45 to clean up dismissed notifications more frequently in User Preferences (more discussion in Slack).
Moving forward, we will have to be more vigilant on a few fronts; for example, establishing and adhering to timelines for keeping marketing banners live. Reducing the number of `STALE_DAYS` runs the risk of having previously dismissed notifications/banners reappear sooner in the UI.
Dismissal functionality should still work as intended

M3-5315: Clean up dismissed notifications more frequently in User Preferences

---

packages/manager/src/features/Images/ImageUpload.tsx

Moves some region text in Upload Image to a tooltip
Go to `/images/create/upload` and hover over the tooltip next to the region input

M3-5496: Move region text to tooltip in Upload Image

---

packages/manager/src/features/Profile/AuthenticationSettings/AuthenticationSettings.tsx
packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx
packages/manager/src/features/Profile/AuthenticationSettings/SMSMessaging.tsx

- Changes copy in Phone Verification section
- Check for spelling
- Check that removing the `<Notice />` did not break any UI

Phone Verification Copy Changes

---

packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/SecurityQuestions.tsx

Changes the word `call` to `contact` for the description copy in the security questions section.
Ensure the word call has been replaced by the word contact

M3-5823: Change call to contact in security questions copy

---

packages/manager/package.json
packages/manager/src/initSentry.ts
yarn.lock

- Updates `@sentry/browser` to the latest version
- Define `REACT_APP_SENTRY_URL` in your local env
- To get the Sentry URL ask me or find it in Sentry (Cloud Manager -> Project Settings -> DSNs)
- Add some code in Cloud Manager anywhere that will call Sentry's captureException function to test that exceptions get sent to Sentry
```ts
import { reportException } from 'src/exceptionReporting';
reportException("Test Sentry");
```
- Go to Sentry and verify that exceptions are captured as expected (selected development environment)

Upgrade Sentry to `@sentry/browser@7.1.1`

---

packages/manager/src/features/Domains/DomainBanner.tsx
packages/manager/src/features/Events/EventRow.test.tsx
packages/manager/src/features/Events/EventRow.tsx
packages/manager/src/features/ObjectStorage/BucketLanding/BucketTableRow.test.tsx
packages/manager/src/features/Volumes/VolumeTableRow.test.tsx

This fixes DOM nesting warnings that get logged to the console when running Jest:
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.
```
```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <p>.
```
```
Warning: validateDOMNesting(...): <p> cannot appear as a child of <p>.
```
This is a small part of a larger effort to clean up the Jest tests and console errors and ultimately resolve some of the inconsistencies we've been seeing across environments.
* Navigate to the events landing page at `/events` and confirm that the styling of the events rows has not been impacted by the removal of the `<Typography />` component
* Navigate to the domains landing …

M3-5862: Fix Jest DOM nesting validation warnings

---

packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx

- If an existing user with 2FA enabled **and** without security questions tried to press `Reset two-factor authentication`, they would get an error notice saying `You must add Security Questions to your profile in order to enable Two Factor Authentication`. This may be confusing to users because it says `enable` instead of `reset`
- This PR makes it so the error will say `reset` if the API returns `You must add Security Questions to your profile in order to enable Two Factor Authentication` **and** you have 2FA enabled.
https://user-images.githubusercontent.com/6440455/176538305-e487e383-340a-4d95-a9b2-6adbb7eb4ec4.mov
- Get an account into a state where it does not have security questions, but it does have 2FA enabled
- Press the `Reset two-factor authentication` button
- Verify that you …

M3-5853: Make 2FA / Security Questions Errors Accurate

---

packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx

- Updates 2FA security questions notice font size to match other notices on the page
- Go to `http://localhost:3000/profile/auth` with no Security Questions on your account (you can use the MSW for this)
- View the Notice in the 2FA section and make sure the font size is now `14px` or `0.875rem`

M3-5860: Update 2FA Security Questions Notice Font Size

---

packages/manager/src/queries/account.ts
packages/manager/src/queries/accountAgreements.ts
packages/manager/src/queries/accountPayment.ts
packages/manager/src/queries/accountSettings.ts
packages/manager/src/queries/accountUsers.ts
packages/manager/src/queries/entityTransfers.ts

Once Cloud has established that a user is restricted, we should not attempt to request any of the account endpoints
Go to `/account` on a restricted user and click through the tabs while verifying that we longer make requests to /account endpoints

M3-5759: Don't make /account requests if restricted user

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx

In prod, when you resize your window while on the "Analytics" tab of a Linode Detail page, there can be periods of up to ~30 seconds where the graphs are distorted in their shapes. This occurs because the graphs did not re-render until the data fetch interval came around again.
This PR adds logic to refetch the stats 1.5 seconds after resizing the window.
While on the "Analytics" tab of a Linode Detail page, try resizing the window multiple times. You should see a call to `stats` in the Network tab of Devtools shortly after you do each resize. Compare the behavior on this branch with production.

M3-5255: Fix Linode stats graphs to be more responsive

---

packages/manager/src/features/Domains/CreateDomain/CreateDomain.tsx
packages/manager/src/features/Domains/DisableDomainDialog.tsx
packages/manager/src/features/Domains/DomainTableRow.tsx
packages/manager/src/features/Domains/DomainsLanding.test.tsx
packages/manager/src/features/Domains/DomainsLanding.tsx
packages/manager/src/features/EntityTransfers/EntityTransfersCreate/LinodeTransferTable.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx
packages/manager/src/queries/domains.ts
packages/manager/src/queries/linodes.ts

- Refactors Domains Landing and associated files to integrate React Query along with new patterns
- API paginates the Domains Landing table for all users (not just large accounts)
- Testing functionality of the Domains landing page
- `Create`, `Delete`, `Enable`, and `Disable` should work like production
`yarn test Domain`
> **Note**: Most of these are because we need to update the React Query store instead of the Redux store in many places
- Changes when editing Domains are not reflected on the landing page 
- Cloning a Domain is not reflected in the landing page

M3-5180: Refactor Domains Landing to begin React Query integration

---

packages/manager/cypress.json

This PR increases Cypress's request timeout from 20 seconds to 30 seconds. This should help prevent failures that are related to the slow `/account` response time for some of our test accounts while we explore longterm solutions.
There isn't much to verify since this is a config change and not a code change, but you could run `yarn cy:debug`, run pretty much any test, and observe that the timeout displayed in the left sidebar is 30 seconds rather than 20 seconds.

Increase Cypress request timeout to 30 seconds from 20 seconds

---

packages/manager/src/components/PaymentMethodRow/PaymentMethodRow.test.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.test.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx

This fixes `usePayPalScriptReducer` errors that get logged to the console when running Jest:
```
Error: usePayPalScriptReducer must be used within a PayPalScriptProvider
```
I've also mocked a few calls to the APIv4 client library which will eliminate a couple `Warning: captured a ... request without a corresponding request handler` warnings (see M3-5864 for the remaining work on those warnings).
To reproduce, run `yarn test` against `develop`, and observe a handful of `usePayPalScriptReducer` errors in the console output.
To verify these changes, run `yarn test` against this branch and observe that those errors are no longer present.
To verify just the …

M3-5863: Fix Jest 'usePayPalScriptReducer' errors

---

packages/manager/src/components/ImageSelect/icons.ts

Adds Kali distro icon
Go to `/linodes/create` and select Kali as the image

Add Kali distro icon

---

packages/manager/src/components/FileUploader/FileUploader.tsx

We've received intermittent reports since last year about some users on Linux attempting to upload properly-zipped Images under 5GB who received error messages stating that the file was in excess of 5GB.
I replicated this issue on Ubuntu 22.04. First I added a `console.log()` in `onDropRejected()` to see what was going on; the error for a valid file on the `File` object stated that it was not an `x-gzip` file. The `type` property on the `File` object was listed as `application/gzip`, not the `application/x-gzip` that we explicitly accepted. However, `x-gzip` and `gzip` are functionally equivalent, so we should accept both.
In the code, the reason why the max size error was showing erroneously is because of the logic in `onDropRejected()`: `wrongFileType` was false because "gzip" was being …

M3-5722: Image upload max size bug on Linux

---

packages/manager/cypress/integration/objectStorage/access-key.e2e.spec.ts
packages/manager/cypress/integration/objectStorage/access-keys.smoke.spec.ts
packages/manager/src/assets/icons/download.svg
packages/manager/src/components/CopyableAndDownloadableTextField.tsx
packages/manager/src/components/DownloadTooltip.tsx
packages/manager/src/features/Profile/SecretTokenDialog/SecretTokenDialog.tsx

Adds the ability to download the keys for a token from the text field that displays it.
1. Navigate to /profile/tokens
2. Create a new Personal Access Token
3. Ensure that the `TextFields` displaying the keys have both a download and copy `Tooltip` at the end of the `TextField`
4. Click the download `Tooltip`
5. Ensure the file downloaded
- Contains the string displayed in the `TextField`
- Is named the label of the `TextField` in snake case

M3-5462: Keys and secrets modals update UI

---

packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/components/RenderGuard.tsx
packages/manager/src/features/Users/UserPermissions.tsx

- Improves button alignment in `/account/users/<username>/permissions`
- Includes code clean up and minor refactor 🧹
- Test ActionsPanels throughout Cloud Manager
- Check button placement at `/account/users/<username>/permissions`

Button Placement in User Permissions and `ActionsPanel.tsx` Clean Up

---

packages/manager/src/featureFlags.ts
packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
packages/manager/src/features/OneClickApps/FakeSpec.ts
packages/manager/src/features/OneClickApps/LinkSection.tsx

Sometimes, there are small mismatches in a Marketplace app's doc link that break the link (missing a dash, capital letter, etc).
This PR adds the ability to override the app's doc link using LaunchDarkly so that we can fix the link without an immediate release/hotfix
Go to Marketplace and check the docs link in the Kali Linux detail drawer with the `one-click-apps-docs-override` flag on/off

M3-5877: Override Marketplace app doc link with LaunchDarkly

---

packages/manager/cypress/integration/account/security-questions.spec.ts
packages/manager/cypress/support/intercepts/profile.ts

This PR adds Cypress integration tests for account security questions at `/profile/auth`. These tests use mocked data to confirm that the Cloud Manager UI responds accordingly when adding and updating security questions.
**How do I run relevant tests?**
**⚠️ Note:** these tests may fail if you have not yet dismissed the banner regarding Linode/Akamai billing. This is because the banner is displayed over the Cloud Manager content, and in some circumstances can block Cypress's click attempts.
To run via CLI:
```
yarn cy:run -s "cypress/integration/account/security-questions.spec.ts"
```
To run interactively:
```
yarn cy:debug
```
Then search for _security-questions_.

M3-5771: Add Cypress tests for account security questions

---

packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts

- These changes make it so that the graph legends for the Linode Analytics tab line up on mobile
- This issue was reported in https://github.com/linode/manager/issues/7893
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
- Run Cloud Manager locally
- Open an account with a running Linode
- Observe the graph legends in the analytics tab
Please let me know if you have any questions!

Align Graph Legends on Mobile

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/ProductInformationBanner/ProductInformationBanner.tsx
packages/manager/src/featureFlags.ts
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx

Add a dismissible banner to the Databases Landing and Database Create pages regarding maintenance.
This PR modifies `ProductInformationBanner` to make it capable of displaying a warning icon to the left of the banner text.
Confirm that the dismissible banner is visible on the Databases Landing page (both the empty state and also when you have DBs) and Database Create page, and that dismissing the banner in one location dismisses it in all of them.

[Hotfix] Add dismissible banner to Database Landing and Database Create pages re: maintenance

---

packages/manager/src/mocks/serverHandlers.ts

This adds MSW handlers for GET requests to `/account/users`, `/object-storage/keys`, and related endpoints. The primary motivation for this is to clean up the console warnings that appear when running Jest, but adding these handlers also allows us to mock the account users pages (including grants and profiles) and the object storage access keys landing page.
Note that because I did not add any handlers for update operations, attempting to edit anything related to account users or access keys with MSW enabled will result in not found errors.
1. Confirm that no MSW warning is shown in the console when running the affected tests:
```
yarn test AccessKeyLanding.test UserMenu.test
```
2. (Optional) …

M3-5864: Add MSW handlers for `/account/users` and `/object-storage/keys` requests

---

package.json
yarn.lock

- Pins  `hosted-git-info`  to the latest version at address CVE-2021-23362 
With these types of tickets, it would be nice to be able to just update the dependencies that depend on `hosted-git-info` to resolve this, but packages that use `hosted-git-info` such as `npm-run-all` have not updated `hosted-git-info`  to the latest yet, so it's no use.
- Test functionality of Cloud Manager (`yarn up`)
- Test functionality of Storybook (`yarn storybook`)
- Storybook depends on `hosted-git-info`

M3-5092: `hosted-git-info` - CVE-2021-23362 

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/AddPaymentMethodDrawer/AddPaymentMethodDrawer.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/GooglePayChip.tsx
packages/manager/src/features/Billing/GooglePayProvider.ts

Display an error notice in Add Payment Drawer instead of a toast (and some minor refactoring)
Before
After
Point to dev and try to make/add a third party payment on an account that has the `pays by akamai` flag
Also test normal flow on an account without the flag

M3-5876: Add Payment Drawer error notice

---

packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx

Currently in prod, if you go to `/linodes/create` and fill in the region but then switch Create tabs to create the Linode from a different source, the "Region" field appears to be populated still, but the actual value has been cleared (which is why filling everything out on the most recent Create tab and clicking "Create Linode" results in the user seeing an error on the "Region" field, although it appears to be populated).
This PR clears the value when the region ID does not return a matched region.
1. Go to `/linodes/create` and choose a region 
2. Switch Create tabs by clicking "Marketplace", etc.
3. Observe: the "Region" field should no longer be populated on this branch, and filling out the rest of the required information should allow you to successfully create a Linode with no …

M3-5584: Clear the region in Linode Create flow when switching between Create tabs

---

packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddDeviceDrawer.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallLanding/AddFirewallDrawer.tsx
packages/manager/src/utilities/grants.test.ts
packages/manager/src/utilities/grants.ts

- Filters out `ready-only` Linodes from the `Firewall Create Drawer` and `Add Linode to Firewall Drawer` for restricted users. 
- We are doing this because the API does not allow restricted users to create firewalls with Linodes the user does not have permission to modify. The API error message for this was ambiguous and this change will result in a more useable experience for restricted users using firewalls.
- Have a **primary account with full permission** and a **restricted user** with **read only permission on a Linode**
- Give the restricted user has permission to create firewalls
- On the restricted user, try to create a Firewall and attempt to attach a Linode you have `read-only` permission on
- You should not see this Linode in the dropdown
- You should see a note in the dropdown …

M3-5435: Filter `read_only` Linodes From Firewall Select For Restricted Users

---

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
packages/manager/src/queries/stackscripts.ts

Marketplace apps take a few seconds to load bc the stackscripts API endpoint is slow.
This PR uses React Query to prefetch and cache the apps so that we only have to load the endpoint once
- Hover over Marketplace in the nav bar and confirm that a network request to stackscripts is made
- Go to `/linodes/create?type=One-Click` via url and wait for the apps to load. Go somewhere else, and then go back. The apps should display without loading

M3-5874: Improve Marketplace loading

---

packages/manager/cypress/support/index.js
packages/manager/cypress/support/request-tracking.ts

Tracks the number of Linode APIv4 requests made and prints the total to the Cypress log after each test. It also lays the groundwork to add a maximum request threshold and to begin failing tests if they exceed that value.
You can play with the constants in `request-tracking.ts` to tweak the behavior and thresholds for request tracking. Right now I have the max number of requests set to `null` so that no tests fail, but once we have a better understanding of the number of requests that are typical for our tests we can set an appropriate value for the max.
Run manager with `yarn up`, then:
```
yarn cy:debug
```
Run any test, and observe that the total number of Linode APIv4 requests is shown in …

(Experimental) Detect excessive Linode APIv4 requests during Cypress tests

---

packages/manager/src/factories/billing.ts
packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
packages/manager/src/features/Billing/PdfGenerator/utils.ts

This fixes the invoice formatting issue that occurs when any of the (sub)totals listed at the bottom of the invoice overflow their column.
This change removes the hardcoded column width (which was `30` units) and implements new logic to calculate the final widths of the columns.
1. Enable MSW
2. Modify the [mocked invoice values](https://github.com/linode/manager/blob/develop/packages/manager/src/factories/billing.ts#L40-L52) to correspond with what's described in M3-5831.
3. Navigate to `/account/billing` and click _Download PDF_ for any of the listed invoices
4. View the generated PDF and confirm that formatting issue is fixed
5. _(Optional)_ Continue modifying the [mocked invoice …

M3-5831: Fix invoice formatting issue

---

packages/manager/src/factories/stackscripts.ts
packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/AppInfo.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.test.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx

Adds the app logo to the header of the setup form if the app has a setup form.
Tasks: 
1. Navigate to the Marketplace
2. Click on an App that has a setup form like `Wordpress`
3. Ensure the App logo is shown to the left of the paper's header

M3-5869: Marketplace UI Refinement: Create form

---

packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx

Under certain circumstances outlined in the ticket, a user would see this screen when navigating to the "Backups" tab of the Linode Detail page:
This PR fixes this bug.
More in-depth explanation and steps for testing are in the Slack thread in the team channel.

M3-5143: Fix Linode Backups tab error

---

packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.style.ts

This fixes an issue where the "Copy IP" button in the Linodes landing page, Linodes "Network" tab, and Node Balancer landing page are not visible when they have keyboard focus.
Currently, these buttons are only visible when the user hovers their cursor over the corresponding table row. This change makes it so that the buttons are visible on hover _and_ on keyboard focus.
**What are the steps to verify the changes?**
1. Navigate to the Linode landing page (create a Linode if one does not already exist)
2. Confirm that "Copy IP" button is visible when you hover your cursor over the row
3. Confirm that "Copy IP" button is visible when you navigate to it via keyboard
4. Repeat for the Linode details page "Network" tab, and Node Balancers landing page

M3-5910: Make "Copy IP" buttons visible on keyboard focus

---

packages/manager/src/features/Users/UserDetail.tsx

In prod, if you're on the "Users & Grants" tab on the Account page, click on "User Profile" for a user, click on the "User Permissions" tab, and then use the browser Back button to navigate back, you'll observe odd behavior: the tab doesn't switch, and if you hit the Back button enough, you'll go back further than expected.
The changes I made bring the behavior more in line with what we see on the Object Storage landing page. It's not ideal because it still takes two clicks of the browser Back button to get to the first tab, but this seems to be either a problem with ReachTabs or the way we're implementing it.
Test out the "Users & Grants" --> "User Profile" --> "User Permissions" path and then the reverse using the browser Back button. You shouldn't get stuck as much now.

M3-4919: Fix browser Back button behavior on the User Permissions tab

---

packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectAppPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx

- When an app is passed as a query param for Linode creation, scroll to the selected app in the list
- This helps clearly show users what app they have selected from a redirect
- If this new scroll didn't happen, users would be very confused if they were redirected from the `linode.com` site after finding an app they want to deploy
- This ticket requests that we don't open the details drawer when coming from the linode.com site but that change needs to be made on their end. I will make sure that change is made
https://user-images.githubusercontent.com/6440455/183512901-3a4dba53-fa1a-4a86-b142-e72f004d73c0.mov
- Visit a link like `http://localhost:3000/linodes/create?type=One-Click&appID=607488` and observe scroll behavior

M3-5875: Marketplace App Selection Scrolling based on Query Params

---

packages/manager/cypress/tsconfig.json

- Fixes issues with Cypress resolving `@linode/api-v4` and `@linode/validation`
- This ended up being an issue because Cypresse's use of webpack 4 does not seem to respect our new `exports` field in the package.json of `@linode/api-v4` and `@linode/validation`. To combat this, we will use an alias to force all imports of  `@linode/api-v4` and `@linode/validation` to use the proper file. Over time as Cypress updates things internally, I would expect this issue to go away and for us to no longer need this alias. 
- Remove old `@linode/api-v4` and `@linode/validation` dependencies
```
rm -rf packages/api-v4/lib && rm -rf packages/validation/lib && rm packages/api-v4/index.js && rm packages/api-v4/index.d.ts && rm packages/validation/index.js && rm packages/validation/index.d.ts
```
- Run …

Fix Cypress Testing with new `api-v4` and `validation` changes

---

packages/manager/cypress/plugins/index.js

This is a small tweak that changes the way Cypress reads environment variables on startup. Currently, only the `.env` file gets read. This change allows those values to be overridden by or supplemented with the process's environment variables.
Run the tests without specifying any environment variables to confirm that this doesn't break our existing setup. Once a few tests pass, you can quit the process.
```
yarn cy:run
```
Then run the tests with an invalid `MANAGER_OAUTH` value to confirm that you can override the `.env` file. The tests are expected to fail, so you can quit the process once you start seeing failures.
```
MANAGER_OAUTH=intentionallyinvalidvalue yarn cy:run
```

M3-5809: Allow environment variables to override .env in Cypress

---

packages/manager/src/features/Images/ImageSelect.tsx
packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx
packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx

Add an "Any/All" option in the StackScript Create flow in the "Target Images" dropdown.
On the StackScript Create page, select "Any/All" for the "Target Images" dropdown. Ensure that no other images can be added. Also test the reverse, i.e., selecting other images and then selecting "Any/All"—doing the latter should clear the other selections out.
Confirm that creation goes through as expected.

M3-5880: "Any/All" option in StackScript Create flow

---

packages/api-v4/src/account/types.ts
packages/manager/src/__data__/account.ts
packages/manager/src/components/TableContentWrapper/TableContentWrapper.test.tsx
packages/manager/src/components/TableContentWrapper/TableContentWrapper.tsx
packages/manager/src/components/TableRowEmptyState/TableRowEmptyState.tsx
packages/manager/src/factories/account.ts
packages/manager/src/features/Account/AccountLanding.tsx
packages/manager/src/features/Billing/BillingDetail.tsx
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.test.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentInformation.tsx
packages/manager/src/features/Billing/BillingPanels/PaymentInfoPanel/PaymentMethods.tsx
packages/manager/src/features/Billing/billingUtils.ts

Updates UI in `/account/billing` for Akamai customers
- Hide Make a Payment/Add Payment Method buttons and Payment Methods
- Added information banner to page and text to Payment Methods paper and Billing & Payments table
- Changed Accrued charges tooltip text
Check the `/account/billing` page as a Linode user and as an Akamai user (reach out for acc info)
```
yarn test PaymentInformation TableContentWrapper
```

M3-5899: UI changes for Akamai customer invoicing

---

packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptRow.tsx

- If an image has `any/all` as a compatible image, display `Any/All` as the only `Compatible Images` in a normal font
- Create a Stackscript with `any/all` as the compatible images in dev
- View it from StackScripts landing (`http://localhost:3000/stackscripts/account`)
```
curl -X POST \
-H "Authorization: Bearer [token]" \
-H "Content-Type: application/json" \
-d '{ "images": ["any/all"], "label": "test", "script": "#!/bin/bash" }' \
https://[dev api domain]/v4/linode/stackscripts | json_pp
```

M3-5881: Add `Any/All` Option on StackScripts Landing

---

packages/manager/src/components/StackScript/StackScript.tsx

- Shows an `Any/All` chip when a StackScript has `any/all` as its images
- Create a StackScript with `any/all` as the compatible image
- Verify that `Any/All` shows up under `Compatible Images`
```
curl -X POST \
-H "Authorization: Bearer [token]" \
-H "Content-Type: application/json" \
-d '{ "images": ["any/all"], "label": "test", "script": "#!/bin/bash" }' \
https://[dev api domain]/v4/linode/stackscripts | json_pp
```

M3-5882: Show `Any/All` Chip on StackScripts Details

---

packages/manager/src/features/StackScripts/StackScriptForm/StackScriptForm.tsx

- Revised tooltip for "Target Images" dropdown to include `"Any/All" allows you to use private images.` at the end
- Revised tooltip for "Label" field to state requirements (3-128 characters)
- Removed tooltip for "Description" field
Visit the StackScript Create and StackScript Edit pages and verify the changes above
~~I'm going to rebase to `develop` again once https://github.com/linode/manager/pull/8499 is merged in since the commit history includes commits from the Cypress PR somehow...~~ done

M3-5902: StackScript Create tooltips edits

---

packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx

- Allow users to deploy Linodes from StackScripts with Private Image
- Refactor `FromStackScriptContent.tsx` to a FC 
- Changes `all` variant of `<ImageSelect />` show private images first
- **Note**: This will also affect the Linode Rebuild Image input, but I think this is for the better to show private images first
- Create a StackScript with a Private Image #8499
- Try to deploy a Linode using that private image on `http://localhost:3000/linodes/create?type=StackScripts`

M3-5884: Linode Create - Deploy StackScripts with Private Image

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx

- Fixes bug relating to UDF Input fields clearing when Deploying a Linode from an Account or Community Stackscript that has UDFs
- This bug was my bad. I rewrote a Class component to a functional component and overlooked the fact that the class component was a PureComponent which handles prop updates differently
- Test Deploying a Account or Community Stackscript at `http://localhost:3000/linodes/create?type=StackScripts&subtype=Community` and ensure all types of UDF field configurations work
- Ensure the new `any/all` image option still works as expected

Hotfix StackScripts User Defined Field Input Bug

---

packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
packages/manager/src/utilities/ga.ts

Adds google analytics events for search and filtering on the marketplace page.
1. Navigate to the marketplace page.
2. Click on the app search bar.
3. Ensure that a GA event is sent in the network tab of the developer tools
4. Click the category dropdown
5. Select a category
6. Ensure that a GA event is sent in the network tab of the developer tools

M3-5911: Marketplace UI Refinement: Searching and filtering analytics

---

packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx

- Updates the documentation link in the Linode `Power Off` Dialog to link to the correct place in the Linode docs site
- **🚫 Old:** https://www.linode.com/docs/platform/billing-and-support/how-linode-billing-works/#if-my-linode-is-powered-off-will-i-be-billed
- **✅ New:** https://www.linode.com/docs/guides/understanding-billing-and-payments/#will-i-be-billed-for-powered-off-or-unused-services
- Click to Power off on a Linode that is `Running` to see the following dialog
- Verify that the link in this dialog brings you to the `Will I Be Billed For Powered Off or Unused Services?` section in the Linode docs

M3-5871: Update `Power Off` Linode Dialog Accrued Changes Documentation Link

---

packages/manager/src/features/linodes/LinodesDetail/HostMaintenanceError.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeResize/LinodeResize.tsx

Fixes apostrophes for Linode Resize and Host Maintenance errors
Before
After
Set the `disksError` and `hostMaintenance` errors to true in `LinodeResize.tsx` and then check the modal

M3-5816: Fix apostrophes in Linode Resize and Host Maintenance error

---

packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx

Following up on https://github.com/linode/manager/pull/8513, this PR addresses an edge case bug revealed by some E2E test failures.
Essentially, when `preferences?.type_to_confirm` (the value that gets passed to the `visible` prop of the `TypeToConfirm` component) was `undefined`, the TTC input did not appear and the language in the instruction text did not match. By treating `visible` as true if it isn't explicitly false, we get the desired and expected behavior.
Confirm that:
1. When TTC is enabled, you see the text field and `To disable type-to-confirm, go to the Type-to-Confirm section of My Settings.` below it
2. When TTC is disabled, you see only the text `To enable type-to-confirm, go to the Type-to-Confirm section of My Settings.`
in the modals for the Rebuild Linode, Resize …

Fix Type-to-Confirm edge case bug

---

packages/manager/src/components/SupportLink/SupportLink.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketDrawer.tsx
packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx
packages/manager/src/mocks/serverHandlers.ts

- Adds Volume Status to the Volumes Landing Page
- Adds initial support to pre-populate the support ticket modal with a pre-selected entity
- Check Volumes Landing for Volume statuses
- Use the MSW to see all possible states

M3-5635: Volume Status on Volumes landing

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx

- Show a `Delete` button for Private IPv4 addresses on a Linode
- Spin up a Linode in dev
- Add a Private IP address
- Verify that you see a `Delete` Button and that you can successfully delete the private IPv4 address

M3-5927: Allow Deletion of Private IPv4 Addresses

---

docker-compose.yml
packages/manager/cypress/plugins/index.js

This builds off the improvements from PR #8490, and accomplishes two things:
- Passes Cypress and Cloud-related environment variables from the host environment (Jenkins, soon) to Docker when running tests
- Allows Cypress to run when no `.env` file is present (currently Cypress stops if it cannot load the file)
I've confirmed that the `docker-compose.yml` changes work as expected in Jenkins (feel free to reach out and I can refer you to the related test project and jobs where these changes were applied and demonstrated to work).
To test the `.env` file changes, do the following:
1. Run Cypress as-is and confirm that it behaves as expected (i.e., existing configurations are not broken)
2. Temporarily rename your `.env` file, run Cypress, and confirm that it does not exit upon failing to …

Improve Cypress/Docker Environment Variable Handling

---

packages/manager/src/eventMessageGenerator.ts
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx

- Adjust day mapping so that Monday through Sunday is 1 through 7, respectively
- Change `status` field in `eventMessageCreators` from `notification` to `finished` for `database_update` notification, per confirmation with the API team. This ensures the correctly-worded notification is displayed in the drawer and on the Events landing page.
- Move database-related events in `eventMessageCreators` so that the list is (more) alphabetical order

M3-5931: Fix database maintenance window mapping and database_update notification message

---

packages/manager/src/featureFlags.ts
packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx
packages/manager/src/features/GlobalNotifications/TaxCollectionBanner.tsx

Changes the format we expect from the `taxCollectionBanner` flag to allow regions within the same country to have different dates. Also only displays the banner for up to 5 weeks after the date specified in the flag data. The new data shape keeps the top level `date` field. This is now used as the default date for all regions in the list. The region list has been changed from a list of strings to a list of objects. The objects have two properties `name` and `date`. The `name` field is the string that we use to denote the region. The `date` field is used to specify a date that is different from the default one specified for the country. If a region has a date specified that will always override the country level one.  
Check ticket for testing procedure

M3-5843: Allow each state to have their own date for a Tax Collection Banner

---

packages/manager/cypress/integration/account/two-factor-auth.spec.ts
packages/manager/cypress/support/intercepts/profile.ts
packages/manager/cypress/support/ui/index.ts
packages/manager/cypress/support/ui/toggle.ts
packages/manager/cypress/tsconfig.json

Adds Cypress integration tests for 2FA. Confirms UI flows for enabling, disabling, and resetting 2FA, and confirms that 2FA cannot be enabled when security questions are not answered.
**How do I run relevant tests?**
`yarn up`, and then:
```
yarn cy:run -s "cypress/integration/account/two-factor-auth.spec.ts"
```
Or, if you want to run them interactively:
```
yarn cy:debug
```
And search for `two-factor-auth.spec.ts`.

M3-5850: Add Cypress tests for two-factor authentication

---

packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.test.tsx
packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx

- Pulls timezone offsets from [Luxon](https://github.com/moment/luxon/) so that they are more accurate
- Previously, we pulled them from the static `timezones.ts` file, which did not incorporate **Daylight Savings Time**
- Rewrites `TimezoneForm.tsx` to be a FC and use hooks
- Rewrites `TimezoneForm.test.tsx` to use React Testing library and newer patterns
> **Note**: Notice how the offset for EST is -5
> **Note**: Notice how the offset for EST is -4. This is because it is taking into account the fact we are current in daylight savings time. If you do some Googling, you will see that this is currently the correct offset
- Go to `http://localhost:3000/profile/display` 
- Check functionality of the timezone input for …

M3-5787: Improve Timezone Offsets by Pulling Them From `Luxon`

---

packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
packages/manager/src/features/linodes/LinodesLanding/ListView.tsx

This is a first stab at reducing unnecessary re-renders in the LinodesLanding page. Through the Profiler, I found that LinodeRow re-rendered unnecessarily when clicking an action such as Power on/off in the action menu due to the `openTagDrawer` prop changing. This shouldn't be happening since we no longer show tags in list view. So, I went ahead and removed the tag code.
1. Go to the Linodes landing page while on list view (this should be the default view)
2. Start profiling, click on an action in the action menu such as Power on/off for a Linode
3. Stop profiling after you click the action
4. Verify that LinodeRow is no longer being re-rendered

M3-4882: Reduce unnecessary re-renders in LinodesLanding

---

packages/manager/src/components/Drawer/Drawer.tsx

Fixes an issue where long titles cause a drawer's close button to get forced to a new line:
**Before:**
**After:**
This also tweaks the CSS slightly so that resources with a long but single-word name still break as expected:
1. Create a Linode with a long label and visit its details page
2. Navigate to the "Storage" tab, click "Create Volume"
3. Confirm that the Drawer title has a line break, but the Drawer close button is in its expected place (top-right corner)
4. Confirm that Drawer behaves as expected with regular length titles as well
This command runs a selection of E2E tests which include drawer interactions:
(Took about 2 and a half minutes on my machine)
```bash
$ yarn cy:run -s …
```

M3-5166: Fix close button wrapping for Drawers with long titles

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx

Adds GA events to the docs links on the empty Database landing page.
1. Navigate to an empty Database landing page
2. Click the _Need help getting started? Browse database guides_ link
3. Ensure that it sends a GA event with the contents: `{ category: 'Managed Databases landing page empty', action: 'Click:link', label: 'Need help getting started? Browse database guides.'}`
4. Click the `Create Database Cluster` button
5. Ensure it sends a GA event with the contents: `{  category: 'Managed Databases landing page empty', action: 'Click:button', label: 'Create Database Cluster' }`

M3-5906: Events tags on Managed Databases landing page

---

packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx

- Makes the Database Engine icon **white** when the option is focused in the Engine Select component
- I chose to do this with a css filter on the svg to prevent us from needing to include more assets
- Test the `Database Engine` select on `http://localhost:3000/databases/create`
- Verify that the icon is easy to see when the option is focused
- Try getting the `Database Engine` Select into weird states and verify that the icon looks correct

M3-5891: Make Database Engine Icons More Visible on Focus

---

packages/manager/src/components/DocsLink/DocsLink.tsx
packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx

Adds contextual help to the Linode create flow. In particular it adds a link to the _Getting Started_ and _Choosing a Compute Instance Type and Plan_ docs. For the time being I altered the `DocsLink` component to have a prop called `onClick` that allows the developer to specify what should happen when a user clicks the link in addition to the base functionality of the link. Another alteration I made was to the `TabbedPanel` component. I added the `docsLink` prop to allow the developer to add a `DocsLink` on the same paper as the panel across from the header.
1. Navigate to the Linode create page
2. Ensure at the top right of the page there is a `DocsLink` labeled _Getting Started_ and that it links to the _Getting Started_ doc
3. Ensure that a GA event is sent that has the content of `{ …

M3-5829: Add contextual help to linode create page

---

packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx

Adds GA events to the docs links on the empty Linode landing page.
1. Navigate to an empty Linode landing page (you may need to enable mocks)
2. Click the _Learn more about getting started_ link
3. Ensure that it sends a GA event with the contents: `{ category: 'Linodes landing page empty', action: 'Click:link', label: 'Learn more about getting started'}`
4. Click the _visit our guides and tutorials_ link
5. Ensure it sends a GA event with the contents: `{  category: 'Linodes landing page empty', action: 'Click:link', label: 'visit our guides and tutorials' }`
6. Click the `Create` button
7. Ensure that it sends a GA event with the contents: `{  category: 'Linodes landing page empty', action: 'Click:button', label: 'Create Linode' }`

M3-5905: Events tags on Linodes landing page

---

.github/workflows/e2e_schedule_and_push.yml

This upgrades the version of the Cypress GitHub Action that we use from v2.x to v4.x so that we can support Cypress 10. It additionally removes the `headless` option, since headless is the default as of Cypress 8.x.
Once this is merged, I can re-run the scheduled action and hopefully the tests will run as expected. There is the potential that this won't fix the problem (as I haven't been able to test it directly), but it should not make the situation any worse than it already is.

Upgrade Cypress action for Cypress 10 support

---

packages/api-v4/src/linodes/types.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeConfigs.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
packages/manager/src/store/linodes/config/config.reducer.test.ts

Users were able to, in Classic Manager (and presently via the API), select a disk for `initrd`. This PR adds a dropdown in the Linode Config modal in the "Block Device Assignment" section for initrd. The dropdown is populated by disks with an initrd filesystem.
- Create a few disks with a filesystem type of "initrd"
- Add or edit a Linode Configuration. Confirm that the "initrd" field is visible in the modal and that it is populated with any disks on that Linode with a filesystem type of "initrd".
- Select a disk and save the changes. Go through the modal flow a few times to ensure the correct disk is saved for initrd and shows up the next time you open the modal.

M3-4935: Add initrd selection to Linode Config modal

---

.gitignore
packages/api-v4/package.json
packages/manager/config/jest/typescriptTransform.js
packages/manager/package.json
yarn.lock

This switches the transformer used to transpile our Jest tests from `ts-jest` to [`@swc/jest`](https://swc.rs/docs/usage/jest). I additionally included the [`jest_workaround`](https://www.npmjs.com/package/jest_workaround) plugin which allows us to mutate ES modules -- something that `ts-jest` allows but `@swc/jest` does not, and which is required for `jest.spyOn(...)` to work.
On my machine, this reduces manager's (uncached) Jest run time from about **8 minutes** to around **100 seconds**.
Confirm that tests work as expected for manager and api-v4:
1. Run `yarn` to install the new dependencies
2. Run `yarn test --clearCache` to clear Jest's cache
* This is not strictly necessary, but makes it …

Use `swc` to run Jest tests

---

packages/manager/cypress/e2e/account/change-username.spec.ts
packages/manager/cypress/plugins/index.js
packages/manager/cypress/support/intercepts/profile.ts

This makes some improvements and additions to the Cypress username update test to reduce flakiness:
- Disables Google Safebrowsing API requests during tests. These get made automatically by Chrome (not Cloud Manager), and occasionally cause or contribute to test timeouts
- Improves the structure of the existing test (waits for GET requests to be made and for username input field to render before interacting with the page)
- Mocks the username update request and confirms that the UI updates accordingly (currently, the test does not click the "Save Changes" button, so it really is not validating much)
- Adds a new test to confirm that the account username can be changed via the Profile Display page
**What are the steps to reproduce the issue or verify the …

Improve username update E2E test flakiness

---

packages/manager/.storybook/manager-head.html

I was planning to write a ticket to capture this issue, but figured it'd probably just be quicker to fix it while it's still in mind.
This sets a max width of `260px` on the Storybook logo. I chose `260px` mostly arbitrarily because I thought it looked good, so definitely open to feedback and tweaks.
Run `yarn storybook`, open Storybook at `localhost:6006` and resize the sidebar. Confirm that the logo stops growing once it reaches a maximum width of 260 pixels.
Note: If `yarn storybook` doesn't show the logo or CSS changes, you may have to run `yarn storybook --no-manager-cache`.

Set Storybook logo max width

---

packages/api-v4/src/firewalls/types.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.test.ts
packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
packages/manager/src/features/Firewalls/shared.ts
packages/validation/src/firewalls.schema.ts

- Adds support for `IPENCAP` in Cloud Manager
- 🌎[Linode API Documentation on Firewall Rules](https://www.linode.com/docs/api/networking/#firewall-rules-update)
- Create or have a Linode Firewall
- Add a rule to that Firewall that uses `IPENCAP` as the `Protocol`
- Confirm that you can add an `IPENCAP` firewall rule
- Test many different configurations of firewall rules and ensure Cloud Manager's validation holds up
- Make sure you are pressing `Save Changes` to commit your firewall changes and get validation from the API

M3-5937: Add Firewall Support for `IPENCAP` Protocol

---

packages/manager/src/features/ObjectStorage/ObjectUploader/reducer.ts

Fix Cloud Manager crashing when overwriting an Object Storage file that already exists. This was because the `foundFile` variable was being defined and used in two different cases, but was not being correctly scoped with curly braces.
1. Upload an object to a bucket.
2. Upload it again.
3. Click `Replace`

M3-5950: Fix Object Storage overwrite error

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx

- Adds ARIA labels to the previous/next buttons on the Network Transfer History graph shown on the "Network" tab of the Linode details page
- The labels are formatted _Show network transfer history for \<Month\> \<Year\>_, or _Show network transfer history for last 30 days_ (whichever is applicable) -- very open to feedback for this language
- Disables the previous and next buttons when there is no data left to navigate to
- We already apply a disabled class to the buttons in these situations, this change just makes it apparent to screen reader users that the buttons are disabled
- Modifies a utility function and updates tests accordingly
To verify button ARIA label and disabled state:
1. Enable …

M3-5903: Add ARIA labels for network transfer history previous/next buttons

---

packages/manager/.eslintrc.js
packages/manager/package.json
packages/manager/src/components/LineGraph/LineGraph.tsx
packages/manager/src/components/LongviewLineGraph/LongviewLineGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/ApacheGraphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Graphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLGraphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/CPUGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/DiskGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/LoadGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/MemoryGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/OverviewGraphs/NetworkGraph.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx
packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesGraphs.tsx
packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
yarn.lock

This improves screen reader accessibility for graphs used throughout Cloud Manager. It accomplishes this by making these changes:
* Graphs can be focused via keyboard navigation
* Graphs now have the `graphics-document` ARIA role. This is still technically a [WAI proposal](https://www.w3.org/TR/graphics-aria-1.0/), but has wide support among browsers and assistive tech.
* `eslint-plugin-jsx-a11y` doesn't yet recognize this role and related roles, but it seems like support will be added in an upcoming release
* Each graph has an ARIA label describing its purpose
For now, the actual contents of the graphs are still inaccessible to screen readers and other assistive tech -- we have another ticket to improve that aspect later.
**What are the steps to reproduce the …

M3-5904: Improve graph accessibility

---

docs/development-guide/08-testing.md

This improves our first time setup documentation for running Cypress locally. Specifically, it breaks the "Running the E2E tests" section into two sections: "First Time Setup" and "Running the End-to-End Tests", and fleshes out the instructions related to PAT generation and `.env` config.
In the near future I plan to break up this documentation further, adding a new "Writing End-to-End Tests" section and moving some of the links, code examples, and intercept information there (along with additional/updated information).
* Review changes for typos, inaccuracies, etc.
* Review the steps from the perspective of a newcomer and try to identify gaps, confusing instructions, etc. that could be improved

Improve first time setup docs for Cypress

---

packages/manager/src/components/AccessPanel/AccessPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.test.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx

Fixes the bug causing misalignment of Password and SSH Key fields by removing the default MUI theme padding.
For consistency, applied a bottom margin to match the top margin once bottom padding was removed.
Using the browser Developer Tools, view the component with the React Developer Tools > Components tab and search for 'AccessPanel'. Verify that the component's padding has been removed and a bottom margin added in its place.

M3-5552: Fix Linode Add Disk Drawer UI width bug

---

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx

Currently in Firefox, if you try using the Tab key to navigate through the Linode or Database Create flow, you run into an issue when you reach the plan selection table: there is no indicator of which row has focus. You may have to press Tab many times to get through the listed plans and to the next field, but you do not know where you are in the table because of the lack of a visual indicator.
This PR addresses this by highlighting the row that has focus.
In Chrome and Firefox, use the Tab key to navigate to and through the Linode and Database plan panels in the Create flow. You should observe a visual indicator for the row with focus. If you use the mouse to click the radio button for a row, you should also see the visual indicator.

M3-5900: Visual indicator when navigating Linode and Database plan selection tables

---

packages/manager/public/index.html
packages/manager/src/components/EnhancedSelect/EnhancedSelect.css
packages/manager/src/components/EnhancedSelect/Select.styles.ts
packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx
packages/manager/src/components/EnhancedSelect/components/SingleValue.tsx
packages/manager/src/components/ImageSelect/ImageOption.tsx
packages/manager/src/themeFactory.ts

- In Safari on iOS, the browser zooms in when a user clicks into any TextField. This is very annoying and not great.
- At first I thought it was an issue with our `<meta name="viewport" />`, but it's not the main issue.
- After some research I found that Safari will do this if your input font size is less than 16px.
- The fix was to make all inputs have a font size of `1rem` / `16px` on `XS` screen sizes
https://user-images.githubusercontent.com/6440455/178029324-c51c5c89-ed39-4ee1-8759-dfc315506630.mp4
https://user-images.githubusercontent.com/6440455/178029338-323030c5-453e-4997-8100-cc3729f21bec.mp4
- Test Cloud Manager's inputs in your computer's browser
- Test Cloud Manager on your mobile phone's browser

M3-5889: Safari on iOS Accessibility and Zoom Fix

---

packages/manager/.env.example
packages/manager/src/factories/account.ts
packages/manager/src/factories/kubernetesCluster.ts
packages/manager/src/features/Kubernetes/ClusterList/ClusterList.tsx
packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.test.tsx
packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx
packages/manager/src/features/Kubernetes/kubeUtils.ts

- Add HA chip to the Kubernetes landing page
- Update HA chip size in the Kubernetes details page to match the landing page chip
- Minor refactoring
Check the view in `/kubernetes/clusters` and `/kubernetes/clusters/<cluster_id>/summary`
```
yarn test ClusterRow
```

M3-5764: Add HA chip to Kubernetes landing page

---

packages/api-v4/src/support/types.ts
packages/manager/src/factories/support.ts
packages/manager/src/features/Support/ExpandableTicketPanel.tsx

This adds the `friendly_name` property to the `SupportReply` interface. This will be displayed on ticket replies by Linode support instead of showing their current handle. 
*This is contingent on changes to the API.*
The proposed API changes will always return a `friendly_name`; it defaults to the `created_by` value.
I've already added the `friendly_name` property to the `supportReplyFactory` for mock data; you can see it populating with the name "Lucy" for any replies created by `support-staff`.

SD-168: Mask admin usernames in the Cloud Manager

---

packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx

When a LKE cluster has only one remaining node pool disable the the node pool delete button.  Also adds a tooltip to the disabled delete button explaining why the button is disabled.
1. Navigate to a LKE cluster
2. Ensure that when there are more than 1 node pools the delete node pool buttons are active
3. Ensure that when there is only 1 node pool the button is disabled
4. Ensure that when hovering over the button a tooltip explaining why the button is disabled appears

M3-4792: Handle attempted deletion of last LKE pool

---

packages/api-v4/src/linodes/types.ts
packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx
packages/manager/src/factories/linodes.ts
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/mocks/serverHandlers.ts

Add support for `prodedicated` plan types in the Linode Create flow
Go to `/linodes/create` while pointing to dev or turn on the mocks

M3-5901: Support Pro Dedicated Plans

---

packages/manager/src/features/linodes/LinodesCreate/AttachVLAN.tsx

Update the link regarding Configuration Profiles in the "Attach a VLAN" section in the Linode Create flow.
The link formally directed users to this [deprecated guide](https://www.linode.com/docs/guides/disk-images-and-configuration-profiles/) but it should now direct them [here](https://www.linode.com/docs/guides/linode-configuration-profiles/).
Check that the link in the Linode Create flow brings users to the correct guide titled "Managing Configuration Profiles on a Linode".

M3-5960: Update link regarding Configuration Profile in "Attach a VLAN" section

---

packages/validation/src/linodes.schema.ts

Updates the linode schema to support new linode label 64 character limit, which was formerly 32 characters.
When a linode label exceeding the valid length is entered, the existing message is currently returned as input validation:
With these changes, the input validation message for a linode label exceeding the new valid length now displays the limit:
1. Generate a label that is a string > 32 characters and <= 64 characters. 
2. Create a new linode with the label. Confirm that no error message displays; the linode is created successfully.
3. Edit the linode's label to be a different string > 32 characters and <= 64 …

M3-5626: Update linode label to 64 char max

---

packages/manager/cypress/e2e/domains/smoke-create-domain-records.spec.ts

Fixes our failing domain CAA record test by supplying a random domain name (rather than a regular old random string) when creating the record. This is necessary as of [API v4.138.0](https://developers.linode.com/changelog/#API-4.138.0), which implements validation for CAA record values.
To reproduce the issue, run the following command against `develop`. To verify the fix, run the same command with this branch checked out:
```
yarn cy:run -s "cypress/e2e/domains/smoke-create-domain-records.spec.ts"
```

Update Cypress domain CAA record test to use domain name value

---

packages/manager/cypress/e2e/volumes/attach-volume.spec.ts

This temporarily disables the volume detach E2E tests, one of which has been failing and the other has issues preventing it from being useful (it detaches a volume before it's finished being attached).
Once the volume detach issue (which is unrelated to Cloud Manager) is fixed, I'll re-enable both of these tests (and fix the one that needs fixing).
Disabling these tests should help Cypress run faster, since the failing test and its retries add several minutes to Cypress's run time.
Run the following command, and ensure that both detach tests are skipped.
```bash
yarn cy:run -s "cypress/e2e/volumes/attach-volume.spec.ts"
```

Temporarily skip volume detach E2E tests

---

packages/api-v4/src/request.ts

When the api-v4 package is used in a node script the User-Agent header is set to `linodejs`. It also provides users with the ability to prefix the new User-Agent with a custom string if they want to. This does not effect the HTTP requests made in cloud or when the package is used in a browser. 
Ensure that HTTP requests made via manager have their normal browser specific User-Agent.
Ensure that HTTP requests made by using the api-v4 package have `linodejs` set for their User-Agent.

M3-3166: [CHANGED] Custom User Agent

---

packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx

Makes the info button on Marketplace app cards keyboard navigable. Users can now select the button and expand the drawer to access information about the application.
https://user-images.githubusercontent.com/114685994/196762382-90ef0a0b-5101-4ae6-808f-b5836b54aebd.mov
1. Visit the Marketplace.
2. Use keyboard navigation to tab to a Marketplace app selection card.
3. Once a card is selected, press tab again and observe that the Info button is now focusable.
4. Press Enter and the drawer will open. Tab to the close button and press Enter; observe the drawer closes.
5. Enable a screen reader such as Voice Over, …

M3-5920: Make info button accessible via keyboard nav

---

packages/manager/package.json
yarn.lock

- Removes Babel because it is no longer needed
- We no longer depend on Babel to build Cloud Manager
- We no longer need Babel to transform for unit testing
- Test local development `yarn dev` and ensure it still works as expected
- Test building Cloud Manager for production `yarn build` and serving it with `yarn start:ci`
- Test Storybook development with `yarn storybook`
- Test building Storybook with `yarn build-storybook`

Remove unused `babel` dependencies

---

packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
packages/validation/src/account.schema.ts

Updates the Account schema to prevent an unnecessary error on the "Company Name" field when you try updating your billing contact info on an account that did not initially require certain information.
The easiest way to test this would be to create a new Cloud account using your Akamai email address. From that account, you can try editing your billing contact info (not the "Company Name" field) in prod and saving it to observe the unnecessary error on the "Company Name" field. On this branch, you should be able to make those initial changes without receiving an error for that field.

M3-5969: Prevent unnecessary error for `company` field when updating Account info

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/queries/stackscripts.ts

Marketplace wasn't really made to scale, so we were only getting the first page of Marketplace apps with a max of 100 results. This is an issue because we now have 102 apps through Marketplace but only the first 100 are showing; Yacht and Zabbix were no longer displayed.
This PR adds pagination support to get all the Marketplace apps
Go to Marketplace and ensure that the Yacht and Zabbix apps are showing

M3-5963: Add pagination support for Marketplace

---

package.json
yarn.lock

- Re-adds a resolution for `nth-check` for CVE-2021-3803
- I removed this in #8587 unintentionally, my fault!
- Rerun `yarn dev` and check Cloud Manager in general

Re-add `nth-check` Yarn Resolution for CVE-2021-3803

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx

The copy in the "Backup Schedule" section on the Backups tab of the Database detail page now reads, "A backup of this database is created every 24 hours and each backup is retained for 7 days."

M3-5968: Revised copy on Database Backups tab

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/components/Paginate.ts
packages/manager/src/factories/grants.ts
packages/manager/src/features/Users/UserPermissions.tsx
packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
packages/manager/src/mocks/serverHandlers.ts

- **Client-side** paginates user grants on `https://cloud.linode.com/account/users/:username/permissions`
- For larger accounts, this page will switch to a "Tab" mode
- For smaller accounts, this page will remain as is
https://user-images.githubusercontent.com/115251059/200047030-b4a1c459-496d-4727-a715-5dda239ecfbf.mov
https://user-images.githubusercontent.com/115251059/200046392-233d4533-452d-4695-902c-bf53d1cae64e.mov
- Test `https://cloud.linode.com/account/users/:username/permissions` in depth
- Turn on the MSW to simulate a large account

M3-5977: Improve User Permissions Page for Large Accounts

---

packages/manager/src/components/ActionMenu/ActionMenu.tsx
packages/manager/src/components/EnhancedSelect/components/SelectControl.tsx
packages/manager/src/components/HighlightedMarkdown/__snapshots__/HighlightedMarkdown.test.tsx.snap
packages/manager/src/components/TextField.tsx
packages/manager/src/components/core/Divider.tsx
packages/manager/src/components/core/Grid.ts
packages/manager/src/components/core/Grid.tsx
packages/manager/src/containers/SummaryPanels.styles.ts
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
packages/manager/src/features/Kubernetes/ClusterList/ClusterRow.tsx
packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx
packages/manager/src/features/Profile/LishSettings/LishSettings.tsx
packages/manager/src/features/Profile/SSHKeys/SSHKeyCreationDrawer.tsx
packages/manager/src/features/Volumes/VolumeDrawer/VolumeConfigForm.tsx
packages/manager/src/features/linodes/LinodesCreate/AddonsPanel.tsx
packages/manager/src/themeFactory.ts
packages/manager/src/themes.ts

- Fix UI regressions caused by the upgrade to MUI v5
- Open `https://cloud.linode.com` in one tab, and open this PR in another
- Compare the UI visually throughout the entire app
- Try to find any major UI discrepancies

M3-5935: Fix MUI v5 UI Issues

---

package.json

Removes two old scripts from `package.json` that are no longer used with Storybook. 
- Run `yarn storybook:e2e` and `yarn storybook:debug` from the base of the repo and verify that you receive a console error of "Command not found" for each. We removed the commands; they should no longer even attempt to run and then fail. 
- Run `yarn storybook` and `yarn build-storybook` to observe output looks normal.

Remove no-longer-used Storybook scripts from package.json

---

scripts/generate_changelog.py

Updates the `generate_changelog.py` script in the following ways:
- Allows the user to specify what sub-repo the changelog should be generated for
- Adds the new naming conventions form PR name standardization proposal 
- Automatically strips Jira labels from changelog
- Automatically inserts current date
the syntax for calling the script has changed it should now take this form
`python generate_changelog.py <version number> <origin> <repo to generate changelog for>`
The repo argument is optional and only needed to specify `api-v4` or `validation`
Ensure you can generate a changelog for the repos without error

M3-5501: [BUILD] Update the changelog generation script

---

packages/manager/package.json

Generates a Cobertura coverage report when running jest with the `--coverage` flag.
Run `yarn test --coverage` and confirm that the following file exists after it completes:
```
packages/manager/coverage/cobertura-coverage.xml
```

Enable Cobertura coverage report

---

packages/api-v4/src/volumes/types.ts
packages/manager/src/features/Volumes/VolumeAttachmentDrawer.tsx
packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
packages/manager/src/features/Volumes/VolumeTableRow.tsx
packages/manager/src/features/Volumes/VolumesLanding.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeStorage/LinodeStorage.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
packages/manager/src/queries/base.ts
packages/manager/src/queries/domains.ts
packages/manager/src/queries/volumes.ts

- Makes `http://localhost:3000/linodes/:id/storage` use React Query
https://user-images.githubusercontent.com/115251059/198066432-616af01d-d604-47a2-b6d3-2be813113bfd.mov
- Test all possible volume actions from `http://localhost:3000/linodes/:id/storage` 
- When testing, check back with the `http://localhost:3000/volumes` page to make sure the cache is updating properly as mutations occur
- Test volume actions `http://localhost:3000/volumes` and make sure `http://localhost:3000/linodes/:id/storage` remains up to date

React Query for Volumes - Linode Storage

---

packages/api-v4/src/stackscripts/types.ts
packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx

Add the ability to group StackScript user defined fields with custom labels (this will mainly be used to group Marketplace App setup inputs)
1. Create/edit a StackScript to include a UDF field with the Header set to "Yes"
2. Go to `/linodes/create?type=StackScripts` and select that StackScript
3. Confirm that the header you defined displays under Advanced Options
Example StackScript:
```
#!/bin/bash
#<UDF name="header_test" label="Test Group Header" default="Yes" header="Yes">
#<UDF name="disable_root" label="Choose the addons you'd like to add to this instance?" manyOf="Redis,Memcached, JetBackups, Desktop Environment,Cockpit,None," default="None" >
#<UDF name="disable_rot" label="Would you like Redis installed?" oneOf="Yes,No" default="No" >
#<UDF name="disable_roo" label="Which Stack …
```

Add ability to group StackScript UDFs with custom labels

---

scripts/generate_changelog.py
scripts/publish_changelog.sh

Automates the creation of PRs against linode developers repo for package changelogs.
1. Open a terminal to the root of the project repo
2. run `scripts/publish_changelog.sh <PACKAGE_NAME>`
replace `<PACKAGE_NAME>` with `manager`, `api-v4`, or `validation` 
3. Check the success message for the location of the generated file
4. Ensure generated file is properly formatted and has the correct content.

M3-5505: [DOCS] Automate developers site changlog PR

---

packages/manager/src/components/TypeToConfirm/TypeToConfirm.test.tsx
packages/manager/src/components/TypeToConfirm/TypeToConfirm.tsx
packages/manager/src/features/Account/EnableObjectStorage.test.tsx
packages/manager/src/features/Account/EnableObjectStorage.tsx

Implements type-to-confirm for object storage cancellation in the user's Account Settings.
**TTC enabled:**
**TTC disabled:**
https://user-images.githubusercontent.com/114685994/202314676-dfbcdef3-0265-4034-9ad1-f669646fd71a.mov
- If Object Storage is not already active, create a new Object Storage bucket to enable it. 
- Navigate to My Settings and ensure type-to-confirm is enabled.
- Navigate to Account Settings and click the Cancel Object Storage button.
- Observe the type-to-confirm pattern present on the Cancel Object Storage dialog.
- Navigate to My Settings and toggle the type-to-confirm setting to disabled.
- Navigate to Account Settings and click the Cancel Object Storage button
- …

M3-5461: Add Object Storage type to confirm

---

packages/manager/src/components/CheckoutSummary/CheckoutSummary.test.tsx
packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx
packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.test.tsx
packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
packages/manager/src/features/linodes/LinodesCreate/types.ts
packages/manager/src/utilities/stringUtils.test.ts
packages/manager/src/utilities/stringUtils.ts

When an OCA with a UDF regarding clusters is selected, display a notice regarding the number of clusters and the creation of an additional temporary node. Additionally, add text regarding the temporary node and pricing for multiple nodes to the Summary panel.
Notice:
Summary:
Test the OCA flow with an OCA with clusters and an OCA without clusters. The former should show features like the above screenshots; the latter should be unchanged from their current functionality.
StackScript deployments from other areas of the app should be tested as well to ensure they've not been adversely impacted.

M3-5996: Cluster Pricing UI updates

---

packages/manager/src/features/OneClickApps/AppDetailDrawer.test.tsx
packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx

- Refactors in `AppDetailDrawer.tsx` to prevent bugs
- Add support in `AppDetailDrawer.tsx` to support clusters
- Add relevant unit tests
1. Confirm that OCCs display in the drawer with the title being `[app name] Cluster` and that "Learn about database cluster" and "Set up Linode API token" links appear in the "Guides" section
2. Confirm that regular OCAs have not been adversely impacted by the changes and also that nothing weird happens when switching between selected apps

M3-5997: Update OCA drawer to support clusters

---

packages/manager/src/components/Placeholder/Placeholder.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.test.tsx
packages/manager/src/features/linodes/LinodesLanding/LinksSection.tsx

Adjusts spacing for the `Placeholder` component. This effects the spacing of all empty state landing pages across the app. Also removes the `Grid` component usage from the `Placeholder` component replacing it with `CSS Grid`. This should allow for a more consistent layout with a wide variety of content and screen sizes.
Ensure the empty state for all entities looks right. Try changing the window size and seeing how things collapse and expand.

M3-5958: [Changed] Landing page 2 column layout – adjust spacing

---

packages/manager/src/components/SelectionCard/CardBase.test.tsx
packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx

Adds the ability to add a chip to add components to the right of a card's heading. This is used to add a Chip to the right of the heading on the SelectionCards of one click apps that are targeted at clusters.
1. In a text editor open the `AppPanelSection.tsx` file
2. On line 53 set the value of `isCluster` to `true`
3. Navigate to the marketplace
4. Ensure Chip indicating that an app is deployed on a cluster is in the correct place.
`yarn test CardBase`

M3-5994: [Changed] One Click Cluster App Card

---

packages/manager/src/components/Notice/Notice.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx
packages/manager/src/features/linodes/SMTPRestrictionText.test.ts
packages/manager/src/features/linodes/SMTPRestrictionText.tsx
packages/manager/src/mocks/serverHandlers.ts

Adds two SMTP restriction notices to Cloud Manager for customers with _**accounts created on or after**_ the next release date.
Notice 1—at the bottom of the Linode create page 
Notice 2—on the Linode detail page, above tab set, with the Network tab selected
**Notice 1:**
Without EU agreement:
With EU agreement:
**Notice 2:**
- Turn on MSW to mock a user who created an account on the day of the next release.
Notice 1:
- Navigate to the Linode Create page. Scroll to bottom of page and observe SMTP text.
- Set the new linode's region to London, UK or Frankfurt, DE 
- Scroll to the bottom of the page and observe SMTP text and EU agreement text.
- Adjust the screen size and confirm that the …

M3-5991: SMTP add helper text

---

packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
packages/manager/cypress/support/ui/action-menu.ts
packages/manager/cypress/support/ui/toast.ts
packages/manager/cypress/support/util/random.ts

Adds flows to the machine image E2E test to verify that updating and deleting machine images works as expected.
I opted to add flows to the existing image creation test rather than creating separate tests since the data setup (i.e. creating an image) can take a minute or two.
Run `yarn dev`, and then run:
```bash
yarn cy:run -s "cypress/e2e/images/machine-image-upload.spec.ts"
```
And confirm that all of the tests pass.
To run the tests interactively, run `yarn cy:debug` and search for `machine-image-upload.spec.ts`.

M3-5922: Add machine image update and delete E2E tests

---

packages/manager/src/components/Placeholder/Placeholder.tsx

In PR #8615 a bug was introduced that caused empty state landing pages that had more than one action button to overlap the buttons. This PR fixes that by wrapping the buttons in a div and making that div flex with gap. This should help dealing with more buttons in the future as well.
Before:
After:
Navigate to domains and get it in an empty state
Ensure both buttons are visible and not overlapping
Change the screen size to a phone and ensure that the two buttons stack
run `yarn cy:run -s "cypress/e2e/domains/smoke-create-domain.spec.ts"`

Fix for two column layout placeholder button overlap

---

packages/manager/src/constants.ts
packages/manager/src/features/linodes/SMTPRestrictionText.test.tsx
packages/manager/src/features/linodes/SMTPRestrictionText.tsx
packages/manager/src/mocks/serverHandlers.ts

Updates the magic date of SMTP restriction notices to reflect a pushed release date. 
Toggle the MSW on (mocks have been updated with an `active_since` date of 11/30/22) and verify that the SMTP notice is visible on the bottom of the Linode Create and above the Network tab of the Linode Details page. Accounts created before this date should not show the notices. (More detailed steps are in #8621.)
`yarn dev` and then `yarn test SMTPRestrictionText` and confirm 6/6 tests pass.

Update SMTP notice magic date to match pushed release

---

packages/manager/Dockerfile
packages/manager/cypress.config.ts
packages/manager/package.json
yarn.lock

Upgrades Cloud Manager to use Cypress 11.
It doesn't seem like much has changed between Cypress 10 and 11, and most of the changes are focused on component testing rather than e2e testing.
```bash
yarn cy:run
```
I've run Cypress 11 locally and confirmed that our tests are still passing.

Upgrade to Cypress 11

---

packages/manager/src/constants.ts

- Updates the rates that Linodes are migrated at so that our Linode Migration estimates are more accurate
- Verify that the estimates in this PR are lower than estimates in production for the same Linode
- There is no promise that this estimate is correct, but now it should be closer to the actual time it takes to migrate a Linode

M3-5511: Improve Linode Migration Time Estimates

---

packages/api-v4/src/images/types.ts
packages/manager/src/components/ImageSelect/ImageSelect.test.tsx
packages/manager/src/components/ImageSelect/ImageSelect.tsx
packages/manager/src/constants.ts
packages/manager/src/factories/images.ts

Goal is to replace manual process of setting flags in DB to get suffix ( "deprecated") added to distro's  in the manager.
- Automatically filters deprecated images 
- Automatically Adds suffix "deprecated"
**Before:** 
**After:**
- Navigate to route /linodes
- Click on create linode
- Validate Images in "Choose a Distribution"
`yarn test components/ImageSelect/ImageSelect`

M3-5753: Filter deprecated images

---

packages/manager/cypress/support/api/images.ts
packages/manager/src/factories/images.ts

End of life field is set to null in `imageFactory` As our e2e specs are using this factory to build mock data.
This fixes failed 2e2 test `create-linode-from-image.spec.ts`
Navigate to `imageFactory` validate end of life filed
yarn cypress:debug 
Then run spec file `create-linode-from-image.spec.ts` under Images

Update imageFactory eol fied as null

---

packages/manager/cypress/e2e/stackscripts/create-stackscripts.spec.ts
packages/manager/cypress/e2e/stackscripts/stackscripts.spec.ts
packages/manager/cypress/fixtures/stackscripts/stackscript-basic.sh
packages/manager/cypress/fixtures/stackscripts/stackscript-no-shebang.sh
packages/manager/cypress/fixtures/stackscripts/stackscript-udf-invalid.sh
packages/manager/cypress/fixtures/stackscripts/stackscript-udf.sh
packages/manager/cypress/support/intercepts/linodes.ts
packages/manager/cypress/support/intercepts/stackscripts.ts
packages/manager/cypress/support/util/polling.ts
packages/manager/package.json
yarn.lock

This fleshes out our StackScript E2E tests so that they validate functionality related to user-defined fields and Any/All target images.
These tests are pretty slow because one of the tests has to wait for a Linode and an Image to be created before the test can begin (taking anywhere between 4-7 minutes total on my machine).
**How do I run relevant e2e tests?**
```
yarn cy:run -s "cypress/e2e/stackscripts/create-stackscripts.spec.ts"
```

M3-5925, M3-5926: StackScript User-Defined Fields and Any/All Images E2E

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.test.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx

- Reduce unnecessary requests to a linode instance's `/ips` endpoint
- Fix delayed loading of /56 & /64 IPv6 ranges
- This was due to a change made in `LinodeNetworking.tsx` (https://github.com/linode/manager/pull/8082)
- IPv6 ranges were only displayed after we got IPv6 range info for _all_ IPv6 ranges on the account. And getting one IPv6 range info is one request. So, the more IPv6 ranges an account has, the more requests we need to make and the longer it takes for the last request to finish
- For just viewing the Linode's IPv6 addresses, we didn't need to wait for all the requests to be finished first. The info we needed to display the IP addresses were already available in the Linode instance's `/ips` response
(Linode was deleted after this)
Local …

M3-5855: Fix delayed loading of /56 ranges in Linode Network tab

---

packages/manager/cypress/e2e/objectStorage/access-key.e2e.spec.ts
packages/manager/cypress/e2e/objectStorage/access-keys.smoke.spec.ts

This fixes the object storage E2E failures we're seeing -- we updated the modal labels to be more descriptive, but forgot to update the E2E tests as well.
The failures can be disregarded in the meantime, but this PR will fix them.
**How do I run relevant e2e tests?**
Run `yarn dev`, then:
```bash
yarn cy:run -s "cypress/e2e/objectStorage/access-key.e2e.spec.ts,cypress/e2e/objectStorage/access-key.smoke.spec.ts"
```
And confirm that all of the tests pass.

Update access key tests to reflect modal button label improvements

---

packages/manager/cypress/e2e/databases/update-database.spec.ts

This unskips a DBaaS test that was accidentally skipped during development for M3-6000 (#8634).
**What are the steps to verify the changes?**
In one console, run `yarn dev`. In another, run:
```bash
yarn cy:run -s "cypress/e2e/databases/update-database.spec.ts"
```
And confirm that both tests pass.

Unskip DBaaS update test

---

packages/manager/config/env.js
packages/manager/public/index.html

Allows New Relic to be disabled in production builds when the `DISABLE_NEW_RELIC` environment variable is set.
**Why?**
We currently have at least one error being reported by New Relic, and running E2E tests against a production build consistently triggers alerts. This change allows us to disable New Relic on these builds to prevent disruptive alerts during E2E tests.
This may also be useful for any users who want to self host Cloud Manager.
1. (If necessary, manually run `yarn` to install dependencies if they're out of sync)
1. Run `yarn build`
1. Confirm that New Relic is enabled by checking `./packages/manager/build/index.html` and confirming that `<script type="text/javascript" src="/new-relic.js">` is present.
1. Run `DISABLE_NEW_RELIC=1 yarn build`
1. …

Allow New Relic to be disabled for production builds

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailNavigation.tsx

Displays the SMTP restriction notice above the tab set on the linode details page, _regardless_ of which tab is selected. We want to increase the visibility of the dismissible notice, which currently only displays if the user selects the "Network" tab.
**Prod:**
https://user-images.githubusercontent.com/114685994/207397061-f80d4974-d0ff-4d9b-aff5-9c6931ffae7f.mov
**This change:**
https://user-images.githubusercontent.com/114685994/207397295-01684bfa-1d24-4d03-b3c0-c532aa857f74.mov
1. Use an account created (or temporarily modified) to have an activated date of on or after 11/30/22. **Note**: you can also use the MSW, please be aware that the dismissible notice only dismisses until the page is …

M3-6016: Relocate SMTP restriction notice for better visibility

---

packages/manager/src/constants.ts

Updates the `DOCS_SEARCH_URL` constant to use a more recent URL. It now also searches product docs, api docs, and reference architectures in addition to guides. If there is another place where the URL needs to be updated, please make those changes.
Perform a search where the `DOCS_SEARCH_URL` constant is used (likely within the Help & Support section). Use a product related term (such as `NodeBalancers`) and verify that product documentation appears in the search box.

Update the docs search URL

---

packages/manager/src/features/OneClickApps/FakeSpec.ts

- Updates links to all of the Marketplace App guides so that they point to the current canonical URLs
- Updates the titles of the above links to reflect a change that will go live soon (replaces "Deploying" with "Deploy")
- Fixes the text in the Shadowsocks link (replaces PR #8652)

Updates links to the marketplace app guides

---

packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts

This fixes an issue with a test in `smoke-linode-landing-table.spec.ts` which causes it to fail in cases where the test environment is not `localhost:3000`. Also fixes a TypeScript error and does a little bit of refactoring of the test file.
You can verify that the test continues to pass locally by running `yarn dev` and then:
```bash
yarn cy:run -s "cypress/e2e/linodes/smoke-linode-landing-table.spec.ts"
```
If you want to confirm the fix for non-localhost environments, an easy (but slow) way to do it is by running the tests via Docker:
(You can speed this up a lot by temporarily setting `specPattern` in `cypress.config.ts` to `'cypress/e2e/linodes/smoke-linode-landing-table.spec.ts'` before …

Fix Linode landing page tests for non-localhost environments

---

packages/manager/src/components/NotificationMenu/NotificationMenu.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx

Removes blocklisted events from the NotificationMenu popover, to reach parity with the list of events on the the Events Landing page. Blocklisted events include events like `linode_migrate_datacenter_create`.
**Prod:**
**This branch:**
1. Create a new nanode or use an existing one.
2. Kick off a migration for the linode.
3. Navigate to the Events Landing page at localhost:3000/events. 
4. Click on the notification icon in the TopMenu and observe that the list of events in the popover notification menu matches the list of events on the Events Landing page.
5. Compare this to prod and observe that in prod, the event for initiating a migration is visible in the popover's event list but not visible …

M3-5170: Filter blocklisted events from Notification Menu

---

packages/manager/src/App.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
packages/manager/src/features/Images/ImagesDrawer.tsx
packages/manager/src/features/Images/ImagesLanding.tsx
packages/manager/src/hooks/useImages.ts
packages/manager/src/queries/base.ts
packages/manager/src/queries/images.ts
packages/manager/src/store/index.ts

The first of two or three PRs related to transitioning Images out of Redux and into React Query.
In terms of functionality, this PR focuses on the Images landing page and the "Capture Image" tab when you go to create an image, and having them rely on RQ instead of Redux.
The next piece in this effort will be the "Upload Image" tab and associated functionality/infrastructure.
Ensure functionality parity of Images landing & the "Capture Image" tab between this branch and prod.
Confirm that the RQ cache is storing and updating the Images data as you would expect.

M3-5182: RQ-ify Images endpoints, Pt. 1

---

packages/manager/src/components/TabbedPanel/TabbedPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
packages/manager/src/features/linodes/LinodesCreate/types.ts

- In the Plan selection table, default selection to the currently selected Linode's plan
- Add the "Current Plan" chip to the selected Linode's plan 
- Focus the correct tab on the plan selection table.
Addressed this in both cloning and resizing Linode. 
https://user-images.githubusercontent.com/119517080/208792119-de97f49c-47a8-43dc-9c73-ac965661a92f.mov
https://user-images.githubusercontent.com/119517080/208792460-e90a5334-4f72-4e62-9c72-c3411258780e.mov
- Click clone Linode
- Select Linode to be cloned
- Scroll down the page and validate selected tab w.r.t the Linode's plan.
- Click resize Linode
- Scroll down the modal and validate selected tab w.r.t the Linode's plan.
**How do I run …

M3-5999: Cloning in Cloud Manager should highlight the Linode to be cloned in the "Select Linode to Clone From" matrix

---

packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/linodes/clone-linode.spec.ts
packages/manager/cypress/e2e/linodes/rescue-linode.spec.ts
packages/manager/cypress/e2e/linodes/smoke-delete-linode.spec.ts
packages/manager/cypress/support/api/linodes.ts

This fixes some test flake we've been seeing recently involving the action menu on Linode details pages. The underlying issue (involving incorrect `data-valuetext` attribs on the menu items) is still present and can be fixed separately since it has no UX impact.
Run the affected E2E tests and confirm that they all pass, ideally without any flakiness.
Run `yarn dev`, then:
```bash
yarn cy:run -s "cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts,cypress/e2e/linodes/clone-linode.spec.ts,cypress/e2e/linodes/rescue-linode.spec.ts,cypress/e2e/linodes/smoke-delete-linode.spec.ts"
```

M3-6037: Fix Linode clone, delete, and rescue test flake

---

packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.test.tsx
packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx

This PR sets the value of `page_size` to either `25` or `500` based on the current value of `window.location.pathname`. This change helps avoid the API from throttling users who switch routes frequently resulting in a 429 error code from the server.
**`page_size=25`**
**`page_size=500`**
Log into Cloud Manager with a user account that has more than one StackScript. Next navigate to any other page and then quickly return to the StackScripts landing page. User should NOT experience any 429 server codes.
`yarn test`

Increase page size to prevent api throttle error

---

packages/manager/src/constants.ts
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/GooglePayButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PayPalButton.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx
packages/manager/src/features/Billing/billingUtils.test.ts
packages/manager/src/features/Billing/billingUtils.ts

- Surface any API errors that happen when we make a payment with PayPal 
-  Previously we just showed a generic error
- This is important because the API may return something like `{ "errors": [ { "reason": "Maximum amount is $2000.00" } ] }`
- Makes Paypal and Google pay buttons use updated limit logic
- Ask me for the link to this if you need to see it
https://user-images.githubusercontent.com/115251059/208533774-b2972e0a-cd31-4613-905f-416969e3c841.mov
https://user-images.githubusercontent.com/115251059/208533725-02db67e4-1579-43a3-b78f-2c53b3fc8fd7.mov
- I recommend testing with local development or development environment
- Test one-time payments in the make a payment drawer (`/account/billing/make-payment`)
- Verify logic is correct with internal documentation (ask me for links)

M3-5726: Update and Improve PayPal Payment Limits and Logic

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx

Adds the `<ExternalLinkIcon />` to the YouTube links on the empty state Database Landing page. Maintains consistency with the external links on the empty state Linode Landing page.
This branch:
Prod:
1. Use an account without any existing databases.
2. Navigate to http://localhost:3000/databases. 
3. Observe that the links in the Getting Started Playlist section display the external link icon beside the link text.
4. Adjust window size and confirm no strange spacing issues occur.
5. Confirm that clicking the icon or the link text redirects to external YouTube links.

M3-6020: Add external link icons to YouTube docs

---

packages/manager/src/components/BillingTooltip.tsx
packages/manager/src/components/TableContentWrapper/TableContentWrapper.test.tsx
packages/manager/src/features/Account/AccountLanding.tsx
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
packages/manager/src/features/Billing/billingUtils.ts

For _Akamai-billed customers only_, we are making the following changes to the billing information text:
- Removing the /Account banner that says: "Linode products and services will appear on your Akamai Technologies invoice"
- Removing the text "Future Linode products and services will appear on your Akamai Technologies invoice" from the  billing table
- Adding a tooltip to explain invoicing in the billing table with new copy
- Updating the header of the billing table to correspond with new tooltip copy
Previously:
https://user-images.githubusercontent.com/114685994/211042981-70245bc7-6dd6-4410-910d-3626642554a6.mov
This change:
https://user-images.githubusercontent.com/114685994/211069140-b5ca21cb-477d-47b8-8cb1-1698d5dba18e.mov
**What are the steps to …

M3-5980: Update text for Akamai-billed customers

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeConfigDialog.tsx

This PR fixes a broken from the Linode's Config Profile edit view when the Linode has a VLAN enabled. 
Test that the URL does indeed lead a page that doesn't result in a 404, specifically points to [Attach a VLAN to a Compute Instance | Linode](https://www.linode.com/docs/products/networking/vlans/guides/attach-to-compute-instance/#attaching-a-vlan-to-an-existing-compute-instance.)

M3-6034: Fix broken URL in Linode Config Profile edit view

---

packages/api-v4/src/account/index.ts
packages/api-v4/src/account/logins.ts
packages/api-v4/src/account/types.ts
packages/manager/src/features/Account/AccountLanding.tsx
packages/manager/src/features/Account/AccountLogins.tsx
packages/manager/src/features/Account/AccountLoginsTableRow.tsx
packages/manager/src/queries/accountLogins.ts

This consumes the /account/logins API endpoint and displays the data on a new "Logins" tab/page in the Account section.
I used existing patterns for RQ, API paginated tables, etc.
This still needs to be validated with UX.
- Visit localhost:3000/account/logins. 
- Check error states, loading state, responsiveness, etc. 
- Check sortable table columns
- Try viewing it with a restricted user (you'll receive an "Unauthorized" error from the API)
- Populate it with a variety of data by creating a restricted user on your account and logging in with it
No unit tests yet.

Feature: show login history on Account page

---

packages/manager/src/components/Dialog/Dialog.tsx

Fixes an alignment issue in some `Dialog`s that was caused by the `className` prop overriding existing styles.
Before:
After: 
1. Navigate to Account > Service Transfers > Make a Service Transfer.
2. Create a Service Transfer.
3. Inspect the alignment of the "Service Transfer Token" modal.
4. Verify other dialogs in the app look as expected.

M3-6002: Align left modal title

---

packages/manager/src/features/OneClickApps/FakeSpec.ts

This PR fixes a broken from the Information drawer for the Peppermint Marketplace App to point to the correct official URL
Test that the URL loads the official [peppermint.sh](https://peppermint.sh/) website.

Fix broken URL for Peppermint OCA

---

packages/validation/src/firewalls.schema.ts
packages/validation/src/linodes.schema.ts

- Uses a default export of the `ipaddr.js` package to prevent node errors. We are thinking that `ipaddr.js` is lacking support for our build system.
- Fixes
- #8713
- #8706
- #8675 
- Run `yarn build && yarn pack` in `packages/validation`
- Note the absolute path of the built package (for me it is `/Users/bnussman/Development/manager/packages/validation/linode-validation-v0.17.0.tgz`)
- Set this version in api-v4's package.json in palace of `"*"`
- Run `yarn build && yarn pack` in `packages/api-v4`
- Note the absolute path of the built package (for me it is `/Users/bnussman/Development/manager/packages/api-v4/linode-api-v4-v0.85.0.tgz`)
- Make a new Node.js + Typescript project outside of Cloud Manager
- Install the built package into your test node project and make …

M3-6066: Fix `api-v4` and `validation` Node Errors

---

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx

Sets plan tab to "Dedicated"
Navigate to create linode
Validate the plan tab is set to default if no plan is selected.

M3-6068: Incorrect tab selection on Linode Create

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
packages/manager/src/queries/accountMaintenance.ts

- Fixes linode details header showing past maintenance events
- Relates to (https://github.com/linode/manager/pull/8707 but I failed to also make the same change change here
- Use the MSW to verify that you don't see a maintenance banner (like the one shown below) at the top of a Linode's Details Page on linodes that show no maintenance on the Linodes landing page

Fix Linodes Detail Showing Past Maintenance Events

---

packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx

- Fixes NodeBalanacer Mode Change Select
- Fixed by using function parameters rather than relying on the event
It was caused by this error
- Test changing the `Mode` of a nodebalancer node
- Verify you can change the mode and save it successfully

M3-6069: Fix NodeBalanacer Mode Change Select

---

packages/manager/cypress/e2e/firewalls/migrate-linode-with-firewall.spec.ts
packages/manager/cypress/e2e/images/machine-image-upload.spec.ts
packages/manager/cypress/e2e/stackscripts/create-stackscripts.spec.ts
packages/manager/cypress/support/ui/index.ts
packages/manager/cypress/support/ui/select.ts

* Fixes the StackScript test failures related to the MUIv5 upgrade
* Fixes the Image, Migration, and StackScript test failures related to the recent region selection improvements
**MUIv5 Fix**
Since upgrading to MUIv5, our `<HelpIcon />` buttons have an `aria-label` attribute containing the contents of the tooltip when it had previously used the `title` attribute. `cy.findByLabelText` checks against `aria-label`, so it was tripping up on that help icon since its content matches our query.
This PR increases the strictness of the selector, matching against any element with a label which begins with "StackScript Label" (case sensitive). Now only the input field will be selected, not the tooltip button.
**Region Selection Fix**
This adds some helpers to make …

Fix E2E Tests for MUIv5, Region Selection Improvements

---

packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx

Co-authored-by: Hussain Khalil <hussain@sanpilot.co>
Changes all occurrences of "Disk IO" to "Disk I/O"
Before:
After:
Go to a Linode > Settings > Notification Thresholds

M3-5951: Disk IO -> Disk I/O

---

packages/api-v4/src/index.ts
packages/api-v4/src/request.ts
packages/manager/src/components/Notice/Notice.tsx
packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.test.tsx
packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/LinodesCreate/types.ts
packages/manager/src/themeFactory.ts

Show the API awareness modal after validation check passes.
- Adds content and respective links to the API awareness modal.
- Adds Tabs component.
- Add installation guides.
- Wired GA events
-  Validation check to show / hide modal
- Navigate to Create Linode page
- Click on "Create using command line" button - Try with out filling required data.
- Should show the inline error messages.
- Enter data for all required fields.
- Click on "Create using command line"
- Show show the API awareness modal.
- Validate all the links. 
yarn test

M3 6045: Add modal content, tabs and validation check

---

packages/manager/cypress/e2e/linodes/smoke-delete-linode.spec.ts
packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts
packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts
packages/manager/cypress/e2e/objectStorage/object-storage.smoke.spec.ts
packages/manager/cypress/e2e/volumes/create-volume.smoke.spec.ts
packages/manager/cypress/e2e/volumes/delete-volume.spec.ts

Updates E2E tests to account for type to confirm improvements. This should fix the ~6 tests that have been failing recently as a result.
```bash
yarn cy:run -s "cypress/e2e/linodes/smoke-delete-linode.spec.ts,cypress/e2e/linodes/smoke-linode-landing-table.spec.ts,cypress/e2e/objectStorage/object-storage.e2e.spec.ts,cypress/e2e/objectStorage/object-storage.smoke.spec.ts,cypress/e2e/volumes/create-volume.smoke.spec.ts,cypress/e2e/volumes/delete-volume.spec.ts"
```
Note that I have observed some flakiness in `create-volume.smoke.spec.ts` that's unrelated to these changes; try re-running those tests if you happen to encounter a failure when you run the command above.

Fix tests for Type-to-Confirm improvements

---

packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx

- The Linodes landing page had extra top and bottom padding that other landing pages did not.
- This has been bugging me for quite some time so I had to put up a fix 😖
- The solution was to just remove a few useless `<Grid />`s 
- The diff may look crazy, but that's just because I removed so many `<Grid />`s  causing less indentation in the file
- Test layout, ui, and responsiveness of the Linodes Landing table (`http://localhost:3000/linodes`)
- Verify that the padding matches other landing pages like Volumes

Fix Linodes Landing Extra Padding

---

packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx

- Switches `require` statements to`import` statements in `HighlightedMarkdown.tsx` to match our current import patterns and better support modern build tools
- There should be no visible change
- Verify the app builds and runs as normal
- Check a component such as the Kubernetes Kube Config Drawer to verify yaml is highlighted as you would expect (compare to production to verify)

Switch `require`s to `import`s for `highlight.js` Languages

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx

Updates the labels for the video playlist section in Linodes and Databases.
Also includes a minor code refactoring to preserve the existing analytics labels and make the analytics events more consistent between the two affected components.
Linodes:
Databases:
Linodes:
Databases:
1. Navigate to the Linodes/Databases features.
2. Delete any existing Linodes/Databases
3. Verify UX copy is correct
4. Verify analytics tags remain the same as before

M3-6027: Update UX copy for getting started playlists

---

packages/manager/package.json
packages/manager/src/types/index.ts
yarn.lock

- We use `react-csv` but we did not install typescript types for it
- This PR adds a real typescript `@types/...` package for `react-csv`
- Nothing really to test here, just verify the app runs locally without errors and passes all builds in CI

Use `@types/react-csv` for `react-csv`

---

packages/api-v4/README.md
packages/api-v4/package.json
packages/api-v4/tsup.config.ts
packages/manager/package.json
packages/validation/package.json
packages/validation/tsup.config.ts

- Users that want to use api-v4 or validation in plain javascript + node would see an error like this
```sh
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs"
```
- Removes tsup's `legacyOutput` option so we get expected file extension (`.cjs`) that work in Node.js
> **Note**: This is completely unrelated to https://github.com/linode/manager/pull/8716
- Build and Pack validation by doing `cd packages/validation && yarn build && yarn pack`
- Copy output file …

M3-6135: Fix `api-v4` and `validation` CommonJS not accepted by Node.js

---

packages/manager/src/features/linodes/LinodesCreate/ApiAwarenessModal/index.tsx
packages/manager/src/features/linodes/LinodesCreate/CodeBlock/styles.ts
packages/manager/src/utilities/generate-cURL.test.ts
packages/manager/src/utilities/generate-cURL.ts
packages/manager/src/utilities/generate-cli.test.ts
packages/manager/src/utilities/generate-cli.ts

Adds functions to generate Linode CLI and cURL commands to create Linodes.
This is a work in progress to just get the basics down. I want to move this to a single function or an object that can generate both cURL and Linode CLI comands.
`yarn test generate-cURL`

M3-6046: dynamically generate cURL and CLI commands

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Refactors `FirewallRuleTable.tsx` to support screen readers by converting the underlying structure from a table into an unordered list arranged in a `Grid` to [improve compatibility with react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/issues/2233). Added `aria-label`s and tab navigability where necessary to improve access to fields within a list item. 
Previously, the FirewallRuleTable was [inaccessible for users using screen readers and keyboard navigation](https://github.com/linode/manager/issues/7483#event-4432711610). The table did not always provide enough context for the user to know how to interact with drag & drop functionality or interact with the FirewallRuleAccessMenu buttons, and the fields in each table row were unknown to the …

M3-6039: Update FirewallRuleTable to support screen readers

---

package.json
yarn.lock

- Update `ua-parser-js` to `0.7.33` for CVE-2022-25927
- We prefer to do this instead of approving https://github.com/linode/manager/pull/8741 because this yarn  resolution method allows our `yarn.lock` to remain in sync with our package.json(s)
- Ensure manager builds and works as expected

Manually pin `ua-parser-js` to `0.7.33` for CVE-2022-25927

---

packages/api-v4/src/account/types.ts
packages/manager/src/factories/grants.ts
packages/manager/src/features/Users/UserPermissions.tsx
packages/manager/src/features/Users/UserPermissionsEntitySection.tsx

- Allows unrestricted user to adjust Database related permissions of a user
- Adds `add_databases` and `database` as user permissions options
<details>
<summary>Screenshots</summary>
</details>
- Test modifying permissions on a user
- Specify test Database-related permissions

M3-6153: Add Databases as a User Permissions Option 

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/utilities/escapeStringForCLI.ts
packages/manager/src/utilities/generate-cURL.test.ts
packages/manager/src/utilities/generate-cURL.ts
packages/manager/src/utilities/generate-cli.test.ts
packages/manager/src/utilities/generate-cli.ts

Wraps the arguments for the generated CLI commands with single quotes so everything is properly escaped for the CLI.
Use the generated CLI command to make a new linode.
run `yarn test generate-cli`

Fix strings in cli commands

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Fixes styling of FirewallRuleTable when in dark mode by relying on `theme` colors.. I forgot to test dark mode when working on [M3-6039](https://github.com/linode/manager/pull/8735)...
This branch ✅ :
Staging ❌ :
Switch dark mode on and off in My Settings and test that firewall rules colors correspond with the theme.
)

Fix FirewallRuleTable styling for dark mode

---

packages/manager/src/utilities/generate-cli.ts

- Uses new escapeStringForCLI function for parsing strings in CLI command generation
- Test creating a Linode using the new **Create from Command** Line button, using the **CLI** tab
- Verify you can use spaces in tags names
- Verify you can use complex characters in both tags and root passwords
Some test cases
- `testing’okay/this\is!a&testing’okay`
- `\\yay’’testing//\\okay’test'okay'test!!nice`
- `this is a test tag`

New Escape Function for CLI Generation

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Fixes a previous fix that was missed in #8776: due to applying the text styling to the wrong CSS rule, a newly created firewall rule row would should up in dark mode with black text rather than `theme.textColors.tableStatic`. 
A set height of 40px for a firewall rule row also caused a strange issue, noticeable in dark mode, for the undo button of newly added firewall rule(s), where the button had a height of 41px and extended beyond the container. Unsetting the row `height` seemed to fix the issue.
Fix:
https://user-images.githubusercontent.com/114685994/217683444-9cfca002-125c-466f-a9f2-ab0ee69412bf.mov
Staging:
https://user-images.githubusercontent.com/114685994/217683459-b89f15ab- …

Fix dark mode illegible text, undo button spacing on newly added rules

---

packages/manager/cypress/e2e/account/service-transfer.spec.ts

This fixes an ARIA label mismatch that's causing one of the new service transfer tests to fail. Sorry for the trouble, I should've caught this before merging earlier!
Run the service transfer tests and confirm that they all pass.
`yarn up` and
```bash
yarn cy:run -s "cypress/e2e/account/service-transfer.spec.ts"
```

Fix dialog close button ARIA label mismatch

---

packages/manager/src/features/linodes/MigrateLanding/MigrateLinode.tsx
packages/manager/src/queries/accountAgreements.ts

- Allow us to conditionally enable the User Agreements query
- Only enable the `useAccountAgreements` in the Migrate Linode Modal if the modal is open
- This will save us one fetch to the API when we load cloud manager at `http://localhost:3000/linodes`
- Go to `http://localhost:3000/linodes` with at least one Linode on your account 
- First verify account agreements have **not** been fetched 
- Verify that when you open the Linode **Migrate** modal, the account agreements endpoint is fetched to get a user's agreements

Account Agreements Query Small Optimization

---

packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts

This is a tiny fix for the failure in `smoke-linode-landing-table.spec.ts`, which stems from the accessibility improvements made by PR #8779 -- the affected test attempts to find a top menu icon by its `aria-label` attribute, but that attribute is no longer present. This PR fixes it by finding the element by its `title` attribute instead.
Run Cloud Manager with `yarn up`, then run the command below and confirm that the tests pass, particularly the `checks the landing top menu items` test.
**How do I run relevant e2e tests?**
```bash
yarn cy:run -s "cypress/e2e/linodes/smoke-linode-landing-table.spec.ts"
```

Fix Cypress failure involving top menu icon changes

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/validation/src/linodes.schema.ts

- Updates the `CreateLinodeSchema` in `validation` to match the Linode API. 
- `image` is now required by the API when you specify a `stackscript_id`, we need to update our client side validation to match this API behavior
- This PR also passes the `errors` prop to both `FromStackScriptContent` panels because they did not previously have errors data passed to them, resulting in image errors not being surfaced
- Test Linode Creation
- Test that you see an error under the image field if you try to deploy a Linode from a Stackscript with no image selected
- Test all other ways to deploy a Linode and ensure that no other flows were adversely affected

M3-6079: Creating a Linode via a StackScript - Require `image` Field

---

packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackup.tsx
packages/manager/src/utilities/getEventsActionLink.ts

Currently, we do not indicate on Cloud when a Linode backup is still post-processing, or if it fails after processing. This PR adds a status column to the Linode backups table and links the event row message to the Linode's backup tab for more transparency. 
Failure state
Enable/create a snapshot in a Linode's detail page -> Backups tab. Notice the new status column.
When a snapshot has finished being taken (100%, check the notification menu or the entity detail header), the Backups table should update with the new snapshot and you should see a status of Processing. Wait a little while and the status should then update to success/failure.
In the notification menu/events page, clicking on the snapshot backup event should bring you to the Linode's backup tab
To mock a failure state, you can …

M3-5065: Add status to Linode Backups table

---

packages/manager/cypress/e2e/account/personal-access-tokens.spec.ts
packages/manager/cypress/support/intercepts/profile.ts
packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx

This adds a couple integration tests for Cloud Manager PAT CRUD operations. It confirms that UI flows work as expected when users create, rename, and revoke personal access tokens. I opted to mock all of the data involved rather than create actual PATs and risk them leaking into logs, recordings, etc.
Run `yarn up` and then:
```bash
yarn cy:run -s "cypress/e2e/account/personal-access-tokens.spec.ts"
```

M3-6009: Add Cypress integration tests for Personal Access Token CRUD

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx

- If the user reselectes the **same preset** in the firewalls rule drawer, **do not reset the form** to the preset defaults
- This was causing users to accidentally loose their progress when they reselected the same preset
Note how form resets when the same preset is selected resulting in the users progress being lost
https://user-images.githubusercontent.com/115251059/218135926-12711216-1df3-44aa-900b-70f2005341f9.mov
Note how the form does not change state at all
https://user-images.githubusercontent.com/115251059/218135792-dc2c847c-4fd5-4618-a57a-af2940e1fdda.mov
- Test the behavior and functionality of the Firewall Rules drawer

M3-5807: Don't Reset the Firewall Rule Drawer if the same preset is reselected

---

packages/manager/src/components/TextTooltip/TextTooltip.tsx
packages/manager/src/components/TextTooltip/index.ts
packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx

Makes a few updates to standardize the tooltip by doing the following:
- Renames from `BillingTooltip` to a more generic `TextTooltip`
- Removes const billing text and replace with prop for popover text
- Replicates default behavior for triggering tooltips on mobile – our other tooltips using button components open popover immediately on click; don't require a long-press which is the MUI Tooltip default
- Also fixes a small alignment issue in the table header at `sm` screen breakpoint; `xs` breakpoint was previously used and should not have been
Previously, this was only used as a billing notice for Akamai customers, but we expect to expand its use.
Tooltip in non-mobile view should behave and look unchanged:
<details>
<summary> Screencaps 📹  </summary> …

M3-6163: Standardize Text Tooltip

---

packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/FolderActionMenu.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/FolderTableRow.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/ObjectTableContent.tsx
packages/manager/src/features/ObjectStorage/utilities.ts
packages/manager/src/queries/objectStorage.ts

- Adds ability to create Object Storage "folders"
- Test Object Storage in depth
- Test folder creation and deletion
- Verify object functionality still works as expected
I don’t think I’m going to do a good job of asking this question, but I need some guidance on this. Which method should we use to create a folder in Cloud Manager?
- Create a fake folder in memory that does not get sent to the API at all so the user can go into the folder to upload an object, resulting in the folder actually being “created”
- **Pros:** Less hacky from an S3 perspective
- **Cons:** Folder will not persist if user refreshes the page
- Create a 0 byte object with a name that ends in a forward slash (the PR is currently doing this)
- **Pros:** “Folder” will persist upon refresh
- **Cons:** Feels hacky from …

M3-4090: Object Storage Add Ability to Create "Folders"

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx

Type error when IP Sharing multiple /56 IP addresses
Resolves Type error when IP Sharing multiple /56 IP addresses
https://user-images.githubusercontent.com/119517080/219345478-939dbe65-979d-4227-b0c4-a17bbe26482c.mov
https://user-images.githubusercontent.com/119517080/219344577-2f82a6ea-59dd-4437-b0ca-f14da5708206.mov
- Create two new linodes (1GB nanodes work fine) in the `Frankfurt, DE` region. Recommend labeling them: `ip-sharing-1`, `ip-sharing-2`
- From the Network tab on the Linode Details page of `ip-sharing-1`, click "Add an IP Address" and set up two /56 addresses. (Temporarily adjust `IPv6 max per DC` to a higher number in admin if you have to; you may receive a limit error.)
- Go to the Network tab of the second Frankfurt linode, `ip-sharing-2`.
- …

M3-6015: Type error when IP Sharing multiple /56 IP addresses

---

package.json
packages/manager/package.json
yarn.lock

- Removes `wait-on` package to solve CVE-2023-25166 dependabot
- `wait-on` depended on `@sideway/formula` and `@sideway/formula` has a ReDoS Vulnerability
- Thankfully, we no longer use `wait-on` so we can just remove it, resulting in us no longer depending on `@sideway/formula` 
- For context, we previously used `wait-on` for e2e pipelines but we now use docker livelesness checks
- Test general features of Cloud Manager 
- Verify e2es pass

Remove `wait-on` package for CVE-2023-25166

---

packages/manager/cypress/support/api/tags.ts
packages/manager/cypress/support/ui/common.ts

This fixes a small issue with the Cypress clean-up function for tags -- it was only fetching the first page of results, causing a lot of tags not to get cleaned up, ultimately contributing to some recent failures.
1. Create some tags that are prefixed with `cy-test-`. I think the easiest way to do this is to create a new Linode, specifying the new tags during the process.
2. Run `yarn cy:debug` and run any test
3. In the test `before` hook, you should observe HTTP DELETE requests for each of the tags you created (and no tags that aren't prefixed with `cy-test-`). You can observe this in the left sidebar, or you can open the dev tools and observe the Network tab.

Fetch all tags when cleaning Cypress test tags

---

packages/api-v4/src/account/types.ts
packages/manager/src/components/StatusIcon/StatusIcon.tsx
packages/manager/src/features/Account/AccountLogins.tsx
packages/manager/src/features/Account/AccountLoginsTableRow.tsx
packages/manager/src/index.css

- Adds new `Access` column to the Account Logins table to show if a login was `successful` or `failed`
- `http://localhost:3000/account/login-history`
- Checkout internal api PR that adds `status` to `/v4/account/logins`
- Switch Cloud Manager's env to use local development
- Visit `http://localhost:3000/account/login-history` and test the new column
- Test loading state
- Test ordering
- Test mobile experience

M3-6078: Account Logins Show `Successful` or `Failed` Access

---

packages/manager/config/webpackDevServer.config.js

- Allow webpack server to be accessed by linode domains
- Checkout this PR in our internal development envrionemnt
- Verify that you can access cloud manager from `cloud.lindev.local` without seeing a `invalid host header` error

Add support for local development access from local domain

---

packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx

When opening the Notifications dropdown currently, a `validateDOMNesting` warning gets logged to the console because there's a case of `<p>` being a descendant of `<p>`.
It seems this was being caused in `RenderEvent.tsx` by `<Typography>` wrapping `<HighlightedMarkdown>`, which returns `<Typography>`. 
Confirm the warning displayed below is no longer logged to the console when opening the Notifications dropdown on this branch.

fix: [M3-5840] - Fix validateDOMNesting warning in console

---

packages/manager/package.json
packages/manager/src/assets/icons/reload.svg
packages/manager/src/components/Button/Button.test.tsx
packages/manager/src/components/Button/Button.tsx
packages/manager/src/components/HelpIcon/HelpIcon.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
packages/manager/src/styles/index.ts
packages/manager/src/styles/keyframes.ts
packages/manager/src/themeFactory.ts
packages/manager/src/utilities/isPropValid/index.ts
packages/manager/src/utilities/isPropValid/isPropValid.ts
yarn.lock

This refactors the `Button` component to the new [sx](https://mui.com/material-ui/react-box/#the-sx-prop) and [styled](https://mui.com/system/styled/#difference-with-the-sx-prop) API. I also added [tss-react](https://github.com/garronej/tss-react) so that we can begin migrating the older makeStyles API which will give us better type safety and autocomplete than MUI v4, while providing an almost seamless transition in moving away from the deprecated JSS API.
- Added `tss-react`
- Added `Button.test.tsx` for more coverage
- Refactored `Button` to use `styled` API
- Added `sx` prop to `HelpIcon` for one-off styling
- Added util `isPropValid` to filter out props that are not valid DOM attributes
- Created `packages/manager/src/styles` folder for all future shared `keyframes`
| Before & After …

refactor: M3-6195 - Add tss-react and refactor Button to styled API

---

packages/api-v4/src/networking/types.ts
packages/manager/src/constants.ts
packages/manager/src/features/Lish/lishUtils.ts
packages/manager/src/features/linodes/LinodesDetail/utilities.ts

Lish URLs have been updated to accept the scheme: `<region.id>.webconsole.linode.com`. Previously, it used a custom, hardcoded prefix (that isn't returned from the /regions endpoint). This way, we don't have to update this hardcoded map every time we open a new datacenter.
This is Part 1 of the changes described in the ticket. Part 2 will be to update region display names to make use of the new "label" field on the /regions endpoint.
Create new Linodes in different DCs, click "Launch LISH console" and make sure it works. Use the "LISH Console via SSH" command in your own terminal and verify it works.

M3-6081 Dynamic Lish URLs

---

packages/manager/cypress/e2e/databases/create-database.spec.ts

This fixes a failing DBaaS test triggered by today's maintenance. The tests run against specific database engine versions, and today's maintenance changed which versions are available.
This fix increases the leniency so that the tests should continue to pass regardless of which minor versions of our database engines are available, so we won't have to update the tests every time we upgrade our available database engines. 
Confirm that the following tests pass:
```bash
yarn cy:run -s "cypress/e2e/databases/create-database.spec.ts"
```

fix: Allow DBaaS e2e tests to pass regardless of engine minor version

---

packages/api-v4/src/images/images.ts
packages/api-v4/src/images/types.ts
packages/manager/src/components/CheckBox/CheckBox.tsx
packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx
packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx
packages/manager/src/store/image/image.requests.ts
packages/validation/src/images.schema.ts

Adds a non-required checkbox field (and accompanying help tooltip) to the Image **Capture** form so that a user can indicate if an image supports cloud init. By default, a captured image does not support cloud init.
Note that #8800 is the related PR for the Image **Upload** form.
TODO:
1. Check out this PR and switch your environment to Dev to test these changes. Ask if you need more details on testing these changes with a properly configured dev account.
2. Have at least one Linode with an attached Disk on your account.
3. Navigate to http://localhost:3000/images/create/disk to the Capture Image form.
4. Open the browser's dev tools, navigate to the network tab, and use the search bar to filter …

feat: [M3-6149] - Add Cloud Init checkbox to Image Capture/Create flow

---

packages/api-v4/src/constants.ts
packages/manager/src/components/PasswordInput/PasswordInput.tsx
packages/manager/src/components/PasswordInput/StrengthIndicator.test.tsx
packages/manager/src/components/PasswordInput/StrengthIndicator.tsx
packages/manager/src/constants.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx

- Increase `MINIMUM_PASSWORD_STRENGTH` from 2 to 4
- Refactors in `StrengthIndicator.tsx` to bring it up-to-date with our modern code conventions
- Add unit tests for `StrengthIndicator.tsx`
- Don't scale scores of 4 down in `PasswordInput.tsx`
- Enforce password complexity/requirements in `LinodeSettingsPasswordPanel.tsx`
`Do Not Merge` until the 3/6 release process begins.
- Ensure that the strength indicators for password inputs throughout the app have not been adversely impacted.
- Run `yarn test strengthindicator`

refactor: [M3-6070] - Increase minimum acceptable password strength

---

packages/api-v4/src/images/types.ts
packages/api-v4/src/linodes/types.ts
packages/manager/src/components/Accordion/Accordion.tsx
packages/manager/src/factories/images.ts
packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/LinodeCreateContainer.tsx
packages/manager/src/features/linodes/UserDataAccordion.tsx
packages/validation/src/linodes.schema.ts

Add User Data accordion to the Linode Create flow so that a user can configure their Linode using cloud-init.
Todo:
Testing Create via Distribution
1. Point to the dev environment (you might also need additional account setup, reach out for more info)
2. Navigate to the Linode create page http://localhost:3000/linodes/create
3. Select a distribution that supports cloud-init
- Arch Linux, Cent OS 7, and Ubuntu 16.04 LTS have been marked as cloud-init compatible for testing purposes
4. If the distribution supports cloud-init, you should see an `Add User Data` accordion
- If the distribution doesn't support cloud-init, you should _not_ see the accordion
5. Enter some text (can be anything) into the User Data input field and fill out the rest of the required Linode Create fields
6. Click on …

feat: [M3 6143] - Add User Data Accordion to Linode Create page

---

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx

Fixes a bug in the Firewall Rules Table where `whiteSpace: 'nowrap'` [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) was preventing fields with long labels or long lists of ports or IP addresses from wrapping text in their containers. The result was overlapping, illegible text in the Port, Sources, and Action columns. The `whiteSpace` property was previously used when rendering the rules with table components, but caused rendering issues after the refactor in #8735. 
🐛 Bug in prod:
Fix in this branch:
*Bug in prod:*
1. Navigate to the Firewalls landing page (https://cloud.linode.com/firewalls/) and create a firewall or use an existing one.
2. Click on the firewall …

fix: [M3-6211] - Fix Firewall Rules Table rendering overlapping text

---

packages/manager/cypress/e2e/images/smoke-create-image.spec.ts

This updates the Image capture smoke test for the React Query improvements that were recently made. It also cleans up some util functions that I'm gradually removing from tests.
```bash
yarn cy:run -s 'cypress/e2e/images/smoke-create-image.spec.ts'
```

fix: Cypress React Query Images improvements

---

packages/manager/cypress/e2e/managed/managed-ssh.spec.ts
packages/manager/cypress/support/api/managed.ts

- Fixes an issue where an initial failure in the Managed SSH test causes subsequent attempts to be guaranteed to fail. This is because the test assumes the IDs of some mock data created using factory.ts, but factory.ts's sequence numbers do not automatically reset between attempts
- Fixes a typo involving a mock; this never manifested as a failure before since the real data matches the desired mock data in this case
```bash
yarn cy:run -s "cypress/e2e/managed/managed-ssh.spec.ts,cypress/e2e/managed/managed-navigation.spec.ts"
```

fix: Improve Cypress Managed SSH Test Flake

---

packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLandingEmptyState.tsx
packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
packages/manager/src/features/linodes/LinodesLanding/ListLinodesEmptyState.tsx
packages/manager/src/utilities/emptyStateLandingUtils.ts

- New utility file for empty state landing page constants and GA send event function
- Refactors for DBaaS and Linode empty state landing pages related to the above
- Resource links added to Kubernetes empty state landing page
- Confirm that the GA events are still being sent as expected for the DBaaS and Linode empty state landing page interactions
- This can be checked via network requests -- in Firefox, for example, you should see Google Analytics-related requests and you can drill down into the request and see the label, etc. associated with the click. In Chrome it seems the visibility of these requests depends on your local browser settings/configuration
- Confirm the GA events are being sent as expected for the Kubernetes empty state landing page interactions
- Confirm the links …

feat: [M3-6160] - Add resource links to Kubernetes empty state landing page

---

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx

Reverted regression changes for logo when we removed outdated code for brand update.
| <video src="https://user-images.githubusercontent.com/125309814/222316265-10b5c06c-d9e7-4f9d-be85-4608e5468041.mp4" /> | <video src="https://user-images.githubusercontent.com/125309814/220502069-781d4117-805c-4b66-8255-59f3fcee047a.mp4" /> |
- Pull down branch
- Run `yarn up` to run locally
- Observe logo is back to normal

fix: [M3-6166] - Revert select changes to logo brand update

---

packages/manager/package.json
packages/manager/src/assets/icons/reload.svg
packages/manager/src/components/Button/Button.test.tsx
packages/manager/src/components/Button/Button.tsx
packages/manager/src/components/HelpIcon/HelpIcon.tsx
packages/manager/src/features/ObjectStorage/BucketDetail/CreateFolderDrawer.tsx
packages/manager/src/features/Profile/APITokens/RevokeTokenDialog.tsx
packages/manager/src/styles/index.ts
packages/manager/src/styles/keyframes.ts
packages/manager/src/themeFactory.ts
packages/manager/src/utilities/isPropValid/index.ts
packages/manager/src/utilities/isPropValid/isPropValid.ts
yarn.lock

I merged `develop` into the `feature/metadata` branch last week, but somehow the `tss-react` changes from #8821 were lost somewhere along the way. This PR just pulls those changes in.
- Ensure the app builds successfully and Cloud works as expected
- `yarn Button.test.tsx`

Pull `tss-react`-related changes into `feature/metadata`

---

.github/workflows/ci.yml

Reverts temporary changes we made to `workflows/ci.yml` found here: https://github.com/linode/manager/pull/8677. We forgot to undo changes before merging.

fix: Removed development branch and reverted to master

---

packages/manager/src/features/OneClickApps/FakeSpec.ts
packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx

The One Click Clusters feature branch has been stale for a few months. So, when we pulled in changes from develop, there was a regression from when we added the ability to search by category & alt name/desc in https://github.com/linode/manager/pull/8657.
This PR fixes Cluster apps not showing up when trying to search for "cluster" or their app name/category (e.g. "MongoDB", "database", etc) by adding the `cluster_name` property to apps that can also be deployed as a Cluster
Note: The Cluster app StackScripts are still being worked on/finalized so there will be missing icons, etc.
Go to `/linodes/create?type=One-Click` and try searching for cluster/database/mongodb/postgre/redis/mysql/etc

fix: [M3-6216] - Cluster search regression

---

packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts

Temporarily change the "Remit To" invoice address for US customers from the Akamai office back to the Philly office
Before
After
1. Go to /account/billing
2. Update Billing Contact address to a US address
3. Download PDF of an invoice
4. Check the "Remit To" address in the invoice, it should display the Philly office
5. Update Billing Contact address to a CA address
6. Download PDF of an invoice, the "Remit To" address should display the Akamai Cambridge office
7. Update Billing Contact address to an international address
8. Download PDF of an invoice, the "Remit To" address should display the Akamai international office

change: [M3-6218] - Temporarily change Remit To invoice address

---

packages/manager/cypress/e2e/account/service-transfer.spec.ts
packages/manager/cypress/support/intercepts/linodes.ts

- Added mock linode data
- Used mock linode data in some tests of `service-transfer.spec.ts`
1. Mock a Linode.
2. Navigate to Service Transfer landing page with managed enable.
3. Make a service transfer.
4. An error message "You cannot initiate transfers with Managed enabled." is shown.
Run command: `yarn cy:run -s "cypress/e2e/account/service-transfer.spec.ts"`

refactor: [M3-6228] - Use Mock Linode Data for Managed Service Transfer Test

---

packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts
packages/manager/cypress/support/intercepts/object-storage.ts

This adds a new end-to-end test to confirm that Object Storage objects behave as expected. It confirms that objects can be uploaded, deleted, replaced, accessed when public, and that folders can be created and deleted.
`yarn up`, and then:
```bash
yarn cy:run -s "cypress/e2e/objectStorage/object-storage.e2e.spec.ts"
```
Alternatively, to run the tests interactively run `yarn cy:debug` and search for `object-storage.e2e.spec.ts`.

test: [M3-5952] - Object Storage object upload, access, delete tests

---

packages/manager/src/eventMessageGenerator.ts
packages/manager/src/features/Events/EventRow.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx
packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
packages/manager/src/features/NotificationCenter/NotificationData/useEventInfo.ts
packages/manager/src/utilities/getEventsActionLink.ts

Improves the notification event messages by making the following changes:
- Applying hover state on every event type
- Previously, events referencing a deleted (non-linkable) entity did not have a hover state because only linkable events were hoverable
- Adding hyperlinks to entity names 
- Removing hyperlinks from event row itself
- Pointer will no longer appear when hovering anywhere on the event row
- This will make the target of the pointer more clear and allow for multiple hyperlinks (e.g. an entity name and a docs link) to be clickable within a single  event message
**Notification Center:**
| Prod | This branch  | 
| ------- | --- | 
| ![Screen Shot 2023-03-01 at 10 20 48 PM](https://user-images.githubusercontent.com/114685994/222347433-b3b0327e-878e-4c5c-80 …

refactor: [M3-5800] - Improve notification event links

---

.github/workflows/e2e_schedule_and_push.yml

This updates the GitHub Actions e2e test workflow that runs each morning and each time code is merged to `develop`, `staging`, and `master`. It replaces `yarn up` with `yarn build` followed by `yarn start:manager:ci`. We've observed better performance using this command, and it may sidestep the issues currently occurring with Cypress timing out.
The best we can really do is run the `yarn build`, etc., commands locally and hope they'll work just as well via GitHub Actions. We'll know pretty quickly once we merge this if there are any problems.

refactor: Use `yarn start:manager:ci` for GitHub Actions E2E workflows

---

.github/workflows/e2e_schedule_and_push.yml

- Minor change to https://github.com/linode/manager/pull/8854
- We need to install dependencies before we run build
- We missed this because our old yarn up command did this for us, it was just overlooked when we made the change in https://github.com/linode/manager/pull/8854

fix: Run install before building for Cypress e2e tests in Github Actions

---

packages/manager/package.json

- Runs the typescript compiler concurrently alongside the Vite dev server
- We are doing this so we can get instant feedback when we make changes that result in type errors
- This is very useful when refactoring and making changes that affect other files in the codebase
- I chose this method over https://vite-plugin-checker.netlify.app/ for the following reasons
- Saves us from needing yet another dependency
- As a team, we decided we don't care for an error overlay
- If we find that tsc in watch mode has annoying behavior or output, we can revert this and give the plugin a try
> **Note**: Folloing this ticket, I will investinate to see if we would benefit from https://www.typescriptlang.org/docs/handbook/project-references.html
https://user-images.githubusercontent.com/115251059/224132664 …

chore: Run Typescript in watch mode for local development

---

.github/workflows/ci.yml
.github/workflows/e2e_schedule_and_push.yml

This upgrades the versions of the actions that we use in our CI and E2E workflows to resolve the warnings shown on our runs.
This is related to the PR I accidentally opened a few minutes ago. Sorry about that!
**Before:**
**After:**
We can't really test the E2E workflow changes until after this PR gets merged. However, the CI changes will be included in the run against this PR so we'll have a partial view of whether things work before merging.

chore: [M3-5975] - Upgrade actions in GitHub Actions workflows

---

packages/api-v4/src/linodes/types.ts
packages/manager/src/components/CheckBox/CheckBox.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.styles.ts
packages/manager/src/features/linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx
packages/manager/src/features/linodes/UserDataAccordion.styles.ts
packages/manager/src/features/linodes/UserDataAccordion.test.tsx
packages/manager/src/features/linodes/UserDataAccordion.tsx
packages/validation/src/linodes.schema.ts

Adds User Data section to the Linode Rebuild flow when an image with `cloud-init` capability is selected.
- Ensure that the existing User Data work elsewhere in the app has not been adversely impacted by changes made on this branch
- Confirm that Linode rebuild requests go through with the `{ metadata: { user_data: [encoded string ...] } }` property (or `null` instead of encoded string when the Reuse checkbox is marked)

feat: [M3-6146] - Add User Data to Linode Rebuild flow

---

.github/workflows/ci.yml

- Re-adds yarn cache step to `build-validation` step
- For some unknown reason, we removed it https://github.com/linode/manager/pull/7475 but I can't figure out why
- I think it's worth trying this again, if things go bad we can just revert this PR
- This could save us some time in CI
- Verify that the Github Actions ci passes for this PR
- Well just have to observe this change once it's merged

ci: Re-add cache to `build-validation` CI step

---

packages/manager/cypress.config.ts

This updates the Node version warning that shows when you run Cypress. It will now recommend using Node 18 to align with our recent Node version improvements.
Throwing this question out there too: do any of us get any value out of this warning? Do we think it's helpful for other potential contributors?
This message will no longer be shown if you're running Node 18.x:
1. Run `yarn cy:run` (note: the dev server does not need to be running for this)
2. If you're running Node 18, confirm that no warning is shown
3. If you're not running Node 18, confirm that a warning is shown and that Node 18 is recommended

chore: [M3-6210] - Update Cypress recommended Node version message

---

packages/manager/src/components/Radio/Radio.tsx

- Fixes the Radio styles caused (somehow) by https://github.com/linode/manager/pull/8838
1. Go to `http://localhost:3000/linodes/create`
2. Select a Plan
3. Observe that the Radio buttons look correct AFTER a selection has been made. Please check both **light** and **dark** mode.

fix: [M3-6235] - Fix Radio Styles after Vite Upgrade

---

docker-compose.yml

This fixes the Cypress runs that occur against our PRs by prefixing the build IDs with the PR branch name. This ensures that the build ID that gets passed to Cypress is unique, preventing an issue where Cypress would bail out because it was seeing existing runs under the same ID.
Existing PRs and branches created before this gets merged will continue having this issue, but since it doesn't block anything we can either choose to ignore it or merge these changes in on a case-by-case basis.

fix: Use Jenkins build number for Cypress unique build ID

---

packages/manager/src/features/Volumes/VolumeDrawer/AttachVolumeToLinodeForm.tsx
packages/manager/src/features/Volumes/VolumeDrawer/VolumeSelect.tsx
packages/manager/src/queries/volumes.ts
packages/manager/src/themeFactory.ts
packages/manager/src/themes.ts

- Introduces a new pattern to infinite load entities in Select components
- Why?
- For large customers our `useAll` queries are loading tens of thousands of items which will cause Cloud Manager so slow down or crash when rendering large numbers of items in Select components 
Main Points
- Infinity loads items in the Volumes Select component
- Never loads all volumes on the account 
- Allows you to search for volumes using an API filter 
- Uses MUI and not react-select 🥹
> **Note**: I know I did not add any debouncing. We can add that if we think it is important
https://user-images.githubusercontent.com/115251059/224890641-fd246800-d238-4f26-a10d-2a9b842d41c5.mov
- Test attaching an existing volume to a Linode form `http://localhost:3000/linodes/:id/storage`

refactor: Infinitely Loaded Entity Select

---

packages/manager/cypress/support/constants/regions.ts

- Updates the expected region `Tokyo 2, JP` to `Tokyo, JP` because `Tokyo 2, JP` is not a real thing according to the API
- Caused by us using the API to get region names https://github.com/linode/manager/pull/8851
- Check e2e status in CI

fix: Region in e2e tests for region `Tokyo, JP`

---

packages/manager/package.json
packages/manager/src/features/Account/AccountLanding.tsx
packages/manager/src/features/Account/AccountLogins.tsx
packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
packages/manager/src/features/Account/Agreements/withAgreements.ts
packages/manager/src/features/Account/AutoBackups.tsx
packages/manager/src/features/Account/CloseAccountDialog.tsx
packages/manager/src/features/Account/CloseAccountSetting.tsx
packages/manager/src/features/Account/EnableManaged.tsx
packages/manager/src/features/Account/EnableObjectStorage.tsx
packages/manager/src/features/Account/GlobalSettings.tsx
packages/manager/src/features/Account/ImportGroupsAsTags.test.tsx
packages/manager/src/features/Account/ImportGroupsAsTags.tsx
packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
packages/manager/src/features/Account/NetworkHelper.tsx
yarn.lock

Migrates `SRC > Features > Account` from JSS to tss-react (Emotion)
- Bumped `tss-react` version to get latest fixes from author 🎉 
- https://github.com/garronej/tss-react/issues/160 
- New updated documentation for class components: https://docs.tss-react.dev/api/withstyles#with-class-components 
- Removed `@mui/styles` imports
- Removed `React.FC`
- Removed `any` and added better typechecking to `Account/Agreements/withAgreements.ts`
- Removed deprecated `createStyles` and unnecessary `withStyles`
- Other minor cleanup
- Go to `/account/` locally and ensure all functionality still works

refactor: [M3-6241] - MUI v5 Migration - Features > Account

---

packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx

Disable the "Download CA Certificate" button while the database is be provisioned.
You can either spin up a new DB instance or utilize the MSW. I believe right now we have it so that if you go to a Database Details page with the MSW on, it randomizes the database status and view according to the status. You can either refresh until you get `Provisioning` (shouldn't be more than 2-3 refreshes) or make a change in `serverHandlers.ts`.
Confirm that DBs in statuses other than provisioning have not been impacted.

feat: [M3-5746] - Disable Download CA Certificate when DB is provisioning

---

packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/AccordionHeading.tsx
packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.test.tsx
packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx
packages/manager/src/features/linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx

Fix -> Hide warning message if Linode create flow is other than clone or backup's
- Navigate to Linode create flow
- Select image that supports clound-init (In dev select either CentOS Stream 9, Ubuntu 22.10)
- Should be able to see warning message in User data accordion for only Clone and backup's
- yarn test UserDataAccordion
- yarn cy:run
-

fix: [M3-6254] - Show warning message for only Linode clone and backups

---

packages/manager/src/components/CopyTooltip/CopyTooltip.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx
packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackupActionMenu.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsMenuItem.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx
packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx
packages/manager/src/features/Databases/DatabaseDetail/index.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseActionMenu.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx
packages/manager/src/features/Databases/index.tsx

Migrates `SRC > Features > Databases` from JSS to tss-react (Emotion)
- Removed `@mui/styles` imports
- Removed `React.FC`
- Removed deprecated `createStyles` and unnecessary `withStyles`
- Removed conditional display logic from when DBaaS was in beta
- Fixed truncation bug in Maintenance Window section
<details>
<summary>Maintenance Window truncation bug</summary>
**Production**:
**This branch**:
</details>
Take a look through the `/databases` flows in the app to ensure there have been no regressions.

refactor: [M3-6261] - MUI v5 Migration - `Features > Databases`

---

packages/manager/src/components/Accordion/Accordion.tsx

Migrates `SRC > Components > Accordion` from JSS to tss-react (Emotion)
Confirm there have been no visual regressions for Accordions in the app (ex: on Service Transfers tab)

refactor: [M3-6290] - MUI v5 Migration - `Components > Accordion`

---

packages/manager/cypress/e2e/account/service-transfer.spec.ts
packages/manager/src/components/Accordion/Accordion.tsx

- Fixes e2e test failures that I think were caused by https://github.com/linode/manager/pull/8905
- `yarn cy:debug` and run `service-transfer.spec.ts`

fix: `service-transfer.spec.ts` test failures

---

packages/manager/src/components/Drawer/Drawer.tsx
packages/manager/src/components/DrawerContent/DrawerContent.test.tsx
packages/manager/src/components/DrawerContent/DrawerContent.tsx

- Runs the codemod on `Drawer.tsx`.
- Runs the codemod on `DrawerContent.tsx` but no styling updates here -- this component didn't have styles to begin with!
- Removes `React.FC` from `Drawer` and `DrawerContent`.
- Updates the unit test for `DrawerContent` due to the need to explicitly declare the `children` prop with the removal of `React.FC`.
- A couple other small code clean up items (renaming 'DDrawer' to 'Drawer', destructuring rather than using `props.`)
Visually compare prod and this branch in a few places the components are used throughout the app. For example:
- The Add/Resize/Rename a Disk on a linode drawer
- The Add Payment Method drawer: …

refactor: [M3-6327, M3-6328] - MUI v5 Migration - Components > Drawer, DrawerContent 

---

packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/LinodeNetworking.tsx

During header refactor, the IP Addresses headline was accidentally changed: https://github.com/linode/manager/commit/49d2b7f003b05ba19bd089a0620016988e641771#diff-5caa4223a15c042e9ba9a0431e4cdfc099eff9021c407a2b8f41b927c9895b7dL716
1. Go to a Linode details page
2. Click on the Networking tab
3. Scroll down to table of IP Addresses and observe the header change

fix: [M3-4876] - Update incorrect headline

---

CHANGELOG.md
packages/manager/package.json
packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx

- Merges https://github.com/linode/manager/pull/8904 into `staging` for a hotfix
- fixes nodebalancers not saving correctly due to Bluebird being imported as `Promise`. This removed the blueird import and uses native promises

hotfix: NodeBalancer Configs

---

packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx
packages/manager/src/styles/keyframes.ts

Migrates SRC > Components > SelectionCard from JSS to `styled`/`sx` API
- Migrated to MUI `Grid` v2
- Removed `@mui/styles` imports
- Removed React.FC
- Replaced hardcoded classnames with `sx` equivalent
- Removed several unused styles
> **Note**: This drawer in `develop` seemed to be broken. Using test prod account `prod-test-012` seems to be fine: https://cloud.linode.com/account/billing/make-payment
| ![Screen Shot 2023-03-27 at 12 48 08 PM](https://user-images.githubusercontent.com/125309814/228018383-fb40aaa0-ca5d-4da5-941d-77fa8b74f207.png) | ![Screen Shot 2023-03-24 at 10 55 44 AM](https://user-images.githubusercontent.com/125309814/228018421-d397aac9-fcf2-48fe-a1ec-3fa74f932e25.png)|
1. Toggle our mock service workers
2. Go to: …

refactor: [M3-6387] - MUI v5 Migration - Components > SelectionCard

---

packages/manager/src/eventMessageGenerator.ts
packages/manager/src/features/Events/EventRow.tsx
packages/manager/src/mocks/serverHandlers.ts
packages/manager/src/utilities/getEventsActionLink.ts

- Users who use https://www.linode.com/community/ were experiencing crashes when they opened the events menu when they clicked the bell icon in the top right of Cloud Manager
- Cloud Manager would crash because a `community_question_reply` event would exist where `entity` is `null`. When we did `entity!.url`, this would cause a crash because you can't access a property on null
- The actual fix is safely accessing the `url` value on line `22` of `packages/manager/src/utilities/getEventsActionLink.ts` (this is what was causing the crash)
- This PR also includes some minor improvements:
- Uses named export instead of default export 
- Improves some event messages for community related events
- Turn the MSW **on**
- Open the Event/Notification menu by clicking the bell icon in the top right …

fix: [M3-6433] - Fix crash for Events with a `null` community post `entity`

---

packages/manager/src/components/AccountActivation/AccountActivationError.tsx
packages/manager/src/components/AccountActivation/AccountActivationLanding.tsx
packages/manager/src/components/ActionMenu/ActionMenu.tsx

Migrates `SRC > Components > AccountActivation` and `SRC > Components > ActionMenu` from JSS to tss-react (Emotion)
- Removed `@mui/styles` imports
- Removed `React.FC`
<details>
<summary>Account Activation landing page</summary>
</details>
To see the Account Activation landing page, you can set L217 of `MainContent.tsx` to `true`.
Ensure that `ActionMenu`'s in the app behave and appear as expected.

refactor: [M3-6291, M3-6292] – MUI v5 Migration - `Components > AccountActivation`, `Components > ActionMenu`

---

packages/manager/src/components/DocsLink/DocsLink.tsx
packages/manager/src/components/ExternalLink/ExternalLink.tsx
packages/manager/src/components/IconTextLink/IconTextLink.tsx

- Runs the tss-react codemod on `DocsLink.tsx`, `ExternalLink.tsx`, and `IconTextLink.tsx`.
- Removes `withStyles` and `createStyles` from `IconTextLink.tsx`.
- Removes `React.FC` from all components and explicitly defines `children` prop as necessary.
- Test that there have been no visual regressions in `ExternalLink`s, such as on an empty state landing page.
- Test that there have been no visual regressions in the `DocsLink` (and `IconTextLink`, which is used by `DocsLink`), such as on the Linode Create page.

refactor: [M3-6323, M3-6339, M3-6348] - MUI v5 Migration - Components > DocsLink, ExternalLink, IconTextLink

---

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx

- When I did https://github.com/linode/manager/pull/8915 I caused a this regression
- `packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx` is only suppose to show notifications regarding a specific Linode but in my refactor, I accidently render **all** notifications. This fix restores previous behavior which is only showing notifications on a Linode details page that are associated with a Linode
- Turn **on** the MSW
- Go to `http://localhost:3000/linodes/0`
- Verify that you **do not** see a notice saying anything about a "past due balance"
- If you are able to confirm that, you can consider this fix to be working

fix: Linode Details Notifications showing all notifications

---

packages/manager/src/components/ActionsPanel/ActionsPanel.tsx
packages/manager/src/components/SelectionCard/CardBase.tsx
packages/manager/src/components/SelectionCard/SelectionCard.tsx
packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx
packages/manager/src/features/LinodeConfigSelectionDrawer/LinodeConfigSelectionDrawer.tsx
packages/manager/src/features/Users/UserPermissions.tsx
packages/manager/src/features/linodes/LinodesCreate/AppPanelSection.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectLinodePanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
packages/manager/src/features/linodes/LinodesCreate/SelectionCardWrapper.tsx

The parent components for Marketplace selection cards needed to be updated as well with new Gridv2.
- Updated all Grid references that used `SelectionCard`
- Migrated `ActionsPanel` since that was connected to one of the files affected
|<img width="889" alt="Screen Shot 2023-03-29 at 4 32 55 PM" src="https://user-images.githubusercontent.com/125309814/228661204-76251380-13fd-40d1-baaf-64617a2ef83d.png">|<img width="1918" alt="Screen Shot 2023-03-29 at 4 31 25 PM" src="https://user-images.githubusercontent.com/125309814/228661232-11390ab1-8424-4899-8843-fbc79ead28a0.png">|
- Compare http://localhost:3000/linodes/create?type=One-Click with Prod
- Ensure "Make a Payment" is still good: http://localhost:3000/account/billing/make-payment
- …

fix: [M3-6387] - MUI v5 Migration - Components > SelectionCard & ActionsPanel

---

packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx

- Fixes a bug that caused users to see `Could not apply filter` when filtering by `Status` on the `/linodes/:id/storage` page in the Volumes Table
- This bug was caused by misspelling `status` as `Status` which resulted in an API error because `Status` is not a field returned by the API but `status` is
- This PR also adds pagination controls to Firewalls Landing because they were missing
https://user-images.githubusercontent.com/115251059/228903288-5cd57927-8c13-48ed-8b38-058fe3871424.mov
- You may need a volume attached to a Linode
- Go to  `/linodes/:id/storage` for that Linode and stort the volumes table by `Status`
- Verify that the API returns a successful response in the dev tools and that the table shows no errors

fix: [M3-6453] - Filtering by `Status` on Linode Details Volumes Table

---

packages/manager/src/queries/profile.ts

- This is a small tweak to our grants query that only enables the query when a user is restricted
- For unrestricted users, the `/v4/profile/grants` endpoint returns an empty response because the user is unrestricted 
- https://www.linode.com/docs/api/profile/#grants-list
- This change will save Cloud Manager from making an unnecessary API call resulting in possible better performance and less load on the Linode API
| ![Screenshot 2023-03-29 at 6 40 49 PM](https://user-images.githubusercontent.com/115251059/228688375-fc7723e9-4c76-414d-b4bf-d342053c5686.jpg)     | ![after](https://user-images.githubusercontent.com/115251059/228688293-331d6e60-8015-4d01-b675-133098d45d7b.jpg)     |
- As an unrestricted user
- Login and verify that Cloud does **not** …

perf: Only fetch `/v4/profile/grants` if a user is `restricted`

---

packages/manager/src/components/BackupStatus/BackupStatus.tsx
packages/manager/src/components/BackupStatus/index.ts
packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRowBackupCell.tsx

Migrates `SRC > Components > BackupStatus` from JSS to tss-react (Emotion)
On the Linodes landing page, confirm that cells in the "Last Backup" column still display as expected.

refactor: [M3-6295] - MUI v5 Migration - `Components > BackupStatus`

---

packages/manager/.storybook/preview.tsx
packages/manager/src/components/EntityTable/EntityTable.stories.mdx
packages/manager/src/components/TooltipIcon/TooltipIcon.stories.mdx

Some components in storybook make some auxiliary API requests that will currently fail.  An example is the `TagsInput` component, which requests tag suggestions to display when the user has the input selected.
| ![Screenshot 2023-04-04 at 3 00 10 PM](https://user-images.githubusercontent.com/122488130/229893895-fac5f275-227e-4bb3-93de-65e0c7c02b99.jpg)|![Screenshot 2023-04-04 at 2 59 37 PM](https://user-images.githubusercontent.com/122488130/229893932-cc619416-fbfc-4ece-b92c-14d2d13bc15b.jpg)|
Run storybook locally via `yarn storybook` and verify that components that make API requests (e.g., `TagsInput`) display correctly.

docs: Enable MSW in storybook

---

packages/manager/src/featureFlags.ts

Remove deprecated `linode_tax_id` property from the `TaxBanner` interface in `featureFlags.ts` and clean up the LD `tax-banner` variations accordingly.
Ensure that the Billing & Payment History section and invoices have not been adversely impacted.

chore: [M3-5939] - Remove deprecated `linode_tax_id` property

---

packages/manager/src/components/BetaChip/BetaChip.tsx
packages/manager/src/components/BetaChip/index.ts
packages/manager/src/components/Breadcrumb/Breadcrumb.test.tsx
packages/manager/src/components/Breadcrumb/Breadcrumb.tsx
packages/manager/src/components/Breadcrumb/index.tsx
packages/manager/src/components/LandingHeader/LandingHeader.tsx
packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
packages/manager/src/dev-tools/FeatureFlagTool.tsx
packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeControls.tsx
packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailsBreadcrumb.tsx

- Migrate BetaChip and Breadcrumb component from JSS to tss-react (Emotion)
- Remove React.FC
- Use named exports instead of default
Use the DevTools to turn the Database Beta flag on and observe the Beta chip in the primary nav and Database Create breadcrumb. Check other places in the app where Breadcrumb is used

refactor: [M3-6297, M3-6298] - MUI v5 Migration - Components > BetaChip & Breadcrumb

---

packages/manager/src/components/BarPercent/BarPercent.tsx

Migrates `SRC > Components > BarPcent` from JSS to tss-react (Emotion)
Confirm that the `BarPercent` component looks as expected throughout the app, including in the Monthly Network Transfer Pool modal and event progress bar in the notifications drawer.

refactor: [M3-6296] - MUI v5 Migration - `Components > BarPercent`
