linode/manager

packages/manager/cypress/e2e/linodes/clone-linode.spec.ts
This fixes some flake with our `clone-linode.spec.ts` e2e tests. The tests fail when there are Linodes present on the account in the Newark region, because Cypress mistakenly clicks the Linode in the "Select Linode to Clone From" section instead of the "Newark, NJ" region selection item.
This is a quick band aid to fix the problem, but in the future we'll introduce UI helpers to simplify interactions with drop-downs, autocomplete text fields, etc. that will guard against issues like this.
1. On your test account, create a Linode in the Newark region. Make sure the Linode label does **not** have a `cy-test-` prefix.
2. Run `yarn && yarn build && yarn start:manager:ci`
3. To reproduce the issue, …
=> fix: Fix Clone Linode e2e test flake when Newark resources exist

packages/manager/cypress/e2e/nodebalancers/smoke-create-nodebal.spec.ts, packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- Caused by https://github.com/linode/manager/pull/8964
- Fixes e2e test failure caused by updates
- Removes some render guards because the equals function that the render guard is using does not work as expected
- Look at cypress results of this PR
- If the nodebal spec passes, we can assume I fixed the bug and the e2e test
=> fix: NodeBalancer Create e2e tests and associated bug

packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
- Local version of `Skeleton` no longer exists, so fixing import path for skeleton to use MUI
- Test loading states on NodeBalancer create, update, and delete actions
=> fix: skeleton import path

README.md
- Rebrands to Akamai
- Makes our `README.md` look less crusty
- Uses badges to give us (and users) some useful stats
- CI status (we can't do cypress with our current setup, sorry)
- Online status for cloud.linode.com
- Cloud Manager's version
- Storybook Link
- api-v4 and validation versions
- api-v4 and validation bundle sizes
- ~Adds some emojis to add some color (we can remove if it's too cringe)~
=> chore: [M3-5751] - Improve the `README.md`

packages/manager/src/components/CheckBox/CheckBox.tsx
Migrates `SRC > Components > CheckBox` from JSS to styled components
Confirm that there have been no visual regressions in the app where the `CheckBox` component is used (e.g., the "Enable HA Control Plane" option in the LKE Create flow, SSH Key panel in the Linode Create flow, etc.).
=> refactor: [M3-6299] – MUI v5 Migration - `Components > CheckBox`

packages/manager/src/components/Dialog/Dialog.tsx
- This PR fixes the Block Device Assignment related form labels bleed through the header background.
- Removes unwanted Grid tags.
- Navigate to Linode's page and click on Linode.
- Click on Configurations tab.
- Click on Add Configuration button.
-  Validate Block Device Assignment related form labels. (Content shouldn't overlap the header)
- yarn test
- yarn cy:run
=> fix: [M3-6425] - Linode Details Add Configurations Modal Header

packages/manager/src/components/Breadcrumb/Breadcrumb.stories.mdx
Looks like default exports are being deprecated and the `Breadcrumb` Storybook doc import was broken as a result. We were also missing a `React` import for the `EditableBreadcrumbTemplate` `useState` instance.
I think it broke from this [PR](https://github.com/alioso/manager/commit/f40f7b607f42ac59fad7aee4d819afd073b5a368)
**Before**
**After**
Pull PR locally, run `yarn storybook` and navigate to http://localhost:6006/?path=/docs/components-breadcrumb--docs
=> fix: [M3-6298] - Fix breadcrumb story import and missing react import

packages/manager/src/components/StackScript/StackScript.tsx, packages/manager/src/components/StackScript/index.ts
Migrates `SRC > Components > StackScript` from JSS to tss-react (Emotion)
Ensure nothing broke visually on the StackScript Detail page.
=> refactor: [M3-6395] – MUI v5 Migration - `Components > StackScript`

packages/manager/src/components/SplashScreen/SplashScreen.tsx
Migrates `SRC > Components > SplashScreen` from JSS to styled components (Emotion)
Confirm the splash screen on app load/reload has not been adversely impacted.
=> refactor: [M3-6394] – MUI v5 Migration - `Components > SplashScreen`

CHANGELOG.md, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.tsx
- Clears the Kubernetes Delete Dialog onSuccess so that the dialog input is empty the next time it is opened
- Thank you @jdamore-linode for finding this
https://user-images.githubusercontent.com/115251059/231811670-8b38f5b3-5d94-4511-b605-1af5ac88c3ca.mov
https://user-images.githubusercontent.com/115251059/231811550-71d2dd08-6f8e-4962-965e-81bb14d509ca.mov
- Make sure the Kubernetes Delete Dialog clears when reopening it
=> fix: [M3-6312] - Clear Kubernetes Delete Dialog when it is reopened

CHANGELOG.md, packages/manager/src/eventMessageGenerator.test.ts, packages/manager/src/eventMessageGenerator.ts
**Issue**
Our `applyLinking` script was attempting to replace entity labels within backticks, resulting in plaintext HTML in our event list. It was also not linking the true entity because the replace instance wasn't using a global modifier in case two instances of the label were matching.
**Solution**
Modified the replace to only target true labels and leave alone strings surrounded by backticks. Also added a test for the `applyLinking` function
**Before**
**After**
1. add a new domain
2. add a new ttl record with a different name
3. add a new ttl record with same name as domain
4. navigate to /events
=> fix: [M3-6430] - Event entities should only be linked for true labels

packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx, packages/validation/src/firewalls.schema.ts
Fix a [codeQL inefficient regex warning](https://github.com/linode/manager/security/code-scanning/25) for firewall custom ports (exponential backtracking on strings containing many repetitions of '-') in the firewall rule drawer.
I increased the regex matching specificity to only match:
`42`
`1-10`
`1,2,3,4,5`
and disallow things like:
`1--10`
`1-2-3`
`1,2,3-4-5`
`1-2,3-4`
along with extra spaces etc
- pull code locally, and add some rules at `/firewalls/[id]/rules`
- `yarn test FirewallRuleDrawer`
or
- test regex at https://regex101.com/ or other online tool
=> fix: [M3-6442] - Inefficient firewall custom ports regex

packages/manager/src/components/StatusIcon/StatusIcon.stories.mdx, packages/manager/src/components/StatusIcon/StatusIcon.tsx, packages/manager/src/components/StatusIcon/index.tsx, packages/manager/src/features/Account/AccountLoginsTableRow.tsx, packages/manager/src/features/Account/Maintenance/MaintenanceTableRow.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx, packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx, packages/manager/src/features/Domains/DomainTableRow.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx, packages/manager/src/features/Volumes/VolumeTableRow.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupTableRow.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- Migrate StatusIcon component from JSS to styled components (Emotion)
- Use named export instead of default
- Check places in the app where StatusIcon is used
- Ensure that the StatusIcon story renders in Storybook
=> refactor: [M3-6396] - MUIv5 Migration - Components > StatusIcon

CHANGELOG.md, README.md
- The badge for the validation said api-v4 on accident. This updates the badge to show the correct label
- Use Github's view feature to see the `README.md`
=> fix: `README.md` Validation Version Badge Label

packages/manager/src/components/ColorPalette/ColorPalette.stories.mdx, packages/manager/src/components/ColorPalette/ColorPalette.tsx
- Ran the tss-react codemod on ColorPalette.
- Modernized ColorPalette by using named exports.
yarn test
yarn cy:run
=> refactor: [M3-6303] - SRC > Components > ColorPalette

docs/PULL_REQUEST_TEMPLATE.md
Slightly improves the PR template
- Adds "Major Changes" section for changes you want to highlight
- Adds table for preview section
- Be more explicit for testing section
- Add `note` syntax for "Commit message" section
=> chore: slightly improve PR template

packages/manager/cypress/e2e/linodes/rescue-linode.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts
Attempts to resolve the flakiness we've been seeing with these tests by navigating directly to the Linode rescue dialog at `/linodes/:id/?rescue=true`. We've been seeing some flakiness in this test and others related to Cypress's interactions with our action menus (and I still haven't nailed down the root cause of that) so this works around that problem by cutting out the action menu interactions.
`yarn && yarn build && yarn start:manager:ci`, and then:
```bash
yarn cy:run -s "cypress/e2e/linodes/rescue-linode.spec.ts"
```
=> refactor: Clean up Linode rescue tests, work around flake caused by action menu interactions

CHANGELOG.md, packages/manager/src/components/Radio/Radio.tsx
This is a tiny styling tweak to the radio button component to make sure that the halo that appears when hovering over a radio button is circular.
*Before:*
*After:*
To reproduce, navigate to any page that uses radio buttons (Linode create page, for example) and observe that the hover effect halo on the radio button is an oval. To verify this change, check out this branch and confirm that the hover effect is circular.
=> fix: Increase radio button padding to fix hover effect shape

CHANGELOG.md, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx, packages/manager/src/utilities/areArraysEqual.test.ts, packages/manager/src/utilities/areArraysEqual.ts
When the IP Transfer dialog is opened, a user can click "Save" without having selected any action. Clicking the button displays a message that says "IP transferred successfully" even though no action was taken.
This is confusing since it may lead users to believe that they've successfully transferred an IP from one Linode to another without having done so.
This PR adds a simple check to the onSubmit to see if any action has been selected for a linode. If not, it displays an error to the user. It also does so for the IP sharing modal.
This PR also:
- Resets the error messages on modal open
- Fixes a styling regression from https://github.com/linode/manager/pull/8985/files
- If necessary, create a Linode
- Navigate to its details page, click on the "Network" tab
- Click the "IP Transfer" …
=> fix: [M3-5976] - Prevent IP transfer & sharing modals form submission if no action selected

packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx
- Fixes flake in `ObjectDetailsDrawer.test.tsx` by ensuring a test has a clean environment with a consistent timezone
- `yarn test ObjectDetailsDrawer`
=> fix: Improve stability of `ObjectDetailsDrawer.test.tsx`

packages/manager/src/components/ExternalLink/ExternalLink.tsx
- Fixes https://github.com/linode/manager/security/code-scanning/23
- Uses Braintree's `sanitize-url` because it already is already baked into our repo
- I considered `sanitize-html`, which we also have installed, but Braintree's `sanitize-url` seems like a better fit for this use case
- The `<ExternalLink />` component now sanitizes any link it is given
- Verify that the `<ExternalLink />` component still works as expected
- You can test this by clicking links in the Footer
- Verify that `SupportSearchLanding` (http://localhost:3000/support/search/?query=) still works as expected because this is what triggered the alert
=> fix: [M3-6446] - Fix code scanning alert that DOM text is reinterpreted as HTML

packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts, packages/manager/src/components/EnhancedSelect/components/MenuList.tsx
- Uses the `autocompletePopper` UI helper to interact with the Object Storage ACL select element, eliminating the issue that causes occasional flakiness with the Object Storage end-to-end tests.
- Wraps the `EnhancedSelect` component's menu list items in a div with a `data-qa-autocomplete-popper` attribute. This was done so that our e2e `autocompletePopper` UI helper works with our old selects (`EnhancedSelect`) in addition to newer selects based on MUI. I was reluctant to change the DOM structure but haven't observed any issues or changes stemming from this addition -- happy to revisit if the team would prefer another approach.
`yarn && yarn build && yarn start:manager:ci` and then:
```bash
yarn cy:run -s "cypress/e2e/objectStorage/object-storage.e2e.spec.ts"
```
Confirm that the tests …
=> refactor: Improve Object Storage E2E flake related to ACL select

packages/manager/cypress/e2e/firewalls/update-firewall.spec.ts, packages/manager/cypress/support/ui/buttons.ts, packages/manager/src/factories/firewalls.ts
Add Cypress end-to-end tests which confirm the expected behavior of Cloud Manager Firewall features.
Test cases:
- Linodes can be added and removed from a firewall
- Inbound rules can be added and removed from a firewall
- Outbound rules can be added and removed from a firewall
- Firewalls can be enabled and disabled, and their status is reflected on the landing page (/firewalls)
`yarn cy:run -s "cypress/e2e/firewalls/update-firewall.spec.ts"`
=> test: [M3-6248] - Add Cypress Firewall e2e Update tests

packages/manager/.eslintrc.js
Adding a couple rules that should prevent a commit from going through if condition met (before that contributors may have been able to see the error in the IDE but commit could go through nonetheless
I set `react-hooks/exhaustive-deps` as a warning for now (there's 80+ offenders in the codebase) but since we only lint staged code anyway it shouldn't affect velocity either way unless you start editing and attempt to commit said offender
=> chore: add more hook rules to eslint

packages/api-v4/src/firewalls/types.ts, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleTable.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/firewallRuleEditor.ts
- Fixes `firewallRuleEditor.test.ts` failing caused by changes in #9017 
- Makes api-v4 types accurate
- Improves handling of `label` and `description`
- `yarn test firewallRuleEditor.test.ts`
- Thoroughly test the firewalls rule editor
- Specifically test the functionality of creating rules, editing rules, and discarding changes.
- Specifically test the `label` and `description` fields and their behavior
=> fix: `firewallRuleEditor.test.ts` failure

CHANGELOG.md, packages/manager/src/components/CheckoutBar/CheckoutBar.tsx, packages/manager/src/components/CheckoutBar/DisplaySection.tsx, packages/manager/src/components/CheckoutBar/DisplaySectionList.tsx, packages/manager/src/components/CheckoutBar/index.ts, packages/manager/src/components/CheckoutBar/styles.ts, packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx
Migrates `SRC > Components > CheckoutBar` from JSS to styled components.
- Removed `packages/manager/src/components/CheckoutBar/index.ts`
- Made use of styled components in `CheckoutBar.tsx`, housed in `/CheckoutBar/styles.ts`
Go to `/kubernetes/create` and ensure the checkout bar looks and functions the same as in prod.
=> refactor: [M3-6300] - MUI v5 Migration - `Components > CheckoutBar` 

CHANGELOG.md, packages/manager/src/components/LineGraph/AccessibleGraphData.test.tsx, packages/manager/src/components/LineGraph/AccessibleGraphData.tsx, packages/manager/src/components/LineGraph/LineGraph.stories.mdx, packages/manager/src/components/LineGraph/LineGraph.tsx, packages/manager/src/components/LineGraph/NewMetricDisplay.styles.ts, packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
Apart from a general description as to what the chart is representing, there's is currently no information details available to screen readers users. This is an accessibility issue described in M3-5915.
This PR attempts to improve this limitation by adding a visually hidden data table to each line chart. Please refer to the self review for implementation details as well as the code inline comments.
This PR follows the [accessibility guidelines for the canvas element](https://pauljadam.com/demos/canvas.html).
Note: this only targets `<Linegraphs />` and does not address Longview graphs (I added a separate M3-6517 ticket for those, which is lower priority).
There is no visual change associated with this PR
A few ways this PR should be tested.
1. Use an accessibility tool to inspect the new …
=> feat: [M3-5915] Accessible graph data

packages/manager/cypress/e2e/domains/smoke-create-domain-records.spec.ts, packages/manager/cypress/e2e/domains/smoke-create-domain.spec.ts, packages/manager/cypress/support/intercepts/domains.ts
- Refactor Domains tests to use defined intercepts methods
- Created a `domains.ts` file.
- Changed to use the intercepts methods in the file above.
Run the commands:
`yarn cy:run -s "cypress/e2e/domains/smoke-create-domain-records.spec.ts"`
`yarn cy:run -s "cypress/e2e/domains/smoke-create-domain.spec.ts"`
=> refactor: [M3-6217]: Refactor Domains E2E Test Intercepts

CHANGELOG.md, packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx, packages/manager/src/components/Notice/Notice.tsx
Our current banner text is too large and cramped. To improve readability, we'll change text size of body text to `14px` (or equivalent) and line height to `20px`. Blue banner title can remain current size.
These requirements should apply to:
- AbuseTicketBanner
- DismissibleBanner
- ProductInformationBanner
- DomainBanner
- APIMaintenanceBanner
- ComplianceBanner
- TaxCollectionBanner
- StatusBanners
...all of which rely on the `DismissibleBanner` component, which uses the `Notice` component under the hood.
- Removes fontSize styling on the inner `p` tag of the `Notice` component, which was overwriting existing styling of `fontSize: 0.875rem` (`14px`). 
- Adds lineHeight styling to `DismissibleBanner.tsx`. Existing Typography styling was applying a …
=> style: [M3-6030] - Adjust banner text size and spacing to improve readability

packages/manager/src/features/StackScripts/stackScriptUtils.ts
- Removes MongoDB Marketplace Apps
- Verify you do not see any MongoDB Marketplace Apps
- Verify both normal and cluster do not show
=> fix: [M3-6543] - Remove MongoDB Marketplace Apps

CHANGELOG.md, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Currently these PDFs are >1 MB in size. With this change, my testing showed the resulting PDF to be closer to 50kb in size. Logo quality looks the same to me 🤷🏽 
Generate a PDF of the same invoice with and without this change.
=> fix: [M3-6022] - Add compression to logo when rendering in JPG format during invoice PDF generation

packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/objectStorage.ts, packages/manager/src/utilities/testHelpers.tsx
- Surfaces any general errors as a notice in the Object Storage Create Bucket drawer
- Previously, only errors specific to the `label` and `region` would show
- Enable the MSW
- Uncomment the mock error in `serverHandlers.ts` 
- Try to create an Object Storage Bucket
- Observe that a general error is shown as a notice
=> fix: [M3-6540] - Surface general errors in the Object Storage Bucket Create Drawer

CHANGELOG.md, packages/manager/src/features/Volumes/VolumesLanding.tsx, packages/manager/src/features/Volumes/VolumesLandingEmptyState.styles.ts, packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx, packages/manager/src/features/linodes/LinodesLanding/LinksSubSection.tsx
Add resource links to Volumes empty state landing page
- New files: `VolumesLandingEmptyState.tsx` & `VolumesLandingEmptyState.styles.ts`
- Some empty state styling updated to use `styled()` API
- Associated changes in `VolumesLanding.tsx`
<details>
<summary>Normal view</summary>
</details>
<details>
<summary>Mobile view</summary>
</details>
Confirm that all links and copy are correct. Check the layout at various breakpoints.
=> feat: [M3-6464] – Add resource links to empty Volumes landing page

packages/manager/src/featureFlags.ts, packages/manager/src/features/linodes/LinodesCreate/PremiumPlansAvailabilityNotice.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
This PR allows the "This plan is only available in the Washington, DC region." notices for the Linode and LKE creation pages to be dynamic for quick iteration during the launch, as the available DC(s) isn't confirmed yet. 
This PR introduces no visual difference as the content is the same, just made dynamic
1. make sure to have the `premium_dedicatedcpu` tag in admin (enables premium feature)
2. make sure to have your `REACT_APP_LAUNCH_DARKLY_ID` env var set locally to the production key
3. confirm flag setup is proper in LaunchDarkly (`premiumPlansAvailabilityNotice`)
4. navigate to /linodes/create & /kubernetes/create then Linode Plan > Premium and confirm both banners are showing up and have the right content
5. Alternatively feel free to change the flag string in LD to confirm the …
=> feat: [M3-6520] - Add new flag to deliver DC availability notice for premium plans

CHANGELOG.md, packages/manager/src/features/OneClickApps/FakeSpec.ts
Remove 'MongoDB' from ClusterControl description in Marketplace
| ![Screen Shot 2023-05-03 at 3 22 59 PM](https://user-images.githubusercontent.com/125309814/236024233-768c1d29-1e86-46bd-8e51-142a0d541ca5.png) | ![Screen Shot 2023-05-03 at 3 22 30 PM](https://user-images.githubusercontent.com/125309814/236024274-0a6c4d86-2d39-4360-8b77-0f2f6e1ae3a2.png) |
1. Go to: http://localhost:3000/linodes/create?type=One-Click
3. Search for "ClusterControl"
4. Click information icon
5. Observe drawer no longer contains reference to MongoDB
=> fix: [M3-6558] - Remove 'MongoDB' from ClusterControl description in Marketplace

CHANGELOG.md, packages/manager/src/features/Search/refinedSearch.test.ts, packages/manager/src/features/Search/refinedSearch.ts
`simpleSearch` is mistakingly interpreting an IPv6 address as containing a search field because of the presence of semi-colons. This PR adds a `shouldSkipFieldSearch` utility that maps through x number of string matching expressions that can force a simple search (no field lookup)
1. Make sure to have a linode with an IPv6 address
2. Copy address from the summary, paste it in the search bar and make sure there's a match
=> fix: [M3-5088] - Allow simple search for IPv6 addresses

packages/manager/cypress.config.ts
Enables Cypress's experimental memory management config option in an attempt to reduce the number of failed runs caused by Chrome renderer process crashes.
I'm going to run our tests against this PR several times to get an idea of whether or not this is effective, and will have this labeled with Work in Progress and Do Not Merge in the meantime.
There are two things that we want to confirm with this PR to the best of our abilities: that it fixes the Chrome renderer crash when run via Jenkins/GHA, and that it continues working when running locally.
We can rely on the Jenkins PR runs to confirm the first, and to confirm the second we can run Cypress locally:
```bash
yarn cy:run
```
I'll probably re-run the Jenkins job several times to continue building confidence that this change is …
=> fix: [M3-6509] - Enable Cypress's experimental memory management config

packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts, packages/manager/cypress/e2e/images/machine-image-upload.spec.ts, packages/manager/cypress/e2e/images/smoke-create-image.spec.ts, packages/manager/cypress/support/intercepts/images.ts, packages/manager/cypress/support/intercepts/linodes.ts
- Refactor Images tests to use defined intercepts methods
- Created a `images.ts` file.
- Updated code in `linodes.ts` file.
- Changed to use the intercepts methods in the file above.
`yarn cy:run -s "cypress/e2e/images/create-linode-from-image.spec.ts"`
`yarn cy:run -s "cypress/e2e/images/machine-image-upload.spec.ts"`
`yarn cy:run -s "cypress/e2e/images/smoke-create-image.spec.ts"`
=> refactor: [M3-6222] - Refactor Images E2E Test Intercepts

packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- Fixes UI regression in the Linode Details Entity Header access table caused by https://github.com/linode/manager/pull/9082
- This could probably be fixed other ways but making the easy change because it matches the original intention of the component and we may rebuild some UI soon and it can be fixed then
| ![Screenshot 2023-05-05 at 9 21 08 AM](https://user-images.githubusercontent.com/115251059/236469194-3c65113f-844b-4146-a225-44d2ed850e33.jpg) | ![Screenshot 2023-05-05 at 9 20 50 AM](https://user-images.githubusercontent.com/115251059/236469243-0c54c586-c826-4971-a2c4-6cb5933dedd0.jpg) |
- Check the UI shown above
=> fix: Linode Details Access Table UI

CHANGELOG.md, packages/manager/src/features/linodes/LinodesLanding/AppsSection.tsx
Update the highlighted OCAs on the empty state Linodes landing page and slightly increase the height of the button cards
| ![Screenshot 2023-05-04 at 4 28 03 PM](https://user-images.githubusercontent.com/114682940/236322117-c1c1567d-a4cf-4d34-860a-0bb9671119f1.jpg) | ![Screenshot 2023-05-04 at 4 36 21 PM](https://user-images.githubusercontent.com/114682940/236323377-03795922-b02c-4fee-81eb-186d46e7f105.jpg) |
- Ensure the OCA links on the empty state Linodes landing page take you to the indicated OCAs
=> change: [M3-6483] – Update OCAs highlighted on empty state Linodes landing page

packages/manager/src/components/ShowMoreExpansion/ShowMoreExpansion.tsx, packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Updates `ShowMoreExpansion` component used for Stackscripts `UserDefinedFieldsPanel` and `TicketAttachments` (although you're not able to attach more than 5 attachments at a time to a ticket, so we may be able to be remove this). I didn't want to do too much refactoring here since this seems like a component that will get removed in the future.
- Update import/exports
- Remove jss for tss emotion
| TicketAttachment.tsx (can't get to show)  | UserDefinedFieldsPanel.tsx   |
| <img width="581" alt="Screen Shot 2023-05-08 at 1 22 57 PM" src="https://user-images.githubusercontent.com/125309814/236892465-1b826e3b-69fb-4481-b121-c9ba9a2cb131.png"> | ![Screen Shot 2023-05-08 at 1 03 41 PM](https://user-images.githubusercontent.com/125309814/236892488-01d5a579-a70a-4933-9f77-6 …
=> refactor: [M3-6390] - MUI v5 - Components/ShowMoreExpansion

CHANGELOG.md, packages/manager/src/components/CheckoutSummary/CheckoutSummary.tsx, packages/manager/src/components/CheckoutSummary/SummaryItem.tsx
Migrates `SRC > Components > CheckoutSummary` from JSS to styled components.
Confirm that the checkout summary sections in the Linode Create and Kubernetes Create flows are unchanged compared to prod across viewport widths.
=> refactor: [M3-6301] – `MUI v5 - Components > CheckoutSummary`

CHANGELOG.md, packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSection.tsx, packages/manager/src/components/EmptyLandingPageResources/ResourcesLinksSubSection.tsx, packages/manager/src/features/Images/ImagesLanding.tsx, packages/manager/src/features/Images/ImagesLandingEmptyState.tsx, packages/manager/src/features/Images/ImagesLandingEmptyStateData.ts
Adding new resource links to Images landing empty state
**Note**: no subtitle was provided for this landing page
| ![Screenshot 2023-05-08 at 1 12 04 PM](https://user-images.githubusercontent.com/130582365/236887550-01d6e669-3076-42b3-a1bf-9d1fa9e0e4f3.jpg) | ![Screenshot 2023-05-08 at 1 11 54 PM](https://user-images.githubusercontent.com/130582365/236887553-d71c640c-110c-40b6-b12f-b3cc82a038d6.jpg) |
1. Navigate to /images with no image created and verify CTA and link destinations
=> feat: [M3-6466] Add resource links to Images empty state

CHANGELOG.md, packages/manager/cypress/e2e/objectStorage/access-keys.smoke.spec.ts, packages/manager/cypress/e2e/objectStorage/object-storage.e2e.spec.ts, packages/manager/cypress/e2e/objectStorage/object-storage.smoke.spec.ts, packages/manager/cypress/support/ui/index.ts, packages/manager/cypress/support/ui/landing-page-empty-state-resources.ts, packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx, packages/manager/src/components/LandingHeader/LandingHeader.tsx, packages/manager/src/components/Placeholder/Placeholder.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLanding.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLandingEmptyResourcesData.ts, packages/manager/src/features/ObjectStorage/BucketLanding/BucketLandingEmptyState.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/StylesBucketIcon.ts, packages/manager/src/features/ObjectStorage/ObjectStorageLanding.tsx
Add resource links to Object Storage empty state
**Note**: no description text was provided by the ticket
| ![Screenshot 2023-05-08 at 5 26 20 PM](https://github.com/linode/manager/assets/130582365/a1cc2057-843d-419f-b46b-5fcc359e3cfb)  | ![Screenshot 2023-05-09 at 11 49 22 AM](https://github.com/linode/manager/assets/130582365/3453fd81-62b7-463b-b2ec-82fb59ba7610) |
1. Navigate to /object-storage/buckets with no bucket created and verify CTA and link destinations
2. Verify headers on both "Buckets" & "Access Keys" tabs
3. Create a bucket
4. Verify headers on both "Buckets" & "Access Keys" tabs
=> feat: [M3-6468] Add resource links to Object Storage empty state

packages/manager/src/features/Databases/DatabaseLanding/DatabaseEmptyState.tsx
Restores `<ProductInformationBanner />` in `DatabaseEmptyState.tsx` so DBaaS-specific banners will display on the empty state landing page.
On an account with no DBaaS instances, confirm that you see the banner displayed in the screenshot below:
=> fix: [M3-6575] – Restore `<ProductInformationBanner />` in DatabaseEmptyState.tsx

CHANGELOG.md, packages/manager/src/App.tsx
- Send page views to Adobe Analytics
- We are making this change to match what we did for Google Analytics
- This is pretty typical SPAs to need this
- Run `_satellite.setDebug(true)` in the dev console
- Refresh the page
- Navigate around the app 
- Verify you see `🚀 "page view" does not match any direct call identifiers.` in the console
- This sounds like an error, but I think it's just because configuration is needed on the Adobe Analytics side
=> chore: [M3-6574] - Send Adobe Analytics Page Views

packages/manager/src/features/OneClickApps/FakeSpec.ts
**Brief description explaining the purpose of the changes**
This is a follow up from #9081 because the `alt_description` still contained a reference to the app. This meant that ClusterControl came up in the search results if a user searched "MongoDB" (and would likely be read out via a screenreader, though I didn't confirm that). 
| ![Screenshot 2023-05-15 at 11 25 20 AM](https://github.com/linode/manager/assets/114685994/4888a8af-7dd9-4e2d-b167-1584cd7e0f42) | ![Screenshot 2023-05-15 at 11 25 07 AM](https://github.com/linode/manager/assets/114685994/69362702-feed-4456-8462-2bb3b14f6f9a) |
2. **How to reproduce the issue (if applicable)?**
Test the marketplace search on staging and note that "ClusterControl" is returned as a search result if the …
=> fix: Remove 'MongoDB' from ClusterControl alt_description in Marketplace

CHANGELOG.md, packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx, packages/manager/src/components/EntityHeader/EntityHeader.tsx, packages/manager/src/components/EntityHeader/index.tsx, packages/manager/src/features/linodes/LinodeEntityDetail.tsx
- Fix import/export of EntityHeader
- removed React.FC
We currently have disabled summary view in dev, but it affects this component:
1. Things should function the same
=> refactor: [M3-6334] - MUI v5 - Components > EntityHeader

packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx
- Send the user back to `/linodes` when they delete a Linode from the details page
- This behavior was lost during a React Query for Linodes refactor, this PR is restoring the lost functionality
https://github.com/linode/manager/assets/115251059/0da079da-6a26-4b03-9afa-d5759534f426
https://github.com/linode/manager/assets/115251059/4bd88bbf-e882-4edc-a889-4e340ae48ef5
- Delete a Linode from its details page and verify that you get sent back to `/linodes` upon a successful deletion
=> fix: Redirect to Linodes Landing when delete happens on the Linode details page

packages/manager/cypress/e2e/domains/smoke-delete-domain.spec.ts, packages/manager/cypress/e2e/domains/smoke-domain-download-zone-file.spec.ts, packages/manager/cypress/e2e/domains/smoke-domain-import-a-zone.spec.ts, packages/manager/cypress/support/helpers.ts, packages/manager/cypress/support/intercepts/domains.ts, packages/manager/src/factories/domain.ts
Add new cypress tests for Domain
- Add Domain delete tests.
- Add Domain import a zone tests.
- Add Domain download zone file tests.
`yarn cy:run -s "cypress/e2e/domains/smoke-delete-domain.spec.ts"`
`yarn cy:run -s "cypress/e2e/images/smoke-domain-import-a-zone.spec.ts"`
`yarn cy:run -s "cypress/e2e/images/smoke-domain-download-zone-file.spec.ts"`
=> test: [M3-6550] - Add Domain delete, import a zone, and download zone file Cypress tests

packages/manager/scripts/changelog/changeset.mjs, packages/manager/scripts/changelog/utils/getPullRequestId.mjs
Minor changeset improvements and bug fix
- Changeset commits will now add a little bit of information from the description
- Fixed a bug where the command wasn't failing if there was no PR. We were getting successful commits with `NAN` in the name: `pr-NaN-tech-stories-1684294685319.md`
Working now
=> chore: [M3-6582] - Changeset description and bug fix

CHANGELOG.md, packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx
Hotfix for a reference error for linodes detail page backup tabs
- Placement / reference of the code needed to happen after initialization
> **Note**: Use `<video src="" />` tag when including recordings in table
| ![Screenshot 2023-05-17 at 9 24 35 AM](https://github.com/linode/manager/assets/125309814/2e53ad45-4291-4da2-a53e-37dadf590c62) | ![Screen Shot 2023-05-17 at 10 00 43 AM](https://github.com/linode/manager/assets/125309814/56a99fca-975e-455c-b2af-a974e73d37ed) |
1. Checkout branch `yarn dev`
2. Go to: http://localhost:3000/linodes/44259525/backup
3. Observe page loads and backups are restored
=> hotfix: Linodes Details - Backups - Initialize linode before referencing

packages/manager/cypress/e2e/linodes/smoke-linode-landing-table.spec.ts, packages/manager/src/components/EntityTable/EntityTableHeader.tsx, packages/manager/src/components/EntityTable/types.ts, packages/manager/src/features/linodes/LinodeEntityDetail.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, packages/manager/src/features/linodes/LinodesLanding/CardView.tsx, packages/manager/src/features/linodes/LinodesLanding/DeleteLinodeDialog.tsx, packages/manager/src/features/linodes/LinodesLanding/DisplayGroupedLinodes.tsx, packages/manager/src/features/linodes/LinodesLanding/DisplayLinodes.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.styles.ts, packages/manager/src/features/linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/linodes/LinodesLanding/ListView.tsx, packages/manager/src/features/linodes/LinodesLanding/SortableTableHead.tsx, packages/manager/src/features/linodes/LinodesLanding/TableWrapper.tsx, packages/manager/src/features/linodes/PowerActionsDialogOrDrawer.tsx, packages/manager/src/features/linodes/index.tsx, packages/manager/src/features/linodes/transitions.ts
- Manually reverts #9062
> **Warning**: Please test Linodes Landing thoroughly 
- Test functionality of Linodes Landing
- Test action menu actions
- Please verify that actions and their respective dialogs work
- Test Group by tag and summary view
- Verify that the table still updates in real time with percentages from events data
=> hotfix: Revert Linode Landing Changes

packages/manager/.changeset/pr-9131-tech-stories-1684293772869.md, packages/manager/.changeset/pr-9131-tech-stories-1684293796866.md, packages/manager/src/components/Breadcrumb/FinalCrumb.tsx, packages/manager/src/components/EditableText/EditableText.tsx, packages/manager/src/components/EmptyLandingPageResources/ResourcesSection.tsx, packages/manager/src/components/EnhancedSelect/Select.tsx, packages/manager/src/components/H1Header/H1Header.tsx, packages/manager/src/components/H1Header/index.tsx, packages/manager/src/components/NotFound.tsx, packages/manager/src/components/Placeholder/.Placeholder.stories.mdx, packages/manager/src/components/Placeholder/Placeholder.tsx, packages/manager/src/components/Placeholder/index.ts, packages/manager/src/components/StackScript/StackScript.tsx, packages/manager/src/features/CancelLanding/CancelLanding.tsx, packages/manager/src/features/Events/EventsLanding.tsx, packages/manager/src/features/Help/Panels/SearchPanel.tsx, packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.test.tsx, packages/manager/src/features/Help/SupportSearchLanding/SupportSearchLanding.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/NetworkGraphs.tsx, packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx, packages/manager/src/features/Search/SearchLanding.tsx, packages/manager/src/features/StackScripts/StackScriptBase/StackScriptBase.tsx, packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromImageContent.tsx, packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, packages/manager/src/features/linodes/LinodesDetail/LinodeBackup/BackupsPlaceholder.tsx, packages/manager/src/styles/keyframes.ts
Migrated `Placeholder` and `H1Header` to `styled` api and removed `jss`
- Update import/exports
- Converted to styled component
There should be no visual changes.
1. `yarn dev`
2. Find any empty landing page
3. Example: http://localhost:3000/nodebalancers
=> refactor: [M3-6374, M3-6344] - MUI v5 Migration - `Components > Placeholder & H1Header`

packages/manager/.changeset/pr-9130-fixed-1684419720777.md, packages/manager/src/IdentifyUser.tsx
- Wow this literally took me almost entire workday to figure out 😖
- Fixes API Maintenance mode (I think) 🎉🚀
- I say I think because I can't perfectly reproduce our production load balancer configuration locally so if other problems lie at the loadbalancer level, maintenance mode may still not work. I'm pretty confident this will fix it.
- If the `if` statement that calls `client.identify` can't run, just mark feature flags as loaded in an `else`
- This allows `MainContent.tsx` to render, therefore allowing `<MaintenanceScreen />` to render when our axios interceptor intercepts the maintenance header
> **Note**: Before, Cloud Manager would just show the splash screen loading spinner infinitely 
Contact me, trust me and approve, or wait for testing instructions to be updated
=> fix: [M3-6581] - Fix Cloud Manager Maintenance Mode

CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.test.tsx, packages/manager/src/features/linodes/LinodesLanding/LinodeActionMenu.tsx
Seems to be a slight bug introduced with [a refactor](https://github.com/linode/manager/commit/b9fcf70f3d51094067b578fd10fbd2fd0da7c1ac#diff-af5757c9f2be53593a6a9655c8ea746d322078c01a070da0400f8325d4e127b3L167-R125). We no longer should need to check for `matchesSmDown` anymore.
- Reboot should be disabled if there's readonly access or if the linodes not running
| <img width="203" alt="Screen Shot 2023-05-21 at 6 13 29 PM" src="https://github.com/linode/manager/assets/125309814/0dab6634-d54c-43d8-b43f-5b8055dee9c6"> | <img width="206" alt="Screen Shot 2023-05-21 at 6 14 18 PM" src="https://github.com/linode/manager/assets/125309814/8bb2ba0d-6fa2-41c6-b8d8-4914c755037c"> |
1. Go to a linode detail page
2. Reduce screen size below < 960px
3. Open …
=> hotfix: [M3-6594] - Enable linode action menu "reboot" on mobile

CHANGELOG.md, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
Users without full account access cannot create NodeBalancers if they do not have the global permission to add Domains, even if they are granted the permission to add NodeBalancers.
- We were checking the wrong grant for `NodeBalancerCreate`
| ![Screen Shot 2023-05-22 at 2 02 05 PM](https://github.com/linode/manager/assets/125309814/c6aedc40-b8ac-41fc-9aa2-3a472eb0d494) | User should now have access to create a node balancer if given permissions |
1. add a limited user
2. enable that user's global permission for "Can add NodeBalancers to this account ($)"
3. save
4. login as the limed user.
5. create a nodebalancer
=> hotfix: [M3-6598] - Limited cannot create NodeBalancer

CHANGELOG.md, packages/manager/src/components/LinodeMultiSelect/LinodeMultiSelect.tsx
- Uses a fetch all for the Linode Multi Select because the Linode API could not handle large filters when filtering out linodes
- As a fix for now, I think we can just let the client do the searching and filtering rather than the API
- This fixes the ability for some users to attach linodes to firewalls that already consist of hundreds of linodes
- Verify you can add and remove linodes to a firewall
- Check the functionality of the Select component that displays these linodes
=> hotfix: Linode Multi Select not working with large filters

CHANGELOG.md, packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/AccessSelect.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/BucketAccess.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/ObjectDetailsDrawer.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/BucketDetailsDrawer.tsx
- This one is kind of hard to explain, but `packages/manager/src/features/ObjectStorage/BucketDetail/index.tsx` named imported `<BucketAccess />` which was **not** memoized, which resulted in this component's `useEffect`running more often then it should. It made an API call in the useEffect which caused the loading state to happen every time the parent component updated. 
- This fix is just to remove default imports and memoize the component so that we are guaranteed to import a memoized version of the component.
- Another fix probably could have been to React Query ify `<AccessSelect />` so that is does not rely on props and useEffects to track its state
- I'll make a ticket and react query-ify this at a later date 
https://github.com/linode/manager/assets/115251059/34a74534-9dec-4aab-8f4 …
=> fix: [M3-6576]: Fix Bucket Access Component Reloading API Data too often

packages/manager/.changeset/pr-9129-tech-stories-1684288822656.md, packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx, packages/manager/src/components/EditableEntityLabel/index.tsx, packages/manager/src/components/EntityIcon/EntityIcon.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx
Migrate `EditableEntityLabel` to `styled` api and remove `jss`. Only used for Longview pages.
- Update import/exports
- Converted to styled component
- Added `style` prop for EntityIcon
- Alphabetized properties
There should be no visual changes.
1. `yarn dev`
2. Go to: http://localhost:3000/longview
=> refactor: [M3-6329] - MUI v5 Migration - `Components > EditableEntityLabel`

packages/manager/src/features/linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, packages/manager/src/utilities/ga.ts
Updates the `sendMarketplaceSearchEvent` that fires on both the category dropdown and search bar in the Marketplace. 
- Formats the event in a more standard way (e.g. `action:` `[interaction_type] : [input type]`)
- Restores ability to track when users search via search bar for a Marketplace app, while providing a generic label and not tracking the search query
P.S. Another PR will go through the rest of the custom events to standardize the format/contents of the `category`, `action`, `label`, and `value` fields, in cases where it is inconsistent. It is separate from this PR to keep the scope of these changes small, while we're comparing GA to AA data during the migration. 
-  Use the PR preview link. (Alternatively: check this PR out locally, but …
=> change: [M3-5963] - Update Marketplace analytics search event

.github/workflows/changeset-bot.yml, packages/manager/.changeset/pr-9137-added-1684448927783.md, packages/manager/package.json, packages/manager/scripts/changelog/action.yml, packages/manager/scripts/changelog/changeset-bot.mjs, packages/manager/scripts/changelog/compiled/README.md, packages/manager/scripts/changelog/compiled/index.mjs, packages/manager/scripts/changelog/utils/constants.mjs, packages/manager/scripts/changelog/utils/getPullRequestId.mjs, yarn.lock
This PR adds a bot that will comment on an open PR to remind the user to add a changeset or that a changeset was found and all is good.
This PR can be tested manually by running `node scripts/changelog/changeset-bot.mjs` while hardcoding some [values from the script](https://github.com/linode/manager/pull/9137/files#diff-174d6b88577f9b99e8f309a2582a3df23b40919cdab9c4b172c80bf2c4f1ef54R10-R13):
```
const owner = 'linode';
const repo = 'manager';
const pr_number = '[YOUR PR]';
const token = '[WHATEVER PAT YOU HAVE]';
```
**NOTE**: `Changeset Bot` step is failing now because the workflow needs to be merged for `GITHUB_TOKEN` to be available (won't work since this is from a forked branch). I confirmed it worked well when opening a PR within the same fork: …
=> Chore: [M3-6511] Changeset BOT

packages/manager/.changeset/pr-9161-fixed-1684864339130.md, packages/manager/src/App.tsx, packages/manager/src/constants.ts, packages/manager/src/hooks/useScript.ts, packages/manager/src/utilities/ga.ts
This is an attempt to improve the `loadScript` function and error handling for its use with Adobe Analytics.
- Removes the error logged when a custom event fires unsuccessfully
- This will get rid of the annoying Sentry errors that are currently being triggered when any user blocking the analytics scripts performs an action that would fire a custom event to track, if analytics were enabled.
- Modifies `loadScript` function to return a promise.
- Attempts to verify that all three scripts necessary for Adobe (the launch script and its two extensions) are present in the DOM if the script claims it has loaded successfully with a resolved promise.
- "Attempts" because I haven't found a way to successfully stop all 3 scripts from loading, even with `assets.adobedtm.com/extensions/*`requests …
=> fix: [M3-6586] - Improve error handing for loadScript and Adobe Analytics

packages/manager/.changeset/pr-9142-tech-stories-1685027048549.md, packages/manager/src/components/DismissibleBanner/DismissibleBanner.tsx, packages/manager/src/components/Notice/Notice.tsx, packages/manager/src/features/GlobalNotifications/ComplianceBanner.tsx, packages/manager/src/features/GlobalNotifications/TaxCollectionBanner.tsx, packages/manager/src/features/Help/StatusBanners.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/UpgradeKubernetesVersionBanner.tsx
- Move dismissibleButton to DismissibleBanner component instead of passing it to the Notice Component.
- Minor refactoring so that primary action buttons are aligned with the dismissible button
Turn the MSW on and check for any dismissible banner regressions
=> refactor: [M3-6073] - Move dismissibleButton to DismissibleBanner component

packages/manager/.changeset/pr-9173-tech-stories-1684963143824.md, packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/components/SelectRegionPanel/index.ts, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx, packages/manager/src/features/linodes/LinodesCreate/LinodeCreate.tsx
Migrate `SelectRegionPanel` to `styled/sx` api and remove `jss`
- Converted the `regionHelperText` function to a component since we don't want to invoke functions like this in the JSX
- Update export/imports
- Other changes involved removing `compose`, alphabetizing props & attributes
No Visual changes
1. Try to create a nodebalancer http://localhost:3000/nodebalancers/create
2. Do the same for linode create from backups https://cloud.linode.com/linodes/create?type=Backups
3. Observe / test "Region" section
=> refactor: [M3-6388] - MUI v5 - `Components > SelectRegionPanel`

packages/manager/cypress/e2e/images/create-linode-from-image.spec.ts, packages/manager/cypress/e2e/images/machine-image-upload.spec.ts, packages/manager/cypress/e2e/images/smoke-create-image.spec.ts, packages/manager/cypress/support/intercepts/images.ts
This increases the timeout in `machine-image-upload.spec.ts` when uploading a machine image and waiting for the success toast notification. We've been seeing a lot of flake (currently our flakiest test) because it's taking longer than 2 minutes for the uploaded images to become available.
`yarn && yarn build && yarn start:manager:ci`, and then:
```bash
yarn cy:run -s "cypress/e2e/images/machine-image-upload.spec.ts"
```
=> test: Increase machine image upload timeout from 2 minutes to 4 minutes

packages/manager/src/queries/linodes/networking.ts
- If you allocated an IPv6 range, query invalidation would happen properly but a dependent query would not be guaranteed to be invalided with the correct information
Notice how after allocating an IPv6 range in the same DC, the IPv6 does **not** show up in the sharing dialog as expected. It would show up if the user refreshed, but that is obviously bad.
https://github.com/linode/manager/assets/115251059/e43b3457-f22d-4dab-b749-895f321f75a1
1. Create two linodes (Linode A and Linode B) in the same datacenter
2. Open the IP Sharing dialog on Linode B (we must do this is populate the initial cache)
3. Navigate to LInode A's details page and allocate an IPv6 on Linode A
4. Navigate back to the IP Sharing dialog on Linode B
5. Verify that you can see the new IPv6 you just allocated in the …
=> fix: IP Sharing Query Invalidation

packages/manager/src/features/linodes/LinodesCreate/SelectPlanPanel.tsx, packages/manager/src/features/linodes/LinodesCreate/SelectPlanQuantityPanel.tsx
Simple PR to use the correct HTML entity for our premium plans trademark characters
| ![Screenshot 2023-05-30 at 3 08 18 PM](https://github.com/linode/manager/assets/130582365/782af123-7298-4c73-bad7-65adb83ca2b6) | ![Screenshot 2023-05-30 at 3 07 58 PM](https://github.com/linode/manager/assets/130582365/e8785930-20e0-42c5-9879-d6873d8eaa34) |
1. Navigate to the create Linode workflow > Linode Plan > Premium tab
2. Verify the trademark character has been replaced with the proper entity
=> Refactor: [M3-6519]: Replace trademark html entities

packages/api-v4/src/object-storage/buckets.ts, packages/manager/.changeset/pr-9167-tech-stories-1684946718170.md, packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.test.tsx, packages/manager/src/features/ObjectStorage/BucketDetail/BucketSSL.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/objectStorage.ts
- Uses React Query to handle data fetching and mutations for Object Storage Bucket SSL settings
- `https://cloud.linode.com/object-storage/buckets/:cluster/:bucket/ssl`
- Slightly decreases the size of the inputs because they grew when we upgraded from MUI v4 to MUI v5
- Adds some toast notifications to give the user more obvious feedback
> **Note**: I recommend test this with the MSW because it is time consuming to setup a real domain and certificate
- Turn the MSW **on**
- Navigate to `http://localhost:3000/object-storage/buckets/test/test/ssl`
- Test adding a SSL certificate (you can use fake values because we are using the MSW)
- Test removing the certificate
=> refactor: [M3-6623] - React Query - Object Storage - Bucket SSL/TLS

packages/manager/package.json, yarn.lock
This upgrades `cypress-vite`, which allows us to preprocess our Cypress spec files using Vite. I believe this upgrade fixes an issue we see where spec files are occasionally built multiple times before Cypress is able to run them.
- Upgrade `cypress-vite` from `v1.3.2` to `v1.4.0`.
Confirm Cypress tests run and pass as expected. We can rely on the automated run for this.
=> chore: Upgrade cypress-vite dependency to v1.4.0

packages/manager/cypress.config.ts
- Fixes missing `fs` import in our cypress config (https://github.com/linode/manager/commit/b53e73d96c91af68b3f6fc60cd48514d0023a184#diff-d023ed4a17f94524bd01ac032411794e19ef22a83c9fdb54d55eed8ced993248)
- Verify all CI and e2es pass for this PR
=> fix: Re-add `fs` import to Cypress config

packages/manager/.changeset/pr-9207-fixed-1685730490031.md, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
There's currently an issue with the app search input in marketplace if the apps haven't loaded yet (the loader will just keep showing). To remediate this I disabled the input until the apps have loaded and improved the disabled styles and placeholder text to reflect that.
| <video src="https://github.com/linode/manager/assets/130582365/283c7e1c-b5c0-4ef6-b867-3db01f5014b1" /> | <video src="https://github.com/linode/manager/assets/130582365/24f858bf-ed25-44f6-9c3e-67877f959794" /> |
1. Pull code locally and navigate to /linodes/create?type=One-Click
2. Confirm behavior described in PR description
=> Fix: [M3-6482] Marketplace: disable app search till loading complete

packages/manager/.changeset/pr-9212-tech-stories-1686072978202.md, packages/manager/package.json, yarn.lock
- Update to `vite@4.3.9` for CVE-2023-34092
- Also updates Vite related dependencies
- Run `yarn` to ensure you have updated dependencies
- Verify that you can start the local dev server with `yarn dev`
- Verify that CI / e2es pass
=> Update to`vite@4.3.9` for `CVE-2023-34092`

packages/manager/.changeset/pr-9211-tech-stories-1686019152206.md, packages/manager/src/components/ProductNotification/ProductNotification.test.tsx, packages/manager/src/components/ProductNotification/ProductNotification.tsx, packages/manager/src/components/ProductNotification/index.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx
**MUI migration SRC > Components > TableContentWrapper**
- Run tss-react codemod on `ProductNotification` 
- Renamed Props to    ProductNotificationProps,
- Changes default exports to named exports
- Add  unit test coverage to `ProductNotification` 
- Verify Notifications component where it uses `ProductNotification`.
- Verify e2e tests pass
- Verify unit test passes: ```yarn test ProductNotification```
=> refactor: [M3-6378] - MUI v5 - Components > ProductNotification

packages/manager/src/features/Account/AutoBackups.tsx, packages/manager/src/features/Backups/AutoEnroll.tsx
In the past, the "Backup pricing page" URL on the Accounts page could result in a broken link for some customers when Google Analytics were attached to the parameter for cross-domain tracking. For example, the URL becomes `https://linode.com/backups?_gl=<something>` and `https://linode.com/backups` needed to be redirected to `https://www.linode.com/products/backups/`. A workaround with regex pattern matching was added on the backend when this issue came up to fix the broken redirect link.
Long-term: we should still fix this URL in Cloud because it is best practice to link to the final URL directly, rather than the URL that will be redirected.
- Updated URL from `https://www.linode.com/backups` (or `https://linode.com/backups`) to `https://www.linode.com/products/backups/` 
1. **How to …
=> fix: [M3-6071] - Use final URL for link to Backups pricing page

packages/manager/.changeset/pr-9214-fixed-1686072216523.md, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.container.tsx, packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx
- Don't conditionally render VLANs depending on Account Capabilities
- Restricted users do not have permission to GET /account which does **not** allow them to see account capabilities
- Therefore it's not valid to check for permissions for restricted users using account capabilities
- This resulted in us hiding VLANs related UI for restricted users unintentionally
- Simply just don't perform any checks against `account.capabilities` because it is not a valid way to check permissions when considering restricted users
| ![Screenshot 2023-06-06 at 1 20 16 PM](https://github.com/linode/manager/assets/115251059/115d1849-93c5-4098-99f5-e613cbb23351) | ![Screenshot 2023-06-06 at 1 20 23 PM](https://github.com/linode/manager/assets/115251059/326612b0-85 …
=> fix: [M3-6555] - Don't conditionally render VLANs depending on Account Capabilities

packages/manager/src/components/ActionMenu/ActionMenu.tsx
When we resize the browser, the ActionMenu items get modified as the three first ones get either displayed in the bar (desktop) or in the ActionMenu itself (mobile).
While all visible data gets updated in the menu, the `data-valuetext` tag was not updating to reflect the proper value, which could cause flakiness when relying on them for E2E tests.
This PR adds the `valueText` prop to the menu item so it's always updating on resize.
Note: this isn't at all customer impacting or a fix necessitating a changeset
Comparing production and local code:
1. Go to linode detail on desktop
2. Open the action menu and inspect the first item
3. Keep menu open and resize browser till items are shuffled
4. Confirm fix on the `data-valuetext` tag for each menu item
=> Fix: [M3-6036] Ensure ActionMenu item valueText tag gets updated on resize

packages/manager/.changeset/pr-9226-added-1686168141780.md, packages/manager/src/featureFlags.ts, packages/manager/src/features/GlobalNotifications/APIMaintenanceBanner.tsx, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubernetesClusterDetail.tsx, packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
We needed to add product information banners on Kubernetes pages for upcoming maintenance.
- fix: Fixed banner regression
- feat: Updated banner types
- feat: Added banner to landing, detail, and create pages
> **Note**: You will see two banners on the LKE pages since we're currently using `apiMaintenance` flag to serve the banner for now.
|![Screen Shot 2023-06-07 at 4 11 58 PM](https://github.com/linode/manager/assets/125309814/cea05e78-d283-4e1d-9471-ab6723925b7b)|![Screen Shot 2023-06-07 at 4 13 58 PM](https://github.com/linode/manager/assets/125309814/57cb785f-7a88-4914-8b5c-d39f5f3b4c06)|
1. Confirm you see banners when going to http://localhost:3000/kubernetes/clusters
=> feat: [M3-6674] - Add kubernetes product information banner

packages/manager/.changeset/pr-9218-tech-stories-1686268120191.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeVolumes.tsx, packages/manager/src/features/Volumes/VolumeTableRow.tsx, packages/manager/src/features/Volumes/VolumesActionMenu.tsx, packages/manager/src/features/Volumes/VolumesLanding.tsx
- Finishes up React Query for Linode Storage - Volumes
- Linode Volumes have already been React Query-ifyed but we never removed the crazy `withLinodeDetailContext` part of it
- Check the volumes table on `http://localhost:3000/linodes/{id}/storage` for any issues
- Check basic operations like creating a volume and deleting a volume from this view
=> refactor: [M3-6490] - React Query - Linode Storage - Finish Volumes

packages/manager/.changeset/pr-9230-tech-stories-1686242146063.md, packages/manager/src/features/Help/HelpLanding.test.tsx, packages/manager/src/features/Help/HelpLanding.tsx, packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx, packages/manager/src/features/Help/Panels/SearchPanel.tsx, packages/manager/src/features/Help/index.tsx
Simple PR to remove the icon in the Help Landing green banner.
This PR also refactors touched class components and make use of styled components.
**Note**: added a subtle margin below the banner search title. Everything else should be identical.
| ![Screenshot 2023-06-08 at 12 38 42 PM](https://github.com/linode/manager/assets/130582365/a7f3df7b-fa17-4f92-8afd-9053803778d9) | ![Screenshot 2023-06-08 at 12 38 35 PM](https://github.com/linode/manager/assets/130582365/40346da7-05ae-4de8-b12f-2216126f494f) |
Navigate to /support locally and compare page with production
=> Refactor: [M3-6619]: HelpLanding: remove icon and MUI refactor

packages/manager/.changeset/pr-9215-fixed-1686154022321.md, packages/manager/src/features/Events/EventRow.test.tsx, packages/manager/src/features/Events/EventRow.tsx, packages/manager/src/features/NotificationCenter/NotificationData/RenderEvent.tsx, packages/manager/src/utilities/eventUtils.test.ts, packages/manager/src/utilities/eventUtils.ts
The original ask was to show an accurate completion timestamp for a Backup Restore event in the Activity Feed. Currently, these events show the created timestamp, even when the event has completed. The time between a backup restore starting and completing is most noticeable for a large linode (over 10 GB) and the inaccurate information can be misleading and confusing to users.
Because we always displayed the `created` timestamp and had no method of calculating or updating it for completed events, other events that take some time to complete (e.g. a linode migration) also had inaccurate timestamps. API does not return a completed timestamp, but it does return an event `duration` (the total duration in seconds that it takes for the Event to complete).
This PR fixes that by adding a util …
=> fix: [M3-5972] - Better/correct timestamps for finished event messages

packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/DNSResolvers.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkingSummaryPanel.tsx
On the linode detail > network tab, when showing the networking v6 resolvers, they overflow their containers and we sometimes can't even read the value. This PR does two things:
- adjust the the width os the grid items so that the addresses show in full > 1268px and increase grid spacing slightly for better readability
- add an `overflow: auto` to be able to scroll through the values at mid size breakpoints before the grid items get stacked on mobile (100% width, no change there)
It's not perfect (when v4 resolvers there's a bit of white space to the right) but this display has always been a problematic responsive layout and at some point we should consider redesigning it a bit so we don't cram too much in a grid row and account for various type of data to fit in gracefully.
| Before  | …
=> Fix: [M3-6637] - Linode networking v6 resolvers overflow

packages/manager/CHANGELOG.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/LinodeBackups.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeRescue/RescueDialog.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/MutationNotification.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailNavigation.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx, packages/manager/src/queries/types.ts
- Fix Linode details crashing for Linodes with no plan
- For Linodes with no plan, we were requesting `/v4/linode/types/${id}` but id was empty string resulting in the query actually GETing all the types from the API
- Test against an account with Linodes that don't have plans
=> fix: [M3-6686] - Linode Details crashing for Linodes that don't have plans

packages/manager/.changeset/pr-9240-changed-1686335599449.md, packages/manager/src/components/DialogTitle/DialogTitle.tsx, packages/manager/src/features/Linodes/PowerActionsDialogOrDrawer.tsx
This ticket addresses a few small dialog layout and copy improvements for the Linode Power Actions dialog. 
- Removes "Are you sure..." Typography in both Power Off and On states
- Reformats the notice's line breaks on Power Off dialog
- Includes new copy linking to [Guides - Setting Up and Securing a Compute Instance](https://www.linode.com/docs/products/compute/compute-instances/guides/set-up-and-secure/) on Power On dialog
- Changes the notice to a warning notice, not an important warning notice on Power Off dialog
- Fixes bug where a long dialog title overlaps and obscures the dialog 'X' button
| ![Screenshot 2023-06-09 at 11 17 15 AM](https://github.com/linode/manager/assets/114685994/0d3cce49-2f25-475c-a60f-a3d670c36a70) | ![Screenshot …
=> feat, fix: [M3-6560, M3-6641] - Update Linode Power confirmation dialog layout and UX copy

packages/api-v4/.changeset/pr-9257-added-1686756493120.md, packages/api-v4/src/databases/types.ts, packages/manager/src/mocks/serverHandlers.ts
**Support new plan in Database types**
**update MSW to show new plan in Database types**
1. Navigate (http://localhost:3000/databases/create)
2. Verify new plan tab in plans table
=> feat: [M3-6703] - Update MSW and Database API-V4 types to support new plans

packages/manager/.changeset/pr-9254-tech-stories-1686608779585.md, packages/manager/src/components/FileUploader/FileUploader.stories.mdx, packages/manager/src/components/FileUploader/FileUploader.styles.ts, packages/manager/src/components/FileUploader/FileUploader.tsx, packages/manager/src/features/Images/ImageUpload.tsx, packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.styles.ts, packages/manager/src/features/ObjectStorage/ObjectUploader/FileUpload.tsx
- Fix bug where the upload arrow wasn't animating
- Migrate styles for the FileUploader component and code pattern updates
Before
https://github.com/linode/manager/assets/115299789/b9101542-592b-4d2f-ba31-f0c789c472df
After
https://github.com/linode/manager/assets/115299789/9857eced-d717-4e1c-a590-4ddd8d3572ad
Check the success/error states of the File Upload in `/images/create/upload` and in an Object Storage bucket, ensure there are no regressions
=> refactor: [M3-6340] - MUI v5 Migration - `Components > FileUploader`

packages/manager/src/components/ModeSelect/ModeSelect.tsx, packages/manager/src/components/ModeSelect/index.tsx, packages/manager/src/components/NavTabs/NavTabs.tsx, packages/manager/src/components/NavTabs/index.ts, packages/manager/src/features/Images/ImagesCreate/ImageCreate.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeAdvanced/LinodeDiskDrawer.tsx, packages/manager/src/features/Managed/ManagedLanding.tsx, packages/manager/src/features/Profile/Profile.tsx, packages/manager/src/features/StackScripts/StackScriptPanel/StackScriptPanel.tsx, packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx, packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx
These were MUI Migration tickets, but there were no styles to migrate.
I looked into removing Reach UI from NavTabs in favor of the MUI Tabs but decided that effort should be its own tech story due to the amount of tab-related components we have and how widely we use tabs across the app. A ticket for this is now in our backlog: M3-6705.
- Use named rather than default exports
- Update props names
- Remove React.FC
Check that there have been no regressions in NavTabs or ModeSelect components in the app. 
NavTabs can be found on https://localhost:3000/profile/display and ModeSelect can be found on the Linode Disk Drawer from Linode Details > Storage > Add Disk.
=> refactor: [M3-6362,M3-6365] - Update `Components > ModeSelect, NavTabs`

packages/manager/.changeset/pr-9260-fixed-1686769842584.md, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx, packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx, packages/manager/src/features/OneClickApps/oneClickApps.ts
- Rename `FakeSpec.ts` to `oneClickApps.ts`.
- Fix a host of typos and punctuation errors in App summaries and descriptions.
1. Review spelling and punctuation changes.
=> fix: [M3-6706] - Fix Marketplace App typos

packages/manager/.changeset/pr-9263-tech-stories-1686839868932.md, packages/manager/src/components/IPSelect/IPSelect.tsx, packages/manager/src/components/IPSelect/index.ts, packages/manager/src/factories/linodes.ts, packages/manager/src/features/Managed/SSHAccess/EditSSHAccessDrawer.tsx, packages/manager/src/mocks/serverHandlers.ts
- This ticket is technically a style migration ticket but no styles are needed so I am going to refactor this to use RQ
- Makes `<IPSelect />` source data from React Query
- Made the Linode mock data more realistic
1. Enable the MSW
2. Go to `http://localhost:3000/managed/ssh-access`
3. Click edit on a row
4. Verify that the IP Select component shows IP addresses
If you want to test further
1. Enable managed on your account
2. Go to `http://localhost:3000/managed/ssh-access`
3. Click edit on a row
3. Test the IP Select component
=> refactor: [M3-6351] - Refactor `<IPSelect />`

packages/manager/.changeset/pr-9272-fixed-1686929413003.md, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
At smaller screen sizes, the `Add Another Configuration` and `Create Nodebalancer` buttons on https://cloud.linode.com/nodebalancers/create were misaligned. 
- Applies the necessary left or right margin to each button at smaller breakpoints to maintain consistent spacing.
| ![Screenshot 2023-06-16 at 8 20 23 AM](https://github.com/linode/manager/assets/114685994/9ce176ce-a119-467e-85a3-c735b02e63b6) | ![Screenshot 2023-06-16 at 8 20 39 AM](https://github.com/linode/manager/assets/114685994/f5f9aea4-e2f4-4260-aaf5-2a9039695b36) |
1. **How to reproduce the issue (if applicable)?**
Go to https://cloud.linode.com/nodebalancers/create, use the browser dev tools to adjust viewport, and observe that the buttons are too close to the edge of the screen …
=> fix: [M3-6568] - Button alignment on Nodebalancer Create page

packages/manager/.changeset/pr-9278-tech-stories-1686942932396.md, packages/manager/src/components/MaintenanceBanner/MaintenanceBanner.tsx, packages/manager/src/components/MaintenanceBanner/index.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/Notifications.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/Profile/APITokens/utils.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/utilities/isPast.test.ts, packages/manager/src/utilities/isPast.ts
- Style migration for MaintenanceBanner 
- The general UX of this banner feels questionable but this is just a clean up / style migration for it
- Cleans up `<MaintenanceBanner />` 
- Fixes default export of `isPast`
Some styles were removed but the component should look the same
- Go to the Linodes Landing Page
- Look for a Linode that has a status of `Maintenance Scheduled`
- Click it to go to the details page
- Check the banner
=> refactor: [M3-6360] - MUI v5 Migration - `Components > MaintenanceBanner`

packages/manager/.changeset/pr-9271-tech-stories-1686927837582.md, packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.test.tsx, packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx
On the Billing Activity table, requests to `/payments` and `/invoices` include a `date` filter depending on which time range the user has selected. 
E.g. if the user selected "30 days", Cloud requests invoices with a filter like this: `{ date: { "+gte": <currentDate - 30 days> } }`.
This negatively impacts RQ caching, because a new cache key is generated for every request (since the date is specified down to the _second_). 
**This PR rounds these dates to the start of the given day**. This means that RQ will cache results for an entire day.
**Additionally,** I removed the `date` filter when users select "All Time". Previously the unix epoch was used to keep the code simpler, but removing this altogether might be better from an API perspective.
- Run the app and test the /account page. 
- …
=> refactor: Round dates on the filters for invoices and payments

.github/workflows/ci.yml, packages/manager/.changeset/pr-9274-tech-stories-1686938963869.md
Any PR to `master` has been failing our Github Actions pipeline over the last few weeks and its annoying to see the ❌ every time 
- Removes `cp` command that was used when we deployed a beta environment 
- Related PRs
- https://github.com/linode/manager/pull/8804 
- https://github.com/linode/manager/pull/9041
- The proof this works is here: https://github.com/linode/manager/actions/runs/5292639874/jobs/9579833769?pr=9274
=> fix: Github Actions CI `build-manager`

packages/manager/.changeset/pr-9270-tech-stories-1686927343871.md, packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.test.tsx, packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx, packages/manager/src/components/LabelAndTagsPanel/index.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Refactored `LabelAndTagsPanel` by removing jss, converting to functional component.
- Converted from class to functional component
- Removed render guards
- Converted tests from Enzyme to RTL and added some more tests
1. Ensure everything renders and functionality is unchanged
2. Run tests `yarn test packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.test.tsx`
=> refactor: [M3-6352] - MUI v5 Migration - `Components > LabelAndTagsPanel`

packages/manager/.changeset/pr-9273-fixed-1686932547524.md, packages/manager/src/components/EntityTable/EntityTableHeader.tsx, packages/manager/src/features/Linodes/LinodesLanding/CardView.tsx, packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx, packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.styles.ts, packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx
This code is a mess. There's so much duplication and it needs a serious refactor. Trying to have a minimal footprint here so only addressing styles and some exports.
The PR achieves a couple things:
- Add the active/toggled color on the icon
- Cleans up the styles and consolidates grid/list styles and layout
**Note: default view (no summary view, no tags) should be unchanged**
| ![Screenshot 2023-06-16 at 11 52 03 AM](https://github.com/linode/manager/assets/130582365/46dbdd0f-3ca0-4624-8f08-c32acf9e7384) | ![Screenshot 2023-06-16 at 11 51 53 AM](https://github.com/linode/manager/assets/130582365/18fdcd88-d36d-46ab-9bf4-b5b79b43a909) |
| ![Screenshot 2023-06-16 at 11 52 34 AM](https://github.com/linode/manager/assets/130582365/42d74f1f-f172-4de6- …
=> Fix: [M3-6612] Grid/Tag views and toggle styling (Linodes Landing)

packages/manager/.changeset/pr-9281-fixed-1686955648087.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx
Fixes unexpected behavior in the Notification Thresholds accordion within a Linode's Settings where default values were being displayed after toggling off -> on a setting, rather than the values a user saved.
Now, when a user makes and saves a change to a value and then toggles a setting, that saved threshold value will accurately display in the text field, rather than the default value.
| <video src="https://github.com/linode/manager/assets/114685994/fb0e0be0-8450-4ab0-97f3-4c52e04c37f7" /> | <video src="https://github.com/linode/manager/assets/114685994/590ee075-e469-4450-8703-20ab7fdbd92e" /> |
**How to reproduce the issue (if applicable)?**
1. Have a Linode on hand or spin one up and and navigate to the Settings tab of the Linode Details …
=> fix: [M3-6687] - Show accurate Notification Threshold values when toggling in Linode Settings

packages/manager/.changeset/pr-9280-fixed-1686949826559.md, packages/manager/src/eventMessageGenerator.test.ts, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/mocks/serverHandlers.ts
Fixes a crash that occurs when viewing events that contain RegEx special characters.
1. Trigger an entity event containing RegEx special characters (a known bad string is `(?)`).
- This PR adds an event to the MSW that contains special characters and should crash the app without this fix
2. Open the Notifications menu or navigate to `/events`.
3. Verify the app doesn't crash.
=> fix: [M3-6664] - Fix crash due to unescaped RegEx

packages/api-v4/src/account/types.ts, packages/api-v4/src/profile/profile.ts, packages/manager/cypress/e2e/profile/add-oauth-app.spec.ts, packages/manager/cypress/e2e/profile/delete-oauth-app.spec.ts, packages/manager/cypress/e2e/profile/edit-oauth-app.spec.ts, packages/manager/cypress/e2e/profile/reset-oauth-app.spec.ts, packages/manager/cypress/support/api/profile.ts, packages/manager/cypress/support/intercepts/profile.ts, packages/manager/cypress/support/ui/common.ts, packages/manager/cypress/support/util/random.ts, packages/manager/src/factories/accountOAuth.ts, packages/manager/src/factories/index.ts
Add new cypress tests for OAuth Apps
- Add `OAuth Apps` addition tests.
- Add `OAuth Apps` editing  tests.
- Add `OAuth Apps` resetting tests.
- Add `OAuth Apps` deletion tests.
`yarn cy:run -s "cypress/e2e/profile/*.spec.ts"`
=> test: [M3-6549] - Add Cypress Integration tests for OAuth Apps

packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts, packages/manager/cypress/support/intercepts/stackscripts.ts, packages/manager/src/factories/stackscripts.ts
Add new cypress tests for StackScript landing page
- Add `StackScript landing page` smoke tests.
`yarn cy:run -s "cypress/e2e/stackscripts/smoke-stackscripts-landing-page.spec.ts"`
=> test: [M3-6506] - Add StackScript Landing Page Integration Tests

packages/manager/.changeset/pr-9289-fixed-1687364211275.md, packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx, packages/manager/src/components/DialogTitle/DialogTitle.tsx
The confirmation modal had a min width CSS rule that made it overflow on mobile under 450px. This PR removes the rule to fix the overflow as well as improving the line height of the modal title which was unecessarily excessive.
| ![Screenshot 2023-06-21 at 12 12 28 PM](https://github.com/linode/manager/assets/130582365/ea0f569f-f56a-4cf0-ba37-22ae8040eb24) | ![Screenshot 2023-06-21 at 12 12 50 PM](https://github.com/linode/manager/assets/130582365/4de961e2-eb45-4614-8c8e-60fdad4ad024) |
Try deleting a Linode to be prompted for the confirmation modal in mobile view (450 or lower) and confirm both changes
=> fix: [M3-6683]: Fix confirmation modal overflow on mobile

packages/manager/.changeset/pr-9292-tech-stories-1687376650053.md, packages/manager/src/components/Button/Button.tsx, packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.test.tsx, packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx, packages/manager/src/components/SingleTextFieldForm/index.ts, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
- MUI style migration for `<SingleTextFieldForm />`
- Run tss migration on `<SingleTextFieldForm />`
- Update spacing to make it more consistent on the `http://localhost:3000/profile/display` page
- Clean up exports
| ![Screenshot 2023-06-21 at 3 39 41 PM](https://github.com/linode/manager/assets/115251059/7880fce0-f53e-4030-a9c6-93049a0e913b) | ![Screenshot 2023-06-21 at 3 39 48 PM](https://github.com/linode/manager/assets/115251059/9c6e41d6-c9e4-4566-900b-93642df1e09e) |
- Go to `http://localhost:3000/profile/display` and test the forms
=> refactor: [M3-6391] - MUI v5 Migration - `Components > SingleTextFieldForm`

packages/manager/.changeset/pr-9298-fixed-1687455527847.md, packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts, packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts, packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts, packages/manager/cypress/support/intercepts/firewalls.ts, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
This makes a few changes to the Firewall create and update e2e tests, as well as the Image capture test, to reduce flakiness.
Changes to address flake:
- Updates interactions involving Linode multi select fields to reflect recent UX improvements made to the component
- Adds a couple intercepts and waits for them to resolve during UI interactions
Other changes:
- Removes some UI interactions involving Firewall creation in update tests and replaces them with API calls
- Fixes a small accessibility issue with `LinodeSelectV2` involving its label `for` attribute not matching the input field's ID
We can lean on the automated run for this, but you can run these tests locally to better confirm that flake is resolved:
`yarn && yarn start:manager:ci && yarn build`, and then
```bash
yarn cy:run -s …
```
=> fix: Reduce Firewall create and update e2e test flakiness

packages/manager/.changeset/pr-9303-fixed-1687530086967.md, packages/manager/src/foundations/themes/light.ts
Tiny PR to fix the regression with our text input placeholder opacity. It affects any text field in the application.
regression was introduced by the LinodeSelect refactor: https://github.com/linode/manager/commit/6b0ea3f70e67de6bd027fce31fc8b3715a5e0cb8#diff-f767369a01cd40921dc0da8dac44cf6777e3c155f3680aa2990be0da93c2dc48R877
| ![Screenshot 2023-06-23 at 10 26 09 AM](https://github.com/linode/manager/assets/130582365/f4944600-f65a-41cb-9838-6e80dde632f5) | ![Screenshot 2023-06-23 at 10 24 53 AM](https://github.com/linode/manager/assets/130582365/c210a3cd-f2ba-4934-b6d0-9ecb96d8ee6e) |
| ![Screenshot 2023-06-23 at 10 26 25 AM](https://github.com/linode/manager/assets/130582365/58210631-64d3-41dd-a956-1130c06c55fb) | ![Screenshot 2023-06-23 at 10 …
=> Fix: [M3-6716] Regression with placeholder opacity

packages/manager/.changeset/pr-9304-added-1687531307023.md, packages/manager/src/features/Images/ImageUpload.tsx, packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Update placeholder metadata docs link with the actual link.
- Check the two metadata docs links on the Linode Create flow (there's one in the tooltip, and one in the User Data explainer copy)
- The UserDataAccordion also appears in the Rebuild from Image flow
- To see the metadata sections in Linode Create, you can just change L761 of LinodeCreate.tsx.
=> feat: Update metadata docs link

packages/manager/.changeset/pr-9290-added-1687466679796.md, packages/manager/src/components/AccessPanel/UserSSHKeyPanel.tsx, packages/manager/src/components/Code/Code.tsx, packages/manager/src/components/Code/index.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/ResizeDiskDrawer.tsx, packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.test.tsx, packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx, packages/manager/src/features/Profile/SSHKeys/SSHKeys.tsx
This PR:
- Adds a helper text to the Create SHHKey drawer
- Trims the SSHKey value on blur
- Removes the default export for the component
| ![Screenshot 2023-06-22 at 4 10 05 PM](https://github.com/linode/manager/assets/130582365/9c059dec-621e-486e-9048-0dc54bbc7164) | ![Screenshot 2023-06-22 at 4 09 28 PM](https://github.com/linode/manager/assets/130582365/f6d9b8ce-8909-47e8-9bf9-ff4a71297be8) |
1. Navigate to /profile/keys and Click on "Add An SSH Key"
2. Confirm the helper text content
3. Try submitting a valid key with extra space or line and confirm it gets trimmed and submits
=> Feat: [M3-6473] - Add helper text to the Add SSHKey Drawer Form

packages/manager/.changeset/pr-9282-tech-stories-1687053909997.md, packages/manager/src/components/LandingLoading/LandingLoading.stories.tsx, packages/manager/src/components/LandingLoading/LandingLoading.test.tsx, packages/manager/src/components/LandingLoading/LandingLoading.tsx, packages/manager/src/components/LandingLoading/index.ts, packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Disks/Disks.tsx, packages/manager/src/features/Volumes/VolumesLanding.tsx
Refactored `LandingLoading` as part of MUI v5 passthrough
- Fixed imports/exports
- Cleaned up the return JSX
- Added `timeoutId` so we can cleanup `setTimeout`
Todo:
> **Note**: Added a blue border for the video preview (as a test to make it stand out)
|Volumes | Storybook      | Tests |
| -----------| ----------- | ----------- |
|<video src="https://github.com/linode/manager/assets/125309814/99c25dc5-9827-4c4c-a844-a7af89d4e030"/> |![Screenshot 2023-06-20 at 11 18 17 PM](https://github.com/linode/manager/assets/125309814/7f2e1bbc-8081-4552-b1ff-cf74a6bc4241)|<img width="856" alt="Screenshot 2023-06-20 at 11 25 18 PM" src="https://github.com/linode/manager/assets/125309814/23aa3815-93d1-46bb-abf3-6017bb219d1c">|
1. Slow down network speed and go `/volumes`
2. Storybook: …
=> refactor: [M3-6354] - MUI v5 Migration - `Components > LandingLoading`

packages/manager/.changeset/pr-9319-tech-stories-1687875908852.md, packages/manager/src/components/Toolbar.ts, packages/manager/src/components/core/Toolbar.ts, packages/manager/src/features/TopMenu/TopMenu.tsx
- Style migration for the `<Toolbar />` component
- Moves `packages/manager/src/components/core/Toolbar.ts` to `packages/manager/src/components/Toolbar.ts` 🗂️
- Use **only** named exports 🧼💡
- Verify the app's Top Menu bar looks normal
=> refactor: [M3-6791] - MUI v5 Migration - `Components > Toolbar`

packages/manager/.changeset/pr-9321-tech-stories-1687879529410.md, packages/manager/src/components/AppBar.ts, packages/manager/src/components/core/AppBar.ts, packages/manager/src/features/TopMenu/TopMenu.tsx
- Style migration for the `<AppBar />` component
- Moves `packages/manager/src/components/core/AppBar.ts` ➡️ `packages/manager/src/components/AppBar.ts` 🗂️
- Changed default export to named export 🧼
- Verify the app's top navigation bar looks and works as expected
=> refactor: [M3-6793] - MUI v5 Migration - `Components > AppBar`

packages/api-v4/CHANGELOG.md, packages/api-v4/package.json, packages/api-v4/src/account/types.ts, packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/eventMessageGenerator.test.ts, packages/manager/src/eventMessageGenerator.ts
Fixes a bug that causes the app to crash when opening the Notification Menu.
- Updates `Entity` type in `api-v4` package to reflect the possibility of a null `label`
- Adds null check to `applyLinking` function
1. Verify opening the Events Menu does not cause a crash when a user has an entity event with a null label (e.g., `entity_transfer`)
=> hotfix: Notification Menu crash due to null value

packages/manager/.changeset/pr-9296-fixed-1687442580014.md, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx
**Fix Object Storage > Create Access Key Drawer Layout Issue**
| ![image](https://github.com/linode/manager/assets/119517080/37254eb8-73bc-43b9-bb40-bfc24c71715f) | ![image](https://github.com/linode/manager/assets/119517080/864b508f-cae8-4f07-bc54-850d09c1f998)|
|![image](https://github.com/linode/manager/assets/119517080/99fc6f22-4a6f-43e3-b2cc-cca19bc4930d)|![image](https://github.com/linode/manager/assets/119517080/8eb47b3e-9692-436b-8b5e-2f6763d44950)|
1. **Navigate to Object storage and click create access key button**
2. **Validate drawer layout with no buckets.**
3. **Validate drawer layout with one or more buckets**
=> fix: [M3-6638] - Object Storage > Create Access Key Drawer Layout Issue

packages/api-v4/CHANGELOG.md, packages/api-v4/package.json, packages/api-v4/src/account/types.ts, packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/eventMessageGenerator.test.ts, packages/manager/src/eventMessageGenerator.ts
- Crash when viewing notifications due to `null` label in event entity ([#9331](https://github.com/linode/manager/pull/9331))
- Updated Entity interface to reflect the possibility of a `null` label ([#9331](https://github.com/linode/manager/pull/9331))
=> Release v1.96.1 - staging → master

packages/manager/src/components/AppBar.ts
- Fixes dev server not starting
- Fixes bad import causing Vite dev server to break https://github.com/linode/manager/pull/9321
- Verify Cloud Manager works when `yarn dev` is ran
=> fix: local dev server `AppBarProps` export

packages/manager/.changeset/pr-9286-added-1687296191023.md, packages/manager/.changeset/pr-9286-fixed-1687296191023.md, packages/manager/src/App.tsx, packages/manager/src/features/Profile/Settings/Settings.tsx
For some historical context on the light/dark mode keyboard shortcut feature, refer to #7595 and #7606.
This PR exposes the keyboard shortcut in copy as opposed to having it be just an easter egg.
- Instructional text/copy added to the "Theme" section re: keyboard shortcut
Confirm that `Ctrl` + `Shift` + `D` works to change the theme in the app in Chrome, Firefox, and Safari.
Confirm that the copy in the Theme section of the "My Settings" page is accurate.
=> feat: [M3-6707] – Light/dark mode shortcut copy on the "My Settings" page

packages/manager/.changeset/pr-9336-fixed-1687982995866.md, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.test.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleDrawer.utils.ts, packages/validation/.changeset/pr-9336-fixed-1687983041491.md, packages/validation/src/firewalls.schema.ts
The previous validation for firewall custom ports made use of a regex that was not encompassing the same conditions as what the validation was doing sever-side. 
In order to fix this in a more permanent manner, I more closely matched the API validation on the client and returned the same error messages for better feedback for the user. I also added test cases to reflect these new changes. 
1. Navigate to an existing firewall or create a new one
2. Click on the "Add an Outbound Rule" (or "Inbound"), follow a similar config as the screenshot above, and hit the "Custom Port Range" fields with a lot of combinations making sure it passes or fails properly (you can use the examples in the updated test for example
3. Click on Add Rule with a valid port/port range
4. When drawer close, hit save …
=> Fix: [M3-6800] Firewall custom port validation

packages/api-v4/.changeset/pr-9335-changed-1687980892035.md, packages/api-v4/src/entity-transfers/types.ts, packages/manager/cypress/e2e/core/account/service-transfer.spec.ts, packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx, packages/manager/src/features/ToastNotifications/ToastNotifications.tsx, packages/manager/src/mocks/serverHandlers.ts
There are two places in Cloud Manager ([image upload error toast](https://github.com/linode/manager/blob/develop/packages/manager/src/features/ToastNotifications/ToastNotifications.tsx#L140-L142), [entity transfer request status table column](https://github.com/linode/manager/blob/develop/packages/manager/src/features/EntityTransfers/RenderTransferRow.tsx#L170)) where we were performing string manipulation to edit an event message or status from API that returns "cancelled" rather than "canceled". Both spellings are correct -  "cancelled" is British-English and "canceled" is American English - but for consistency's sake, it would be better to use one spelling; "canceled" is already in use in all other places throughout the app.
API is now always returning the spelling "canceled" (see …
=> chore: [M3-6666] -  Clean up for consistent spelling of "canceled"

packages/manager/.changeset/pr-9352-fixed-1688140397688.md, packages/manager/src/components/ActionMenu/ActionMenu.tsx
Small fix to address a deprecation of the color of the tooltip help icon in the action menu. This PR targets that particular tooltip icon and should not introduce any deprecation to other tooltip icons.
| ![Screenshot 2023-06-30 at 11 50 51 AM](https://github.com/linode/manager/assets/130582365/3a6c26e6-df46-4bd1-a98f-8a6a54dac92a) | ![Screenshot 2023-06-30 at 11 50 28 AM](https://github.com/linode/manager/assets/130582365/160cb297-f7fd-479c-8925-d7c5d47fd948) |
1. Linode Details > Storage tab > Disk action menu > Try to Delete a disk with a _powered on_ linode
=> Fix: [M3-6786] ActionMenu tooltip icon color

packages/manager/.changeset/pr-9355-fixed-1688147944694.md, packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Previously, when downloading an invoice, we would make a request for the logo image for every page of the invoice potentially causing delays for large accounts. This PR fixes that by fetching the image only once and passing that to jsPDF's addImage function
- Go to /account/billing
- In the browser dev tools, go to the network tab and filter by .png
- Download an invoice PDF and observe only 1 request made for the akamai logo
- Open the PDF and ensure that the logo is still on every page
=> fix: [M3-6177] - Only request logo once for invoice pdf

packages/manager/cypress/e2e/core/account/default-payment-method.spec.ts, packages/manager/cypress/e2e/core/account/google-pay.spec.ts, packages/manager/cypress/e2e/core/images/create-linode-from-image.spec.ts, packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts
A couple small changes to slightly improve the resiliency of our tests.
- Most changes involve positioning intercepts and mocks before calls to `cy.visitWithLogin()`. Sometimes the desired API request is triggered before `cy.visitWithLogin()` has finished (since it waits for the page to finish loading before allowing the next command to execute, and some API requests are made in the meantime), so the desired API request is never intercepted and the test fails. This seems to happen more often on local runs than in CI.
- Fixes another potential cause of flake when interacting with a region select drop-down. I made the assertion more specific because the existing selector occasionally finds multiple matching elements which causes the test to fail.
1. Wait for the automated run to finish
2. …
=> fix: Fix miscellaneous Cypress test flake

packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
This fixes some flake in the Linode landing page test which deletes multiple Linodes in sequence. This test is flaky because it does not wait for the UI to update before proceeding with the next deletion, but when the UI does update it causes any action menus which are open to close. When this happens after Cypress has already clicked on the action menu, the test fails. 
We can rely on the automated tests to confirm that this test passes without flake, but to test this locally you can run:
```bash
yarn cy:run -s "cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts"
```
=> fix: Fix Linode landing page delete smoke test flake

packages/manager/cypress/e2e/core/account/service-transfer.spec.ts, packages/manager/cypress/e2e/core/account/smoke-billing-activity.spec.ts, packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts, packages/manager/cypress/e2e/core/domains/smoke-delete-domain.spec.ts, packages/manager/cypress/e2e/core/firewalls/create-firewall.spec.ts, packages/manager/cypress/e2e/core/firewalls/delete-firewall.spec.ts, packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts, packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts, packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts, packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts, packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts, packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts, packages/manager/cypress/e2e/core/volumes/clone-volume.spec.ts, packages/manager/cypress/e2e/core/volumes/create-volume.spec.ts, packages/manager/cypress/e2e/core/volumes/delete-volume.spec.ts, packages/manager/cypress/e2e/core/volumes/resize-volume.spec.ts, packages/manager/cypress/e2e/core/volumes/update-volume.spec.ts, packages/manager/cypress/support/commands.ts, packages/manager/cypress/support/e2e.ts, packages/manager/cypress/support/index.d.ts, packages/manager/cypress/support/util/backoff.ts
This fixes the `cy.defer()` custom Cypress command signature and implementation to resolve TypeScript errors. The new implementation is a pretty thin wrapper around `cy.wrap()`, which accomplishes the same thing but isn't as ergonomic.
1. Confirm that the tests continue to pass via the automated Cypress run
2. Check out this PR, and confirm there aren't any type errors in `cypress/support/commands.ts` at or around line 38.
=> fix: [M3-6627] - Fix `cy.defer()` TypeScript errors

packages/manager/.changeset/pr-9366-fixed-1688578241873.md, packages/manager/src/features/Volumes/VolumesLandingEmptyStateData.ts
`NVM` should be `NVMe` for Block Storage
=> fix: NVM should be NVMe

packages/api-v4/.changeset/pr-9361-added-1688422080839.md, packages/api-v4/src/index.ts, packages/api-v4/src/vpcs/index.ts, packages/api-v4/src/vpcs/types.ts, packages/api-v4/src/vpcs/vpcs.ts, packages/manager/.changeset/pr-9361-added-1688421871670.md, packages/manager/src/App.tsx, packages/manager/src/queries/vpcs.ts, packages/validation/.changeset/pr-9361-added-1688422154757.md, packages/validation/src/index.ts, packages/validation/src/vpcs.schema.ts
Add initial VPC endpoints, validation, and RQ queries.
- Add VPC endpoints
- Add VPC types
- Add `createVPCSchema` and `updateVPCSchema` for validation
Reach out for detailed testing instructions if you want to work with the queries in alpha.
=> feat: [M3-6722] – VPC endpoints, validation, & React Query queries

packages/manager/.changeset/pr-9364-added-1688576551150.md, packages/manager/src/eventMessageGenerator.ts, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/CaptureSnapshot.tsx, packages/manager/src/features/ToastNotifications/ToastNotifications.tsx, packages/manager/src/mocks/serverHandlers.ts
Error messaging for the backups service is minimal and does not provide users with much insight on the reason for a failure or whether they can address it.
Ultimately, we want to display more detailed error messages in Cloud Manager for failed backup restores and snapshot backups, which will require API to return these errors for Cloud to surface. This is ticketed and in the backlog: ARB-4001.
In the meantime, this PR addresses front-end improvements we can make to error messaging with the goal of (a) error prevention and (b) providing additional general context of limitations and requirements for the backup service.
We are updating generic error messages with a docs link to point users to potential reasons for the failure. We are also adding a warning notice in the linode create page to …
=> feat: [M3-6789] - Improve failed backup error messaging

packages/manager/.changeset/pr-9358-fixed-1688405470106.md, packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.tsx, packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/QRCodeForm.tsx, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx
**Old:** 
```
To disable Google authentication and log in using your Linode credentials, click the Linode button above. 
```
**New:**
```
To disable Google authentication and log in using your Cloud Manager credentials, click the Cloud Manager button above.
```
- Run the app and check the copy at http://localhost:3000/profile/auth.
=> fix: wording in "My Profile" -> "Login and Authentication"

packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts, packages/manager/cypress/e2e/core/stackscripts/delete-stackscripts.spec.ts, packages/manager/cypress/e2e/core/stackscripts/smoke-stackscripts-landing-page.spec.ts, packages/manager/cypress/e2e/core/stackscripts/update-stackscripts.spec.ts, packages/manager/cypress/support/intercepts/stackscripts.ts
Add new E2E tests for `StackScript`
- Add update `StackScript` tests
- Add delete `StackScript` tests
`yarn cy:run -s "cypress/e2e/core/stackscripts/*.spec.ts"`
=> test: [M3-6505] - Add StackScript Update/Delete E2E Tests

packages/manager/.changeset/pr-9374-changed-1688763763302.md, packages/manager/cypress/e2e/core/account/change-username.spec.ts, packages/manager/cypress/e2e/core/account/security-questions.spec.ts, packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts, packages/manager/src/components/TextField.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
- Add labelTooltipText prop to the TextField component
- Update Metadata copy with suggested changes from @wildmanonline
| ![user data tooltip before](https://github.com/linode/manager/assets/115299789/0c7be335-0810-4c23-805b-b08d4c4136f9) | ![user data tooltip after](https://github.com/linode/manager/assets/115299789/39111b25-3ded-40c6-a923-c24abd81ff68) |
| ![user data before](https://github.com/linode/manager/assets/115299789/9fb1fd10-2c69-4b7d-a1e8-93ed5214d48f) | ![user data after](https://github.com/linode/manager/assets/115299789/687535df-625e-45fc-afa6-6f6915819db7) |
- Turn on the MSW and go to `/linodes/create`
- Select `metadata-test-distro`
- Select the London, UK region
- Scroll down to the Add User Data accordion
=> feat: [M3-6842] - Update Metadata copy

packages/manager/src/components/EnhancedSelect/Select.tsx
Fixed larger than normal gap between selects
- Changed order to apply overrides properly
| <img width="577" alt="Screenshot 2023-07-10 at 2 52 57 PM" src="https://github.com/linode/manager/assets/125309814/0bb63d6b-1dc4-4c3f-bfaf-78ac69221ef0"> | <img width="572" alt="Screenshot 2023-07-10 at 2 52 51 PM" src="https://github.com/linode/manager/assets/125309814/a07da4e7-a06c-4a7f-86a5-2abb9510069c"> |
Go to `/account/billing`
=> fix: minor css regression account > billing history dropdowns

packages/api-v4/CHANGELOG.md, packages/api-v4/package.json, packages/manager/CHANGELOG.md, packages/manager/cypress/e2e/core/account/change-username.spec.ts, packages/manager/cypress/e2e/core/account/security-questions.spec.ts, packages/manager/cypress/e2e/core/kubernetes/smoke-lke-create.spec.ts, packages/manager/package.json, packages/manager/src/components/EnhancedSelect/Select.tsx, packages/manager/src/components/TextField.tsx, packages/manager/src/features/Images/ImagesDrawer.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordion.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx, packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx, packages/validation/CHANGELOG.md, packages/validation/package.json
**Brief description explaining the purpose of the changes**
- Change #1
- Change #2
> **Note**: Use `<video src="" />` tag when including recordings in table
| Content | Content |
2. **How to reproduce the issue (if applicable)?**
3. **How to verify changes?**
4. **How to run Unit or E2E tests?**
> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**
`<commit type>: [JIRA-ticket-number] - <description>`
**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user …
=> Master to develop v1.97.0

packages/manager/cypress.config.ts, packages/manager/cypress/e2e/region/hello-world.spec.ts, packages/manager/cypress/e2e/region/linodes/create-linode.spec.ts, packages/manager/cypress/e2e/region/linodes/delete-linode.spec.ts, packages/manager/cypress/e2e/region/linodes/update-linode.spec.ts, packages/manager/cypress/support/constants/timeouts.ts, packages/manager/cypress/support/intercepts/linodes.ts, packages/manager/cypress/support/util/backoff.ts, packages/manager/cypress/support/util/promises.ts, packages/manager/cypress/support/util/regions.ts
Adds end-to-end tests to our Cypress regions test suite to confirm that Linode create, update, and delete operations work end-to-end against all of our regions.
- Add Linode create region tests
- Add Linode update (label, root password) region tests
- Add Linode delete (via details page) region tests
At the moment, these tests can only be run locally. They're also slow because they create real resources against all of our regions. To speed things up, you can run the tests against only a single region:
(Note: You don't have to have Cloud running locally for this.)
```bash
CYPRESS_BASE_URL="https://cloud.linode.com" CY_TEST_SUITE="region" CY_TEST_REGION="us-east" yarn cy:run -s "cypress/e2e/region/linodes/*.spec.ts"
```
If you do want to run the tests against every region (which will be …
=> test: [M3-6627] - Add region tests for Linodes

packages/manager/.changeset/pr-9376-tech-stories-1689016335781.md, packages/manager/src/GoTo.tsx, packages/manager/src/MainContent.tsx, packages/manager/src/features/LoadBalancers/EntryPoints/EntryPointCreate/EntryPointCreate.tsx, packages/manager/src/features/LoadBalancers/EntryPoints/EntryPointLanding/EntryPointLanding.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerCreate.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerDetail.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerLanding.tsx, packages/manager/src/features/LoadBalancers/Routes/RouteCreate/RouteCreate.tsx, packages/manager/src/features/LoadBalancers/Routes/RouteLanding/RouteLanding.tsx, packages/manager/src/features/LoadBalancers/index.tsx
Create basic files, folders, and routing for AGLB routes.
Initial routes in include:
Load Balancer Landing - `/loadbalancers`
Load Balancer Create - `/loadbalancers/create`
Load Balancer Details - `/loadbalancer/:id/:tab`
Route Landing - `/loadbalancers/routes`
Route Create - `/loadbalancers/routes/create`
Entry Point Landing - `/loadbalancers/entrypoints`
Entry Point Create - `/loadbalancers/entrypoints/create`
See self-review for a couple places I request feedback from the team.
Akamai Global Load Balancer Landing:
Load Balancer Details Landing:
**How to setup test environment?**
Check out this branch.
**How to verify changes?**
Confirm that you can navigate to the following URLs:
Load Balancer Landing:
- http://localhost:3000/loadbalancers (url when the 'Load Balancers' tab is clicked) …
=> feat: [M3-6822] - Add initial routes, folders, pages, and tabs for AGLB

packages/manager/.changeset/pr-9362-fixed-1688576649790.md, packages/manager/src/components/BarPercent/BarPercent.tsx, packages/manager/src/components/TransferDisplay/TransferDisplay.test.tsx, packages/manager/src/components/TransferDisplay/TransferDisplay.tsx
For accounts without any active Linode services, the MNTP percentage was displaying a misleading "You have used 100% of your Monthly Network Transfer Pool". This was due to `poolUsagePct` calculation: if `used` < `quota`, calculate the percentage; else, set the percentage to 100% because the `quota` must have been reached. 
In the case where usage was `0` and quota was `0`, this calculation resulted in 100%. Although technically a correct calculation, I think this seems misleading because it could cause customers to think they have reached a limit or are being billed for something they are not.
TODO:
- `poolUsagePct` evaluates to `0` if the data `used` is `0`
- When an account's usage is 0%, such as when there are no active services on the account, the MNTP text reads "You have used 0.00% …
=> fix: [M3-6834]: Misleading MNTP percentage for accounts with no active services

packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts
Recent improvements to the Linode top bar navigation broke the Linode landing table tests which check those elements. This fixes that.
Because we replaced links with buttons for navigation, we can no longer test that the Linode Cloud Community button navigates the user to the expected place because it also opens in a separate tab, which Cypress is unable to interact with. Previously we asserted that the `href` attribute had an expected value but this is no longer available.
We'll wait for the automated run to confirm that `smoke-linode-landing-table.spec.ts` passes.
=> chore: Fix broken Linode landing table top bar navigation test

packages/manager/src/dev-tools/FeatureFlagTool.tsx
Super tiny PR to persist our MSW flag choices via local storage.
Enable an MSW flag and reload the page.
=> Chore: Enable local storage for MSW feature flags

packages/manager/.changeset/pr-9405-added-1689345233361.md, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.test.tsx, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Small PR to add the AGLB create menu entry - also added a test for good measure since I was adding a prop
Subtitle and icon are TODO items
1. Pull code locally, enable both MSW & the AGLB flag
2. Confirm presence and behavior of new create menu entry
3. Verify there's no regression with the create menu when the flag is off
=> Feat: [M3-6806] AGLB - Add LoadBalancer create menu entry

packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts
Add new coverage for Linode deletion from Linode landing page.
- Add a new test for for Linode deletion from Linode landing page.
`yarn cy:run -s "cypress/e2e/core/linodes/smoke-delete-linode.spec.ts"`
=> M3-6577: Add Cypress coverage for Linode deletion from details page

packages/manager/.changeset/pr-9420-tech-stories-1689780372828.md, packages/manager/src/components/GaugePercent/GaugePercent.stories.mdx, packages/manager/src/components/GaugePercent/GaugePercent.styles.ts, packages/manager/src/components/GaugePercent/GaugePercent.tsx, packages/manager/src/components/GaugePercent/index.ts, packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Load.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Network.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/RAM.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Storage.tsx, packages/manager/src/features/Longview/LongviewLanding/Gauges/Swap.tsx
Ran Codemod against SRC > Component > GaugePercent
Before:
After:
Go to the Longview section and make sure the functionality and the visual components are the same.
Note: You might need to setup a Longview client: 
1. Create a new Linode (ex. Debian 11, Debian 12 does not work)
2. Create a new Longview client (Click the "Add Client" button)
3. Copy the installation curl command
4. SSH into your Linode and paste the installation command
Reference: https://www.linode.com/docs/products/tools/longview/guides/troubleshooting/
=> refactor: [M3-6342] - MUI v5 Migration - SRC > Component > GaugePercent

packages/manager/.changeset/pr-9414-changed-1689694769486.md, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/AttachVLAN.tsx, packages/manager/src/features/Linodes/LinodesCreate/VLANAccordion.tsx
We want to demote VLAN in favor of VPC, so the VLAN section will now be hidden inside an accordion.
https://github.com/linode/manager/assets/115299789/b73b7c9c-f265-4f40-a72b-10d5b1b6bfaf
Go to `/linodes/create` and scroll down to the VLAN section. Using the dev tools, turn the VPC feature flag on/off
=> feat: [M3-6732] - Make VLAN section in Linode Create an Accordion

packages/manager/src/components/DocumentTitle/DocumentTitle.tsx
- Type-checking on `develop` is failing ❌
- Fixes type error relating to https://github.com/linode/manager/pull/9406
- Uses a generic to type `withDocumentTitleProvider`
- Verify type checking passes
=> fix: `withDocumentTitleProvider` type-checking error

packages/manager/.changeset/pr-9417-fixed-1689705981191.md, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.styles.tsx, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelectV2.tsx
Fix LinodeSelect dropdown styling to make sure items don't appear over the global nav
- add zIndex property and disablePortal prop to underlying component
before
after
- go to  `/images/create/disk ` or `/domains/create` to ensure linode select works as expected, and to `/firewalls` and see if the linode dropdown for creating a firewall/adding linodes to a firewall still look the same
=> fix: [M3-6799] - Linode Select Dropdown Z-index

docker-compose.yml
Sorry guys! When I merged the regions PR earlier, it also brought back some params related to Cypress recording that don't belong.
If the e2e tests run against this PR, we should be good (they don't even necessarily need to pass, the tests themselves just need to run)
=> fix: Fix automated Cypress tests

packages/manager/.changeset/pr-9424-fixed-1689773023166.md, packages/manager/src/features/Images/ImagesActionMenu.tsx
Moved edit image action item into drop down menu
- Ensure that all menu actions are in a dropdown menu for ImagesActionMenu.tsx regardless of image status
before:
after:
Verify that when uploading an image, when the image is in 'Processing' state, the edit button is inside the dropdown menu; verify that actions still work as expected
=> fix: [M3-6006] - Make images landing page "Edit" buttons consistent

packages/manager/.changeset/pr-9435-tech-stories-1689887826129.md, packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx, packages/manager/src/hooks/useIsLargeAccount.ts
- Makes it so Cloud Manager will only try fetch Linodes when it absolutely needs to
- After https://github.com/linode/manager/pull/9421 is merged, if you were to load the app to a non-linodes route, for the first time ever in Cloud Manager's history, Linodes will not be fetched! 🎉
- Disable `useIsLargeAccount` until we absolutely need to know if the account is large or not
> Notice how there is one less fetch. After https://github.com/linode/manager/pull/9421 is also merged, there will be zero fetches to Linodes initially
| ![Screenshot 2023-07-20 at 5 13 09 PM](https://github.com/linode/manager/assets/115251059/98f455d8-426d-47de-9a32-ac966410a037) | ![Screenshot 2023-07-20 at 5 12 43 …
=> chore: Only enable `useIsLargeAccount` when it's absolutely needed

packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
Our StackScript test broke because one of the Images the test selects, `Ubuntu 22.10`, became deprecated and tripped up a Cypress selector.
This quickly fixes the test by updating the images used by the tests to their latest versions.
There's potential to fix this permanently by making an API request to fetch the same data that's shown in Cloud, but this happens so infrequently that today I opted to fix it quickly but plan to revisit this in the future.
We can rely on the automated tests for this, but reviewers can use the following command to run the affected test locally:
```bash
yarn cy:run -s "cypress/e2e/core/stackscripts/create-stackscripts.spec.ts"
```
=> fix: Fix StackScript test by using latest images available

packages/manager/.changeset/pr-9452-tech-stories-1690342391207.md, packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.stories.tsx, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx
We want to allow for a fully custom `noOptionsText` without italics
- Added two additional storybook stories for custom no options text and multi-select
- Allow for a fully custom `noOptionsText` without italics
> **Note**
The mult-select is just a visual with the `actions` tab used to show data received by event handler. Don't expect to uncheck/check additional options.
| Screenshots   | |
| <img width="442" alt="Screenshot 2023-07-25 at 11 21 16 PM" src="https://github.com/linode/manager/assets/125309814/2e9f75ea-b318-4163-9484-6d41f4e7449d"> | <img width="462" alt="Screenshot 2023-07-25 at 11 21 21 PM" src="https://github.com/linode/manager/assets/125309814/95c66aef-8f98-496f-b37f-63d0f99bdc3b"> |
1. Go to storybook page …
=> refactor: [M3 6730] - LinodeSelect - Allow fully custom noOptionsText

packages/manager/.changeset/pr-9461-fixed-1690542546973.md, packages/manager/src/components/ActionsPanel/ActionsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsAlertsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsPasswordPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx
**fix: ActionsPanel regression**
| ![image](https://github.com/linode/manager/assets/119517080/4e9b1b5c-129e-4607-b5c2-00e11b28f4b0) | ![image](https://github.com/linode/manager/assets/119517080/e9b46d17-a87f-4502-a34b-d9c6d38a4137) |
1. **Navigate to http://localhost:3000/linodes/48056700/settings**
2. **Validate the position of save buttons for label panel and reset root password  panel**
=> fix: ActionsPanel regression

packages/manager/.changeset/pr-9459-fixed-1690565333481.md, packages/manager/.changeset/pr-9459-tech-stories-1690511497337.md, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
Issue: The data entered into the "Create Firewall" drawer persists after cancelling or creating a firewall.
Reset the form inputs every time the drawer is opened.
| <video src="https://github.com/linode/manager/assets/139489745/a3aa7aaf-6d3d-46a8-9c5e-6dd8c1663f8b" /> | <video src="https://github.com/linode/manager/assets/139489745/10b7c81a-6a86-419e-b548-30a871727def" /> |
1. Navigate to the Firewalls tab
2. Hit "Create Firewall"
3. Enter some text into the fields, try closing the drawer and creating a test firewall. Open the window again and make sure the inputs are cleared.
=> fix: [M3-6658] - Cleared Firewall Drawer Inputs

packages/manager/.changeset/pr-9473-fixed-1690900164385.md, packages/manager/src/features/StackScripts/stackScriptUtils.ts
Gopaddle was missing from the app list, this PR re-adds that and wazuh per OCA-1177
Go to Marketplace and search for the apps, ensure that they show up
=> fix: Add Gopaddle & re-add Wazuh Marketplace apps

docs/CONTRIBUTING.md, packages/api-v4/.changeset/README.md, packages/manager/.changeset/README.md, packages/manager/.changeset/pr-9419-tech-stories-1689716682370.md, packages/validation/.changeset/README.md, scripts/changelog/utils/constants.mjs
During the [v1.98.0 release](https://github.com/linode/manager/releases/tag/linode-manager%40v1.98.0), we added an Upcoming Features section to our changelog. If we want to continue this in our future releases, offically adding this changeset type to our automated changelog generation script will allow us to categorize our changesets more easily/accurately.
Run `yarn changeset` and confirm Upcoming Features is listed under the changeset types to select from. Create a changeset of that type, don't commit it, and run `yarn generate-changelogs` to confirm a changelog is generated with an Upcoming Features section.
=> chore: Add 'Upcoming Features' to the changeset types

packages/manager/.changeset/pr-9484-changed-1690998482707.md, packages/manager/src/features/Linodes/LinodesCreate/SelectPlanPanel/utils.ts
- Change `Premium` to `Premium CPU` in the Plans table
| ![Screenshot 2023-08-02 at 1 44 38 PM](https://github.com/linode/manager/assets/115251059/bcd266c2-5ada-4634-b060-7b9a78b32c83) | ![Screenshot 2023-08-02 at 1 44 15 PM](https://github.com/linode/manager/assets/115251059/baf71a99-8692-4366-80c1-f9ab68ca64ed) |
- Verify you now see `Premium CPU` instead of just `Premium` in affected plans table
- Check the Linode create page (`http://localhost:3000/linodes/create`)
- Check the Kubernetes create page (`http://localhost:3000/kubernetes/create`)
=> chore: [M3-6954] - Change `Premium` to `Premium CPU`

packages/manager/.changeset/pr-9491-fixed-1691152316740.md, packages/manager/src/features/EntityTransfers/EntityTransfersLanding/TransferControls.tsx
Fixed the input alignment in Account > Service Transfers
- Fixed alignment for screen size <960
- Fixed alignment for screen size <600
- Fixed alignment for screen size <450
| --- | --- |
| ![Screenshot 2023-08-03 at 8 00 39 PM](https://github.com/linode/manager/assets/139489745/be7782a4-9d32-461c-a3ef-1a8e1af999c5) | ![Screenshot 2023-08-03 at 8 05 45 PM](https://github.com/linode/manager/assets/139489745/15564471-3f96-4cbc-8bb3-0148b08c1edf) |
| ![Screenshot 2023-08-03 at 8 03 15 PM](https://github.com/linode/manager/assets/139489745/775b09a1-0f32-4305-9547-6fff7fbbcafa) | ![Screenshot 2023-08-03 at 8 10 18 PM](https://github.com/linode/manager/assets/139489745/56a7a457-8215-4a30-986d-02a066c0da5d) |
| ![Screenshot 2023-08-03 at 8 03 37 …
=> fix: [M3-6688] - Alignment Issue on Service Transfers Page

packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/SummaryPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancerTableRow.tsx
Due to styling changes in the IPAddress component (see this pr: https://github.com/linode/manager/pull/9445), the copy icon stopped showing up for Nodebalancers in both the Nodebalancer landing page and a Nodebalancer details page.
(Something interesting to note is that the Linodes landing page and the NodeBalancer landing pages have different behavior for the IP address copy icon. This PR just restores the NodeBalancer IP address behavior to what it used to be, but might be worth looking into trying to get them to have matching behavior)
- Make IP address' copy icons show up for node balancer pages
**prod**:
**not prod**:
| ![image](https://github.com/linode/manager/assets/139280159/036adcff-c40e-46e5-a61b-427eeb11277b) | …
=> fix: IP Address copy icon regression

packages/manager/CHANGELOG.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Cloud was crashing when pasting user data from https://gist.githubusercontent.com/ngaffa/15d46c98dd82620c8120ddf7398d6dbd/raw/1b5efe9669f62ddfc50b9bdb746294fa8b3cfc6e/cloud-init.yaml 
It seems that what looks like an apostrophe is actually a UTF-8-encoded right single quotation mark which the `btoa` function doesn't support. The fix was to encode the user input before calling `btoa`
| <video src="https://github.com/linode/manager/assets/115299789/539e315d-948d-4a6b-8f81-be4db9b67afc" />| <video src="https://github.com/linode/manager/assets/115299789/1d3f2412-ee17-40c7-b8e2-83859eccedd7" /> |
- Go to Linode Create
- Select a cloud-init compatible image
- Select a Metadata compatible region (Washington DC or Paris)
- Observe that pasting the gist …
=> fix: [M3-6985] - User data input crash

packages/manager/src/features/Help/Panels/AlgoliaSearchBar.tsx
Fixes the UI bug which was causing markup to appear in the `AlgoliaSearchBar` in the `/Support` landing page. Also makes it possible for text to be cleared via `isClearable` prop.
- Change `isClearable={false}` to `isClearable={true}`
- Change `highlight: true` to `highlight: false`
|  ![before](https://github.com/linode/manager/assets/119514965/dfb7805e-61d7-46ae-9637-602c5236cc68) | ![after](https://github.com/linode/manager/assets/119514965/7a5451e8-653a-4039-868d-8391a877897f) |
1. Navigate to `/Support` landing page and type in a search term.
2. Use the mouse to click on one of the results, this will open a new tab.
3. Close the new tab.
4. Inspect the text inside the `AlgoliaSearchBar` and verify that …
=> fix: [M3-6898] - Markup in Help landing

packages/manager/src/features/Linodes/LinodesLanding/AppsSection.tsx
**Brief description explaining the purpose of the changes**
- `StyledLink` and `StyledAppLinkDiv` styles needed to be swapped.
| Before  | After   | Prod |
| ![Screenshot 2023-08-07 at 2 37 08 PM](https://github.com/linode/manager/assets/125309814/8e0d3e7f-2bfd-460e-b409-33cb72a4c53d) | ![Screenshot 2023-08-07 at 2 36 40 PM](https://github.com/linode/manager/assets/125309814/6dd304ce-0592-475b-9820-b3f9e21b8115) | ![Screenshot 2023-08-07 at 2 36 46 PM](https://github.com/linode/manager/assets/125309814/b094c480-8873-4088-8ca9-29b9f4252add) |
1. Don't have any linodes in account
2. Go to http://localhost:3000/linodes
3. Observe fixes
=> fix: linodes empty state - styles needed to be swapped

packages/manager/src/features/OneClickApps/AppDetailDrawer.tsx
fixes the issue where drawers for the marketplace apps weren't full width
- remove line that set width to be 300px for any view
| ![image](https://github.com/linode/manager/assets/139280159/1beec7de-8772-46e2-a8a6-85e96505e38e) | ![image](https://github.com/linode/manager/assets/139280159/3774e3f5-4472-402c-9894-4f0e1510241c) |
1. Test that the app detail drawer on marketplace is full width on mobile viewports
=> fix: Make drawer full width for app detail drawer on mobile viewport

packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx
- Fixes unclearable Linode `label` on the Linode Create page
- Caused by https://github.com/linode/manager/pull/9421
> [!NOTE]
> I am pressing backspace but the label keeps repopulating
https://github.com/linode/manager/assets/115251059/be6395e6-f242-4dd8-b659-7e056f66c0ea
- Verify you can fully backspace the auto-generated Linode label on the Linode Create flow
- Please compare behavior to production to verify no behavior has been changed
=> fix: Allow auto-generated Linode `label` to be cleared

packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx, packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx, packages/validation/src/volumes.schema.ts
- Makes the Volume Create form match production's behavior
- The `LinodeSelect` was expecting `null` to clear the type-ahead input, but we were using -1 to represent no selection. Switching `-1` to `null` allows the `LinodeSelect` to work as expected
> [!important]
> Notice how the type-ahead (aka input value) of the MUI Autocomplete does **not** clear
https://github.com/linode/manager/assets/115251059/2c54dc2a-12f2-4ea8-87fa-6d4923df8473
https://github.com/linode/manager/assets/115251059/d071a6ae-8c2f-47b6-baac-e12c5c7eb53e
- Verify that `/volumes/create`  works the same as production
and also
- Type a label
- Pick a Region
- Pick a Linode
- Clear the Region input
- Verify that the Linode Select clears completely (no type-ahead and no value in the form state)
=> fix: Linode Select clear behavior by using `null` instead of `-1` in form state

packages/manager/.changeset/pr-9499-fixed-1691416274996.md, packages/manager/src/features/Users/UserPermissionsEntitySection.tsx
Users, the permissions table radio buttons are unaligned on mobile view
| ![image](https://github.com/linode/manager/assets/119517080/45408715-2111-4ccf-af2f-2fbeb97f3524) | ![image](https://github.com/linode/manager/assets/119517080/d668ff8f-dfc7-4ed1-88f1-cfa358df0180) |
1. **Navigate to http://localhost:3000/account/users/user/permissions**
2. **validate the layout in small screen.**
=> fix: [M3-6498] - User Permissions table radio button misalignment on mobile

packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts
Fixes the failing test in `smoke-create-domain-records.spec.ts` by changing the value used when inserting a TXT record.
A recent improvement in the API added additional validation to these records which caused our test to begin failing, and updating the test to use the expected format resolves the issue.
We can rely on the automated tests for this, but you can also run the test locally with this command:
```bash
yarn cy:run -s "cypress/e2e/core/domains/smoke-create-domain-records.spec.ts"
```
=> fix: Fix domain test by using key=value format for TXT records

packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts, packages/manager/src/features/Linodes/LinodesLanding/CardView.tsx
Add Cypress tests for Linode landing page "Summary View" button
- Add test to verify "Summary View" button works as expected.
`yarn cy:run -s "cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts"`
=> M3-6614 Add Cypress tests for Linode landing page 'Summary View'

packages/manager/.changeset/pr-9509-fixed-1691434601314.md, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx
The `scrollableAncestor="window"` prop on the `Waypoint` instance was breaking the infinite scrolling for the node pools on a K8 cluster detail. From what I can understand and read, the prop is responsible for:
> A custom ancestor to determine if the target is visible in it. This is useful in cases where you do not want the immediate scrollable ancestor to be the container. For example, when your target is in a div that has overflow auto but you are detecting onEnter based on the window.
Which we are not doing at all since our handler is based on a count of node pools. 
Removing this prop fixes the issue (loads the next 25 node pools on scroll) and does not appear to introduce any other regression.
1. Pull code locally, and create 10 node pools on a given k8 cluster (no need to test with …
=> fix: [M3-6668] Broken K8 node pool infinite scrolling

packages/manager/.changeset/pr-9521-fixed-1691588152719.md, packages/manager/src/components/EnhancedSelect/Select.styles.ts
**Fixed the styling syntax error.**
| ![image](https://github.com/linode/manager/assets/119517080/854eb514-208c-401f-a1e7-be7d26527550) | ![image](https://github.com/linode/manager/assets/119517080/5996dc24-0f79-4239-a52d-af63704381ce) |
##How to test
- Navigate to http://localhost:3000/support/tickets.
- Validate dropdown input field "What is this regarding?".
=> fix:[M3-6500] - Enhanced Select fields text cut off at bottom

packages/manager/.changeset/pr-9527-tech-stories-1691605134705.md, packages/manager/src/components/ActionMenu/ActionMenu.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Processes/ProcessesTable.tsx, packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
Replaced deprecated keycodes.
event.keyCode === 13
becomes
event.key === 'Enter'
Link for conversions: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
1. SearchBar.tsx: In the search bar at the top of the page, type the name of one of your Linodes, hover over it, and then hit the `Enter` key. You should navigate to the details page.
2. ActionMenu.tsx: Navigate to the `Linodes` page, hit the Action Menu (`...`) for any linode, hover over any option, and hit the `Enter` key. That option should be executed.
3. ProcessesTable.tsx: Navigate to the `Longview` page. Click `View Details` on any of the Longviews. Navigate to the `Processes` tab. Hover over any process and try to hit the 'Enter' key. This functionality wasn't working pre-changes and still is not …
=> refactor: [M3-6669] - Replaced deprecated keycodes

packages/manager/.changeset/pr-9533-tech-stories-1691707780382.md, packages/manager/src/components/ActionMenu/ActionMenu.tsx, packages/manager/src/components/Link.tsx, packages/manager/src/components/UserMenu.stories.mdx, packages/manager/src/features/NotificationCenter/NotificationSection.tsx, packages/manager/src/features/TopMenu/TopMenu.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/features/TopMenu/UserMenu/index.ts, packages/manager/src/foundations/themes/dark.ts
- The codebase has many different packages that all do the same things, we are trying to consolidate. In this case, we want to use MUI's Menu/Popper/Popover components instead of Reach UI's Menu
- This is similar to https://github.com/linode/manager/pull/9224
- Makes `UserMenu` use a MUI `Popover` instead of a Reach UI `Menu`
- Uses **a ton** less one-off styles
| ![Screenshot 2023-08-10 at 6 51 46 PM](https://github.com/linode/manager/assets/115251059/1e35e904-7a90-4e8f-b807-81d61b5d09e3) | ![Screenshot 2023-08-10 at 6 51 52 PM](https://github.com/linode/manager/assets/115251059/d446ffd0-3bb1-4828-ac50-9e359744090d) |
> [!important]
> I know the styles aren't 1:1 but I did my best to get them close. Also, does this new implementation have any …
=> refactor: [M3-7006] - Make `UserMenu` use MUI instead of Reach UI

packages/manager/.changeset/pr-9543-tech-stories-1692026704155.md, packages/manager/src/features/Linodes/LinodesLanding/IPAddress.tsx
- Fixes the duplicate key error when on the Linodes Landing page (and NodeBalancer landing page)
- Use **lodash** instead of **ramda** `tail()` function
- Clean up `IPAddress.tsx` while fixing the bug
| ![Screenshot 2023-08-14 at 11 18 33 AM](https://github.com/linode/manager/assets/115251059/29f7036e-6c02-4988-b798-a7dadeb403e8) | ![Screenshot 2023-08-14 at 11 18 19 AM](https://github.com/linode/manager/assets/115251059/3cb93dc5-d666-4e71-9ab7-aadabcdf0c4f) |
- Have at least 1 Linode 
- Go to `/linodes`
- Verify you don't see a console error about duplicate keys
=> fix: Duplicate `key` error on Linodes Landing

packages/manager/.changeset/pr-9534-fixed-1691788679611.md, packages/manager/src/components/EnhancedSelect/components/SelectPlaceholder.tsx, packages/manager/src/components/Tag/Tag.tsx, packages/manager/src/features/Search/ResultRow.tsx, packages/manager/src/features/Search/SearchLanding.tsx, packages/manager/src/features/TopMenu/SearchBar/SearchBar.styles.ts, packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
This PR addresses a few issues with the top search bar and the search landing page. Some (the circular dependency for instance) seem to be newer degradations while the others may have never been addressed or prioritized. 
The task involves improvements to the basic search (not the dropdown search results who remained untouched).
Notably, the improvements made to the UX are related to the state of the search field value while interacting with the search field and navigating the application. 
Please see the self review for details about the fixes
| ![Screenshot 2023-08-11 at 23 09 45](https://github.com/linode/manager/assets/130582365/3e2d4f32-51fa-42d3-967e-7d3dd6efae4c) | ![Screenshot 2023-08-11 at 23 10 …
=> fix: [M3-7002] Topbar Search fixes

docs/development-guide/13-coding-standards.md
Documenting our conversation regarding unions, const enums, and plain old javascript objects using `as const`.
=> chore: [M3-7012] - Add documentation for Typescript unions, const enums and objects

packages/manager/.changeset/pr-9548-fixed-1692123558409.md, packages/manager/src/components/Link.tsx, packages/manager/src/features/Support/Hively.tsx
- Fixes Hively link visual bug 🎨
- Caused by https://github.com/linode/manager/pull/9411
- Added `hideIcon` prop to the `<Link />` component for special cases like this
- I probably could have used a plain `<a>` here but I figured we'd want to use `<Link />` for consistency
- Cleans up styles and fixes UI bug
- Remove use of `makeStyles`
- Removed use of `React.FC`
| ![Screenshot 2023-08-15 at 2 11 15 PM](https://github.com/linode/manager/assets/115251059/ace81023-3d95-4953-b6a9-f02e9523173a) | ![Screenshot 2023-08-15 at 2 11 02 PM](https://github.com/linode/manager/assets/115251059/d1726a1e-f59d-4956-b7e4-215397293874) |
- You can either create a support ticket in the **dev** environment and respond to yourself OR just manually make this …
=> fix: [M3-7024] - Fix Hively visual regression

packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx
- https://github.com/linode/manager/pull/9540 and https://github.com/linode/manager/pull/9485 merged together and caused `LinodeRow.test.tsx` to fail because Action Menus now behave differenty
- This is my bad! I should have caught this considering I merged https://github.com/linode/manager/pull/9540 after https://github.com/linode/manager/pull/9485 was already merged
- Open action menu before making assertions
- Verify unit tests pass in Github Actions ⬇️
=> fix: Failing `LinodeRow.test.tsx` unit test

packages/manager/.changeset/pr-9554-fixed-1692219454826.md, packages/manager/src/features/Firewalls/FirewallDetail/index.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx, packages/manager/src/features/Firewalls/index.tsx
- Fixes the firewalls breadcrumb incorrectly containing the `id` 🍞
- Caused by https://github.com/linode/manager/pull/8856 I think
- Clean up tabs logic to be more readable and simple 🧼
- Fix breadcrumb by passing it a pathname with the firewall's `label` 🍞
- Greatly improves the `/firewalls/create` routing code and behavior 🔗
| Breadcrumb has `id` 😕 | Breadcrumb has only the `label` ✅ |
| ![Screenshot 2023-08-16 at 4 39 51 PM](https://github.com/linode/manager/assets/115251059/68b2b70c-519d-49c6-a1e2-b024c83417c6) | ![Screenshot 2023-08-16 at 4 39 38 PM](https://github.com/linode/manager/assets/115251059/d1f0f496-d256-4c07-a8eb-5ef3fead72b4) |
| Create drawer does not correlate with the URL 😕 | Create drawer is 1:1 with the URL ✅ |
| <video …
=> fix: [M3-6836] - Fix Firewalls Breadcrumb

packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts
This flag gates our upcoming changes for DC-specific pricing. 
- Creates the feature flag in Launch Darkly
- Adds the feature flag to `featureFlags.ts`
- Adds the feature flag to dev tools
1. **How to verify changes?**
- Check out this branch.
- Confirm the new feature flag is returned from Launch Darkly in the network requests of the browser dev tools.
- Confirm that DC-Specific Pricing shows up in the dev tools under the Feature Flags section.
=> chore: [M3-6691] - Add DC-specific pricing feature flag

packages/manager/.changeset/pr-9564-added-1692350316540.md, packages/manager/src/utilities/pricing/constants.ts, packages/manager/src/utilities/pricing/dynamicPricing.test.tsx, packages/manager/src/utilities/pricing/dynamicPricing.ts, packages/manager/src/utilities/pricing/entityPricing.ts
This PR introduces utils and constants for region based dynamic pricing based on region, while waiting for our pricing endpoint, so it's is a bit of throwaway work, tho some bits can be hopefully re-used in the future, specifically the region based increase calculation.
We will need to iterate on this as we go but this is a good starting point to tackle the entities we're confident the pricing can be hardcoded this way (Backup (?),  LKE HA, Nodebalancer, Volume).
Please see self review for more details.
This screenshot was taken while testing the `getDCSpecificPricingDisplay` util in the Volume Create flow, which you can easily do by modifying   the following way:
**`CreateVolumeForm.tsx`**
& 
**`SizeField.tsx`**
See preview section
=> feat: [M3-7037] Introduce dynamic pricing utils

packages/manager/.changeset/pr-9566-upcoming-features-1692376980714.md, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx, packages/manager/src/utilities/pricing/dynamicPricing.ts
- Adds DC Specific pricing to the NodeBalancer Create page 💵
- Allows a undefined region to be passed to `getDCSpecificPrice` 🚫
- Makes NodeBalancer Create show a dynamic price 💵
https://github.com/linode/manager/assets/115251059/e6b1d6a4-6d62-487f-af51-93e41c36cd8a
- Go to `http://localhost:3000/nodebalancers/create`
- Verify that no price shows when no region is selected
- Verify that the price in normal regions is `$10.00`
- Verify that the price in **Sao Paulo** and **Jakarta** are higher
=> feat: [M3-6974] - Add DC Specific Pricing to NodeBalancer Create

packages/manager/.changeset/pr-9567-tech-stories-1692380986951.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx
- Makes it so the dev tools flag checkboxes actually represent which flags are on/off in real life
- They have been very confusing and misleading in certain circumstances creating a confusing developer experience.
- Also, thoughts on reverting #9400?
- I'd prefer to have my local app match exactly what launchdarkly has by default, does anyone else feel this way?
| ![Screenshot 2023-08-18 at 1 31 10 PM](https://github.com/linode/manager/assets/115251059/f4a60971-8fb8-4ea6-b026-d01103bc23ef) | ![Screenshot 2023-08-18 at 1 29 44 PM](https://github.com/linode/manager/assets/115251059/c2403489-d680-4676-b418-9d3d519e0f2b)
- Clear local storage and make sure the dev tools show feature flags accurately
=> fix: Make feature flag dev tools show reality

packages/manager/.changeset/pr-9573-fixed-1692642029020.md, packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.tsx, packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx
Timezone Form Styles:
- The timezone form on `/profile/display` had some unintended styling 🎨
- Caused by https://github.com/linode/manager/pull/9341
Stackscripts:
- Hotfix to revert state bug with `FromStrackScriptContent` after it was converted to a functional component in https://github.com/linode/manager/commit/af161f33b451d35c2175c19465eeb4c710f30c72
Timezone Form Styles:
- Removes red background 🔴
- Fixes incorrect `marginTop` 🔝
Stackscripts:
- Reverts FromStrackScriptContent to class component
| ![Screenshot 2023-08-21 at 2 16 41 PM](https://github.com/linode/manager/assets/115251059/50755316-665f-4b27-9956-a5c223bc4def) | ![Screenshot 2023-08-21 at 2 17 27 PM](https://github.com/linode/manager/assets/115251059/5f2c8a73-0ed0-4cb6-9544-a9b2 …
=> hotfix: Timezone Form Styles and revert FromStrackScriptContent to a class component 

packages/manager/.changeset/pr-9587-fixed-1692802396223.md, packages/manager/src/components/CopyTooltip/CopyTooltip.tsx, packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts, packages/manager/src/features/Linodes/LinodeEntityDetail.tsx
Small fix to a regression from https://github.com/linode/manager/pull/9501 to re-add the hover tooltip in Linode summary
=> fix: [M3-7050] re-instate copy tooltip hover state in Linode Summary

packages/manager/.changeset/pr-9563-fixed-1692305293304.md, packages/manager/src/features/Longview/LongviewLanding/Gauges/CPU.tsx
- Cloud Manager would crash for a Longview client with a negative number of cores
- I don't know why we allow users to have a negative number of cores 😅
- Make sure `clamp` won't throw
| ![Screenshot 2023-08-17 at 4 41 04 PM](https://github.com/linode/manager/assets/115251059/a00f04f8-d647-4aee-8e7f-49430007da81) | ![Screenshot 2023-08-17 at 4 40 26 PM](https://github.com/linode/manager/assets/115251059/0f36c4d6-51d2-451c-a841-0941dfa3dbce) |
- Create a Debian 10 (or similar) Linode
- Create a Longview client and set it up with that Linode you just created
- It's super easy, don't worry!
- Edit `/opt/linode/longview/Linode/Longview/DataGetter/SysInfo.pm` and change line 67 from `my $cores = grep {/processor/} @cpu_info;` to `my $cores = -1;`
- …
=> fix: [M3-7040] - Longview crashing the app with a negative number of CPU cores

packages/api-v4/.changeset/pr-9586-upcoming-features-1692798602248.md, packages/api-v4/src/account/account.ts, packages/api-v4/src/account/types.ts, packages/api-v4/src/linodes/types.ts, packages/manager/.changeset/pr-9586-upcoming-features-1692798648869.md, packages/manager/src/components/EntityHeader/EntityHeader.stories.tsx, packages/manager/src/factories/account.ts, packages/manager/src/factories/billing.ts, packages/manager/src/factories/linodes.ts, packages/manager/src/factories/types.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/accountTransfer.ts
Updates api-v4 types and mocks for expected DC-specific pricing changes to API responses.
Note: #9572 includes the api-v4 updates for adding `region_prices` to a Linode; I'll pull those changes in once that PR is merged.
- Turn the Mock Service Worker on.
- Ensure the DC-Specific Pricing flag is on.
4. **How to verify changes?**
- With **mocks on,** go to the following pages and confirm using the browser dev tools' network tab that the API responses returned for the following endpoints have the data you'd expect based on the example payload in the API spec. The API spec is linked in this ticket or the epic.:
- Linode Create: confirm `backups` has added `region_prices` list for the `linode/types` endpoint
- MNTP dialog:  confirm `region_transfers` has …
=> feat: [M3-6965] - Update api-v4 and mocks for DC-specific pricing

packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts
This is a tiny change to fix the TypeScript error we're seeing when running `vpc-landing-page.spec.ts`. It looks like we did a find+replace of `vpc` to `vpcs` which also inadvertently touched the import.
Run `yarn && yarn build && yarn start:manager:ci`, and then run:
```bash
yarn cy:run -s "cypress/e2e/core/vpc/vpc-landing-page.spec.ts"
```
=> fix: Fix VPC landing page test import

packages/manager/.changeset/pr-9602-fixed-1693332727991.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/LinodeRebuildDialog.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx
We missed a region check in the Linode Rebuild dialog, causing the Add User Data accordion to display when rebuilding a Linode on regions that do not support Metadata. This PR adds a `regionSupportsMetadata` utility function to be used in the Rebuild dialog as well as other places where the accordion is displayed.
Note: I hid the IP addresses for preview purposes
| <video src="https://github.com/linode/manager/assets/115299789/5ec91adb-3904-4478-8d24-5b5b589082a3" /> | <video src="https://github.com/linode/manager/assets/115299789/d8062546-bb3a-4cae-aaf0-e70b0effc7fa" /> |
- Go to the Linodes landing page and rebuild a Linode whose region does not support Metadata (which is any region other than Washington, DC and Paris, FR)
- Select an Image …
=> fix: [M3-7062] - Hide User Data accordion in Linode Rebuild dialog for unsupported regions

docker-compose.yml
This PR attempts to resolve the Jenkins E2E test instability we've seen caused by conflicts related to the `web` service and its name.
There is a corresponding internal PR which modifies the pipeline to take these changes into account. Both PRs will need to be merged at the same time to limit test breakage. Additionally, existing branches will need to pull in the latest changes from `develop` to avoid breakage.
* Removed `web` service hardcoded port and container name so that multiple containers serving Cloud Manager can run simultaneously on a single host
* Removed the hardcoded container name from the test runner services, allowing me to consolidate the `e2e-1`, `e2e-2`, etc. services into a single `e2e` service
This isn't easily testable, but I will abort the automatic test run that …
=> fix: [M3-6999] - Remove Docker Compose hardcoded container names

packages/manager/.changeset/pr-9603-tech-stories-1693333265033.md, packages/manager/package.json, packages/manager/src/components/ActionMenu/ActionMenu.tsx, packages/manager/src/components/Chip.tsx, packages/manager/src/components/Tag/Tag.tsx, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/foundations/themes/light.ts, yarn.lock
- Updates MUI and Emotion to `latest`
- Updating MUI fixes the issues where scrolling with a Menu open would not move the menu correctly. This allows us to re-enable scrolling while action menus are open.
- https://github.com/linode/manager/pull/9540#issuecomment-1677665164
- https://github.com/mui/material-ui/pull/37773
| Notice how you **can't** scroll 😣 | Notice how you **can** scroll and the action menu remains in the correct position 🎉 |
| <video src="https://github.com/linode/manager/assets/115251059/95ed7908-7c3e-40df-af90-908e511a7b44" /> | <video src="https://github.com/linode/manager/assets/115251059/5ed655de-e01b-4d67-bb04-52d901d343cd" /> |
- Checkout the PR
- Run `yarn` for good measure
- Run `yarn dev` and verify the app works and …
=> chore: Update Material UI and Emotion

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- Disable extra Configs API call when VPC is off
| ![Screenshot 2023-08-30 at 3 46 51 PM](https://github.com/linode/manager/assets/115251059/65eaa9fc-14a4-4b7d-995e-717c766b00b2) | ![Screenshot 2023-08-30 at 3 47 40 PM](https://github.com/linode/manager/assets/115251059/9a9c4502-ba77-4683-8b70-9d79ca010662) |
- Make sure configs API calls **do not** happen when the VPC flag is off
=> hotfix: Disable Configs API call when VPC is off

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx
- Extra API calls for Linode Configs ([#9609](https://github.com/linode/manager/pull/9609))
=> Release v1.100.2 - staging → master

packages/manager/src/components/CheckoutBar/CheckoutBar.tsx, packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx, packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx, packages/manager/src/utilities/pricing/constants.ts
Clarifies that HA selection is also needed to create a cluster. Also moves the copy to a prop because it shouldn't have been in `CheckoutBar`, a core component. 
Relates to changes made in #9568 and #9489. 
Still not sure that user feedback in this form is ideal because if a user selects a node pool and a region, the text is replaced with the price and user still can't submit without an HA selection.
| ![Screenshot 2023-08-31 at 9 22 03 AM](https://github.com/linode/manager/assets/114685994/d22c6b79-0e77-4e60-87b1-f32a3db7323b) | ![Screenshot 2023-08-31 at 9 21 19 AM](https://github.com/linode/manager/assets/114685994/46ce4487-7592-44ef-8cb4-ba6149920938) |
1. **How to verify changes?**
Play around with the kube create form, selecting HA, …
=> fix: Kube checkout bar copy 

packages/manager/.changeset/pr-9619-fixed-1693518126299.md, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Apache/Apache.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/GaugesSection.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/IconSection.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/LongviewDetailOverview.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/MySQL/MySQLLanding.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINX.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/NGINX/NGINXGraphs.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/Network/Network.tsx, packages/manager/src/features/Longview/LongviewDetail/DetailTabs/ProcessGraphs.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientHeader.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientInstructions.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClientRow.tsx, packages/manager/src/features/Longview/LongviewLanding/LongviewClients.tsx, packages/manager/src/features/Longview/shared/InstallationInstructions.tsx
- Added back spacing that disappeared due to changing from default to named imports when importing Grids in Longview files
- This is just a really quick solution just to get the styling back to what it used to be, will be working on cleaning up the styling and everything in the actual MUI refactor PRs after
- see comment on #9600 for more details 
- add spacing to any grids with the container prop that didn't have spacing specified 
| current prod  | what prod should look like   |
| ![image](https://github.com/linode/manager/assets/139280159/c213782e-916d-4fa0-85e1-0a3dca49bbf0) | ![image](https://github.com/linode/manager/assets/139280159/8bff6014-9675-490f-898c-5bd8001b06dc) |
1. `git checkout 84f1083 `to see how the styling previously looked, and compare this …
=> fix: Restore Longview styling to what it used to be

packages/manager/cypress/e2e/core/images/smoke-create-image.spec.ts, packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts, packages/manager/cypress/e2e/core/longview/longview.spec.ts
Another test resource clean-up PR! This stems from the changes made in #9529. This should fix some of the failures we've recently seen in these specs:
- `smoke-create-image.spec.ts`
- `backup-linode.spec.ts`
- `longview.spec.ts` 
In all 3 cases, the test failures are due to the tests creating Linodes but failing to clean up existing Linodes first.
We can rely on the automated test run to confirm that these 3 specs pass, indicating that these changes haven't broken the tests. However, manual testing may be required to confirm that the clean up actually functions as expected:
1. Create some test Linodes whose labels start with `cy-test-`
2. Navigate to the Linodes landing page in your browser, and stay there
3. Separately run one of the spec files above, and observe in your browser that the …
=> fix: Fix E2E failures caused by inadequate resource clean-up

packages/manager/.changeset/pr-9625-removed-1693588382719.md, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.test.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
- Removes VPC column from linode landing page table (see ticket and discussion for more details)
- related pr: https://github.com/linode/manager/pull/9485
** Kept logic for:
- Kept the validation/api changes from that PR, as those changes still reflect the API
- Keeping IP address label as 'Public IP address'
- kept the factories for linode configs as well, in case those are useful later down the road
- removed VPC column related logic from LinodeRow.tsx and updated tests
| ![image](https://github.com/linode/manager/assets/139280159/82410463-3ae0-4802-9f05-468e1397e36a) | ![image](https://github.com/linode/manager/assets/139280159/9ad19abf-c5a8-4d5c-9faf-c46debd46473) |
1. Navigate to Linode landing page and confirm that VPC column is gone, even …
=> change: [M3-7077] - Remove VPC column from Linodes landing page table

packages/manager/.changeset/pr-9606-upcoming-features-1693548349929.md, packages/manager/src/factories/types.ts, packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.test.tsx, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.test.tsx, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.test.tsx, packages/manager/src/features/Kubernetes/KubeCheckoutBar/KubeCheckoutBar.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeClusterSpecs.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePoolsDisplay.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx, packages/manager/src/features/Kubernetes/kubeUtils.test.ts, packages/manager/src/features/Kubernetes/kubeUtils.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/utilities/pricing/constants.ts, packages/manager/src/utilities/pricing/kubernetes.test.tsx, packages/manager/src/utilities/pricing/kubernetes.ts
This PR adds DC-specific pricing for Kubernetes node pools in the create flow and on the details page in add/resize drawers.
**With the mocks and feature flag on:**
Kube Create page:
- When a region **is selected**, the Node Pools table displays the hourly and monthly pricing corresponding to the selected region.
- When a region **is not selected,** the Node Pools table does not display rows, and instead displays a message: "Select a Region to view plans and prices."
- The Cluster Summary displays correctly calculated DC-specific pricing based on the Linode's region – both Node Pool line items and the total.
- When either a region or a pool is not selected, the cluster summary does not display prices and displays helper text indicating what selections must be made for pricing and cluster …
=> feat: [M3-7048] - Add DC-specific pricing for Kubernetes node pools

packages/manager/src/features/Billing/BillingPanels/BillingSummary/BillingSummary.tsx
- Caused by https://github.com/linode/manager/pull/9603
| ![Screenshot 2023-09-01 at 10 24 48 AM](https://github.com/linode/manager/assets/115251059/dc8e69d7-9b71-4ad5-a418-f6628296d99c) | ![Screenshot 2023-09-01 at 10 25 22 AM](https://github.com/linode/manager/assets/115251059/12028174-dc84-44a0-8375-4835932523fe) |
- Verify `/account/billing` looks good 🎨
=> fix: Billing Summary UI Regression from MUI Update

packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
- Fixes the alignment of the Select and Inputs in the Attach VLAN section on the Linode create page
| ![Screenshot 2023-09-05 at 2 48 37 PM](https://github.com/linode/manager/assets/115251059/de07697c-6623-4771-af99-35a13943ae6a) | ![Screenshot 2023-09-05 at 2 48 47 PM](https://github.com/linode/manager/assets/115251059/d9eda717-deb7-486f-beac-a73cb61cb7da) |
- Go to `/linodes/create` and verify that the Attach VLAN section looks like production
=> fix: Linode Crate - Attach VLAN - Grid Conatiner

packages/manager/cypress/e2e/core/linodes/rebuild-linode.spec.ts
Add Cypress tests for rebuilding Linodes.
- Add e2e tests to verify the flow of rebuilding a Linode.
`yarn cy:run -s "cypress/e2e/core/linodes/rebuild-linode.spec.ts"`
=> test: [M3-6553] - Add e2e tests for Linode Rebuild

packages/manager/src/components/PrimaryNav/PrimaryNav.styles.ts, packages/manager/src/components/Table/Table.styles.ts, packages/manager/src/features/Footer/Footer.tsx, packages/manager/src/foundations/themes/dark.ts, packages/manager/src/foundations/themes/light.ts, packages/manager/src/index.tsx
- Oh no! Our MUI theme isn't installed correctly! 😖
- The background color of the body is white ⚪️ in dark mode and it drives me absolutely nuts 🌰
- Set missing UI theme styles
- Add `<CssBaseline />` to mount base styles
https://github.com/linode/manager/assets/115251059/b3088fa1-0e78-484d-8dab-a52049db4ea4
https://github.com/linode/manager/assets/115251059/6e9aa519-b56e-48ce-9a07-38931fe054f9
- Check that the body's background in light mode is white
- Check that the body's background is in dark mode is gray
- Check for general style regressions
=> fix: MUI Theme Base CSS Styles

packages/manager/.changeset/pr-9639-fixed-1694031609043.md, packages/manager/src/features/Support/SupportTicketDetail/CloseTicketLink.tsx
This fixes a typo on the "Confirm Ticket Close" modal, displayed when closing a support ticket.
| ![Screenshot 2023-09-06 at 2 40 31 PM](https://github.com/linode/manager/assets/114753608/2fd18f30-4b36-4851-8f45-136ecddc0c8e) | ![Screenshot 2023-09-06 at 2 40 17 PM](https://github.com/linode/manager/assets/114753608/da18f68b-d9dd-455e-b2e0-1a7d5862e27b) |
1. Pull down this code and run it locally
2. In ReplyActions.tsx, change L34 to: `{true && <CloseTicketLink ticketId={ticketId} />}`
3. Go to http://localhost:3000/support/tickets/0 (mocks on)
4. Click "close this ticket" near the bottom of the screen to see this modal.
=> fix: [M3-7088] - Fix typo in `CloseTicketLink.tsx`

packages/validation/.changeset/pr-9641-fixed-1694095072428.md, packages/validation/src/linodes.schema.ts
Latest API release was responsible for exposing an issue with our validation schema when editing a linode config.
**NOTE**: I will write an e2e test to cover this issue in a subsequent PR
Our config interfaces properly types `interface.label` and `interface.ipam_address` as `string | null`, however our yup schema validation (which apparently never encountered a null value before) was throwing an error.
This is due to the fact that the API now seems to return a default public record (brand new Linode created with VLAN) in the interface array which has `null` `ipam_address` & `label`. 
⚠️ I am wondering if this is the desired behavior (because of this it is impossible to add a new public interface when editing - you will get an "Only one public interface per config is allowed." error). CC …
=> hotfix: [M3-7085] Edit VLAN config validation bug

packages/manager/.changeset/pr-9643-fixed-1694103276021.md, packages/manager/src/components/TableRow/TableRow.styles.ts, packages/manager/src/components/TableRow/TableRow.tsx
There was an issue on the longview processes table where the entire row was not highlighted, and the arrow was not in the correct place. This is important because the data to the right of the table is contingent on the selected row.
- We needed `selected={selected}` passed to the styled component
- Removed unnecessary styled components for the arrow
- Simplified how we create the css arrow
| ![Screenshot 2023-09-07 at 12 09 34 PM](https://github.com/linode/manager/assets/125309814/382f850b-fdb0-4bf3-809f-966daf48b8fd) | ![Screenshot 2023-09-07 at 11 59 28 AM](https://github.com/linode/manager/assets/125309814/6b9857bd-c2b4-48e3-8078-795da93e6326)  |
https://github.com/linode/manager/assets/125309814/c9689759-4ace-48e0-9b50-4ca7501cb3a2
1. Create …
=> fix: [M3-6950] - Restored longview active table rows and arrow

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/queries/databases.ts, packages/manager/src/queries/domains.ts, packages/manager/src/queries/firewalls.ts, packages/manager/src/queries/images.ts, packages/manager/src/queries/kubernetes.ts, packages/manager/src/queries/linodes/linodes.ts, packages/manager/src/queries/nodebalancers.ts, packages/manager/src/queries/volumes.ts, packages/validation/.changeset/pr-9641-fixed-1694095072428.md, packages/validation/CHANGELOG.md, packages/validation/package.json
- FIxes bug where restricted users would not have read-write permissions after they created a firewall
| <video src="https://github.com/linode/manager/assets/115251059/269ec1fd-364d-4962-aaca-6cd776a2760b" /> | <video src="https://github.com/linode/manager/assets/115251059/da0fb2a9-45fd-443c-bffb-be7743783289" /> |
- As a restricted user
- Create a firewall
- Verify that a GET to `/v4/profile/grants` happens
- Verify that you can edit that firewall immediately after creation
- As a non-restricted user
- Create a firewall
- Verify you **don't** see a GET to `/v4/profile/grants` (because it's unnecessary for an unrestricted user)
- Verify that you can edit that firewall immediately after creation
=> hotfix: [M3-7084] - Fix Restricted User Permissions after entity creation

packages/api-v4/src/aglb/certificates.ts, packages/manager/.changeset/pr-9616-upcoming-features-1693507025003.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-details-page.spec.ts, packages/manager/cypress/support/intercepts/load-balancers.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerCertificates.tsx, packages/manager/src/queries/aglb/certificates.ts, packages/validation/src/index.ts, packages/validation/src/loadbalancers.schema.ts
- Adds Create Certificate Drawer ✨
- Go to `http://localhost:3000/loadbalancers/1/certificates` with the **MSW on** and try to upload a certificate (you can use fake values)
- Nothing will really happen when you submit the form successfully because of the inherent nature of React Query and the MSW
- Check client side validation
=> feat: [M3-7029] - Add AGLB Certificate Create Drawer

packages/manager/.changeset/pr-9648-fixed-1694120022815.md, packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLanding.tsx
"Transfered" is not a word and should be "Transferred": https://dictionary.cambridge.org/dictionary/english/transferred. 
| ![Screenshot 2023-09-07 at 1 42 20 PM](https://github.com/linode/manager/assets/114685994/ae7452d8-5139-4ad6-b0df-db853015a062) | ![Screenshot 2023-09-07 at 1 51 09 PM](https://github.com/linode/manager/assets/114685994/42c636b6-8753-4fee-9d0e-32dbd1231922) |
2. **How to reproduce the issue (if applicable)?**
- Go to https://cloud.linode.com/nodebalancers with at least one nodebalancer on your account and observe the typo in the table.
4. **How to verify changes?**
- Go to http://localhost:3000/nodebalancers with at least one nodebalancer on your account and observe the corrected typo in the table.
=> fix: [M3-7092] - Typo in NodeBalancer landing table column header

packages/manager/.changeset/pr-9647-upcoming-features-1694186188307.md, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
- Add the ability to filter the subnets table by label or id in the VPC details page
- Display the number of subnets in parenthesis
https://github.com/linode/manager/assets/115299789/92875da1-a095-4558-80ea-975f960659fd
```
yarn test VPCSubnetsTable
```
Create some subnets in a VPC and try to filter by label/id. Ensure that table column sorting still works.
=> feat: [M3-6747] - Add filter subnets field

docs/development-guide/08-testing.md, packages/manager/cypress.config.ts, packages/manager/cypress/support/plugins/configure-file-watching.ts
Allows file watching and automatic reloading to be disabled via an environment variable (including in `.env`) when using the Cypress UI.
By default, Cypress's UI will automatically reload a test if any changes are made to the spec file which can be disruptive. This PR allows the behavior to optionally be disabled by setting the `CY_TEST_DISABLE_FILE_WATCHING` environment variable when running Cypress.
Developers can permanently set this behavior by adding it to their `.env` file.
- Reads `CY_TEST_DISABLE_FILE_WATCHING` environment variable to determine whether or not to disable file watching UI
- Adds docs for `CY_TEST_DISABLE_FILE_WATCHING`
1. Run `yarn cy:debug`
2. Run a test, and modify and save the corresponding test file; observe that Cypress reloads automatically
3. Close Cypress, …
=> change: Allow Cypress file watching to be disabled using environment variable

packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
This fixes Machine Image resources from accumulating on our test accounts, which has recently been causing some test failures.
In this case, the `cleanUp('images');` call was not deleting any of the desired Images because I forgot to call `authenticate()` first. In most cases this results in a 401, but the Images endpoint can be called without authentication (only returning public Images in that case) so the issue slipped under the radar.
(The test accounts have been cleaned up in the meantime)
We can rely on the automated tests for this.
=> fix: Resolve test account Machine Image resource accumulation by authenticating clean up requests

packages/manager/.changeset/pr-9663-upcoming-features-1694534723160.md, packages/manager/src/features/Billing/BillingPanels/BillingActivityPanel/BillingActivityPanel.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts, packages/manager/src/features/Billing/PdfGenerator/utils.test.ts, packages/manager/src/features/Billing/PdfGenerator/utils.ts, packages/manager/src/mocks/serverHandlers.ts
- Displays regions using their `label` and `id` in the DC specific pricing invoices. This ticket is a follow up to address some feedback from #9597. 
> [!important]
> The CSV does not contain the region `label` because I followed the current pattern of showing "pure" API data. (Notice how the dates are in the API's format)
- Verify that you see Region `label`s and `id`s on the Invoices with the `DC Specific Pricing` feature flag on
- Verify you **do not** see the region column when the flag is **off**
=> feat: [M3-7096] - Show Region `label` in addition to `id` on Invoices

packages/manager/.changeset/pr-9665-fixed-1694552506393.md, packages/manager/src/utilities/generate-cli.test.ts, packages/manager/src/utilities/generate-cli.ts
Fix metadata command when creating with the Linode CLI
| ![cli before](https://github.com/linode/manager/assets/115299789/92e4b8b8-3da8-4239-b887-4c0043cd1937) |  ![cli after](https://github.com/linode/manager/assets/115299789/44efc0f1-9ce4-48ac-8121-a8d833ff170d) |
| ![cli command before](https://github.com/linode/manager/assets/115299789/ad1b54cf-6eda-4db1-9303-32b367c357b0) | ![cli command after](https://github.com/linode/manager/assets/115299789/380672cd-b8db-478b-8db6-b10cdff00cf6) |
```
yarn test packages/manager/src/utilities/generate-cli.test.ts
```
- Go to `/linodes/create` and fill out the create form with a cloud-init compatible image and a metadata compatible region (e.g. Washington, DC)
- Enter some text in the User Data field of …
=> fix: [M3-7099] - Metadata CLI command

packages/manager/.changeset/pr-9666-upcoming-features-1694557714134.md, packages/manager/src/components/ActionsPanel/ActionsPanel.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/DeleteCertificateDialog.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerCertificates.tsx, packages/manager/src/queries/aglb/certificates.ts
- Adds a basic Delete Confirmation Dialog to the Certificate page
- The decision to use a basic confirmation dialog rather than a type-to-confirm has been confirmed by UX  ✅
- Go to `http://localhost:3000/loadbalancers/0/certificates`
- Try to delete a certificate
- Test the dialog for functionality and style
- **Note** The certificate won't actually disappear upon deletion because of how the MSW and React Query work
=> feat: [M3-7107] - Add AGLB Certificate Delete Dialog

docs/development-guide/05-fetching-data.md, docs/development-guide/06-performance.md, docs/development-guide/11-feature-flags.md, packages/api-v4/REACT.md
- Remove `React.FC` usage from our docs because we don't use `React.FC` anymore
- https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13
- Check diff and make sure I didn't mess up any examples in the docs
=> chore: Remove `React.FC` from docs examples

packages/manager/.changeset/pr-9667-fixed-1694576063628.md, packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/ContactInformation.tsx
- Fixes alignment issue with Billing Contact information on the Account page (`http://localhost:3000/account/billing`)
- Caused by https://github.com/linode/manager/pull/9603 and related to 
- https://github.com/linode/manager/pull/9623
- https://github.com/linode/manager/pull/9622
- It seems that MUI need `<Grid>` to be a child of `<Grid container>` rather than a `<Box>` so it can correctly apply Grid styles
| ![Screenshot 2023-09-12 at 11 27 35 PM](https://github.com/linode/manager/assets/115251059/43c6a79a-7a17-477f-8d7c-d25ac5a6d5d9) | ![Screenshot 2023-09-12 at 11 27 49 PM](https://github.com/linode/manager/assets/115251059/dcd8b99b-406c-4e40-b37f-de1fbba97ace) |
- Go to `http://localhost:3000/account/billing` and check the alignment and …
=> fix: Billing Contact UI Regression from by MUI Update

packages/manager/.changeset/pr-9670-upcoming-features-1694618602374.md, packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/src/components/DynamicPriceNotice.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx, packages/manager/src/constants.ts, packages/manager/src/features/Kubernetes/CreateCluster/HAControlPlane.tsx, packages/manager/src/features/Linodes/CloneLanding/Details.tsx, packages/manager/src/features/Linodes/LinodesCreate/utilities.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPSharing.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx, packages/manager/src/features/NotificationCenter/NotificationData/useFormattedNotifications.tsx, packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx, packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx, packages/manager/src/utilities/pricing/constants.ts, packages/manager/src/utilities/pricing/dynamicPricing.ts
This PR does some clean up for DC pricing and attempts to standardize language for "region" and "data center", both of which have been used throughout this project. As a result, it touches a few other components not directly related to DC pricing in order to rename consistently and avoid running into this problem again in another 6 months. 
Changes have been reviewed by UX and Docs.
- Use "region" rather than "Region" in notices, since the word is not at the beginning of a sentence or labeling a field.
- Use "data center" rather than "datacenter", since we've previously used both, but "datacenter" was used in copy much less often (only 3 places). 
- Remove the "How Data Center Pricing Works" docs link for now, since it was deemed redundant to display this link while the (temporary) info …
=> chore: [M3-7042] - DC-Specific Pricing Copy and Link Cleanup

packages/manager/.changeset/pr-9675-upcoming-features-1694635724766.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationAccordion.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/DeleteConfigurationDialog.tsx, packages/manager/src/queries/aglb/configurations.ts
- Adds AGLB Configuration delete dialog 🗑️
- Go to `http://localhost:3000/loadbalancers/0/configurations`
- Try deleting a Configuration
- Check the dialog for spelling, styles, and functionality
- ⚠️ Because of how the MSW and React Query work, the configuration delete action might seem a bit weird
=> feat: [M3-7108] - Add AGLB Configuration Delete Dialog

packages/manager/.changeset/pr-9683-fixed-1694731625764.md, packages/manager/src/features/Volumes/VolumeCreate/CreateVolumeForm.tsx, packages/manager/src/features/Volumes/VolumeDrawer/CreateVolumeForLinodeForm.tsx, packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx
This PR cleans up some copy for static Volume pricing ($0.10/GB per month) that was previously missed when creating a volume from a Linode's Storage tab. It also corrects a bug with the size field helper text related to when it should display.
These issues were found/fixed in #9601, but due to that PR's size and amount of refactoring, should be fixed in their own PR.  
| Prod  | This Branch   |
| ![Screenshot 2023-09-14 at 3 21 40 PM](https://github.com/linode/manager/assets/114685994/b2063822-0a90-4a59-a4ad-82a85dc88328) ![image](https://github.com/linode/manager/assets/114685994/8cda9896-671f-40aa-bbf2-de76c1d75cf3) | ![Screenshot 2023-09-14 at 3 30 01 PM](https://github.com/linode/manager/assets/114685994/c61180e6-f844-4eb2-bf99-ec4e4308a551) ![Screenshot …
=> fix: [M3-7138] - Fix Create Volume Drawer static pricing copy and misplaced helper text

packages/manager/.changeset/pr-9673-fixed-1694628742725.md, packages/manager/src/features/NodeBalancers/NodeBalancerActiveCheck.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerConfigPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerPassiveCheck.tsx
This PR fixes the alignment of the NB create flow panels and accordions. This one has bothered me for a while!
| ![Screenshot 2023-09-13 at 13 30 52](https://github.com/linode/manager/assets/130582365/9bda7e9c-cf2f-4970-bb68-bf8f92e9c1cc)| ![Screenshot 2023-09-13 at 14 07 00](https://github.com/linode/manager/assets/130582365/b0b902cd-bed2-4b78-9a73-2c961d7932b5) |
1. Navigate to nodebalancers/create
2. Check the alignment of all visible panels on desktop and mobile
3. Check the alignment of all conditionally rendered panels on desktop and mobile (toggle `Protocol` in Configurations &  `Type` in Active Health Checks etc)
=> fix: [M3-7117] - Fix style consistency issues with NodeBalancer create flow panels

CODEOWNERS
Small PR to add a CODEOWNER file needed for the auto assignment of PRs
There's not much to test, once merged it should trigger the rules configured in the repo's settings.
No need for a changeset here either.
=> feat: [M3-7141] Add codeowner file to monorepo root

packages/manager/.changeset/pr-9690-upcoming-features-1695050611174.md, packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/src/components/DynamicPriceNotice.tsx, packages/manager/src/components/SelectRegionPanel/RegionHelperText.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.test.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/utilities/pricing/dynamicPricing.ts, packages/manager/src/utilities/pricing/linodes.test.ts, packages/manager/src/utilities/pricing/linodes.ts
- Updates the DC specific pricing notices on Linode Create, Kubernetes Create, and NodeBalancer Create.
- No notice is shown by default (this is new)
- A new **warning** notice shows when you select a region that has DC specific pricing
- No changes to Linode Clone warning (you should see `The selected region has a different price structure` if you clone to a region with different pricing)
| ![Screenshot 2023-09-15 at 5 08 04 PM](https://github.com/linode/manager/assets/115251059/b80e9f95-935b-4202-8b99-cbd5ed9ab793) | ![Screenshot 2023-09-15 at 5 07 56 PM](https://github.com/linode/manager/assets/115251059/3d8a85c6-ca2d-412e-bf52-58abe062749d) |
| ![Screenshot 2023-09-15 at 5 07 28 PM](https://github.com/linode/manager/assets/115251059/6d5adc20- …
=> change: [M3-7145] - Update DC Specific Pricing Notices

packages/manager/.changeset/pr-9692-upcoming-features-1695054097678.md, packages/manager/src/components/Dialog/Dialog.tsx, packages/manager/src/components/TooltipIcon.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayDialog.test.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayDialog.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayDialogHeader.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayUsage.test.tsx, packages/manager/src/components/TransferDisplay/utils.test.tsx, packages/manager/src/components/TransferDisplay/utils.ts
This PR improves the copy and typography in the Network Transfer Display Dialog. 
- Modifies copy
- Adds header tooltips
- Modifies size of typography elements
| ![Screenshot 2023-09-18 at 12 12 26 (2)](https://github.com/linode/manager/assets/130582365/e90e9d80-eb39-41a1-b8be-4a29f6d1765a) | ![Screenshot 2023-09-18 at 12 06 32](https://github.com/linode/manager/assets/130582365/5d80f47a-daf4-489a-8df1-93444575ad58) |
|  | ![Screenshot 2023-09-18 at 12 10 08 (2)](https://github.com/linode/manager/assets/130582365/f4950c45-1698-4540-9872-dbe3a1fb4c9d) |
**Setup**
1. Enable the DC-Specific Pricing flag
2. Enable MSW
Testing Steps
1. Navigate to /linodes
2. Click on the "Monthly Network Transfer Pool" under the linodes table list
3. Confirm copy, …
=> feat: [M3-7144] - MNTP Dialog Updates for DC-specific pricing

packages/manager/cypress/e2e/core/linodes/migrate-linode.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/cypress/support/intercepts/linodes.ts
Add new cypress tests for Linode migration dialog DC pricing
- Add e2e tests to verify the DC pricing information in Linode migration dialog.
```
yarn cy:run -s "cypress/e2e/core/linodes/migrate-linode.spec.ts"
```
=> test: [M3-7068] - Add integration tests for Linode migration dialog DC-specific pricing

packages/manager/.changeset/pr-9693-upcoming-features-1695157943571.md, packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts, packages/manager/src/features/Events/eventMessageGenerator.ts
Changes the copy of the notification message in the `Events` landing page to account for the ability to add `NodeBalancers` to `Firewalls`. 
- Replaces `device` for the appropriate device type (`Linode` or `NodeBalancer`) in the message displayed in the `Events` landing page.
| ![m3-7017-before](https://github.com/linode/manager/assets/119514965/ae5708cf-385c-4919-9f09-bb27c26cd8f7) | ![m3-7017-after](https://github.com/linode/manager/assets/119514965/5ee485d4-b763-465c-9171-1e3db74889f6) |
1. On you `localhost` instance, switch over to the `Dev` environment via the CloudManager dev tools.
2. On a existing `Firewall` entity add at least one instance of both `Linode` and `NodeBalancer`.
3. Validate the event notification messages in the `Events` …
=> feat: [M3-7017] - Update firewall events

packages/manager/.changeset/pr-9697-fixed-1695133545193.md, packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts, packages/manager/src/components/DownloadCSV/DownloadCSV.tsx, packages/manager/src/components/Link.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx, packages/manager/src/features/Account/index.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, packages/manager/src/features/Billing/InvoiceDetail/index.ts, packages/manager/src/features/Billing/index.tsx
Small PR to improve accessibility and markup on the Billing Detail page since those were bothering me and throwing warnings in the console.
- Provide accessibility to the back button link
- Improve markup of the Download CVS Link
- Update imports/exports
This PR should contain no visual regression and should be tested against any.
**Local Setup**:
Pull and run code locally 
**Steps**:
1. Navigate to /account/billing/invoices/{invoiceId}
2. Confirm there's no warning in the console about Link Accessibility
3. Confirm there's no visual regression (no difference from the production page)
4. Confirm the Download CSV link works as expected
=> fix: [M3-7155] - Link Accessibility & Markup on Billing Detail page

packages/manager/.changeset/pr-9698-tech-stories-1695221027793.md, packages/manager/src/features/Profile/AuthenticationSettings/SecurityQuestions/QuestionAndAnswerPair.tsx, packages/manager/src/features/Profile/AuthenticationSettings/TPAProviders.styles.ts
- Cleans up 2️⃣ console errors on `http://localhost:3000/profile/auth`
- Don't forward the `edit` prop to `StyledQuestionContainer`'s `Box` 
- Don't forward the `isButtonEnabled` prop to `StyledButton`'s `Button`
| ![Screenshot 2023-09-19 at 11 28 26 AM](https://github.com/linode/manager/assets/115251059/1bc4c54f-8c09-4886-8cd6-2a47c78250eb) | ![Screenshot 2023-09-19 at 11 28 04 AM](https://github.com/linode/manager/assets/115251059/a1a60f69-70ef-4393-9aae-fac86452cbb1) |
- Go to `http://localhost:3000/profile/auth` and observe the console
- On `develop`, you should console errors
- On this PR, you should see no console errors
- Verify the provider buttons still work (click Github and Google)
- Verify you can still edit a security question
=> fix: [M3-7156] - `TPAProviders` invalid prop on a DOM element console errors

packages/manager/.changeset/pr-9705-fixed-1695242987904.md, packages/manager/package.json, packages/manager/src/App.test.tsx, packages/manager/src/App.tsx, packages/manager/src/LinodeThemeWrapper.tsx, packages/manager/src/components/Button/Button.test.tsx, packages/manager/src/components/HighlightedMarkdown/HighlightedMarkdown.tsx, packages/manager/src/components/LandingHeader/LandingHeader.test.tsx, packages/manager/src/env.d.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeConfigDrawer.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromImageContent.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromStackScriptContent.test.tsx, packages/manager/src/index.tsx, packages/manager/src/utilities/testHelpers.tsx, packages/manager/src/utilities/theme.ts
- Fixes bug where Highlight.js theme would not switch
- The the would not switch because both css files were loaded at the same time. The solution involves switching out the css when the theme is changed.
- Made `LinodeThemeWrapper` a named export ✏️
- Moves Highlight.js logic from the `LinodeThemeWrapper` to the `HighlightedMarkdown` so that the css is only imported when `HighlightedMarkdown` is imported. (This helps us seperate concerns and defer loading until it is really needed)
- Removed unnecessary uses of `LinodeThemeWrapper` in some unit tests 🚫
- Removed weird `setTimeout` logic that did nothing 🚫
| ![Screenshot 2023-09-20 at 3 30 24 PM](https://github.com/linode/manager/assets/115251059/e0286274-5783-4682-9508-092c5e79a6c3) | …
=> fix: [M3-7105] - Highlight.js Theme Switching

packages/manager/.changeset/pr-9702-fixed-1695158299608.md, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts, packages/manager/src/features/Billing/PdfGenerator/utils.ts, packages/manager/src/mocks/serverHandlers.ts
> [!important]
> I recommend checking the internal ticket to see context of this 🪲
Fixes unnecessary wrap in invoice and payment PDFs that caused some `id` numbers to be partially cut off and improves general positioning
- Do not enforce a maxWidth in the `addTitle` function
- Replaced hard-coded table start position with dynamic start position 🎉
|   ![Screenshot 2023-09-19 at 4 49 28 PM](https://github.com/linode/manager/assets/115251059/7bac73b4-fc9e-4a21-9bb5-e310464f6a23)  |  ![Screenshot 2023-09-19 at 5 01 32 PM](https://github.com/linode/manager/assets/115251059/799fc9e7-4174-4874-9fd2-70e5934b3827) |
|  ![Screenshot 2023-09-19 at 4 49 17 PM](https://github.com/linode/manager/assets/115251059/72f980d9-9c11-411d-901a-bd539f028e16)   | …
=> fix: [M3-7008] - Invoice and Payment `id` wrapping in generated PDFs

packages/manager/.changeset/pr-9700-fixed-1695156150613.md, packages/manager/src/utilities/analytics.ts
This pr fixes this codeQL warning and type the _satellite object a bit better
- Escape expression in `eventPayload` replaced values
- Ensure all occurrences of `|` are replaced (as opposed to one before)
**Setup**:
1. Pull code locally
2. Follow the local analytics [debugging setup](https://github.com/linode/manager/blob/develop/docs/development-guide/13-coding-standards.md#locally-testing-page-views--custom-events-andor-troubleshooting)
**Steps**:
1. Navigate to /linodes
2. Open any action menu and observe the analytic event in the console
3. Modify the [sendLinodeActionEvent](https://github.com/linode/manager/blob/develop/packages/manager/src/utilities/analytics.ts#L30) method to include one or several `|` (pipe) characters
4. Confirm they all get removed from the event payload
=> fix: [M3-7078] codeQL warning with analytics.ts

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx
Metadata is now in General Availability so we need to remove the beta chip from the Add User Data accordion
| ![image](https://github.com/linode/manager/assets/115299789/56d844ed-8321-438f-bebd-063282cded99) | ![image](https://github.com/linode/manager/assets/115299789/126a1844-733e-403a-a3a1-1207671a028d) |
- Go to `/linodes/create`
- Select a cloud-init compatible image (there will be a note icon to the right)
- Select a region that supports Metadata (e.g. Washington, DC)
- Scroll down to the bottom and check the Add User Data accordion
=> Release v1.103.0 - release → staging

packages/manager/cypress/e2e/core/databases/create-database.spec.ts, packages/manager/cypress/e2e/core/databases/delete-database.spec.ts, packages/manager/cypress/e2e/core/databases/update-database.spec.ts
This mocks the `databases` feature flag in our DBaaS tests so that the state of the Launch Darkly flag does not impact the tests. This should fix the failures we've been getting since this value changed in the Development environment.
- Mock `databases` feature flag in Cypress DBaaS tests
We can rely on the automated tests for this. If the DBaaS tests pass, then we know this PR will accomplish its purpose.
=> test: Mock DBaaS feature flag in Cypress tests

packages/manager/.changeset/pr-9710-upcoming-features-1695410168923.md, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx, packages/manager/src/features/VPCs/utils.test.ts, packages/manager/src/features/VPCs/utils.ts
Ensure that a linode row inside the subnets table only shows the IP specific to that subnet
Add subnetId to SubnetLinodeRow props, and find the interface associated with that specific subnet
| ![image](https://github.com/linode/manager/assets/139280159/708441ee-b957-45f6-a03f-dfdcdfc5ed32) | ![image](https://github.com/linode/manager/assets/139280159/32dc5dfa-3bdb-4b0d-9e32-2b537f6877a5) |
MSW example: 
**How to verify changes?**
- Using the MSW:
- Most linodes will have a blank VPC IPv4 column because the mock subnet_id of the mock linode's configs' interfaces don't match the subnet that the linode corresponds to. However, you can go to
- `packages/manager/src/factories/linodeConfigInterfaceFactory.ts` line 28 and try to put in specific …
=> feat: [M3-7157] - Only show IPv4s specific to a linode-subnet relationship on VPC details page

packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts
Add Cypress integration tests for Cloud Manager to confirm DC-specific pricing UX when creating a Kubernetes cluster.
- Confirms that DC-specific pricing notices and prices are present in the LKE create form when the feature flag is on.
- Confirms that the plan table shows a message in place of plans when a region is not selected.
- Confirms that the cluster summary create button is disabled until a plan and region selection are made.
- Confirms that HA helper text updates dynamically to display pricing when a region is selected.
- Confirms that the pricing warning notice is visible for a region with DC-specific pricing and not visible otherwise.
1. **How to run Unit or E2E tests?**
```
```
=> test: [M3-7101] - Add integration tests for Kubernetes Create DC-specific pricing

packages/manager/src/components/BarPercent/BarPercent.tsx, packages/manager/src/components/BarPercent/index.ts, packages/manager/src/components/TransferDisplay/LegacyTransferDisplay.tsx, packages/manager/src/components/TransferDisplay/TransferDisplayUsage.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/LinodeDiskRow.tsx, packages/manager/src/features/NotificationCenter/NotificationData/RenderProgressEvent.tsx
- Fix some console errors and general issues with our `BarPercent` component 🛠️
- Fix `narrow` prop getting passed to the underlying component
- Fixed `undefined` className
- Use **named exports** instead of default exports ✏️
| ![Screenshot 2023-09-25 at 10 47 49 AM](https://github.com/linode/manager/assets/115251059/893676fb-8d99-4939-8c1b-61d1f336f982)  | ![Screenshot 2023-09-25 at 10 48 31 AM](https://github.com/linode/manager/assets/115251059/8f496fd8-c94a-416d-8c26-0cbd5c8f0ac6) |
| ![Screenshot 2023-09-25 at 10 47 18 AM](https://github.com/linode/manager/assets/115251059/e1b3035b-9235-4bba-be8d-cd63b17397f4) | ![Screenshot 2023-09-25 at 10 46 55 AM](https://github.com/linode/manager/assets/115251059/06455332-6bda-4de1-9612-3a00f267508c) | …
=> fix: [M3-7174] - Fix `BarPercent` console errors and other improvements

packages/manager/.changeset/pr-9720-added-1695748436771.md, packages/manager/src/features/Volumes/VolumeCreate.tsx, packages/manager/src/features/Volumes/VolumeDrawer/SizeField.tsx, packages/manager/src/features/Volumes/Volumes.tsx, packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
- Adds a `LandingHeader` to be consistent with other create pages
- Adds a `DocumentTitleSegement` so that "Create a Volume" shows in the browsers document tab title while on the Volume Create page
- Adds a `DocumentTitleSegement` so that "Volumes" shows  in the browsers document tab title while on the Volumes Landing empty state
- Renames `CreateVolumeForm.tsx` ➡️ `VolumeCreate.tsx` to match our other create pages
- Moves errors notices into the `Paper`
| ![Screenshot 2023-09-26 at 10 27 30 AM](https://github.com/linode/manager/assets/115251059/9a2acce7-c65f-4112-9cfc-255024f7073a) | ![Screenshot 2023-09-26 at 10 27 05 AM](https://github.com/linode/manager/assets/115251059/fad42cd4-72cc-4f93-856e-140855f42ad5) |
| ![Screenshot 2023-09-26 at 10 …
=> chore: [M3-7187] - Improvements to Volumes Create

packages/manager/.changeset/pr-9726-fixed-1695827222025.md, packages/manager/src/components/ActionsPanel/ActionsPanel.test.tsx, packages/manager/src/components/ActionsPanel/ActionsPanel.tsx, packages/manager/src/features/Domains/CloneDomainDrawer.tsx, packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.test.tsx, packages/manager/src/features/Profile/SSHKeys/DeleteSSHKeyDialog.tsx
This PR aimed to fix a bug with a missing button label in the Delete SSH Key dialog and ended up fixing another related bug in the Clone Domain drawer.
- Adds the missing `Delete` label to the primary action button in the SSH key delete dialog
- Makes `label` a required, not an optional, prop for `ActionButtonProps`
- Inadvertently fixes another bug, where the `Cancel` button appears invisible in the Clone Domain drawer because it was also missing a label
- Adds unit test for `DeleteSSHKeyDialog` component and updates unit test for `ActionPanel` component.
| ![image](https://github.com/linode/manager/assets/114685994/421f3f63-d72b-493b-b87f-6cfe4ff459d8) | ![image](https://github.com/linode/manager/assets/114685994/f64a99ba-e904-4669-b2d6-910884c …
=> fix: [M3-7191] - Missing primary and secondary action button labels in Delete SSH Key dialog and Clone Domain drawer

packages/manager/.changeset/pr-9721-fixed-1695755881914.md, packages/manager/src/features/Users/UsersLanding.tsx
- Fixes styles on the `http://localhost:3000/account/users` page 🎨
- Removes **tons** of unused styled 🗑️
| ![Screenshot 2023-09-26 at 3 12 18 PM](https://github.com/linode/manager/assets/115251059/6dcd4db4-7bb4-448c-897d-7e533018dcc4) | ![Screenshot 2023-09-26 at 3 12 25 PM](https://github.com/linode/manager/assets/115251059/63ed7e78-6a31-46a1-b6be-ebb1044d8877) |
- Go to `http://localhost:3000/account/users` and check the UI in general
- Check the styles and positioning of the `Add A User` button
=> fix: [M3-7192] - Account Users `Add A User` Button Alignment

packages/manager/.changeset/pr-9722-fixed-1695762935283.md, packages/manager/src/features/Databases/DatabaseDetail/AddAccessControlDrawer.tsx
- The loading state is applied to both the primary button and the cancel button. It should only be applied to the primary button
- Caused by https://github.com/linode/manager/pull/9341
| ![Screenshot 2023-09-26 at 5 03 15 PM](https://github.com/linode/manager/assets/115251059/f926e7bd-b7ae-47c6-9f69-6c3256070392) | ![Screenshot 2023-09-26 at 5 03 38 PM](https://github.com/linode/manager/assets/115251059/d59630b5-8236-4903-bbc5-9548ad27ae27) |
1. Create a Database (or use an existing one)
2. Go to the Database details page
3. Edit access controls
4. Save Changes and watch closely  👀
5. Verify **only** the `Update Access Controls` button shows a loading spinner, **not both**
=> fix: [M3-7196] - Database Access Drawer Incorrect Loading State

packages/manager/src/features/Account/Maintenance/MaintenanceTable.tsx
- Caused by https://github.com/linode/manager/pull/9697 I think
- Fixes the `Download CSV` button on the `http://localhost:3000/account/maintenance` page
- This `Download CSV` is unique compared to others because it lazily fetches data when the user presses the button. That's why there is a weird ref involved.
| Clicking download does nothing | Clicking download downloads the CSV |
| <video src="https://github.com/linode/manager/assets/115251059/e47b8976-d752-4943-81c7-38636b3f269e" /> | <video src="https://github.com/linode/manager/assets/115251059/38890e7c-9822-446c-baac-c0f0a0294866" /> |
- Go to `http://localhost:3000/account/maintenance` and test the `Download CSV` functionality
- Turn on the MSW if you need to mock some maintenance events
=> fix: CSV Download on Account Maintenance

packages/manager/src/components/DownloadCSV/DownloadCSV.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx
This PR fixes the download CSV button on the invoice detail page. 
Two different PRs touched this file for this release: https://github.com/linode/manager/pull/9697 & https://github.com/linode/manager/pull/9687
My initial fix had wrapped the Download button as a span inside the CSVLink (slightly better semantically) but https://github.com/linode/manager/pull/9687/files#diff-8d0889ab4c29796d8405ff92e8a926c9b6d672b073b7703931ee9cbdcdf97a91L42 broke that by removing the wrapping. 
Since it seems clearer to everyone to use the ref and the onClick behaviour I reverted to the original implementation which allowed to require the onClick prop to be passed.
1. Navigate to /account/billing/invoices/{invoice-Id}
2. Confirm the "Download CSV" **button** downloads the file properly and is accessible …
=> [Fix]: Invoice detail CSV button

packages/manager/.changeset/pr-9735-upcoming-features-1696265642529.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRoutes.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRouteDialog.tsx, packages/manager/src/queries/aglb/routes.ts
- Adds a basic AGLB Route Delete Dialog
- Turn the MSW **on**
- Go to `http://localhost:3000/loadbalancers/0/routes`
- Test the Delete Dialog
- Check spelling ✏️
- Check styles 🎨
- Check functionality 🎮
- Verify a `DELETE https://api.linode.com/v4beta/aglb/0/routes/24` API call happens on delete
- Verify existing routes get invalidated upon delete (You should see a `GET https://api.linode.com/v4beta/aglb/0/routes?page=1&page_size=25` API call)
=> feat: [M3-7109] - Add AGLB Delete Route Dialog 

packages/manager/.changeset/pr-9739-fixed-1696019997998.md, packages/manager/src/components/Dialog/Dialog.tsx
You've been annoyed by this on our modals?
Look no further, this fix is for you.
The title prop on our modals creates more trouble than it's worth. It adds html tooltip (a proper HTML `title` feature) that follows you around and often obfuscate content or distracts the user.
It does not add any particular accessibility feature (known to me) and does not seem to be standard at all:
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/
We already have the necessary features described in the [accessibility standards docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) so there's no need to continue defining them and require them on those components.
- Prevent forwarding the title prop to the html
1. Open …
=> fix: [M3-7208] Prevent forwarding the title prop to the markup

packages/manager/.changeset/pr-9745-tech-stories-1696272112150.md, packages/manager/src/initSentry.ts
- We're disabling Sentry performance tracing because we are running into plan limits and this Sentry feature isn't crucial to our workflow.
(We still use Sentry for logging errors)
> [!NOTE]
> These steps just confirm error reporting is still working as expected
- Make sure you have `REACT_APP_SENTRY_URL` defined in your env
- Throw an error in a component
- Go to that component and make Cloud Manager crash 
- Verify you see the error in sentry
=> chore: [M3-7224] - Disable Sentry Performance Tracing

packages/manager/.changeset/pr-9743-upcoming-features-1696347149626.md, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx
previous PR here: https://github.com/linode/manager/pull/9742
Switched to point to develop
Previously, the dismissible banner on the VPC details page was global, so dismissing it once dismissed this for every VPC. Added a unique identifier to the preference key so that the banner is unique for each VPC
- Using the dev environment:
- Create at least two VPCs
- Assign at least one linode to each of the VPCs
- Confirm that dismissing the banner that pops up on one of the VPC details page (image above) does not dismiss the banner on the other VPC's detail page page
- Using MSW:
- Close the dismissible banner on one of the mock VPC's detail pages
- Confirm the banner remains closed on that detail page
- Navigate to another VPC's detail page and confirm the banner still appears
=> fix: [M3-7226] - Make Reboot Linodes dismissible banner on VPC Details page unique

scripts/changelog/changeset.mjs
Resolve codeQL alert due to not escaping backslashes
- Updated regex pattern to check for any number of backslashes before a \` when replacing instances
looks like the alert for the changeset script (last alert in the before picture) is gone! (I installed the codeQL extension on VSCode + set it up and ran it). Note: the other alerts aren't part of this PR. They aren't showing up in the Security tab, and seem to be for build files, so I'm unsure if we'll need to create tickets for them (?)
| ![image](https://github.com/linode/manager/assets/139280159/262f0552-19d6-4378-ad64-6b3c87f3421e) | ![image](https://github.com/linode/manager/assets/139280159/08677180-80fd-4496-a11a-0f2989b90d18) |
(this doesn't actually affect the changeset, just the …
=> fix: [M3-7079] - Resolve "Incomplete string escape or encoding" alert in changeset.mjs

packages/manager/.changeset/pr-9752-tech-stories-1696367849962.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeStorage/CreateDiskDrawer.tsx
In order to fix up our TextField component, we need to **not** allow it to be used as a select component. This PR replaces the TextField Select in CreateDiskDrawer with a modern alternative like Autocomplete
| ![Screenshot 2023-10-03 at 5 07 18 PM](https://github.com/linode/manager/assets/115251059/b34177fe-ffc6-4280-aa25-92e7f60b0f2e) | ![Screenshot 2023-10-03 at 5 07 48 PM](https://github.com/linode/manager/assets/115251059/c5e70ea0-a562-476d-b4d9-74fdbd9f1795) |
- Create a Linode
- Go to the Linode's details page
- Go to the `Storage` tab
- Shutdown the Linode
- Delete all of the Linode's disks
- Click `Add Disk`
- Test the `Filesystem` select functionality
- Verify the POST post works and sends the correct filesystem type in the payload
=> chore: [M3-7231] - Migrate Filesystem TextField Select to Autocomplete

packages/manager/.changeset/pr-9731-fixed-1695931370886.md, packages/manager/src/components/Drawer.tsx
This PR fixes an edge case where very long `Drawer` titles (in this case, due to long firewall names) overlap the `Drawer` close (X) icon.
Note: we fixed a similar issue before with Dialogs, not Drawers.
- Adds right margin to the drawer title to prevent overlap with close icon
- Reorders props to resolve eslint perfectionist warnings
- Fixes a typo that appears in the component's Storybook documentation
| ---- | ---- |
| ![longdrawertitle_prod](https://github.com/linode/manager/assets/114685994/0fd5e514-92c0-4ac3-9594-9e303feaddcd) | ![Screenshot 2023-10-04 at 6 56 05 AM](https://github.com/linode/manager/assets/114685994/3574a681-fd39-4757-8b02-30be3fe6e0a3) |
- Create a firewall with a long …
=> fix: [M3-7072] - Long drawer titles overlapping close icon

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/DisabledRegions.tsx, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.test.tsx, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/RegionSelect.tsx, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/disabledRegions.tsx, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Volumes/VolumeCreate.tsx
This PR adds a fake Tokyo region menu item with a tooltip to our RegionSelect to show users that Tokyo is now disabled
- Adds a fake menu item with a tooltip if user does not have the `tokyo-enable` flag on their account
- Improve the API for declaring disabled regions
- Puts the change behind the feature flag (`soldOutTokyo`) => currently `off` as a prod flag
- Adds a `Sold Out Tokyo` mock entry in dev settings (can be removed later but helpful to test quickly)
**Note**: the code could be greatly improved given more time. The goal here remains to implement the proper functionality and UI for a hotfix
**Note**: OBJ isn't available for **anyone** in Tokyo 
The following scenari should be tested:
- User should see the Tokyo region menu item
- User should not see this option as disabled
- …
=> hotfix: [M3-7234] - Disable Tokyo in RegionSelect

packages/manager/CHANGELOG.md, packages/manager/cypress/e2e/core/billing/billing-invoices.spec.ts, packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/src/factories/types.ts, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, packages/manager/src/features/Billing/InvoiceDetail/InvoiceTable.tsx, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts, packages/manager/src/features/Billing/PdfGenerator/utils.test.ts, packages/manager/src/features/Billing/PdfGenerator/utils.ts, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.test.tsx, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/utilities/pricing/constants.ts, packages/manager/src/utilities/pricing/dynamicPricing.test.ts, packages/manager/src/utilities/pricing/dynamicPricing.ts
There are two issues with DC-specific pricing:
1. on past invoices, the Region column for invoice items is not backfilled due to how this is data is collected and populated on the back-end, which may cause confusion for users who have a region column with no data
2. monthly prices (previously all integers, displayed as `$n/mo`) are now displaying inconsistently -- most often with one decimal place, but in at least one instance (resize node pool drawer, 2GB linode) with way too many decimal places
- Fixes issue 1 by hiding the Region column on invoices before DC-specific pricing was implemented. This month's invoice and invoices going forward should include region data for invoice items.
- Fixes issue 2 by displaying monthly prices returned from the API as decimals (at this point, only …
=> hotfix: DC-specific pricing -- monthly price decimals and invoice region column

docs/CONTRIBUTING.md, packages/api-v4/.changeset/README.md, packages/manager/.changeset/README.md, packages/validation/.changeset/README.md, scripts/changelog/utils/constants.mjs
Add 'Tests' to Changeset types as per frontend cafe discussion and updated relevant docs
Run `yarn changeset` and confirm `Tests` is listed under the changeset types to select from. Create a changeset of that type, don't commit it, and run `yarn generate-changelogs` to confirm a changelog is generated with a 'Tests' section.
=> chore: [M3-7243] - Add 'Tests' to Changeset types

packages/api-v4/src/aglb/certificates.ts, packages/api-v4/src/aglb/types.ts, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts, packages/manager/src/factories/aglb.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/Certificates.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/aglb/certificates.ts, packages/validation/src/loadbalancers.schema.ts
Add an edit drawer for AGLB certificates.
- Creates the Edit Certificate drawer with dynamic fields depending on certificate type
- Adds the useLoadBalancerCertificateMutation
- Adds a unit test for `EditCertificateDrawer` component
- Updates the MSW `PUT` endpoint for `*/v4beta/aglb/:id/certificates/:certId` to return a `downstream` cert in addition to the existing `ca` certs.
| Service Target Certificates  | TLS Certificates   |
|  ![Screenshot 2023-10-05 at 3 30 54 PM](https://github.com/linode/manager/assets/114685994/8a9f3bf7-d7e3-4d1c-83d9-5c702f2a4683) | ![Screenshot 2023-10-05 at 3 30 38 PM](https://github.com/linode/manager/assets/114685994/8bc5e7e0-6c44-48d3-b742-874ba2526012) |
- Check out this PR.
- `yarn dev`
- …
=> feat: [M3-7160] - Add AGLB "Edit Certificate" drawer

packages/manager/.changeset/pr-9751-upcoming-features-1696367790874.md, packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts, packages/manager/src/components/Autocomplete/Autocomplete.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx, packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx, packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.tsx, packages/manager/src/features/VPCs/VPCCreate/SubnetNode.test.tsx, packages/manager/src/features/VPCs/VPCCreate/SubnetNode.tsx, packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.styles.ts, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
Address Showcase feedback
VPC Create
- Added remove X icon to default subnet label input.
- Changed button text from “Add Subnet” to “Add Another Subnet”.
- Button text is “Add a Subnet” when there are no subnets added.
VPC Details - Subnets
- Added `Unassign Linode` inline button to the Subnets table row which will open the Unassign Linodes drawer with the Linode pre-selected and the Linode select hidden.
- Added helper text to the Unassign Linode drawer per the UX mocks and hide the helper text if the drawer is opened via inline Unassign Linode
- Updated Subnets table empty state text
- Pluralize Subnet action menu item text “Assign Linode” -> “Assign Linodes” and “Unassign Linode” -> “Unassign Linodes”.
| VPC Create  | VPC Details - Subnets  |
| <video …
=> feat: [M3-7119] - Showcase VPC feedback

packages/manager/.changeset/pr-9746-fixed-1696274683693.md, packages/manager/src/features/NodeBalancers/NodeBalancersLanding/NodeBalancersLandingEmptyState.tsx
Fixed the top spacing for the NodeBalancer empty state
- Added top padding to NodeBalancer empty state
</details>
<details>
<summary>Before</summary>
| Domains  | NodeBalancer   |
| ![Screenshot 2023-10-02 at 3 21 57 PM](https://github.com/linode/manager/assets/139489745/f052977d-ab75-487b-ad8a-29fd00a1966b) | ![Screenshot 2023-10-02 at 3 22 22 PM](https://github.com/linode/manager/assets/139489745/0aaa1129-201b-47ea-b4e0-614bd8e51cae) |
</details>
<details>
<summary>After</summary>
| Domains  | NodeBalancer   |
| ![Screenshot 2023-10-02 at 3 20 07 PM](https://github.com/linode/manager/assets/139489745/48c0f0a5-25c3-4af4-8052-2e2488ca04aa) | ![Screenshot 2023-10-02 at 3 20 30 PM](https://github.com/linode/manager/assets/139489745/14feb808-9772-4a …
=> fix: [M3-6931] - Fixed top spacing for NodeBalancer empty state

docs/PULL_REQUEST_TEMPLATE.md
- Contains some fixes for the new PR template (https://github.com/linode/manager/pull/9747)
- Fixes bullet points for the `As an Author I have considered 🤔` section
- Removes unnecessary `<br>`s
Not sure now to best preview this
| before | after |
|   ![Screenshot 2023-10-06 at 2 51 13 PM](https://github.com/linode/manager/assets/115251059/a6a9b7d6-7617-49d4-809b-380081cb5653)     |   ![Screenshot 2023-10-06 at 2 50 56 PM](https://github.com/linode/manager/assets/115251059/24ca92ad-cc7e-4013-af01-f04152a65667)   |
=> change: PR Template Updates

packages/manager/.changeset/pr-9780-fixed-1696969213915.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferContent.tsx
Currently, on the Linode Details > Network tab, we display Monthly Network Transfer bar percents, labeled with a legend that looks like the following:
debian-us-sea (0.26 GB - 1%)
Global Pool Used (1 GB) - 1%
We should format these two legend labels consistently:
debian-us-sea (0.26 GB - 1%)
**Global Pool Used (1 GB - 1%)**
- The percentage of the Global/DC-specific pool used is formatted in the same way that the percentage of the pool that the linode has used: [label] ([number] GB - [percent]%)
|![Screenshot 2023-10-10 at 12 50 56 PM](https://github.com/linode/manager/assets/114685994/36326751-306b-4ab4-888b-7a1084dba2d0) | ![Screenshot 2023-10-10 at 1 08 25 PM](https://github.com/linode/manager/assets/114685994/b7cf725f-66cc-4482-a365-dd3a884b4 …
=> fix: [M3-7259] - Fix inconsistent display of % in Linode Details MNTP legend

packages/manager/.changeset/pr-9753-changed-1696626338930.md, packages/manager/src/features/StackScripts/stackScriptUtils.ts
We received a report that the CS:GO app is defunct because the sequel is out. removing pending updates. 
- comment out CS:GO marketplace app to remove from front-end
=> change: [OCA-1218] - Comment out CS:GO app pending update

packages/manager/.changeset/pr-9776-fixed-1696956017237.md, packages/manager/src/features/Support/Hively.stories.tsx, packages/manager/src/features/Support/Hively.tsx
Feedback Smiley Ratings should be easily clickable, however it overlaps with the "How did I do?" link
- `margin` is overwritten due to being in a `Stack`, so switching to `padding` which is the more better approach.
- Added Storybook
| <img width="246" alt="Screenshot 2023-10-10 at 12 31 40 PM" src="https://github.com/linode/manager/assets/125309814/5a291cb3-cc2e-4184-ac60-909904e56145"> | <img width="400" alt="Screenshot 2023-10-10 at 12 36 54 PM" src="https://github.com/linode/manager/assets/125309814/009211d6-8b44-44c2-a529-37a3350cfcb7"> |
- Run storybook `yarn storybook`
- Go to http://localhost:6006/?path=/docs/components-hively--documentation
- Observe that there's no more overlapping happening in component
=> fix: [M3-7256] - Added spacing for Hively external link

packages/manager/.changeset/pr-9748-tech-stories-1696350216805.md, packages/manager/src/MainContent.tsx, packages/manager/src/components/ActionsPanel/ActionsPanel.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/index.tsx, packages/manager/src/features/Users/CreateUserDrawer.tsx, packages/manager/src/features/Users/UserDeleteConfirmationDialog.tsx, packages/manager/src/features/Users/UserDetail.tsx, packages/manager/src/features/Users/UserPermissions.styles.ts, packages/manager/src/features/Users/UserPermissions.tsx, packages/manager/src/features/Users/UserPermissionsEntitySection.styles.ts, packages/manager/src/features/Users/UserPermissionsEntitySection.tsx, packages/manager/src/features/Users/UserProfile.styles.ts, packages/manager/src/features/Users/UserProfile.tsx, packages/manager/src/features/Users/UsersActionMenu.tsx, packages/manager/src/features/Users/UsersLanding.tsx, packages/manager/src/features/Users/index.tsx
MUI v5 migration for `Users`
- Ran `tss-react` codemod on `src > features > Users`.
- Replaced default export with named export.
- Removed `index.tsx` file.
The work on this PR is contained to only migrate the styling to the newer API.
1. Verify the functionality around the `Users` feature works as expected.
2. Look for any UI defects or regressions in the `Users` landing page.
3. Visit `account/users` and validate adding new users and changing the `User Permissions`.
=> refactor: [M3-6287] - MUI v5 `Features > Users`

packages/manager/.changeset/pr-9788-changed-1697134985443.md, packages/manager/src/components/AccessPanel/AccessPanel.tsx, packages/manager/src/components/LabelAndTagsPanel/LabelAndTagsPanel.tsx, packages/manager/src/components/TabbedPanel/TabbedPanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromImage.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeRebuild/RebuildFromStackScript.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/ImageAndPassword.tsx, packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx
- **Finally** fixes error placement on the Linode Create page 🎉 (This is long overdue)
- Moves Notice style errors **below** headings
- Uses Text Field `errorText` for errors that relate to TextFields
| ![Screenshot 2023-10-12 at 11 25 34 AM](https://github.com/linode/manager/assets/115251059/6efc8b49-7f96-492a-8036-6d83e506d84c) | ![Screenshot 2023-10-12 at 11 25 44 AM](https://github.com/linode/manager/assets/115251059/2e605ce5-83fe-4c4b-954f-0936188faf37) |
| ![Screenshot 2023-10-12 at 11 22 24 AM](https://github.com/linode/manager/assets/115251059/ba324e87-de69-4b46-aab9-e0b9a1bced1c) | ![Screenshot 2023-10-12 at 11 25 03 AM](https://github.com/linode/manager/assets/115251059/798de232-05b3-4558-bfbc-49c09216308c) |
| ![Screenshot 2023-10-12 …
=> change: [M3-7266] - Improve Linode Create Error Placement

packages/api-v4/src/nodebalancers/types.ts, packages/manager/.changeset/pr-9733-upcoming-features-1697041470658.md, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx
- Added the firewall panel to the create NodeBalancer flow so users can assign a firewall as soon as a NodeBalancer is created.
- Added the firewall panel to the create NodeBalancer flow
- Added helper text to the firewall panel
- Cleaned up and added "Firewall Assigned" to Checkout Summary
| ![Screenshot 2023-09-29 at 10 17 12 AM](https://github.com/linode/manager/assets/139489745/c28b6a04-f8c4-463d-9f2c-41228049645e) | ![Screenshot 2023-09-29 at 10 18 34 AM](https://github.com/linode/manager/assets/139489745/9ae0aa5c-acab-4ad5-a1be-84396cb5f071) |
| ![Screenshot 2023-09-29 at 10 20 18 AM](https://github.com/linode/manager/assets/139489745/fc525519-1dfa-407b-a149-f146ace3042f) | ![Screenshot 2023-09-29 at 10 20 49 …
=> feat: [M3-7021] - Added Firewall panel to create NodeBalancer flow

packages/manager/.changeset/pr-9782-tests-1697147463647.md, packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
This fixes a consistent failure that occurs upon any re-attempt of the LKE create tests. If the LKE test fails on its first attempt for any reason, the Launch Darkly feature flag mocks will fail to be set in any of the reattempts, leading the tests to fail each time. This addresses the issue by setting up the mocks inside of the test instead of in a `before` hook.
Additionally, I set the tests to use Kubernetes v1.27 and clean up Linodes in addition to LKE clusters prior to running the tests, but the mock changes are the real fix here.
- Move LKE feature flag mocks to resolve failure on reattempts
- Use Kubernetes 1.27 for LKE create E2E tests
- Clean up Linodes before running LKE create test
This is challenging to reproduce because the failure …
=> test: Fix Cypress LKE create test failures stemming from reset mocks

packages/manager/.changeset/pr-9777-tests-1696958372039.md, packages/manager/cypress/support/setup/defer-command.ts
This improves error handling when a Linode API error or validation error occurs during a Cypress test by adding additional information to the command log. This is intended to help troubleshoot test failures.
(Meta: Not sure if this is better suited as `test` or `refactor` type, happy to change this to `refactor` if we think that's more applicable)
- Detect common error types (Linode API error, generic Axios error, Linode schema validation error) and add additional information to the error message when Promise rejects in `cy.defer`
| **Linode API error:** | |
| <img width="391" alt="Linode API Error Before" src="https://github.com/linode/manager/assets/97627410/1337fdc4-0b9d-4762-9ee9-29f15007031c"> | <img width="375" alt="Linode API Error After …
=> test: Improve Cypress error messages when Linode API errors occur

packages/manager/.changeset/pr-9791-fixed-1697461463011.md, scripts/changelog/changeset.mjs
We're getting a [codeQL warning](https://github.com/linode/manager/security/code-scanning/30) for "Shell command built from environment values" for not properly handling the variable in the shell command. 
> Dynamically constructing a shell command with values from the local environment, such as file paths, may inadvertently change the meaning of the shell command. Such changes can occur when an environment value contains characters that the shell interprets in a special way, for instance quotes and spaces. This can result in the shell command misbehaving, or even allowing a malicious user to execute arbitrary commands on the system.
> **Recommendation**
> If possible, use hard-coded string literals to specify the shell command to run, and provide the dynamic arguments to the shell …
=> fix: [M3-7081] - Quote variable in changeset shell command

packages/manager/.changeset/pr-9801-tests-1697547109194.md, packages/manager/cypress/e2e/core/databases/create-database.spec.ts, packages/manager/cypress/e2e/core/databases/delete-database.spec.ts, packages/manager/cypress/e2e/core/databases/update-database.spec.ts, packages/manager/cypress/support/constants/databases.ts, packages/manager/cypress/support/intercepts/databases.ts
This fixes the DBaaS tests by mocking the request to the DBaaS node types endpoint.
We can rely on the automated tests, but to run the tests locally you can use this command:
```bash
yarn cy:run -s "cypress/e2e/core/databases/create-database.spec.ts,cypress/e2e/core/databases/update-database.spec.ts,cypress/e2e/core/databases/delete-database.spec.ts"
```
=> test: Fix DBaaS tests after API update

packages/manager/.changeset/pr-9787-upcoming-features-1697145963212.md, packages/manager/cypress/e2e/core/vpc/vpc-create.spec.ts, packages/manager/src/components/EnhancedSelect/variants/RegionSelect/disabledRegions.tsx, packages/manager/src/features/VPCs/VPCCreate/VPCCreate.tsx
- For the VPC Create page, rather than showing all regions, we only show the regions that support VPCs in the region select
- NOTE: Hiding the disabled Tokyo region from this page as well, since 1) Tokyo doesn't support VPCs yet, and 2)  the tooltip for disabled Tokyo region mentions using the Osaka region instead, but Osaka also doesn't support VPCs and doesn't show up
|![image](https://github.com/linode/manager/assets/139280159/9eae0d04-d6a1-4530-868d-e0b2786b0346) |![image](https://github.com/linode/manager/assets/139280159/5eea12cb-e598-4bff-83d3-bc67971b1fe4) |
- Using the dev environment, with vpc admin tags, navigate to the VPC Create page
- Verify that the region select on the VPC Create page only contains the following regions (these …
=> feat: [M3-7252] - Only show regions that support VPCs in VPC Create page

packages/manager/.changeset/pr-9798-upcoming-features-1697553282360.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
Bug from https://github.com/linode/manager/pull/9709
On the prod env, we were unable to edit a config due to the config interface being deleted. This was due to the `regionHasVPCs` variable being coupled with `regionHasVLANS` in the if statement to delete config interfaces. The fix was to handle VPCs and VLANs separately.
Note: Linode details have been obfuscated
| <video src="https://github.com/linode/manager/assets/115299789/5d61c3ae-131c-4c66-b5e9-bde536a90bda" /> | <video src="https://github.com/linode/manager/assets/115299789/39d40d03-53b5-4a85-85a8-c8d1aba4a20b" /> |
- Point to the prod environment
- Go to a Linode's details page and click on the `Configurations` tab
- Click the edit button and scroll down to the Networking section
- …
=> fix: [M3-7270] - Edit Linode VLAN config interface

packages/api-v4/src/regions/types.ts, packages/manager/.changeset/pr-9815-fixed-1697665414544.md, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx
Filter regions selection on database create by capability to prevent user selecting a region that doesn't support dbaas.
- Add capability "Managed Databases" to list of capabilities
- Filter the regions by the "Managed Databases" capability.
- Go to create a database and verify Chennai and Osaka are not listed in the regions selection
=> fix: [UIE-6961]: Only show regions that support Databases on the Database Create page

packages/manager/.changeset/pr-9808-fixed-1697722511987.md, packages/manager/src/MainContent.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
Fix the Dbaas menu flickering on page load when waiting for API call.
- Wait for API call to finish before checking for error.
- User with restricted access - no billing access
- Login in as restricted user
- Refresh page and see the Dbaas menu appear then disappear on user interaction
- Menu does not appear for restricted user during page load
=> fix: [UIE-6952] - DBaaS menu flickers on page load

packages/manager/.changeset/pr-9816-tests-1697660159676.md, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.test.tsx
- Reworks some things about `ConfigureForm.test.tsx` to make it work in Vitest  and makes other minor improvements
- Uses built in options to set the feature flag
- Reduces `jest.mock` usage (uses MSW to mock the needed API call)
- Removes `jest.isolateModules` usage
- Improves mock data so that the test won't break if the underlying factory changes
|   ![Screenshot 2023-10-18 at 4 07 33 PM](https://github.com/linode/manager/assets/115251059/853ac8f4-34c1-4699-90d0-ab734acdaf4c)     |     ![Screenshot 2023-10-18 at 4 05 47 PM](https://github.com/linode/manager/assets/115251059/e53d80cd-ce1a-4220-998a-dde41fb29119)  |
```sh
yarn test ConfigureForm
```
=> test: [M3-7283] - Make `ConfigureForm.test.tsx` Vitest compatible 

packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts
Add new cypress tests for NodeBalancer creation tiered pricing.
- Add e2e tests to verify the DC pricing information in NodeBalancer creation flow.
```
yarn cy:run -s "cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts"
```
=> test: [M3-7071] - Add Cypress integration tests for NodeBalancer Create DC-specific pricing

packages/manager/cypress/support/constants/databases.ts, packages/manager/cypress/support/util/regions.ts
- Fixes Database Create e2e test now that we filter out some regions in the Database Create Region select
-  https://github.com/linode/manager/pull/9815
- The fix involves filtering out regions that do not support `Managed Databases` when choosing a region at random
- Adds `options` to the `chooseRegion` function
- Verify you have `MANAGER_OAUTH` setup in your `packages/manager/.env`
- `yarn cy:debug`
- Run the `create-database.spec.ts` test
- Verify the test passes
- Check CI e2e run for relevant failures
=> test: Fix Database Create e2e test region selection

packages/manager/.changeset/pr-9812-fixed-1697639234272.md, packages/manager/src/features/Images/ImageUpload.tsx
- In Images Create > Upload Image (http://localhost:3000/images/create/upload), reduce the spacing above and below the Linode CLI help text
- Decreased spacing above and below the Linode CLI help text
| ![Screenshot 2023-10-18 at 10 31 52 AM](https://github.com/linode/manager/assets/139489745/c31e32ba-16bb-44fb-a459-cb8669e1a745) | ![Screenshot 2023-10-18 at 10 28 38 AM](https://github.com/linode/manager/assets/139489745/9bd08d57-8e39-494a-93b8-298b49c57c09) |
- There are no prerequisites
- Navigate to https://cloud.linode.com/images/create/upload
- Scroll down to the bottom of the page and confirm the spacing above and below the …
=> fix: [M3-7104] - Images create > upload image > reduce space above and below Linode CLI help text

packages/manager/.changeset/pr-9813-added-1697655032681.md, packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx, packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx, packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx, packages/manager/src/utilities/pricing/dynamicPricing.ts
Object storage has hardcoded prices throughout the codebase. The service is a flat $5/month. Beyond the first 250GB storage and 1TB outbound transfer, it's and $0.02/GB/month. We need to update this due to pricing changes for DC-specific overage rates and clarification that outbound transfer is *not* added to DC-specific pools, only the global pool.
The only time a user sees the Enable Object Storage notice is the first time they create a bucket or access key and must opt-in to the service. 
- For this reason, we are adding region-specific overage pricing to the Create Bucket drawer.
Note: Access keys are not currently tied to regions.
- Overage prices on the Create Bucket drawer reflect accurate prices for dynamic region pricing.
- Copy updates are made in the Enable Object Storage modal …
=> feat: [M3-6973] - Add DC-specific pricing Object Storage overages

packages/manager/.changeset/pr-9823-fixed-1697820563300.md, packages/manager/src/MainContent.tsx, packages/manager/src/components/SideMenu.tsx, packages/manager/src/constants.ts, packages/manager/src/features/Footer.tsx, packages/manager/src/features/Footer/Footer.tsx
- Cleans up and fixes our Footer styles 🎨
- Fixes footer for `xs` viewports
- Uses less `Grid`
- Cleans up unnecessarily complex styles 
- Added nice animation
| ![Screenshot 2023-10-20 at 12 37 54 PM](https://github.com/linode/manager/assets/115251059/649f2db0-66bb-448e-b9b9-30b75500c31a) | ![Screenshot 2023-10-20 at 12 37 47 PM](https://github.com/linode/manager/assets/115251059/b6846895-f6aa-4cc6-9c43-64a5067d3751) |
| ![Screenshot 2023-10-20 at 12 37 33 PM](https://github.com/linode/manager/assets/115251059/7a606d58-84b1-4c31-8470-c70246d203d6) | ![Screenshot 2023-10-20 at 12 37 20 PM](https://github.com/linode/manager/assets/115251059/d90d7545-ea41-4884-afba-dd644e6da806) |
https://github.com/linode/manager/assets/115251059/7c70cad1-1432-499 …
=> fix: [M3-7298] - Improve Footer Styles

packages/api-v4/.changeset/pr-9824-upcoming-features-1697827003419.md, packages/api-v4/src/linodes/types.ts, packages/api-v4/src/vpcs/types.ts, packages/manager/.changeset/pr-9824-upcoming-features-1697827056392.md, packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts, packages/manager/src/factories/linodeConfigInterfaceFactory.ts, packages/manager/src/factories/subnets.ts, packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx, packages/manager/src/features/Linodes/LinodeEntityDetail.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.test.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.test.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx, packages/manager/src/features/VPCs/utils.test.ts, packages/manager/src/features/VPCs/utils.ts
This PR updates interface and subnet return object in the API package to make sure they match the updated API spec, and fixes any type errors that result from that.
- Updated interface and subnet object types
- Updated subnets and linodeConfigInterface factories
- Fixed type errors in VPC and Linode related files/tests
- Update array lengths in [subnet related factories](https://github.com/linode/manager/pull/9824/files#diff-9eeb348b3f8ccff161e226783ae206137ffde28c9d7f0a9ad5212589bf24ac46) due to a a memory issue
Because these changes had to do with the subnet/interface return object, not the create payloads, there shouldn't be any validation package issues. 
There should be no visual changes.
- Use the dev environment and make sure your account …
=> change: [M3-7227] - Update VPC-related API types in accordance with new API changes

packages/manager/.changeset/pr-9807-tests-1697570775779.md, packages/manager/cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts, packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts, packages/manager/cypress/support/intercepts/firewalls.ts, packages/manager/cypress/support/intercepts/linodes.ts, packages/manager/cypress/support/util/regions.ts
This cleans up the Cypress Firewall tests by implementing newer testing patterns.
- Remove calls to `cy.intercept`, replacing them with calls intercept and mocking utils
- Use `ui` helpers where applicable, reduce number of calls to `cy.get()`
- Adds a couple assertions related to migration warnings shown to and accepted by the user
```bash
yarn && yarn build && yarn start:manager:ci
```
```bash
yarn cy:run -s "cypress/e2e/core/firewalls/create-firewall.spec.ts,cypress/e2e/core/firewalls/delete-firewall.spec.ts,cypress/e2e/core/firewalls/migrate-linode-with-firewall.spec.ts,cypress/e2e/core/firewalls/update-firewall.spec.ts"
```
=> tests: [M3-6219] - Clean up Cypress Firewall tests

packages/manager/.changeset/pr-9835-fixed-1698158982152.md, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.styles.ts, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx, packages/manager/src/features/Kubernetes/CreateCluster/index.tsx, packages/manager/src/features/Kubernetes/index.tsx
We had wrong label styles on the CreateCluster form, resulting in faux bolds, line height and letter spacing. Was very prominent on safari which has more font rendering fidelity than chrome.
- Fix/remove erroneous styles
- Add dividers and spacing to the form to be consistent with other create flows (example: DB create)
- Move styles to own files and cleanup import/exports
| ![Screenshot 2023-10-24 at 10 43 21](https://github.com/linode/manager/assets/130582365/be3696c7-a26c-4075-b4a3-27b91403ed3d) | ![Screenshot 2023-10-24 at 10 43 29](https://github.com/linode/manager/assets/130582365/9024f0c1-c434-45c6-946d-1ea664980fb5) |
- pull code loacally
- see current rendering at https://cloud.linode.com/kubernetes/create
- Navigate to …
=> fix: [M3-6889] CreateCluster styles

packages/manager/.changeset/pr-9827-upcoming-features-1698091273479.md, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.test.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx, packages/manager/src/features/Linodes/LinodesCreate/SelectAppPanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromAppsContent.tsx
- Add dropshadow and update maxHeight to list to indicate scrolling is necessary
- Fix dropshadow UI bug on Safari for market place apps
- See [this comment here](https://github.com/linode/manager/pull/9687#discussion_r1335967787) for some background behind this issue
|![image](https://github.com/linode/manager/assets/139280159/07e30b69-fdc1-4147-b6d6-c2915fb9d132) |![image](https://github.com/linode/manager/assets/139280159/396d723d-0e20-4f34-9dec-9768daa8fed7) |
- checkout this branch
- yarn storybook --> RemovableSelectionsList
- Marketplace fix: navigate to the marketplace apps on **safari**
- For the removable selections list
- verify that the default example now cuts off the 11th item in the list. 
- verify …
=> change: [M3-7182] - Update RemovableSelectionsList default maximum height to cut off the last list item

packages/manager/.changeset/pr-9833-tests-1698335199212.md, packages/manager/cypress/e2e/core/databases/update-database.spec.ts, packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts
Add test coverage to check disk metrics parameters.  
Add test coverage for low disk size event.
Add new cypress assertions to check disk metrics parameters "Total disk size" and "Used disk size" added to the UI. 
Add test coverage for low disk size event.
- ...
- ...
yarn cy:run -s "cypress/e2e/core/databases/update-database.spec.ts"
yarn cy:run -s "cypress/e2e/core/notificationsAndEvents/events.spec.ts"
=> test: [DBASS1-574] - Adding test coverage for disk metrics added to UI.

packages/manager/.changeset/pr-9834-changed-1698111109868.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Based on conversations with a couple of stakeholders (see ticket), it was pointed out that some tweaks needed to be made with regards to when and where `public` interfaces are included in the Linode Create payload based on the various configurations of VPC, VLAN, and Private IP a user might choose in the Create flow.
This PR makes changes so that:
1. VPC assigned (no VLAN) + "Private IP" add-on is selected --> a `public` interface is added into the `interfaces[1]` slot
2. VLAN assigned (no VPC) --> retain existing behavior (`public` interface added in the `interfaces[0]` slot)
3. VPC and VLAN assigned + "Private IP" add-on selected --> a `public` interface is added into the `interfaces[2]` slot
If a VPC is assigned, the VPC interface will always occupy the `interfaces[0]` slot. 
- Tweak …
=> fix: [M3-7285] – Tweak when and where `public` interfaces are included in Linode Create payload

packages/manager/.changeset/pr-9785-fixed-1697059201989.md, packages/manager/.changeset/pr-9837-fixed-1698172001079.md, packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
Migrated the Linode dropdown in Firewall Landing > Create Firewall drawer from the LinodeSelect component to the Autocomplete component 
- Migrated Linode Dropdown from LinodeSelect to the Autocomplete component
- Fixed NodeBalancer dropdown incorrect highlighted options
- Added successful toast notification for firewall creation
| <video src="https://github.com/linode/manager/assets/139489745/bd2e37c0-6c5e-4493-97df-260dad4647dc" /> | <video src="https://github.com/linode/manager/assets/139489745/ac8bad92-c559-4595-8266-fcf0a8681063" /> |
- Checkout the feature branch (feature/firewall-nodebalancer)
- Navigate to http://localhost:3000/firewalls/create
- Select a NodeBalancer, the correct NodeBalancer is created, but all of the options are …
=> fix: [M3-7313] - Migrated Linode dropdown to Autocomplete in Firewall Landing > Create Firewall drawer

packages/manager/.changeset/pr-9851-upcoming-features-1698695391804.md, packages/manager/src/features/VPCs/VPCDetail/SubnetUnassignLinodesDrawer.tsx
Saw this little bug when looking into Cassie's pr #9818 and thought I'd just put up a quick fix for it. Will create a ticket + add it to this PR's header once I'm done writing this pr
- When removing linodes from our 'Linodes to unassign' list, make sure their configs also get removed so that we don't accidentally still unassign them
| <video src="https://github.com/linode/manager/assets/139280159/f1b62a67-2cd6-4de3-9fba-00513d8ca364" /> | <video src="https://github.com/linode/manager/assets/139280159/be0bc4c1-fe2c-47a9-a0ae-a83b1153df34" /> |
- Using the dev env and with vpc flags
- OR with vpc flags on the prod account (this should be working now, though it wasn't for …
=> fix: [M3-7348] - Only unassign linodes in the 'Linodes to be Unassigned from Subnet' list for Subnet Unassign Drawer

packages/manager/.changeset/pr-9854-fixed-1698764756434.md, packages/manager/.changeset/pr-9854-fixed.md, packages/manager/src/features/OneClickApps/oneClickApps.ts
fixes hyper link 404s in cloud manager marketplace pane for Main Concept docs.
corrects links to match docs naming scheme here: https://github.com/linode/docs/commit/bd25fe4fbd088c0ca7bf3db3d91f2bffeecdc776
=> fix: [OCA-1229] - Correct links to Main Concept and Simplex docs

packages/api-v4/src/aglb/loadbalancers.ts, packages/api-v4/src/aglb/types.ts, packages/manager/.changeset/pr-9856-upcoming-features-1698773808066.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerBasicCreate.tsx, packages/manager/src/features/LoadBalancers/index.tsx, packages/manager/src/queries/aglb/loadbalancers.ts, packages/validation/src/loadbalancers.schema.ts
- For AGLB Alpha, users won't be able to configure their AGLB during creation so we must have a "basic" create flow
- This PR adds a _basic_ flow that is controlled by a feature flag. This will allow us to very easily toggle between the create flows for development
- Lots of temporary code is created to support this "basic" creation but it allows us to continue to develop the main product
- Adds new Basic Create Page
- Adds `aglbFullCreateFlow` feature flag
- Test that toggling `aglbFullCreateFlow` shows two different create flows
- Verify the only thing in the payload is a `label` for the basic create flow
=> feat: [M3-7353] - Add AGLB Basic Create Flow

packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts
Add new cypress assertions for backup prices in Linode create flow.
- Add new cypress assertions to check backup prices when creating a Linode.
```
yarn cy:run -s "cypress/e2e/core/linodes/create-linode.spec.ts"
```
=> test: [M3-7189] - Add assertions for backup prices in Linode Create flow

packages/manager/.changeset/pr-9859-upcoming-features-1698850082776.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts
Add a new dcGetWell flag for the feature and add an item to developer settings
You can pull the code locally and condition the rendering of an element with `flags.dcGetWell` and toggle the "DC Get Well" developer setting.
=> upcoming: [M3-7212] - Add dcGetWell flag

packages/api-v4/.changeset/pr-9860-upcoming-features-1698852464578.md, packages/api-v4/src/account/account.ts, packages/api-v4/src/account/types.ts, packages/manager/.changeset/pr-9860-upcoming-features-1698852576816.md, packages/manager/src/factories/accountAvailability.ts, packages/manager/src/factories/index.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/accountAvailability.ts
- Adds api-v4 endpoints and types for DC Get Well
- Adds react queries and mock data for DC Get Well endpoints 
This should have no impact (yet) on customer facing codebase.
- Review endpoints, spelling, and types -- cross reference endpoints and types to API specification on internal ticket
- If you'd like to test the MSW, you can use the react queries in some file and check the network calls
=> upcoming: [M3-7213] - DC Get Well endpoints, queries, and mock data

packages/manager/.changeset/pr-9846-added-1699023355495.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts, packages/manager/cypress/support/intercepts/load-balancers.ts
Add new integration tests for Akamai Global Load Balancer certificate delete flow.
- Add new cypress test cases to check deleting AGLB certificates.
```
yarn cy:run -s "cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts"
```
=> test: [M3-7133] - Add integration tests for AGLB certificate delete flow

packages/manager/.changeset/pr-9866-upcoming-features-1698872557988.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
Fixes some bugs in the Linode Create and Add/Edit Config flows
- fixes error text incorrectly displaying in Linode Add/Edit config flow
- prevents clearing subnet section when clicking on currently assigned VPC
**Note: spoke with UX, we will be hiding the Create VPC link -- as a result, hiding the text in the Add/Edit config flow. Have also changed the copy for the Add/Edit config flow if no VPCs exist in the linode's region -- see comment
| <video src="https://github.com/linode/manager/assets/139280159/c0ffe75e-712a-4a26-9b9f-7d620305a5a8" /> | <video src="https://github.com/linode/manager/assets/139280159/1424e4de-4b04-4ac3-8d8b-daddc0d0e66f" /> |
| …
=> fix: [M3-7340] - Fix error text displaying in Linode Add/Edit config flow and prevent clearing subnet section when clicking on currently assigned VPC

packages/manager/.changeset/pr-9857-upcoming-features-1698788535458.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCEditDrawer.tsx
Clear VPC errors in the Linode Create and VPC Edit drawer flow after the input has changed
| <video src="https://github.com/linode/manager/assets/115299789/0a429b4b-f5d1-4e53-9aff-416a4f6f935e" /> | <video src="https://github.com/linode/manager/assets/115299789/ff973e4d-3fb3-4030-9422-0c05766b25c1" /> |
| <video src="https://github.com/linode/manager/assets/115299789/f6d6e70e-e415-4a0d-94c5-0fdd2049ab5e" /> | <video src="https://github.com/linode/manager/assets/115299789/ea9ecf3a-7204-4d43-9a5f-0a9740400dbc" /> |
- Point to the dev env and ensure your account has vpc customer tags
- Create two VPCs if you don't already have one
Linode Create
- Be on the develop branch or go to the remote dev environment
- Go to `/linodes/create` and select a …
=> feat: [M3-7235, M3-7236] - VPC UX error feedback

packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/ScheduleSettings.test.tsx
- Fixes `ScheduleSettings.test.tsx`  that broken due to Daylight savings time ending
- Makes the unit test use `utc` for asserting the time
- Adds a DST-compatible unit test for `America/New_York`
- `yarn test ScheduleSettings.test.tsx`
- Or verify Github Actions passes
=> fix: `ScheduleSettings.test.tsx` failing due to daylight savings time ending

packages/api-v4/.changeset/pr-9878-upcoming-features-1699304438796.md, packages/api-v4/src/regions/regions.ts, packages/api-v4/src/regions/types.ts, packages/manager/.changeset/pr-9878-upcoming-features-1699304466665.md, packages/manager/src/factories/regions.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/regions.ts
- Adds api-v4 endpoints and types for Sold Out Plans
- Adds react queries and mock data for Sold Out Plans
This should have no impact (yet) on customer facing codebase.
Verification steps
- Review endpoints, spelling, and types -- cross reference endpoints and types with these two endpoints: [one](https://www.linode.com/docs/api/regions/#regions-availability-list) and [two](https://www.linode.com/docs/api/regions/#region-availability-view)
- If you'd like to test the MSW, you can use the react queries in some file and check the network calls. You can also cross reference the shape of the data returned by the MSW with the data returned from the actual queries
- Verify `/regions/:regionId` endpoint still works as expected (changed `regionID` to `regionId` for the input name)
*Check all that …
=> upcoming: [M3-7365] - New endpoints, query, types and mock data for Sold Out Plans

packages/manager/.changeset/pr-9861-fixed-1698947793164.md, packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx
Temporarily remove sorting on "Region" column due to API error 400 Bad request. Once the backend is fixed we can add back sorting on "Region" column. All other columns can be sorted without API error.
- Change TableSortCell to TableCell on Region column
- Navigate to https://cloud.linode.com/databases and click on the "Region" column to sort.
- To unblock go to https://cloud.linode.com/profile/settings?preferenceEditor=true
and remove "databases-order" from sort keys
- Navigate to https://cloud.linode.com/databases the "Region" column is no longer sortable.
=> fix: [UIE-6977] - Remove sort on region column on DBaaS landing page

packages/manager/.changeset/pr-9880-tests-1699311124062.md, packages/manager/.changeset/pr-9880-upcoming-features-1699311064702.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-certificates.spec.ts, packages/manager/cypress/support/intercepts/load-balancers.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.tsx, packages/validation/.changeset/pr-9880-upcoming-features-1699311177462.md, packages/validation/src/loadbalancers.schema.ts
This PR does two things, because fixing the validation was necessary for writing a complete integration test that confirmed all input errors were handled gracefully.
1. Add Cypress integration tests to confirm the UI flow for AGLB certification editing works as expected.
2. Provide form validation to prevent a user from being able to edit a certificate and provide a blank label.
Integration tests in `load-balancer-certificates.spec.ts` test the following:
- User can edit certificates from the AGLB certificate page (route: /loadbalancers/:id/certificates)
- Certificates page updates to reflect edited certificates
- Cloud Manager handles user input errors (e.g. empty or invalid fields/selections) gracefully
- Cloud Manager handles server errors (e.g. HTTP 500 responses from the API) …
=> test, upcoming: [M3-7134, M3-7314] - Add integration test for AGLB Edit Certificate flow and improve form validation

packages/manager/.changeset/pr-9883-tech-stories-1699388327594.md, packages/manager/src/features/NodeBalancers/NodeBalancerConfigNode.tsx, packages/manager/src/mocks/serverHandlers.ts
Now that our `Chip` component support the `color` prop, we can remove some one-off styling 🎉
- Removes one-off styled `Chip` in favor of using Chip directly with the `color` prop
- Adds mocks to help you test this PR
| ![Screenshot 2023-11-07 at 3 10 30 PM](https://github.com/linode/manager/assets/115251059/f490e102-04a2-42b3-bfe4-a390d83e6b79) | ![Screenshot 2023-11-07 at 3 08 05 PM](https://github.com/linode/manager/assets/115251059/ce3a0014-d6be-435f-8034-96d67de9ab28) |
|![Screenshot 2023-11-07 at 3 10 20 PM](https://github.com/linode/manager/assets/115251059/4b324ef5-03e6-47ce-b00c-8e9a57185583) | ![Screenshot 2023-11-07 at 3 07 55 PM](https://github.com/linode/manager/assets/115251059/21d2a8c3-8182-4977-9cd8-b122130622c8) |
- Run `yarn` in …
=> refactor: NodeBalancer Config Node - Remove one-off-styled `Chip`

packages/manager/.changeset/pr-9888-fixed-1699476376459.md, packages/manager/src/features/Linodes/LinodesLanding/LinodeActionMenu.tsx
We're missing the URL param on the Linode detail action menu clone item, resulting in the region select not getting the default value.
- Add missing region ID param to Linode Detail clone action menu item
| ![Screenshot 2023-11-08 at 15 39 21](https://github.com/linode/manager/assets/130582365/a1056469-60cc-47e0-a4a5-b4cf8cfedd7c) | ![Screenshot 2023-11-08 at 15 38 59](https://github.com/linode/manager/assets/130582365/536ee0c0-908f-4a83-b509-237717ef1d30) |
- Pull and run code locally
- On production, navigate to a linode detail and click on the "Clone" action menu item in the detail header
- Notice the region select …
=> fix: [M3-7389] - Add missing region ID param to Linode Detail clone action menu item

packages/manager/.changeset/pr-9818-added-1699024035326.md, packages/manager/cypress/e2e/core/volumes/attach-volume.spec.ts, packages/manager/cypress/e2e/core/vpc/vpc-linodes-update.spec.ts, packages/manager/cypress/support/constants/vpc.ts, packages/manager/cypress/support/intercepts/configs.ts, packages/manager/cypress/support/intercepts/linodes.ts
Add new cypress tests for VPC assign/unassign flows.
- Add e2e tests to verify assigning/unassigning Linode(s) to/from a VPC.
```
yarn cy:run -s "cypress/e2e/core/vpc/vpc-linodes-update.spec.ts"
```
1. When there are multiple Linodes in the select list, users type the label to select one of them, then it will deselect all when users type another label and select it.
1. When users click the `Unassign Linode`  button, it doesn’t send any request to tell the VPC to unassign Linodes.
=> test: [M3-7124] - Add Cypress integration tests for VPC assign/unassign flows

packages/api-v4/.changeset/pr-9891-upcoming-features-1699549450125.md, packages/api-v4/.changeset/pr-9891-upcoming-features-1699549504970.md, packages/api-v4/src/aglb/types.ts, packages/manager/.changeset/pr-9891-upcoming-features-1699549397674.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-service-targets.spec.ts, packages/manager/src/factories/aglb.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CertificateSelect.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetRow.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/aglb/certificates.ts, packages/validation/.changeset/pr-9891-upcoming-features-1699549582236.md, packages/validation/.changeset/pr-9891-upcoming-features-1699549618358.md, packages/validation/src/loadbalancers.schema.ts
Adds `protocol` support to AGLB certificates based on a change to the API. This PR also makes other Service Target related changes/fixes
- Adds new `protocol` field to Service Targets
- There is now a _Protocol_ Select in the Service Target Create/Edit Drawer
- The protocol is now listed in the Service Targets table
- Changes `ca_certificate` ➡️ `certificate_id` based on API change
| ![Screenshot 2023-11-09 at 11 49 01 AM](https://github.com/linode/manager/assets/115251059/0b9893ff-3f54-4ca1-8d87-19aea947f5d3) | ![Screenshot 2023-11-09 at 11 48 34 AM](https://github.com/linode/manager/assets/115251059/acde31b4-d620-40a6-b2e3-16e4890a931d) |
| ![Screenshot 2023-11-09 at 11 48 53 AM](https://github.com/linode/manager/assets/115251059/f3a20923-de9d- …
=> feat: [M3-7390] - Add AGLB `protocol` to Service Targets

packages/manager/.changeset/pr-9892-tests-1699549772226.md, packages/manager/Dockerfile, packages/manager/package.json, yarn.lock
Upgrades from Cypress 13.4.0 to 13.5.0.
Normally wouldn't update so quickly since we just upgraded to 13.x, but 13.5.0 [includes a lot of bugfixes](https://docs.cypress.io/guides/references/changelog#13-5-0), and I realized I never updated our Dockerfile when we upgraded to 13.4.0 so wanted to take the opportunity to take care of that too.
(This means that at the moment, our GHA tests are using Cypress 13.x, but our Jenkins tests are still using 12.)
- Upgrades Cypress from 13.4.0 to 13.5.0
- Updates our Dockerfile for Cypress 13.5.0
We can rely on the automated tests for this, but they can be run locally with `yarn cy:run`.
=> test: Upgrade from Cypress 13.4.0 to Cypress 13.5.0

packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx
We lost a one-liner added in https://github.com/linode/manager/pull/9865 that checks off the "Assign a public IPv4 address for this Linode" checkbox in the Edit Linode Config dialog when the `ipv4.nat_1_1` property is populated. This PR restores it.
- Account with proper VPC tags
On the release branch:
- In the Linode Create flow, assign a VPC and check off the "Assign a public IPv4 address for this Linode" checkbox. Proceed with creation
- (with your DevTools > Network tab open filtered for `configs`) On the newly-created Linode, go to the Configurations tab, edit the config, scroll down the Edit Config dialog to the "Networking" section and observe: the VPC interface's "Assign a public IPv4 address for this Linode" checkbox is unchecked, despite the network request showing …
=> fix: Restore `nattedIPv4Address` prop passed from `LinodeConfigDialog` --> `InterfaceSelect`

packages/manager/.changeset/pr-9900-fixed-1699974142591.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx
Fixes back button disabled state on the Linode Details network tab
| ![Screenshot 2023-11-14 at 9 51 10 AM](https://github.com/linode/manager/assets/115251059/9d63b752-428e-4875-a80d-dfa0bb09c29d) | ![Screenshot 2023-11-14 at 9 57 07 AM](https://github.com/linode/manager/assets/115251059/0f90c8fd-8d64-42a1-99c1-463c8bbf00b8) |
- You must have a Linode that has > 1 month of network data to show on the graph
- Go to http://localhost:3000/linodes/:id/networking
- Observe that the back button appears to be disabled even though clicking it goes back a month
- Verify the button appears to be enabled when there is past network history to be viewed
=> fix: [M3-7400] - Linode Network Transfer History - Back button incorrectly disabled

packages/manager/.changeset/pr-9887-fixed-1699470171696.md, packages/manager/src/components/DebouncedSearchTextField/DebouncedSearchTextField.tsx, packages/manager/src/components/StackScript/StackScript.tsx, packages/manager/src/components/StackScript/index.ts, packages/manager/src/features/StackScripts/StackScriptDialog.tsx, packages/manager/src/features/StackScripts/StackScriptsDetail.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCSubnetsTable.tsx
- Fixes the overflow bug on the VPC and StackScript details page
- Fixes cutoff searchbar on VPC details page 
- note: placeholder text so far still gets larger when the screen gets smaller (consistent across all searchbars) -- currently forcing a default width of the searchbar on the VPC details page as a result + Also updated the margin for the searchbar and Create Subnet button in the VPCSubnetsTable, due to adding the flex-wrap property so that the search bar and button don't squash each other on smaller screens. this is an alternate fix compared to trying to decrease the placeholder text font (think I just need to target the correct mui classes, but was having trouble with it -- will still look into it)
| …
=> fix: [M3-7331] - VPC and StackScript details overflow

packages/manager/.changeset/pr-9907-upcoming-features-1700075574257.md, packages/manager/src/queries/accountAvailability.ts
- Forgot to do this in the original PR 😅 , but basically just making our existing query for `useAccountAvailabilitiesQuery` use `getAll`
- Verify that data still looks as expected when using this query and that pagination is gone 
=> upcoming: Update `useAccountAvailabilitiesQuery` query to use `getAll`

packages/manager/.changeset/pr-9910-fixed-1700149776187.md, packages/manager/src/mocks/serverHandlers.ts
During release testing, we ran into a bunch of 'oh snap' popups due to the MSW. This PR should hopefully get rid of them all - the issues seem to stem from VPC and Firewall mock requests.
- Use the MSW
- Navigate to VPC Landing, Firewall Landing, Linode pages like the Network tab or Configurations tab -- the error pops up on these pages
- Perform a general check of CM using the MSW and verify that no 'oh snap' errors appear. Confirm they don't appear on ^ pages
=> fix: [M3-7405] - Take care of 'oh snap' errors from MSW

packages/manager/.changeset/pr-9884-tech-stories-1699542889621.md, packages/manager/src/components/EditableEntityLabel/EditableEntityLabel.tsx, packages/manager/src/components/EditableEntityLabel/EditableInput.styles.tsx, packages/manager/src/components/EditableEntityLabel/EditableInput.tsx
Refactors on `SRC > Components > EditableInput` for MUI v5 migration
- Converts `makeStyles` to `styled` API
- Moved styles to separate file
- Buttons "x" and checkmark have been converted to IconButton and look nicer
> [!note]
> Gif below has been slowed down and is a little pixelated compared to what you'll actually see.
- Pull down branch
- Go to any longview page with a client
- There should be no visual changes except for the icon buttons
- Observe changing `typeVariant` in the `EditableEntityLabel` file to `h1/h2/table-cell` work
=> refactor: [M3-6964] - MUI v5 Migration - `SRC > Components > EditableInput`

packages/manager/.changeset/pr-9919-upcoming-features-1700494666167.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts
Add a new `parentChildAccountAccess` flag and add it to our dev console.
- Pull the code 
- Toggle the flag in our developer settings
- use `flags.parentChildAccountAccess` to conditionally render any element
=> feat: [M3-7410] - Add Parent/Child Feature Flag

packages/manager/.changeset/pr-9915-fixed-1700235447855.md, packages/manager/src/components/TableCell/TableCell.tsx
Something about our TableCell with an Action Menu is not working well in some tables. The ActionMenu is causing the TableCell to be the wrong size and position the border incorrectly. ☹️
- Removes the static `height` assigned to a `TableCell`  with the `actionCell` prop
| ![before-zoomed](https://github.com/linode/manager/assets/115251059/4417ca46-3873-41f1-98e8-edc890ff02b7)  | ![after-zoomed](https://github.com/linode/manager/assets/115251059/67acbd13-7735-4bc7-82dd-3245b210c22f) |
| ![before](https://github.com/linode/manager/assets/115251059/21086a6d-5a89-472c-8927-8b6248a157b0)  |  ![after](https://github.com/linode/manager/assets/115251059/a91622c2-de57-4bef-aaa5-affbe407e4c8)  |
- Go to …
=> fix: [M3-7407]: `TableCell` with `ActionMenu` incorrect size and border placement

packages/manager/.changeset/pr-9920-tests-1700498392893.md, packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts, packages/manager/cypress/support/intercepts/vpc.ts, packages/manager/src/features/VPCs/VPCDetail/SubnetDeleteDialog.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.test.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCDeleteDialog.tsx
- Add unit tests for VPC Delete component
- Add additional integration test to confirm error handling for VPC deletion
- Small bug fix for VPC delete error state (make sure error doesn't persist when opening up the delete dialog)
Bug fix: 
| <video src="https://github.com/linode/manager/assets/139280159/1ca5ee48-5d0f-40e2-8eb4-bc56b67849b4" /> | <video src="https://github.com/linode/manager/assets/139280159/0b88e51d-5e65-4467-8480-e2e915b4eafe" /> |
For testing the bug
- With VPC account tags, set up two vpcs:
- one VPC with at least one linode assigned to it
- some other VPC
- Navigate to VPC landing page
- Try to delete the VPC with a linode assigned to it (you …
=> test: [M3-6750] - VPC Delete tests

packages/manager/.changeset/pr-9930-fixed-1700680496652.md, packages/manager/src/features/Images/ImagesLandingEmptyStateData.ts
Fixes a typo on the Images landing page empty state by replacing "DNS Manager Guides" with "Getting Started Guides"
- Just replaces "DNS Manager Guides" with "Getting Started Guides"
| 📷 | 📷 |
Not covered by any E2E tests right now (see M3-7452, however). Can be tested manually by navigating to `/images` and confirming page title. This may require deleting the images on your test account, or using MSW to mock your images request to force the empty state.
=> fix: [M3-7451] - Replace Images landing page section title with "Getting Started Guides"

packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts, packages/manager/cypress/support/intercepts/configs.ts, packages/manager/cypress/support/intercepts/vlans.ts
Add regression tests to verify Linode Config VPC assignment to interface.
- Add new tests to assign VPC to the interface in Linode Config page.
```
yarn cy:run -s "cypress/e2e/core/linodes/linode-config.spec.ts"
```
=> test: [M3-7322] - Add Cypress test to confirm Linode Config VPC assignment

packages/manager/tsconfig.test.json
- Deletes an unused `tsconfig` file we no longer need 🎉🗑️
- This tsconfig file was used for our jest tests, but now that we are on Vitest, we don't need it. Thank you Vitest 🙏🏼
- Verify unit tests still run as expected `yarn test`
- Verify all CI passes
=> refactor:  Remove unused `tsconfig.test.json`

packages/manager/.changeset/pr-9934-tests-1701101589138.md, packages/manager/cypress/e2e/core/general/maintenance-mode.spec.ts, packages/manager/cypress/support/intercepts/general.ts, packages/manager/cypress/support/util/paginate.ts, packages/manager/cypress/support/util/response.ts
Adds an integration test for Cloud Manager's handling of the API's maintenance mode. It confirms that the maintenance mode message and link to status page are shown.
- Adds maintenance mode integration test
- Cleans up Cypress response types
We can rely on CI for this, but you can run the new test locally with this command:
`yarn && yarn build && yarn start:manager:ci`, and then:
```bash
yarn cy:run -s "cypress/e2e/core/general/maintenance-mode.spec.ts"
```
=> test: [M3-7468] - Add Cypress integration test for API maintenance mode handling

packages/api-v4/.changeset/pr-9942-upcoming-features-1701206431848.md, packages/api-v4/src/account/types.ts, packages/manager/.changeset/pr-9942-upcoming-features-1701206553615.md, packages/manager/src/factories/accountUsers.ts, packages/manager/src/factories/grants.ts, packages/manager/src/mocks/serverHandlers.ts
`GET /account/users` and `GET /account/users/<username>` requests will return a new `user_type` field to allow us to distinguish between users. 
`GET /account/users/<username>/grants` will return a new grant type: `child_account_access`, which will be true for parent accounts with access to child account endpoints.
These additions to existing endpoints set us up to implement account switching and user permissions flows.
- Updated the `User` interface and factory to include the new `user_type` field
- Updated the `Account` interface and `Grant` factory to include the new `child_account_access` field
- Updated the MSW `account/users` endpoint to include a child, parent, and proxy user
- IRL, we'd never see all three parent, proxy, and child users on one account, but mocking each user type …
=> upcoming: [M3-7413] - Update existing user account endpoints and mocks for Parent/Child Account Switching 

packages/manager/.changeset/pr-9943-upcoming-features-1701209599920.md, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts, packages/manager/src/components/RegionSelect/RegionSelect.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.ts, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/ClusterSelect.tsx, packages/manager/src/features/Volumes/VolumeCreate.tsx, packages/manager/src/mocks/serverHandlers.ts
- The bulk of the logic for disabling regions was implemented [here](https://github.com/linode/manager/pull/9909)! 🎉 This PR adds some additional logic to disable regions when creating various entities:
- Linodes/Migrating Linodes
- Volumes
- Nodebalancers
- Managed Databases
- Object Storage
There will be a part 2 PR for additional stuff later - definitely Kubernetes, potentially Service Transfers
- Updated `getRegionOptions` in `RegionSelect` to filter regions based on capability - only show the regions that actually support whichever capability we pass in + added relevant test
- Update MSW so that we can see a disabled region in Object Storage & Databases
- Add logic for disabled regions in Linodes/Migrate Linodes, Volume, Nodebalancers, Managed Databases, Object Storage
- update …
=> upcoming: [M3-7214 - M3-7216, M3-7219, M3-7221, M3-7222] - Add DC Get Well logic to various user flows pt1

packages/manager/.changeset/pr-9899-upcoming-features-1699911388781.md, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
We are grabbing configs for every Linode in the Linodes landing page to check if it is a VPC-only Linode which does not scale well (same problem as the VPC Linodes landing column). This PR reverts the Linodes landing portion of https://github.com/linode/manager/pull/9899 and adds a warning banner
- Revert disabling of the Public IP Address column in the Linodes landing table for VPC-only Linodes
- Add warning banner to the Linodes landing page
- Ensure your account has vpc customer tags
- Go to `/linodes` and filter your Network tab by `configs`. You should see a configs request for each Linode you have
- Go to `/linodes` and filter your Network tab by `configs`
- You should no longer see a configs request for each Linode you have
- You should see a warning banner
=> change: [M3-7485] - Revert Disable Public IP for Linodes Landing

packages/api-v4/src/aglb/types.ts, packages/manager/.changeset/pr-9941-upcoming-features-1701203325929.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts, packages/manager/cypress/support/intercepts/load-balancers.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/EditCertificateDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ApplyCertificatesDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/CertificateTable.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerServiceTargets.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx, packages/manager/src/queries/aglb/serviceTargets.ts, packages/validation/src/loadbalancers.schema.ts
- Adds AGLB e2es for updating configurations using only **mock data** 🧪
- Also improves **error handling** for AGLB configurations 🚫
- Disabled the "Save Configuration" button if no changes have been made ⏹️
- Fixed bug where a rule would not be creatable (we pass `label` to fix this) 🐛
- Only shows `downstream` certificates when configuring a Configuration 🔐
- Handles the certificates endpoint not returning `certificate` for alpha 🚫
https://github.com/linode/manager/assets/115251059/bbe2b4ed-2ff7-45b9-8ac8-a202aefefdc7
- Run `yarn cy:debug`
- Run the `load-balancer-configurations.spec.ts` tests
- Manually test the Configurations tab with the MSW **on** for any regressions
=> upcoming: [M3-7131] - Add AGLB Configuration Edit Tests & General Bug Fixes

packages/manager/.changeset/pr-9938-upcoming-features-1701201054946.md, packages/manager/package.json, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/NetworkTransferHistoryChart.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx, yarn.lock
This PR is part of a bigger effort to replace chart.js with the more modern Recharts. As a first step, replace the Linode Network Transfer History chart.
| <video src="https://github.com/linode/manager/assets/115299789/3376b759-9062-4e5f-a1ea-db283660eb5b" /> | <video src="https://github.com/linode/manager/assets/115299789/0bc10953-bda9-4290-be3f-470311a9b4de" /> |
- Have a Linode that's been running for a while
- Go to the Network tab of a Linode that's been running for a while
- Confirm the updated UI and that there are no regressions in the graph, units, etc
=> upcoming: [M3-7301] - Replace Linode Network Transfer History chart with Recharts

packages/manager/.changeset/pr-9952-tests-1701457740855.md, packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts, packages/manager/cypress/support/intercepts/account.ts, packages/manager/cypress/support/intercepts/general.ts, packages/manager/cypress/support/ui/accordion.ts
This adds Cypress integration tests for various UI flows related to account cancellation via Cloud Manager's Account Settings page. Broadly speaking, these tests confirm that users can cancel their account, are correctly prompted to complete an exit survey, and that Cloud responds gracefully to API errors that occur during the cancellation process.
- Adds account cancellation test for unrestricted users
- Adds account cancellation test for restricted users
- ℹ️ Currently Cloud doesn't handle this any differently from any other API error that could occur when cancelling an account, but if we were to enhance this UX we'll now have a test case to cover it
We can rely on CI to make sure that the tests pass and that changes made to mock utils and UI helpers do not cause any unintended issues. …
=> test: [M3-6169] - Account cancellation integration tests

packages/api-v4/src/account/types.ts, packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.ts, packages/manager/src/factories/accountAvailability.ts, packages/manager/src/mocks/serverHandlers.ts
The API spec is being updated slightly. This PR matches those updates.
-`id` field in AccountAvailbility object changed to `region`
- confirm MSW still works as expected (see PR #9943 for testing instructions)
=> fix: Update types for DC get well endpoint

packages/api-v4/src/aglb/types.ts, packages/manager/.changeset/pr-9954-fixed-1701698397297.md, packages/manager/.changeset/pr-9954-upcoming-features-1701698414248.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts, packages/manager/src/components/TableCell/TableCell.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerCreate/ConfigurationDetails.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerCreate/LoadBalancerRegions.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/CreateCertificateDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/constants.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Certificates/index.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerSummary.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/CreateRouteDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/DeleteRuleDialog.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.test.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/ServiceTargetDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.test.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/ServiceTargets/utils.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Settings/Region.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerLanding/LoadBalancerRow.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerLanding/Ports.tsx, packages/validation/src/loadbalancers.schema.ts
- Fixes ActionCell styles 🎨
- Make copy changes required by technical writer ✏️
- Add rule drawer now has dynamic copy depending on the protocol
- Improves spacing of some error notices ⛔️
- Fixes a lot of validation / payloads to match what the Linode API allows 🚛
- You should now be able to add TCP Rules now
- You should be able to delete Rules
| ![Screenshot 2023-12-01 at 4 48 00 PM](https://github.com/linode/manager/assets/115251059/07dc9ca4-e4ce-46c3-8170-7340bf87c39a) | ![Screenshot 2023-12-01 at 4 47 52 PM](https://github.com/linode/manager/assets/115251059/93df0a3f-275b-4780-8edc-342fe390a524) |
| ![Screenshot 2023-12-01 at 4 50 18 PM](https://github.com/linode/manager/assets/115251059/15225359-3dd1-4d50-b85b-09287914f1cd) | ![Screenshot …
=> upcoming: [M3-7520] - AGLB Fixes and Improvements

packages/manager/.changeset/pr-9962-upcoming-features-1701804783926.md, packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx, packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx, packages/manager/src/features/VPCs/constants.ts
Update the copy and "Learn more" links on the VPC Create page
<details>
<summary>Screenshot</summary>
</details>
- An account with the proper VPC tags
- Ensure the copy and links on the VPC Create page match the ticket (note: the docs have not been published yet so the links will not go to an actual guide, but the URLs have been finalized)
=> change: [M3-7493] – Update UX copy on VPC Create page

packages/manager/.changeset/pr-9951-upcoming-features-1701454182728.md, packages/manager/cypress/e2e/core/vpc/vpc-landing-page.spec.ts, packages/manager/src/features/VPCs/VPCLanding/VPCEmptyState.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCEmptyStateData.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCLandingEmptyStateData.tsx
Update copy and resource links for the empty state VPC landing page.
- Minor copy tweaks
- Resource links added (links have not yet been published yet so the hyperlinks won't work at this point, but the URLs have been finalized)
- MSW
If you have VPCs on your account already, the easiest way to test this would be turning the MSW, commenting these lines out in `serverHandlers.ts`, and refreshing the page:
https://github.com/linode/manager/blob/1141d10c3801992fe07f114280250150bc737738/packages/manager/src/mocks/serverHandlers.ts#L443-L445
Confirm that:
- Copy matches the ticket/mockup
- Links match what's listed in the ticket
=> change: [M3-7492] – VPC Landing page empty state resource links & copy updates

packages/manager/.changeset/pr-9966-upcoming-features-1701878955797.md, packages/manager/src/features/VPCs/constants.ts
Update `VPC_REBOOT_MESSAGE` with new copy for "Reboot Needed" tooltip.
<details>
<summary>Screenshots</summary>
VPC Details page:
Linode Details page:
</details>
- Account with proper VPC tags
The easiest way to test this:
- Assign a Linode to a subnet from the VPC Details page (subnet row --> three-dot menu --> "Assign Linodes")
- Observe: the assigned Linode should appear in the subnet inner table with a status of "Reboot Needed" and a tooltip with the updated copy
=> change: [M3-7494] – Update copy for Linode "Reboot Needed" tooltip

packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx
This PR removes the new VPC-related banner on the Linodes Landing page, currently visible in dev. This was a Product and UX decision based on engineering feedback.
This PR reverts the changes to LinodesLanding in [this PR](https://github.com/linode/manager/pull/9933/files).
| ![Screenshot 2023-12-06 at 11 09 23 AM](https://github.com/linode/manager/assets/114753608/b59b0a04-9934-404b-9bdb-0c1d473104e0) | ![Screenshot 2023-12-06 at 10 58 22 AM](https://github.com/linode/manager/assets/114753608/cf23dbe6-ad2d-4071-9e04-ad285930d9f9) |
- Run this branch locally against the prod API
- Clear any dismissible banners 
- Verify the Linodes Landing page works as expected and does not include the VPC banner.l
*Check all …
=> change: Remove VPC Banner on Linodes Landing

packages/manager/.changeset/pr-9971-fixed-1701887926900.md, packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.ts
This **giant** PR fixes a small issue with the region select DCs not being sorted properly in Firefox.
- Adjust RegionSelect sorting util  
| Before (Firefox)  | After (Firefox)  |
| ![Screenshot 2023-12-06 at 13 38 23](https://github.com/linode/manager/assets/130582365/da667f02-5ecd-4ac5-9a32-4d25e6850463) | ![Screenshot 2023-12-06 at 13 33 18](https://github.com/linode/manager/assets/130582365/d5ac5152-2c48-4460-a841-1583208c7195) |
- on develop & while using firefox, go to a create flow featuring the RegionSelect and notice the DCs are not alphabetically sorted.
- on this branch & while using firefox, go to a create flow featuring the RegionSelect and notice the DCs are now properly alphabetically sorted.
- Ensure there's no regression in the sorting for other …
=> fix: [M3-7533] - RegionSelect sorting in Firefox

packages/manager/src/features/NodeBalancers/NodeBalancerDeleteDialog.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSettings.tsx, packages/manager/src/queries/nodebalancers.ts
FW NodeBalancer Release 1.108.0 fixes
- NodeBalancer Settings tab helper text now shows when the NodeBalancer doe not have an assigned Firewall
- Invalidated Firewall query after NodeBalancer delete
- FW-NodeBalancer Feature Flag turned on
- Dev tools > Network > Disable cache
- After deleting NodeBalancer, ensure that the Firewall table gets updated
- Make sure helper text in the NodeBalancer's Setting page in the Firewall's panel is visible when there is not an assigned Firewall and not visible when there is.
=> fix: FW NodeBalancer Release Fixes

packages/manager/.changeset/pr-9968-upcoming-features-1701991737243.md, packages/manager/CHANGELOG.md, packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/constants.ts, packages/manager/src/features/VPCs/constants.ts
Update UX copy in the VPCPanel and Linode Add/Edit Config dialog
- UX copy updates and added a docs link
- Account with proper VPC tags
- VPCPanel changes can be verified in the Linode Create flow and/or the Linode Add/Edit Config dialog
- "Learn more" is hyperlinked to the finalized (but unpublished) doc URL
- Copy in tooltip for VPC dropdown changed
- Copy in tooltip for "Assign a public IPv4 address for this Linode" checkbox changed
- Copy in tooltip for "Auto-assign a VPC IPv4 address for this Linode in the VPC" checkbox changed
- Copy changes for unrecommended configuration notices in Add/Edit Config dialog (instructions for specific configurations/scenarios outlined in "Preview" section in https://github.com/linode/manager/pull/9916)
=> change: [M3-7499, M3-7502, M3-7507] – UX copy updates for VPC Panel in Linode Create & Linode Add/Edit Config Dialog

packages/manager/.changeset/pr-9977-upcoming-features-1701987666651.md, packages/manager/src/env.d.ts, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/account.ts
This PR adds Mock Service Worker (MSW) endpoints for all new "Parent/Child" API calls. (Updates to all existing endpoints were previously done in #9942.) These changes will enable us to mock the Parent/Child API interactions, ensuring our development remains unimpeded and independent of ongoing API changes. 
- Added endpoints to the MSW for new Parent/Child endpoints.
- Updated the queries for `useChildAccounts` and `useChildAccount` to allow an unrestricted parent account to be able to reach these endpoints. (They will have `child_account_access` by default, but we can't check grants on an unrestricted user, which was relied upon in the initial implementation of the queries.)
|   |   |
| --- | --- |
| ![Screenshot 2023-12-08 at 10 05 53 …
=> upcoming: [M3-7414] - Add mocks and update queries for new Parent/Child endpoints

.github/workflows/coverage.yml, .github/workflows/coverage_badge.yml, packages/manager/.changeset/pr-9988-tech-stories-1702336644030.md
Slightly speeds up our new code coverage Github Actions jobs by not building a production Cloud Manager bundle 🏎️
We should see an improvement of about 30-60 seconds ⏲️ Nothing groundbreaking, but slightly better. 
- Check the GitHub Actions below this PR and verify that the Code Coverage jobs work as expected
=> ci: Speed Up Code Coverage Github Actions Jobs

packages/manager/.changeset/pr-9990-upcoming-features-1702400746535.md, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx
Update the descriptive copy for the Private IP add-on in the Linode Create flow.
- Copy change for Private IP add-on in Linode Create flow
- An account with the proper VPC tags
- On an account with the proper VPC tags or with the VPC feature flag on, you should see the text for the Private IP add-on in the Linode Create flow
=> change: [M3-7505] – Update copy for Private IP add-on in Linode Create flow

packages/manager/.changeset/pr-9955-tests-1701693591911.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-landing-page.spec.ts, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-summary.spec.ts, packages/manager/cypress/support/intercepts/load-balancers.ts
Adds more e2e tests for AGLB.
- yarn cy:debug
- Run load-balancer-summary.spec.ts
- Run load-balancer-landing-page.spec.ts
=> test: [M3-7135] - Add integration test for AGLB Load Balancer delete flows

packages/manager/.changeset/pr-9995-tests-1702420300908.md, packages/manager/cypress/e2e/core/volumes/landing-page-empty-state.spec.ts
This PR introduces Cypress tests for the `Volumes` landing page in an empty state (no volumes exists).
- The tests verify that the empty state works as expected.
- Run `yarn cy:run -s "/Users/ecarrill/Desktop/manager/packages/manager/cypress/e2e/core/volumes/landing-page-empty-state.spec.ts"`
- Verify e2e test passes.
=> test: [M3-7470] - Cypress test for Volumes landing page empty state

packages/manager/.changeset/pr-10000-tests-1702591069388.md, packages/manager/cypress/e2e/core/firewalls/landing-page-empty-state.spec.ts
Introduces Cypress tests for the `Firewalls` landing page in an empty state (no firewalls exist).
- The tests verify that the empty state works as expected.
- Run `yarn cy:run -s "cypress/e2e/core/firewalls/landing-page-empty-state.spec.ts"`
- Verify e2e test passes.
=> test: [M3-7464] - Add Cypress test FW landing page empty state

packages/manager/.changeset/pr-9992-changed-1703028128822.md, packages/manager/.changeset/pr-9992-upcoming-features-1702939785550.md, packages/manager/src/factories/oauth.ts, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/utils.test.ts, packages/manager/src/features/Profile/APITokens/utils.ts
New Scope:
Introduce a new OAuth scope named "child_account" for all users, but visible only to "Parent" accounts. As per API spec: its purpose is to allow Parent Account Users with the `child_account_access` grant to specify a Token with less permission than their User, i.e. a Token that is unable to list and/or create Tokens for the Child Account(s).
Token Configuration:
Default all scopes to `none` for users. Users should enable scopes as needed, contrary to having the initial state set to `read_write`. 
- In the Create PAT drawer, a new "Child Account Access" scope is visible for **parent** users.
- In the View PAT drawer, a new "Child Account Access" scope is visible for **parent** users.
| ![Screenshot 2023-12-13 at 4 01 40 …
=> upcoming, change: [M3-7524] - Add child_account OAuth scope to Create and View PAT drawers

packages/manager/.changeset/pr-10011-changed-1703028750129.md, packages/manager/src/features/Users/UserPermissions.tsx
Updated toast notifications in user permissions.
- Updated toast notifications
| | 
|---|
| ![Screenshot 2023-12-22 at 2 46 49 PM](https://github.com/linode/manager/assets/139489745/1ae0c537-dacb-4265-9da7-68046f58a2f6) |
| ![Screenshot 2023-12-22 at 2 47 23 PM](https://github.com/linode/manager/assets/139489745/6b707179-119c-4a93-9f30-e31663a07d9a) |
| ![Screenshot 2023-12-22 at 2 47 37 PM](https://github.com/linode/manager/assets/139489745/4c753526-f51c-4038-9ba6-c243d00ec555) |
- Ensure that saving full account access, global (soon to be renamed "general"), and entity specific permissions triggers a toast notification. ('User permissions successfully saved.' or '[Entity-specific/general] user permissions successfully saved.')
=> change: [M3-7461] - Update toast notifications for UserPermissions

packages/manager/.changeset/pr-9980-added-1701986820847.md, packages/manager/cypress/e2e/core/linodes/switch-linode-state.spec.ts
Add regression tests for powering on/off and rebooting Linodes
- Add regression tests to power on/off and reboot Linodes
```
yarn cy:run -s "cypress/e2e/core/linodes/switch-linode-state.spec.ts"
```
=> test: [M3-6608] - Add Linode power off, power on and reboot tests

packages/manager/.changeset/pr-10023-tests-1704213295558.md, packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.test.tsx, packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/CreditCard.tsx, packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentDrawer.tsx, packages/manager/src/features/Billing/BillingPanels/BillingSummary/PaymentDrawer/PaymentMethodCard.tsx, packages/manager/src/utilities/creditCard.test.ts, packages/manager/src/utilities/creditCard.ts
- Fixes failing unit test caused by the New Year (`2023` ➡️ `2024`) 🎆
- Mocks dates by changing Luxon's settings 📅
- Simplifies function and naming ✏️
- Removes default exports ❌
This is the test that needed to be fixed.
```sh
yarn test CreditCard
```
Check this for good measure because it contains the expiry logic
```sh
yarn test creditCard
```
=> fix: Failing `CreditCard.test.tsx` Unit Test

packages/manager/.changeset/pr-10013-added-1703179399644.md, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/src/components/SelectionCard/CardBase.tsx, packages/manager/src/components/SelectionCard/SelectionCard.tsx, packages/manager/src/constants.ts, packages/manager/src/factories/regions.ts, packages/manager/src/featureFlags.ts, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx, packages/manager/src/features/components/PlansPanel/PlanContainer.styles.ts, packages/manager/src/features/components/PlansPanel/PlanContainer.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts, packages/manager/src/features/components/PlansPanel/utils.test.ts, packages/manager/src/features/components/PlansPanel/utils.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/regions.ts
This PR implements sold out chips to our `PlanSelection` components (both Linode and Kubernetes). It helps our users with picking a `GPU` or `Premium CPU` plan by showing them plans that are actually available to them instead of trying to select unavailable plans that would lead to an API error upon submission.
It utilizes the new regions/availability endpoint which only returns availability for `GPU` or `Premium CPU` plans (it may be expanded later on). In the background, the endpoint gets refreshed at 15m via a cron job checking available resources in our DCs.
⚠️: While the endpoint is already live in production, we're waiting for an API update that will convert the `plan` value to our regular plan Ids. This is why this PR is to be tested with mock data.
⚠️: The feature flag is …
=> feat: [M3-7373] - Sold Out Chips

packages/manager/.changeset/pr-10038-added-1704495369939.md, packages/manager/src/features/Events/eventMessageGenerator.ts
Add support for `obj_access_key_create`, `obj_access_key_delete`, and `obj_access_key_update` events so that they are properly formatted in the Events dropdown and Events landing page.
- Add OBJ Access Key events to `eventMessageGenerator.ts`
<details>
<summary>Screenshot</summary>
</details>
- Create, edit, and delete an OBJ Access Key
- Observe: OBJ Access Key events should be properly formatted as shown in the screenshot in the Preview section
=> feat: [M3-7563] – Add proper support for OBJ Access Key events

packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/utils.test.ts, packages/manager/src/features/Profile/APITokens/utils.ts, packages/manager/src/features/Users/UserPermissions.tsx, packages/manager/src/queries/profile.ts
- Fixes profile query keys causing some mutations to not invalidate the correct query key
- Relates to https://github.com/linode/manager/pull/9987
- I left `useProfile` alone because the parent/child project needs `headers` functionality. Other profile query keys were reverted to their old format
- This bug is a perfect example of why we need a query key factory 🏭😖
- Also fixes:
- An unrelated bug with User Permission loading state
- An unrelated bug with `read_only` PAT resulting in an error: `Invalid OAuth scope: child_account:read_only`
Query keys:
- Test profile related features such as...
- Revoking a trusted device
- Enabling / disabling 2FA
- Creating, updating, and deleting SSH keys
- Verify the changes to `useGrants` does not break anything 
- Do you best to …
=> fix: Profile Query Keys, User Permissions loading state, and read_only PAT creation

packages/manager/.changeset/pr-10033-tests-1704470547191.md, packages/manager/cypress/e2e/core/general/gdpr-agreement.spec.ts, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/cypress/support/intercepts/account.ts, packages/manager/src/features/Account/Agreements/EUAgreementCheckbox.tsx
Small PR to add e2e coverage for the GDPR agreement panel.
Since we are using existing test accounts it is preferable to mock the response from `account/agreements`.
- Add a new `gdpr-agreement.spec.ts`
- Add a new util to mock the response from `account/agreements`
- pull code locally, run `yarn up` and `yarn cy:debug`, pick the `gdpr-agreement` test and run it
=> test: [M3-7409] - Add GDPR agreement e2e

packages/manager/.changeset/pr-10042-fixed-1704748141170.md, packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.styles.tsx, packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx, packages/manager/src/features/Managed/ManagedDashboardCard/ManagedDashboardCard.styles.tsx
Fix loading and dark mode styling for the Managed Summary tab
| <video src="https://github.com/linode/manager/assets/115299789/f67fa4ed-7ccd-4e6e-bbef-71c862aa10e3" /> | <video src="https://github.com/linode/manager/assets/115299789/9d76afd6-0c65-4c2f-aef8-c8b8117f1486" /> |
- Have an account that's Managed (you can do so via admin)
- On another branch, go to `/managed/summary` and observe the styling loading blip
- The container background in dark mode does not match the graph.
-  Go to `/managed/summary`, there should no longer be a styling loading blip.
- The container background in dark mode should now match the graph.
=> fix: [M3-7260] - Managed Summary layout

packages/manager/.changeset/pr-10045-tests-1704834823931.md, packages/manager/.changeset/pr-10045-upcoming-features-1704814925607.md, packages/manager/cypress/e2e/core/account/user-permissions.spec.ts, packages/manager/src/features/Users/UserPermissions.tsx
As a child user, the UI of the permissions page will be the same as global or non-parent/child, except for Billing Access. Billing Access will be set to "Read Only" with the option for unrestricted child users to switch it to "None" for other child users. "Read-Write" will always be disabled. In other words, child account users will have no permission greater than "Read Only" billing access.
**Why are we enforcing this in the UI, rather than relying on the `account_access` grant?**
For an unrestricted (admin) child account user's `account_access` (which determines Billing Access), the API will return `read_write` in order for the user to have access to the rest of the user permissions, including managing those of their proxy user. Therefore, we need to make an additional check of the …
=> upcoming: [M3-7463] - Disable Billing access user permission for child users

packages/manager/.changeset/pr-10048-upcoming-features-1704822100414.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx
- The AGLB Configuration "Save Changes" button remained disabled even if they tried to remove a route from a configuration
| "Save Changes" never becomes enabled after removing a route | The "Save Changes" button becomes enabled when a change is made | 
|  <video src="https://github.com/linode/manager/assets/115251059/374a5bb3-a4b0-4ec2-a9a5-3128747fd96d" /> | <video src="https://github.com/linode/manager/assets/115251059/870728cf-ad5b-41cb-ae1a-7c92da610a67" /> |
- Use the dev environment
- Sign into the `dev-test-aglb` account
- Test using any AGLB on the test account
- Go to the configurations tab on an AGLB
- Remove a route from a configuration using the action menu
- Observe that when you remove the route, you are unable to save changes
- …
=> fix: [M3-7624] - AGLB Configuration - Save button disabled when trying to remove a route

packages/manager/.changeset/pr-10057-fixed-1704983627685.md, packages/manager/.changeset/pr-10057-tests-1704983693919.md, packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts, packages/manager/src/features/Kubernetes/UpgradeVersionModal.tsx
- Fixes the Kubernetes Upgrade Flow
- This bug was not caught by our automated testing because we did not have full coverage for the upgrade flow 
- On the Kubernetes Upgrade flow on the Kubernetes Details page, users were not able to reach step 2 of the upgrade flow. The Upgrade dialog would close after submitting step 1. 
- This was caused by us rendering `null` in our upgrade component when we still need to render step 2  
- **This bug only applies to the details page**
- This was the case because on the details page, we passed the version of the cluster to the upgrade dialog from the React Query store, which caused the dialog to close immediately when the version updated. The reason this did not happen to the landing page is because the cluster's current version was stored in an …
=> fix: [M3-7630] - Fix Kubernetes Upgrade Flow

packages/manager/.changeset/pr-10049-fixed-1704837468392.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
This PR fixes a small bug in which a user within the linode create flow can't use the "Marketplace" link in the PrimaryNav.
I've left a code comment that explains the problem and why it was fixed this way.
- Add a one time fix to update the selected tab when using the the "Marketplace" primary nav link
| <video src="https://github.com/linode/manager/assets/130582365/4a73f14d-f062-4710-bba3-c9670346b2b2" /> | <video src="https://github.com/linode/manager/assets/130582365/1dad4ffb-2068-49ec-89ab-ca56cff608d7" /> |
- Navigate to https://cloud.linode.com/linodes/create
- Click on the "Marketplace" primary nav item
- Notice nothing happens
- Pull code locally and run `yarn up`
- Navigate to http://localhost:3000/linodes/create
- Click on the …
=> fix: [M3-7307] Fix PrimaryNav marketplace navigation within Linode Create

packages/api-v4/package.json, packages/manager/.changeset/pr-10059-tech-stories-1704987208139.md, packages/manager/package.json, yarn.lock
- Updates Axios so that `follow-redirects` gets updated to >= 1.15.4
- Resolves https://github.com/linode/manager/security/dependabot/90
- Verify api-v4 and Cloud Manger still work - our automated testing should be able to confirm this
=> chore: [M3-7634] - Update `axios` to resolve `follow-redirects` dependabot alert

packages/manager/.changeset/pr-10032-tests-1704400629879.md, packages/manager/cypress/e2e/core/linodes/update-linode-labels.spec.ts
Add regression tests for updating/renaming the Linode label.
- Add regression tests to update/rename a Linode label
```
yarn cy:run -s "cypress/e2e/core/linodes/update-linode-labels.spec.ts"
```
=> `test`: [M3-6616] - Add tests to update/rename linode label

LICENSE, packages/manager/.changeset/pr-10067-changed-1705423329479.md
This PR updates Cloud Manager's licence to the latest Akamai's recommended `Apache` licence. (from the Open Source Working Group)
- Update Cloud Manager's Licence
=> changed: [M3-7512] Update Cloud Manager LICENCE

packages/manager/.changeset/pr-10052-upcoming-features-1704993330964.md, packages/manager/src/components/LandingHeader/LandingHeader.tsx, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.tsx
This PR adds a convenient "Switch Account" button to the Account Landing page to allow an alternative and efficient way (aside from the user menu) to access the account switching drawer.
- A 'Switch Account' button is now visible on the Billing Info tab of the Account Landing page for parent and proxy users
<details>
<summary>
Video
</summary>
https://github.com/linode/manager/assets/114685994/fac2174a-c225-46de-81cb-142cfbb92f20
</details>
- Check out this PR and `yarn dev`.
- Turn the parent/child feature flag and mocks on. 
- Go to http://localhost:3000/account/billing and observe the Switch Account button.
- Click the button and observe that it opens and displays a list of child accounts. (By default, `user_type` is parent.)
- Go …
=> upcoming: [M3-7475] - Add Switch Account button to Account Landing page

packages/manager/.changeset/pr-10073-fixed-1705544271675.md, packages/manager/src/components/CopyableTextField/CopyableTextField.tsx
Standardize Copy Icon Color Variations in CopyableTextField.
|![image](https://github.com/linode/manager/assets/119517080/2e9907d1-056d-4424-bf3f-72ceebeec8a2)| ![image](https://github.com/linode/manager/assets/119517080/4226b065-1583-43c5-a417-d0b637338a51) |
|![image](https://github.com/linode/manager/assets/119517080/6c6b3850-d5c2-43df-b455-ba1f292153c1)|![image](https://github.com/linode/manager/assets/119517080/c179cc49-ba6e-4d07-bcee-da284a376ad9) |
- Verify all references of CopyableTextField.
- Ensure there is no regression.
=> fix: [M3-7638] - Standardize Copy Icon Color Variations in CopyableTextField

packages/manager/.changeset/pr-10069-upcoming-features-1705512789450.md, packages/manager/cypress/e2e/core/account/user-permissions.spec.ts, packages/manager/src/features/Users/UserDetail.tsx, packages/manager/src/features/Users/UserPermissions.tsx, packages/manager/src/mocks/serverHandlers.ts
Depending on the type of user managing the account, we want to restrict account access to billing.
- Regular/Parent Account Users: No change, they can configure `None | Read Only | Read Write`.
- Child Account Users: Can configure `None | Read Only`, `Read Write` is disabled.
- Proxy Users: `Read Write` is enabled and immutable, `None | Read Only` are disabled. 
- `currentUser` and `username` created ambiguity as to what user we're actually dealing with for permissions, so to provide clarity:
- `currentUser` is now `accountUsername`
- `username` is now `currentUsername` 
- Removed `checkAndEnableChildAccountAccess` and it's accompanying state properties since we can infer all this based on `user_type`.
-  Removed from state: `childAccountAccessEnabled` and `isAccountAccessRestricted`
- …
=> upcoming: [M3-7462] - User Permissions: Configure Billing Account Access

packages/manager/.changeset/pr-10071-fixed-1705522697458.md, packages/manager/src/utilities/generate-cli.test.ts, packages/manager/src/utilities/generate-cli.ts
The Linode CLI doesn't accept `interfaces.ipv4` as an object. Instead, it should be configured individually as `interfaces.ipv4.vpc` and `interfaces.ipv4.nat_1_1`. `interfaces.vpc_id` is also not a valid argument.
- `interfaces.ipv4` object -> individual arguments 
- Removed `interfaces.vpc_id` from the Linode CLI command
| ![image](https://github.com/linode/manager/assets/115299789/2bfefd9b-eefc-41bc-be64-f7b95c980b23) | ![image](https://github.com/linode/manager/assets/115299789/17861307-0d7d-449e-bc01-f8f58d6ece72) |
- On a different branch, go to `/linodes/create`. Fill out the form, add a VPC, and click the `Create Using Command Line` button. Notice how `--interfaces.ipv4` is an object.
(How to …
=> fix: [M3-7638] - VPC arguments in Linode Create flow CLI

packages/manager/.changeset/pr-10077-fixed-1705594578246.md, packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx
Fixes a dark mode bug for some Linode action buttons on the Linodes details page 🎨
I think this bug has been around for a few months.
| ![Screenshot 2024-01-18 at 11 10 02 AM](https://github.com/linode/manager/assets/115251059/596d8f66-16b3-4cd5-b96e-d7e7874b88b5) | ![Screenshot 2024-01-18 at 11 10 08 AM](https://github.com/linode/manager/assets/115251059/bec8f231-0641-42a7-9dbc-14655baae06f)  |
- Switch to Dark Mode 🌚
- Go to the Linodes details page on any Linode 
- Hover over one of the action buttons "Power off", "Reboot", or "Launch LISH Console"
- Verify that these buttons are the correct color
- Verify light mode is still the correct color ☀️
=> fix: [M3-7664] - Linode Action Buttons Incorrect Color in Dark Mode

packages/validation/.changeset/pr-10063-changed-1705088599651.md, packages/validation/src/objectStorageKeys.schema.ts
Update OBJ validation to reflect the upcoming OBJ Multi-Cluster changes.
Changes to _createBucketSchema_, which were in scope for this ticket, were already made in https://github.com/linode/manager/pull/9976.
- Add optional `regions` property in `createObjectStorageKeysSchema` (it cannot be an empty array nor null)
At this stage, the main concern is verifying that this change does not break existing functionality: you should still be able to create Access Keys as you can currently, with no unexpected errors in the UI or in the console.
=> feat: [M3-7564] – Update OBJ validation

packages/manager/.changeset/pr-10072-changed-1705529283172.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromBackupsContent.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx
This PR address sub-task 1 of M3-7580 Updates to Linode Clone UI.
I plan to release each sub-task directly to develop under a new feature flag, `linodeCloneUIChanges`.
- Adds a new notice to the Clone Linodes flow recommending users power off their Linode before cloning
|  ![Screenshot 2024-01-17 at 4 59 40 PM](https://github.com/linode/manager/assets/122488130/8ec559f5-fd1a-4b9e-ba97-700e86bd3cb8) |  ![Screenshot 2024-01-17 at 4 59 25 PM](https://github.com/linode/manager/assets/122488130/e7849b73-9ba7-4897-909d-b206fb35ccc4) |
- Enable the "Linode Clone UI Changes" feature flag
- Navigate to the Create Linode flow
- Click on the "Clone Linode" tab
- Verify a notice appears recommending users power off their Linode before cloning
*Check all …
=> change: [M3-7651] - Add Clone Linode power-off notice

packages/manager/.changeset/pr-10074-changed-1705590614132.md, packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Removed the Unified Migrations feature flag since the feature has been released.
- Removed feature flag in E2E and Linode Resize
- Added loading state to submit button
- Attempt to resize a linode
- Observe resize panel is still showing
- Observe warm resizes still work
=> changed: [M3-7663] - Remove unified migrations feature flag

packages/manager/cypress/e2e/core/account/user-permissions.spec.ts, packages/manager/cypress/support/intercepts/account.ts
Add regression tests for adding users on `Users & Grants` page.
- Add regression tests to add users on `Users & Grants` page.
```
yarn cy:run -s "cypress/e2e/core/account/user-permissions.spec.ts"
```
=> test: [M3-7482] - Add cypress tests to add users on "Users & Grants" page

packages/manager/.changeset/pr-10010-added-1703035008158.md, packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx, packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.test.tsx, packages/manager/src/features/VPCs/VPCCreate/MultipleSubnetInput.tsx, packages/manager/src/features/VPCs/VPCCreate/VPCCreate.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetCreateDrawer.tsx, packages/manager/src/queries/vpcs.ts, packages/manager/src/utilities/subnets.test.ts, packages/manager/src/utilities/subnets.ts
When creating new subnets via both the Create VPC flow and the Create Subnet drawer, we will now be incrementing the subnet range so that the default value is not a static 10.0.4.0/24 value.
Talked with Daniel about this behavior 👍 - 
- For both the VPC Create flows and Subnet Create Drawer, the recommended IP will start at 10.0.0.0/24 or 10.0.1.0/24 and go up to 10.0.1.0/24, 10.0.2.0/24, etc. 10.0.x.0/24 ips will be the only ones recommended. 
- (There was a previous version that depended more on the user's already existing IPs for the Subnet Create Drawer >> checkout and run [this commit](https://github.com/linode/manager/pull/10010/commits/207c2d4d1efe99d474d0b324877917bfe414af59) - this led to pretty frequent recommendation of "bad IPs" (ips that are technically valid but have …
=> feat: [M3-7168] - Increment Subnet IPv4 value when recommending new subnet range

packages/manager/.changeset/pr-10078-changed-1705616003861.md, packages/manager/src/components/AreaChart/AreaChart.tsx
Right justify the chart tooltip datapoints so that they are more discernible as suggested by Kendall/Andrew
| ![image](https://github.com/linode/manager/assets/115299789/1acb4bae-f8bb-4c78-9ae4-4350f5321bed) | ![image](https://github.com/linode/manager/assets/115299789/9aa3ffee-e6f3-4ad7-b16c-5d18d819bc9b) |
- Have a Linode that's been running for a while
- Hover over a chart (like in the Linode Details Analytics tab) to see the tooltip text. Data points should be right aligned
=> change: [M3-7668] - Right align chart tooltip data points

packages/manager/.changeset/pr-10079-upcoming-features-1705615366001.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/constants.tsx
- Updates AGLB Configuration Ports Copy
- Tweaks form error handling so that it matches the behavior of other dynamic forms
- Updates the `port` dynamically if you choose HTTP or HTTPS when you haven't provided a custom port
| ![Screenshot 2024-01-18 at 4 59 31 PM](https://github.com/linode/manager/assets/115251059/aa167043-b314-41ed-a9b9-dc69bff3ce1a) | ![Screenshot 2024-01-18 at 4 59 20 PM](https://github.com/linode/manager/assets/115251059/27a2c990-4d36-44b0-a28a-fa1aefec8e2e) |
- Use the `dev-test-aglb` account
- Use the dev environment
- Go to http://localhost:3000/loadbalancers/13/configurations
- Click `Add Configuration`
- Check the copy on the ports field tooltip
=> upcoming: [M3-7599] - Update AGLB Configuration Ports Copy

packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
Instead of hard-coding `true` for `isBeta` (which determines whether the beta chip is displayed or not), we can rely on the feature flag.
As of the open beta, the API returns `VPCs` in `account.capabilities` for all users, so our feature flag does not actually control access to VPC features in Cloud at this time. Once VPC enters GA, we can safely turn off the feature flag, making this a good case for using it.
I don't think a changeset is needed here, but I can add one if there's disagreement on that.
Two options:
1) Using our DevTool, toggle the checkbox for the VPC feature flag and refresh the page. Observe: the presence of the beta chip for VPC in the PrimaryNav should reflect the current state of that checkbox (unchecked --> no beta chip, checked --> beta chip)
2) Add `vpc: false` in …
=> refactor: [M3-7672] – Use feature flag to govern display of beta chip for VPC in PrimaryNav

packages/manager/.changeset/pr-10091-tests-1705938529204.md, packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
The Ubuntu 23.04 image was recently marked as deprecated by the API, which impacts the label shown in Cloud and consequently caused the Cloud Manager StackScript test to fail. I updated the test to look for 23.10 instead.
- Replace check for Ubuntu 23.04 with Ubuntu 23.10
We can rely on the automated testing for this.
=> test - Fix StackScript Test Failure due to Ubuntu 23.04 Image Deprecation

packages/manager/.changeset/pr-10094-tests-1705959873279.md, packages/manager/cypress/e2e/core/domains/domains-empty-landing-page.spec.ts
This fixes a flaky test by changing a `should('not.be.visible')` assertion to `should('not.exist')`. This test passes most of the time because the `should('not.be.visible')` assertion passes during a brief moment when the drawer close animation occurs (i.e. the element is still present in the DOM, but not visible). However, every so often this assertion does not occur quickly enough and the element is no longer present in the DOM, and the assertion fails.
This was initially planned to be included in a larger PR containing more fixes, but that's taking longer than I had planned and there's no reason to hold this back in the meantime.
- Fix Domains landing page empty state test flake
We can rely on CI, but this test can also be run locally using …
=> test: Fix Domains landing page empty state test flake

packages/manager/.changeset/pr-10101-fixed-1706061984923.md, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.styles.ts
- Fixes button colors of VPC action buttons (`Edit` and `Delete`)
- Relates to https://github.com/linode/manager/pull/10077
| ![Screenshot 2024-01-23 at 8 54 50 PM](https://github.com/linode/manager/assets/115251059/a59a30e0-9352-42e1-9c0a-d00b5d29a355) | ![Screenshot 2024-01-23 at 8 54 40 PM](https://github.com/linode/manager/assets/115251059/35382c81-44bb-48e4-90cb-5e057dbb16ee) |
- Go to VPC details page
- Check the colors of the `Edit` and `Delete` buttons in both light ☀️ and dark mode 🌑
=> fix: [M3-7692] - VPC Action Buttons Incorrect Color in Dark Mode

packages/manager/.changeset/pr-10093-tests-1706031852395.md, packages/manager/cypress/e2e/core/account/user-permissions.spec.ts, packages/manager/cypress/support/intercepts/account.ts
Add regression tests for deleting users on `Users & Grants` page.
- Add regression tests to delete users on `Users & Grants` page.
```
yarn cy:run -s "cypress/e2e/core/account/user-permissions.spec.ts"
```
=> test: [M3-7483] - Add test to delete users on "Users & Grants" page

packages/manager/.changeset/pr-10109-upcoming-features-1706136926455.md, packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts, packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx, packages/manager/src/features/Profile/APITokens/APITokenTable.tsx
According to the API spec:
Proxy users may not generate additional tokens for themselves.
Proxy users will be able to view the tokens provisioned for them, but will not be able to modify them.
Proxy users should still be able to revoke their own PAT.
- The "Create A Personal Access Token" button is disabled for proxy users.
- The disabled button has a tooltip that reads: "You can only create API tokens for your own company."
- Proxy users can view the tokens provisioned for them but cannot modify them.
- The disabled Rename action has a tooltip that reads: "Only company users can edit API tokens."
- Added Cypress test coverage for proxy user disabled PAT states.
| Description  | Screenshot   |
| Disabled Edit action button |![Screenshot 2024-01-24 at 3 40 29 …
=> upcoming: [M3-7481] - Disable creating and editing API tokens for proxy users

packages/manager/.changeset/pr-10096-upcoming-features-1706030600745.md, packages/manager/src/components/Breadcrumb/FinalCrumb.tsx, packages/manager/src/components/Breadcrumb/types.ts, packages/manager/src/components/EditableText/EditableText.stories.tsx, packages/manager/src/components/EditableText/EditableText.test.tsx, packages/manager/src/components/EditableText/EditableText.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx, packages/manager/src/features/PlacementGroups/index.tsx, packages/manager/src/features/PlacementGroups/utils.test.ts, packages/manager/src/features/PlacementGroups/utils.ts, packages/manager/src/mocks/serverHandlers.ts
This PR implements the Placement Groups Detail page and associated routing. It does not implement tabs content (summary & linodes list) which are left for subsequent tickets.
- Implement the detail page and its routing
- Add a couple simple utils and their tests
- Make the `EditableTextField` take a  new `textSuffix` prop to manage the breadcrumb suffix
- Add test and a story for ☝️ 
- Fix the HTTP method for placement group query MSW
- Pull and run code locally
- Turn on the "Placement Group" dev setting and MSW
- Navigate to http://localhost:3000/placement-groups
- Click on a placement group in the table
- Confirm the Placement Group Detail page and its content (breadcrumb w/ editint label, docs link, tabs without content) 
=> upcoming: [M3-7610] - Placement Groups Detail

packages/api-v4/src/networking/types.ts, packages/manager/.changeset/pr-10108-added-1706218083195.md, packages/manager/src/factories/linodeConfigInterfaceFactory.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.test.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddressRow.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeNetworkingActionMenu.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/types.ts
Add support for displaying VPC IPv4 addresses and ranges in the Linode Details -> Network tab -> "IP Addresses" table
- Add Support for VPC IPv4 addresses and ranges to the Linode IP Address table
- If there is a VPC interface with 1:1 NAT, hide the Public IPv4 IP address row
- Improve mobile text display of the Type column
| ![ip address table before](https://github.com/linode/manager/assets/115299789/da3851c5-6040-4361-8446-512a87fefcd8) | ![image](https://github.com/linode/manager/assets/115299789/13f23888-972a-4d78-8433-df3585281fef) |
| Mobile before  | Mobile after   |
| ![mobile before](https://github.com/linode/manager/assets/115299789/b35299fc-058c-4a1b-8c46-3174810a2ef5) | …
=> feat: [M3-7644] - Add VPC IPv4 address and range to Linode IP Address Table

packages/manager/.changeset/pr-10089-added-1706135120889.md, packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.style.ts, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsListTable.tsx, packages/manager/src/features/Linodes/LinodeSelect/LinodeSelect.tsx, packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.test.tsx, packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.test.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetAssignLinodesDrawer.tsx, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx, packages/manager/src/features/VPCs/constants.ts, packages/manager/src/utilities/noneSingleOrMultipleWithChip.test.tsx, packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx, packages/validation/.changeset/pr-10089-changed-1706135447361.md, packages/validation/src/linodes.schema.ts
Rework the "Assign Linodes" drawer to support the assigning and display of IPv4 ranges.
This PR will not be merged into `develop` but rather into a to-be created branch to accommodate the off-cycle release next week to release this for VPC.
- Rely on VPC feature flag to determine whether the "BETA Feedback" link is displayed or not on the VPC landing & detail pages
- Update `LinodeInterfaceSchema` to remove max length of 1 for `ip_ranges` field
- New `AssignIPRanges` component (will be used in the Linode Create flow & Add/Edit Linode Config dialog as well in subsequent tickets)
- Added `RemovableSelectionsListTable` component instead of muddying `RemovableSelectionsList` (the latter will be getting used in other projects also, not just VPC anymore)
- Minor adjustments in …
=> feat: [M3-7641] – Support IPv4 ranges in VPC "Assign Linodes" drawer

packages/manager/.changeset/pr-10103-upcoming-features-1706069199851.md, packages/manager/src/components/ActionsPanel/ActionsPanel.tsx, packages/manager/src/components/SingleTextFieldForm/SingleTextFieldForm.tsx, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.test.tsx, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx, packages/manager/src/features/Profile/DisplaySettings/TimezoneForm.tsx, packages/manager/src/mocks/serverHandlers.ts
As a parent user logged into a proxy account, I should not be able to change the email address or username set by the provisioning API.  
- Fixed alignment of input fields and buttons at `/profile/display` page.
- Added unit tests for disabling `Username` and `Email`
- As proxy user: added tooltip text to buttons to disabled buttons for context
| ![Screenshot 2024-01-23 at 10 41 23 PM](https://github.com/linode/manager/assets/125309814/cea5d150-0917-49e3-bbaf-80ffadd254cb) | ![Screenshot 2024-01-23 at 10 51 06 PM](https://github.com/linode/manager/assets/125309814/79c08fc4-4b11-4ba9-b35b-f87dbeae3a06) |
- Turn on MSW and Parent/Child feature flag
- Set `user_type` to `proxy` in [serverHandlers](https://github.com/linode/manager/blob/develop/packa …
=> upcoming: [M3-7530] - Restrict proxy users from updating username/email

packages/manager/.changeset/pr-10107-upcoming-features-1706135635175.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx
- Puts ACLB rules at the top of the table / array when the rule is created
| <video src="https://github.com/linode/manager/assets/115251059/bf69b633-99b0-4298-a7ae-a8f553e18ec1"/> | <video src="https://github.com/linode/manager/assets/115251059/3e326b7d-87bb-476e-aef7-11a4a0dbf6ee" /> |
- Have the AGLB flag on
- Use the dev environment
- Login to the `dev-test-aglb` account
- Verify that when you create a new rule, it is placed at the **top** of the rules table.
=> upcoming: [M3-7699] - Put newly created ACLB Rules at the top of the table upon creation

packages/manager/.changeset/pr-10112-upcoming-features-1706218217394.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RulesTable.tsx
- Changes ACLB Rule table column  `Execution` ➡️ `Execution Order`
- Changes the values `First 2 3 Last` to `1 2 3 4`
- This is a change requested by UX
| ![Screenshot 2024-01-25 at 4 09 38 PM](https://github.com/linode/manager/assets/115251059/0fb56ecb-74e2-49cc-a845-9868f52d9687)  | ![Screenshot 2024-01-25 at 4 08 54 PM](https://github.com/linode/manager/assets/115251059/a2a32167-01ef-4c9a-ac1b-28a39d788826) |
- Login to `dev-test-aglb` account using the dev API **or** use the MSW to test this
- Go to an AGLB
- View rules on any route
- Verify the rules has an `Execution Order` column
- Verify the rules `Execution Order` column has numeric values `1 2 3 4`
=> upcoming: [M3-7707] - Change AGLB Rule Execution Order Column Header and Values

packages/manager/.changeset/pr-10121-tech-stories-1706560897746.md, packages/manager/src/featureFlags.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx, packages/manager/src/queries/kubernetes.ts
Just doing some feature flag clean up. The Kubernetes Dashboard feature has been in production for at least a year or two. I think we can safely clean up this flag! 🧹
As tempting as it is, this PR does not attempt to fix how broken this summary section is.
> [!note]
> This should **not** result in UI changes. This feature has been enabled for a long time and should remain enabled.
- Verify you see the `Kubernetes Dashboard` button on the Kubernetes Details page on any LKE cluster
=> change: [M3-7715] - Remove `kubernetesDashboardAvailability` feature flag

packages/manager/.changeset/pr-10119-changed-1706549896002.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts, packages/manager/src/components/CollapsibleTable/CollapsibleRow.tsx
Small PR to rectify the orientation of the Collapsible TableRow icon
| Before (closed)  | After (closed)  |
| ![localhost_3000_vpcs_19662 (2)](https://github.com/linode/manager/assets/130582365/3f54c5ab-bbd7-47ea-9275-282b7c740295) | ![localhost_3000_vpcs_19662](https://github.com/linode/manager/assets/130582365/af639afc-b162-4809-95fe-096c0fa3f9b0) |
| Before (open)  | After (open)  |
| ![localhost_3000_vpcs_19662 (3)](https://github.com/linode/manager/assets/130582365/7645d344-f033-4c03-8e99-46b8eaaf47c5) | ![localhost_3000_vpcs_19662 (1)](https://github.com/linode/manager/assets/130582365/da037d26-639a-4141-940e-af9d8f1363fb) |
- Have a VPC and subnet
- Navigate to http://localhost:3000/vpcs/{id}
- Observe the new orientation of the …
=> change: [M3-7710] - Table Collapsible row icon orientation

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx
- Updated VPC flag for primary navigation
=> Release v1.110.1 - `staging` → `master` 

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/VPCs/VPCDetail/VPCDetail.tsx, packages/manager/src/features/VPCs/VPCLanding/VPCLanding.tsx
- Remove VPC beta feedback link
=> Release v1.110.2 - `staging` → `master` 

packages/manager/.changeset/pr-10127-fixed-1706638177404.md, packages/manager/src/features/NodeBalancers/NodeBalancerCreate.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerDetail.tsx
Adds a custom label to the `NodeBalancerDetail` & `NodeBalancerCreate` breadcrumb labels. This eliminates the inconsistent capitalization between "Nodebalancers" and "NodeBalancers".
- "Nodebalancers" ➡️ "NodeBalancers" in the NodeBalancers details & create breadcrumb labels
| ![Screenshot 2024-01-30 at 1 06 34 PM](https://github.com/linode/manager/assets/122488130/88bf6098-4b9c-4154-97d9-a45b7366ca88) | ![Screenshot 2024-01-30 at 1 06 42 PM](https://github.com/linode/manager/assets/122488130/2c1974bd-52e0-48dd-87c6-2b05d90dbbde) |
| ![Screenshot 2024-01-30 at 1 29 19 PM](https://github.com/linode/manager/assets/122488130/823cc026-05fe-4b06-88ab-57783ef7e894) | ![Screenshot 2024-01-30 at …
=> fix: Custom breadcrumb for NodeBalancers details page

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Users/UserPermissions.tsx
- Enable `Can add VPCs to this account` for user permissions
=> Release v1.110.3 - staging → master

packages/api-v4/src/aglb/types.ts, packages/manager/.changeset/pr-10126-upcoming-features-1706637215176.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/MatchTypeInfo.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts, packages/validation/.changeset/pr-10126-upcoming-features-1706637249025.md, packages/validation/src/loadbalancers.schema.ts
Adds new `path_regex` Rule match type to ACLB. This will allow users to create rules that match on a path using regex.
| ![Screenshot 2024-01-30 at 12 48 09 PM](https://github.com/linode/manager/assets/115251059/29f4792a-12fc-45a3-ac37-deffbd520d8a) | ![Screenshot 2024-01-30 at 12 47 53 PM](https://github.com/linode/manager/assets/115251059/c4c7a29e-c9b7-441c-baea-d6b28efa90fa)  |
- Switch your Cloud Manager to use the dev environemnt 
- Login to `dev-test-aglb` account for testing
- On the `aglbsqaMDDA013007` ACLB try to create/edit a rule and choose `Path Regex` as the match type
- Verify the copy for tooltips are updated
=> upcoming: [M3-7695] - Add new `path_regex` match type to ACLB

packages/manager/.changeset/pr-10132-fixed-1706715510568.md, packages/manager/src/components/EditableText/EditableText.tsx
This is a tiny PR to fix a small pixel shift when switching on the editable breadcrumb.
Currently, when clicking on the pencil icon to edit the final breadcrumb (title), we can see the whole breadcrumb shift two pixels and make the content underneath shift as well (see **before** video).
- Remove unnecessary initial vertical borders
- Remove fade-in animation (I don't think it adds anything? - makes it looks" buggy")
| <video src="https://github.com/linode/manager/assets/130582365/a823cf9f-09d0-4a64-ad24-6b32469f0d59" /> | <video src="https://github.com/linode/manager/assets/130582365/4f8ca504-3232-479c-a124-05d40e30cf2f" /> |
- Test editable breadcrumbs for various entity details (firewall, linode etc)
=> fix: [M3-7722] - Adjust EditableText styling to prevent pixel shift

packages/manager/.changeset/pr-10102-upcoming-features-1706069240239.md, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx, packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/queries/account.ts
Now that `user_type` is returned from the `/account/profile` endpoint, we can save ourselves some query calls.
- Updated tests and files that didn't need to call `/account/users/`
Shouldn't be any visual changes
- Run `yarn test` ensure all tests pass
- Run `cyrun cypress/e2e/core/account` ensure all tests pass
- Verify user menu still works as intended as with MSW
- Verify we can see `Child Account Access` by [following steps here](https://github.com/linode/manager/pull/10083)
=> upcoming: [M3-7660] - Cleanup files to use `profile` to get `user_type`

packages/manager/src/features/Account/SwitchAccountDrawer.tsx, packages/manager/src/mocks/serverHandlers.ts
This PR fixes a couple of issues impacting account switching:
1. Fixes a typo introduced [here](https://github.com/linode/manager/pull/10064#discussion_r1459818274) that was causing a parent token's `scopes` and `expiry` to not be fetched and then stored correctly from local storage, causing the "switch" back to a parent account (which relies on the stored parent's token in local storage) to fail.
2. Fixes a [bug](https://github.com/linode/manager/pull/10110#discussion_r1474686256) where "Bearer" would have been included twice in an auth token.
This PR also changes the `user_type` back to `parent` in the MSW. This doesn't really matter, but we've used a default of `parent` throughout this project so it's helpful to keep it the same default for consistency.
| ------- …
=> fix: [M3-7728] - Token issues when account switching

packages/manager/CHANGELOG.md, packages/manager/src/components/CheckoutBar/CheckoutBar.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/utilities/pricing/dynamicPricing.ts
Hide error message for $0 regions since that is not technically an error. Continue to display the error icon otherwise.
- Error message tooltip no longer displayed for $0 region prices in Linode and Kubernetes Create
- Plus and minus and Add buttons are no longer disabled in Kubernetes Create Plan table if the price is $0
| Linode Create Before  | Linode Create After   |
| ![image](https://github.com/linode/manager/assets/115299789/a90745c3-48ef-4f47-93f6-65e646ea7ec9) | ![image](https://github.com/linode/manager/assets/115299789/a27826f4-e4f5-46c7-909a-2320b725a9da) |
| Kubernetes Create Before  | Kubernetes Create After   |
| <video src="https://github.com/linode/manager/assets/115299789/bafdc8b2-2582-4 …
=> change: [M3-7703] - Hide error message for $0 regions

packages/manager/.changeset/pr-10142-fixed-1707158870254.md, packages/manager/src/testSetup.ts
Since we changed our buttons to feature an aria tag VS using a `disabled` attribute, both `toBeEnabled` & `toBeDisabled` can lead to false positives.
The reason is, the `jest-dom` assertion for `toBeEnabled` will look for a `disabled` attribute which isn't going to be present since we've altered our Button to feature an `aria-disabled` tag instead, leading to a false positive.
We've applied the fix for our e2e but the unit suite configuration needed to be handled as well.
- Add an interceptor for `toBeEnabled` & `toBeDisabled` assertions (for buttons only) that checks for `aria-disabled` tags as well
- An easy to reproduce the initial issue is to use an existing assertion such as the `CloseAccountSetting` component locally (**on develop branch**)
-  hardcode this …
=> fix: [M3-7725] - Unit tests button enabled assertions

packages/manager/.changeset/pr-10150-tests-1707236804326.md, packages/manager/cypress/e2e/core/billing/billing-contact.spec.ts
This resolves the Cypress failure in `billing-contact.spec.ts`. The failure stems from the account's company name appearing in the user menu button at the top of the page -- that issue will be handled separately, but this fixes the test in the meantime by searching for the company name only in the billing contact summary section on the billing page.
- Fix `billing-contact.spec.ts` failure
We can rely on CI for this
---
> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**
`<commit type>: [JIRA-ticket-number] - <description>`
**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build …
=> test: [M3-7737] - Resolve Billing Contact Cypress failure

packages/manager/.changeset/pr-10148-tech-stories-1707231054836.md, packages/manager/src/featureFlags.ts, packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx
In production, `regionDropdown` has been **enabled** for the last two years and has not changed. I think we can safely remove this flag from the codebase. 🧹
- Go to http://localhost:3000/account/billing/edit
- Verify **Country** and **State** are required
- Verify this drawer looks and functions the same locally as it does in production
=> refactor: [M3-7736] - Clean up `regionDropdown` feature flag

packages/manager/.changeset/pr-10139-tests-1707331596288.md, packages/manager/cypress/e2e/core/account/change-username.spec.ts, packages/manager/cypress/e2e/core/account/user-permissions.spec.ts
Add regression tests for checking proxy user disabled username/email field
- Add regression tests to check proxy user disabled username/email field
```
yarn cy:run -s "cypress/e2e/core/account/change-username.spec.ts"
```
=> test: [M3-7698] - Add test to check proxy user disabled username/email field

packages/manager/.changeset/pr-10157-fixed-1707328749030.md, packages/manager/cypress/e2e/core/kubernetes/lke-update.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/AddNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.test.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/ResizeNodePoolDrawer.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.test.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/utils.ts
This PR supports $0 region pricing by correctly showing pricing without errors on the LKE Details page. It also fixes the UI for invalid (`null` or `undefined`) prices in the Resize Pool drawer.
Currently, once a user creates a LKE cluster in a region where pricing is $0 (currently: Madrid, which is in LA):
When trying to **resize pool**, the UI displays a confusing `0` in place of the "Current pool" and "Resized pool" calculations, the pricing error is displayed, but a user is actually still able to complete the resize because the enhanced number input is still clickable and can be incremented, at which point the user can save changes.
When trying to **add a node pool**, after adding at lease one node, the UI displays a pricing error and pricing display text with $--.-- placeholder …
=> fix: [M3-7741] - Hide error notices for $0 regions in Resize Pool and Add a Node Pool drawers

packages/manager/.changeset/pr-10161-fixed-1707341493849.md, packages/manager/cypress/e2e/core/linodes/backup-linode.spec.ts, packages/manager/cypress/support/constants/dc-specific-pricing.ts, packages/manager/src/factories/index.ts, packages/manager/src/features/Backups/BackupDrawer.test.tsx, packages/manager/src/features/Backups/BackupDrawer.tsx, packages/manager/src/features/Backups/BackupLinodeRow.test.tsx, packages/manager/src/features/Backups/BackupLinodeRow.tsx, packages/manager/src/utilities/pricing/backups.test.tsx, packages/manager/src/utilities/pricing/backups.ts
This fixes a couple issues in the "Enable All Backups" drawer when one or more Linodes are in a $0-priced region.
- Fixes calculation of total backup cost
- Removes error indicator
- Fixes calculation of total backup price when one or more Linodes is in a $0 region
- Removes error indicator from backup rows for Linodes in $0 regions
- Adds and updates tests to account for these states
| <img width="1048" alt="Screenshot 2024-02-07 at 1 33 36 PM" src="https://github.com/linode/manager/assets/97627410/06488726-0d30-4e72-8337-6344c71e0880"> | <img width="1194" alt="Screenshot …
=> fix: [M3-7746] - Fix $0 region price error in "Enable All Backups" drawer

packages/manager/.changeset/pr-10156-fixed-1707363343774.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/IPTransfer.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/LinodeIPAddresses.tsx, packages/manager/src/queries/linodes/networking.ts
This PR aims to fix a regression where users weren't able to transfer IPv6 ranges in the Linode Network tab.
I am frankly unsure how that was a regression considering we weren't pulling the ranges in the modal whatsoever, but perhaps someone has better context about this. Long story short, I hope my fix is the right one considering my lack of context. One thing I know is that adding those back to the modal works fine, and the transfer goes through.
This component is gross. It is a dirty ramda rat fest and the UI is questionable. While I wanted to only address the problem at heart, I couldn't help but attempt to improve the UI and make things at least look better for our users in the modal and add IP drawer.
- Add (back?) IPvs ranges to the modal
- Improve layout and styling in modal and …
=> fix: [M3-7004] - Allow IPv6 ranges transfers

packages/manager/.changeset/pr-10166-fixed-1707414781493.md, packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.test.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrationPricing.tsx
When migrating to or from a region with $0 pricing, the Linode migrate dialog hides the $0.00 price. This fixes the issue and adds some unit tests.
- Adds unit tests for MigrationPricing component
- Updates MigrationPricing logic to account for $0 pricing
| <img width="956" alt="To Zero Region" src="https://github.com/linode/manager/assets/97627410/a7bfe71f-b452-4730-88c8-23017ac302b9"> | <img width="947" alt="Screenshot 2024-02-08 at 12 24 28 PM" src="https://github.com/linode/manager/assets/97627410/4d76e05f-87ab-40df-bab8-80c7e6d9eaa0"> |
To run the new unit tests:
```bash
yarn test MigrationPricing.test
```
To run related Cypress tests:
`yarn && yarn build && yarn start:manager:ci` and then
```bash …
```
=> fix: [M3-7747] - Fix Linode Migration dialog hidden $0 price

packages/manager/.changeset/pr-10153-fixed-1707249479775.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.test.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeBackup/EnableBackupsDialog.tsx
This fixes an error message that appears when enabling Linode backups in regions with $0 prices. 
- Only show the error message if the retrieved backup price is `null` or `undefined`, but allow `0`
Serve Cloud with `yarn && yarn build && yarn start:manager:ci`, and then:
```bash
CY_TEST_REGION='es-mad' yarn cy:run -s "cypress/e2e/core/linodes/backup-linode.spec.ts"
```
(Note: This will only work on accounts that have access to the `es-mad` region, and won't be properly validated by our CI)
1. Create a Linode in the `es-mad` region
2. Navigate to its details page, then click the "Backups" tab
3. Attempt to enable backups and confirm that an error message does not appear on the confirmation dialog and that you're able to enable backups successfully
(*Edit:* You can also test that the error …
=> fix: [M3-7739] - Fix error when enabling backups for Linodes in regions with $0 price

packages/manager/.changeset/pr-10125-tests-1707232650553.md, packages/manager/.changeset/pr-10125-upcoming-features-1707232753513.md, packages/manager/cypress/e2e/core/account/account-login-history.spec.ts, packages/manager/cypress/support/intercepts/account.ts, packages/manager/src/factories/accountLogin.ts, packages/manager/src/features/Account/AccountLogins.tsx, packages/manager/src/features/Account/AccountLoginsTableRow.tsx, packages/manager/src/features/Account/utils.ts, packages/manager/src/mocks/serverHandlers.ts
Currently, all restricted users receive an unauthorized message (see Before screenshot) after the table data fails to populate when they access the Login History tab. In the case of a child user (user_type: child), who is unrestricted by the API (account_access: read_write), but should be restricted in the UI, we must manually restrict the child user from viewing this page.
This PR updates the child view to not show login history information and display a warning notice to convey unauthorized access. For consistency, we will also make these changes for restricted users.
> [!NOTE] 
The API has recently changed from `user_type: null` to `user_type: "default"`. This is not reflected in this PR at this time because I didn't want to duplicate the work we'll need to make these changes on the …
=> upcoming: [M3-7527] - Improve Login History restricted and child user experience

packages/manager/.changeset/pr-10164-upcoming-features-1707487417041.md, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx, packages/manager/src/features/PlacementGroups/constants.ts, packages/manager/src/features/PlacementGroups/utils.ts
This PR introduces the `PlacementGroupsSummary` component.
- Add Summary panel which displays the Placement Group's configuration details.
- Add logic to display a warning notice in the even the Placement Group is not compliant.
- Add unit testing for component.
- Enable the following using the Cloud Manager Dev Tools:
- Placement Groups feature flag
- MSW
- Navigate to `http://localhost:3000/placement-groups`
- Click on a Placement Group from the table.
- Verify the configuration info to match the info from the Placement Group you clicked.
- Verify that the tooltip is rendered and behaves as expected.
- Run the following unit test: `yarn test PlacementGroupsSummary`
=> upcoming: [M3-7611] - Placement Groups Detail Summary

package.json, packages/manager/.changeset/pr-10175-fixed-1707751671549.md, packages/manager/package.json
I assume the script was broken since the vite update. This small PR makes it available again via [vite-bunder-visualizer](https://www.npmjs.com/package/vite-bundle-visualizer#vite-bundle-visualizer)
- fix broken bundle analyzer script in package.json
- from the root, run `yarn build:analyze`
- see failure
- from the root, run `yarn build:analyze`
- confirm report opening in the browser
=> chore: [M3-7754] - fix bundle analyse script

packages/manager/CHANGELOG.md, packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx, packages/manager/src/features/VPCs/constants.ts
Updated "Learn more" docs link for IPv4 ranges
The "Learn more" link in the "Additional IPv4 ranges" section (in the VPC section of the Linode Create flow, in the Add/Edit Linode Config dialog for VPC interfaces, and in the VPC "Assign Linodes" drawer) should bring you to https://www.linode.com/docs/products/networking/vpc/guides/assign-services/
=> change: [M3-7755] – Update IPv4 range "Learn more" docs link

packages/api-v4/.changeset/pr-10176-upcoming-features-1707761577767.md, packages/api-v4/src/account/types.ts, packages/api-v4/src/profile/types.ts, packages/manager/.changeset/pr-10176-tests-1707761742808.md, packages/manager/.changeset/pr-10176-upcoming-features-1707761677226.md, packages/manager/cypress/e2e/core/account/account-login-history.spec.ts, packages/manager/cypress/e2e/core/account/change-username.spec.ts, packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts, packages/manager/src/factories/accountUsers.ts, packages/manager/src/factories/profile.ts, packages/manager/src/features/Account/AccountLogins.tsx, packages/manager/src/features/Account/CloseAccountSetting.tsx, packages/manager/src/features/Account/utils.ts, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.test.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.test.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/features/Users/UserRow.test.tsx
API has changed the `user_type` for regular (non parent/child/proxy) users to return "default" rather than `null`.
Since we've been basing our mocks off of a `null` user_type, this API update required some refactoring in the UI, as well as updates to tests (unit and Cypress).
- Updates `user_type` in `types.ts` apiv4 files to include `"default"` instead of `null` a valid value
- Updates factories
- Updates components, unit test, and Cypress tests that explicitly referred to `user_type: null` or used nullish coalescing to display UI components to a "regular" (non-parent/proxy/child) user.
- This includes fixing an issue that was causing the user menu to always display the company name above the username for any user type, which should *not* be visible to regular users.
| Before  | After …
=> change: [M3-7740] - Use "default" for  non-parent/proxy/child `user_type` instead of null

packages/manager/.changeset/pr-10186-changed-1707835872709.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
Updates the Linode Graph's X Axis to show **days** instead of **hours** on the x-axis when the user select a longer time period 📈
| ![Screenshot 2024-02-13 at 9 45 31 AM](https://github.com/linode/manager/assets/115251059/a73ef224-e655-43ae-b554-85c1c855c628) | ![Screenshot 2024-02-13 at 9 45 21 AM](https://github.com/linode/manager/assets/115251059/c9812c3a-ff53-49f6-8e90-e53e8ca0b503) |
- Make sure you have the `recharts` flag on
- Go to the Analytics tab of on a Linode's details page
- Try viewing the last 30 days or longer of stats
- Verify the X Axis is showing units in days instead of hours
- Verify the X Axis is user friendly
=> change: [M3-7735] - Improve Linode Graph X Axis Labels when viewing historic data

packages/manager/.changeset/pr-10183-tech-stories-1707777141390.md, packages/manager/src/components/Breadcrumb/FinalCrumb.tsx, packages/manager/src/components/Breadcrumb/types.ts, packages/manager/src/components/EditableText/EditableText.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/LinodeSettingsLabelPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, packages/manager/src/utilities/analytics.ts
In the breadcrumb on a Linode detail page, we want a custom event to track the use of the inline edit label feature.
- Adds `sendEditBreadcrumbEvent`, which fires whenever the edit (pencil) icon is clicked on a Linode's details page.
- Adds `sendUpdateLinodeLabelEvent`, which fires when the label is updated in the editable breadcrumb and when the label is updated on the Settings tab. 
| Component | Custom Event |
| --- | --- |
| ![image](https://github.com/linode/manager/assets/114685994/a99682f8-b969-4fa6-adf0-932904d96232) | ![image](https://github.com/linode/manager/assets/114685994/a9b69c0d-321e-4a9c-9d6c-d3d9b9d6f446) |
| ![Screenshot 2024-02-13 at 2 46 56 PM](https://github.com/linode/manager/assets/114685994/299c3e0d-8b77-492b-ab04-337a4ea41446) | ![Screenshot 2024-02-13 at 2 46 32 …
=> change: [M3-7731] - Tag breadcrumb label edit icon on Linode Details page for analytics

packages/manager/.changeset/pr-10197-fixed-1708020473057.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx
In our new Recharts graphs, the tooltip unit would sometimes not match the units that the graph was using. This PR fixes that issue. The graph's units (shown in the graph title), should match what is shown in the tooltip.
- De-ramda-ifyed the touched file 😤
- Removed unused `totalTraffic` prop 🗑️
- Fixed tooltip units 🔧
| Notice how the tooltip shows 31.63 Kb/s. This is not correct. It is really 31.63 Mb/s | Notice how the tooltip shows 31.63 Mb/s  |
| ![Screenshot 2024-02-15 at 12 56 13 PM](https://github.com/linode/manager/assets/115251059/4ae7de3e-54af-45f5-a7f4-2089e3469235) | ![Screenshot 2024-02-15 at …
=> fix: [M3-7758] - Linode Network Graph Tooltip - Incorrect Units

packages/manager/.changeset/pr-10162-upcoming-features-1708036002117.md, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.stories.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.test.tsx, packages/manager/src/components/RemovableSelectionsList/RemovableSelectionsList.tsx, packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx, packages/manager/src/factories/placementGroups.ts, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx, packages/manager/src/features/PlacementGroups/index.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/placementGroups.ts
This PR adds the delete placement group modal to the PG flow. It also touches a few components for some cleanup or enhancing (non breaking changes)
ℹ️ **CONTEXT**: The reason for adding the removable list in the delete modal is because (not unlike buckets) we can't delete a Placement Group that still has Linodes assigned to it
- Add the PG delete modal and its test
- Make sure inputProps are passed in `TypeToConfirmDialog `
- Allow RemovableSelectionsList to take a readable remove label + test update + story
⚠️ NOTE: this is MSW mock data so we won't get the proper UI data changes 👎 
- Have the "Placement Group" flag and MSW turned on
- Navigate to `http://localhost:3000/placement-groups`
- Click "Delete" for any placement group
- Confirm UI and MSW requests
- change the [factory …
=> upcoming: [M3-7618] - Delete Placement Group Modal

packages/manager/.changeset/pr-10202-tests-1708119481596.md, packages/manager/.changeset/pr-10202-upcoming-features-1708119409383.md, packages/manager/cypress/e2e/core/account/display-settings.spec.ts, packages/manager/cypress/e2e/core/account/user-profile.spec.ts, packages/manager/src/features/Account/constants.ts, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx, packages/manager/src/features/Profile/constants.ts, packages/manager/src/features/Users/UserProfile.tsx
In Cloud Manager, a proxy user cannot be deleted, nor can its email address or username be edited once it is provisioned. 
This PR is a follow up from #10103 which restricted proxy users from updating their username or email on the Display Settings page (http://localhost:3000/profile/display). There is one additional place that a proxy user could be edited, which is by visiting the User Profile page for the proxy user via URL. (The User Profile button is not visible for a proxy user on the Users & Grants page, http://localhost:3000/account/users.)
- Disables the username and email fields and the buttons on the proxy user's profile. Displays tooltips with reason for disabling.
- Separates out tests in `change-username.spec.ts` into two different …
=> upcoming: [M3-7775] - Disable ability to edit or delete a proxy user via User Profile page

packages/manager/.changeset/pr-10211-tests-1708466647763.md, packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts, packages/manager/cypress/support/intercepts/object-storage.ts, packages/manager/cypress/support/ui/autocomplete.ts
Adds a Cypress test to cover the OBJ Bucket creation flow when OBJ Multicluster is enabled. Using mock API data, it confirms that a bucket can be created, that Cloud uses a region ID rather than a cluster ID in its payload, and that the landing page updates to reflect the new bucket.
- Add a test for Bucket creation when OBJ Multicluster feature is enabled
- Update OBJ create mock util to be more consistent with other utils
- Add UI helper to find an autocomplete popper
- Add mock util for OBJ create error
We can rely on CI for this, or `yarn cy:debug` and search for `object-storage.smoke.spec.ts`
=> test: [M3-7434]: Add a Cypress test for OBJ Multicluster Bucket create flow

packages/manager/.changeset/pr-10215-fixed-1708555044784.md, packages/manager/src/features/Kubernetes/CreateCluster/NodePoolPanel.tsx
🐛  On the cluster creation page, if you remove an added node pool from the cluster summary, that plan in the node pool does not become re-enabled.
Fix: This was happening because the number of node pools in the map was being reset to 0 when a node pool was added to a cluster. When the number input is 0, the add button is disabled. We should not reset the number of node pools to 0 once it has been added to the pool.
- Removed the call to `updatePlanCount` in the handler for adding a node pool to a cluster. 
| <video src="https://github.com/linode/manager/assets/114685994/3ffc5437-9855-4bfb-90c5-498c441fa67b"/> |<video src="https://github.com/linode/manager/assets/114685994/302f2862-4e75-4b03-8d12-81371ed6c …
=> fix: [M3-7059] - Stop resetting count and disabling Add button when adding node pool to Kubernetes cluster

docs/.vitepress/config.ts, docs/.vitepress/plugins/sidebar.ts, docs/.vitepress/tsconfig.json, package.json, packages/manager/.changeset/pr-10214-tech-stories-1708552464325.md, packages/manager/tsconfig.json
- Updates the docs site sidebar to be generated based on file names and folder structure of the `docs/` folder 🗂️
- I think this will be nice because it will enable anyone to add documentation without needing to modify any Vitepress configuration 🔧
- Updates Vitepress to latest 🆕
| ![Screenshot 2024-02-21 at 3 46 12 PM](https://github.com/linode/manager/assets/115251059/df3feb8f-1d89-4969-b141-e6b801109f8a) | ![Screenshot 2024-02-21 at 4 45 18 PM](https://github.com/linode/manager/assets/115251059/a00d7f36-d174-4245-9f89-c80cd63f3784)  |
- Create a test markdown file at `docs/development-guide/example/testing.md` with some markdown in it
- Run `yarn docs`
- Go to `http://localhost:5173/manager/`
- Observe that the new docs …
=> poc: [M3-7799] - Improve Docs Site Sidebar

packages/manager/.changeset/pr-10223-tech-stories-1708637625570.md, packages/manager/src/components/Chip.stories.tsx, packages/manager/src/components/Chip.tsx, packages/manager/src/features/Databases/DatabaseLanding/DatabaseRow.tsx, packages/manager/src/features/Kubernetes/ClusterList/KubernetesClusterRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/KubeSummaryPanel.tsx, packages/manager/src/features/Linodes/LinodeEntityDetail.styles.ts, packages/manager/src/features/Linodes/LinodeEntityDetailHeader.tsx, packages/manager/src/utilities/noneSingleOrMultipleWithChip.tsx
After talking about Chips in our cafe meeting, I looked at the Chip component and I couldn't un-see some of this code 😩😤
This PR simplifies our override of MUI's `<Chip />` and removes some _styled components_ that went way too far
> [!note]
> The goal of this PR is to clean up Chip related code, but **not change to how it looks** 👁️  
|   ![Screenshot 2024-02-22 at 4 06 20 PM](https://github.com/linode/manager/assets/115251059/7bc17bc5-07ab-4e15-baf3-53b96a517887)     |  ![Screenshot 2024-02-22 at 4 06 48 PM](https://github.com/linode/manager/assets/115251059/5653ef45-606a-4edc-8a5a-17bea045e892)     |
|     ![Screenshot 2024-02-22 at 4 07 56 PM](https://github.com/linode/manager/assets/115251059/e51f5f4b-59c3-468b-8dd6-86292e7bb365)   | …
=> chore: [M3-7803] - Clean up `Chip` component

packages/manager/.changeset/pr-10230-upcoming-features-1708982538087.md, packages/manager/src/features/Users/UsersLanding.tsx
The filter we're applying to child accounts needs to be scoped to child users. Currently, with the parent/child flag on, all users are seeing an error.
From API: "Because this is a computed filter, the API only supports filtering on a single user_type (and no other complex filtering logic), which in this case would be `child`."
- Updated the filters on the `useAccountUsers` that populates the table of non-proxy users to only filter on `child` users when logged into a child  or proxy user account. API doesn't support complex filtering logic on this field.
- Fixed an issue where the `numCols` was dynamic for the users in the Business Partner table, and it should not have been. (We don't display the Child Account Access column there, as we do in the other table.)
> [!NOTE]  
> Test coverage …
=> fix: [M3-7811] - Fix Users & Grants query filtering on user_type

packages/manager/.changeset/pr-10231-fixed-1708986686253.md, packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx, packages/manager/src/foundations/themes/light.ts
The disabled styles for the textfield input are currently broken, ending up having to impact on the styling when a field is disabled.
I picked the same bg color for disabled state as Radio/Checkboxes for consistency
- Fix theme layer style declaration for Textfield disabled styles
- Add disabled cursor (**UX approved**)
| ![Screenshot 2024-02-27 at 08 20 00](https://github.com/linode/manager/assets/130582365/41709ded-a7ee-4029-ac5a-6712e33f0bec) | ![Screenshot 2024-02-27 at 08 20 00](https://github.com/linode/manager/assets/130582365/4e5991d1-f2c6-4035-889f-ac6acf080690) |
https://github.com/linode/manager/assets/130582365/ac78e971-ac88-4323-a7ef-dfbf321928ca
- Confirm the fix to the styles by all/either 
- using storybook or, in context (esp …
=> fix: [M3-7812] Textfield input disabled styles

packages/manager/.changeset/pr-10234-upcoming-features-1709068609413.md, packages/manager/.changeset/pr-10234-upcoming-features-1709068764309.md, packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts, packages/manager/src/features/Account/SwitchAccountDrawer.tsx
There were a few issues with proxy tokens and loading child users for proxy accounts.
- The prefix `Bearer` was missing from the proxy token sending us back to login upon switching.
- We were always passing the current token to `ChildAccountList` which prevented us from fetching child accounts while in a proxy account. This token needs to be the parent token when logged in as a proxy.
03/04/2024
https://github.com/linode/manager/assets/125309814/527048e9-531f-4979-8a0b-a726ba5569ef
- You need to create parent & child accounts (see me if you want to)
- Log into dev using parent account creds
- Open user menu and click "Switch Accounts"
- Observe children load
- Select any child accounts and observe page refresh 
- You should now be in proxy account
- Open …
=> upcoming: [M3-7814, M3-7819] - Fix Account Switching

packages/manager/.changeset/pr-10225-fixed-1708720961774.md, packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx, packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeCreateForm.tsx
This PR fixes a bad bug crashing the application when attempting to create a volume from the linode detail (storage tab).
The `useEffect` in question was attempting to select a default value for the config select component and set the value for the field, creating an infinite loop with the label validation of the formik form (expecting a non-falsy value).
It is a bit a of weird bug, which did not surface before the react 18 update and the way useEffect was optimized. I can't say I fully understand the clash between our `formik` initial values, `setFieldValue` and our validation patterns but the fix here is to `validateOnChange` only when the form has been submitted, not when `setFieldValue` is being called, since the useEffect is actually doing the right thing (esp for the …
=> fix: [M3-7804] - Volume Create Drawer Crash (Linode detail)

packages/manager/.changeset/pr-10225-fixed-1708720961774.md, packages/manager/.changeset/pr-10235-fixed-1709135736984.md, packages/manager/src/features/Volumes/VolumeDrawer/ConfigSelect.tsx, packages/manager/src/features/Volumes/VolumeDrawer/LinodeVolumeCreateForm.tsx
This PR fixes a bad bug crashing the application when attempting to create a volume from the linode detail (storage tab).
follow up to https://github.com/linode/manager/pull/10225 which did not fix it completely
The `useEffect` in question was attempting to select a default value for the config select component and set the value for the field, creating an infinite loop with the label validation of the formik form (expecting a non-falsy value).
It is a bit a of weird bug, which did not surface before the react 18 update and the way useEffect was optimized. I can't say I fully understand the clash between our `formik` initial values, `setFieldValue` and our validation patterns. The fix here is to avoid the useEffect all together
Due to another interesting fact, the e2e test was not breaking …
=> fix: [M3-7804] - LinodeVolumeCreateForm crash (for real this time)

packages/manager/.changeset/pr-10232-changed-1709130492234.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/LoadBalancerRegions.tsx
- Switches IAD out for Miami 🇺🇸 
- We are doing this for region availability reasons for the Beta period
3/4/2024
| ![Screenshot 2024-02-27 at 1 06 18 PM](https://github.com/linode/manager/assets/115251059/c1bc7479-a4c4-42ee-9f50-ddd39c8d28b0) | ![Screenshot 2024-02-27 at 1 06 14 PM](https://github.com/linode/manager/assets/115251059/87468ca8-8983-4221-a180-53260527105f) |
- Browse ACLB and verify that any place regions are displayed, you see `Miami, FL` and **not** `Washington, DC`
=> change: [M3-7815] - Change ACLB Beta Regions

packages/manager/.changeset/pr-10239-tests-1709145080838.md, packages/manager/cypress/vite.config.ts
Recent improvements to Cloud Manager's dev tools introduced various `MODULE_LEVEL_DIRECTIVE` and `SOURCEMAP_ERROR` console warnings when Cypress builds each spec file via Vite.
The cause of these warnings is relatively well-understood[1] and the underlying issue(s) are harmless and irrelevant from a Cloud Manager development perspective. This PR addresses the issue by using the `@vitejs/react-plugin-swc` plugin to suppress the `MODULE_LEVEL_DIRECTIVE` warning, and by manually supressing the related `SOURCEMAP_ERROR` warnings.
(1) MUI contains [`'use client'` module-level directives](https://react.dev/reference/react/use-client), which are intended to allow library developers to denote client-side and server-side code. Meanwhile, Rollup (and therefore Vite) [does not support module-level …
=> test: [M3-7820] - Suppress Cypress "MODULE_LEVEL_DIRECTIVE" and "SOURCEMAP_ERROR" warnings

packages/manager/.changeset/pr-10208-added-1708450451347.md, packages/manager/src/features/Billing/InvoiceDetail/InvoiceDetail.tsx, packages/manager/src/features/Billing/PdfGenerator/utils.ts
In an effort to clarify to customers that they are being charged for powered-down (shutdown) instances, we want to add the following byline to customer invoices:
```
This invoice may include Linode Compute Instances that have been powered off as the data is maintained and resources are still reserved. If you no longer need powered-down Linodes, you can <a href="https://www.linode.com/docs/products/platform/billing/guides/stop-billing/">remove the service</a> from your account.
```
>[!note]
Adding a link in the PDF added a lot of complexity, so I reached out to Customer Success and they seemed fine with spelling out the link. Open to suggestions to make that better.
- Updated generated PDF with logic to smartly break to new page if content doesn't fit
- Added copy to Cloud Manager invoice …
=> feat: [M3-7577] - Add invoice byline for powered down instances

packages/manager/.changeset/pr-10167-tests-1709236661581.md, packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
Add regression tests to check Images landing page empty state.
- Add regression tests to check the empty state in Images landing page.
```
yarn cy:run -s "cypress/e2e/core/images/images-empty-landing-page.spec.ts"
```
=> test: [M3-7452] - Add Cypress test to check empty state in Images landing page

packages/manager/.changeset/pr-10238-upcoming-features-1709143092179.md, packages/manager/src/__data__/regionsData.ts, packages/manager/src/components/RegionSelect/RegionSelect.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.tsx, packages/manager/src/components/RegionSelect/RegionSelect.types.ts, packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.ts, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx, packages/manager/src/mocks/serverHandlers.ts
We want to cultivate that edge instances are different from core instances. So, migrating a Linode instance from core to edge or from edge to core should not be possible. Only edge-to-edge migrations and core-to-core migrations should be possible.
- Hide core regions if the current Linode is in an edge region
- Hide edge regions if the current Linode is in a core region
- Open the Migrate Linode dialog via the Linodes landing table dropdown action or Linode details header dropdown action
- Observe the current region is an edge region and the New region input only contains edge regions
- Change line `770` in `serverHandlers.ts` to a core region like `us-east`
- Hard refresh the page and open the Migrate …
=> upcoming: [M3-7727] - Only support Edge to Edge Migrations

packages/manager/.changeset/pr-10204-tests-1708976001328.md, packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts, packages/manager/cypress/support/constants/user.ts
Add regression tests for checking child user verification banner
- Add regression tests to check child user verification banner
```
yarn cy:run -s "cypress/e2e/core/account/user-verification-banner.spec.ts"
```
=> test: [M3-7497] - Add tests for child user verification banner

packages/manager/src/queries/base.ts
With React Query, it is reccomneded that you update the cache in an "immutable" way. 
Essentially, we were updating the cache, but the changes were not getting propagated and rendered because updating an existing value within the same array. The fix in this case to just copy the array before committing to the cache. 
See https://tanstack.com/query/v4/docs/framework/react/guides/updates-from-mutation-responses#immutability
> [!note]
> This PR fixes Cypress test failures in `machine-image-upload.spec.ts`
- Run `yarn cy:debug` and watch the `uploads machine image, mock finish event` test. After `@getImage`, we should see the changes render immediately and the test should pass.
=> fix: React Query `updateInPaginatedStore` helper function not working as expected

docs/development-guide/05-fetching-data.md, docs/tooling/react-query.md, packages/manager/.changeset/pr-10241-tech-stories-1709241014115.md, packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts, packages/manager/package.json, packages/manager/src/features/Profile/AuthenticationSettings/PhoneVerification/PhoneVerification.tsx, packages/manager/src/features/Profile/AuthenticationSettings/TwoFactor/TwoFactor.tsx, packages/manager/src/features/StackScripts/StackScriptCreate/StackScriptCreate.tsx, packages/manager/src/hooks/useInitialRequests.ts, packages/manager/src/queries/base.ts, packages/manager/src/queries/databases.ts, packages/manager/src/queries/domains.ts, packages/manager/src/queries/firewalls.ts, packages/manager/src/queries/images.ts, packages/manager/src/queries/kubernetes.ts, packages/manager/src/queries/linodes/linodes.ts, packages/manager/src/queries/nodebalancers.ts, packages/manager/src/queries/placementGroups.ts, packages/manager/src/queries/profile.ts, packages/manager/src/queries/tokens.ts, packages/manager/src/queries/volumes.ts, yarn.lock
- Based on our discussion, we decided that our own Query Key factory was slowly becoming more like  `@lukemorales/query-key-factory` so we are going to proceed with `@lukemorales/query-key-factory` 🏭 
- This PR updates profile queries to use the new query key factory 🎉 
- Fixes duplicate `GET /v4/profile` when Cloud Manager loads
- If we are happy with how this looks, we will start using this and refactoring old query keys!
- Test all profile related features 👤 
- Use the React Query dev tools and verify profile query keys look as expected 🔧 
- Verify that parent child features still work 👪
=> refactor: [M3-7437] - Use `@lukemorales/query-key-factory` for Profile Queries

packages/manager/.changeset/pr-10252-upcoming-features-1709581147040.md, packages/manager/src/features/Users/UsersLanding.tsx, packages/manager/src/features/Users/UsersLandingProxyTableHead.tsx, packages/manager/src/features/Users/UsersLandingTableBody.tsx, packages/manager/src/features/Users/UsersLandingTableHead.tsx
Navigating through different breakpoints in the application, I notice that the loading state columns are misaligned. This inconsistency is particularly noticeable for normal users, parent users with additional "child account access" column, and proxy users where the "last login" column is removed. To enhance the user experience and ensure clarity in data presentation, we need to account for these variations in column arrangement and loading state across breakpoints.
In addition, if the proxy user doesn't have full access - we should disable the query to fetch the proxy user in the table instead of returning "Unauthorized".
- Adjusting column count based on the three conditions described.
- Adding `whiteSpace: 'nowrap'` to prevent excessive collapsing as we scale down breakpoints. It's not …
=> upcoming: [M3-7835] - Adjust user table column count

packages/manager/.changeset/pr-10259-upcoming-features-1709654629410.md, packages/manager/cypress/e2e/core/account/account-login-history.spec.ts, packages/manager/cypress/e2e/core/account/user-permissions.spec.ts, packages/manager/cypress/e2e/core/account/user-profile.spec.ts, packages/manager/cypress/e2e/core/account/user-verification-banner.spec.ts, packages/manager/src/features/Account/constants.ts, packages/manager/src/features/Account/utils.ts, packages/manager/src/features/Users/UserPermissions.tsx, packages/manager/src/features/Users/UserProfile.tsx, packages/manager/src/features/Users/UsersLanding.tsx
We're making a copy change to the way we represent the reseller.
- Change Business Partner to Parent User
3/18
| Screenshots  |   |
| ![Screenshot 2024-03-05 at 10 43 07 AM](https://github.com/linode/manager/assets/125309814/8117469b-c973-40fe-a5a6-2047fe36508b) | ![Screenshot 2024-03-05 at 10 42 39 AM](https://github.com/linode/manager/assets/125309814/051875a0-1007-4c71-8cb9-ba10d012747c) |
|![Screenshot 2024-03-05 at 10 42 31 AM](https://github.com/linode/manager/assets/125309814/1dc82a34-ceef-4c3f-99aa-cc13c43a0872)|![Screenshot 2024-03-05 at 10 52 28 AM](https://github.com/linode/manager/assets/125309814/4271d14b-22dd-40c7-8143-c991a5a10e33)|
- Update `parent` to `child` in …
=> upcoming: [M3-7839] - Change Business Partner to Parent User

packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.test.tsx, packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx, packages/manager/src/features/Account/CloseAccountDialog.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/DeleteKubernetesClusterDialog.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
We currently don't have the possibility of disabling the TypeToConfirm input (only its submit button).
In the case of a TypeToConfirm Modal where an action needs to be taken before being abled to delete the entity, we want to be able to disable the input in order for the user to not fill and then to realize they still can't delete it.
This is the case for the `PlacementGroupDeleteModal` for which we need to delete all attached Linodes in order to delete the PlacementGroup
- Add new `disableTypeToConfirmInput` prop to allow disabling the input 
- Improve naming conventions
- Improve test coverage
- Have both the "Placement Group" feature flag and MSW turned on
- Navigate to http://localhost:3000/placement-groups/delete/1
- Confirm …
=> change: [M3-7813] - Allow the disabling of the TypeToConfirm input

docs/development-guide/11-feature-flags.md, packages/manager/.changeset/pr-10256-upcoming-features-1709671609446.md, packages/manager/src/components/DetailsPanel/DetailsPanel.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx
This PR introduces JSON payload for the Placement Group feature.
- Add new flag in Launch Darkly with JSON payload variations (will delete old one once this is merged to production)
- Apply to flag to codebase
- Modify Flag Dev Tools to handle JSON object (with `enabled` key)
- Update Feature Flag documentation
- Pull code locally
- Open Cloud Manager Dev Tools and click on the "Reset to LD default flags" button.
- Confirm the toggling of the Placement Groups feature flag and other flags (no regression)
=> upcoming: [M3-7723] - Placement Group feature flag as object

packages/manager/.changeset/pr-10245-tests-1709311899662.md, packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts, packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts, packages/manager/cypress/support/intercepts/account.ts
This resolves the test failures that we've recently been seeing in `object-storage.e2e.spec.ts`. There are a couple issues at play that contribute to these failures:
- After a Bucket has been created, the landing page re-renders (presumably in response to some API request resolving), causing occasional failures when the re-render occurs after Cypress has located some element (e.g. the "Delete" table row button) but before it has interacted with it. (I think this is irrelevant from a user experience point of view)
- Less frequently, the test fails due to an issue with the Buckets landing page where the page fails to display a newly created Bucket if the Bucket was created before the initial requests to fetch Buckets have all completed (see M3-7833)
This PR only seeks to resolve test …
=> test: Resolve OBJ create and delete E2E test flake

packages/api-v4/.changeset/pr-10264-changed-1709750042330.md, packages/api-v4/src/aclb/types.ts, packages/manager/.changeset/pr-10264-fixed-1709749998087.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-routes.spec.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.test.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/RuleDrawer.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/RuleRow.tsx, packages/validation/.changeset/pr-10264-changed-1709750194085.md, packages/validation/src/loadbalancers.schema.ts
- Fixes rule creation by not sending `match_condition` in the payload for TCP rules 🧰 
- Improves the service target tooltip 🎨 
- Fixes TTL alignment issue 🔘 
| <video src="https://github.com/linode/manager/assets/115251059/4b333dd8-c5f4-4066-9ac9-a51ba7afea64" /> | <video src="https://github.com/linode/manager/assets/115251059/cabbff0e-fe84-4330-8efc-fb46dde09143" />  |
| ![Screenshot 2024-03-06 at 11 56 05 AM](https://github.com/linode/manager/assets/115251059/25028461-219a-4108-9828-607d6dea04c5) | ![Screenshot 2024-03-06 at 11 55 58 AM](https://github.com/linode/manager/assets/115251059/9d433f3a-18fa-432b-a892-32406b17f673) |
| ![Screenshot 2024-03-06 at 11 56 44 AM](https://github.com/linode/manager/assets/115251059/9e386f0c-bba9-43b7-b20e-4 …
=> fix: [M3-7824] - ACLB TCP Rule Creation and other fixes

packages/manager/.changeset/pr-10267-tests-1709834235631.md, packages/manager/cypress/e2e/core/images/images-empty-landing-page.spec.ts
This is a tiny fix for a test flake issue in `images-empty-landing-page.spec.ts`. Clicking "Create Image" directs to `images/create` which quickly redirects to `images/create/disk`. Most of the time Cypress is able to assert that the URL did end with `images/create`, but because it redirects so quickly the assertion occasionally fails.
This fixes the issue by checking for `images/create/disk` instead. I'm mostly interested in fixing this for the performance benefit; it doesn't seem like this has ever led to an actual test failure, but does cause flake pretty often.
We can lean on CI, or
```bash
yarn cy:run -s "cypress/e2e/core/images/images-empty-landing-page.spec.ts"
```
=> test: Fix test flake for Images landing page test

packages/manager/.changeset/pr-10263-upcoming-features-1709749179406.md, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx, packages/manager/src/features/PlacementGroups/constants.ts, packages/manager/src/hooks/usePlacementGroupsData.ts, packages/manager/src/mocks/serverHandlers.ts
Pretty simple PR to update the assign linode drawer. Due to some recent UX changes, the decision was made to assign one linode at a time in the drawer and remove the current experience with the unassign selectable list inside the drawer.
- Simplify Assign Linode Drawer logic and adjust tests
- Rename "edit" to "assign" through the feature
- Improve query skipping where relevant
- Turn on both the "Placement Groups" feature flag and MSW
- Navigate to http://localhost:3000/placement-groups/1/linodes/assign
- Click on "Assign Linode to Placement Group"
- Confirm Drawer appearance and behavior
=> upcoming: [M3-7842] - Update Assign Linode Drawer and improve query skipping

packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
We had to adjust the logic for `isChildAccountAccessRestricted` to parent users only since this is where the grant can be toggled. This was being applied to the proxy user inadvertently preventing the proxy from switching to accounts.
- Added E2E test for this use-case
3/18
See testing instructions: https://github.com/linode/manager/pull/10237
=> upcoming: [M3-7816-v2] - Adjust logic for when to show Switch Account button

docs/development-guide/13-coding-standards.md, packages/manager/.changeset/pr-10261-tech-stories-1709842863706.md, packages/manager/src/components/GroupByTagToggle.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx, packages/manager/src/features/Linodes/LinodesLanding/DisplayGroupedLinodes.tsx, packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx, packages/manager/src/features/Linodes/LinodesLanding/SortableTableHead.tsx
With our recent upgrade to React 18, we can begin making use of new hooks that were introduced with that version. This PR implements `useId()` in a few files.
- **useId**
- One potential use case we discussed early on was using this hook for generating unique IDs for React list items, but the [docs](https://react.dev/reference/react/useId#usage) explicitly state this should not be done. Of the scenarios outlined in the "Usage" section of the docs, the most relevant one for us is generating unique IDs for accessibility attributes.
- **useTransition**
- Our use of React Query and reliance on the loading state it provides makes `useTransition` mostly superfluous to us.
- **useDeferredValue** 
- May have some applicability, but it cannot be used as a 1:1 replacement everywhere we do …
=> refactor: [M3-6708] – Implement new React 18 hooks

packages/manager/.changeset/pr-10271-changed-1710174159065.md, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/constants.tsx, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Routes/utils.ts
We were not recommending  valid values to the user. This PR updates our placeholders and tooltips to use the correct format of `key=value`
| ![Screenshot 2024-03-11 at 12 03 00 PM](https://github.com/linode/manager/assets/115251059/3487eb34-8208-439b-9597-32fba4d31a18) | ![Screenshot 2024-03-11 at 12 02 35 PM](https://github.com/linode/manager/assets/115251059/a9cc3ea0-234f-4fe8-aab3-d068d7d277a0) |
- Use the MSW, `dev-test-aglb`, or `prod-test-065`
- Go the an existing ACLB
- Go to the **routes tab**
- **Create a route** if none exits
- On a route, open the **add rule drawer**
- In this drawer, verify the tooltip and placeholder text uses **`key=value`** format for **header** and **query string** matches
=> change: [M3-7856] - Update ACLB Match Condition Tooltips and Placeholders

packages/manager/.changeset/pr-10270-upcoming-features-1710171371281.md, packages/manager/cypress/e2e/core/account/display-settings.spec.ts, packages/manager/cypress/e2e/core/account/personal-access-tokens.spec.ts, packages/manager/cypress/e2e/core/account/user-profile.spec.ts, packages/manager/src/MainContent.tsx, packages/manager/src/features/Account/CloseAccountSetting.test.tsx, packages/manager/src/features/Account/CloseAccountSetting.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.tsx, packages/manager/src/features/Account/constants.ts, packages/manager/src/features/Billing/BillingPanels/ContactInfoPanel/UpdateContactInformationForm/UpdateContactInformationForm.tsx, packages/manager/src/features/Profile/APITokens/APITokenMenu.tsx, packages/manager/src/features/Profile/APITokens/APITokenTable.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
This PR addresses some updating messaging and account management fixes / improvements.
- Update Proxy Account Tooltip (Proxy User):
- When attempting to close an account as a proxy user, the tooltip should now read: "Contact customer support to close this account."
- Clarify Account Closure Instructions (Proxy User):
- Change the tooltip text from "Remove indirect customers before closing the account." to "Remove child accounts before closing the account."
- Update Account Login Indicator (General):
- Modify the account indicator text from "You are currently logged in as:" to "Current account:"
- New PAT Tooltip for Proxy View (Proxy User):
- For proxy users, introduce a new tooltip for disabled Personal Access Tokens (PAT) creation with the text: "You can't perform this action on child …
=> upcoming: [M3-7857] - Account Management Copy Updates & Improvements

packages/manager/src/features/TopMenu/UserMenu/UserMenu.test.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/features/TopMenu/UserMenu/utils.test.ts, packages/manager/src/features/TopMenu/UserMenu/utils.ts
In #10248, I didn't test the regular user experience thoroughly enough, because the conditional logic was defaulting to the profile email of the user if no company name was set, even if the user was not a parent/child/proxy account. We don't want this. 
We **should** see the following:
- For a regular (default) user, there should be no changes to the top menu and user menu (i.e. it should display username only). 
- For parent/child/proxy users, the top menu should display username and company names. 
- For parent/proxy users, the user menu dropdown should display the company name.
- For **restricted parent users who do not have `account_access` set to at least `read_only`**, the top menu should display username and email (in place of company).
For **restricted parent users who do not have …
=> fix: [M3-7826-v2] - Fix email displaying in top menu for all users without a company name

packages/manager/.changeset/pr-10279-fixed-1710360079232.md, packages/manager/src/components/MultipleIPInput/MultipleIPInput.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRuleForm.tsx
There was an issue where on first page load where the `IP / Netmask` input fields weren't populating properly when you first open the firewall rules drawer.
- Remove the autoFocus which we don't need. We could technically keep this, but just seemed odd that we wanted to focus those fields apart from all the other relevant fields.
- Root issue was we're overriding our IPs when an input is blurred. I added a check to ensure the value is not empty before we attempt to call onBlur and set our state
3/18
| <video src="https://github.com/linode/manager/assets/125309814/bd1cb6f7-44a6-49cd-a317-274c5bac00d3" /> | <video src="https://github.com/linode/manager/assets/125309814/25ecd4c3-3d09-4fc2-9626-153565918479" /> |
Initial / Secondary Render
- Create …
=> fix: [M3-7867] -Ensure IP / Mask for firewall rules drawer correctly populates

packages/manager/.changeset/pr-10280-added-1710363273220.md, packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeCards.tsx, packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeRow.tsx, packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodeTable.tsx
Address refinements identified during the review process for Clone UI changes
- Don't need to make a request for every Linode in the Table view since we already have the data
- No more jumpy loading spinners
- Added "No results" state for mobile card view
| ![image](https://github.com/linode/manager/assets/115299789/1c7306c8-2263-4eee-99e6-1b67c4f33f67) | ![image](https://github.com/linode/manager/assets/115299789/122c25e4-029f-4210-94a5-378b6d481183) |
| <video src="https://github.com/linode/manager/assets/115299789/9ecd7360-96e4-4ac7-965b-db0b492598de" /> | <video src="https://github.com/linode/manager/assets/115299789/71a9936e-c16c-4eda-b2c9-58bba90597ae" /> | 
- Go to the Clone Linode page and observe that a network …
=> feat: [M3-7829] - Linode Clone UI refinements

packages/manager/.changeset/pr-10284-upcoming-features-1710432233464.md, packages/manager/src/features/Images/ImageUpload.tsx, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/AddIPDrawer.tsx, packages/manager/src/features/Linodes/MigrateLinode/CautionNotice.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Address feedback from the Gecko Beta Demo/Review meeting
- Warning notice updates
- Add period to end of sentences
- Replace "standard pricing" warning text from the edge plan table to "billing"
- Add warning text to the caution notice for edge migrations
- Storage table column should display as normal (should not be N/A) for edge plans
- Filter edge regions from Image Upload
| ![image](https://github.com/linode/manager/assets/115299789/82cd337f-7ab2-4786-aca6-f306e912fcee) | ![image](https://github.com/linode/manager/assets/115299789/2557692f-096c-451e-a8bb-ac4deb202a65) |
| ![image](https://github.com/linode/manager/assets/115299789/e01663de-1abd-4c3a-9419-3b9be6f1b25c) | ![image](https://github.com/linode/manager/assets/115299789/bf3451a9-a339 …
=> upcoming: [M3-7868] - Gecko Beta Demo feedback

packages/api-v4/.changeset/pr-10291-tech-stories-1710770920874.md, packages/api-v4/package.json, packages/manager/.changeset/pr-10291-tech-stories-1710770854595.md, packages/manager/package.json, yarn.lock
- Bumps our `axios` version so that `follow-redirects` gets bumped for CVE-2024-28849
- Resolves https://github.com/linode/manager/pull/10290
| ![Screenshot 2024-03-18 at 10 02 55 AM](https://github.com/linode/manager/assets/115251059/5f645d71-e5a9-4b89-8867-5504f2dfbe48) | ![Screenshot 2024-03-18 at 10 01 55 AM](https://github.com/linode/manager/assets/115251059/fa1abfaa-4762-457c-b57c-1476eef04729) |
- Run `yarn` for good measure (installs dependencies)
- Run `yarn why follow-redirects` and verify we are on `follow-redirects` >= 1.15.6
=> chore: Update `axios` to resolve `follow-redirects` CVE-2024-28849 

packages/manager/src/features/Linodes/SMTPRestrictionText.test.tsx
- Fixes breakage in `SMTPRestrictionText.test.tsx` because I merged after the MSW Change
- `yarn test SMTPRestrictionText.test.tsx`
=> fix: `SMTPRestrictionText.test.tsx` MSW Change

packages/manager/src/features/Linodes/LinodesCreate/SelectLinodePanel/SelectLinodePanel.tsx
The new clone UX changes introduce a bulleted list of notices. Until that feature flag is switched on, the list is currently displaying as a bulleted list containing a single notice.
4/1
| ![Screenshot 2024-03-19 at 4 27 24 PM](https://github.com/linode/manager/assets/122488130/c348ece5-16f0-418d-a2e4-ab6bcef6577f) | ![Screenshot 2024-03-19 at 4 28 58 PM](https://github.com/linode/manager/assets/122488130/fbb4be68-1630-49ed-a4be-2f739f033588) |
| With feature flag enabled ![Screenshot 2024-03-19 at 4 31 52 PM](https://github.com/linode/manager/assets/122488130/134a7a0f-1b81-4a87-b369-a8c1dd1d83ea) | (Unchanged) |
- Ensure "Linode Clone UI Changes" feature flag turned off
- Navigate to Clone Linode UI
- Verify notice doesn't appear as a bullet
- …
=> fix: [M3-7894] - Hide bullet for single notice

packages/api-v4/src/placement-groups/types.ts, packages/manager/.changeset/pr-10300-upcoming-features-1711040772223.md, packages/manager/src/__data__/linodes.ts, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx, packages/manager/src/factories/linodes.ts, packages/manager/src/factories/placementGroups.ts, packages/manager/src/features/Linodes/LinodesCreate/AddonsPanel.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.test.tsx, packages/manager/src/features/PlacementGroups/utils.test.ts, packages/manager/src/features/PlacementGroups/utils.ts, packages/manager/src/hooks/usePlacementGroupsData.ts, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/placementGroups.ts
This PR implements the necessary types/payload necessary changes noticed when testing the Placement Groups feature in Alpha. Some of those were not communicated to us and added to the API specs afterwards. 
The good news is: Placement Groups can now partially be tested with a real API 🎉 
Endpoints implemented so far:
- `PUT /v4/placement/groups/:id`
- `DELETE /v4/placement/groups/:id`
- `POST /v4/placement/groups`
- `GET /v4/placement/groups/:id`
- `GET /v4/placement/groups`
which means that a few things still won't work:
- assigning linodes to a PG
- unassigning linodes to a PG
- getting region limits (max amount of PG/customer, max amount of Linodes/PG/Region
- squeezed in:
-  a small fix to control the PG select component so the value of a newly created PG gets selected on the linode …
=> upcoming: [M3-7871] - Placement Groups in alpha - type updates

packages/manager/.changeset/pr-10304-upcoming-features-1711050408019.md, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Very simple PR to add a placement group display section to the checkout summary: "Assigned to Placement Group"
- Add placement group display section to the checkout summary
- Have both the "Placement Group" feature flag and MSW enabled
- Go to http://localhost:3000/linodes/create
- Select the "Newark, NJ" region
- Scroll to the Details panel
- Select a placement group in the drop down
- Confirm the "Assigned to Placement Group" item in the checkout summary at the bottom of the page
=> upcoming: [M3-7431] - Add placement group to checkout summary

packages/manager/.changeset/pr-10303-fixed-1710976860713.md, packages/manager/src/features/Users/UsersLanding.tsx, packages/manager/src/features/Users/UsersLandingTableBody.tsx
Recently, we lost loading state on the Users table on the Users & Grants page. In the UI, this means we'd go directly from the empty state table ("No items to display.") to the full list of users, once the request returned the data. 
We attempted to throw in a bug fix for perpetually loading table state for a restricted user in #10233, and inadvertently broke the loading state for other users. This PR has the real fix for the original issue we were seeing, which stems from a [breaking change in TanStack Query v4](https://github.com/TanStack/query/issues/3584). TLDR: when a query is disabled, `isLoading` will perpetually return `true`. Since we disable the useAccountUsers query for a restricted user, that would be the case here (and therefore we got stuck in loading table state.)
- Replace …
=> fix: [M3-7881] - Restore loading state to Users & Grants table

packages/manager/.changeset/pr-10305-upcoming-features-1711059101461.md, packages/manager/src/features/Users/UsersLanding.tsx
We should make a UI change to only display the Child Account Access column for users with the `child_account_access` grant enabled.
This is a place where we missed the grant check for a restricted parent. Since this is a restricted user they won’t ever see anything more than that column header without Full Account Access, so this is minor. But, to maintain consistency, a restricted parent user without the child account access grant should not see any UI features related to Parent/Child. 
- Adds a grant check for `child_account_access` to determine whether to display the Child Account Access column header
4/1/24
| ![Current](https://github.com/linode/manager/assets/114685994/d0849d71-55c2-4ae4-9e1b-b4d1071ff35e) | …
=> fix: [M3-7909] - Hide the Child Account Access table header for parent users without `child_account_access` grant

packages/manager/.changeset/pr-10306-tech-stories-1711123927073.md, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodeEntityDetail.test.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.test.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.test.tsx
Following up on #10299, this PR removes the VPC feature flag from `featureFlags.ts`, removes it from our feature flag DevTool, and cleans up a few unit tests accordingly.
After the next release, the LD flag will be archived.
04/01/2024
- `InterfaceSelect.test.tsx`, `LinodeConfigDialog.test.tsx`, `LinodeEntityDetail.test.tsx` should pass
- VPC should no longer be an option in our feature flag DevTool
=> refactor: [M3-7895] – Remove VPC feature flag

packages/manager/.changeset/pr-10308-upcoming-features-1711132212593.md, packages/manager/src/features/Linodes/LinodeCreatev2/Access.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Access.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx, packages/manager/src/foundations/themes/light.ts
- Adds the Password and SSH Key section to the new Linode Create flow 🆕 
- Fixes issue where there was too much space between the general error and the tabs 🔧 
You can test via the preview link if you want!
- Make sure the `Linode Create v2` feature flag is toggled **on** using our dev tools
- Go to http://localhost:3000/linodes/create and test general functionality
- Check my code 👨‍💻 
- Make sure my unit tests are sufficient 🧪
=> upcoming: [M3-7879] - Linode Create Refactor - Part 4 - Access

packages/manager/.changeset/pr-10311-changed-1711378782884.md, packages/manager/cypress/e2e/core/loadBalancers/load-balancer-configurations.spec.ts, packages/manager/src/features/LoadBalancers/LoadBalancerDetail/Configurations/ConfigurationForm.tsx, packages/validation/.changeset/pr-10311-changed-1711379618292.md, packages/validation/src/loadbalancers.schema.ts
Updates the ACLB configuration to prevent users from running into an API error.
New API validation was added that will throw if you try to send `certificates` with a `http` or `tcp` configuration. We now need to make sure we don't send certificates if the user selects `http` or `tcp` for their configuration
- Login to `dev-test-aglb`
- Go to http://localhost:3000/loadbalancers/38/configurations/17
- Without this PR checked out, you will observe that you can't change an HTTPS configuration to a HTTP or TCP. You would get an error saying `Certificate table must be empty with configuration protocol "http"`
- Test creating/updating a configuration
- Test with various different **certificate** / **protocol** combinations
- Ensure the form works as expected
=> change: [M3-7922] - Clear ACLB configuration certificates if `http` or `tcp` protocol is selected

packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts
Add regression tests to check Parent/Child Close Account flows
- Add new tests to tests to check Parent/Child Close Account flows
```
yarn cy:run -s "cypress/e2e/core/account/account-cancellation.spec.ts"
```
=> test: [M3-7508] - Add tests to check Parent and Child Close Account flows

packages/manager/.changeset/pr-10312-upcoming-features-1711384895230.md, packages/manager/src/components/ConfirmationDialog/ConfirmationDialog.tsx, packages/manager/src/components/Drawer.tsx, packages/manager/src/components/TypeToConfirmDialog/TypeToConfirmDialog.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx, packages/manager/src/features/PlacementGroups/types.ts
This PR brings UI improvements to both the PG Edit Drawer & Delete Modal. Now that the feature is in ALPHA, it is easier to implement the right patterns (loading, error handling) to both these flows.
- Add new `onExited` optional prop to Dialog and Drawer in order to reset state/data when closing animation completes (see https://github.com/linode/manager/pull/10287 and cafe item for reference)
- **Delete Modal**: 
- Notice: remove second bullet point notice (turn it into regular notice (no bullet) when no linode is attached) & remove linode list, only keep type to confirm when no linode is attached
- Improve error and loading patterns
- Edit Drawer
- Improve error and loading patterns
| Delete Modal  | Edit Drawer   |
| <video …
=> upcoming: [M3-7903] - Placement Groups: Edit Drawer & Delete Modal UI Updates

packages/manager/.changeset/pr-10315-upcoming-features-1711410039390.md, packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
- Adds the ability to attach a Firewall to a Linode in the new Linode Create Flow 🔥
- Turn on the `Linode Create v2` feature flag using the local dev tools
- Test creating a Linode with a firewall attached
- Verify you can create a Firewall from the Linode Create Flow
- Verify functionality is the same as the existing create flow
=> upcoming: [M3-7925] - Linode Create Refactor - Add Firewall - Part 5

packages/manager/.changeset/pr-10314-upcoming-features-1711460549811.md, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/queries/placementGroups.ts
Small PR to being key factory to placement groups and update some naming conventions. Please see the self review for  more contextual info about about the invalidation choices (or lack thereof).
- Compose new key factory
- Implement factory keys in queries
- Rename `useUnpaginatedPlacementGroupsQuery` with `useAllPlacementGroupsQuery`
No change/regression to the UI is to be expected with this PR
- ⚠️⚠️ have the dev admin placement-group customer tag ⚠️⚠️
- Switch to the dev API
- Have the "Placement Group" feature flag on
- Have MSW off
- Navigate to http://localhost:3000/placement-groups
- Confirm the overall behavior when creating, editing, deleting PGs, and creating a new linode with a PG 
=> upcoming: [M3-7840] - Placement Groups Query Key Factory

packages/manager/.changeset/pr-10313-upcoming-features-1711398916591.md, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.tsx, packages/manager/src/features/Account/utils.ts, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/hooks/usePendingRevocationToken.test.ts, packages/manager/src/hooks/usePendingRevocationToken.ts
As a user who frequently switches between accounts, I notice that proxy tokens (PATs) accumulate when switching into the same account repeatedly. To mitigate this, we want to ensure that we automatically revoke proxy tokens whenever a user switches accounts.
- New `usePendingRevocationToken` hook with accompanying unit test.
- Needed to consolidate code required for both `UserMenu` and `AccountLanding` 
- Added `getPersonalAccessTokenForRevocation` to compare the token we have in local storage to what we have stored in our database from the API endpoint.
4/1
| <video src="https://github.com/linode/manager/assets/125309814/d0453e41-86cf-40ab-a73b-dc983ef249e3" /> | <video src="https://github.com/linode/manager/assets/125309814/17d5418b-4cf3-4382-8 …
=> feat: [M3-7888] - Revoke proxy PAT when switching accounts

packages/api-v4/.changeset/pr-10319-changed-1711487054721.md, packages/api-v4/.changeset/pr-10319-changed-1711487087221.md, packages/api-v4/src/linodes/types.ts, packages/manager/.changeset/pr-10319-upcoming-features-1711487110394.md, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Addons.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/Backups.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/PrivateIP.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.test.ts, packages/manager/src/features/Linodes/LinodeCreatev2/Addons/utilities.ts, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx, packages/validation/.changeset/pr-10319-changed-1711487139814.md, packages/validation/src/linodes.schema.ts
Adds the "Add-ons" section to the new Linode Create Flow 🎉 
- Adds the "Add-ons" section to the new Linode Create flow
- The ability to add a private IP 🔌  
- The ability to enable backups 💾 
- Adds jsdoc style comments to the Linode Create type in api-v4 📝 (copy paste from API spec)
- Allows `firewall_id` to be null in the Linode Create type because the API allows it ✅ 
- Turn on the new Linode Create Flow feature flag using your local dev tools 🎏  (you can use the preview link or checkout this PR)
- Go to the Linode Create Flow
- Test general create flow functionality
- Test both the `Private IP` checkbox and the `Backups` checkbox ☑️ 
- Check my code for anything unreadable or questionable 📖 
- Verify unit tests are sufficient 🧪
=> upcoming: [M3-7927] - Linode Create Refactor - Part 6 - Add-ons

packages/manager/.changeset/pr-10324-fixed-1711637470278.md, packages/manager/src/features/Databases/DatabaseDetail/index.tsx
Fix issues with the Resize tab and Settings tab when the "databaseResize" feature flag is turned off in the alpha.
| <img src="https://github.com/linode/manager/assets/157619599/abd47813-a4b6-4961-8dde-d1ffe6a11d46" width="400" /> | <img src="https://github.com/linode/manager/assets/157619599/cc4bdfd4-963f-4526-93dc-04aef6ae5b98" width="400" />
|<img src="https://github.com/linode/manager/assets/157619599/ef232596-20b3-4350-a200-0f887e75a396" width="400" />  | <img src="https://github.com/linode/manager/assets/157619599/0b9e4371-389c-4370-93b5-c37fe8cb1ba3" width="400" />
Open application, navigate to /databases, select the database cluster. If feature flag is turned on go to the Resize tab. If feature …
=> fix: [UIE-7491] - Hide DBaaS resize tab behind feature flag

packages/manager/.changeset/pr-10320-fixed-1711553963315.md, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeRow.tsx, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.styles.ts, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodeTable.tsx
Fix the status icon indicator when a Kubernetes Linode is provisioning from grey to pulsing orange. I also went ahead and did some styling/file cleanup.
| ![Screenshot 2024-03-27 at 10 38 24 AM](https://github.com/linode/manager/assets/115299789/e7c9142f-49b4-4c7d-841d-f553c2c9a6ad) | <video src="https://github.com/linode/manager/assets/115299789/591ae82c-45d2-453f-818b-2719f06dc2d5" /> |
- On develop or prod, create a new Kubernetes cluster and observe the grey provisioning Linode icon status in the details page
- Create a new Kubernetes cluster and observe the pulsing orange provisioning Linode icon status in the details page
- Ensure there are no visual regressions from the …
=> fix: [M3-7605] - Wrong status indicator when provisioning a LKE

README.md
Update the `README.md` to use the correct logo
For context, the Logo became white in https://github.com/linode/manager/pull/10137 so we need to update the `README.md` to pull the color logo
=> fix: `README.md` Logo

packages/manager/.changeset/pr-10333-changed-1711728610850.md, packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx
When the Notification count is past 100, the numbers become difficult to read because their edges appear outside the colored dot. I decided to use the chip component to better display the Notification count.
| ![image](https://github.com/linode/manager/assets/115299789/5216c7a7-265e-4ab0-90e2-df76b98e6c79) | ![image](https://github.com/linode/manager/assets/115299789/ab487188-1028-41ac-bc21-2344c0cbd9f6) |
- Update the label to a 3 digit number on line 141 of `NotificationMenu.tsx`
- Confirm the notification badge display in the top right corner
=> change: [M3-7873] - Use Chip for notification badge

packages/manager/.changeset/pr-10323-upcoming-features-1711570823407.md, packages/manager/src/features/Account/AccountLanding.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.tsx, packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx, packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.tsx, packages/manager/src/features/Account/SwitchAccounts/utils.ts, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx
To set the stage for automatic token refresh features, we need to tweak our code to make it more reusable. This effort is a step towards that goal, aiming to make our token management smoother and improve overall user experience.
- Moved the functions that handle proxy token creation and storage management into a utils file. This move streamlines our code and makes these key functionalities easier to access and use across the board.
>[!note]
In a follow-up PR, I'll tidy up by moving all the account switching stuff – files, utils, and components – into the `/Account/SwitchAccount/` directory.
4/15
- Log into Parent account using developer credentials
- Ensure you can switch accounts back and forth between parent/proxy
- Ensure that proxy …
=> upcoming: [M3-7939] - Refactor for Auto-Token Refresh Prep

packages/manager/.changeset/pr-10316-tests-1711480175744.md, packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts, packages/manager/cypress/support/constants/account.ts
Fix the PR comments in previous PR [Add tests to check Parent and Child Close Account flows](https://github.com/linode/manager/pull/10296).
=> fix: [M3-7508] - Follow up on tests to check Parent and Child 'Close Account' flows

packages/manager/.changeset/pr-10334-upcoming-features-1711997020117.md, packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Summary.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx
- Adds the _Summary_ section to the new Linode Create flow 📄 
- Using local dev tools, turn on the `Linode Create v2` flag 🎏 
- Test the summary section on the new Linode Create flow
- Verify it correctly summarizes what options you have selected
- Verify it behaves the same as the current Linode Create flow (compare to production)
- Check on smaller screen sizes 📱
=> upcoming: [M3-7928] - Linode Create Refactor - Summary - Part 8

packages/manager/.changeset/pr-10344-fixed-1712089845550.md, packages/manager/src/features/Profile/SSHKeys/CreateSSHKeyDrawer.tsx
Fixes a small issue where the "Add an SSH Key" form doesn't reset when clicking the drawer's close or cancel buttons.
- Resets formik state when clicking the drawer's close and cancel buttons
- Confirm form resets as expected via Profile page at `/profile/keys`
- Confirm form resets as expected via Linode create flow
- Confirm SSH keys can still be added via Profile page at `/profile/keys`
- Confirm SSH keys can still be added via Linode create flow
=> fix: [M3-7953] - Reset SSH key form on cancel and close

packages/manager/.changeset/pr-10340-upcoming-features-1712145875071.md, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
This PR mainly just updates the UI for the `PrimaryNav` and `TopMenu` components.
- Move `Placement Groups` below `Images`
- Add `Placement Groups` to the `Create` menu on the `TopMenu` component.
04/15/2024
| ![b1](https://github.com/linode/manager/assets/119514965/4786f0cb-b832-4a61-a9d8-6a024ea01c8d) | ![a1](https://github.com/linode/manager/assets/119514965/efc1ebf4-7dc4-4edf-86bd-1b0d3d8e0c13) |
| ![b2](https://github.com/linode/manager/assets/119514965/abe27866-d43d-4126-8adf-a02152fa0fca) | ![a2](https://github.com/linode/manager/assets/119514965/ce389833-1349-4a5d-8e48-90603544cc69) |
- Have the `Placement Group` feature flag turned on.
- Verify the UI to reflect the changes described in the `Description`.
- Verify the interactions of …
=> upcoming: [M3-7901] - Update navigation items for Placement Groups

packages/manager/.changeset/pr-10349-tests-1712253815522.md, packages/manager/cypress/e2e/core/billing/restricted-user-billing.spec.ts
Add new tests to check the Account billing drawers.
- Add new cypress tests to tests `Make a Payment`, `Update Billing Contact Information`, and `Add Payment Method` access will be disabled for restricted users or child user accounts
```
yarn cy:run -s "cypress/e2e/core/billing/restricted-user-billing.spec.ts"
```
=> test: [M3-7797] - Add Cypress tests for Account billing drawers

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/Search/SearchLanding.tsx, packages/manager/src/features/TopMenu/SearchBar/SearchBar.tsx
- Fixes search for large accounts
- React Query queries with `enabled: false` now mark `isLoading` as `true`. It use to be `isLoading` `false` when a query was disabled.
- "Why does everything work if you hard refresh on the search landing page"
- We enabled queries when `!isLargeAccount` in `SearchLanding.tsx`. The queries will be enabled for a split second while we load `isLargeAccount ` because `!undefined` is `true`
- Test search on both small and large accounts
=> fix: [M3-7962] - Large Account Search Loading State

packages/manager/CHANGELOG.md, packages/manager/src/features/Profile/APITokens/CreateAPITokenDrawer.tsx, packages/manager/src/features/Profile/APITokens/ViewAPITokenDrawer.tsx
The Cloud Manager isn't working right when making tokens that should have access to everything. Even when you choose 'all' for the token's access level, it's mistakenly giving limited access (even though the scopes are all included). Also, when making tokens using the API and setting access to * (which should mean everything), it should reply with * to show that. But, it's listing out each access area one by one instead of just using *, which is not what's supposed to happen.
- No longer need to filter out `child account access` since API is in prod
- We're still only visually showing the "child account access" perm for accounts that have access to it from a user experience point of view (even though the perm will be part of the token). This is ok since features are still blocked from a …
=> fix: [M3-7967] - Returning proper scope when selecting all perms

packages/manager/.changeset/pr-10358-fixed-1712607995201.md, packages/manager/src/hooks/usePendingRevocationToken.ts, packages/manager/src/queries/tokens.ts
Disable unnecessary runs of the usePersonalAccessTokensQuery, which was running for all accounts - regardless of `user_type` - from the UserMenu. This query is used within the `usePendingRevocationToken` hook, which allows us to revoke PATs for proxy accounts when account switching occurs (see #10313). 
- Updates `usePersonalAccessTokensQuery` to allow it to be enabled/disabled.
4/15/24
- Log into https://cloud.linode.com as a regular user and observe that there is an API call to `/tokens` made when Cloud is loaded, since the user menu will load on any page. The UI doesn't need access to tokens for this user at this point, so the call is unnecessary.
- Check out this branch and, as the same user, log into …
=> fix: [M3-7961] - Disable usePersonAccessTokensQuery in token revocation hook based on `user_type`

packages/manager/.changeset/pr-10325-added-1712325278400.md, packages/manager/.changeset/pr-10325-upcoming-features-1712325236278.md, packages/manager/src/components/Breadcrumb/FinalCrumb.tsx, packages/manager/src/components/Breadcrumb/types.ts, packages/manager/src/components/DescriptionList/DescriptionList.stories.tsx, packages/manager/src/components/DescriptionList/DescriptionList.styles.ts, packages/manager/src/components/DescriptionList/DescriptionList.test.tsx, packages/manager/src/components/DescriptionList/DescriptionList.tsx, packages/manager/src/components/EditableText/EditableText.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodes.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTable.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsUnassignModal.tsx
This PR achieves two main goals:
- Consolidate summaries styles and their data (drawers, PG detail)
- Consolidate PG detail (summary + linodes list, no tabs)
- Remove "(`Affinity Type`)" appendages
- Introduce new `DescriptionList` component for summaries (only used for PG, meant to be expanded)
- component, test, storybook
- Implement `DescriptionList` in PG drawers and PG detail
- Remove tabs on Placement Group Details page
- Remove (`Affinity Type`)" appendages in
- drawers
- breadcrumb
- Update tests
| PG Detail | Create Drawer | Assign Drawer | Edit Drawer | Storybook |
| ------- | ------- | ------- | ------- | ------- |
| ![Screenshot 2024-04-05 at 09 08 17](https://github.com/linode/manager/assets/130582365/b7663d2a-66f1-4d73-9d30-a7834db16509) | ![Screen Shot 2024-04-05 at 09 09 …
=> upcoming: [M3-7937] - Update Placement Groups detail and summaries

packages/manager/.changeset/pr-10357-tech-stories-1712339827520.md, packages/manager/cypress/support/ui/toast.ts, packages/manager/package.json, packages/manager/src/components/Snackbar/Snackbar.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsLinodes/PlacementGroupsLinodesTable.tsx, packages/manager/src/features/Users/UserPermissions.tsx, packages/manager/src/index.tsx, yarn.lock
Update Notistack to 3.0.1 - pretty light refactor for a major update. This will bring us up to date with the lib and prevent some console errors we saw surface recently between React/Router & Notistack. ex:
Every time we'd have a snackbar pop up ⬆️ 
see [Migration Notes](https://notistack.com/migration) for more info
- Update Notistack to `3.0.1`
- Update Styling with new API in Snackbar.tsx
- Update Class Components instances
ℹ️ There should be no functional or visual regressions as a result of this PR (1/1 refactor)
- pull code, run `yarn && yarn up`
- test application overall for potential regression
=> refactor: [M3-7960] - Update Notistack to `3.0.1`

packages/manager/.changeset/pr-10362-fixed-1712610411475.md, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyDrawer.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyLanding.tsx
This PR fixes the issue of unable to update label of OBJ limited access key.
- Updated relevant type `UpdateObjectStorageKeyRequest` for `handleEditKey` 
- Update payload includes only `lablel` 
- Checkout develop. 
- Create Object Storage access key with limited access.
- Click "Edit Label".
- Change label and click Save Changes.
(How to verify changes) 
- Checkout this PR branch.
- Turn off OBJ feature flag and MSW 
- Create Object Storage access key with limited access.
- Click "Edit Label".
- Change label and click Save Changes. 
- Should be able to update label.
- Verify payload.
-  Turn on OBJ feature flag and MSW 
- Create / update Access key and verify the payload.
- Make sure there is no …
=> fix: [M3-7952] - Unable to update label of OBJ limited access key

packages/manager/src/featureFlags.ts, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
Add Akamai's Japanese QI System ID to Japanese Invoices.
- Conditionally render Japanese QI System ID in pdfGenerator function.
- Add's new field to the taxes object in LD (Note this filed is not yet added. Will be added once it is merged into Prod.)
Example: 
```
{
"country_tax": {
"tax_id": "******",
"tax_name": "Japan JCT",
**"qi_registration": "**********"**
},
"provincial_tax_ids": {}
}
```
- Turn on MSW
- Change account country to "JP" in MSW
- Navigate to http://localhost:3000/account/billing
- Click on Download invoice and verify the IQ registration appears under Tax Id's (top left side in invoice).
- Validate the changes reflect AC in the ticket. 
=> change: [M3-7847] - Add Akamai's Japanese QI System ID to Japanese Invoices.

packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts
Observing some weird hanging with one of the Parent/Child tests. Spent some time trying to figure it out but ran out of time, and don't want this interfering with the tests during our next release or during any potential hotfixes (hoping whatever might be causing this isn't already present in `staging` in case there's a hotfix before our next release -- if this does become an issue). Feel free to merge whenever (or don't if the problem stops happening 🤷‍♂️)
I posted some information about this issue in the notification channel, but I don't have any reason to believe this is caused by a Cloud bug so there shouldn't be any major risk to skipping this temporarily. I will unskip this and figure out the issue when I'm back.
Please specify a release date to guarantee timely review of this PR. …
=> test: Skip hanging Parent/Child test

packages/manager/.changeset/pr-10364-changed-1712674027336.md, packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx
Delete "Resizing to smaller plans is not supported" tooltip for current plan in Dedicated tab.
Delete "Resizing to smaller plans is not supported" tooltip for current plan in Dedicated tab. 
Release date 04/15/24
| <img src="https://github.com/linode/manager/assets/157619599/d593b77a-3887-480c-aa60-0bf8cf58529e" width="400" /> | <img src="https://github.com/linode/manager/assets/157619599/be2e4fe4-4d50-4362-8fcf-dd87537adcd4" width="400" />|
- Navigate to Databases
- Choose a Database cluster with Dedicated plan
- Navigate to Resize tab
- In the table of plans, the current plan does not have a tooltip.
=> change: [UIE-7563] - Delete tooltip displaying for current plan in Databases

packages/manager/.changeset/pr-10354-upcoming-features-1712327982879.md, packages/manager/src/components/VLANSelect.tsx, packages/manager/src/components/VPCSelect.test.tsx, packages/manager/src/components/VPCSelect.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Summary.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts, packages/manager/src/hooks/useCreateVPC.ts, packages/manager/src/queries/vpcs.ts, packages/validation/.changeset/pr-10354-changed-1712605368375.md, packages/validation/src/linodes.schema.ts
- Adds a VPC section to the new Linode Create flow ✨
- Builds **new** VPC panel that uses react hook from tooling 🔧
- Adds a VPC Select
- Adds `Create a Linode` to the document title to match the existing flow
- Improves error handling for VPC IP ranges
- Turn on the `Linode Create v2` feature flag 🎏 
- Test the new VPC selction 🧪 
- Compare functionality to the existing Linode Create flow 🔍 
- Test error handling in the VPC section ❌
=> upcoming: [M3-7924] - Linode Create Refactor - VPC - Part 10

packages/manager/.changeset/pr-10363-upcoming-features-1712613073120.md, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/LinodesCreate/TabbedContent/FromLinodeContent.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodesLanding.tsx, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx, packages/manager/src/features/Linodes/MigrateLinode/MigrateLinode.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx
Update the gecko feature flag from a boolean to an object so we can have more granular control for Beta/GA
- Use `gecko2` object feature flag over `gecko` feature flag
- Add placeholder logic for GA for the Linode's landing page and region select
| Gecko Beta  | Gecko GA   |
| ![image](https://github.com/linode/manager/assets/115299789/5d18858c-6cf2-47f1-aaac-ed5b34633b3f) | ![Screenshot 2024-04-08 at 5 24 50 PM](https://github.com/linode/manager/assets/115299789/a52aea52-70c1-4f04-a9f2-ec0749eb3894) |
| ![Screenshot 2024-04-08 at 5 25 53 PM](https://github.com/linode/manager/assets/115299789/d1f26722-a792-429b-bf2e-c3a5d3dabef2) | ![image](https://github.com/linode/manager/assets/115299789/6114af77-7be0-4310-b6ac-d4c6208450e1) |
- Ensure you have the gecko customer …
=> feat: [M3-7959] - Update gecko feature flag to object

packages/manager/.changeset/pr-10366-upcoming-features-1712781737734.md, packages/manager/src/queries/linodes/linodes.ts
Now that the `POST` & `DELETE` `linode/instances` Alpha endpoint have been updated to work with placement groups, we need to invalidate the related PG if:
- on POST (create linode) we assign a placement group
- on DELETE (delete linode) we delete a linode assigned to a placement group
- Invalidate PG queries on Linode create & delete mutations
| Create Linode (and assign to PG)  | Delete Linode (and unassign from PG) |
| <video src="https://github.com/linode/manager/assets/130582365/0d2e2f0b-d1c6-4a13-8e34-ecb9f73c98fc" /> |  <video src="https://github.com/linode/manager/assets/130582365/0935c560-a7c0-487c-bb60-9b2ac5094125" /> |
- Using alpha environment and having the "Placement Group" feature flag enabled, either:
- use your account (need the `placement-group` …
=> upcoming: [M3-7972] - Invalidate PG queries on Linode create/delete

packages/manager/.changeset/pr-10321-tests-1712172117252.md, packages/manager/cypress/e2e/core/longview/longview.spec.ts, packages/manager/cypress/support/constants/longview.ts, packages/manager/cypress/support/intercepts/longview.ts
Add new tests to check the empty state message in Longview landing page.
- Add new cypress tests to tests to check Longview empty state
```
yarn cy:run -s "cypress/e2e/core/longview/longview.spec.ts"
```
=> test: [M3-7395] Add new cypress tests to longview landing page

packages/manager/.changeset/pr-10370-tests-1712857880206.md, packages/manager/cypress/e2e/core/images/machine-image-upload.spec.ts
- I'm hoping this fixes the constant failures we're getting on the Github Actions cypress tests 
- We were returning the **same** API response for different Image endpoint filters. This is causing the same image to show up in two tables. It should only show in one. 
-  This PR just updates the mock to respect the API filtering so that. the image only shows once on the page
- Verify e2e test passes in Jenkins
- Verify e2e test passes locally
We will hope and pray it passes in Github Actions 🙏 😅
=> fix: `machine-image-upload.spec.ts` e2e test flake

docs/development-guide/13-coding-standards.md, docs/tooling/analytics.md, packages/manager/.changeset/pr-10365-tech-stories-1712760397845.md
Based on cafe discussion, we want to be able to send a new variable to Adobe Analytics to capture more information about custom events. An example of this is a boolean like "isLinodePoweredOn": [true/false], which is not easily decipherable via our existing variables. See #10337.
After working with the Adobe Analytics backend team, we have added a new object variable, which we stringify before sending to Adobe Analytics, to allow us to capture more descriptive aspects of our custom events, as needed. (**Note**: the changes to the AA backend are testable Cloud + their dev environment right now, and were released to their prod environment on 4/10, ahead of our next release.)
**This PR handles only the documentation updates for the described changes above.**
- Removes the Adobe Analytics …
=> change: [M3-7964] - Update developer guide documentation for Adobe Analytics

packages/manager/.changeset/pr-10372-upcoming-features-1712891100686.md, packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts, packages/manager/src/GoTo.tsx, packages/manager/src/MainContent.tsx, packages/manager/src/components/DetailsPanel/DetailsPanel.tsx, packages/manager/src/components/PrimaryNav/PrimaryNav.tsx, packages/manager/src/factories/account.ts, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/utils.test.ts, packages/manager/src/features/PlacementGroups/utils.ts, packages/manager/src/features/TopMenu/AddNewMenu/AddNewMenu.tsx
This PR improves and simplifies the logic for allowing users to access the Placement Group feature in Cloud Manager.
It originated from the omission to include the "Placement Group" capability in the restriction logic (only the feature flag was used).
I intentionally avoided using `isFeatureEnabled`, both because it is currently a candidate for refactor, and the fact the hook is clean, concise and isolated to the feature (clear, dedicated naming convention).
- Create a new hook to check that both the flag is on and the account capability is returned for the current user
- Implement hook in
- Primary Routes
- Placement Group feature
- Linode Create flows (v1 & v2)
- Primary Nav
- Create Menu
- GoTo menu
- Remove unnecessary checks since the feature is gated properly
- Complement coverage …
=> upcoming: [M3-7986] - Fix & Improve Placement Groups feature restriction

packages/manager/.changeset/pr-10379-upcoming-features-1713259266637.md, packages/manager/src/assets/icons/entityIcons/placement-groups.svg
Update the Placement Group icon/logo
- The dimensions of the Placement Group svg icon are changed to 24 x 24.
04/29/2024
| ![icon-before](https://github.com/linode/manager/assets/119514965/42c45b60-4afc-4387-964a-f991d799bac2) | ![icon-after](https://github.com/linode/manager/assets/119514965/7e0f90ad-1a37-4cb8-8dd4-877a1c702b35) |
| ![beforee](https://github.com/linode/manager/assets/119514965/06586426-def0-4123-a3fd-423e38db41b6) | ![afterr](https://github.com/linode/manager/assets/119514965/4632fd12-dbac-42fe-aba9-f09cb533148f) |
- Using the Cloud Manager developer tools switch over to the `Dev` environment and turn on the `Placement Groups` feature flag.
- Verify that the Placement …
=> upcoming: [M3-7979] - Update Placement Group svg icon

packages/manager/.changeset/pr-10371-tech-stories-1713200214722.md, packages/manager/src/utilities/accountCapabilities.test.ts, packages/manager/src/utilities/accountCapabilities.ts
Deprecate `isFeatureEnabled` function and add new function `isFeatureEnabledV2` which uses AND logic instead of OR
|  | Capabilities On   | Capabilities Off |
| LD Feature Flag On | Show feature: YES | Show feature: NO |
| LD Feature Flag Off | Show feature: NO | Show feature: NO |
=> refactor: [M3-7770] - isFeatureEnabledV2 to check for feature flag AND account capability

packages/manager/.changeset/pr-10374-upcoming-features-1712936111438.md, packages/manager/package.json, packages/manager/src/components/RegionSelect/RegionSelect.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/components/VLANSelect.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Access.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Error.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Firewall.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/UserData/UserData.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VLAN.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPC.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/VPC/VPCRanges.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts, packages/validation/src/linodes.schema.ts, yarn.lock
- Adds dynamic validation to the new Linode Create flow 🔥 
- Adds `onBlur` and `ref` to many components
- `onBlur` allows the form to perform validation `onBlur` 
- `ref` allows react-hook-form to focus errors aromatically onSubmit
- Expected behavior ⌨️ 
- before submit, fields will be validated onBlur
- after submission, fields will be validated onChange 
https://github.com/linode/manager/assets/115251059/54cdefdb-3962-4f5f-a585-c8a10e5b5d56
- Test validation throughout the new form
=> upcoming: [M3-7987] - Linode Create Refactor - Validation

packages/manager/.changeset/pr-10373-changed-1712939610447.md, packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx, packages/manager/src/components/RegionSelect/RegionOption.tsx, packages/manager/src/components/RegionSelect/RegionSelect.tsx, packages/manager/src/components/RegionSelect/RegionSelect.types.ts, packages/manager/src/components/RegionSelect/RegionSelect.utils.test.tsx, packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx, packages/manager/src/features/PlacementGroups/types.ts
This PR allows customizing the disabled RegionSelect option. Previously the disabling of a region (and its associated tooltip) we controlled statically, only based on the region capabilities.
With this update, we keep defaulting to the capability based disabling, and allow a custom handler to disable a region based on whatever logic needed. In this case, it is for the `PlacementGroupCreateDrawer` to allow disabling a region based on the `maximum_pgs_per_customer` region limit.
- Add new `handleDisabledRegion` prop to `RegionSelect`
- Change `unavailable` front end code to take a new `disabledProps` so we can configure custom tooltip messages and dimensions as well
- Modify `getOptionDisabled` to reflect the new `disabledProps` prop
- Improve naming conventions and prop destructuring
- …
=> upcoming: [M3-7978] - RegionSelect disabled option API updates

packages/manager/.changeset/pr-10380-fixed-1713263110419.md, packages/manager/src/components/CopyableTextField/CopyableTextField.tsx, packages/manager/src/foundations/themes/dark.ts
The `CopyableTextField` component and the `dark.ts` file contain outdated Material UI vendor specific CSS prefix properties. As a consequence, the console tab in Chrome dev tools is filled with a long console error message. This PR resolves that issue.
- Updates the kebab-case styled css object property for text fill color.
04/29/2024
https://github.com/linode/manager/assets/119514965/dacc7a2b-7f70-4ad5-bb9a-616696a93ef2
https://github.com/linode/manager/assets/119514965/9c2ee552-4cbb-4578-80f5-37372d61ecc2
- Launch the Cloud Manager application from the Chrome web browser.
- Open the dev tools and click on the console tab. 
- Checkout the latest from `develop` and visit …
=> fix: [M3-7992] - Fix CSS vendor prefix bug in Chrome

packages/manager/.changeset/pr-10391-tests-1713534776248.md, packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts
- Updates the latest kernel to fix the `linode-config.spec.ts` failures ❌ 
- Verify `linode-config.spec.ts` passes in Jenkins ✅ 
- Verify `linode-config.spec.ts` passes locally (_optional_) ✅ 
```
yarn cy:run -s "cypress/e2e/core/linodes/linode-config.spec.ts"
```
=> fix: Update latest kernel version to fix `linode-config.spec.ts`

packages/manager/.changeset/pr-10383-changed-1713295259053.md, packages/manager/cypress/e2e/core/linodes/smoke-linode-landing-table.spec.ts, packages/manager/src/components/PrimaryNav/SideMenu.stories.tsx, packages/manager/src/features/TopMenu/Community.tsx, packages/manager/src/features/TopMenu/Help.tsx, packages/manager/src/features/TopMenu/NotificationMenu/NotificationMenu.tsx, packages/manager/src/features/TopMenu/TopMenu.tsx, packages/manager/src/features/TopMenu/TopMenuIcon.tsx, packages/manager/src/features/TopMenu/TopMenuTooltip.tsx
Cleans up and fixes many inconsistencies with the Top Menu 🧹 
| <video src="https://github.com/linode/manager/assets/115251059/5b1558cb-ce6e-423b-88a1-fec18ed6f73e" /> | <video src="https://github.com/linode/manager/assets/115251059/69f93066-23c5-496f-8cdd-29b4faf6032f" /> | 
| <video src="https://github.com/linode/manager/assets/115251059/05adb51e-d1e2-4100-88b0-7e0b993a856b" /> | <video src="https://github.com/linode/manager/assets/115251059/a308640f-2371-4932-90d3-ddafe3aae5e3" /> |
| <video src="https://github.com/linode/manager/assets/115251059/8e9e336d-6d9e-412f-8fc4-71900edefe76" /> | <video src="https://github.com/linode/manager/assets/115251059/3ca6fa …
=> change: [M3-7994] - Clean up Top Menu and Fix Inconsistencies

packages/manager/.changeset/pr-10394-changed-1713812025608.md, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlanInformation.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/features/components/PlansPanel/constants.ts
Following up on https://github.com/linode/manager/pull/10228, shift from using "limited availability" verbiage to "limited **deployment** availability".
- Tooltip for disabled plans: `This plan has limited availability.` --> `This plan has limited deployment availability.`
- For these plans in tablet/mobile view, the chip should have also changed from `Limited Availability` --> `Limited Deployment Availability`
- Notice on plan panel when all plans are unavailable: `These plans have limited availability. Learn more.` --> `These plans have limited deployment availability. Learn more.`
4/29/24
<details>
<summary>Screenshots</summary>
These screenshots are from the Linode Create flow, but the phrasing change should be observed in the corresponding flows for LKE and DBaaS as well.
</details> …
=> change: [M3-7998] – "Limited Availability" --> "Limited Deployment Availability" phrasing change

packages/manager/src/components/Link.tsx, packages/manager/src/features/TopMenu/Help.tsx
- Fixes a few console errors caused by https://github.com/linode/manager/pull/10383 Sorry!! 🤦 
- Allows our `Link` component to accept a ref (had to do this to fix Tooltip ref error)
| ![Screenshot 2024-04-23 at 10 54 24 AM](https://github.com/linode/manager/assets/115251059/864192f0-e875-452c-8ef4-8b7c30fb08a4) | ![Screenshot 2024-04-23 at 10 54 16 AM](https://github.com/linode/manager/assets/115251059/7bb73a12-6f4b-4ac7-8d7c-35dc0bd7d4f1) |
- Verify you don't see any console errors related to the Top Menu 
- Verify the top menu buttons for Help and Community...
- Have working tooltips 💡 
- Have `aria-label`s 📖 
- Look good and consistent 🎨
=> fix: TopMenu related console errors

packages/manager/.changeset/pr-10395-upcoming-features-1713819325776.md, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelection.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelection.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelectionList.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScriptSelectionRow.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/StackScripts.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFields.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/utilities.test.ts, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/utilities.ts, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts, packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx
Adds initial User Defined Field support to the Linode Create flow when deploying from a StackScript
- Extracts out some until functions from the existing create flow and unit tests them (no changes in logic, only naming changes) 🧪 
- Adds initial User Defined Field support to the new Linode Create flow
- Check out this PR or use an internal preview link
- Enable the `Linode Create v2` feature flag
- Select various community StackScripts and check the functionality of the user defined fields section
- Compare behavior to production
=> upcoming: [M3-8028]: Linode Create Refactor - User Defined Fields

packages/manager/.changeset/pr-10396-tests-1713821841742.md, packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts, packages/manager/cypress/support/e2e.ts, packages/manager/cypress/support/index.d.ts, packages/manager/cypress/support/setup/page-visit-tracking-commands.ts
This un-skips and fixes the Parent/Child account switching test that was recently disabled by #10353 due to an issue with it hanging.
The root cause of the hanging is unknown but appears to be related to the timing of Cypress's assertions when a page reload or other browser navigation is involved. I detailed my findings in the Jira ticket, but the only reliable workaround I found to resolve the issue involves detecting and waiting for the page load before asserting any HTTP requests, state of DOM elements, etc. (credit to [a commenter on this very old and loosely related thread](https://github.com/cypress-io/cypress/issues/1805#issuecomment-525482440) on Cypress's repo)
To facilitate the workaround, I added a couple new Cypress commands: `cy.trackPageVisit()` and …
=> test: [M3-7982] - Fix hanging account switching test

packages/manager/.changeset/pr-10387-changed-1713887237963.md, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts, packages/manager/cypress/support/intercepts/regions.ts, packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx, packages/manager/src/components/TableRow/TableRow.styles.ts, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanContainer.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.test.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlanSelection.tsx, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx, packages/manager/src/features/components/PlansPanel/PlanContainer.test.tsx, packages/manager/src/features/components/PlansPanel/PlanContainer.tsx, packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx, packages/manager/src/features/components/PlansPanel/PlanInformation.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.test.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.styles.ts, packages/manager/src/features/components/PlansPanel/PlansPanel.test.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx, packages/manager/src/features/components/PlansPanel/constants.ts, packages/manager/src/features/components/PlansPanel/utils.test.ts, packages/manager/src/features/components/PlansPanel/utils.ts
This PR brings the latest changes to the PlanSelection panels on both the Linode and Kubernetes creation flows.
The diff is a bit larger than expected considering the need to refactor this portion of the code to allow for easier customization in the future. Both flows share very similar logic for rendering plan selection data, and identical logic for filtering unavailable and limited availability plans.
The logic implemented in this PR for the displaying of notices, disabled status and related tooltips is derived from the new requirements shown in the screenshots below:
| 1 | 2 | 3 | 4 | 5 |
| ------- | ------- | ------- | ------- | ------- |
| <img width="1440" alt="DC Get Well User Story #5_2@2x" src="https://github.com/linode/manager/assets/130582365/c499becc-3915-4258-8d56-e9b2bef3beb2 …
=> change: [M3-7996] - DC Get Well - PlanSelection availability updates and consolidation

packages/manager/.changeset/pr-10399-upcoming-features-1713888729255.md, packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts, packages/manager/src/components/DetailsPanel/DetailsPanel.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/Details.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyState.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyStateData.ts, packages/manager/src/features/PlacementGroups/constants.ts
Updates to the text copy as it pertains to the Placement Groups project.
⚠️ _This is NOT the final copy_ ⚠️
- No code changes, just text copy updates. Please, refer to the Internal Ticket and the Mocks for information on where the changes are made.
04/29/2024
- Using the Cloud Manager developer tools:
- Switch to the dev API
- Turn the "Placement Group" feature flag on
- Turn MSW off
- Using the information on the Internal Ticket and the Mocks do a quick inspections that the text copy changes satisfy the requirements.
=> upcoming: [M3-7932] - Placement Groups copy updates

packages/manager/.changeset/pr-10408-upcoming-features-1714066606151.md, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupSelectOption.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx, packages/manager/src/components/TextTooltip/TextTooltip.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsRow.tsx
Small PR to bring a couple UI updates to the Placement Groups
- Change PlacementGroupSelect option label to have the affinity type floating right and remove affinity type from selected option
- Improve PG table row linodes tooltip (linking, placement)
| ![Screenshot 2024-04-25 at 13 24 59](https://github.com/linode/manager/assets/130582365/aa8015fd-a24b-472f-8bbc-66d704fed75d) | ![Screenshot 2024-04-25 at 13 25 34](https://github.com/linode/manager/assets/130582365/4bd411b7-af5d-42f1-a283-a5a655b4632f) |
|  ![Screenshot 2024-04-25 at 13 28 03](https://github.com/linode/manager/assets/130582365/8f19a529-cecb-47ac-b3a3-c1ba0f4812d4) | ![Screenshot 2024-04-25 at 13 27 …
=> upcoming: [M3-7980] - Update PlacementGroups linodes tooltip and SelectPlacementGroup option label

packages/manager/.changeset/pr-10411-upcoming-features-1714138447215.md, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsDetail.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetail/PlacementGroupsSummary/PlacementGroupsSummary.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLanding.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsLanding/PlacementGroupsLandingEmptyStateData.ts, packages/manager/src/features/PlacementGroups/constants.ts
This PR adds content to the `ResourcesSection` component of the Placement Groups landing page with an empty state.
- Links to the Placement Groups docs and the Linode docs.
| ![aaaa](https://github.com/linode/manager/assets/119514965/a51da6c5-34a7-4cb7-af24-24de45f558dd) | ![bbbb](https://github.com/linode/manager/assets/119514965/cf035454-30f7-4d57-ace7-5f5271445058) |
- Using the Cloud Manager developer tools, turn on the `Placement Groups` feature flag.
- Verify that the `ResourcesSection` component is rendered in the Placement Groups landing page with an empty state.
- Verify that both links open in new tabs.
- Verify that all tests are passing.
=> upcoming: [M3-7671] - Add Resources Section to Placement Groups Landing in Empty State

packages/manager/.changeset/pr-10406-changed-1714060751957.md, packages/manager/cypress/e2e/core/account/account-cancellation.spec.ts, packages/manager/src/features/Account/CloseAccountDialog.tsx
Update Account Closure Dialog Wording
| ![image](https://github.com/linode/manager/assets/119517080/2fce6c13-585d-4845-92bc-a525aa0010e0)| ![image](https://github.com/linode/manager/assets/119517080/db0dd617-b8de-4b08-bccf-d6fd98be6a81)|
- Navigate to http://localhost:3000/account/settings
- Verify Account Closure Dialog title.
=> change: [M3-6856] - Update Account Closure Dialog Wording

packages/api-v4/.changeset/pr-10413-changed-1714154673845.md, packages/api-v4/src/kubernetes/types.ts, packages/api-v4/src/linodes/types.ts, packages/validation/.changeset/pr-10413-changed-1714154797841.md, packages/validation/src/linodes.schema.ts
Add `disk_encryption` to types & validation schemas as appropriate based on the API spec (see ticket for link)
- `EncryptionStatus` type added; `disk_encryption` field added to `Linode`, `Disk`, `CreateLinodeRequest`, and `RebuildRequest` interfaces
- `disk_encryption` added to `CreateLinodeSchema` and `RebuildLinodeSchema`; it is nullable and optional, but if provided should have a value of either "enabled" or "disabled"
> [!NOTE]
> `@TODO LDE: remove optionality once LDE is fully rolled out` was added as a comment to a few new properties. These are instances where, when LDE is fully rolled out, `disk_encryption` will always be included on that object. I think marking them as optional at this point is fair because not doing so would be premature, and also likely confuse consumers of the …
=> feat: [M3-8005] – Add `disk_encryption` to types & validation schemas

packages/manager/.changeset/pr-10417-tests-1714418018265.md, packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts, packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
This fixes a couple OBJ E2E tests that are failing following the latest API release. The failures are caused by the API responding with a `400` when we pass the `region` property in OBJ requests; previously this property was ignored, but now the API handles the property by rejecting it when a certain API-side config flag is not set.
Our OBJ factories include values for both the `region` and `cluster` properties, so this fixes the issue by manually setting `region` to `undefined` in the impacted tests.
We can rely on CI for this; in its current state, these two tests fail 100% of the time, so it should be pretty easy to determine whether or not this PR resolves the problem.
=> test: [M3-8050] - Fix OBJ E2E tests following API release

packages/manager/.changeset/pr-10418-upcoming-features-1714423037799.md, packages/manager/src/factories/disk.ts, packages/manager/src/factories/kubernetesCluster.ts, packages/manager/src/factories/linodes.ts
Add `disk_encryption` to `linodeDiskFactory`, `linodeFactory`, and `nodePoolFactory`
5/13/24
This can be verified with the RQ Dev Tool -- with the MSW on, when going to the Linodes landing page, Linode Details page, and the Kubernetes landing page, you should be able to click into the relevant queries and observe `disk_encryption` is present.
<details>
<summary>Screenshots</summary>
</details>
=> feat: [M3-8006] – Support `disk_encryption` in mocks

packages/manager/.changeset/pr-10424-fixed-1714505413640.md, packages/manager/src/components/Table/Table.tsx
This previous [commit](https://github.com/linode/manager/commit/f9f33aa18ce9531123e73de65ea7781047243012#diff-dfeecf2f4fb1286e817742e67398c802505389acdc4c8f487c50b77e61b4a68eL81) introduced an issue with classes meant for the table wrapper being passed to the table component.
Previously, we were using `lodash` omit to remove props that were not even being passed, so it was useless. The good news is that my util is actually better typed than the `lodash` one so when i switched i was seeing typed errors trying to remove non-existing props. 
**The fix**: we only need to pass true table props to the actual Table component and keep the extra props for the wrapper.
- prevent forwarding non table props to the `Table` component
| ![Screen Shot …
=> fix: [M3-8053] - Fix table component props forwarding

scripts/changelog/generate-changelogs.mjs, scripts/changelog/utils/initiateChangelogEntry.mjs
Based on a cafe discussion, remove the semver bump in `generate-changelogs.mjs` since those are handled in a different step in the release process.
* Run `yarn generate-changelogs`
* Verify changelogs are generated as before, except without a version bump
=> change: Remove semver bump in `generate-changelogs.mjs`

packages/manager/.changeset/pr-10427-fixed-1714532198771.md, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx
Small fix to make sure the PlacementGroupSelect gets its selected option cleared when no value is selected. In the Linode create flow, we clear the value when the `selectedRegionId` is updated. While the value is cleared and everything works as expected, an artifact of not clearing the input results in the selected option still showing in the select instead of the desired "None" placeholder.
from [mui.com](https://mui.com/material-ui/api/autocomplete/)
`clearOnBlur`
> If true, the input's text is cleared on blur if no value is selected. Set it to true if you want to help the user enter a new value. Set it to false if you want to help the user resume their search.
- Set `PlacementGroupSelect` `clearOnBlur` to `true`
**5/13/2024**
| <video …
=> upcoming: [M3-8051] - Set PlacementGroupSelect clearOnBlur

packages/manager/.changeset/pr-10403-tests-1714588716317.md, packages/manager/.changeset/pr-10403-tests-1714588819736.md, packages/manager/cypress/e2e/core/domains/smoke-clone-domain.spec.ts, packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts, packages/manager/cypress/support/constants/domains.ts
Add regression tests to clone domain.
- Check users can clone a domain from the Domain landing page
```
yarn cy:run -s "cypress/e2e/core/domains/smoke-clone-domain.spec.ts"
```
=> M3-7467 Add Cypress test for Domain cloning

packages/manager/.changeset/pr-10384-tests-1713976558483.md, packages/manager/cypress/e2e/core/firewalls/update-firewall.spec.ts
Add regression tests to rename firewall label on landing page.
- Check user can update a Firewall's label from the Firewall details page
- Check label shown on details page updates to reflect change
```
yarn cy:run -s "cypress/e2e/core/firewalls/update-firewall.spec.ts"
```
=> test: [M3-7465] - Add Cypress test coverage for Firewall renaming

packages/manager/.changeset/pr-10425-tests-1714509893790.md, packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts, packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts, packages/manager/cypress/support/intercepts/placement-groups.ts
Adds a couple integration tests for Placement Group deletion flows:
- With Linodes attached
- Without Linodes attached
- Adds deletion tests in `delete-placement-groups.spec.ts`
- Fixes a mistake in PG mock utils where an empty array was being passed where an argument should've been used
- Renames mock utils file from `vm-placement.ts` to `placement-groups.ts`
We can rely on CI, or run the tests manually:
`yarn && yarn build && yarn start:manager:ci`, then
```bash
yarn cy:run -s "cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts"
```
Alternatively you can use `yarn cy:debug` to watch the tests run.
=> test: [M3-7781 & M3-7782] - Add Cypress integration tests for Placement Group deletion flows

packages/manager/.changeset/pr-10431-upcoming-features-1714656373835.md, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx
Replaces a remaining implementation of the feature flag restriction for Placement Groups feature with the recently created utility function `useIsPlacementGroupsEnabled()`.
- Straight forward replacement of one function with another.
- No UI/UX changes.
| Feature Flag Off  |  Feature Flag On  |
| ![Screenshot 2024-05-02 at 6 06 47 AM](https://github.com/linode/manager/assets/119514965/e237183a-2fa9-4e35-8384-9793bbd79ae3) | ![Screenshot 2024-05-02 at 6 06 58 AM](https://github.com/linode/manager/assets/119514965/223b0cdc-243b-4706-82b5-199b4b4ce5af) |
- Have the `placement-group` customer tag on the user account used for testing.
- Using the Cloud Manager Dev Tools:
- Enable and Disable the …
=> upcoming: [M3-8062] - Replace PG feature flag restriction with `useIsPlacementGroupsEnabled`

packages/manager/cypress/e2e/core/placementGroups/delete-placement-groups.spec.ts
Quick fix for the VMPG delete failures -- the wording on the toast notification was improved, but on a branch that didn't have these tests, so the tests began failing when they were merged.
(Don't think a changeset is even necessary here since these tests haven't been released yet -- any other thoughts?)
CI's good enough here.
=> test: Fix Placement Group delete tests following wording improvement

packages/api-v4/.changeset/pr-10433-changed-1714662873531.md, packages/api-v4/src/regions/types.ts, packages/manager/.changeset/pr-10433-changed-1714664264011.md, packages/manager/src/__data__/regionsData.ts, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/constants.ts, packages/manager/src/features/PlacementGroups/utils.test.ts, packages/manager/src/features/PlacementGroups/utils.ts
`maximum_pgs_per_customer`: This value can be unlimited for some customers in some regions, for which the API returns the `null` value. The UI representation of this `null` value is the "unlimited" string
- Allow `null` for `maximum_pgs_per_customer` in APIv4
- Add new util to return the proper limit in the UI
**5/13/2024**
ℹ️ have both the "Placement Group" feature flag and MSW on
- Navigate to http://localhost:3000/placement-groups/create
- Pick Toronto as the region
- Notice the helper text
=> upcoming: [M3-8025] - Placement Groups: Allow null for maximum_pgs_per_customer

packages/api-v4/src/placement-groups/types.ts, packages/manager/.changeset/pr-10434-upcoming-features-1714746439358.md, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityEnforcementRadioGroup.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityTypeSelect.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsEditDrawer.tsx, packages/manager/src/features/PlacementGroups/utils.test.ts, packages/manager/src/features/PlacementGroups/utils.ts
Part 2 (final) of Placement Group copy updates
- Update copy in various places
- Update interface names to reflect copy changes
- Update relevant tests
**5/13/2024**
- Confirm copy changes in code and UI (placement group features)
- Placement Group Create Drawer
- Placement Group Assign Linode Drawer
- Placement Group Edit drawer
=> upcoming: [M3 -8049] - Last round of placement group copy updates

packages/manager/.changeset/pr-10438-upcoming-features-1714732245367.md, packages/manager/src/utilities/generate-cli.test.ts, packages/manager/src/utilities/generate-cli.ts
This PR allows Placement Group data to be passed in as arguments via the `Linode CLI`. 
- The Placement Group object is flattened to obtain and pass the `id` value. In the end the relevant argument and value are passed as follows: `placement_group.id 1234`.
05/13/2024
| ![Screenshot 2024-05-03 at 10 22 09 AM](https://github.com/linode/manager/assets/119514965/36aeab3e-a4d6-4abd-8a2d-454dea2f0239) | ![linode-cli-arg](https://github.com/linode/manager/assets/119514965/afbf418c-fb8f-4c1a-8bd5-74eaf50cdf2a) |
- ...
- Verify that a new Linode instance can be created when passing a Placement Group id argument using the `linode-cli` tool.
=> upcoming: [M3-7690] - Support PlacementGroups in CLI tool

packages/manager/.changeset/pr-10447-fixed-1715190382947.md, packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts
Fixes a test failure in `one-click-apps.spec.ts` stemming from a backend update made to the Minecraft app earlier today. The backend change made the app compatible only with Ubuntu 22.04, and this test attempts to deploy using Ubuntu 20.04, leading to the failure.
This is a really quick fix to get the test passing again, but wrote up M3-8089 to revisit this test and eliminate the risk of this type of issue happening again.
- Fixes failure by replacing Ubuntu 20.04 with Ubuntu 22.04
We can rely on CI for this one.
=> test: [M3-8088] - Fix One-Click App test failure by using Ubuntu 22.04 image

packages/manager/.changeset/pr-10439-upcoming-features-1715011188623.md, packages/manager/src/components/AccessPanel/AccessPanel.tsx, packages/manager/src/components/DiskEncryption/DiskEncryption.test.tsx, packages/manager/src/components/DiskEncryption/DiskEncryption.tsx, packages/manager/src/components/DiskEncryption/constants.tsx
This PR adds a new `DiskEncryption` component that will be used (with some coming modifications) in the Linode Create, Linode Rebuild, and LKE Create flows.
5/13/24
| Enabled  | Disabled   |
| ![Screenshot 2024-05-06 at 11 54 50 AM](https://github.com/linode/manager/assets/114682940/04a41438-d3e1-4a1b-8668-90cfcc669247) | ![Screenshot 2024-05-06 at 10 27 12 AM](https://github.com/linode/manager/assets/114682940/651de78d-97e8-450e-aa33-22929f900c9f) |
Temporary code that will be removed prior to merging was added to `AccessPanel.tsx` so you can see the "Disk Encryption" section in the Linode Create flow or in the Linode Rebuild dialog. You may set L122 in `AccessPanel.tsx` to `false` to see the enabled state.
=> feat: [M3-8018] – "Disk Encryption" section component

packages/manager/src/components/ImageSelectv2/ImageSelectv2.test.tsx, packages/manager/src/components/ImageSelectv2/ImageSelectv2.tsx
- Adds the distribution icon to the new ImageSelect on the new Linode Create flow 🖼️ 
- Add unit test to ensure Icon renders
| ![Screenshot 2024-05-06 at 1 45 22 PM](https://github.com/linode/manager/assets/115251059/7c457538-39a1-48ce-b73d-9f722c4fcb57) |  ![Screenshot 2024-05-06 at 1 45 06 PM](https://github.com/linode/manager/assets/115251059/e29f7d67-3054-4b53-a5cb-a6504e8d2127) |
- Turn on the `Linode Create v2` flag using local dev tool
- Verify you see the distro icon of the selected distribution 👀 
- Compare styles to production make make sure they look very similar
=> upcoming: [M3-8077] - Add Distribution Icon to Image Select v2

packages/manager/.changeset/pr-10450-fixed-1715198221685.md, packages/manager/src/factories/types.ts, packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx, packages/manager/src/features/components/PlansPanel/PlanContainer.tsx, packages/manager/src/features/components/PlansPanel/PlanSelection.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx, packages/manager/src/features/components/PlansPanel/types.ts, packages/manager/src/features/components/PlansPanel/utils.test.ts, packages/manager/src/features/components/PlansPanel/utils.ts
My previous [PR](https://github.com/linode/manager/pull/10407) (not yet released) introduced a regressions where the database resize plans disabled due to being smaller were not reflecting the original logic, due to a flaw in my understanding of the feature.
For plans of the **same size**:
expected: 
- resizing from dedicated to shared : **not allowed**
- resizing from shared to dedicated : **allowed**
The current bug in develop is the fact that resizing from dedicated to shared is allowed in Cloud Manager, but will result in an API error
- Add smallerPlan filtering to the `extractPlansInformation` util and use original DatabaseResize smaller plan disabling logic
- Update tests
**5/13/2024**
| ![Screen Shot 2024-05-08 at 15 49 …
=> fix: [M3-8057] - Disable dedicated > shared DatabaseResize same plan size selection

packages/manager/.changeset/pr-10445-tests-1715197562638.md, packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts, packages/manager/cypress/support/intercepts/placement-groups.ts
Adds a Cypress integration test for basic Placement Group create flow. It confirms that a Placement Group can be created from the landing page, that the outgoing API request contains the expected payload, and that Cloud responds as expected by showing a toast and updating its content upon successful Placement Group creation.
- Adds PG create test in `cypress/e2e/core/placementGroups/create-placement-groups.spec.ts`
- Adds PG create mock util
`yarn && yarn build && yarn start:manager:ci`, and then:
```bash
yarn cy:run -s "cypress/e2e/core/placementGroups/create-placement-groups.spec.ts"
```
Alternatively, you can run the test via `yarn cy:debug`.
=> test: [M3-7772] - Add Cypress integration test for Placement Group create flow

packages/manager/src/components/CopyTooltip/CopyTooltip.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Actions.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Region.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts, packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.test.tsx, packages/manager/src/features/Linodes/LinodesCreate/ApiAwarenessModal/ApiAwarenessModal.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
- Adds the "Create using Command Line" button to the new Linode Create flow 🎉 
- Enable the `Linode Create v2` feature flag using local dev tools
- Verify you see the `Create Using Command Line` button at the bottom of the new Linode Create flow
- Verify the create using command line works as expected and opens the dialog with the correct information 📄
=> refactor: [M3-8080] - Linode Create Refactor - Add API/CLI Modal

packages/manager/.changeset/pr-10455-upcoming-features-1715611895814.md, packages/manager/src/components/DetailsPanel/DetailsPanel.test.tsx, packages/manager/src/components/DetailsPanel/DetailsPanel.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.test.tsx, packages/manager/src/components/PlacementGroupsSelect/PlacementGroupsSelect.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Details/PlacementGroupPanel.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/Linodes/MigrateLinode/ConfigureForm.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAssignLinodesDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsCreateDrawer.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.test.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/constants.ts, packages/manager/src/queries/linodes/linodes.ts, packages/manager/src/queries/placementGroups.ts
This PR addresses small tech debt left by iterations on the PlacementGroupSelect component and related utils.
- `PlacementGroupSelect` now filters PGs via query instead of client-side
- Cleanup `PlacementGroupSelect` props and remove what's unused
- Remove duplicate state management in `PlacementGroupDetailPanel`
- Use `selectedPlacementGroupId` rather than the whole PG object for prop drilling
- Allow `useAllPlacementGroupsQuery` query to take a filter
- Small capitalization copy change for the `PlacementGroupSelect`  `noOptionsMessage`
There should be no visual change as a result of this PR
ℹ️ Test in ALPHA
- Confirm behavior of PG select in Linode Create Flow (both v1 and v2)
- Make sure PGs are properly filtered by region
- Make sure flows work and PG is selected in the final payload …
=> upcoming: [M3-7993] - PlacementGroups Select optimizations & cleanup

packages/manager/.changeset/pr-10446-tests-1715197487403.md, packages/manager/cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts, packages/manager/cypress/support/intercepts/placement-groups.ts
Adds a test to confirm the populated state of the Placement Group landing page. Specifically, confirms that each Placement Group is listed as expected and that non-compliance indicator is present when necessary (and absent otherwise).
- Adds Placement Group populated landing page test
- Adds a mock util that will be necessary but didn't actually get used
```bash
yarn cy:run -s "cypress/e2e/core/placementGroups/placement-groups-landing-page.spec.ts"
```
=> test: [M3-7771] - Add Placement Group populated landing page test

packages/manager/.changeset/pr-10467-tests-1715779598575.md, packages/manager/cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts, packages/manager/cypress/support/intercepts/nodebalancers.ts
Clean up cy.intercept calls in nodebalancer
- Replace calls to cy.intercept with intercept utils in nodebalancers.ts.
- Adds interceptCreateNodeBalancers() util
We can rely on CI to confirm that this test has not been broken by these changes, but to run the test locally you can use this command:
`yarn cy:run -s "cypress/e2e/core/nodebalancers/smoke-create-nodebal.spec.ts"`
=> test: [M3-6225] - Clean up cy.intercept calls in nodebalancer

packages/manager/.changeset/pr-10470-tests-1715719518601.md, packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
Quick fix for the StackScript test that began failing today because Fedora 38 got marked as deprecated. Also opened M3-8098 to improve this test's resilience to backend Image changes.
- Use up-to-date Images in StackScript test
We can rely on CI for this, but to run the test locally you can use this command:
```bash
yarn cy:run -s "cypress/e2e/core/stackscripts/create-stackscripts.spec.ts"
```
=> test: [M3-8102] - Fix StackScript test failure by using up-to-date images

packages/manager/.changeset/pr-10472-tests-1715794017061.md, packages/manager/cypress/e2e/core/notificationsAndEvents/events.spec.ts, packages/manager/cypress/e2e/core/notificationsAndEvents/notifications.spec.ts
Clean up cy.intercept calls in notification and events
Replace calls to cy.intercept with intercept utils in events.ts
We can rely on CI to confirm that this test has not been broken by these changes, but to run the test locally you can use this command:
```
yarn cy:run -s "cypress/e2e/core/notificationsAndEvents/*"
```
=> test: [M3-6226] - Clean up cy.intercept calls in notification and events

packages/manager/.changeset/pr-10478-tests-1715876232371.md, packages/manager/cypress/e2e/core/linodes/smoke-delete-linode.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts
Clean up cy.intercept calls in smoke-delete-linode
- Replace calls to cy.intercept with intercept utils in linodes.ts and account.ts
- Adds interceptDeleteLinode() util
We can rely on CI to confirm that this test has not been broken by these changes, but to run the test locally you can use this command:
```
yarn cy:run -s "cypress/e2e/core/linodes/smoke-delete-linode.spec.ts"
```
=> test: [M3-8106] - Clean up cy.intercept calls in smoke-delete-linode

packages/manager/.changeset/pr-10474-added-1715961690900.md, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.test.tsx, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx
This adds "Default Inbound Policy" and "Default Outbound Policy" to the Create Firewall Drawer.
The default inbound policy is now "Drop", which is a change from what Firewalls implicitly default to in Production today. Note: Cloud Manager currently specifies this default, not the API.
- Add "Default Inbound Policy" and "Default Outbound Policy" to the Create Firewall Drawer.
May 27, 2024
| ![Screenshot 2024-05-15 at 3 14 07 PM](https://github.com/linode/manager/assets/114753608/1f392e08-1b9d-4137-87e9-c5ffeee7599c) | ![Screenshot 2024-05-15 at 3 12 30 PM](https://github.com/linode/manager/assets/114753608/0a406d7c-33eb-4b4e-8910-7cd33fbe37aa) |
- Run the updated unit tests: `yarn test CreateFirewallDrawer`
- Open the Create Firewall Drawer and …
=> feat: [M3-8104] - Add options for default policies when creating a Firewall

packages/manager/.changeset/pr-10476-tests-1715869194947.md, packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts
Clean up cy.intercept calls in resize-linode
- Replace calls to cy.intercept with intercept utils in linodes.ts.
- Adds interceptLinodeResize() util
We can rely on CI to confirm that this test has not been broken by these changes, but to run the test locally you can use this command:
```
yarn cy:run -s "cypress/e2e/core/linodes/resize-linode.spec.ts"
```
=> test: [M3-8105] - Clean up cy.intercept calls in resize-linode

packages/manager/.changeset/pr-10483-tech-stories-1715958313413.md, packages/manager/src/components/LineGraph/AccessibleGraphData.tsx, packages/manager/src/components/LineGraph/LineGraph.tsx, packages/manager/src/dev-tools/FeatureFlagTool.tsx, packages/manager/src/featureFlags.ts, packages/manager/src/features/Linodes/LinodesDetail/LinodeNetworking/NetworkingSummaryPanel/TransferHistory.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/LinodeSummary.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeSummary/NetworkGraphs.tsx, packages/manager/src/features/Managed/ManagedDashboardCard/ManagedChartPanel.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx
This PR gets rid of the recharts feature flag in order to remove heavy dependencies we're shipping to our users in the Linode detail flow.
- `charts.js`
- `moment,js` (which is a dpendency of the above)
It cleans up conditional rendering of the old charts since everything has been stable since the new charts have been released.
Only remaining components using charts.js:
- `GaugePercent` 
- `LineGraph`
which are both only for longview 🎉 
🥇 Thanks @hana-linode for the super clean handling of splitting the feature initially, was very easy to clean up
- Remove flag and and old charts behind it
No visual change expected as part of this PR
- Confirm all charts are showing (recharts) in both the Linode detail/networking and managed UIs
=> refactor: [M3-8097] - Retire recharts feature flag

.gitignore, docs/development-guide/08-testing.md, package.json, packages/manager/package.json, packages/manager/vite.config.ts, yarn.lock
[`vitest-preview`](https://www.vitest-preview.com/) is a nifty package that lets you visually debug unit tests in the browser. I believe it could be a useful addition for our unit testing workflow.
- Add `vitest-preview` package and make related configuration changes
- Document how to use it to visually debug unit tests
- Follow the steps in the documentation to debug a test using vitest-preview
- Review documentation changes for readability, concision, and grammar/spelling errors
=> Add `vitest-preview` package and document usage

packages/manager/.changeset/pr-10490-fixed-1716227619276.md, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
We ended up with two speedtext helper texts displaying on the LKE Create Cluster form. I'm not entirely sure why this happened, but I think it was a combination of deciding where to place the helper text in this form once the pricing link was added *and* changes to RegionSelect and/or Autocomplete that made the helper text show up where it should be, when it wasn't originally due to some bug.
- Removed one of the helper texts. 
05/28
| ![Screenshot 2024-05-20 at 10 55 29 AM](https://github.com/linode/manager/assets/114685994/ebf99bc0-7159-4df9-bafa-aa6ee25be607) ![Screenshot 2024-05-20 at 10 55 15 AM](https://github.com/linode/manager/assets/114685994/a16f6718-f1cc-4944-8774-38ddb656fdd4) | ![Screenshot 2024-05-20 at 10 54 …
=> fix: [M3-8067] - Remove duplicate speedtest helper text in Create Cluster form

packages/manager/.changeset/pr-10473-tests-1715795923381.md, packages/manager/cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts, packages/manager/cypress/e2e/core/placementGroups/create-placement-groups.spec.ts, packages/manager/src/components/TextTooltip/TextTooltip.tsx, packages/manager/src/components/Tooltip.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsAffinityEnforcementRadioGroup.tsx, packages/manager/src/features/PlacementGroups/PlacementGroupsDetailPanel.tsx, packages/manager/src/features/PlacementGroups/constants.ts
PR to add an integration test to the Placement Group feature within Linode Create flow
The test covers the following:
- "Placement Group" Region capability including related notices
- Placement Group creation within the Linode Create flow
- Linode Creation with a placement group
- New `create-linode-with-placement-groups.spec.ts` test
- Add needed `data-test-id`
- Fix small issue with tooltip  `data-test-id` containing JSX element as a child (was showing as "Object Object")
- Confirm appropriate steps for the test
- run `yarn cy:run -s "cypress/e2e/core/placementGroups/create-linode-with-placement-groups.spec.ts"`
=> test: [M3-7991] - Integration Test: Linode Create with Placement Group 

packages/manager/.changeset/pr-10486-upcoming-features-1716217159383.md, packages/manager/src/features/PlacementGroups/PlacementGroupsDeleteModal.tsx
In the `PlacementGroupDeleteModal`, API error messages are persisting when encountering an error, closing the dialog and reopening it. This PR resets error messages on Close so the user the does see then when reopening the modal
- Reset delete and unassign queries errors on modal close
- ℹ️ test in ALPHA
- have at least one placement group created
- Navigate to http://localhost:3000/placement-groups/delete/{your placement group ID}
- In your network tab, block network request for `DELETE | https://api.dev.linode.com/v4/placement/groups/`
- Click on the "Delete" button
- Confirm "An unexpected error occurred." error message in dialog
- Close dialog
- Reopen by clicking on "Delete" for the same PG in the table row
- Confirm error is no longer in the modal (was without the fix) 
*Check all …
=> fix: [M3-8112] - Reset errors in PlacementGroupDeleteModal

package.json, packages/manager/.changeset/pr-10422-tech-stories-1714510098465.md, scripts/tod-payload/index.ts
This adds another script in `scripts/` to generate a payload for our internal test result store, TOD. See M3-7843 for the Cloud/TOD epic which provides more context and outlines our plan to integrate Cloud with TOD.
The purpose of this script is to consume a JUnit XML file (or a bunch of JUnit XML files) and output a TOD-compatible JSON payload. This payload contains the JUnit data itself, along with various metadata describing the project and test run.
I opted to add the script here because it will need to be invoked from Jenkins and from GitHub Actions, and wanted to avoid having to implement the same script twice.
- Add `yarn generate-tod` script
You'll need at least one JUnit XML file to test with. The quickest way to generate one is to pass `--reporter=junit` when invoking `yarn …
=> test: [M3-7844] - Add script to generate JSON payload for TOD test results

packages/manager/src/utilities/analytics/utils.ts
With our first implementation of form events (#10392) , there were some additional changes required that were not known in the initial implementation of code for the form event analytics. The working form events were reviewed by Front End and UX, but missing a complete MADS QA after added to the UI. (In the future, we will work this step into our review process for new/more complex analytics events to ensure this doesn't happen again.)
A MADS review of the changes was done after the PR was already merged, and changes requested are listed in the ticket tied to this subtask (M3-8126). While we work to clarify and confirm final changes, we need to stop the form analytics in develop from being released to prod. This subtask disables those events for now, since the release branch will be cut …
=> change: [M3-8129] - Temporarily disable form event analytics

packages/manager/.changeset/pr-10501-tech-stories-1716324364842.md, packages/manager/src/components/AccessPanel/AccessPanel.tsx, packages/manager/src/components/BackupStatus/BackupStatus.tsx, packages/manager/src/components/Checkbox.tsx, packages/manager/src/components/PasswordInput/PasswordInput.tsx, packages/manager/src/components/TextField.tsx, packages/manager/src/components/Toggle/Toggle.stories.tsx, packages/manager/src/components/Toggle/Toggle.test.tsx, packages/manager/src/components/Toggle/Toggle.tsx, packages/manager/src/components/TooltipIcon.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx, packages/manager/src/features/Images/ImageUpload.tsx, packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/UserData/UserDataHeading.tsx, packages/manager/src/features/Linodes/LinodesCreate/UserDataAccordion/UserDataAccordionHeading.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeConfigs/LinodeConfigDialog.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResizeUnifiedMigrationPanel.tsx, packages/manager/src/features/Linodes/LinodesLanding/LinodeRow/LinodeRow.tsx, packages/manager/src/features/Linodes/PublicIpsUnassignedTooltip.tsx, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx, packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/FieldTypes/UserDefinedText.tsx, packages/manager/src/features/StackScripts/UserDefinedFieldsPanel/UserDefinedFieldsPanel.tsx, packages/manager/src/features/VPCs/VPCDetail/AssignIPRanges.tsx, packages/manager/src/features/VPCs/VPCDetail/SubnetLinodeRow.tsx
In a recent user session, we were made aware that our tooltip are not accessible because often having the `disableInteractive` prop passed to them.
> Makes a tooltip not interactive, i.e. it will close when the user hovers over the tooltip before the leaveDelay is expired.
As a result, users complained they were unable to copy the test within tooltips to translate it (google translate or else).
While not having translations in Cloud Manager, this is an accessibility issue we can easily fix by removing this setting and making sure all tooltips are interactive. It does not seem to have any huge drawback to keep interactivity enabled by default for all tooltips (as far as we were able to tell) and the resulting behavior appears to outweigh any potential behavioral change in the way users …
=> refactor: [M3-8125] Remove and Prevent tooltip disableInteractive

packages/api-v4/.changeset/pr-10468-added-1716219170108.md, packages/api-v4/src/object-storage/index.ts, packages/api-v4/src/object-storage/prices.ts, packages/manager/.changeset/pr-10468-changed-1716219242980.md, packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts, packages/manager/src/factories/types.ts, packages/manager/src/features/Account/EnableObjectStorage.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/CreateBucketDrawer.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.test.tsx, packages/manager/src/features/ObjectStorage/BucketLanding/OveragePricing.tsx, packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.test.tsx, packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/objectStorage.ts, packages/manager/src/utilities/pricing/dynamicPricing.test.ts, packages/manager/src/utilities/pricing/dynamicPricing.ts
API is now returning pricing data through the `/object-storage/types` endpoint. 
In this PR, prices can be dynamically displayed for base region pricing and DC-specific region pricing, using the prices returned in the new endpoint, for Object Storage.
> [!NOTE]  
> Outbound transfer overages will be done in a follow-up PR, since pricing for network transfer overages is the same across Cloud Manager and not currently being returned by the API. They are creating a new endpoint for this.
- Created the necessary api-v4 endpoint, query, and interface to use the object-storage/types endpoint.
- Modified `getDCSpecificPriceByType` to optionally accept interval (hourly or monthly) and decimal precision params and updated util unit test accordingly.
- Created the necessary factories and endpoint …
=> refactor: [M3-7382] - Use `object-storage/types` endpoint for pricing data 

packages/manager/.changeset/pr-10509-fixed-1716415172498.md, packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallLanding.tsx
Fix bug where we were trying to fetch devices with an invalid Firewall id
| ![image](https://github.com/linode/manager/assets/115299789/d8f56067-552a-4422-8f8d-7217cd34b0cd) | ![image](https://github.com/linode/manager/assets/115299789/63201a5a-b79a-4a68-ad73-22a4060fd9ea) |
- Go to the Firewalls landing page `/firewalls` and observe the devices network request. Notice failed device requests with a -1 firewall id
- Go to the Firewalls landing page `/firewalls` and observe the devices network request. Notice no more failed device requests
=> fix: [M3-8042] - Firewall landing device request with -1 ID

packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/StackScripts/UserDefinedFields/UserDefinedFieldInput.tsx
Fixes bugs and console errors with Linode Create v2 User Defined Fields 🐛 
| <video src="https://github.com/linode/manager/assets/115251059/e0cc6c9a-fda5-49f6-a3cc-d8e58835c6e4" /> | <video src="https://github.com/linode/manager/assets/115251059/98ce6dd1-6311-43d8-83c0-da7da70a2ae2" />  |
- Enable the Linode Create v2 flag
- Test UFDs for various StackScripts or marketplace apps
- To test a multi-select you can use the `lillq / Apache, MySQL, Ruby Setup` on the community tab
=> fix: Linode Create v2 - UDFs

packages/manager/.changeset/pr-10506-tests-1716399579811.md, packages/manager/cypress/e2e/core/images/create-linode-from-image.spec.ts, packages/manager/cypress/e2e/core/longview/longview.spec.ts
Some of our Cypress tests have stray calls to console.log and similar functions (console.info, console.error, etc.), and these should be removed.
Remove console.log functions in the spec files (cypress/e2e/*/)
```
yarn cy:run -s "cypress/e2e/core/longview/longview.spec.ts,cypress/e2e/core/images/create-linode-from-image.spec.ts"
```
=> test: [M3-7557] - remove console logs from e2e tests

packages/manager/src/features/Images/ImagesDrawer.tsx
In #10466 I accidentally committed a `Promise.reject` that was intended to test error handling in `ImagesDrawer`.
- Delete testing error
Verify images can be edited without generating the test error.
=> fix: Delete testing error introduced by mistake

packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts
- I made a mistake in https://github.com/linode/manager/pull/10471 (specifically [here](https://github.com/linode/manager/pull/10471/files#diff-900b58e628d8181eeabb2f9ad13f1134a69af7ca3573aa1b38a8dd51e089b5faR135-R137))
- I removed the `randomLabel()` from the `createImage` call because at the time, it didn't occur to me that the image label mattered for the sake of the test. I was correct in that sense, but I failed to remember that cypress only cleans up entities that are prefixed with `cy-test` 🤦 . Our test accounts are filling up with Images that are not being cleaned up as a result 😣
- This PR adds back the `randomLabel()` so the image is created with a label that will be cleaned up
- Verify the image created by `create-stackscripts.spec.ts` are prefixed with `cy-test`
=> fix: Cypress test creating an Image without a `cy-test` prefixed label

packages/manager/.changeset/pr-10519-upcoming-features-1716918242639.md, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
This PR checks the length of regions before reading its data while rending Table cell in Access Key table.
6/7
- Use dev env and dev account with appropriate account tags.(reach me if you need help on account tags).
- Navigate to http://localhost:3000/object-storage/access-keys
- Verify Access Key landing page renders.
- Navigate to http://localhost:3000/object-storage/access-keys
- Verify Access Key landing page renders.
=> fix: [M3-8164] - regions length check

packages/manager/.changeset/pr-10496-tech-stories-1716315886330.md, packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts, packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx, packages/manager/src/queries/support.ts
Updates Support Ticket Queries to use a query key factory and latest patterns
- Uses query key factory for support ticket queries 🏭 
- Uses v5 compatible patterns to make upgrading easier in the future 📦  (see [here](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#supports-a-single-signature-one-object))
- Updates mutation handles to be a bit more optimized with the invalidations  🔁
> [!note]
> No UI changes
> [!warning]
> I recommend testing this in dev so that our support team does not get test tickets coming in
- Test support tickets in general
- Test creating a Support Ticket
- Verify cache updates as expected 
- Test adding a comment to a support ticket
- Verify cache updates as expected
=> refactor: [M3-8128] - Query Key Factory for Support Tickets

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/components/TextTooltip/TextTooltip.test.tsx, packages/manager/src/components/TextTooltip/TextTooltip.tsx
A bug/artifact [I introduced](https://github.com/linode/manager/pull/10473/files#diff-12683df425c3158844e1a0ae2f06f393deb4a8d757ffddda5ea966624c52730dR69) for testing purposes while writing an end to end test (mea culpa 😭).
- Remove erroneous `leaveDelay` on `<TextTooltip />`
- Add unit
5/29/2024
Use PROD
- Go to linode/create
- select a region
- Scroll down the the details panel
- Hover over Placement Groups "region"
- Notice tooltip won't go away
- Go to linode/create
- select a region
- Scroll down the the details panel
- Hover over Placement Groups "region"
- Confirm tooltip goes away
=> hotfix: [M3-8182] - Remove leaveDelay from TooltipText

packages/manager/.changeset/pr-10429-fixed-1716930064091.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeSettings/InterfaceSelect.tsx
There were a couple of problems in the Add/Edit Configuration dialog:
- Interface select errors were not always being surfaced.
- ~**This was fixed in PR #10459:** General errors were not reliably being focused by `scrollErrorIntoView` because the scrolling can happen before the general error is updated in form state (via `formik.setStatus`), and therefore there is no notice to scroll to in the DOM, since `generalError` being defined is a condition for rendering the notice.~
> [!NOTE] 
> This PR's scope is small. There is more going on with the Linode Config Dialog because it's too large of a component handling both Create and Edit state and should be refactored. This is resulting in:
> -  A bug related to form state for the `interfaces` array causing it to sometimes display incorrect …
=> fix: [M3-7977] - Surface interface error in Linode Config dialog 

packages/manager/.changeset/pr-10515-added-1716569243109.md, packages/manager/cypress/e2e/core/parentChild/account-switching.spec.ts, packages/manager/src/features/Account/SwitchAccountDrawer.test.tsx, packages/manager/src/features/Account/SwitchAccountDrawer.tsx, packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.test.tsx, packages/manager/src/features/Account/SwitchAccounts/ChildAccountList.tsx, packages/manager/src/mocks/serverHandlers.ts
This PR brings two improvements to the Switch Account drawer, allowing users with hundreds of child accounts to more easily navigate that list:
1. Search capabilities on the company name
2. Alphabetization of the list of company names
We are already incrementally fetching the list using an infinite query, but the existing UI still requires scrolling and visually searching, which can be a burden on the user.
- Sorted the list of child accounts alphabetically.
- Added a search bar and functionality to filter the child account list based on company name.
- Updated the info notice to show more accurate terminology and slightly more specific helper text if there are no results.
- Added unit test and Cypress test coverage.
06/10
https://github.com/linode/manager/assets/114685994/525d3e2a-e7d9-48 …
=> feat: [M3-7883] - Add search and alphabetical sorting to Switch Account drawer

packages/api-v4/.changeset/pr-10503-added-1716386367795.md, packages/api-v4/.changeset/pr-10503-changed-1716386563929.md, packages/api-v4/src/databases/databases.ts, packages/api-v4/src/databases/types.ts, packages/manager/.changeset/pr-10503-tech-stories-1716386590480.md, packages/manager/src/factories/databases.ts, packages/manager/src/features/Databases/DatabaseCreate/DatabaseCreate.tsx, packages/manager/src/features/Databases/DatabaseDetail/AccessControls.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/DatabaseBackups.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseBackups/RestoreFromBackupDialog.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResize.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseResize/DatabaseResizeCurrentConfiguration.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsDeleteClusterDialog.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/DatabaseSettingsResetPasswordDialog.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSettings/MaintenanceWindow.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryClusterConfiguration.tsx, packages/manager/src/features/Databases/DatabaseDetail/DatabaseSummary/DatabaseSummaryConnectionDetails.tsx, packages/manager/src/features/Databases/DatabaseDetail/index.tsx, packages/manager/src/features/Databases/DatabaseLanding/DatabaseLanding.tsx, packages/manager/src/features/Databases/utilities.ts, packages/manager/src/features/Support/SupportTickets/SupportTicketDialog.tsx, packages/manager/src/hooks/useEventHandlers.ts, packages/manager/src/queries/databases.ts, packages/manager/src/queries/databases/databases.ts, packages/manager/src/queries/databases/events.ts, packages/manager/src/queries/databases/requests.ts, packages/manager/src/utilities/getEventsActionLink.test.ts
Updates React Query layer of Databases to adapt our latest patterns
- Updates Database queries to use a query key factory 🏭 
- Updates Database queries and mutations to use the "single object notation" (see [here](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5#supports-a-single-signature-one-object)) in efforts to make updating from v4 to v5 easier 📦 
- Updates some Database responses and types to match what the API actually returns 💡 
> [!note]
> No UI changes
- Checkout this PR locally and/or test with the internal preview link 🔗 
- Test Database functionality in general 👀 
- Verify general cache updates happen as expected. For example, renaming a database should propagate to all screens
- Verify all Database automated testing passes ✅
=> refactor: [M3-8130] - Query Key Factory for Databases

packages/manager/.changeset/pr-10527-fixed-1717019227934.md, packages/manager/src/features/Firewalls/FirewallLanding/FirewallRow.tsx
Tiny PR to close out a ticket I made many months ago that was sitting in the backlog.
On the Firewalls landing page, linked linodes and NBs in the Services column list have some extra leading white space included in the link.
- Moved the comma and spacing out of the Link component.
- Very minor string clean up.
6/10
| ![Screenshot 2024-05-29 at 1 52 30 PM](https://github.com/linode/manager/assets/114685994/c06f2c01-68cf-40ca-8e59-1d618a5fc4fa)| ![Screenshot 2024-05-29 at 1 52 03 PM](https://github.com/linode/manager/assets/114685994/1885ea2f-7d60-4af7-8777-ff04ca93c265) |
- Have a combination of at least 4 linodes or nodebalancers on your account, or create them.
1. Go …
=> fix: [M3-7717] - Fix leading whitespace in list of Linode and Nodebalancer links for Firewall Services

packages/manager/.changeset/pr-10531-fixed-1717084620266.md, packages/manager/src/components/CheckoutBar/styles.ts
The Cluster Summary section needs some padding on the left-hand side at breakpoints between 1280px and tablet view (960px).
- Changed the breakpoint from `md` to 1280, which is when the checkout bar is no longer visually a sidebar. This happens before we hit the tablet breakpoint. 
6/10
| ![Screenshot 2024-05-29 at 4 09 59 PM](https://github.com/linode/manager/assets/114685994/9b7aeba6-82ec-4c4e-ae92-ff0e8cd1a908) | <video src="https://github.com/linode/manager/assets/114685994/a7d8ed04-b8e8-4ed8-b0c8-f91e932309e8" /> |
- Use the dev tools to set screen size < 1280 and >= 960
- Go to https://cloud.linode.com/kubernetes/create
- Observe the Cluster Summary section is too close to the edge of the paper …
=> fix: [M3-7592] - Fix misalignment of Cluster Summary at small desktop screen sizes

packages/manager/.changeset/pr-10529-tests-1717072137790.md, packages/manager/cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts, packages/manager/cypress/support/intercepts/placement-groups.ts
This adds Cypress integration tests for the Placement Group update label flow via Placement Group's landing page.
- Two new mocking functions for the label update flow: `mockUpdatePlacementGroupLabel()` and `mockUpdatePlacementGroupLabelError()`
06/10/2024
- Check this branch out and run 
```
yarn cy:run -s "cypress/e2e/core/placementGroups/update-placement-group-label.spec.ts"
```
- Or you can run the tests in `debug` mode by running `yarn cy:debug`.
- Verify that all tests are passing.
- Validate that the flows and assertions covered by these changes are adequate.
=> test: [M3-7784] - Cypress integration tests for Placement Group update label flow

packages/manager/.changeset/pr-10534-fixed-1717169773875.md, packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx
`useAllFirewallDevicesQuery` was not always being invalidated when modifying a Firewall.
As a result, without refreshing the page, adding/deleting rules or enabling/disabling a Firewall with assigned device(s) will not show the Firewall's most accurate status or rules on the NodeBalancer Details > Settings  or Linode Details > Network tab if the query for that Firewall has already been cached because the page was previously visited.
- Added query invalidation on submission of the Firewall Dialog for enabling and disabling a Firewall.
- Added query invalidation on submission of updated Firewall rules.
- Cleaned up naming of query keys for consistency (capitalization; made query key plural for `nodebalancers`).
6/10
| <video …
=> fix: [M3-7718] - Stale assigned Firewall data displaying on Linode and NodeBalancer details pages

packages/manager/.changeset/pr-10536-changed-1717183226858.md, packages/manager/cypress/e2e/core/linodes/plan-selection.spec.ts, packages/manager/src/features/Kubernetes/KubernetesPlansPanel/KubernetesPlansPanel.tsx, packages/manager/src/features/components/PlansPanel/PlanInformation.test.tsx, packages/manager/src/features/components/PlansPanel/PlanInformation.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx, packages/manager/src/features/components/PlansPanel/utils.ts
This PR modifies the display logic of the limited availability banner in the Selection Plan. This is the result of product wanted to limit the display of the banner, especially as it relates to the 512Gb plan since the banner would always display for any class with a 512 plan.
The solution was to only display the banner if more than half of the plans are disabled. Since that logic already existed for the disabled tooltip, I leveraged this util to apply it to the notice.
As a result, the logic is as follow:
- If more than half plans are disabled, show the limited availability banner and hide the limited availability tooltip
- If less than half plans are disabled, hide the limited availability banner and show the limited availability tooltip
Additionally, it was decided to include the …
=> change: [M3-8159] - Modify limited availability banner display logic

packages/manager/.changeset/pr-10540-added-1717433580405.md, packages/manager/.changeset/pr-10540-tech-stories-1717433580405.md, packages/manager/.eslintrc.cjs
Tiny PR to start enforcing `consistent-type-imports` through the codebase (`import type` for type file)
https://typescript-eslint.io/rules/consistent-type-imports
This will remain a warning it does not affect the developer experience negatively other than suggesting to make that change when creating or editing a file. It will also make it easier/quicker to fix those via shortcuts when encountered.
- Add `consistent-type-imports` warning to our `es-lint` rules
- Pull locally and open random file to see the new lint warning
=> change: [M3-6541] - eslint: consistent-type-imports

packages/manager/.changeset/pr-10555-upcoming-features-1717778847157.md, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/OMC_AccessKeyDrawer.tsx
This PR prevents causing potential defect of crashing the Access key landing page when flag is on but no tags are assigned to the customer.  
6/10
- Checkout to develop
- Turn the OBJ flan on. use the account that doesn't have obj regions tag.
- Verify the Accesskey landing page.
- Checkout to develop
- Turn the OBJ flan on. use the account that doesn't have obj regions tag.
- Verify Accesskey landing page.
- Verify Edit/ Permission / Revoke actions for the key.
=> upcoming: [M3-8218] - Obj fix for crashing accesskey page when relevant customer tags are not added.

packages/manager/src/features/ObjectStorage/EnableObjectStorageModal.tsx
This PR fixes two bugs in the Access Key drawer caused by the transition to `object-storage/types` (#10468).
The two issues were that:
1. Since we were disabling the query conditionally, we needed to be using `isInitialLoading` rather than `isLoading` to avoid getting stuck in perpetual loading state
2. Even with the above change, we were still using a value from the query to determine the fallback pricing. If the query was disabled, then that value would be undefined, and we'd see the $--.-- (unknown pricing) for Access Keys. 
- Remove the condition that disabled the query when `regionId` was not provided. This means that the query will always run, which we want to be the case so we can get pricing from the API even when there is no `regionId` (e.g. for Access Keys). If there *is* a …
=> fix: [M3-8162] - Inability to create access keys due to incorrectly running `/types` query

packages/manager/.changeset/pr-10559-tech-stories-1718119071574.md, packages/manager/src/queries/domains.ts
- Updates domain queries to use the query key factory 🏭 
- Updates functions to use single object notation to prepare for the v4 to v5 upgrade (see [here](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#supports-a-single-signature-one-object)) 🔧 
> [!note]
> No UI changes expected
- Test general functionality of **Domains** in Cloud Manager 👀🌎
=> refactor: [M3-8127] - Query Key Factory for Domains

packages/manager/.changeset/pr-10546-tests-1717604850412.md, packages/manager/.changeset/pr-10546-upcoming-features-1717603180090.md, packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts, packages/manager/src/components/DiskEncryption/constants.tsx, packages/manager/src/features/Kubernetes/KubernetesLanding/KubernetesLanding.tsx
Add a dismissible banner regarding disk encryption to the Kubernetes landing page.
Initially I mentioned in the ticket to consider using `ProductInformationBanner` for this, but that's not well-suited to this case because this banner needs to be feature flagged.
- Organize `DiskEncryption/constants.ts` file better
- Add dismissible Disk Encryption info banner to Kubernetes landing page
6/24
1. Have the `linode_disk_encryption` tag on your account
2. Point at the alpha/dev environment
3. Have the Linode Disk Encryption (LDE) flag in our dev tool toggled on
Without the tag and/or with the LDE flag in our dev tool toggled off, you should not see any LDE-related things in the UI. Otherwise,
- Navigate to the Kubernetes landing page
- Confirm: you see a dismissible banner that reads, "Disk …
=> upcoming: [M3-8031] – Add Disk Encryption info banner to Kubernetes landing page

packages/manager/.changeset/pr-10552-tests-1717702940797.md, packages/manager/cypress/e2e/core/placementGroups/placement-groups-navigation.spec.ts
This PR adds integration tests for the Placement Groups navigation with the feature flag on and off.
- Tests for displaying and hiding the `Placement Groups` item in the sidebar navigation.
- Tests for manual navigation to `/placement-groups` when feature flag is disabled.
- No visual changes.
- Run the tests by running 
- `yarn cy:debug` and selecting the `placement-groups-navigation.spect.ts` test.
- Or run `yarn cy:run -s "cypress/e2e/core/placementGroups/placement-groups-navigation.spect.ts"` from the terminal.
=> test: [M3-7769] - Add Placement Groups Navigation Integration Tests

packages/manager/.changeset/pr-10556-tech-stories-1717782967942.md, packages/manager/src/features/Firewalls/FirewallDetail/Devices/AddNodebalancerDrawer.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Devices/RemoveDeviceDialog.tsx, packages/manager/src/features/Firewalls/FirewallDetail/Rules/FirewallRulesLanding.tsx, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx, packages/manager/src/features/Firewalls/FirewallLanding/FirewallDialog.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerConfigurations.tsx, packages/manager/src/features/NodeBalancers/NodeBalancerDetail/NodeBalancerSummary/TablesPanel.tsx, packages/manager/src/hooks/useEventHandlers.ts, packages/manager/src/queries/nodebalancers.ts
- Updates NodeBalancer queries to use a Query Key Factory and latest TanStack query patterns
> [!note]
> No UI changes expected
- Generally test all NodeBalancer related features
- Test assigning / unassigning NodeBalancers from Firewalls 
- Verify all NodeBalancer automated tests pass
=> refactor: [M3-8216] - NodeBalancer Query Key Factory

packages/manager/.changeset/pr-10477-tests-1717448262964.md, packages/manager/cypress/e2e/core/account/ssh-keys.spec.ts, packages/manager/cypress/support/constants/account.ts, packages/manager/cypress/support/intercepts/profile.ts
Add integration test to add SSH key via Profile page.
- Check users can add SSH key through Profile page
```
yarn cy:run -s "cypress/e2e/core/account/ssh-keys.spec.ts"
```
=>  test: [M3-7954] - Cypress integration test to add SSH key via Profile page

packages/manager/cypress/e2e/core/kubernetes/lke-landing-page.spec.ts
This tweaks our new LKE disk encryption banner tests to be more resilient to differences between our development accounts and our CI test accounts. Specifically, our CI test accounts often don't have LKE clusters, so I added mocks so that the tests continue to pass when this is the case.
I don't think a changelog entry is necessary here since these tests have not been included in a release yet.
- Mock clusters for both LKE landing page disk encryption banner tests
We can rely on the automated tests for this since they're currently failing consistently, but you can also run the test locally if you want to check it out:
```bash
yarn cy:run -s "cypress/e2e/core/kubernetes/lke-landing-page.spec.ts"
```
=> test: Improve disk encryption banner test in CI

packages/manager/.changeset/pr-10574-tests-1718222529272.md, packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts
The StackScript pagination test has recently started failing. It's failing because Cypress is not scrolling down far enough in the page to trigger pagination, although I'm not sure specifically what changed to cause this to happen.
I've cleaned up the test a bit and specifically changed it so that it will always scroll to the last item in the StackScripts list to trigger pagination.
We can rely on CI, or we can run it locally. I ran it on repeat 20 times (skipping the rest of the tests in the spec) and it passed each time:
```bash
repeat 5 yarn cy:run -s "cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts"
```
=> test: Improve stability of StackScript pagination test

packages/manager/.changeset/pr-10554-changed-1718122854647.md, packages/manager/cypress/support/ui/constants.ts, packages/manager/cypress/support/ui/pages/linode-create-page.ts, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Distributions.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx
Rename `Choose a Distribution` to `Choose an OS` in the Linode Create flow. The tab will stay as Distribution for now.
| ![distro](https://github.com/linode/manager/assets/115299789/1073ca09-5a4c-4366-88bc-79871e3b4973) | ![os](https://github.com/linode/manager/assets/115299789/75ce3eeb-cf60-4118-8e94-1f76b26b3f64) |
- Go to `/linodes/create?type=Distributions`
=> change: [M3-8153] - Rename to Choose an OS in Linode Create flow

packages/manager/.changeset/pr-10585-tests-1718380830458.md, packages/manager/cypress/e2e/core/account/security-questions.spec.ts
This mocks the profile request in the security questions test so that TFA is disabled in the API response. This is necessary to fix a test failure in our GHA runs (and soon our Jenkins runs), but is probably good to have mocked anyway just so the test runs consistently.
- Confirm that test continues to pass in CI
- Confirm that test passes when running using a test account that has TFA enabled
=> test: Mock profile to fix GHA test failure

README.md, packages/manager/.changeset/pr-10582-changed-1718310753730.md
Tiny PR to link our README to the new docs
- Update "Getting Started" and "Contributing" links to our new GH documentation pages
=> change: [M3-7646] - Link Cloud Manager README to new documentation pages

packages/manager/.changeset/pr-10581-tests-1718308219716.md, packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts, packages/manager/cypress/e2e/core/linodes/linode-config.spec.ts, packages/manager/cypress/e2e/core/linodes/rescue-linode.spec.ts, packages/manager/cypress/e2e/core/linodes/resize-linode.spec.ts
Since merging #10538, a few of our tests have become especially flaky. This appears to be caused by an API issue where the API responds with `400` `Linode busy` when performing some actions on Linodes that are attached to Firewalls. This happens most often when attempting to interact with a Linode that has just finished booting.
See also #10580, which makes this issue more reproducible for troubleshooting/exploration purposes.
- Avoid attaching Firewalls to Linodes in impacted tests, disabling internet access instead
- Increase clone test timeout (disabling internet access requires the Linode to have an image, which causes the clone operation to be slower)
We can rely on CI for this. Ideally all of the identified tests will pass without any flake.
To run the tests locally, use this …
=> test: Resolve Linode/Firewall E2E flake by using alternative security method

docs/CONTRIBUTING.md, packages/manager/.changeset/pr-10587-fixed-1718643059797.md
Follow up to https://github.com/linode/manager/pull/10582
Small fix to fix the display of the commit types list in out CONTRIBUTING doc page.
- fix markup
| ![Linode Manager Contributing](https://github.com/linode/manager/assets/130582365/af98ea43-570e-4b3a-a69f-c373c11940b4) | ![Contributing html screenshot](https://github.com/linode/manager/assets/130582365/6f31e728-4b76-4014-9020-0f05748c9896) |
- Pull code locally, run `yarn docs` and navigate to http://localhost:5173/manager/CONTRIBUTING.html
=> fix: [M3-7646]  CONTRIBUTING commit type list markup

packages/manager/.changeset/pr-10590-fixed-1718722141069.md, packages/manager/src/components/TextTooltip/TextTooltip.tsx
Small PR to add a missing `TabIndex` to the `TextTooltip` so that we can properly trigger the tooltip while navigation tabbing.
- Add a missing `TabIndex` to the `TextTooltip`
- One example where this can be tested is the Linode Create flow in the Plan Selection GPU tab, as shown in screenshot
=> fix: [M3-8269] - Accessibility: Add tabindex to TextTooltip

packages/manager/.changeset/pr-10591-tests-1718746383365.md, packages/manager/package.json, packages/manager/src/features/Events/utils.test.tsx, packages/manager/src/hooks/useOrder.test.tsx, packages/manager/src/index.tsx, packages/manager/src/queries/base.ts, packages/manager/vite.config.ts
This attempts to fix the hanging tests we've been dealing with recently in CI. This has been an issue when running the tests locally for a long time, but we recently began seeing the issue in CI as well (possibly related to the recent Vitest version upgrade).
The fix, if it works, involves modifying our React Query client factory to use our `oneTimeFetch` preset by default. Specifically, our `oneTimeFetch` preset sets the RQ cache time to `Infinity` per [React Query's recommendation](https://tanstack.com/query/v4/docs/framework/react/guides/testing#set-cachetime-to-infinity-with-jest) for testing. The query client that is used by the app will continue to use the `longLived` preset, but tests (existing and future) will get a `oneTimeFetch` query client unless another preset is specified. …
=> test: [M3-7330] - Attempt to fix hanging unit tests

packages/manager/.changeset/pr-10596-tests-1718806691101.md, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.test.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyTable/HostNameTableCell.tsx
This a followup of #10555 -  Adds unit test coverage for HostNameTableCell.
6/24
- Verify unit test for HostNameTableCell. 
- Verify access key landing page is working as expected.
=> test: Unit test coverage - HostNameTableCell

packages/manager/.changeset/pr-10583-fixed-1718375225734.md, packages/manager/src/components/TagCell/TagCell.test.tsx, packages/manager/src/components/TagCell/TagCell.tsx, packages/manager/src/features/Linodes/LinodeEntityDetailFooter.tsx
Attempting to add a tag to the Linode would give the `"" already added` error, even if no text is entered or no tag has been applied. This is because a User must be an unrestricted User in order to add or modify tags on Linodes. This is actually explicitly mentioned in [the API docs](https://techdocs.akamai.com/linode-api/reference/put-linode-instance)
- Added account access grant check
- Added disabled tooltip text
- Added unit test
Next release
| <img width="452" alt="Screenshot 2024-06-14 at 10 23 05 AM" src="https://github.com/linode/manager/assets/125309814/75d2c4e2-4091-4310-9c81-f453e23c6d1a"> | <img width="255" alt="Screenshot 2024-06-14 at 9 40 15 AM" src="https://github.com/linode/manager/assets/125309814/203fd06c-900e-4195-a727-cee7e87 …
=> fix: [M3-8193] - Check account access for disabling add tags button

packages/manager/.changeset/pr-10602-tests-1718985699307.md, packages/manager/cypress/e2e/core/objectStorage/access-key.e2e.spec.ts, packages/manager/cypress/e2e/core/objectStorage/access-keys.smoke.spec.ts, packages/manager/cypress/e2e/core/objectStorage/enable-object-storage.spec.ts, packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts, packages/manager/cypress/e2e/core/objectStorage/object-storage.smoke.spec.ts
- Updates Object Storage Cypress tests to mock account `capabilities` as needed 👤 
- We need to mock capabilities because the API recently turned on the `Object Storage Access Key Regions` capability and many of our tests were written under the assumption that `Object Storage Access Key Regions` was not returned in `capabilities`
- Verify Cypress tests pass ✅
=> test: Update Object Storage tests to mock account `capabilities` as needed

packages/manager/CHANGELOG.md, packages/manager/package.json, packages/manager/src/features/ObjectStorage/BucketDetail/BucketDetail.tsx, packages/manager/src/features/ObjectStorage/utilities.ts, packages/manager/src/utilities/accountCapabilities.ts
- Fixes incorrect Object Storage URLs given to users by Cloud Manager when Multi-Cluster is **enabled**
- Cloud Manager was putting the **region id** in the URL instead of the expected **cluster id**
| <video src="https://github.com/linode/manager/assets/115251059/c1fdacfb-4541-4e7d-9d3a-a2e3c65153ed" /> | <video src="https://github.com/linode/manager/assets/115251059/fa880759-5d2e-46cc-a422-12836caeb4ff" /> |
- Make sure you have an Object Storage bucket on your account
- Using an existing object (or upload a new object), open that object's details drawer
- Verify the link in that details drawer brings you to the object 🔗
=> fix: Object Storage Object URLs

packages/manager/CHANGELOG.md, packages/manager/src/factories/account.ts, packages/manager/src/featureFlags.ts, packages/manager/src/features/Billing/PdfGenerator/PdfGenerator.ts
1. For JP customers, invoices must include both a QI Registration # and the tax rate in order to apply for purchase tax credit. This adds the tax rate to the invoice.
2. For EU customers, invoices will include VAT for B2C transactions and exclude VAT for B2B transactions. We will show both the VAT and B2B tax id numbers on the invoice template for EU countries.
- Created country map for targeting
- Added `Standard Tax is 10%` to the JP invoices
- Added `Switzerland VAT: CHE-115.356.067 MWST` for EU B2B invoices
LD additions to Tax object:
```
"tax_ids": {
"B2B": {
"tax_id": "CHE-115.356.067 MWST",
"tax_name": "Switzerland VAT"
}
}
```
6/24
> [!note]
`Swiss:` has been updated to `Switzerland VAT:`
- Turn on MSW
- Change account country to "JP" in MSW
- …
=> added: [M3-8008, M3-8277] - Update invoices for JP and EU

packages/manager/.changeset/pr-10584-fixed-1718376872460.md, packages/manager/src/features/NotificationCenter/NotificationData/useEventNotifications.tsx
We have a conditional hook in our code that could cause a runtime crash. We don’t pass any givenEvents anywhere in the app, so I guess we’ve just never had a problem with it
- Renamed some variables for clarity
- Added a return type to avoid type casting
Next release
- Run linter and ensure it passes
- Check events and ensure there's no changes (there shouldn't be)
- For fun, you can pass in `providedEvents` and see app crash.
=> fix: [M3-8264] - Conditional invocation of useEventInfiniteQuery hook

packages/api-v4/.changeset/pr-10589-upcoming-features-1718971604339.md, packages/api-v4/src/cloudpulse/dashboards.ts, packages/api-v4/src/cloudpulse/index.ts, packages/api-v4/src/cloudpulse/types.ts, packages/api-v4/src/index.ts, packages/manager/.changeset/pr-10589-upcoming-features-1718716331830.md, packages/manager/src/features/CloudPulse/Overview/GlobalFilters.tsx, packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.test.tsx, packages/manager/src/features/CloudPulse/shared/CloudPulseDashboardSelect.tsx, packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.test.tsx, packages/manager/src/features/CloudPulse/shared/CloudPulseRegionSelect.tsx, packages/manager/src/features/CloudPulse/shared/CloudPulseResourcesSelect.tsx, packages/manager/src/mocks/serverHandlers.ts, packages/manager/src/queries/cloudpulse/dashboards.ts
1. Added Dashboard Selection component inside the Global Filters of CloudPulse view.
1. Created a new component CloudPulseDashboardSelect.
2. Added the component into the GlobalFilters of Monitor landing page.
3. Added a new useCloudViewDashboardsQuery method to fetch all available dashboards.
4. Added unit tests for the dashboard selection component.
5. Removed the hard-coded service type passed to resource selection component into the global filters.
6. Added a clearable option for region selection component
:bulb: Use `<video src="" />` tag when …
=> upcoming: [DI-19062] - Dashboard Select component in cloudpulse global filters view

packages/manager/.changeset/pr-10609-tests-1719255666019.md, packages/manager/cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts
This fixes the failure in `cypress/e2e/core/objectStorage/object-storage.e2e.spec.ts` that's currently present in `develop`. The test is failing because it navigates directly to the bucket, and the URL we're using for that is out-of-date (`/object-storage/buckets/:cluster` instead of `/object-storage/buckets/:region`). As a result, Cloud Manager eventually fails to retrieve a desired object's URL, causing the URL not to be rendered in the object details drawer which triggers a failure.
Our OBJ tests are in a messy state since some of the tests target multicluster and others don't, and this PR probably worsens the situation. I'll follow up by writing some tickets to organize these tests and add coverage where it's lacking.
- Resolve failure by navigating to …
=> test: Fix Cypress failure by accounting for OBJ Multicluster in upload test

packages/manager/cypress/e2e/core/helpAndSupport/open-support-ticket.spec.ts
This fixes a failure in one of our new Help & Support tests that's occurring in CI -- the test checks the support ticket form's validation error behavior and asserts the presence of a note stating that no LKE entities exist. This assertion fails on test accounts that do have clusters, so this PR mocks the cluster request to ensure the form behaves as expected.
- Mock empty LKE clusters array so that expected validation message always appears
- Remove hardcoded domain label to make test more resilient to factory changes and Factory.ts sequence tracking
It's probably best to test this one manually since we can't guarantee whether a CI account will (or will not) have LKE clusters.
1. Create an LKE cluster on your account
2. Run the test via `yarn cy:run -s …
=> test: Fix CI support ticket test failure by mocking clusters

packages/manager/.changeset/pr-10615-tests-1719412831217.md, packages/manager/cypress/e2e/core/domains/smoke-create-domain-records.spec.ts, packages/manager/cypress/support/api/domains.ts, packages/manager/cypress/support/constants/domains.ts
The domain record tests in `smoke-create-domain-records.spec.ts` are parameterized against an array containing 5 items (each item representing a domain record type that can be created). This PR combines the tests into a single test which attempts to create each type of record as a result. By reducing the number of tests from 5 to 1, it results in a more performant solution (cuts test run time in half).
- Combines the assertions from each record type creation in a single assertion.
2024/07/08
| ![before-change](https://github.com/linode/manager/assets/119514965/8b47919d-7c7b-4cbc-9927-124f2b736382) | ![after-change](https://github.com/linode/manager/assets/119514965/dcb34410-7244-4019-9aab-a119067db4b5) | …
=> test: [M3-7320] - De-Parameterize Cypress Domain Record Create Tests

packages/manager/.changeset/pr-10622-tests-1719519067716.md, packages/manager/cypress/e2e/core/general/smoke-deep-link.spec.ts, packages/manager/cypress/support/ui/constants.ts
The tests in the `deep-link-smoke.spect.ts` spec were originally parameterized against an array containing 19 items, and each test made one or two assertions. This PR de-parameterizes the tests and combines them into a single test that checks each deep link. In the end, it eliminates 18 tests and cuts down the test run time.
- Replaced deprecated methods.
- Updated the `Page` interface by removing the `first` and `skip` properties.
- Removed the nested ternary assertion logic.
2024/07/08
| ![7319-before](https://github.com/linode/manager/assets/119514965/e692ed76-82e8-43c2-a8c1-462cf0dcb660) | ![7319-after](https://github.com/linode/manager/assets/119514965/5d839145-e307-4faf-a8d5-6b907dc09eb3) |
(How to …
=> test: [M3-7319] - De-Parameterize Cypress Deep Link Smoke Tests

packages/manager/.changeset/pr-10611-upcoming-features-1719332278758.md, packages/manager/src/features/Linodes/index.tsx
- Prevent Linode Create v2 from toggling mid-creation
- We are doing this so that if we need to toggle the flag, the user's form progress to be lost. That could be frustrating to a user 😠 
| <video src="https://github.com/linode/manager/assets/115251059/546cb772-b4a8-41f9-a1c9-6c2780de08f2" /> | <video src="https://github.com/linode/manager/assets/115251059/2463eab5-9559-490f-8982-f04f0cbc09ab" /> |
| Notice how the form resets when the flag is toggled because the create flows changed | Notice how the create flow does not change when the flag is toggled | 
- By toggling the flag with local dev tools, verify the form does not reset when the flag is toggled
=> upcoming: [M3-8282] - Prevent Linode Create v2 from toggling mid-creation

packages/manager/.changeset/pr-10629-upcoming-features-1719848495146.md, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Marketplace/AppSelect.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/resolvers.ts, packages/manager/src/features/Linodes/LinodeCreatev2/schemas.ts
Surfaces a `You must select a Marketplace App.` error on the Linode Create v2 Marketplace tab if no app is selected 🚫 
| ![Screenshot 2024-07-01 at 11 38 26 AM](https://github.com/linode/manager/assets/115251059/88888c8b-9599-45f8-b20a-12b105627156) | ![Screenshot 2024-07-01 at 11 37 48 AM](https://github.com/linode/manager/assets/115251059/b540a466-c68b-4315-bee7-3c563f3ad7ac) |
- Turn on Linode Create v2
- Verify you see an error saying `You must select a Marketplace App.` if you try to submit the form without selecting an app 👀 
- Verify this is parity with Linode Create v1
=> upcoming: [M3-8310] - Add Validation to Linode Create v2 Marketplace Tab

packages/manager/src/components/RegionSelect/RegionSelect.utils.tsx
Looks like there was a change made to the `isDistributedRegionSupported` function which caused a regression in the distributed regions displaying in the Linode Create flow
| ![image](https://github.com/linode/manager/assets/115299789/9ca25b9f-6990-4afc-b674-3d3509c77cec) | ![image](https://github.com/linode/manager/assets/115299789/c1f2cca2-8f0b-442d-ba6e-eafc167acd97) |
- Ensure your account has the `new-dc-testing`, `edge_testing` and `edge_compute` customer tags
- Go to the remote dev environment and observe no Distributed regions in the Linode Create flow
- Either locally or in the preview link, go to the Linode Create flow. Distributed …
=> fix: Distributed regions not displaying in the Linode Create flow

packages/manager/.changeset/pr-10593-tests-1718736692043.md, packages/manager/cypress/e2e/core/kubernetes/lke-create.spec.ts
Assertions should be added to the [LKE creation e2e test](https://github.com/linode/manager/blob/develop/packages/manager/cypress/e2e/kubernetes/lke-create.spec.ts) to confirm that the correct information is shown
- Add assertions for created LKE cluster in Cypress LKE tests
```
```
=> test: [M3-6620] - Add assertions for created LKE cluster in Cypress LKE tests

packages/manager/.changeset/pr-10612-tests-1719343415784.md, packages/manager/cypress/e2e/core/vpc/vpc-details-page.spec.ts
Combine 3 tests into 1 to create a subnet, edit it and confirm the details page updates to reflect the change, and then delete the subnet and once again confirm that the page updates to reflect the removed subnet.
- modified cypress/e2e/core/vpc/vpc-details-page.spec.ts
```
yarn cy:run -s "cypress/e2e/core/vpc/vpc-details-page.spec.ts”
```
=> test: [M3-7318] - Combine vpc details page subset create, edit, and delete tests

packages/manager/.changeset/pr-10637-upcoming-features-1719936723714.md, packages/manager/src/components/Snackbar/Snackbar.tsx, packages/manager/src/foundations/themes/dark.ts, packages/manager/src/foundations/themes/index.ts, packages/manager/src/foundations/themes/light.ts
Toast notifications are not properly styled for Cloud Manager's dark theme, resulting in white text on an almost white background.
- Since we're using 3rd party `Notistack`, I created a new style in our theme. Note: This will get cleaned up with the refactoring post launch.
- Now using `NotificationToast` tokens
- CDS does not have a default, so info colors are used for that
7/8
| ![Screenshot 2024-06-27 at 1 31 26 PM](https://github.com/linode/manager/assets/125309814/176fdbcc-08f6-44f4-a448-b5c176e85278) | <video src="https://github.com/linode/manager/assets/125309814/adf2d641-b356-405f-825a-2ca95c06c0dc" /> |
| Light Spec | Dark Spec  |
|<img width="448" …
=> refactor: [M3-8299] - Fix Notification Toast in Dark Mode

packages/manager/.changeset/pr-10628-upcoming-features-1719846490755.md, packages/manager/src/components/VLANSelect.tsx, packages/manager/src/hooks/useDebouncedValue.test.ts, packages/manager/src/hooks/useDebouncedValue.ts
- Adds debouncing the `VLANSelect` created for and used on Linode Create v2 ⏲️ 
- Adds a new `useDebouncedValue` hook to make this easy
- Let me know if you know of a better way 💡  
| <video src="https://github.com/linode/manager/assets/115251059/9bc3cab4-9c88-4980-8a66-d3dcc36b75a5" /> | <video src="https://github.com/linode/manager/assets/115251059/9b7c1a6e-fb92-41b7-b4fe-34e637c0e6b5" /> |
- Turn on `Linode Create v2`
- Verify that the API search performed by the `VLANSelect` is debounced and works as expected
=> upcoming: [M3-8066] - Debounce the Linode Create v2 `VLANSelect`

packages/manager/.changeset/pr-10618-fixed-1719521792524.md, packages/manager/src/features/Linodes/LinodesDetail/LinodeResize/LinodeResize.tsx
Improve the UX for the Linode Resize dialog.
- Only display Linode Resize form if linode data has been loaded (if it is still loading, render a `<CircleProgress />`)
- Prevent dialog title from being `Resize Linode undefined` by rendering an empty string when `linode.label` is undefined as the linode data loads
- Implement `scrollErrorIntoViewV2()` to ensure errors are scrolled into view
7/8/24
| <video src="https://github.com/linode/manager/assets/114682940/2ac2565b-3e92-432f-968c-29ee653a01b4" /> | <video src="https://github.com/linode/manager/assets/114682940/95140031-c936-49cb-a712-5a1eaa82c97d" /> |
<details>
<summary>Error scrolls into view</summary>
https://github.com/linode/manager/assets/114682940/9ecc52bf-8773-49a3-ab04-a757d3a7bc87 …
=> fix: [M3-7590, M3-7886] – Improve UX for Linode Resize dialog when linode data is being loaded or there is a form error

packages/manager/.changeset/pr-10633-tests-1719934397905.md, packages/manager/cypress/e2e/core/linodes/clone-linode.spec.ts, packages/manager/cypress/e2e/core/linodes/create-linode.spec.ts, packages/manager/cypress/e2e/core/linodes/legacy-create-linode.spec.ts, packages/manager/cypress/e2e/core/oneClickApps/one-click-apps.spec.ts, packages/manager/cypress/e2e/core/stackscripts/create-stackscripts.spec.ts, packages/manager/cypress/e2e/core/stackscripts/smoke-community-stackscrips.spec.ts, packages/manager/cypress/support/intercepts/linodes.ts, packages/manager/cypress/support/util/linodes.ts
This modifies our Cypress tests so that any Linodes created during the course of a test are created with no access to the internet. It does this by modifying the `interceptCreateLinode` util to mutate the outgoing request.
Note that this applies only to Linodes that are created via Cloud Manager during the tests -- Linodes created directly by Cypress via our JS SDK already have extra measures taken to secure them (see #10538).
- Mutate outgoing Linode create requests to place Linodes behind VLAN and, more importantly, without access to the internet
- Increase clone test timeout
1. Confirm that tests continue to pass (we can do this via CI)
2. Confirm that created Linodes are not connected to the internet
- There are a couple ways to do this, but this is the easiest:
1. Run a Linode create …
=> test: [M3-8122] - Disable access to internet for Linodes created during Cypress tests

packages/manager/.changeset/pr-10642-removed-1720016794302.md, packages/manager/src/features/Images/ImagesCreate/ImageUpload.tsx
Removes inaccurate helper text on the Image Upload page 🗑️ based on Image Service product and UX feedback
| ![Screenshot 2024-07-03 at 10 24 31 AM](https://github.com/linode/manager/assets/115251059/f0b056fb-f8d8-436f-87f1-13f721bac1ef) | ![Screenshot 2024-07-03 at 10 24 09 AM](https://github.com/linode/manager/assets/115251059/40f69872-a91b-4ca6-9c15-8188f56c4e51) |
- Go to `http://localhost:3000/images/create/upload` and verify the helper text above the `Region` field is gone
=> change: [M3-8323] - Remove Region Helper Text

packages/manager/.changeset/pr-10640-added-1720026539138.md, packages/manager/src/featureFlags.ts, packages/manager/src/features/GlobalNotifications/GlobalNotifications.tsx, packages/manager/src/features/GlobalNotifications/TokensUpdateBanner.tsx
This PR adds a new dismissible banner for the upcoming design/token updates.
The banner needs to be a little dynamic, featuring the two following variations:
```
{
"enabled": true,
"key": "design-tokens-7-9-2024",
"link": "https://www.linode.com/docs/guides/an-overview-of-the-cloud-manager"
}
```
```
{
"enabled": false,
"key": "design-tokens-7-9-2024",
"link": "https://www.linode.com/docs/guides/an-overview-of-the-cloud-manager"
}
```
The key is meant to give us the ability to re-introduce the banner for future updates (since it is generic) when people have dismissed it already. 
- Create new feature flag
- Implement banner
**7/8 2024**
The flag is currently only enabled in `development`
- Verify `Cloud Manager Design Updates Banner` configuration in LD
- Pull code locally and confirm …
=> change: [M3-8322] - Add Design Update Global Notification Banner

packages/manager/.changeset/pr-10636-upcoming-features-1719935270528.md, packages/manager/src/components/ImageSelect/ImageOption.tsx, packages/manager/src/components/ImageSelect/ImageSelect.test.tsx, packages/manager/src/components/ImageSelect/ImageSelect.tsx, packages/manager/src/components/ImageSelectv2/ImageOptionv2.test.tsx, packages/manager/src/components/ImageSelectv2/ImageOptionv2.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.test.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/Tabs/Images.tsx
- Adds a notice saying `Indicates compatibility with distributed compute regions.` beside the Image Select on the Linode Create flow for customers that have Images with the `distributed-images` capability 🌐 
- Add to both Linode Create v1 and v2 ➕ 
-  Added unit test for both flows 🧪 
> [!important]
> Please test using Linode Create v1 and v2
- Verify you see `Indicates compatibility with distributed compute regions.` if the customer has >= 1 image with the `distributed-images` capability 🌐 
- Verify this only shows on the `Images` tab of the Linode Create flow 👀 
- Verify styles, alignment, and spacing look good 🎨
=> upcoming: [M3-8320] - Add Image distributed compatibility notice to Linode Create

docs/development-guide/13-coding-standards.md
A tiny PR to update the Coding Standard sections of our Cloud Manager Docs to include links to two of our most important VSCode extensions. I found myself linking the extension, rather than our docs, in a PR review comment where linting needed to happen. We might as well include these links in our docs.
- Adds links to the listed VS Code extensions
- Adds emphasis
| ![Screenshot 2024-07-03 at 12 14 58 PM](https://github.com/linode/manager/assets/114685994/a51b7a9c-c408-4675-a1ab-644168f1514d) | ![Screenshot 2024-07-03 at 12 05 46 PM](https://github.com/linode/manager/assets/114685994/0fcc6ea8-ccb3-4a91-b464-09009a28b8cf) |
- Check out this PR, run `yarn docs` locally, go to the Coding Standards page, and confirm the above …
=> change: Link two VSCode extensions mentioned in our Coding Standards docs

packages/manager/.changeset/pr-10627-added-1719905623432.md, packages/manager/src/features/Volumes/VolumesLanding.tsx
Here, we are restricting users from creating new Volume when they do not have access or have read only access.
- Disabled Create Volume Button on the Landing Page
July 8th, 2024
| ![Screenshot 2024-07-01 at 8 30 45 PM](https://github.com/linode/manager/assets/172569094/94f048b4-a188-4c97-a15c-e090ed91deff) | ![Screenshot 2024-07-01 at 8 36 41 PM](https://github.com/linode/manager/assets/172569094/4b1a388a-bb68-4fb0-a845-891261f5ca4a) |
- A restricted user …
=> feat: [M3-7684] - Disable Create Volume button with tooltiptext on Landing Page for restricted users

packages/manager/.changeset/pr-10630-added-1719904456730.md, packages/manager/.changeset/pr-10630-changed-1719904456730.md, packages/manager/src/features/Volumes/VolumesLandingEmptyState.test.tsx, packages/manager/src/features/Volumes/VolumesLandingEmptyState.tsx
Here, we are restricting users from creating new Volume from the Empty State Landing Page when they do not have access or have read-only access.
- Disabled Create Volume Button on the Empty State Landing Page
July 8th, 2024
| ![Screenshot 2024-07-01 at 9 23 51 PM](https://github.com/linode/manager/assets/172569094/cd281925-ba66-4021-9f29-98846ed0d9a5) | ![Screenshot 2024-07-01 at 9 30 01 PM](https://github.com/linode/manager/assets/172569094/cce77dde-368e-45b1-93f1-2f3b379c9648) |
- An unrestricted admin …
=> feat: [M3-7684] - Disable Create Volume button with tooltiptext on 'Empty State Landing Page' for Restricted Users 

packages/manager/.changeset/pr-10632-changed-1719914806428.md, packages/manager/src/features/Volumes/VolumeCreate.tsx
Keeping the Create Volumes Page error notification position consistent with other tabs like NodeBalancers.
- The position of error notification has been moved from inside the box to outside, which is now consistent with other tabs like NodeBalancers.
- Used `getRestrictedResourceText` utility to show a Notice / error notification message.
July 8th, 2024
| ![Screenshot 2024-07-01 at 11 21 53 PM](https://github.com/linode/manager/assets/172569094/3d806e80-7c76-43b7-9fec-5cf3e7de1299) | ![Screenshot 2024-07-01 at 11 48 30 PM](https://github.com/linode/manager/assets/172569094/ddbb868e-77b8-4fe9-94b7-12ebeaec9dad) |
- Log in with a restricted user account (read-only access) and go to the …
=> change: [M3-7684] - Keep Create Volumes Page Error Notification Position Consistent

packages/manager/.changeset/pr-10641-added-1720011097638.md, packages/manager/src/features/Account/utils.ts, packages/manager/src/features/Volumes/VolumesActionMenu.tsx
Here, we are disabling Volume Action Menu buttons when they do not have access or have read-only access.
- Disabled Volume Action Menu buttons (edit, resize, clone, detach, delete)
- Disabled delete action menu will show a restricted user tooltip notice due to `read-only` access.  Otherwise, it will show a restricted action notice if a Linode is attached.
July 8th, 2024
Before_readonly_user_unattached_linode
https://github.com/linode/manager/assets/172569094/22258cdc-1952-4e89-8194-22476ba888de
https://github.com/linode/manager/assets/172569094/96e8d42f-4550-42f9-8eba-653303ee2a80 …
=> feat: [M3-7684] - Disable Volume Action Menu Buttons for Restricted Users

packages/manager/.changeset/pr-10646-fixed-1720111189359.md, packages/manager/src/features/Volumes/AttachVolumeDrawer.tsx, packages/manager/src/features/Volumes/ResizeVolumeDrawer.tsx
To prevent unauthorized access to specific flows and provide clearer guidance, we aim to restrict entry to users without the required permissions. But for these restricted users, error notices in Volume Drawers are currently not tailored to the action: The text 'edit' is incorrectly displayed on Resize Volume drawer and Attach Volume drawer; it should show 'resize' and 'attach' respectively. 
- Fixed the incorrect error notices by replacing 'edit' with 'resize' and 'edit' with 'attach' on the respective Volume drawers.
July 8th, 2024
| ![before-resize-volume-drawer](https://github.com/linode/manager/assets/172569094/2033e2bc-1943-46bf-8e01-cead0566df78) | ![after-resize-volume-drawer](https://github.com/linode/manager/ass …
=> fix: [M3-7684] - Incorrect Error Notice in Volume Drawers for Restricted Users

packages/manager/src/foundations/themes/dark.ts, packages/manager/src/foundations/themes/light.ts
Fix an issue with the clickable Chip not being readable in Dark Theme.
Seems like more could be done to improve those in next iterations, but meanwhile we're only fixing readability here
- fix to light and dark theme files to improve dark theme clickable chip
ℹ️ No need for a changeset, this bug has not reached production yet
7/8/2024
| ![image](https://github.com/linode/manager/assets/130582365/679c1c5f-13de-4591-a1c7-40672284ec45) | ![Screenshot 2024-07-08 at 12 00 28](https://github.com/linode/manager/assets/130582365/b0d781f6-414c-42ff-876e-de900c968539) |
- Should verify with an outdated k8 cluster version (see screenshots)
- Should confirm no additional regressions with other Chips in light or dark theme
=> Release v1.123.0 fixes

packages/manager/.changeset/pr-10649-upcoming-features-1720453076417.md, packages/manager/src/features/Linodes/LinodeCreatev2/Actions.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/index.tsx, packages/manager/src/features/Linodes/LinodeCreatev2/utilities.ts, packages/manager/src/queries/stackscripts.ts, packages/manager/src/utilities/analytics/customEventAnalytics.ts
- This PR adds custom analytics events to Linode Create v2
- This PR's goal is to copy over **only events UX wanted to retain** from Linode Create v1
- View [this doc](https://docs.google.com/spreadsheets/d/1gSYxVvRUm8bES_iiej9_Q_s7rQ-ooHLEsbjZwrluUoU/edit?gid=0#gid=0) to see what events are kept / not kept 📄 
- The events that are retained _should_ work the same way as they did on Linode Create v1
- Enable `Linode Create v2` feature flag 🇺🇸 
- Run `_satellite.setDebug(true)` in your browser's console ⌨️ 
- Refresh the page 🔄
- Create various Linodes on different tabs of the Linode Create flow
- Verify Analytics events fire for each creation
- **Verify those analytics events match what Linode Create v1 would capture**
=> upcoming: [M3-8328] - Add Analytics Events to Linode Create v2

docs/CONTRIBUTING.md, packages/manager/.changeset/pr-10657-fixed-1720475119486.md
Fix the github CLI link in our contributing guide leading to a 404 error
- Go to the old link https://cli.github.com/manual/installation and notice a 404 error
- Go to the new link https://github.com/cli/cli#installation, there should not be a 404 error
=> fix: Github CLI install link in Contributing guide

packages/manager/.changeset/pr-10654-tech-stories-1720468649871.md, packages/manager/src/hooks/useToastNotifications.tsx
We need to enhance the API of this hook to increase its flexibility in handling event notifications. For example, we have a new event, `tax_id_invalid`. When this event is successful (indicating the tax ID is invalid), we want to display the error variant and ensure the notification persists. Currently, there's no way to easily inverse the toast variant depending on the event.
- Renamed `persistFailureMessage` to `persist`
- Added `tax_id_invalid` event which is feature flagged
- Added an `invertVariant` property to handle scenarios where a successful negative event should be represented as an `error` variant.
- Added new interface:
```
interface ToastMessage {
link?: JSX.Element;
message: ((event: Event) => string | undefined) | string;
persist?: boolean;
}
```
7/22
(How to verify …
=> feat:[M3-8330] - Improve API flexibility for useToastNotification

packages/manager/.changeset/pr-10661-removed-1720547888843.md, packages/manager/src/components/GravatarByEmail.tsx, packages/manager/src/features/Profile/DisplaySettings/DisplaySettings.tsx, packages/manager/src/features/TopMenu/UserMenu/UserMenu.tsx, packages/manager/src/utilities/analytics/customEventAnalytics.ts
In #10389, we tagged Gravatar components to determine whether we can justify sunsetting support for it. Now that we have collected data for a period of time and this Product decision has been made, we can save analytics calls and costs by untagging Gravatar-related analytics.
- Removes analytics events `sendHasGravatarEvent` and `sendManageGravatarEvent`
7/22
- Ensure your `REACT_APP_ADOBE_ANALYTICS_URL` environment variable is set in `.env`
- Run `window._satellite.setDebug(true)` in your browser console
- Refresh your page
| When the page loads, verify you **do not** see an analytics event like this if you have a Gravatar| ![Screenshot 2024-04-18 at 3 57 …
=> change: [M3-8329] - Clean up Gravatar analytics events

packages/manager/.changeset/pr-10660-fixed-1720504089793.md, packages/manager/src/features/Kubernetes/KubernetesClusterDetail/NodePoolsDisplay/NodePool.tsx
The "Delete Pool" button on the LKE details page is misaligned and positioned a few pixels higher than the other nearby buttons.
- Removed unnecessary bottom margin for the "Delete Pool" button
22nd July 2024
| ![before](https://github.com/linode/manager/assets/172569094/3dac3458-cb30-4c4f-89fe-3d2bea19b619) | ![after](https://github.com/linode/manager/assets/172569094/fa90b9a6-849f-423d-abbf-144c483aa605) |
- Create an LKE cluster
- Navigate to the LKE cluster's details page
- Observe that "Delete Pools" button is misaligned with nearby buttons
- Ensure that it is visually aligned with the other nearby buttons.
- Verify that the "Delete Pool" button is no longer positioned higher than the other buttons.
- Confirm that …
=> fix: [M3-6518] - LKE details page "Delete Pool" button misaligned

packages/manager/.changeset/pr-10645-tech-stories-1720037366869.md, packages/manager/src/components/OrderBy.tsx, packages/manager/src/components/SelectFirewallPanel/SelectFirewallPanel.tsx, packages/manager/src/components/SelectRegionPanel/SelectRegionPanel.tsx, packages/manager/src/features/Firewalls/FirewallLanding/CreateFirewallDrawer.tsx, packages/manager/src/features/Images/ImagesCreate/CreateImageTab.tsx, packages/manager/src/features/Linodes/CloneLanding/CloneLanding.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreate.tsx, packages/manager/src/features/Linodes/LinodesCreate/LinodeCreateContainer.tsx, packages/manager/src/features/Linodes/LinodesCreate/VPCCreateDrawer.tsx, packages/manager/src/features/Linodes/LinodesCreate/VPCPanel.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetail.tsx, packages/manager/src/features/Linodes/LinodesDetail/LinodesDetailHeader/LinodeDetailHeader.tsx, packages/manager/src/features/Linodes/LinodesLanding/DisplayLinodes.tsx, packages/manager/src/features/Linodes/types.ts, packages/manager/src/features/Support/SupportTickets/SupportTicketsLanding.tsx, packages/manager/src/features/VPCs/VPCCreate/FormComponents/SubnetContent.tsx, packages/manager/src/features/VPCs/VPCCreate/FormComponents/VPCTopSectionContent.tsx, packages/manager/src/features/components/PlansPanel/PlansPanel.tsx, packages/manager/src/hooks/useOrder.ts, packages/manager/src/layouts/LoginAsCustomerCallback.tsx, packages/manager/src/layouts/OAuth.test.tsx, packages/manager/src/layouts/OAuth.tsx, packages/manager/src/utilities/queryParams.ts, packages/manager/tsconfig.json
Follow up to @jaalah's comment in https://github.com/linode/manager/pull/10479 about improving the type safety of getQueryParamsFromQueryString and removing the casting. The big diff is mostly from ESLint shuffling imports and code around
- Type safe `getQueryParamsFromQueryString`
- Added `dom.iterable` to tsconfig.json
- There should be no UI changes or regressions compared to prod
=> refactor: [M3-8285] - Improve getQueryParamsFromQueryString type safety

packages/manager/.changeset/pr-10663-fixed-1720582006219.md, packages/manager/src/hooks/useInitialRequests.ts
- I forgot to do this in https://github.com/linode/manager/pull/10543 😣
- Updates `useInitialRequests` to use the preferences query key factory 🏭  so that it stores prefetched preferences in the correct query key 🔑 
- This _should_ fix what @johnwcallahan observed because preferences will properly loaded before the splash screen is hidden 👁️ 🚫 
- > when I refresh https://cloud.linode.com/linodes, I briefly see the CDS banner before it disappears (I have previously dismissed it)
| ![Screenshot 2024-07-09 at 11 21 00 PM](https://github.com/linode/manager/assets/115251059/c4764c4e-1489-4c2f-9f67-5b31a321aed1) | ![Screenshot 2024-07-09 at 11 20 26 PM](https://github.com/linode/manager/assets/115251059/ee4bcaff-7f8b-4f19-916e-05a7956c2e67) |
- Verify …
=> fix: [M3-8337] - User Preferences not being cached properly when the app loads 

packages/manager/.changeset/pr-10664-fixed-1720621088378.md, packages/manager/src/components/Snackbar/Snackbar.tsx, packages/manager/src/components/Snackbar/ToastNotifications.stories.tsx, packages/manager/src/hooks/useToastNotifications.tsx
- Removes some unnecessary styles for our Toast implementation 🗑️ 
- Fixes flaw with `useToastNotifications` that caused toasts to show up with no message 🔧 
- Improves how content wraps inside of toast notifications 🎨 
- Adds a `maxWidth` to Toast Notifications on larger screens so that they don't take up the full width of the screen
- See the `WithLongMessage` Storybook story 📖 
| <video src="https://github.com/linode/manager/assets/115251059/4970469b-4215-4951-9843-aa6404c956ac" /> | <video src="https://github.com/linode/manager/assets/115251059/79742e20-8b9c-44ef-a51a-e2e9f8bae9cb" /> |
| <video src="https://github.com/linode/manager/assets/115251059/0aeef353-615a-4379-acc8-e9d66a5f71e2" /> | <video …
=> fix: [M3-8342] - Toast Notifications for Images 

packages/manager/.changeset/pr-10674-upcoming-features-1720716452894.md, packages/manager/cypress/e2e/core/images/manage-image-regions.spec.ts, packages/manager/src/components/Autocomplete/Autocomplete.tsx, packages/manager/src/components/RegionSelect/RegionMultiSelect.tsx, packages/manager/src/components/RegionSelect/RegionSelect.types.ts, packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.test.tsx, packages/manager/src/features/Images/ImagesLanding/ImageRegions/ImageRegionRow.tsx, packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.test.tsx, packages/manager/src/features/Images/ImagesLanding/ImageRegions/ManageImageRegionsForm.tsx, packages/manager/src/features/ObjectStorage/AccessKeyLanding/AccessKeyRegions/AccessKeyRegions.tsx
Updates the "Manage Image Regions" Drawer based on UX feedback 🖌️ 
- The Manage Regions Multi-Select should not show any tags in the TextField 🚫🏷️
- Regions should not be filtered from the Multi-Select 🌐 
- Make last region immutable when there is only one region left in the list ✖️ 
- Close the drawer when "Save" is pressed (and the API request is successful 📕 
| <video src="https://github.com/linode/manager/assets/115251059/5e5ec345-8a1e-40a4-9c42-de0892728a84" /> | <video src="https://github.com/linode/manager/assets/115251059/d3180a75-3bc8-4c15-9115-f594f227f498" /> |
- Turn on Image Service Gen 2 feature flag
- Test the "Manage Regions" feature on the  Image called `multi-regions-test-image` 🧪 
- Verify all of the changes …
=> upcoming: [M3-8340] - Update Manage Image Regions Drawer based on UX feedback 

packages/manager/.changeset/pr-10673-tech-stories-1720710990405.md, packages/manager/src/components/Autocomplete/Autocomplete.tsx, packages/manager/src/features/Kubernetes/CreateCluster/CreateCluster.tsx
We want to get rid of our dependency on react-select for accessibility reasons and to consolidate our usage of third-party libraries.
- Replaced `Select` with Autocomplete in `CreateCluster` component. 
- The `Item` type previously imported from `EnhancedSelect/Select` has been added to `Autocomplete/Autocomplete`
- It simplifies imports and improves code maintainability.
- Added `disableClearable` prop condition to `Autocomplete` to prevent uncontrolled behavior with an initial empty value.
22nd July, 2024
- Navigate to http://localhost:3000/kubernetes/create 
- Verify 'Kubernetes Version' dropdown functionality remains unchanged when using `Autocomplete`. 
- Verify that the `disableClearable` prop condition is correctly applied to `Autocomplete` to prevent …
=> refactor: [M3-6901, M3-6914] - Replace Select with Autocomplete in: kubernetes

packages/manager/.changeset/pr-10671-added-1720708134201.md, packages/manager/src/features/Images/ImagesLanding/ImagesLanding.test.tsx, packages/manager/src/features/Images/ImagesLanding/ImagesLanding.tsx
Here, we are restricting users from creating new Image when they do not have access or have read only access.
- Disabled Create Image Button on the Landing Page
|![07_53_12](https://github.com/linode/manager/assets/174600419/3b2d7260-3ccf-4418-9323-67e9d9c7c6ac)|![07_52_51](https://github.com/linode/manager/assets/174600419/2a792087-481d-4d60-9439-2e3c1a483894)|
- Start with `Read Only` for everything
- …
=> feat: [M3-7683] - Disable Create Image button with tooltiptext on Landing Page for restricted users

packages/manager/.changeset/pr-10644-tests-1720540166205.md, packages/manager/cypress/e2e/core/longview/longview.spec.ts, packages/manager/cypress/support/intercepts/longview.ts
Add Cypress integration tests using mock API data to confirm the UI flow when a user renames or deletes a Longview client in Cloud Manager.
- Add new tests in e2e longview.spec.ts
- Add new intercepts functions in longview.ts
```
yarn cy:run -s "cypress/e2e/core/longview/longview.spec.ts”
```
=> test: [M3-8155,M3-8154] - Add tests for longview client rename and deletion

packages/manager/.changeset/pr-10680-fixed-1721142009108.md, packages/manager/src/hooks/useToastNotifications.tsx
- Fixes a bug in `useToastNotifications.tsx` that caused a support ticket link to not show
- The "fix" is basically just to use `toLowerCase` to ignore casing. The event from the API said `contact support`, but Cloud Manager was checking for `contact Support`
- July 22, 2024
| ![Screenshot 2024-07-15 at 4 52 13 PM](https://github.com/user-attachments/assets/3662a555-af93-4e23-a7f1-ac3a56c52a36) | ![Screenshot 2024-07-15 at 4 52 21 PM](https://github.com/user-attachments/assets/17e7a683-0c52-4f4b-9ee2-fb4e1d33b5e2) |
- `gzip` something that is not an Image
- Try uploading it in **dev**
- Verify the toast you see has a support link and does not appear broken
=> fix: Image Upload Toast Support Link

packages/manager/.changeset/pr-10679-tech-stories-1721072052210.md, packages/manager/src/queries/managed/managed.ts
- Updates Managed Queries to use a query key factory 🏭 
- Fixes breaking changes in preparation for v5 (see [here](https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5))  🔨 
- Doesn't change any application logic, just switches over to the factory 
- Use the MSW, use an account with managed enabled, or enable managed on your account
- Verify managed create, update, and delete actions work as expected 👀 
- Verify all automated testing for managed passes ✅
=> refactor: [M3-7432] - Update Managed Queries to use Query Key Factory
